Audacity: AudacityApp.cpp File Reference
AudacityApp.cpp File Reference
#include "Audacity.h"
#include <wx/defs.h>
#include <wx/app.h>
#include <wx/docview.h>
#include <wx/event.h>
#include <wx/ipc.h>
#include <wx/log.h>
#include <wx/window.h>
#include <wx/intl.h>
#include <wx/menu.h>
#include <wx/msgdlg.h>
#include <wx/snglinst.h>
#include <wx/sysopt.h>
#include <wx/fontmap.h>
#include <wx/fs_zip.h>
#include <wx/image.h>
#include <wx/dir.h>
#include <wx/file.h>
#include <wx/filename.h>
#include "AudacityApp.h"
#include "AboutDialog.h"
#include "AColor.h"
#include "AudioIO.h"
#include "Benchmark.h"
#include "DirManager.h"
#include "commands/CommandHandler.h"
#include "commands/AppCommandEvent.h"
#include "effects/LoadEffects.h"
#include "effects/Contrast.h"
#include "effects/VST/VSTEffect.h"
#include "FFmpeg.h"
#include "GStreamerLoader.h"
#include "Internat.h"
#include "LangChoice.h"
#include "Languages.h"
#include "Prefs.h"
#include "Project.h"
#include "Screenshot.h"
#include "Sequence.h"
#include "WaveTrack.h"
#include "prefs/PrefsDialog.h"
#include "Theme.h"
#include "PlatformCompatibility.h"
#include "FileNames.h"
#include "AutoRecovery.h"
#include "SplashDialog.h"
#include "FFT.h"
#include "BlockFile.h"
#include "ondemand/ODManager.h"
#include "commands/Keyboard.h"
#include "LoadModules.h"
#include "import/Import.h"
Typedefs
typedef int(AudacityApp::* SPECIALKEYEVENT)(wxKeyEvent &)
Functions
DEFINE_EVENT_TYPE (EVT_OPEN_AUDIO_FILE)
DEFINE_EVENT_TYPE (EVT_CAPTURE_KEYBOARD)
DEFINE_EVENT_TYPE (EVT_RELEASE_KEYBOARD)
DEFINE_EVENT_TYPE (EVT_CAPTURE_KEY)
void QuitAudacity (bool bForce)
void QuitAudacity ()
void SaveWindowSize ()
Variables
static wxFrame * gParentFrame = NULL
bool gInited = false
bool gIsQuitting = false
Typedef Documentation
typedef int(AudacityApp::* SPECIALKEYEVENT)(wxKeyEvent &)
Function Documentation
DEFINE_EVENT_TYPE (EVT_CAPTURE_KEY)
DEFINE_EVENT_TYPE (EVT_RELEASE_KEYBOARD)
DEFINE_EVENT_TYPE (EVT_CAPTURE_KEYBOARD)
DEFINE_EVENT_TYPE (EVT_OPEN_AUDIO_FILE)
Custom events
void QuitAudacity ()
References QuitAudacity().
void QuitAudacity (bool bForce)
References AppQuiting, CloseContrastDialog(), CloseScreenshotTools(), AudacityProject::DeleteAllProjectsDeleteLock(), AudacityProject::DeleteClipboard(), ModuleManager::Dispatch(), gAudacityProjects, AudacityApp::mLogger, ODManager::Quit(), SaveWindowSize(), and wxGetApp().
Referenced by AudacityProject::OnCloseWindow(), AudacityProject::OnExit(), AudacityApp::OnInit(), AudacityApp::OnMenuExit(), and QuitAudacity().
void SaveWindowSize ()
References gAudacityProjects, GetDefaultWindowRect(), AudacityProject::GetNormalizedWindowState(), gPrefs, AudacityApp::SetWindowRectAlreadySaved(), and wxGetApp().
Referenced by AudacityProject::OnCloseWindow(), and QuitAudacity().
Variable Documentation
bool gInited = false
Referenced by AudacityApp::OnInit().
bool gIsQuitting = false
Referenced by AudacityProject::OnCloseWindow(), AudacityApp::OnEndSession(), and AudacityApp::OnExit().
wxFrame* gParentFrame = NULL [static]
Referenced by AudacityApp::OnInit().