Audacity: CompareAudioCommand.cpp File Reference
CompareAudioCommand.cpp File Reference
Contains definitions for CompareAudioCommand class.
#include "CompareAudioCommand.h"
#include "../Project.h"
#include "Command.h"
Functions
int min (int a, int b)
Detailed Description
Contains definitions for CompareAudioCommand class.
Function Documentation
int min (int a, int b) [inline]
Referenced by RecordingPrefs::Apply(), CompareAudioCommand::Apply(), SimpleBlockFile::BuildFromXML(), PCMAliasBlockFile::BuildFromXML(), ODPCMAliasBlockFile::CalcSummary(), ODDecodeBlockFile::CalcSummary(), BlockFile::CalcSummary(), ComputeMinMax256(), AdornedRulerPanel::DoDrawMarks(), TimeTrack::Draw(), TrackArtist::DrawClipWaveform(), BlockFile::FixSummary(), Sequence::GetMinMax(), BlockFile::GetMinMax(), EffectNoiseRemoval::GetProfile(), TrackList::GetStartTime(), GuessFloatFormats(), TrackPanel::HandleVZoomButtonUp(), EffectAmplify::Init(), AudacityProject::NearestZeroCrossing(), TimerRecordDialog::OnDatePicker_End(), TimerRecordDialog::OnDatePicker_Start(), TimerRecordDialog::OnTimeText_Duration(), ToolDock::PositionBar(), EffectNoiseRemoval::RemoveNoise(), TimerRecordDialog::TransferDataFromWindow(), MixerTrackCluster::UpdateMeter(), and TrackArtist::UpdateVRuler().