Audacity: ExportPCM.cpp File Reference
ExportPCM.cpp File Reference
#include <wx/defs.h>
#include <wx/choice.h>
#include <wx/dynlib.h>
#include <wx/filename.h>
#include <wx/intl.h>
#include <wx/timer.h>
#include <wx/msgdlg.h>
#include <wx/progdlg.h>
#include <wx/string.h>
#include <wx/textctrl.h>
#include <wx/window.h>
#include "sndfile.h"
#include "../Audacity.h"
#include "../FileFormats.h"
#include "../Internat.h"
#include "../LabelTrack.h"
#include "../Mix.h"
#include "../Prefs.h"
#include "../Project.h"
#include "../Tags.h"
#include "../Track.h"
#include "../WaveTrack.h"
#include "../ondemand/ODManager.h"
#include "Export.h"
#include <id3tag.h>
Classes
class ExportPCMOptions
class ExportPCM
Defines
#define ID_FORMAT_CHOICE 7101
#define ID_HEADER_CHOICE 7102
#define ID_ENCODING_CHOICE 7103
Functions
struct id3_frame * id3_frame_new (char const *)
id3_length_t id3_latin1_length (id3_latin1_t const *)
void id3_latin1_decode (id3_latin1_t const *, id3_ucs4_t *)
static int ReadExportFormatPref ()
static void WriteExportFormatPref (int format)
ExportPlugin * New_ExportPCM ()
Define Documentation
#define ID_ENCODING_CHOICE 7103
Referenced by ExportPCMOptions::PopulateOrExchange().
#define ID_FORMAT_CHOICE 7101
#define ID_HEADER_CHOICE 7102
Referenced by ExportPCMOptions::PopulateOrExchange().
Function Documentation
struct id3_frame* id3_frame_new (char const *) [read]
void id3_latin1_decode (id3_latin1_t const * , id3_ucs4_t *)
id3_length_t id3_latin1_length (id3_latin1_t const *)
ExportPlugin* New_ExportPCM ()
Referenced by Exporter::Exporter().
static int ReadExportFormatPref () [static]
References gPrefs.
Referenced by ExportPCM::Export(), ExportPCMOptions::ExportPCMOptions(), and ExportPCM::GetExtension().
static void WriteExportFormatPref (int format) [static]
References gPrefs.
Referenced by ExportPCMOptions::OnOK().