Audacity: ExpandingToolBar.cpp File Reference
ExpandingToolBar.cpp File Reference
#include "../Theme.h"
#include <wx/wxprec.h>
#include <wx/window.h>
#include <wx/dcmemory.h>
#include <wx/log.h>
#include <wx/dragimag.h>
#include <wx/arrimpl.cpp>
#include <wx/dialog.h>
#include "ExpandingToolBar.h"
#include "AButton.h"
#include "../AllThemeResources.h"
#include "../Experimental.h"
Classes
class ToolBarArrangement
Small class that holds some layout information for an ExpandingToolBar.
class ExpandingToolBarEvtHandler
A custom event handler for ExpandingToolBar.
Enumerations
enum { kToggleButtonID = 5000, kTimerID }
Functions
WX_DEFINE_OBJARRAY (wxArrayRect)
Variables
const int kToggleButtonHeight = 8
const int kTimerInterval = 50
const wxRect kDummyRect = wxRect(-9999, -9999, 0, 0)
Enumeration Type Documentation
anonymous enum
Enumerator:
kToggleButtonID
kTimerID
Function Documentation
WX_DEFINE_OBJARRAY (wxArrayRect)
Variable Documentation
const wxRect kDummyRect = wxRect(-9999, -9999, 0, 0)
Referenced by ExpandingToolBar::FinishMoving(), ExpandingToolBar::StartMoving(), and ExpandingToolBar::UpdateMoving().
const int kTimerInterval = 50
const int kToggleButtonHeight = 8
Referenced by ExpandingToolBar::Layout().