Audacity: FFT.h File Reference
FFT.h File Reference
#include "Experimental.h"
Functions
void PowerSpectrum (int NumSamples, float *In, float *Out)
void RealFFT (int NumSamples, float *RealIn, float *RealOut, float *ImagOut)
void InverseRealFFT (int NumSamples, float *RealIn, float *ImagIn, float *RealOut)
void FFT (int NumSamples, bool InverseTransform, float *RealIn, float *ImagIn, float *RealOut, float *ImagOut)
void WindowFunc (int whichFunction, int NumSamples, float *data)
const wxChar * WindowFuncName (int whichFunction)
int NumWindowFuncs ()
void DeinitFFT ()
Function Documentation
void DeinitFFT ()
References CleanupFFT(), gFFTBitTable, and MaxFastBits.
Referenced by AudacityApp::OnExit().
void FFT (int NumSamples, bool InverseTransform, float * RealIn, float * ImagIn, float * RealOut, float * ImagOut)
References FastReverseBits(), gFFTBitTable, InitFFT(), IsPowerOfTwo(), M_PI, and NumberOfBitsNeeded().
Referenced by EqualizationDialog::CalcFilter(), ComputeSpectrum(), PowerSpectrum(), RealFFT(), FreqWindow::Recalc(), and EqualizationPanel::Recalc().
void InverseRealFFT (int NumSamples, float * RealIn, float * ImagIn, float * RealOut)
References GetFFT(), HFFT, InverseRealFFTf(), ReleaseFFT(), and ReorderToTime().
Referenced by EqualizationDialog::CalcFilter(), FreqWindow::Recalc(), and EqualizationPanel::Recalc().
int NumWindowFuncs ()
Referenced by FreqWindow::FreqWindow(), SpectrumPrefs::Populate(), and FreqWindow::Recalc().
void PowerSpectrum (int NumSamples, float * In, float * Out)
References FFT(), GetFFT(), HFFT, M_PI, RealFFTf(), and ReleaseFFT().
Referenced by ComputeSpectrum(), and FreqWindow::Recalc().
void RealFFT (int NumSamples, float * RealIn, float * RealOut, float * ImagOut)
References FFT(), GetFFT(), HFFT, M_PI, RealFFTf(), and ReleaseFFT().
Referenced by EqualizationDialog::CalcFilter(), ComputeSpectrum(), and FreqWindow::Recalc().
void WindowFunc (int whichFunction, int NumSamples, float * data)
References M_PI.
Referenced by ComputeSpectrum(), WaveClip::GetSpectrogram(), and FreqWindow::Recalc().
const wxChar* WindowFuncName (int whichFunction)
Referenced by FreqWindow::FreqWindow(), and SpectrumPrefs::Populate().