Audacity: Project.cpp File Reference
Project.cpp File Reference
Implements AudacityProject, DropTarget, and FileObject. Includes Menus.cpp.
#include "Audacity.h"
#include <stdio.h>
#include <iostream>
#include <wx/wxprec.h>
#include <wx/apptrait.h>
#include <wx/defs.h>
#include <wx/app.h>
#include <wx/dc.h>
#include <wx/dcmemory.h>
#include <wx/dnd.h>
#include <wx/docview.h>
#include <wx/event.h>
#include <wx/ffile.h>
#include <wx/filedlg.h>
#include <wx/filefn.h>
#include <wx/filename.h>
#include <wx/intl.h>
#include <wx/log.h>
#include <wx/menu.h>
#include <wx/msgdlg.h>
#include <wx/notebook.h>
#include <wx/progdlg.h>
#include <wx/scrolbar.h>
#include <wx/sizer.h>
#include <wx/statusbr.h>
#include <wx/string.h>
#include <wx/textfile.h>
#include <wx/timer.h>
#include <wx/generic/filedlgg.h>
#include <wx/display.h>
#include <wx/arrimpl.cpp>
#include "Project.h"
#include "AutoRecovery.h"
#include "AudacityApp.h"
#include "AColor.h"
#include "AudioIO.h"
#include "Dependencies.h"
#include "HistoryWindow.h"
#include "Lyrics.h"
#include "LyricsWindow.h"
#include "MixerBoard.h"
#include "Internat.h"
#include "import/Import.h"
#include "LabelTrack.h"
#include "Legacy.h"
#include "Mix.h"
#include "NoteTrack.h"
#include "Prefs.h"
#include "Tags.h"
#include "Track.h"
#include "TrackPanel.h"
#include "WaveTrack.h"
#include "DirManager.h"
#include "effects/Effect.h"
#include "prefs/PrefsDialog.h"
#include "widgets/ErrorDialog.h"
#include "widgets/Meter.h"
#include "widgets/Ruler.h"
#include "widgets/Warning.h"
#include "xml/XMLFileReader.h"
#include "PlatformCompatibility.h"
#include "Experimental.h"
#include "export/Export.h"
#include "FileNames.h"
#include "BlockFile.h"
#include "ondemand/ODManager.h"
#include "ondemand/ODTask.h"
#include "ondemand/ODComputeSummaryTask.h"
#include "LoadModules.h"
#include "Theme.h"
#include "AllThemeResources.h"
#include "FileDialog.h"
#include "toolbars/ToolManager.h"
#include "toolbars/ControlToolBar.h"
#include "toolbars/DeviceToolBar.h"
#include "toolbars/EditToolBar.h"
#include "toolbars/MeterToolBar.h"
#include "toolbars/MixerToolBar.h"
#include "toolbars/SelectionBar.h"
#include "toolbars/ToolsToolBar.h"
#include "toolbars/TranscriptionToolBar.h"
#include "commands/ScriptCommandRelay.h"
#include "commands/CommandDirectory.h"
#include "commands/CommandTargets.h"
#include "commands/Command.h"
#include "commands/CommandType.h"
#include "CaptureEvents.h"
#include "../images/AudacityLogoAlpha.xpm"
Classes
class VarSetter< T >
class ScrollBar
Enumerations
enum { FirstID = 1000, HSBarID, VSBarID, TrackPanelID }
Functions
static void SetActiveProject (AudacityProject *project)
AUDACITY_DLL_API AudacityProject * GetActiveProject ()
AudacityProject * CreateNewAudacityProject ()
void RedrawAllProjects ()
void RefreshCursorForAllProjects ()
AUDACITY_DLL_API void CloseAllProjects ()
void GetDefaultWindowRect (wxRect *defRect)
bool IsWindowAccessible (wxRect *requestedRect)
void GetNextWindowPlacement (wxRect *nextRect, bool *pMaximized, bool *pIconized)
wxString CreateUniqueName ()
Variables
const int sbarSpaceWidth = 15
const int sbarControlWidth = 15
const int sbarExtraLen = 0
const int sbarHjump = 30
static int gAudacityOffsetInc = 0
static int gAudacityPosInc = 0
static AudacityProject * gActiveProject
AProjectArray gAudacityProjects
Detailed Description
Implements AudacityProject, DropTarget, and FileObject. Includes Menus.cpp.
Enumeration Type Documentation
anonymous enum
Enumerator:
FirstID
HSBarID
VSBarID
TrackPanelID
Function Documentation
AUDACITY_DLL_API void CloseAllProjects ()
References AUDACITY_DLL_API, gAudacityOffsetInc, gAudacityPosInc, and gAudacityProjects.
AudacityProject* CreateNewAudacityProject ()
References ModuleManager::Dispatch(), gAudacityProjects, gAudioIO, GetNextWindowPlacement(), ProjectInitialized, SetActiveProject(), and AudioIO::SetListener().
Referenced by LOFImportFileHandle::lofOpenFiles(), AudacityApp::MRUOpen(), AudacityProject::OnCloseWindow(), AudacityApp::OnInit(), AudacityApp::OnMenuNew(), AudacityProject::OnNew(), AudacityProject::OpenFiles(), and RecoverAllProjects().
wxString CreateUniqueName ()
Referenced by AudacityProject::AutoSave().
AUDACITY_DLL_API AudacityProject* GetActiveProject ()
Referenced by BatchCommands::ApplyChain(), BatchCommands::ApplyCommandInBatchMode(), BatchCommands::ApplyEffectCommand(), BatchCommands::ApplySpecialCommand(), Theme::ApplyUpdatedImages(), audacityAudioCallback(), BatchProcessDialog::BatchProcessDialog(), LabelTrack::CaptureKey(), EffectNoiseRemoval::CleanSpeechMayReadNoisegate(), EffectNoiseRemoval::CleanSpeechMayWriteNoiseGate(), ContrastDialog::ContrastDialog(), EffectEqualization::DontPromptUser(), TranscriptionToolBar::EnableDisableButtons(), EditToolBar::EnableDisableButtons(), ControlToolBar::EnableDisableButtons(), ExecCommand(), ExportPlugin::Export(), FreqWindow::FreqWindow(), BatchCommands::GetAllCommands(), CommandManager::GetCategories(), ContrastDialog::GetDB(), BatchCommands::GetEndTime(), TranscriptionToolBar::GetSamples(), CommandManager::HandleCommandEntry(), TrackPanel::HandleMinimizing(), TrackPanel::HandleSelect(), CommandManager::HandleTextualCommand(), CommandManager::InsertItem(), BatchCommands::IsMono(), Track::IsSynchroSelected(), LOFImportFileHandle::LOFImportFileHandle(), AudacityApp::MRUOpen(), BatchProcessDialog::OnApplyToFiles(), TranscriptionToolBar::OnAutomateSelection(), ControlToolBar::OnBatch(), EditToolBar::OnButton(), TranscriptionToolBar::OnCalibrate(), AudacityApp::OnChar(), DeviceToolBar::OnChoice(), TranscriptionToolBar::OnEndOff(), TranscriptionToolBar::OnEndOn(), ContrastDialog::OnExport(), ControlToolBar::OnFF(), AudacityApp::OnKeyDown(), Lyrics::OnKeyEvent(), ControlToolBar::OnKeyEvent(), AudacityApp::OnKeyUp(), TranscriptionToolBar::OnMakeLabel(), Meter::OnMouse(), HighlightTextCtrl::OnMouseEvent(), LWSlider::OnMouseEvent(), AButton::OnMouseEvent(), ControlToolBar::OnPlay(), TranscriptionToolBar::OnPlaySpeed(), ControlToolBar::OnRecord(), ControlToolBar::OnRewind(), LabelDialog::OnSelectCell(), TranscriptionToolBar::OnSelectSilence(), TranscriptionToolBar::OnSelectSound(), TranscriptionToolBar::OnStartOff(), TranscriptionToolBar::OnStartOn(), ContrastDialog::OnUseSelectionB(), ContrastDialog::OnUseSelectionF(), ControlToolBar::PlayCurrentRegion(), ControlToolBar::PlayPlayRegion(), KeyConfigPrefs::Populate(), NoiseRemovalDialog::PopulateOrExchange(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), EffectEqualization::ProcessOne(), EffectNoiseRemoval::PromptUser(), EffectEqualization::PromptUser(), TimerRecordDialog::RunWaitDialog(), TrackPanel::SelectionHandleClick(), TrackPanel::SelectTrackLength(), TrackPanel::SetFocusedTrack(), ControlToolBar::SetupCutPreviewTracks(), ShowHelpDialog(), SnapManager::Snap(), SnapManager::SnapManager(), ODManager::Start(), Meter::StartMonitoring(), ControlToolBar::StopPlaying(), AudioIO::StopStream(), WaveTrack::SyncAdjust(), ToneGenDialog::TransferDataFromWindow(), Lyrics::Update(), AudacityProject::UpdateMenus(), WaveTrack::WaveTrack(), and BatchCommands::WriteMp3File().
void GetDefaultWindowRect (wxRect * defRect)
Referenced by GetNextWindowPlacement(), and SaveWindowSize().
void GetNextWindowPlacement (wxRect * nextRect, bool * pMaximized, bool * pIconized)
References gAudacityProjects, GetDefaultWindowRect(), gPrefs, and IsWindowAccessible().
Referenced by CreateNewAudacityProject().
bool IsWindowAccessible (wxRect * requestedRect)
Referenced by GetNextWindowPlacement().
void RedrawAllProjects ()
References gAudacityProjects.
Referenced by ToolsToolBar::OnTool().
void RefreshCursorForAllProjects ()
References gAudacityProjects.
Referenced by ToolsToolBar::SetCurrentTool().
void SetActiveProject (AudacityProject * project) [static]
References gActiveProject.
Referenced by CreateNewAudacityProject(), AudacityProject::OnActivate(), and AudacityProject::OnMouseEvent().
Variable Documentation
AudacityProject* gActiveProject [static]
Referenced by AudacityProject::OnCloseWindow(), and SetActiveProject().
int gAudacityOffsetInc = 0 [static]
Referenced by CloseAllProjects().
int gAudacityPosInc = 0 [static]
Referenced by CloseAllProjects().
AProjectArray gAudacityProjects
Referenced by BatchPrefs::Apply(), CloseAllProjects(), CreateNewAudacityProject(), ODTask::DoSome(), ControlToolBar::EnableDisableButtons(), GetNextWindowPlacement(), AudacityApp::MRUOpen(), AudacityProject::OnCloseWindow(), AudacityApp::OnEndSession(), AudacityProject::OnIconize(), AudacityApp::OnMenuAbout(), AudacityApp::OnMenuExit(), AudacityApp::OnMenuNew(), AudacityApp::OnMenuOpen(), AudacityApp::OnMenuPreferences(), PrefsDialog::OnOK(), AudacityProject::OnPlayStop(), AudacityProject::OnPreferences(), ControlToolBar::OnRecord(), AudacityProject::OpenFiles(), QuitAudacity(), RedrawAllProjects(), RefreshCursorForAllProjects(), and SaveWindowSize().
const int sbarControlWidth = 15
const int sbarExtraLen = 0
const int sbarHjump = 30
Referenced by AudacityProject::OnScrollLeft(), AudacityProject::OnScrollLeftButton(), AudacityProject::OnScrollRight(), and AudacityProject::OnScrollRightButton().
const int sbarSpaceWidth = 15