Audacity: TimerRecordDialog.cpp File Reference
TimerRecordDialog.cpp File Reference
#include "Audacity.h"
#include <wx/defs.h>
#include <wx/datetime.h>
#include <wx/intl.h>
#include <wx/progdlg.h>
#include <wx/sizer.h>
#include <wx/string.h>
#include <wx/timer.h>
#include <wx/dynlib.h>
#include "TimerRecordDialog.h"
#include "Project.h"
#include "Internat.h"
#include "Prefs.h"
Defines
#define MAX_PROG 1000
#define TIMER_ID 7000
Enumerations
enum {
ID_DATEPICKER_START = 10000, ID_TIMETEXT_START, ID_DATEPICKER_END, ID_TIMETEXT_END,
ID_TIMETEXT_DURATION
}
Functions
static double wxDateTime_to_AudacityTime (wxDateTime &dateTime)
Variables
const int kTimerInterval = 50
Define Documentation
#define MAX_PROG 1000
#define TIMER_ID 7000
Enumeration Type Documentation
anonymous enum
Enumerator:
ID_DATEPICKER_START
ID_TIMETEXT_START
ID_DATEPICKER_END
ID_TIMETEXT_END
ID_TIMETEXT_DURATION
Function Documentation
static double wxDateTime_to_AudacityTime (wxDateTime & dateTime) [static]
Referenced by TimerRecordDialog::OnDatePicker_End(), TimerRecordDialog::OnTimer(), TimerRecordDialog::PopulateOrExchange(), and TimerRecordDialog::UpdateEnd().
Variable Documentation
const int kTimerInterval = 50