Audacity: TrackArtist.cpp File Reference
TrackArtist.cpp File Reference
#include "Audacity.h"
#include "AudacityApp.h"
#include "TrackArtist.h"
#include "float_cast.h"
#include <math.h>
#include <float.h>
#include <wx/brush.h>
#include <wx/colour.h>
#include <wx/dc.h>
#include <wx/dcmemory.h>
#include <wx/gdicmn.h>
#include <wx/image.h>
#include <wx/pen.h>
#include <wx/log.h>
#include <wx/datetime.h>
#include "allegro.h"
#include "NoteTrack.h"
#include "AColor.h"
#include "BlockFile.h"
#include "Envelope.h"
#include "Track.h"
#include "WaveTrack.h"
#include "LabelTrack.h"
#include "TimeTrack.h"
#include "Prefs.h"
#include "Sequence.h"
#include "Spectrum.h"
#include "ViewInfo.h"
#include "widgets/Ruler.h"
#include "Theme.h"
#include "AllThemeResources.h"
Defines
#define TIME_TO_X(t) (r.x + (int) (((t) - h) * pps))
#define X_TO_TIME(xx) (((xx) - r.x) / pps + h)
#define CLIP_MAX 16000
#define CLIP(x)
#define RED(i) (unsigned char)((((i) >> 16) & 0xff))
#define GREEN(i) (unsigned char)((((i) >> 8) & 0xff))
#define BLUE(i) (unsigned char)(((i) & 0xff))
Functions
int GetWaveYPos (float value, float min, float max, int height, bool dB, bool outer, float dBr, bool clip)
float sumFreqValues (float *freq, int x0, float bin0, float bin1)
static char * IsShape (Alg_note_ptr note)
static double LookupRealAttribute (Alg_note_ptr note, Alg_attribute attr, double def)
static long LookupIntAttribute (Alg_note_ptr note, Alg_attribute attr, long def)
static bool LookupLogicalAttribute (Alg_note_ptr note, Alg_attribute attr, bool def)
static const char * LookupStringAttribute (Alg_note_ptr note, Alg_attribute attr, const char *def)
static char * LookupAtomAttribute (Alg_note_ptr note, Alg_attribute attr, char *def)
static int PITCH_TO_Y (double p, int bottom)
Variables
const int octaveHeight = 62
const int blackPos [5] = { 6, 16, 32, 42, 52 }
const int whitePos [7] = { 0, 9, 17, 26, 35, 44, 53 }
const int notePos [12]
Define Documentation
#define BLUE (i) (unsigned char)(((i) & 0xff))
Referenced by TrackArtist::DrawNoteTrack().
#define CLIP (x)
Value:
{ long c = (x); if (c < -CLIP_MAX) c = -CLIP_MAX; \
                  if (c > CLIP_MAX) c = CLIP_MAX; (x) = c; }
Referenced by TrackArtist::DrawNoteTrack().
#define CLIP_MAX 16000
Referenced by TrackArtist::DrawNoteTrack().
#define GREEN (i) (unsigned char)((((i) >> 8) & 0xff))
Referenced by TrackArtist::DrawNoteTrack().
#define RED (i) (unsigned char)((((i) >> 16) & 0xff))
Referenced by TrackArtist::DrawNoteTrack().
#define TIME_TO_X (t) (r.x + (int) (((t) - h) * pps))
Referenced by TrackArtist::DrawNoteTrack().
#define X_TO_TIME (xx) (((xx) - r.x) / pps + h)
Referenced by TrackArtist::DrawNoteTrack().
Function Documentation
int GetWaveYPos (float value, float min, float max, int height, bool dB, bool outer, float dBr, bool clip)
Takes a value between min and max and returns a value between height and 0
Todo:
Should this function move int GuiWaveTrack where it can then use the zoomMin, zoomMax and height values without having to have them passed in to it??
Referenced by TrackArtist::DrawEnvelope(), TrackArtist::DrawIndividualSamples(), TrackArtist::DrawMinMaxRMS(), Envelope::DrawPoints(), TrackArtist::DrawWaveformBackground(), Envelope::HandleMouseButtonDown(), TrackPanel::HitTestEnvelope(), and TrackPanel::HitTestSamples().
char * IsShape (Alg_note_ptr note) [static]
Referenced by TrackArtist::DrawNoteTrack().
char * LookupAtomAttribute (Alg_note_ptr note, Alg_attribute attr, char * def) [static]
Referenced by TrackArtist::DrawNoteTrack().
long LookupIntAttribute (Alg_note_ptr note, Alg_attribute attr, long def) [static]
Referenced by TrackArtist::DrawNoteTrack().
bool LookupLogicalAttribute (Alg_note_ptr note, Alg_attribute attr, bool def) [static]
Referenced by TrackArtist::DrawNoteTrack().
double LookupRealAttribute (Alg_note_ptr note, Alg_attribute attr, double def) [static]
Referenced by TrackArtist::DrawNoteTrack().
const char * LookupStringAttribute (Alg_note_ptr note, Alg_attribute attr, const char * def) [static]
Referenced by TrackArtist::DrawNoteTrack().
int PITCH_TO_Y (double p, int bottom) [static]
References notePos, and octaveHeight.
Referenced by TrackArtist::DrawNoteTrack().
float sumFreqValues (float * freq, int x0, float bin0, float bin1)
Referenced by TrackArtist::DrawClipSpectrum().
Variable Documentation
const int blackPos[5] = { 6, 16, 32, 42, 52 }
Referenced by TrackArtist::DrawNoteTrack(), and TrackArtist::DrawVRuler().
const int notePos[12]
Initial value:
 { 1, 6, 11, 16, 21, 27,
                        32, 37, 42, 47, 52, 57 }
Referenced by TrackArtist::DrawNoteTrack(), TrackArtist::DrawVRuler(), and PITCH_TO_Y().
const int octaveHeight = 62
Referenced by TrackArtist::DrawNoteTrack(), TrackArtist::DrawVRuler(), and PITCH_TO_Y().
const int whitePos[7] = { 0, 9, 17, 26, 35, 44, 53 }
Referenced by TrackArtist::DrawVRuler().