Audacity: ExportFFmpegOptions Class Reference
ExportFFmpegOptions Class Reference
Custom FFmpeg export dialog.
#include <ExportFFmpegDialogs.h>
Public Member Functions
ExportFFmpegOptions (wxWindow *parent)
~ExportFFmpegOptions ()
void PopulateOrExchange (ShuttleGui &S)
void OnOK (wxCommandEvent &event)
void OnFormatList (wxCommandEvent &event)
void DoOnFormatList ()
void OnCodecList (wxCommandEvent &event)
void DoOnCodecList ()
void OnAllFormats (wxCommandEvent &event)
void OnAllCodecs (wxCommandEvent &event)
void OnSavePreset (wxCommandEvent &event)
void OnLoadPreset (wxCommandEvent &event)
void OnDeletePreset (wxCommandEvent &event)
void OnImportPresets (wxCommandEvent &event)
void OnExportPresets (wxCommandEvent &event)
Static Public Attributes
static CompatibilityEntry CompatibilityList []
static int iAACProfileValues []
AAC profiles.
static const wxChar * iAACProfileNames []
Names of AAC profiles to be displayed.
static ExposedFormat fmts []
List of export types.
static const int iAACSampleRates [] = { 7350, 8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000, 64000, 88200, 0 }
Sample rates supported by AAC encoder (must end with zero-element).
static ApplicableFor apptable []
static const wxChar * PredictionOrderMethodNames [] = { _("Estimate"), _("2-level"), _("4-level"), _("8-level"), _("Full search"), _("Log search")}
Prediction order method - names. Labels are indices of this array.
Private Member Functions
void FindSelectedFormat (wxString **name, wxString **longname)
Finds the format currently selected and returns it's name and description.
void FindSelectedCodec (wxString **name, wxString **longname)
Finds the codec currently selected and returns it's name and description.
void FetchFormatList ()
Retreives format list from libavformat.
int FetchCompatibleFormatList (CodecID id, wxString *selfmt)
void FetchCodecList ()
Retreives codec list from libavcodec.
int FetchCompatibleCodecList (const wxChar *fmt, CodecID id)
void FetchPresetList ()
Retreives list of presets from configuration file.
void EnableDisableControls (AVCodec *cdc, wxString *selfmt)
Private Attributes
wxArrayString mShownFormatNames
wxArrayString mShownFormatLongNames
wxArrayString mShownCodecNames
wxArrayString mShownCodecLongNames
wxArrayString mFormatNames
wxArrayString mFormatLongNames
wxArrayString mCodecNames
wxArrayString mCodecLongNames
wxArrayString mProfileNames
wxArrayInt mProfileLabels
wxArrayString mPredictionOrderMethodNames
wxArrayInt mPredictionOrderMethodLabels
wxChoice * mFormatChoice
wxChoice * mCodecChoice
wxListBox * mFormatList
wxListBox * mCodecList
wxStaticText * mFormatName
wxStaticText * mCodecName
wxChoice * mPresetChoice
wxComboBox * mPresetCombo
wxSpinCtrl * mBitrateSpin
wxSpinCtrl * mQualitySpin
wxSpinCtrl * mSampleRateSpin
wxTextCtrl * mLanguageText
wxTextCtrl * mTag
wxSpinCtrl * mCutoffSpin
wxCheckBox * mBitReservoirCheck
wxChoice * mProfileChoice
wxSpinCtrl * mCompressionLevelSpin
wxSpinCtrl * mFrameSizeSpin
wxCheckBox * mUseLPCCheck
wxSpinCtrl * mLPCCoeffsPrecisionSpin
wxSpinCtrl * mMinPredictionOrderSpin
wxSpinCtrl * mMaxPredictionOrderSpin
wxChoice * mPredictionOrderMethodChoice
wxSpinCtrl * mMinPartitionOrderSpin
wxSpinCtrl * mMaxPartitionOrderSpin
wxSpinCtrl * mMuxRate
wxSpinCtrl * mPacketSize
wxButton * mOk
wxButton * mSavePreset
wxButton * mLoadPreset
wxButton * mDeletePreset
wxButton * mImportPresets
wxButton * mExportPresets
int mBitRateFromChoice
int mSampleRateFromChoice
FFmpegPresets * mPresets
wxArrayString * mPresetNames
Detailed Description
Custom FFmpeg export dialog.
Options dialog for Custom FFmpeg export format.
Constructor & Destructor Documentation
ExportFFmpegOptions::ExportFFmpegOptions (wxWindow * parent)
References FFmpegLibs::avcodec_find_encoder, DoOnCodecList(), DoOnFormatList(), eIsCreatingFromPrefs, FetchCodecList(), FetchFormatList(), FFmpegPresets::GetPresetList(), gPrefs, iAACProfileNames, iAACProfileValues, mCodecList, mFormatList, mPredictionOrderMethodLabels, mPredictionOrderMethodNames, mPresetNames, mPresets, mProfileLabels, mProfileNames, PickFFmpegLibs(), PopulateOrExchange(), PredictionOrderMethodNames, and FFmpegLibs::ValidLibsLoaded().
ExportFFmpegOptions::~ExportFFmpegOptions ()
References DropFFmpegLibs(), mPresetNames, and mPresets.
Member Function Documentation
void ExportFFmpegOptions::DoOnCodecList ()
References FFmpegLibs::avcodec_find_encoder_by_name, EnableDisableControls(), FetchCompatibleFormatList(), FindSelectedCodec(), FindSelectedFormat(), FFmpegLibs::guess_format, mCodecName, and mFormatList.
Referenced by ExportFFmpegOptions(), and OnCodecList().
void ExportFFmpegOptions::DoOnFormatList ()
References FFmpegLibs::avcodec_find_encoder_by_name, EnableDisableControls(), FetchCompatibleCodecList(), FindSelectedCodec(), FindSelectedFormat(), FFmpegLibs::guess_format, mCodecList, and mFormatName.
Referenced by ExportFFmpegOptions(), and OnFormatList().
void ExportFFmpegOptions::EnableDisableControls (AVCodec * cdc, wxString * selfmt) [private]
References apptable, ApplicableFor::control, and ApplicableFor::format.
Referenced by DoOnCodecList(), and DoOnFormatList().
void ExportFFmpegOptions::FetchCodecList () [private]
Retreives codec list from libavcodec.
References FFmpegLibs::av_codec_next, mCodecLongNames, mCodecNames, mShownCodecLongNames, and mShownCodecNames.
Referenced by ExportFFmpegOptions().
int ExportFFmpegOptions::FetchCompatibleCodecList (const wxChar * fmt, CodecID id) [private]
Retreives a list of codecs compatible to format
Parameters:
fmt Format short name
id id of the codec selected at the moment
Returns:
index of the id in new codec list or -1 if it is not in the list
References FFmpegLibs::av_codec_next, FFmpegLibs::avcodec_find_encoder, CompatibilityList, CompatibilityEntry::fmt, FFmpegLibs::guess_format, mCodecList, mShownCodecLongNames, and mShownCodecNames.
Referenced by DoOnFormatList().
int ExportFFmpegOptions::FetchCompatibleFormatList (CodecID id, wxString * selfmt) [private]
Retreives a list of formats compatible to codec
Parameters:
id Codec ID
selfmt format selected at the moment
Returns:
index of the selfmt in new format list or -1 if it is not in the list
References FFmpegLibs::av_oformat_next, CompatibilityList, CompatibilityEntry::fmt, FFmpegLibs::guess_format, mFormatList, mShownFormatLongNames, and mShownFormatNames.
Referenced by DoOnCodecList().
void ExportFFmpegOptions::FetchFormatList () [private]
Retreives format list from libavformat.
References FFmpegLibs::av_oformat_next, mFormatLongNames, mFormatNames, mShownFormatLongNames, and mShownFormatNames.
Referenced by ExportFFmpegOptions().
void ExportFFmpegOptions::FetchPresetList () [private]
Retreives list of presets from configuration file.
void ExportFFmpegOptions::FindSelectedCodec (wxString ** name, wxString ** longname) [private]
Finds the codec currently selected and returns it's name and description.
References mCodecList, mCodecLongNames, and mCodecNames.
Referenced by DoOnCodecList(), and DoOnFormatList().
void ExportFFmpegOptions::FindSelectedFormat (wxString ** name, wxString ** longname) [private]
Finds the format currently selected and returns it's name and description.
References mFormatList, mFormatLongNames, and mFormatNames.
Referenced by DoOnCodecList(), and DoOnFormatList().
void ExportFFmpegOptions::OnAllCodecs (wxCommandEvent & event)
References mCodecList, mCodecLongNames, mCodecNames, mShownCodecLongNames, and mShownCodecNames.
void ExportFFmpegOptions::OnAllFormats (wxCommandEvent & event)
References mFormatList, mFormatLongNames, mFormatNames, mShownFormatLongNames, and mShownFormatNames.
void ExportFFmpegOptions::OnCodecList (wxCommandEvent & event)
References DoOnCodecList().
void ExportFFmpegOptions::OnDeletePreset (wxCommandEvent & event)
References FFmpegPresets::DeletePreset(), mPresetNames, and mPresets.
void ExportFFmpegOptions::OnExportPresets (wxCommandEvent & event)
References FFmpegPresets::ExportPresets(), gPrefs, and mPresets.
void ExportFFmpegOptions::OnFormatList (wxCommandEvent & event)
References DoOnFormatList().
void ExportFFmpegOptions::OnImportPresets (wxCommandEvent & event)
References FFmpegPresets::GetPresetList(), gPrefs, FFmpegPresets::ImportPresets(), mPresetCombo, mPresetNames, and mPresets.
void ExportFFmpegOptions::OnLoadPreset (wxCommandEvent & event)
References FFmpegPresets::LoadPreset(), mCodecList, mCodecLongNames, mCodecNames, mFormatList, mFormatLongNames, mFormatNames, mPresets, mShownCodecLongNames, mShownCodecNames, mShownFormatLongNames, and mShownFormatNames.
void ExportFFmpegOptions::OnOK (wxCommandEvent & event)
References FFmpegLibs::avcodec_find_encoder_by_name, eIsSavingToPrefs, gPrefs, mCodecList, mFormatList, and PopulateOrExchange().
void ExportFFmpegOptions::OnSavePreset (wxCommandEvent & event)
References mPresetCombo, mPresetNames, mPresets, name, and FFmpegPresets::SavePreset().
void ExportFFmpegOptions::PopulateOrExchange (ShuttleGui & S)
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddCombo(), ShuttleGuiBase::AddFixedText(), ShuttleGuiBase::AddListBox(), ShuttleGui::AddSpace(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddVariableText(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), gPrefs, ShuttleGui::Id(), mBitrateSpin, mCodecList, mCodecName, mCodecNames, mCompressionLevelSpin, mCutoffSpin, mDeletePreset, mExportPresets, mFormatList, mFormatName, mFormatNames, mFrameSizeSpin, mImportPresets, mLanguageText, mLoadPreset, mLPCCoeffsPrecisionSpin, mMaxPartitionOrderSpin, mMaxPredictionOrderSpin, mMinPartitionOrderSpin, mMinPredictionOrderSpin, mMuxRate, mPacketSize, mPredictionOrderMethodChoice, mPredictionOrderMethodLabels, mPredictionOrderMethodNames, mPresetCombo, mPresetNames, mProfileChoice, mProfileLabels, mProfileNames, mQualitySpin, mSampleRateSpin, mSavePreset, mTag, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::SetStretchyRow(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartVerticalLay(), ShuttleGuiBase::TieCheckBox(), ShuttleGuiBase::TieChoice(), ShuttleGuiBase::TieSpinCtrl(), and ShuttleGuiBase::TieTextBox().
Referenced by ExportFFmpegOptions(), and OnOK().
Member Data Documentation
ApplicableFor ExportFFmpegOptions::apptable [static]
Some controls (parameters they represent) are only applicable to a number of codecs and/or formats. Syntax: first, enable a control for each applicable format-codec combination then disable it for anything else "any" - any format CODEC_ID_NONE - any codec This list must end with {FALSE,FFmpegExportCtrlID(0),CODEC_ID_NONE,NULL}
Referenced by EnableDisableControls().
CompatibilityEntry ExportFFmpegOptions::CompatibilityList [static]
Format-codec compatibility list Must end with NULL entry
Referenced by FetchCompatibleCodecList(), and FetchCompatibleFormatList().
ExposedFormat ExportFFmpegOptions::fmts [static]
Initial value:
{
   {FMT_M4A,         wxT("M4A"),     wxT("m4a"),  wxT("ipod"), 48,  true ,true ,_("M4A (AAC) Files (FFmpeg)"),         CODEC_ID_AAC,    true},
   {FMT_AC3,         wxT("AC3"),     wxT("ac3"),  wxT("ac3"),  7,   false,false,_("AC3 Files (FFmpeg)"),               CODEC_ID_AC3,    true},
   {FMT_AMRNB,       wxT("AMRNB"),   wxT("amr"),  wxT("amr"),  1,   false,false,_("AMR (narrow band) Files (FFmpeg)"), CODEC_ID_AMR_NB, true},
   {FMT_WMA2,        wxT("WMA"),     wxT("wma"),  wxT("asf"),  2,   false,false,_("WMA (version 2) Files (FFmpeg)"),   CODEC_ID_WMAV2,  true},
   {FMT_OTHER,       wxT("FFMPEG"),  wxT(""),     wxT(""),     255, true ,true ,_("Custom FFmpeg Export"),             CODEC_ID_NONE,   true}
}
List of export types.
Referenced by AdjustFormatIndex(), ExportFFmpeg::Export(), ExportFFmpeg::ExportFFmpeg(), ExportFFmpeg::Init(), and ExportFFmpeg::InitCodecs().
const wxChar * ExportFFmpegOptions::iAACProfileNames [static]
Initial value:
 {
   _("LC"),
   _("Main"),
}
Names of AAC profiles to be displayed.
Referenced by ExportFFmpegOptions().
int ExportFFmpegOptions::iAACProfileValues [static]
Initial value:
 {
   FF_PROFILE_AAC_LOW,
   FF_PROFILE_AAC_MAIN,
   FF_PROFILE_AAC_LTP
}
AAC profiles.
Referenced by ExportFFmpegOptions().
const int ExportFFmpegOptions::iAACSampleRates = { 7350, 8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000, 64000, 88200, 0 } [static]
Sample rates supported by AAC encoder (must end with zero-element).
Referenced by ExportFFmpeg::InitCodecs().
int ExportFFmpegOptions::mBitRateFromChoice [private]
wxSpinCtrl* ExportFFmpegOptions::mBitrateSpin [private]
Referenced by PopulateOrExchange().
wxCheckBox* ExportFFmpegOptions::mBitReservoirCheck [private]
wxChoice* ExportFFmpegOptions::mCodecChoice [private]
wxListBox* ExportFFmpegOptions::mCodecList [private]
Referenced by DoOnFormatList(), ExportFFmpegOptions(), FetchCompatibleCodecList(), FindSelectedCodec(), OnAllCodecs(), OnLoadPreset(), OnOK(), and PopulateOrExchange().
wxArrayString ExportFFmpegOptions::mCodecLongNames [private]
Referenced by FetchCodecList(), FindSelectedCodec(), OnAllCodecs(), and OnLoadPreset().
wxStaticText* ExportFFmpegOptions::mCodecName [private]
Referenced by DoOnCodecList(), and PopulateOrExchange().
wxArrayString ExportFFmpegOptions::mCodecNames [private]
Referenced by FetchCodecList(), FindSelectedCodec(), OnAllCodecs(), OnLoadPreset(), and PopulateOrExchange().
wxSpinCtrl* ExportFFmpegOptions::mCompressionLevelSpin [private]
Referenced by PopulateOrExchange().
wxSpinCtrl* ExportFFmpegOptions::mCutoffSpin [private]
Referenced by PopulateOrExchange().
wxButton* ExportFFmpegOptions::mDeletePreset [private]
Referenced by PopulateOrExchange().
wxButton* ExportFFmpegOptions::mExportPresets [private]
Referenced by PopulateOrExchange().
wxChoice* ExportFFmpegOptions::mFormatChoice [private]
wxListBox* ExportFFmpegOptions::mFormatList [private]
Referenced by DoOnCodecList(), ExportFFmpegOptions(), FetchCompatibleFormatList(), FindSelectedFormat(), OnAllFormats(), OnLoadPreset(), OnOK(), and PopulateOrExchange().
wxArrayString ExportFFmpegOptions::mFormatLongNames [private]
Referenced by FetchFormatList(), FindSelectedFormat(), OnAllFormats(), and OnLoadPreset().
wxStaticText* ExportFFmpegOptions::mFormatName [private]
Referenced by DoOnFormatList(), and PopulateOrExchange().
wxArrayString ExportFFmpegOptions::mFormatNames [private]
Referenced by FetchFormatList(), FindSelectedFormat(), OnAllFormats(), OnLoadPreset(), and PopulateOrExchange().
wxSpinCtrl* ExportFFmpegOptions::mFrameSizeSpin [private]
Referenced by PopulateOrExchange().
wxButton* ExportFFmpegOptions::mImportPresets [private]
Referenced by PopulateOrExchange().
wxTextCtrl* ExportFFmpegOptions::mLanguageText [private]
Referenced by PopulateOrExchange().
wxButton* ExportFFmpegOptions::mLoadPreset [private]
Referenced by PopulateOrExchange().
wxSpinCtrl* ExportFFmpegOptions::mLPCCoeffsPrecisionSpin [private]
Referenced by PopulateOrExchange().
wxSpinCtrl* ExportFFmpegOptions::mMaxPartitionOrderSpin [private]
Referenced by PopulateOrExchange().
wxSpinCtrl* ExportFFmpegOptions::mMaxPredictionOrderSpin [private]
Referenced by PopulateOrExchange().
wxSpinCtrl* ExportFFmpegOptions::mMinPartitionOrderSpin [private]
Referenced by PopulateOrExchange().
wxSpinCtrl* ExportFFmpegOptions::mMinPredictionOrderSpin [private]
Referenced by PopulateOrExchange().
wxSpinCtrl* ExportFFmpegOptions::mMuxRate [private]
Referenced by PopulateOrExchange().
wxButton* ExportFFmpegOptions::mOk [private]
wxSpinCtrl* ExportFFmpegOptions::mPacketSize [private]
Referenced by PopulateOrExchange().
wxChoice* ExportFFmpegOptions::mPredictionOrderMethodChoice [private]
Referenced by PopulateOrExchange().
wxArrayInt ExportFFmpegOptions::mPredictionOrderMethodLabels [private]
Referenced by ExportFFmpegOptions(), and PopulateOrExchange().
wxArrayString ExportFFmpegOptions::mPredictionOrderMethodNames [private]
Referenced by ExportFFmpegOptions(), and PopulateOrExchange().
wxChoice* ExportFFmpegOptions::mPresetChoice [private]
wxComboBox* ExportFFmpegOptions::mPresetCombo [private]
Referenced by OnImportPresets(), OnSavePreset(), and PopulateOrExchange().
wxArrayString* ExportFFmpegOptions::mPresetNames [private]
Referenced by ExportFFmpegOptions(), OnDeletePreset(), OnImportPresets(), OnSavePreset(), PopulateOrExchange(), and ~ExportFFmpegOptions().
FFmpegPresets* ExportFFmpegOptions::mPresets [private]
Referenced by ExportFFmpegOptions(), OnDeletePreset(), OnExportPresets(), OnImportPresets(), OnLoadPreset(), OnSavePreset(), and ~ExportFFmpegOptions().
wxChoice* ExportFFmpegOptions::mProfileChoice [private]
Referenced by PopulateOrExchange().
wxArrayInt ExportFFmpegOptions::mProfileLabels [private]
Referenced by ExportFFmpegOptions(), and PopulateOrExchange().
wxArrayString ExportFFmpegOptions::mProfileNames [private]
Referenced by ExportFFmpegOptions(), and PopulateOrExchange().
wxSpinCtrl* ExportFFmpegOptions::mQualitySpin [private]
Referenced by PopulateOrExchange().
int ExportFFmpegOptions::mSampleRateFromChoice [private]
wxSpinCtrl* ExportFFmpegOptions::mSampleRateSpin [private]
Referenced by PopulateOrExchange().
wxButton* ExportFFmpegOptions::mSavePreset [private]
Referenced by PopulateOrExchange().
wxArrayString ExportFFmpegOptions::mShownCodecLongNames [private]
Referenced by FetchCodecList(), FetchCompatibleCodecList(), OnAllCodecs(), and OnLoadPreset().
wxArrayString ExportFFmpegOptions::mShownCodecNames [private]
Referenced by FetchCodecList(), FetchCompatibleCodecList(), OnAllCodecs(), and OnLoadPreset().
wxArrayString ExportFFmpegOptions::mShownFormatLongNames [private]
Referenced by FetchCompatibleFormatList(), FetchFormatList(), OnAllFormats(), and OnLoadPreset().
wxArrayString ExportFFmpegOptions::mShownFormatNames [private]
Referenced by FetchCompatibleFormatList(), FetchFormatList(), OnAllFormats(), and OnLoadPreset().
wxTextCtrl* ExportFFmpegOptions::mTag [private]
Referenced by PopulateOrExchange().
wxCheckBox* ExportFFmpegOptions::mUseLPCCheck [private]
const wxChar * ExportFFmpegOptions::PredictionOrderMethodNames = { _("Estimate"), _("2-level"), _("4-level"), _("8-level"), _("Full search"), _("Log search")} [static]
Prediction order method - names. Labels are indices of this array.
Referenced by ExportFFmpegOptions().
The documentation for this class was generated from the following files:
ExportFFmpegDialogs.h
ExportFFmpegDialogs.cpp