Audacity: CrossFader Class Reference
CrossFader Class Reference
Not used by Audacity (yet) apparently work in progress that has been abandoned.
#include <CrossFade.h>
Public Member Functions
CrossFader ()
~CrossFader ()
void SetMixCrossFade ()
void SetTriangularCrossFade ()
void SetExponentialCrossFade ()
void AddClip (WaveClip *clip)
void ClearClips ()
bool GetSamples (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len)
Protected Attributes
WaveClipList mClips
Private Member Functions
bool CrossFadeMix (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len)
Private Attributes
FadeType mType
Detailed Description
Not used by Audacity (yet) apparently work in progress that has been abandoned.
Constructor & Destructor Documentation
CrossFader::CrossFader ()
CrossFader::~CrossFader ()
Member Function Documentation
void CrossFader::AddClip (WaveClip * clip)
References mClips.
void CrossFader::ClearClips ()
References mClips.
bool CrossFader::CrossFadeMix (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len) [private]
References floatSample, WaveClip::GetNumSamples(), WaveClip::GetSequence(), WaveClip::GetStartSample(), int16Sample, int24Sample, and mClips.
Referenced by GetSamples().
bool CrossFader::GetSamples (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len)
References CrossFadeMix(), FT_EXPONENTIAL, FT_MIX, FT_TRIANGULAR, and mType.
void CrossFader::SetExponentialCrossFade () [inline]
References FT_EXPONENTIAL, and mType.
void CrossFader::SetMixCrossFade () [inline]
References FT_MIX, and mType.
void CrossFader::SetTriangularCrossFade () [inline]
References FT_TRIANGULAR, and mType.
Member Data Documentation
WaveClipList CrossFader::mClips [protected]
Referenced by AddClip(), ClearClips(), and CrossFadeMix().
FadeType CrossFader::mType [private]
Referenced by GetSamples(), SetExponentialCrossFade(), SetMixCrossFade(), and SetTriangularCrossFade().
The documentation for this class was generated from the following files:
CrossFade.h
CrossFade.cpp