Audacity: WaveTrack Class Reference
WaveTrack Class Reference
A Track that contains audio waveform data.
#include <WaveTrack.h>
Classes
class Location
Used only by WaveTrack, a special way to hold location that can accommodate merged regions.
Public Types
enum LocationType { locationCutLine = 1, locationMergePoint }
enum {
WaveformDisplay, WaveformDBDisplay, SpectrumDisplay, SpectrumLogDisplay,
PitchDisplay
}
typedef bool(WaveTrack::* EditFunction)(double, double)
typedef bool(WaveTrack::* EditDestFunction)(double, double, Track **)
Public Member Functions
virtual ~WaveTrack ()
virtual double GetOffset ()
virtual void SetOffset (double o)
double GetStartTime ()
double GetEndTime ()
virtual int GetKind () const
double GetRate () const
void SetRate (double newRate)
float GetGain () const
void SetGain (float newGain)
float GetPan () const
void SetPan (float newPan)
float GetChannelGain (int channel)
sampleFormat GetSampleFormat ()
bool ConvertToSampleFormat (sampleFormat format)
virtual bool Cut (double t0, double t1, Track **dest)
virtual bool Copy (double t0, double t1, Track **dest)
virtual bool Clear (double t0, double t1)
virtual bool Paste (double t0, Track *src)
virtual bool ClearAndPaste (double t0, double t1, Track *src, bool preserve=true, bool merge=true, TimeWarper *effectWarper=NULL)
virtual bool Silence (double t0, double t1)
virtual bool InsertSilence (double t, double len)
virtual bool SplitAt (double t)
virtual bool Split (double t0, double t1)
virtual bool CutAndAddCutLine (double t0, double t1, Track **dest)
virtual bool ClearAndAddCutLine (double t0, double t1)
virtual bool SplitCut (double t0, double t1, Track **dest)
virtual bool SplitDelete (double t0, double t1)
virtual bool Join (double t0, double t1)
virtual bool Disjoin (double t0, double t1)
virtual bool Trim (double t0, double t1)
bool HandleClear (double t0, double t1, bool addCutLines, bool split)
virtual bool SyncAdjust (double oldT1, double newT1)
bool IsEmpty (double t0, double t1)
bool Append (samplePtr buffer, sampleFormat format, sampleCount len, unsigned int stride=1, XMLWriter *blockFileLog=NULL)
You must call Flush after the last Append.
bool Flush ()
Flush must be called after last Append.
bool AppendAlias (wxString fName, sampleCount start, sampleCount len, int channel, bool useOD)
bool AppendCoded (wxString fName, sampleCount start, sampleCount len, int channel, int decodeType)
unsigned int GetODFlags ()
gets an int with OD flags so that we can determine which ODTasks should be run on this track after save/open, etc.
void DeleteWaveCaches ()
Deletes all clips' wavecaches. Careful, This may not be threadsafe.
void AddInvalidRegion (sampleCount startSample, sampleCount endSample)
Adds an invalid region to the wavecache so it redraws that portion only.
bool Get (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len)
bool Set (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len)
void GetEnvelopeValues (double *buffer, int bufferLen, double t0, double tstep)
bool GetMinMax (float *min, float *max, double t0, double t1)
bool GetRMS (float *rms, double t0, double t1)
WaveClip * GetClipAtX (int xcoord)
Sequence * GetSequenceAtX (int xcoord)
Envelope * GetEnvelopeAtX (int xcoord)
Envelope * GetActiveEnvelope (void)
sampleCount GetBestBlockSize (sampleCount t)
sampleCount GetMaxBlockSize ()
sampleCount GetIdealBlockSize ()
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual void HandleXMLEndTag (const wxChar *tag)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
virtual bool GetErrorOpening ()
bool Lock ()
bool CloseLock ()
bool Unlock ()
sampleCount TimeToLongSamples (double t0) const
double LongSamplesToTime (sampleCount pos)
WaveClipList::compatibility_iterator GetClipIterator ()
WaveClip * CreateClip ()
WaveClip * GetLastOrCreateClip ()
int GetClipIndex (WaveClip *clip)
WaveClip * GetClipByIndex (int index)
int GetNumClips () const
void FillSortedClipArray (WaveClipArray &clips)
bool CanOffsetClip (WaveClip *clip, double amount, double *allowedAmount=NULL)
bool CanInsertClip (WaveClip *clip)
void MoveClipToTrack (int clipIndex, WaveTrack *dest)
void MoveClipToTrack (WaveClip *clip, WaveTrack *dest)
WaveClip * RemoveAndReturnClip (WaveClip *clip)
void AddClip (WaveClip *clip)
bool MergeClips (int clipidx1, int clipidx2)
void UpdateLocationsCache ()
int GetNumCachedLocations ()
Location GetCachedLocation (int index)
bool ExpandCutLine (double cutLinePosition, double *cutlineStart=NULL, double *cutlineEnd=NULL)
bool RemoveCutLine (double cutLinePosition)
virtual void Merge (const Track &orig)
bool Resample (int rate, ProgressDialog *progress=NULL)
void SetDisplay (int display)
int GetDisplay ()
void GetDisplayBounds (float *min, float *max)
void SetDisplayBounds (float min, float max)
Public Attributes
enum WaveTrack:: { ... } WaveTrackDisplay
Protected Attributes
WaveClipList mClips
sampleFormat mFormat
int mRate
float mGain
float mPan
float mDisplayMin
float mDisplayMax
int mDisplay
int mDisplayNumLocations
int mDisplayNumLocationsAllocated
Location * mDisplayLocations
Private Member Functions
WaveTrack (DirManager *projDirManager, sampleFormat format=(sampleFormat) 0, double rate=0)
WaveTrack (WaveTrack &orig)
void Init (const WaveTrack &orig)
virtual Track * Duplicate ()
Private Attributes
wxCriticalSection mFlushCriticalSection
wxCriticalSection mAppendCriticalSection
double mLegacyProjectFileOffset
Friends
class TrackFactory
Detailed Description
A Track that contains audio waveform data.
Member Typedef Documentation
typedef bool(WaveTrack::* WaveTrack::EditDestFunction)(double, double, Track **)
typedef bool(WaveTrack::* WaveTrack::EditFunction)(double, double)
Member Enumeration Documentation
anonymous enum
Enumerator:
WaveformDisplay
WaveformDBDisplay
SpectrumDisplay
SpectrumLogDisplay
PitchDisplay
enum WaveTrack::LocationType
Enumerator:
locationCutLine
locationMergePoint
Constructor & Destructor Documentation
WaveTrack::WaveTrack (DirManager * projDirManager, sampleFormat format = (sampleFormat)0, double rate = 0) [private]
References GetActiveProject(), AudacityProject::GetDefaultFormat(), Track::GetDefaultName(), AudacityProject::GetRate(), gPrefs, mDisplay, mDisplayLocations, mDisplayMax, mDisplayMin, mDisplayNumLocations, mDisplayNumLocationsAllocated, mFormat, mGain, mLegacyProjectFileOffset, mPan, mRate, Track::SetDefaultName(), and Track::SetName().
Referenced by Copy(), and Duplicate().
WaveTrack::WaveTrack (WaveTrack & orig) [private]
References gPrefs, Init(), mClips, Track::mDirManager, mDisplay, and mLegacyProjectFileOffset.
WaveTrack::~WaveTrack () [virtual]
References GetClipIterator(), ODManager::Instance(), ODManager::IsInstanceCreated(), mClips, mDisplayLocations, and ODManager::RemoveWaveTrack().
Member Function Documentation
void WaveTrack::AddClip (WaveClip * clip)
References mClips.
Referenced by EffectReverse::ProcessOneWave().
void WaveTrack::AddInvalidRegion (sampleCount startSample, sampleCount endSample)
Adds an invalid region to the wavecache so it redraws that portion only.
References GetClipIterator().
bool WaveTrack::Append (samplePtr buffer, sampleFormat format, sampleCount len, unsigned int stride = 1, XMLWriter * blockFileLog = NULL)
You must call Flush after the last Append.
References WaveClip::Append(), and GetLastOrCreateClip().
Referenced by BlockGenerator::GenerateTrack(), EffectDtmf::GenerateTrack(), PCMImportFileHandle::Import(), ImportRaw(), MixAndRender(), BenchmarkDialog::OnRun(), output_cb(), EffectSBSMS::Process(), EffectStereoToMono::ProcessOne(), EffectSoundTouch::ProcessOne(), EffectEqualization::ProcessOne(), EffectChangeSpeed::ProcessOne(), EffectSoundTouch::ProcessStereoResults(), EffectNoiseRemoval::RemoveNoise(), MyFLACFile::write_callback(), and FFmpegImportFileHandle::WriteData().
bool WaveTrack::AppendAlias (wxString fName, sampleCount start, sampleCount len, int channel, bool useOD)
References WaveClip::AppendAlias(), and GetLastOrCreateClip().
bool WaveTrack::AppendCoded (wxString fName, sampleCount start, sampleCount len, int channel, int decodeType)
for use with On-Demand decoding of compressed files. decodeType should be an enum from ODDecodeTask that specifies what Type of encoded file this is, such as eODFLAC
References WaveClip::AppendCoded(), and GetLastOrCreateClip().
bool WaveTrack::CanInsertClip (WaveClip * clip)
References GetClipIterator(), WaveClip::GetEndTime(), and WaveClip::GetStartTime().
Referenced by TrackPanel::MoveClipToTrack().
bool WaveTrack::CanOffsetClip (WaveClip * clip, double amount, double * allowedAmount = NULL)
References GetClipIterator(), WaveClip::GetEndTime(), and WaveClip::GetStartTime().
Referenced by TrackPanel::DoSlide().
bool WaveTrack::Clear (double t0, double t1) [virtual]
Reimplemented from Track.
References HandleClear().
Referenced by Cut(), AudacityProject::OnCutLabels(), AudacityProject::OnDeleteLabels(), AudacityProject::OnPaste(), ControlToolBar::OnRecord(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), Generator::Process(), EffectStereoToMono::ProcessOne(), EffectEqualization::ProcessOne(), AudioIO::StopStream(), SyncAdjust(), and Trim().
bool WaveTrack::ClearAndAddCutLine (double t0, double t1) [virtual]
References HandleClear().
Referenced by CutAndAddCutLine(), and AudacityProject::OnCutLabels().
bool WaveTrack::ClearAndPaste (double t0, double t1, Track * src, bool preserve = true, bool merge = true, TimeWarper * effectWarper = NULL) [virtual]
References FillSortedClipArray(), GetClipIndex(), GetClipIterator(), WaveClip::GetCutLines(), WaveClip::GetEndTime(), Track::GetEndTime(), WaveClip::GetOffset(), WaveClip::GetStartTime(), HandleClear(), LongSamplesToTime(), MergeClips(), Paste(), WaveClip::SetOffset(), SplitAt(), TimeToLongSamples(), TimeWarper::Warp(), and WAVETRACK_MERGE_POINT_TOLERANCE.
Referenced by EffectSBSMS::Process(), Generator::Process(), EffectSoundTouch::ProcessOne(), EffectNyquist::ProcessOne(), EffectNoiseRemoval::ProcessOne(), EffectChangeSpeed::ProcessOne(), and EffectSoundTouch::ProcessStereo().
bool WaveTrack::CloseLock ()
References GetClipIterator().
bool WaveTrack::ConvertToSampleFormat (sampleFormat format)
References GetClipIterator(), and mFormat.
bool WaveTrack::Copy (double t0, double t1, Track ** dest) [virtual]
References WaveClip::CreateFromCopy(), GetClipIterator(), GetEndTime(), WaveClip::GetEndTime(), WaveClip::GetOffset(), GetRate(), GetSampleFormat(), WaveClip::GetStartTime(), GetStartTime(), Init(), WaveClip::InsertSilence(), mClips, Track::mDirManager, WaveClip::Offset(), WaveClip::RemoveAllCutLines(), WaveClip::SetIsPlaceholder(), WaveClip::SetOffset(), and WaveTrack().
Referenced by Cut(), CutAndAddCutLine(), AudacityProject::OnCopyLabels(), AudacityProject::OnCutLabels(), EffectRepeat::Process(), EffectEqualization::ProcessOne(), and SplitCut().
WaveClip * WaveTrack::CreateClip ()
References mClips, Track::mDirManager, mFormat, and mRate.
Referenced by GetLastOrCreateClip(), HandleXMLChild(), InsertSilence(), and Join().
bool WaveTrack::Cut (double t0, double t1, Track ** dest) [virtual]
References Clear(), and Copy().
Referenced by BenchmarkDialog::OnRun(), Paste(), and SyncAdjust().
bool WaveTrack::CutAndAddCutLine (double t0, double t1, Track ** dest) [virtual]
References ClearAndAddCutLine(), and Copy().
void WaveTrack::DeleteWaveCaches ()
Deletes all clips' wavecaches. Careful, This may not be threadsafe.
References GetClipIterator().
bool WaveTrack::Disjoin (double t0, double t1) [virtual]
References REGION::end, floatSample, GetClipIterator(), WaveClip::GetEndTime(), GetRate(), WaveClip::GetSamples(), WaveClip::GetStartTime(), SplitDelete(), REGION::start, TimeToLongSamples(), WaveClip::TimeToSamplesClip(), and WAVETRACK_MERGE_POINT_TOLERANCE.
Referenced by AudacityProject::OnDisjoinLabels().
Track * WaveTrack::Duplicate () [private, virtual]
Implements Track.
References WaveTrack().
Referenced by TrackFactory::DuplicateWaveTrack().
bool WaveTrack::ExpandCutLine (double cutLinePosition, double * cutlineStart = NULL, double * cutlineEnd = NULL)
References WaveClip::ExpandCutLine(), WaveClip::FindCutLine(), GetClipIterator(), WaveClip::GetEndTime(), WaveClip::GetStartTime(), gPrefs, and WaveClip::Offset().
Referenced by TrackPanel::HandleTrackLocationMouseEvent().
void WaveTrack::FillSortedClipArray (WaveClipArray & clips)
References GetClipIterator(), and SortClipArrayCmpFunc().
Referenced by ClearAndPaste(), EffectReverse::ProcessOneWave(), and UpdateLocationsCache().
bool WaveTrack::Flush ()
Flush must be called after last Append.
References WaveClip::Flush(), and GetLastOrCreateClip().
Referenced by PCMImportFileHandle::Import(), OggImportFileHandle::Import(), MP3ImportFileHandle::Import(), FLACImportFileHandle::Import(), FFmpegImportFileHandle::Import(), MixAndRender(), AudacityProject::OnPaste(), ControlToolBar::OnRecord(), BenchmarkDialog::OnRun(), EffectSBSMS::Process(), Generator::Process(), EffectStereoToMono::ProcessOne(), EffectSoundTouch::ProcessOne(), EffectNyquist::ProcessOne(), EffectNoiseRemoval::ProcessOne(), EffectEqualization::ProcessOne(), EffectChangeSpeed::ProcessOne(), EffectSoundTouch::ProcessStereo(), AudioIO::StopStream(), and SyncAdjust().
bool WaveTrack::Get (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len)
MM: Now that each wave track can contain multiple clips, we don't have a continous space of samples anymore, but we simulate it, because there are alot of places (e.g. effects) using this interface. This interface makes much sense for modifying samples, but note that it is not time-accurate, because the "offset" is a double value and therefore can lie inbetween samples. But as long as you use the same value for "start" in both calls to "Set" and "Get" it is guaranteed that the same samples are affected.
References ClearSamples(), GetClipIterator(), WaveClip::GetEndSample(), WaveClip::GetNumSamples(), WaveClip::GetSamples(), WaveClip::GetStartSample(), and SAMPLE_SIZE.
Referenced by CompareAudioCommand::Apply(), EffectAutoDuck::ApplyDuckFade(), EffectChangePitch::DeduceFrequencies(), FreqWindow::GetAudio(), TrackPanel::HitTestSamples(), Mixer::MixSameRate(), Mixer::MixVariableRates(), AudacityProject::NearestZeroCrossing(), VoiceKey::OffBackward(), VoiceKey::OffForward(), VoiceKey::OnBackward(), VoiceKey::OnForward(), BenchmarkDialog::OnRun(), VampEffect::Process(), EffectTruncSilence::Process(), EffectAutoDuck::Process(), EffectTwoPassSimpleMono::ProcessOne(), EffectStereoToMono::ProcessOne(), EffectSoundTouch::ProcessOne(), EffectSimpleMono::ProcessOne(), EffectRepair::ProcessOne(), EffectNormalize::ProcessOne(), EffectNoiseRemoval::ProcessOne(), EffectFindClipping::ProcessOne(), EffectEqualization::ProcessOne(), EffectEcho::ProcessOne(), EffectClickRemoval::ProcessOne(), EffectChangeSpeed::ProcessOne(), EffectReverse::ProcessOneClip(), EffectSoundTouch::ProcessStereo(), LadspaEffect::ProcessStereo(), AudioUnitEffect::ProcessStereo(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::ProcessTwo(), resampleCB(), VoiceKey::TestDirectionChanges(), VoiceKey::TestEnergy(), and VoiceKey::TestSignChanges().
Envelope * WaveTrack::GetActiveEnvelope (void)
References GetClipIterator(), Envelope::GetDragPoint(), and WaveClip::GetEnvelope().
Referenced by TrackPanel::ForwardEventToWaveTrackEnvelope().
sampleCount WaveTrack::GetBestBlockSize (sampleCount t)
References GetClipIterator(), Sequence::GetMaxBlockSize(), GetMaxBlockSize(), WaveClip::GetNumSamples(), WaveClip::GetSequence(), WaveClip::GetStartTime(), and mRate.
Referenced by CompareAudioCommand::Apply(), BlockGenerator::GenerateTrack(), EffectDtmf::GenerateTrack(), EffectNyquist::GetCallback(), EffectTwoPassSimpleMono::ProcessOne(), EffectSoundTouch::ProcessOne(), EffectSimpleMono::ProcessOne(), EffectNormalize::ProcessOne(), EffectNoiseRemoval::ProcessOne(), EffectChangeSpeed::ProcessOne(), EffectReverse::ProcessOneClip(), EffectSoundTouch::ProcessStereo(), resampleCB(), VoiceKey::TestDirectionChanges(), VoiceKey::TestEnergy(), and VoiceKey::TestSignChanges().
Location WaveTrack::GetCachedLocation (int index) [inline]
Referenced by TrackArtist::DrawWaveform(), and TrackPanel::HandleTrackLocationMouseEvent().
float WaveTrack::GetChannelGain (int channel)
References mGain, and mPan.
Referenced by audacityAudioCallback(), Mixer::MixSameRate(), Mixer::MixVariableRates(), and MixerTrackCluster::UpdateMeter().
WaveClip * WaveTrack::GetClipAtX (int xcoord)
References GetClipIterator(), and WaveClip::GetDisplayRect().
Referenced by GetEnvelopeAtX(), GetSequenceAtX(), TrackPanel::HandleSelect(), and TrackPanel::StartSlide().
WaveClip * WaveTrack::GetClipByIndex (int index)
References mClips.
Referenced by AudacityProject::GetTime(), MergeClips(), BenchmarkDialog::OnRun(), and Paste().
int WaveTrack::GetClipIndex (WaveClip * clip)
References mClips.
Referenced by ClearAndPaste().
WaveClipList::compatibility_iterator WaveTrack::GetClipIterator () [inline]
Referenced by AddInvalidRegion(), CanInsertClip(), CanOffsetClip(), ClearAndPaste(), CloseLock(), ConvertToSampleFormat(), Copy(), DeleteWaveCaches(), Disjoin(), TrackArtist::DrawSpectrum(), TrackArtist::DrawTrack(), TrackArtist::DrawWaveform(), ExpandCutLine(), FillSortedClipArray(), Get(), GetActiveEnvelope(), GetAllSeqBlocks(), GetBestBlockSize(), GetClipAtX(), GetEndTime(), GetEnvelopeValues(), GetErrorOpening(), GetMaxBlockSize(), GetMinMax(), GetODFlags(), GetRMS(), UndoManager::GetSpaceUsage(), GetStartTime(), HandleClear(), InsertSilence(), TrackArtist::InvalidateSpectrumCache(), IsEmpty(), Join(), Lock(), MoveClipToTrack(), Paste(), EffectEqualization::ProcessOne(), EffectReverse::ProcessOneWave(), AudacityProject::RedrawProject(), RemoveCutLine(), Resample(), Set(), SetOffset(), SetRate(), Silence(), SnapManager::SnapManager(), SplitAt(), Trim(), Unlock(), WriteXML(), and ~WaveTrack().
int WaveTrack::GetDisplay () [inline]
Referenced by TrackArtist::DrawTrack(), TrackPanel::ForwardEventToWaveTrackEnvelope(), TrackPanel::HitTestEnvelope(), TrackPanel::HitTestSamples(), TrackPanel::OnSetDisplay(), and TrackArtist::UpdateVRuler().
void WaveTrack::GetDisplayBounds (float * min, float * max)
References mDisplayMax, and mDisplayMin.
Referenced by TrackArtist::DrawClipWaveform(), TrackPanel::ForwardEventToWaveTrackEnvelope(), TrackPanel::HandleVZoomButtonUp(), TrackPanel::HitTestEnvelope(), TrackPanel::HitTestSamples(), and TrackArtist::UpdateVRuler().
double WaveTrack::GetEndTime () [virtual]
Reimplemented from Track.
References GetClipIterator(), and mClips.
Referenced by Copy(), UndoManager::Debug(), Effect::GetSamples(), AudacityProject::GetTime(), MixerTrackCluster::HandleSelect(), Mixer::MixSameRate(), Mixer::MixVariableRates(), ControlToolBar::OnRecord(), BenchmarkDialog::OnRun(), Paste(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), EffectSoundTouch::Process(), EffectSimpleMono::Process(), EffectSBSMS::Process(), EffectRepair::Process(), EffectNormalize::Process(), EffectNoiseRemoval::Process(), EffectFindClipping::Process(), EffectEqualization::Process(), EffectEcho::Process(), EffectClickRemoval::Process(), EffectChangeSpeed::Process(), EffectStereoToMono::ProcessOne(), EffectSoundTouch::ProcessOne(), EffectNyquist::ProcessOne(), EffectNoiseRemoval::ProcessOne(), EffectChangeSpeed::ProcessOne(), EffectTwoPassSimpleMono::ProcessPass(), EffectSoundTouch::ProcessStereo(), EffectRepeat::PromptUser(), AudioIO::StopStream(), SyncAdjust(), and Trim().
Envelope * WaveTrack::GetEnvelopeAtX (int xcoord)
References GetClipAtX(), and WaveClip::GetEnvelope().
Referenced by TrackPanel::ForwardEventToWaveTrackEnvelope(), TrackPanel::HitTestEnvelope(), and TrackPanel::HitTestSamples().
void WaveTrack::GetEnvelopeValues (double * buffer, int bufferLen, double t0, double tstep)
References GetClipIterator(), WaveClip::GetEndTime(), WaveClip::GetEnvelope(), GetStartTime(), WaveClip::GetStartTime(), and Envelope::GetValues().
Referenced by Mixer::MixSameRate(), and Mixer::MixVariableRates().
bool WaveTrack::GetErrorOpening () [virtual]
Reimplemented from Track.
References GetClipIterator().
float WaveTrack::GetGain () const
References mGain.
Referenced by TrackInfo::DrawSliders(), MixerTrackCluster::UpdateGain(), and AudacityProject::WriteXML().
sampleCount WaveTrack::GetIdealBlockSize ()
References Sequence::GetIdealBlockSize(), GetLastOrCreateClip(), and WaveClip::GetSequence().
Referenced by EffectNyquist::GetCallback(), and MixAndRender().
virtual int WaveTrack::GetKind () const [inline, virtual]
Reimplemented from Track.
Referenced by TrackPanel::DoSlide(), and EffectStereoToMono::Process().
WaveClip * WaveTrack::GetLastOrCreateClip ()
References CreateClip(), mClips, Track::mOffset, and WaveClip::SetOffset().
Referenced by Append(), AppendAlias(), AppendCoded(), Flush(), GetIdealBlockSize(), HandleXMLChild(), HandleXMLEndTag(), and RecordingRecoveryHandler::HandleXMLTag().
sampleCount WaveTrack::GetMaxBlockSize ()
References GetClipIterator(), Sequence::GetMaxBlockSize(), WaveClip::GetSequence(), Track::mDirManager, and mFormat.
Referenced by CompareAudioCommand::Apply(), BlockGenerator::GenerateTrack(), EffectDtmf::GenerateTrack(), GetBestBlockSize(), PCMImportFileHandle::Import(), FLACImportFileHandle::Import(), ImportRaw(), EffectCompressor::InitPass1(), EffectTruncSilence::Process(), EffectSBSMS::Process(), EffectTwoPassSimpleMono::ProcessOne(), EffectStereoToMono::ProcessOne(), EffectSoundTouch::ProcessOne(), EffectSimpleMono::ProcessOne(), EffectNormalize::ProcessOne(), EffectNoiseRemoval::ProcessOne(), EffectEqualization::ProcessOne(), EffectClickRemoval::ProcessOne(), EffectChangeSpeed::ProcessOne(), EffectReverse::ProcessOneClip(), EffectSoundTouch::ProcessStereo(), LadspaEffect::ProcessStereo(), AudioUnitEffect::ProcessStereo(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::ProcessTwo(), VoiceKey::TestDirectionChanges(), VoiceKey::TestEnergy(), and VoiceKey::TestSignChanges().
bool WaveTrack::GetMinMax (float * min, float * max, double t0, double t1)
References GetClipIterator(), WaveClip::GetEndTime(), and WaveClip::GetStartTime().
Referenced by MixerTrackCluster::UpdateMeter().
int WaveTrack::GetNumCachedLocations () [inline]
Referenced by TrackArtist::DrawWaveform(), and TrackPanel::HandleTrackLocationMouseEvent().
int WaveTrack::GetNumClips () const
References mClips.
Referenced by AudacityProject::GetTime(), and Paste().
unsigned int WaveTrack::GetODFlags ()
gets an int with OD flags so that we can determine which ODTasks should be run on this track after save/open, etc.
References GetClipIterator(), Sequence::GetODFlags(), and WaveClip::GetSequence().
double WaveTrack::GetOffset () [virtual]
Reimplemented from Track.
References GetStartTime().
Referenced by TranscriptionToolBar::GetSamples(), MixerTrackCluster::HandleSelect(), and SetOffset().
float WaveTrack::GetPan () const
References mPan.
Referenced by TrackInfo::DrawSliders(), MixerTrackCluster::UpdatePan(), and AudacityProject::WriteXML().
double WaveTrack::GetRate () const
References mRate.
Referenced by EffectToneGen::BeforeTrack(), VoiceKey::CalibrateNoise(), Copy(), EffectChangePitch::DeduceFrequencies(), ODTask::DemandTrackUpdate(), Disjoin(), EffectEqualization::DontPromptUser(), TrackPanel::DoSlide(), EffectNoise::GenerateBlock(), EffectDtmf::GenerateTrack(), FreqWindow::GetAudio(), TranscriptionToolBar::GetSamples(), TrackPanel::HitTestSamples(), VampEffect::Init(), Mixer::Mixer(), Mixer::MixSameRate(), Mixer::MixVariableRates(), AudacityProject::NearestZeroCrossing(), VoiceKey::OffBackward(), VoiceKey::OffForward(), VoiceKey::OnBackward(), VoiceKey::OnForward(), AudacityProject::OnPaste(), TrackPanel::OnTrackMenu(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), EffectSimpleMono::Process(), EffectSBSMS::Process(), EffectRepair::Process(), EffectNormalize::Process(), Mixer::Process(), Generator::Process(), EffectSoundTouch::ProcessOne(), EffectNyquist::ProcessOne(), EffectNoiseRemoval::ProcessOne(), EffectEqualization::ProcessOne(), EffectEcho::ProcessOne(), EffectChangeSpeed::ProcessOne(), EffectTwoPassSimpleMono::ProcessPass(), EffectSpikeCleaner::ProcessSimpleMono(), EffectSoundTouch::ProcessStereo(), LadspaEffect::ProcessStereo(), AudioUnitEffect::ProcessStereo(), EffectRepeat::PromptUser(), EffectEqualization::PromptUser(), MixerTrackCluster::ResetMeter(), SyncAdjust(), and TrackArtist::UpdateVRuler().
bool WaveTrack::GetRMS (float * rms, double t0, double t1)
References GetClipIterator(), WaveClip::GetEndTime(), WaveClip::GetNumSamples(), and WaveClip::GetStartTime().
Referenced by MixerTrackCluster::UpdateMeter().
sampleFormat WaveTrack::GetSampleFormat () [inline]
Referenced by Copy(), AudacityProject::OnPaste(), TrackPanel::OnTrackMenu(), EffectSBSMS::Process(), Generator::Process(), EffectSoundTouch::ProcessOne(), EffectNyquist::ProcessOne(), EffectNoiseRemoval::ProcessOne(), EffectChangeSpeed::ProcessOne(), EffectSoundTouch::ProcessStereo(), and SyncAdjust().
Sequence * WaveTrack::GetSequenceAtX (int xcoord)
References GetClipAtX(), and WaveClip::GetSequence().
double WaveTrack::GetStartTime () [virtual]
Reimplemented from Track.
References GetClipIterator(), and mClips.
Referenced by Copy(), UndoManager::Debug(), EffectChangePitch::DeduceFrequencies(), GetEnvelopeValues(), GetOffset(), Effect::GetSamples(), Join(), Paste(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), EffectSoundTouch::Process(), EffectSimpleMono::Process(), EffectSBSMS::Process(), EffectRepair::Process(), EffectNormalize::Process(), EffectNoiseRemoval::Process(), EffectFindClipping::Process(), EffectEqualization::Process(), EffectEcho::Process(), EffectClickRemoval::Process(), EffectChangeSpeed::Process(), EffectStereoToMono::ProcessOne(), EffectTwoPassSimpleMono::ProcessPass(), EffectRepeat::PromptUser(), and AudioIO::StopStream().
bool WaveTrack::HandleClear (double t0, double t1, bool addCutLines, bool split)
References WaveClip::AfterClip(), WaveClip::BeforeClip(), WaveClip::Clear(), WaveClip::ClearAndAddCutLine(), GetClipIterator(), WaveClip::GetEndTime(), WaveClip::GetEnvelope(), Envelope::GetNumberOfPoints(), WaveClip::GetOffset(), WaveClip::GetRate(), WaveClip::GetStartTime(), Envelope::GetValue(), gPrefs, Envelope::Insert(), mClips, Track::mDirManager, WaveClip::Offset(), Envelope::RemoveUnneededPoints(), and WaveClip::WithinClip().
Referenced by Clear(), ClearAndAddCutLine(), ClearAndPaste(), EffectNoiseRemoval::ProcessOne(), and SplitDelete().
XMLTagHandler * WaveTrack::HandleXMLChild (const wxChar * tag) [virtual]
Implements Track.
References CreateClip(), WaveClip::GetEnvelope(), GetLastOrCreateClip(), WaveClip::GetSequence(), mLegacyProjectFileOffset, and WaveClip::SetOffset().
void WaveTrack::HandleXMLEndTag (const wxChar * tag) [virtual]
Reimplemented from XMLTagHandler.
References GetLastOrCreateClip(), and WaveClip::HandleXMLEndTag().
bool WaveTrack::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements Track.
References Internat::CompatibleToDouble(), XMLValueChecker::IsGoodInt(), XMLValueChecker::IsGoodString(), XMLValueChecker::IsValidChannel(), Track::mChannel, mGain, Track::mHeight, mLegacyProjectFileOffset, Track::mMinimized, Track::mMute, Track::mName, mPan, mRate, Track::mSolo, and Track::SetLinked().
void WaveTrack::Init (const WaveTrack & orig) [private]
Reimplemented from Track.
References Track::GetDefaultName(), Track::GetName(), mDisplay, mDisplayLocations, mDisplayMax, mDisplayMin, mDisplayNumLocations, mDisplayNumLocationsAllocated, mFormat, mGain, mPan, mRate, Track::SetDefaultName(), and Track::SetName().
Referenced by Copy(), and WaveTrack().
bool WaveTrack::InsertSilence (double t, double len) [virtual]
Reimplemented from Track.
References WaveClip::BeforeClip(), CreateClip(), GetClipIterator(), WaveClip::InsertSilence(), mClips, WaveClip::Offset(), and WaveClip::WithinClip().
Referenced by EffectSilence::GenerateTrack(), Effect::GetSamples(), FFmpegImportFileHandle::Import(), AudacityProject::OnPaste(), ControlToolBar::OnRecord(), AudioIO::StopStream(), and SyncAdjust().
bool WaveTrack::IsEmpty (double t0, double t1)
References GetClipIterator(), WaveClip::GetEndTime(), WaveClip::GetStartTime(), and mRate.
Referenced by Paste(), Generator::Process(), and SyncAdjust().
bool WaveTrack::Join (double t0, double t1) [virtual]
References CreateClip(), GetClipIterator(), WaveClip::GetEndTime(), WaveClip::GetOffset(), GetStartTime(), WaveClip::GetStartTime(), WaveClip::InsertSilence(), mClips, mRate, WaveClip::Paste(), and WaveClip::SetOffset().
Referenced by AudacityProject::OnJoinLabels(), and EffectEqualization::ProcessOne().
bool WaveTrack::Lock ()
References GetClipIterator().
double WaveTrack::LongSamplesToTime (sampleCount pos)
References mRate.
Referenced by CompareAudioCommand::Apply(), EffectAutoDuck::ApplyDuckFade(), ClearAndPaste(), EffectRepeat::Process(), EffectAutoDuck::Process(), EffectNoiseRemoval::ProcessOne(), EffectFindClipping::ProcessOne(), EffectEqualization::ProcessOne(), EffectReverse::ProcessOneWave(), and SplitAt().
void WaveTrack::Merge (const Track & orig) [virtual]
References Track::GetKind(), mDisplay, and Track::Wave.
bool WaveTrack::MergeClips (int clipidx1, int clipidx2)
References GetClipByIndex(), WaveClip::GetEndTime(), mClips, and WaveClip::Paste().
Referenced by ClearAndPaste(), and TrackPanel::HandleTrackLocationMouseEvent().
void WaveTrack::MoveClipToTrack (WaveClip * clip, WaveTrack * dest)
References GetClipIterator(), and mClips.
void WaveTrack::MoveClipToTrack (int clipIndex, WaveTrack * dest)
References mClips.
Referenced by TrackPanel::MoveClipToTrack().
bool WaveTrack::Paste (double t0, Track * src) [virtual]
References Cut(), GetClipByIndex(), GetClipIterator(), WaveClip::GetEndTime(), GetEndTime(), WaveClip::GetIsPlaceholder(), Track::GetKind(), GetNumClips(), WaveClip::GetStartSample(), WaveClip::GetStartTime(), GetStartTime(), gPrefs, IsEmpty(), WaveClip::MarkChanged(), mClips, Track::mDirManager, mRate, WaveClip::Offset(), WaveClip::Paste(), WaveClip::Resample(), TimeToLongSamples(), Track::Wave, and WaveClip::WithinClip().
Referenced by ClearAndPaste(), AudacityProject::EditClipboardByLabel(), ControlToolBar::OnRecord(), BenchmarkDialog::OnRun(), EffectRepeat::Process(), EffectStereoToMono::ProcessOne(), EffectEqualization::ProcessOne(), and SyncAdjust().
WaveClip * WaveTrack::RemoveAndReturnClip (WaveClip * clip)
References mClips.
Referenced by EffectReverse::ProcessOneWave().
bool WaveTrack::RemoveCutLine (double cutLinePosition)
References GetClipIterator().
Referenced by TrackPanel::HandleTrackLocationMouseEvent().
bool WaveTrack::Resample (int rate, ProgressDialog * progress = NULL)
References GetClipIterator(), and mRate.
bool WaveTrack::Set (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len)
References GetClipIterator(), WaveClip::GetEndSample(), WaveClip::GetNumSamples(), WaveClip::GetStartSample(), WaveClip::MarkChanged(), SAMPLE_SIZE, and WaveClip::SetSamples().
Referenced by EffectAutoDuck::ApplyDuckFade(), EffectTruncSilence::Process(), EffectTwoPassSimpleMono::ProcessOne(), EffectSimpleMono::ProcessOne(), EffectRepair::ProcessOne(), EffectNormalize::ProcessOne(), EffectEcho::ProcessOne(), EffectClickRemoval::ProcessOne(), EffectReverse::ProcessOneClip(), LadspaEffect::ProcessStereo(), AudioUnitEffect::ProcessStereo(), and EffectSimplePairedTwoTrack< _DataType, _xxxSample >::ProcessTwo().
void WaveTrack::SetDisplay (int display) [inline]
Referenced by TrackPanel::OnSetDisplay().
void WaveTrack::SetDisplayBounds (float min, float max)
References mDisplayMax, and mDisplayMin.
Referenced by TrackPanel::HandleVZoomButtonUp().
void WaveTrack::SetGain (float newGain)
References mGain.
Referenced by MixerTrackCluster::HandleSliderGain(), TrackPanel::HandleSliders(), AudacityProject::SaveCompressedWaveTracks(), and TrackPanel::SetTrackGain().
void WaveTrack::SetOffset (double o) [virtual]
Reimplemented from Track.
References GetClipIterator(), WaveClip::GetOffset(), GetOffset(), Track::mOffset, and WaveClip::SetOffset().
Referenced by ControlToolBar::OnRecord(), and AudioIO::StopStream().
void WaveTrack::SetPan (float newPan)
References mPan.
Referenced by MixerTrackCluster::HandleSliderPan(), TrackPanel::HandleSliders(), AudacityProject::SaveCompressedWaveTracks(), and TrackPanel::SetTrackPan().
void WaveTrack::SetRate (double newRate)
References GetClipIterator(), and mRate.
Referenced by BenchmarkDialog::OnRun().
bool WaveTrack::Silence (double t0, double t1) [virtual]
Reimplemented from Track.
References GetClipIterator(), WaveClip::GetEndSample(), WaveClip::GetNumSamples(), WaveClip::GetSequence(), WaveClip::GetStartSample(), WaveClip::MarkChanged(), mRate, and Sequence::SetSilence().
Referenced by AudacityProject::OnSilenceLabels().
bool WaveTrack::Split (double t0, double t1) [virtual]
References SplitAt().
Referenced by AudacityProject::OnSplit(), and AudacityProject::OnSplitLabels().
bool WaveTrack::SplitAt (double t) [virtual]
References WaveClip::Clear(), GetClipIterator(), WaveClip::GetEndTime(), WaveClip::GetEnvelope(), WaveClip::GetOffset(), WaveClip::GetRate(), WaveClip::GetStartTime(), Envelope::GetValue(), Envelope::Insert(), LongSamplesToTime(), mClips, Track::mDirManager, mRate, WaveClip::Offset(), TimeToLongSamples(), and WaveClip::WithinClip().
Referenced by ClearAndPaste(), EffectReverse::ProcessOneWave(), and Split().
bool WaveTrack::SplitCut (double t0, double t1, Track ** dest) [virtual]
References Copy(), and SplitDelete().
Referenced by AudacityProject::OnSplitCutLabels().
bool WaveTrack::SplitDelete (double t0, double t1) [virtual]
References HandleClear().
Referenced by Disjoin(), AudacityProject::OnSplitDeleteLabels(), SplitCut(), and Trim().
bool WaveTrack::SyncAdjust (double oldT1, double newT1) [virtual]
Reimplemented from Track.
References Clear(), Cut(), Flush(), GetActiveProject(), GetEndTime(), GetRate(), GetSampleFormat(), AudacityProject::GetTrackFactory(), gPrefs, InsertSilence(), IsEmpty(), TrackFactory::NewWaveTrack(), and Paste().
AUDACITY_DLL_API sampleCount WaveTrack::TimeToLongSamples (double t0) const
References AUDACITY_DLL_API, and mRate.
Referenced by CompareAudioCommand::Apply(), EffectAutoDuck::ApplyDuckFade(), ClearAndPaste(), EffectChangePitch::DeduceFrequencies(), Disjoin(), BlockGenerator::GenerateTrack(), FreqWindow::GetAudio(), Effect::GetSamples(), Mixer::Mixer(), Mixer::MixVariableRates(), AudacityProject::NearestZeroCrossing(), Paste(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), EffectSoundTouch::Process(), EffectSimpleMono::Process(), EffectSBSMS::Process(), EffectReverse::Process(), EffectRepeat::Process(), EffectRepair::Process(), EffectNyquist::Process(), EffectNormalize::Process(), EffectNoiseRemoval::Process(), EffectFindClipping::Process(), EffectEqualization::Process(), EffectEcho::Process(), EffectClickRemoval::Process(), EffectChangeSpeed::Process(), EffectAutoDuck::Process(), EffectReverse::ProcessOneWave(), EffectTwoPassSimpleMono::ProcessPass(), Mixer::Reposition(), SplitAt(), and MixerTrackCluster::UpdateMeter().
bool WaveTrack::Trim (double t0, double t1) [virtual]
References Clear(), WaveClip::Clear(), GetClipIterator(), GetEndTime(), WaveClip::GetEndTime(), WaveClip::GetStartTime(), WaveClip::SetOffset(), and SplitDelete().
bool WaveTrack::Unlock ()
References GetClipIterator().
void WaveTrack::UpdateLocationsCache ()
References WaveTrack::Location::clipidx1, WaveTrack::Location::clipidx2, FillSortedClipArray(), WaveClip::GetCutLines(), WaveClip::GetEndTime(), WaveClip::GetOffset(), WaveClip::GetStartTime(), locationCutLine, locationMergePoint, mClips, mDisplayLocations, mDisplayNumLocations, mDisplayNumLocationsAllocated, WaveTrack::Location::pos, WaveTrack::Location::typ, and WAVETRACK_MERGE_POINT_TOLERANCE.
Referenced by TrackArtist::DrawWaveform().
void WaveTrack::WriteXML (XMLWriter & xmlFile) [virtual]
Implements Track.
References XMLWriter::EndTag(), Track::GetActualHeight(), GetClipIterator(), Track::GetMinimized(), Track::mChannel, mGain, Track::mLinked, Track::mMute, Track::mName, mPan, mRate, Track::mSolo, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
Friends And Related Function Documentation
friend class TrackFactory [friend]
Member Data Documentation
wxCriticalSection WaveTrack::mAppendCriticalSection [private]
WaveClipList WaveTrack::mClips [protected]
Referenced by AddClip(), Copy(), CreateClip(), GetClipByIndex(), GetClipIndex(), GetEndTime(), GetLastOrCreateClip(), GetNumClips(), GetStartTime(), HandleClear(), InsertSilence(), Join(), MergeClips(), MoveClipToTrack(), Paste(), RemoveAndReturnClip(), SplitAt(), UpdateLocationsCache(), WaveTrack(), and ~WaveTrack().
int WaveTrack::mDisplay [protected]
Referenced by Init(), Merge(), and WaveTrack().
Location* WaveTrack::mDisplayLocations [protected]
Referenced by Init(), UpdateLocationsCache(), WaveTrack(), and ~WaveTrack().
float WaveTrack::mDisplayMax [protected]
Referenced by GetDisplayBounds(), Init(), SetDisplayBounds(), and WaveTrack().
float WaveTrack::mDisplayMin [protected]
Referenced by GetDisplayBounds(), Init(), SetDisplayBounds(), and WaveTrack().
int WaveTrack::mDisplayNumLocations [protected]
Referenced by Init(), UpdateLocationsCache(), and WaveTrack().
int WaveTrack::mDisplayNumLocationsAllocated [protected]
Referenced by Init(), UpdateLocationsCache(), and WaveTrack().
wxCriticalSection WaveTrack::mFlushCriticalSection [private]
sampleFormat WaveTrack::mFormat [protected]
Referenced by ConvertToSampleFormat(), CreateClip(), GetMaxBlockSize(), Init(), and WaveTrack().
float WaveTrack::mGain [protected]
Referenced by GetChannelGain(), GetGain(), HandleXMLTag(), Init(), SetGain(), WaveTrack(), and WriteXML().
double WaveTrack::mLegacyProjectFileOffset [private]
Referenced by HandleXMLChild(), HandleXMLTag(), and WaveTrack().
float WaveTrack::mPan [protected]
Referenced by GetChannelGain(), GetPan(), HandleXMLTag(), Init(), SetPan(), WaveTrack(), and WriteXML().
int WaveTrack::mRate [protected]
Referenced by CreateClip(), GetBestBlockSize(), GetRate(), HandleXMLTag(), Init(), IsEmpty(), Join(), LongSamplesToTime(), Paste(), Resample(), SetRate(), Silence(), SplitAt(), TimeToLongSamples(), WaveTrack(), and WriteXML().
enum { ... } WaveTrack::WaveTrackDisplay
The documentation for this class was generated from the following files:
WaveTrack.h
WaveTrack.cpp