Audacity: ChangeTempoDialog Class Reference
ChangeTempoDialog Class Reference
Dialog used with EffectChangeTempo.
#include <ChangeTempo.h>
Public Member Functions
ChangeTempoDialog (EffectChangeTempo *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
double m_PercentChange
unsigned int m_FromBPM
unsigned int m_ToBPM
double m_FromLength
double m_ToLength
Private Member Functions
void OnText_PercentChange (wxCommandEvent &event)
void OnSlider_PercentChange (wxCommandEvent &event)
void OnText_FromBPM (wxCommandEvent &event)
void OnText_ToBPM (wxCommandEvent &event)
void OnText_ToLength (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
void Update_Text_PercentChange ()
void Update_Slider_PercentChange ()
void Update_Text_ToBPM ()
void Update_Text_ToLength ()
Private Attributes
EffectChangeTempo * mEffect
bool m_bLoopDetect
wxTextCtrl * m_pTextCtrl_PercentChange
wxSlider * m_pSlider_PercentChange
wxTextCtrl * m_pTextCtrl_FromBPM
wxTextCtrl * m_pTextCtrl_ToBPM
wxTextCtrl * m_pTextCtrl_FromLength
wxTextCtrl * m_pTextCtrl_ToLength
Detailed Description
Dialog used with EffectChangeTempo.
Constructor & Destructor Documentation
ChangeTempoDialog::ChangeTempoDialog (EffectChangeTempo * effect, wxWindow * parent)
Member Function Documentation
void ChangeTempoDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References m_PercentChange, EffectChangeTempo::m_PercentChange, mEffect, Effect::Preview(), TransferDataFromWindow(), and Update_Text_PercentChange().
void ChangeTempoDialog::OnSlider_PercentChange (wxCommandEvent & event) [private]
References m_bLoopDetect, m_PercentChange, m_pSlider_PercentChange, PERCENTCHANGE_SLIDER_WARP, Update_Text_PercentChange(), Update_Text_ToBPM(), and Update_Text_ToLength().
void ChangeTempoDialog::OnText_FromBPM (wxCommandEvent & event) [private]
References m_bLoopDetect, m_FromBPM, m_pTextCtrl_FromBPM, and Update_Text_ToBPM().
void ChangeTempoDialog::OnText_PercentChange (wxCommandEvent & event) [private]
References m_bLoopDetect, m_PercentChange, m_pTextCtrl_PercentChange, Update_Slider_PercentChange(), Update_Text_ToBPM(), and Update_Text_ToLength().
void ChangeTempoDialog::OnText_ToBPM (wxCommandEvent & event) [private]
References m_bLoopDetect, m_FromBPM, m_PercentChange, m_pTextCtrl_ToBPM, m_ToBPM, Update_Slider_PercentChange(), Update_Text_PercentChange(), and Update_Text_ToLength().
void ChangeTempoDialog::OnText_ToLength (wxCommandEvent & event) [private]
References m_bLoopDetect, m_FromLength, m_PercentChange, m_pTextCtrl_ToLength, m_ToLength, Update_Slider_PercentChange(), Update_Text_PercentChange(), and Update_Text_ToBPM().
void ChangeTempoDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddSlider(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddUnits(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGui::Id(), ID_SLIDER_PERCENTCHANGE, ID_TEXT_FROMBPM, ID_TEXT_FROMLENGTH, ID_TEXT_PERCENTCHANGE, ID_TEXT_TOBPM, ID_TEXT_TOLENGTH, m_pSlider_PercentChange, m_pTextCtrl_FromBPM, m_pTextCtrl_FromLength, m_pTextCtrl_PercentChange, m_pTextCtrl_ToBPM, m_pTextCtrl_ToLength, PERCENTCHANGE_MAX, PERCENTCHANGE_MIN, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartMultiColumn().
bool ChangeTempoDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References m_FromBPM, m_PercentChange, m_pTextCtrl_FromBPM, m_pTextCtrl_PercentChange, m_pTextCtrl_ToBPM, m_pTextCtrl_ToLength, m_ToBPM, and m_ToLength.
Referenced by OnPreview().
bool ChangeTempoDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References m_bLoopDetect, m_FromBPM, m_FromLength, m_pTextCtrl_FromBPM, m_pTextCtrl_FromLength, m_pTextCtrl_ToBPM, m_pTextCtrl_ToLength, m_ToBPM, m_ToLength, Update_Slider_PercentChange(), and Update_Text_PercentChange().
void ChangeTempoDialog::Update_Slider_PercentChange () [private]
References m_PercentChange, m_pSlider_PercentChange, and PERCENTCHANGE_SLIDER_WARP.
Referenced by OnText_PercentChange(), OnText_ToBPM(), OnText_ToLength(), and TransferDataToWindow().
void ChangeTempoDialog::Update_Text_PercentChange () [private]
References m_PercentChange, and m_pTextCtrl_PercentChange.
Referenced by OnPreview(), OnSlider_PercentChange(), OnText_ToBPM(), OnText_ToLength(), and TransferDataToWindow().
void ChangeTempoDialog::Update_Text_ToBPM () [private]
References m_FromBPM, m_PercentChange, m_pTextCtrl_ToBPM, and m_ToBPM.
Referenced by OnSlider_PercentChange(), OnText_FromBPM(), OnText_PercentChange(), and OnText_ToLength().
void ChangeTempoDialog::Update_Text_ToLength () [private]
References m_FromLength, m_PercentChange, m_pTextCtrl_ToLength, and m_ToLength.
Referenced by OnSlider_PercentChange(), OnText_PercentChange(), and OnText_ToBPM().
Member Data Documentation
bool ChangeTempoDialog::m_bLoopDetect [private]
Referenced by OnSlider_PercentChange(), OnText_FromBPM(), OnText_PercentChange(), OnText_ToBPM(), OnText_ToLength(), and TransferDataToWindow().
unsigned int ChangeTempoDialog::m_FromBPM
Referenced by OnText_FromBPM(), OnText_ToBPM(), EffectChangeTempo::PromptUser(), TransferDataFromWindow(), TransferDataToWindow(), and Update_Text_ToBPM().
double ChangeTempoDialog::m_FromLength
Referenced by OnText_ToLength(), EffectChangeTempo::PromptUser(), TransferDataToWindow(), and Update_Text_ToLength().
double ChangeTempoDialog::m_PercentChange
Referenced by OnPreview(), OnSlider_PercentChange(), OnText_PercentChange(), OnText_ToBPM(), OnText_ToLength(), EffectChangeTempo::PromptUser(), TransferDataFromWindow(), Update_Slider_PercentChange(), Update_Text_PercentChange(), Update_Text_ToBPM(), and Update_Text_ToLength().
wxSlider* ChangeTempoDialog::m_pSlider_PercentChange [private]
Referenced by OnSlider_PercentChange(), PopulateOrExchange(), and Update_Slider_PercentChange().
wxTextCtrl* ChangeTempoDialog::m_pTextCtrl_FromBPM [private]
Referenced by OnText_FromBPM(), PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
wxTextCtrl* ChangeTempoDialog::m_pTextCtrl_FromLength [private]
Referenced by PopulateOrExchange(), and TransferDataToWindow().
wxTextCtrl* ChangeTempoDialog::m_pTextCtrl_PercentChange [private]
Referenced by OnText_PercentChange(), PopulateOrExchange(), TransferDataFromWindow(), and Update_Text_PercentChange().
wxTextCtrl* ChangeTempoDialog::m_pTextCtrl_ToBPM [private]
Referenced by OnText_ToBPM(), PopulateOrExchange(), TransferDataFromWindow(), TransferDataToWindow(), and Update_Text_ToBPM().
wxTextCtrl* ChangeTempoDialog::m_pTextCtrl_ToLength [private]
Referenced by OnText_ToLength(), PopulateOrExchange(), TransferDataFromWindow(), TransferDataToWindow(), and Update_Text_ToLength().
unsigned int ChangeTempoDialog::m_ToBPM
Referenced by OnText_ToBPM(), EffectChangeTempo::PromptUser(), TransferDataFromWindow(), TransferDataToWindow(), and Update_Text_ToBPM().
double ChangeTempoDialog::m_ToLength
Referenced by OnText_ToLength(), EffectChangeTempo::PromptUser(), TransferDataFromWindow(), TransferDataToWindow(), and Update_Text_ToLength().
EffectChangeTempo* ChangeTempoDialog::mEffect [private]
Referenced by OnPreview().
The documentation for this class was generated from the following files:
ChangeTempo.h
ChangeTempo.cpp