Audacity: CommandImplementation Class Reference
CommandImplementation Class Reference
#include <Command.h>
Public Member Functions
void Progress (double completed)
void Status (wxString status)
void Error (wxString message)
CommandImplementation (CommandType &type, CommandOutputTarget *output)
virtual ~CommandImplementation ()
wxString GetName ()
An instance method for getting the command name (for consistency).
CommandSignature & GetSignature ()
Get the signature of the command.
bool SetParameter (const wxString &paramName, const wxVariant &paramValue)
virtual bool Apply (CommandExecutionContext context)
Protected Member Functions
void TypeCheck (const wxString &typeName, const wxString &paramName, const wxVariant &param)
void CheckParam (const wxString &paramName)
bool GetBool (const wxString &paramName)
long GetLong (const wxString &paramName)
double GetDouble (const wxString &paramName)
wxString GetString (const wxString &paramName)
Protected Attributes
CommandOutputTarget * mOutput
Private Member Functions
bool Valid (const wxString &paramName, const wxVariant &paramValue)
Private Attributes
CommandType & mType
ParamValueMap mParams
Constructor & Destructor Documentation
CommandImplementation::CommandImplementation (CommandType & type, CommandOutputTarget * output)
Constructor should not be called directly; only by a factory which ensures name and params are set appropriately for the command.
CommandImplementation::~CommandImplementation () [virtual]
References mOutput.
Member Function Documentation
bool CommandImplementation::Apply (CommandExecutionContext context) [virtual]
Actually carry out the command. Return true if successful and false otherwise.
Implements Command.
Reimplemented in BatchEvalCommand, CompareAudioCommand, ExecMenuCommand, GetAllMenuCommands, GetProjectInfoCommand, GetTrackInfoCommand, HelpCommand, ImportCommand, ExportCommand, MessageCommand, GetPreferenceCommand, SetPreferenceCommand, ScreenshotCommand, SelectCommand, SetProjectInfoCommand, and SetTrackInfoCommand.
void CommandImplementation::CheckParam (const wxString & paramName) [protected]
References GetName(), and mParams.
Referenced by GetBool(), GetDouble(), GetLong(), and GetString().
void CommandImplementation::Error (wxString message) [virtual]
Implements Command.
References CommandOutputTarget::Error(), and mOutput.
Referenced by SetTrackInfoCommand::Apply(), SetProjectInfoCommand::Apply(), SelectCommand::Apply(), ExportCommand::Apply(), HelpCommand::Apply(), GetTrackInfoCommand::Apply(), GetProjectInfoCommand::Apply(), CompareAudioCommand::GetSelection(), and SetParameter().
bool CommandImplementation::GetBool (const wxString & paramName) [protected]
References CheckParam(), mParams, and TypeCheck().
Referenced by GetAllMenuCommands::Apply().
double CommandImplementation::GetDouble (const wxString & paramName) [protected]
References CheckParam(), mParams, and TypeCheck().
Referenced by SelectCommand::Apply(), and CompareAudioCommand::Apply().
long CommandImplementation::GetLong (const wxString & paramName) [protected]
References CheckParam(), mParams, and TypeCheck().
Referenced by SetTrackInfoCommand::Apply(), SelectCommand::Apply(), ExportCommand::Apply(), and GetTrackInfoCommand::Apply().
wxString CommandImplementation::GetName () [virtual]
An instance method for getting the command name (for consistency).
Get the name of the command.
Implements Command.
References CommandType::GetName(), and mType.
Referenced by CheckParam(), SetParameter(), and TypeCheck().
CommandSignature & CommandImplementation::GetSignature () [virtual]
Get the signature of the command.
Implements Command.
References CommandType::GetSignature(), and mType.
wxString CommandImplementation::GetString (const wxString & paramName) [protected]
References CheckParam(), mParams, and TypeCheck().
Referenced by SetTrackInfoCommand::Apply(), SetProjectInfoCommand::Apply(), SelectCommand::Apply(), ScreenshotCommand::Apply(), SetPreferenceCommand::Apply(), GetPreferenceCommand::Apply(), MessageCommand::Apply(), ExportCommand::Apply(), ImportCommand::Apply(), HelpCommand::Apply(), GetTrackInfoCommand::Apply(), GetProjectInfoCommand::Apply(), ExecMenuCommand::Apply(), and BatchEvalCommand::Apply().
void CommandImplementation::Progress (double completed) [virtual]
Implements Command.
References mOutput, and CommandOutputTarget::Progress().
Referenced by CompareAudioCommand::Apply().
bool CommandImplementation::SetParameter (const wxString & paramName, const wxVariant & paramValue) [virtual]
Attempt to one of the command's parameters to a particular value. (Note: wxVariant is reference counted)
Reimplemented from Command.
References Error(), Validator::GetConverted(), Validator::GetDescription(), GetName(), CommandType::GetSignature(), CommandSignature::GetValidator(), mParams, mType, and Validator::Validate().
Referenced by ScreenFrame::DoCapture(), ScreenFrame::OnToggleBackgroundBlue(), and ScreenFrame::OnToggleBackgroundWhite().
void CommandImplementation::Status (wxString status) [virtual]
Implements Command.
References mOutput, and CommandOutputTarget::Status().
Referenced by SelectCommand::Apply(), GetPreferenceCommand::Apply(), MessageCommand::Apply(), ExportCommand::Apply(), HelpCommand::Apply(), GetTrackInfoCommand::Apply(), GetProjectInfoCommand::Apply(), GetAllMenuCommands::Apply(), CompareAudioCommand::Apply(), CompareAudioCommand::GetSelection(), GetTrackInfoCommand::SendBooleanStatus(), GetProjectInfoCommand::SendFocusedTrackIndex(), GetProjectInfoCommand::SendNumberOfTracks(), and GetProjectInfoCommand::SendTracksInfo().
void CommandImplementation::TypeCheck (const wxString & typeName, const wxString & paramName, const wxVariant & param) [protected]
References GetName().
Referenced by GetBool(), GetDouble(), GetLong(), and GetString().
bool CommandImplementation::Valid (const wxString & paramName, const wxVariant & paramValue) [private]
Using the command signature, looks up a possible parameter value and checks whether it passes the validator.
Member Data Documentation
CommandOutputTarget* CommandImplementation::mOutput [protected]
Referenced by ScreenshotCommand::Capture(), Error(), Progress(), Status(), and ~CommandImplementation().
ParamValueMap CommandImplementation::mParams [private]
Referenced by CheckParam(), GetBool(), GetDouble(), GetLong(), GetString(), and SetParameter().
CommandType& CommandImplementation::mType [private]
Referenced by GetName(), GetSignature(), and SetParameter().
The documentation for this class was generated from the following files:
Command.h
Command.cpp