Audacity: ChangePitchDialog Class Reference
ChangePitchDialog Class Reference
#include <ChangePitch.h>
Public Member Functions
ChangePitchDialog (EffectChangePitch *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
int m_FromPitchIndex
bool m_bWantPitchDown
int m_ToPitchIndex
double m_SemitonesChange
float m_FromFrequency
float m_ToFrequency
double m_PercentChange
Private Member Functions
void Calc_ToFrequency ()
void Calc_ToPitchIndex ()
void Calc_SemitonesChange_fromPitches ()
void Calc_SemitonesChange_fromPercentChange ()
void Calc_PercentChange ()
void OnChoice_FromPitch (wxCommandEvent &event)
void OnRadioButton_PitchUpDown (wxCommandEvent &event)
void OnChoice_ToPitch (wxCommandEvent &event)
void OnText_SemitonesChange (wxCommandEvent &event)
void OnText_FromFrequency (wxCommandEvent &event)
void OnText_ToFrequency (wxCommandEvent &event)
void OnText_PercentChange (wxCommandEvent &event)
void OnSlider_PercentChange (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
void Update_RadioButton_PitchUpDown ()
void Update_Choice_ToPitch ()
void Update_Text_SemitonesChange ()
void Update_Text_ToFrequency ()
void Update_Text_PercentChange ()
void Update_Slider_PercentChange ()
Private Attributes
EffectChangePitch * mEffect
bool m_bLoopDetect
wxChoice * m_pChoice_FromPitch
wxRadioButton * m_pRadioButton_PitchUp
wxRadioButton * m_pRadioButton_PitchDown
wxChoice * m_pChoice_ToPitch
wxTextCtrl * m_pTextCtrl_SemitonesChange
wxTextCtrl * m_pTextCtrl_FromFrequency
wxTextCtrl * m_pTextCtrl_ToFrequency
wxTextCtrl * m_pTextCtrl_PercentChange
wxSlider * m_pSlider_PercentChange
Constructor & Destructor Documentation
ChangePitchDialog::ChangePitchDialog (EffectChangePitch * effect, wxWindow * parent)
Member Function Documentation
void ChangePitchDialog::Calc_PercentChange () [private]
References m_PercentChange, and m_SemitonesChange.
Referenced by OnChoice_ToPitch(), OnRadioButton_PitchUpDown(), and OnText_SemitonesChange().
void ChangePitchDialog::Calc_SemitonesChange_fromPercentChange () [private]
References m_PercentChange, and m_SemitonesChange.
Referenced by OnSlider_PercentChange(), OnText_PercentChange(), and OnText_ToFrequency().
void ChangePitchDialog::Calc_SemitonesChange_fromPitches () [private]
References m_bWantPitchDown, m_FromPitchIndex, m_SemitonesChange, and m_ToPitchIndex.
Referenced by OnChoice_ToPitch(), and OnRadioButton_PitchUpDown().
void ChangePitchDialog::Calc_ToFrequency () [private]
References m_FromFrequency, m_PercentChange, and m_ToFrequency.
Referenced by OnChoice_ToPitch(), OnRadioButton_PitchUpDown(), OnSlider_PercentChange(), OnText_FromFrequency(), OnText_PercentChange(), and OnText_SemitonesChange().
void ChangePitchDialog::Calc_ToPitchIndex () [private]
References m_bWantPitchDown, m_FromPitchIndex, m_SemitonesChange, and m_ToPitchIndex.
Referenced by OnChoice_FromPitch(), OnSlider_PercentChange(), OnText_FromFrequency(), OnText_PercentChange(), OnText_SemitonesChange(), and OnText_ToFrequency().
void ChangePitchDialog::OnChoice_FromPitch (wxCommandEvent & event) [private]
References Calc_ToPitchIndex(), m_bLoopDetect, m_FromPitchIndex, m_pChoice_FromPitch, and Update_Choice_ToPitch().
void ChangePitchDialog::OnChoice_ToPitch (wxCommandEvent & event) [private]
References Calc_PercentChange(), Calc_SemitonesChange_fromPitches(), Calc_ToFrequency(), m_bLoopDetect, m_pChoice_ToPitch, m_ToPitchIndex, Update_Slider_PercentChange(), Update_Text_PercentChange(), Update_Text_SemitonesChange(), and Update_Text_ToFrequency().
void ChangePitchDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References m_PercentChange, EffectChangePitch::m_SemitonesChange, m_SemitonesChange, mEffect, Effect::Preview(), TransferDataFromWindow(), and Update_Text_PercentChange().
void ChangePitchDialog::OnRadioButton_PitchUpDown (wxCommandEvent & event) [private]
References Calc_PercentChange(), Calc_SemitonesChange_fromPitches(), Calc_ToFrequency(), m_bLoopDetect, m_bWantPitchDown, m_pRadioButton_PitchUp, Update_Slider_PercentChange(), Update_Text_PercentChange(), Update_Text_SemitonesChange(), and Update_Text_ToFrequency().
void ChangePitchDialog::OnSlider_PercentChange (wxCommandEvent & event) [private]
References Calc_SemitonesChange_fromPercentChange(), Calc_ToFrequency(), Calc_ToPitchIndex(), m_bLoopDetect, m_bWantPitchDown, m_FromFrequency, m_PercentChange, m_pSlider_PercentChange, m_ToFrequency, PERCENTCHANGE_SLIDER_WARP, Update_Choice_ToPitch(), Update_RadioButton_PitchUpDown(), Update_Text_PercentChange(), Update_Text_SemitonesChange(), and Update_Text_ToFrequency().
void ChangePitchDialog::OnText_FromFrequency (wxCommandEvent & event) [private]
References Calc_ToFrequency(), Calc_ToPitchIndex(), FreqToMIDInoteNumber(), m_bLoopDetect, m_bWantPitchDown, m_FromFrequency, m_FromPitchIndex, m_pTextCtrl_FromFrequency, m_ToFrequency, PitchIndex(), Update_Choice_ToPitch(), Update_RadioButton_PitchUpDown(), and Update_Text_ToFrequency().
void ChangePitchDialog::OnText_PercentChange (wxCommandEvent & event) [private]
References Calc_SemitonesChange_fromPercentChange(), Calc_ToFrequency(), Calc_ToPitchIndex(), m_bLoopDetect, m_bWantPitchDown, m_FromFrequency, m_PercentChange, m_pTextCtrl_PercentChange, m_ToFrequency, Update_Choice_ToPitch(), Update_RadioButton_PitchUpDown(), Update_Slider_PercentChange(), Update_Text_SemitonesChange(), and Update_Text_ToFrequency().
void ChangePitchDialog::OnText_SemitonesChange (wxCommandEvent & event) [private]
References Calc_PercentChange(), Calc_ToFrequency(), Calc_ToPitchIndex(), m_bLoopDetect, m_bWantPitchDown, m_FromFrequency, m_pTextCtrl_SemitonesChange, m_SemitonesChange, m_ToFrequency, Update_Choice_ToPitch(), Update_RadioButton_PitchUpDown(), Update_Slider_PercentChange(), Update_Text_PercentChange(), and Update_Text_ToFrequency().
void ChangePitchDialog::OnText_ToFrequency (wxCommandEvent & event) [private]
References Calc_SemitonesChange_fromPercentChange(), Calc_ToPitchIndex(), m_bLoopDetect, m_bWantPitchDown, m_FromFrequency, m_PercentChange, m_pTextCtrl_ToFrequency, m_ToFrequency, Update_Choice_ToPitch(), Update_RadioButton_PitchUpDown(), Update_Slider_PercentChange(), Update_Text_PercentChange(), and Update_Text_SemitonesChange().
void ChangePitchDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddChoice(), ShuttleGuiBase::AddPrompt(), ShuttleGuiBase::AddRadioButton(), ShuttleGuiBase::AddRadioButtonToGroup(), ShuttleGuiBase::AddSlider(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddUnits(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), ShuttleGui::Id(), ID_CHOICE_FROMPITCH, ID_CHOICE_TOPITCH, ID_RADIOBUTTON_PITCHUPDOWN, ID_SLIDER_PERCENTCHANGE, ID_TEXT_FROMFREQUENCY, ID_TEXT_PERCENTCHANGE, ID_TEXT_SEMITONESCHANGE, ID_TEXT_TOFREQUENCY, m_pChoice_FromPitch, m_pChoice_ToPitch, m_pRadioButton_PitchDown, m_pRadioButton_PitchUp, m_pSlider_PercentChange, m_pTextCtrl_FromFrequency, m_pTextCtrl_PercentChange, m_pTextCtrl_SemitonesChange, m_pTextCtrl_ToFrequency, PERCENTCHANGE_MAX, PERCENTCHANGE_MIN, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::StartVerticalLay().
bool ChangePitchDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References m_bWantPitchDown, m_FromFrequency, m_FromPitchIndex, m_pChoice_FromPitch, m_pChoice_ToPitch, m_PercentChange, m_pRadioButton_PitchUp, m_pTextCtrl_FromFrequency, m_pTextCtrl_PercentChange, m_pTextCtrl_SemitonesChange, m_pTextCtrl_ToFrequency, m_SemitonesChange, m_ToFrequency, and m_ToPitchIndex.
Referenced by OnPreview().
bool ChangePitchDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References m_bLoopDetect, m_FromFrequency, m_FromPitchIndex, m_pChoice_FromPitch, m_pTextCtrl_FromFrequency, Update_Choice_ToPitch(), Update_RadioButton_PitchUpDown(), Update_Slider_PercentChange(), Update_Text_PercentChange(), Update_Text_SemitonesChange(), and Update_Text_ToFrequency().
void ChangePitchDialog::Update_Choice_ToPitch () [private]
References m_pChoice_ToPitch, and m_ToPitchIndex.
Referenced by OnChoice_FromPitch(), OnSlider_PercentChange(), OnText_FromFrequency(), OnText_PercentChange(), OnText_SemitonesChange(), OnText_ToFrequency(), and TransferDataToWindow().
void ChangePitchDialog::Update_RadioButton_PitchUpDown () [private]
References m_bWantPitchDown, m_pRadioButton_PitchDown, and m_pRadioButton_PitchUp.
Referenced by OnSlider_PercentChange(), OnText_FromFrequency(), OnText_PercentChange(), OnText_SemitonesChange(), OnText_ToFrequency(), and TransferDataToWindow().
void ChangePitchDialog::Update_Slider_PercentChange () [private]
References m_PercentChange, m_pSlider_PercentChange, and PERCENTCHANGE_SLIDER_WARP.
Referenced by OnChoice_ToPitch(), OnRadioButton_PitchUpDown(), OnText_PercentChange(), OnText_SemitonesChange(), OnText_ToFrequency(), and TransferDataToWindow().
void ChangePitchDialog::Update_Text_PercentChange () [private]
References m_PercentChange, and m_pTextCtrl_PercentChange.
Referenced by OnChoice_ToPitch(), OnPreview(), OnRadioButton_PitchUpDown(), OnSlider_PercentChange(), OnText_SemitonesChange(), OnText_ToFrequency(), and TransferDataToWindow().
void ChangePitchDialog::Update_Text_SemitonesChange () [private]
References m_pTextCtrl_SemitonesChange, and m_SemitonesChange.
Referenced by OnChoice_ToPitch(), OnRadioButton_PitchUpDown(), OnSlider_PercentChange(), OnText_PercentChange(), OnText_ToFrequency(), and TransferDataToWindow().
void ChangePitchDialog::Update_Text_ToFrequency () [private]
References m_pTextCtrl_ToFrequency, and m_ToFrequency.
Referenced by OnChoice_ToPitch(), OnRadioButton_PitchUpDown(), OnSlider_PercentChange(), OnText_FromFrequency(), OnText_PercentChange(), OnText_SemitonesChange(), and TransferDataToWindow().
Member Data Documentation
bool ChangePitchDialog::m_bLoopDetect [private]
Referenced by OnChoice_FromPitch(), OnChoice_ToPitch(), OnRadioButton_PitchUpDown(), OnSlider_PercentChange(), OnText_FromFrequency(), OnText_PercentChange(), OnText_SemitonesChange(), OnText_ToFrequency(), and TransferDataToWindow().
bool ChangePitchDialog::m_bWantPitchDown
Referenced by Calc_SemitonesChange_fromPitches(), Calc_ToPitchIndex(), OnRadioButton_PitchUpDown(), OnSlider_PercentChange(), OnText_FromFrequency(), OnText_PercentChange(), OnText_SemitonesChange(), OnText_ToFrequency(), EffectChangePitch::PromptUser(), TransferDataFromWindow(), and Update_RadioButton_PitchUpDown().
float ChangePitchDialog::m_FromFrequency
Referenced by Calc_ToFrequency(), OnSlider_PercentChange(), OnText_FromFrequency(), OnText_PercentChange(), OnText_SemitonesChange(), OnText_ToFrequency(), EffectChangePitch::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
int ChangePitchDialog::m_FromPitchIndex
Referenced by Calc_SemitonesChange_fromPitches(), Calc_ToPitchIndex(), OnChoice_FromPitch(), OnText_FromFrequency(), EffectChangePitch::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
wxChoice* ChangePitchDialog::m_pChoice_FromPitch [private]
Referenced by OnChoice_FromPitch(), PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
wxChoice* ChangePitchDialog::m_pChoice_ToPitch [private]
Referenced by OnChoice_ToPitch(), PopulateOrExchange(), TransferDataFromWindow(), and Update_Choice_ToPitch().
double ChangePitchDialog::m_PercentChange
Referenced by Calc_PercentChange(), Calc_SemitonesChange_fromPercentChange(), Calc_ToFrequency(), OnPreview(), OnSlider_PercentChange(), OnText_PercentChange(), OnText_ToFrequency(), EffectChangePitch::PromptUser(), TransferDataFromWindow(), Update_Slider_PercentChange(), and Update_Text_PercentChange().
wxRadioButton* ChangePitchDialog::m_pRadioButton_PitchDown [private]
Referenced by PopulateOrExchange(), and Update_RadioButton_PitchUpDown().
wxRadioButton* ChangePitchDialog::m_pRadioButton_PitchUp [private]
Referenced by OnRadioButton_PitchUpDown(), PopulateOrExchange(), TransferDataFromWindow(), and Update_RadioButton_PitchUpDown().
wxSlider* ChangePitchDialog::m_pSlider_PercentChange [private]
Referenced by OnSlider_PercentChange(), PopulateOrExchange(), and Update_Slider_PercentChange().
wxTextCtrl* ChangePitchDialog::m_pTextCtrl_FromFrequency [private]
Referenced by OnText_FromFrequency(), PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
wxTextCtrl* ChangePitchDialog::m_pTextCtrl_PercentChange [private]
Referenced by OnText_PercentChange(), PopulateOrExchange(), TransferDataFromWindow(), and Update_Text_PercentChange().
wxTextCtrl* ChangePitchDialog::m_pTextCtrl_SemitonesChange [private]
Referenced by OnText_SemitonesChange(), PopulateOrExchange(), TransferDataFromWindow(), and Update_Text_SemitonesChange().
wxTextCtrl* ChangePitchDialog::m_pTextCtrl_ToFrequency [private]
Referenced by OnText_ToFrequency(), PopulateOrExchange(), TransferDataFromWindow(), and Update_Text_ToFrequency().
double ChangePitchDialog::m_SemitonesChange
Referenced by Calc_PercentChange(), Calc_SemitonesChange_fromPercentChange(), Calc_SemitonesChange_fromPitches(), Calc_ToPitchIndex(), OnPreview(), OnText_SemitonesChange(), EffectChangePitch::PromptUser(), TransferDataFromWindow(), and Update_Text_SemitonesChange().
float ChangePitchDialog::m_ToFrequency
Referenced by Calc_ToFrequency(), OnSlider_PercentChange(), OnText_FromFrequency(), OnText_PercentChange(), OnText_SemitonesChange(), OnText_ToFrequency(), EffectChangePitch::PromptUser(), TransferDataFromWindow(), and Update_Text_ToFrequency().
int ChangePitchDialog::m_ToPitchIndex
Referenced by Calc_SemitonesChange_fromPitches(), Calc_ToPitchIndex(), OnChoice_ToPitch(), EffectChangePitch::PromptUser(), TransferDataFromWindow(), and Update_Choice_ToPitch().
EffectChangePitch* ChangePitchDialog::mEffect [private]
Referenced by OnPreview().
The documentation for this class was generated from the following files:
ChangePitch.h
ChangePitch.cpp