Audacity: Meter Class Reference
Meter Class Reference
VU Meter, for displaying recording/playback level.
#include <Meter.h>
Public Types
enum Style {
HorizontalStereo, VerticalStereo, VerticalMulti, Equalizer,
Waveform, MixerTrackCluster
}
Public Member Functions
Meter (wxWindow *parent, wxWindowID id, bool isInput, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, Style style=HorizontalStereo, float fDecayRate=60.0f)
~Meter ()
void UpdatePrefs ()
void Clear ()
Style GetStyle ()
void SetStyle (Style newStyle)
void Reset (double sampleRate, bool resetClipping)
This method is thread-safe! Feel free to call from a different thread (like from an audio I/O callback).
void UpdateDisplay (int numChannels, int numFrames, float *sampleData)
Update the meters with a block of audio data.
void UpdateDisplay (int numChannels, int numFrames, float *maxLeft, float *rmsLeft, float *maxRight, float *rmsRight, const sampleCount kSampleCount)
bool IsMeterDisabled ()
Find out if the level meter is disabled or not.
float GetMaxPeak ()
double ToLinearIfDB (double value)
void OnErase (wxEraseEvent &evt)
void OnPaint (wxPaintEvent &evt)
void OnSize (wxSizeEvent &evt)
void OnMouse (wxMouseEvent &evt)
void OnMeterUpdate (wxTimerEvent &evt)
void HandlePaint (wxDC &dc)
void HandleLayout ()
void OnDisableMeter (wxCommandEvent &evt)
void OnHorizontal (wxCommandEvent &evt)
void OnVertical (wxCommandEvent &evt)
void OnMulti (wxCommandEvent &evt)
void OnEqualizer (wxCommandEvent &evt)
void OnWaveform (wxCommandEvent &evt)
void OnLinear (wxCommandEvent &evt)
void OnDB (wxCommandEvent &evt)
void OnClip (wxCommandEvent &evt)
void OnMonitor (wxCommandEvent &evt)
void OnFloat (wxCommandEvent &evt)
void OnPreferences (wxCommandEvent &evt)
bool IsClipping ()
void StartMonitoring ()
Private Member Functions
void DrawMeterBar (wxDC &dc, MeterBar *meterBar)
void ResetBar (MeterBar *bar, bool resetClipping)
void RepaintBarsNow ()
void CreateIcon (int aquaOffset)
wxFont GetFont ()
Private Attributes
MeterUpdateQueue mQueue
wxTimer mTimer
int mWidth
int mHeight
bool mIsInput
Style mStyle
Style mSavedStyle
bool mDB
int mDBRange
bool mDecay
float mDecayRate
bool mClip
int mNumPeakSamplesToClip
double mPeakHoldDuration
double mT
double mRate
long mMeterRefreshRate
long mMeterDisabled
int mNumBars
MeterBar mBar [kMaxMeterBars]
bool mLayoutValid
wxBitmap * mBitmap
wxRect mMenuRect
wxPoint mIconPos
wxPoint mLeftTextPos
wxPoint mRightTextPos
wxSize mLeftSize
wxSize mRightSize
wxBitmap * mIcon
wxPen mPen
wxPen mLightPen
wxPen mSavedLightPen
wxPen mDarkPen
wxPen mSavedDarkPen
wxPen mDisabledPen
wxPen mPeakPeakPen
wxBrush mBrush
wxBrush mRMSBrush
wxBrush mClipBrush
wxBrush mBkgndBrush
wxBrush mSavedBkgndBrush
wxBrush mSavedBrush
wxBrush mSavedRMSBrush
wxBrush mDisabledBkgndBrush
wxRect mAllBarsRect
Ruler mRuler
Detailed Description
VU Meter, for displaying recording/playback level.
This is a bunch of common code that can display many different forms of VU meters and other displays.
But note that a lot of later code here assumes these are MeterToolBar meters, e.g., Meter::StartMonitoring, so these are not as generic/common as originally intended.
Member Enumeration Documentation
enum Meter::Style
Enumerator:
HorizontalStereo
VerticalStereo
VerticalMulti
Equalizer
Waveform
MixerTrackCluster
Constructor & Destructor Documentation
Meter::Meter (wxWindow * parent, wxWindowID id, bool isInput, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, Style style = HorizontalStereo, float fDecayRate = 60.0f)
References ThemeBase::Colour(), kMaxMeterBars, and theTheme.
Meter::~Meter ()
References gAudioIO, AudioIO::IsMonitoring(), mBitmap, mIcon, and AudioIO::StopStream().
Member Function Documentation
void Meter::Clear ()
References MeterUpdateQueue::Clear(), and mQueue.
Referenced by MeterToolBar::Clear().
void Meter::CreateIcon (int aquaOffset) [private]
Todo:
Remove wasteful delete/new pair. It is done in every call to layout.
JKC: !!!! If you pass theTheme.Bitmap(bmpMic) you get a white rather than a black mic. Weird behaviour in wxWidgets, I guess.
References ThemeBase::Image(), mIcon, mIsInput, and theTheme.
Referenced by HandleLayout().
void Meter::DrawMeterBar (wxDC & dc, MeterBar * meterBar) [private]
References AColor::Bevel(), MeterBar::clipping, AColor::Line(), mBkgndBrush, mBrush, mClip, mClipBrush, mDarkPen, mLightPen, mPeakPeakPen, mPen, mRMSBrush, MeterBar::peak, MeterBar::peakHold, MeterBar::peakPeakHold, MeterBar::r, MeterBar::rClip, MeterBar::rms, and MeterBar::vert.
Referenced by HandlePaint(), and RepaintBarsNow().
wxFont Meter::GetFont () [private]
Referenced by HandlePaint().
float Meter::GetMaxPeak ()
References mBar, and mNumBars.
Referenced by audacityAudioCallback().
Style Meter::GetStyle () [inline]
References mStyle.
void Meter::HandleLayout ()
References CreateIcon(), HorizontalStereo, intmax(), intmin(), Ruler::LinearDBFormat, mAllBarsRect, mBar, mClip, mDB, mDBRange, mHeight, mIcon, mIconPos, mLayoutValid, mLeftSize, mLeftTextPos, mMenuRect, mNumBars, mRightSize, mRightTextPos, mRuler, mStyle, mWidth, Ruler::OfflimitsPixels(), MeterBar::r, MeterBar::rClip, Ruler::RealFormat, ResetBar(), Ruler::SetBounds(), Ruler::SetFlip(), Ruler::SetFormat(), Ruler::SetLabelEdges(), Ruler::SetOrientation(), Ruler::SetRange(), MeterBar::vert, VerticalStereo, and Waveform.
Referenced by HandlePaint(), and MeterToolBar::UpdatePrefs().
void Meter::HandlePaint (wxDC & dc)
References AColor::Arrow(), AColor::Bevel(), Ruler::Draw(), DrawMeterBar(), GetFont(), HandleLayout(), mBar, mBkgndBrush, mHeight, mIcon, mIconPos, mLayoutValid, mLeftSize, mLeftTextPos, mMenuRect, mMeterDisabled, mNumBars, mRightSize, mRightTextPos, mRuler, mStyle, mWidth, and VerticalStereo.
Referenced by OnPaint().
bool Meter::IsClipping ()
References kMaxMeterBars, and mBar.
bool Meter::IsMeterDisabled ()
Find out if the level meter is disabled or not.
This method is thread-safe! Feel free to call from a different thread (like from an audio I/O callback).
References mMeterDisabled.
Referenced by audacityAudioCallback().
void Meter::OnClip (wxCommandEvent & evt)
void Meter::OnDB (wxCommandEvent & evt)
References mDB, and mLayoutValid.
void Meter::OnDisableMeter (wxCommandEvent & evt)
References gAudioIO, gPrefs, AudioIO::IsMonitoring(), mBkgndBrush, mBrush, mDarkPen, mDisabledBkgndBrush, mDisabledPen, mIsInput, mLayoutValid, mLightPen, mMeterDisabled, mRMSBrush, mSavedBkgndBrush, mSavedBrush, mSavedDarkPen, mSavedLightPen, mSavedRMSBrush, and AudioIO::StopStream().
Referenced by StartMonitoring().
void Meter::OnEqualizer (wxCommandEvent & evt)
References Equalizer, and SetStyle().
void Meter::OnErase (wxEraseEvent & evt)
void Meter::OnFloat (wxCommandEvent & evt)
void Meter::OnHorizontal (wxCommandEvent & evt)
References HorizontalStereo, and SetStyle().
void Meter::OnLinear (wxCommandEvent & evt)
References mDB, and mLayoutValid.
void Meter::OnMeterUpdate (wxTimerEvent & evt)
References MeterBar::clipping, MeterUpdateMsg::clipping, floatMax(), gAudioIO, MeterUpdateQueue::Get(), MeterUpdateMsg::headPeakCount, MeterBar::isclipping, mBar, mDB, mDBRange, mDecay, mDecayRate, mIsInput, mMeterDisabled, mNumBars, mNumPeakSamplesToClip, mPeakHoldDuration, mQueue, mRate, mT, MeterUpdateMsg::numFrames, MeterUpdateMsg::peak, MeterBar::peak, MeterBar::peakHold, MeterBar::peakHoldTime, MeterBar::peakPeakHold, RepaintBarsNow(), MeterUpdateMsg::rms, MeterBar::rms, MeterUpdateMsg::tailPeakCount, and MeterBar::tailPeakCount.
void Meter::OnMonitor (wxCommandEvent & evt)
References StartMonitoring().
void Meter::OnMouse (wxMouseEvent & evt)
References gAudioIO, GetActiveProject(), gPrefs, AudioIO::IsMonitoring(), mDB, mIsInput, mMenuRect, mMeterDisabled, mStyle, OnAutomatedInputLevelAdjustmentID, OnPreferencesID, StartMonitoring(), AudacityProject::TP_DisplayStatusMessage(), and VerticalStereo.
void Meter::OnMulti (wxCommandEvent & evt)
References SetStyle(), and VerticalMulti.
void Meter::OnPaint (wxPaintEvent & evt)
References HandlePaint(), mBitmap, mHeight, and mWidth.
void Meter::OnPreferences (wxCommandEvent & evt)
References gPrefs, mMeterRefreshRate, and mTimer.
void Meter::OnSize (wxSizeEvent & evt)
References mBitmap, mHeight, mLayoutValid, and mWidth.
void Meter::OnVertical (wxCommandEvent & evt)
References SetStyle(), and VerticalStereo.
void Meter::OnWaveform (wxCommandEvent & evt)
References SetStyle(), and Waveform.
void Meter::RepaintBarsNow () [private]
References DrawMeterBar(), mAllBarsRect, mBar, mBitmap, mHeight, mLayoutValid, mNumBars, and mWidth.
Referenced by OnMeterUpdate().
void Meter::Reset (double sampleRate, bool resetClipping)
This method is thread-safe! Feel free to call from a different thread (like from an audio I/O callback).
References MeterUpdateQueue::Get(), kMaxMeterBars, mBar, mLayoutValid, mMeterRefreshRate, mQueue, mRate, mT, mTimer, and ResetBar().
Referenced by MixerTrackCluster::ResetMeter(), AudioIO::SetMeters(), and AudioIO::StopStream().
void Meter::ResetBar (MeterBar * bar, bool resetClipping) [private]
References MeterBar::clipping, MeterBar::isclipping, MeterBar::peak, MeterBar::peakHold, MeterBar::peakHoldTime, MeterBar::peakPeakHold, MeterBar::rms, and MeterBar::tailPeakCount.
Referenced by HandleLayout(), and Reset().
void Meter::SetStyle (Meter::Style newStyle)
References mLayoutValid, and mStyle.
Referenced by OnEqualizer(), OnHorizontal(), OnMulti(), MeterToolBar::OnSize(), OnVertical(), and OnWaveform().
void Meter::StartMonitoring ()
References gAudioIO, GetActiveProject(), MeterToolBar::GetMeters(), AudacityProject::GetMeterToolBar(), AudacityProject::GetRate(), AudioIO::IsMonitoring(), mMeterDisabled, OnDisableMeter(), AudioIO::SetMeters(), AudioIO::StartMonitoring(), and AudioIO::StopStream().
Referenced by OnMonitor(), OnMouse(), and MeterToolBar::StartMonitoring().
double Meter::ToLinearIfDB (double value)
References mDB, and mDBRange.
void Meter::UpdateDisplay (int numChannels, int numFrames, float * maxLeft, float * rmsLeft, float * maxRight, float * rmsRight, const sampleCount kSampleCount)
References MeterUpdateMsg::clipping, floatMax(), MeterUpdateMsg::headPeakCount, intmin(), MAX_AUDIO, mDB, mDBRange, mNumBars, mNumPeakSamplesToClip, mQueue, MeterUpdateMsg::numFrames, MeterUpdateMsg::peak, MeterUpdateQueue::Put(), MeterUpdateMsg::rms, MeterUpdateMsg::tailPeakCount, and ToDB().
void Meter::UpdateDisplay (int numChannels, int numFrames, float * sampleData)
Update the meters with a block of audio data.
Process the supplied block of audio data, extracting the peak and RMS levels to send to the meter. Also record runs of clipped samples to detect clipping that lies on block boundaries. This method is thread-safe! Feel free to call from a different thread (like from an audio I/O callback).
First overload:
Parameters:
numChannels The number of channels of audio being played back or recorded.
numFrames The number of frames (samples) in this data block. It is assumed that there are the same number of frames in each channel.
sampleData The audio data itself, as interleaved samples. So indexing through the array we get the first sample of channel, first sample of channel 2 etc up to the first sample of channel (numChannels), then the second sample of channel 1, second sample of channel 2, and so to the second sample of channel (numChannels). The last sample in the array will be the (numFrames) sample for channel (numChannels).
The second overload is for ease of use in MixerBoard.
References MeterUpdateMsg::clipping, floatMax(), MeterUpdateMsg::headPeakCount, intmin(), MAX_AUDIO, mDB, mDBRange, mNumBars, mNumPeakSamplesToClip, mQueue, MeterUpdateMsg::numFrames, MeterUpdateMsg::peak, MeterUpdateQueue::Put(), MeterUpdateMsg::rms, MeterUpdateMsg::tailPeakCount, and ToDB().
Referenced by audacityAudioCallback(), and MixerTrackCluster::UpdateMeter().
void Meter::UpdatePrefs ()
References ENV_DB_RANGE, gPrefs, mDBRange, mIsInput, mMeterDisabled, mMeterRefreshRate, and mStyle.
Referenced by MeterToolBar::UpdatePrefs().
Member Data Documentation
wxRect Meter::mAllBarsRect [private]
Referenced by HandleLayout(), and RepaintBarsNow().
MeterBar Meter::mBar[kMaxMeterBars] [private]
Referenced by GetMaxPeak(), HandleLayout(), HandlePaint(), IsClipping(), OnMeterUpdate(), RepaintBarsNow(), and Reset().
wxBitmap* Meter::mBitmap [private]
Referenced by OnPaint(), OnSize(), RepaintBarsNow(), and ~Meter().
wxBrush Meter::mBkgndBrush [private]
Referenced by DrawMeterBar(), HandlePaint(), and OnDisableMeter().
wxBrush Meter::mBrush [private]
Referenced by DrawMeterBar(), and OnDisableMeter().
bool Meter::mClip [private]
Referenced by DrawMeterBar(), and HandleLayout().
wxBrush Meter::mClipBrush [private]
Referenced by DrawMeterBar().
wxPen Meter::mDarkPen [private]
Referenced by DrawMeterBar(), and OnDisableMeter().
bool Meter::mDB [private]
Referenced by HandleLayout(), OnDB(), OnLinear(), OnMeterUpdate(), OnMouse(), ToLinearIfDB(), and UpdateDisplay().
int Meter::mDBRange [private]
Referenced by HandleLayout(), OnMeterUpdate(), ToLinearIfDB(), UpdateDisplay(), and UpdatePrefs().
bool Meter::mDecay [private]
Referenced by OnMeterUpdate().
float Meter::mDecayRate [private]
Referenced by OnMeterUpdate().
wxBrush Meter::mDisabledBkgndBrush [private]
Referenced by OnDisableMeter().
wxPen Meter::mDisabledPen [private]
Referenced by OnDisableMeter().
int Meter::mHeight [private]
Referenced by HandleLayout(), HandlePaint(), OnPaint(), OnSize(), and RepaintBarsNow().
wxBitmap* Meter::mIcon [private]
Referenced by CreateIcon(), HandleLayout(), HandlePaint(), and ~Meter().
wxPoint Meter::mIconPos [private]
Referenced by HandleLayout(), and HandlePaint().
bool Meter::mIsInput [private]
Referenced by CreateIcon(), OnDisableMeter(), OnMeterUpdate(), OnMouse(), and UpdatePrefs().
bool Meter::mLayoutValid [private]
Referenced by HandleLayout(), HandlePaint(), OnDB(), OnDisableMeter(), OnLinear(), OnSize(), RepaintBarsNow(), Reset(), and SetStyle().
wxSize Meter::mLeftSize [private]
Referenced by HandleLayout(), and HandlePaint().
wxPoint Meter::mLeftTextPos [private]
Referenced by HandleLayout(), and HandlePaint().
wxPen Meter::mLightPen [private]
Referenced by DrawMeterBar(), and OnDisableMeter().
wxRect Meter::mMenuRect [private]
Referenced by HandleLayout(), HandlePaint(), and OnMouse().
long Meter::mMeterDisabled [private]
Referenced by HandlePaint(), IsMeterDisabled(), OnDisableMeter(), OnMeterUpdate(), OnMouse(), StartMonitoring(), and UpdatePrefs().
long Meter::mMeterRefreshRate [private]
Referenced by OnPreferences(), Reset(), and UpdatePrefs().
int Meter::mNumBars [private]
Referenced by GetMaxPeak(), HandleLayout(), HandlePaint(), OnMeterUpdate(), RepaintBarsNow(), and UpdateDisplay().
int Meter::mNumPeakSamplesToClip [private]
Referenced by OnMeterUpdate(), and UpdateDisplay().
double Meter::mPeakHoldDuration [private]
Referenced by OnMeterUpdate().
wxPen Meter::mPeakPeakPen [private]
Referenced by DrawMeterBar().
wxPen Meter::mPen [private]
Referenced by DrawMeterBar().
MeterUpdateQueue Meter::mQueue [private]
Referenced by Clear(), OnMeterUpdate(), Reset(), and UpdateDisplay().
double Meter::mRate [private]
Referenced by OnMeterUpdate(), and Reset().
wxSize Meter::mRightSize [private]
Referenced by HandleLayout(), and HandlePaint().
wxPoint Meter::mRightTextPos [private]
Referenced by HandleLayout(), and HandlePaint().
wxBrush Meter::mRMSBrush [private]
Referenced by DrawMeterBar(), and OnDisableMeter().
Ruler Meter::mRuler [private]
Referenced by HandleLayout(), and HandlePaint().
wxBrush Meter::mSavedBkgndBrush [private]
Referenced by OnDisableMeter().
wxBrush Meter::mSavedBrush [private]
Referenced by OnDisableMeter().
wxPen Meter::mSavedDarkPen [private]
Referenced by OnDisableMeter().
wxPen Meter::mSavedLightPen [private]
Referenced by OnDisableMeter().
wxBrush Meter::mSavedRMSBrush [private]
Referenced by OnDisableMeter().
Style Meter::mSavedStyle [private]
Style Meter::mStyle [private]
Referenced by GetStyle(), HandleLayout(), HandlePaint(), OnMouse(), SetStyle(), and UpdatePrefs().
double Meter::mT [private]
Referenced by OnMeterUpdate(), and Reset().
wxTimer Meter::mTimer [private]
Referenced by OnPreferences(), and Reset().
int Meter::mWidth [private]
Referenced by HandleLayout(), HandlePaint(), OnPaint(), OnSize(), and RepaintBarsNow().
The documentation for this class was generated from the following files:
Meter.h
Meter.cpp