Audacity: GUIPrefs Class Reference
GUIPrefs Class Reference
A PrefsPanel for general GUI preferences.
#include <GUIPrefs.h>
Public Member Functions
GUIPrefs (wxWindow *parent)
~GUIPrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
Private Attributes
wxArrayString mLangCodes
wxArrayString mLangNames
wxArrayString mHtmlHelpCodes
wxArrayString mHtmlHelpChoices
wxArrayString mRangeCodes
wxArrayString mRangeChoices
Detailed Description
A PrefsPanel for general GUI preferences.
Constructor & Destructor Documentation
GUIPrefs::GUIPrefs (wxWindow * parent)
References Populate().
GUIPrefs::~GUIPrefs ()
Member Function Documentation
bool GUIPrefs::Apply () [virtual]
Implements PrefsPanel.
References eIsSavingToPrefs, GetSystemLanguageCode(), gPrefs, AudacityApp::InitLang(), PopulateOrExchange(), and wxGetApp().
void GUIPrefs::Populate () [private]
References eIsCreatingFromPrefs, GetLanguages(), mHtmlHelpChoices, mHtmlHelpCodes, mLangCodes, mLangNames, mRangeChoices, mRangeCodes, and PopulateOrExchange().
Referenced by GUIPrefs().
void GUIPrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGui::AddSpace(), bQuitOnCloseDefault, ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), mHtmlHelpChoices, mHtmlHelpCodes, mLangCodes, mLangNames, mRangeChoices, mRangeCodes, ShuttleGuiBase::SetBorder(), ShuttleGui::SetSizeHints(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::TieCheckBox(), and ShuttleGuiBase::TieChoice().
Referenced by Apply(), and Populate().
Member Data Documentation
wxArrayString GUIPrefs::mHtmlHelpChoices [private]
Referenced by Populate(), and PopulateOrExchange().
wxArrayString GUIPrefs::mHtmlHelpCodes [private]
Referenced by Populate(), and PopulateOrExchange().
wxArrayString GUIPrefs::mLangCodes [private]
Referenced by Populate(), and PopulateOrExchange().
wxArrayString GUIPrefs::mLangNames [private]
Referenced by Populate(), and PopulateOrExchange().
wxArrayString GUIPrefs::mRangeChoices [private]
Referenced by Populate(), and PopulateOrExchange().
wxArrayString GUIPrefs::mRangeCodes [private]
Referenced by Populate(), and PopulateOrExchange().
The documentation for this class was generated from the following files:
GUIPrefs.h
GUIPrefs.cpp