Audacity: TracksPrefs Class Reference
TracksPrefs Class Reference
A PrefsPanel for track display and behavior properties.
#include <TracksPrefs.h>
Public Member Functions
TracksPrefs (wxWindow *parent)
~TracksPrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
Private Attributes
wxArrayString mSoloCodes
wxArrayString mSoloChoices
wxArrayInt mViewCodes
wxArrayString mViewChoices
Detailed Description
A PrefsPanel for track display and behavior properties.
Constructor & Destructor Documentation
TracksPrefs::TracksPrefs (wxWindow * parent)
References Populate().
TracksPrefs::~TracksPrefs ()
Member Function Documentation
bool TracksPrefs::Apply () [virtual]
Implements PrefsPanel.
References eIsSavingToPrefs, and PopulateOrExchange().
void TracksPrefs::Populate () [private]
References eIsCreatingFromPrefs, mSoloChoices, mSoloCodes, mViewChoices, mViewCodes, and PopulateOrExchange().
Referenced by TracksPrefs().
void TracksPrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGui::AddSpace(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), mSoloChoices, mSoloCodes, mViewChoices, mViewCodes, ShuttleGuiBase::SetBorder(), ShuttleGui::SetSizeHints(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::TieCheckBox(), and ShuttleGuiBase::TieChoice().
Referenced by Apply(), and Populate().
Member Data Documentation
wxArrayString TracksPrefs::mSoloChoices [private]
Referenced by Populate(), and PopulateOrExchange().
wxArrayString TracksPrefs::mSoloCodes [private]
Referenced by Populate(), and PopulateOrExchange().
wxArrayString TracksPrefs::mViewChoices [private]
Referenced by Populate(), and PopulateOrExchange().
wxArrayInt TracksPrefs::mViewCodes [private]
Referenced by Populate(), and PopulateOrExchange().
The documentation for this class was generated from the following files:
TracksPrefs.h
TracksPrefs.cpp