Audacity: PlaybackPrefs Class Reference
PlaybackPrefs Class Reference
A PrefsPanel used to select playback options.
#include <PlaybackPrefs.h>
Public Member Functions
PlaybackPrefs (wxWindow *parent)
virtual ~PlaybackPrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
Detailed Description
A PrefsPanel used to select playback options.
Presents interface for user to update the various playback options like previewing and seeking.
Constructor & Destructor Documentation
PlaybackPrefs::PlaybackPrefs (wxWindow * parent)
References Populate().
PlaybackPrefs::~PlaybackPrefs () [virtual]
Member Function Documentation
bool PlaybackPrefs::Apply () [virtual]
Implements PrefsPanel.
References eIsSavingToPrefs, and PopulateOrExchange().
void PlaybackPrefs::Populate () [private]
References eIsCreatingFromPrefs, and PopulateOrExchange().
Referenced by PlaybackPrefs().
void PlaybackPrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddUnits(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndThreeColumn(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartThreeColumn(), and ShuttleGuiBase::TieTextBox().
Referenced by Apply(), and Populate().
The documentation for this class was generated from the following files:
PlaybackPrefs.h
PlaybackPrefs.cpp