Audacity: ToolBarFrame Class Reference
ToolBarFrame Class Reference
A miniframe based container for ExpandingToolBars providing modeless presentation.
#include <ExpandingToolBar.h>
Public Member Functions
ToolBarFrame (wxWindow *parent, wxWindowID id, const wxString &name=wxEmptyString, const wxPoint &pos=wxDefaultPosition)
~ToolBarFrame ()
virtual void Fit ()
void SetChild (ExpandingToolBar *child)
Protected Attributes
ExpandingToolBar * mChild
Detailed Description
A miniframe based container for ExpandingToolBars providing modeless presentation.
Constructor & Destructor Documentation
ToolBarFrame::ToolBarFrame (wxWindow * parent, wxWindowID id, const wxString & name = wxEmptyString, const wxPoint & pos = wxDefaultPosition)
ToolBarFrame::~ToolBarFrame ()
Member Function Documentation
void ToolBarFrame::Fit () [virtual]
References mChild.
Referenced by SetChild().
void ToolBarFrame::SetChild (ExpandingToolBar * child)
References Fit(), and mChild.
Referenced by ExpandingToolBar::OnSize().
Member Data Documentation
ExpandingToolBar* ToolBarFrame::mChild [protected]
Referenced by Fit(), and SetChild().
The documentation for this class was generated from the following files:
ExpandingToolBar.h
ExpandingToolBar.cpp