Audacity: ExportMP2Options Class Reference
ExportMP2Options Class Reference
Public Member Functions
ExportMP2Options (wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
void OnOK (wxCommandEvent &event)
Private Attributes
wxArrayString mBitRateNames
wxArrayInt mBitRateLabels
Constructor & Destructor Documentation
ExportMP2Options::ExportMP2Options (wxWindow * parent)
References eIsCreatingFromPrefs, and iBitrates.
Member Function Documentation
void ExportMP2Options::OnOK (wxCommandEvent & event)
References eIsSavingToPrefs, and PopulateOrExchange().
void ExportMP2Options::PopulateOrExchange (ShuttleGui & S)
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndTwoColumn(), mBitRateLabels, mBitRateNames, ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartTwoColumn(), and ShuttleGuiBase::TieChoice().
Referenced by OnOK().
Member Data Documentation
wxArrayInt ExportMP2Options::mBitRateLabels [private]
Referenced by PopulateOrExchange().
wxArrayString ExportMP2Options::mBitRateNames [private]
Referenced by PopulateOrExchange().
The documentation for this class was generated from the following file:
ExportMP2.cpp