Audacity: EffectEqualization Class Reference
EffectEqualization Class Reference
An Effect.
#include <Equalization.h>
Public Types
enum { windowSize = 16384 }
enum { loFreqI = 20 }
enum curveType {
amradio, acoustic, nab, lp,
aes, deccaffrrmicro, deccaffrr78, riaa,
inverseriaa, col78, deccaffrrlp, emi78,
rcavictor1938, rcavictor1947, nCurveTypes
}
enum { nCurvePoints = 28 }
Public Member Functions
EffectEqualization ()
virtual ~EffectEqualization ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool Init ()
virtual bool PromptUser ()
virtual bool DontPromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Process ()
Static Public Attributes
static const float curvex []
static const float curvey [][nCurvePoints]
static const wxChar * curveNames []
Private Member Functions
bool ProcessOne (int count, WaveTrack *t, sampleCount start, sampleCount len)
void Filter (sampleCount len, float *buffer)
void ReadPrefs ()
Private Attributes
HFFT hFFT
float * mFFTBuffer
float * mFilterFuncR
float * mFilterFuncI
int mM
wxString mCurveName
bool mLin
double mdBMax
double mdBMin
bool mDrawMode
int mInterp
bool mPrompting
bool mDrawGrid
bool mEditingBatchParams
Friends
class EqualizationDialog
class EqualizationPanel
Detailed Description
An Effect.
Performs filtering, using an FFT to do a FIR filter. It lets the user draw an arbitrary envelope (using the same envelope editing code that is used to edit the track's amplitude envelope).
Also allows the curve to be specified with a series of 'graphic EQ' sliders.
The filter is applied using overlap/add of Hanning windows.
Has presets of certain specific equalization curves, suitable for old recordings.
Clone of the FFT Filter effect, no longer part of Audacity.
Member Enumeration Documentation
anonymous enum
Enumerator:
windowSize
anonymous enum
Enumerator:
loFreqI
anonymous enum
Enumerator:
nCurvePoints
enum EffectEqualization::curveType
Enumerator:
amradio
acoustic
nab
lp
aes
deccaffrrmicro
deccaffrr78
riaa
inverseriaa
col78
deccaffrrlp
emi78
rcavictor1938
rcavictor1947
nCurveTypes
Constructor & Destructor Documentation
EffectEqualization::EffectEqualization ()
References hFFT, InitializeFFT(), mFFTBuffer, mFilterFuncI, mFilterFuncR, mPrompting, ReadPrefs(), and windowSize.
EffectEqualization::~EffectEqualization () [virtual]
References EndFFT(), hFFT, mFFTBuffer, mFilterFuncI, and mFilterFuncR.
Member Function Documentation
bool EffectEqualization::DontPromptUser () [virtual]
References EqualizationDialog::CalcFilter(), EqualizationDialog::curveName, TrackListCondIterator::First(), GetActiveProject(), AudacityProject::GetRate(), WaveTrack::GetRate(), EqualizationDialog::interp, EqualizationDialog::linCheck, loFreqI, EqualizationDialog::M, mCurveName, mFilterFuncI, mFilterFuncR, mInterp, mM, Effect::mTracks, EqualizationDialog::TransferDataToWindow(), Track::Wave, and windowSize.
Referenced by TransferParameters().
void EffectEqualization::Filter (sampleCount len, float * buffer) [private]
References hFFT, InverseRealFFTf(), mFFTBuffer, mFilterFuncI, mFilterFuncR, RealFFTf(), and ReorderToTime().
Referenced by ProcessOne().
virtual wxString EffectEqualization::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectEqualization::GetEffectCategories () [inline, virtual]
virtual wxString EffectEqualization::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectEqualization::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectEqualization::Init () [virtual]
Reimplemented from Effect.
bool EffectEqualization::Process () [virtual]
Implements Effect.
References Effect::CopyInputTracks(), TrackListCondIterator::First(), WaveTrack::GetEndTime(), WaveTrack::GetStartTime(), Effect::mOutputTracks, Effect::mT0, Effect::mT1, TrackListCondIterator::Next(), ProcessOne(), Effect::ReplaceProcessedTracks(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectEqualization::ProcessOne (int count, WaveTrack * t, sampleCount start, sampleCount len) [private]
References WaveTrack::Append(), WaveTrack::Clear(), WaveTrack::Copy(), Filter(), floatSample, WaveTrack::Flush(), WaveTrack::Get(), GetActiveProject(), WaveTrack::GetClipIterator(), WaveClip::GetEndTime(), WaveTrack::GetMaxBlockSize(), WaveTrack::GetRate(), WaveClip::GetStartTime(), AudacityProject::GetTrackFactory(), WaveTrack::Join(), WaveTrack::LongSamplesToTime(), mM, TrackFactory::NewWaveTrack(), WaveTrack::Paste(), Effect::TrackProgress(), and windowSize.
Referenced by Process().
bool EffectEqualization::PromptUser () [virtual]
Reimplemented from Effect.
References EqualizationDialog::curveName, EqualizationDialog::dBMax, EqualizationDialog::dBMin, EqualizationDialog::drawGrid, EqualizationDialog::drawMode, TrackListCondIterator::First(), GetActiveProject(), AudacityProject::GetRate(), WaveTrack::GetRate(), gPrefs, EqualizationDialog::interp, EqualizationDialog::linCheck, loFreqI, EqualizationDialog::M, mCurveName, mdBMax, mdBMin, mDrawGrid, mDrawMode, mEditingBatchParams, mFilterFuncI, mFilterFuncR, mInterp, mLin, mM, Effect::mParent, mPrompting, Effect::mTracks, ReadPrefs(), Track::Wave, and windowSize.
void EffectEqualization::ReadPrefs () [private]
References gPrefs, mCurveName, mdBMax, mdBMin, mDrawGrid, mDrawMode, mInterp, mLin, and mM.
Referenced by EffectEqualization(), and PromptUser().
bool EffectEqualization::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References DontPromptUser(), mCurveName, mInterp, mLin, mM, mPrompting, NUM_INTERP_CHOICES, Shuttle::TransferBool(), Shuttle::TransferEnum(), Shuttle::TransferInt(), and Shuttle::TransferString().
Friends And Related Function Documentation
friend class EqualizationDialog [friend]
friend class EqualizationPanel [friend]
Member Data Documentation
const wxChar * EffectEqualization::curveNames [static]
Initial value:
  {
    wxT("amradio"),
    wxT("acoustic"),
    wxT("NAB"),
    wxT("Columbia LP"),
    wxT("AES"),
    wxT("Decca FFRR Micro"),
    wxT("Decca FFRR 78"),
    wxT("RIAA"),
    wxT("Inverse RIAA"),
    wxT("Columbia 78"),
    wxT("Decca FFRR LP"),
    wxT("EMI 78"),
    wxT("RCA Victor 1938"),
    wxT("RCA Victor 1947")
  }
const float EffectEqualization::curvex [static]
Initial value:
  {
   30., 31., 50., 63., 70., 100., 125., 200., 250., 300.,
   400., 500., 600., 700., 800., 900., 1000., 2000., 3000., 4000.,
   5000., 6000., 7000., 8000., 9000., 10000., 15000., 16000.
}
Referenced by EqualizationDialog::LoadDefaultCurves().
const float EffectEqualization::curvey [static]
Referenced by EqualizationDialog::LoadDefaultCurves().
HFFT EffectEqualization::hFFT [private]
Referenced by EffectEqualization(), Filter(), and ~EffectEqualization().
wxString EffectEqualization::mCurveName [private]
Referenced by DontPromptUser(), PromptUser(), ReadPrefs(), and TransferParameters().
double EffectEqualization::mdBMax [private]
Referenced by PromptUser(), and ReadPrefs().
double EffectEqualization::mdBMin [private]
Referenced by PromptUser(), and ReadPrefs().
bool EffectEqualization::mDrawGrid [private]
Referenced by PromptUser(), and ReadPrefs().
bool EffectEqualization::mDrawMode [private]
Referenced by PromptUser(), and ReadPrefs().
bool EffectEqualization::mEditingBatchParams [private]
Referenced by PromptUser().
float* EffectEqualization::mFFTBuffer [private]
Referenced by EffectEqualization(), Filter(), and ~EffectEqualization().
float* EffectEqualization::mFilterFuncI [private]
Referenced by DontPromptUser(), EffectEqualization(), Filter(), PromptUser(), and ~EffectEqualization().
float* EffectEqualization::mFilterFuncR [private]
Referenced by DontPromptUser(), EffectEqualization(), Filter(), PromptUser(), and ~EffectEqualization().
int EffectEqualization::mInterp [private]
Referenced by DontPromptUser(), PromptUser(), ReadPrefs(), and TransferParameters().
bool EffectEqualization::mLin [private]
Referenced by PromptUser(), ReadPrefs(), and TransferParameters().
int EffectEqualization::mM [private]
Referenced by DontPromptUser(), ProcessOne(), PromptUser(), ReadPrefs(), and TransferParameters().
bool EffectEqualization::mPrompting [private]
Referenced by EffectEqualization(), PromptUser(), and TransferParameters().
The documentation for this class was generated from the following files:
Equalization.h
Equalization.cpp