Audacity: ImportXMLTagHandler Class Reference
ImportXMLTagHandler Class Reference
#include <Project.h>
Public Member Functions
ImportXMLTagHandler (AudacityProject *pProject)
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
Private Attributes
AudacityProject * mProject
Constructor & Destructor Documentation
ImportXMLTagHandler::ImportXMLTagHandler (AudacityProject * pProject) [inline]
References mProject.
Member Function Documentation
virtual XMLTagHandler* ImportXMLTagHandler::HandleXMLChild (const wxChar * tag) [inline, virtual]
Implements XMLTagHandler.
bool ImportXMLTagHandler::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements XMLTagHandler.
References Internat::CompatibleToDouble(), AudacityProject::GetDirManager(), DirManager::GetProjectDataDir(), AudacityProject::Import(), XMLValueChecker::IsGoodFileName(), XMLValueChecker::IsGoodPathName(), XMLValueChecker::IsGoodString(), and mProject.
virtual void ImportXMLTagHandler::WriteXML (XMLWriter & xmlFile) [inline, virtual]
Member Data Documentation
AudacityProject* ImportXMLTagHandler::mProject [private]
Referenced by HandleXMLTag(), and ImportXMLTagHandler().
The documentation for this class was generated from the following files:
Project.h
Project.cpp