Audacity: FindClippingDialog Class Reference
FindClippingDialog Class Reference
FindClippingDialog used with EffectFindClipping.
#include <FindClipping.h>
Public Member Functions
FindClippingDialog (EffectFindClipping *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataFromWindow ()
Private Attributes
EffectFindClipping * mEffect
Detailed Description
FindClippingDialog used with EffectFindClipping.
Constructor & Destructor Documentation
FindClippingDialog::FindClippingDialog (EffectFindClipping * effect, wxWindow * parent)
References EffectDialog::Init(), and mEffect.
Member Function Documentation
void FindClippingDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddTitle(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), mEffect, EffectFindClipping::mStart, EffectFindClipping::mStop, ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), and ShuttleGuiBase::TieTextBox().
bool FindClippingDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References mEffect, EffectFindClipping::mStart, and EffectFindClipping::mStop.
Member Data Documentation
EffectFindClipping* FindClippingDialog::mEffect [private]
Referenced by FindClippingDialog(), PopulateOrExchange(), and TransferDataFromWindow().
The documentation for this class was generated from the following files:
FindClipping.h
FindClipping.cpp