Audacity: EffectAvcCompressor Class Reference
EffectAvcCompressor Class Reference
An unused Effect (we use EffectCompressor instead) derived from EffectSimplePairedTwoTrackBase.
#include <AvcCompressor.h>
Public Member Functions
EffectAvcCompressor ()
virtual ~EffectAvcCompressor ()
virtual wxString GetEffectName ()
virtual wxString GetEffectAction ()
virtual wxString GetEffectDescription ()
virtual void End ()
Protected Member Functions
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Init ()
bool ProcessSimplePairedTwoTrack (void *bufferLeft, void *bufferRight, sampleCount len)
Protected Attributes
AutoVolCtrl mAutoVolCtrl
long mnChangeWindow
iAVCBufferList * mpBufferList
iAVCBufferList * mpBufferPrevious
long mnDelay
AvcCompressorDialog * mpDialog
Private Member Functions
void OutputSample (IAVCSAMPLETYPE left, IAVCSAMPLETYPE right)
Detailed Description
An unused Effect (we use EffectCompressor instead) derived from EffectSimplePairedTwoTrackBase.
Constructor & Destructor Documentation
EffectAvcCompressor::EffectAvcCompressor ()
EffectAvcCompressor::~EffectAvcCompressor () [virtual]
References mpDialog.
Member Function Documentation
void EffectAvcCompressor::End () [virtual]
Reimplemented from EffectSimplePairedTwoTrack< IAVCSAMPLETYPE, AVCCOMPSAMPLETYPE >.
References mAutoVolCtrl, mpBufferList, mpBufferPrevious, and OutputSample().
virtual wxString EffectAvcCompressor::GetEffectAction () [inline, virtual]
Implements Effect.
wxString EffectAvcCompressor::GetEffectDescription () [virtual]
Reimplemented from Effect.
virtual wxString EffectAvcCompressor::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectAvcCompressor::Init () [protected, virtual]
Reimplemented from EffectSimplePairedTwoTrack< IAVCSAMPLETYPE, AVCCOMPSAMPLETYPE >.
void EffectAvcCompressor::OutputSample (IAVCSAMPLETYPE left, IAVCSAMPLETYPE right) [inline, private]
References iAVCBufferList::mnLen, iAVCBufferList::mnNext, mpBufferList, iAVCBufferList::mpLeftBuffer, iAVCBufferList::mpNext, and iAVCBufferList::mpRightBuffer.
Referenced by End(), and ProcessSimplePairedTwoTrack().
bool EffectAvcCompressor::ProcessSimplePairedTwoTrack (void * bufferLeft, void * bufferRight, sampleCount len) [protected, virtual]
Reimplemented from EffectSimplePairedTwoTrackBase.
References mAutoVolCtrl, mnDelay, iAVCBufferList::mnLen, iAVCBufferList::mnNext, mpBufferList, mpBufferPrevious, iAVCBufferList::mpLeftBuffer, iAVCBufferList::mpNext, iAVCBufferList::mpRightBuffer, and OutputSample().
bool EffectAvcCompressor::PromptUser () [protected, virtual]
Reimplemented from Effect.
References AvcCompressorDialog::GetAdjusterWindow(), AvcCompressorDialog::GetChangeWindow(), AvcCompressorDialog::GetDelay(), AvcCompressorDialog::GetMinimumPercent(), AvcCompressorDialog::GetTransformArray(), mAutoVolCtrl, mnChangeWindow, mnDelay, EffectSimplePairedTwoTrack< IAVCSAMPLETYPE, AVCCOMPSAMPLETYPE >::mnTracks, Effect::mParent, and mpDialog.
bool EffectAvcCompressor::TransferParameters (Shuttle & shuttle) [protected, virtual]
Reimplemented from Effect.
Member Data Documentation
AutoVolCtrl EffectAvcCompressor::mAutoVolCtrl [protected]
Referenced by End(), ProcessSimplePairedTwoTrack(), and PromptUser().
long EffectAvcCompressor::mnChangeWindow [protected]
Referenced by PromptUser().
long EffectAvcCompressor::mnDelay [protected]
Referenced by ProcessSimplePairedTwoTrack(), and PromptUser().
iAVCBufferList* EffectAvcCompressor::mpBufferList [protected]
Referenced by End(), OutputSample(), and ProcessSimplePairedTwoTrack().
iAVCBufferList* EffectAvcCompressor::mpBufferPrevious [protected]
Referenced by End(), and ProcessSimplePairedTwoTrack().
AvcCompressorDialog* EffectAvcCompressor::mpDialog [protected]
Referenced by PromptUser(), and ~EffectAvcCompressor().
The documentation for this class was generated from the following files:
AvcCompressor.h
AvcCompressor.cpp