Audacity: AudacityApp Class Reference
AudacityApp Class Reference
AudacityApp is the 'main' class for Audacity.
#include <AudacityApp.h>
Public Member Functions
virtual bool OnInit (void)
virtual int OnExit (void)
virtual void OnFatalException ()
float * GetCleanSpeechNoiseGate ()
int GetCleanSpeechNoiseGateExpectedCount ()
void SetCleanSpeechNoiseGate (float *pNG)
void SetCleanSpeechNoiseGateExpectedCount (int count)
void InitLang (const wxString &lang)
void OnMenuAbout (wxCommandEvent &event)
void OnMenuNew (wxCommandEvent &event)
void OnMenuOpen (wxCommandEvent &event)
void OnMenuPreferences (wxCommandEvent &event)
void OnMenuExit (wxCommandEvent &event)
void OnEndSession (wxCloseEvent &event)
void OnKeyDown (wxKeyEvent &event)
void OnChar (wxKeyEvent &event)
void OnKeyUp (wxKeyEvent &event)
void OnCaptureKeyboard (wxCommandEvent &event)
void OnReleaseKeyboard (wxCommandEvent &event)
void OnMRUClear (wxCommandEvent &event)
void OnMRUFile (wxCommandEvent &event)
bool MRUOpen (wxString fileName)
void OnReceiveCommand (AppCommandEvent &event)
FileHistory * GetRecentFiles ()
void AddFileToHistory (const wxString &name)
bool GetWindowRectAlreadySaved () const
void SetWindowRectAlreadySaved (bool alreadySaved)
Static Public Member Functions
static void AddUniquePathToPathList (wxString path, wxArrayString &pathList)
static void AddMultiPathsToPathList (wxString multiPathString, wxArrayString &pathList)
static void FindFilesInPathList (const wxString &pattern, const wxArrayString &pathList, wxArrayString &results, int flags=wxDIR_FILES)
Public Attributes
wxArrayString audacityPathList
A list of directories that should be searched for Audacity files (plug-ins, help files, etc.).
wxString defaultTempDir
Default temp directory.
Importer * mImporter
wxLogWindow * mLogger
Private Member Functions
void InitCommandHandler ()
void DeInitCommandHandler ()
bool InitTempDir ()
bool CreateSingleInstanceChecker (wxString dir)
void PrintCommandLineHelp (void)
bool InitCleanSpeech ()
Private Attributes
CommandHandler * mCmdHandler
FileHistory * mRecentFiles
wxLocale * mLocale
wxSingleInstanceChecker * mChecker
float * mCleanSpeechNoiseGate
int mCleanSpeechNoiseGateExpectedCount
wxString mAppHomeDir
wxString mPresetsDir
bool mWindowRectAlreadySaved
Detailed Description
AudacityApp is the 'main' class for Audacity.
It handles initialization and termination by subclassing wxApp.
Member Function Documentation
void AudacityApp::AddFileToHistory (const wxString & name)
References FileHistory::AddFileToHistory(), and mRecentFiles.
Referenced by AudacityProject::BuildCleanFileName(), AudacityProject::Import(), AudacityProject::OpenFile(), and AudacityProject::SaveAs().
void AudacityApp::AddMultiPathsToPathList (wxString multiPathString, wxArrayString & pathList) [static]
References AddUniquePathToPathList().
Referenced by ModuleManager::Initialize(), LoadLadspaPlugins(), LoadModules(), and OnInit().
void AudacityApp::AddUniquePathToPathList (wxString path, wxArrayString & pathList) [static]
Referenced by AddMultiPathsToPathList(), GetLanguages(), ModuleManager::Initialize(), LoadLadspaPlugins(), LoadModules(), LoadNyquistPlugins(), OnInit(), and EffectNyquist::SetXlispPath().
bool AudacityApp::CreateSingleInstanceChecker (wxString dir) [private]
References mChecker, and name.
Referenced by InitTempDir().
void AudacityApp::DeInitCommandHandler () [private]
References mCmdHandler.
Referenced by OnExit().
void AudacityApp::FindFilesInPathList (const wxString & pattern, const wxArrayString & pathList, wxArrayString & results, int flags = wxDIR_FILES) [static]
Referenced by ModuleManager::Initialize(), LoadLadspaPlugins(), LoadModules(), LoadNyquistPlugins(), EffectNyquist::SetXlispPath(), and TranslationExists().
float* AudacityApp::GetCleanSpeechNoiseGate () [inline]
References mCleanSpeechNoiseGate.
Referenced by AudacityProject::OnExportCleanSpeechPresets(), and AudacityProject::OnImportCleanSpeechPresets().
int AudacityApp::GetCleanSpeechNoiseGateExpectedCount () [inline]
References mCleanSpeechNoiseGateExpectedCount.
Referenced by AudacityProject::OnExportCleanSpeechPresets(), and AudacityProject::OnImportCleanSpeechPresets().
FileHistory* AudacityApp::GetRecentFiles () [inline]
References mRecentFiles.
Referenced by AudacityProject::CreateRecentFilesMenu(), AudacityProject::RebuildMenuBar(), and AudacityProject::~AudacityProject().
bool AudacityApp::GetWindowRectAlreadySaved () const [inline]
References mWindowRectAlreadySaved.
bool AudacityApp::InitCleanSpeech () [private]
References FileNames::DataDir(), gPrefs, and OSFILENAME.
Referenced by OnInit().
void AudacityApp::InitCommandHandler () [private]
References mCmdHandler.
Referenced by OnInit().
void AudacityApp::InitLang (const wxString & lang)
References AUDACITY_NAME, audacityPathList, Internat::Init(), and mLocale.
Referenced by GUIPrefs::Apply(), EffectsPrefs::Apply(), and OnInit().
bool AudacityApp::InitTempDir () [private]
References CreateSingleInstanceChecker(), defaultTempDir, gPrefs, OSFILENAME, DirManager::SetTempDir(), PrefsDialog::ShowTempDirPage(), and wxGetApp().
Referenced by OnInit().
bool AudacityApp::MRUOpen (wxString fileName)
References CreateNewAudacityProject(), gAudacityProjects, GetActiveProject(), AudacityProject::GetDirty(), AudacityProject::GetIsEmpty(), gPrefs, and AudacityProject::OpenFile().
Referenced by OnMRUFile().
void AudacityApp::OnCaptureKeyboard (wxCommandEvent & event)
void AudacityApp::OnChar (wxKeyEvent & event)
References GetActiveProject(), and AudacityProject::HandleChar().
void AudacityApp::OnEndSession (wxCloseEvent & event)
References gAudacityProjects, and gIsQuitting.
int AudacityApp::OnExit (void) [virtual]
References BlockFile::Deinit(), DeinitAudioIO(), DeInitCommandHandler(), DeinitFFT(), DropFFmpegLibs(), FinishPreferences(), gIsQuitting, gPrefs, mChecker, mImporter, mLocale, mRecentFiles, FileHistory::Save(), and UnloadEffects().
void AudacityApp::OnFatalException () [virtual]
bool AudacityApp::OnInit (void) [virtual]
References FileHistory::AddFilesToMenu(), AddMultiPathsToPathList(), AddUniquePathToPathList(), AppInitialized, AUDACITY_NAME, AUDACITY_VERSION_STRING, audacityPathList, CreateNewAudacityProject(), defaultTempDir, ModuleManager::Dispatch(), Theme::EnsureInitialised(), FFmpegStartup(), FinishPreferences(), GetSystemLanguageCode(), gInited, gParentFrame, gPrefs, GStreamerStartup(), AColor::Init(), InitAudioIO(), InitCleanSpeech(), InitCommandHandler(), InitDitherers(), ModuleManager::Initialize(), InitLang(), InitPreferences(), InitTempDir(), INSTALL_PREFIX, FileHistory::Load(), LoadEffects(), LoadModules(), MakeHijackPanel(), mAppHomeDir, AudacityProject::MayStartMonitoring(), mCmdHandler, mImporter, mLocale, mLogger, mRecentFiles, AudacityProject::mShowSplashScreen, mWindowRectAlreadySaved, AudacityProject::OnHelpWelcome(), AudacityProject::OpenFile(), PrintCommandLineHelp(), QuitAudacity(), RunBenchmark(), DirManager::SetDontDeleteTempFiles(), Sequence::SetMaxDiskBlockSize(), SetOption(), CommandHandler::SetProject(), ShowAutoRecoveryDialogIfNeeded(), theTheme, and FileHistory::UseMenu().
void AudacityApp::OnKeyDown (wxKeyEvent & event)
References GetActiveProject(), and AudacityProject::HandleKeyDown().
void AudacityApp::OnKeyUp (wxKeyEvent & event)
References GetActiveProject(), and AudacityProject::HandleKeyUp().
void AudacityApp::OnMenuAbout (wxCommandEvent & event)
References gAudacityProjects.
void AudacityApp::OnMenuExit (wxCommandEvent & event)
References gAudacityProjects, and QuitAudacity().
void AudacityApp::OnMenuNew (wxCommandEvent & event)
References CreateNewAudacityProject(), and gAudacityProjects.
void AudacityApp::OnMenuOpen (wxCommandEvent & event)
References gAudacityProjects, and AudacityProject::OpenFiles().
void AudacityApp::OnMenuPreferences (wxCommandEvent & event)
References gAudacityProjects.
void AudacityApp::OnMRUClear (wxCommandEvent & event)
References FileHistory::Clear(), and mRecentFiles.
void AudacityApp::OnMRUFile (wxCommandEvent & event)
References FileHistory::GetHistoryFile(), mRecentFiles, MRUOpen(), and FileHistory::RemoveFileFromHistory().
void AudacityApp::OnReceiveCommand (AppCommandEvent & event)
References mCmdHandler, and CommandHandler::OnReceiveCommand().
void AudacityApp::OnReleaseKeyboard (wxCommandEvent & event)
void AudacityApp::PrintCommandLineHelp (void) [private]
Referenced by OnInit().
void AudacityApp::SetCleanSpeechNoiseGate (float * pNG) [inline]
References mCleanSpeechNoiseGate.
Referenced by EffectNoiseRemoval::EffectNoiseRemoval().
void AudacityApp::SetCleanSpeechNoiseGateExpectedCount (int count) [inline]
References mCleanSpeechNoiseGateExpectedCount.
Referenced by EffectNoiseRemoval::EffectNoiseRemoval().
void AudacityApp::SetWindowRectAlreadySaved (bool alreadySaved) [inline]
References mWindowRectAlreadySaved.
Referenced by AudacityProject::OnCloseWindow(), and SaveWindowSize().
Member Data Documentation
wxArrayString AudacityApp::audacityPathList
A list of directories that should be searched for Audacity files (plug-ins, help files, etc.).
On Unix this will include the directory Audacity was installed into, plus the current user's .audacity-data/Plug-Ins directory. Additional directories can be specified using the AUDACITY_PATH environment variable. On Windows or Mac OS, this will include the directory which contains the Audacity program.
Referenced by GetLanguages(), ModuleManager::Initialize(), InitLang(), LoadLadspaPlugins(), LoadModules(), LoadNyquistPlugins(), OnInit(), and EffectNyquist::SetXlispPath().
wxString AudacityApp::defaultTempDir
Default temp directory.
Referenced by InitTempDir(), and OnInit().
wxString AudacityApp::mAppHomeDir [private]
Referenced by OnInit().
wxSingleInstanceChecker* AudacityApp::mChecker [private]
Referenced by CreateSingleInstanceChecker(), and OnExit().
float* AudacityApp::mCleanSpeechNoiseGate [private]
Referenced by GetCleanSpeechNoiseGate(), and SetCleanSpeechNoiseGate().
int AudacityApp::mCleanSpeechNoiseGateExpectedCount [private]
Referenced by GetCleanSpeechNoiseGateExpectedCount(), and SetCleanSpeechNoiseGateExpectedCount().
CommandHandler* AudacityApp::mCmdHandler [private]
Referenced by DeInitCommandHandler(), InitCommandHandler(), OnInit(), and OnReceiveCommand().
Importer* AudacityApp::mImporter
Referenced by AudacityProject::Import(), BatchProcessDialog::OnApplyToFiles(), OnExit(), OnInit(), and AudacityProject::ShowOpenDialog().
wxLocale* AudacityApp::mLocale [private]
Referenced by InitLang(), OnExit(), and OnInit().
wxLogWindow* AudacityApp::mLogger
Referenced by FFmpegLibs::InitLibs(), AudacityProject::OnCloseWindow(), OnInit(), AudacityProject::OnLog(), and QuitAudacity().
wxString AudacityApp::mPresetsDir [private]
FileHistory* AudacityApp::mRecentFiles [private]
Referenced by AddFileToHistory(), GetRecentFiles(), OnExit(), OnInit(), OnMRUClear(), and OnMRUFile().
bool AudacityApp::mWindowRectAlreadySaved [private]
Referenced by GetWindowRectAlreadySaved(), OnInit(), and SetWindowRectAlreadySaved().
The documentation for this class was generated from the following files:
AudacityApp.h
AudacityApp.cpp