Audacity: XMLFileWriter Class Reference
XMLFileWriter Class Reference
Wrapper to output XML data to files.
#include <XMLWriter.h>
Public Member Functions
XMLFileWriter ()
virtual ~XMLFileWriter ()
void Open (const wxString &name, const wxString &mode)
Open the file. Might throw XMLFileWriterException.
void Close ()
Close file. Might throw XMLFileWriterException.
void CloseWithoutEndingTags ()
void Write (const wxString &data)
Write to file. Might throw XMLFileWriterException.
Detailed Description
Wrapper to output XML data to files.
XMLFileWriter
Constructor & Destructor Documentation
XMLFileWriter::XMLFileWriter ()
XMLFileWriter class
XMLFileWriter::~XMLFileWriter () [virtual]
References Close().
Member Function Documentation
void XMLFileWriter::Close ()
Close file. Might throw XMLFileWriterException.
References CloseWithoutEndingTags(), XMLWriter::EndTag(), and XMLWriter::mTagstack.
Referenced by CloseWithoutEndingTags(), ConvertLegacyProjectFile(), TagsEditor::OnSave(), KeyConfigPrefs::OnSave(), AudacityProject::Save(), EqualizationDialog::SaveCurves(), Write(), and ~XMLFileWriter().
void XMLFileWriter::CloseWithoutEndingTags ()
Close file without automatically ending tags. Might throw XMLFileWriterException.
References Close().
Referenced by AudacityProject::AutoSave(), and Close().
void XMLFileWriter::Open (const wxString & name, const wxString & mode)
Open the file. Might throw XMLFileWriterException.
Referenced by AudacityProject::AutoSave(), ConvertLegacyProjectFile(), FFmpegPresets::ExportPresets(), TagsEditor::OnSave(), KeyConfigPrefs::OnSave(), AudacityProject::Save(), EqualizationDialog::SaveCurves(), and FFmpegPresets::~FFmpegPresets().
void XMLFileWriter::Write (const wxString & data) [virtual]
Write to file. Might throw XMLFileWriterException.
Implements XMLWriter.
References Close().
Referenced by ConvertLegacyProjectFile().
The documentation for this class was generated from the following files:
XMLWriter.h
XMLWriter.cpp