Audacity: ExportCL Class Reference
ExportCL Class Reference
Public Member Functions
ExportCL ()
void Destroy ()
bool DisplayOptions (wxWindow *parent, int format=0)
int Export (AudacityProject *project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec *mixerSpec=NULL, Tags *metadata=NULL, int subformat=0)
called to export audio into a file.
Constructor & Destructor Documentation
ExportCL::ExportCL ()
References ExportPlugin::AddExtension(), ExportPlugin::AddFormat(), ExportPlugin::SetCanMetaData(), ExportPlugin::SetDescription(), ExportPlugin::SetFormat(), and ExportPlugin::SetMaxChannels().
Member Function Documentation
void ExportCL::Destroy () [virtual]
Reimplemented from ExportPlugin.
bool ExportCL::DisplayOptions (wxWindow * parent, int format = 0) [virtual]
Reimplemented from ExportPlugin.
int ExportCL::Export (AudacityProject * project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec * mixerSpec = NULL, Tags * metadata = NULL, int subformat = 0) [virtual]
called to export audio into a file.
Parameters:
selectedOnly Set to true if all tracks should be mixed, to false if only the selected tracks should be mixed and exported.
metadata A Tags object that will over-ride the one in *project and be used to tag the file that is exported.
subformat Control which of the multiple formats this exporter is capable of exporting should be used. Used where a single export plug-in handles a number of related formats, but they have separate entries in the Format drop-down list box. For example, the options to export to "Other PCM", "AIFF 16 Bit" and "WAV 16 Bit" are all the same libsndfile export plug-in, but with subformat set to 0, 1, and 2 respectively.
Reimplemented from ExportPlugin.
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddTextWindow(), wav_header::avgBytesPerSec, wav_header::bitsPerSample, wav_header::blockAlign, wav_header::channels, wav_header::dataID, wav_header::dataLen, Drain(), eIsCreating, eProgressSuccess, wav_header::fmtID, wav_header::formatChunkLen, wav_header::formatTag, Mixer::GetBuffer(), AudacityProject::GetRate(), TrackList::GetTimeTrack(), AudacityProject::GetTracks(), TrackList::GetWaveTracks(), gPrefs, ShuttleGui::Id(), int16Sample, wav_header::lenAfterRiff, Mixer::MixGetCurrentTime(), Mixer::Process(), wav_header::riffID, wav_header::riffType, SAMPLE_SIZE, wav_header::sampleRate, ShuttleGuiBase::StartHorizontalLay(), and ProgressDialog::Update().
The documentation for this class was generated from the following file:
ExportCL.cpp