#!/usr/bin/perl

print "maketarball v0.94 -- make Audacity distribution tarball\n";

if(@ARGV == 0) {
	display_usage();
	exit;
}

unless(-f "AudacityApp.cpp") {
	print "Must be run from Audacity directory\n";
	exit;
}

# find version number
open(HEADER, "AudacityApp.h");
@lines = <HEADER>;
$lines = join " ", @lines;
$lines =~ /AUDACITY_VERSION_STRING "([0-9.a-z]*)"/;
$version = $1;
print "version set to $version...\n";
close(HEADER);

if($ARGV[0] eq "debian") {
	print "target set to debian...\n";

	print "making copy of source directory...\n";
	`cp -r . ../audacity-$version`;
	chdir "../audacity-$version";

	print "removing xaudio...\n";
	`rm -rf xaudio`;

	print "removing windows and mac project files...\n";
	`rm -f audacity-carbon.rsrc audacity.Rsrc audacity.dsp audacity.dsw`;
	`rm -f audacity.mcp`;

	printf "removing CVS directories...\n";
	`find . -name "CVS" -exec rm -rf '{}' \\; 2> /dev/null`;

	printf "removing executable and other intermediate files...\n";
	`rm -rf audacity .depend obj config.cache config.status config.log Makefile`;

	printf "removing the copy of this script...\n";
	`rm -f maketarball`;

	printf "patching README.txt to remove xaudio copyright notices...\n";
	`patch < README-debian.diff; rm -f README-debian.diff`;

	printf "patching configure.in and regenerating configure to disallow selecting xaudio...\n";
	`patch < configure-debian.diff; rm -f configure-debian.diff; autoconf;`;
	
	print "making tarball audacity-debian-$version.tar.gz...\n";
	chdir "..";
	`tar zcf audacity-debian-$version.tar.gz audacity-$version`;
	
	print "deleting temporary copy...\n";
	`rm -rf audacity-$version`;
	
	print "done.\n";
}
elsif($ARGV[0] eq "src") {
	print "target set to src...\n";

	print "making copy of source directory...\n";
	`cp -r . ../audacity-src-$version`;
	chdir "../audacity-src-$version";

	printf "removing CVS directories...\n";
	`find . -name "CVS" -exec rm -rf '{}' \\; 2> /dev/null`;

	printf "removing executable and other intermediate files...\n";
	`rm -rf audacity .depend obj config.cache config.status config.log Makefile`;

	printf "removing the copy of this script...\n";
	`rm -f maketarball`;

	print "making tarball audacity-src-$version.tgz...\n";
	chdir "..";
	`tar zcf audacity-src-$version.tgz audacity-src-$version`;
	
	print "deleting temporary copy...\n";
	`rm -rf audacity-$version`;
	
	print "done.\n";
} else {
	print "target $ARGV[0] not recognized.\n";
	display_usage();
	exit;
}


sub display_usage() {
	print "Usage: maketarball <target>\n";
	print "\n";
	print "Available Targets:\n";
	print "  debian - Debian GNU/Linux source tarball:\n";
	print "           removes xaudio and non-Linux files\n";
	print "  src - Removes development files for SourceForge distribution\n";
	print "\n";
}
