//#include "ControlButtons/Disabled.xpm"

#ifdef __WXMAC__
#include "Aqua/UpButtonSquare.xpm"
#include "Aqua/DownButtonSquare.xpm"
#include "Aqua/HiliteButtonSquare.xpm"
#else
#include "ControlButtons/UpButton.xpm"
#include "ControlButtons/DownButton.xpm"
#include "ControlButtons/HiliteButton.xpm"
#endif

#include "ControlButtons/EnvelopeAlpha.xpm"
#include "ControlButtons/Envelope.xpm"
#include "ControlButtons/FFwdAlpha.xpm"
#include "ControlButtons/FFwdDisabled.xpm"
#include "ControlButtons/FFwd.xpm"
#include "ControlButtons/IBeamAlpha.xpm"
#include "ControlButtons/IBeam.xpm"
#include "ControlButtons/PlayAlpha.xpm"
#include "ControlButtons/PlayDisabled.xpm"
#include "ControlButtons/Play.xpm"
#include "ControlButtons/RecordAlpha.xpm"
#include "ControlButtons/RecordDisabled.xpm"
#include "ControlButtons/Record.xpm"
#include "ControlButtons/RewindAlpha.xpm"
#include "ControlButtons/RewindDisabled.xpm"
#include "ControlButtons/Rewind.xpm"
#include "ControlButtons/SliderThumb.xpm"
#include "ControlButtons/Slider.xpm"
#include "ControlButtons/StopAlpha.xpm"
#include "ControlButtons/StopDisabled.xpm"
#include "ControlButtons/Stop.xpm"
#include "ControlButtons/TimeShiftAlpha.xpm"
#include "ControlButtons/TimeShift.xpm"
#include "ControlButtons/ZoomAlpha.xpm"
#include "ControlButtons/Zoom.xpm"
#include "ControlButtons/DrawAlpha.xpm"
#include "ControlButtons/Draw.xpm"
