Audacity: ErrorDialog.h File Reference
ErrorDialog.h File Reference
#include "../Audacity.h"
#include <wx/defs.h>
#include <wx/window.h>
Functions
void ShowErrorDialog (wxWindow *parent, const wxString &dlogTitle, const wxString &message, const wxString &helpURL)
Displays an error dialog with a button that offers help.
void ShowInfoDialog (wxWindow *parent, const wxString &dlogTitle, const wxString &shortMsg, const wxString &message, const int xSize, const int ySize)
Displays cutable information in a text ctrl, with an OK button.
void ShowHtmlText (wxWindow *pParent, const wxString &Title, const wxString &HtmlText)
Displays a new window with wxHTML help.
void ShowHelpDialog (wxWindow *parent, const wxString &localFileName, const wxString &remoteURL)
Function Documentation
void ShowErrorDialog (wxWindow * parent, const wxString & dlogTitle, const wxString & message, const wxString & helpURL)
Displays an error dialog with a button that offers help.
Referenced by AudacityProject::Import().
void ShowHelpDialog (wxWindow * parent, const wxString & localFileName, const wxString & remoteURL)
Displays a file in your browser, if it's available locally, OR else links to the internet.
References GetActiveProject(), gPrefs, HelpText(), AudacityProject::mHelpPref, OpenInDefaultBrowser(), and ShowHtmlText().
Referenced by LinkingHtmlWindow::OnLinkClicked(), AudacityProject::OnManual(), and AudacityProject::OnQuickHelp().
void ShowHtmlText (wxWindow * pParent, const wxString & Title, const wxString & HtmlText)
Displays a new window with wxHTML help.
void ShowInfoDialog (wxWindow * parent, const wxString & dlogTitle, const wxString & shortMsg, const wxString & message, const int xSize, const int ySize)
Displays cutable information in a text ctrl, with an OK button.
Mostly we use this so that we have the code for resizability in one place. Other considerations like screen readers are also handled by having the code in one place.
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTextWindow(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddWindow(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndVerticalLay(), eOkButton, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartVerticalLay().
Referenced by AudacityProject::OnAudioDeviceInfo(), and ExportMultiple::OnExport().