Audacity: LegacyBlockFile.cpp File Reference
LegacyBlockFile.cpp File Reference
#include <float.h>
#include <math.h>
#include <wx/filefn.h>
#include <wx/file.h>
#include <wx/ffile.h>
#include <wx/utils.h>
#include <wx/log.h>
#include "LegacyBlockFile.h"
#include "../FileFormats.h"
#include "../Internat.h"
#include "sndfile.h"
Functions
void ComputeLegacySummaryInfo (wxFileName fileName, int summaryLen, sampleFormat format, SummaryInfo *info, bool noRMS, bool Silent, float *min, float *max, float *rms)
Function Documentation
void ComputeLegacySummaryInfo (wxFileName fileName, int summaryLen, sampleFormat format, SummaryInfo * info, bool noRMS, bool Silent, float * min, float * max, float * rms)
References SummaryInfo::bytesPerFrame, CopySamples(), DeleteSamples(), SummaryInfo::fields, floatSample, SummaryInfo::format, SummaryInfo::frames256, SummaryInfo::frames64K, NewSamples(), SummaryInfo::offset256, SummaryInfo::offset64K, SAMPLE_SIZE, and SummaryInfo::totalSummaryBytes.
Referenced by LegacyAliasBlockFile::LegacyAliasBlockFile(), and LegacyBlockFile::LegacyBlockFile().