Audacity: RawAudioGuess.cpp File Reference
RawAudioGuess.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <wx/defs.h>
#include <wx/ffile.h>
#include "../Internat.h"
#include "RawAudioGuess.h"
Defines
#define RAW_GUESS_DEBUG 0
Functions
float AmpStat (float *data, int len)
float JumpStat (float *data, int len)
float SecondDStat (float *data, int len)
float RedundantStereo (float *data, int len)
void ExtractFloats (bool doublePrec, bool bigendian, bool stereo, int offset, char *rawData, int dataSize, float *data1, float *data2, int *len1, int *len2)
void Extract (bool bits16, bool sign, bool stereo, bool bigendian, bool offset, char *rawData, int dataSize, float *data1, float *data2, int *len1, int *len2)
int GuessFloatFormats (int numTests, char **rawData, int dataSize, int *out_offset, int *out_channels)
int Guess8Bit (int numTests, char **rawData, int dataSize, int *out_channels)
int Guess16Bit (int numTests, char **rawData, int dataSize, bool evenMSB, int *out_offset, int *out_channels)
int GuessIntFormats (int numTests, char **rawData, int dataSize, int *out_offset, int *out_channels)
int RawAudioGuess (const wxString &in_fname, int *out_offset, int *out_channels)
Define Documentation
#define RAW_GUESS_DEBUG 0
Function Documentation
float AmpStat (float * data, int len)
Referenced by GuessIntFormats().
void Extract (bool bits16, bool sign, bool stereo, bool bigendian, bool offset, char * rawData, int dataSize, float * data1, float * data2, int * len1, int * len2)
Referenced by Guess16Bit(), Guess8Bit(), and GuessIntFormats().
void ExtractFloats (bool doublePrec, bool bigendian, bool stereo, int offset, char * rawData, int dataSize, float * data1, float * data2, int * len1, int * len2)
Referenced by GuessFloatFormats().
int Guess16Bit (int numTests, char ** rawData, int dataSize, bool evenMSB, int * out_offset, int * out_channels)
References Extract(), JumpStat(), and RedundantStereo().
Referenced by GuessIntFormats().
int Guess8Bit (int numTests, char ** rawData, int dataSize, int * out_channels)
References Extract(), JumpStat(), and RedundantStereo().
Referenced by GuessIntFormats().
int GuessFloatFormats (int numTests, char ** rawData, int dataSize, int * out_offset, int * out_channels)
References ExtractFloats(), JumpStat(), max, min(), RedundantStereo(), and SecondDStat().
Referenced by RawAudioGuess().
int GuessIntFormats (int numTests, char ** rawData, int dataSize, int * out_offset, int * out_channels)
References AmpStat(), Extract(), Guess16Bit(), and Guess8Bit().
Referenced by RawAudioGuess().
float JumpStat (float * data, int len)
Referenced by Guess16Bit(), Guess8Bit(), and GuessFloatFormats().
int RawAudioGuess (const wxString & in_fname, int * out_offset, int * out_channels)
References GuessFloatFormats(), and GuessIntFormats().
Referenced by ImportRaw().
float RedundantStereo (float * data, int len)
Referenced by Guess16Bit(), Guess8Bit(), and GuessFloatFormats().
float SecondDStat (float * data, int len)
Referenced by GuessFloatFormats().