Audacity: SampleFormat.cpp File Reference
SampleFormat.cpp File Reference
Functions that work with Dither and initialise it.
#include <wx/intl.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "SampleFormat.h"
#include "Prefs.h"
#include "Dither.h"
Functions
void InitDitherers ()
const wxChar * GetSampleFormatStr (sampleFormat format)
AUDACITY_DLL_API samplePtr NewSamples (int count, sampleFormat format)
AUDACITY_DLL_API void DeleteSamples (samplePtr p)
void ClearSamples (samplePtr src, sampleFormat format, int start, int len)
void CopySamples (samplePtr src, sampleFormat srcFormat, samplePtr dst, sampleFormat dstFormat, unsigned int len, bool highQuality, unsigned int stride)
void CopySamplesNoDither (samplePtr src, sampleFormat srcFormat, samplePtr dst, sampleFormat dstFormat, unsigned int len, unsigned int stride)
Variables
Dither::DitherType gLowQualityDither = Dither::none
Dither::DitherType gHighQualityDither = Dither::none
Dither gDitherAlgorithm
Detailed Description
Functions that work with Dither and initialise it.
This file handles converting between all of the different sample formats that Audacity supports, such as 16-bit, 24-bit (packed into a 32-bit int), and 32-bit float.
Floating-point samples use the range -1.0...1.0, inclusive. Integer formats use the full signed range of their data type, for example 16-bit samples use the range -32768...32767. This means that reading in a wav file and writing it out again ('round tripping'), via floats, is lossless; -32768 equates to -1.0f and 32767 equates to +1.0f - (a little bit). It also means (unfortunatly) that writing out +1.0f leads to clipping by 1 LSB. This creates some distortion, but I (MJS) have not been able to measure it, it's so small. Zero is preserved.
http://limpet.net/audacity/bugzilla/show_bug.cgi?id=200 leads to some of the discussions that were held about this.
Note: These things are now handled by the Dither class, which also replaces the CopySamples() method (msmeyer)
Function Documentation
void ClearSamples (samplePtr src, sampleFormat format, int start, int len)
References SAMPLE_SIZE.
Referenced by audacityAudioCallback(), AudioIO::FillBuffers(), WaveTrack::Get(), Sequence::Read(), SilentBlockFile::ReadData(), ODDecodeBlockFile::ReadData(), and Sequence::Set().
void CopySamples (samplePtr src, sampleFormat srcFormat, samplePtr dst, sampleFormat dstFormat, unsigned int len, bool highQuality, unsigned int stride)
References Dither::Apply(), gHighQualityDither, and gLowQualityDither.
Referenced by WaveClip::Append(), Sequence::Append(), audacityAudioCallback(), ODPCMAliasBlockFile::CalcSummary(), ODDecodeBlockFile::CalcSummary(), BlockFile::CalcSummary(), ComputeLegacySummaryInfo(), Sequence::ConvertToSampleFormat(), DoSoftwarePlaythrough(), RingBuffer::Get(), EffectNyquist::GetCallback(), WaveClip::GetWaveDisplay(), Mixer::Process(), RingBuffer::Put(), BlockFile::Read256(), BlockFile::Read64K(), SimpleBlockFile::ReadData(), PCMAliasBlockFile::ReadData(), ODPCMAliasBlockFile::ReadData(), LegacyBlockFile::ReadData(), and Sequence::Set().
void CopySamplesNoDither (samplePtr src, sampleFormat srcFormat, samplePtr dst, sampleFormat dstFormat, unsigned int len, unsigned int stride)
References Dither::Apply(), and Dither::none.
AUDACITY_DLL_API void DeleteSamples (samplePtr p)
References AUDACITY_DLL_API.
Referenced by Sequence::Append(), ComputeLegacySummaryInfo(), Sequence::ConvertToSampleFormat(), Sequence::Copy(), Sequence::CopyWrite(), Sequence::Delete(), AudioIO::FillBuffers(), BlockFile::GetMinMax(), PCMImportFileHandle::Import(), Sequence::Paste(), EffectNyquist::ProcessOne(), SimpleBlockFile::ReadData(), PCMAliasBlockFile::ReadData(), ODPCMAliasBlockFile::ReadData(), LegacyBlockFile::ReadData(), RemoveDependencies(), Sequence::Set(), ODDecodeBlockFile::WriteODDecodeBlockFile(), ODPCMAliasBlockFile::WriteSummary(), AliasBlockFile::WriteSummary(), AudioIO::~AudioIO(), Mixer::~Mixer(), RingBuffer::~RingBuffer(), and WaveClip::~WaveClip().
const wxChar* GetSampleFormatStr (sampleFormat format)
References floatSample, int16Sample, and int24Sample.
Referenced by TrackPanel::BuildMenus(), TrackPanel::DrawOutside(), and TrackPanel::OnFormatChange().
void InitDitherers ()
References gHighQualityDither, gLowQualityDither, gPrefs, Dither::none, and Dither::shaped.
Referenced by QualityPrefs::Apply(), and AudacityApp::OnInit().
AUDACITY_DLL_API samplePtr NewSamples (int count, sampleFormat format)
References AUDACITY_DLL_API, and SAMPLE_SIZE.
Referenced by WaveClip::Append(), Sequence::Append(), ComputeLegacySummaryInfo(), Sequence::ConvertToSampleFormat(), Sequence::Copy(), Sequence::CopyWrite(), ODFlacDecoder::Decode(), Sequence::Delete(), AudioIO::FillBuffers(), EffectNyquist::GetCallback(), BlockFile::GetMinMax(), PCMImportFileHandle::Import(), ImportRaw(), Mixer::Mixer(), Sequence::Paste(), SimpleBlockFile::ReadData(), PCMAliasBlockFile::ReadData(), ODPCMAliasBlockFile::ReadData(), LegacyBlockFile::ReadData(), RemoveDependencies(), RingBuffer::RingBuffer(), Sequence::Set(), ODPCMAliasBlockFile::WriteSummary(), and AliasBlockFile::WriteSummary().
Variable Documentation
Dither gDitherAlgorithm
Dither::DitherType gHighQualityDither = Dither::none
Referenced by CopySamples(), and InitDitherers().
Dither::DitherType gLowQualityDither = Dither::none
Referenced by CopySamples(), and InitDitherers().