Audacity: SoundActivatedRecord Class Reference
SoundActivatedRecord Class Reference
Configures sound activated recording.
#include <SoundActivatedRecord.h>
Public Member Functions
SoundActivatedRecord (wxWindow *parent)
~SoundActivatedRecord ()
Private Member Functions
void OnOK (wxCommandEvent &event)
void PopulateOrExchange (ShuttleGui &S)
DECLARE_EVENT_TABLE ()
Detailed Description
Configures sound activated recording.
Constructor & Destructor Documentation
SoundActivatedRecord::SoundActivatedRecord (wxWindow * parent)
References eIsCreatingFromPrefs.
SoundActivatedRecord::~SoundActivatedRecord ()
Member Function Documentation
SoundActivatedRecord::DECLARE_EVENT_TABLE () [private]
void SoundActivatedRecord::OnOK (wxCommandEvent & event) [private]
References eIsSavingToPrefs, and PopulateOrExchange().
void SoundActivatedRecord::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndVerticalLay(), ENV_DB_RANGE, gPrefs, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartVerticalLay(), and ShuttleGuiBase::TieSlider().
Referenced by OnOK().
The documentation for this class was generated from the following files:
SoundActivatedRecord.h
SoundActivatedRecord.cpp