Audacity: OptionValidator Class Reference
OptionValidator Class Reference
Parameter must be one of the defined options.
#include <Validators.h>
Public Member Functions
void AddOption (const wxString &option)
void AddOptions (const wxArrayString &options)
virtual bool Validate (const wxVariant &v)
Judge whether the passed value satisfies the Validator.
virtual wxString GetDescription () const
virtual Validator * GetClone () const
This MUST be overridden, to avoid slicing!
Private Attributes
wxArrayString mOptions
Detailed Description
Parameter must be one of the defined options.
Member Function Documentation
void OptionValidator::AddOption (const wxString & option) [inline]
References mOptions.
Referenced by SetTrackInfoCommandType::BuildSignature(), SetProjectInfoCommandType::BuildSignature(), SelectCommandType::BuildSignature(), ScreenshotCommandType::BuildSignature(), ExportCommandType::BuildSignature(), GetTrackInfoCommandType::BuildSignature(), and GetProjectInfoCommandType::BuildSignature().
void OptionValidator::AddOptions (const wxArrayString & options) [inline]
References mOptions.
virtual Validator* OptionValidator::GetClone () const [inline, virtual]
This MUST be overridden, to avoid slicing!
Reimplemented from Validator.
References mOptions.
virtual wxString OptionValidator::GetDescription () const [inline, virtual]
Return a description (for error messages) should be of the form 'v must be $description'
Reimplemented from Validator.
References mOptions.
virtual bool OptionValidator::Validate (const wxVariant & v) [inline, virtual]
Judge whether the passed value satisfies the Validator.
Reimplemented from Validator.
References mOptions, and Validator::SetConverted().
Member Data Documentation
wxArrayString OptionValidator::mOptions [private]
Referenced by AddOption(), AddOptions(), GetClone(), GetDescription(), and Validate().
The documentation for this class was generated from the following file:
Validators.h