Audacity: EqualizationDialog Class Reference
EqualizationDialog Class Reference
Dialog used with EffectEqualization.
#include <Equalization.h>
Public Member Functions
EqualizationDialog (EffectEqualization *effect, double loFreq, double hiFreq, float *filterFuncR, float *filterFuncI, long windowSize, wxString CurveName, bool disallowCustom, wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE)
~EqualizationDialog ()
virtual bool Validate ()
virtual bool TransferDataToWindow ()
virtual bool TransferDataFromWindow ()
virtual bool CalcFilter ()
void EnvelopeUpdated ()
void EnvelopeUpdated (Envelope *env, bool lin)
Public Attributes
wxRadioButton * mFaderOrDraw [2]
wxChoice * mInterpChoice
wxCheckBox * mLinFreq
int M
wxString curveName
bool linCheck
float dBMin
float dBMax
double whens [NUM_PTS]
double whenSliders [NUMBER_OF_BANDS+1]
int bandsInUse
bool drawMode
int interp
bool drawGrid
RulerPanel * dBRuler
RulerPanel * freqRuler
Static Public Attributes
static const double thirdOct []
Private Types
enum {
ID_FILTERPANEL = 10000, ID_LENGTH, ID_DBMAX, ID_DBMIN,
ID_CURVE, ID_SAVEAS, ID_DELETE, ID_CLEAR,
ID_INVERT, drawRadioID, sliderRadioID, ID_INTERP,
ID_LIN_FREQ, GridOnOffID, ID_SLIDER
}
Private Member Functions
void MakeEqualizationDialog ()
void CreateChoice ()
void LoadDefaultCurves ()
void LoadCurves ()
void SaveCurves ()
void Select (int sel)
void setCurve (int currentCurve)
void setCurve (wxString curveName)
void setCurve (void)
void GraphicEQ (Envelope *env)
void spline (double x[], double y[], int n, double y2[])
double splint (double x[], double y[], int n, double y2[], double xr)
void LayoutEQSliders ()
bool SaveAs ()
void RevertCustom ()
void Finish (bool ok)
bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
XMLTagHandler * HandleXMLChild (const wxChar *tag)
void WriteXML (XMLWriter &xmlFile)
void OnPaint (wxPaintEvent &event)
void OnSize (wxSizeEvent &event)
void OnErase (wxEraseEvent &event)
void OnSlider (wxCommandEvent &event)
void OnInterp (wxCommandEvent &event)
void OnSliderM (wxCommandEvent &event)
void OnSliderDBMAX (wxCommandEvent &event)
void OnSliderDBMIN (wxCommandEvent &event)
void OnDrawRadio (wxCommandEvent &event)
void OnSliderRadio (wxCommandEvent &event)
void OnLinFreq (wxCommandEvent &event)
void UpdateGraphic (void)
void EnvLogToLin (void)
void EnvLinToLog (void)
void ErrMin (void)
void OnCurve (wxCommandEvent &event)
void OnSaveAs (wxCommandEvent &event)
void OnDelete (wxCommandEvent &event)
void OnClear (wxCommandEvent &event)
void OnInvert (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
void OnOk (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void OnGridOnOff (wxCommandEvent &event)
Private Attributes
EffectEqualization * m_pEffect
bool mDisallowCustom
double mLoFreq
double mHiFreq
float * mFilterFuncR
float * mFilterFuncI
long mWindowSize
bool mDirty
wxSlider * m_sliders [NUMBER_OF_BANDS]
int m_sliders_old [NUMBER_OF_BANDS]
double m_EQVals [NUMBER_OF_BANDS+1]
EqualizationPanel * mPanel
Envelope * mLogEnvelope
Envelope * mLinEnvelope
wxBoxSizer * mCurveSizer
wxChoice * mCurve
wxButton * mDelete
wxButton * mSaveAs
wxStaticText * mMText
wxStaticText * octText
wxSlider * MSlider
wxSlider * dBMinSlider
wxSlider * dBMaxSlider
wxBoxSizer * szrC
wxBoxSizer * szrG
wxBoxSizer * szrV
wxBoxSizer * szrH
wxBoxSizer * szrI
wxBoxSizer * szrL
wxBoxSizer * szr3
wxBoxSizer * szr4
wxBoxSizer * szr2
wxFlexGridSizer * szr1
wxSize size
wxCheckBox * mGridOnOff
EQCurveArray mCurves
EQCurve mCustomBackup
Detailed Description
Dialog used with EffectEqualization.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
ID_FILTERPANEL
ID_LENGTH
ID_DBMAX
ID_DBMIN
ID_CURVE
ID_SAVEAS
ID_DELETE
ID_CLEAR
ID_INVERT
drawRadioID
sliderRadioID
ID_INTERP
ID_LIN_FREQ
GridOnOffID
ID_SLIDER
Constructor & Destructor Documentation
EqualizationDialog::EqualizationDialog (EffectEqualization * effect, double loFreq, double hiFreq, float * filterFuncR, float * filterFuncI, long windowSize, wxString CurveName, bool disallowCustom, wxWindow * parent, wxWindowID id, const wxString & title, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE)
EqualizationDialog::~EqualizationDialog ()
References mLinEnvelope, and mLogEnvelope.
Member Function Documentation
bool EqualizationDialog::CalcFilter () [virtual]
References FFT(), Envelope::GetValue(), InverseRealFFT(), M, M_PI, mFaderOrDraw, mFilterFuncI, mFilterFuncR, mHiFreq, mLinEnvelope, mLinFreq, mLoFreq, mLogEnvelope, mWindowSize, and RealFFT().
Referenced by EffectEqualization::DontPromptUser(), and EqualizationPanel::Recalc().
void EqualizationDialog::CreateChoice () [private]
References ID_CURVE, mCurve, mCurves, and mCurveSizer.
Referenced by MakeEqualizationDialog(), and SaveAs().
void EqualizationDialog::EnvelopeUpdated (Envelope * env, bool lin)
References Envelope::GetNumberOfPoints(), Envelope::GetPoints(), mCurves, mDirty, mHiFreq, and Select().
void EqualizationDialog::EnvelopeUpdated ()
References mFaderOrDraw, mLinEnvelope, mLinFreq, and mLogEnvelope.
Referenced by EnvLinToLog(), ErrMin(), OnClear(), OnDrawRadio(), OnInterp(), OnInvert(), EqualizationPanel::OnMouseEvent(), OnSlider(), and setCurve().
void EqualizationDialog::EnvLinToLog (void) [private]
References EnvelopeUpdated(), Envelope::Flatten(), Envelope::GetNumberOfPoints(), Envelope::GetPoints(), Envelope::Insert(), mHiFreq, mLinEnvelope, mLogEnvelope, Envelope::Move(), and Envelope::SetTrackLen().
Referenced by OnInvert(), OnLinFreq(), and UpdateGraphic().
void EqualizationDialog::EnvLogToLin (void) [private]
References Envelope::Flatten(), Envelope::GetNumberOfPoints(), Envelope::GetPoints(), Envelope::Insert(), mHiFreq, mLinEnvelope, mLogEnvelope, Envelope::Move(), and Envelope::SetTrackLen().
Referenced by OnDrawRadio(), OnInvert(), and OnLinFreq().
void EqualizationDialog::ErrMin (void) [private]
References bandsInUse, Envelope::CopyFrom(), EnvelopeUpdated(), Envelope::Flatten(), Envelope::GetValue(), GraphicEQ(), m_EQVals, mCurves, Envelope::Mirror(), mLogEnvelope, NUM_PTS, Select(), Envelope::SetInterpolateDB(), Envelope::SetTrackLen(), and whens.
Referenced by UpdateGraphic().
void EqualizationDialog::Finish (bool ok) [private]
References mLinEnvelope, mLogEnvelope, and mPanel.
Referenced by OnCancel(), and OnOk().
void EqualizationDialog::GraphicEQ (Envelope * env) [private]
References bandsInUse, Envelope::Flatten(), Envelope::Insert(), m_EQVals, M_PI, mInterpChoice, Envelope::Move(), mPanel, NUM_PTS, NUMBER_OF_BANDS, EqualizationPanel::RecalcRequired, Envelope::SetTrackLen(), spline(), splint(), whens, and whenSliders.
Referenced by ErrMin(), OnInterp(), OnInvert(), OnSlider(), and UpdateGraphic().
XMLTagHandler * EqualizationDialog::HandleXMLChild (const wxChar * tag) [private, virtual]
Implements XMLTagHandler.
bool EqualizationDialog::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [private, virtual]
Implements XMLTagHandler.
References Internat::CompatibleToDouble(), XMLValueChecker::IsGoodString(), and mCurves.
void EqualizationDialog::LayoutEQSliders () [private]
References mHiFreq, mLoFreq, NUMBER_OF_BANDS, szr1, szr2, szrG, and thirdOct.
Referenced by OnSize(), TransferDataFromWindow(), and UpdateGraphic().
void EqualizationDialog::LoadCurves () [private]
References FileNames::DataDir(), XMLFileReader::GetErrorStr(), LoadDefaultCurves(), mCurves, and XMLFileReader::Parse().
void EqualizationDialog::LoadDefaultCurves () [private]
References EffectEqualization::curvex, EffectEqualization::curvey, mCurves, EffectEqualization::nCurvePoints, EffectEqualization::nCurveTypes, and SaveCurves().
Referenced by LoadCurves().
void EqualizationDialog::MakeEqualizationDialog () [private]
Next row of wxFlexGridSizer
References CreateChoice(), CreateStdButtonSizer(), dBMaxSlider, dBMinSlider, dBRuler, drawRadioID, eCancelButton, eOkButton, ePreviewButton, freqRuler, Ruler::GetMaxSize(), GridOnOffID, ID_CLEAR, ID_DBMAX, ID_DBMIN, ID_DELETE, ID_FILTERPANEL, ID_INTERP, ID_INVERT, ID_LENGTH, ID_LIN_FREQ, ID_SAVEAS, ID_SLIDER, Ruler::IntFormat, label, Ruler::LinearDBFormat, M, m_EQVals, m_sliders, m_sliders_old, mCurveSizer, mDelete, mFaderOrDraw, mFilterFuncI, mFilterFuncR, mGridOnOff, mHiFreq, mInterpChoice, mLinFreq, mLoFreq, mLogEnvelope, mMText, mPanel, mSaveAs, MSlider, mWindowSize, name, NUM_INTERP_CHOICES, NUMBER_OF_BANDS, OnErase(), RulerPanel::ruler, Ruler::SetBounds(), Ruler::SetFlip(), Ruler::SetFormat(), Ruler::SetLabelEdges(), Ruler::SetLog(), Ruler::SetOrientation(), Ruler::SetRange(), Ruler::SetUnits(), sliderRadioID, szr1, szr2, szr3, szr4, szrC, szrG, szrH, szrI, szrL, szrV, thirdOct, and wxSliderBugfix.
void EqualizationDialog::OnCancel (wxCommandEvent & event) [private]
References Finish(), mDisallowCustom, and RevertCustom().
void EqualizationDialog::OnClear (wxCommandEvent & event) [private]
References bandsInUse, drawMode, EnvelopeUpdated(), Envelope::Flatten(), m_EQVals, m_sliders, m_sliders_old, mLinEnvelope, mLogEnvelope, mPanel, EqualizationPanel::RecalcRequired, and Envelope::SetTrackLen().
void EqualizationDialog::OnCurve (wxCommandEvent & event) [private]
References drawMode, mCurve, setCurve(), and UpdateGraphic().
void EqualizationDialog::OnDelete (wxCommandEvent & event) [private]
References mCurve, mCurves, SaveCurves(), Select(), and setCurve().
void EqualizationDialog::OnDrawRadio (wxCommandEvent & event) [private]
References Envelope::Delete(), drawMode, EnvelopeUpdated(), EnvLogToLin(), freqRuler, Envelope::GetNumberOfPoints(), Envelope::GetPoints(), EqualizationPanel::mEnvelope, mHiFreq, mLinEnvelope, mLinFreq, mLogEnvelope, mPanel, EqualizationPanel::RecalcRequired, RulerPanel::ruler, Ruler::SetLog(), Ruler::SetRange(), szrG, szrH, szrI, szrL, and szrV.
void EqualizationDialog::OnErase (wxEraseEvent & event) [private]
Referenced by MakeEqualizationDialog().
void EqualizationDialog::OnGridOnOff (wxCommandEvent & event) [private]
void EqualizationDialog::OnInterp (wxCommandEvent & event) [private]
References EnvelopeUpdated(), GraphicEQ(), interp, mFaderOrDraw, mInterpChoice, and mLogEnvelope.
void EqualizationDialog::OnInvert (wxCommandEvent & event) [private]
References drawMode, EnvelopeUpdated(), EnvLinToLog(), EnvLogToLin(), Envelope::GetNumberOfPoints(), Envelope::GetPoints(), GraphicEQ(), m_EQVals, m_sliders, m_sliders_old, mHiFreq, mLinEnvelope, mLinFreq, mLogEnvelope, Envelope::Move(), mPanel, NUMBER_OF_BANDS, EqualizationPanel::Recalc(), and thirdOct.
void EqualizationDialog::OnLinFreq (wxCommandEvent & event) [private]
References EnvLinToLog(), EnvLogToLin(), freqRuler, linCheck, EqualizationPanel::mEnvelope, mHiFreq, mLinEnvelope, mLinFreq, mLoFreq, mLogEnvelope, mPanel, EqualizationPanel::Recalc(), RulerPanel::ruler, Ruler::SetLog(), and Ruler::SetRange().
Referenced by TransferDataToWindow().
void EqualizationDialog::OnOk (wxCommandEvent & event) [private]
References Envelope::Delete(), drawMode, Finish(), Envelope::GetNumberOfPoints(), Envelope::GetPoints(), mCurves, mDirty, mDisallowCustom, mLogEnvelope, SaveCurves(), Select(), TransferDataFromWindow(), and Validate().
void EqualizationDialog::OnPaint (wxPaintEvent & event) [private]
void EqualizationDialog::OnPreview (wxCommandEvent & event) [private]
References m_pEffect, mPanel, Effect::Preview(), EqualizationPanel::RecalcRequired, and TransferDataFromWindow().
void EqualizationDialog::OnSaveAs (wxCommandEvent & event) [private]
References SaveAs().
void EqualizationDialog::OnSize (wxSizeEvent & event) [private]
References LayoutEQSliders(), and mFaderOrDraw.
void EqualizationDialog::OnSlider (wxCommandEvent & event) [private]
References EnvelopeUpdated(), GraphicEQ(), m_EQVals, m_sliders, m_sliders_old, mHiFreq, mLogEnvelope, NUMBER_OF_BANDS, thirdOct, and wxSliderBugfix.
void EqualizationDialog::OnSliderDBMAX (wxCommandEvent & event) [private]
References TransferDataFromWindow().
void EqualizationDialog::OnSliderDBMIN (wxCommandEvent & event) [private]
References TransferDataFromWindow().
void EqualizationDialog::OnSliderM (wxCommandEvent & event) [private]
References mPanel, EqualizationPanel::RecalcRequired, and TransferDataFromWindow().
void EqualizationDialog::OnSliderRadio (wxCommandEvent & event) [private]
References UpdateGraphic().
void EqualizationDialog::RevertCustom () [private]
References mCurves, mCustomBackup, EQCurve::Name, and EQCurve::points.
Referenced by OnCancel(), and SaveCurves().
bool EqualizationDialog::SaveAs () [private]
References CreateChoice(), mCurves, name, SaveCurves(), and Select().
Referenced by OnSaveAs(), and Validate().
void EqualizationDialog::SaveCurves () [private]
References XMLFileWriter::Close(), FileNames::DataDir(), XMLFileWriterException::GetMessage(), mDisallowCustom, XMLFileWriter::Open(), RevertCustom(), and WriteXML().
Referenced by LoadDefaultCurves(), OnDelete(), OnOk(), and SaveAs().
void EqualizationDialog::Select (int sel) [private]
References curveName, mCurve, mCurves, and mDelete.
Referenced by EnvelopeUpdated(), ErrMin(), OnDelete(), OnOk(), SaveAs(), and setCurve().
void EqualizationDialog::setCurve (void) [private]
References mCurves.
Referenced by OnCurve(), OnDelete(), setCurve(), and TransferDataToWindow().
void EqualizationDialog::setCurve (wxString curveName) [private]
References mCurves, and setCurve().
void EqualizationDialog::setCurve (int currentCurve) [private]
References EnvelopeUpdated(), Envelope::Flatten(), Envelope::Insert(), mCurves, mHiFreq, mLinEnvelope, mLinFreq, mLogEnvelope, mPanel, EqualizationPanel::RecalcRequired, Select(), and Envelope::SetTrackLen().
void EqualizationDialog::spline (double x[], double y[], int n, double y2[]) [private]
Referenced by GraphicEQ().
double EqualizationDialog::splint (double x[], double y[], int n, double y2[], double xr) [private]
Referenced by GraphicEQ().
bool EqualizationDialog::TransferDataFromWindow () [virtual]
References EqualizationPanel::dBMax, dBMax, dBMaxSlider, EqualizationPanel::dBMin, dBMin, dBMinSlider, dBRuler, freqRuler, Ruler::GetMaxSize(), LayoutEQSliders(), EqualizationPanel::M, M, mMText, mPanel, MSlider, RulerPanel::ruler, Ruler::SetRange(), szr1, and szrG.
Referenced by OnOk(), OnPreview(), OnSliderDBMAX(), OnSliderDBMIN(), OnSliderM(), and TransferDataToWindow().
bool EqualizationDialog::TransferDataToWindow () [virtual]
References curveName, dBMax, dBMaxSlider, dBMin, dBMinSlider, drawGrid, drawMode, interp, linCheck, M, mFaderOrDraw, mGridOnOff, mInterpChoice, mLinFreq, MSlider, OnLinFreq(), setCurve(), TransferDataFromWindow(), and UpdateGraphic().
Referenced by EffectEqualization::DontPromptUser().
void EqualizationDialog::UpdateGraphic (void) [private]
References bandsInUse, drawMode, EnvLinToLog(), ErrMin(), freqRuler, Envelope::GetValue(), GraphicEQ(), Envelope::Insert(), LayoutEQSliders(), m_EQVals, m_sliders, m_sliders_old, EqualizationPanel::mEnvelope, mHiFreq, mLinEnvelope, mLinFreq, mLoFreq, mLogEnvelope, mPanel, NUMBER_OF_BANDS, RulerPanel::ruler, Ruler::SetLog(), Ruler::SetRange(), szrG, szrH, szrI, szrL, szrV, thirdOct, and whenSliders.
Referenced by OnCurve(), OnSliderRadio(), and TransferDataToWindow().
bool EqualizationDialog::Validate () [virtual]
References curveName, mDisallowCustom, and SaveAs().
Referenced by OnOk().
void EqualizationDialog::WriteXML (XMLWriter & xmlFile) [private]
References XMLWriter::EndTag(), mCurves, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
Referenced by SaveCurves().
Member Data Documentation
int EqualizationDialog::bandsInUse
Referenced by ErrMin(), GraphicEQ(), OnClear(), and UpdateGraphic().
wxString EqualizationDialog::curveName
Referenced by EffectEqualization::DontPromptUser(), EffectEqualization::PromptUser(), Select(), TransferDataToWindow(), and Validate().
float EqualizationDialog::dBMax
Referenced by EffectEqualization::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* EqualizationDialog::dBMaxSlider [private]
Referenced by MakeEqualizationDialog(), TransferDataFromWindow(), and TransferDataToWindow().
float EqualizationDialog::dBMin
Referenced by EffectEqualization::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* EqualizationDialog::dBMinSlider [private]
Referenced by MakeEqualizationDialog(), TransferDataFromWindow(), and TransferDataToWindow().
RulerPanel* EqualizationDialog::dBRuler
Referenced by MakeEqualizationDialog(), EqualizationPanel::OnPaint(), and TransferDataFromWindow().
bool EqualizationDialog::drawGrid
Referenced by EqualizationPanel::OnPaint(), EffectEqualization::PromptUser(), and TransferDataToWindow().
bool EqualizationDialog::drawMode
Referenced by OnClear(), OnCurve(), OnDrawRadio(), OnInvert(), OnOk(), EffectEqualization::PromptUser(), TransferDataToWindow(), and UpdateGraphic().
RulerPanel* EqualizationDialog::freqRuler
Referenced by MakeEqualizationDialog(), OnDrawRadio(), OnLinFreq(), EqualizationPanel::OnPaint(), TransferDataFromWindow(), and UpdateGraphic().
int EqualizationDialog::interp
Referenced by EffectEqualization::DontPromptUser(), OnInterp(), EffectEqualization::PromptUser(), and TransferDataToWindow().
bool EqualizationDialog::linCheck
Referenced by EffectEqualization::DontPromptUser(), OnLinFreq(), EffectEqualization::PromptUser(), and TransferDataToWindow().
int EqualizationDialog::M
Referenced by CalcFilter(), EffectEqualization::DontPromptUser(), MakeEqualizationDialog(), EffectEqualization::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
double EqualizationDialog::m_EQVals[NUMBER_OF_BANDS+1] [private]
Referenced by ErrMin(), GraphicEQ(), MakeEqualizationDialog(), OnClear(), OnInvert(), OnSlider(), and UpdateGraphic().
EffectEqualization* EqualizationDialog::m_pEffect [private]
Referenced by OnPreview().
wxSlider* EqualizationDialog::m_sliders[NUMBER_OF_BANDS] [private]
Referenced by MakeEqualizationDialog(), OnClear(), OnInvert(), OnSlider(), and UpdateGraphic().
int EqualizationDialog::m_sliders_old[NUMBER_OF_BANDS] [private]
Referenced by MakeEqualizationDialog(), OnClear(), OnInvert(), OnSlider(), and UpdateGraphic().
wxChoice* EqualizationDialog::mCurve [private]
Referenced by CreateChoice(), OnCurve(), OnDelete(), and Select().
EQCurveArray EqualizationDialog::mCurves [private]
Referenced by CreateChoice(), EnvelopeUpdated(), ErrMin(), HandleXMLTag(), LoadCurves(), LoadDefaultCurves(), OnDelete(), OnOk(), RevertCustom(), SaveAs(), Select(), setCurve(), and WriteXML().
wxBoxSizer* EqualizationDialog::mCurveSizer [private]
Referenced by CreateChoice(), and MakeEqualizationDialog().
EQCurve EqualizationDialog::mCustomBackup [private]
Referenced by RevertCustom().
wxButton* EqualizationDialog::mDelete [private]
Referenced by MakeEqualizationDialog(), and Select().
bool EqualizationDialog::mDirty [private]
Referenced by EnvelopeUpdated(), and OnOk().
bool EqualizationDialog::mDisallowCustom [private]
Referenced by OnCancel(), OnOk(), SaveCurves(), and Validate().
wxRadioButton* EqualizationDialog::mFaderOrDraw[2]
Referenced by CalcFilter(), EnvelopeUpdated(), MakeEqualizationDialog(), OnInterp(), EqualizationPanel::OnPaint(), OnSize(), and TransferDataToWindow().
float* EqualizationDialog::mFilterFuncI [private]
Referenced by CalcFilter(), and MakeEqualizationDialog().
float* EqualizationDialog::mFilterFuncR [private]
Referenced by CalcFilter(), and MakeEqualizationDialog().
wxCheckBox* EqualizationDialog::mGridOnOff [private]
Referenced by MakeEqualizationDialog(), and TransferDataToWindow().
double EqualizationDialog::mHiFreq [private]
Referenced by CalcFilter(), EnvelopeUpdated(), EnvLinToLog(), EnvLogToLin(), LayoutEQSliders(), MakeEqualizationDialog(), OnDrawRadio(), OnInvert(), OnLinFreq(), OnSlider(), setCurve(), and UpdateGraphic().
wxChoice* EqualizationDialog::mInterpChoice
Referenced by GraphicEQ(), MakeEqualizationDialog(), OnInterp(), and TransferDataToWindow().
Envelope* EqualizationDialog::mLinEnvelope [private]
Referenced by CalcFilter(), EnvelopeUpdated(), EnvLinToLog(), EnvLogToLin(), Finish(), OnClear(), OnDrawRadio(), OnInvert(), OnLinFreq(), setCurve(), UpdateGraphic(), and ~EqualizationDialog().
wxCheckBox* EqualizationDialog::mLinFreq
Referenced by CalcFilter(), EnvelopeUpdated(), MakeEqualizationDialog(), OnDrawRadio(), OnInvert(), OnLinFreq(), EqualizationPanel::OnPaint(), setCurve(), TransferDataToWindow(), and UpdateGraphic().
double EqualizationDialog::mLoFreq [private]
Referenced by CalcFilter(), LayoutEQSliders(), MakeEqualizationDialog(), OnLinFreq(), and UpdateGraphic().
Envelope* EqualizationDialog::mLogEnvelope [private]
Referenced by CalcFilter(), EnvelopeUpdated(), EnvLinToLog(), EnvLogToLin(), ErrMin(), Finish(), MakeEqualizationDialog(), OnClear(), OnDrawRadio(), OnInterp(), OnInvert(), OnLinFreq(), OnOk(), OnSlider(), setCurve(), UpdateGraphic(), and ~EqualizationDialog().
wxStaticText* EqualizationDialog::mMText [private]
Referenced by MakeEqualizationDialog(), and TransferDataFromWindow().
EqualizationPanel* EqualizationDialog::mPanel [private]
Referenced by Finish(), GraphicEQ(), MakeEqualizationDialog(), OnClear(), OnDrawRadio(), OnInvert(), OnLinFreq(), OnPreview(), OnSliderM(), setCurve(), TransferDataFromWindow(), and UpdateGraphic().
wxButton* EqualizationDialog::mSaveAs [private]
Referenced by MakeEqualizationDialog().
wxSlider* EqualizationDialog::MSlider [private]
Referenced by MakeEqualizationDialog(), TransferDataFromWindow(), and TransferDataToWindow().
long EqualizationDialog::mWindowSize [private]
Referenced by CalcFilter(), and MakeEqualizationDialog().
wxStaticText* EqualizationDialog::octText [private]
wxSize EqualizationDialog::size [private]
wxFlexGridSizer* EqualizationDialog::szr1 [private]
Referenced by LayoutEQSliders(), MakeEqualizationDialog(), and TransferDataFromWindow().
wxBoxSizer* EqualizationDialog::szr2 [private]
Referenced by LayoutEQSliders(), and MakeEqualizationDialog().
wxBoxSizer* EqualizationDialog::szr3 [private]
Referenced by MakeEqualizationDialog().
wxBoxSizer* EqualizationDialog::szr4 [private]
Referenced by MakeEqualizationDialog().
wxBoxSizer* EqualizationDialog::szrC [private]
Referenced by MakeEqualizationDialog().
wxBoxSizer* EqualizationDialog::szrG [private]
Referenced by LayoutEQSliders(), MakeEqualizationDialog(), OnDrawRadio(), TransferDataFromWindow(), and UpdateGraphic().
wxBoxSizer* EqualizationDialog::szrH [private]
Referenced by MakeEqualizationDialog(), OnDrawRadio(), and UpdateGraphic().
wxBoxSizer* EqualizationDialog::szrI [private]
Referenced by MakeEqualizationDialog(), OnDrawRadio(), and UpdateGraphic().
wxBoxSizer* EqualizationDialog::szrL [private]
Referenced by MakeEqualizationDialog(), OnDrawRadio(), and UpdateGraphic().
wxBoxSizer* EqualizationDialog::szrV [private]
Referenced by MakeEqualizationDialog(), OnDrawRadio(), and UpdateGraphic().
const double EqualizationDialog::thirdOct [static]
Initial value:
{
   20., 25., 31., 40., 50., 63., 80., 100., 125., 160., 200.,
   250., 315., 400., 500., 630., 800., 1000., 1250., 1600., 2000.,
   2500., 3150., 4000., 5000., 6300., 8000., 10000., 12500., 16000., 20000.,
}
Referenced by LayoutEQSliders(), MakeEqualizationDialog(), OnInvert(), OnSlider(), and UpdateGraphic().
double EqualizationDialog::whens[NUM_PTS]
Referenced by ErrMin(), and GraphicEQ().
double EqualizationDialog::whenSliders[NUMBER_OF_BANDS+1]
Referenced by GraphicEQ(), and UpdateGraphic().
The documentation for this class was generated from the following files:
Equalization.h
Equalization.cpp