Audacity: EffectNyquist Class Reference
EffectNyquist Class Reference
An Effect that calls up a Nyquist (XLISP) plug in, i.e. many possible effects from this one class.
#include <Nyquist.h>
Public Member Functions
EffectNyquist (wxString fName)
virtual ~EffectNyquist ()
bool SetXlispPath ()
bool LoadedNyFile ()
void Continue ()
void Break ()
void Stop ()
void SetCommand (wxString cmd)
wxString GetOutput ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool PromptUser ()
virtual bool Process ()
Private Member Functions
bool ProcessOne ()
int GetCallback (float *buffer, int channel, long start, long len, long totlen)
int PutCallback (float *buffer, int channel, long start, long len, long totlen)
void OutputCallback (int c)
void OSCallback ()
void Parse (wxString line)
void ParseFile ()
wxString UnQuote (wxString s)
double GetCtrlValue (wxString s)
Static Private Member Functions
static int StaticGetCallback (float *buffer, int channel, long start, long len, long totlen, void *userdata)
static int StaticPutCallback (float *buffer, int channel, long start, long len, long totlen, void *userdata)
static void StaticOutputCallback (int c, void *userdata)
static void StaticOSCallback (void *userdata)
Private Attributes
wxString mXlispPath
wxFileName mFileName
Name of the Nyquist script file this effect is loaded from.
wxDateTime mFileModified
When the script was last modified on disk.
bool mStop
bool mBreak
bool mCont
bool mCompiler
bool mIsSal
bool mExternal
bool mInteractive
bool mOK
wxString mCmd
wxString mName
Name of the Effect.
wxString mAction
wxString mInfo
bool mDebug
std::string mDebugOutput
NyqControlArray mControls
int mCurNumChannels
WaveTrack * mCurTrack [2]
sampleCount mCurStart [2]
sampleCount mCurLen
bool mFirstInGroup
double mOutputTime
int mCount
double mProgressIn
double mProgressOut
double mProgressTot
double mScale
samplePtr mCurBuffer [2]
sampleCount mCurBufferStart [2]
sampleCount mCurBufferLen [2]
WaveTrack * mOutputTrack [2]
wxArrayString mCategories
Detailed Description
An Effect that calls up a Nyquist (XLISP) plug in, i.e. many possible effects from this one class.
Constructor & Destructor Documentation
EffectNyquist::EffectNyquist (wxString fName)
Parameters:
fName File name of the Nyquist script defining this effect. If an empty string, then prompt the user for the Nyquist code to interpret.
References ADVANCED_EFFECT, BUILTIN_EFFECT, HIDDEN_EFFECT, mAction, mBreak, mCmd, mCompiler, mCont, mDebug, mExternal, mFileModified, mFileName, mInteractive, mIsSal, mName, mOK, mStop, ParseFile(), PROCESS_EFFECT, and Effect::SetEffectFlags().
EffectNyquist::~EffectNyquist () [virtual]
Member Function Documentation
void EffectNyquist::Break ()
References mBreak.
void EffectNyquist::Continue ()
References mCont.
int EffectNyquist::GetCallback (float * buffer, int channel, long start, long len, long totlen) [private]
References CopySamples(), floatSample, WaveTrack::GetBestBlockSize(), WaveTrack::GetIdealBlockSize(), mCurBuffer, mCurBufferLen, mCurBufferStart, mCurLen, mCurStart, mCurTrack, mProgressIn, mProgressOut, mProgressTot, mScale, NewSamples(), SAMPLE_SIZE, and Effect::TotalProgress().
Referenced by StaticGetCallback().
double EffectNyquist::GetCtrlValue (wxString s) [private]
References Internat::CompatibleToDouble(), TrackListCondIterator::First(), Effect::mTracks, and Track::Wave.
Referenced by PromptUser().
virtual wxString EffectNyquist::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectNyquist::GetEffectCategories () [inline, virtual]
virtual wxString EffectNyquist::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectNyquist::GetEffectName () [inline, virtual]
Get the name of the effect (taken from the script that is loaded). Note that this name is currently not translated because the translations system doesn't see the lisp files containing the Nyquist effect scripts.
Returns:
The name of the effect
Implements Effect.
wxString EffectNyquist::GetOutput ()
bool EffectNyquist::LoadedNyFile () [inline]
Referenced by LoadNyquistEffect().
void EffectNyquist::OSCallback () [private]
References mBreak, mCont, and mStop.
void EffectNyquist::OutputCallback (int c) [private]
References mDebug, mDebugOutput, and mExternal.
void EffectNyquist::Parse (wxString line) [private]
References ANALYZE_EFFECT, NyqControl::highStr, INSERT_EFFECT, NyqControl::label, NyqControl::lowStr, mAction, mCategories, mCompiler, mControls, mDebug, mInfo, mIsSal, mName, mOK, NyqControl::name, NYQ_CTRL_CHOICE, NYQ_CTRL_INT, NYQ_CTRL_REAL, NYQ_CTRL_STRING, PLUGIN_EFFECT, PROCESS_EFFECT, Effect::SetEffectFlags(), NyqControl::type, UNINITIALIZED_CONTROL, UnQuote(), NyqControl::val, NyqControl::valStr, and NyqControl::var.
Referenced by ParseFile(), and SetCommand().
void EffectNyquist::ParseFile () [private]
References mCmd, mControls, mFileName, mIsSal, mOK, Parse(), PLUGIN_EFFECT, PROCESS_EFFECT, and Effect::SetEffectFlags().
Referenced by EffectNyquist(), and PromptUser().
bool EffectNyquist::Process () [virtual]
Implements Effect.
References Track::All, Effect::CopyInputTracks(), TrackGroupIterator::First(), TrackListCondIterator::First(), Effect::GetEffectFlags(), Effect::GetNumWaveGroups(), mBreak, mCont, mCount, mCurLen, mCurNumChannels, mCurStart, mCurTrack, mDebug, mDebugOutput, mExternal, mFirstInGroup, mOutputTime, Effect::mOutputTracks, Effect::mParent, Effect::mProgress, mProgressIn, mProgressOut, mProgressTot, mScale, mStop, Effect::mT0, Effect::mT1, TrackListCondIterator::Next(), PROCESS_EFFECT, ProcessOne(), Effect::ReplaceProcessedTracks(), StaticOSCallback(), StaticOutputCallback(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectNyquist::ProcessOne () [private]
References LabelTrack::AddLabel(), Effect::AddToOutputTracks(), WaveTrack::ClearAndPaste(), DeleteSamples(), TrackGroupIterator::First(), TrackListIterator::First(), WaveTrack::Flush(), Effect::GetEffectFlags(), WaveTrack::GetEndTime(), WaveTrack::GetRate(), WaveTrack::GetSampleFormat(), Track::GetSelected(), INSERT_EFFECT, Track::IsSynchroSelected(), Track::Label, LAT1CTOWX, mCmd, mCompiler, mControls, mCurBuffer, mCurLen, mCurNumChannels, mCurTrack, mDebug, mExternal, Effect::mFactory, mFirstInGroup, mIsSal, mOutputTime, mOutputTrack, Effect::mOutputTracks, Effect::mParent, Effect::mT0, Effect::mT1, TrackFactory::NewLabelTrack(), TrackFactory::NewWaveTrack(), TrackGroupIterator::Next(), TrackListIterator::Next(), NYQ_CTRL_CHOICE, NYQ_CTRL_INT, NYQ_CTRL_REAL, NYQ_CTRL_STRING, StaticGetCallback(), StaticPutCallback(), Track::SyncAdjust(), and Internat::ToString().
Referenced by Process().
bool EffectNyquist::PromptUser () [virtual]
Reimplemented from Effect.
References eDebugID, NyquistInputDialog::GetCommand(), GetCtrlValue(), NyqControl::high, NyqControl::highStr, NyqControl::low, NyqControl::lowStr, mCmd, mControls, mDebug, mExternal, mFileModified, mFileName, mInfo, mInteractive, mName, Effect::mParent, NYQ_CTRL_CHOICE, NYQ_CTRL_INT, NYQ_CTRL_STRING, ParseFile(), SetXlispPath(), NyqControl::ticks, NyqControl::type, UNINITIALIZED_CONTROL, NyqControl::val, and NyqControl::valStr.
int EffectNyquist::PutCallback (float * buffer, int channel, long start, long len, long totlen) [private]
References floatSample, mOutputTrack, mProgressIn, mProgressOut, mProgressTot, mScale, and Effect::TotalProgress().
Referenced by StaticPutCallback().
void EffectNyquist::SetCommand (wxString cmd)
References HIDDEN_EFFECT, INSERT_EFFECT, mCmd, mControls, mExternal, mInteractive, mIsSal, mOK, Parse(), and Effect::SetEffectFlags().
bool EffectNyquist::SetXlispPath ()
References AudacityApp::AddUniquePathToPathList(), AudacityApp::audacityPathList, AudacityApp::FindFilesInPathList(), mXlispPath, and wxGetApp().
Referenced by PromptUser().
int EffectNyquist::StaticGetCallback (float * buffer, int channel, long start, long len, long totlen, void * userdata) [static, private]
References GetCallback().
Referenced by ProcessOne().
void EffectNyquist::StaticOSCallback (void * userdata) [static, private]
Referenced by Process().
void EffectNyquist::StaticOutputCallback (int c, void * userdata) [static, private]
Referenced by Process().
int EffectNyquist::StaticPutCallback (float * buffer, int channel, long start, long len, long totlen, void * userdata) [static, private]
References PutCallback().
Referenced by ProcessOne().
void EffectNyquist::Stop ()
References mStop.
wxString EffectNyquist::UnQuote (wxString s) [private]
Referenced by Parse().
Member Data Documentation
wxString EffectNyquist::mAction [private]
Referenced by EffectNyquist(), and Parse().
bool EffectNyquist::mBreak [private]
Referenced by Break(), EffectNyquist(), OSCallback(), and Process().
wxArrayString EffectNyquist::mCategories [private]
Referenced by Parse().
wxString EffectNyquist::mCmd [private]
Referenced by EffectNyquist(), ParseFile(), ProcessOne(), PromptUser(), and SetCommand().
bool EffectNyquist::mCompiler [private]
Referenced by EffectNyquist(), Parse(), and ProcessOne().
bool EffectNyquist::mCont [private]
Referenced by Continue(), EffectNyquist(), OSCallback(), and Process().
NyqControlArray EffectNyquist::mControls [private]
Referenced by Parse(), ParseFile(), ProcessOne(), PromptUser(), and SetCommand().
int EffectNyquist::mCount [private]
Referenced by Process().
samplePtr EffectNyquist::mCurBuffer[2] [private]
Referenced by GetCallback(), and ProcessOne().
sampleCount EffectNyquist::mCurBufferLen[2] [private]
Referenced by GetCallback().
sampleCount EffectNyquist::mCurBufferStart[2] [private]
Referenced by GetCallback().
sampleCount EffectNyquist::mCurLen [private]
Referenced by GetCallback(), Process(), and ProcessOne().
int EffectNyquist::mCurNumChannels [private]
Referenced by Process(), and ProcessOne().
sampleCount EffectNyquist::mCurStart[2] [private]
Referenced by GetCallback(), and Process().
WaveTrack* EffectNyquist::mCurTrack[2] [private]
Referenced by GetCallback(), Process(), and ProcessOne().
bool EffectNyquist::mDebug [private]
Referenced by EffectNyquist(), OutputCallback(), Parse(), Process(), ProcessOne(), and PromptUser().
std::string EffectNyquist::mDebugOutput [private]
Referenced by OutputCallback(), and Process().
bool EffectNyquist::mExternal [private]
Referenced by EffectNyquist(), OutputCallback(), Process(), ProcessOne(), PromptUser(), and SetCommand().
wxDateTime EffectNyquist::mFileModified [private]
When the script was last modified on disk.
Referenced by EffectNyquist(), and PromptUser().
wxFileName EffectNyquist::mFileName [private]
Name of the Nyquist script file this effect is loaded from.
Referenced by EffectNyquist(), ParseFile(), and PromptUser().
bool EffectNyquist::mFirstInGroup [private]
Referenced by Process(), and ProcessOne().
wxString EffectNyquist::mInfo [private]
Referenced by Parse(), and PromptUser().
bool EffectNyquist::mInteractive [private]
True if the code to execute is obtained interactively from the user via the "Nyquist Prompt", false for all other effects (lisp code read from files)
Referenced by EffectNyquist(), PromptUser(), and SetCommand().
bool EffectNyquist::mIsSal [private]
Referenced by EffectNyquist(), Parse(), ParseFile(), ProcessOne(), and SetCommand().
wxString EffectNyquist::mName [private]
Name of the Effect.
Referenced by EffectNyquist(), Parse(), and PromptUser().
bool EffectNyquist::mOK [private]
Referenced by EffectNyquist(), Parse(), ParseFile(), and SetCommand().
double EffectNyquist::mOutputTime [private]
Referenced by Process(), and ProcessOne().
WaveTrack* EffectNyquist::mOutputTrack[2] [private]
Referenced by ProcessOne(), and PutCallback().
double EffectNyquist::mProgressIn [private]
Referenced by GetCallback(), Process(), and PutCallback().
double EffectNyquist::mProgressOut [private]
Referenced by GetCallback(), Process(), and PutCallback().
double EffectNyquist::mProgressTot [private]
Referenced by GetCallback(), Process(), and PutCallback().
double EffectNyquist::mScale [private]
Referenced by GetCallback(), Process(), and PutCallback().
bool EffectNyquist::mStop [private]
Referenced by EffectNyquist(), OSCallback(), Process(), and Stop().
wxString EffectNyquist::mXlispPath [private]
Referenced by SetXlispPath().
The documentation for this class was generated from the following files:
Nyquist.h
Nyquist.cpp