Audacity: Shuttle Class Reference
Shuttle Class Reference
Moves data from one place to another, converting it as required.
#include <Shuttle.h>
Public Member Functions
Shuttle ()
virtual ~Shuttle ()
virtual bool TransferBool (const wxString &Name, bool &bValue, const bool &bDefault)
virtual bool TransferFloat (const wxString &Name, float &fValue, const float &fDefault)
virtual bool TransferDouble (const wxString &Name, double &dValue, const double &dDefault)
virtual bool TransferInt (const wxString &Name, int &iValue, const int &iDefault)
virtual bool TransferInt (const wxString &Name, wxLongLong_t &iValue, const wxLongLong_t &iDefault)
virtual bool TransferLongLong (const wxString &Name, wxLongLong_t &iValue, const wxLongLong_t &iDefault)
virtual bool TransferString (const wxString &Name, wxString &strValue, const wxString &strDefault)
virtual bool TransferEnum (const wxString &Name, int &iValue, const int nChoices, const wxString *pFirstStr)
virtual bool TransferWrappedType (const wxString &Name, WrappedType &W)
virtual bool ExchangeWithMaster (const wxString &Name)
Public Attributes
bool mbStoreInClient
wxString mValueString
Detailed Description
Moves data from one place to another, converting it as required.
Shuttle provides a base class for transfering parameter data into and out of clasess into some other structure. This is a common requirement and is needed for:
Prefs data
Command line parameter data
Project data in XML
The 'Master' is the string side of the shuttle transfer, the 'Client' is the binary data side of the transfer.
See also:
ShuttleBase
ShuttleGui
Constructor & Destructor Documentation
Shuttle::Shuttle ()
virtual Shuttle::~Shuttle () [inline, virtual]
Member Function Documentation
bool Shuttle::ExchangeWithMaster (const wxString & Name) [virtual]
Reimplemented in ShuttleCli, and ShuttlePrefs.
Referenced by TransferBool(), TransferDouble(), TransferEnum(), TransferFloat(), TransferInt(), TransferLongLong(), TransferString(), and TransferWrappedType().
bool Shuttle::TransferBool (const wxString & Name, bool & bValue, const bool & bDefault) [virtual]
Reimplemented in ShuttlePrefs.
References ExchangeWithMaster(), mbStoreInClient, and mValueString.
Referenced by EffectTimeScale::TransferParameters(), EffectNormalize::TransferParameters(), EffectEqualization::TransferParameters(), and EffectCompressor::TransferParameters().
bool Shuttle::TransferDouble (const wxString & Name, double & dValue, const double & dDefault) [virtual]
Reimplemented in ShuttlePrefs.
References ExchangeWithMaster(), mbStoreInClient, and mValueString.
Referenced by EffectTruncSilence::TransferParameters(), EffectTimeScale::TransferParameters(), EffectNormalize::TransferParameters(), EffectCompressor::TransferParameters(), EffectChangeTempo::TransferParameters(), EffectChangeSpeed::TransferParameters(), EffectChangePitch::TransferParameters(), and EffectAutoDuck::TransferParameters().
bool Shuttle::TransferEnum (const wxString & Name, int & iValue, const int nChoices, const wxString * pFirstStr) [virtual]
References ExchangeWithMaster(), mbStoreInClient, and mValueString.
Referenced by EffectTruncSilence::TransferParameters(), EffectSpikeCleaner::TransferParameters(), EffectLeveller::TransferParameters(), and EffectEqualization::TransferParameters().
bool Shuttle::TransferFloat (const wxString & Name, float & fValue, const float & fDefault) [virtual]
References ExchangeWithMaster(), mbStoreInClient, and mValueString.
Referenced by EffectWahwah::TransferParameters(), EffectPhaser::TransferParameters(), EffectEcho::TransferParameters(), EffectBassBoost::TransferParameters(), and EffectAmplify::TransferParameters().
bool Shuttle::TransferInt (const wxString & Name, wxLongLong_t & iValue, const wxLongLong_t & iDefault) [virtual]
References TransferLongLong().
bool Shuttle::TransferInt (const wxString & Name, int & iValue, const int & iDefault) [virtual]
Reimplemented in ShuttlePrefs.
References ExchangeWithMaster(), mbStoreInClient, and mValueString.
Referenced by EffectTruncSilence::TransferParameters(), EffectSpikeCleaner::TransferParameters(), EffectRepeat::TransferParameters(), EffectPhaser::TransferParameters(), EffectLeveller::TransferParameters(), EffectFindClipping::TransferParameters(), EffectEqualization::TransferParameters(), and EffectClickRemoval::TransferParameters().
bool Shuttle::TransferLongLong (const wxString & Name, wxLongLong_t & iValue, const wxLongLong_t & iDefault) [virtual]
Todo:
Fix for long long values.
References ExchangeWithMaster(), mbStoreInClient, and mValueString.
Referenced by TransferInt().
bool Shuttle::TransferString (const wxString & Name, wxString & strValue, const wxString & strDefault) [virtual]
Reimplemented in ShuttlePrefs.
References ExchangeWithMaster(), mbStoreInClient, and mValueString.
Referenced by CommandBuilder::BuildCommand(), and EffectEqualization::TransferParameters().
bool Shuttle::TransferWrappedType (const wxString & Name, WrappedType & W) [virtual]
Reimplemented in ShuttlePrefs.
References ExchangeWithMaster(), mbStoreInClient, mValueString, WrappedType::ReadAsString(), and WrappedType::WriteToAsString().
Referenced by ShuttleGuiBase::DoDataShuttle().
Member Data Documentation
bool Shuttle::mbStoreInClient
Referenced by CommandBuilder::BuildCommand(), Effect::DoEffect(), ShuttleCli::ExchangeWithMaster(), BatchCommands::GetCurrentParamsFor(), BatchCommands::SetCurrentParametersFor(), ShuttleGui::ShuttleGui(), ShuttlePrefs::TransferBool(), TransferBool(), ShuttlePrefs::TransferDouble(), TransferDouble(), TransferEnum(), TransferFloat(), ShuttlePrefs::TransferInt(), TransferInt(), TransferLongLong(), ShuttlePrefs::TransferString(), TransferString(), and TransferWrappedType().
wxString Shuttle::mValueString
Referenced by ShuttleCli::ExchangeWithMaster(), TransferBool(), TransferDouble(), TransferEnum(), TransferFloat(), TransferInt(), TransferLongLong(), TransferString(), and TransferWrappedType().
The documentation for this class was generated from the following files:
Shuttle.h
Shuttle.cpp