Audacity: MixerToolBar Class Reference
MixerToolBar Class Reference
A ToolBar that provides the record and playback volume settings.
#include <MixerToolBar.h>
Public Member Functions
MixerToolBar ()
virtual ~MixerToolBar ()
void Create (wxWindow *parent)
void RecreateTipWindows ()
void UpdatePrefs ()
void UpdateControls ()
void SetMixer (wxCommandEvent &event)
virtual void Populate ()
virtual void Repaint (wxDC *dc)
virtual void EnableDisableButtons ()
void OnFocus (wxFocusEvent &event)
void OnCaptureKey (wxCommandEvent &event)
void OnSlider (wxCommandEvent &event)
void ShowOutputGainDialog ()
void ShowInputGainDialog ()
void ShowInputSourceDialog ()
void AdjustOutputGain (int adj)
void AdjustInputGain (int adj)
DECLARE_CLASS (MixerToolBar)
DECLARE_EVENT_TABLE ()
Private Member Functions
void InitializeMixerToolBar ()
void SetToolTips ()
Private Attributes
wxBitmap * mPlayBitmap
wxBitmap * mRecordBitmap
ASlider * mInputSlider
ASlider * mOutputSlider
wxChoice * mInputSourceChoice
Detailed Description
A ToolBar that provides the record and playback volume settings.
Constructor & Destructor Documentation
MixerToolBar::MixerToolBar ()
Methods for MixerToolBar
MixerToolBar::~MixerToolBar () [virtual]
References mPlayBitmap, and mRecordBitmap.
Member Function Documentation
void MixerToolBar::AdjustInputGain (int adj)
References ASlider::Decrease(), ASlider::Increase(), mInputSlider, SetMixer(), and UpdateControls().
Referenced by AudacityProject::OnInputGainDec(), and AudacityProject::OnInputGainInc().
void MixerToolBar::AdjustOutputGain (int adj)
References ASlider::Decrease(), ASlider::Increase(), mOutputSlider, SetMixer(), and UpdateControls().
Referenced by AudacityProject::OnOutputGainDec(), and AudacityProject::OnOutputGainInc().
void MixerToolBar::Create (wxWindow * parent) [virtual]
Reimplemented from ToolBar.
MixerToolBar::DECLARE_CLASS (MixerToolBar)
Reimplemented from ToolBar.
MixerToolBar::DECLARE_EVENT_TABLE ()
Reimplemented from ToolBar.
virtual void MixerToolBar::EnableDisableButtons () [inline, virtual]
Implements ToolBar.
void MixerToolBar::InitializeMixerToolBar () [private]
void MixerToolBar::OnCaptureKey (wxCommandEvent & event)
References mInputSlider, mInputSourceChoice, and mOutputSlider.
void MixerToolBar::OnFocus (wxFocusEvent & event)
Referenced by Populate().
void MixerToolBar::OnSlider (wxCommandEvent & event)
void MixerToolBar::Populate () [virtual]
Implements ToolBar.
References ToolBar::Add(), ThemeBase::Bitmap(), ASlider::Enable(), gAudioIO, AudioIO::GetInputSourceNames(), AudioIO::GetMixer(), AudioIO::InputMixerWorks(), mInputSlider, mInputSourceChoice, mOutputSlider, mPlayBitmap, mRecordBitmap, OnFocus(), SetToolTips(), theTheme, and UpdateControls().
void MixerToolBar::RecreateTipWindows ()
References mInputSlider, mOutputSlider, and ASlider::RecreateTipWin().
Referenced by AudacityProject::AudacityProject().
virtual void MixerToolBar::Repaint (wxDC * dc) [inline, virtual]
Implements ToolBar.
void MixerToolBar::SetMixer (wxCommandEvent & event)
References gAudioIO, ASlider::Get(), mInputSlider, mInputSourceChoice, mOutputSlider, and AudioIO::SetMixer().
Referenced by AdjustInputGain(), AdjustOutputGain(), ShowInputGainDialog(), and ShowOutputGainDialog().
void MixerToolBar::SetToolTips () [private]
References ASlider::IsEnabled(), mInputSlider, and mOutputSlider.
Referenced by Populate(), and UpdatePrefs().
void MixerToolBar::ShowInputGainDialog ()
References mInputSlider, SetMixer(), ASlider::ShowDialog(), and UpdateControls().
Referenced by AudacityProject::OnInputGain().
void MixerToolBar::ShowInputSourceDialog ()
References ShuttleGuiBase::AddChoice(), ShuttleGui::AddStandardButtons(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndVerticalLay(), mInputSourceChoice, ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartVerticalLay().
Referenced by AudacityProject::OnInputSource().
void MixerToolBar::ShowOutputGainDialog ()
References mOutputSlider, SetMixer(), ASlider::ShowDialog(), and UpdateControls().
Referenced by AudacityProject::OnOutputGain().
void MixerToolBar::UpdateControls ()
References gAudioIO, ASlider::Get(), AudioIO::GetMixer(), mInputSlider, mInputSourceChoice, mOutputSlider, ASlider::Set(), and AudioIO::SetMixer().
Referenced by AdjustInputGain(), AdjustOutputGain(), AudacityProject::OnTimer(), Populate(), ShowInputGainDialog(), and ShowOutputGainDialog().
void MixerToolBar::UpdatePrefs () [virtual]
Reimplemented from ToolBar.
References ASlider::Enable(), gAudioIO, AudioIO::GetInputSourceNames(), AudioIO::GetMixer(), AudioIO::InputMixerWorks(), mInputSlider, mInputSourceChoice, ToolBar::SetLabel(), SetToolTips(), and ToolBar::Updated().
Member Data Documentation
ASlider* MixerToolBar::mInputSlider [private]
Referenced by AdjustInputGain(), OnCaptureKey(), Populate(), RecreateTipWindows(), SetMixer(), SetToolTips(), ShowInputGainDialog(), UpdateControls(), and UpdatePrefs().
wxChoice* MixerToolBar::mInputSourceChoice [private]
Referenced by OnCaptureKey(), Populate(), SetMixer(), ShowInputSourceDialog(), UpdateControls(), and UpdatePrefs().
ASlider* MixerToolBar::mOutputSlider [private]
Referenced by AdjustOutputGain(), OnCaptureKey(), Populate(), RecreateTipWindows(), SetMixer(), SetToolTips(), ShowOutputGainDialog(), and UpdateControls().
wxBitmap* MixerToolBar::mPlayBitmap [private]
Referenced by Populate(), and ~MixerToolBar().
wxBitmap* MixerToolBar::mRecordBitmap [private]
Referenced by Populate(), and ~MixerToolBar().
The documentation for this class was generated from the following files:
MixerToolBar.h
MixerToolBar.cpp