Audacity: ExportMultiple Class Reference
ExportMultiple Class Reference
Presents a dialog box allowing the user to export multiple files either by exporting each track as a separate file, or by exporting each label as a separate file.
#include <ExportMultiple.h>
Public Member Functions
ExportMultiple (AudacityProject *parent)
virtual ~ExportMultiple ()
int ShowModal ()
Private Member Functions
void CanExport ()
void CountTracksAndLabels ()
bool DirOk ()
int ExportMultipleByLabel (bool byName, wxString prefix, bool addNumber)
Export multiple labeled regions of the project to separate files.
int ExportMultipleByTrack (bool byName, wxString prefix, bool addNumber)
Export each track in the project to a separate file.
int DoExport (int channels, wxFileName name, bool selectedOnly, double t0, double t1, Tags tags)
wxString MakeFileName (wxString input)
Takes an arbitrary text string and converts it to a form that can be used as a file name, if necessary prompting the user to edit the file name produced.
void PopulateOrExchange (ShuttleGui &S)
void EnableControls ()
void OnFormat (wxCommandEvent &event)
void OnOptions (wxCommandEvent &event)
void OnCreate (wxCommandEvent &event)
void OnChoose (wxCommandEvent &event)
void OnLabel (wxCommandEvent &event)
void OnFirst (wxCommandEvent &event)
void OnFirstFileName (wxCommandEvent &event)
void OnTrack (wxCommandEvent &event)
void OnByName (wxCommandEvent &event)
void OnByNumber (wxCommandEvent &event)
void OnPrefix (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void OnExport (wxCommandEvent &event)
Private Attributes
Exporter mExporter
ExportPluginArray mPlugins
AudacityProject * mProject
TrackList * mTracks
TrackListIterator mIterator
LabelTrack * mLabels
int mNumLabels
int mNumWaveTracks
wxArrayPtrVoid mSelected
int mFilterIndex
int mPluginIndex
int mSubFormatIndex
bool mInitialized
wxArrayString mExported
wxArrayString exclude
wxChoice * mFormat
wxButton * mOptions
wxTextCtrl * mDir
wxButton * mCreate
wxButton * mChoose
wxRadioButton * mLabel
wxStaticText * mLabelLabel
wxCheckBox * mFirst
wxStaticText * mFirstFileLabel
wxTextCtrl * mFirstFileName
wxRadioButton * mTrack
wxStaticText * mTrackLabel
wxRadioButton * mByNumberAndName
wxRadioButton * mByName
wxRadioButton * mByNumber
wxStaticText * mPrefixLabel
wxTextCtrl * mPrefix
wxCheckBox * mOverwrite
wxButton * mCancel
wxButton * mExport
Detailed Description
Presents a dialog box allowing the user to export multiple files either by exporting each track as a separate file, or by exporting each label as a separate file.
Constructor & Destructor Documentation
ExportMultiple::ExportMultiple (AudacityProject * parent)
ExportMultiple::~ExportMultiple () [virtual]
Member Function Documentation
void ExportMultiple::CanExport () [private]
void ExportMultiple::CountTracksAndLabels () [private]
References TrackListIterator::First(), Track::GetKind(), Track::GetLinked(), LabelTrack::GetNumLabels(), Track::Label, mIterator, mLabels, mNumLabels, mNumWaveTracks, mTracks, TrackListIterator::Next(), and Track::Wave.
bool ExportMultiple::DirOk () [private]
References mDir.
Referenced by OnExport().
int ExportMultiple::DoExport (int channels, wxFileName name, bool selectedOnly, double t0, double t1, Tags tags) [private]
Export one file of an export multiple set
Called once for each file in the list to do a (non-interactive) export
Parameters:
channels Number of channels to export
name The file name (and path) to export to
selectedOnly Should we export the selected tracks only?
t0 Start time for export
t1 End time for export
tags Metadata to include in the file (if possible).
References DirManager::EnsureSafeFilename(), eProgressStopped, eProgressSuccess, AudacityProject::GetDirManager(), mExported, mOverwrite, mPluginIndex, mPlugins, mProject, and mSubFormatIndex.
Referenced by ExportMultipleByLabel(), and ExportMultipleByTrack().
void ExportMultiple::EnableControls () [private]
References mByName, mByNumber, mByNumberAndName, mExport, mFirst, mFirstFileLabel, mFirstFileName, mInitialized, mLabel, mPrefix, and mPrefixLabel.
Referenced by OnByName(), OnByNumber(), OnFirst(), OnFirstFileName(), OnFormat(), OnLabel(), OnPrefix(), OnTrack(), and ShowModal().
int ExportMultiple::ExportMultipleByLabel (bool byName, wxString prefix, bool addNumber) [private]
Export multiple labeled regions of the project to separate files.
Uses a single label track in the project to split up the audio into a series of sections, each of which is exported to a separate file.
Parameters:
byName Controls whether files are named after the text in the labels that define them (true), or just numbered (false).
prefix The string used to prefix the file number if files are being numbered rather than named
References channels, ExportKit::destfile, DoExport(), eProgressStopped, eProgressSuccess, ExportKit::filetags, TrackList::GetEndTime(), LabelTrack::GetLabel(), TrackList::GetNumExportChannels(), AudacityProject::GetShowId3Dialog(), AudacityProject::GetTags(), MakeFileName(), FileNames::MakeNameUnique(), mDir, mFirst, mFirstFileName, mLabels, mNumLabels, mPluginIndex, mPlugins, mProject, mSubFormatIndex, mTracks, name, Tags::SetTag(), Tags::ShowEditDialog(), LabelStruct::t, ExportKit::t0, ExportKit::t1, LabelStruct::t1, TAG_TITLE, TAG_TRACK, and LabelStruct::title.
Referenced by OnExport().
int ExportMultiple::ExportMultipleByTrack (bool byName, wxString prefix, bool addNumber) [private]
Export each track in the project to a separate file.
Parameters:
byName Controls whether files are named after the track names (true), or just numbered (false).
prefix The string used to prefix the file number if files are being numbered rather than named
< Array of pointers to the tracks which were selected when we started
References channels, ExportKit::destfile, DoExport(), eProgressStopped, eProgressSuccess, ExportKit::filetags, TrackListIterator::First(), Track::GetChannel(), Track::GetEndTime(), Track::GetKind(), Track::GetLinked(), Track::GetName(), Track::GetSelected(), AudacityProject::GetShowId3Dialog(), Track::GetStartTime(), AudacityProject::GetTags(), MakeFileName(), FileNames::MakeNameUnique(), mDir, mIterator, mNumLabels, Track::MonoChannel, mPluginIndex, mPlugins, mProject, mSelected, mSubFormatIndex, mTracks, name, TrackListIterator::Next(), Track::SetSelected(), Tags::SetTag(), Tags::ShowEditDialog(), ExportKit::t0, ExportKit::t1, TAG_TITLE, TAG_TRACK, and Track::Wave.
Referenced by OnExport().
wxString ExportMultiple::MakeFileName (wxString input) [private]
Takes an arbitrary text string and converts it to a form that can be used as a file name, if necessary prompting the user to edit the file name produced.
References exclude, and Internat::SanitiseFilename().
Referenced by ExportMultipleByLabel(), and ExportMultipleByTrack().
void ExportMultiple::OnByName (wxCommandEvent & event) [private]
References EnableControls().
void ExportMultiple::OnByNumber (wxCommandEvent & event) [private]
References EnableControls().
void ExportMultiple::OnCancel (wxCommandEvent & event) [private]
void ExportMultiple::OnChoose (wxCommandEvent & event) [private]
References mDir.
void ExportMultiple::OnCreate (wxCommandEvent & event) [private]
References mDir.
void ExportMultiple::OnExport (wxCommandEvent & event) [private]
References DirOk(), eIsSavingToPrefs, eProgressCancelled, eProgressFailed, eProgressStopped, eProgressSuccess, ExportMultipleByLabel(), ExportMultipleByTrack(), mByName, mByNumberAndName, mExported, mFilterIndex, mFormat, mLabel, mPluginIndex, mPlugins, mPrefix, mSubFormatIndex, PopulateOrExchange(), and ShowInfoDialog().
void ExportMultiple::OnFirst (wxCommandEvent & event) [private]
References EnableControls().
void ExportMultiple::OnFirstFileName (wxCommandEvent & event) [private]
References EnableControls().
void ExportMultiple::OnFormat (wxCommandEvent & event) [private]
References EnableControls().
void ExportMultiple::OnLabel (wxCommandEvent & event) [private]
References EnableControls().
void ExportMultiple::OnOptions (wxCommandEvent & event) [private]
References mFormat, mPluginIndex, mPlugins, and mSubFormatIndex.
void ExportMultiple::OnPrefix (wxCommandEvent & event) [private]
References EnableControls().
void ExportMultiple::OnTrack (wxCommandEvent & event) [private]
References EnableControls().
void ExportMultiple::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddCheckBox(), ShuttleGuiBase::AddRadioButton(), ShuttleGuiBase::AddRadioButtonToGroup(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddVariableText(), ByNameAndNumberID, ByNameID, ByNumberID, ChooseID, CreateID, DirID, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndRadioButtonGroup(), ShuttleGuiBase::EndStatic(), FirstFileNameID, FirstID, FormatID, AudacityProject::GetName(), gPrefs, ShuttleGui::Id(), LabelID, mByName, mByNumber, mByNumberAndName, mDir, mExport, mFilterIndex, mFirst, mFirstFileLabel, mFirstFileName, mFormat, mLabel, mLabelLabel, mOverwrite, mPluginIndex, mPlugins, mPrefix, mPrefixLabel, mProject, mSubFormatIndex, mTrack, mTrackLabel, name, OptionsID, OverwriteID, PrefixID, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartRadioButtonGroup(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::TieChoice(), ShuttleGuiBase::TieRadioButton(), ShuttleGuiBase::TieTextBox(), and TrackID.
Referenced by OnExport().
int ExportMultiple::ShowModal ()
References EnableControls(), mLabel, mNumLabels, mNumWaveTracks, and mTrack.
Referenced by AudacityProject::OnExportMultiple().
Member Data Documentation
wxArrayString ExportMultiple::exclude [private]
Array of characters not allowed to be in file names on this platform
Referenced by MakeFileName().
wxRadioButton* ExportMultiple::mByName [private]
button to choose naming exported file from label text
Referenced by EnableControls(), OnExport(), and PopulateOrExchange().
wxRadioButton* ExportMultiple::mByNumber [private]
button to choose numbering exported files
Referenced by EnableControls(), and PopulateOrExchange().
wxRadioButton* ExportMultiple::mByNumberAndName [private]
button to choose number AND name for exported files
Referenced by EnableControls(), OnExport(), and PopulateOrExchange().
wxButton* ExportMultiple::mCancel [private]
wxButton* ExportMultiple::mChoose [private]
wxButton* ExportMultiple::mCreate [private]
wxTextCtrl* ExportMultiple::mDir [private]
The directory all the exported files will end up in
Referenced by DirOk(), ExportMultipleByLabel(), ExportMultipleByTrack(), OnChoose(), OnCreate(), and PopulateOrExchange().
wxButton* ExportMultiple::mExport [private]
Referenced by EnableControls(), and PopulateOrExchange().
wxArrayString ExportMultiple::mExported [private]
Referenced by DoExport(), and OnExport().
Exporter ExportMultiple::mExporter [private]
int ExportMultiple::mFilterIndex [private]
The index in the drop-down list of export formats (mFormat) of the selected export format. This list includes all possible plug-in - subformat combinations.
Referenced by OnExport(), and PopulateOrExchange().
wxCheckBox* ExportMultiple::mFirst [private]
Check box to export audio before first label
Referenced by EnableControls(), ExportMultipleByLabel(), and PopulateOrExchange().
wxStaticText* ExportMultiple::mFirstFileLabel [private]
description text for mFirstFileName
Referenced by EnableControls(), and PopulateOrExchange().
wxTextCtrl* ExportMultiple::mFirstFileName [private]
Name to use for exporting audio before the first label in the file
Referenced by EnableControls(), ExportMultipleByLabel(), and PopulateOrExchange().
wxChoice* ExportMultiple::mFormat [private]
Drop-down list of export formats (combinations of plug-in and subformat)
Referenced by OnExport(), OnOptions(), and PopulateOrExchange().
bool ExportMultiple::mInitialized [private]
Referenced by EnableControls().
TrackListIterator ExportMultiple::mIterator [private]
Iterator used to work through all the tracks in the project
Referenced by CountTracksAndLabels(), and ExportMultipleByTrack().
wxRadioButton* ExportMultiple::mLabel [private]
button to choose export based on Labels
Referenced by EnableControls(), OnExport(), PopulateOrExchange(), and ShowModal().
wxStaticText* ExportMultiple::mLabelLabel [private]
description text for mLabel
Referenced by PopulateOrExchange().
LabelTrack* ExportMultiple::mLabels [private]
Referenced by CountTracksAndLabels(), and ExportMultipleByLabel().
int ExportMultiple::mNumLabels [private]
Referenced by CountTracksAndLabels(), ExportMultipleByLabel(), ExportMultipleByTrack(), and ShowModal().
int ExportMultiple::mNumWaveTracks [private]
Referenced by CountTracksAndLabels(), and ShowModal().
wxButton* ExportMultiple::mOptions [private]
wxCheckBox* ExportMultiple::mOverwrite [private]
Referenced by DoExport(), and PopulateOrExchange().
int ExportMultiple::mPluginIndex [private]
The index in mPlugins of the selected export plug-in
Referenced by DoExport(), ExportMultipleByLabel(), ExportMultipleByTrack(), OnExport(), OnOptions(), and PopulateOrExchange().
ExportPluginArray ExportMultiple::mPlugins [private]
Array of references to available exporter plug-ins
Referenced by DoExport(), ExportMultipleByLabel(), ExportMultipleByTrack(), OnExport(), OnOptions(), and PopulateOrExchange().
wxTextCtrl* ExportMultiple::mPrefix [private]
Referenced by EnableControls(), OnExport(), and PopulateOrExchange().
wxStaticText* ExportMultiple::mPrefixLabel [private]
Referenced by EnableControls(), and PopulateOrExchange().
AudacityProject* ExportMultiple::mProject [private]
Referenced by DoExport(), ExportMultipleByLabel(), ExportMultipleByTrack(), and PopulateOrExchange().
wxArrayPtrVoid ExportMultiple::mSelected [private]
Referenced by ExportMultipleByTrack().
int ExportMultiple::mSubFormatIndex [private]
The selected subformat number within the selected export plug-in set by mPluginIndex
Referenced by DoExport(), ExportMultipleByLabel(), ExportMultipleByTrack(), OnExport(), OnOptions(), and PopulateOrExchange().
wxRadioButton* ExportMultiple::mTrack [private]
button to choose export based on tracks
Referenced by PopulateOrExchange(), and ShowModal().
wxStaticText* ExportMultiple::mTrackLabel [private]
Referenced by PopulateOrExchange().
TrackList* ExportMultiple::mTracks [private]
The list of tracks in the project that is being exported
Referenced by CountTracksAndLabels(), ExportMultipleByLabel(), and ExportMultipleByTrack().
The documentation for this class was generated from the following files:
ExportMultiple.h
ExportMultiple.cpp