Audacity: Theme Class Reference
Theme Class Reference
Based on ThemeBase, Theme manages image and icon resources.
#include <Theme.h>
Public Member Functions
Theme (void)
~Theme (void)
virtual void EnsureInitialised ()
virtual void ApplyUpdatedImages ()
void RegisterImages ()
void RegisterColours ()
Public Attributes
bool mbInitialised
Detailed Description
Based on ThemeBase, Theme manages image and icon resources.
Theme is a class which manages theme resources. It maps sets of ids to the resources and to names of the resources, so that they can be loaded/saved from files.
Theme adds the Audacity specific images to ThemeBase.
See also:
Themability
Constructor & Destructor Documentation
Theme::Theme (void)
References mbInitialised.
Theme::~Theme (void)
Member Function Documentation
void Theme::ApplyUpdatedImages () [virtual]
Implements ThemeBase.
References GetActiveProject(), AudacityProject::GetControlToolBar(), and ControlToolBar::ReCreateButtons().
Referenced by ThemePrefs::OnLoadThemeCache(), ThemePrefs::OnLoadThemeComponents(), and ThemePrefs::OnReadThemeInternal().
void Theme::EnsureInitialised () [virtual]
Implements ThemeBase.
References gPrefs, ThemeBase::LoadThemeAtStartUp(), mbInitialised, RegisterColours(), and RegisterImages().
Referenced by AudacityApp::OnInit().
void Theme::RegisterColours ()
Referenced by EnsureInitialised().
void Theme::RegisterImages ()
Referenced by EnsureInitialised().
Member Data Documentation
bool Theme::mbInitialised
Referenced by EnsureInitialised(), and Theme().
The documentation for this class was generated from the following files:
Theme.h
Theme.cpp