Audacity: SetTrackInfoCommand Class Reference
SetTrackInfoCommand Class Reference
Command that sets track information (currently name only).
#include <SetTrackInfoCommand.h>
Public Member Functions
SetTrackInfoCommand (CommandType &type, CommandOutputTarget *target)
virtual ~SetTrackInfoCommand ()
virtual bool Apply (CommandExecutionContext context)
Detailed Description
Command that sets track information (currently name only).
Constructor & Destructor Documentation
SetTrackInfoCommand::SetTrackInfoCommand (CommandType & type, CommandOutputTarget * target) [inline]
virtual SetTrackInfoCommand::~SetTrackInfoCommand () [inline, virtual]
Member Function Documentation
bool SetTrackInfoCommand::Apply (CommandExecutionContext context) [virtual]
Actually carry out the command. Return true if successful and false otherwise.
Reimplemented from CommandImplementation.
References CommandImplementation::Error(), CommandImplementation::GetLong(), CommandImplementation::GetString(), AudacityProject::GetTracks(), name, and CommandExecutionContext::proj.
The documentation for this class was generated from the following files:
SetTrackInfoCommand.h
SetTrackInfoCommand.cpp