Audacity: BatchPrefs Class Reference
BatchPrefs Class Reference
A PrefsPanel that builds up a chain of effects in BatchCommands.
#include <BatchPrefs.h>
Public Member Functions
BatchPrefs (wxWindow *parent)
Constructor.
~BatchPrefs ()
virtual bool Apply ()
Send changed values back to Prefs, and update Audacity.
Private Member Functions
void Populate ()
Creates the dialog and its contents.
void PopulateOrExchange (ShuttleGui &S)
Defines the dialog and does data exchange with it.
DECLARE_EVENT_TABLE ()
Detailed Description
A PrefsPanel that builds up a chain of effects in BatchCommands.
Constructor & Destructor Documentation
BatchPrefs::BatchPrefs (wxWindow * parent)
Constructor.
References Populate().
BatchPrefs::~BatchPrefs ()
Member Function Documentation
bool BatchPrefs::Apply () [virtual]
Send changed values back to Prefs, and update Audacity.
Implements PrefsPanel.
References eIsSavingToPrefs, gAudacityProjects, gPrefs, and PopulateOrExchange().
BatchPrefs::DECLARE_EVENT_TABLE () [private]
void BatchPrefs::Populate () [private]
Creates the dialog and its contents.
References eIsCreatingFromPrefs, and PopulateOrExchange().
Referenced by BatchPrefs().
void BatchPrefs::PopulateOrExchange (ShuttleGui & S) [private]
Defines the dialog and does data exchange with it.
References ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::TieCheckBox().
Referenced by Apply(), and Populate().
The documentation for this class was generated from the following files:
BatchPrefs.h
BatchPrefs.cpp