Audacity: ExportFFmpegAC3Options Class Reference
ExportFFmpegAC3Options Class Reference
AC3 export options dialog.
#include <ExportFFmpegDialogs.h>
Public Member Functions
ExportFFmpegAC3Options (wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
void OnOK (wxCommandEvent &event)
Static Public Attributes
static const int iAC3BitRates [] = { 32000, 40000, 48000, 56000, 64000, 80000, 96000, 112000, 128000, 160000, 192000, 224000, 256000, 320000, 384000, 448000, 512000, 576000, 640000 }
Bit Rates supported by AC3 encoder.
static const int iAC3SampleRates [] = { 32000, 44100, 48000, 0 }
Private Attributes
wxArrayString mBitRateNames
wxArrayInt mBitRateLabels
wxChoice * mBitRateChoice
wxButton * mOk
int mBitRateFromChoice
Detailed Description
AC3 export options dialog.
Options dialog for FFmpeg exporting of AC3 format.
Constructor & Destructor Documentation
ExportFFmpegAC3Options::ExportFFmpegAC3Options (wxWindow * parent)
References eIsCreatingFromPrefs, iAC3BitRates, mBitRateLabels, mBitRateNames, and PopulateOrExchange().
Member Function Documentation
void ExportFFmpegAC3Options::OnOK (wxCommandEvent & event)
References eIsSavingToPrefs, and PopulateOrExchange().
void ExportFFmpegAC3Options::PopulateOrExchange (ShuttleGui & S)
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndTwoColumn(), mBitRateLabels, mBitRateNames, ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartTwoColumn(), and ShuttleGuiBase::TieChoice().
Referenced by ExportFFmpegAC3Options(), and OnOK().
Member Data Documentation
const int ExportFFmpegAC3Options::iAC3BitRates = { 32000, 40000, 48000, 56000, 64000, 80000, 96000, 112000, 128000, 160000, 192000, 224000, 256000, 320000, 384000, 448000, 512000, 576000, 640000 } [static]
Bit Rates supported by AC3 encoder.
Referenced by ExportFFmpegAC3Options().
const int ExportFFmpegAC3Options::iAC3SampleRates = { 32000, 44100, 48000, 0 } [static]
Sample Rates supported by AC3 encoder (must end with zero-element) It is not used in dialog anymore, but will be required later
Referenced by ExportFFmpeg::InitCodecs().
wxChoice* ExportFFmpegAC3Options::mBitRateChoice [private]
int ExportFFmpegAC3Options::mBitRateFromChoice [private]
wxArrayInt ExportFFmpegAC3Options::mBitRateLabels [private]
Referenced by ExportFFmpegAC3Options(), and PopulateOrExchange().
wxArrayString ExportFFmpegAC3Options::mBitRateNames [private]
Referenced by ExportFFmpegAC3Options(), and PopulateOrExchange().
wxButton* ExportFFmpegAC3Options::mOk [private]
The documentation for this class was generated from the following files:
ExportFFmpegDialogs.h
ExportFFmpegDialogs.cpp