Audacity: BatchCommands Class Reference
BatchCommands Class Reference
Maintains the chain of commands used in batch processing. See also BatchCommandDialog and BatchProcessDialog.
#include <BatchCommands.h>
Public Member Functions
BatchCommands ()
bool ApplyChain (const wxString &filename=wxT(""))
bool ApplyCommand (const wxString command, const wxString params)
bool ApplyCommandInBatchMode (const wxString &command, const wxString &params)
bool ApplySpecialCommand (int iCommand, const wxString command, const wxString params)
bool ApplyEffectCommand (Effect *f, const wxString command, const wxString params)
bool ApplyMenuCommand (const wxString command, const wxString params)
bool ReportAndSkip (const wxString command, const wxString params)
void AbortBatch ()
bool WriteMp3File (const wxString Name, int bitrate)
double GetEndTime ()
bool IsMono ()
wxArrayString GetNames ()
void ResetChain ()
bool ReadChain (const wxString &chain)
bool WriteChain (const wxString &chain)
bool AddChain (const wxString &chain)
bool DeleteChain (const wxString &name)
bool RenameChain (const wxString &oldchain, const wxString &newchain)
void AddToChain (const wxString &command, int before=-1)
void AddToChain (const wxString &command, const wxString &params, int before=-1)
void DeleteFromChain (int index)
wxString GetCommand (int index)
wxString GetParams (int index)
int GetCount ()
void SetWavToMp3Chain ()
void SetCleanSpeechChain ()
bool IsFixed (const wxString &name)
void RestoreChain (const wxString &name)
void Split (const wxString &str, wxString &command, wxString &param)
wxString Join (const wxString &command, const wxString &param)
Static Public Member Functions
static bool PromptForParamsFor (wxString command, wxWindow *parent)
static wxString GetCurrentParamsFor (wxString command)
static bool SetCurrentParametersFor (Effect *f, const wxString command, const wxString params)
static wxArrayString GetAllCommands ()
Public Attributes
wxArrayString mCommandChain
wxArrayString mParamsChain
bool mAbort
Exporter mExporter
wxString mFileName
Detailed Description
Maintains the chain of commands used in batch processing. See also BatchCommandDialog and BatchProcessDialog.
Constructor & Destructor Documentation
BatchCommands::BatchCommands ()
References AddChain(), CleanSpeech, GetNames(), MP3Conversion, names, ResetChain(), RestoreChain(), and WriteChain().
Member Function Documentation
void BatchCommands::AbortBatch ()
References mAbort.
bool BatchCommands::AddChain (const wxString & chain)
References FileNames::ChainDir(), and name.
Referenced by BatchCommands(), and EditChainsDialog::OnAdd().
void BatchCommands::AddToChain (const wxString & command, const wxString & params, int before = -1)
References mCommandChain, and mParamsChain.
void BatchCommands::AddToChain (const wxString & command, int before = -1)
References GetCurrentParamsFor().
Referenced by EditChainsDialog::OnCommandActivated(), EditChainsDialog::OnDown(), EditChainsDialog::OnInsert(), EditChainsDialog::OnUp(), SetCleanSpeechChain(), and SetWavToMp3Chain().
bool BatchCommands::ApplyChain (const wxString & filename = wxT(""))
References ApplyCommandInBatchMode(), GetActiveProject(), UndoManager::GetCurrentState(), AudacityProject::GetUndoManager(), gPrefs, mAbort, mCommandChain, mFileName, mParamsChain, name, AudacityProject::PushState(), and AudacityProject::SetStateTo().
Referenced by BatchEvalCommand::Apply(), BatchProcessDialog::OnApplyToFiles(), and BatchProcessDialog::OnApplyToProject().
bool BatchCommands::ApplyCommand (const wxString command, const wxString params)
References ApplyEffectCommand(), ApplySpecialCommand(), EffectManager::Get(), EffectManager::GetEffectByIdentifier(), and SpecialCommands.
Referenced by BatchEvalCommand::Apply(), and ApplyCommandInBatchMode().
bool BatchCommands::ApplyCommandInBatchMode (const wxString & command, const wxString & params)
References ApplyCommand(), GetActiveProject(), AudacityProject::GetShowId3Dialog(), and AudacityProject::SetShowId3Dialog().
Referenced by ApplyChain().
bool BatchCommands::ApplyEffectCommand (Effect * f, const wxString command, const wxString params)
References ALL_EFFECTS, CONFIGURED_EFFECT, GetActiveProject(), AudacityProject::OnEffect(), ReportAndSkip(), and AudacityProject::SelectAllIfNone().
Referenced by ApplyCommand(), and ApplySpecialCommand().
bool BatchCommands::ApplyMenuCommand (const wxString command, const wxString params)
References ReportAndSkip().
bool BatchCommands::ApplySpecialCommand (int iCommand, const wxString command, const wxString params)
References ApplyEffectCommand(), AudacityProject::BuildCleanFileName(), EffectManager::Get(), GetActiveProject(), EffectManager::GetEffectByIdentifier(), GetEndTime(), AudacityProject::GetFileName(), IsMono(), mExporter, mFileName, Exporter::Process(), ReportAndSkip(), and WriteMp3File().
Referenced by ApplyCommand().
bool BatchCommands::DeleteChain (const wxString & name)
References FileNames::ChainDir(), and name.
Referenced by EditChainsDialog::OnRemove().
void BatchCommands::DeleteFromChain (int index)
References mCommandChain, and mParamsChain.
Referenced by EditChainsDialog::OnCommandActivated(), EditChainsDialog::OnDelete(), EditChainsDialog::OnDown(), and EditChainsDialog::OnUp().
wxArrayString BatchCommands::GetAllCommands () [static]
References ADVANCED_EFFECT, BUILTIN_EFFECT, EffectManager::Get(), GetActiveProject(), AudacityProject::GetCleanSpeechMode(), EffectManager::GetEffects(), PROCESS_EFFECT, and SpecialCommands.
Referenced by BatchCommandDialog::PopulateCommandList().
wxString BatchCommands::GetCommand (int index)
References mCommandChain.
Referenced by EditChainsDialog::OnCommandActivated(), EditChainsDialog::OnDown(), EditChainsDialog::OnUp(), and EditChainsDialog::PopulateList().
int BatchCommands::GetCount ()
References mCommandChain.
Referenced by EditChainsDialog::PopulateList().
wxString BatchCommands::GetCurrentParamsFor (wxString command) [static]
References EffectManager::Get(), EffectManager::GetEffectByIdentifier(), Shuttle::mbStoreInClient, ShuttleCli::mParams, and Effect::TransferParameters().
Referenced by AddToChain(), BatchCommandDialog::OnEditParams(), and BatchCommandDialog::OnItemSelected().
double BatchCommands::GetEndTime ()
References GetActiveProject(), TrackList::GetEndTime(), and AudacityProject::GetTracks().
Referenced by ApplySpecialCommand(), and WriteMp3File().
wxArrayString BatchCommands::GetNames ()
References FileNames::ChainDir(), and names.
Referenced by BatchCommands(), EditChainsDialog::PopulateChains(), and BatchProcessDialog::PopulateOrExchange().
wxString BatchCommands::GetParams (int index)
References mParamsChain.
Referenced by EditChainsDialog::OnCommandActivated(), EditChainsDialog::OnDown(), EditChainsDialog::OnUp(), and EditChainsDialog::PopulateList().
bool BatchCommands::IsFixed (const wxString & name)
References CleanSpeech, and MP3Conversion.
Referenced by EditChainsDialog::OnChainsBeginEdit(), and EditChainsDialog::OnChainSelected().
bool BatchCommands::IsMono ()
References TrackListIterator::First(), GetActiveProject(), Track::GetLinked(), AudacityProject::GetTracks(), and TrackListIterator::Next().
Referenced by ApplySpecialCommand(), and WriteMp3File().
wxString BatchCommands::Join (const wxString & command, const wxString & param)
bool BatchCommands::PromptForParamsFor (wxString command, wxWindow * parent) [static]
References EffectManager::Get(), EffectManager::GetEffectByIdentifier(), Effect::mParent, and Effect::PromptUser().
Referenced by BatchCommandDialog::OnEditParams().
bool BatchCommands::ReadChain (const wxString & chain)
References FileNames::ChainDir(), mCommandChain, mParamsChain, name, and ResetChain().
Referenced by BatchEvalCommand::Apply(), BatchProcessDialog::OnApplyToFiles(), BatchProcessDialog::OnApplyToProject(), and EditChainsDialog::OnChainSelected().
bool BatchCommands::RenameChain (const wxString & oldchain, const wxString & newchain)
References FileNames::ChainDir().
Referenced by EditChainsDialog::OnChainsEndEdit().
bool BatchCommands::ReportAndSkip (const wxString command, const wxString params)
References gPrefs.
Referenced by ApplyEffectCommand(), ApplyMenuCommand(), and ApplySpecialCommand().
void BatchCommands::ResetChain ()
References mCommandChain, and mParamsChain.
Referenced by BatchCommands(), ReadChain(), SetCleanSpeechChain(), and SetWavToMp3Chain().
void BatchCommands::RestoreChain (const wxString & name)
References CleanSpeech, MP3Conversion, SetCleanSpeechChain(), and SetWavToMp3Chain().
Referenced by BatchCommands(), and EditChainsDialog::OnDefaults().
void BatchCommands::SetCleanSpeechChain ()
References AddToChain(), and ResetChain().
Referenced by RestoreChain().
bool BatchCommands::SetCurrentParametersFor (Effect * f, const wxString command, const wxString params) [static]
References Shuttle::mbStoreInClient, ShuttleCli::mParams, and Effect::TransferParameters().
Referenced by BatchCommandDialog::OnEditParams().
void BatchCommands::SetWavToMp3Chain ()
References AddToChain(), and ResetChain().
Referenced by RestoreChain().
void BatchCommands::Split (const wxString & str, wxString & command, wxString & param)
bool BatchCommands::WriteChain (const wxString & chain)
References FileNames::ChainDir(), mCommandChain, mParamsChain, and name.
Referenced by BatchCommands(), EditChainsDialog::ChangeOK(), and EditChainsDialog::OnOK().
bool BatchCommands::WriteMp3File (const wxString Name, int bitrate)
References GetActiveProject(), GetEndTime(), gPrefs, IsMono(), mExporter, and Exporter::Process().
Referenced by ApplySpecialCommand().
Member Data Documentation
bool BatchCommands::mAbort
Referenced by AbortBatch(), and ApplyChain().
wxArrayString BatchCommands::mCommandChain
Referenced by AddToChain(), ApplyChain(), DeleteFromChain(), GetCommand(), GetCount(), ReadChain(), ResetChain(), and WriteChain().
Exporter BatchCommands::mExporter
Referenced by ApplySpecialCommand(), and WriteMp3File().
wxString BatchCommands::mFileName
Referenced by ApplyChain(), and ApplySpecialCommand().
wxArrayString BatchCommands::mParamsChain
Referenced by AddToChain(), ApplyChain(), DeleteFromChain(), GetParams(), ReadChain(), ResetChain(), and WriteChain().
The documentation for this class was generated from the following files:
BatchCommands.h
BatchCommands.cpp