Audacity: ScreenshotCommand Class Reference
ScreenshotCommand Class Reference
Implements a command for capturing various areas of the screen or project window.
#include <ScreenshotCommand.h>
Public Member Functions
wxTopLevelWindow * GetFrontWindow (AudacityProject *project)
ScreenshotCommand (CommandType &type, CommandOutputTarget *output, wxWindow *ignore=NULL)
bool Apply (CommandExecutionContext context)
Private Member Functions
wxString MakeFileName (wxString path, wxString basename)
wxRect GetBackgroundRect ()
void Capture (wxString basename, wxWindow *window, int x, int y, int width, int height, bool bg=false)
void CaptureToolbar (ToolManager *man, int type, wxString name)
void CaptureDock (wxWindow *win, wxString fileName)
Private Attributes
wxWindow * mIgnore
bool mBackground
wxColour mBackColor
Detailed Description
Implements a command for capturing various areas of the screen or project window.
Constructor & Destructor Documentation
ScreenshotCommand::ScreenshotCommand (CommandType & type, CommandOutputTarget * output, wxWindow * ignore = NULL) [inline]
Member Function Documentation
bool ScreenshotCommand::Apply (CommandExecutionContext context) [virtual]
Actually carry out the command. Return true if successful and false otherwise.
Reimplemented from CommandImplementation.
References Capture(), CaptureDock(), CaptureToolbar(), ControlBarID, DeviceBarID, EditBarID, TrackPanel::FindTrackRect(), GetBackgroundRect(), ToolManager::GetBotDock(), GetFrontWindow(), AdornedRulerPanel::GetRulerHeight(), CommandImplementation::GetString(), ToolManager::GetTopDock(), AudacityProject::GetTracks(), MakeFileName(), mBackColor, mBackground, MeterBarID, MixerBarID, TrackPanel::mRuler, AudacityProject::mToolManager, AudacityProject::mTrackPanel, CommandExecutionContext::proj, ToolManager::Reset(), ToolsBarID, and TranscriptionBarID.
Referenced by ScreenFrame::DoCapture().
void ScreenshotCommand::Capture (wxString basename, wxWindow * window, int x, int y, int width, int height, bool bg = false) [private]
References CommandOutputTarget::Error(), GetBackgroundRect(), mBackColor, mBackground, CommandImplementation::mOutput, CommandOutputTarget::Status(), and Yield().
Referenced by Apply(), CaptureDock(), and CaptureToolbar().
void ScreenshotCommand::CaptureDock (wxWindow * win, wxString fileName) [private]
References Capture().
Referenced by Apply().
void ScreenshotCommand::CaptureToolbar (ToolManager * man, int type, wxString name) [private]
References Capture(), ToolManager::GetToolBar(), ToolManager::IsVisible(), mIgnore, ToolManager::ShowHide(), and Yield().
Referenced by Apply().
wxRect ScreenshotCommand::GetBackgroundRect () [private]
Referenced by Apply(), and Capture().
wxTopLevelWindow * ScreenshotCommand::GetFrontWindow (AudacityProject * project)
References mIgnore.
Referenced by Apply(), and ScreenFrame::OnUIUpdate().
wxString ScreenshotCommand::MakeFileName (wxString path, wxString basename) [private]
Referenced by Apply().
Member Data Documentation
wxColour ScreenshotCommand::mBackColor [private]
Referenced by Apply(), and Capture().
bool ScreenshotCommand::mBackground [private]
Referenced by Apply(), and Capture().
wxWindow* ScreenshotCommand::mIgnore [private]
Referenced by CaptureToolbar(), and GetFrontWindow().
The documentation for this class was generated from the following files:
ScreenshotCommand.h
ScreenshotCommand.cpp