Audacity: ExportFFmpegAMRNBOptions Class Reference
ExportFFmpegAMRNBOptions Class Reference
Options dialog for FFmpeg exporting of AMRNB format.
#include <ExportFFmpegDialogs.h>
Public Member Functions
ExportFFmpegAMRNBOptions (wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
void OnOK (wxCommandEvent &event)
Static Public Attributes
static int iAMRNBBitRate []
Private Attributes
wxArrayString mBitRateNames
wxArrayInt mBitRateLabels
wxChoice * mBitRateChoice
wxButton * mOk
int mBitRateFromChoice
Detailed Description
Options dialog for FFmpeg exporting of AMRNB format.
Constructor & Destructor Documentation
ExportFFmpegAMRNBOptions::ExportFFmpegAMRNBOptions (wxWindow * parent)
References eIsCreatingFromPrefs, iAMRNBBitRate, mBitRateLabels, mBitRateNames, and PopulateOrExchange().
Member Function Documentation
void ExportFFmpegAMRNBOptions::OnOK (wxCommandEvent & event)
References eIsSavingToPrefs, and PopulateOrExchange().
void ExportFFmpegAMRNBOptions::PopulateOrExchange (ShuttleGui & S)
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndTwoColumn(), mBitRateLabels, mBitRateNames, ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartTwoColumn(), and ShuttleGuiBase::TieChoice().
Referenced by ExportFFmpegAMRNBOptions(), and OnOK().
Member Data Documentation
int ExportFFmpegAMRNBOptions::iAMRNBBitRate [static]
Initial value:
{ 4750, 5150, 5900, 6700, 7400, 7950, 10200, 12200 }
Bit Rates supported by libAMR-NB encoder Sample Rate is always 8 kHz
Referenced by ExportFFmpegAMRNBOptions().
wxChoice* ExportFFmpegAMRNBOptions::mBitRateChoice [private]
int ExportFFmpegAMRNBOptions::mBitRateFromChoice [private]
wxArrayInt ExportFFmpegAMRNBOptions::mBitRateLabels [private]
Referenced by ExportFFmpegAMRNBOptions(), and PopulateOrExchange().
wxArrayString ExportFFmpegAMRNBOptions::mBitRateNames [private]
Referenced by ExportFFmpegAMRNBOptions(), and PopulateOrExchange().
wxButton* ExportFFmpegAMRNBOptions::mOk [private]
The documentation for this class was generated from the following files:
ExportFFmpegDialogs.h
ExportFFmpegDialogs.cpp