Audacity: LibraryPrefs Class Reference
LibraryPrefs Class Reference
A PrefsPanel used to select manage external libraries like the MP3 and FFmpeg encoding libraries.
#include <LibraryPrefs.h>
Public Member Functions
LibraryPrefs (wxWindow *parent)
~LibraryPrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
Creates the dialog and its contents.
void PopulateOrExchange (ShuttleGui &S)
void SetMP3VersionText (bool prompt=false)
void SetFFmpegVersionText ()
void OnMP3FindButton (wxCommandEvent &e)
void OnMP3DownButton (wxCommandEvent &e)
void OnFFmpegFindButton (wxCommandEvent &e)
void OnFFmpegDownButton (wxCommandEvent &e)
DECLARE_EVENT_TABLE ()
Private Attributes
wxStaticText * mMP3Version
wxStaticText * mFFmpegVersion
Detailed Description
A PrefsPanel used to select manage external libraries like the MP3 and FFmpeg encoding libraries.
Constructor & Destructor Documentation
LibraryPrefs::LibraryPrefs (wxWindow * parent)
LibraryPrefs::~LibraryPrefs ()
Member Function Documentation
bool LibraryPrefs::Apply () [virtual]
Implements PrefsPanel.
References eIsSavingToPrefs, and PopulateOrExchange().
LibraryPrefs::DECLARE_EVENT_TABLE () [private]
void LibraryPrefs::OnFFmpegDownButton (wxCommandEvent & e) [private]
References OpenInDefaultBrowser().
void LibraryPrefs::OnFFmpegFindButton (wxCommandEvent & e) [private]
References DropFFmpegLibs(), FFmpegLibsInst, FFmpegLibs::FindLibs(), FFmpegLibs::FreeLibs(), LoadFFmpeg(), PickFFmpegLibs(), and SetFFmpegVersionText().
void LibraryPrefs::OnMP3DownButton (wxCommandEvent & e) [private]
Opens a file-finder dialog so that the user can tell us where the MP3 library is.
References OpenInDefaultBrowser().
void LibraryPrefs::OnMP3FindButton (wxCommandEvent & e) [private]
Opens a file-finder dialog so that the user can tell us where the MP3 library is.
References SetMP3VersionText().
void LibraryPrefs::Populate () [private]
Creates the dialog and its contents.
References eIsCreatingFromPrefs, PopulateOrExchange(), SetFFmpegVersionText(), and SetMP3VersionText().
void LibraryPrefs::PopulateOrExchange (ShuttleGui & S) [private]
This PopulateOrExchange function is a good example of mixing the fully automatic style of reading/writing from GUI to prefs with the partial form.
You'll notice that some of the Tie functions have Prefs identifiers in them and others don't.
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddVariableText(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndTwoColumn(), ShuttleGui::Id(), ID_FFMPEG_DOWN_BUTTON, ID_FFMPEG_FIND_BUTTON, ID_MP3_DOWN_BUTTON, ID_MP3_FIND_BUTTON, mFFmpegVersion, mMP3Version, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::StartTwoColumn().
Referenced by Apply(), and Populate().
void LibraryPrefs::SetFFmpegVersionText () [private]
References GetFFmpegVersion(), and mFFmpegVersion.
Referenced by OnFFmpegFindButton(), and Populate().
void LibraryPrefs::SetMP3VersionText (bool prompt = false) [private]
Sets the a text area on the dialog to have the name of the MP3 Library version.
References GetMP3Version(), and mMP3Version.
Referenced by OnMP3FindButton(), and Populate().
Member Data Documentation
wxStaticText* LibraryPrefs::mFFmpegVersion [private]
Referenced by PopulateOrExchange(), and SetFFmpegVersionText().
wxStaticText* LibraryPrefs::mMP3Version [private]
Referenced by PopulateOrExchange(), and SetMP3VersionText().
The documentation for this class was generated from the following files:
LibraryPrefs.h
LibraryPrefs.cpp