Audacity: ODManager Class Reference
ODManager Class Reference
A singleton that manages currently running Tasks on an arbitrary number of threads.
#include <ODManager.h>
Classes
class ODManagerHelperThread
Public Member Functions
void DemandTrackUpdate (WaveTrack *track, double seconds)
changes the tasks associated with this Waveform to process the task from a different point in the track
void DecrementCurrentThreads ()
Reduces the count of current threads running. Meant to be called when ODTaskThreads end in their own threads. Thread-safe.
void AddNewTask (ODTask *task, bool lockMutex=true)
Adds a wavetrack, creates a queue member.
void SignalTaskQueueLoop ()
Wakes the queue loop up by signalling its condition variable.
void RemoveWaveTrack (WaveTrack *track)
removes a wavetrack and notifies its associated tasks to stop using its reference.
void MakeWaveTrackIndependent (WaveTrack *track)
if it shares a queue/task, creates a new queue/task for the track, and removes it from any previously existing tasks.
bool MakeWaveTrackDependent (WaveTrack *dependentTrack, WaveTrack *masterTrack)
void ReplaceWaveTrack (WaveTrack *oldTrack, WaveTrack *newTrack)
replace the wavetrack whose wavecache the gui watches for updates
void AddTask (ODTask *task)
Adds a task to the running queue. Threas-safe.
void RemoveTaskIfInQueue (ODTask *task)
removes a task from the active task queue
void FillTipForWaveTrack (WaveTrack *t, const wxChar **ppTip)
fills in the status bar message for a given track
float GetOverallPercentComplete ()
Gets the total percent complete for all tasks combined.
int GetTotalNumTasks ()
Get Total Number of Tasks.
Static Public Member Functions
static ODManager * Instance ()
Gets the singleton instance.
static void Quit ()
Kills the ODMananger Thread.
static void MarkLoadedODFlag ()
sets a flag that is set if we have loaded some OD blockfiles from PCM.
static void UnmarkLoadedODFlag ()
resets a flag that is set if we have loaded some OD blockfiles from PCM.
static bool HasLoadedODFlag ()
returns a flag that is set if we have loaded some OD blockfiles from PCM.
static bool IsInstanceCreated ()
returns whether or not the singleton instance was created yet
static void Pause (bool pause=true)
static void Resume ()
static void LockLibSndFileMutex ()
static void UnlockLibSndFileMutex ()
Protected Member Functions
ODManager ()
virtual ~ODManager ()
void Init ()
Launches a thread for the manager and starts accepting Tasks.
void Start ()
Start the main loop for the manager.
void UpdateQueues ()
Remove references in our array to Tasks that have been completed/Schedule new ones.
Protected Attributes
std::vector
< ODWaveTrackTaskQueue * > mQueues
ODLock mQueuesMutex
std::vector< ODTask * > mTasks
ODLock mTasksMutex
bool mPause
ODLock mPauseLock
int mNeedsDraw
int mCurrentThreads
Number of threads currently running. Accessed thru multiple threads.
ODLock mCurrentThreadsMutex
int mMaxThreads
Maximum number of threads allowed out.
bool mTerminate
ODLock mTerminateMutex
bool mTerminated
ODLock mTerminatedMutex
ODLock mQueueNotEmptyCondLock
ODCondition * mQueueNotEmptyCond
Detailed Description
A singleton that manages currently running Tasks on an arbitrary number of threads.
Constructor & Destructor Documentation
ODManager::ODManager () [protected]
References gPause, mPause, mQueueNotEmptyCond, mQueueNotEmptyCondLock, mTerminate, and mTerminated.
Referenced by Instance().
ODManager::~ODManager () [protected, virtual]
References mQueueNotEmptyCond, and mQueues.
Member Function Documentation
void ODManager::AddNewTask (ODTask * task, bool lockMutex = true)
Adds a wavetrack, creates a queue member.
Adds a new task to the queue. Creates a queue if the tracks associated with the task is not in the list
Parameters:
task the task to add
lockMutex locks the mutexes if true (default). This function is used within other ODManager calls, which many need to set this to false.
References AddTask(), ODWaveTrackTaskQueue::AddTask(), ODTask::GetWaveTrack(), mQueues, and mQueuesMutex.
Referenced by PCMImportFileHandle::Import(), FLACImportFileHandle::Import(), ODWaveTrackTaskQueue::MakeWaveTrackIndependent(), AudacityProject::OpenFile(), and AudacityProject::PopState().
void ODManager::AddTask (ODTask * task)
Adds a task to the running queue. Threas-safe.
Adds a task to running queue. Thread-safe.
References mPause, mPauseLock, mQueueNotEmptyCond, mQueueNotEmptyCondLock, mTasks, and mTasksMutex.
Referenced by AddNewTask(), ODTask::DoSome(), and UpdateQueues().
void ODManager::DecrementCurrentThreads ()
Reduces the count of current threads running. Meant to be called when ODTaskThreads end in their own threads. Thread-safe.
References mCurrentThreads, and mCurrentThreadsMutex.
Referenced by ODTaskThread::Entry().
void ODManager::DemandTrackUpdate (WaveTrack * track, double seconds)
changes the tasks associated with this Waveform to process the task from a different point in the track
changes the tasks associated with this Waveform to process the task from a different point in the track
Parameters:
track the track to update
seconds the point in the track from which the tasks associated with track should begin processing from.
References mQueues, and mQueuesMutex.
Referenced by TrackPanel::ExtendSelection(), and TrackPanel::SelectionHandleClick().
void ODManager::FillTipForWaveTrack (WaveTrack * t, const wxChar ** ppTip)
fills in the status bar message for a given track
References mQueues, and mQueuesMutex.
Referenced by TrackPanel::SetCursorAndTipWhenSelectTool().
float ODManager::GetOverallPercentComplete ()
Gets the total percent complete for all tasks combined.
References GetTotalNumTasks(), mQueues, and mQueuesMutex.
Referenced by AudacityProject::OnTimer().
int ODManager::GetTotalNumTasks ()
Get Total Number of Tasks.
References mQueues, and mQueuesMutex.
Referenced by GetOverallPercentComplete(), and AudacityProject::OnTimer().
bool ODManager::HasLoadedODFlag () [static]
returns a flag that is set if we have loaded some OD blockfiles from PCM.
References sHasLoadedOD.
Referenced by AudacityProject::OpenFile().
void ODManager::Init () [protected]
Launches a thread for the manager and starts accepting Tasks.
References mCurrentThreads, and mMaxThreads.
Referenced by Instance().
ODManager * ODManager::Instance () [static]
Gets the singleton instance.
References gManagerCreated, Init(), and ODManager().
Referenced by ODTask::DoSome(), ODTaskThread::Entry(), ODManager::ODManagerHelperThread::Entry(), TrackPanel::ExtendSelection(), PCMImportFileHandle::Import(), FLACImportFileHandle::Import(), ODWaveTrackTaskQueue::MakeWaveTrackIndependent(), TrackPanel::OnMergeStereo(), AudacityProject::OnTimer(), AudacityProject::OpenFile(), Pause(), AudacityProject::PopState(), Quit(), Effect::ReplaceProcessedTracks(), TrackPanel::SelectionHandleClick(), TrackPanel::SetCursorAndTipWhenSelectTool(), TrackPanel::SplitStereo(), ODWaveTrackTaskQueue::~ODWaveTrackTaskQueue(), and WaveTrack::~WaveTrack().
bool ODManager::IsInstanceCreated () [static]
returns whether or not the singleton instance was created yet
References gManagerCreated.
Referenced by TrackPanel::ExtendSelection(), TrackPanel::OnMergeStereo(), AudacityProject::OnTimer(), Pause(), AudacityProject::PopState(), Quit(), Effect::ReplaceProcessedTracks(), TrackPanel::SelectionHandleClick(), TrackPanel::SetCursorAndTipWhenSelectTool(), TrackPanel::SplitStereo(), and WaveTrack::~WaveTrack().
void ODManager::LockLibSndFileMutex () [static]
Referenced by ExportPCM::Export(), PCMAliasBlockFile::ReadData(), and ODPCMAliasBlockFile::ReadData().
bool ODManager::MakeWaveTrackDependent (WaveTrack * dependentTrack, WaveTrack * masterTrack)
attach the track in question to another, already existing track's queues and tasks. Remove the task/tracks. Returns success if it was possible.. Some ODTask conditions make it impossible until the Tasks finish.
attach the track in question to another, already existing track's queues and tasks. Remove the task/tracks. only works if both tracks exist. Sets needODUpdate flag for the task. This is complicated and will probably need better design in the future.
Returns:
returns success. Some ODTask conditions require that the tasks finish before merging. e.g. they have different effects being processed at the same time.
References ODWaveTrackTaskQueue::CanMergeWith(), ODWaveTrackTaskQueue::MergeWaveTrack(), mQueues, and mQueuesMutex.
Referenced by TrackPanel::OnMergeStereo().
void ODManager::MakeWaveTrackIndependent (WaveTrack * track)
if it shares a queue/task, creates a new queue/task for the track, and removes it from any previously existing tasks.
References ODWaveTrackTaskQueue::MakeWaveTrackIndependent(), mQueues, and mQueuesMutex.
Referenced by TrackPanel::SplitStereo().
void ODManager::MarkLoadedODFlag () [static]
sets a flag that is set if we have loaded some OD blockfiles from PCM.
References sHasLoadedOD.
Referenced by DirManager::HandleXMLTag().
void ODManager::Pause (bool pause = true) [static]
References gPause, Instance(), IsInstanceCreated(), mPause, mPauseLock, mQueueNotEmptyCond, and mQueueNotEmptyCondLock.
Referenced by AudacityProject::OnImport(), AudacityProject::OpenFiles(), and Resume().
void ODManager::Quit () [static]
Kills the ODMananger Thread.
References Instance(), IsInstanceCreated(), mQueueNotEmptyCond, mQueueNotEmptyCondLock, mTerminate, mTerminated, mTerminatedMutex, and mTerminateMutex.
Referenced by QuitAudacity().
void ODManager::RemoveTaskIfInQueue (ODTask * task)
removes a task from the active task queue
References mTasks, and mTasksMutex.
Referenced by ODWaveTrackTaskQueue::~ODWaveTrackTaskQueue().
void ODManager::RemoveWaveTrack (WaveTrack * track)
removes a wavetrack and notifies its associated tasks to stop using its reference.
References mQueues, and mQueuesMutex.
Referenced by WaveTrack::~WaveTrack().
void ODManager::ReplaceWaveTrack (WaveTrack * oldTrack, WaveTrack * newTrack)
replace the wavetrack whose wavecache the gui watches for updates
References mQueues, and mQueuesMutex.
Referenced by Effect::ReplaceProcessedTracks().
void ODManager::Resume () [static]
References Pause().
Referenced by AudacityProject::OnImport(), and AudacityProject::OpenFiles().
void ODManager::SignalTaskQueueLoop ()
Wakes the queue loop up by signalling its condition variable.
References mPause, mPauseLock, mQueueNotEmptyCond, and mQueueNotEmptyCondLock.
Referenced by AudacityProject::OnTimer().
void ODManager::Start () [protected]
Start the main loop for the manager.
Main loop for managing threads and tasks.
References AudacityProject::AllProjectsDeleteLock(), AudacityProject::AllProjectsDeleteUnlock(), GetActiveProject(), mCurrentThreads, mCurrentThreadsMutex, mMaxThreads, mNeedsDraw, mPause, mPauseLock, mQueueNotEmptyCond, mQueueNotEmptyCondLock, mQueues, mQueuesMutex, mTasks, mTasksMutex, mTerminate, mTerminated, mTerminatedMutex, mTerminateMutex, and UpdateQueues().
Referenced by ODManager::ODManagerHelperThread::Entry().
void ODManager::UnlockLibSndFileMutex () [static]
Referenced by ExportPCM::Export(), PCMAliasBlockFile::ReadData(), and ODPCMAliasBlockFile::ReadData().
void ODManager::UnmarkLoadedODFlag () [static]
resets a flag that is set if we have loaded some OD blockfiles from PCM.
References sHasLoadedOD.
Referenced by AudacityProject::OpenFile().
void ODManager::UpdateQueues () [protected]
Remove references in our array to Tasks that have been completed/Schedule new ones.
remove tasks from ODWaveTrackTaskQueues that have been done. Schedules new ones if they exist Also remove queues that have become empty.
References AddTask(), ODWaveTrackTaskQueue::GetFrontTask(), mQueues, and mQueuesMutex.
Referenced by Start().
Member Data Documentation
int ODManager::mCurrentThreads [protected]
Number of threads currently running. Accessed thru multiple threads.
Referenced by DecrementCurrentThreads(), Init(), and Start().
ODLock ODManager::mCurrentThreadsMutex [protected]
Referenced by DecrementCurrentThreads(), and Start().
int ODManager::mMaxThreads [protected]
Maximum number of threads allowed out.
Referenced by Init(), and Start().
int ODManager::mNeedsDraw [protected]
Referenced by Start().
bool ODManager::mPause [protected]
Referenced by AddTask(), ODManager(), Pause(), SignalTaskQueueLoop(), and Start().
ODLock ODManager::mPauseLock [protected]
Referenced by AddTask(), Pause(), SignalTaskQueueLoop(), and Start().
ODCondition* ODManager::mQueueNotEmptyCond [protected]
Referenced by AddTask(), ODManager(), Pause(), Quit(), SignalTaskQueueLoop(), Start(), and ~ODManager().
ODLock ODManager::mQueueNotEmptyCondLock [protected]
Referenced by AddTask(), ODManager(), Pause(), Quit(), SignalTaskQueueLoop(), and Start().
std::vector<ODWaveTrackTaskQueue*> ODManager::mQueues [protected]
Referenced by AddNewTask(), DemandTrackUpdate(), FillTipForWaveTrack(), GetOverallPercentComplete(), GetTotalNumTasks(), MakeWaveTrackDependent(), MakeWaveTrackIndependent(), RemoveWaveTrack(), ReplaceWaveTrack(), Start(), UpdateQueues(), and ~ODManager().
ODLock ODManager::mQueuesMutex [protected]
Referenced by AddNewTask(), DemandTrackUpdate(), FillTipForWaveTrack(), GetOverallPercentComplete(), GetTotalNumTasks(), MakeWaveTrackDependent(), MakeWaveTrackIndependent(), RemoveWaveTrack(), ReplaceWaveTrack(), Start(), and UpdateQueues().
std::vector<ODTask*> ODManager::mTasks [protected]
Referenced by AddTask(), RemoveTaskIfInQueue(), and Start().
ODLock ODManager::mTasksMutex [protected]
Referenced by AddTask(), RemoveTaskIfInQueue(), and Start().
bool ODManager::mTerminate [protected]
Referenced by ODManager(), Quit(), and Start().
bool ODManager::mTerminated [protected]
Referenced by ODManager(), Quit(), and Start().
ODLock ODManager::mTerminatedMutex [protected]
Referenced by Quit(), and Start().
ODLock ODManager::mTerminateMutex [protected]
Referenced by Quit(), and Start().
The documentation for this class was generated from the following files:
ODManager.h
ODManager.cpp