Audacity: ExpandingToolBar Class Reference
ExpandingToolBar Class Reference
A smart ToolBar class that has a "MainPanel" which is always displayed, and an "ExtraPanel" that can be hidden to save space.
#include <ExpandingToolBar.h>
Public Member Functions
ExpandingToolBar (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
virtual ~ExpandingToolBar ()
wxPanel * GetMainPanel ()
wxPanel * GetExtraPanel ()
void SetAutoExpand (bool enabled)
bool GetAutoExpand ()
void Expand ()
void Collapse (bool now=false)
bool IsExpanded ()
void OnSize (wxSizeEvent &evt)
void OnToggle (wxCommandEvent &evt)
void OnTimer (wxTimerEvent &evt)
void StartMoving ()
void UpdateMoving ()
void FinishMoving ()
virtual bool Layout ()
virtual void Fit ()
Protected Member Functions
void RecursivelyPushEventHandlers (wxWindow *win)
bool IsCursorInWindow ()
void ReparentExtraPanel ()
void MoveDrawer (wxSize prevSize)
wxBitmap GetToolbarBitmap ()
void TryAutoExpand ()
void TryAutoCollapse ()
DECLARE_EVENT_TABLE ()
Protected Attributes
wxPanel * mMainPanel
wxPanel * mExtraPanel
ToolBarGrabber * mGrabber
AButton * mToggleButton
bool mIsAutoExpanded
bool mIsManualExpanded
bool mIsExpanded
bool mAutoExpand
bool mFirstTime
wxSize mMainSize
wxSize mExtraSize
wxSize mButtonSize
wxSize mGrabberSize
wxSize mCurrentDrawerSize
wxSize mTargetDrawerSize
wxSize mCurrentTotalSize
WindowHash mWindowHash
wxTimer mTimer
ToolBarFrame * mFrameParent
ToolBarDialog * mDialogParent
ToolBarArea * mAreaParent
ToolBarArrangement * mSavedArrangement
ImageRollPanel * mTargetPanel
wxDragImage * mDragImage
wxWindow * mTopLevelParent
wxArrayRect mDropTargets
wxRect mDropTarget
Static Protected Attributes
static int msNoAutoExpandStack = 0
Friends
class ExpandingToolBarEvtHandler
Detailed Description
A smart ToolBar class that has a "MainPanel" which is always displayed, and an "ExtraPanel" that can be hidden to save space.
Can be docked into a ToolBarArea or floated in an ToolBarFrame;
If auto-expanding is off, behavior is very simple: clicking the toggle button expands, clicking it again collapses.
If auto-expanding is on, behavior is a little more complicated. When the mouse movers over a toolbar and it is collapsed, it gets auto-expanded, and it gets auto-collapsed as soon as the mouse leaves. However, if they manually toggle it collapsed while it was auto-expanded, it will stay collapsed until you move the mouse completely away and then back again later. If you manually expand it, it will stay manually expanded until you manually collapse it.
Constructor & Destructor Documentation
ExpandingToolBar::ExpandingToolBar (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
Todo:
check whether this is a memory leak (and check similar code)
References ImageRoll::HorizontalRoll, ThemeBase::Image(), ImageRoll::SplitV(), and theTheme.
ExpandingToolBar::~ExpandingToolBar () [virtual]
Member Function Documentation
void ExpandingToolBar::Collapse (bool now = false)
References Fit(), mCurrentDrawerSize, mIsAutoExpanded, mIsManualExpanded, MoveDrawer(), mTargetDrawerSize, mToggleButton, and AButton::PopUp().
Referenced by OnToggle().
ExpandingToolBar::DECLARE_EVENT_TABLE () [protected]
void ExpandingToolBar::Expand ()
References Fit(), mIsAutoExpanded, mIsManualExpanded, mToggleButton, and AButton::PushDown().
Referenced by OnToggle().
void ExpandingToolBar::FinishMoving ()
References ToolBarArea::CollapseAll(), kDummyRect, kTimerInterval, mAreaParent, mDragImage, mDropTarget, ToolBarArea::MoveChild(), mSavedArrangement, msNoAutoExpandStack, mTargetPanel, mTimer, mTopLevelParent, ToolBarArea::RestoreArrangement(), and ToolBarArea::SetCapturedChild().
Referenced by ToolBarArea::OnMouse().
void ExpandingToolBar::Fit () [virtual]
References kTimerInterval, mButtonSize, mCurrentDrawerSize, mCurrentTotalSize, mExtraSize, mFirstTime, mGrabberSize, mIsAutoExpanded, mIsExpanded, mIsManualExpanded, mMainSize, mTargetDrawerSize, and mTimer.
Referenced by Collapse(), Expand(), TryAutoCollapse(), and TryAutoExpand().
bool ExpandingToolBar::GetAutoExpand () [inline]
References mAutoExpand.
wxPanel* ExpandingToolBar::GetExtraPanel () [inline]
References mExtraPanel.
wxPanel* ExpandingToolBar::GetMainPanel () [inline]
References mMainPanel.
wxBitmap ExpandingToolBar::GetToolbarBitmap () [protected]
Referenced by StartMoving().
bool ExpandingToolBar::IsCursorInWindow () [protected]
References mCurrentTotalSize, and mGrabber.
Referenced by OnTimer(), and ExpandingToolBarEvtHandler::ProcessEvent().
bool ExpandingToolBar::IsExpanded () [inline]
References mIsExpanded.
bool ExpandingToolBar::Layout () [virtual]
References kToggleButtonHeight, mButtonSize, mExtraPanel, mExtraSize, mGrabber, mGrabberSize, mMainPanel, mMainSize, and mToggleButton.
void ExpandingToolBar::MoveDrawer (wxSize prevSize) [protected]
References mAreaParent, mButtonSize, mCurrentDrawerSize, mCurrentTotalSize, mDialogParent, mExtraPanel, mFrameParent, mMainSize, and ReparentExtraPanel().
Referenced by Collapse(), and OnTimer().
void ExpandingToolBar::OnSize (wxSizeEvent & evt)
References ToolBarArea::AddChild(), mAreaParent, mDialogParent, mFrameParent, ToolBarDialog::SetChild(), and ToolBarFrame::SetChild().
void ExpandingToolBar::OnTimer (wxTimerEvent & evt)
References IsCursorInWindow(), mAutoExpand, mCurrentDrawerSize, MoveDrawer(), msNoAutoExpandStack, mTargetDrawerSize, TryAutoCollapse(), and TryAutoExpand().
void ExpandingToolBar::OnToggle (wxCommandEvent & evt)
References Collapse(), Expand(), and mIsExpanded.
void ExpandingToolBar::RecursivelyPushEventHandlers (wxWindow * win) [protected]
References ExpandingToolBarEvtHandler, and mWindowHash.
void ExpandingToolBar::ReparentExtraPanel () [protected]
References mButtonSize, mExtraPanel, mGrabberSize, and mMainSize.
Referenced by MoveDrawer().
void ExpandingToolBar::SetAutoExpand (bool enabled) [inline]
References mAutoExpand.
void ExpandingToolBar::StartMoving ()
References ToolBarArea::CollapseAll(), ToolBarArea::GetDropTargets(), GetToolbarBitmap(), ThemeBase::Image(), kDummyRect, mAreaParent, mDragImage, mDropTarget, mDropTargets, mSavedArrangement, msNoAutoExpandStack, mTargetPanel, mTimer, mTopLevelParent, ToolBarArea::RemoveChild(), ToolBarArea::SaveArrangement(), ToolBarArea::SetCapturedChild(), ImageRollPanel::SetLogicalFunction(), theTheme, and ImageRoll::VerticalRoll.
Referenced by ToolBarGrabber::OnMouse().
void ExpandingToolBar::TryAutoCollapse () [protected]
References Fit(), mIsAutoExpanded, mIsManualExpanded, mToggleButton, and AButton::PopUp().
Referenced by OnTimer().
void ExpandingToolBar::TryAutoExpand () [protected]
References Fit(), mAutoExpand, mIsAutoExpanded, mIsManualExpanded, msNoAutoExpandStack, mToggleButton, and AButton::PushDown().
Referenced by OnTimer(), and ExpandingToolBarEvtHandler::ProcessEvent().
void ExpandingToolBar::UpdateMoving ()
References kDummyRect, mAreaParent, mDragImage, mDropTarget, mDropTargets, mSavedArrangement, and mTargetPanel.
Referenced by ToolBarArea::OnMouse().
Friends And Related Function Documentation
friend class ExpandingToolBarEvtHandler [friend]
Referenced by RecursivelyPushEventHandlers().
Member Data Documentation
ToolBarArea* ExpandingToolBar::mAreaParent [protected]
Referenced by FinishMoving(), MoveDrawer(), OnSize(), StartMoving(), and UpdateMoving().
bool ExpandingToolBar::mAutoExpand [protected]
Referenced by GetAutoExpand(), OnTimer(), SetAutoExpand(), and TryAutoExpand().
wxSize ExpandingToolBar::mButtonSize [protected]
Referenced by Fit(), Layout(), MoveDrawer(), and ReparentExtraPanel().
wxSize ExpandingToolBar::mCurrentDrawerSize [protected]
Referenced by Collapse(), Fit(), MoveDrawer(), and OnTimer().
wxSize ExpandingToolBar::mCurrentTotalSize [protected]
Referenced by Fit(), IsCursorInWindow(), and MoveDrawer().
ToolBarDialog* ExpandingToolBar::mDialogParent [protected]
Referenced by MoveDrawer(), and OnSize().
wxDragImage* ExpandingToolBar::mDragImage [protected]
Referenced by FinishMoving(), StartMoving(), and UpdateMoving().
wxRect ExpandingToolBar::mDropTarget [protected]
Referenced by FinishMoving(), StartMoving(), and UpdateMoving().
wxArrayRect ExpandingToolBar::mDropTargets [protected]
Referenced by StartMoving(), and UpdateMoving().
wxPanel* ExpandingToolBar::mExtraPanel [protected]
Referenced by GetExtraPanel(), Layout(), MoveDrawer(), and ReparentExtraPanel().
wxSize ExpandingToolBar::mExtraSize [protected]
Referenced by Fit(), and Layout().
bool ExpandingToolBar::mFirstTime [protected]
Referenced by Fit().
ToolBarFrame* ExpandingToolBar::mFrameParent [protected]
Referenced by MoveDrawer(), and OnSize().
ToolBarGrabber* ExpandingToolBar::mGrabber [protected]
Referenced by IsCursorInWindow(), and Layout().
wxSize ExpandingToolBar::mGrabberSize [protected]
Referenced by Fit(), Layout(), and ReparentExtraPanel().
bool ExpandingToolBar::mIsAutoExpanded [protected]
Referenced by Collapse(), Expand(), Fit(), TryAutoCollapse(), and TryAutoExpand().
bool ExpandingToolBar::mIsExpanded [protected]
Referenced by Fit(), IsExpanded(), and OnToggle().
bool ExpandingToolBar::mIsManualExpanded [protected]
Referenced by Collapse(), Expand(), Fit(), TryAutoCollapse(), and TryAutoExpand().
wxPanel* ExpandingToolBar::mMainPanel [protected]
Referenced by GetMainPanel(), and Layout().
wxSize ExpandingToolBar::mMainSize [protected]
Referenced by Fit(), Layout(), MoveDrawer(), and ReparentExtraPanel().
ToolBarArrangement* ExpandingToolBar::mSavedArrangement [protected]
Referenced by FinishMoving(), StartMoving(), and UpdateMoving().
int ExpandingToolBar::msNoAutoExpandStack = 0 [static, protected]
Referenced by FinishMoving(), OnTimer(), StartMoving(), and TryAutoExpand().
wxSize ExpandingToolBar::mTargetDrawerSize [protected]
Referenced by Collapse(), Fit(), and OnTimer().
ImageRollPanel* ExpandingToolBar::mTargetPanel [protected]
Referenced by FinishMoving(), StartMoving(), and UpdateMoving().
wxTimer ExpandingToolBar::mTimer [protected]
Referenced by FinishMoving(), Fit(), and StartMoving().
AButton* ExpandingToolBar::mToggleButton [protected]
Referenced by Collapse(), Expand(), Layout(), TryAutoCollapse(), and TryAutoExpand().
wxWindow* ExpandingToolBar::mTopLevelParent [protected]
Referenced by FinishMoving(), and StartMoving().
WindowHash ExpandingToolBar::mWindowHash [protected]
Referenced by RecursivelyPushEventHandlers().
The documentation for this class was generated from the following files:
ExpandingToolBar.h
ExpandingToolBar.cpp