Audacity: FFmpegImportFileHandle Class Reference
FFmpegImportFileHandle Class Reference
! Does acual import, returned by FFmpegImportPlugin::Open
Public Member Functions
FFmpegImportFileHandle (const wxString &name)
~FFmpegImportFileHandle ()
bool Init ()
bool InitCodecs ()
wxString GetFileDescription ()
int GetFileUncompressedBytes ()
int Import (TrackFactory *trackFactory, Track ***outTracks, int *outNumTracks, Tags *tags)
streamContext * ReadNextFrame ()
int DecodeFrame (streamContext *sc, bool flushing)
int WriteData (streamContext *sc)
void WriteMetadata (AVFormatContext *avf, Tags *tags)
wxInt32 GetStreamCount ()
wxArrayString * GetStreamInfo ()
void SetStreamUsage (wxInt32 StreamID, bool Use)
Private Attributes
AVFormatContext * mFormatContext
Format description, also contains metadata and some useful info.
int mNumStreams
mNumstreams is less or equal to mFormatContext->nb_streams
streamContext ** mScs
Array of pointers to stream contexts. Length is mNumStreams.
wxArrayString * mStreamInfo
Array of stream descriptions. Length is mNumStreams.
wxInt64 mProgressPos
Current timestamp, file position or whatever is used as first argument for Update().
wxInt64 mProgressLen
Duration, total length or whatever is used as second argument for Update().
bool mCancelled
True if importing was canceled by user.
bool mStopped
True if importing was stopped by user.
wxString mName
WaveTrack *** mChannels
2-dimentional array of WaveTrack's. First dimention - streams, second - channels of a stream. Length is mNumStreams
Detailed Description
! Does acual import, returned by FFmpegImportPlugin::Open
An ImportFileHandle for FFmpeg data.
Constructor & Destructor Documentation
FFmpegImportFileHandle::FFmpegImportFileHandle (const wxString & name)
References mCancelled, mChannels, mFormatContext, mName, mNumStreams, mProgressLen, mProgressPos, mScs, mStopped, mStreamInfo, and PickFFmpegLibs().
FFmpegImportFileHandle::~FFmpegImportFileHandle ()
References FFmpegLibs::av_close_input_file, FFmpegLibs::av_free, FFmpegLibs::av_log_default_callback, FFmpegLibs::av_log_set_callback, DropFFmpegLibs(), mFormatContext, mNumStreams, mScs, mStreamInfo, and FFmpegLibs::ValidLibsLoaded().
Member Function Documentation
int FFmpegImportFileHandle::DecodeFrame (streamContext * sc, bool flushing)
! Decodes the frame
Parameters:
sc - stream context (from ReadNextFrame)
flushing - true if flushing (no more frames left), false otherwise
Returns:
0 on success, -1 if it can't decode any further
References FFmpegLibs::av_fast_realloc, FFmpegLibs::avcodec_decode_audio2, _streamContext::m_codecCtx, _streamContext::m_decodedAudioSamples, _streamContext::m_decodedAudioSamplesSiz, _streamContext::m_decodedAudioSamplesValidSiz, _streamContext::m_frameValid, _streamContext::m_pkt, _streamContext::m_pktDataPtr, _streamContext::m_pktRemainingSiz, and _streamContext::m_pktValid.
Referenced by Import().
wxString FFmpegImportFileHandle::GetFileDescription () [virtual]
Implements ImportFileHandle.
References DESC.
int FFmpegImportFileHandle::GetFileUncompressedBytes () [virtual]
Implements ImportFileHandle.
wxInt32 FFmpegImportFileHandle::GetStreamCount () [inline, virtual]
! Called by Import.cpp
Returns:
number of readable streams in the file
Implements ImportFileHandle.
References mNumStreams.
wxArrayString* FFmpegImportFileHandle::GetStreamInfo () [inline, virtual]
! Called by Import.cpp
Returns:
array of strings - descriptions of the streams
Implements ImportFileHandle.
References mStreamInfo.
int FFmpegImportFileHandle::Import (TrackFactory * trackFactory, Track *** outTracks, int * outNumTracks, Tags * tags) [virtual]
! Imports audio
Returns:
import status (see Import.cpp)
TODO: Nag FFmpeg devs about start_time until they finally say WHAT is this and HOW to handle it.
Implements ImportFileHandle.
References FFmpegLibs::av_free_packet, ImportFileHandle::CreateProgress(), DecodeFrame(), eProgressCancelled, eProgressFailed, eProgressStopped, eProgressSuccess, WaveTrack::Flush(), WaveTrack::InsertSilence(), int16Sample, Track::LeftChannel, _streamContext::m_frameValid, _streamContext::m_initialchannels, _streamContext::m_pkt, _streamContext::m_pktRemainingSiz, _streamContext::m_pktValid, _streamContext::m_stream, mChannels, mFormatContext, mNumStreams, Track::MonoChannel, mScs, TrackFactory::NewWaveTrack(), ReadNextFrame(), Track::RightChannel, Track::SetChannel(), Track::SetLinked(), WriteData(), and WriteMetadata().
bool FFmpegImportFileHandle::Init ()
! Format initialization
Returns:
true if successful, false otherwise
References FFmpegLibs::av_find_stream_info, FFmpegLibs::av_log_set_callback, av_log_wx_callback(), InitCodecs(), mFormatContext, mName, ufile_fopen_input(), and FFmpegLibs::ValidLibsLoaded().
Referenced by FFmpegImportPlugin::Open().
bool FFmpegImportFileHandle::InitCodecs ()
! Codec initialization
Returns:
true if successful, false otherwise
References FFmpegLibs::avcodec_find_decoder, FFmpegLibs::avcodec_open, _streamContext::m_codecCtx, _streamContext::m_stream, mFormatContext, mNumStreams, mScs, and mStreamInfo.
Referenced by Init().
streamContext * FFmpegImportFileHandle::ReadNextFrame ()
! Reads next audio frame
Returns:
pointer to the stream context structure to which the frame belongs to or NULL on error, or 1 if stream is not to be imported.
References FFmpegLibs::av_free_packet, FFmpegLibs::av_read_frame, _streamContext::m_pkt, _streamContext::m_pktDataPtr, _streamContext::m_pktRemainingSiz, _streamContext::m_pktValid, mFormatContext, mNumStreams, and mScs.
Referenced by Import().
void FFmpegImportFileHandle::SetStreamUsage (wxInt32 StreamID, bool Use) [inline, virtual]
! Called by Import.cpp
Parameters:
StreamID - index of the stream in mStreamInfo and mScs arrays
Use - true if this stream should be imported, false otherwise
Implements ImportFileHandle.
References _streamContext::m_use, mNumStreams, and mScs.
int FFmpegImportFileHandle::WriteData (streamContext * sc)
! Writes decoded data into WaveTracks. Called by DecodeFrame
Parameters:
sc - stream context
Returns:
0 on success, 1 on error or interruption
References WaveTrack::Append(), eProgressSuccess, int16Sample, _streamContext::m_codecCtx, _streamContext::m_decodedAudioSamples, _streamContext::m_decodedAudioSamplesValidSiz, _streamContext::m_initialchannels, _streamContext::m_pkt, _streamContext::m_stream, mChannels, mFormatContext, mNumStreams, ImportFileHandle::mProgress, mProgressLen, mProgressPos, mScs, and ProgressDialog::Update().
Referenced by Import().
void FFmpegImportFileHandle::WriteMetadata (AVFormatContext * avf, Tags * tags)
! Writes extracted metadata to tags object
Parameters:
avf - file context \ tags - Audacity tags object
References Tags::Clear(), Tags::SetTag(), TAG_ALBUM, TAG_ARTIST, TAG_COMMENTS, TAG_GENRE, TAG_TITLE, TAG_TRACK, and TAG_YEAR.
Referenced by Import().
Member Data Documentation
bool FFmpegImportFileHandle::mCancelled [private]
True if importing was canceled by user.
Referenced by FFmpegImportFileHandle().
WaveTrack*** FFmpegImportFileHandle::mChannels [private]
2-dimentional array of WaveTrack's. First dimention - streams, second - channels of a stream. Length is mNumStreams
Referenced by FFmpegImportFileHandle(), Import(), and WriteData().
AVFormatContext* FFmpegImportFileHandle::mFormatContext [private]
Format description, also contains metadata and some useful info.
Referenced by FFmpegImportFileHandle(), Import(), Init(), InitCodecs(), ReadNextFrame(), WriteData(), and ~FFmpegImportFileHandle().
wxString FFmpegImportFileHandle::mName [private]
Referenced by FFmpegImportFileHandle(), and Init().
int FFmpegImportFileHandle::mNumStreams [private]
mNumstreams is less or equal to mFormatContext->nb_streams
Referenced by FFmpegImportFileHandle(), GetStreamCount(), Import(), InitCodecs(), ReadNextFrame(), SetStreamUsage(), WriteData(), and ~FFmpegImportFileHandle().
wxInt64 FFmpegImportFileHandle::mProgressLen [private]
Duration, total length or whatever is used as second argument for Update().
Referenced by FFmpegImportFileHandle(), and WriteData().
wxInt64 FFmpegImportFileHandle::mProgressPos [private]
Current timestamp, file position or whatever is used as first argument for Update().
Referenced by FFmpegImportFileHandle(), and WriteData().
streamContext** FFmpegImportFileHandle::mScs [private]
Array of pointers to stream contexts. Length is mNumStreams.
Referenced by FFmpegImportFileHandle(), Import(), InitCodecs(), ReadNextFrame(), SetStreamUsage(), WriteData(), and ~FFmpegImportFileHandle().
bool FFmpegImportFileHandle::mStopped [private]
True if importing was stopped by user.
Referenced by FFmpegImportFileHandle().
wxArrayString* FFmpegImportFileHandle::mStreamInfo [private]
Array of stream descriptions. Length is mNumStreams.
Referenced by FFmpegImportFileHandle(), GetStreamInfo(), InitCodecs(), and ~FFmpegImportFileHandle().
The documentation for this class was generated from the following file:
ImportFFmpeg.cpp