Audacity: ASlider Class Reference
ASlider Class Reference
ASlider is a custom slider, allowing for a slicker look and feel.
#include <ASlider.h>
Public Member Functions
ASlider (wxWindow *parent, wxWindowID id, wxString name, const wxPoint &pos, const wxSize &size, int style=FRAC_SLIDER, bool popup=true, bool canUseShift=true, float stepValue=STEP_CONTINUOUS, int orientation=wxHORIZONTAL)
virtual ~ASlider ()
void GetScroll (float &line, float &page)
void SetScroll (float line, float page)
float Get (bool convert=true)
void Set (float value)
void Increase (float steps)
void Decrease (float steps)
bool ShowDialog (wxPoint pos=wxPoint(-1,-1))
void SetSpeed (float speed)
void OnErase (wxEraseEvent &event)
void OnPaint (wxPaintEvent &event)
void OnSize (wxSizeEvent &event)
void OnMouseEvent (wxMouseEvent &event)
void OnCaptureLost (wxMouseCaptureLostEvent &event)
void OnKeyEvent (wxKeyEvent &event)
void OnSlider (wxCommandEvent &event)
void OnSetFocus (wxFocusEvent &event)
void OnKillFocus (wxFocusEvent &event)
void RecreateTipWin ()
bool Enable (bool enable=true)
bool IsEnabled () const
Protected Attributes
int mStyle
Private Attributes
LWSlider * mLWSlider
bool mSliderIsFocused
Friends
class ASliderAx
Detailed Description
ASlider is a custom slider, allowing for a slicker look and feel.
It allows you to use images for the slider background and the thumb.
Constructor & Destructor Documentation
ASlider::ASlider (wxWindow * parent, wxWindowID id, wxString name, const wxPoint & pos, const wxSize & size, int style = FRAC_SLIDER, bool popup = true, bool canUseShift = true, float stepValue = STEP_CONTINUOUS, int orientation = wxHORIZONTAL)
ASlider::~ASlider () [virtual]
References mLWSlider.
Member Function Documentation
void ASlider::Decrease (float steps)
References LWSlider::Decrease(), and mLWSlider.
Referenced by MixerToolBar::AdjustInputGain(), MixerToolBar::AdjustOutputGain(), and TranscriptionToolBar::AdjustPlaySpeed().
bool ASlider::Enable (bool enable = true)
References LWSlider::GetEnabled(), mLWSlider, and LWSlider::SetEnabled().
Referenced by MixerToolBar::Populate(), and MixerToolBar::UpdatePrefs().
float ASlider::Get (bool convert = true)
References LWSlider::Get(), and mLWSlider.
Referenced by TranscriptionToolBar::Create(), SliderDialog::Get(), MixerTrackCluster::HandleSliderGain(), MixerTrackCluster::HandleSliderPan(), TranscriptionToolBar::OnSensitivitySlider(), TranscriptionToolBar::OnSpeedSlider(), MixerToolBar::SetMixer(), SliderDialog::TransferDataToWindow(), and MixerToolBar::UpdateControls().
void ASlider::GetScroll (float & line, float & page)
References LWSlider::GetScroll(), and mLWSlider.
void ASlider::Increase (float steps)
References LWSlider::Increase(), and mLWSlider.
Referenced by MixerToolBar::AdjustInputGain(), MixerToolBar::AdjustOutputGain(), and TranscriptionToolBar::AdjustPlaySpeed().
bool ASlider::IsEnabled () const
References LWSlider::GetEnabled(), and mLWSlider.
Referenced by MixerToolBar::SetToolTips().
void ASlider::OnCaptureLost (wxMouseCaptureLostEvent & event)
References mLWSlider, and LWSlider::OnMouseEvent().
void ASlider::OnErase (wxEraseEvent & event)
void ASlider::OnKeyEvent (wxKeyEvent & event)
References mLWSlider, and LWSlider::OnKeyEvent().
void ASlider::OnKillFocus (wxFocusEvent & event)
References mSliderIsFocused.
void ASlider::OnMouseEvent (wxMouseEvent & event)
Reimplemented in MixerTrackSlider.
References mLWSlider, and LWSlider::OnMouseEvent().
void ASlider::OnPaint (wxPaintEvent & event)
References AColor::DrawFocus(), LWSlider::mHeight, mLWSlider, mSliderIsFocused, LWSlider::mWidth, and LWSlider::OnPaint().
void ASlider::OnSetFocus (wxFocusEvent & event)
References mSliderIsFocused.
void ASlider::OnSize (wxSizeEvent & event)
References mLWSlider, and LWSlider::OnSize().
void ASlider::OnSlider (wxCommandEvent & event)
References LWSlider::GetId(), and mLWSlider.
void ASlider::RecreateTipWin ()
References mLWSlider, and LWSlider::RecreateTipWin().
Referenced by MixerToolBar::RecreateTipWindows().
void ASlider::Set (float value)
References mLWSlider, and LWSlider::Set().
Referenced by TranscriptionToolBar::Populate(), SliderDialog::TransferDataFromWindow(), MixerToolBar::UpdateControls(), MixerTrackCluster::UpdateGain(), and MixerTrackCluster::UpdatePan().
void ASlider::SetScroll (float line, float page)
References mLWSlider, and LWSlider::SetScroll().
Referenced by TranscriptionToolBar::Populate().
void ASlider::SetSpeed (float speed)
References mLWSlider, and LWSlider::SetSpeed().
bool ASlider::ShowDialog (wxPoint pos = wxPoint(-1, -1))
References mLWSlider, and LWSlider::ShowDialog().
Referenced by MixerToolBar::ShowInputGainDialog(), MixerToolBar::ShowOutputGainDialog(), and TranscriptionToolBar::ShowPlaySpeedDialog().
Friends And Related Function Documentation
friend class ASliderAx [friend]
Member Data Documentation
LWSlider* ASlider::mLWSlider [private]
Referenced by Decrease(), Enable(), Get(), GetScroll(), Increase(), IsEnabled(), OnCaptureLost(), OnKeyEvent(), OnMouseEvent(), OnPaint(), OnSize(), OnSlider(), RecreateTipWin(), Set(), SetScroll(), SetSpeed(), ShowDialog(), and ~ASlider().
bool ASlider::mSliderIsFocused [private]
Referenced by OnKillFocus(), OnPaint(), and OnSetFocus().
int ASlider::mStyle [protected]
Referenced by MixerTrackSlider::OnMouseEvent().
The documentation for this class was generated from the following files:
ASlider.h
ASlider.cpp