Audacity: Generator Class Reference
Generator Class Reference
#include <Generator.h>
Public Member Functions
Generator ()
Protected Member Functions
virtual bool GenerateTrack (WaveTrack *tmp, const WaveTrack &track, int ntrack)=0
virtual bool Init ()
virtual void BeforeGenerate ()
virtual void BeforeTrack (const WaveTrack &track)
virtual void Success ()
virtual void Failure ()
bool Process ()
Protected Attributes
double mDuration
Constructor & Destructor Documentation
Generator::Generator () [inline]
Member Function Documentation
virtual void Generator::BeforeGenerate () [inline, protected, virtual]
Reimplemented in EffectToneGen.
Referenced by Process().
virtual void Generator::BeforeTrack (const WaveTrack & track) [inline, protected, virtual]
Reimplemented in EffectToneGen.
Referenced by Process().
virtual void Generator::Failure () [inline, protected, virtual]
Referenced by Process().
virtual bool Generator::GenerateTrack (WaveTrack * tmp, const WaveTrack & track, int ntrack) [protected, pure virtual]
Implemented in EffectDtmf, BlockGenerator, and EffectSilence.
Referenced by Process().
virtual bool Generator::Init () [inline, protected, virtual]
Reimplemented from Effect.
Reimplemented in EffectDtmf, and EffectNoise.
bool Generator::Process () [protected, virtual]
Implements Effect.
References Track::All, BeforeGenerate(), BeforeTrack(), WaveTrack::Clear(), WaveTrack::ClearAndPaste(), Effect::CopyInputTracks(), Failure(), TrackListIterator::First(), WaveTrack::Flush(), GenerateTrack(), Track::GetKind(), WaveTrack::GetRate(), WaveTrack::GetSampleFormat(), Track::GetSelected(), Effect::GetTimeWarper(), gPrefs, WaveTrack::IsEmpty(), Track::IsSynchroSelected(), mDuration, Effect::mFactory, Effect::mOutputTracks, Effect::mT0, Effect::mT1, TrackFactory::NewWaveTrack(), TrackListIterator::Next(), Effect::ReplaceProcessedTracks(), Effect::SetTimeWarper(), Success(), Track::SyncAdjust(), and Track::Wave.
virtual void Generator::Success () [inline, protected, virtual]
Reimplemented in EffectDtmf, and EffectNoise.
Referenced by Process().
Member Data Documentation
double Generator::mDuration [protected]
Referenced by EffectSilence::GenerateTrack(), BlockGenerator::GenerateTrack(), EffectDtmf::GenerateTrack(), EffectToneGen::GetEffectDescription(), EffectSilence::GetEffectDescription(), EffectNoise::GetEffectDescription(), EffectDtmf::GetEffectDescription(), EffectNoise::Init(), EffectDtmf::Init(), Process(), EffectToneGen::PromptUser(), EffectSilence::PromptUser(), EffectNoise::PromptUser(), EffectDtmf::PromptUser(), EffectNoise::Success(), and EffectDtmf::Success().
The documentation for this class was generated from the following files:
Generator.h
Generator.cpp