Audacity: TimeDialog Class Reference
TimeDialog Class Reference
Dialog used to request a time value.
#include <TimeDialog.h>
Public Member Functions
TimeDialog (wxWindow *parent, const wxString &title, const wxString &prompt=_("Duration"))
void SetFormatString (wxString formatString)
void SetSampleRate (double sampleRate)
void SetTimeValue (double newTime)
const double GetTimeValue ()
Private Member Functions
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
void OnUpdate (wxCommandEvent &event)
DECLARE_EVENT_TABLE ()
Private Attributes
wxString mPrompt
wxString mFormat
double mRate
double mTime
TimeTextCtrl * mTimeCtrl
Detailed Description
Dialog used to request a time value.
Constructor & Destructor Documentation
TimeDialog::TimeDialog (wxWindow * parent, const wxString & title, const wxString & prompt = _("Duration"))
References eIsCreating.
Member Function Documentation
TimeDialog::DECLARE_EVENT_TABLE () [private]
const double TimeDialog::GetTimeValue ()
References mTime.
Referenced by AudacityProject::OnSetLeftSelection(), AudacityProject::OnSetRightSelection(), and EffectSilence::PromptUser().
void TimeDialog::OnUpdate (wxCommandEvent & event) [private]
void TimeDialog::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddWindow(), TimeTextCtrl::EnableMenu(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), TimeTextCtrl::GetBuiltinFormat(), mFormat, mPrompt, mRate, mTime, mTimeCtrl, ShuttleGuiBase::SetBorder(), TimeTextCtrl::SetFormatString(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartVerticalLay(), and TransferDataToWindow().
void TimeDialog::SetFormatString (wxString formatString)
References mFormat, and TransferDataToWindow().
Referenced by AudacityProject::OnSetLeftSelection(), AudacityProject::OnSetRightSelection(), and EffectSilence::PromptUser().
void TimeDialog::SetSampleRate (double sampleRate)
References mRate, and TransferDataToWindow().
Referenced by AudacityProject::OnSetLeftSelection(), AudacityProject::OnSetRightSelection(), and EffectSilence::PromptUser().
void TimeDialog::SetTimeValue (double newTime)
References mTime, and TransferDataToWindow().
Referenced by AudacityProject::OnSetLeftSelection(), AudacityProject::OnSetRightSelection(), and EffectSilence::PromptUser().
bool TimeDialog::TransferDataFromWindow () [private]
References TimeTextCtrl::GetTimeValue(), mTime, and mTimeCtrl.
bool TimeDialog::TransferDataToWindow () [private]
References TimeTextCtrl::GetBuiltinFormat(), mFormat, mRate, mTime, mTimeCtrl, TimeTextCtrl::SetFormatString(), TimeTextCtrl::SetSampleRate(), and TimeTextCtrl::SetTimeValue().
Referenced by PopulateOrExchange(), SetFormatString(), SetSampleRate(), and SetTimeValue().
Member Data Documentation
wxString TimeDialog::mFormat [private]
Referenced by PopulateOrExchange(), SetFormatString(), and TransferDataToWindow().
wxString TimeDialog::mPrompt [private]
Referenced by PopulateOrExchange().
double TimeDialog::mRate [private]
Referenced by PopulateOrExchange(), SetSampleRate(), and TransferDataToWindow().
double TimeDialog::mTime [private]
Referenced by GetTimeValue(), PopulateOrExchange(), SetTimeValue(), TransferDataFromWindow(), and TransferDataToWindow().
TimeTextCtrl* TimeDialog::mTimeCtrl [private]
Referenced by PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
TimeDialog.h
TimeDialog.cpp