Audacity: SplashDialog Class Reference
SplashDialog Class Reference
The SplashDialog shows help information for Audacity when Audacity starts up.
#include <SplashDialog.h>
Public Member Functions
SplashDialog (wxWindow *parent)
virtual ~SplashDialog ()
void OnOK (wxCommandEvent &event)
Static Public Member Functions
static void Show2 (wxWindow *pParent)
Private Member Functions
void Populate (ShuttleGui &S)
void OnDontShow (wxCommandEvent &Evt)
Private Attributes
HtmlWindow * mpHtml
wxStaticBitmap * m_pIcon
wxBitmap * m_pLogo
Static Private Attributes
static SplashDialog * pSelf = NULL
Detailed Description
The SplashDialog shows help information for Audacity when Audacity starts up.
It was written for the benefit of new users who do not want to read the manual. The text of the dialog is kept short to increase the chance of it being read. The content is designed to reduce the most commonly asked questions about Audacity.
Constructor & Destructor Documentation
SplashDialog::SplashDialog (wxWindow * parent)
References ThemeBase::Colour(), eIsCreating, and theTheme.
Referenced by Show2().
SplashDialog::~SplashDialog () [virtual]
References m_pIcon, and m_pLogo.
Member Function Documentation
void SplashDialog::OnDontShow (wxCommandEvent & Evt) [private]
References gPrefs.
void SplashDialog::OnOK (wxCommandEvent & event)
void SplashDialog::Populate (ShuttleGui & S) [private]
References ShuttleGuiBase::AddCheckBox(), ShuttleGuiBase::AddWindow(), ThemeBase::Colour(), DontShowID, ShuttleGuiBase::EndVerticalLay(), ShuttleGuiBase::GetParent(), gPrefs, HelpText(), ShuttleGui::Id(), LOGOWITHNAME_HEIGHT, LOGOWITHNAME_WIDTH, m_pIcon, m_pLogo, mpHtml, ShuttleGui::Prop(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartVerticalLay(), and theTheme.
void SplashDialog::Show2 (wxWindow * pParent) [static]
References HelpText(), mpHtml, pSelf, and SplashDialog().
Referenced by AudacityProject::OnHelpWelcome().
Member Data Documentation
wxStaticBitmap* SplashDialog::m_pIcon [private]
Referenced by Populate(), and ~SplashDialog().
wxBitmap* SplashDialog::m_pLogo [private]
Referenced by Populate(), and ~SplashDialog().
HtmlWindow* SplashDialog::mpHtml [private]
Referenced by Populate(), and Show2().
SplashDialog * SplashDialog::pSelf = NULL [static, private]
Referenced by Show2().
The documentation for this class was generated from the following files:
SplashDialog.h
SplashDialog.cpp