Audacity: CommandBuilder Class Reference
CommandBuilder Class Reference
A type of factory for Commands of various sorts.
#include <CommandBuilder.h>
Public Member Functions
CommandBuilder (const wxString &cmdString)
CommandBuilder (const wxString &cmdName, const wxString &cmdParams)
~CommandBuilder ()
bool WasValid ()
Command * GetCommand ()
void Cleanup ()
const wxString & GetErrorMessage ()
Private Member Functions
void Failure (const wxString &msg=wxEmptyString)
void Success (Command *cmd)
void BuildCommand (const wxString &cmdName, wxString cmdParams)
void BuildCommand (wxString cmdString)
Private Attributes
bool mValid
Command * mCommand
wxString mError
Detailed Description
A type of factory for Commands of various sorts.
CommandBuilder has the task of deciding what command is meant by a given command string, and producing a suitable command object. For now, it doesn't actually do any processing - it just passes everything on to the BatchCommand system by constructing BatchCommandEval objects.
Constructor & Destructor Documentation
CommandBuilder::CommandBuilder (const wxString & cmdString)
References BuildCommand().
CommandBuilder::CommandBuilder (const wxString & cmdName, const wxString & cmdParams)
References BuildCommand().
CommandBuilder::~CommandBuilder ()
References Cleanup().
Member Function Documentation
void CommandBuilder::BuildCommand (wxString cmdString) [private]
References BuildCommand(), mError, mValid, and ScriptCommandRelay::SendResponse().
void CommandBuilder::BuildCommand (const wxString & cmdName, wxString cmdParams) [private]
References CommandType::Create(), Failure(), CommandDirectory::Get(), CommandSignature::GetDefaults(), ScriptCommandRelay::GetResponseTarget(), CommandType::GetSignature(), CommandDirectory::LookUp(), Shuttle::mbStoreInClient, mCommand, ShuttleCli::mParams, Command::SetParameter(), Success(), and Shuttle::TransferString().
Referenced by BuildCommand(), and CommandBuilder().
void CommandBuilder::Cleanup ()
References mCommand.
Referenced by ExecCommand(), and ~CommandBuilder().
void CommandBuilder::Failure (const wxString & msg = wxEmptyString) [private]
References mError, and mValid.
Referenced by BuildCommand().
Command * CommandBuilder::GetCommand ()
References mCommand, and mValid.
Referenced by ExecCommand().
const wxString & CommandBuilder::GetErrorMessage ()
References mError.
Referenced by ExecCommand().
void CommandBuilder::Success (Command * cmd) [private]
References mCommand, and mValid.
Referenced by BuildCommand().
bool CommandBuilder::WasValid ()
References mValid.
Referenced by ExecCommand().
Member Data Documentation
Command* CommandBuilder::mCommand [private]
Referenced by BuildCommand(), Cleanup(), GetCommand(), and Success().
wxString CommandBuilder::mError [private]
Referenced by BuildCommand(), Failure(), and GetErrorMessage().
bool CommandBuilder::mValid [private]
Referenced by BuildCommand(), Failure(), GetCommand(), Success(), and WasValid().
The documentation for this class was generated from the following files:
CommandBuilder.h
CommandBuilder.cpp