Audacity: Importer Class Reference
Importer Class Reference
Class which actulaly imports the auido, using functions defined in ImportPCM.cpp, ImportMP3.cpp, ImportOGG.cpp, ImportRawData.cpp, and ImportLOF.cpp.
#include <Import.h>
Public Member Functions
Importer ()
~Importer ()
void GetSupportedImportFormats (FormatList *formatList)
int Import (wxString fName, TrackFactory *trackFactory, Track ***tracks, Tags *tags, wxString &errorMessage)
Private Attributes
ImportPluginList * mImportPluginList
UnusableImportPluginList * mUnusableImportPluginList
Detailed Description
Class which actulaly imports the auido, using functions defined in ImportPCM.cpp, ImportMP3.cpp, ImportOGG.cpp, ImportRawData.cpp, and ImportLOF.cpp.
Constructor & Destructor Documentation
Importer::Importer ()
References GetFFmpegImportPlugin(), GetFLACImportPlugin(), GetGStreamerImportPlugin(), GetLOFImportPlugin(), GetMP3ImportPlugin(), GetOGGImportPlugin(), GetPCMImportPlugin(), GetQTImportPlugin(), mImportPluginList, and mUnusableImportPluginList.
Importer::~Importer ()
References mImportPluginList, and mUnusableImportPluginList.
Member Function Documentation
void Importer::GetSupportedImportFormats (FormatList * formatList)
References ImportPlugin::GetPluginFormatDescription(), ImportPlugin::GetSupportedExtensions(), and mImportPluginList.
Referenced by BatchProcessDialog::OnApplyToFiles(), and AudacityProject::ShowOpenDialog().
int Importer::Import (wxString fName, TrackFactory * trackFactory, Track *** tracks, Tags * tags, wxString & errorMessage)
References eProgressCancelled, eProgressFailed, eProgressStopped, eProgressSuccess, ImportPlugin::GetPluginFormatDescription(), ImportFileHandle::GetStreamCount(), gPrefs, ImportFileHandle::Import(), mImportPluginList, mUnusableImportPluginList, ImportPlugin::Open(), ImportFileHandle::SetStreamUsage(), UnusableImportPlugin::SupportsExtension(), and ImportPlugin::SupportsExtension().
Referenced by AudacityProject::Import().
Member Data Documentation
ImportPluginList* Importer::mImportPluginList [private]
Referenced by GetSupportedImportFormats(), Import(), Importer(), and ~Importer().
UnusableImportPluginList* Importer::mUnusableImportPluginList [private]
Referenced by Import(), Importer(), and ~Importer().
The documentation for this class was generated from the following files:
Import.h
Import.cpp