#!/usr/bin/perl

# Copyright 2003, 2004 Dominic Mazzoni and Matt Brubeck
# Distributed under the GNU General Public License 2.0.
# See the file LICENSE.txt for details.
# Version 1.2.2 for audacity 1.2.5 release tweaked by Richard Ash

print "maketarball 1.2.2 -- make Audacity distribution tarball\n";

unless(-f "src/Audacity.h") {
	print "Must be run from Audacity directory\n";
	exit;
}

# find version number
open(HEADER, "src/Audacity.h");
@lines = <HEADER>;
$lines = join " ", @lines;
$lines =~ /AUDACITY_VERSION_STRING "([0-9\-.a-z]*)"/;
$version = $1;
print "version set to $version...\n";
close(HEADER);

print "making copy of source directory...\n";
`cp -r . ../audacity-src-$version`;
chdir "../audacity-src-$version";

print "making distclean...\n";
`make distclean`;

print "removing CVS directories...\n";
`find . -name "CVS" -exec rm -rf '{}' \\; 2> /dev/null`;
`find . -name ".cvsignore" -exec rm -rf '{}' \\; 2> /dev/null`;

print "removing emacs / vim temp files...\n";
`find . -name "*~" -exec rm -rf '{}' \\; 2> /dev/null`;

print "removing executable and other intermediate files...\n";
`rm -rf audacity .depend obj config.cache config.status config.log Makefile`;
`rm -rf autom4te.cache`;

print "removing bugs and todo lists\n";
`rm -f bugs.txt todo.txt`;

print "removing scripts...\n";
`rm -rf scripts`;

print "removing libraries that should be installed locally...\n";
`rm -rf lib-src/libogg lib-src/libvorbis lib-src/libmad lib-src/id3lib`;
`rm -rf lib-src/libid3tag`;
`rm -rf lib-src/iAVC lib-src/libsamplerate`;
`rm -rf lib-src/wave++ lib-src/libflac`;

print "removing qa and test files\n";
`rm -rf qa`;
`rm -rf tests`;

print "removing doxygen files (unfinished)\n";
`rm audacity.dox`;

print "removing webbrowser help files\n";
`rm -rf help/webbrowser`;

print "removing unused portaudio-v19 dirs\n";
`rm -rf lib-src/portaudio-v19/docs`;
`rm -rf lib-src/portaudio-v19/pa_asio`;
`rm -rf lib-src/portaudio-v19/pa_sgi`;
`rm -rf lib-src/portaudio-v19/pa_mac_sm`;
`rm -f lib-src/portaudio-v19/pa_tests/debug*`;

print "removing wxstd locale files (since they should come with wxWidgets)\n";
`rm -rf locale/wxstd`;

print "removing Nyquist plug-ins that are just for show\n";
`rm -f plug-ins/analyze.ny plug-ins/fadein.ny plug-ins/fadeout.ny`;
`rm -f plug-ins/beat.ny plug-ins/undcbias.ny`;

#print "removing out-of-date translations: sl\n";
#`rm -f locale/sl.po`;
#
#`mv locale/Makefile.in /tmp/Makefile.in.tmp`;
#`sed 's/\<sl\>//' /tmp/Makefile.in.tmp > locale/Makefile.in`;
#`rm /tmp/Makefile.in.tmp`;

print "Giving VC++ project/workspace files DOS line endings\n";
`unix2dos win/audacity.sln`;
`unix2dos win/audacity.vcproj`;

print "Changing Windows header so that it doesn't build with\n";
print "support for libmad, libid3tag, or libvorbis by default.\n";

open FP, ">>win/configwin.h";
print FP "\n\n";
print FP "// The Audacity source tarball does NOT come with\n";
print FP "// libmad, libid3tag, libogg, or libvorbis.\n";
print FP "\n";
print FP "// Delete the following lines if you install them manually.\n";
print FP "\n";
print FP "#undef MP3SUPPORT\n";
print FP "#undef USE_LIBID3TAG\n";
print FP "#undef USE_LIBMAD\n";
print FP "#undef USE_LIBVORBIS\n";
close FP;

print "Removing VC++ 6.0 workspace and projects\n";
`rm win/audacity-nomp3ogg.dsw`;
`rm win/audacity.dsp`;
`rm win/audacity.dsw`;

#print "making tarball audacity-src-$version.tgz...\n";
chdir "..";
#`tar zcf audacity-src-$version.tgz audacity-src-$version`;

print "done.\n";
