Audacity: Contrast.cpp File Reference
Contrast.cpp File Reference
#include "../Audacity.h"
#include "../AudacityApp.h"
#include "Contrast.h"
#include "../Envelope.h"
#include "../FFT.h"
#include "../WaveTrack.h"
#include "../Prefs.h"
#include "../Project.h"
#include "../FileNames.h"
#include "../widgets/LinkingHtmlWindow.h"
#include "FileDialog.h"
#include <math.h>
#include <limits>
#include <wx/file.h>
#include <wx/ffile.h>
#include <wx/bitmap.h>
#include <wx/brush.h>
#include <wx/button.h>
#include <wx/datetime.h>
#include <wx/dcmemory.h>
#include <wx/image.h>
#include <wx/intl.h>
#include <wx/msgdlg.h>
#include <wx/sizer.h>
#include <wx/statbox.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/valtext.h>
#include "../PlatformCompatibility.h"
Enumerations
enum {
ID_BUTTON_GETFOREGROUND = 10001, ID_BUTTON_GETBACKGROUND, ID_BUTTON_USECURRENTF, ID_BUTTON_USECURRENTB,
ID_BUTTON_GETURL, ID_BUTTON_EXPORT, ID_BUTTON_RESET, ID_BUTTON_CLOSE,
ID_FOREGROUNDSTART_T, ID_FOREGROUNDEND_T, ID_BACKGROUNDSTART_T, ID_BACKGROUNDEND_T,
ID_FOREGROUNDDB_TEXT, ID_BACKGROUNDDB_TEXT, ID_RESULTS_TEXT, ID_RESULTSDB_TEXT
}
Functions
void InitContrastDialog (wxWindow *parent)
void CloseContrastDialog ()
Variables
static ContrastDialog * gContrastDialog = NULL
Enumeration Type Documentation
anonymous enum
Enumerator:
ID_BUTTON_GETFOREGROUND
ID_BUTTON_GETBACKGROUND
ID_BUTTON_USECURRENTF
ID_BUTTON_USECURRENTB
ID_BUTTON_GETURL
ID_BUTTON_EXPORT
ID_BUTTON_RESET
ID_BUTTON_CLOSE
ID_FOREGROUNDSTART_T
ID_FOREGROUNDEND_T
ID_BACKGROUNDSTART_T
ID_BACKGROUNDEND_T
ID_FOREGROUNDDB_TEXT
ID_BACKGROUNDDB_TEXT
ID_RESULTS_TEXT
ID_RESULTSDB_TEXT
Function Documentation
void CloseContrastDialog ()
Referenced by QuitAudacity().
void InitContrastDialog (wxWindow * parent)
References ContrastDialog::bBGset, ContrastDialog::bFGset, ContrastDialog::mBackgroundEndT, ContrastDialog::mBackgroundStartT, ContrastDialog::mForegroundEndT, ContrastDialog::mForegroundStartT, and TimeTextCtrl::SetTimeValue().
Referenced by AudacityProject::OnContrast().
Variable Documentation
ContrastDialog* gContrastDialog = NULL [static]