Audacity: FFmpeg.cpp File Reference
FFmpeg.cpp File Reference
#include "Audacity.h"
#include "FFmpeg.h"
#include "AudacityApp.h"
#include <wx/file.h>
Classes
class FindFFmpegDialog
Allows user to locate libav* libraries.
Defines
#define PROBE_BUF_MIN 2048
#define PROBE_BUF_MAX (1<<20)
#define ID_FFMPEG_BROWSE 5000
#define ID_FFMPEG_DLOAD 5001
Functions
FFmpegLibs * PickFFmpegLibs ()
void DropFFmpegLibs ()
bool LoadFFmpeg (bool showerror)
void FFmpegStartup ()
wxString GetFFmpegVersion (wxWindow *parent)
void av_log_wx_callback (void *ptr, int level, const char *fmt, va_list vl)
static int ufile_open (URLContext *h, const char *filename, int flags)
static int ufile_read (URLContext *h, unsigned char *buf, int size)
static int ufile_write (URLContext *h, unsigned char *buf, int size)
static offset_t ufile_seek (URLContext *h, offset_t pos, int whence)
static int ufile_close (URLContext *h)
int ufile_fopen (ByteIOContext **s, const wxString &name, int flags)
int ufile_fopen_input (AVFormatContext **ic_ptr, wxString &name)
Variables
FFmpegLibs * FFmpegLibsInst = NULL
URLProtocol ufile_protocol
Define Documentation
#define ID_FFMPEG_BROWSE 5000
Referenced by FindFFmpegDialog::PopulateOrExchange().
#define ID_FFMPEG_DLOAD 5001
Referenced by FindFFmpegDialog::PopulateOrExchange().
#define PROBE_BUF_MAX (1<<20)
Referenced by ufile_fopen_input().
#define PROBE_BUF_MIN 2048
Referenced by ufile_fopen_input().
Function Documentation
void av_log_wx_callback (void * ptr, int level, const char * fmt, va_list vl)
Callback function to catch FFmpeg log messages. Uses wxLogMessage.
Referenced by FFmpegImportFileHandle::Init(), and ExportFFmpeg::Init().
void DropFFmpegLibs ()
! Helper function - destroys FFmpegLibs object if there is no need for it anymore, or just decrements it's reference count
References FFmpegLibs::refcount.
Referenced by CheckFFmpegPresence(), ExportFFmpeg::Destroy(), GetFFmpegVersion(), LoadFFmpeg(), AudacityApp::OnExit(), LibraryPrefs::OnFFmpegFindButton(), ExportFFmpegOptions::~ExportFFmpegOptions(), and FFmpegImportFileHandle::~FFmpegImportFileHandle().
void FFmpegStartup ()
Called during Audacity start-up to try and load the ffmpeg libraries
References gPrefs, and LoadFFmpeg().
Referenced by AudacityApp::OnInit().
wxString GetFFmpegVersion (wxWindow * parent)
References DropFFmpegLibs(), FFmpegLibs::GetLibraryVersion(), PickFFmpegLibs(), and FFmpegLibs::ValidLibsLoaded().
Referenced by LibraryPrefs::SetFFmpegVersionText().
bool LoadFFmpeg (bool showerror)
References DropFFmpegLibs(), gPrefs, FFmpegLibs::LoadLibs(), PickFFmpegLibs(), and FFmpegLibs::ValidLibsLoaded().
Referenced by FFmpegStartup(), and LibraryPrefs::OnFFmpegFindButton().
FFmpegLibs* PickFFmpegLibs ()
! Helper function - creates FFmpegLibs object if it does not exists or just increments reference count if it does It is usually called by constructors or initializators
References FFmpegLibs::refcount.
Referenced by CheckFFmpegPresence(), ExportFFmpeg::ExportFFmpeg(), ExportFFmpegOptions::ExportFFmpegOptions(), FFmpegImportFileHandle::FFmpegImportFileHandle(), GetFFmpegVersion(), LoadFFmpeg(), and LibraryPrefs::OnFFmpegFindButton().
static int ufile_close (URLContext * h) [static]
int ufile_fopen (ByteIOContext ** s, const wxString & name, int flags)
References FFmpegLibs::url_close, FFmpegLibs::url_fdopen, and FFmpegLibs::url_open_protocol.
Referenced by ExportFFmpeg::Init(), and ufile_fopen_input().
int ufile_fopen_input (AVFormatContext ** ic_ptr, wxString & name)
References FFmpegLibs::av_freep, FFmpegLibs::av_iformat_next, FFmpegLibs::av_malloc, FFmpegLibs::av_open_input_stream, FFmpegLibs::get_buffer, FFmpegLibs::match_ext, PROBE_BUF_MAX, PROBE_BUF_MIN, ufile_fopen(), FFmpegLibs::url_fclose, and FFmpegLibs::url_fseek.
Referenced by FFmpegImportFileHandle::Init().
static int ufile_open (URLContext * h, const char * filename, int flags) [static]
static int ufile_read (URLContext * h, unsigned char * buf, int size) [static]
static offset_t ufile_seek (URLContext * h, offset_t pos, int whence) [static]
static int ufile_write (URLContext * h, unsigned char * buf, int size) [static]
Variable Documentation
FFmpegLibs* FFmpegLibsInst = NULL
This pointer to the shared object has global scope and is used to track the singleton object which wraps the FFmpeg codecs
Referenced by LibraryPrefs::OnFFmpegFindButton().
URLProtocol ufile_protocol
Initial value:
 {
    "ufile",
    ufile_open,
    ufile_read,
    ufile_write,
    ufile_seek,
    ufile_close,
}