Audacity: PitchName.cpp File Reference
PitchName.cpp File Reference
Utilities for converting from frequency to pitch and from pitch to absolute (e.g., C4 for middle C) or nominal (A through G#) pitch name.
#include <math.h>
#include <stdio.h>
#include "PitchName.h"
Functions
double FreqToMIDInoteNumber (double freq)
unsigned int PitchIndex (double pitchNum)
wxChar * PitchName (double pitchNum, bool bWantFlats)
wxChar * PitchName_Absolute (double pitchNum, bool bWantFlats)
Variables
wxChar gPitchName [10]
wxChar * pPitchName
Detailed Description
Utilities for converting from frequency to pitch and from pitch to absolute (e.g., C4 for middle C) or nominal (A through G#) pitch name.
Function Documentation
double FreqToMIDInoteNumber (double freq)
Referenced by EffectChangePitch::DeduceFrequencies(), ChangePitchDialog::OnText_FromFrequency(), and FreqWindow::PlotPaint().
unsigned int PitchIndex (double pitchNum)
Referenced by EffectChangePitch::DeduceFrequencies(), ChangePitchDialog::OnText_FromFrequency(), and PitchName().
wxChar* PitchName (double pitchNum, bool bWantFlats)
References gPitchName, PitchIndex(), and pPitchName.
Referenced by PitchName_Absolute().
wxChar* PitchName_Absolute (double pitchNum, bool bWantFlats)
References gPitchName, PitchName(), and pPitchName.
Referenced by FreqWindow::PlotPaint().
Variable Documentation
wxChar gPitchName[10]
Referenced by PitchName(), and PitchName_Absolute().
wxChar* pPitchName
Referenced by PitchName(), and PitchName_Absolute().