Audacity: Command Class Reference
Command Class Reference
Base class which encapsulates a process.
#include <Command.h>
Public Member Functions
virtual void Progress (double completed)=0
virtual void Status (wxString message)=0
virtual void Error (wxString message)=0
virtual ~Command ()
virtual wxString GetName ()=0
virtual CommandSignature & GetSignature ()=0
virtual bool SetParameter (const wxString &paramName, const wxVariant &paramValue)
virtual bool Apply (CommandExecutionContext context)=0
Detailed Description
Base class which encapsulates a process.
That process may depend on certain parameters (determined by the command's signature) and may produce output on various channels. Any process which is to be controlled by a script should be separated out into its own Command class. (And that class should be registered with the CommandDirectory).
Constructor & Destructor Documentation
virtual Command::~Command () [inline, virtual]
Member Function Documentation
virtual bool Command::Apply (CommandExecutionContext context) [pure virtual]
Implemented in BatchEvalCommand, DecoratedCommand, ApplyAndSendResponse, CommandImplementation, CompareAudioCommand, ExecMenuCommand, GetAllMenuCommands, GetProjectInfoCommand, GetTrackInfoCommand, HelpCommand, ImportCommand, ExportCommand, MessageCommand, GetPreferenceCommand, SetPreferenceCommand, ScreenshotCommand, SelectCommand, SetProjectInfoCommand, and SetTrackInfoCommand.
Referenced by ApplyAndSendResponse::Apply(), and CommandHandler::OnReceiveCommand().
virtual void Command::Error (wxString message) [pure virtual]
Implemented in DecoratedCommand, and CommandImplementation.
Referenced by DecoratedCommand::Error().
virtual wxString Command::GetName () [pure virtual]
Implemented in DecoratedCommand, and CommandImplementation.
Referenced by DecoratedCommand::GetName().
virtual CommandSignature& Command::GetSignature () [pure virtual]
Implemented in DecoratedCommand, and CommandImplementation.
Referenced by DecoratedCommand::GetSignature().
virtual void Command::Progress (double completed) [pure virtual]
Implemented in DecoratedCommand, and CommandImplementation.
Referenced by DecoratedCommand::Progress().
bool Command::SetParameter (const wxString & paramName, const wxVariant & paramValue) [virtual]
Reimplemented in DecoratedCommand, and CommandImplementation.
Referenced by CommandBuilder::BuildCommand(), AudacityProject::SafeDisplayStatusMessage(), and DecoratedCommand::SetParameter().
virtual void Command::Status (wxString message) [pure virtual]
Implemented in DecoratedCommand, and CommandImplementation.
Referenced by DecoratedCommand::Status().
The documentation for this class was generated from the following files:
Command.h
Command.cpp