Audacity: AudacityPrintout Class Reference
AudacityPrintout Class Reference
Derived from wxPrintout, this class helps with printing.
Public Member Functions
AudacityPrintout (wxString title, TrackList *tracks)
bool OnPrintPage (int page)
bool HasPage (int page)
bool OnBeginDocument (int startPage, int endPage)
void GetPageInfo (int *minPage, int *maxPage, int *selPageFrom, int *selPageTo)
Private Attributes
TrackList * mTracks
Detailed Description
Derived from wxPrintout, this class helps with printing.
Constructor & Destructor Documentation
AudacityPrintout::AudacityPrintout (wxString title, TrackList * tracks) [inline]
Member Function Documentation
void AudacityPrintout::GetPageInfo (int * minPage, int * maxPage, int * selPageFrom, int * selPageTo)
bool AudacityPrintout::HasPage (int page)
bool AudacityPrintout::OnBeginDocument (int startPage, int endPage)
bool AudacityPrintout::OnPrintPage (int page)
References Ruler::Draw(), TrackArtist::DrawTrack(), TrackListIterator::First(), TrackList::GetEndTime(), Track::GetHeight(), TrackList::GetHeight(), ViewInfo::h, ViewInfo::lastZoom, AColor::Line(), mTracks, TrackListIterator::Next(), scale(), ViewInfo::screen, ViewInfo::sel0, ViewInfo::sel1, TrackArtist::SetBackgroundBrushes(), Ruler::SetBounds(), Ruler::SetFormat(), Ruler::SetLabelEdges(), Ruler::SetOrientation(), Ruler::SetRange(), Ruler::TimeFormat, ViewInfo::total, ViewInfo::vpos, and ViewInfo::zoom.
Member Data Documentation
TrackList* AudacityPrintout::mTracks [private]
Referenced by OnPrintPage().
The documentation for this class was generated from the following file:
Printing.cpp