Audacity: EffectChangePitch Class Reference
EffectChangePitch Class Reference
#include <ChangePitch.h>
Public Member Functions
EffectChangePitch ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual wxString GetEffectDescription ()
virtual bool Init ()
virtual void DeduceFrequencies ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool CheckWhetherSkipEffect ()
virtual bool Process ()
Private Attributes
int m_FromPitchIndex
bool m_bWantPitchDown
int m_ToPitchIndex
double m_SemitonesChange
float m_FromFrequency
float m_ToFrequency
double m_PercentChange
Friends
class ChangePitchDialog
Constructor & Destructor Documentation
EffectChangePitch::EffectChangePitch ()
References m_bWantPitchDown, m_FromFrequency, m_FromPitchIndex, m_PercentChange, m_SemitonesChange, m_ToFrequency, and m_ToPitchIndex.
Member Function Documentation
virtual bool EffectChangePitch::CheckWhetherSkipEffect () [inline, virtual]
Reimplemented from Effect.
References m_PercentChange.
void EffectChangePitch::DeduceFrequencies () [virtual]
References ComputeSpectrum(), TrackListCondIterator::First(), floatSample, FreqToMIDInoteNumber(), WaveTrack::Get(), WaveTrack::GetRate(), WaveTrack::GetStartTime(), m_bWantPitchDown, m_FromFrequency, m_FromPitchIndex, m_PercentChange, m_ToFrequency, m_ToPitchIndex, Effect::mT0, Effect::mTracks, PitchIndex(), WaveTrack::TimeToLongSamples(), and Track::Wave.
Referenced by PromptUser().
virtual wxString EffectChangePitch::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectChangePitch::GetEffectCategories () [inline, virtual]
wxString EffectChangePitch::GetEffectDescription () [virtual]
Reimplemented from Effect.
References GetEffectName(), and m_SemitonesChange.
virtual wxString EffectChangePitch::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectChangePitch::GetEffectName () [inline, virtual]
Implements Effect.
Referenced by GetEffectDescription().
bool EffectChangePitch::Init () [virtual]
Reimplemented from Effect.
References EffectSoundTouch::mSoundTouch.
bool EffectChangePitch::Process () [virtual]
Reimplemented from EffectSoundTouch.
References m_SemitonesChange, EffectSoundTouch::mSoundTouch, and Effect::SetTimeWarper().
bool EffectChangePitch::PromptUser () [virtual]
Reimplemented from Effect.
References DeduceFrequencies(), m_bWantPitchDown, ChangePitchDialog::m_bWantPitchDown, m_FromFrequency, ChangePitchDialog::m_FromFrequency, m_FromPitchIndex, ChangePitchDialog::m_FromPitchIndex, m_PercentChange, ChangePitchDialog::m_PercentChange, m_SemitonesChange, ChangePitchDialog::m_SemitonesChange, m_ToFrequency, ChangePitchDialog::m_ToFrequency, m_ToPitchIndex, ChangePitchDialog::m_ToPitchIndex, and Effect::mParent.
bool EffectChangePitch::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References m_PercentChange, m_SemitonesChange, and Shuttle::TransferDouble().
Friends And Related Function Documentation
friend class ChangePitchDialog [friend]
Member Data Documentation
bool EffectChangePitch::m_bWantPitchDown [private]
Referenced by DeduceFrequencies(), EffectChangePitch(), and PromptUser().
float EffectChangePitch::m_FromFrequency [private]
Referenced by DeduceFrequencies(), EffectChangePitch(), and PromptUser().
int EffectChangePitch::m_FromPitchIndex [private]
Referenced by DeduceFrequencies(), EffectChangePitch(), and PromptUser().
double EffectChangePitch::m_PercentChange [private]
Referenced by CheckWhetherSkipEffect(), DeduceFrequencies(), EffectChangePitch(), PromptUser(), and TransferParameters().
double EffectChangePitch::m_SemitonesChange [private]
Referenced by EffectChangePitch(), GetEffectDescription(), ChangePitchDialog::OnPreview(), Process(), PromptUser(), and TransferParameters().
float EffectChangePitch::m_ToFrequency [private]
Referenced by DeduceFrequencies(), EffectChangePitch(), and PromptUser().
int EffectChangePitch::m_ToPitchIndex [private]
Referenced by DeduceFrequencies(), EffectChangePitch(), and PromptUser().
The documentation for this class was generated from the following files:
ChangePitch.h
ChangePitch.cpp