Audacity: ToolBarGrabber Class Reference
ToolBarGrabber Class Reference
Draws the grabber for an ExpandingToolBar.
#include <ExpandingToolBar.h>
Public Member Functions
DECLARE_DYNAMIC_CLASS (ToolBarGrabber)
ToolBarGrabber (wxWindow *parent, wxWindowID id, ExpandingToolBar *ownerToolbar, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
void OnPaint (wxPaintEvent &evt)
void OnSize (wxSizeEvent &evt)
void OnMouse (wxMouseEvent &evt)
Protected Member Functions
DECLARE_EVENT_TABLE ()
Protected Attributes
int mState
ImageRoll mImageRoll [2]
ExpandingToolBar * mOwnerToolBar
Detailed Description
Draws the grabber for an ExpandingToolBar.
Constructor & Destructor Documentation
ToolBarGrabber::ToolBarGrabber (wxWindow * parent, wxWindowID id, ExpandingToolBar * ownerToolbar, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
References ThemeBase::Image(), ImageRoll::SplitH(), theTheme, and ImageRoll::VerticalRoll.
Member Function Documentation
ToolBarGrabber::DECLARE_DYNAMIC_CLASS (ToolBarGrabber)
ToolBarGrabber::DECLARE_EVENT_TABLE () [protected]
void ToolBarGrabber::OnMouse (wxMouseEvent & evt)
References mOwnerToolBar, mState, and ExpandingToolBar::StartMoving().
void ToolBarGrabber::OnPaint (wxPaintEvent & evt)
References ImageRoll::Draw(), mImageRoll, and mState.
void ToolBarGrabber::OnSize (wxSizeEvent & evt)
Member Data Documentation
ImageRoll ToolBarGrabber::mImageRoll[2] [protected]
Referenced by OnPaint().
ExpandingToolBar* ToolBarGrabber::mOwnerToolBar [protected]
Referenced by OnMouse().
int ToolBarGrabber::mState [protected]
Referenced by OnMouse(), and OnPaint().
The documentation for this class was generated from the following files:
ExpandingToolBar.h
ExpandingToolBar.cpp