Audacity: LangChoiceDialog Class Reference
LangChoiceDialog Class Reference
A dialog used (at start up) to present the user with a choice of languages for Audacity.
Public Member Functions
LangChoiceDialog (wxWindow *parent, wxWindowID id, const wxString &title)
wxString GetLang ()
Private Member Functions
void OnOk (wxCommandEvent &event)
Private Attributes
wxChoice * mChoice
wxString mLang
int mNumLangs
wxArrayString mLangCodes
wxArrayString mLangNames
Detailed Description
A dialog used (at start up) to present the user with a choice of languages for Audacity.
Constructor & Destructor Documentation
LangChoiceDialog::LangChoiceDialog (wxWindow * parent, wxWindowID id, const wxString & title)
References ShuttleGuiBase::AddChoice(), ShuttleGui::AddStandardButtons(), eIsCreating, ShuttleGuiBase::EndVerticalLay(), eOkButton, GetLanguages(), GetSystemLanguageCode(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartVerticalLay().
Member Function Documentation
wxString LangChoiceDialog::GetLang () [inline]
References mLang.
Referenced by ChooseLanguage().
void LangChoiceDialog::OnOk (wxCommandEvent & event) [private]
References GetSystemLanguageCode(), mChoice, mLang, mLangCodes, and mLangNames.
Member Data Documentation
wxChoice* LangChoiceDialog::mChoice [private]
Referenced by OnOk().
wxString LangChoiceDialog::mLang [private]
Referenced by GetLang(), and OnOk().
wxArrayString LangChoiceDialog::mLangCodes [private]
Referenced by OnOk().
wxArrayString LangChoiceDialog::mLangNames [private]
Referenced by OnOk().
int LangChoiceDialog::mNumLangs [private]
The documentation for this class was generated from the following file:
LangChoice.cpp