Audacity: ApplyAndSendResponse Class Reference
ApplyAndSendResponse Class Reference
#include <Command.h>
Public Member Functions
ApplyAndSendResponse (Command *cmd)
virtual bool Apply (CommandExecutionContext context)
Constructor & Destructor Documentation
ApplyAndSendResponse::ApplyAndSendResponse (Command * cmd) [inline]
Member Function Documentation
bool ApplyAndSendResponse::Apply (CommandExecutionContext context) [virtual]
Implements DecoratedCommand.
References Command::Apply(), DecoratedCommand::GetName(), DecoratedCommand::mCommand, and DecoratedCommand::Status().
The documentation for this class was generated from the following files:
Command.h
Command.cpp