Audacity: EffectAutoDuckPanel Class Reference
EffectAutoDuckPanel Class Reference
#include <AutoDuck.h>
Public Member Functions
EffectAutoDuckPanel (EffectAutoDuckDialog *parent, wxWindowID id)
virtual ~EffectAutoDuckPanel ()
Private Types
enum EControlPoint {
innerFadeDown = 0, outerFadeDown, innerFadeUp, outerFadeUp,
duckAmount, none = 99
}
Private Member Functions
void OnPaint (wxPaintEvent &evt)
void OnMouseCaptureChanged (wxMouseCaptureChangedEvent &evt)
void OnMouseCaptureLost (wxMouseCaptureLostEvent &evt)
void OnLeftDown (wxMouseEvent &evt)
void OnLeftUp (wxMouseEvent &evt)
void OnMotion (wxMouseEvent &evt)
void ResetControlPoints ()
EControlPoint GetNearestControlPoint (const wxPoint &pt)
Private Attributes
EffectAutoDuckDialog * mParent
wxBitmap * mBackgroundBitmap
EControlPoint mCurrentControlPoint
wxPoint mControlPoints [AUTO_DUCK_PANEL_NUM_CONTROL_POINTS]
wxPoint mMoveStartControlPoints [AUTO_DUCK_PANEL_NUM_CONTROL_POINTS]
wxPoint mMouseDownPoint
bool mControlPointMoveActivated
Member Enumeration Documentation
enum EffectAutoDuckPanel::EControlPoint [private]
Enumerator:
innerFadeDown
outerFadeDown
innerFadeUp
outerFadeUp
duckAmount
none
Constructor & Destructor Documentation
EffectAutoDuckPanel::EffectAutoDuckPanel (EffectAutoDuckDialog * parent, wxWindowID id)
EffectAutoDuckPanel::~EffectAutoDuckPanel () [virtual]
References mBackgroundBitmap.
Member Function Documentation
EffectAutoDuckPanel::EControlPoint EffectAutoDuckPanel::GetNearestControlPoint (const wxPoint & pt) [private]
References AUTO_DUCK_PANEL_NUM_CONTROL_POINTS, CONTROL_POINT_REGION, GetDistance(), mControlPoints, and none.
Referenced by OnLeftDown(), and OnMotion().
void EffectAutoDuckPanel::OnLeftDown (wxMouseEvent & evt) [private]
References AUTO_DUCK_PANEL_NUM_CONTROL_POINTS, GetNearestControlPoint(), mControlPointMoveActivated, mControlPoints, mCurrentControlPoint, mMouseDownPoint, mMoveStartControlPoints, and none.
void EffectAutoDuckPanel::OnLeftUp (wxMouseEvent & evt) [private]
References mCurrentControlPoint, and none.
void EffectAutoDuckPanel::OnMotion (wxMouseEvent & evt) [private]
References CONTROL_POINT_MIN_MOVE, DUCK_AMOUNT_SCALE, DUCK_AMOUNT_START, duckAmount, FADE_DOWN_START, FADE_SCALE, FADE_UP_START, GetNearestControlPoint(), innerFadeDown, innerFadeUp, MAX_DUCK_AMOUNT, MAX_FADE, mControlPointMoveActivated, mCurrentControlPoint, EffectAutoDuckDialog::mDuckAmountDbBox, MIN_DUCK_AMOUNT, MIN_FADE, EffectAutoDuckDialog::mInnerFadeDownLenBox, EffectAutoDuckDialog::mInnerFadeUpLenBox, mMouseDownPoint, mMoveStartControlPoints, EffectAutoDuckDialog::mOuterFadeDownLenBox, EffectAutoDuckDialog::mOuterFadeUpLenBox, mParent, none, outerFadeDown, outerFadeUp, and Internat::ToDisplayString().
void EffectAutoDuckPanel::OnMouseCaptureChanged (wxMouseCaptureChangedEvent & evt) [private]
References mCurrentControlPoint, and none.
void EffectAutoDuckPanel::OnMouseCaptureLost (wxMouseCaptureLostEvent & evt) [private]
References mCurrentControlPoint, and none.
void EffectAutoDuckPanel::OnPaint (wxPaintEvent & evt) [private]
References AUTO_DUCK_PANEL_NUM_CONTROL_POINTS, ThemeBase::Colour(), DUCK_AMOUNT_SCALE, DUCK_AMOUNT_START, duckAmount, AColor::envelopePen, FADE_DOWN_START, FADE_SCALE, FADE_UP_START, innerFadeDown, innerFadeUp, AColor::Line(), MAX_DUCK_AMOUNT, MAX_FADE, mBackgroundBitmap, mControlPoints, EffectAutoDuckDialog::mDuckAmountDbBox, EffectAutoDuckDialog::mInnerFadeDownLenBox, EffectAutoDuckDialog::mInnerFadeUpLenBox, EffectAutoDuckDialog::mOuterFadeDownLenBox, EffectAutoDuckDialog::mOuterFadeUpLenBox, mParent, outerFadeDown, outerFadeUp, ResetControlPoints(), TEXT_DISTANCE, theTheme, and Internat::ToDisplayString().
void EffectAutoDuckPanel::ResetControlPoints () [private]
References duckAmount, innerFadeDown, innerFadeUp, mControlPoints, outerFadeDown, and outerFadeUp.
Referenced by OnPaint().
Member Data Documentation
wxBitmap* EffectAutoDuckPanel::mBackgroundBitmap [private]
Referenced by OnPaint(), and ~EffectAutoDuckPanel().
bool EffectAutoDuckPanel::mControlPointMoveActivated [private]
Referenced by OnLeftDown(), and OnMotion().
wxPoint EffectAutoDuckPanel::mControlPoints[AUTO_DUCK_PANEL_NUM_CONTROL_POINTS] [private]
Referenced by GetNearestControlPoint(), OnLeftDown(), OnPaint(), and ResetControlPoints().
EControlPoint EffectAutoDuckPanel::mCurrentControlPoint [private]
Referenced by OnLeftDown(), OnLeftUp(), OnMotion(), OnMouseCaptureChanged(), and OnMouseCaptureLost().
wxPoint EffectAutoDuckPanel::mMouseDownPoint [private]
Referenced by OnLeftDown(), and OnMotion().
wxPoint EffectAutoDuckPanel::mMoveStartControlPoints[AUTO_DUCK_PANEL_NUM_CONTROL_POINTS] [private]
Referenced by OnLeftDown(), and OnMotion().
EffectAutoDuckDialog* EffectAutoDuckPanel::mParent [private]
Referenced by OnMotion(), and OnPaint().
The documentation for this class was generated from the following files:
AutoDuck.h
AutoDuck.cpp