Audacity: FindFFmpegDialog Class Reference
FindFFmpegDialog Class Reference
Allows user to locate libav* libraries.
Public Member Functions
FindFFmpegDialog (wxWindow *parent, wxString path, wxString name, wxString type)
void PopulateOrExchange (ShuttleGui &S)
void OnBrowse (wxCommandEvent &event)
void OnDownload (wxCommandEvent &event)
wxString GetLibPath ()
Private Attributes
wxFileName mLibPath
wxString mPath
wxString mName
wxString mType
wxTextCtrl * mPathText
Detailed Description
Allows user to locate libav* libraries.
Constructor & Destructor Documentation
FindFFmpegDialog::FindFFmpegDialog (wxWindow * parent, wxString path, wxString name, wxString type) [inline]
References eIsCreating, mLibPath, mName, mPath, mType, and PopulateOrExchange().
Member Function Documentation
wxString FindFFmpegDialog::GetLibPath () [inline]
References mLibPath.
Referenced by FFmpegLibs::FindLibs().
void FindFFmpegDialog::OnBrowse (wxCommandEvent & event) [inline]
References mLibPath, mName, mPathText, and mType.
void FindFFmpegDialog::OnDownload (wxCommandEvent & event) [inline]
References OpenInDefaultBrowser().
void FindFFmpegDialog::PopulateOrExchange (ShuttleGui & S) [inline]
References ShuttleGuiBase::AddButton(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddVariableText(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndVerticalLay(), ShuttleGui::Id(), ID_FFMPEG_BROWSE, ID_FFMPEG_DLOAD, mLibPath, mName, mPathText, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), and ShuttleGuiBase::StartVerticalLay().
Referenced by FindFFmpegDialog().
Member Data Documentation
wxFileName FindFFmpegDialog::mLibPath [private]
Referenced by FindFFmpegDialog(), GetLibPath(), OnBrowse(), and PopulateOrExchange().
wxString FindFFmpegDialog::mName [private]
Referenced by FindFFmpegDialog(), OnBrowse(), and PopulateOrExchange().
wxString FindFFmpegDialog::mPath [private]
Referenced by FindFFmpegDialog().
wxTextCtrl* FindFFmpegDialog::mPathText [private]
Referenced by OnBrowse(), and PopulateOrExchange().
wxString FindFFmpegDialog::mType [private]
Referenced by FindFFmpegDialog(), and OnBrowse().
The documentation for this class was generated from the following file:
FFmpeg.cpp