Audacity: TrackPanelListener Class Reference
TrackPanelListener Class Reference
A now badly named class which is used to give access to a subset of the TrackPanel functions from all over the place.
#include <TrackPanel.h>
Public Member Functions
TrackPanelListener ()
virtual ~TrackPanelListener ()
virtual void TP_DisplaySelection ()=0
virtual void TP_DisplayStatusMessage (wxString msg)=0
virtual int TP_GetCurrentTool ()=0
virtual ToolsToolBar * TP_GetToolsToolBar ()=0
virtual ControlToolBar * TP_GetControlToolBar ()=0
virtual void TP_OnPlayKey ()=0
virtual void TP_PushState (wxString shortDesc, wxString longDesc, bool consolidate=false)=0
virtual void TP_ModifyState ()=0
virtual void TP_RedrawScrollbars ()=0
virtual void TP_ScrollLeft ()=0
virtual void TP_ScrollRight ()=0
virtual void TP_ScrollWindow (double scrollto)=0
virtual void TP_ScrollUpDown (int delta)=0
virtual void TP_HandleResize ()=0
Detailed Description
A now badly named class which is used to give access to a subset of the TrackPanel functions from all over the place.
Constructor & Destructor Documentation
TrackPanelListener::TrackPanelListener () [inline]
virtual TrackPanelListener::~TrackPanelListener () [inline, virtual]
Member Function Documentation
virtual void TrackPanelListener::TP_DisplaySelection () [pure virtual]
Implemented in AudacityProject.
Referenced by TrackPanel::DisplaySelection().
virtual void TrackPanelListener::TP_DisplayStatusMessage (wxString msg) [pure virtual]
Implemented in AudacityProject.
Referenced by TrackPanel::HandleClosing(), TrackPanel::HandleCursor(), and TrackPanel::OnTrackClose().
virtual ControlToolBar* TrackPanelListener::TP_GetControlToolBar () [pure virtual]
Implemented in AudacityProject.
virtual int TrackPanelListener::TP_GetCurrentTool () [pure virtual]
Implemented in AudacityProject.
virtual ToolsToolBar* TrackPanelListener::TP_GetToolsToolBar () [pure virtual]
Implemented in AudacityProject.
Referenced by TrackPanel::DrawTracks(), TrackPanel::HandleCursor(), TrackPanel::HandleTrackSpecificMouseEvent(), and TrackPanel::StartSlide().
virtual void TrackPanelListener::TP_HandleResize () [pure virtual]
Implemented in AudacityProject.
Referenced by TrackPanel::MakeParentResize().
virtual void TrackPanelListener::TP_ModifyState () [pure virtual]
Implemented in AudacityProject.
Referenced by TrackPanel::MakeParentModifyState().
virtual void TrackPanelListener::TP_OnPlayKey () [pure virtual]
Implemented in AudacityProject.
virtual void TrackPanelListener::TP_PushState (wxString shortDesc, wxString longDesc, bool consolidate = false) [pure virtual]
Implemented in AudacityProject.
Referenced by TrackPanel::MakeParentPushState().
virtual void TrackPanelListener::TP_RedrawScrollbars () [pure virtual]
Implemented in AudacityProject.
Referenced by TrackPanel::HandleClosing(), TrackPanel::MakeParentRedrawScrollbars(), and TrackPanel::OnTrackClose().
virtual void TrackPanelListener::TP_ScrollLeft () [pure virtual]
Implemented in AudacityProject.
Referenced by TrackPanel::ScrollDuringDrag().
virtual void TrackPanelListener::TP_ScrollRight () [pure virtual]
Implemented in AudacityProject.
Referenced by TrackPanel::ScrollDuringDrag().
virtual void TrackPanelListener::TP_ScrollUpDown (int delta) [pure virtual]
Implemented in AudacityProject.
Referenced by TrackPanel::EnsureVisible(), TrackPanel::HandleWheelRotation(), and TrackPanel::OnTimer().
virtual void TrackPanelListener::TP_ScrollWindow (double scrollto) [pure virtual]
Implemented in AudacityProject.
Referenced by TrackPanel::DoDrawIndicator(), TrackPanel::HandleWheelRotation(), and TrackPanel::ScrollIntoView().
The documentation for this class was generated from the following file:
TrackPanel.h