Audacity: DecoratedCommand Class Reference
DecoratedCommand Class Reference
#include <Command.h>
Public Member Functions
virtual void Progress (double completed)
virtual void Status (wxString message)
virtual void Error (wxString message)
DecoratedCommand (Command *cmd)
virtual ~DecoratedCommand ()
virtual wxString GetName ()
virtual CommandSignature & GetSignature ()
virtual bool SetParameter (const wxString &paramName, const wxVariant &paramValue)
virtual bool Apply (CommandExecutionContext context)=0
Protected Attributes
Command * mCommand
Constructor & Destructor Documentation
DecoratedCommand::DecoratedCommand (Command * cmd) [inline]
DecoratedCommand::~DecoratedCommand () [virtual]
References mCommand.
Member Function Documentation
virtual bool DecoratedCommand::Apply (CommandExecutionContext context) [pure virtual]
Implements Command.
Implemented in ApplyAndSendResponse.
void DecoratedCommand::Error (wxString message) [virtual]
Implements Command.
References Command::Error(), and mCommand.
wxString DecoratedCommand::GetName () [virtual]
Implements Command.
References Command::GetName(), and mCommand.
Referenced by ApplyAndSendResponse::Apply().
CommandSignature & DecoratedCommand::GetSignature () [virtual]
Implements Command.
References Command::GetSignature(), and mCommand.
void DecoratedCommand::Progress (double completed) [virtual]
Implements Command.
References mCommand, and Command::Progress().
bool DecoratedCommand::SetParameter (const wxString & paramName, const wxVariant & paramValue) [virtual]
Reimplemented from Command.
References mCommand, and Command::SetParameter().
void DecoratedCommand::Status (wxString message) [virtual]
Implements Command.
References mCommand, and Command::Status().
Referenced by ApplyAndSendResponse::Apply().
Member Data Documentation
Command* DecoratedCommand::mCommand [protected]
Referenced by ApplyAndSendResponse::Apply(), Error(), GetName(), GetSignature(), Progress(), SetParameter(), Status(), and ~DecoratedCommand().
The documentation for this class was generated from the following files:
Command.h
Command.cpp