Audacity: NormalizeDialog Class Reference
NormalizeDialog Class Reference
Dialog used with EffectNormalize.
#include <Normalize.h>
Public Member Functions
NormalizeDialog (EffectNormalize *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
bool mGain
bool mDC
double mLevel
Private Member Functions
void OnUpdateUI (wxCommandEvent &evt)
void OnPreview (wxCommandEvent &event)
void UpdateUI ()
Private Attributes
EffectNormalize * mEffect
wxCheckBox * mGainCheckBox
wxCheckBox * mDCCheckBox
wxStaticText * mLevelMinux
wxTextCtrl * mLevelTextCtrl
wxStaticText * mLeveldB
Detailed Description
Dialog used with EffectNormalize.
Constructor & Destructor Documentation
NormalizeDialog::NormalizeDialog (EffectNormalize * effect, wxWindow * parent)
Member Function Documentation
void NormalizeDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References mDC, EffectNormalize::mDC, mEffect, mGain, EffectNormalize::mGain, mLevel, EffectNormalize::mLevel, Effect::Preview(), and TransferDataFromWindow().
void NormalizeDialog::OnUpdateUI (wxCommandEvent & evt) [private]
References UpdateUI().
void NormalizeDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddCheckBox(), ShuttleGui::AddSpace(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddVariableText(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndTwoColumn(), ShuttleGuiBase::EndVerticalLay(), ShuttleGui::GetBorder(), ShuttleGui::Id(), ID_NORMALIZE_AMPLITUDE, mDC, mDCCheckBox, mGain, mGainCheckBox, mLevel, mLeveldB, mLevelMinux, mLevelTextCtrl, ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartTwoColumn(), ShuttleGuiBase::StartVerticalLay(), and Internat::ToString().
bool NormalizeDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References Internat::CompatibleToDouble(), mDC, mDCCheckBox, mGain, mGainCheckBox, mLevel, and mLevelTextCtrl.
Referenced by OnPreview(), and TransferDataToWindow().
bool NormalizeDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References mDC, mDCCheckBox, mGain, mGainCheckBox, mLevel, mLevelTextCtrl, Internat::ToString(), TransferDataFromWindow(), and UpdateUI().
Referenced by EffectNormalize::PromptUser().
void NormalizeDialog::UpdateUI () [private]
References mGainCheckBox, mLeveldB, mLevelMinux, and mLevelTextCtrl.
Referenced by OnUpdateUI(), and TransferDataToWindow().
Member Data Documentation
bool NormalizeDialog::mDC
Referenced by OnPreview(), PopulateOrExchange(), EffectNormalize::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
wxCheckBox* NormalizeDialog::mDCCheckBox [private]
Referenced by PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
EffectNormalize* NormalizeDialog::mEffect [private]
Referenced by OnPreview().
bool NormalizeDialog::mGain
Referenced by OnPreview(), PopulateOrExchange(), EffectNormalize::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
wxCheckBox* NormalizeDialog::mGainCheckBox [private]
Referenced by PopulateOrExchange(), TransferDataFromWindow(), TransferDataToWindow(), and UpdateUI().
double NormalizeDialog::mLevel
Referenced by OnPreview(), PopulateOrExchange(), EffectNormalize::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
wxStaticText* NormalizeDialog::mLeveldB [private]
Referenced by PopulateOrExchange(), and UpdateUI().
wxStaticText* NormalizeDialog::mLevelMinux [private]
Referenced by PopulateOrExchange(), and UpdateUI().
wxTextCtrl* NormalizeDialog::mLevelTextCtrl [private]
Referenced by PopulateOrExchange(), TransferDataFromWindow(), TransferDataToWindow(), and UpdateUI().
The documentation for this class was generated from the following files:
Normalize.h
Normalize.cpp