Audacity: ToolBar Class Reference
ToolBar Class Reference
Works with ToolManager and ToolDock to provide a dockable window in which buttons can be placed.
#include <ToolBar.h>
Public Member Functions
ToolBar (int type, const wxString &label, const wxString &section, bool resizable=false)
virtual ~ToolBar ()
virtual void Create (wxWindow *parent)
virtual void EnableDisableButtons ()=0
virtual void ReCreateButtons ()
virtual void UpdatePrefs ()
int GetType ()
wxString GetTitle ()
wxString GetLabel ()
wxString GetSection ()
ToolDock * GetDock ()
void SetLabel (const wxString &label)
void SetDock (ToolDock *dock)
void SetDocked (ToolDock *dock, bool pushed)
bool Expose (bool show=true)
bool IsResizable ()
bool IsVisible ()
bool IsDocked ()
DECLARE_CLASS (ToolBar)
DECLARE_EVENT_TABLE ()
Protected Member Functions
AButton * MakeButton (teBmps eUp, teBmps eDown, teBmps eHilite, teBmps eStandard, teBmps eDisabled, wxWindowID id, wxPoint placement, bool processdownevents, wxSize size)
void SetButton (bool down, AButton *button)
void MakeMacRecoloredImage (teBmps eBmpOut, teBmps eBmpIn)
void MakeRecoloredImage (teBmps eBmpOut, teBmps eBmpIn)
void MakeButtonBackgroundsLarge ()
void MakeButtonBackgroundsSmall ()
wxBoxSizer * GetSizer ()
void Add (wxWindow *window, int proportion=0, int flag=wxALIGN_TOP, int border=0, wxObject *userData=NULL)
void Add (wxSizer *sizer, int proportion=0, int flag=0, int border=0, wxObject *userData=NULL)
void Add (int width, int height, int proportion=0, int flag=0, int border=0, wxObject *userData=NULL)
void AddSpacer (int size=14)
void AddStretchSpacer (int prop=1)
void Detach (wxWindow *window)
void Detach (wxSizer *sizer)
void Updated ()
virtual void Populate ()=0
virtual void Repaint (wxDC *dc)=0
void OnErase (wxEraseEvent &event)
void OnPaint (wxPaintEvent &event)
void OnLeftDown (wxMouseEvent &event)
void OnLeftUp (wxMouseEvent &event)
void OnMotion (wxMouseEvent &event)
void OnCaptureLost (wxMouseCaptureLostEvent &event)
Private Member Functions
bool IsResizeGrabberHit (wxPoint &pos)
void Init (wxWindow *parent, int type, const wxString &title, const wxString &label)
Private Attributes
wxWindow * mParent
Grabber * mGrabber
wxBoxSizer * mHSizer
wxSizerItem * mSpacer
wxPoint mResizeStart
wxString mLabel
wxString mSection
int mType
ToolDock * mDock
bool mVisible
bool mResizable
Detailed Description
Works with ToolManager and ToolDock to provide a dockable window in which buttons can be placed.
Constructor & Destructor Documentation
ToolBar::ToolBar (int type, const wxString & label, const wxString & section, bool resizable = false)
ToolBar::~ToolBar () [virtual]
Member Function Documentation
void ToolBar::Add (int width, int height, int proportion = 0, int flag = 0, int border = 0, wxObject * userData = NULL) [protected]
References mHSizer.
void ToolBar::Add (wxSizer * sizer, int proportion = 0, int flag = 0, int border = 0, wxObject * userData = NULL) [protected]
References mHSizer.
void ToolBar::Add (wxWindow * window, int proportion = 0, int flag = wxALIGN_TOP, int border = 0, wxObject * userData = NULL) [protected]
References mHSizer.
Referenced by TranscriptionToolBar::AddButton(), EditToolBar::AddButton(), ControlToolBar::ArrangeButtons(), TranscriptionToolBar::Populate(), ToolsToolBar::Populate(), SelectionBar::Populate(), MixerToolBar::Populate(), MeterToolBar::Populate(), DeviceToolBar::Populate(), and ToolManager::ReadConfig().
void ToolBar::AddSpacer (int size = 14) [protected]
References mHSizer.
Referenced by EditToolBar::AddSeparator().
void ToolBar::AddStretchSpacer (int prop = 1) [protected]
References mHSizer.
void ToolBar::Create (wxWindow * parent) [virtual]
Reimplemented in ControlToolBar, DeviceToolBar, EditToolBar, MeterToolBar, MixerToolBar, SelectionBar, ToolsToolBar, and TranscriptionToolBar.
References GetLabel(), GetTitle(), mParent, mType, mVisible, ReCreateButtons(), and SetLabel().
Referenced by ToolManager::ReadConfig().
ToolBar::DECLARE_CLASS (ToolBar)
Reimplemented in ControlToolBar, DeviceToolBar, EditToolBar, MeterToolBar, MixerToolBar, SelectionBar, ToolsToolBar, and TranscriptionToolBar.
ToolBar::DECLARE_EVENT_TABLE ()
Reimplemented in ControlToolBar, DeviceToolBar, EditToolBar, MeterToolBar, MixerToolBar, SelectionBar, ToolsToolBar, and TranscriptionToolBar.
void ToolBar::Detach (wxSizer * sizer) [protected]
References mHSizer.
void ToolBar::Detach (wxWindow * window) [protected]
References mHSizer.
Referenced by ControlToolBar::ArrangeButtons(), and ControlToolBar::ReCreateButtons().
virtual void ToolBar::EnableDisableButtons () [pure virtual]
Implemented in ControlToolBar, DeviceToolBar, EditToolBar, MeterToolBar, MixerToolBar, SelectionBar, ToolsToolBar, and TranscriptionToolBar.
Referenced by AudacityProject::ModifyToolbarMenus(), and ToolManager::Reset().
bool ToolBar::Expose (bool show = true)
References IsDocked(), and mVisible.
Referenced by ToolManager::Expose(), ToolDock::Expose(), ToolManager::ReadConfig(), ToolManager::ShowHide(), and ToolDock::ShowHide().
ToolDock * ToolBar::GetDock ()
References mDock.
Referenced by ToolManager::Expose(), ReCreateButtons(), ToolManager::Reset(), and ToolManager::ShowHide().
wxString ToolBar::GetLabel ()
References mLabel.
Referenced by Create(), and GetTitle().
wxString ToolBar::GetSection ()
References mSection.
Referenced by ToolManager::ReadConfig(), and ToolManager::WriteConfig().
wxBoxSizer * ToolBar::GetSizer () [protected]
References mHSizer.
Referenced by ControlToolBar::ArrangeButtons(), MeterToolBar::OnSize(), and SelectionBar::Populate().
wxString ToolBar::GetTitle ()
References GetLabel().
Referenced by Create(), SetDocked(), and UpdatePrefs().
int ToolBar::GetType ()
References mType.
void ToolBar::Init (wxWindow * parent, int type, const wxString & title, const wxString & label) [private]
bool ToolBar::IsDocked ()
References mDock.
Referenced by ToolManager::Expose(), Expose(), ToolManager::IsDocked(), ToolManager::IsVisible(), ToolManager::OnGrabber(), OnLeftDown(), ToolFrame::OnMotion(), OnMotion(), OnPaint(), ToolManager::Reset(), ToolManager::ShowHide(), and ToolManager::WriteConfig().
bool ToolBar::IsResizable ()
References mResizable.
Referenced by OnLeftDown(), ToolFrame::OnMotion(), OnMotion(), ToolFrame::OnPaint(), OnPaint(), ToolDock::PositionBar(), ReCreateButtons(), ToolManager::Reset(), and ToolFrame::ToolFrame().
bool ToolBar::IsResizeGrabberHit (wxPoint & pos) [private]
Returns:
true iff pos is in resize grabber.
References RWIDTH.
Referenced by OnLeftDown(), and OnMotion().
bool ToolBar::IsVisible ()
References mVisible.
Referenced by ToolManager::IsVisible(), ToolManager::ShowHide(), and ToolDock::ShowHide().
AButton * ToolBar::MakeButton (teBmps eUp, teBmps eDown, teBmps eHilite, teBmps eStandard, teBmps eDisabled, wxWindowID id, wxPoint placement, bool processdownevents, wxSize size) [protected]
Makes a button and its four different state bitmaps
Parameters:
eUp Background for when button is Up.
eDown Background for when button is Down.
eHilite Background for when button is Hilit.
eStandard Foreground when enabled.
eDisabled Foreground when disabled.
id Windows Id.
placement Placement position
processdownevents true iff button handles down events.
size Size of the background.
References ThemeBase::Image(), OverlayImage(), and theTheme.
Referenced by TranscriptionToolBar::AddButton(), EditToolBar::AddButton(), and ToolsToolBar::MakeTool().
void ToolBar::MakeButtonBackgroundsLarge () [protected]
References MakeMacRecoloredImage(), and MakeRecoloredImage().
Referenced by ControlToolBar::Populate().
void ToolBar::MakeButtonBackgroundsSmall () [protected]
References MakeMacRecoloredImage(), and MakeRecoloredImage().
Referenced by TranscriptionToolBar::Populate(), ToolsToolBar::Populate(), and EditToolBar::Populate().
void ToolBar::MakeMacRecoloredImage (teBmps eBmpOut, teBmps eBmpIn) [protected]
References ThemeBase::Image(), ThemeBase::ReplaceImage(), and theTheme.
Referenced by MakeButtonBackgroundsLarge(), and MakeButtonBackgroundsSmall().
void ToolBar::MakeRecoloredImage (teBmps eBmpOut, teBmps eBmpIn) [protected]
References ChangeImageColour(), ThemeBase::Image(), ThemeBase::ReplaceImage(), and theTheme.
Referenced by MakeButtonBackgroundsLarge(), and MakeButtonBackgroundsSmall().
void ToolBar::OnCaptureLost (wxMouseCaptureLostEvent & event) [protected]
void ToolBar::OnErase (wxEraseEvent & event) [protected]
void ToolBar::OnLeftDown (wxMouseEvent & event) [protected]
References IsDocked(), IsResizable(), IsResizeGrabberHit(), and mResizeStart.
void ToolBar::OnLeftUp (wxMouseEvent & event) [protected]
void ToolBar::OnMotion (wxMouseEvent & event) [protected]
References IsDocked(), IsResizable(), IsResizeGrabberHit(), mResizeStart, and Updated().
void ToolBar::OnPaint (wxPaintEvent & event) [protected]
References AColor::Dark(), ThemeBase::Image(), IsDocked(), IsResizable(), AColor::Line(), Repaint(), and theTheme.
virtual void ToolBar::Populate () [protected, pure virtual]
Implemented in ControlToolBar, DeviceToolBar, EditToolBar, MeterToolBar, MixerToolBar, SelectionBar, ToolsToolBar, and TranscriptionToolBar.
Referenced by ReCreateButtons().
void ToolBar::ReCreateButtons () [virtual]
Reimplemented in ControlToolBar.
References GetDock(), IsResizable(), mGrabber, mHSizer, mSpacer, mType, Populate(), RWIDTH, SetDocked(), toolbarGap, and toolbarSingle.
Referenced by Create(), SelectionBar::OnUpdate(), and ToolManager::Reset().
virtual void ToolBar::Repaint (wxDC * dc) [protected, pure virtual]
Implemented in ControlToolBar, DeviceToolBar, EditToolBar, MeterToolBar, MixerToolBar, SelectionBar, ToolsToolBar, and TranscriptionToolBar.
Referenced by OnPaint().
void ToolBar::SetButton (bool down, AButton * button) [protected]
Reimplemented in TranscriptionToolBar.
References AButton::PopUp(), and AButton::PushDown().
Referenced by EditToolBar::OnButton().
void ToolBar::SetDock (ToolDock * dock)
void ToolBar::SetDocked (ToolDock * dock, bool pushed)
References GetTitle(), mDock, mGrabber, and Grabber::PushButton().
Referenced by ToolDock::Dock(), ToolManager::OnGrabber(), ToolManager::OnMouse(), ToolManager::ReadConfig(), ReCreateButtons(), and ToolFrame::ToolFrame().
void ToolBar::SetLabel (const wxString & label)
References mLabel.
Referenced by Create(), TranscriptionToolBar::UpdatePrefs(), SelectionBar::UpdatePrefs(), MixerToolBar::UpdatePrefs(), MeterToolBar::UpdatePrefs(), EditToolBar::UpdatePrefs(), DeviceToolBar::UpdatePrefs(), and ControlToolBar::UpdatePrefs().
void ToolBar::Updated () [protected]
Referenced by OnMotion(), SelectionBar::OnUpdate(), MixerToolBar::UpdatePrefs(), and ControlToolBar::UpdatePrefs().
void ToolBar::UpdatePrefs () [virtual]
Reimplemented in ControlToolBar, DeviceToolBar, EditToolBar, MeterToolBar, MixerToolBar, SelectionBar, ToolsToolBar, and TranscriptionToolBar.
References GetTitle(), and mGrabber.
Referenced by ToolManager::UpdatePrefs().
Member Data Documentation
ToolDock* ToolBar::mDock [private]
Referenced by GetDock(), IsDocked(), and SetDocked().
Grabber* ToolBar::mGrabber [private]
Referenced by ReCreateButtons(), SetDocked(), and UpdatePrefs().
wxBoxSizer* ToolBar::mHSizer [private]
Referenced by Add(), AddSpacer(), AddStretchSpacer(), Detach(), GetSizer(), and ReCreateButtons().
wxString ToolBar::mLabel [private]
Referenced by GetLabel(), and SetLabel().
wxWindow* ToolBar::mParent [private]
Referenced by Create().
bool ToolBar::mResizable [private]
Referenced by IsResizable().
wxPoint ToolBar::mResizeStart [private]
Referenced by OnLeftDown(), and OnMotion().
wxString ToolBar::mSection [private]
Referenced by GetSection().
wxSizerItem* ToolBar::mSpacer [private]
Referenced by ReCreateButtons().
int ToolBar::mType [private]
Referenced by Create(), GetType(), and ReCreateButtons().
bool ToolBar::mVisible [private]
Referenced by Create(), Expose(), and IsVisible().
The documentation for this class was generated from the following files:
ToolBar.h
ToolBar.cpp