Audacity: EffectSpikeCleaner Class Reference
EffectSpikeCleaner Class Reference
An EffectSimpleMono for removing spikes.
#include <SpikeCleaner.h>
Public Member Functions
EffectSpikeCleaner ()
virtual wxString GetEffectName ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool Init ()
virtual bool CheckWhetherSkipEffect ()
virtual void End ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
Protected Member Functions
virtual bool ProcessSimpleMono (float *buffer, sampleCount len)
Private Attributes
int mSpikeMaxDurationMs
int mSpikeDbChoiceIndex
Friends
class SpikeCleanerDialog
Detailed Description
An EffectSimpleMono for removing spikes.
This is a simple version, Audacity could do with a more sophisticated approach to this.
Constructor & Destructor Documentation
EffectSpikeCleaner::EffectSpikeCleaner ()
References Init().
Member Function Documentation
bool EffectSpikeCleaner::CheckWhetherSkipEffect () [virtual]
Reimplemented from Effect.
References mSpikeDbChoiceIndex, mSpikeMaxDurationMs, Enums::NumDbChoices, and SKIP_EFFECT_MILLISECOND.
void EffectSpikeCleaner::End () [virtual]
Reimplemented from Effect.
References gPrefs, and gValidateSpikeFramesRemoved.
virtual wxString EffectSpikeCleaner::GetEffectAction () [inline, virtual]
Implements Effect.
virtual wxString EffectSpikeCleaner::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectSpikeCleaner::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectSpikeCleaner::Init () [virtual]
Reimplemented from Effect.
References gPrefs, gValidateSpikeFramesRemoved, mSpikeDbChoiceIndex, mSpikeMaxDurationMs, Enums::NumDbChoices, and SKIP_EFFECT_MILLISECOND.
Referenced by EffectSpikeCleaner().
bool EffectSpikeCleaner::ProcessSimpleMono (float * buffer, sampleCount len) [protected, virtual]
Implements EffectSimpleMono.
References Enums::Db2Signal, TrackListCondIterator::First(), WaveTrack::GetRate(), gValidateSpikeFramesRemoved, mSpikeDbChoiceIndex, mSpikeMaxDurationMs, Effect::mTracks, and Track::Wave.
bool EffectSpikeCleaner::PromptUser () [virtual]
Reimplemented from Effect.
References gPrefs, Effect::mParent, mSpikeDbChoiceIndex, SpikeCleanerDialog::mSpikeDbChoiceIndex, mSpikeMaxDurationMs, SpikeCleanerDialog::mSpikeMaxDurationMs, and SpikeCleanerDialog::TransferDataToWindow().
bool EffectSpikeCleaner::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References Enums::GetDbChoices(), mSpikeDbChoiceIndex, mSpikeMaxDurationMs, Enums::NumDbChoices, Shuttle::TransferEnum(), and Shuttle::TransferInt().
Friends And Related Function Documentation
friend class SpikeCleanerDialog [friend]
Member Data Documentation
int EffectSpikeCleaner::mSpikeDbChoiceIndex [private]
Referenced by CheckWhetherSkipEffect(), Init(), ProcessSimpleMono(), PromptUser(), and TransferParameters().
int EffectSpikeCleaner::mSpikeMaxDurationMs [private]
Referenced by CheckWhetherSkipEffect(), Init(), ProcessSimpleMono(), PromptUser(), and TransferParameters().
The documentation for this class was generated from the following files:
SpikeCleaner.h
SpikeCleaner.cpp