Audacity: ProgressDialog Class Reference
ProgressDialog Class Reference
Custom progress dialog with Audacity specific semantics.
#include <ProgressDialog.h>
Public Member Functions
ProgressDialog (const wxString &title, const wxString &message=wxEmptyString, ProgressDialogFlags flags=pdlgEmptyFlags)
virtual ~ProgressDialog ()
bool Show (bool show=true)
int Update (int value, const wxString &message=wxEmptyString)
int Update (double current, const wxString &message=wxEmptyString)
int Update (double current, double total, const wxString &message=wxEmptyString)
int Update (wxULongLong_t current, wxULongLong_t total, const wxString &message=wxEmptyString)
int Update (wxLongLong current, wxLongLong total, const wxString &message=wxEmptyString)
int Update (wxLongLong_t current, wxLongLong_t total, const wxString &message=wxEmptyString)
int Update (int current, int total, const wxString &message=wxEmptyString)
void SetMessage (const wxString &message)
Protected Attributes
wxStaticText * mElapsed
wxStaticText * mRemaining
wxGauge * mGauge
wxLongLong_t mStartTime
wxLongLong_t mLastUpdate
int mLastValue
bool mCancel
bool mStop
Private Member Functions
void OnCancel (wxCommandEvent &e)
void OnStop (wxCommandEvent &e)
void Beep ()
DECLARE_EVENT_TABLE ()
Private Attributes
wxWindow * mHadFocus
wxStaticText * mMessage
wxWindowDisabler * mDisable
Detailed Description
Custom progress dialog with Audacity specific semantics.
ProgressDialog Class
Constructor & Destructor Documentation
ProgressDialog::ProgressDialog (const wxString & title, const wxString & message = wxEmptyString, ProgressDialogFlags flags = pdlgEmptyFlags)
Methods for ProgressDialog
References pdlgHideCancelButton, and pdlgHideStopButton.
ProgressDialog::~ProgressDialog () [virtual]
References Beep(), mDisable, mHadFocus, and Show().
Member Function Documentation
void ProgressDialog::Beep () [private]
References beep, gPrefs, mStartTime, and name.
Referenced by ~ProgressDialog().
ProgressDialog::DECLARE_EVENT_TABLE () [private]
void ProgressDialog::OnCancel (wxCommandEvent & e) [private]
References mCancel.
void ProgressDialog::OnStop (wxCommandEvent & e) [private]
References mCancel, and mStop.
void ProgressDialog::SetMessage (const wxString & message)
References mMessage.
Referenced by TimerProgressDialog::Update(), and Update().
bool ProgressDialog::Show (bool show = true)
References mDisable.
Referenced by TimerProgressDialog::Update(), Update(), and ~ProgressDialog().
int ProgressDialog::Update (int current, int total, const wxString & message = wxEmptyString)
References Update().
int ProgressDialog::Update (wxLongLong_t current, wxLongLong_t total, const wxString & message = wxEmptyString)
References Update().
int ProgressDialog::Update (wxLongLong current, wxLongLong total, const wxString & message = wxEmptyString)
References Update().
int ProgressDialog::Update (wxULongLong_t current, wxULongLong_t total, const wxString & message = wxEmptyString)
References Update().
int ProgressDialog::Update (double current, double total, const wxString & message = wxEmptyString)
References Update().
int ProgressDialog::Update (double current, const wxString & message = wxEmptyString)
References Update().
int ProgressDialog::Update (int value, const wxString & message = wxEmptyString)
References eProgressCancelled, eProgressStopped, eProgressSuccess, mCancel, mElapsed, mGauge, mLastUpdate, mLastValue, mRemaining, mStartTime, mStop, SetMessage(), and Show().
Referenced by UploadDialog::DownloadFile(), ExportOGG::Export(), ExportMP3::Export(), ExportMP2::Export(), ExportFLAC::Export(), ExportFFmpeg::Export(), ExportCL::Export(), DirManager::FillBlockfilesCache(), UploadDialog::GetDeleteList(), PCMImportFileHandle::Import(), OggImportFileHandle::Import(), FLACImportFileHandle::Import(), ImportRaw(), input_cb(), MixAndRender(), Effect::Preview(), FreqWindow::Recalc(), RemoveDependencies(), UploadDialog::RemoveItems(), WaveClip::Resample(), rm_dash_rf_enumerate_i(), rm_dash_rf_execute(), DirManager::SetProject(), Effect::TotalProgress(), Effect::TrackGroupProgress(), Effect::TrackProgress(), Update(), GUIProgressTarget::Update(), UploadDialog::UploadFile(), MyFLACFile::write_callback(), DirManager::WriteCacheToDisk(), and FFmpegImportFileHandle::WriteData().
Member Data Documentation
bool ProgressDialog::mCancel [protected]
Referenced by OnCancel(), OnStop(), TimerProgressDialog::Update(), and Update().
wxWindowDisabler* ProgressDialog::mDisable [private]
Referenced by Show(), and ~ProgressDialog().
wxStaticText* ProgressDialog::mElapsed [protected]
Referenced by TimerProgressDialog::Update(), and Update().
wxGauge* ProgressDialog::mGauge [protected]
Referenced by TimerProgressDialog::Update(), and Update().
wxWindow* ProgressDialog::mHadFocus [private]
Referenced by ~ProgressDialog().
wxLongLong_t ProgressDialog::mLastUpdate [protected]
Referenced by TimerProgressDialog::Update(), and Update().
int ProgressDialog::mLastValue [protected]
Referenced by TimerProgressDialog::Update(), and Update().
wxStaticText* ProgressDialog::mMessage [private]
Referenced by SetMessage().
wxStaticText* ProgressDialog::mRemaining [protected]
Referenced by TimerProgressDialog::Update(), and Update().
wxLongLong_t ProgressDialog::mStartTime [protected]
Referenced by Beep(), TimerProgressDialog::Update(), and Update().
bool ProgressDialog::mStop [protected]
Referenced by OnStop(), TimerProgressDialog::Update(), and Update().
The documentation for this class was generated from the following files:
ProgressDialog.h
ProgressDialog.cpp