Audacity: lv2_event_helpers.h File Reference
lv2_event_helpers.h File Reference
#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "lv2_event.h"
Classes
struct LV2_Event_Iterator
Functions
static uint16_t lv2_event_pad_size (uint16_t size)
static void lv2_event_buffer_reset (LV2_Event_Buffer *buf, uint16_t stamp_type, uint8_t *data)
static LV2_Event_Buffer * lv2_event_buffer_new (uint32_t capacity, uint16_t stamp_type)
static bool lv2_event_begin (LV2_Event_Iterator *iter, LV2_Event_Buffer *buf)
static bool lv2_event_is_valid (LV2_Event_Iterator *iter)
static bool lv2_event_increment (LV2_Event_Iterator *iter)
static LV2_Event * lv2_event_get (LV2_Event_Iterator *iter, uint8_t **data)
static uint16_t lv2_event_get_nonpod_type (LV2_Event_Iterator *iter)
static bool lv2_event_write (LV2_Event_Iterator *iter, uint32_t frames, uint32_t subframes, uint16_t type, uint16_t size, const uint8_t *data)
static uint8_t * lv2_event_reserve (LV2_Event_Iterator *iter, uint32_t frames, uint32_t subframes, uint16_t type, uint16_t size)
static bool lv2_event_write_event (LV2_Event_Iterator *iter, const LV2_Event *ev, const uint8_t *data)
Detailed Description
This header defines some helper functions for the the LV2 events extension with URI <http://lv2plug.in/ns/ext/event> ('lv2ev').
These functions are provided for convenience only, use of them is not required for supporting lv2ev (i.e. the events extension is defined by the raw buffer format described in lv2_event.h and NOT by this API).
Note that these functions are all static inline which basically means: do not take the address of these functions.
Function Documentation
static bool lv2_event_begin (LV2_Event_Iterator * iter, LV2_Event_Buffer * buf) [inline, static]
Reset an iterator to point to the start of buf.
Returns:
True if iter is valid, otherwise false (buffer is empty)
References LV2_Event_Iterator::buf, LV2_Event_Iterator::offset, and LV2_Event_Buffer::size.
static LV2_Event_Buffer* lv2_event_buffer_new (uint32_t capacity, uint16_t stamp_type) [inline, static]
Allocate a new, empty event buffer.
References LV2_Event_Buffer::capacity, and lv2_event_buffer_reset().
static void lv2_event_buffer_reset (LV2_Event_Buffer * buf, uint16_t stamp_type, uint8_t * data) [inline, static]
Initialize (empty, reset..) an existing event buffer. The contents of buf are ignored entirely and overwritten, except capacity which is unmodified.
References LV2_Event_Buffer::data, LV2_Event_Buffer::event_count, LV2_Event_Buffer::header_size, LV2_Event_Buffer::size, and LV2_Event_Buffer::stamp_type.
Referenced by lv2_event_buffer_new().
static LV2_Event* lv2_event_get (LV2_Event_Iterator * iter, uint8_t ** data) [inline, static]
Dereference an event iterator (get the event currently pointed at). iter must be valid. data if non-NULL, will be set to point to the contents of the event returned.
Returns:
A Pointer to the event iter is currently pointing at, or NULL if the end of the buffer is reached (in which case data is also set to NULL).
References LV2_Event_Iterator::buf, LV2_Event_Buffer::data, lv2_event_is_valid(), and LV2_Event_Iterator::offset.
static uint16_t lv2_event_get_nonpod_type (LV2_Event_Iterator * iter) [inline, static]
Get the type of the non-POD event referenced by an event iterator. iter must be valid.
Returns:
The type of the non-POD event, or 0 if the event is not non-POD.
References LV2_Event_Iterator::buf, LV2_Event_Buffer::data, lv2_event_is_valid(), LV2_Event_Iterator::offset, LV2_Event::size, and LV2_Event::type.
static bool lv2_event_increment (LV2_Event_Iterator * iter) [inline, static]
Advance iter forward one event. iter must be valid.
Returns:
True if iter is valid, otherwise false (reached end of buffer)
References LV2_Event_Iterator::buf, LV2_Event_Buffer::data, lv2_event_is_valid(), lv2_event_pad_size(), LV2_Event_Iterator::offset, and LV2_Event::size.
static bool lv2_event_is_valid (LV2_Event_Iterator * iter) [inline, static]
Check if iter is valid..
Returns:
True if iter is valid, otherwise false (past end of buffer)
References LV2_Event_Iterator::buf, LV2_Event_Iterator::offset, and LV2_Event_Buffer::size.
Referenced by lv2_event_get(), lv2_event_get_nonpod_type(), and lv2_event_increment().
static uint16_t lv2_event_pad_size (uint16_t size) [inline, static]
Pad a size to 64 bits (for event sizes)
Referenced by lv2_event_increment(), lv2_event_reserve(), lv2_event_write(), and lv2_event_write_event().
static uint8_t* lv2_event_reserve (LV2_Event_Iterator * iter, uint32_t frames, uint32_t subframes, uint16_t type, uint16_t size) [inline, static]
Reserve space for an event in the buffer and return a pointer to the memory where the caller can write the event data, or NULL if there is not enough room in the buffer.
References LV2_Event_Iterator::buf, LV2_Event_Buffer::capacity, LV2_Event_Buffer::data, LV2_Event_Buffer::event_count, LV2_Event::frames, lv2_event_pad_size(), LV2_Event_Iterator::offset, LV2_Event::size, LV2_Event_Buffer::size, LV2_Event::subframes, and LV2_Event::type.
static bool lv2_event_write (LV2_Event_Iterator * iter, uint32_t frames, uint32_t subframes, uint16_t type, uint16_t size, const uint8_t * data) [inline, static]
Write an event at iter. The event (if any) pointed to by will be overwritten, and iter incremented to point to the following event (i.e. several calls to this function can be done in sequence without twiddling iter in-between).
Returns:
True if event was written, otherwise false (buffer is full).
References LV2_Event_Iterator::buf, LV2_Event_Buffer::capacity, LV2_Event_Buffer::data, LV2_Event_Buffer::event_count, LV2_Event::frames, lv2_event_pad_size(), LV2_Event_Iterator::offset, LV2_Event::size, LV2_Event_Buffer::size, LV2_Event::subframes, and LV2_Event::type.
static bool lv2_event_write_event (LV2_Event_Iterator * iter, const LV2_Event * ev, const uint8_t * data) [inline, static]
Write an event at iter. The event (if any) pointed to by will be overwritten, and iter incremented to point to the following event (i.e. several calls to this function can be done in sequence without twiddling iter in-between).
Returns:
True if event was written, otherwise false (buffer is full).
References LV2_Event_Iterator::buf, LV2_Event_Buffer::capacity, LV2_Event_Buffer::data, LV2_Event_Buffer::event_count, lv2_event_pad_size(), LV2_Event_Iterator::offset, LV2_Event::size, and LV2_Event_Buffer::size.