Audacity: ErrorDialog.cpp File Reference
ErrorDialog.cpp File Reference
#include "../Audacity.h"
#include <wx/button.h>
#include <wx/icon.h>
#include <wx/dialog.h>
#include <wx/intl.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/utils.h>
#include <wx/html/htmlwin.h>
#include <wx/settings.h>
#include <wx/statusbr.h>
#include "LinkingHtmlWindow.h"
#include "../Theme.h"
#include "../AllThemeResources.h"
#include "../ShuttleGui.h"
#include "../HelpText.h"
#include "../Internat.h"
#include "../Project.h"
#include "../Prefs.h"
Classes
class ErrorDialog
class HtmlTextHelpDialog
Functions
void ShowHtmlText (wxWindow *pParent, const wxString &Title, const wxString &HtmlText, bool bIsFile=false, bool bModal=false)
void ShowErrorDialog (wxWindow *parent, const wxString &dlogTitle, const wxString &message, const wxString &helpURL)
Displays an error dialog with a button that offers help.
void ShowInfoDialog (wxWindow *parent, const wxString &dlogTitle, const wxString &shortMsg, const wxString &message, const int xSize, const int ySize)
Displays cutable information in a text ctrl, with an OK button.
void ShowHelpDialog (wxWindow *parent, const wxString &localFileName, const wxString &remoteURL)
Function Documentation
void ShowErrorDialog (wxWindow * parent, const wxString & dlogTitle, const wxString & message, const wxString & helpURL)
Displays an error dialog with a button that offers help.
Referenced by AudacityProject::Import().
void ShowHelpDialog (wxWindow * parent, const wxString & localFileName, const wxString & remoteURL)
Displays a file in your browser, if it's available locally, OR else links to the internet.
References GetActiveProject(), gPrefs, HelpText(), AudacityProject::mHelpPref, OpenInDefaultBrowser(), and ShowHtmlText().
Referenced by LinkingHtmlWindow::OnLinkClicked(), AudacityProject::OnManual(), and AudacityProject::OnQuickHelp().
void ShowHtmlText (wxWindow * pParent, const wxString & Title, const wxString & HtmlText, bool bIsFile = false, bool bModal = false)
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddWindow(), ThemeBase::Bitmap(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndPanel(), ShuttleGui::Id(), BrowserFrame::mpHtml, ShuttleGui::Prop(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartPanel(), and theTheme.
Referenced by ErrorDialog::OnHelp(), and ShowHelpDialog().
void ShowInfoDialog (wxWindow * parent, const wxString & dlogTitle, const wxString & shortMsg, const wxString & message, const int xSize, const int ySize)
Displays cutable information in a text ctrl, with an OK button.
Mostly we use this so that we have the code for resizability in one place. Other considerations like screen readers are also handled by having the code in one place.
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTextWindow(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddWindow(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndVerticalLay(), eOkButton, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartVerticalLay().
Referenced by AudacityProject::OnAudioDeviceInfo(), and ExportMultiple::OnExport().