Audacity: ExportFFmpeg.cpp File Reference
ExportFFmpeg.cpp File Reference
#include "../Audacity.h"
#include "../FFmpeg.h"
#include <wx/choice.h>
#include <wx/intl.h>
#include <wx/timer.h>
#include <wx/msgdlg.h>
#include <wx/progdlg.h>
#include <wx/string.h>
#include <wx/textctrl.h>
#include <wx/listbox.h>
#include <wx/window.h>
#include <wx/spinctrl.h>
#include <wx/combobox.h>
#include "../FileFormats.h"
#include "../Internat.h"
#include "../LabelTrack.h"
#include "../Mix.h"
#include "../Prefs.h"
#include "../Project.h"
#include "../Tags.h"
#include "../Track.h"
#include "../WaveTrack.h"
#include "Export.h"
#include "ExportFFmpegDialogs.h"
Classes
class ExportFFmpeg
Controlling class for FFmpeg exporting. Creates the options dialog of the appropriate type, adds tags and invokes the export function.
Defines
#define MAX_AUDIO_PACKET_SIZE (128 * 1024)
Functions
static bool CheckFFmpegPresence ()
static int AdjustFormatIndex (int format)
void AddStringTagUTF8 (char field[], int size, wxString value)
void AddStringTagANSI (char field[], int size, wxString value)
ExportPlugin * New_ExportFFmpeg ()
Variables
FFmpegLibs * FFmpegLibsInst
Define Documentation
#define MAX_AUDIO_PACKET_SIZE (128 * 1024)
Referenced by ExportFFmpeg::ExportFFmpeg(), and ExportFFmpeg::InitCodecs().
Function Documentation
void AddStringTagANSI (char field[], int size, wxString value)
Referenced by ExportFFmpeg::AddTags().
void AddStringTagUTF8 (char field[], int size, wxString value)
Referenced by ExportFFmpeg::AddTags().
static int AdjustFormatIndex (int format) [static]
References FMT_OTHER, and ExportFFmpegOptions::fmts.
Referenced by ExportFFmpeg::CheckFileName(), ExportFFmpeg::DisplayOptions(), and ExportFFmpeg::Export().
static bool CheckFFmpegPresence () [static]
References DropFFmpegLibs(), PickFFmpegLibs(), and FFmpegLibs::ValidLibsLoaded().
Referenced by ExportFFmpeg::CheckFileName(), ExportFFmpeg::DisplayOptions(), and ExportFFmpeg::Export().
ExportPlugin* New_ExportFFmpeg ()
Referenced by Exporter::Exporter().
Variable Documentation
FFmpegLibs* FFmpegLibsInst
This pointer to the shared object has global scope and is used to track the singleton object which wraps the FFmpeg codecs
Referenced by LibraryPrefs::OnFFmpegFindButton().