Audacity: Keyboard.cpp File Reference
Keyboard.cpp File Reference
#include "../Audacity.h"
#include "Keyboard.h"
Functions
wxString KeyStringNormalize (const wxString &key)
wxString KeyStringDisplay (const wxString &key)
wxString KeyEventToKeyString (const wxKeyEvent &event)
Function Documentation
wxString KeyEventToKeyString (const wxKeyEvent & event)
References KeyStringNormalize().
Referenced by CommandManager::HandleKey(), and KeyConfigPrefs::OnCaptureKeyDown().
wxString KeyStringDisplay (const wxString & key)
References KeyStringNormalize().
Referenced by KeyConfigPrefs::OnCaptureKeyDown(), and KeyConfigPrefs::RepopulateBindingsList().
wxString KeyStringNormalize (const wxString & key)
Referenced by KeyConfigPrefs::Apply(), CommandManager::GetKey(), CommandManager::HandleXMLTag(), KeyEventToKeyString(), KeyStringDisplay(), CommandManager::NewIdentifier(), and CommandManager::SetKeyFromName().