Audacity: LoadAudioUnits.h File Reference
LoadAudioUnits.h File Reference
Functions
void LoadAudioUnits ()
Function Documentation
void LoadAudioUnits ()
References EffectManager::Get(), name, and EffectManager::RegisterEffect().
Referenced by LoadEffects().