Audacity: RealFFTf.cpp File Reference
RealFFTf.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "RealFFTf.h"
Defines
#define MAX_HFFT 10
Functions
HFFT InitializeFFT (int fftlen)
void EndFFT (HFFT h)
HFFT GetFFT (int fftlen)
void ReleaseFFT (HFFT hFFT)
void CleanupFFT ()
void RealFFTf (fft_type *buffer, HFFT h)
void InverseRealFFTf (fft_type *buffer, HFFT h)
void ReorderToFreq (HFFT hFFT, fft_type *buffer, fft_type *RealOut, fft_type *ImagOut)
void ReorderToTime (HFFT hFFT, fft_type *buffer, fft_type *TimeOut)
Variables
static HFFT hFFTArray [MAX_HFFT] = { NULL }
static int nFFTLockCount [MAX_HFFT] = { 0 }
Define Documentation
#define MAX_HFFT 10
Referenced by CleanupFFT(), GetFFT(), and ReleaseFFT().
Function Documentation
void CleanupFFT ()
References EndFFT(), hFFTArray, MAX_HFFT, and nFFTLockCount.
Referenced by DeinitFFT().
void EndFFT (HFFT h)
Referenced by EffectNoiseRemoval::Cleanup(), CleanupFFT(), WaveClip::GetSpectrogram(), ReleaseFFT(), EffectEqualization::~EffectEqualization(), and WaveClip::~WaveClip().
HFFT GetFFT (int fftlen)
References hFFTArray, InitializeFFT(), MAX_HFFT, and nFFTLockCount.
Referenced by InverseRealFFT(), PowerSpectrum(), and RealFFT().
HFFT InitializeFFT (int fftlen)
References fft_type, HFFT, and M_PI.
Referenced by EffectEqualization::EffectEqualization(), GetFFT(), WaveClip::GetSpectrogram(), and EffectNoiseRemoval::Initialize().
void InverseRealFFTf (fft_type * buffer, HFFT h)
References fft_type.
Referenced by EffectEqualization::Filter(), InverseRealFFT(), and EffectNoiseRemoval::RemoveNoise().
void RealFFTf (fft_type * buffer, HFFT h)
References fft_type.
Referenced by ComputeSpectrumUsingRealFFTf(), EffectNoiseRemoval::FillFirstHistoryWindow(), EffectEqualization::Filter(), PowerSpectrum(), and RealFFT().
void ReleaseFFT (HFFT hFFT)
References EndFFT(), hFFTArray, MAX_HFFT, and nFFTLockCount.
Referenced by InverseRealFFT(), PowerSpectrum(), and RealFFT().
void ReorderToFreq (HFFT hFFT, fft_type * buffer, fft_type * RealOut, fft_type * ImagOut)
void ReorderToTime (HFFT hFFT, fft_type * buffer, fft_type * TimeOut)
Referenced by EffectEqualization::Filter(), and InverseRealFFT().
Variable Documentation
HFFT hFFTArray[MAX_HFFT] = { NULL } [static]
Referenced by CleanupFFT(), GetFFT(), and ReleaseFFT().
int nFFTLockCount[MAX_HFFT] = { 0 } [static]
Referenced by CleanupFFT(), GetFFT(), and ReleaseFFT().