Audacity: SBSMSEffect.cpp File Reference
SBSMSEffect.cpp File Reference
#include "../Audacity.h"
#include <math.h>
#include "SBSMSEffect.h"
#include "../WaveTrack.h"
#include "../Project.h"
#include "TimeWarper.h"
Classes
class resampleBuf
Functions
long samplesCB (audio *chdata, long numFrames, void *userData)
real stretchCB (long nProcessed, void *userData)
real ratioCB (long nProcessed, void *userData)
long resampleCB (void *cb_data, sbsms_resample_frame *data)
Function Documentation
real ratioCB (long nProcessed, void * userData)
Referenced by EffectSBSMS::Process().
long resampleCB (void * cb_data, sbsms_resample_frame * data)
References resampleBuf::buf, resampleBuf::end, floatSample, WaveTrack::Get(), WaveTrack::GetBestBlockSize(), resampleBuf::leftBuffer, resampleBuf::leftTrack, resampleBuf::offset, resampleBuf::ratio, resampleBuf::rightBuffer, and resampleBuf::rightTrack.
Referenced by EffectSBSMS::Process().
long samplesCB (audio * chdata, long numFrames, void * userData)
Referenced by EffectSBSMS::Process().
real stretchCB (long nProcessed, void * userData)
Referenced by EffectSBSMS::Process().