Audacity: XMLValueChecker Class Reference
XMLValueChecker Class Reference
XMLValueChecker implements static bool methods for checking input values from XML files.
#include <XMLTagHandler.h>
Static Public Member Functions
static bool IsGoodString (const wxString str)
static bool IsGoodFileName (const wxString strFileName, const wxString strDirName=wxEmptyString)
static bool IsGoodSubdirName (const wxString strSubdirName, const wxString strDirName=wxEmptyString)
static bool IsGoodPathName (const wxString strPathName)
static bool IsGoodInt (const wxString strInt)
static bool IsValidChannel (const int nValue)
static bool IsValidSampleFormat (const int nValue)
static bool IsGoodFileString (wxString str)
Detailed Description
XMLValueChecker implements static bool methods for checking input values from XML files.
Member Function Documentation
bool XMLValueChecker::IsGoodFileName (const wxString strFileName, const wxString strDirName = wxEmptyString) [static]
References IsGoodFileString().
Referenced by PCMAliasBlockFile::BuildFromXML(), ODPCMAliasBlockFile::BuildFromXML(), ODDecodeBlockFile::BuildFromXML(), LegacyBlockFile::BuildFromXML(), LegacyAliasBlockFile::BuildFromXML(), ImportXMLTagHandler::HandleXMLTag(), and IsGoodPathName().
bool XMLValueChecker::IsGoodFileString (wxString str) [static]
References IsGoodString().
Referenced by SimpleBlockFile::BuildFromXML(), PCMAliasBlockFile::BuildFromXML(), ODPCMAliasBlockFile::BuildFromXML(), ODDecodeBlockFile::BuildFromXML(), IsGoodFileName(), and IsGoodSubdirName().
bool XMLValueChecker::IsGoodInt (const wxString strInt) [static]
References IsGoodString().
Referenced by SimpleBlockFile::BuildFromXML(), SilentBlockFile::BuildFromXML(), PCMAliasBlockFile::BuildFromXML(), ODPCMAliasBlockFile::BuildFromXML(), ODDecodeBlockFile::BuildFromXML(), LegacyBlockFile::BuildFromXML(), LegacyAliasBlockFile::BuildFromXML(), WaveTrack::HandleXMLTag(), TimeTrack::HandleXMLTag(), Tags::HandleXMLTag(), Sequence::HandleXMLTag(), LabelTrack::HandleXMLTag(), Envelope::HandleXMLTag(), and RecordingRecoveryHandler::HandleXMLTag().
bool XMLValueChecker::IsGoodPathName (const wxString strPathName) [static]
References IsGoodFileName().
Referenced by PCMAliasBlockFile::BuildFromXML(), ODPCMAliasBlockFile::BuildFromXML(), ODDecodeBlockFile::BuildFromXML(), LegacyAliasBlockFile::BuildFromXML(), and ImportXMLTagHandler::HandleXMLTag().
bool XMLValueChecker::IsGoodString (const wxString str) [static]
Referenced by SimpleBlockFile::BuildFromXML(), PCMAliasBlockFile::BuildFromXML(), WaveTrack::HandleXMLTag(), WaveClip::HandleXMLTag(), TimeTrack::HandleXMLTag(), Tags::HandleXMLTag(), ImportXMLTagHandler::HandleXMLTag(), LabelTrack::HandleXMLTag(), EqualizationDialog::HandleXMLTag(), CommandManager::HandleXMLTag(), IsGoodFileString(), and IsGoodInt().
bool XMLValueChecker::IsGoodSubdirName (const wxString strSubdirName, const wxString strDirName = wxEmptyString) [static]
References IsGoodFileString().
bool XMLValueChecker::IsValidChannel (const int nValue) [static]
References Track::LeftChannel, and Track::MonoChannel.
Referenced by PCMAliasBlockFile::BuildFromXML(), ODPCMAliasBlockFile::BuildFromXML(), ODDecodeBlockFile::BuildFromXML(), LegacyAliasBlockFile::BuildFromXML(), WaveTrack::HandleXMLTag(), TimeTrack::HandleXMLTag(), and RecordingRecoveryHandler::HandleXMLTag().
bool XMLValueChecker::IsValidSampleFormat (const int nValue) [static]
References floatSample, int16Sample, and int24Sample.
Referenced by LegacyBlockFile::BuildFromXML(), and Sequence::HandleXMLTag().
The documentation for this class was generated from the following files:
XMLTagHandler.h
XMLTagHandler.cpp