Audacity: ImportExportPrefs Class Reference
ImportExportPrefs Class Reference
A PrefsPanel used to select import and export options.
#include <ImportExportPrefs.h>
Public Member Functions
ImportExportPrefs (wxWindow *parent)
~ImportExportPrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
Creates the dialog and its contents.
void PopulateOrExchange (ShuttleGui &S)
Detailed Description
A PrefsPanel used to select import and export options.
Constructor & Destructor Documentation
ImportExportPrefs::ImportExportPrefs (wxWindow * parent)
References Populate().
ImportExportPrefs::~ImportExportPrefs ()
Member Function Documentation
bool ImportExportPrefs::Apply () [virtual]
Implements PrefsPanel.
References eIsSavingToPrefs, and PopulateOrExchange().
void ImportExportPrefs::Populate () [private]
Creates the dialog and its contents.
References eIsCreatingFromPrefs, and PopulateOrExchange().
Referenced by ImportExportPrefs().
void ImportExportPrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddFixedText(), ShuttleGuiBase::EndRadioButtonGroup(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartRadioButtonGroup(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::TieCheckBox(), and ShuttleGuiBase::TieRadioButton().
Referenced by Apply(), and Populate().
The documentation for this class was generated from the following files:
ImportExportPrefs.h
ImportExportPrefs.cpp