Audacity: TimerRecordDialog Class Reference
TimerRecordDialog Class Reference
Dialog for Timer Record, i.e., timed or long recording.
#include <TimerRecordDialog.h>
Public Member Functions
TimerRecordDialog (wxWindow *parent)
~TimerRecordDialog ()
void OnTimer (wxTimerEvent &event)
bool RunWaitDialog ()
Runs the wait for start dialog. Returns false if the user clicks stop.
Private Member Functions
void OnDatePicker_Start (wxDateEvent &event)
void OnTimeText_Start (wxCommandEvent &event)
void OnDatePicker_End (wxDateEvent &event)
void OnTimeText_End (wxCommandEvent &event)
void OnTimeText_Duration (wxCommandEvent &event)
void OnOK (wxCommandEvent &event)
wxString GetDisplayDate (wxDateTime &dt)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataFromWindow ()
void UpdateDuration ()
void UpdateEnd ()
int WaitForStart ()
DECLARE_EVENT_TABLE ()
Private Attributes
wxDateTime m_DateTime_Start
wxDateTime m_DateTime_End
wxTimeSpan m_TimeSpan_Duration
wxDatePickerCtrl * m_pDatePickerCtrl_Start
TimeTextCtrl * m_pTimeTextCtrl_Start
wxDatePickerCtrl * m_pDatePickerCtrl_End
TimeTextCtrl * m_pTimeTextCtrl_End
TimeTextCtrl * m_pTimeTextCtrl_Duration
wxTimer m_timer
Detailed Description
Dialog for Timer Record, i.e., timed or long recording.
Constructor & Destructor Documentation
TimerRecordDialog::TimerRecordDialog (wxWindow * parent)
References eIsCreating, gPrefs, and kTimerInterval.
TimerRecordDialog::~TimerRecordDialog ()
Member Function Documentation
TimerRecordDialog::DECLARE_EVENT_TABLE () [private]
wxString TimerRecordDialog::GetDisplayDate (wxDateTime & dt) [private]
Referenced by RunWaitDialog(), and WaitForStart().
void TimerRecordDialog::OnDatePicker_End (wxDateEvent & event) [private]
References TimeTextCtrl::GetTimeValue(), m_DateTime_End, m_DateTime_Start, m_pDatePickerCtrl_End, m_pTimeTextCtrl_End, min(), TimeTextCtrl::SetTimeValue(), UpdateDuration(), and wxDateTime_to_AudacityTime().
Referenced by OnTimeText_End().
void TimerRecordDialog::OnDatePicker_Start (wxDateEvent & event) [private]
References TimeTextCtrl::GetTimeValue(), m_DateTime_Start, m_pDatePickerCtrl_Start, m_pTimeTextCtrl_Start, min(), OnTimer(), and UpdateEnd().
Referenced by OnTimeText_Start().
void TimerRecordDialog::OnOK (wxCommandEvent & event) [private]
References gPrefs, m_timer, m_TimeSpan_Duration, and TransferDataFromWindow().
void TimerRecordDialog::OnTimer (wxTimerEvent & event)
References m_DateTime_Start, m_pDatePickerCtrl_Start, m_pTimeTextCtrl_Start, TimeTextCtrl::SetTimeValue(), UpdateEnd(), and wxDateTime_to_AudacityTime().
Referenced by OnDatePicker_Start(), and RunWaitDialog().
void TimerRecordDialog::OnTimeText_Duration (wxCommandEvent & event) [private]
References TimeTextCtrl::GetTimeValue(), m_pTimeTextCtrl_Duration, m_TimeSpan_Duration, min(), and UpdateEnd().
void TimerRecordDialog::OnTimeText_End (wxCommandEvent & event) [private]
References TimeTextCtrl::GetTimeValue(), m_DateTime_End, m_pDatePickerCtrl_End, m_pTimeTextCtrl_End, OnDatePicker_End(), and TimeTextCtrl::SetTimeValue().
void TimerRecordDialog::OnTimeText_Start (wxCommandEvent & event) [private]
References TimeTextCtrl::GetTimeValue(), m_DateTime_Start, m_pDatePickerCtrl_Start, m_pTimeTextCtrl_Start, OnDatePicker_Start(), and TimeTextCtrl::SetTimeValue().
void TimerRecordDialog::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddWindow(), Internat::CompatibleToDouble(), TimeTextCtrl::EnableMenu(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), ID_DATEPICKER_END, ID_DATEPICKER_START, ID_TIMETEXT_DURATION, ID_TIMETEXT_END, ID_TIMETEXT_START, m_DateTime_End, m_DateTime_Start, m_pDatePickerCtrl_End, m_pDatePickerCtrl_Start, m_pTimeTextCtrl_Duration, m_pTimeTextCtrl_End, m_pTimeTextCtrl_Start, m_TimeSpan_Duration, ShuttleGuiBase::SetBorder(), TimeTextCtrl::SetTimeValue(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartVerticalLay(), and wxDateTime_to_AudacityTime().
bool TimerRecordDialog::RunWaitDialog ()
Runs the wait for start dialog. Returns false if the user clicks stop.
Runs the wait for start dialog. Returns false if the user clicks stop while we are recording so that the high
References eProgressCancelled, eProgressFailed, eProgressSuccess, GetActiveProject(), GetDisplayDate(), kTimerInterval, m_DateTime_End, m_DateTime_Start, m_TimeSpan_Duration, AudacityProject::OnRecord(), AudacityProject::OnStop(), OnTimer(), and WaitForStart().
Referenced by AudacityProject::OnTimerRecord().
bool TimerRecordDialog::TransferDataFromWindow () [private]
References TimeTextCtrl::GetTimeValue(), m_DateTime_End, m_DateTime_Start, m_pDatePickerCtrl_End, m_pDatePickerCtrl_Start, m_pTimeTextCtrl_End, m_pTimeTextCtrl_Start, m_TimeSpan_Duration, and min().
Referenced by OnOK().
void TimerRecordDialog::UpdateDuration () [private]
References Internat::CompatibleToDouble(), m_DateTime_End, m_DateTime_Start, m_pTimeTextCtrl_Duration, m_TimeSpan_Duration, and TimeTextCtrl::SetTimeValue().
Referenced by OnDatePicker_End().
void TimerRecordDialog::UpdateEnd () [private]
References m_DateTime_End, m_DateTime_Start, m_pDatePickerCtrl_End, m_pTimeTextCtrl_End, m_TimeSpan_Duration, TimeTextCtrl::SetTimeValue(), and wxDateTime_to_AudacityTime().
Referenced by OnDatePicker_Start(), OnTimer(), and OnTimeText_Duration().
int TimerRecordDialog::WaitForStart () [private]
References eProgressSuccess, GetDisplayDate(), m_DateTime_Start, and pdlgHideStopButton.
Referenced by RunWaitDialog().
Member Data Documentation
wxDateTime TimerRecordDialog::m_DateTime_End [private]
Referenced by OnDatePicker_End(), OnTimeText_End(), PopulateOrExchange(), RunWaitDialog(), TransferDataFromWindow(), UpdateDuration(), and UpdateEnd().
wxDateTime TimerRecordDialog::m_DateTime_Start [private]
Referenced by OnDatePicker_End(), OnDatePicker_Start(), OnTimer(), OnTimeText_Start(), PopulateOrExchange(), RunWaitDialog(), TransferDataFromWindow(), UpdateDuration(), UpdateEnd(), and WaitForStart().
wxDatePickerCtrl* TimerRecordDialog::m_pDatePickerCtrl_End [private]
Referenced by OnDatePicker_End(), OnTimeText_End(), PopulateOrExchange(), TransferDataFromWindow(), and UpdateEnd().
wxDatePickerCtrl* TimerRecordDialog::m_pDatePickerCtrl_Start [private]
Referenced by OnDatePicker_Start(), OnTimer(), OnTimeText_Start(), PopulateOrExchange(), and TransferDataFromWindow().
TimeTextCtrl* TimerRecordDialog::m_pTimeTextCtrl_Duration [private]
Referenced by OnTimeText_Duration(), PopulateOrExchange(), and UpdateDuration().
TimeTextCtrl* TimerRecordDialog::m_pTimeTextCtrl_End [private]
Referenced by OnDatePicker_End(), OnTimeText_End(), PopulateOrExchange(), TransferDataFromWindow(), and UpdateEnd().
TimeTextCtrl* TimerRecordDialog::m_pTimeTextCtrl_Start [private]
Referenced by OnDatePicker_Start(), OnTimer(), OnTimeText_Start(), PopulateOrExchange(), and TransferDataFromWindow().
wxTimer TimerRecordDialog::m_timer [private]
Referenced by OnOK().
wxTimeSpan TimerRecordDialog::m_TimeSpan_Duration [private]
Referenced by OnOK(), OnTimeText_Duration(), PopulateOrExchange(), RunWaitDialog(), TransferDataFromWindow(), UpdateDuration(), and UpdateEnd().
The documentation for this class was generated from the following files:
TimerRecordDialog.h
TimerRecordDialog.cpp