Audacity: EffectFindClipping Class Reference
EffectFindClipping Class Reference
Locates clipping and inserts labels when found.
#include <FindClipping.h>
Public Member Functions
EffectFindClipping ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual wxString GetEffectDescription ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Process ()
Private Member Functions
bool ProcessOne (LabelTrack *l, int count, WaveTrack *t, sampleCount start, sampleCount len)
Private Attributes
int mStart
Using int rather than sampleCount because values are only ever small numbers.
int mStop
Using int rather than sampleCount because values are only ever small numbers.
Friends
class FindClippingDialog
Detailed Description
Locates clipping and inserts labels when found.
Constructor & Destructor Documentation
EffectFindClipping::EffectFindClipping ()
References ANALYZE_EFFECT, BUILTIN_EFFECT, mStart, mStop, and Effect::SetEffectFlags().
Member Function Documentation
virtual wxString EffectFindClipping::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectFindClipping::GetEffectCategories () [inline, virtual]
wxString EffectFindClipping::GetEffectDescription () [virtual]
Reimplemented from Effect.
virtual wxString EffectFindClipping::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectFindClipping::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectFindClipping::Process () [virtual]
Implements Effect.
References TrackList::Add(), LabelTrack::Copy(), TrackListCondIterator::First(), WaveTrack::GetEndTime(), LabelTrack::GetEndTime(), WaveTrack::GetStartTime(), LabelTrack::GetStartTime(), Track::Label, Effect::mFactory, Effect::mT0, Effect::mT1, Effect::mTracks, TrackFactory::NewLabelTrack(), TrackListCondIterator::Next(), ProcessOne(), TrackList::Remove(), Track::SetName(), Track::SetOffset(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectFindClipping::ProcessOne (LabelTrack * l, int count, WaveTrack * t, sampleCount start, sampleCount len) [private]
References LabelTrack::AddLabel(), floatSample, WaveTrack::Get(), WaveTrack::LongSamplesToTime(), MAX_AUDIO, mStart, mStop, and Effect::TrackProgress().
Referenced by Process().
bool EffectFindClipping::PromptUser () [virtual]
Reimplemented from Effect.
References Effect::mParent.
bool EffectFindClipping::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References mStart, mStop, and Shuttle::TransferInt().
Friends And Related Function Documentation
friend class FindClippingDialog [friend]
Member Data Documentation
int EffectFindClipping::mStart [private]
Using int rather than sampleCount because values are only ever small numbers.
Referenced by EffectFindClipping(), FindClippingDialog::PopulateOrExchange(), ProcessOne(), FindClippingDialog::TransferDataFromWindow(), and TransferParameters().
int EffectFindClipping::mStop [private]
Using int rather than sampleCount because values are only ever small numbers.
Referenced by EffectFindClipping(), FindClippingDialog::PopulateOrExchange(), ProcessOne(), FindClippingDialog::TransferDataFromWindow(), and TransferParameters().
The documentation for this class was generated from the following files:
FindClipping.h
FindClipping.cpp