Audacity: EffectAutoDuck Class Reference
EffectAutoDuck Class Reference
Implements the Auto Ducking effect.
#include <AutoDuck.h>
Public Member Functions
EffectAutoDuck ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Init ()
virtual void End ()
virtual bool CheckWhetherSkipEffect ()
virtual bool Process ()
Private Member Functions
bool ApplyDuckFade (int trackNumber, WaveTrack *t, double t0, double t1)
Private Attributes
double mDuckAmountDb
double mInnerFadeDownLen
double mInnerFadeUpLen
double mOuterFadeDownLen
double mOuterFadeUpLen
double mThresholdDb
double mMaximumPause
WaveTrack * mControlTrack
Friends
class EffectAutoDuckDialog
Detailed Description
Implements the Auto Ducking effect.
Constructor & Destructor Documentation
EffectAutoDuck::EffectAutoDuck ()
References ADVANCED_EFFECT, BUILTIN_EFFECT, gPrefs, mControlTrack, mDuckAmountDb, mInnerFadeDownLen, mInnerFadeUpLen, mMaximumPause, mOuterFadeDownLen, mOuterFadeUpLen, mThresholdDb, PARAM_DEFAULT_DUCK_AMOUNT_DB, PARAM_DEFAULT_INNER_FADE_DOWN_LEN, PARAM_DEFAULT_INNER_FADE_UP_LEN, PARAM_DEFAULT_MAXIMUM_PAUSE, PARAM_DEFAULT_OUTER_FADE_DOWN_LEN, PARAM_DEFAULT_OUTER_FADE_UP_LEN, PARAM_DEFAULT_THRESHOLD_DB, PROCESS_EFFECT, and Effect::SetEffectFlags().
Member Function Documentation
bool EffectAutoDuck::ApplyDuckFade (int trackNumber, WaveTrack * t, double t0, double t1) [private]
References BUF_SIZE, floatSample, WaveTrack::Get(), Effect::GetNumWaveTracks(), WaveTrack::LongSamplesToTime(), mDuckAmountDb, mInnerFadeDownLen, mInnerFadeUpLen, mOuterFadeDownLen, mOuterFadeUpLen, Effect::mT0, Effect::mT1, WaveTrack::Set(), WaveTrack::TimeToLongSamples(), and Effect::TotalProgress().
Referenced by Process().
bool EffectAutoDuck::CheckWhetherSkipEffect () [virtual]
Reimplemented from Effect.
void EffectAutoDuck::End () [virtual]
Reimplemented from Effect.
References mControlTrack.
virtual wxString EffectAutoDuck::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectAutoDuck::GetEffectCategories () [inline, virtual]
virtual wxString EffectAutoDuck::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectAutoDuck::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectAutoDuck::Init () [virtual]
Reimplemented from Effect.
References TrackListIterator::First(), Track::GetKind(), Track::GetSelected(), gPrefs, mControlTrack, mDuckAmountDb, mInnerFadeDownLen, mInnerFadeUpLen, mMaximumPause, mOuterFadeDownLen, mOuterFadeUpLen, Effect::mParent, mThresholdDb, Effect::mTracks, TrackListIterator::Next(), PARAM_DEFAULT_DUCK_AMOUNT_DB, PARAM_DEFAULT_INNER_FADE_DOWN_LEN, PARAM_DEFAULT_INNER_FADE_UP_LEN, PARAM_DEFAULT_MAXIMUM_PAUSE, PARAM_DEFAULT_OUTER_FADE_DOWN_LEN, PARAM_DEFAULT_OUTER_FADE_UP_LEN, PARAM_DEFAULT_THRESHOLD_DB, and Track::Wave.
bool EffectAutoDuck::Process () [virtual]
Implements Effect.
References ApplyDuckFade(), BUF_SIZE, Effect::CopyInputTracks(), TrackListCondIterator::First(), floatSample, WaveTrack::Get(), Track::GetKind(), Effect::GetNumWaveTracks(), WaveTrack::LongSamplesToTime(), mControlTrack, mMaximumPause, mOuterFadeDownLen, mOuterFadeUpLen, Effect::mOutputTracks, Effect::mT0, Effect::mT1, mThresholdDb, TrackListCondIterator::Next(), Effect::ReplaceProcessedTracks(), RMS_WINDOW_SIZE, AutoDuckRegion::t0, AutoDuckRegion::t1, WaveTrack::TimeToLongSamples(), Effect::TotalProgress(), and Track::Wave.
bool EffectAutoDuck::PromptUser () [virtual]
Reimplemented from Effect.
References gPrefs, mDuckAmountDb, mInnerFadeDownLen, mInnerFadeUpLen, mMaximumPause, mOuterFadeDownLen, mOuterFadeUpLen, Effect::mParent, and mThresholdDb.
bool EffectAutoDuck::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References mDuckAmountDb, mInnerFadeDownLen, mInnerFadeUpLen, mMaximumPause, mOuterFadeDownLen, mOuterFadeUpLen, mThresholdDb, PARAM_DEFAULT_DUCK_AMOUNT_DB, PARAM_DEFAULT_INNER_FADE_DOWN_LEN, PARAM_DEFAULT_INNER_FADE_UP_LEN, PARAM_DEFAULT_MAXIMUM_PAUSE, PARAM_DEFAULT_OUTER_FADE_DOWN_LEN, PARAM_DEFAULT_OUTER_FADE_UP_LEN, PARAM_DEFAULT_THRESHOLD_DB, and Shuttle::TransferDouble().
Friends And Related Function Documentation
friend class EffectAutoDuckDialog [friend]
Member Data Documentation
WaveTrack* EffectAutoDuck::mControlTrack [private]
Referenced by EffectAutoDuck(), End(), Init(), and Process().
double EffectAutoDuck::mDuckAmountDb [private]
Referenced by ApplyDuckFade(), EffectAutoDuck(), Init(), EffectAutoDuckDialog::OnOk(), PromptUser(), and TransferParameters().
double EffectAutoDuck::mInnerFadeDownLen [private]
Referenced by ApplyDuckFade(), EffectAutoDuck(), Init(), EffectAutoDuckDialog::OnOk(), PromptUser(), and TransferParameters().
double EffectAutoDuck::mInnerFadeUpLen [private]
Referenced by ApplyDuckFade(), EffectAutoDuck(), Init(), EffectAutoDuckDialog::OnOk(), PromptUser(), and TransferParameters().
double EffectAutoDuck::mMaximumPause [private]
Referenced by EffectAutoDuck(), Init(), EffectAutoDuckDialog::OnOk(), Process(), PromptUser(), and TransferParameters().
double EffectAutoDuck::mOuterFadeDownLen [private]
Referenced by ApplyDuckFade(), EffectAutoDuck(), Init(), EffectAutoDuckDialog::OnOk(), Process(), PromptUser(), and TransferParameters().
double EffectAutoDuck::mOuterFadeUpLen [private]
Referenced by ApplyDuckFade(), EffectAutoDuck(), Init(), EffectAutoDuckDialog::OnOk(), Process(), PromptUser(), and TransferParameters().
double EffectAutoDuck::mThresholdDb [private]
Referenced by EffectAutoDuck(), Init(), EffectAutoDuckDialog::OnOk(), Process(), PromptUser(), and TransferParameters().
The documentation for this class was generated from the following files:
AutoDuck.h
AutoDuck.cpp