Audacity: ShuttlePrefs Class Reference
ShuttlePrefs Class Reference
A kind of Shuttle to exchange data with preferences e.g. the registry.
#include <ShuttlePrefs.h>
Public Member Functions
ShuttlePrefs ()
virtual ~ShuttlePrefs ()
virtual bool TransferBool (const wxString &Name, bool &bValue, const bool &bDefault)
virtual bool TransferDouble (const wxString &Name, double &dValue, const double &dDefault)
virtual bool TransferInt (const wxString &Name, int &iValue, const int &iDefault)
virtual bool TransferString (const wxString &Name, wxString &strValue, const wxString &strDefault)
virtual bool TransferWrappedType (const wxString &Name, WrappedType &W)
virtual bool ExchangeWithMaster (const wxString &Name)
Detailed Description
A kind of Shuttle to exchange data with preferences e.g. the registry.
This class may be used by ShuttleGui to do the two step exchange,
     Gui -- Data -- Prefs
Constructor & Destructor Documentation
ShuttlePrefs::ShuttlePrefs () [inline]
virtual ShuttlePrefs::~ShuttlePrefs () [inline, virtual]
Member Function Documentation
bool ShuttlePrefs::ExchangeWithMaster (const wxString & Name) [virtual]
Reimplemented from Shuttle.
bool ShuttlePrefs::TransferBool (const wxString & Name, bool & bValue, const bool & bDefault) [virtual]
Reimplemented from Shuttle.
References gPrefs, and Shuttle::mbStoreInClient.
Referenced by TransferWrappedType().
bool ShuttlePrefs::TransferDouble (const wxString & Name, double & dValue, const double & dDefault) [virtual]
Reimplemented from Shuttle.
References gPrefs, and Shuttle::mbStoreInClient.
Referenced by TransferWrappedType().
bool ShuttlePrefs::TransferInt (const wxString & Name, int & iValue, const int & iDefault) [virtual]
Reimplemented from Shuttle.
References gPrefs, and Shuttle::mbStoreInClient.
Referenced by TransferWrappedType().
bool ShuttlePrefs::TransferString (const wxString & Name, wxString & strValue, const wxString & strDefault) [virtual]
Reimplemented from Shuttle.
References gPrefs, and Shuttle::mbStoreInClient.
Referenced by TransferWrappedType().
bool ShuttlePrefs::TransferWrappedType (const wxString & Name, WrappedType & W) [virtual]
Reimplemented from Shuttle.
References eWrappedBool, eWrappedDouble, eWrappedEnum, eWrappedInt, eWrappedString, WrappedType::eWrappedType, WrappedType::mpBool, WrappedType::mpDouble, WrappedType::mpInt, WrappedType::mpStr, TransferBool(), TransferDouble(), TransferInt(), and TransferString().
The documentation for this class was generated from the following files:
ShuttlePrefs.h
ShuttlePrefs.cpp