Audacity: EffectSBSMS Class Reference
EffectSBSMS Class Reference
#include <SBSMSEffect.h>
Public Member Functions
virtual bool Process ()
void setParameters (double rateStart, double rateEnd, double pitchStart, double pitchEnd, int quality, bool bPreAnalyze)
Static Public Attributes
static bool bInit = FALSE
Private Member Functions
bool ProcessLabelTrack (Track *track)
Private Attributes
double rateStart
double rateEnd
double pitchStart
double pitchEnd
int quality
bool bPreAnalyze
int mCurTrackNum
double mCurT0
double mCurT1
real mTotalStretch
Member Function Documentation
bool EffectSBSMS::Process () [virtual]
Implements Effect.
Reimplemented in EffectTimeScale.
References Track::All, WaveTrack::Append(), bInit, resampleBuf::block, bPreAnalyze, resampleBuf::buf, WaveTrack::ClearAndPaste(), Effect::CopyInputTracks(), resampleBuf::end, TrackListIterator::First(), floatSample, WaveTrack::Flush(), WaveTrack::GetEndTime(), Track::GetKind(), Track::GetLinked(), WaveTrack::GetMaxBlockSize(), WaveTrack::GetRate(), WaveTrack::GetSampleFormat(), Track::GetSelected(), WaveTrack::GetStartTime(), Effect::GetTimeWarper(), Track::IsSynchroSelected(), Track::Label, resampleBuf::leftBuffer, resampleBuf::leftTrack, mCurT0, mCurT1, mCurTrackNum, Effect::mFactory, Effect::mOutputTracks, Effect::mT0, Effect::mT1, mTotalStretch, TrackFactory::NewWaveTrack(), TrackListIterator::Next(), resampleBuf::offset, resampleBuf::outBuf, resampleBuf::outputLeftBuffer, resampleBuf::outputLeftTrack, resampleBuf::outputRightBuffer, resampleBuf::outputRightTrack, resampleBuf::pitch, pitchEnd, pitchStart, ProcessLabelTrack(), quality, rateEnd, rateStart, resampleBuf::ratio, ratioCB(), Effect::ReplaceProcessedTracks(), resampleCB(), resampleBuf::resampler, resampleBuf::rightBuffer, resampleBuf::rightTrack, samplesCB(), resampleBuf::sbsmser, Effect::SetTimeWarper(), stretchCB(), Track::SyncAdjust(), WaveTrack::TimeToLongSamples(), Effect::TrackProgress(), and Track::Wave.
bool EffectSBSMS::ProcessLabelTrack (Track * track) [private]
References Effect::GetTimeWarper(), Effect::mT0, Effect::mT1, mTotalStretch, rateEnd, rateStart, Effect::SetTimeWarper(), and LabelTrack::WarpLabels().
Referenced by Process().
void EffectSBSMS::setParameters (double rateStart, double rateEnd, double pitchStart, double pitchEnd, int quality, bool bPreAnalyze)
Referenced by EffectTimeScale::Process().
Member Data Documentation
bool EffectSBSMS::bInit = FALSE [static]
Referenced by Process().
bool EffectSBSMS::bPreAnalyze [private]
Referenced by Process().
double EffectSBSMS::mCurT0 [private]
Referenced by Process().
double EffectSBSMS::mCurT1 [private]
Referenced by Process().
int EffectSBSMS::mCurTrackNum [private]
Referenced by Process().
real EffectSBSMS::mTotalStretch [private]
Referenced by Process(), and ProcessLabelTrack().
double EffectSBSMS::pitchEnd [private]
Referenced by EffectTimeScale::Process(), and Process().
double EffectSBSMS::pitchStart [private]
Referenced by EffectTimeScale::Process(), and Process().
int EffectSBSMS::quality [private]
Referenced by EffectTimeScale::Process(), and Process().
double EffectSBSMS::rateEnd [private]
Referenced by EffectTimeScale::Process(), Process(), and ProcessLabelTrack().
double EffectSBSMS::rateStart [private]
Referenced by EffectTimeScale::Process(), Process(), and ProcessLabelTrack().
The documentation for this class was generated from the following files:
SBSMSEffect.h
SBSMSEffect.cpp