Audacity: TimeRenderer Class Reference
TimeRenderer Class Reference
#include <Grid.h>
Public Member Functions
void Draw (wxGrid &grid, wxGridCellAttr &attr, wxDC &dc, const wxRect &rect, int row, int col, bool isSelected)
wxSize GetBestSize (wxGrid &grid, wxGridCellAttr &attr, wxDC &dc, int row, int col)
wxGridCellRenderer * Clone () const
Member Function Documentation
wxGridCellRenderer * TimeRenderer::Clone () const
void TimeRenderer::Draw (wxGrid & grid, wxGridCellAttr & attr, wxDC & dc, const wxRect & rect, int row, int col, bool isSelected)
References TimeEditor::GetFormat(), and TimeEditor::GetRate().
wxSize TimeRenderer::GetBestSize (wxGrid & grid, wxGridCellAttr & attr, wxDC & dc, int row, int col)
References TimeEditor::GetFormat(), and TimeEditor::GetRate().
The documentation for this class was generated from the following files:
Grid.h
Grid.cpp