Audacity: LabelTrack Class Reference
LabelTrack Class Reference
A LabelTrack is a Track that holds labels (LabelStruct).
#include <LabelTrack.h>
Public Member Functions
bool IsGoodLabelCharacter (int keyCode, wxChar charCode)
We'll only accept these characters within a label.
bool IsGoodLabelFirstCharacter (int keyCode, wxChar charCode)
bool IsTextSelected ()
void CreateCustomGlyphs ()
LabelTrack (DirManager *projDirManager)
LabelTrack (const LabelTrack &orig)
virtual ~LabelTrack ()
virtual void SetOffset (double dOffset)
void Draw (wxDC &dc, const wxRect &r, double h, double pps, double sel0, double sel1)
int getSelectedIndex () const
virtual int GetKind () const
virtual double GetStartTime ()
virtual double GetEndTime ()
virtual Track * Duplicate ()
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
virtual bool Cut (double t0, double t1, Track **dest)
virtual bool Copy (double t0, double t1, Track **dest)
virtual bool Clear (double t0, double t1)
virtual bool Paste (double t, Track *src)
bool Repeat (double t0, double t1, int n)
virtual bool Silence (double t0, double t1)
virtual bool InsertSilence (double t, double len)
int OverGlyph (int x, int y)
void ResetFlags ()
bool OverTextBox (const LabelStruct *pLabel, int x, int y)
bool CutSelectedText ()
bool CopySelectedText ()
bool PasteSelectedText (double sel0, double sel1)
void SetDragXPos (const int d)
void SetInBox (bool inTextBox)
void SetResetCursorPos (bool resetFlag)
void SetWrongDragging (bool rightFlag)
void SetDrawCursor (bool drawCursorFlag)
bool HandleMouse (const wxMouseEvent &evt, wxRect &r, double h, double pps, double *newSel0, double *newSel1)
bool CaptureKey (wxKeyEvent &event)
bool OnKeyDown (double &sel0, double &sel1, wxKeyEvent &event)
KeyEvent is called for every keypress when over the label track.
bool OnChar (double &sel0, double &sel1, wxKeyEvent &event)
KeyEvent is called for every keypress when over the label track.
void Import (wxTextFile &f)
Import labels, handling files with or without end-times.
void Export (wxTextFile &f)
Export labels including label start and end-times.
void Unselect ()
bool IsSelected () const
int GetNumLabels () const
const LabelStruct * GetLabel (int index) const
int AddLabel (double t, double t1, const wxString &title=wxT(""))
int GetLabelIndex (double t, double t1)
void DeleteLabel (int index)
bool CalcCursorX (wxWindow *parent, int *x)
int getCurrentCursorPosition () const
void MayAdjustLabel (int iLabel, int iEdge, bool bAllowSwapping, double fNewTime)
void MayMoveLabel (int iLabel, int iEdge, double fNewTime)
bool PasteOver (double t, Track *src)
bool SplitCut (double b, double e, Track **dest)
bool SplitDelete (double b, double e)
void ShiftLabelsOnInsert (double length, double pt)
void ChangeLabelsOnReverse (double b, double e)
void ScaleLabels (double b, double e, double change)
double AdjustTimeStampOnScale (double t, double b, double e, double change)
void WarpLabels (const TimeWarper &warper)
wxString GetTextOfLabels (double t0, double t1)
void SortLabels ()
Static Public Member Functions
static void ResetFont ()
static wxBitmap & GetGlyph (int i)
static bool IsTextClipSupported ()
Public Attributes
bool mbHitCenter
int mOldEdge
Private Member Functions
void ComputeLayout (const wxRect &r, double h, double pps)
void ComputeTextPosition (const wxRect &r, int index)
void SetCurrentCursorPosition (wxDC &dc, int xPos)
void calculateFontHeight (wxDC &dc)
void RemoveSelectedText ()
Private Attributes
int mSelIndex
int mMouseOverLabelLeft
Keeps track of the currently selected label.
int mMouseOverLabelRight
Keeps track of which left label the mouse is currently over.
int mxMouseDisplacement
Keeps track of which right label the mouse is currently over.
LabelArray mLabels
Displacement of mouse cursor from the centre being dragged.
int xUsed [MAX_NUM_ROWS]
int mXPos1
int mXPos2
left X pos of highlighted area
int mCurrentCursorPos
right X pos of highlighted area
int mInitialCursorPos
current cursor position
double mMouseXPos
initial cursor position
int mDragXPos
mouse X pos
bool mInBox
end X pos of dragging
bool mResetCursorPos
flag to tell if the mouse is in text box
bool mRightDragging
flag to reset cursor position(used in the dragging the glygh)
bool mDrawCursor
flag to tell if it's a valid dragging
double mClipLen
flag to tell if drawing the cursor or not
bool mIsAdjustingLabel
bool mbIsMoving
Static Private Attributes
static int mIconHeight
static int mIconWidth
static int mTextHeight
static bool mbGlyphsReady = false
static wxBitmap mBoundaryGlyphs [NUM_GLYPH_CONFIGS *NUM_GLYPH_HIGHLIGHTS]
static int mFontHeight = -1
static wxFont msFont
Friends
class LabelStruct
Detailed Description
A LabelTrack is a Track that holds labels (LabelStruct).
These are used to annotate a waveform. Each label has a start time and an end time. The text of the labels is editable and the positions of the end points are draggable.
Constructor & Destructor Documentation
LabelTrack::LabelTrack (DirManager * projDirManager)
References CreateCustomGlyphs(), Track::GetDefaultName(), ResetFlags(), ResetFont(), Track::SetDefaultName(), Track::SetHeight(), and Track::SetName().
Referenced by Copy(), Duplicate(), and SplitCut().
LabelTrack::LabelTrack (const LabelTrack & orig)
References LabelStruct, mLabels, mSelIndex, ResetFlags(), LabelStruct::t, LabelStruct::t1, and LabelStruct::title.
LabelTrack::~LabelTrack () [virtual]
References mLabels.
Member Function Documentation
int LabelTrack::AddLabel (double t, double t1, const wxString & title = wxT(""))
References LabelStruct, mCurrentCursorPos, mDrawCursor, mInitialCursorPos, mLabels, mSelIndex, LabelStruct::t, LabelStruct::t1, and LabelStruct::title.
Referenced by VampEffect::AddFeatures(), AudacityProject::DoAddLabel(), LabelDialog::OnExport(), AudacityProject::OnPasteNewLabel(), PasteSelectedText(), EffectNyquist::ProcessOne(), and EffectFindClipping::ProcessOne().
double LabelTrack::AdjustTimeStampOnScale (double t, double b, double e, double change)
Referenced by ScaleLabels().
bool LabelTrack::CalcCursorX (wxWindow * parent, int * x)
References mCurrentCursorPos, mIconWidth, mLabels, mSelIndex, and msFont.
Referenced by TrackPanel::OnKeyDown(), and AudacityProject::OnPaste().
void LabelTrack::calculateFontHeight (wxDC & dc) [private]
References mFontHeight.
Referenced by Draw().
bool LabelTrack::CaptureKey (wxKeyEvent & event)
References gAudioIO, GetActiveProject(), AudacityProject::GetAudioIOToken(), AudacityProject::GetCommandManager(), CommandManager::GetKeyFromName(), GetLabelIndex(), IsGoodLabelCharacter(), IsGoodLabelFirstCharacter(), AudioIO::IsStreamActive(), mSelIndex, AudacityProject::mViewInfo, AudacityProject::OnAddLabel(), ViewInfo::sel0, and ViewInfo::sel1.
void LabelTrack::ChangeLabelsOnReverse (double b, double e)
References mLabels, and SortLabels().
Referenced by EffectReverse::Process().
bool LabelTrack::Clear (double t0, double t1) [virtual]
Reimplemented from Track.
References DeleteLabel(), and mLabels.
Referenced by Cut().
void LabelTrack::ComputeLayout (const wxRect & r, double h, double pps) [private]
ComputeLayout determines which row each label should be placed on, and reserves space for it. Function assumes that the labels are sorted.
References ComputeTextPosition(), MAX_NUM_ROWS, mIconHeight, mIconWidth, mLabels, mTextHeight, and xUsed.
Referenced by Draw().
void LabelTrack::ComputeTextPosition (const wxRect & r, int index) [private]
ComputeTextPosition is 'smart' about where to display the label text.
The text must be displayed between its endpoints x and x1 We'd also like it centered between them, and we'd like it on screen. It isn't always possible to achieve all of this, so we do the best we can.
This function has a number of tests and adjustments to the text start position. The tests later in the function will take priority over the ones earlier, so because centering is the first thing we do, it's the first thing we lose if we can't do everything we want to.
References mIconWidth, and mLabels.
Referenced by ComputeLayout().
bool LabelTrack::Copy (double t0, double t1, Track ** dest) [virtual]
References Track::GetDirManager(), LabelStruct, LabelTrack(), mClipLen, mLabels, LabelStruct::t, LabelStruct::t1, and LabelStruct::title.
Referenced by EffectFindClipping::Process().
bool LabelTrack::CopySelectedText ()
Copy the selected text in the text box
Returns:
true if text is selected in text box, false otherwise
References mCurrentCursorPos, mInitialCursorPos, mLabels, and mSelIndex.
Referenced by TrackPanel::OnCopySelectedText().
void LabelTrack::CreateCustomGlyphs ()
CreateCustomGlyphs() creates the mBoundaryGlyph array. It's a bit like painting by numbers!
Schematically the glyphs we want will 'look like': <O, O> and <O> for a left boundary to a label, a right boundary and both. we're creating all three glyphs using the one Xpm Spec.
When we hover over a glyph we highlight the inside of either the '<', the 'O' or the '>' or none, giving 3 x 4 = 12 combinations.
Two of those combinations aren't used, but treating them specially would make other code more complicated.
References mbGlyphsReady, mBoundaryGlyphs, mIconHeight, mIconWidth, mTextHeight, NUM_GLYPH_CONFIGS, and NUM_GLYPH_HIGHLIGHTS.
Referenced by LabelTrack().
bool LabelTrack::Cut (double t0, double t1, Track ** dest) [virtual]
References Clear(), and SplitCut().
bool LabelTrack::CutSelectedText ()
Cut the selected text in the text box
Returns:
true if text is selected in text box, false otherwise
References IsTextSelected(), mCurrentCursorPos, mInitialCursorPos, mLabels, and mSelIndex.
Referenced by TrackPanel::OnCutSelectedText().
void LabelTrack::DeleteLabel (int index)
References mCurrentCursorPos, mLabels, and mSelIndex.
Referenced by Clear(), OnKeyDown(), Silence(), SplitDelete(), and LabelDialog::TransferDataFromWindow().
void LabelTrack::Draw (wxDC & dc, const wxRect & r, double h, double pps, double sel0, double sel1)
Draw calls other functions to draw the LabelTrack.
Parameters:
dc the device context
r the LabelTrack rectangle.
References calculateFontHeight(), ThemeBase::Colour(), ComputeLayout(), TrackArtist::DrawLinkTiles(), Track::GetSelected(), Track::IsSynchroSelected(), AColor::labelSelectedBrush, AColor::labelSelectedPen, AColor::labelSurroundPen, AColor::labelSyncSelBrush, AColor::labelSyncSelPen, AColor::labelTextEditBrush, AColor::labelTextNormalBrush, AColor::labelUnselectedBrush, AColor::labelUnselectedPen, AColor::Line(), mbHitCenter, mCurrentCursorPos, mDragXPos, mDrawCursor, mFontHeight, mInitialCursorPos, mLabels, mMouseOverLabelLeft, mMouseOverLabelRight, mMouseXPos, mResetCursorPos, mSelIndex, msFont, mTextHeight, mXPos1, mXPos2, SetCurrentCursorPosition(), and theTheme.
Referenced by TrackArtist::DrawLabelTrack().
virtual Track* LabelTrack::Duplicate () [inline, virtual]
Implements Track.
References LabelTrack().
void LabelTrack::Export (wxTextFile & f)
Export labels including label start and end-times.
References mLabels.
Referenced by LabelDialog::OnExport().
int LabelTrack::getCurrentCursorPosition () const [inline]
References mCurrentCursorPos.
double LabelTrack::GetEndTime () [virtual]
Reimplemented from Track.
References mLabels.
Referenced by Paste(), EffectFindClipping::Process(), and AudacityProject::UpdateLyrics().
wxBitmap & LabelTrack::GetGlyph (int i) [static]
References ThemeBase::Bitmap(), and theTheme.
Referenced by LabelStruct::DrawGlyphs().
virtual int LabelTrack::GetKind () const [inline, virtual]
Reimplemented from Track.
References Track::Label.
const LabelStruct * LabelTrack::GetLabel (int index) const
References mLabels.
Referenced by LabelDialog::AddLabels(), ExportMultiple::ExportMultipleByLabel(), AudacityProject::GetRegionsByLabel(), AudacityProject::GetUpdateFlags(), TrackPanel::HandleLabelTrackMouseEvent(), AudacityProject::OnSplitLabelsToTracks(), SnapManager::SnapManager(), and AudacityProject::UpdateLyrics().
int LabelTrack::GetLabelIndex (double t, double t1)
References mLabels, LabelStruct::t, and LabelStruct::t1.
Referenced by CaptureKey().
int LabelTrack::GetNumLabels () const
References mLabels.
Referenced by LabelDialog::AddLabels(), ExportMultiple::CountTracksAndLabels(), AudacityProject::GetRegionsByLabel(), AudacityProject::GetUpdateFlags(), AudacityProject::OnSplitLabelsToTracks(), SnapManager::SnapManager(), LabelDialog::TransferDataFromWindow(), and AudacityProject::UpdateLyrics().
int LabelTrack::getSelectedIndex () const [inline]
References mSelIndex.
Referenced by LabelDialog::AddLabels(), and TrackPanel::HandleLabelTrackMouseEvent().
double LabelTrack::GetStartTime () [virtual]
Reimplemented from Track.
References mLabels.
Referenced by AudacityProject::GetTime(), and EffectFindClipping::Process().
wxString LabelTrack::GetTextOfLabels (double t0, double t1)
References mLabels.
bool LabelTrack::HandleMouse (const wxMouseEvent & evt, wxRect & r, double h, double pps, double * newSel0, double * newSel1)
HandleMouse gets called with every mouse move or click.
References Constrain(), MayAdjustLabel(), MayMoveLabel(), mbHitCenter, mbIsMoving, mCurrentCursorPos, mDragXPos, mFontHeight, mInBox, mInitialCursorPos, mIsAdjustingLabel, mLabels, mMouseOverLabelLeft, mMouseOverLabelRight, mMouseXPos, mResetCursorPos, mRightDragging, mSelIndex, mxMouseDisplacement, mXPos1, mXPos2, OverGlyph(), OverTextBox(), and SortLabels().
Referenced by TrackPanel::HandleLabelTrackMouseEvent(), and TrackPanel::SelectionHandleClick().
XMLTagHandler * LabelTrack::HandleXMLChild (const wxChar * tag) [virtual]
Implements Track.
bool LabelTrack::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements Track.
References Internat::CompatibleToDouble(), XMLValueChecker::IsGoodInt(), XMLValueChecker::IsGoodString(), LabelStruct, mLabels, Track::mName, Track::SetHeight(), Track::SetMinimized(), LabelStruct::t, LabelStruct::t1, and LabelStruct::title.
void LabelTrack::Import (wxTextFile & f)
Import labels, handling files with or without end-times.
References Internat::CompatibleToDouble(), LabelStruct, mLabels, SortLabels(), LabelStruct::t, LabelStruct::t1, and LabelStruct::title.
Referenced by LabelDialog::OnImport(), and AudacityProject::OnImportLabels().
bool LabelTrack::InsertSilence (double t, double len) [virtual]
Reimplemented from Track.
References mLabels.
bool LabelTrack::IsGoodLabelCharacter (int keyCode, wxChar charCode)
We'll only accept these characters within a label.
Referenced by CaptureKey(), and OnChar().
bool LabelTrack::IsGoodLabelFirstCharacter (int keyCode, wxChar charCode)
The 'typing at selection creates label' feature will only accept these charCodes as a first label character.
Referenced by CaptureKey().
bool LabelTrack::IsSelected () const
References mLabels, and mSelIndex.
Referenced by AudacityProject::OnPaste(), and TrackPanel::SelectionHandleClick().
bool LabelTrack::IsTextClipSupported () [static]
Returns:
true if the text data is available in the clipboard, false otherwise
Referenced by AudacityProject::GetUpdateFlags(), TrackPanel::HandleLabelTrackMouseEvent(), and PasteSelectedText().
bool LabelTrack::IsTextSelected ()
References mCurrentCursorPos, mInitialCursorPos, mLabels, and mSelIndex.
Referenced by CutSelectedText(), AudacityProject::GetUpdateFlags(), and TrackPanel::HandleLabelTrackMouseEvent().
void LabelTrack::MayAdjustLabel (int iLabel, int iEdge, bool bAllowSwapping, double fNewTime)
If the index is for a real label, adjust its left or right boundary. - index of label, -1 for none. - which edge is requested to move, -1 for left +1 for right. - if we can switch which edge is being dragged. fNewTime - the new time for this edge of the label.
References LabelStruct::AdjustEdge(), mLabels, mMouseOverLabelLeft, mMouseOverLabelRight, LabelStruct::t, and LabelStruct::t1.
Referenced by HandleMouse().
void LabelTrack::MayMoveLabel (int iLabel, int iEdge, double fNewTime)
References mLabels.
Referenced by HandleMouse().
bool LabelTrack::OnChar (double & sel0, double & sel1, wxKeyEvent & event)
KeyEvent is called for every keypress when over the label track.
References IsGoodLabelCharacter(), LabelStruct, mCurrentCursorPos, mDrawCursor, mInitialCursorPos, mLabels, mSelIndex, RemoveSelectedText(), LabelStruct::t, LabelStruct::t1, and LabelStruct::title.
bool LabelTrack::OnKeyDown (double & sel0, double & sel1, wxKeyEvent & event)
KeyEvent is called for every keypress when over the label track.
References DeleteLabel(), mCurrentCursorPos, mDragXPos, mDrawCursor, mInitialCursorPos, mLabels, mSelIndex, and RemoveSelectedText().
Referenced by TrackPanel::OnKeyDown().
int LabelTrack::OverGlyph (int x, int y)
OverGlyph returns 0 if not over a glyph, 1 if over the left-hand glyph, and 2 if over the right-hand glyph on a label. 3 if over both right and left.
It also sets up member variables: mMouseLabelLeft - index of any left label hit mMouseLabelRight - index of any right label hit mbHitCenter - if (x,y) 'hits the spot'.
TODO: Investigate what happens with large numbers of labels, might need a binary search rather than a linear one.
References mbHitCenter, mInBox, mLabels, mMouseOverLabelLeft, mMouseOverLabelRight, mTextHeight, OverTextBox(), LabelStruct::x, LabelStruct::x1, and LabelStruct::y.
Referenced by TrackPanel::HandleLabelTrackMouseEvent(), HandleMouse(), and TrackPanel::SetCursorAndTipWhenInLabelTrack().
bool LabelTrack::OverTextBox (const LabelStruct * pLabel, int x, int y)
References mIconHeight, mIconWidth, LabelStruct::width, LabelStruct::xText, and LabelStruct::y.
Referenced by TrackPanel::HandleLabelTrackMouseEvent(), HandleMouse(), and OverGlyph().
bool LabelTrack::Paste (double t, Track * src) [virtual]
References GetEndTime(), Track::GetKind(), Track::Label, mClipLen, PasteOver(), and ShiftLabelsOnInsert().
bool LabelTrack::PasteOver (double t, Track * src)
References Track::GetKind(), Track::Label, LabelStruct, mLabels, LabelStruct::t, LabelStruct::t1, and LabelStruct::title.
Referenced by Paste().
bool LabelTrack::PasteSelectedText (double sel0, double sel1)
Paste the text on the clipboard to text box
Returns:
true if mouse is clicked in text box, false otherwise
References AddLabel(), IsTextClipSupported(), mCurrentCursorPos, mInitialCursorPos, mLabels, and mSelIndex.
Referenced by AudacityProject::OnPaste(), AudacityProject::OnPasteNewLabel(), and TrackPanel::OnPasteSelectedText().
void LabelTrack::RemoveSelectedText () [private]
References mCurrentCursorPos, mDragXPos, mInitialCursorPos, mLabels, and mSelIndex.
Referenced by OnChar(), and OnKeyDown().
bool LabelTrack::Repeat (double t0, double t1, int n)
References LabelStruct, mLabels, ShiftLabelsOnInsert(), LabelStruct::t, LabelStruct::t1, and LabelStruct::title.
Referenced by EffectRepeat::Process().
void LabelTrack::ResetFlags ()
References mCurrentCursorPos, mDragXPos, mDrawCursor, mInitialCursorPos, mMouseXPos, mResetCursorPos, mRightDragging, mXPos1, and mXPos2.
Referenced by LabelTrack().
void LabelTrack::ResetFont () [static]
References gPrefs, mFontHeight, and msFont.
Referenced by LabelTrack(), and TrackPanel::OnSetFont().
void LabelTrack::ScaleLabels (double b, double e, double change)
References AdjustTimeStampOnScale(), and mLabels.
void LabelTrack::SetCurrentCursorPosition (wxDC & dc, int xPos) [private]
Set the cursor position according to x position of mouse uses GetTextExtent to find the character position corresponding to the x pixel position.
References mCurrentCursorPos, mLabels, and mSelIndex.
Referenced by Draw().
void LabelTrack::SetDragXPos (const int d) [inline]
References mDragXPos.
Referenced by TrackPanel::HandleLabelTrackMouseEvent().
void LabelTrack::SetDrawCursor (bool drawCursorFlag) [inline]
References mDrawCursor.
void LabelTrack::SetInBox (bool inTextBox) [inline]
References mInBox.
Referenced by TrackPanel::HandleLabelTrackMouseEvent().
void LabelTrack::SetOffset (double dOffset) [virtual]
Reimplemented from Track.
References mLabels.
void LabelTrack::SetResetCursorPos (bool resetFlag) [inline]
References mResetCursorPos.
Referenced by TrackPanel::HandleLabelTrackMouseEvent().
void LabelTrack::SetWrongDragging (bool rightFlag) [inline]
References mRightDragging.
Referenced by TrackPanel::HandleLabelTrackMouseEvent().
void LabelTrack::ShiftLabelsOnInsert (double length, double pt)
References mLabels.
Referenced by Paste(), and Repeat().
bool LabelTrack::Silence (double t0, double t1) [virtual]
Reimplemented from Track.
References DeleteLabel(), LabelStruct, mLabels, SortLabels(), LabelStruct::t, LabelStruct::t1, and LabelStruct::title.
void LabelTrack::SortLabels ()
Sorts the labels in order of their starting times. This function is called often (whilst dragging a label) We expect them to be very nearly in order, so insertion sort (with a linear search) is a reasonable choice.
References mLabels, mMouseOverLabelLeft, mMouseOverLabelRight, and mSelIndex.
Referenced by ChangeLabelsOnReverse(), HandleMouse(), Import(), and Silence().
bool LabelTrack::SplitCut (double b, double e, Track ** dest)
References Track::GetDirManager(), LabelTrack(), mClipLen, mLabels, and mSelIndex.
Referenced by Cut().
bool LabelTrack::SplitDelete (double b, double e)
References DeleteLabel(), and mLabels.
void LabelTrack::Unselect ()
References mSelIndex.
Referenced by AudacityProject::OnPasteNewLabel().
void LabelTrack::WarpLabels (const TimeWarper & warper)
References mLabels, and TimeWarper::Warp().
Referenced by EffectSoundTouch::ProcessLabelTrack(), EffectSBSMS::ProcessLabelTrack(), and EffectChangeSpeed::ProcessLabelTrack().
void LabelTrack::WriteXML (XMLWriter & xmlFile) [virtual]
Implements Track.
References XMLWriter::EndTag(), Track::GetActualHeight(), Track::GetMinimized(), mLabels, Track::mName, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
Friends And Related Function Documentation
friend class LabelStruct [friend]
Referenced by AddLabel(), Copy(), HandleXMLTag(), Import(), LabelTrack(), OnChar(), PasteOver(), Repeat(), and Silence().
Member Data Documentation
bool LabelTrack::mbGlyphsReady = false [static, private]
Referenced by CreateCustomGlyphs().
bool LabelTrack::mbHitCenter
Referenced by Draw(), HandleMouse(), OverGlyph(), and TrackPanel::SetCursorAndTipWhenInLabelTrack().
bool LabelTrack::mbIsMoving [private]
Referenced by HandleMouse().
wxBitmap LabelTrack::mBoundaryGlyphs [static, private]
We have several variants of the icons (highlighting). The icons are draggable, and you can drag one boundary or all boundaries at the same timecode depending on whether you click the centre (for all) or the arrow part (for one). Currently we have twelve variants but we're only using six.
Referenced by CreateCustomGlyphs().
double LabelTrack::mClipLen [private]
flag to tell if drawing the cursor or not
Referenced by Copy(), Paste(), and SplitCut().
int LabelTrack::mCurrentCursorPos [private]
right X pos of highlighted area
Referenced by AddLabel(), CalcCursorX(), CopySelectedText(), CutSelectedText(), DeleteLabel(), Draw(), getCurrentCursorPosition(), HandleMouse(), IsTextSelected(), OnChar(), OnKeyDown(), PasteSelectedText(), RemoveSelectedText(), ResetFlags(), and SetCurrentCursorPosition().
int LabelTrack::mDragXPos [private]
mouse X pos
Referenced by Draw(), HandleMouse(), OnKeyDown(), RemoveSelectedText(), ResetFlags(), and SetDragXPos().
bool LabelTrack::mDrawCursor [private]
flag to tell if it's a valid dragging
Referenced by AddLabel(), Draw(), OnChar(), OnKeyDown(), ResetFlags(), and SetDrawCursor().
int LabelTrack::mFontHeight = -1 [static, private]
Referenced by calculateFontHeight(), Draw(), HandleMouse(), and ResetFont().
int LabelTrack::mIconHeight [static, private]
Referenced by ComputeLayout(), CreateCustomGlyphs(), LabelStruct::DrawGlyphs(), LabelStruct::DrawLines(), and OverTextBox().
int LabelTrack::mIconWidth [static, private]
Referenced by CalcCursorX(), ComputeLayout(), ComputeTextPosition(), CreateCustomGlyphs(), LabelStruct::DrawGlyphs(), LabelStruct::DrawText(), LabelStruct::DrawTextBox(), and OverTextBox().
bool LabelTrack::mInBox [private]
end X pos of dragging
Referenced by HandleMouse(), OverGlyph(), and SetInBox().
int LabelTrack::mInitialCursorPos [private]
current cursor position
Referenced by AddLabel(), CopySelectedText(), CutSelectedText(), Draw(), HandleMouse(), IsTextSelected(), OnChar(), OnKeyDown(), PasteSelectedText(), RemoveSelectedText(), and ResetFlags().
bool LabelTrack::mIsAdjustingLabel [private]
Referenced by HandleMouse().
LabelArray LabelTrack::mLabels [private]
Displacement of mouse cursor from the centre being dragged.
Referenced by AddLabel(), CalcCursorX(), ChangeLabelsOnReverse(), Clear(), ComputeLayout(), ComputeTextPosition(), Copy(), CopySelectedText(), CutSelectedText(), DeleteLabel(), Draw(), Export(), GetEndTime(), GetLabel(), GetLabelIndex(), GetNumLabels(), GetStartTime(), GetTextOfLabels(), HandleMouse(), HandleXMLTag(), Import(), InsertSilence(), IsSelected(), IsTextSelected(), LabelTrack(), MayAdjustLabel(), MayMoveLabel(), OnChar(), OnKeyDown(), OverGlyph(), PasteOver(), PasteSelectedText(), RemoveSelectedText(), Repeat(), ScaleLabels(), SetCurrentCursorPosition(), SetOffset(), ShiftLabelsOnInsert(), Silence(), SortLabels(), SplitCut(), SplitDelete(), WarpLabels(), WriteXML(), and ~LabelTrack().
int LabelTrack::mMouseOverLabelLeft [private]
Keeps track of the currently selected label.
Referenced by Draw(), HandleMouse(), MayAdjustLabel(), OverGlyph(), and SortLabels().
int LabelTrack::mMouseOverLabelRight [private]
Keeps track of which left label the mouse is currently over.
Referenced by Draw(), HandleMouse(), MayAdjustLabel(), OverGlyph(), and SortLabels().
double LabelTrack::mMouseXPos [private]
initial cursor position
Referenced by Draw(), HandleMouse(), and ResetFlags().
int LabelTrack::mOldEdge
Referenced by TrackPanel::SetCursorAndTipWhenInLabelTrack().
bool LabelTrack::mResetCursorPos [private]
flag to tell if the mouse is in text box
Referenced by Draw(), HandleMouse(), ResetFlags(), and SetResetCursorPos().
bool LabelTrack::mRightDragging [private]
flag to reset cursor position(used in the dragging the glygh)
Referenced by HandleMouse(), ResetFlags(), and SetWrongDragging().
int LabelTrack::mSelIndex [private]
Referenced by AddLabel(), CalcCursorX(), CaptureKey(), CopySelectedText(), CutSelectedText(), DeleteLabel(), Draw(), getSelectedIndex(), HandleMouse(), IsSelected(), IsTextSelected(), LabelTrack(), OnChar(), OnKeyDown(), PasteSelectedText(), RemoveSelectedText(), SetCurrentCursorPosition(), SortLabels(), SplitCut(), and Unselect().
wxFont LabelTrack::msFont [static, private]
Referenced by CalcCursorX(), Draw(), and ResetFont().
int LabelTrack::mTextHeight [static, private]
Referenced by ComputeLayout(), CreateCustomGlyphs(), Draw(), LabelStruct::DrawGlyphs(), LabelStruct::DrawLines(), LabelStruct::DrawText(), LabelStruct::DrawTextBox(), and OverGlyph().
int LabelTrack::mxMouseDisplacement [private]
Keeps track of which right label the mouse is currently over.
Referenced by HandleMouse().
int LabelTrack::mXPos1 [private]
Referenced by Draw(), HandleMouse(), and ResetFlags().
int LabelTrack::mXPos2 [private]
left X pos of highlighted area
Referenced by Draw(), HandleMouse(), and ResetFlags().
int LabelTrack::xUsed[MAX_NUM_ROWS] [private]
Referenced by ComputeLayout().
The documentation for this class was generated from the following files:
LabelTrack.h
LabelTrack.cpp