Audacity: FFmpegPresets Class Reference
FFmpegPresets Class Reference
#include <ExportFFmpegDialogs.h>
Public Member Functions
FFmpegPresets ()
~FFmpegPresets ()
wxArrayString * GetPresetList ()
void LoadPreset (ExportFFmpegOptions *parent, wxString &name)
void SavePreset (ExportFFmpegOptions *parent, wxString &name)
void DeletePreset (wxString &name)
FFmpegPreset * FindPreset (wxString &name)
void ImportPresets (wxString &filename)
void ExportPresets (wxString &filename)
bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
XMLTagHandler * HandleXMLChild (const wxChar *tag)
void WriteXMLHeader (XMLWriter &xmlFile)
void WriteXML (XMLWriter &xmlFile)
Private Attributes
FFmpegPresetList * mPresets
Constructor & Destructor Documentation
FFmpegPresets::FFmpegPresets ()
References FileNames::DataDir(), mPresets, and XMLFileReader::Parse().
FFmpegPresets::~FFmpegPresets ()
References FileNames::DataDir(), mPresets, XMLFileWriter::Open(), WriteXML(), and WriteXMLHeader().
Member Function Documentation
void FFmpegPresets::DeletePreset (wxString & name)
References FFmpegPreset::mPresetName, and mPresets.
Referenced by ExportFFmpegOptions::OnDeletePreset().
void FFmpegPresets::ExportPresets (wxString & filename)
References XMLFileWriter::Open(), WriteXML(), and WriteXMLHeader().
Referenced by ExportFFmpegOptions::OnExportPresets().
FFmpegPreset * FFmpegPresets::FindPreset (wxString & name)
References FFmpegPreset::mPresetName, and mPresets.
Referenced by HandleXMLTag(), LoadPreset(), and SavePreset().
wxArrayString * FFmpegPresets::GetPresetList ()
References FFmpegPreset::mPresetName, and mPresets.
Referenced by ExportFFmpegOptions::ExportFFmpegOptions(), and ExportFFmpegOptions::OnImportPresets().
XMLTagHandler * FFmpegPresets::HandleXMLChild (const wxChar * tag) [virtual]
Implements XMLTagHandler.
bool FFmpegPresets::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements XMLTagHandler.
References FFmpegExportCtrlIDNames, FindPreset(), FFmpegPreset::mControlState, and mPresets.
void FFmpegPresets::ImportPresets (wxString & filename)
References XMLFileReader::Parse().
Referenced by ExportFFmpegOptions::OnImportPresets().
void FFmpegPresets::LoadPreset (ExportFFmpegOptions * parent, wxString & name)
References FindPreset(), and FFmpegPreset::mControlState.
Referenced by ExportFFmpegOptions::OnLoadPreset().
void FFmpegPresets::SavePreset (ExportFFmpegOptions * parent, wxString & name)
References FindPreset(), FFmpegPreset::mControlState, and mPresets.
Referenced by ExportFFmpegOptions::OnSavePreset().
void FFmpegPresets::WriteXML (XMLWriter & xmlFile)
References XMLWriter::EndTag(), FFmpegExportCtrlIDNames, FFmpegPreset::mControlState, FFmpegPreset::mPresetName, mPresets, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
Referenced by ExportPresets(), and ~FFmpegPresets().
void FFmpegPresets::WriteXMLHeader (XMLWriter & xmlFile)
References XMLWriter::Write().
Referenced by ExportPresets(), and ~FFmpegPresets().
Member Data Documentation
FFmpegPresetList* FFmpegPresets::mPresets [private]
Referenced by DeletePreset(), FFmpegPresets(), FindPreset(), GetPresetList(), HandleXMLTag(), SavePreset(), WriteXML(), and ~FFmpegPresets().
The documentation for this class was generated from the following files:
ExportFFmpegDialogs.h
ExportFFmpegDialogs.cpp