Audacity: SetProjectInfoCommand Class Reference
SetProjectInfoCommand Class Reference
Command that returns requested project information.
#include <SetProjectInfoCommand.h>
Public Member Functions
SetProjectInfoCommand (CommandType &type, CommandOutputTarget *target)
virtual ~SetProjectInfoCommand ()
virtual bool Apply (CommandExecutionContext context)
Private Types
typedef void(SetProjectInfoCommand::* Setter)(Track *trk, bool setting) const
Private Member Functions
void SetAllTracksParam (TrackList *projTracks, wxString boolValueStr, Setter functPtrToSetter)
void setSelected (Track *trk, bool setting) const
void setSolo (Track *trk, bool setting) const
void setMute (Track *trk, bool setting) const
Detailed Description
Command that returns requested project information.
Member Typedef Documentation
typedef void(SetProjectInfoCommand::* SetProjectInfoCommand::Setter)(Track *trk, bool setting) const [private]
Constructor & Destructor Documentation
SetProjectInfoCommand::SetProjectInfoCommand (CommandType & type, CommandOutputTarget * target) [inline]
virtual SetProjectInfoCommand::~SetProjectInfoCommand () [inline, virtual]
Member Function Documentation
bool SetProjectInfoCommand::Apply (CommandExecutionContext context) [virtual]
Actually carry out the command. Return true if successful and false otherwise.
Reimplemented from CommandImplementation.
References CommandImplementation::Error(), CommandImplementation::GetString(), AudacityProject::GetTracks(), kSetOfTracksStr, CommandExecutionContext::proj, SetAllTracksParam(), setMute(), setSelected(), and setSolo().
void SetProjectInfoCommand::SetAllTracksParam (TrackList * projTracks, wxString boolValueStr, Setter functPtrToSetter) [private]
References TrackListIterator::First(), and TrackListIterator::Next().
Referenced by Apply().
void SetProjectInfoCommand::setMute (Track * trk, bool setting) const [private]
References Track::GetKind(), Track::SetMute(), and Track::Wave.
Referenced by Apply().
void SetProjectInfoCommand::setSelected (Track * trk, bool setting) const [private]
References Track::SetSelected().
Referenced by Apply().
void SetProjectInfoCommand::setSolo (Track * trk, bool setting) const [private]
References Track::GetKind(), Track::SetSolo(), and Track::Wave.
Referenced by Apply().
The documentation for this class was generated from the following files:
SetProjectInfoCommand.h
SetProjectInfoCommand.cpp