Audacity: ControlToolBar Class Reference
ControlToolBar Class Reference
A ToolBar that has the main control buttons.
#include <ControlToolBar.h>
Public Member Functions
ControlToolBar ()
virtual ~ControlToolBar ()
void Create (wxWindow *parent)
void UpdatePrefs ()
virtual void OnKeyEvent (wxKeyEvent &event)
void OnRewind (wxCommandEvent &evt)
void OnPlay (wxCommandEvent &evt)
void OnStop (wxCommandEvent &evt)
void OnBatch (wxCommandEvent &evt)
void OnRecord (wxCommandEvent &evt)
void OnFF (wxCommandEvent &evt)
void OnPause (wxCommandEvent &evt)
void SetPlay (bool down)
void SetStop (bool down)
void SetRecord (bool down)
bool IsRecordDown ()
void PlayCurrentRegion (bool looped=false, bool cutpreview=false)
void PlayPlayRegion (double t0, double t1, bool looped=false, bool cutpreview=false, TimeTrack *timetrack=NULL)
void PlayDefault ()
void StopPlaying (bool stopStream=true)
void Populate ()
virtual void Repaint (wxDC *dc)
virtual void EnableDisableButtons ()
void OnKeyDown (wxKeyEvent &event)
void OnKeyUp (wxKeyEvent &event)
void SetVUMeters (AudacityProject *p)
virtual void ReCreateButtons ()
DECLARE_CLASS (ControlToolBar)
DECLARE_EVENT_TABLE ()
Private Types
enum {
ID_PLAY_BUTTON, ID_RECORD_BUTTON, ID_PAUSE_BUTTON, ID_STOP_BUTTON,
ID_FF_BUTTON, ID_REW_BUTTON, ID_BATCH_BUTTON, BUTTON_COUNT
}
Private Member Functions
AButton * MakeButton (teBmps eFore, teBmps eDisabled, int id, bool processdownevents, const wxChar *label)
void MakeLoopImage ()
void ArrangeButtons ()
void RegenerateToolsTooltips ()
void SetupCutPreviewTracks (double playStart, double cutStart, double cutEnd, double playEnd)
void ClearCutPreviewTracks ()
Private Attributes
AButton * mRewind
AButton * mPlay
AButton * mBatch
AButton * mRecord
AButton * mPause
AButton * mStop
AButton * mFF
bool mPaused
bool mErgonomicTransportButtons
bool mCleanSpeechMode
wxBoxSizer * mBatchGroup
wxBoxSizer * mSizer
TrackList * mCutPreviewTracks
Static Private Attributes
static AudacityProject * mBusyProject = NULL
Detailed Description
A ToolBar that has the main control buttons.
This class, which is a child of Toolbar, creates the window containing the tool selection (ibeam, envelope, move, zoom), the rewind/play/stop/record/ff buttons, and the volume control. The window can be embedded within a normal project window, or within a ToolbarFrame that is managed by a global ToolBarStub called gControlToolBarStub.
All of the controls in this window were custom-written for Audacity - they are not native controls on any platform - however, it is intended that the images could be easily replaced to allow "skinning" or just customization to match the look and feel of each platform.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
ID_PLAY_BUTTON
ID_RECORD_BUTTON
ID_PAUSE_BUTTON
ID_STOP_BUTTON
ID_FF_BUTTON
ID_REW_BUTTON
ID_BATCH_BUTTON
BUTTON_COUNT
Constructor & Destructor Documentation
ControlToolBar::ControlToolBar ()
Methods for ControlToolBar
References gPrefs.
ControlToolBar::~ControlToolBar () [virtual]
References OnKeyDown(), and OnKeyUp().
Member Function Documentation
void ControlToolBar::ArrangeButtons () [private]
References ToolBar::Add(), ToolBar::Detach(), ToolBar::GetSizer(), mBatch, mCleanSpeechMode, mErgonomicTransportButtons, mFF, mPause, mPlay, mRecord, mRewind, mSizer, and mStop.
Referenced by Populate().
void ControlToolBar::ClearCutPreviewTracks () [private]
References TrackList::Clear(), and mCutPreviewTracks.
Referenced by SetupCutPreviewTracks(), and StopPlaying().
void ControlToolBar::Create (wxWindow * parent) [virtual]
Reimplemented from ToolBar.
References OnKeyDown(), and OnKeyUp().
ControlToolBar::DECLARE_CLASS (ControlToolBar)
Reimplemented from ToolBar.
ControlToolBar::DECLARE_EVENT_TABLE ()
Reimplemented from ToolBar.
void ControlToolBar::EnableDisableButtons () [virtual]
Implements ToolBar.
References gAudacityProjects, gAudioIO, GetActiveProject(), AudacityProject::GetTracks(), AudioIO::IsBusy(), AButton::IsDown(), mBatch, mFF, mPause, mPlay, mRecord, mRewind, mStop, Track::Note, AButton::SetEnabled(), and Track::Wave.
Referenced by SetPlay(), SetRecord(), and SetStop().
bool ControlToolBar::IsRecordDown ()
References AButton::IsDown(), and mRecord.
AButton * ControlToolBar::MakeButton (teBmps eFore, teBmps eDisabled, int id, bool processdownevents, const wxChar * label) [private]
References ThemeBase::ImageSize(), AButton::SetFocusRect(), and theTheme.
Referenced by Populate().
void ControlToolBar::MakeLoopImage () [private]
References ThemeBase::ImageSize(), mPlay, OverlayImage(), AButton::SetAlternateImages(), and theTheme.
Referenced by Populate().
void ControlToolBar::OnBatch (wxCommandEvent & evt)
References AButton::Disable(), AButton::Enable(), GetActiveProject(), mBatch, mFF, mPause, mPlay, mRewind, mStop, AudacityProject::OnApplyChain(), and AButton::PopUp().
void ControlToolBar::OnFF (wxCommandEvent & evt)
References GetActiveProject(), mFF, AButton::PopUp(), AButton::PushDown(), AudacityProject::SkipEnd(), and AButton::WasShiftDown().
Referenced by AudacityProject::OnSkipEnd().
void ControlToolBar::OnKeyDown (wxKeyEvent & event)
References AButton::IsDown(), mPlay, and AButton::SetAlternate().
Referenced by Create(), and ~ControlToolBar().
void ControlToolBar::OnKeyEvent (wxKeyEvent & event) [virtual]
References gAudioIO, GetActiveProject(), AudioIO::IsBusy(), AudioIO::IsStreamActive(), PlayCurrentRegion(), SetPlay(), SetStop(), and StopPlaying().
void ControlToolBar::OnKeyUp (wxKeyEvent & event)
References AButton::IsDown(), mPlay, and AButton::SetAlternate().
Referenced by Create(), and ~ControlToolBar().
void ControlToolBar::OnPause (wxCommandEvent & evt)
References gAudioIO, mPause, mPaused, AButton::PopUp(), AButton::PushDown(), and AudioIO::SetPaused().
Referenced by audacityAudioCallback(), and AudacityProject::OnPause().
void ControlToolBar::OnPlay (wxCommandEvent & evt)
References GetActiveProject(), PlayDefault(), StopPlaying(), and AudacityProject::TP_DisplaySelection().
void ControlToolBar::OnRecord (wxCommandEvent & evt)
References TrackList::Add(), WaveTrack::Clear(), AButton::Disable(), TrackListIterator::First(), WaveTrack::Flush(), gAudacityProjects, gAudioIO, GetActiveProject(), AudacityProject::GetCleanSpeechMode(), WaveTrack::GetEndTime(), Track::GetHeight(), TrackList::GetNoteTrackArray(), AudacityProject::GetRate(), AudacityProject::GetSel0(), AudacityProject::GetSel1(), TrackList::GetTimeTrack(), AudacityProject::GetTrackFactory(), AudacityProject::GetTracks(), TrackList::GetWaveTrackArray(), gPrefs, WaveTrack::InsertSilence(), AudioIO::IsBusy(), TrackList::IsEmpty(), Track::LeftChannel, mBusyProject, Track::MonoChannel, mRecord, TrackFactory::NewWaveTrack(), TrackListIterator::Next(), WaveTrack::Paste(), AButton::PopUp(), TrackList::Remove(), Track::RightChannel, AudacityProject::SetAudioIOToken(), Track::SetChannel(), Track::SetHeight(), Track::SetLinked(), Track::SetMinimized(), WaveTrack::SetOffset(), SetPlay(), SetRecord(), AButton::SetShift(), SetStop(), SetVUMeters(), AudioIO::StartStream(), AButton::WasShiftDown(), and Track::Wave.
Referenced by AudacityProject::OnRecord(), and AudacityProject::OnRecordAppend().
void ControlToolBar::OnRewind (wxCommandEvent & evt)
References GetActiveProject(), mRewind, AButton::PopUp(), AButton::PushDown(), AudacityProject::Rewind(), and AButton::WasShiftDown().
Referenced by AudacityProject::OnSkipStart().
void ControlToolBar::OnStop (wxCommandEvent & evt)
References StopPlaying().
Referenced by AudacityProject::MakeReadyToPlay(), AudacityProject::OnCloseWindow(), AudacityProject::OnPlayStopSelect(), AudacityProject::OnStop(), and AudacityProject::OnStopSelect().
void ControlToolBar::PlayCurrentRegion (bool looped = false, bool cutpreview = false)
References GetActiveProject(), AudacityProject::GetPlayRegion(), loopedPlay, AudacityProject::mLastPlayMode, mPlay, normalPlay, PlayPlayRegion(), and AButton::SetAlternate().
Referenced by OnKeyEvent(), AudacityProject::OnPlayCutPreview(), AudacityProject::OnPlayLooped(), AudacityProject::OnPlayStop(), AudacityProject::OnPlayStopSelect(), and PlayDefault().
void ControlToolBar::PlayDefault ()
References mPlay, PlayCurrentRegion(), AButton::PopUp(), AButton::WasControlDown(), and AButton::WasShiftDown().
Referenced by AdornedRulerPanel::OnMouseEvents(), and OnPlay().
void ControlToolBar::PlayPlayRegion (double t0, double t1, bool looped = false, bool cutpreview = false, TimeTrack * timetrack = NULL)
References TrackListIterator::First(), gAudioIO, GetActiveProject(), TrackList::GetEndTime(), TrackList::GetNoteTrackArray(), AudacityProject::GetRate(), TrackList::GetStartTime(), TrackList::GetTimeTrack(), AudacityProject::GetTracks(), TrackList::GetWaveTrackArray(), gPrefs, AudioIO::IsBusy(), mBusyProject, mCutPreviewTracks, mPlay, TrackListIterator::Next(), Track::Note, AButton::PopUp(), AudioIO::SeekStream(), AudacityProject::SetAudioIOToken(), SetPlay(), SetRecord(), SetStop(), SetupCutPreviewTracks(), SetVUMeters(), AudioIO::StartStream(), and Track::Wave.
Referenced by AudacityProject::OnPlayOneSecond(), TranscriptionToolBar::OnPlaySpeed(), AudacityProject::OnPlayToSelection(), PlayCurrentRegion(), and TrackPanel::SelectionHandleClick().
void ControlToolBar::Populate () [virtual]
Implements ToolBar.
References ArrangeButtons(), ID_BATCH_BUTTON, ID_FF_BUTTON, ID_PAUSE_BUTTON, ID_PLAY_BUTTON, ID_RECORD_BUTTON, ID_REW_BUTTON, ID_STOP_BUTTON, MakeButton(), ToolBar::MakeButtonBackgroundsLarge(), MakeLoopImage(), mBatch, mFF, mPause, mPlay, mRecord, mRewind, mStop, and RegenerateToolsTooltips().
void ControlToolBar::ReCreateButtons () [virtual]
Reimplemented from ToolBar.
References ToolBar::Detach(), mSizer, and RegenerateToolsTooltips().
Referenced by Theme::ApplyUpdatedImages(), and UpdatePrefs().
void ControlToolBar::RegenerateToolsTooltips () [private]
References mBatch, mFF, mPause, mPlay, mRecord, mRewind, and mStop.
Referenced by Populate(), ReCreateButtons(), and UpdatePrefs().
void ControlToolBar::Repaint (wxDC * dc) [virtual]
Implements ToolBar.
References AColor::Bevel(), and mSizer.
void ControlToolBar::SetPlay (bool down)
References EnableDisableButtons(), mPlay, AButton::PopUp(), AButton::PushDown(), and AButton::SetAlternate().
Referenced by AudacityProject::MakeReadyToPlay(), OnKeyEvent(), AudacityProject::OnPlayStop(), AudacityProject::OnPlayStopSelect(), OnRecord(), PlayPlayRegion(), TrackPanel::SelectionHandleClick(), and StopPlaying().
void ControlToolBar::SetRecord (bool down)
References EnableDisableButtons(), mRecord, AButton::PopUp(), and AButton::PushDown().
Referenced by OnRecord(), PlayPlayRegion(), and StopPlaying().
void ControlToolBar::SetStop (bool down)
References EnableDisableButtons(), mPlay, mStop, AButton::PopUp(), and AButton::PushDown().
Referenced by AudacityProject::MakeReadyToPlay(), OnKeyEvent(), AudacityProject::OnPlayStop(), AudacityProject::OnPlayStopSelect(), OnRecord(), PlayPlayRegion(), and StopPlaying().
void ControlToolBar::SetupCutPreviewTracks (double playStart, double cutStart, double cutEnd, double playEnd) [private]
References TrackList::Add(), Track::Clear(), ClearCutPreviewTracks(), Track::Duplicate(), GetActiveProject(), Track::GetLink(), AudacityProject::GetTracks(), mCutPreviewTracks, and Track::Wave.
Referenced by PlayPlayRegion().
void ControlToolBar::SetVUMeters (AudacityProject * p)
References gAudioIO, MeterToolBar::GetMeters(), AudacityProject::GetMeterToolBar(), and AudioIO::SetMeters().
Referenced by OnRecord(), and PlayPlayRegion().
void ControlToolBar::StopPlaying (bool stopStream = true)
References MeterToolBar::Clear(), ClearCutPreviewTracks(), gAudioIO, GetActiveProject(), AudacityProject::GetMeterToolBar(), AudacityProject::MayStartMonitoring(), mBusyProject, mPause, mPaused, mStop, AButton::PopUp(), AButton::PushDown(), AudioIO::SetPaused(), SetPlay(), SetRecord(), SetStop(), and AudioIO::StopStream().
Referenced by OnKeyEvent(), AdornedRulerPanel::OnMouseEvents(), OnPlay(), TranscriptionToolBar::OnPlaySpeed(), AudacityProject::OnPlayStop(), OnStop(), TrackPanel::OnTimer(), and TrackPanel::SelectionHandleClick().
void ControlToolBar::UpdatePrefs () [virtual]
Reimplemented from ToolBar.
References gPrefs, mCleanSpeechMode, mErgonomicTransportButtons, ReCreateButtons(), RegenerateToolsTooltips(), ToolBar::SetLabel(), and ToolBar::Updated().
Member Data Documentation
AButton* ControlToolBar::mBatch [private]
Referenced by ArrangeButtons(), EnableDisableButtons(), OnBatch(), Populate(), and RegenerateToolsTooltips().
wxBoxSizer* ControlToolBar::mBatchGroup [private]
AudacityProject * ControlToolBar::mBusyProject = NULL [static, private]
Referenced by OnRecord(), PlayPlayRegion(), and StopPlaying().
bool ControlToolBar::mCleanSpeechMode [private]
Referenced by ArrangeButtons(), and UpdatePrefs().
TrackList* ControlToolBar::mCutPreviewTracks [private]
Referenced by ClearCutPreviewTracks(), PlayPlayRegion(), and SetupCutPreviewTracks().
bool ControlToolBar::mErgonomicTransportButtons [private]
Referenced by ArrangeButtons(), and UpdatePrefs().
AButton* ControlToolBar::mFF [private]
Referenced by ArrangeButtons(), EnableDisableButtons(), OnBatch(), OnFF(), Populate(), and RegenerateToolsTooltips().
AButton* ControlToolBar::mPause [private]
Referenced by ArrangeButtons(), EnableDisableButtons(), OnBatch(), OnPause(), Populate(), RegenerateToolsTooltips(), and StopPlaying().
bool ControlToolBar::mPaused [private]
Referenced by OnPause(), and StopPlaying().
AButton* ControlToolBar::mPlay [private]
Referenced by ArrangeButtons(), EnableDisableButtons(), MakeLoopImage(), OnBatch(), OnKeyDown(), OnKeyUp(), PlayCurrentRegion(), PlayDefault(), PlayPlayRegion(), Populate(), RegenerateToolsTooltips(), SetPlay(), and SetStop().
AButton* ControlToolBar::mRecord [private]
Referenced by ArrangeButtons(), EnableDisableButtons(), IsRecordDown(), OnRecord(), Populate(), RegenerateToolsTooltips(), and SetRecord().
AButton* ControlToolBar::mRewind [private]
Referenced by ArrangeButtons(), EnableDisableButtons(), OnBatch(), OnRewind(), Populate(), and RegenerateToolsTooltips().
wxBoxSizer* ControlToolBar::mSizer [private]
Referenced by ArrangeButtons(), ReCreateButtons(), and Repaint().
AButton* ControlToolBar::mStop [private]
Referenced by ArrangeButtons(), EnableDisableButtons(), OnBatch(), Populate(), RegenerateToolsTooltips(), SetStop(), and StopPlaying().
The documentation for this class was generated from the following files:
ControlToolBar.h
ControlToolBar.cpp