Audacity: EffectSimplePairedTwoTrack< _DataType, _xxxSample > Class Template Reference
EffectSimplePairedTwoTrack< _DataType, _xxxSample > Class Template Reference
Obsolete. Don't use it.
#include <SimplePairedTwoTrack.h>
Public Member Functions
virtual bool Process ()
Protected Member Functions
virtual bool Init ()
virtual bool ProcessTwo (int count, WaveTrack *left, WaveTrack *right, sampleCount lstart, sampleCount rstart, sampleCount len)
void End ()
Protected Attributes
sampleCount mnBlockSize
_DataType * mLeftBuffer
_DataType * mRightBuffer
int mnTracks
Detailed Description
template<class _DataType, sampleFormat _xxxSample>
class EffectSimplePairedTwoTrack< _DataType, _xxxSample >
Obsolete. Don't use it.
Member Function Documentation
template<class _DataType , sampleFormat _xxxSample> void EffectSimplePairedTwoTrack< _DataType, _xxxSample >::End () [inline, protected, virtual]
Reimplemented from Effect.
Reimplemented in EffectAvcCompressor.
References EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mLeftBuffer, EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mnBlockSize, and EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mRightBuffer.
template<class _DataType , sampleFormat _xxxSample> bool EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Init () [inline, protected, virtual]
Reimplemented from Effect.
Reimplemented in EffectAvcCompressor.
References TrackListIterator::First(), Track::GetLinked(), Effect::GetSamples(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mnBlockSize, EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mnTracks, Effect::mTracks, and TrackListIterator::Next().
template<class _DataType , sampleFormat _xxxSample> bool EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Process () [inline, virtual]
Implements Effect.
References Effect::CopyInputTracks(), TrackListCondIterator::First(), Track::GetLinked(), Effect::GetSamples(), Effect::mOutputTracks, TrackListCondIterator::Next(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::ProcessTwo(), Effect::ReplaceProcessedTracks(), and Track::Wave.
template<class _DataType , sampleFormat _xxxSample> bool EffectSimplePairedTwoTrack< _DataType, _xxxSample >::ProcessTwo (int count, WaveTrack * left, WaveTrack * right, sampleCount lstart, sampleCount rstart, sampleCount len) [inline, protected, virtual]
References WaveTrack::Get(), WaveTrack::GetMaxBlockSize(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mLeftBuffer, EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mnBlockSize, EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mnTracks, EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mRightBuffer, EffectSimplePairedTwoTrackBase::ProcessSimplePairedTwoTrack(), WaveTrack::Set(), Effect::TrackGroupProgress(), and Effect::TrackProgress().
Referenced by EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Process().
Member Data Documentation
template<class _DataType, sampleFormat _xxxSample> _DataType* EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mLeftBuffer [protected]
Referenced by EffectSimplePairedTwoTrack< _DataType, _xxxSample >::End(), and EffectSimplePairedTwoTrack< _DataType, _xxxSample >::ProcessTwo().
template<class _DataType, sampleFormat _xxxSample> sampleCount EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mnBlockSize [protected]
Referenced by EffectSimplePairedTwoTrack< _DataType, _xxxSample >::End(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Init(), and EffectSimplePairedTwoTrack< _DataType, _xxxSample >::ProcessTwo().
template<class _DataType, sampleFormat _xxxSample> int EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mnTracks [protected]
Referenced by EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Init(), and EffectSimplePairedTwoTrack< _DataType, _xxxSample >::ProcessTwo().
template<class _DataType, sampleFormat _xxxSample> _DataType* EffectSimplePairedTwoTrack< _DataType, _xxxSample >::mRightBuffer [protected]
Referenced by EffectSimplePairedTwoTrack< _DataType, _xxxSample >::End(), and EffectSimplePairedTwoTrack< _DataType, _xxxSample >::ProcessTwo().
The documentation for this class was generated from the following file:
SimplePairedTwoTrack.h