Audacity: FileHistory Class Reference
FileHistory Class Reference
Similar to FileHistory, but customized to our needs.
#include <FileHistory.h>
Public Member Functions
FileHistory (size_t maxfiles=9, wxWindowID idbase=wxID_FILE)
virtual ~FileHistory ()
void AddFileToHistory (const wxString &file, bool update=true)
void RemoveFileFromHistory (size_t i, bool update=true)
void Clear ()
void UseMenu (wxMenu *menu)
void RemoveMenu (wxMenu *menu)
void Load (wxConfigBase &config, const wxString &group)
void Save (wxConfigBase &config, const wxString &group)
void AddFilesToMenu ()
void AddFilesToMenu (wxMenu *menu)
size_t GetCount ()
wxString GetHistoryFile (size_t i) const
Private Attributes
size_t mMaxFiles
wxWindowID mIDBase
wxArrayPtrVoid mMenus
wxArrayString mHistory
Detailed Description
Similar to FileHistory, but customized to our needs.
Constructor & Destructor Documentation
FileHistory::FileHistory (size_t maxfiles = 9, wxWindowID idbase = wxID_FILE)
References mIDBase, and mMaxFiles.
FileHistory::~FileHistory () [virtual]
Member Function Documentation
void FileHistory::AddFilesToMenu (wxMenu * menu)
References mHistory, and mIDBase.
void FileHistory::AddFilesToMenu ()
References mMenus.
Referenced by AddFileToHistory(), Clear(), AudacityProject::CreateRecentFilesMenu(), Load(), AudacityApp::OnInit(), and RemoveFileFromHistory().
void FileHistory::AddFileToHistory (const wxString & file, bool update = true)
References AddFilesToMenu(), mHistory, and mMaxFiles.
Referenced by AudacityApp::AddFileToHistory(), and Load().
void FileHistory::Clear ()
References AddFilesToMenu(), and mHistory.
Referenced by AudacityApp::OnMRUClear().
size_t FileHistory::GetCount ()
References mHistory.
wxString FileHistory::GetHistoryFile (size_t i) const
References mHistory.
Referenced by AudacityApp::OnMRUFile().
void FileHistory::Load (wxConfigBase & config, const wxString & group)
References AddFilesToMenu(), AddFileToHistory(), and mHistory.
Referenced by AudacityApp::OnInit().
void FileHistory::RemoveFileFromHistory (size_t i, bool update = true)
References AddFilesToMenu(), and mHistory.
Referenced by AudacityApp::OnMRUFile().
void FileHistory::RemoveMenu (wxMenu * menu)
References mMenus.
Referenced by AudacityProject::RebuildMenuBar(), and AudacityProject::~AudacityProject().
void FileHistory::Save (wxConfigBase & config, const wxString & group)
References mHistory.
Referenced by AudacityApp::OnExit().
void FileHistory::UseMenu (wxMenu * menu)
References mMenus.
Referenced by AudacityProject::CreateRecentFilesMenu(), and AudacityApp::OnInit().
Member Data Documentation
wxArrayString FileHistory::mHistory [private]
Referenced by AddFilesToMenu(), AddFileToHistory(), Clear(), GetCount(), GetHistoryFile(), Load(), RemoveFileFromHistory(), and Save().
wxWindowID FileHistory::mIDBase [private]
Referenced by AddFilesToMenu(), and FileHistory().
size_t FileHistory::mMaxFiles [private]
Referenced by AddFileToHistory(), and FileHistory().
wxArrayPtrVoid FileHistory::mMenus [private]
Referenced by AddFilesToMenu(), RemoveMenu(), and UseMenu().
The documentation for this class was generated from the following files:
FileHistory.h
FileHistory.cpp