Audacity: FileNames Class Reference
FileNames Class Reference
Provides Static functions to yield filenames.
#include <FileNames.h>
Static Public Member Functions
static wxString MkDir (const wxString &Str)
static wxString TempDir ()
static void MakeNameUnique (wxArrayString &otherNames, wxFileName &newName)
static wxString DataDir ()
Audacity user data directory.
static wxString AutoSaveDir ()
static wxString HtmlHelpDir ()
static wxString HtmlHelpIndexFile (bool quick)
static wxString ChainDir ()
static wxString NRPDir ()
static wxString NRPFile ()
static wxString PluginsCache ()
static wxString PlugInDir ()
The user plug-in directory (not a system one).
static wxString ThemeDir ()
static wxString ThemeComponentsDir ()
static wxString ThemeCachePng ()
static wxString ThemeCacheAsCee ()
static wxString ThemeComponent (const wxString &Str)
static wxString ThemeCacheHtm ()
static wxString ThemeImageDefsAsCee ()
Private Member Functions
FileNames ()
~FileNames ()
Detailed Description
Provides Static functions to yield filenames.
This class helps us with setting a base path, and makes it easier for us to keep track of the different kinds of files we read and write from.
JKC: In time I plan to add all file names and file extensions used throughout Audacity into this one place.
Constructor & Destructor Documentation
FileNames::FileNames () [inline, private]
FileNames::~FileNames () [inline, private]
Member Function Documentation
wxString FileNames::AutoSaveDir () [static]
References DataDir(), and MkDir().
Referenced by AudacityProject::AutoSave(), HaveFilesToRecover(), AutoRecoveryDialog::PopulateList(), RecoverAllProjects(), and RemoveAllAutoSaveFiles().
wxString FileNames::ChainDir () [static]
References DataDir(), and MkDir().
Referenced by BatchCommands::AddChain(), BatchCommands::DeleteChain(), BatchCommands::GetNames(), BatchCommands::ReadChain(), BatchCommands::RenameChain(), and BatchCommands::WriteChain().
wxString FileNames::DataDir () [static]
Audacity user data directory.
Where audacity keeps it's settings and other user data squirreled away, by default ~/.audacity-data/ on Unix, Application Data/Audacity on windows system
References gDataDir, PlatformCompatibility::GetExecutablePath(), and MkDir().
Referenced by AutoSaveDir(), ChainDir(), FFmpegPresets::FFmpegPresets(), AudacityApp::InitCleanSpeech(), InitPreferences(), EqualizationDialog::LoadCurves(), UploadDialog::LoadFtpSiteList(), Tags::LoadGenres(), NRPDir(), UploadDialog::OnDeleteSite(), TagsEditor::OnEdit(), AudacityProject::OnExportCleanSpeechPresets(), AudacityProject::OnImportCleanSpeechPresets(), TagsEditor::OnLoad(), TagsEditor::OnReset(), TagsEditor::OnSave(), PlugInDir(), PluginsCache(), AboutDialog::PopulateInformationPage(), EqualizationDialog::SaveCurves(), UploadDialog::SaveFtpSite(), ThemeDir(), and FFmpegPresets::~FFmpegPresets().
wxString FileNames::HtmlHelpDir () [static]
References PlatformCompatibility::GetExecutablePath().
Referenced by FileLink(), HtmlHelpIndexFile(), and LinkingHtmlWindow::OnLinkClicked().
wxString FileNames::HtmlHelpIndexFile (bool quick) [static]
References HtmlHelpDir().
Referenced by AudacityProject::OnManual(), and AudacityProject::OnQuickHelp().
void FileNames::MakeNameUnique (wxArrayString & otherNames, wxFileName & newName) [static]
Referenced by ExportMultiple::ExportMultipleByLabel(), ExportMultiple::ExportMultipleByTrack(), and AudacityProject::SaveCompressedWaveTracks().
wxString FileNames::MkDir (const wxString & Str) [static]
Referenced by AutoSaveDir(), ChainDir(), DataDir(), NRPDir(), PlugInDir(), TempDir(), ThemeComponentsDir(), and ThemeDir().
wxString FileNames::NRPDir () [static]
References DataDir(), and MkDir().
Referenced by EffectNoiseRemoval::CleanSpeechMayReadNoisegate(), EffectNoiseRemoval::CleanSpeechMayWriteNoiseGate(), and NRPFile().
wxString FileNames::NRPFile () [static]
References NRPDir().
Referenced by EffectNoiseRemoval::CleanSpeechMayReadNoisegate(), and EffectNoiseRemoval::CleanSpeechMayWriteNoiseGate().
wxString FileNames::PlugInDir () [static]
The user plug-in directory (not a system one).
This returns the string path to where the user may have put plug-ins if they don't have system admin rights. Under default settings, it's <DataDir>/Plug-Ins/
References DataDir(), and MkDir().
wxString FileNames::PluginsCache () [static]
References DataDir().
Referenced by PluginManager::Close(), and PluginManager::Open().
wxString FileNames::TempDir () [static]
Returns the directory used for temp files.
Todo:
put a counter in here to see if it gets used a lot. if it does, then maybe we should cache the path name each time.
References gPrefs, and MkDir().
wxString FileNames::ThemeCacheAsCee () [static]
References ThemeDir().
Referenced by ThemeBase::CreateImageCache().
wxString FileNames::ThemeCacheHtm () [static]
References ThemeDir().
Referenced by ThemeBase::WriteImageMap().
wxString FileNames::ThemeCachePng () [static]
References ThemeDir().
Referenced by ThemeBase::CreateImageCache(), and ThemeBase::ReadImageCache().
wxString FileNames::ThemeComponent (const wxString & Str) [static]
References ThemeComponentsDir().
Referenced by ThemeBase::LoadComponents(), and ThemeBase::SaveComponents().
wxString FileNames::ThemeComponentsDir () [static]
References MkDir(), and ThemeDir().
Referenced by ThemeBase::LoadComponents(), ThemeBase::SaveComponents(), and ThemeComponent().
wxString FileNames::ThemeDir () [static]
References DataDir(), and MkDir().
Referenced by ThemeCacheAsCee(), ThemeCacheHtm(), ThemeCachePng(), ThemeComponentsDir(), and ThemeImageDefsAsCee().
wxString FileNames::ThemeImageDefsAsCee () [static]
References ThemeDir().
Referenced by ThemeBase::WriteImageDefs().
The documentation for this class was generated from the following files:
FileNames.h
FileNames.cpp