Audacity: TrackArtist Class Reference
TrackArtist Class Reference
This class handles the actual rendering of WaveTracks (both waveforms and spectra), NoteTracks, LabelTracks and TimeTracks.
#include <TrackArtist.h>
Public Member Functions
TrackArtist ()
~TrackArtist ()
void SetColours ()
void DrawTracks (TrackList *tracks, Track *start, wxDC &dc, wxRegion &reg, wxRect &r, wxRect &clip, ViewInfo *viewInfo, bool drawEnvelope, bool drawSamples, bool drawSliders)
void DrawTrack (const Track *t, wxDC &dc, const wxRect &r, const ViewInfo *viewInfo, bool drawEnvelope, bool drawSamples, bool drawSliders, bool hasSolo)
void DrawVRuler (Track *t, wxDC *dc, wxRect &r)
void UpdateVRuler (Track *t, wxRect &r)
void SetInset (int left, int top, int right, int bottom)
void UpdatePrefs ()
void InvalidateSpectrumCache (TrackList *tracks)
void InvalidateSpectrumCache (WaveTrack *track)
int GetSpectrumMinFreq (int deffreq)
int GetSpectrumMaxFreq (int deffreq)
int GetSpectrumLogMinFreq (int deffreq)
int GetSpectrumLogMaxFreq (int deffreq)
int GetSpectrumWindowSize ()
void SetSpectrumMinFreq (int freq)
void SetSpectrumMaxFreq (int freq)
void SetSpectrumLogMinFreq (int freq)
void SetSpectrumLogMaxFreq (int freq)
void SetBackgroundBrushes (wxBrush unselectedBrush, wxBrush selectedBrush, wxPen unselectedPen, wxPen selectedPen)
Static Public Member Functions
static void DrawLinkTiles (wxDC *dc, wxRect r)
Private Member Functions
void DrawWaveform (WaveTrack *track, wxDC &dc, const wxRect &r, const ViewInfo *viewInfo, bool drawEnvelope, bool drawSamples, bool drawSliders, bool dB, bool muted)
void DrawSpectrum (WaveTrack *track, wxDC &dc, const wxRect &r, const ViewInfo *viewInfo, bool autocorrelation, bool logF)
void DrawNoteTrack (NoteTrack *track, wxDC &dc, const wxRect &r, const ViewInfo *viewInfo)
void DrawLabelTrack (LabelTrack *track, wxDC &dc, const wxRect &r, const ViewInfo *viewInfo)
void DrawTimeTrack (TimeTrack *track, wxDC &dc, const wxRect &r, const ViewInfo *viewInfo)
void DrawTimeSlider (WaveTrack *track, wxDC &dc, const wxRect &r, const ViewInfo *viewInfo, bool rightwards)
void DrawClipWaveform (WaveTrack *track, WaveClip *clip, wxDC &dc, const wxRect &r, const ViewInfo *viewInfo, bool drawEnvelope, bool drawSamples, bool drawSliders, bool dB, bool muted)
void DrawClipSpectrum (WaveTrack *track, WaveClip *clip, wxDC &dc, const wxRect &r, const ViewInfo *viewInfo, bool autocorrelation, bool logF)
void DrawWaveformBackground (wxDC &dc, const wxRect &r, const double env[], float zoomMin, float zoomMax, bool dB, const sampleCount where[], sampleCount ssel0, sampleCount ssel1, bool drawEnvelope, bool synchroSelection)
void DrawMinMaxRMS (wxDC &dc, const wxRect &r, const double env[], float zoomMin, float zoomMax, bool dB, const float min[], const float max[], const float rms[], const int bl[], bool showProgress, bool muted)
void DrawIndividualSamples (wxDC &dc, const wxRect &r, float zoomMin, float zoomMax, bool dB, WaveClip *clip, double t0, double pps, double h, bool drawSamples, bool showPoints, bool muted)
void DrawNegativeOffsetTrackArrows (wxDC &dc, const wxRect &r)
void DrawEnvelope (wxDC &dc, const wxRect &r, const double env[], float zoomMin, float zoomMax, bool dB)
void DrawEnvLine (wxDC &dc, const wxRect &r, int x, int y, int cy, bool top)
Private Attributes
float mdBrange
long mShowClipping
int mLogMaxFreq
int mLogMinFreq
int mMaxFreq
int mMinFreq
int mWindowSize
bool mIsGrayscale
int mInsetLeft
int mInsetTop
int mInsetRight
int mInsetBottom
wxBrush blankBrush
wxBrush unselectedBrush
wxBrush selectedBrush
wxBrush syncSelBrush
wxBrush sampleBrush
wxBrush selsampleBrush
wxBrush dragsampleBrush
wxBrush muteSampleBrush
wxPen blankPen
wxPen unselectedPen
wxPen selectedPen
wxPen syncSelPen
wxPen samplePen
wxPen rmsPen
wxPen muteRmsPen
wxPen selsamplePen
wxPen muteSamplePen
wxPen odProgressNotYetPen
wxPen odProgressDonePen
wxPen shadowPen
wxPen clippedPen
wxPen muteClippedPen
Ruler * vruler
Detailed Description
This class handles the actual rendering of WaveTracks (both waveforms and spectra), NoteTracks, LabelTracks and TimeTracks.
It's actually a little harder than it looks, because for waveforms at least it needs to cache the samples that are currently on-screen.
Constructor & Destructor Documentation
TrackArtist::TrackArtist ()
References ENV_DB_RANGE, mdBrange, mInsetBottom, mInsetLeft, mInsetRight, mInsetTop, mShowClipping, SetColours(), UpdatePrefs(), and vruler.
TrackArtist::~TrackArtist ()
References vruler.
Member Function Documentation
void TrackArtist::DrawClipSpectrum (WaveTrack * track, WaveClip * clip, wxDC & dc, const wxRect & r, const ViewInfo * viewInfo, bool autocorrelation, bool logF) [private]
References GetColorGradient(), WaveClip::GetEndTime(), WaveClip::GetOffset(), WaveClip::GetRate(), Track::GetSelected(), WaveClip::GetSpectrogram(), GetSpectrumLogMaxFreq(), GetSpectrumLogMinFreq(), GetSpectrumMaxFreq(), GetSpectrumMinFreq(), GetSpectrumWindowSize(), WaveClip::GetStartTime(), gPrefs, ViewInfo::h, SpecPxCache::len, mIsGrayscale, WaveClip::mSpecPxCache, scale(), ViewInfo::sel0, ViewInfo::sel1, WaveClip::SetDisplayRect(), sumFreqValues(), SpecPxCache::valid, SpecPxCache::values, and ViewInfo::zoom.
Referenced by DrawSpectrum().
void TrackArtist::DrawClipWaveform (WaveTrack * track, WaveClip * clip, wxDC & dc, const wxRect & r, const ViewInfo * viewInfo, bool drawEnvelope, bool drawSamples, bool drawSliders, bool dB, bool muted) [private]
References DrawEnvelope(), DrawIndividualSamples(), DrawMinMaxRMS(), DrawNegativeOffsetTrackArrows(), Envelope::DrawPoints(), DrawTimeSlider(), DrawWaveformBackground(), WaveTrack::GetDisplayBounds(), WaveClip::GetEndTime(), WaveClip::GetEnvelope(), WaveClip::GetOffset(), WaveClip::GetRate(), Track::GetSelected(), WaveClip::GetStartTime(), Envelope::GetValues(), WaveClip::GetWaveDisplay(), ViewInfo::h, Track::IsSynchroSelected(), AColor::Line(), max, min(), ViewInfo::sel0, ViewInfo::sel1, WaveClip::SetDisplayRect(), and ViewInfo::zoom.
Referenced by DrawWaveform().
void TrackArtist::DrawEnvelope (wxDC & dc, const wxRect & r, const double env[], float zoomMin, float zoomMax, bool dB) [private]
References DrawEnvLine(), AColor::envelopePen, GetWaveYPos(), and mdBrange.
Referenced by DrawClipWaveform().
void TrackArtist::DrawEnvLine (wxDC & dc, const wxRect & r, int x, int y, int cy, bool top) [private]
References AColor::Line().
Referenced by DrawEnvelope().
void TrackArtist::DrawIndividualSamples (wxDC & dc, const wxRect & r, float zoomMin, float zoomMax, bool dB, WaveClip * clip, double t0, double pps, double h, bool drawSamples, bool showPoints, bool muted) [private]
References clippedPen, dragsampleBrush, floatSample, WaveClip::GetEnvelope(), WaveClip::GetNumSamples(), WaveClip::GetOffset(), WaveClip::GetRate(), WaveClip::GetSamples(), Envelope::GetValueAtX(), GetWaveYPos(), AColor::Line(), MAX_AUDIO, mdBrange, mShowClipping, muteClippedPen, muteSamplePen, sampleBrush, and samplePen.
Referenced by DrawClipWaveform().
void TrackArtist::DrawLabelTrack (LabelTrack * track, wxDC & dc, const wxRect & r, const ViewInfo * viewInfo) [private]
References LabelTrack::Draw(), Track::GetSelected(), ViewInfo::h, Track::IsSynchroSelected(), ViewInfo::sel0, ViewInfo::sel1, and ViewInfo::zoom.
Referenced by DrawTrack().
void TrackArtist::DrawLinkTiles (wxDC * dc, wxRect r) [static]
References ThemeBase::Image(), and theTheme.
Referenced by LabelTrack::Draw(), TrackInfo::DrawBackground(), and DrawWaveformBackground().
void TrackArtist::DrawMinMaxRMS (wxDC & dc, const wxRect & r, const double env[], float zoomMin, float zoomMax, bool dB, const float min[], const float max[], const float rms[], const int bl[], bool showProgress, bool muted) [private]
References clippedPen, GetWaveYPos(), AColor::Line(), MAX_AUDIO, mdBrange, mShowClipping, muteClippedPen, muteRmsPen, muteSamplePen, rmsPen, and samplePen.
Referenced by DrawClipWaveform().
void TrackArtist::DrawNegativeOffsetTrackArrows (wxDC & dc, const wxRect & r) [private]
References AColor::Line().
Referenced by DrawClipWaveform().
void TrackArtist::DrawNoteTrack (NoteTrack * track, wxDC & dc, const wxRect & r, const ViewInfo * viewInfo) [private]
References blackPos, blankBrush, blankPen, BLUE, CLIP, CLIP_MAX, AColor::DarkMIDIChannel(), NoteTrack::GetBottomNote(), Track::GetSelected(), GREEN, ViewInfo::h, IsShape(), LAT1CTOWX, AColor::LightMIDIChannel(), AColor::Line(), LookupAtomAttribute(), LookupIntAttribute(), LookupLogicalAttribute(), LookupRealAttribute(), LookupStringAttribute(), AColor::MIDIChannel(), NoteTrack::mSeq, NoteTrack::mSerializationBuffer, NoteTrack::mSerializationLength, NoteTrack::mVisibleChannels, name, notePos, octaveHeight, PITCH_TO_Y(), RED, ViewInfo::sel0, ViewInfo::sel1, TIME_TO_X, X_TO_TIME, and ViewInfo::zoom.
Referenced by DrawTrack().
void TrackArtist::DrawSpectrum (WaveTrack * track, wxDC & dc, const wxRect & r, const ViewInfo * viewInfo, bool autocorrelation, bool logF) [private]
References ViewInfo::bIsPlaying, blankBrush, ViewInfo::bUpdateTrackIndicator, DrawClipSpectrum(), DrawWaveform(), and WaveTrack::GetClipIterator().
Referenced by DrawTrack().
void TrackArtist::DrawTimeSlider (WaveTrack * track, wxDC & dc, const wxRect & r, const ViewInfo * viewInfo, bool rightwards) [private]
References AColor::Dark(), AColor::Light(), and AColor::Line().
Referenced by DrawClipWaveform().
void TrackArtist::DrawTimeTrack (TimeTrack * track, wxDC & dc, const wxRect & r, const ViewInfo * viewInfo) [private]
References TimeTrack::Draw(), Envelope::DrawPoints(), TimeTrack::GetEnvelope(), ViewInfo::h, and ViewInfo::zoom.
Referenced by DrawTrack().
void TrackArtist::DrawTrack (const Track * t, wxDC & dc, const wxRect & r, const ViewInfo * viewInfo, bool drawEnvelope, bool drawSamples, bool drawSliders, bool hasSolo)
References DrawLabelTrack(), DrawNoteTrack(), DrawSpectrum(), DrawTimeTrack(), DrawWaveform(), WaveTrack::GetClipIterator(), WaveTrack::GetDisplay(), Track::GetKind(), Track::GetMute(), Track::GetSolo(), Track::Label, Track::Note, WaveTrack::PitchDisplay, WaveTrack::SpectrumDisplay, WaveTrack::SpectrumLogDisplay, Track::Time, Track::Wave, WaveTrack::WaveformDBDisplay, and WaveTrack::WaveformDisplay.
Referenced by DrawTracks(), and AudacityPrintout::OnPrintPage().
void TrackArtist::DrawTracks (TrackList * tracks, Track * start, wxDC & dc, wxRegion & reg, wxRect & r, wxRect & clip, ViewInfo * viewInfo, bool drawEnvelope, bool drawSamples, bool drawSliders)
References DrawTrack(), TrackListIterator::First(), Track::GetHeight(), Track::GetLink(), Track::GetLinked(), Track::GetSolo(), Track::GetY(), mInsetBottom, mInsetLeft, mInsetRight, mInsetTop, TrackListIterator::Next(), TrackListIterator::StartWith(), and ViewInfo::vpos.
Referenced by TrackPanel::DrawTracks().
void TrackArtist::DrawVRuler (Track * t, wxDC * dc, wxRect & r)
References AColor::BevelTrackInfo(), blackPos, Ruler::Draw(), Track::GetKind(), Track::Label, AColor::Line(), Track::Note, notePos, octaveHeight, WaveTrack::PitchDisplay, Track::Time, UpdateVRuler(), vruler, Track::vrulerSize, Track::Wave, and whitePos.
Referenced by TrackPanel::DrawEverythingElse().
void TrackArtist::DrawWaveform (WaveTrack * track, wxDC & dc, const wxRect & r, const ViewInfo * viewInfo, bool drawEnvelope, bool drawSamples, bool drawSliders, bool dB, bool muted) [private]
References blankBrush, DrawClipWaveform(), WaveTrack::GetCachedLocation(), WaveTrack::GetClipIterator(), WaveTrack::GetNumCachedLocations(), AColor::Line(), WaveTrack::locationCutLine, WaveTrack::Location::pos, WaveTrack::Location::typ, and WaveTrack::UpdateLocationsCache().
Referenced by DrawSpectrum(), and DrawTrack().
void TrackArtist::DrawWaveformBackground (wxDC & dc, const wxRect & r, const double env[], float zoomMin, float zoomMax, bool dB, const sampleCount where[], sampleCount ssel0, sampleCount ssel1, bool drawEnvelope, bool synchroSelection) [private]
References blankBrush, DrawLinkTiles(), GetWaveYPos(), AColor::Line(), mdBrange, selectedBrush, syncSelBrush, and unselectedBrush.
Referenced by DrawClipWaveform().
int TrackArtist::GetSpectrumLogMaxFreq (int deffreq)
References mLogMaxFreq.
Referenced by DrawClipSpectrum(), TrackPanel::HandleVZoomButtonUp(), and UpdateVRuler().
int TrackArtist::GetSpectrumLogMinFreq (int deffreq)
References mLogMinFreq.
Referenced by DrawClipSpectrum(), TrackPanel::HandleVZoomButtonUp(), and UpdateVRuler().
int TrackArtist::GetSpectrumMaxFreq (int deffreq)
References mMaxFreq.
Referenced by DrawClipSpectrum(), TrackPanel::HandleVZoomButtonUp(), and UpdateVRuler().
int TrackArtist::GetSpectrumMinFreq (int deffreq)
References mMinFreq.
Referenced by DrawClipSpectrum(), TrackPanel::HandleVZoomButtonUp(), and UpdateVRuler().
int TrackArtist::GetSpectrumWindowSize ()
References mWindowSize.
Referenced by DrawClipSpectrum(), and TrackPanel::HandleVZoomButtonUp().
void TrackArtist::InvalidateSpectrumCache (WaveTrack * track)
References WaveTrack::GetClipIterator().
void TrackArtist::InvalidateSpectrumCache (TrackList * tracks)
References TrackListCondIterator::First(), TrackListCondIterator::Next(), and Track::Wave.
Referenced by TrackPanel::HandleVZoomButtonUp(), and TrackPanel::OnSetDisplay().
void TrackArtist::SetBackgroundBrushes (wxBrush unselectedBrush, wxBrush selectedBrush, wxPen unselectedPen, wxPen selectedPen) [inline]
Referenced by AudacityPrintout::OnPrintPage().
void TrackArtist::SetColours ()
References blankBrush, blankPen, clippedPen, dragsampleBrush, muteClippedPen, muteRmsPen, muteSamplePen, odProgressDonePen, odProgressNotYetPen, rmsPen, sampleBrush, samplePen, selectedBrush, selectedPen, selsampleBrush, selsamplePen, ThemeBase::SetBrushColour(), ThemeBase::SetPenColour(), shadowPen, syncSelBrush, syncSelPen, theTheme, unselectedBrush, and unselectedPen.
Referenced by TrackArtist().
void TrackArtist::SetInset (int left, int top, int right, int bottom)
References mInsetBottom, mInsetLeft, mInsetRight, and mInsetTop.
Referenced by TrackPanel::TrackPanel().
void TrackArtist::SetSpectrumLogMaxFreq (int freq)
References mLogMaxFreq.
Referenced by TrackPanel::HandleVZoomButtonUp().
void TrackArtist::SetSpectrumLogMinFreq (int freq)
References mLogMinFreq.
Referenced by TrackPanel::HandleVZoomButtonUp().
void TrackArtist::SetSpectrumMaxFreq (int freq)
References mMaxFreq.
Referenced by TrackPanel::HandleVZoomButtonUp().
void TrackArtist::SetSpectrumMinFreq (int freq)
References mMinFreq.
Referenced by TrackPanel::HandleVZoomButtonUp().
void TrackArtist::UpdatePrefs ()
References gPrefs, mdBrange, mIsGrayscale, mLogMaxFreq, mLogMinFreq, mMaxFreq, mMinFreq, mShowClipping, and mWindowSize.
Referenced by TrackArtist(), and TrackPanel::UpdatePrefs().
void TrackArtist::UpdateVRuler (Track * t, wxRect & r)
References WaveTrack::GetDisplay(), WaveTrack::GetDisplayBounds(), Track::GetKind(), Ruler::GetMaxSize(), WaveTrack::GetRate(), GetSpectrumLogMaxFreq(), GetSpectrumLogMinFreq(), GetSpectrumMaxFreq(), GetSpectrumMinFreq(), Ruler::IntFormat, Track::Label, Ruler::LinearDBFormat, max, mdBrange, min(), Track::Note, WaveTrack::PitchDisplay, Ruler::RealFormat, Ruler::SetBounds(), Ruler::SetFormat(), Ruler::SetLabelEdges(), Ruler::SetLog(), Ruler::SetOrientation(), Ruler::SetRange(), Ruler::SetUnits(), WaveTrack::SpectrumDisplay, WaveTrack::SpectrumLogDisplay, vruler, Track::vrulerSize, Track::Wave, WaveTrack::WaveformDBDisplay, and WaveTrack::WaveformDisplay.
Referenced by DrawVRuler(), and TrackPanel::UpdateTrackVRuler().
Member Data Documentation
wxBrush TrackArtist::blankBrush [private]
Referenced by DrawNoteTrack(), DrawSpectrum(), DrawWaveform(), DrawWaveformBackground(), and SetColours().
wxPen TrackArtist::blankPen [private]
Referenced by DrawNoteTrack(), and SetColours().
wxPen TrackArtist::clippedPen [private]
Referenced by DrawIndividualSamples(), DrawMinMaxRMS(), and SetColours().
wxBrush TrackArtist::dragsampleBrush [private]
Referenced by DrawIndividualSamples(), and SetColours().
float TrackArtist::mdBrange [private]
Referenced by DrawEnvelope(), DrawIndividualSamples(), DrawMinMaxRMS(), DrawWaveformBackground(), TrackArtist(), UpdatePrefs(), and UpdateVRuler().
int TrackArtist::mInsetBottom [private]
Referenced by DrawTracks(), SetInset(), and TrackArtist().
int TrackArtist::mInsetLeft [private]
Referenced by DrawTracks(), SetInset(), and TrackArtist().
int TrackArtist::mInsetRight [private]
Referenced by DrawTracks(), SetInset(), and TrackArtist().
int TrackArtist::mInsetTop [private]
Referenced by DrawTracks(), SetInset(), and TrackArtist().
bool TrackArtist::mIsGrayscale [private]
Referenced by DrawClipSpectrum(), and UpdatePrefs().
int TrackArtist::mLogMaxFreq [private]
Referenced by GetSpectrumLogMaxFreq(), SetSpectrumLogMaxFreq(), and UpdatePrefs().
int TrackArtist::mLogMinFreq [private]
Referenced by GetSpectrumLogMinFreq(), SetSpectrumLogMinFreq(), and UpdatePrefs().
int TrackArtist::mMaxFreq [private]
Referenced by GetSpectrumMaxFreq(), SetSpectrumMaxFreq(), and UpdatePrefs().
int TrackArtist::mMinFreq [private]
Referenced by GetSpectrumMinFreq(), SetSpectrumMinFreq(), and UpdatePrefs().
long TrackArtist::mShowClipping [private]
Referenced by DrawIndividualSamples(), DrawMinMaxRMS(), TrackArtist(), and UpdatePrefs().
wxPen TrackArtist::muteClippedPen [private]
Referenced by DrawIndividualSamples(), DrawMinMaxRMS(), and SetColours().
wxPen TrackArtist::muteRmsPen [private]
Referenced by DrawMinMaxRMS(), and SetColours().
wxBrush TrackArtist::muteSampleBrush [private]
wxPen TrackArtist::muteSamplePen [private]
Referenced by DrawIndividualSamples(), DrawMinMaxRMS(), and SetColours().
int TrackArtist::mWindowSize [private]
Referenced by GetSpectrumWindowSize(), and UpdatePrefs().
wxPen TrackArtist::odProgressDonePen [private]
Referenced by SetColours().
wxPen TrackArtist::odProgressNotYetPen [private]
Referenced by SetColours().
wxPen TrackArtist::rmsPen [private]
Referenced by DrawMinMaxRMS(), and SetColours().
wxBrush TrackArtist::sampleBrush [private]
Referenced by DrawIndividualSamples(), and SetColours().
wxPen TrackArtist::samplePen [private]
Referenced by DrawIndividualSamples(), DrawMinMaxRMS(), and SetColours().
wxBrush TrackArtist::selectedBrush [private]
Referenced by DrawWaveformBackground(), and SetColours().
wxPen TrackArtist::selectedPen [private]
Referenced by SetColours().
wxBrush TrackArtist::selsampleBrush [private]
Referenced by SetColours().
wxPen TrackArtist::selsamplePen [private]
Referenced by SetColours().
wxPen TrackArtist::shadowPen [private]
Referenced by SetColours().
wxBrush TrackArtist::syncSelBrush [private]
Referenced by DrawWaveformBackground(), and SetColours().
wxPen TrackArtist::syncSelPen [private]
Referenced by SetColours().
wxBrush TrackArtist::unselectedBrush [private]
Referenced by DrawWaveformBackground(), and SetColours().
wxPen TrackArtist::unselectedPen [private]
Referenced by SetColours().
Ruler* TrackArtist::vruler [private]
Referenced by DrawVRuler(), TrackArtist(), UpdateVRuler(), and ~TrackArtist().
The documentation for this class was generated from the following files:
TrackArtist.h
TrackArtist.cpp