Audacity: SpectrumPrefs Class Reference
SpectrumPrefs Class Reference
A PrefsPanel for spectrum settings.
#include <SpectrumPrefs.h>
Public Member Functions
SpectrumPrefs (wxWindow *parent)
virtual ~SpectrumPrefs ()
virtual bool Apply ()
virtual bool Validate ()
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
Private Attributes
wxTextCtrl * mMinFreq
wxTextCtrl * mMaxFreq
wxTextCtrl * mGain
wxTextCtrl * mRange
wxTextCtrl * mFrequencyGain
wxArrayString mSizeChoices
wxArrayInt mSizeCodes
wxArrayString mTypeChoices
wxArrayInt mTypeCodes
Detailed Description
A PrefsPanel for spectrum settings.
Constructor & Destructor Documentation
SpectrumPrefs::SpectrumPrefs (wxWindow * parent)
References Populate().
SpectrumPrefs::~SpectrumPrefs () [virtual]
Member Function Documentation
bool SpectrumPrefs::Apply () [virtual]
Implements PrefsPanel.
References eIsSavingToPrefs, and PopulateOrExchange().
void SpectrumPrefs::Populate () [private]
References eIsCreatingFromPrefs, mSizeChoices, mSizeCodes, mTypeChoices, mTypeCodes, NumWindowFuncs(), PopulateOrExchange(), and WindowFuncName().
Referenced by SpectrumPrefs().
void SpectrumPrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndTwoColumn(), mFrequencyGain, mGain, mMaxFreq, mMinFreq, mRange, mSizeChoices, mSizeCodes, mTypeChoices, mTypeCodes, ShuttleGuiBase::SetBorder(), ShuttleGui::SetSizeHints(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartTwoColumn(), ShuttleGuiBase::TieCheckBox(), ShuttleGuiBase::TieChoice(), and ShuttleGuiBase::TieTextBox().
Referenced by Apply(), and Populate().
bool SpectrumPrefs::Validate () [virtual]
References mFrequencyGain, mGain, mMaxFreq, mMinFreq, and mRange.
Member Data Documentation
wxTextCtrl* SpectrumPrefs::mFrequencyGain [private]
Referenced by PopulateOrExchange(), and Validate().
wxTextCtrl* SpectrumPrefs::mGain [private]
Referenced by PopulateOrExchange(), and Validate().
wxTextCtrl* SpectrumPrefs::mMaxFreq [private]
Referenced by PopulateOrExchange(), and Validate().
wxTextCtrl* SpectrumPrefs::mMinFreq [private]
Referenced by PopulateOrExchange(), and Validate().
wxTextCtrl* SpectrumPrefs::mRange [private]
Referenced by PopulateOrExchange(), and Validate().
wxArrayString SpectrumPrefs::mSizeChoices [private]
Referenced by Populate(), and PopulateOrExchange().
wxArrayInt SpectrumPrefs::mSizeCodes [private]
Referenced by Populate(), and PopulateOrExchange().
wxArrayString SpectrumPrefs::mTypeChoices [private]
Referenced by Populate(), and PopulateOrExchange().
wxArrayInt SpectrumPrefs::mTypeCodes [private]
Referenced by Populate(), and PopulateOrExchange().
The documentation for this class was generated from the following files:
SpectrumPrefs.h
SpectrumPrefs.cpp