Audacity: TruncSilenceDialog Class Reference
TruncSilenceDialog Class Reference
Dialog used with EffectTruncSilence.
#include <TruncSilence.h>
Public Member Functions
TruncSilenceDialog (EffectTruncSilence *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
void OnPreview (wxCommandEvent &event)
void OnDurationChange (wxCommandEvent &event)
Private Attributes
EffectTruncSilence * mEffect
wxStaticText * pWarning
wxStaticText * mRatioLabel
wxSlider * mRatioSlider
wxStaticText * mRatioText
Detailed Description
Dialog used with EffectTruncSilence.
Constructor & Destructor Documentation
TruncSilenceDialog::TruncSilenceDialog (EffectTruncSilence * effect, wxWindow * parent)
Member Function Documentation
void TruncSilenceDialog::OnDurationChange (wxCommandEvent & event)
References ID_EFFECT_PREVIEW, mEffect, EffectTruncSilence::mSilenceCompressRatio, EffectTruncSilence::mTruncInitialAllowedSilentMs, EffectTruncSilence::mTruncLongestAllowedSilentMs, pWarning, and EffectDialog::TransferDataFromWindow().
void TruncSilenceDialog::OnPreview (wxCommandEvent & event) [virtual]
Reimplemented from EffectDialog.
References mEffect, Effect::Preview(), and EffectDialog::TransferDataFromWindow().
void TruncSilenceDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddUnits(), ShuttleGuiBase::AddVariableText(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndTwoColumn(), Enums::GetDbChoices(), ShuttleGui::Id(), ID_COMPRESS_FACTOR, ID_LONGEST_SILENCE_TEXT, ID_SHORTEST_SILENCE_TEXT, mEffect, EffectTruncSilence::mSilenceCompressRatio, EffectTruncSilence::mTruncDbChoiceIndex, EffectTruncSilence::mTruncInitialAllowedSilentMs, EffectTruncSilence::mTruncLongestAllowedSilentMs, Enums::NumDbChoices, pWarning, ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartThreeColumn(), ShuttleGuiBase::TieChoice(), and ShuttleGuiBase::TieTextBox().
Member Data Documentation
EffectTruncSilence* TruncSilenceDialog::mEffect [private]
Referenced by OnDurationChange(), OnPreview(), and PopulateOrExchange().
wxStaticText* TruncSilenceDialog::mRatioLabel [private]
wxSlider* TruncSilenceDialog::mRatioSlider [private]
wxStaticText* TruncSilenceDialog::mRatioText [private]
wxStaticText* TruncSilenceDialog::pWarning [private]
Referenced by OnDurationChange(), and PopulateOrExchange().
The documentation for this class was generated from the following files:
TruncSilence.h
TruncSilence.cpp