Audacity: ODTask Class Reference
ODTask Class Reference
A class representing a modular task to be used with the On-Demand structures.
#include <ODTask.h>
Public Types
enum {
eODNone = 0x00000000, eODFLAC = 0x00000001, eODMP3 = 0x00000002, eODFFMPEG = 0x00000004,
eODPCMSummary = 0x00001000, eODOTHER = 0x10000000
}
Public Member Functions
ODTask ()
Constructs an ODTask.
virtual ~ODTask ()
virtual ODTask * Clone ()=0
virtual unsigned int GetODType ()
Subclasses should override to return respective type.
void DoSome (float amountWork=0.0)
void DoAll ()
Call DoSome until PercentComplete >= 1.0.
virtual float PercentComplete ()
return the amount of the task that has been completed. 0.0 to 1.0
virtual bool UsesCustomWorkUntilPercentage ()
virtual float ComputeNextWorkUntilPercentageComplete ()
virtual bool CanMergeWith (ODTask *otherTask)
virtual void StopUsingWaveTrack (WaveTrack *track)
virtual void ReplaceWaveTrack (WaveTrack *oldTrack, WaveTrack *newTrack)
Replaces all instances to a wavetrack with a new one, effectively transferring the task.
void AddWaveTrack (WaveTrack *track)
Adds a WaveTrack to do the task for.
virtual int GetNumWaveTracks ()
virtual WaveTrack * GetWaveTrack (int i)
virtual void DemandTrackUpdate (WaveTrack *track, double seconds)
changes the tasks associated with this Waveform to process the task from a different point in the track
bool IsComplete ()
return
void TerminateAndBlock ()
virtual void Terminate ()
releases memory that the ODTask owns. Subclasses should override.
virtual const char * GetTaskName ()
virtual sampleCount GetDemandSample ()
virtual void SetDemandSample (sampleCount sample)
virtual void RecalculatePercentComplete ()
does an od update and then recalculates the data.
int GetTaskNumber ()
returns the number of tasks created before this instance.
void SetNeedsODUpdate ()
bool GetNeedsODUpdate ()
void ResetNeedsODUpdate ()
virtual const wxChar * GetTip ()=0
virtual bool IsTaskAssociatedWithProject (AudacityProject *proj)
returns true if the task is associated with the project.
bool IsRunning ()
Public Attributes
enum ODTask:: { ... } ODTypeEnum
Protected Member Functions
virtual void CalculatePercentComplete ()=0
calculates the percentage complete from existing data.
virtual void DoSomeInternal ()=0
virtual void Update ()
virtual method called before DoSomeInternal is used from DoSome.
virtual void ODUpdate ()
void SetIsRunning (bool value)
Protected Attributes
int mTaskNumber
float mPercentComplete
ODLock mPercentCompleteMutex
bool mDoingTask
bool mTaskStarted
bool mTerminate
ODLock mTerminateMutex
ODLock mBlockUntilTerminateMutex
std::vector< WaveTrack * > mWaveTracks
ODLock mWaveTrackMutex
sampleCount mDemandSample
ODLock mDemandSampleMutex
bool mIsRunning
ODLock mIsRunningMutex
Private Attributes
bool mNeedsODUpdate
ODLock mNeedsODUpdateMutex
Detailed Description
A class representing a modular task to be used with the On-Demand structures.
ODTask is an abstract class that outlines the methods that will be used to support On-Demand background loading of files. These ODTasks are generally meant to be run in a background thread.
Member Enumeration Documentation
anonymous enum
Enumerator:
eODNone
eODFLAC
eODMP3
eODFFMPEG
eODPCMSummary
eODOTHER
Constructor & Destructor Documentation
ODTask::ODTask ()
Constructs an ODTask.
References mDemandSample, mDoingTask, mIsRunning, mNeedsODUpdate, mPercentComplete, mTaskNumber, and mTerminate.
virtual ODTask::~ODTask () [inline, virtual]
Member Function Documentation
void ODTask::AddWaveTrack (WaveTrack * track)
Adds a WaveTrack to do the task for.
Sets the wavetrack that will be analyzed for ODPCMAliasBlockFiles that will have their summaries computed and written to disk.
References mWaveTracks.
Referenced by PCMImportFileHandle::Import(), FLACImportFileHandle::Import(), ODWaveTrackTaskQueue::MakeWaveTrackIndependent(), AudacityProject::OpenFile(), and AudacityProject::PopState().
virtual void ODTask::CalculatePercentComplete () [protected, pure virtual]
calculates the percentage complete from existing data.
Implemented in ODComputeSummaryTask, and ODDecodeTask.
Referenced by RecalculatePercentComplete().
virtual bool ODTask::CanMergeWith (ODTask * otherTask) [inline, virtual]
returns whether or not this task and another task can merge together, as when we make two mono tracks stereo. for Loading/Summarizing, this is not an issue because the entire track is processed Effects that affect portions of a track will need to check this.
References GetTaskName().
virtual ODTask* ODTask::Clone () [pure virtual]
Implemented in ODComputeSummaryTask, ODDecodeFlacTask, and ODDecodeTask.
virtual float ODTask::ComputeNextWorkUntilPercentageComplete () [inline, virtual]
Reimplemented in ODComputeSummaryTask.
Referenced by DoSome().
void ODTask::DemandTrackUpdate (WaveTrack * track, double seconds) [virtual]
changes the tasks associated with this Waveform to process the task from a different point in the track
changes the tasks associated with this Waveform to process the task from a different point in the track
Parameters:
track the track to update
seconds the point in the track from which the tasks associated with track should begin processing from.
References GetDemandSample(), WaveTrack::GetRate(), mWaveTrackMutex, mWaveTracks, SetDemandSample(), and SetNeedsODUpdate().
void ODTask::DoAll ()
Call DoSome until PercentComplete >= 1.0.
void ODTask::DoSome (float amountWork = 0.0)
Do a modular part of the task. For example, if the task is to load the entire file, load one BlockFile. Relies on DoSomeInternal(), which is the subclasses must implement.
Parameters:
amountWork the percent amount of the total job to do. 1.0 represents the entire job. the default of 0.0 will do the smallest unit of work possible
References ODManager::AddTask(), AudacityProject::AllProjectsDeleteLock(), AudacityProject::AllProjectsDeleteUnlock(), ComputeNextWorkUntilPercentageComplete(), DoSomeInternal(), gAudacityProjects, GetNeedsODUpdate(), ODManager::Instance(), IsTaskAssociatedWithProject(), mBlockUntilTerminateMutex, mDoingTask, mTaskStarted, mTerminate, mTerminateMutex, ODUpdate(), PercentComplete(), SetIsRunning(), Update(), and UsesCustomWorkUntilPercentage().
virtual void ODTask::DoSomeInternal () [protected, pure virtual]
pure virtual function that does some part of the task this object represents. this function is meant to be called repeatedly until the IsComplete is true. Does the smallest unit of work for this task.
Implemented in ODComputeSummaryTask, and ODDecodeTask.
Referenced by DoSome().
sampleCount ODTask::GetDemandSample () [virtual]
References mDemandSample, and mDemandSampleMutex.
Referenced by ODDecodeFlacTask::Clone(), ODComputeSummaryTask::Clone(), DemandTrackUpdate(), ODDecodeTask::OrderBlockFiles(), and ODComputeSummaryTask::OrderBlockFiles().
bool ODTask::GetNeedsODUpdate ()
References mNeedsODUpdate, and mNeedsODUpdateMutex.
Referenced by DoSome(), and RecalculatePercentComplete().
int ODTask::GetNumWaveTracks () [virtual]
References mWaveTrackMutex, and mWaveTracks.
Referenced by ODWaveTrackTaskQueue::AddTask().
virtual unsigned int ODTask::GetODType () [inline, virtual]
Subclasses should override to return respective type.
Reimplemented in ODComputeSummaryTask, ODDecodeFlacTask, and ODDecodeTask.
virtual const char* ODTask::GetTaskName () [inline, virtual]
Reimplemented in ODComputeSummaryTask, and ODDecodeTask.
Referenced by CanMergeWith().
int ODTask::GetTaskNumber () [inline]
returns the number of tasks created before this instance.
virtual const wxChar* ODTask::GetTip () [pure virtual]
Implemented in ODComputeSummaryTask, and ODDecodeTask.
WaveTrack * ODTask::GetWaveTrack (int i) [virtual]
References mWaveTrackMutex, and mWaveTracks.
Referenced by ODManager::AddNewTask(), and ODWaveTrackTaskQueue::AddTask().
bool ODTask::IsComplete ()
return
References IsRunning(), and PercentComplete().
bool ODTask::IsRunning ()
References mIsRunning, and mIsRunningMutex.
Referenced by IsComplete().
bool ODTask::IsTaskAssociatedWithProject (AudacityProject * proj) [virtual]
returns true if the task is associated with the project.
References TrackListIterator::First(), Track::GetKind(), AudacityProject::GetTracks(), mWaveTrackMutex, mWaveTracks, TrackListIterator::Next(), and Track::Wave.
Referenced by DoSome().
void ODTask::ODUpdate () [protected, virtual]
virtual method called in DoSome everytime the user has demanded some OD function so that the ODTask can readjust its computation order. By default just calls Update(), but subclasses with special needs can override this
Reimplemented in ODComputeSummaryTask, and ODDecodeTask.
References ResetNeedsODUpdate(), and Update().
Referenced by DoSome(), and RecalculatePercentComplete().
float ODTask::PercentComplete () [virtual]
return the amount of the task that has been completed. 0.0 to 1.0
References mPercentComplete, and mPercentCompleteMutex.
Referenced by DoSome(), and IsComplete().
void ODTask::RecalculatePercentComplete () [virtual]
does an od update and then recalculates the data.
References CalculatePercentComplete(), GetNeedsODUpdate(), and ODUpdate().
void ODTask::ReplaceWaveTrack (WaveTrack * oldTrack, WaveTrack * newTrack) [virtual]
Replaces all instances to a wavetrack with a new one, effectively transferring the task.
Replaces all instances to a wavetrack with a new one, effectively transferring the task. ODTask has no wavetrack, so it does nothing. But subclasses that do should override this.
References mWaveTrackMutex, and mWaveTracks.
void ODTask::ResetNeedsODUpdate ()
References mNeedsODUpdate, and mNeedsODUpdateMutex.
Referenced by ODUpdate().
void ODTask::SetDemandSample (sampleCount sample) [virtual]
References mDemandSample, and mDemandSampleMutex.
Referenced by DemandTrackUpdate().
void ODTask::SetIsRunning (bool value) [protected]
References mIsRunning, and mIsRunningMutex.
Referenced by DoSome().
void ODTask::SetNeedsODUpdate ()
References mNeedsODUpdate, and mNeedsODUpdateMutex.
Referenced by DemandTrackUpdate().
void ODTask::StopUsingWaveTrack (WaveTrack * track) [virtual]
References mWaveTrackMutex, and mWaveTracks.
virtual void ODTask::Terminate () [inline, virtual]
releases memory that the ODTask owns. Subclasses should override.
Reimplemented in ODComputeSummaryTask.
Referenced by TerminateAndBlock().
void ODTask::TerminateAndBlock ()
References mBlockUntilTerminateMutex, mTerminate, mTerminateMutex, and Terminate().
virtual void ODTask::Update () [inline, protected, virtual]
virtual method called before DoSomeInternal is used from DoSome.
Reimplemented in ODComputeSummaryTask, and ODDecodeTask.
Referenced by DoSome(), and ODUpdate().
virtual bool ODTask::UsesCustomWorkUntilPercentage () [inline, virtual]
Reimplemented in ODComputeSummaryTask.
Referenced by DoSome().
Member Data Documentation
ODLock ODTask::mBlockUntilTerminateMutex [protected]
Referenced by DoSome(), and TerminateAndBlock().
sampleCount ODTask::mDemandSample [protected]
Referenced by ODDecodeFlacTask::Clone(), ODComputeSummaryTask::Clone(), GetDemandSample(), ODTask(), and SetDemandSample().
ODLock ODTask::mDemandSampleMutex [protected]
Referenced by GetDemandSample(), and SetDemandSample().
bool ODTask::mDoingTask [protected]
Referenced by DoSome(), and ODTask().
bool ODTask::mIsRunning [protected]
Referenced by IsRunning(), ODTask(), and SetIsRunning().
ODLock ODTask::mIsRunningMutex [protected]
Referenced by IsRunning(), and SetIsRunning().
bool ODTask::mNeedsODUpdate [private]
Referenced by GetNeedsODUpdate(), ODTask(), ResetNeedsODUpdate(), and SetNeedsODUpdate().
ODLock ODTask::mNeedsODUpdateMutex [private]
Referenced by GetNeedsODUpdate(), ResetNeedsODUpdate(), and SetNeedsODUpdate().
float ODTask::mPercentComplete [protected]
Referenced by ODDecodeTask::CalculatePercentComplete(), ODComputeSummaryTask::CalculatePercentComplete(), ODComputeSummaryTask::ComputeNextWorkUntilPercentageComplete(), ODDecodeTask::DoSomeInternal(), ODComputeSummaryTask::DoSomeInternal(), ODTask(), and PercentComplete().
ODLock ODTask::mPercentCompleteMutex [protected]
Referenced by ODDecodeTask::CalculatePercentComplete(), ODComputeSummaryTask::CalculatePercentComplete(), ODComputeSummaryTask::ComputeNextWorkUntilPercentageComplete(), ODDecodeTask::DoSomeInternal(), ODComputeSummaryTask::DoSomeInternal(), and PercentComplete().
int ODTask::mTaskNumber [protected]
Referenced by ODTask().
bool ODTask::mTaskStarted [protected]
Referenced by DoSome().
bool ODTask::mTerminate [protected]
Referenced by DoSome(), ODTask(), and TerminateAndBlock().
ODLock ODTask::mTerminateMutex [protected]
Referenced by DoSome(), and TerminateAndBlock().
ODLock ODTask::mWaveTrackMutex [protected]
Referenced by DemandTrackUpdate(), ODDecodeTask::DoSomeInternal(), ODComputeSummaryTask::DoSomeInternal(), GetNumWaveTracks(), GetWaveTrack(), IsTaskAssociatedWithProject(), ReplaceWaveTrack(), StopUsingWaveTrack(), ODDecodeTask::Update(), and ODComputeSummaryTask::Update().
std::vector<WaveTrack*> ODTask::mWaveTracks [protected]
Referenced by AddWaveTrack(), DemandTrackUpdate(), ODDecodeTask::DoSomeInternal(), ODComputeSummaryTask::DoSomeInternal(), GetNumWaveTracks(), GetWaveTrack(), IsTaskAssociatedWithProject(), ReplaceWaveTrack(), StopUsingWaveTrack(), ODDecodeTask::Update(), and ODComputeSummaryTask::Update().
enum { ... } ODTask::ODTypeEnum
The documentation for this class was generated from the following files:
ODTask.h
ODTask.cpp