#!/bin/sh

if [ ! -d libiconv* -o ! -d wxWidgets* -o ! -d audacity ]
then
   cat <<EOF

You do not have the build directory setup correctly.  You should have
a structure that looks like this (as an example):

   .
   ..
   audacity
   libiconv-1.11
   wxWidgets-2.4.5 (+ patches in audacity/mac subdirectory)

And you should execute this script like this:

   audacity/scripts/mac_release_build

This will build libiconv first, then wxMac, and finally Audacity using options
that will allow Audacity to run on OS X 10.2.8+.

The final DMG files will reside in this directory.

EOF
   exit 1
fi

echo "Selecting gcc 3.3...requires root access...enter password when prompted"
echo 
sudo gcc_select 3.3

top=$(pwd)

export MACOSX_DEPLOYMENT_TARGET=10.2
export NEXT_ROOT="/Developer/SDKs/MacOSX10.2.8.sdk"
export C_INCLUDE_PATH="$top /Developer/SDKs/MacOSX10.2.8.sdk/usr/include"
export LIBRARY_PATH="$top /Developer/SDKs/MacOSX10.2.8.sdk/usr/lib/gcc/darwin/3.3"
export LD_PREBIND=1
export CPPFLAGS='-DMAC_OS_X_VERSION_MAX_ALLOWED=1020'
export CFLAGS='-DMAC_OS_X_VERSION_MAX_ALLOWED=1020'

#
# Build libiconv
#
if [ ! -f include/iconv.h ]
then
   cd libiconv*

   ./configure --prefix=$top --enable-static=yes --enable-shared=no --disable-shared
   if [ $? -ne 0 ]
   then
      exit 1
   fi

   make -j 4 
   if [ $? -ne 0 ]
   then
      exit 1
   fi

   make install
   if [ $? -ne 0 ]
   then
      exit 1
   fi

   make distclean
   cd $top
fi

#
# Build wxMac ANSI version
#
if [ ! -f lib/libwx_mac-2.4.a ]
then
   cd wxWidgets*
   mkdir bld
   cd bld

   ../configure --prefix=$top --with-libiconv-prefix=$top --enable-static=yes --enable-shared=no --enable-unicode=no
   if [ $? -ne 0 ]
   then
      exit 1
   fi

   make -j 4
   if [ $? -ne 0 ]
   then
      exit 1
   fi

   make install
   if [ $? -ne 0 ]
   then
      exit 1
   fi

   cd ..
   rm -rf bld

   cd $top
fi

#
# Build Audacity ANSI version
#
cd audacity
export NEXT_ROOT="/Developer/SDKs/MacOSX10.2.8.sdk"
export PATH="$top/bin:$PATH"

./configure --enable-static=yes --enable-shared=no --enable-unicode=no --enable-flac
if [ $? -ne 0 ]
then
   exit 1
fi

sed -e "s#-liconv#$top/lib/libiconv.a#" src/Makefile >src/Makefilex
mv src/Makefilex src/Makefile

make
if [ $? -ne 0 ]
then
   exit 1
fi

unset NEXT_ROOT
scripts/mkdmg -test ppc
mv *.dmg ..

make distclean

cd $top

#
# Change gcc back
#
sudo gcc_select 4.0
