Audacity: AudioUnitEffect.cpp File Reference
AudioUnitEffect.cpp File Reference
#include "AudioUnitEffect.h"
#include <wx/defs.h>
#include <wx/button.h>
#include <wx/control.h>
#include <wx/frame.h>
#include <wx/panel.h>
#include <wx/sizer.h>
#include <wx/settings.h>
#include <wx/tokenzr.h>
#include <wx/mac/private.h>
Classes
class AudioUnitGUIControl
Used with AudioUnitEffect.
class AudioUnitDialog
A Dialog used with AudioUnitEffect.
Enumerations
enum { PreviewID = 1 }
Functions
static pascal OSStatus EventHandler (EventHandlerCallRef handler, EventRef event, void *data)
void EventListener (void *inUserData, AudioUnitCarbonView inView, const AudioUnitParameter *inParameter, AudioUnitCarbonViewEventID inEvent, const void *inEventParam)
Variables
static const EventTypeSpec eventList []
Enumeration Type Documentation
anonymous enum
Enumerator:
PreviewID
Function Documentation
static pascal OSStatus EventHandler (EventHandlerCallRef handler, EventRef event, void * data) [static]
References AudioUnitDialog::RemoveHandler().
Referenced by AudioUnitDialog::AudioUnitDialog().
void EventListener (void * inUserData, AudioUnitCarbonView inView, const AudioUnitParameter * inParameter, AudioUnitCarbonViewEventID inEvent, const void * inEventParam)
Referenced by AudioUnitDialog::AudioUnitDialog().
Variable Documentation
const EventTypeSpec eventList[] [static]
Initial value:
{
   {kEventClassWindow, kEventWindowClose},
}