Audacity: Legacy.cpp File Reference
Legacy.cpp File Reference
Converts old Audacity file types. Implements AutoRollbackRenamer.
#include "Audacity.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wx/defs.h>
#include <wx/ffile.h>
#include <wx/filefn.h>
#include <wx/intl.h>
#include <wx/msgdlg.h>
#include <wx/string.h>
#include <wx/textfile.h>
#include "Internat.h"
#include "Legacy.h"
#include "xml/XMLWriter.h"
Classes
class AutoRollbackRenamer
AutoRollbackRenamer handles the renaming of files which is needed when producing a new version of a file which may fail. On failure the old version is put back in place.
Functions
bool ConvertLegacyTrack (wxTextFile *f, XMLFileWriter &xmlFile)
bool ConvertLegacyProjectFile (wxFileName filename)
Detailed Description
Converts old Audacity file types. Implements AutoRollbackRenamer.
These routines convert Audacity project files from the 0.98...1.0 format into an XML format that's compatible with Audacity 1.2.0 and newer.
Function Documentation
bool ConvertLegacyProjectFile (wxFileName filename)
References AUDACITY_VERSION_STRING, XMLFileWriter::Close(), ConvertLegacyTrack(), XMLWriter::EndTag(), label, name, XMLFileWriter::Open(), XMLWriter::StartTag(), XMLFileWriter::Write(), and XMLWriter::WriteAttr().
Referenced by AudacityProject::OpenFile().
bool ConvertLegacyTrack (wxTextFile * f, XMLFileWriter & xmlFile)
References XMLWriter::EndTag(), name, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
Referenced by ConvertLegacyProjectFile().