Audacity: LinkingHtmlWindow.cpp File Reference
LinkingHtmlWindow.cpp File Reference
#include <wx/wxprec.h>
#include "../Audacity.h"
#include <wx/mimetype.h>
#include <wx/filename.h>
#include "LinkingHtmlWindow.h"
#include "../HelpText.h"
#include "../FileNames.h"
#include "ErrorDialog.h"
Functions
void OpenInDefaultBrowser (const wxHtmlLinkInfo &link)
Function Documentation
void OpenInDefaultBrowser (const wxHtmlLinkInfo & link)
Referenced by FindFFmpegDialog::OnDownload(), FindDialog::OnDownload(), LibraryPrefs::OnFFmpegDownButton(), ContrastDialog::OnGetURL(), ErrorDialog::OnHelp(), LinkingHtmlWindow::OnLinkClicked(), LibraryPrefs::OnMP3DownButton(), and ShowHelpDialog().