Audacity: LoadNyquist.cpp File Reference
LoadNyquist.cpp File Reference
#include <wx/defs.h>
#include <wx/filefn.h>
#include <wx/list.h>
#include <wx/log.h>
#include <wx/string.h>
#include "../../Audacity.h"
#include "../../AudacityApp.h"
#include "../EffectManager.h"
#include "Nyquist.h"
Functions
void LoadNyquistEffect (wxString fname)
void LoadNyquistPlugins ()
Function Documentation
void LoadNyquistEffect (wxString fname)
References EffectManager::Get(), EffectNyquist::LoadedNyFile(), and EffectManager::RegisterEffect().
Referenced by LoadNyquistPlugins().
void LoadNyquistPlugins ()
References AudacityApp::AddUniquePathToPathList(), AudacityApp::audacityPathList, AudacityApp::FindFilesInPathList(), EffectManager::Get(), LoadNyquistEffect(), EffectManager::RegisterEffect(), and wxGetApp().
Referenced by LoadEffects().