Audacity: Matrix.h File Reference
Matrix.h File Reference
General routine to interpolate (or even extrapolate small amounts) audio when a few of the samples are bad. Works great for a few dozen bad samples, but not so well with hundreds. Uses the least-squares autoregression (LSAR) algorithm, as described in:.
Classes
class Vector
Holds a matrix of doubles and supports arithmetic operations, including Vector-Matrix operations. Used by InterpolateAudio.
class Matrix
Holds a matrix of doubles and supports arithmetic, subsetting, and matrix inversion. Used by InterpolateAudio.
Functions
bool InvertMatrix (const Matrix &input, Matrix &Minv)
Matrix TransposeMatrix (const Matrix &M)
Matrix IdentityMatrix (int N)
Vector operator+ (const Vector &left, const Vector &right)
Vector operator- (const Vector &left, const Vector &right)
Vector operator* (const Vector &left, const Vector &right)
Vector operator* (const Vector &left, double right)
Vector VectorSubset (const Vector &other, int start, int len)
Vector VectorConcatenate (const Vector &left, const Vector &right)
Vector operator* (const Vector &left, const Matrix &right)
Vector operator* (const Matrix &left, const Vector &right)
Matrix operator+ (const Matrix &left, const Matrix &right)
Matrix operator* (const Matrix &left, const double right)
Matrix ScalarMultiply (const Matrix &left, const Matrix &right)
Matrix MatrixMultiply (const Matrix &left, const Matrix &right)
Matrix MatrixSubset (const Matrix &M, int startRow, int numRows, int startCol, int numCols)
Matrix MatrixConcatenateCols (const Matrix &left, const Matrix &right)
Detailed Description
General routine to interpolate (or even extrapolate small amounts) audio when a few of the samples are bad. Works great for a few dozen bad samples, but not so well with hundreds. Uses the least-squares autoregression (LSAR) algorithm, as described in:.
Holds both the Matrix and Vector classes, supporting linear algebra operations, including matrix inversion. Used by InterpolateAudio.
Simon Godsill, Peter Rayner, and Olivier Cappe. Digital Audio Restoration. Berlin: Springer, 1998.
This is the same work used by Gnome Wave Cleaner (GWC), however this implementation is original.
Function Documentation
Matrix IdentityMatrix (int N)
Referenced by InvertMatrix().
bool InvertMatrix (const Matrix & input, Matrix & Minv)
References Matrix::Cols(), IdentityMatrix(), Matrix::Rows(), and Matrix::SwapRows().
Referenced by InterpolateAudio().
Matrix MatrixConcatenateCols (const Matrix & left, const Matrix & right)
References Matrix::Cols(), and Matrix::Rows().
Referenced by InterpolateAudio().
Matrix MatrixMultiply (const Matrix & left, const Matrix & right)
References Matrix::Cols(), and Matrix::Rows().
Referenced by InterpolateAudio().
Matrix MatrixSubset (const Matrix & M, int startRow, int numRows, int startCol, int numCols)
Referenced by InterpolateAudio().
Matrix operator* (const Matrix & left, const double right)
References Matrix::Cols(), and Matrix::Rows().
Vector operator* (const Matrix & left, const Vector & right)
References Matrix::Cols(), Vector::Len(), and Matrix::Rows().
Vector operator* (const Vector & left, const Matrix & right)
References Matrix::Cols(), Vector::Len(), and Matrix::Rows().
Vector operator* (const Vector & left, double right)
References Vector::Len().
Vector operator* (const Vector & left, const Vector & right)
References Vector::Len().
Matrix operator+ (const Matrix & left, const Matrix & right)
References Matrix::Cols(), and Matrix::Rows().
Vector operator+ (const Vector & left, const Vector & right)
References Vector::Len().
Vector operator- (const Vector & left, const Vector & right)
References Vector::Len().
Matrix ScalarMultiply (const Matrix & left, const Matrix & right)
References Matrix::Cols(), and Matrix::Rows().
Matrix TransposeMatrix (const Matrix & M)
References Matrix::Cols(), and Matrix::Rows().
Referenced by InterpolateAudio().
Vector VectorConcatenate (const Vector & left, const Vector & right)
References Vector::Len().
Referenced by InterpolateAudio().
Vector VectorSubset (const Vector & other, int start, int len)
Referenced by InterpolateAudio().