Audacity: PrefsDialog.cpp File Reference
PrefsDialog.cpp File Reference
#include "../Audacity.h"
#include <wx/defs.h>
#include <wx/button.h>
#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/font.h>
#include <wx/gdicmn.h>
#include <wx/intl.h>
#include <wx/listbox.h>
#include <wx/msgdlg.h>
#include <wx/sizer.h>
#include <wx/listbook.h>
#include "../widgets/treebook.h"
#include "../Experimental.h"
#include "../Project.h"
#include "../Prefs.h"
#include "PrefsDialog.h"
#include "PrefsPanel.h"
#include "BatchPrefs.h"
#include "DevicePrefs.h"
#include "DirectoriesPrefs.h"
#include "EffectsPrefs.h"
#include "GUIPrefs.h"
#include "ImportExportPrefs.h"
#include "KeyConfigPrefs.h"
#include "LibraryPrefs.h"
#include "MousePrefs.h"
#include "PlaybackPrefs.h"
#include "ProjectsPrefs.h"
#include "QualityPrefs.h"
#include "RecordingPrefs.h"
#include "SpectrumPrefs.h"
#include "ThemePrefs.h"
#include "TracksPrefs.h"
#include "WarningsPrefs.h"
Functions
EVT_TREE_KEY_DOWN (wxID_ANY, PrefsDialog::OnTreeKeyDown) PrefsDialog
Function Documentation
EVT_TREE_KEY_DOWN (wxID_ANY , PrefsDialog::OnTreeKeyDown)
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddWindow(), eCancelButton, eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndVerticalLay(), eOkButton, gPrefs, ShuttleGui::Prop(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartVerticalLay().