Audacity: Spectrum.cpp File Reference
Spectrum.cpp File Reference
Functions for computing Spectra.
#include <math.h>
#include "Spectrum.h"
#include "FFT.h"
Functions
static float todB_a (const float *x)
bool ComputeSpectrum (float *data, int width, int windowSize, double rate, float *output, bool autocorrelation, int windowFunc)
Detailed Description
Functions for computing Spectra.
Function Documentation
bool ComputeSpectrum (float * data, int width, int windowSize, double rate, float * output, bool autocorrelation, int windowFunc)
References FFT(), PowerSpectrum(), RealFFT(), and WindowFunc().
Referenced by EffectChangePitch::DeduceFrequencies(), and WaveClip::GetSpectrogram().
static float todB_a (const float * x) [inline, static]