Audacity: MixerTrackCluster Class Reference
MixerTrackCluster Class Reference
#include <MixerBoard.h>
Public Member Functions
MixerTrackCluster (wxWindow *parent, MixerBoard *grandParent, AudacityProject *project, WaveTrack *pLeftTrack, WaveTrack *pRightTrack=NULL, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
virtual ~MixerTrackCluster ()
void HandleResize ()
void HandleSliderGain (const bool bWantPushState=false)
void HandleSliderPan (const bool bWantPushState=false)
void ResetMeter ()
void UpdateForStateChange ()
void UpdateName ()
void UpdateMute ()
void UpdateSolo ()
void UpdatePan ()
void UpdateGain ()
void UpdateMeter (const double t0, const double t1)
Public Attributes
WaveTrack * mLeftTrack
WaveTrack * mRightTrack
Private Member Functions
wxColour GetTrackColor ()
void HandleSelect (const bool bShiftDown)
void OnKeyEvent (wxKeyEvent &event)
void OnMouseEvent (wxMouseEvent &event)
void OnPaint (wxPaintEvent &evt)
void OnButton_MusicalInstrument (wxCommandEvent &event)
void OnSlider_Gain (wxCommandEvent &event)
void OnSlider_Pan (wxCommandEvent &event)
void OnButton_Mute (wxCommandEvent &event)
void OnButton_Solo (wxCommandEvent &event)
Private Attributes
MixerBoard * mMixerBoard
AudacityProject * mProject
wxStaticText * mStaticText_TrackName
wxBitmapButton * mBitmapButton_MusicalInstrument
AButton * mToggleButton_Mute
AButton * mToggleButton_Solo
MixerTrackSlider * mSlider_Pan
MixerTrackSlider * mSlider_Gain
Meter * mMeter
Constructor & Destructor Documentation
MixerTrackCluster::MixerTrackCluster (wxWindow * parent, MixerBoard * grandParent, AudacityProject * project, WaveTrack * pLeftTrack, WaveTrack * pRightTrack = NULL, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
References DB_SLIDER, kDoubleInset, kInset, kLeftSideStackWidth, kQuadrupleInset, kRightSideStackWidth, Meter::MixerTrackCluster, MUSICAL_INSTRUMENT_HEIGHT_AND_WIDTH, MUTE_SOLO_HEIGHT, PAN_HEIGHT, PAN_SLIDER, and TRACK_NAME_HEIGHT.
virtual MixerTrackCluster::~MixerTrackCluster () [inline, virtual]
Member Function Documentation
wxColour MixerTrackCluster::GetTrackColor () [private]
void MixerTrackCluster::HandleResize ()
References AudacityProject::IsSoloNone(), kDoubleInset, kInset, kQuadrupleInset, mMeter, mProject, mSlider_Gain, mToggleButton_Solo, MUSICAL_INSTRUMENT_HEIGHT_AND_WIDTH, MUTE_SOLO_HEIGHT, PAN_HEIGHT, and TRACK_NAME_HEIGHT.
void MixerTrackCluster::HandleSelect (const bool bShiftDown) [private]
References WaveTrack::GetEndTime(), WaveTrack::GetOffset(), AudacityProject::GetSel0(), AudacityProject::GetSel1(), Track::GetSelected(), mLeftTrack, mMixerBoard, mProject, mRightTrack, AudacityProject::mViewInfo, AudacityProject::RefreshTPTrack(), MixerBoard::RefreshTrackClusters(), ViewInfo::sel0, ViewInfo::sel1, AudacityProject::SelectNone(), and Track::SetSelected().
Referenced by OnButton_MusicalInstrument(), and OnMouseEvent().
void MixerTrackCluster::HandleSliderGain (const bool bWantPushState = false)
References ASlider::Get(), mLeftTrack, mProject, mRightTrack, mSlider_Gain, AudacityProject::RefreshTPTrack(), WaveTrack::SetGain(), and AudacityProject::TP_PushState().
Referenced by MixerTrackSlider::OnMouseEvent(), and OnSlider_Gain().
void MixerTrackCluster::HandleSliderPan (const bool bWantPushState = false)
References ASlider::Get(), mLeftTrack, mProject, mRightTrack, mSlider_Pan, AudacityProject::RefreshTPTrack(), WaveTrack::SetPan(), and AudacityProject::TP_PushState().
Referenced by MixerTrackSlider::OnMouseEvent(), and OnSlider_Pan().
void MixerTrackCluster::OnButton_MusicalInstrument (wxCommandEvent & event) [private]
References HandleSelect().
void MixerTrackCluster::OnButton_Mute (wxCommandEvent & event) [private]
References Track::GetSolo(), AudacityProject::HandleTrackMute(), AudacityProject::IsSoloSimple(), mLeftTrack, mMixerBoard, mProject, mToggleButton_Mute, AudacityProject::RedrawProject(), AudacityProject::RefreshTPTrack(), AButton::SetAlternate(), MixerBoard::UpdateSolo(), and AButton::WasShiftDown().
void MixerTrackCluster::OnButton_Solo (wxCommandEvent & event) [private]
References Track::GetSolo(), AudacityProject::HandleTrackSolo(), AudacityProject::IsSoloSimple(), mLeftTrack, mMixerBoard, mProject, mToggleButton_Mute, mToggleButton_Solo, AudacityProject::RedrawProject(), AudacityProject::RefreshTPTrack(), AButton::SetAlternate(), MixerBoard::UpdateMute(), MixerBoard::UpdateSolo(), and AButton::WasShiftDown().
void MixerTrackCluster::OnKeyEvent (wxKeyEvent & event) [private]
References AudacityProject::HandleKeyDown(), and mProject.
void MixerTrackCluster::OnMouseEvent (wxMouseEvent & event) [private]
References HandleSelect().
void MixerTrackCluster::OnPaint (wxPaintEvent & evt) [private]
References AColor::Bevel(), Track::GetSelected(), AColor::Medium(), and mLeftTrack.
void MixerTrackCluster::OnSlider_Gain (wxCommandEvent & event) [private]
References HandleSliderGain().
void MixerTrackCluster::OnSlider_Pan (wxCommandEvent & event) [private]
References HandleSliderPan().
void MixerTrackCluster::ResetMeter ()
References WaveTrack::GetRate(), mLeftTrack, mMeter, and Meter::Reset().
Referenced by UpdateMeter().
void MixerTrackCluster::UpdateForStateChange ()
References UpdateGain(), UpdateName(), and UpdatePan().
void MixerTrackCluster::UpdateGain ()
References WaveTrack::GetGain(), mLeftTrack, mSlider_Gain, and ASlider::Set().
Referenced by UpdateForStateChange(), and MixerBoard::UpdateGain().
void MixerTrackCluster::UpdateMeter (const double t0, const double t1)
References WaveTrack::GetChannelGain(), WaveTrack::GetMinMax(), Track::GetMute(), WaveTrack::GetRMS(), Track::GetSolo(), MixerBoard::HasSolo(), min(), mLeftTrack, mMeter, mMixerBoard, mRightTrack, ResetMeter(), WaveTrack::TimeToLongSamples(), and Meter::UpdateDisplay().
void MixerTrackCluster::UpdateMute ()
References Track::GetMute(), Track::GetSolo(), mLeftTrack, mToggleButton_Mute, AButton::PopUp(), AButton::PushDown(), and AButton::SetAlternate().
Referenced by MixerBoard::UpdateMute().
void MixerTrackCluster::UpdateName ()
References MixerBoard::GetMusicalInstrumentBitmap(), Track::GetName(), mBitmapButton_MusicalInstrument, mLeftTrack, mMixerBoard, and mStaticText_TrackName.
Referenced by UpdateForStateChange(), and MixerBoard::UpdateName().
void MixerTrackCluster::UpdatePan ()
References WaveTrack::GetPan(), mLeftTrack, mSlider_Pan, and ASlider::Set().
Referenced by UpdateForStateChange(), and MixerBoard::UpdatePan().
void MixerTrackCluster::UpdateSolo ()
References Track::GetSolo(), mLeftTrack, mToggleButton_Mute, mToggleButton_Solo, AButton::PopUp(), AButton::PushDown(), and AButton::SetAlternate().
Referenced by MixerBoard::UpdateSolo().
Member Data Documentation
wxBitmapButton* MixerTrackCluster::mBitmapButton_MusicalInstrument [private]
Referenced by UpdateName().
WaveTrack* MixerTrackCluster::mLeftTrack
Referenced by HandleSelect(), HandleSliderGain(), HandleSliderPan(), OnButton_Mute(), OnButton_Solo(), OnPaint(), ResetMeter(), UpdateGain(), UpdateMeter(), UpdateMute(), UpdateName(), UpdatePan(), and UpdateSolo().
Meter* MixerTrackCluster::mMeter [private]
Referenced by HandleResize(), ResetMeter(), and UpdateMeter().
MixerBoard* MixerTrackCluster::mMixerBoard [private]
Referenced by HandleSelect(), OnButton_Mute(), OnButton_Solo(), UpdateMeter(), and UpdateName().
AudacityProject* MixerTrackCluster::mProject [private]
Referenced by HandleResize(), HandleSelect(), HandleSliderGain(), HandleSliderPan(), OnButton_Mute(), OnButton_Solo(), and OnKeyEvent().
WaveTrack* MixerTrackCluster::mRightTrack
Referenced by HandleSelect(), HandleSliderGain(), HandleSliderPan(), and UpdateMeter().
MixerTrackSlider* MixerTrackCluster::mSlider_Gain [private]
Referenced by HandleResize(), HandleSliderGain(), and UpdateGain().
MixerTrackSlider* MixerTrackCluster::mSlider_Pan [private]
Referenced by HandleSliderPan(), and UpdatePan().
wxStaticText* MixerTrackCluster::mStaticText_TrackName [private]
Referenced by UpdateName().
AButton* MixerTrackCluster::mToggleButton_Mute [private]
Referenced by OnButton_Mute(), OnButton_Solo(), UpdateMute(), and UpdateSolo().
AButton* MixerTrackCluster::mToggleButton_Solo [private]
Referenced by HandleResize(), OnButton_Solo(), and UpdateSolo().
The documentation for this class was generated from the following files:
MixerBoard.h
MixerBoard.cpp