Audacity: EffectRepeat Class Reference
EffectRepeat Class Reference
An Effect.
#include <Repeat.h>
Public Member Functions
EffectRepeat ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual wxString GetEffectDescription ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Process ()
Private Attributes
int repeatCount
Friends
class RepeatDialog
Detailed Description
An Effect.
Constructor & Destructor Documentation
EffectRepeat::EffectRepeat ()
References repeatCount.
Member Function Documentation
virtual wxString EffectRepeat::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectRepeat::GetEffectCategories () [inline, virtual]
wxString EffectRepeat::GetEffectDescription () [virtual]
Reimplemented from Effect.
References repeatCount.
virtual wxString EffectRepeat::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectRepeat::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectRepeat::Process () [virtual]
Implements Effect.
References Track::All, WaveTrack::Copy(), Effect::CopyInputTracks(), TrackListIterator::First(), Track::Label, WaveTrack::LongSamplesToTime(), Effect::mOutputTracks, Effect::mT0, Effect::mT1, TrackListIterator::Next(), WaveTrack::Paste(), LabelTrack::Repeat(), repeatCount, Effect::ReplaceProcessedTracks(), Track::SyncAdjust(), WaveTrack::TimeToLongSamples(), Effect::TrackProgress(), and Track::Wave.
bool EffectRepeat::PromptUser () [virtual]
Reimplemented from Effect.
References TrackListCondIterator::First(), WaveTrack::GetEndTime(), WaveTrack::GetRate(), WaveTrack::GetStartTime(), RepeatDialog::maxCount, Effect::mParent, Effect::mT0, Effect::mT1, Effect::mTracks, TrackListCondIterator::Next(), repeatCount, RepeatDialog::repeatCount, RepeatDialog::selectionTimeSecs, RepeatDialog::TransferDataToWindow(), and Track::Wave.
bool EffectRepeat::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References repeatCount, and Shuttle::TransferInt().
Friends And Related Function Documentation
friend class RepeatDialog [friend]
Member Data Documentation
int EffectRepeat::repeatCount [private]
Referenced by EffectRepeat(), GetEffectDescription(), RepeatDialog::OnPreview(), Process(), PromptUser(), and TransferParameters().
The documentation for this class was generated from the following files:
Repeat.h
Repeat.cpp