Audacity: ScreenFrame Class Reference
ScreenFrame Class Reference
Public Member Functions
ScreenFrame (wxWindow *parent, wxWindowID id)
virtual ~ScreenFrame ()
virtual bool ProcessEvent (wxEvent &e)
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
void OnCloseWindow (wxCloseEvent &e)
void OnUIUpdate (wxUpdateUIEvent &e)
void OnDirChoose (wxCommandEvent &e)
void SizeMainWindow (int w, int h)
void OnMainWindowSmall (wxCommandEvent &e)
void OnMainWindowLarge (wxCommandEvent &e)
void OnToggleBackgroundBlue (wxCommandEvent &e)
void OnToggleBackgroundWhite (wxCommandEvent &e)
void DoCapture (wxString captureMode)
void OnCaptureWindowContents (wxCommandEvent &e)
void OnCaptureFullWindow (wxCommandEvent &e)
void OnCaptureWindowPlus (wxCommandEvent &e)
void OnCaptureFullScreen (wxCommandEvent &e)
void OnCaptureToolbars (wxCommandEvent &e)
void OnCaptureSelectionBar (wxCommandEvent &e)
void OnCaptureTools (wxCommandEvent &e)
void OnCaptureControl (wxCommandEvent &e)
void OnCaptureMixer (wxCommandEvent &e)
void OnCaptureMeter (wxCommandEvent &e)
void OnCaptureEdit (wxCommandEvent &e)
void OnCaptureDevice (wxCommandEvent &e)
void OnCaptureTranscription (wxCommandEvent &e)
void TimeZoom (double seconds)
void OnOneSec (wxCommandEvent &e)
void OnTenSec (wxCommandEvent &e)
void OnOneMin (wxCommandEvent &e)
void OnFiveMin (wxCommandEvent &e)
void OnOneHour (wxCommandEvent &e)
void SizeTracks (int h)
void OnShortTracks (wxCommandEvent &e)
void OnMedTracks (wxCommandEvent &e)
void OnTallTracks (wxCommandEvent &e)
void OnCaptureTrackPanel (wxCommandEvent &e)
void OnCaptureRuler (wxCommandEvent &e)
void OnCaptureTracks (wxCommandEvent &e)
void OnCaptureFirstTrack (wxCommandEvent &e)
void OnCaptureSecondTrack (wxCommandEvent &e)
ScreenshotCommand * CreateCommand ()
Private Attributes
wxCheckBox * mDelayCheckBox
wxTextCtrl * mDirectoryTextBox
wxToggleButton * mBlue
wxToggleButton * mWhite
wxStatusBar * mStatus
ScreenshotCommand * mCommand
CommandExecutionContext mContext
Constructor & Destructor Documentation
ScreenFrame::ScreenFrame (wxWindow * parent, wxWindowID id)
References CreateCommand(), mCommand, mContext, mDelayCheckBox, mDirectoryTextBox, mStatus, AudacityProject::mToolManager, Populate(), CommandExecutionContext::proj, and ToolManager::Reset().
ScreenFrame::~ScreenFrame () [virtual]
References mCommand.
Member Function Documentation
ScreenshotCommand * ScreenFrame::CreateCommand () [private]
References CommandDirectory::Get(), and CommandDirectory::LookUp().
Referenced by ScreenFrame().
void ScreenFrame::DoCapture (wxString captureMode) [private]
References ScreenshotCommand::Apply(), mCommand, mContext, mDirectoryTextBox, mStatus, and CommandImplementation::SetParameter().
Referenced by OnCaptureControl(), OnCaptureDevice(), OnCaptureEdit(), OnCaptureFirstTrack(), OnCaptureFullScreen(), OnCaptureFullWindow(), OnCaptureMeter(), OnCaptureMixer(), OnCaptureRuler(), OnCaptureSecondTrack(), OnCaptureSelectionBar(), OnCaptureToolbars(), OnCaptureTools(), OnCaptureTrackPanel(), OnCaptureTracks(), OnCaptureTranscription(), OnCaptureWindowContents(), and OnCaptureWindowPlus().
void ScreenFrame::OnCaptureControl (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureDevice (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureEdit (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureFirstTrack (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureFullScreen (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureFullWindow (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureMeter (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureMixer (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureRuler (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureSecondTrack (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureSelectionBar (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureToolbars (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureTools (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureTrackPanel (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureTracks (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureTranscription (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureWindowContents (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCaptureWindowPlus (wxCommandEvent & e) [private]
References DoCapture().
void ScreenFrame::OnCloseWindow (wxCloseEvent & e) [private]
void ScreenFrame::OnDirChoose (wxCommandEvent & e) [private]
References gPrefs, and mDirectoryTextBox.
void ScreenFrame::OnFiveMin (wxCommandEvent & e) [private]
References TimeZoom().
void ScreenFrame::OnMainWindowLarge (wxCommandEvent & e) [private]
References SizeMainWindow().
void ScreenFrame::OnMainWindowSmall (wxCommandEvent & e) [private]
References SizeMainWindow().
void ScreenFrame::OnMedTracks (wxCommandEvent & e) [private]
References SizeTracks().
void ScreenFrame::OnOneHour (wxCommandEvent & e) [private]
References TimeZoom().
void ScreenFrame::OnOneMin (wxCommandEvent & e) [private]
References TimeZoom().
void ScreenFrame::OnOneSec (wxCommandEvent & e) [private]
References TimeZoom().
void ScreenFrame::OnShortTracks (wxCommandEvent & e) [private]
References AudacityProject::GetTracks(), mContext, CommandExecutionContext::proj, AudacityProject::RedrawProject(), and Track::Wave.
void ScreenFrame::OnTallTracks (wxCommandEvent & e) [private]
References SizeTracks().
void ScreenFrame::OnTenSec (wxCommandEvent & e) [private]
References TimeZoom().
void ScreenFrame::OnToggleBackgroundBlue (wxCommandEvent & e) [private]
References mBlue, mCommand, mWhite, and CommandImplementation::SetParameter().
void ScreenFrame::OnToggleBackgroundWhite (wxCommandEvent & e) [private]
References mBlue, mCommand, mWhite, and CommandImplementation::SetParameter().
void ScreenFrame::OnUIUpdate (wxUpdateUIEvent & e) [private]
References ScreenshotCommand::GetFrontWindow(), IdLastDelayedEvent, IdMainWindowSmall, mCommand, mContext, mDirectoryTextBox, and CommandExecutionContext::proj.
void ScreenFrame::Populate () [private]
References eIsCreating, and PopulateOrExchange().
Referenced by ScreenFrame().
void ScreenFrame::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddCheckBox(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddWindow(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndPanel(), ShuttleGuiBase::EndStatic(), gPrefs, ShuttleGui::Id(), IdCaptureControl, IdCaptureDevice, IdCaptureEdit, IdCaptureFirstTrack, IdCaptureFullScreen, IdCaptureFullWindow, IdCaptureMeter, IdCaptureMixer, IdCaptureRuler, IdCaptureSecondTrack, IdCaptureSelectionBar, IdCaptureToolbars, IdCaptureTools, IdCaptureTrackPanel, IdCaptureTracks, IdCaptureTranscription, IdCaptureWindowContents, IdCaptureWindowPlus, IdDelayCheckBox, IdDirChoose, IdDirectory, IdFiveMin, IdMainWindowLarge, IdMainWindowSmall, IdMedTracks, IdOneHour, IdOneMin, IdOneSec, IdShortTracks, IdTallTracks, IdTenSec, IdToggleBackgroundBlue, IdToggleBackgroundWhite, mBlue, mContext, mDelayCheckBox, mDirectoryTextBox, mWhite, CommandExecutionContext::proj, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartPanel(), and ShuttleGuiBase::StartStatic().
Referenced by Populate().
bool ScreenFrame::ProcessEvent (wxEvent & e) [virtual]
References IdAllDelayedEvents, IdLastDelayedEvent, mDelayCheckBox, and wxEVT_COMMAND_BUTTON_CLICKED.
Referenced by ScreenFrameTimer::Notify().
void ScreenFrame::SizeMainWindow (int w, int h) [private]
References mContext, AudacityProject::mToolManager, CommandExecutionContext::proj, and ToolManager::Reset().
Referenced by OnMainWindowLarge(), and OnMainWindowSmall().
void ScreenFrame::SizeTracks (int h) [private]
References AudacityProject::GetTracks(), mContext, CommandExecutionContext::proj, AudacityProject::RedrawProject(), and Track::Wave.
Referenced by OnMedTracks(), and OnTallTracks().
void ScreenFrame::TimeZoom (double seconds) [private]
References mContext, AudacityProject::mViewInfo, CommandExecutionContext::proj, AudacityProject::RedrawProject(), and ViewInfo::zoom.
Referenced by OnFiveMin(), OnOneHour(), OnOneMin(), OnOneSec(), and OnTenSec().
Member Data Documentation
wxToggleButton* ScreenFrame::mBlue [private]
Referenced by OnToggleBackgroundBlue(), OnToggleBackgroundWhite(), and PopulateOrExchange().
ScreenshotCommand* ScreenFrame::mCommand [private]
Referenced by DoCapture(), OnToggleBackgroundBlue(), OnToggleBackgroundWhite(), OnUIUpdate(), ScreenFrame(), and ~ScreenFrame().
CommandExecutionContext ScreenFrame::mContext [private]
Referenced by DoCapture(), OnShortTracks(), OnUIUpdate(), PopulateOrExchange(), ScreenFrame(), SizeMainWindow(), SizeTracks(), and TimeZoom().
wxCheckBox* ScreenFrame::mDelayCheckBox [private]
Referenced by PopulateOrExchange(), ProcessEvent(), and ScreenFrame().
wxTextCtrl* ScreenFrame::mDirectoryTextBox [private]
Referenced by DoCapture(), OnDirChoose(), OnUIUpdate(), PopulateOrExchange(), and ScreenFrame().
wxStatusBar* ScreenFrame::mStatus [private]
Referenced by DoCapture(), and ScreenFrame().
wxToggleButton* ScreenFrame::mWhite [private]
Referenced by OnToggleBackgroundBlue(), OnToggleBackgroundWhite(), and PopulateOrExchange().
The documentation for this class was generated from the following file:
Screenshot.cpp