Audacity: EffectManager Class Reference
EffectManager Class Reference
EffectManager is the class that handles effects and effect categories.
#include <EffectManager.h>
Public Member Functions
EffectManager ()
~EffectManager ()
void RegisterEffect (Effect *f, int AdditionalFlags=0)
void UnregisterEffects ()
Effect * GetEffect (int ID)
Effect * GetEffectByIdentifier (const wxString strTarget, const int kFlags=ALL_EFFECTS)
int GetNumEffects ()
EffectArray * GetEffects (int flags=ALL_EFFECTS)
Static Public Member Functions
static EffectManager & Get ()
Private Attributes
EffectArray mEffects
int mNumEffects
Detailed Description
EffectManager is the class that handles effects and effect categories.
It maintains a graph of effect categories and subcategories, registers and unregisters effects and can return filtered lists of effects.
Constructor & Destructor Documentation
EffectManager::EffectManager ()
EffectManager::~EffectManager ()
A destructor is needed so we can delete all categories.
Member Function Documentation
EffectManager & EffectManager::Get () [static]
Get the singleton instance of the EffectManager. Probably not safe for multi-thread use.
Referenced by BatchCommands::ApplyCommand(), BatchCommands::ApplySpecialCommand(), AudacityProject::CreateMenusAndCommands(), BatchCommands::GetAllCommands(), BatchCommands::GetCurrentParamsFor(), CommandManager::HandleTextualCommand(), AudacityProject::Import(), LoadAudioUnits(), LoadEffects(), LoadLadspaEffect(), LoadLadspaPlugins(), LoadNyquistEffect(), LoadNyquistPlugins(), LoadVampPlugins(), BatchCommandDialog::OnEditParams(), AudacityProject::OnEffect(), BatchCommandDialog::OnItemSelected(), AudacityProject::OnProcessAny(), AudacityProject::OnStereoToMono(), BatchCommands::PromptForParamsFor(), and UnloadEffects().
Effect * EffectManager::GetEffect (int ID)
Return an effect by its numerical ID.
References mEffects, and mNumEffects.
Referenced by AudacityProject::OnProcessAny().
Effect * EffectManager::GetEffectByIdentifier (const wxString strTarget, const int kFlags = ALL_EFFECTS)
References mEffects.
Referenced by BatchCommands::ApplyCommand(), BatchCommands::ApplySpecialCommand(), BatchCommands::GetCurrentParamsFor(), BatchCommandDialog::OnEditParams(), BatchCommandDialog::OnItemSelected(), and BatchCommands::PromptForParamsFor().
EffectArray * EffectManager::GetEffects (int flags = ALL_EFFECTS)
Returns a sorted array of effects, which may be filtered using the flags parameter. The caller should dispose of the array when done.
References mEffects.
Referenced by AudacityProject::CreateMenusAndCommands(), BatchCommands::GetAllCommands(), CommandManager::HandleTextualCommand(), and AudacityProject::OnEffect().
int EffectManager::GetNumEffects ()
Return the number of registered effects.
References mNumEffects.
void EffectManager::RegisterEffect (Effect * f, int AdditionalFlags = 0)
Register an effect so it will appear in the menu.
References EffectCategory::AddEffect(), Effect::GetEffectName(), mEffects, Effect::mID, mNumEffects, name, Effect::SetEffectFlags(), and Effect::StripAmpersand().
Referenced by LoadAudioUnits(), LoadEffects(), LoadLadspaEffect(), LoadNyquistEffect(), LoadNyquistPlugins(), and LoadVampPlugins().
void EffectManager::UnregisterEffects ()
Unregister all effects.
References mEffects, and mNumEffects.
Referenced by UnloadEffects().
Member Data Documentation
EffectArray EffectManager::mEffects [private]
Referenced by GetEffect(), GetEffectByIdentifier(), GetEffects(), RegisterEffect(), and UnregisterEffects().
int EffectManager::mNumEffects [private]
Referenced by GetEffect(), GetNumEffects(), RegisterEffect(), and UnregisterEffects().
The documentation for this class was generated from the following files:
EffectManager.h
EffectManager.cpp