Audacity: ThemePrefs Class Reference
ThemePrefs Class Reference
A PrefsPanel that configures dynamic loading of Theme icons and colours.
#include <ThemePrefs.h>
Public Member Functions
ThemePrefs (wxWindow *parent)
~ThemePrefs (void)
virtual bool Apply ()
Update the preferences stored on disk.
Private Member Functions
void Populate ()
Creates the dialog and its contents.
void PopulateOrExchange (ShuttleGui &S)
Create the dialog contents, or exchange data with it.
void OnLoadThemeComponents (wxCommandEvent &e)
Load Theme from multiple png files.
void OnSaveThemeComponents (wxCommandEvent &e)
Save Theme to multiple png files.
void OnLoadThemeCache (wxCommandEvent &e)
Load Theme from single png file.
void OnSaveThemeCache (wxCommandEvent &e)
Save Theme to single png file.
void OnReadThemeInternal (wxCommandEvent &e)
Read Theme from internal storage.
void OnSaveThemeAsCode (wxCommandEvent &e)
Save Theme as C source code.
DECLARE_EVENT_TABLE ()
Detailed Description
A PrefsPanel that configures dynamic loading of Theme icons and colours.
Provides:
Button to save current theme as a single png image.
Button to load theme from a single png image.
Button to save current theme to multiple png images.
Button to load theme from multiple png images.
(Optional) Button to save theme as Cee data.
Button to read theme from default values in program.
CheckBox for loading custom themes at startup.
See also:
Themability
Constructor & Destructor Documentation
ThemePrefs::ThemePrefs (wxWindow * parent)
ThemePrefs::~ThemePrefs (void)
Member Function Documentation
bool ThemePrefs::Apply () [virtual]
Update the preferences stored on disk.
Implements PrefsPanel.
References eIsSavingToPrefs, and PopulateOrExchange().
ThemePrefs::DECLARE_EVENT_TABLE () [private]
void ThemePrefs::OnLoadThemeCache (wxCommandEvent & e) [private]
Load Theme from single png file.
References Theme::ApplyUpdatedImages(), ThemeBase::ReadImageCache(), AColor::ReInit(), and theTheme.
void ThemePrefs::OnLoadThemeComponents (wxCommandEvent & e) [private]
Load Theme from multiple png files.
References Theme::ApplyUpdatedImages(), ThemeBase::LoadComponents(), and theTheme.
void ThemePrefs::OnReadThemeInternal (wxCommandEvent & e) [private]
Read Theme from internal storage.
References Theme::ApplyUpdatedImages(), ThemeBase::ReadThemeInternal(), and theTheme.
void ThemePrefs::OnSaveThemeAsCode (wxCommandEvent & e) [private]
Save Theme as C source code.
References ThemeBase::SaveThemeAsCode(), theTheme, and ThemeBase::WriteImageDefs().
void ThemePrefs::OnSaveThemeCache (wxCommandEvent & e) [private]
Save Theme to single png file.
References ThemeBase::CreateImageCache(), theTheme, and ThemeBase::WriteImageMap().
void ThemePrefs::OnSaveThemeComponents (wxCommandEvent & e) [private]
Save Theme to multiple png files.
References ThemeBase::SaveComponents(), and theTheme.
void ThemePrefs::Populate () [private]
Creates the dialog and its contents.
References eIsCreatingFromPrefs, and PopulateOrExchange().
void ThemePrefs::PopulateOrExchange (ShuttleGui & S) [private]
Create the dialog contents, or exchange data with it.
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddFixedText(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGui::Id(), idLoadThemeCache, idLoadThemeComponents, idReadThemeInternal, idSaveThemeAsCode, idSaveThemeCache, idSaveThemeComponents, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::TieCheckBox().
Referenced by Apply(), and Populate().
The documentation for this class was generated from the following files:
ThemePrefs.h
ThemePrefs.cpp