Audacity: EffectSimpleMono Class Reference
EffectSimpleMono Class Reference
An abstract Effect class that simplifies the implementation of a basic monaural effect. Inherit from it if your effect just modifies a single track in place and doesn't care how many samples it gets at a time.
#include <SimpleMono.h>
Public Member Functions
virtual bool Process ()
Protected Member Functions
virtual bool NewTrackSimpleMono ()
virtual bool ProcessSimpleMono (float *buffer, sampleCount len)=0
Protected Attributes
int mCurTrackNum
double mCurRate
double mCurT0
double mCurT1
int mCurChannel
Private Member Functions
bool ProcessOne (WaveTrack *t, sampleCount start, sampleCount end)
Detailed Description
An abstract Effect class that simplifies the implementation of a basic monaural effect. Inherit from it if your effect just modifies a single track in place and doesn't care how many samples it gets at a time.
Your derived class only needs to implement GetEffectName, GetEffectAction, and ProcessSimpleMono.
Member Function Documentation
bool EffectSimpleMono::NewTrackSimpleMono () [protected, virtual]
Reimplemented in EffectBassBoost, EffectFadeIn, EffectFadeOut, EffectPhaser, and EffectWahwah.
Referenced by Process().
bool EffectSimpleMono::Process () [virtual]
Implements Effect.
References Effect::CopyInputTracks(), TrackListCondIterator::First(), Track::GetChannel(), WaveTrack::GetEndTime(), WaveTrack::GetRate(), WaveTrack::GetStartTime(), mCurChannel, mCurRate, mCurT0, mCurT1, mCurTrackNum, Effect::mOutputTracks, Effect::mT0, Effect::mT1, NewTrackSimpleMono(), TrackListCondIterator::Next(), ProcessOne(), Effect::ReplaceProcessedTracks(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectSimpleMono::ProcessOne (WaveTrack * t, sampleCount start, sampleCount end) [private]
References floatSample, WaveTrack::Get(), WaveTrack::GetBestBlockSize(), WaveTrack::GetMaxBlockSize(), mCurTrackNum, ProcessSimpleMono(), WaveTrack::Set(), and Effect::TrackProgress().
Referenced by Process().
virtual bool EffectSimpleMono::ProcessSimpleMono (float * buffer, sampleCount len) [protected, pure virtual]
Implemented in EffectAmplify, EffectBassBoost, EffectFadeIn, EffectFadeOut, EffectInvert, EffectLeveller, EffectPhaser, EffectSpikeCleaner, and EffectWahwah.
Referenced by ProcessOne().
Member Data Documentation
int EffectSimpleMono::mCurChannel [protected]
Referenced by EffectWahwah::NewTrackSimpleMono(), EffectPhaser::NewTrackSimpleMono(), and Process().
double EffectSimpleMono::mCurRate [protected]
Referenced by EffectWahwah::NewTrackSimpleMono(), EffectPhaser::NewTrackSimpleMono(), EffectFadeOut::NewTrackSimpleMono(), EffectFadeIn::NewTrackSimpleMono(), EffectBassBoost::NewTrackSimpleMono(), and Process().
double EffectSimpleMono::mCurT0 [protected]
Referenced by EffectFadeOut::NewTrackSimpleMono(), EffectFadeIn::NewTrackSimpleMono(), and Process().
double EffectSimpleMono::mCurT1 [protected]
Referenced by EffectFadeOut::NewTrackSimpleMono(), EffectFadeIn::NewTrackSimpleMono(), and Process().
int EffectSimpleMono::mCurTrackNum [protected]
Referenced by Process(), and ProcessOne().
The documentation for this class was generated from the following files:
SimpleMono.h
SimpleMono.cpp