Audacity: EffectsPrefs Class Reference
EffectsPrefs Class Reference
A PrefsPanel for general GUI prefernces.
#include <EffectsPrefs.h>
Public Member Functions
EffectsPrefs (wxWindow *parent)
~EffectsPrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
Detailed Description
A PrefsPanel for general GUI prefernces.
Constructor & Destructor Documentation
EffectsPrefs::EffectsPrefs (wxWindow * parent)
References Populate().
EffectsPrefs::~EffectsPrefs ()
Member Function Documentation
bool EffectsPrefs::Apply () [virtual]
Implements PrefsPanel.
References eIsSavingToPrefs, GetSystemLanguageCode(), gPrefs, AudacityApp::InitLang(), PopulateOrExchange(), and wxGetApp().
void EffectsPrefs::Populate () [private]
References eIsCreatingFromPrefs, and PopulateOrExchange().
Referenced by EffectsPrefs().
void EffectsPrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddFixedText(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::TieCheckBox().
Referenced by Apply(), and Populate().
The documentation for this class was generated from the following files:
EffectsPrefs.h
EffectsPrefs.cpp