Audacity: EffectClickRemoval Class Reference
EffectClickRemoval Class Reference
An Effect.
#include <ClickRemoval.h>
Public Member Functions
EffectClickRemoval ()
virtual ~EffectClickRemoval ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Init ()
virtual bool CheckWhetherSkipEffect ()
virtual bool Process ()
Private Member Functions
bool ProcessOne (int count, WaveTrack *track, sampleCount start, sampleCount len)
void RemoveClicks (sampleCount len, float *buffer)
Private Attributes
Envelope * mEnvelope
int windowSize
int mThresholdLevel
int mClickWidth
int sep
Friends
class ClickRemovalDialog
Detailed Description
An Effect.
Clicks are identified as small regions of high amplitude compared to the surrounding chunk of sound. Anything sufficiently tall compared to a large (2048 sample) window around it, and sufficiently narrow, is considered to be a click.
The structure was largely stolen from Domonic Mazzoni's NoiseRemoval module, and reworked for the new effect.
This file is intended to become part of Audacity. You may modify and/or distribute it under the same terms as Audacity itself.
Constructor & Destructor Documentation
EffectClickRemoval::EffectClickRemoval ()
References Init(), sep, and windowSize.
EffectClickRemoval::~EffectClickRemoval () [virtual]
Member Function Documentation
bool EffectClickRemoval::CheckWhetherSkipEffect () [virtual]
Reimplemented from Effect.
References mClickWidth, and mThresholdLevel.
virtual wxString EffectClickRemoval::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectClickRemoval::GetEffectCategories () [inline, virtual]
virtual wxString EffectClickRemoval::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectClickRemoval::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectClickRemoval::Init () [virtual]
Reimplemented from Effect.
References gPrefs, MAX_CLICK_WIDTH, MAX_THRESHOLD, mClickWidth, MIN_CLICK_WIDTH, MIN_THRESHOLD, and mThresholdLevel.
Referenced by EffectClickRemoval().
bool EffectClickRemoval::Process () [virtual]
Implements Effect.
References Effect::CopyInputTracks(), TrackListCondIterator::First(), WaveTrack::GetEndTime(), WaveTrack::GetStartTime(), Effect::mOutputTracks, Effect::mT0, Effect::mT1, TrackListCondIterator::Next(), ProcessOne(), Effect::ReplaceProcessedTracks(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectClickRemoval::ProcessOne (int count, WaveTrack * track, sampleCount start, sampleCount len) [private]
References floatSample, WaveTrack::Get(), WaveTrack::GetMaxBlockSize(), RemoveClicks(), WaveTrack::Set(), Effect::TrackProgress(), and windowSize.
Referenced by Process().
bool EffectClickRemoval::PromptUser () [virtual]
Reimplemented from Effect.
References gPrefs, mClickWidth, Effect::mParent, ClickRemovalDialog::mThresh, mThresholdLevel, ClickRemovalDialog::mWidth, and ClickRemovalDialog::TransferDataToWindow().
void EffectClickRemoval::RemoveClicks (sampleCount len, float * buffer) [private]
References mClickWidth, mThresholdLevel, and sep.
Referenced by ProcessOne().
bool EffectClickRemoval::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References mClickWidth, mThresholdLevel, and Shuttle::TransferInt().
Friends And Related Function Documentation
friend class ClickRemovalDialog [friend]
Member Data Documentation
int EffectClickRemoval::mClickWidth [private]
Referenced by CheckWhetherSkipEffect(), Init(), ClickRemovalDialog::OnPreview(), PromptUser(), RemoveClicks(), and TransferParameters().
Envelope* EffectClickRemoval::mEnvelope [private]
int EffectClickRemoval::mThresholdLevel [private]
Referenced by CheckWhetherSkipEffect(), Init(), ClickRemovalDialog::OnPreview(), PromptUser(), RemoveClicks(), and TransferParameters().
int EffectClickRemoval::sep [private]
Referenced by EffectClickRemoval(), and RemoveClicks().
int EffectClickRemoval::windowSize [private]
Referenced by EffectClickRemoval(), and ProcessOne().
The documentation for this class was generated from the following files:
ClickRemoval.h
ClickRemoval.cpp