Audacity: CommandDirectory Class Reference
CommandDirectory Class Reference
Allows registration and lookup (by name) of command types.
#include <CommandDirectory.h>
Public Member Functions
CommandDirectory ()
~CommandDirectory ()
CommandType * LookUp (const wxString &cmdName) const
void AddCommand (CommandType *type)
Register a type of command with the directory.
Static Public Member Functions
static CommandDirectory * Get ()
Get a pointer to the singleton instance.
static void Destroy ()
Manually delete the singleton instance.
Private Attributes
CommandMap mCmdMap
Static Private Attributes
static CommandDirectory * mInstance = NULL
Detailed Description
Allows registration and lookup (by name) of command types.
A singleton. This fulfills a similar purpose to CommandManager, but for general Commands rather than menu items. Eventually they could be unified but for now they are kept separate to make things simpler.
Constructor & Destructor Documentation
CommandDirectory::CommandDirectory ()
References AddCommand(), and mInstance.
Referenced by Get().
CommandDirectory::~CommandDirectory ()
References mCmdMap.
Member Function Documentation
void CommandDirectory::AddCommand (CommandType * type)
Register a type of command with the directory.
References CommandType::GetName(), and mCmdMap.
Referenced by CommandDirectory().
void CommandDirectory::Destroy () [static]
Manually delete the singleton instance.
References mInstance.
CommandDirectory * CommandDirectory::Get () [static]
Get a pointer to the singleton instance.
References CommandDirectory(), and mInstance.
Referenced by HelpCommand::Apply(), CommandBuilder::BuildCommand(), ScreenFrame::CreateCommand(), and AudacityProject::SafeDisplayStatusMessage().
CommandType * CommandDirectory::LookUp (const wxString & cmdName) const
If a command with the given name has been registered in the directory, return a pointer to the factory for commands of that type. Otherwise return NULL.
References mCmdMap.
Referenced by HelpCommand::Apply(), CommandBuilder::BuildCommand(), ScreenFrame::CreateCommand(), and AudacityProject::SafeDisplayStatusMessage().
Member Data Documentation
CommandMap CommandDirectory::mCmdMap [private]
Referenced by AddCommand(), LookUp(), and ~CommandDirectory().
CommandDirectory * CommandDirectory::mInstance = NULL [static, private]
Referenced by CommandDirectory(), Destroy(), and Get().
The documentation for this class was generated from the following files:
CommandDirectory.h
CommandDirectory.cpp