Audacity: ODDecodeBlockFile Class Reference
ODDecodeBlockFile Class Reference
An AliasBlockFile that references uncompressed data in an existing file.
#include <ODDecodeBlockFile.h>
Public Member Functions
ODDecodeBlockFile (wxFileName baseFileName, wxFileName audioFileName, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, unsigned int decodeType)
Create a disk file and write summary and sample data to it.
ODDecodeBlockFile (wxFileName existingFile, wxFileName audioFileName, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, unsigned int decodeType, float min, float max, float rms, bool dataAvailable)
Create the memory structure to refer to the given block file.
virtual ~ODDecodeBlockFile ()
virtual bool IsSummaryAvailable ()
Returns TRUE if this block's complete summary has been computed and is ready (for OD).
virtual bool IsDataAvailable ()
Returns TRUE if this block's complete data is ready to be accessed by Read().
virtual bool IsSummaryBeingComputed ()
Returns TRUE if the summary has not yet been written, but is actively being computed and written to disk.
virtual wxLongLong GetSpaceUsage ()
virtual void GetMinMax (sampleCount start, sampleCount len, float *outMin, float *outMax, float *outRMS)
Gets extreme values for the specified region.
virtual void GetMinMax (float *outMin, float *outMax, float *outRMS)
Gets extreme values for the entire block.
virtual bool Read256 (float *buffer, sampleCount start, sampleCount len)
Returns the 256 byte summary data block.
virtual bool Read64K (float *buffer, sampleCount start, sampleCount len)
Returns the 64K summary data block.
virtual BlockFile * Copy (wxFileName fileName)
Makes new ODPCMAliasBlockFile or PCMAliasBlockFile depending on summary availability.
virtual void SaveXML (XMLWriter &xmlFile)
Saves as xml ODPCMAliasBlockFile or PCMAliasBlockFile depending on summary availability.
virtual void Recover (void)
Writes the summary file if summary data is available.
void DoWriteBlockFile ()
A public interface to WriteSummary.
void WriteODDecodeBlockFile ()
void SetStart (sampleCount startSample)
Sets the value that indicates where the first sample in this block corresponds to the global sequence/clip. Only for display use.
sampleCount GetStart ()
Gets the value that indicates where the first sample in this block corresponds to the global sequence/clip. Only for display use.
virtual int ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len)
Reads the specified data from the aliased file using libsndfile.
virtual bool ReadSummary (void *data)
Read the summary into a buffer.
virtual unsigned int GetDecodeType ()
Returns the type of audiofile this blockfile is loaded from.
virtual void SetDecodeType (unsigned int type)
void SetClipOffset (sampleCount numSamples)
sets the amount of samples the clip associated with this blockfile is offset in the wavetrack (non effecting)
sampleCount GetClipOffset ()
Gets the number of samples the clip associated with this blockfile is offset by.
void SetODFileDecoder (ODFileDecoder *decoder)
set the decoder,
wxFileName GetAudioFileName ()
virtual void SetFileName (wxFileName &name)
sets the file name the summary info will be saved in. threadsafe.
virtual wxFileName GetFileName ()
sets the file name the summary info will be saved in. threadsafe.
virtual void LockRead ()
Prevents a read on other threads of the encoded audio file.
virtual void UnlockRead ()
Allows reading of encoded file on other threads.
wxFileName GetEncodedAudioFilename ()
void ChangeAudioFile (wxFileName newAudioFile)
Static Public Member Functions
static BlockFile * BuildFromXML (DirManager &dm, const wxChar **attrs)
Reconstructs from XML a ODPCMAliasBlockFile and reschedules it for OD loading.
Protected Member Functions
virtual void * CalcSummary (samplePtr buffer, sampleCount len, sampleFormat format)
Protected Attributes
unsigned int mType
ODLock mFileNameMutex
wxFileName mAudioFileName
The original file the audio came from.
ODLock mDataAvailableMutex
bool mDataAvailable
bool mDataBeingComputed
ODFileDecoder * mDecoder
ODLock mDecoderMutex
ODLock mReadDataMutex
For accessing the audio file that will be decoded. Used by dir manager;.
sampleCount mStart
for reporting after task is complete. Only for display use.
sampleCount mClipOffset
the ODTask needs to know where this blockfile lies in the track, so for convenience, we have this here.
sampleFormat mFormat
sampleCount mAliasStart
int mAliasChannel
Detailed Description
An AliasBlockFile that references uncompressed data in an existing file.
ODDecodeBlockFile is a special type of SimpleBlockFile that does not necessarily have summary OR audio data available The summary and audio is eventually computed and written to a file in a background thread.
ODDecodeBlockFile is a special type of SimpleBlockFile that does not necessarily have summary OR audio data available The summary is eventually computed and written to a file in a background thread. See ODPCMAliasBlockFile for a similar class.
Load On-Demand implementation of the SimpleBlockFIle for audio files that need to be decoded (mp3,flac,etc..).
Also, see ODPCMAliasBlockFile for a similar file.
Constructor & Destructor Documentation
ODDecodeBlockFile::ODDecodeBlockFile (wxFileName baseFileName, wxFileName audioFileName, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, unsigned int decodeType)
Create a disk file and write summary and sample data to it.
References mAudioFileName, and mDataAvailable.
Referenced by BuildFromXML(), and Copy().
ODDecodeBlockFile::ODDecodeBlockFile (wxFileName existingFile, wxFileName audioFileName, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, unsigned int decodeType, float min, float max, float rms, bool dataAvailable)
Create the memory structure to refer to the given block file.
References mAudioFileName, and mDataAvailable.
ODDecodeBlockFile::~ODDecodeBlockFile () [virtual]
Member Function Documentation
BlockFile * ODDecodeBlockFile::BuildFromXML (DirManager & dm, const wxChar ** attrs) [static]
Reconstructs from XML a ODPCMAliasBlockFile and reschedules it for OD loading.
Constructs a ODPCMAliasBlockFile from the xml output of WriteXML. Also schedules the ODPCMAliasBlockFile for OD loading.
XMLValueChecker::IsGoodFileName(summaryFileName.GetFullName(), summaryFileName.GetPath(wxPATH_GET_VOLUME)) ||
Reimplemented from SimpleBlockFile.
References DirManager::AssignFile(), DirManager::GetProjectDataDir(), XMLValueChecker::IsGoodFileName(), XMLValueChecker::IsGoodFileString(), XMLValueChecker::IsGoodInt(), XMLValueChecker::IsGoodPathName(), XMLValueChecker::IsValidChannel(), and ODDecodeBlockFile().
Referenced by DirManager::HandleXMLTag().
void * ODDecodeBlockFile::CalcSummary (samplePtr buffer, sampleCount len, sampleFormat format) [protected, virtual]
A thread-safe version of CalcSummary. BlockFile::CalcSummary uses a static summary array across the class, which we can't use. Get a buffer containing a summary block describing this sample data. This must be called by derived classes when they are constructed, to allow them to construct their summary data, after which they should write that data to their disk file.
This method also has the side effect of setting the mMin, mMax, and mRMS members of this class.
Unlike BlockFile's implementation You SHOULD delete the returned buffer. this is protected so it shouldn't be hard to deal with - just override all BlockFile methods that use this method.
Parameters:
buffer A buffer containing the sample data to be analyzed
len The length of the sample data
format The format of the sample data.
Reimplemented from BlockFile.
References bheaderTag, bheaderTagLen, CopySamples(), floatSample, SummaryInfo::frames256, SummaryInfo::frames64K, max, min(), BlockFile::mMax, BlockFile::mMin, BlockFile::mRMS, BlockFile::mSummaryInfo, SummaryInfo::offset256, SummaryInfo::offset64K, and SummaryInfo::totalSummaryBytes.
void ODDecodeBlockFile::ChangeAudioFile (wxFileName newAudioFile)
Modify this block to point at a different file. This is generally looked down on, but it is necessary in one case: see DirManager::EnsureSafeFilename().
References mAudioFileName.
Referenced by DirManager::EnsureSafeFilename().
BlockFile * ODDecodeBlockFile::Copy (wxFileName newFileName) [virtual]
Makes new ODPCMAliasBlockFile or PCMAliasBlockFile depending on summary availability.
returns true before decoding is complete, because it is linked to the encoded file until then. returns false afterwards.
If the summary has been computed, Construct a new PCMAliasBlockFile based on this one. otherwise construct an ODPCMAliasBlockFile that still needs to be computed.
Parameters:
newFileName The filename to copy the summary data to.
Reimplemented from SimpleBlockFile.
References IsSummaryAvailable(), LockRead(), mAliasChannel, mAliasStart, mAudioFileName, BlockFile::mLen, BlockFile::mMax, BlockFile::mMin, BlockFile::mRMS, mType, ODDecodeBlockFile(), and UnlockRead().
void ODDecodeBlockFile::DoWriteBlockFile () [inline]
A public interface to WriteSummary.
References WriteODDecodeBlockFile().
Referenced by ODDecodeTask::DoSomeInternal().
wxFileName ODDecodeBlockFile::GetAudioFileName () [inline]
References mAudioFileName.
Referenced by ODDecodeTask::GetOrCreateMatchingFileDecoder().
sampleCount ODDecodeBlockFile::GetClipOffset () [inline]
Gets the number of samples the clip associated with this blockfile is offset by.
References mClipOffset.
virtual unsigned int ODDecodeBlockFile::GetDecodeType () [inline, virtual]
Returns the type of audiofile this blockfile is loaded from.
References mType.
wxFileName ODDecodeBlockFile::GetEncodedAudioFilename () [inline]
Get the name of the file where the audio data for this block is stored.
References mAudioFileName.
Referenced by DirManager::EnsureSafeFilename().
wxFileName ODDecodeBlockFile::GetFileName () [virtual]
sets the file name the summary info will be saved in. threadsafe.
Reimplemented from BlockFile.
References BlockFile::mFileName, mFileNameMutex, and name.
void ODDecodeBlockFile::GetMinMax (float * outMin, float * outMax, float * outRMS) [virtual]
Gets extreme values for the entire block.
Reimplemented from BlockFile.
References GetMinMax(), and IsSummaryAvailable().
void ODDecodeBlockFile::GetMinMax (sampleCount start, sampleCount len, float * outMin, float * outMax, float * outRMS) [virtual]
Gets extreme values for the specified region.
Reimplemented from BlockFile.
References IsSummaryAvailable().
Referenced by GetMinMax().
wxLongLong ODDecodeBlockFile::GetSpaceUsage () [virtual]
Reimplemented from SimpleBlockFile.
References IsSummaryAvailable(), and BlockFile::mFileName.
sampleCount ODDecodeBlockFile::GetStart () [inline]
Gets the value that indicates where the first sample in this block corresponds to the global sequence/clip. Only for display use.
References mStart.
Referenced by ODDecodeTask::DoSomeInternal().
bool ODDecodeBlockFile::IsDataAvailable () [virtual]
Returns TRUE if this block's complete data is ready to be accessed by Read().
Reimplemented from BlockFile.
References mDataAvailable, and mDataAvailableMutex.
Referenced by IsSummaryAvailable().
bool ODDecodeBlockFile::IsSummaryAvailable () [virtual]
Returns TRUE if this block's complete summary has been computed and is ready (for OD).
Reimplemented from BlockFile.
References IsDataAvailable().
Referenced by Copy(), GetMinMax(), GetSpaceUsage(), Read256(), Read64K(), ReadData(), ReadSummary(), Recover(), and SaveXML().
virtual bool ODDecodeBlockFile::IsSummaryBeingComputed () [inline, virtual]
Returns TRUE if the summary has not yet been written, but is actively being computed and written to disk.
Reimplemented from BlockFile.
void ODDecodeBlockFile::LockRead () [virtual]
Prevents a read on other threads of the encoded audio file.
Prevents a read on other threads.
Reimplemented from BlockFile.
References mReadDataMutex.
Referenced by Copy(), ODDecodeTask::DoSomeInternal(), DirManager::EnsureSafeFilename(), ReadData(), and SaveXML().
bool ODDecodeBlockFile::Read256 (float * buffer, sampleCount start, sampleCount len) [virtual]
Returns the 256 byte summary data block.
Reimplemented from BlockFile.
References IsSummaryAvailable().
bool ODDecodeBlockFile::Read64K (float * buffer, sampleCount start, sampleCount len) [virtual]
Returns the 64K summary data block.
Reimplemented from BlockFile.
References IsSummaryAvailable().
int ODDecodeBlockFile::ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len) [virtual]
Reads the specified data from the aliased file using libsndfile.
Reads the specified data from the aliased file, using libsndfile, and converts it to the given sample format.
Parameters:
data The buffer to read the sample data into.
format The format to convert the data into
start The offset within the block to begin reading
len The number of samples to read
Reimplemented from SimpleBlockFile.
References ClearSamples(), IsSummaryAvailable(), LockRead(), and UnlockRead().
bool ODDecodeBlockFile::ReadSummary (void * data) [virtual]
Read the summary into a buffer.
Read the summary of this alias block from disk. Since the audio data is elsewhere, this consists of reading the entire summary file.
Parameters:
*data The buffer where the summary data will be stored. It must be at least mSummaryInfo.totalSummaryBytes long.
Reimplemented from SimpleBlockFile.
References IsSummaryAvailable(), BlockFile::mSummaryInfo, and SummaryInfo::totalSummaryBytes.
void ODDecodeBlockFile::Recover (void) [virtual]
Writes the summary file if summary data is available.
Reimplemented from SimpleBlockFile.
References IsSummaryAvailable(), and WriteODDecodeBlockFile().
void ODDecodeBlockFile::SaveXML (XMLWriter & xmlFile) [virtual]
Saves as xml ODPCMAliasBlockFile or PCMAliasBlockFile depending on summary availability.
Writes the xml as a SimpleBlockFile if we can (if we have a summary file) Otherwise writes XML as a subset of attributes with 'odpcmaliasblockfile as the start tag. Most notably, the summaryfile attribute refers to a file that does not yet, so when the project file is read back in and this object reconstructed, it needs to avoid trying to open it as well as schedule itself for OD loading
Reimplemented from SimpleBlockFile.
References XMLWriter::EndTag(), IsSummaryAvailable(), LockRead(), mAliasChannel, mAliasStart, mAudioFileName, BlockFile::mFileName, mFileNameMutex, BlockFile::mLen, mType, XMLWriter::StartTag(), UnlockRead(), and XMLWriter::WriteAttr().
void ODDecodeBlockFile::SetClipOffset (sampleCount numSamples) [inline]
sets the amount of samples the clip associated with this blockfile is offset in the wavetrack (non effecting)
References mClipOffset.
virtual void ODDecodeBlockFile::SetDecodeType (unsigned int type) [inline, virtual]
References mType.
void ODDecodeBlockFile::SetFileName (wxFileName & name) [virtual]
sets the file name the summary info will be saved in. threadsafe.
Reimplemented from BlockFile.
References BlockFile::mFileName, and mFileNameMutex.
void ODDecodeBlockFile::SetODFileDecoder (ODFileDecoder * decoder)
set the decoder,
References mDecoder, and mDecoderMutex.
Referenced by ODDecodeTask::DoSomeInternal().
void ODDecodeBlockFile::SetStart (sampleCount startSample) [inline]
Sets the value that indicates where the first sample in this block corresponds to the global sequence/clip. Only for display use.
References mStart.
void ODDecodeBlockFile::UnlockRead () [virtual]
Allows reading of encoded file on other threads.
Reimplemented from BlockFile.
References mReadDataMutex.
Referenced by Copy(), ODDecodeTask::DoSomeInternal(), DirManager::EnsureSafeFilename(), ReadData(), and SaveXML().
void ODDecodeBlockFile::WriteODDecodeBlockFile ()
Write the summary to disk, using the derived ReadData() to get the data Here, the decoder ODTask associated with this file must fetch the samples with the ODDecodeTask::Decode() method.
References ODFileDecoder::Decode(), DeleteSamples(), mAliasChannel, mAliasStart, mDataAvailable, mDataAvailableMutex, mDecoder, mDecoderMutex, mFileNameMutex, mFormat, BlockFile::mLen, and SimpleBlockFile::WriteSimpleBlockFile().
Referenced by DoWriteBlockFile(), and Recover().
Member Data Documentation
int ODDecodeBlockFile::mAliasChannel [protected]
Referenced by Copy(), SaveXML(), and WriteODDecodeBlockFile().
sampleCount ODDecodeBlockFile::mAliasStart [protected]
Referenced by Copy(), SaveXML(), and WriteODDecodeBlockFile().
wxFileName ODDecodeBlockFile::mAudioFileName [protected]
The original file the audio came from.
Referenced by ChangeAudioFile(), Copy(), GetAudioFileName(), GetEncodedAudioFilename(), ODDecodeBlockFile(), and SaveXML().
sampleCount ODDecodeBlockFile::mClipOffset [protected]
the ODTask needs to know where this blockfile lies in the track, so for convenience, we have this here.
Referenced by GetClipOffset(), and SetClipOffset().
bool ODDecodeBlockFile::mDataAvailable [protected]
Referenced by IsDataAvailable(), ODDecodeBlockFile(), and WriteODDecodeBlockFile().
ODLock ODDecodeBlockFile::mDataAvailableMutex [protected]
Referenced by IsDataAvailable(), and WriteODDecodeBlockFile().
bool ODDecodeBlockFile::mDataBeingComputed [protected]
ODFileDecoder* ODDecodeBlockFile::mDecoder [protected]
Referenced by SetODFileDecoder(), and WriteODDecodeBlockFile().
ODLock ODDecodeBlockFile::mDecoderMutex [protected]
Referenced by SetODFileDecoder(), and WriteODDecodeBlockFile().
ODLock ODDecodeBlockFile::mFileNameMutex [protected]
This lock is for the filename (string) of the blockfile that contains summary/audio data after decoding
Referenced by GetFileName(), SaveXML(), SetFileName(), and WriteODDecodeBlockFile().
sampleFormat ODDecodeBlockFile::mFormat [protected]
Referenced by WriteODDecodeBlockFile().
ODLock ODDecodeBlockFile::mReadDataMutex [protected]
For accessing the audio file that will be decoded. Used by dir manager;.
Referenced by LockRead(), and UnlockRead().
sampleCount ODDecodeBlockFile::mStart [protected]
for reporting after task is complete. Only for display use.
Referenced by GetStart(), and SetStart().
unsigned int ODDecodeBlockFile::mType [protected]
Referenced by Copy(), GetDecodeType(), SaveXML(), and SetDecodeType().
The documentation for this class was generated from the following files:
ODDecodeBlockFile.h
ODDecodeBlockFile.cpp