Audacity: Grabber Class Reference
Grabber Class Reference
The widget to the left of a ToolBar that allows it to be dragged around to new positions.
#include <Grabber.h>
Public Member Functions
Grabber (wxWindow *parent, wxWindowID id)
virtual ~Grabber ()
bool AcceptsFocus () const
void PushButton (bool state)
DECLARE_EVENT_TABLE ()
Protected Member Functions
void OnLeftDown (wxMouseEvent &event)
void OnEnter (wxMouseEvent &event)
void OnLeave (wxMouseEvent &event)
void OnPaint (wxPaintEvent &event)
Private Member Functions
void DrawGrabber (wxDC &dc)
void SendEvent (wxEventType type, const wxPoint &pos)
Private Attributes
bool mOver
bool mPressed
Detailed Description
The widget to the left of a ToolBar that allows it to be dragged around to new positions.
Constructor & Destructor Documentation
Grabber::Grabber (wxWindow * parent, wxWindowID id)
Methods for Grabber
Grabber::~Grabber () [virtual]
Member Function Documentation
bool Grabber::AcceptsFocus () const [inline]
Grabber::DECLARE_EVENT_TABLE ()
void Grabber::DrawGrabber (wxDC & dc) [private]
References AColor::Bevel(), AColor::Dark(), AColor::Light(), AColor::Line(), AColor::Medium(), mOver, and mPressed.
Referenced by OnPaint().
void Grabber::OnEnter (wxMouseEvent & event) [protected]
References mOver.
void Grabber::OnLeave (wxMouseEvent & event) [protected]
References mOver.
void Grabber::OnLeftDown (wxMouseEvent & event) [protected]
References PushButton(), and SendEvent().
void Grabber::OnPaint (wxPaintEvent & event) [protected]
References DrawGrabber().
void Grabber::PushButton (bool state)
References mOver, and mPressed.
Referenced by OnLeftDown(), and ToolBar::SetDocked().
void Grabber::SendEvent (wxEventType type, const wxPoint & pos) [private]
Referenced by OnLeftDown().
Member Data Documentation
bool Grabber::mOver [private]
Referenced by DrawGrabber(), OnEnter(), OnLeave(), and PushButton().
bool Grabber::mPressed [private]
Referenced by DrawGrabber(), and PushButton().
The documentation for this class was generated from the following files:
Grabber.h
Grabber.cpp