Audacity: MeterToolBar Class Reference
MeterToolBar Class Reference
A ToolBar that holds the VU Meter.
#include <MeterToolBar.h>
Public Member Functions
MeterToolBar ()
virtual ~MeterToolBar ()
void Create (wxWindow *parent)
bool DestroyChildren ()
virtual void Populate ()
virtual void Repaint (wxDC *dc)
virtual void EnableDisableButtons ()
virtual void UpdatePrefs ()
void GetMeters (Meter **playMeter, Meter **recordMeter)
void StartMonitoring ()
void Clear ()
virtual void OnSize (wxSizeEvent &event)
DECLARE_CLASS (MeterToolBar)
DECLARE_EVENT_TABLE ()
Private Member Functions
void RegenerateTooltips ()
Private Attributes
wxGridBagSizer * mSizer
Meter * mPlayMeter
Meter * mRecordMeter
Detailed Description
A ToolBar that holds the VU Meter.
Constructor & Destructor Documentation
MeterToolBar::MeterToolBar ()
Methods for MeterToolBar
MeterToolBar::~MeterToolBar () [virtual]
Member Function Documentation
void MeterToolBar::Clear ()
References Meter::Clear(), mPlayMeter, and mRecordMeter.
Referenced by ControlToolBar::StopPlaying().
void MeterToolBar::Create (wxWindow * parent) [virtual]
Reimplemented from ToolBar.
References OnSize().
MeterToolBar::DECLARE_CLASS (MeterToolBar)
Reimplemented from ToolBar.
MeterToolBar::DECLARE_EVENT_TABLE ()
Reimplemented from ToolBar.
bool MeterToolBar::DestroyChildren ()
References gAudioIO, AudioIO::IsBusy(), mPlayMeter, mRecordMeter, and AudioIO::SetMeters().
virtual void MeterToolBar::EnableDisableButtons () [inline, virtual]
Implements ToolBar.
void MeterToolBar::GetMeters (Meter ** playMeter, Meter ** recordMeter)
References mPlayMeter, and mRecordMeter.
Referenced by ControlToolBar::SetVUMeters(), and Meter::StartMonitoring().
void MeterToolBar::OnSize (wxSizeEvent & event) [virtual]
References ToolBar::GetSizer(), Meter::HorizontalStereo, mPlayMeter, mRecordMeter, mSizer, Meter::SetStyle(), and Meter::VerticalStereo.
Referenced by Create().
void MeterToolBar::Populate () [virtual]
Implements ToolBar.
References ToolBar::Add(), gAudioIO, AudioIO::IsBusy(), mPlayMeter, mRecordMeter, mSizer, RegenerateTooltips(), and AudioIO::SetMeters().
void MeterToolBar::RegenerateTooltips () [private]
References mPlayMeter, and mRecordMeter.
Referenced by Populate(), and UpdatePrefs().
virtual void MeterToolBar::Repaint (wxDC * dc) [inline, virtual]
Implements ToolBar.
void MeterToolBar::StartMonitoring ()
References mRecordMeter, and Meter::StartMonitoring().
Referenced by AudacityProject::MayStartMonitoring().
void MeterToolBar::UpdatePrefs () [virtual]
Reimplemented from ToolBar.
References Meter::HandleLayout(), mPlayMeter, mRecordMeter, RegenerateTooltips(), ToolBar::SetLabel(), and Meter::UpdatePrefs().
Member Data Documentation
Meter* MeterToolBar::mPlayMeter [private]
Referenced by Clear(), DestroyChildren(), GetMeters(), OnSize(), Populate(), RegenerateTooltips(), and UpdatePrefs().
Meter* MeterToolBar::mRecordMeter [private]
Referenced by Clear(), DestroyChildren(), GetMeters(), OnSize(), Populate(), RegenerateTooltips(), StartMonitoring(), and UpdatePrefs().
wxGridBagSizer* MeterToolBar::mSizer [private]
Referenced by OnSize(), and Populate().
The documentation for this class was generated from the following files:
MeterToolBar.h
MeterToolBar.cpp