Audacity: ToneGenDialog Class Reference
ToneGenDialog Class Reference
Dialog used with EffectToneGen.
#include <ToneGen.h>
Public Member Functions
ToneGenDialog (EffectToneGen *effect, wxWindow *parent, const wxString &title)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
EffectToneGen * mEffect
bool mbChirp
wxArrayString * waveforms
int waveform
double frequency [2]
double amplitude [2]
double mDuration
bool isSelection
int interpolation
wxArrayString * interpolations
Private Member Functions
void PopulateOrExchangeStandard (ShuttleGui &S)
Populates simple dialog that has a single tone.
void PopulateOrExchangeExtended (ShuttleGui &S)
Populates more complex dialog that has a chirp.
void OnTimeCtrlUpdate (wxCommandEvent &event)
Private Attributes
TimeTextCtrl * mToneDurationT
Detailed Description
Dialog used with EffectToneGen.
Constructor & Destructor Documentation
ToneGenDialog::ToneGenDialog (EffectToneGen * effect, wxWindow * parent, const wxString & title)
Member Function Documentation
void ToneGenDialog::OnTimeCtrlUpdate (wxCommandEvent & event) [private]
void ToneGenDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References mbChirp, PopulateOrExchangeExtended(), and PopulateOrExchangeStandard().
void ToneGenDialog::PopulateOrExchangeExtended (ShuttleGui & S) [private]
Populates more complex dialog that has a chirp.
References ShuttleGuiBase::AddFixedText(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddWindow(), amplitude, TimeTextCtrl::EnableMenu(), ShuttleGuiBase::EndMultiColumn(), frequency, TimeTextCtrl::GetBuiltinFormat(), interpolation, interpolations, isSelection, mDuration, mEffect, Effect::mProjectRate, mToneDurationT, TimeTextCtrl::SetFormatString(), ShuttleGui::SetSizeHints(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::TieChoice(), ShuttleGuiBase::TieTextBox(), waveform, and waveforms.
Referenced by PopulateOrExchange().
void ToneGenDialog::PopulateOrExchangeStandard (ShuttleGui & S) [private]
Populates simple dialog that has a single tone.
References ShuttleGuiBase::AddFixedText(), ShuttleGuiBase::AddWindow(), amplitude, TimeTextCtrl::EnableMenu(), ShuttleGuiBase::EndMultiColumn(), frequency, TimeTextCtrl::GetBuiltinFormat(), isSelection, mDuration, mEffect, Effect::mProjectRate, mToneDurationT, TimeTextCtrl::SetFormatString(), ShuttleGui::SetSizeHints(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::TieChoice(), ShuttleGuiBase::TieTextBox(), waveform, and waveforms.
Referenced by PopulateOrExchange().
bool ToneGenDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References AMP_MAX, AMP_MIN, amplitude, FREQ_MIN, frequency, GetActiveProject(), TimeTextCtrl::GetTimeValue(), mDuration, mToneDurationT, and TrapDouble().
bool ToneGenDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References mDuration, mToneDurationT, and TimeTextCtrl::SetTimeValue().
Referenced by EffectToneGen::PromptUser().
Member Data Documentation
double ToneGenDialog::amplitude[2]
Referenced by PopulateOrExchangeExtended(), PopulateOrExchangeStandard(), EffectToneGen::PromptUser(), and TransferDataFromWindow().
double ToneGenDialog::frequency[2]
Referenced by PopulateOrExchangeExtended(), PopulateOrExchangeStandard(), EffectToneGen::PromptUser(), and TransferDataFromWindow().
int ToneGenDialog::interpolation
Referenced by PopulateOrExchangeExtended(), and EffectToneGen::PromptUser().
wxArrayString* ToneGenDialog::interpolations
Referenced by PopulateOrExchangeExtended(), and EffectToneGen::PromptUser().
bool ToneGenDialog::isSelection
Referenced by PopulateOrExchangeExtended(), PopulateOrExchangeStandard(), and EffectToneGen::PromptUser().
bool ToneGenDialog::mbChirp
Referenced by PopulateOrExchange(), and EffectToneGen::PromptUser().
double ToneGenDialog::mDuration
Referenced by PopulateOrExchangeExtended(), PopulateOrExchangeStandard(), EffectToneGen::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
EffectToneGen* ToneGenDialog::mEffect
Referenced by PopulateOrExchangeExtended(), and PopulateOrExchangeStandard().
TimeTextCtrl* ToneGenDialog::mToneDurationT [private]
Referenced by PopulateOrExchangeExtended(), PopulateOrExchangeStandard(), TransferDataFromWindow(), and TransferDataToWindow().
int ToneGenDialog::waveform
Referenced by PopulateOrExchangeExtended(), PopulateOrExchangeStandard(), and EffectToneGen::PromptUser().
wxArrayString* ToneGenDialog::waveforms
Referenced by PopulateOrExchangeExtended(), PopulateOrExchangeStandard(), and EffectToneGen::PromptUser().
The documentation for this class was generated from the following files:
ToneGen.h
ToneGen.cpp