Audacity: DtmfDialog Class Reference
DtmfDialog Class Reference
#include <DtmfGen.h>
Public Member Functions
DtmfDialog (EffectDtmf *effect, wxWindow *parent, const wxString &title)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
wxString dString
int dNTones
double dTone
double dSilence
double dDuration
double dDutyCycle
double dAmplitude
bool dIsSelection
Private Member Functions
void OnDtmfStringText (wxCommandEvent &event)
void OnDtmfDurationText (wxCommandEvent &event)
void OnDutyCycleSlider (wxCommandEvent &event)
void OnTimeCtrlUpdate (wxCommandEvent &event)
void Recalculate (void)
Private Attributes
EffectDtmf * mEffect
wxSlider * mDtmfDutyS
wxTextCtrl * mDtmfStringT
TimeTextCtrl * mDtmfDurationT
wxStaticText * mDtmfToneT
wxStaticText * mDtmfSilenceT
wxStaticText * mDtmfDutyT
Constructor & Destructor Documentation
DtmfDialog::DtmfDialog (EffectDtmf * effect, wxWindow * parent, const wxString & title)
Member Function Documentation
void DtmfDialog::OnDtmfDurationText (wxCommandEvent & event) [private]
References Recalculate().
void DtmfDialog::OnDtmfStringText (wxCommandEvent & event) [private]
References Recalculate().
void DtmfDialog::OnDutyCycleSlider (wxCommandEvent & event) [private]
References Recalculate().
void DtmfDialog::OnTimeCtrlUpdate (wxCommandEvent & event) [private]
void DtmfDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddFixedText(), ShuttleGuiBase::AddPrompt(), ShuttleGuiBase::AddSlider(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddVariableText(), ShuttleGuiBase::AddWindow(), dAmplitude, dDuration, dDutyCycle, dIsSelection, dSilence, dtmfSymbols, dTone, DUTY_MAX, DUTY_MIN, DUTY_SCALE, TimeTextCtrl::EnableMenu(), ShuttleGuiBase::EndMultiColumn(), TimeTextCtrl::GetBuiltinFormat(), ShuttleGui::Id(), ID_DTMF_DURATION_TEXT, ID_DTMF_DUTYCYCLE_SLIDER, ID_DTMF_DUTYCYCLE_TEXT, ID_DTMF_SILENCE_TEXT, ID_DTMF_STRING_TEXT, ID_DTMF_TONELEN_TEXT, mDtmfDurationT, mDtmfDutyS, mDtmfDutyT, mDtmfSilenceT, mDtmfStringT, mDtmfToneT, mEffect, Effect::mProjectRate, TimeTextCtrl::SetFormatString(), ShuttleGui::SetSizeHints(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartMultiColumn(), and ShuttleGuiBase::TieTextBox().
void DtmfDialog::Recalculate (void) [private]
References dDuration, dDutyCycle, dNTones, dSilence, dString, dTone, DUTY_MAX, DUTY_MIN, DUTY_SCALE, TimeTextCtrl::GetTimeValue(), mDtmfDurationT, mDtmfDutyS, mDtmfDutyT, mDtmfSilenceT, mDtmfStringT, mDtmfToneT, and TrapLong().
Referenced by OnDtmfDurationText(), OnDtmfStringText(), OnDutyCycleSlider(), and TransferDataFromWindow().
bool DtmfDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References AMP_MAX, AMP_MIN, dAmplitude, Recalculate(), and TrapDouble().
bool DtmfDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References dDuration, dDutyCycle, dString, mDtmfDurationT, mDtmfDutyS, mDtmfStringT, and TimeTextCtrl::SetTimeValue().
Member Data Documentation
double DtmfDialog::dAmplitude
Referenced by PopulateOrExchange(), EffectDtmf::PromptUser(), and TransferDataFromWindow().
double DtmfDialog::dDuration
Referenced by PopulateOrExchange(), EffectDtmf::PromptUser(), Recalculate(), and TransferDataToWindow().
double DtmfDialog::dDutyCycle
Referenced by PopulateOrExchange(), EffectDtmf::PromptUser(), Recalculate(), and TransferDataToWindow().
bool DtmfDialog::dIsSelection
Referenced by PopulateOrExchange(), and EffectDtmf::PromptUser().
int DtmfDialog::dNTones
Referenced by EffectDtmf::PromptUser(), and Recalculate().
double DtmfDialog::dSilence
Referenced by PopulateOrExchange(), EffectDtmf::PromptUser(), and Recalculate().
wxString DtmfDialog::dString
Referenced by EffectDtmf::PromptUser(), Recalculate(), and TransferDataToWindow().
double DtmfDialog::dTone
Referenced by PopulateOrExchange(), EffectDtmf::PromptUser(), and Recalculate().
TimeTextCtrl* DtmfDialog::mDtmfDurationT [private]
Referenced by PopulateOrExchange(), Recalculate(), and TransferDataToWindow().
wxSlider* DtmfDialog::mDtmfDutyS [private]
Referenced by PopulateOrExchange(), Recalculate(), and TransferDataToWindow().
wxStaticText* DtmfDialog::mDtmfDutyT [private]
Referenced by PopulateOrExchange(), and Recalculate().
wxStaticText* DtmfDialog::mDtmfSilenceT [private]
Referenced by PopulateOrExchange(), and Recalculate().
wxTextCtrl* DtmfDialog::mDtmfStringT [private]
Referenced by PopulateOrExchange(), Recalculate(), and TransferDataToWindow().
wxStaticText* DtmfDialog::mDtmfToneT [private]
Referenced by PopulateOrExchange(), and Recalculate().
EffectDtmf* DtmfDialog::mEffect [private]
Referenced by PopulateOrExchange().
The documentation for this class was generated from the following files:
DtmfGen.h
DtmfGen.cpp