Audacity: EffectAmplify Class Reference
EffectAmplify Class Reference
An EffectSimpleMono.
#include <Amplify.h>
Public Member Functions
EffectAmplify ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual wxString GetEffectDescription ()
virtual bool Init ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
Protected Member Functions
virtual bool ProcessSimpleMono (float *buffer, sampleCount len)
Private Attributes
float ratio
float peak
Friends
class AmplifyDialog
Detailed Description
An EffectSimpleMono.
This rewritten class supports a smart Amplify effect - it calculates the maximum amount of gain that can be applied to all tracks without causing clipping and selects this as the default parameter.
Constructor & Destructor Documentation
EffectAmplify::EffectAmplify ()
References peak, and ratio.
Member Function Documentation
virtual wxString EffectAmplify::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectAmplify::GetEffectCategories () [inline, virtual]
wxString EffectAmplify::GetEffectDescription () [virtual]
Reimplemented from Effect.
References GetEffectName(), and ratio.
virtual wxString EffectAmplify::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectAmplify::GetEffectName () [inline, virtual]
Implements Effect.
Referenced by GetEffectDescription().
bool EffectAmplify::Init () [virtual]
Reimplemented from Effect.
References TrackListCondIterator::First(), max, min(), Effect::mT0, Effect::mT1, Effect::mTracks, TrackListCondIterator::Next(), peak, and Track::Wave.
bool EffectAmplify::ProcessSimpleMono (float * buffer, sampleCount len) [protected, virtual]
Implements EffectSimpleMono.
References ratio.
bool EffectAmplify::PromptUser () [virtual]
Reimplemented from Effect.
References Effect::mParent, AmplifyDialog::noclip, peak, AmplifyDialog::peak, ratio, AmplifyDialog::ratio, and AmplifyDialog::TransferDataToWindow().
bool EffectAmplify::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References ratio, and Shuttle::TransferFloat().
Friends And Related Function Documentation
friend class AmplifyDialog [friend]
Member Data Documentation
float EffectAmplify::peak [private]
Referenced by EffectAmplify(), Init(), AmplifyDialog::OnPreview(), and PromptUser().
float EffectAmplify::ratio [private]
Referenced by EffectAmplify(), GetEffectDescription(), AmplifyDialog::OnPreview(), ProcessSimpleMono(), PromptUser(), and TransferParameters().
The documentation for this class was generated from the following files:
Amplify.h
Amplify.cpp