Audacity: NoteTrack Class Reference
NoteTrack Class Reference
A Track that is used for Midi notes. (Somewhat old code).
#include <NoteTrack.h>
Public Member Functions
NoteTrack (DirManager *projDirManager)
virtual ~NoteTrack ()
virtual Track * Duplicate ()
virtual int GetKind () const
virtual double GetStartTime ()
virtual double GetEndTime ()
void DrawLabelControls (wxDC &dc, wxRect &r)
bool LabelClick (wxRect &r, int x, int y, bool right)
void SetSequence (Alg_seq *seq)
Alg_seq * GetSequence ()
void PrintSequence ()
int GetVisibleChannels ()
bool ExportMIDI (wxString f)
bool ExportAllegro (wxString f)
virtual bool Cut (double t0, double t1, Track **dest)
virtual bool Copy (double t0, double t1, Track **dest)
virtual bool Clear (double t0, double t1)
virtual bool Paste (double t, Track *src)
int GetBottomNote () const
void SetBottomNote (int note)
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
Private Attributes
Alg_seq * mSeq
char * mSerializationBuffer
long mSerializationLength
double mLen
DirManager * mDirManager
int mBottomNote
int mVisibleChannels
int mLastMidiPosition
Friends
class TrackArtist
Detailed Description
A Track that is used for Midi notes. (Somewhat old code).
Constructor & Destructor Documentation
NoteTrack::NoteTrack (DirManager * projDirManager)
References Track::GetDefaultName(), mBottomNote, mDirManager, mLastMidiPosition, mLen, mSeq, mSerializationBuffer, mSerializationLength, mVisibleChannels, Track::SetDefaultName(), and Track::SetName().
Referenced by Copy(), Cut(), and Duplicate().
NoteTrack::~NoteTrack () [virtual]
References mSeq, and mSerializationBuffer.
Member Function Documentation
bool NoteTrack::Clear (double t0, double t1) [virtual]
Reimplemented from Track.
References mSeq.
bool NoteTrack::Copy (double t0, double t1, Track ** dest) [virtual]
References Track::Init(), mDirManager, mLen, mSeq, and NoteTrack().
bool NoteTrack::Cut (double t0, double t1, Track ** dest) [virtual]
References Track::Init(), mDirManager, mLen, mSeq, and NoteTrack().
void NoteTrack::DrawLabelControls (wxDC & dc, wxRect & r)
References AColor::DarkMIDIChannel(), AColor::LightMIDIChannel(), AColor::Line(), AColor::MIDIChannel(), and mVisibleChannels.
Track * NoteTrack::Duplicate () [virtual]
Implements Track.
References mBottomNote, mDirManager, mLastMidiPosition, mLen, mSeq, mSerializationBuffer, mSerializationLength, mVisibleChannels, and NoteTrack().
bool NoteTrack::ExportAllegro (wxString f)
References mSeq.
Referenced by AudacityProject::OnExportMIDI().
bool NoteTrack::ExportMIDI (wxString f)
References mSeq.
Referenced by AudacityProject::OnExportMIDI().
int NoteTrack::GetBottomNote () const [inline]
Referenced by TrackArtist::DrawNoteTrack().
virtual double NoteTrack::GetEndTime () [inline, virtual]
Reimplemented from Track.
virtual int NoteTrack::GetKind () const [inline, virtual]
Reimplemented from Track.
Alg_seq * NoteTrack::GetSequence ()
References mSeq.
virtual double NoteTrack::GetStartTime () [inline, virtual]
Reimplemented from Track.
int NoteTrack::GetVisibleChannels ()
References mVisibleChannels.
XMLTagHandler * NoteTrack::HandleXMLChild (const wxChar * tag) [virtual]
Implements Track.
bool NoteTrack::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements Track.
bool NoteTrack::LabelClick (wxRect & r, int x, int y, bool right)
References mVisibleChannels.
bool NoteTrack::Paste (double t, Track * src) [virtual]
References Track::GetKind(), mLen, mSeq, and Track::Note.
void NoteTrack::PrintSequence ()
References mSeq.
void NoteTrack::SetBottomNote (int note) [inline]
void NoteTrack::SetSequence (Alg_seq * seq)
Referenced by ImportMIDI().
void NoteTrack::WriteXML (XMLWriter & xmlFile) [virtual]
Implements Track.
Friends And Related Function Documentation
friend class TrackArtist [friend]
Member Data Documentation
int NoteTrack::mBottomNote [private]
Referenced by Duplicate(), and NoteTrack().
DirManager* NoteTrack::mDirManager [private]
Reimplemented from Track.
Referenced by Copy(), Cut(), Duplicate(), and NoteTrack().
int NoteTrack::mLastMidiPosition [private]
Referenced by Duplicate(), and NoteTrack().
double NoteTrack::mLen [private]
Referenced by Copy(), Cut(), Duplicate(), NoteTrack(), and Paste().
Alg_seq* NoteTrack::mSeq [private]
Referenced by Clear(), Copy(), Cut(), TrackArtist::DrawNoteTrack(), Duplicate(), ExportAllegro(), ExportMIDI(), GetSequence(), NoteTrack(), Paste(), PrintSequence(), and ~NoteTrack().
char* NoteTrack::mSerializationBuffer [private]
Referenced by TrackArtist::DrawNoteTrack(), Duplicate(), NoteTrack(), and ~NoteTrack().
long NoteTrack::mSerializationLength [private]
Referenced by TrackArtist::DrawNoteTrack(), Duplicate(), and NoteTrack().
int NoteTrack::mVisibleChannels [private]
Referenced by DrawLabelControls(), TrackArtist::DrawNoteTrack(), Duplicate(), GetVisibleChannels(), LabelClick(), and NoteTrack().
The documentation for this class was generated from the following files:
NoteTrack.h
NoteTrack.cpp