Audacity: CommandSignature Class Reference
CommandSignature Class Reference
Class that maps parameter names to default values and validators.
#include <CommandSignature.h>
Public Member Functions
CommandSignature ()
~CommandSignature ()
void AddParameter (const wxString &name, const wxVariant &dft, Validator *valid)
ParamValueMap GetDefaults () const
Validator & GetValidator (const wxString &paramName)
Private Member Functions
CommandSignature (const CommandSignature &other)
Private Attributes
ParamValueMap mDefaults
ValidatorMap mValidators
Detailed Description
Class that maps parameter names to default values and validators.
Constructor & Destructor Documentation
CommandSignature::CommandSignature (const CommandSignature & other) [inline, explicit, private]
CommandSignature::CommandSignature () [inline, explicit]
CommandSignature::~CommandSignature ()
References mValidators.
Member Function Documentation
void CommandSignature::AddParameter (const wxString & name, const wxVariant & dft, Validator * valid)
References Validator::GetDescription(), mDefaults, mValidators, and Validator::Validate().
Referenced by SetTrackInfoCommandType::BuildSignature(), SetProjectInfoCommandType::BuildSignature(), SelectCommandType::BuildSignature(), ScreenshotCommandType::BuildSignature(), SetPreferenceCommandType::BuildSignature(), GetPreferenceCommandType::BuildSignature(), MessageCommandType::BuildSignature(), ExportCommandType::BuildSignature(), ImportCommandType::BuildSignature(), HelpCommandType::BuildSignature(), GetTrackInfoCommandType::BuildSignature(), GetProjectInfoCommandType::BuildSignature(), GetAllMenuCommandsType::BuildSignature(), ExecMenuCommandType::BuildSignature(), CompareAudioCommandType::BuildSignature(), and BatchEvalCommandType::BuildSignature().
ParamValueMap CommandSignature::GetDefaults () const
References mDefaults.
Referenced by CommandBuilder::BuildCommand(), and CommandType::Describe().
Validator & CommandSignature::GetValidator (const wxString & paramName)
References mValidators.
Referenced by CommandType::Describe(), and CommandImplementation::SetParameter().
Member Data Documentation
ParamValueMap CommandSignature::mDefaults [private]
Referenced by AddParameter(), and GetDefaults().
ValidatorMap CommandSignature::mValidators [private]
Referenced by AddParameter(), GetValidator(), and ~CommandSignature().
The documentation for this class was generated from the following files:
CommandSignature.h
CommandSignature.cpp