Audacity: EffectTruncSilence Class Reference
EffectTruncSilence Class Reference
An Effect.
#include <TruncSilence.h>
Public Member Functions
EffectTruncSilence ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool Init ()
virtual void End ()
virtual bool CheckWhetherSkipEffect ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Process ()
Private Member Functions
void BlendFrames (float *buffer, int leftIndex, int rightIndex, int blendFrameCount)
Private Attributes
sampleCount mBlendFrameCount
int mTruncInitialAllowedSilentMs
int mTruncLongestAllowedSilentMs
int mTruncDbChoiceIndex
double mSilenceCompressRatio
Friends
class TruncSilenceDialog
Detailed Description
An Effect.
Todo:
mBlendFrameCount only retrieved from prefs ... not using dialog Only way to change (for windows) is thru registry The values should be figured dynamically ... too many frames could be invalid
Constructor & Destructor Documentation
EffectTruncSilence::EffectTruncSilence ()
References Init().
Member Function Documentation
void EffectTruncSilence::BlendFrames (float * buffer, int leftIndex, int rightIndex, int blendFrameCount) [private]
bool EffectTruncSilence::CheckWhetherSkipEffect () [virtual]
Reimplemented from Effect.
References mTruncDbChoiceIndex, mTruncLongestAllowedSilentMs, Enums::NumDbChoices, and SKIP_EFFECT_MILLISECOND.
void EffectTruncSilence::End () [virtual]
Reimplemented from Effect.
virtual wxString EffectTruncSilence::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectTruncSilence::GetEffectCategories () [inline, virtual]
virtual wxString EffectTruncSilence::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectTruncSilence::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectTruncSilence::Init () [virtual]
Reimplemented from Effect.
References gPrefs, mBlendFrameCount, mSilenceCompressRatio, mTruncDbChoiceIndex, mTruncInitialAllowedSilentMs, mTruncLongestAllowedSilentMs, Enums::NumDbChoices, and SKIP_EFFECT_MILLISECOND.
Referenced by EffectTruncSilence().
bool EffectTruncSilence::Process () [virtual]
Implements Effect.
References Track::All, WaveTrack::Clear(), Effect::CopyInputTracks(), Enums::Db2Signal, TrackListCondIterator::First(), floatSample, WaveTrack::Get(), GetActiveProject(), WaveTrack::GetEndTime(), WaveTrack::GetMaxBlockSize(), WaveTrack::GetRate(), WaveTrack::GetStartTime(), mBlendFrameCount, Effect::mOutputTracks, mSilenceCompressRatio, Effect::mT0, Effect::mT1, Effect::mTracks, mTruncDbChoiceIndex, mTruncInitialAllowedSilentMs, mTruncLongestAllowedSilentMs, TrackListCondIterator::Next(), Effect::ReplaceProcessedTracks(), WaveTrack::Set(), WaveTrack::TimeToLongSamples(), Effect::TrackProgress(), and Track::Wave.
bool EffectTruncSilence::PromptUser () [virtual]
Reimplemented from Effect.
References gPrefs, Effect::mParent, mSilenceCompressRatio, mTruncDbChoiceIndex, mTruncInitialAllowedSilentMs, and mTruncLongestAllowedSilentMs.
bool EffectTruncSilence::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References Enums::GetDbChoices(), mSilenceCompressRatio, mTruncDbChoiceIndex, mTruncInitialAllowedSilentMs, mTruncLongestAllowedSilentMs, Enums::NumDbChoices, Shuttle::TransferDouble(), Shuttle::TransferEnum(), and Shuttle::TransferInt().
Friends And Related Function Documentation
friend class TruncSilenceDialog [friend]
Member Data Documentation
sampleCount EffectTruncSilence::mBlendFrameCount [private]
Referenced by Init(), and Process().
double EffectTruncSilence::mSilenceCompressRatio [private]
Referenced by Init(), TruncSilenceDialog::OnDurationChange(), TruncSilenceDialog::PopulateOrExchange(), Process(), PromptUser(), and TransferParameters().
int EffectTruncSilence::mTruncDbChoiceIndex [private]
Referenced by CheckWhetherSkipEffect(), Init(), TruncSilenceDialog::PopulateOrExchange(), Process(), PromptUser(), and TransferParameters().
int EffectTruncSilence::mTruncInitialAllowedSilentMs [private]
Referenced by Init(), TruncSilenceDialog::OnDurationChange(), TruncSilenceDialog::PopulateOrExchange(), Process(), PromptUser(), and TransferParameters().
int EffectTruncSilence::mTruncLongestAllowedSilentMs [private]
Referenced by CheckWhetherSkipEffect(), Init(), TruncSilenceDialog::OnDurationChange(), TruncSilenceDialog::PopulateOrExchange(), Process(), PromptUser(), and TransferParameters().
The documentation for this class was generated from the following files:
TruncSilence.h
TruncSilence.cpp