Audacity: PluginManager Class Reference
PluginManager Class Reference
#include <PluginManager.h>
Public Member Functions
PluginManager ()
virtual ~PluginManager ()
void Open ()
void Close ()
wxString Read (const wxString &key, const wxString &def)
long Read (const wxString &key, long def)
void Write (const wxString &key, const wxString &val)
void Write (const wxString &key, long val)
bool HasType (const wxString &type)
void PurgeType (const wxString &type)
int GetPluginCount (const wxString &type)
wxString GetPlugin (const wxString &type, int index)
wxString GetFirstPlugin (const wxString &type)
wxString GetNextPlugin (const wxString &type)
bool IsRegistered (const wxString &type, const wxString &path)
void RegisterPlugin (const wxString &type, const wxString &path)
bool IsPluginEnabled (const wxString &type, const wxString &path)
void EnablePlugin (const wxString &type, const wxString &path, bool enable)
Static Public Member Functions
static PluginManager & Get (bool refresh=false)
Private Member Functions
bool IsDirty ()
void SetDirty (bool dirty=true)
Private Attributes
wxFileConfig * mConfig
bool mDirty
int mCurrentIndex
Constructor & Destructor Documentation
PluginManager::PluginManager ()
References mConfig, and mDirty.
PluginManager::~PluginManager () [virtual]
References Close(), and mConfig.
Member Function Documentation
void PluginManager::Close ()
References IsDirty(), mConfig, FileNames::PluginsCache(), and SetDirty().
Referenced by Open(), and ~PluginManager().
void PluginManager::EnablePlugin (const wxString & type, const wxString & path, bool enable)
References GetPlugin(), GetPluginCount(), mConfig, and SetDirty().
PluginManager & PluginManager::Get (bool refresh = false) [static]
wxString PluginManager::GetFirstPlugin (const wxString & type)
References mConfig, and mCurrentIndex.
wxString PluginManager::GetNextPlugin (const wxString & type)
References mConfig, and mCurrentIndex.
wxString PluginManager::GetPlugin (const wxString & type, int index)
References mConfig.
Referenced by EnablePlugin(), IsPluginEnabled(), and IsRegistered().
int PluginManager::GetPluginCount (const wxString & type)
References mConfig.
Referenced by EnablePlugin(), IsPluginEnabled(), IsRegistered(), and RegisterPlugin().
bool PluginManager::HasType (const wxString & type)
References mConfig.
bool PluginManager::IsDirty () [private]
References mDirty.
Referenced by Close().
bool PluginManager::IsPluginEnabled (const wxString & type, const wxString & path)
References GetPlugin(), GetPluginCount(), and mConfig.
bool PluginManager::IsRegistered (const wxString & type, const wxString & path)
References GetPlugin(), and GetPluginCount().
Referenced by RegisterPlugin().
void PluginManager::Open ()
References Close(), mConfig, name, and FileNames::PluginsCache().
void PluginManager::PurgeType (const wxString & type)
References mConfig.
long PluginManager::Read (const wxString & key, long def)
References mConfig.
wxString PluginManager::Read (const wxString & key, const wxString & def)
References mConfig.
void PluginManager::RegisterPlugin (const wxString & type, const wxString & path)
References GetPluginCount(), IsRegistered(), mConfig, and SetDirty().
void PluginManager::SetDirty (bool dirty = true) [private]
References mDirty.
Referenced by Close(), EnablePlugin(), RegisterPlugin(), and Write().
void PluginManager::Write (const wxString & key, long val)
References mConfig, and SetDirty().
void PluginManager::Write (const wxString & key, const wxString & val)
References mConfig, and SetDirty().
Member Data Documentation
wxFileConfig* PluginManager::mConfig [private]
Referenced by Close(), EnablePlugin(), GetFirstPlugin(), GetNextPlugin(), GetPlugin(), GetPluginCount(), HasType(), IsPluginEnabled(), Open(), PluginManager(), PurgeType(), Read(), RegisterPlugin(), Write(), and ~PluginManager().
int PluginManager::mCurrentIndex [private]
Referenced by GetFirstPlugin(), and GetNextPlugin().
bool PluginManager::mDirty [private]
Referenced by IsDirty(), PluginManager(), and SetDirty().
The documentation for this class was generated from the following files:
PluginManager.h
PluginManager.cpp