Audacity: ThemeBase Class Reference
ThemeBase Class Reference
Theme management - Image loading and saving.
#include <Theme.h>
Public Member Functions
ThemeBase (void)
virtual ~ThemeBase (void)
virtual void EnsureInitialised ()=0
virtual void ApplyUpdatedImages ()=0
void LoadThemeAtStartUp (bool bLookForExternalFiles)
void RegisterImage (int &iIndex, char const **pXpm, const wxString &Name)
void RegisterImage (int &iIndex, const wxImage &Image, const wxString &Name)
void RegisterColour (int &iIndex, const wxColour &Clr, const wxString &Name)
void CreateImageCache (bool bBinarySave=true)
bool ReadImageCache (bool bBinaryRead=true, bool bOkIfNotFound=false)
void LoadComponents (bool bOkIfNotFound=false)
void SaveComponents ()
void ReadThemeInternal ()
void SaveThemeAsCode ()
void WriteImageDefs ()
Writes a series of Macro definitions that can be used in the include file.
void WriteImageMap ()
wxColour & Colour (int iIndex)
wxBitmap & Bitmap (int iIndex)
wxImage & Image (int iIndex)
wxCursor & Cursor (int iIndex)
wxFont & Font (int iIndex)
wxSize ImageSize (int iIndex)
void ReplaceImage (int iIndex, wxImage *pImage)
Replaces both the image and the bitmap.
void SetBrushColour (wxBrush &Brush, int iIndex)
void SetPenColour (wxPen &Pen, int iIndex)
void SetFlags (int flags)
wxImage MaskedImage (char const **pXpm, char const **pMask)
wxImage MakeImageWithAlpha (wxBitmap &Bmp)
Protected Attributes
ArrayOfImages mImages
ArrayOfBitmaps mBitmaps
wxArrayString mBitmapNames
wxArrayInt mBitmapFlags
ArrayOfColours mColours
wxArrayString mColourNames
FlowPacker mFlow
Detailed Description
Theme management - Image loading and saving.
Base for the Theme class. ThemeBase is a generic non-Audacity specific class.
See also:
Themability
Constructor & Destructor Documentation
ThemeBase::ThemeBase (void)
ThemeBase::~ThemeBase (void) [virtual]
Member Function Documentation
virtual void ThemeBase::ApplyUpdatedImages () [pure virtual]
Implemented in Theme.
wxBitmap & ThemeBase::Bitmap (int iIndex)
References EnsureInitialised(), and mBitmaps.
Referenced by AudacityProject::AudacityProject(), LWSlider::Draw(), LabelTrack::GetGlyph(), MixerToolBar::Populate(), DeviceToolBar::Populate(), ReplaceImage(), ShowHtmlText(), and UploadDialog::UploadDialog().
wxColour & ThemeBase::Colour (int iIndex)
References EnsureInitialised(), and mColours.
Referenced by AboutDialog::AboutDialog(), AColor::BevelTrackInfo(), AdornedRulerPanel::DoDrawMarks(), AdornedRulerPanel::DoDrawSelection(), LabelTrack::Draw(), LWSlider::Draw(), TrackInfo::DrawCloseBox(), TrackInfo::DrawMinimize(), TrackPanel::DrawOutside(), FreqWindow::DrawPlot(), TrackInfo::DrawTitleBar(), Meter::Meter(), TimeTextCtrl::OnPaint(), EqualizationPanel::OnPaint(), EffectAutoDuckPanel::OnPaint(), SplashDialog::Populate(), AboutDialog::PopulateAudacityPage(), SetBrushColour(), SetPenColour(), SplashDialog::SplashDialog(), and AColor::UseThemeColour().
void ThemeBase::CreateImageCache (bool bBinarySave = true)
References EnsureInitialised(), FlowPacker::GetNextPosition(), FlowPacker::Init(), mBitmapFlags, mBitmapNames, mColourNames, mColours, FlowPacker::mFlags, mFlow, mImages, FlowPacker::mxPos, FlowPacker::myHeight, FlowPacker::myPos, SourceOutputStream::OpenFile(), PasteSubImage(), FlowPacker::Rect(), resFlagInternal, FlowPacker::SetNewGroup(), FileNames::ThemeCacheAsCee(), and FileNames::ThemeCachePng().
Referenced by LoadThemeAtStartUp(), ThemePrefs::OnSaveThemeCache(), and SaveThemeAsCode().
wxCursor & ThemeBase::Cursor (int iIndex)
References EnsureInitialised().
virtual void ThemeBase::EnsureInitialised () [pure virtual]
Implemented in Theme.
Referenced by Bitmap(), Colour(), CreateImageCache(), Cursor(), Font(), Image(), ImageSize(), LoadThemeAtStartUp(), ReadImageCache(), WriteImageDefs(), and WriteImageMap().
wxFont & ThemeBase::Font (int iIndex)
References EnsureInitialised().
wxImage & ThemeBase::Image (int iIndex)
References EnsureInitialised(), and mImages.
Referenced by Meter::CreateIcon(), TrackArtist::DrawLinkTiles(), ExpandingToolBar::ExpandingToolBar(), ImageSize(), ToolBar::MakeButton(), ToolBar::MakeMacRecoloredImage(), ToolBar::MakeRecoloredImage(), ToolBar::OnPaint(), OverlayImage(), ReadImageCache(), ReplaceImage(), ExpandingToolBar::StartMoving(), and ToolBarGrabber::ToolBarGrabber().
wxSize ThemeBase::ImageSize (int iIndex)
References EnsureInitialised(), Image(), and mImages.
Referenced by TranscriptionToolBar::AddButton(), EditToolBar::AddButton(), ControlToolBar::MakeButton(), ControlToolBar::MakeLoopImage(), and ToolsToolBar::MakeTool().
void ThemeBase::LoadComponents (bool bOkIfNotFound = false)
JKC:
Bug:
(wxWidgets) A png may have been saved with alpha, but when you load it, it comes back with a mask instead! (well I guess it is more efficient). Anyway, we want alpha and not a mask, so we call InitAlpha, and that transfers the mask into the alpha channel, and we're done.
References mBitmapFlags, mBitmapNames, mBitmaps, mImages, resFlagInternal, FileNames::ThemeComponent(), and FileNames::ThemeComponentsDir().
Referenced by LoadThemeAtStartUp(), and ThemePrefs::OnLoadThemeComponents().
void ThemeBase::LoadThemeAtStartUp (bool bLookForExternalFiles)
This function is called to load the initial Theme images. There are many possible choices for what this function should do, as we have (potentially) four sources of images.
(deprecated) programmed in XPMs.
Programmed in in-built theme.
External image Cache file.
External component files.
We currently still have the deprecated XPMs, so we have those being used if the user decides not to load themes.
Parameters:
bLookForExternalFiles uses file iff true.
References CreateImageCache(), EnsureInitialised(), LoadComponents(), ReadImageCache(), and ReadThemeInternal().
Referenced by Theme::EnsureInitialised().
wxImage ThemeBase::MakeImageWithAlpha (wxBitmap & Bmp)
wxImage ThemeBase::MaskedImage (char const ** pXpm, char const ** pMask)
bool ThemeBase::ReadImageCache (bool bBinaryRead = true, bool bOkIfNotFound = false)
Reads an image cache including images, cursors and colours.
Parameters:
bBinaryRead if true means read from an external binary file. otherwise the data is taken from a compiled in block of memory.
bOkIfNotFound if true means do not report absent file.
Returns:
true iff we loaded the images.
Todo:
revisit this hack which makes adding new colours easier but which prevents a colour of (1,1,1) from being added. find an alternative way to make adding new colours easier. e.g. initialise the background to translucent, perhaps.
References EnsureInitialised(), FlowPacker::GetNextPosition(), GetSubImageWithAlpha(), Image(), FlowPacker::Init(), mBitmapFlags, mBitmaps, mColours, FlowPacker::mFlags, mFlow, mImages, FlowPacker::myHeight, FlowPacker::Rect(), FlowPacker::RectMid(), resFlagInternal, FlowPacker::SetNewGroup(), and FileNames::ThemeCachePng().
Referenced by LoadThemeAtStartUp(), ThemePrefs::OnLoadThemeCache(), and ReadThemeInternal().
void ThemeBase::ReadThemeInternal ()
References ReadImageCache().
Referenced by LoadThemeAtStartUp(), and ThemePrefs::OnReadThemeInternal().
void ThemeBase::RegisterColour (int & iIndex, const wxColour & Clr, const wxString & Name)
References mColourNames, and mColours.
void ThemeBase::RegisterImage (int & iIndex, const wxImage & Image, const wxString & Name)
References mBitmapFlags, mBitmapNames, mBitmaps, FlowPacker::mFlags, mFlow, and mImages.
void ThemeBase::RegisterImage (int & iIndex, char const ** pXpm, const wxString & Name)
void ThemeBase::ReplaceImage (int iIndex, wxImage * pImage)
Replaces both the image and the bitmap.
References Bitmap(), and Image().
Referenced by ToolBar::MakeMacRecoloredImage(), and ToolBar::MakeRecoloredImage().
void ThemeBase::SaveComponents ()
Bug:
1 in wxWidgets documentation; wxMkDir returns false if directory didn't exist, even if it successfully creates it. so we create and then test if it exists instead.
Bug:
2 in wxWidgets documentation; wxMkDir has only one argument under MSW
References mBitmapFlags, mBitmapNames, mImages, resFlagInternal, FileNames::ThemeComponent(), and FileNames::ThemeComponentsDir().
Referenced by ThemePrefs::OnSaveThemeComponents().
void ThemeBase::SaveThemeAsCode ()
References CreateImageCache().
Referenced by ThemePrefs::OnSaveThemeAsCode().
void ThemeBase::SetBrushColour (wxBrush & Brush, int iIndex)
References Colour().
Referenced by AColor::Init(), TimeTextCtrl::Layout(), TimeTextCtrl::OnPaint(), and TrackArtist::SetColours().
void ThemeBase::SetFlags (int flags) [inline]
void ThemeBase::SetPenColour (wxPen & Pen, int iIndex)
References Colour().
Referenced by AColor::Init(), TimeTextCtrl::OnPaint(), and TrackArtist::SetColours().
void ThemeBase::WriteImageDefs ()
Writes a series of Macro definitions that can be used in the include file.
References EnsureInitialised(), mBitmapFlags, mBitmapNames, mImages, resFlagCursor, resFlagInternal, resFlagNewLine, resFlagPaired, and FileNames::ThemeImageDefsAsCee().
Referenced by ThemePrefs::OnSaveThemeAsCode().
void ThemeBase::WriteImageMap ()
Writes an html file with an image map of the ImageCache Very handy for seeing what each part is for.
References EnsureInitialised(), FlowPacker::GetNextPosition(), FlowPacker::Init(), mBitmapFlags, mBitmapNames, mColourNames, mColours, FlowPacker::mFlags, mFlow, mImages, FlowPacker::Rect(), resFlagInternal, FlowPacker::SetNewGroup(), and FileNames::ThemeCacheHtm().
Referenced by ThemePrefs::OnSaveThemeCache().
Member Data Documentation
wxArrayInt ThemeBase::mBitmapFlags [protected]
Referenced by CreateImageCache(), LoadComponents(), ReadImageCache(), RegisterImage(), SaveComponents(), WriteImageDefs(), and WriteImageMap().
wxArrayString ThemeBase::mBitmapNames [protected]
Referenced by CreateImageCache(), LoadComponents(), RegisterImage(), SaveComponents(), WriteImageDefs(), and WriteImageMap().
ArrayOfBitmaps ThemeBase::mBitmaps [protected]
Referenced by Bitmap(), LoadComponents(), ReadImageCache(), and RegisterImage().
wxArrayString ThemeBase::mColourNames [protected]
Referenced by CreateImageCache(), RegisterColour(), and WriteImageMap().
ArrayOfColours ThemeBase::mColours [protected]
Referenced by Colour(), CreateImageCache(), ReadImageCache(), RegisterColour(), and WriteImageMap().
FlowPacker ThemeBase::mFlow [protected]
Referenced by CreateImageCache(), ReadImageCache(), RegisterImage(), and WriteImageMap().
ArrayOfImages ThemeBase::mImages [protected]
Referenced by CreateImageCache(), Image(), ImageSize(), LoadComponents(), ReadImageCache(), RegisterImage(), SaveComponents(), WriteImageDefs(), and WriteImageMap().
The documentation for this class was generated from the following files:
Theme.h
Theme.cpp