Audacity: CommandHandler Class Reference
CommandHandler Class Reference
Contains methods for applying commands that are passed to it.
#include <CommandHandler.h>
Public Member Functions
CommandHandler (AudacityApp &app)
~CommandHandler ()
void SetProject (AudacityProject *proj)
void OnReceiveCommand (AppCommandEvent &event)
Private Attributes
CommandExecutionContext * mCurrentContext
Detailed Description
Contains methods for applying commands that are passed to it.
Constructor & Destructor Documentation
CommandHandler::CommandHandler (AudacityApp & app)
CommandHandler::~CommandHandler ()
References mCurrentContext.
Member Function Documentation
void CommandHandler::OnReceiveCommand (AppCommandEvent & event)
References Command::Apply(), mCurrentContext, CommandExecutionContext::proj, and AudacityProject::RedrawProject().
Referenced by AudacityApp::OnReceiveCommand().
void CommandHandler::SetProject (AudacityProject * proj)
References mCurrentContext, and CommandExecutionContext::proj.
Referenced by AudacityApp::OnInit().
Member Data Documentation
CommandExecutionContext* CommandHandler::mCurrentContext [private]
Referenced by OnReceiveCommand(), SetProject(), and ~CommandHandler().
The documentation for this class was generated from the following files:
CommandHandler.h
CommandHandler.cpp