Audacity: AButton Class Reference
AButton Class Reference
A wxButton with mouse-over behaviour.
#include <AButton.h>
Public Types
enum AButtonState { AButtonUp, AButtonOver, AButtonDown, AButtonDis }
Public Member Functions
AButton (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size, ImageRoll up, ImageRoll over, ImageRoll down, ImageRoll dis, bool toggle)
AButton (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size, wxImage up, wxImage over, wxImage down, wxImage dis, bool toggle)
virtual ~AButton ()
virtual void SetAlternateImages (ImageRoll up, ImageRoll over, ImageRoll down, ImageRoll dis)
virtual void SetAlternateImages (wxImage up, wxImage over, wxImage down, wxImage dis)
virtual void SetAlternate (bool useAlternateImages)
virtual void SetFocusRect (wxRect &r)
virtual bool IsEnabled () const
virtual void Disable ()
virtual void Enable ()
void SetEnabled (bool state)
virtual void PushDown ()
virtual void PopUp ()
virtual void OnErase (wxEraseEvent &event)
virtual void OnPaint (wxPaintEvent &event)
virtual void OnSize (wxSizeEvent &event)
virtual void OnMouseEvent (wxMouseEvent &event)
virtual void OnCaptureLost (wxMouseCaptureLostEvent &event)
virtual void OnKeyDown (wxKeyEvent &event)
virtual void OnSetFocus (wxFocusEvent &event)
virtual void OnKillFocus (wxFocusEvent &event)
virtual bool WasShiftDown ()
virtual bool WasControlDown ()
bool IsDown ()
void SetButtonToggles (bool toggler)
void Toggle ()
void Click ()
void SetShift (bool shift)
AButtonState GetState ()
void UseDisabledAsDownHiliteImage (bool flag)
Private Member Functions
bool HasAlternateImages ()
void Init (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size, ImageRoll up, ImageRoll over, ImageRoll down, ImageRoll dis, bool toggle)
Private Attributes
bool mAlternate
bool mToggle
bool mWasShiftDown
bool mWasControlDown
bool mCursorIsInWindow
bool mButtonIsFocused
bool mButtonIsDown
bool mIsClicking
bool mEnabled
bool mUseDisabledAsDownHiliteImage
ImageRoll mImage [4]
ImageRoll mAltImage [4]
wxRect mFocusRect
Friends
class AButtonAx
Detailed Description
A wxButton with mouse-over behaviour.
AButton is a custom button class for Audacity. The main feature it supports that a wxButton does not is mouseovers.
It uses an image for all of its states: up, over, down, and disabled, allowing any sort of customization you want. Currently it does not support transparency effects, so the image musts be rectangular and opaque.
Member Enumeration Documentation
enum AButton::AButtonState
Enumerator:
AButtonUp
AButtonOver
AButtonDown
AButtonDis
Constructor & Destructor Documentation
AButton::AButton (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size, ImageRoll up, ImageRoll over, ImageRoll down, ImageRoll dis, bool toggle)
References Init().
AButton::AButton (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size, wxImage up, wxImage over, wxImage down, wxImage dis, bool toggle)
AButton::~AButton () [virtual]
Member Function Documentation
void AButton::Click ()
References wxEVT_COMMAND_BUTTON_CLICKED.
Referenced by OnKeyDown(), and OnMouseEvent().
void AButton::Disable () [virtual]
References mEnabled.
Referenced by TranscriptionToolBar::Create(), ControlToolBar::OnBatch(), ControlToolBar::OnRecord(), and SetEnabled().
void AButton::Enable () [virtual]
References mEnabled.
Referenced by TranscriptionToolBar::Create(), ControlToolBar::OnBatch(), TranscriptionToolBar::OnCalibrate(), and SetEnabled().
AButton::AButtonState AButton::GetState ()
References AButtonDis, AButtonDown, AButtonOver, AButtonUp, mButtonIsDown, mCursorIsInWindow, mEnabled, mIsClicking, mToggle, and mUseDisabledAsDownHiliteImage.
Referenced by OnMouseEvent(), and OnPaint().
bool AButton::HasAlternateImages () [private]
References mAltImage.
Referenced by OnMouseEvent().
void AButton::Init (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size, ImageRoll up, ImageRoll over, ImageRoll down, ImageRoll dis, bool toggle) [private]
References AButtonAx, mAlternate, mButtonIsDown, mButtonIsFocused, mCursorIsInWindow, mEnabled, mFocusRect, mImage, mIsClicking, mToggle, mUseDisabledAsDownHiliteImage, mWasControlDown, and mWasShiftDown.
Referenced by AButton().
bool AButton::IsDown () [inline]
References mButtonIsDown.
Referenced by ControlToolBar::EnableDisableButtons(), ToolsToolBar::IsDown(), ControlToolBar::IsRecordDown(), ControlToolBar::OnKeyDown(), and ControlToolBar::OnKeyUp().
virtual bool AButton::IsEnabled () const [inline, virtual]
References mEnabled.
void AButton::OnCaptureLost (wxMouseCaptureLostEvent & event) [virtual]
References OnMouseEvent().
void AButton::OnErase (wxEraseEvent & event) [virtual]
void AButton::OnKeyDown (wxKeyEvent & event) [virtual]
References Click(), mWasControlDown, and mWasShiftDown.
void AButton::OnKillFocus (wxFocusEvent & event) [virtual]
References mButtonIsFocused.
void AButton::OnMouseEvent (wxMouseEvent & event) [virtual]
References Click(), GetActiveProject(), GetState(), HasAlternateImages(), mAlternate, mButtonIsDown, mCursorIsInWindow, mEnabled, mIsClicking, mToggle, mWasControlDown, mWasShiftDown, and AudacityProject::TP_DisplayStatusMessage().
Referenced by OnCaptureLost().
void AButton::OnPaint (wxPaintEvent & event) [virtual]
References ImageRoll::Draw(), AColor::DrawFocus(), GetState(), mAlternate, mAltImage, mButtonIsFocused, mFocusRect, and mImage.
void AButton::OnSetFocus (wxFocusEvent & event) [virtual]
References mButtonIsFocused.
void AButton::OnSize (wxSizeEvent & event) [virtual]
References mFocusRect.
void AButton::PopUp () [virtual]
References mButtonIsDown.
Referenced by ExpandingToolBar::Collapse(), EditToolBar::EnableDisableButtons(), ControlToolBar::OnBatch(), EditToolBar::OnButton(), ControlToolBar::OnFF(), ControlToolBar::OnPause(), ControlToolBar::OnRecord(), ControlToolBar::OnRewind(), ToolsToolBar::OnTool(), ControlToolBar::PlayDefault(), ControlToolBar::PlayPlayRegion(), TranscriptionToolBar::SetButton(), ToolBar::SetButton(), ToolsToolBar::SetCurrentTool(), ControlToolBar::SetPlay(), ControlToolBar::SetRecord(), ControlToolBar::SetStop(), ControlToolBar::StopPlaying(), Toggle(), ExpandingToolBar::TryAutoCollapse(), MixerTrackCluster::UpdateMute(), and MixerTrackCluster::UpdateSolo().
void AButton::PushDown () [virtual]
References mButtonIsDown.
Referenced by ToolsToolBar::Create(), ExpandingToolBar::Expand(), ControlToolBar::OnFF(), ControlToolBar::OnPause(), ControlToolBar::OnRewind(), ToolsToolBar::OnTool(), EditToolBar::Populate(), TranscriptionToolBar::SetButton(), ToolBar::SetButton(), ToolsToolBar::SetCurrentTool(), ControlToolBar::SetPlay(), ControlToolBar::SetRecord(), ControlToolBar::SetStop(), ControlToolBar::StopPlaying(), Toggle(), ExpandingToolBar::TryAutoExpand(), MixerTrackCluster::UpdateMute(), and MixerTrackCluster::UpdateSolo().
void AButton::SetAlternate (bool useAlternateImages) [virtual]
References mAlternate.
Referenced by MixerTrackCluster::OnButton_Mute(), MixerTrackCluster::OnButton_Solo(), ControlToolBar::OnKeyDown(), ControlToolBar::OnKeyUp(), ControlToolBar::PlayCurrentRegion(), ControlToolBar::SetPlay(), MixerTrackCluster::UpdateMute(), and MixerTrackCluster::UpdateSolo().
void AButton::SetAlternateImages (wxImage up, wxImage over, wxImage down, wxImage dis) [virtual]
References mAltImage.
void AButton::SetAlternateImages (ImageRoll up, ImageRoll over, ImageRoll down, ImageRoll dis) [virtual]
References mAltImage.
Referenced by ControlToolBar::MakeLoopImage().
void AButton::SetButtonToggles (bool toggler) [inline]
References mToggle.
void AButton::SetEnabled (bool state) [inline]
References Disable(), and Enable().
Referenced by TranscriptionToolBar::EnableDisableButtons(), EditToolBar::EnableDisableButtons(), ControlToolBar::EnableDisableButtons(), and EditToolBar::Populate().
void AButton::SetFocusRect (wxRect & r) [virtual]
References mFocusRect.
Referenced by ControlToolBar::MakeButton().
void AButton::SetShift (bool shift)
References mWasShiftDown.
Referenced by ControlToolBar::OnRecord().
void AButton::Toggle () [inline]
References mButtonIsDown, PopUp(), and PushDown().
void AButton::UseDisabledAsDownHiliteImage (bool flag)
References mUseDisabledAsDownHiliteImage.
bool AButton::WasControlDown () [virtual]
References mWasControlDown.
Referenced by ControlToolBar::PlayDefault().
bool AButton::WasShiftDown () [virtual]
References mWasShiftDown.
Referenced by MixerTrackCluster::OnButton_Mute(), MixerTrackCluster::OnButton_Solo(), ControlToolBar::OnFF(), ControlToolBar::OnRecord(), ControlToolBar::OnRewind(), and ControlToolBar::PlayDefault().
Friends And Related Function Documentation
friend class AButtonAx [friend]
Referenced by Init().
Member Data Documentation
bool AButton::mAlternate [private]
Referenced by Init(), OnMouseEvent(), OnPaint(), and SetAlternate().
ImageRoll AButton::mAltImage[4] [private]
Referenced by HasAlternateImages(), OnPaint(), and SetAlternateImages().
bool AButton::mButtonIsDown [private]
Referenced by GetState(), Init(), IsDown(), OnMouseEvent(), PopUp(), PushDown(), and Toggle().
bool AButton::mButtonIsFocused [private]
Referenced by Init(), OnKillFocus(), OnPaint(), and OnSetFocus().
bool AButton::mCursorIsInWindow [private]
Referenced by GetState(), Init(), and OnMouseEvent().
bool AButton::mEnabled [private]
Referenced by Disable(), Enable(), GetState(), Init(), IsEnabled(), and OnMouseEvent().
wxRect AButton::mFocusRect [private]
Referenced by Init(), OnPaint(), OnSize(), and SetFocusRect().
ImageRoll AButton::mImage[4] [private]
Referenced by Init(), and OnPaint().
bool AButton::mIsClicking [private]
Referenced by GetState(), Init(), and OnMouseEvent().
bool AButton::mToggle [private]
Referenced by GetState(), Init(), OnMouseEvent(), and SetButtonToggles().
bool AButton::mUseDisabledAsDownHiliteImage [private]
Referenced by GetState(), Init(), and UseDisabledAsDownHiliteImage().
bool AButton::mWasControlDown [private]
Referenced by Init(), OnKeyDown(), OnMouseEvent(), and WasControlDown().
bool AButton::mWasShiftDown [private]
Referenced by Init(), OnKeyDown(), OnMouseEvent(), SetShift(), and WasShiftDown().
The documentation for this class was generated from the following files:
AButton.h
AButton.cpp