Audacity: Internat Class Reference
Internat Class Reference
Internationalisation support.
#include <Internat.h>
Static Public Member Functions
static void Init ()
Initialize internationalisation support. Call this once at program start.
static wxChar GetDecimalSeparator ()
Get the decimal separator for the current locale.
static bool CompatibleToDouble (const wxString &stringToConvert, double *result)
Convert a string to a number.
static double CompatibleToDouble (const wxString &stringToConvert)
static wxString ToString (double numberToConvert, int digitsAfterDecimalPoint=-1)
Convert a number to a string, always uses the dot as decimal separator.
static wxString ToDisplayString (double numberToConvert, int digitsAfterDecimalPoint=-1)
Convert a number to a string, uses the user's locale's decimal separator.
static wxString FormatSize (wxLongLong size)
Convert a number to a string while formatting it in bytes, KB, MB, GB.
static wxString FormatSize (double size)
static wxString SanitiseFilename (const wxString &name, const wxString &sub)
Protect against Unicode to multi-byte conversion failures on Windows.
static wxString StripAccelerators (const wxString &str)
Remove accelerator charactors from strings.
Static Private Attributes
static wxChar mDecimalSeparator = wxT('.')
static wxString forbid
static wxArrayString exclude
static wxCharBuffer mFilename
Detailed Description
Internationalisation support.
This class is used to help internationalisation and in general compatibility with different locales and character sets. It deals mostly with converting numbers, but also has important functions to convert to/from UTF-8, which is used in XML files and on Mac OS X for the filesystem.
Member Function Documentation
double Internat::CompatibleToDouble (const wxString & stringToConvert) [static]
References CompatibleToDouble().
bool Internat::CompatibleToDouble (const wxString & stringToConvert, double * result) [static]
Convert a string to a number.
This function will accept BOTH point and comma as a decimal separator, regardless of the current locale. Returns 'true' on success, and 'false' if an error occurs.
References GetDecimalSeparator().
Referenced by SimpleBlockFile::BuildFromXML(), PCMAliasBlockFile::BuildFromXML(), CompatibleToDouble(), EffectNyquist::GetCtrlValue(), LadspaEffectDialog::GetLength(), VampEffectDialog::HandleText(), LadspaEffectDialog::HandleText(), WaveTrack::HandleXMLTag(), WaveClip::HandleXMLTag(), TimeTrack::HandleXMLTag(), AudacityProject::HandleXMLTag(), ImportXMLTagHandler::HandleXMLTag(), LabelTrack::HandleXMLTag(), EqualizationDialog::HandleXMLTag(), EnvPoint::HandleXMLTag(), LabelTrack::Import(), LOFImportFileHandle::lofOpenFiles(), TimerRecordDialog::PopulateOrExchange(), WrappedType::ReadAsDouble(), NormalizeDialog::TransferDataFromWindow(), TimerRecordDialog::UpdateDuration(), and WrappedType::WriteToAsString().
wxString Internat::FormatSize (double size) [static]
References ToDisplayString().
wxString Internat::FormatSize (wxLongLong size) [static]
Convert a number to a string while formatting it in bytes, KB, MB, GB.
Referenced by UndoManager::GetLongDescription(), DependencyDialog::PopulateList(), and DirectoriesPrefs::UpdateFreeSpace().
wxChar Internat::GetDecimalSeparator () [static]
Get the decimal separator for the current locale.
Normally, this is a decimal point ('.'), but e.g. Germany uses a comma (',').
References mDecimalSeparator.
Referenced by CompatibleToDouble(), ToDisplayString(), and ToString().
void Internat::Init () [static]
Initialize internationalisation support. Call this once at program start.
References exclude, forbid, and mDecimalSeparator.
Referenced by AudacityApp::InitLang().
wxString Internat::SanitiseFilename (const wxString & name, const wxString & sub) [static]
Protect against Unicode to multi-byte conversion failures on Windows.
Check a proposed file name string for illegal characters and remove them
References exclude.
Referenced by ExportMultiple::MakeFileName().
wxString Internat::StripAccelerators (const wxString & str) [static]
Remove accelerator charactors from strings.
Utility function - takes a translatable string to be used as a menu item, for example _("&Splash...\tAlt+S"), and strips all of the menu accelerator stuff from it, to make "Splash". That way the same translatable string can be used both when accelerators are needed and when they aren't, saving translators effort.
wxString Internat::ToDisplayString (double numberToConvert, int digitsAfterDecimalPoint = -1) [static]
Convert a number to a string, uses the user's locale's decimal separator.
References GetDecimalSeparator().
Referenced by EffectAutoDuckDialog::EffectAutoDuckDialog(), FormatSize(), LadspaEffectDialog::LadspaEffectDialog(), EffectAutoDuckPanel::OnMotion(), EffectAutoDuckPanel::OnPaint(), VampEffectDialog::OnSlider(), NyquistDialog::OnSlider(), LadspaEffectDialog::OnSlider(), ToString(), VampEffectDialog::UpdateFromPlugin(), and VampEffectDialog::VampEffectDialog().
wxString Internat::ToString (double numberToConvert, int digitsAfterDecimalPoint = -1) [static]
Convert a number to a string, always uses the dot as decimal separator.
References GetDecimalSeparator(), and ToDisplayString().
Referenced by NormalizeDialog::PopulateOrExchange(), EffectNyquist::ProcessOne(), NormalizeDialog::TransferDataToWindow(), and XMLWriter::WriteAttr().
Member Data Documentation
wxArrayString Internat::exclude [static, private]
Referenced by Init(), and SanitiseFilename().
wxString Internat::forbid [static, private]
Referenced by Init().
wxChar Internat::mDecimalSeparator = wxT('.') [static, private]
Referenced by GetDecimalSeparator(), and Init().
wxCharBuffer Internat::mFilename [static, private]
The documentation for this class was generated from the following files:
Internat.h
Internat.cpp