Audacity: EnvPoint Class Reference
EnvPoint Class Reference
EnvPoint, derived from XMLTagHandler, provides Envelope with a draggable point type.
#include <Envelope.h>
Public Member Functions
bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
XMLTagHandler * HandleXMLChild (const wxChar *tag)
void WriteXML (XMLWriter &xmlFile)
Public Attributes
double t
double val
Detailed Description
EnvPoint, derived from XMLTagHandler, provides Envelope with a draggable point type.
Member Function Documentation
XMLTagHandler* EnvPoint::HandleXMLChild (const wxChar * tag) [inline, virtual]
Implements XMLTagHandler.
bool EnvPoint::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [inline, virtual]
Implements XMLTagHandler.
References Internat::CompatibleToDouble(), t, and val.
void EnvPoint::WriteXML (XMLWriter & xmlFile) [inline]
References XMLWriter::EndTag(), XMLWriter::StartTag(), t, val, and XMLWriter::WriteAttr().
Member Data Documentation
double EnvPoint::t
Referenced by Envelope::AddPointAtEnd(), HandleXMLTag(), Envelope::Insert(), and WriteXML().
double EnvPoint::val
Referenced by Envelope::AddPointAtEnd(), HandleXMLTag(), Envelope::Insert(), and WriteXML().
The documentation for this class was generated from the following file:
Envelope.h