Audacity: ImportMIDI.h File Reference
ImportMIDI.h File Reference
#include "../Audacity.h"
Classes
class MIDIParser
Unused class that might someday be used again to read MIDI files into a NoteTrack.
Functions
bool ImportMIDI (wxString fName, NoteTrack *dest)
Function Documentation
bool ImportMIDI (wxString fName, NoteTrack * dest)
References NoteTrack::SetSequence().
Referenced by LOFImportFileHandle::lofOpenFiles(), and AudacityProject::OnImportMIDI().