Audacity: LoadEffects.cpp File Reference
LoadEffects.cpp File Reference
#include "../Audacity.h"
#include "../Prefs.h"
#include "LoadEffects.h"
#include "EffectManager.h"
#include "Amplify.h"
#include "AutoDuck.h"
#include "BassBoost.h"
#include "ChangeSpeed.h"
#include "ClickRemoval.h"
#include "Compressor.h"
#include "DtmfGen.h"
#include "Echo.h"
#include "Equalization.h"
#include "Fade.h"
#include "Invert.h"
#include "Leveller.h"
#include "Noise.h"
#include "NoiseRemoval.h"
#include "Normalize.h"
#include "Phaser.h"
#include "Repair.h"
#include "Repeat.h"
#include "Reverse.h"
#include "Silence.h"
#include "StereoToMono.h"
#include "TimeScale.h"
#include "ToneGen.h"
#include "TruncSilence.h"
#include "Wahwah.h"
#include "FindClipping.h"
#include "ChangePitch.h"
#include "ChangeTempo.h"
#include "nyquist/LoadNyquist.h"
#include "ladspa/LoadLadspa.h"
#include "vamp/LoadVamp.h"
Functions
void LoadEffects ()
void UnloadEffects ()
Function Documentation
void LoadEffects ()
References BUILTIN_EFFECT, EffectManager::Get(), gPrefs, HIDDEN_EFFECT, LoadAudioUnits(), LoadLadspaPlugins(), LoadLV2Plugins(), LoadNyquistPlugins(), LoadVampPlugins(), PROCESS_EFFECT, and EffectManager::RegisterEffect().
Referenced by AudacityApp::OnInit().
void UnloadEffects ()
References EffectManager::Get(), UnloadLadspaPlugins(), UnloadLV2Plugins(), UnloadVampPlugins(), and EffectManager::UnregisterEffects().
Referenced by AudacityApp::OnExit().