Audacity: TrackArtist.h File Reference
TrackArtist.h File Reference
#include <wx/brush.h>
#include <wx/pen.h>
#include "Experimental.h"
#include "Sequence.h"
Classes
class TrackArtist
This class handles the actual rendering of WaveTracks (both waveforms and spectra), NoteTracks, LabelTracks and TimeTracks.
Typedefs
typedef unsigned char uchar
Functions
int GetWaveYPos (float value, float min, float max, int height, bool dB, bool outer, float dBr, bool clip)
Typedef Documentation
typedef unsigned char uchar
Function Documentation
int GetWaveYPos (float value, float min, float max, int height, bool dB, bool outer, float dBr, bool clip)
Takes a value between min and max and returns a value between height and 0
Todo:
Should this function move int GuiWaveTrack where it can then use the zoomMin, zoomMax and height values without having to have them passed in to it??
Referenced by TrackArtist::DrawEnvelope(), TrackArtist::DrawIndividualSamples(), TrackArtist::DrawMinMaxRMS(), Envelope::DrawPoints(), TrackArtist::DrawWaveformBackground(), Envelope::HandleMouseButtonDown(), TrackPanel::HitTestEnvelope(), and TrackPanel::HitTestSamples().