Audacity: ExportFFmpegAMRWBOptions Class Reference
ExportFFmpegAMRWBOptions Class Reference
Options dialog for FFmpeg exporting of AMRWB format.
#include <ExportFFmpegDialogs.h>
Public Member Functions
ExportFFmpegAMRWBOptions (wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
void OnOK (wxCommandEvent &event)
Static Public Attributes
static int iAMRWBBitRate []
Private Attributes
wxArrayString mBitRateNames
wxArrayInt mBitRateLabels
wxChoice * mBitRateChoice
wxButton * mOk
int mBitRateFromChoice
Detailed Description
Options dialog for FFmpeg exporting of AMRWB format.
Constructor & Destructor Documentation
ExportFFmpegAMRWBOptions::ExportFFmpegAMRWBOptions (wxWindow * parent)
References eIsCreatingFromPrefs, iAMRWBBitRate, mBitRateLabels, mBitRateNames, and PopulateOrExchange().
Member Function Documentation
void ExportFFmpegAMRWBOptions::OnOK (wxCommandEvent & event)
References eIsSavingToPrefs, and PopulateOrExchange().
void ExportFFmpegAMRWBOptions::PopulateOrExchange (ShuttleGui & S)
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndTwoColumn(), mBitRateLabels, mBitRateNames, ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartTwoColumn(), and ShuttleGuiBase::TieChoice().
Referenced by ExportFFmpegAMRWBOptions(), and OnOK().
Member Data Documentation
int ExportFFmpegAMRWBOptions::iAMRWBBitRate [static]
Initial value:
{ 6600, 8850, 12650, 14250, 15850, 18250, 19850, 23050, 23850 }
Bit Rates supported by libAMR-WB encoder Sample Rate is always 16 kHz
Referenced by ExportFFmpegAMRWBOptions().
wxChoice* ExportFFmpegAMRWBOptions::mBitRateChoice [private]
int ExportFFmpegAMRWBOptions::mBitRateFromChoice [private]
wxArrayInt ExportFFmpegAMRWBOptions::mBitRateLabels [private]
Referenced by ExportFFmpegAMRWBOptions(), and PopulateOrExchange().
wxArrayString ExportFFmpegAMRWBOptions::mBitRateNames [private]
Referenced by ExportFFmpegAMRWBOptions(), and PopulateOrExchange().
wxButton* ExportFFmpegAMRWBOptions::mOk [private]
The documentation for this class was generated from the following files:
ExportFFmpegDialogs.h
ExportFFmpegDialogs.cpp