Audacity: FFmpegNotFoundDialog Class Reference
FFmpegNotFoundDialog Class Reference
#include <FFmpeg.h>
Public Member Functions
FFmpegNotFoundDialog (wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
void OnOk (wxCommandEvent &event)
Private Attributes
wxCheckBox * mDontShow
Detailed Description
If Audacity failed to load libav*, this dialog shows up and tells user about that. It will pop-up again and again until it is disabled.
Constructor & Destructor Documentation
FFmpegNotFoundDialog::FFmpegNotFoundDialog (wxWindow * parent) [inline]
References eIsCreating, and PopulateOrExchange().
Member Function Documentation
void FFmpegNotFoundDialog::OnOk (wxCommandEvent & event) [inline]
References gPrefs, and mDontShow.
void FFmpegNotFoundDialog::PopulateOrExchange (ShuttleGui & S) [inline]
References ShuttleGuiBase::AddCheckBox(), ShuttleGuiBase::AddFixedText(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::EndVerticalLay(), eOkButton, gPrefs, mDontShow, ShuttleGuiBase::SetBorder(), and ShuttleGuiBase::StartVerticalLay().
Referenced by FFmpegNotFoundDialog().
Member Data Documentation
wxCheckBox* FFmpegNotFoundDialog::mDontShow [private]
Referenced by OnOk(), and PopulateOrExchange().
The documentation for this class was generated from the following file:
FFmpeg.h