Audacity: ClickRemovalDialog Class Reference
ClickRemovalDialog Class Reference
Dialog used with EffectClickRemoval.
#include <ClickRemoval.h>
Public Member Functions
ClickRemovalDialog (EffectClickRemoval *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
EffectClickRemoval * mEffect
int mThresh
int mWidth
Private Member Functions
void OnWidthText (wxCommandEvent &event)
void OnThreshText (wxCommandEvent &event)
void OnWidthSlider (wxCommandEvent &event)
void OnThreshSlider (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
Private Attributes
wxSlider * mWidthS
wxSlider * mThreshS
wxTextCtrl * mWidthT
wxTextCtrl * mThreshT
Detailed Description
Dialog used with EffectClickRemoval.
Constructor & Destructor Documentation
ClickRemovalDialog::ClickRemovalDialog (EffectClickRemoval * effect, wxWindow * parent)
Member Function Documentation
void ClickRemovalDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References EffectClickRemoval::mClickWidth, mEffect, mThresh, EffectClickRemoval::mThresholdLevel, mWidth, Effect::Preview(), and TransferDataFromWindow().
void ClickRemovalDialog::OnThreshSlider (wxCommandEvent & event) [private]
References mThreshS, and mThreshT.
void ClickRemovalDialog::OnThreshText (wxCommandEvent & event) [private]
References MAX_THRESHOLD, MIN_THRESHOLD, mThreshS, mThreshT, and TrapLong().
void ClickRemovalDialog::OnWidthSlider (wxCommandEvent & event) [private]
References mWidthS, and mWidthT.
void ClickRemovalDialog::OnWidthText (wxCommandEvent & event) [private]
References MAX_CLICK_WIDTH, MIN_CLICK_WIDTH, mWidthS, mWidthT, and TrapLong().
void ClickRemovalDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddSlider(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGui::Id(), ID_THRESH_SLIDER, ID_THRESH_TEXT, ID_WIDTH_SLIDER, ID_WIDTH_TEXT, MAX_CLICK_WIDTH, MAX_THRESHOLD, MIN_CLICK_WIDTH, MIN_THRESHOLD, mThreshS, mThreshT, mWidthS, mWidthT, numbers, ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartMultiColumn().
bool ClickRemovalDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References MAX_CLICK_WIDTH, MAX_THRESHOLD, MIN_CLICK_WIDTH, MIN_THRESHOLD, mThresh, mThreshS, mWidth, mWidthS, and TrapLong().
Referenced by OnPreview().
bool ClickRemovalDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References mThresh, mThreshS, mThreshT, mWidth, mWidthS, and mWidthT.
Referenced by EffectClickRemoval::PromptUser().
Member Data Documentation
EffectClickRemoval* ClickRemovalDialog::mEffect
Referenced by OnPreview().
int ClickRemovalDialog::mThresh
Referenced by OnPreview(), EffectClickRemoval::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* ClickRemovalDialog::mThreshS [private]
Referenced by OnThreshSlider(), OnThreshText(), PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
wxTextCtrl* ClickRemovalDialog::mThreshT [private]
Referenced by OnThreshSlider(), OnThreshText(), PopulateOrExchange(), and TransferDataToWindow().
int ClickRemovalDialog::mWidth
Referenced by OnPreview(), EffectClickRemoval::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* ClickRemovalDialog::mWidthS [private]
Referenced by OnWidthSlider(), OnWidthText(), PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
wxTextCtrl* ClickRemovalDialog::mWidthT [private]
Referenced by OnWidthSlider(), OnWidthText(), PopulateOrExchange(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
ClickRemoval.h
ClickRemoval.cpp