Audacity: EffectEcho Class Reference
EffectEcho Class Reference
An Effect that causes an echo, variable delay and volume.
#include <Echo.h>
Public Member Functions
EffectEcho ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual wxString GetEffectDescription ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Process ()
Private Member Functions
bool ProcessOne (int count, WaveTrack *t, sampleCount start, sampleCount len)
Private Attributes
float delay
float decay
Friends
class EchoDialog
Detailed Description
An Effect that causes an echo, variable delay and volume.
Constructor & Destructor Documentation
EffectEcho::EffectEcho ()
References decay, and delay.
Member Function Documentation
virtual wxString EffectEcho::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectEcho::GetEffectCategories () [inline, virtual]
wxString EffectEcho::GetEffectDescription () [virtual]
Reimplemented from Effect.
References decay, delay, and GetEffectName().
virtual wxString EffectEcho::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectEcho::GetEffectName () [inline, virtual]
Implements Effect.
Referenced by GetEffectDescription().
bool EffectEcho::Process () [virtual]
Implements Effect.
References Effect::CopyInputTracks(), TrackListCondIterator::First(), WaveTrack::GetEndTime(), WaveTrack::GetStartTime(), Effect::mOutputTracks, Effect::mT0, Effect::mT1, TrackListCondIterator::Next(), ProcessOne(), Effect::ReplaceProcessedTracks(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectEcho::ProcessOne (int count, WaveTrack * t, sampleCount start, sampleCount len) [private]
References decay, delay, floatSample, WaveTrack::Get(), WaveTrack::GetRate(), WaveTrack::Set(), and Effect::TrackProgress().
Referenced by Process().
bool EffectEcho::PromptUser () [virtual]
Reimplemented from Effect.
References decay, EchoDialog::decay, delay, EchoDialog::delay, and Effect::mParent.
bool EffectEcho::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References decay, delay, and Shuttle::TransferFloat().
Friends And Related Function Documentation
friend class EchoDialog [friend]
Member Data Documentation
float EffectEcho::decay [private]
Referenced by EffectEcho(), GetEffectDescription(), EchoDialog::OnPreview(), ProcessOne(), PromptUser(), and TransferParameters().
float EffectEcho::delay [private]
Referenced by EffectEcho(), GetEffectDescription(), EchoDialog::OnPreview(), ProcessOne(), PromptUser(), and TransferParameters().
The documentation for this class was generated from the following files:
Echo.h
Echo.cpp