Audacity: BrowserFrame Class Reference
BrowserFrame Class Reference
#include <LinkingHtmlWindow.h>
Public Member Functions
void OnForward (wxCommandEvent &event)
void OnBackward (wxCommandEvent &event)
void OnClose (wxCommandEvent &event)
void OnKeyDown (wxKeyEvent &event)
void UpdateButtons ()
Public Attributes
HtmlWindow * mpHtml
Member Function Documentation
void BrowserFrame::OnBackward (wxCommandEvent & event)
References mpHtml, and UpdateButtons().
void BrowserFrame::OnClose (wxCommandEvent & event)
void BrowserFrame::OnForward (wxCommandEvent & event)
void BrowserFrame::OnKeyDown (wxKeyEvent & event)
void BrowserFrame::UpdateButtons ()
References mpHtml.
Referenced by OnBackward(), and LinkingHtmlWindow::OnLinkClicked().
Member Data Documentation
HtmlWindow* BrowserFrame::mpHtml
Referenced by OnBackward(), ShowHtmlText(), and UpdateButtons().
The documentation for this class was generated from the following files:
LinkingHtmlWindow.h
LinkingHtmlWindow.cpp