Audacity: PhaserDialog Class Reference
PhaserDialog Class Reference
Dialog for EffectPhaser.
#include <Phaser.h>
Public Member Functions
PhaserDialog (EffectPhaser *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
wxSlider * GetStagesSlider ()
wxSlider * GetDryWetSlider ()
wxSlider * GetFeedbackSlider ()
wxSlider * GetDepthSlider ()
wxSlider * GetPhaseSlider ()
wxSlider * GetFreqSlider ()
wxTextCtrl * GetStagesText ()
wxTextCtrl * GetDryWetText ()
wxTextCtrl * GetFeedbackText ()
wxTextCtrl * GetDepthText ()
wxTextCtrl * GetPhaseText ()
wxTextCtrl * GetFreqText ()
Public Attributes
float freq
float startphase
float fb
int depth
int stages
int drywet
Private Member Functions
void OnStagesSlider (wxCommandEvent &event)
void OnDryWetSlider (wxCommandEvent &event)
void OnFeedbackSlider (wxCommandEvent &event)
void OnDepthSlider (wxCommandEvent &event)
void OnPhaseSlider (wxCommandEvent &event)
void OnFreqSlider (wxCommandEvent &event)
void OnStagesText (wxCommandEvent &event)
void OnDryWetText (wxCommandEvent &event)
void OnFeedbackText (wxCommandEvent &event)
void OnDepthText (wxCommandEvent &event)
void OnPhaseText (wxCommandEvent &event)
void OnFreqText (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
Private Attributes
EffectPhaser * mEffect
Detailed Description
Dialog for EffectPhaser.
Constructor & Destructor Documentation
PhaserDialog::PhaserDialog (EffectPhaser * effect, wxWindow * parent)
Member Function Documentation
wxSlider* PhaserDialog::GetDepthSlider () [inline]
References ID_PHASER_DEPTHSLIDER.
Referenced by OnDepthSlider(), OnDepthText(), and TransferDataToWindow().
wxTextCtrl* PhaserDialog::GetDepthText () [inline]
References ID_PHASER_DEPTHTEXT.
Referenced by OnDepthSlider(), OnDepthText(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* PhaserDialog::GetDryWetSlider () [inline]
References ID_PHASER_DRYWETSLIDER.
Referenced by OnDryWetSlider(), OnDryWetText(), and TransferDataToWindow().
wxTextCtrl* PhaserDialog::GetDryWetText () [inline]
References ID_PHASER_DRYWETTEXT.
Referenced by OnDryWetSlider(), OnDryWetText(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* PhaserDialog::GetFeedbackSlider () [inline]
References ID_PHASER_FEEDBACKSLIDER.
Referenced by OnFeedbackSlider(), OnFeedbackText(), and TransferDataToWindow().
wxTextCtrl* PhaserDialog::GetFeedbackText () [inline]
References ID_PHASER_FEEDBACKTEXT.
Referenced by OnFeedbackSlider(), OnFeedbackText(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* PhaserDialog::GetFreqSlider () [inline]
References ID_PHASER_FREQSLIDER.
Referenced by OnFreqSlider(), OnFreqText(), and TransferDataToWindow().
wxTextCtrl* PhaserDialog::GetFreqText () [inline]
References ID_PHASER_FREQTEXT.
Referenced by OnFreqSlider(), OnFreqText(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* PhaserDialog::GetPhaseSlider () [inline]
References ID_PHASER_PHASESLIDER.
Referenced by OnPhaseSlider(), OnPhaseText(), and TransferDataToWindow().
wxTextCtrl* PhaserDialog::GetPhaseText () [inline]
References ID_PHASER_PHASETEXT.
Referenced by OnPhaseSlider(), OnPhaseText(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* PhaserDialog::GetStagesSlider () [inline]
References ID_PHASER_STAGESSLIDER.
Referenced by OnStagesSlider(), OnStagesText(), and TransferDataToWindow().
wxTextCtrl* PhaserDialog::GetStagesText () [inline]
References ID_PHASER_STAGESTEXT.
Referenced by OnStagesSlider(), OnStagesText(), TransferDataFromWindow(), and TransferDataToWindow().
void PhaserDialog::OnDepthSlider (wxCommandEvent & event) [private]
References depth, GetDepthSlider(), and GetDepthText().
void PhaserDialog::OnDepthText (wxCommandEvent & event) [private]
References depth, DEPTH_MAX, DEPTH_MIN, GetDepthSlider(), GetDepthText(), and TrapLong().
void PhaserDialog::OnDryWetSlider (wxCommandEvent & event) [private]
References drywet, GetDryWetSlider(), and GetDryWetText().
void PhaserDialog::OnDryWetText (wxCommandEvent & event) [private]
References drywet, DRYWET_MAX, DRYWET_MIN, GetDryWetSlider(), GetDryWetText(), and TrapLong().
void PhaserDialog::OnFeedbackSlider (wxCommandEvent & event) [private]
References fb, GetFeedbackSlider(), and GetFeedbackText().
void PhaserDialog::OnFeedbackText (wxCommandEvent & event) [private]
References fb, FB_MAX, FB_MIN, GetFeedbackSlider(), GetFeedbackText(), and TrapLong().
void PhaserDialog::OnFreqSlider (wxCommandEvent & event) [private]
References freq, GetFreqSlider(), and GetFreqText().
void PhaserDialog::OnFreqText (wxCommandEvent & event) [private]
References freq, FREQ_MAX, FREQ_MIN, GetFreqSlider(), GetFreqText(), and TrapDouble().
void PhaserDialog::OnPhaseSlider (wxCommandEvent & event) [private]
References GetPhaseSlider(), and GetPhaseText().
void PhaserDialog::OnPhaseText (wxCommandEvent & event) [private]
References GetPhaseSlider(), GetPhaseText(), PHASE_MAX, PHASE_MIN, and TrapLong().
void PhaserDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References depth, EffectPhaser::depth, drywet, EffectPhaser::drywet, fb, EffectPhaser::fb, freq, EffectPhaser::freq, M_PI, mEffect, Effect::Preview(), stages, EffectPhaser::stages, startphase, EffectPhaser::startphase, and TransferDataFromWindow().
void PhaserDialog::OnStagesSlider (wxCommandEvent & event) [private]
References GetStagesSlider(), and GetStagesText().
void PhaserDialog::OnStagesText (wxCommandEvent & event) [private]
References GetStagesSlider(), GetStagesText(), STAGES_MAX, STAGES_MIN, and TrapLong().
void PhaserDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddSlider(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), DEPTH_MAX, DEPTH_MIN, DRYWET_MAX, DRYWET_MIN, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), FB_MAX, FB_MIN, FREQ_MAX, FREQ_MIN, ShuttleGui::Id(), ID_PHASER_DEPTHSLIDER, ID_PHASER_DEPTHTEXT, ID_PHASER_DRYWETSLIDER, ID_PHASER_DRYWETTEXT, ID_PHASER_FEEDBACKSLIDER, ID_PHASER_FEEDBACKTEXT, ID_PHASER_FREQSLIDER, ID_PHASER_FREQTEXT, ID_PHASER_PHASESLIDER, ID_PHASER_PHASETEXT, ID_PHASER_STAGESSLIDER, ID_PHASER_STAGESTEXT, PHASE_MAX, PHASE_MIN, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::SetStyle(), STAGES_MAX, STAGES_MIN, ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartMultiColumn().
bool PhaserDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References depth, DEPTH_MAX, DEPTH_MIN, drywet, DRYWET_MAX, DRYWET_MIN, fb, FB_MAX, FB_MIN, freq, FREQ_MAX, FREQ_MIN, GetDepthText(), GetDryWetText(), GetFeedbackText(), GetFreqText(), GetPhaseText(), GetStagesText(), PHASE_MAX, PHASE_MIN, stages, STAGES_MAX, STAGES_MIN, startphase, TrapDouble(), and TrapLong().
Referenced by OnPreview().
bool PhaserDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References depth, drywet, fb, freq, GetDepthSlider(), GetDepthText(), GetDryWetSlider(), GetDryWetText(), GetFeedbackSlider(), GetFeedbackText(), GetFreqSlider(), GetFreqText(), GetPhaseSlider(), GetPhaseText(), GetStagesSlider(), GetStagesText(), stages, and startphase.
Referenced by EffectPhaser::PromptUser().
Member Data Documentation
int PhaserDialog::depth
Referenced by OnDepthSlider(), OnDepthText(), OnPreview(), EffectPhaser::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
int PhaserDialog::drywet
Referenced by OnDryWetSlider(), OnDryWetText(), OnPreview(), EffectPhaser::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
float PhaserDialog::fb
Referenced by OnFeedbackSlider(), OnFeedbackText(), OnPreview(), EffectPhaser::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
float PhaserDialog::freq
Referenced by OnFreqSlider(), OnFreqText(), OnPreview(), EffectPhaser::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
EffectPhaser* PhaserDialog::mEffect [private]
Referenced by OnPreview().
int PhaserDialog::stages
Referenced by OnPreview(), EffectPhaser::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
float PhaserDialog::startphase
Referenced by OnPreview(), EffectPhaser::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
Phaser.h
Phaser.cpp