Audacity: SliderDialog Class Reference
SliderDialog Class Reference
Pop up dialog used with an LWSlider.
#include <ASlider.h>
Public Member Functions
SliderDialog (wxWindow *parent, wxWindowID id, const wxString &title, wxPoint position, wxSize size, int style, float value, float line, float page)
~SliderDialog ()
float Get ()
Private Member Functions
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
void OnSlider (wxCommandEvent &event)
Private Attributes
ASlider * mSlider
wxTextCtrl * mTextCtrl
int mStyle
Detailed Description
Pop up dialog used with an LWSlider.
Constructor & Destructor Documentation
SliderDialog::SliderDialog (wxWindow * parent, wxWindowID id, const wxString & title, wxPoint position, wxSize size, int style, float value, float line, float page)
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddWindow(), eCancelButton, eIsCreating, ShuttleGuiBase::EndVerticalLay(), eOkButton, and ShuttleGuiBase::StartVerticalLay().
SliderDialog::~SliderDialog ()
Member Function Documentation
float SliderDialog::Get ()
References ASlider::Get(), and mSlider.
Referenced by LWSlider::DoShowDialog().
void SliderDialog::OnSlider (wxCommandEvent & event) [private]
References TransferDataToWindow().
bool SliderDialog::TransferDataFromWindow () [private]
References DB_SLIDER, mSlider, mStyle, mTextCtrl, and ASlider::Set().
bool SliderDialog::TransferDataToWindow () [private]
References ASlider::Get(), mSlider, and mTextCtrl.
Referenced by OnSlider().
Member Data Documentation
ASlider* SliderDialog::mSlider [private]
Referenced by Get(), TransferDataFromWindow(), and TransferDataToWindow().
int SliderDialog::mStyle [private]
Referenced by TransferDataFromWindow().
wxTextCtrl* SliderDialog::mTextCtrl [private]
Referenced by TransferDataFromWindow(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
ASlider.h
ASlider.cpp