Audacity: ErrorDialog Class Reference
ErrorDialog Class Reference
Public Member Functions
ErrorDialog (wxWindow *parent, const wxString &dlogTitle, const wxString &message, const wxString &helpURL)
Private Member Functions
void OnOk (wxCommandEvent &event)
void OnHelp (wxCommandEvent &event)
Private Attributes
wxString dhelpURL
Detailed Description
Gives an Error message with an option for help.
Constructor & Destructor Documentation
ErrorDialog::ErrorDialog (wxWindow * parent, const wxString & dlogTitle, const wxString & message, const wxString & helpURL)
References ShuttleGuiBase::AddFixedText(), ShuttleGui::AddStandardButtons(), eHelpButton, eIsCreating, ShuttleGuiBase::EndVerticalLay(), eOkButton, ShuttleGuiBase::SetBorder(), and ShuttleGuiBase::StartVerticalLay().
Member Function Documentation
void ErrorDialog::OnHelp (wxCommandEvent & event) [private]
References dhelpURL, HelpText(), OpenInDefaultBrowser(), ShowHtmlText(), and TitleText().
void ErrorDialog::OnOk (wxCommandEvent & event) [private]
Member Data Documentation
wxString ErrorDialog::dhelpURL [private]
Referenced by OnHelp().
The documentation for this class was generated from the following file:
ErrorDialog.cpp