Audacity: TimeScaleDialog Class Reference
TimeScaleDialog Class Reference
Dialog used with EffectTimeScale.
#include <TimeScale.h>
Public Member Functions
TimeScaleDialog (EffectTimeScale *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
double m_RateStart
double m_RateEnd
double m_HalfStepsStart
double m_HalfStepsEnd
bool m_PreAnalyze
Private Member Functions
void OnText_RateStart (wxCommandEvent &event)
void OnText_RateEnd (wxCommandEvent &event)
void OnText_HalfStepsStart (wxCommandEvent &event)
void OnText_HalfStepsEnd (wxCommandEvent &event)
void OnSlider_RateStart (wxCommandEvent &event)
void OnSlider_RateEnd (wxCommandEvent &event)
void OnCheckBox_PreAnalyze (wxCommandEvent &event)
bool CheckParameters ()
void Update_Text_RateStart ()
void Update_Text_RateEnd ()
void Update_Text_HalfStepsStart ()
void Update_Text_HalfStepsEnd ()
void Update_Slider_RateStart ()
void Update_Slider_RateEnd ()
void Update_CheckBox_PreAnalyze ()
Private Attributes
EffectTimeScale * mEffect
bool m_bLoopDetect
wxTextCtrl * m_pTextCtrl_RateStart
wxSlider * m_pSlider_RateStart
wxTextCtrl * m_pTextCtrl_RateEnd
wxSlider * m_pSlider_RateEnd
wxTextCtrl * m_pTextCtrl_HalfStepsStart
wxTextCtrl * m_pTextCtrl_HalfStepsEnd
wxCheckBox * m_pCheckBox_PreAnalyze
Detailed Description
Dialog used with EffectTimeScale.
Constructor & Destructor Documentation
TimeScaleDialog::TimeScaleDialog (EffectTimeScale * effect, wxWindow * parent)
Member Function Documentation
bool TimeScaleDialog::CheckParameters () [private]
References m_HalfStepsEnd, m_HalfStepsStart, m_RateEnd, and m_RateStart.
Referenced by OnText_HalfStepsEnd(), OnText_HalfStepsStart(), OnText_RateEnd(), and OnText_RateStart().
void TimeScaleDialog::OnCheckBox_PreAnalyze (wxCommandEvent & event) [private]
References m_pCheckBox_PreAnalyze, and m_PreAnalyze.
void TimeScaleDialog::OnSlider_RateEnd (wxCommandEvent & event) [private]
References m_bLoopDetect, m_pSlider_RateEnd, m_RateEnd, and Update_Text_RateEnd().
void TimeScaleDialog::OnSlider_RateStart (wxCommandEvent & event) [private]
References m_bLoopDetect, m_pSlider_RateStart, m_RateStart, and Update_Text_RateStart().
void TimeScaleDialog::OnText_HalfStepsEnd (wxCommandEvent & event) [private]
References CheckParameters(), m_HalfStepsEnd, and m_pTextCtrl_HalfStepsEnd.
void TimeScaleDialog::OnText_HalfStepsStart (wxCommandEvent & event) [private]
References CheckParameters(), m_HalfStepsStart, and m_pTextCtrl_HalfStepsStart.
void TimeScaleDialog::OnText_RateEnd (wxCommandEvent & event) [private]
References CheckParameters(), m_bLoopDetect, m_pTextCtrl_RateEnd, m_RateEnd, and Update_Slider_RateEnd().
void TimeScaleDialog::OnText_RateStart (wxCommandEvent & event) [private]
References CheckParameters(), m_bLoopDetect, m_pTextCtrl_RateStart, m_RateStart, and Update_Slider_RateStart().
void TimeScaleDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddCheckBox(), ShuttleGuiBase::AddSlider(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGui::Id(), ID_CHECKBOX_PREANALYZE, ID_SLIDER_RATE_END, ID_SLIDER_RATE_START, ID_TEXT_HALFSTEPS_END, ID_TEXT_HALFSTEPS_START, ID_TEXT_RATE_END, ID_TEXT_RATE_START, m_pCheckBox_PreAnalyze, m_pSlider_RateEnd, m_pSlider_RateStart, m_pTextCtrl_HalfStepsEnd, m_pTextCtrl_HalfStepsStart, m_pTextCtrl_RateEnd, m_pTextCtrl_RateStart, RATE_DEFAULT, RATE_MAX, RATE_MIN, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartMultiColumn().
bool TimeScaleDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References m_HalfStepsEnd, m_HalfStepsStart, m_pCheckBox_PreAnalyze, m_PreAnalyze, m_pTextCtrl_HalfStepsEnd, m_pTextCtrl_HalfStepsStart, m_pTextCtrl_RateEnd, m_pTextCtrl_RateStart, m_RateEnd, and m_RateStart.
bool TimeScaleDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References m_bLoopDetect, Update_CheckBox_PreAnalyze(), Update_Slider_RateEnd(), Update_Slider_RateStart(), Update_Text_HalfStepsEnd(), Update_Text_HalfStepsStart(), Update_Text_RateEnd(), and Update_Text_RateStart().
void TimeScaleDialog::Update_CheckBox_PreAnalyze () [private]
References m_pCheckBox_PreAnalyze, and m_PreAnalyze.
Referenced by TransferDataToWindow().
void TimeScaleDialog::Update_Slider_RateEnd () [private]
References m_pSlider_RateEnd, and m_RateEnd.
Referenced by OnText_RateEnd(), and TransferDataToWindow().
void TimeScaleDialog::Update_Slider_RateStart () [private]
References m_pSlider_RateStart, and m_RateStart.
Referenced by OnText_RateStart(), and TransferDataToWindow().
void TimeScaleDialog::Update_Text_HalfStepsEnd () [private]
References m_HalfStepsEnd, and m_pTextCtrl_HalfStepsEnd.
Referenced by TransferDataToWindow().
void TimeScaleDialog::Update_Text_HalfStepsStart () [private]
References m_HalfStepsStart, and m_pTextCtrl_HalfStepsStart.
Referenced by TransferDataToWindow().
void TimeScaleDialog::Update_Text_RateEnd () [private]
References m_pTextCtrl_RateEnd, and m_RateEnd.
Referenced by OnSlider_RateEnd(), and TransferDataToWindow().
void TimeScaleDialog::Update_Text_RateStart () [private]
References m_pTextCtrl_RateStart, and m_RateStart.
Referenced by OnSlider_RateStart(), and TransferDataToWindow().
Member Data Documentation
bool TimeScaleDialog::m_bLoopDetect [private]
Referenced by OnSlider_RateEnd(), OnSlider_RateStart(), OnText_RateEnd(), OnText_RateStart(), and TransferDataToWindow().
double TimeScaleDialog::m_HalfStepsEnd
Referenced by CheckParameters(), OnText_HalfStepsEnd(), EffectTimeScale::PromptUser(), TransferDataFromWindow(), and Update_Text_HalfStepsEnd().
double TimeScaleDialog::m_HalfStepsStart
Referenced by CheckParameters(), OnText_HalfStepsStart(), EffectTimeScale::PromptUser(), TransferDataFromWindow(), and Update_Text_HalfStepsStart().
wxCheckBox* TimeScaleDialog::m_pCheckBox_PreAnalyze [private]
Referenced by OnCheckBox_PreAnalyze(), PopulateOrExchange(), TransferDataFromWindow(), and Update_CheckBox_PreAnalyze().
bool TimeScaleDialog::m_PreAnalyze
Referenced by OnCheckBox_PreAnalyze(), EffectTimeScale::PromptUser(), TransferDataFromWindow(), and Update_CheckBox_PreAnalyze().
wxSlider* TimeScaleDialog::m_pSlider_RateEnd [private]
Referenced by OnSlider_RateEnd(), PopulateOrExchange(), and Update_Slider_RateEnd().
wxSlider* TimeScaleDialog::m_pSlider_RateStart [private]
Referenced by OnSlider_RateStart(), PopulateOrExchange(), and Update_Slider_RateStart().
wxTextCtrl* TimeScaleDialog::m_pTextCtrl_HalfStepsEnd [private]
Referenced by OnText_HalfStepsEnd(), PopulateOrExchange(), TransferDataFromWindow(), and Update_Text_HalfStepsEnd().
wxTextCtrl* TimeScaleDialog::m_pTextCtrl_HalfStepsStart [private]
Referenced by OnText_HalfStepsStart(), PopulateOrExchange(), TransferDataFromWindow(), and Update_Text_HalfStepsStart().
wxTextCtrl* TimeScaleDialog::m_pTextCtrl_RateEnd [private]
Referenced by OnText_RateEnd(), PopulateOrExchange(), TransferDataFromWindow(), and Update_Text_RateEnd().
wxTextCtrl* TimeScaleDialog::m_pTextCtrl_RateStart [private]
Referenced by OnText_RateStart(), PopulateOrExchange(), TransferDataFromWindow(), and Update_Text_RateStart().
double TimeScaleDialog::m_RateEnd
Referenced by CheckParameters(), OnSlider_RateEnd(), OnText_RateEnd(), EffectTimeScale::PromptUser(), TransferDataFromWindow(), Update_Slider_RateEnd(), and Update_Text_RateEnd().
double TimeScaleDialog::m_RateStart
Referenced by CheckParameters(), OnSlider_RateStart(), OnText_RateStart(), EffectTimeScale::PromptUser(), TransferDataFromWindow(), Update_Slider_RateStart(), and Update_Text_RateStart().
EffectTimeScale* TimeScaleDialog::mEffect [private]
The documentation for this class was generated from the following files:
TimeScale.h
TimeScale.cpp