Audacity: GetAllMenuCommands Class Reference
GetAllMenuCommands Class Reference
Command which outputs a list of available menu commands on the status channel.
#include <GetAllMenuCommands.h>
Public Member Functions
GetAllMenuCommands (CommandType &type, CommandOutputTarget *target)
virtual ~GetAllMenuCommands ()
virtual bool Apply (CommandExecutionContext context)
Detailed Description
Command which outputs a list of available menu commands on the status channel.
Constructor & Destructor Documentation
GetAllMenuCommands::GetAllMenuCommands (CommandType & type, CommandOutputTarget * target) [inline]
virtual GetAllMenuCommands::~GetAllMenuCommands () [inline, virtual]
Member Function Documentation
bool GetAllMenuCommands::Apply (CommandExecutionContext context) [virtual]
Actually carry out the command. Return true if successful and false otherwise.
Reimplemented from CommandImplementation.
References CommandManager::GetAllCommandNames(), CommandImplementation::GetBool(), AudacityProject::GetCommandManager(), CommandManager::GetEnabled(), name, names, CommandExecutionContext::proj, and CommandImplementation::Status().
The documentation for this class was generated from the following files:
GetAllMenuCommands.h
GetAllMenuCommands.cpp