Audacity: CommandManager Class Reference
CommandManager Class Reference
CommandManager implements a system for organizing all user-callable commands.
#include <CommandManager.h>
Public Member Functions
CommandManager ()
virtual ~CommandManager ()
void PurgeData ()
wxMenuBar * AddMenuBar (wxString sMenu)
void BeginMenu (wxString tName)
void EndMenu ()
wxMenu * BeginSubMenu (wxString tName)
void EndSubMenu ()
void InsertItem (wxString name, wxString label, CommandFunctor *callback, wxString after, int checkmark=-1)
void AddItemList (wxString name, wxArrayString labels, CommandFunctor *callback, bool plugins=false)
void AddCheck (const wxChar *name, const wxChar *label, CommandFunctor *callback, int checkmark=0)
void AddCheck (const wxChar *name, const wxChar *label, CommandFunctor *callback, int checkmark, unsigned int flags, unsigned int mask)
void AddItem (const wxChar *name, const wxChar *label, CommandFunctor *callback, unsigned int flags=NoFlagsSpecifed, unsigned int mask=NoFlagsSpecifed)
void AddItem (const wxChar *name, const wxChar *label_in, CommandFunctor *callback, const wxChar *accel, unsigned int flags=NoFlagsSpecifed, unsigned int mask=NoFlagsSpecifed, int checkmark=-1)
void AddSeparator ()
void AddCommand (const wxChar *name, const wxChar *label, CommandFunctor *callback, unsigned int flags=NoFlagsSpecifed, unsigned int mask=NoFlagsSpecifed)
void AddCommand (const wxChar *name, const wxChar *label, CommandFunctor *callback, const wxChar *accel, unsigned int flags=NoFlagsSpecifed, unsigned int mask=NoFlagsSpecifed)
void SetDefaultFlags (wxUint32 flags, wxUint32 mask)
void SetCommandFlags (wxString name, wxUint32 flags, wxUint32 mask)
void SetCommandFlags (const wxChar **names, wxUint32 flags, wxUint32 mask)
void SetCommandFlags (wxUint32 flags, wxUint32 mask,...)
void EnableUsingFlags (wxUint32 flags, wxUint32 mask)
void Enable (wxString name, bool enabled)
void Check (wxString name, bool checked)
void Modify (wxString name, wxString newLabel)
Changes the label text of a menu item.
void SetKeyFromName (wxString name, wxString key)
void HandleMenuOpen (wxMenuEvent &evt)
void HandleMenuClose (wxMenuEvent &evt)
bool HandleCommandEntry (CommandListEntry *entry, wxUint32 flags, wxUint32 mask)
bool HandleMenuID (int id, wxUint32 flags, wxUint32 mask)
bool HandleKey (wxKeyEvent &evt, wxUint32 flags, wxUint32 mask)
bool HandleTextualCommand (wxString &Str, wxUint32 flags, wxUint32 mask)
void TellUserWhyDisallowed (wxUint32 flagsGot, wxUint32 flagsRequired)
void GetCategories (wxArrayString &cats)
void GetAllCommandNames (wxArrayString &names, bool includeMultis)
wxString GetLabelFromName (wxString name)
wxString GetPrefixedLabelFromName (wxString name)
wxString GetCategoryFromName (wxString name)
wxString GetKeyFromName (wxString name)
wxString GetDefaultKeyFromName (wxString name)
bool GetEnabled (const wxString &name)
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual void HandleXMLEndTag (const wxChar *tag)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
Public Attributes
bool mbHideFlaggedItems
Protected Member Functions
wxMenuBar * CurrentMenuBar ()
wxMenuBar * GetMenuBar (wxString sMenu)
wxMenu * CurrentSubMenu ()
wxMenu * CurrentMenu ()
int NextIdentifier (int ID)
int NewIdentifier (wxString name, wxString label, wxMenu *menu, CommandFunctor *callback, bool multi, int index, int count)
void Enable (CommandListEntry *entry, bool enabled)
wxString GetKey (wxString label)
void ToggleAccels (wxMenu *m, bool show)
bool ItemShouldBeHidden (wxString &Label)
Private Attributes
MenuBarList mMenuBarList
SubMenuList mSubMenuList
CommandList mCommandList
CommandNameHash mCommandNameHash
CommandNameHash mCommandKeyHash
CommandIDHash mCommandIDHash
int mCurrentID
int mHiddenID
int mXMLKeysRead
bool mbSeparatorAllowed
int mHidingLevel
wxString mCurrentMenuName
wxMenu * mCurrentMenu
wxMenu * mOpenMenu
wxUint32 mDefaultFlags
wxUint32 mDefaultMask
Detailed Description
CommandManager implements a system for organizing all user-callable commands.
It creates and manages a menu bar with a command associated with each item, and managing other commands callable by keyboard shortcuts.
Commands are implemented by overriding an abstract functor class. See Menus.cpp for an example use.
Menus or submenus containing lists of items can be added at once, with a single function (functor) to be called when any of the items is selected, with the index number of the selection as the parameter. This is useful for dynamic menus (effects) and submenus containing a list of choices (selection formats).
Menu items can be enabled or disabled individually, groups of "multi-items" can be enabled or disabled all at once, or entire sets of commands can be enabled or disabled all at once using flags. The flags should be a bitfield stored in a 32-bit integer but can be whatever you want. You specify both the desired values of the flags, and the set of flags relevant to a particular command, by using a combination of a flags parameter and a mask parameter. Any flag set to 0 in the mask parameter is the same as "don't care". Any command whose mask is set to zero will not be affected by enabling/disabling by flags.
Constructor & Destructor Documentation
CommandManager::CommandManager ()
Standard Constructor
CommandManager::~CommandManager () [virtual]
Class Destructor. Includes PurgeData, which removes menubars
References PurgeData().
Member Function Documentation
void CommandManager::AddCheck (const wxChar * name, const wxChar * label, CommandFunctor * callback, int checkmark, unsigned int flags, unsigned int mask)
References AddItem().
void CommandManager::AddCheck (const wxChar * name, const wxChar * label, CommandFunctor * callback, int checkmark = 0)
References AddItem(), and NoFlagsSpecifed.
Referenced by AudacityProject::CreateMenusAndCommands().
void CommandManager::AddCommand (const wxChar * name, const wxChar * label, CommandFunctor * callback, const wxChar * accel, unsigned int flags = NoFlagsSpecifed, unsigned int mask = NoFlagsSpecifed)
References label, NewIdentifier(), NoFlagsSpecifed, and SetCommandFlags().
void CommandManager::AddCommand (const wxChar * name, const wxChar * label, CommandFunctor * callback, unsigned int flags = NoFlagsSpecifed, unsigned int mask = NoFlagsSpecifed)
Add a command that doesn't appear in a menu. When the key is pressed, the given function pointer will be called (via the CommandManagerListener)
Referenced by AudacityProject::CreateMenusAndCommands().
void CommandManager::AddItem (const wxChar * name, const wxChar * label_in, CommandFunctor * callback, const wxChar * accel, unsigned int flags = NoFlagsSpecifed, unsigned int mask = NoFlagsSpecifed, int checkmark = -1)
References CurrentMenu(), ItemShouldBeHidden(), label, mbSeparatorAllowed, mHiddenID, NewIdentifier(), NoFlagsSpecifed, and SetCommandFlags().
void CommandManager::AddItem (const wxChar * name, const wxChar * label, CommandFunctor * callback, unsigned int flags = NoFlagsSpecifed, unsigned int mask = NoFlagsSpecifed)
Referenced by AddCheck(), and AudacityProject::CreateMenusAndCommands().
void CommandManager::AddItemList (wxString name, wxArrayString labels, CommandFunctor * callback, bool plugins = false)
Add a list of menu items to the current menu. When the user selects any one of these, the given functor will be called with its position in the list as the index number. When you call Enable on this command name, it will enable or disable all of the items at once.
References BeginSubMenu(), CurrentMenu(), EndSubMenu(), label, MAX_MENU_LEN, MAX_SUBMENU_LEN, mbSeparatorAllowed, mHidingLevel, and NewIdentifier().
Referenced by AudacityProject::CreateMenusAndCommands().
wxMenuBar * CommandManager::AddMenuBar (wxString sMenu)
Makes a new menubar for placement on the top of a project Names it according to the passed-in string argument.
If the menubar already exists, simply returns it.
References GetMenuBar(), MenuBarListEntry::menubar, mHidingLevel, mMenuBarList, and MenuBarListEntry::name.
Referenced by AudacityProject::CreateMenusAndCommands().
void CommandManager::AddSeparator ()
References CurrentMenu(), mbSeparatorAllowed, and mHidingLevel.
Referenced by AudacityProject::CreateMenusAndCommands().
void CommandManager::BeginMenu (wxString tNameIn)
This makes a new menu and adds it to the 'CurrentMenuBar'
If the menu already exists, all of the items in it are cleared instead.
References CurrentMenuBar(), ItemShouldBeHidden(), mCurrentMenu, mCurrentMenuName, and mHidingLevel.
Referenced by AudacityProject::CreateMenusAndCommands().
wxMenu * CommandManager::BeginSubMenu (wxString tNameIn)
This starts a new submenu, and names it according to the function's argument.
References ItemShouldBeHidden(), mbSeparatorAllowed, SubMenuListEntry::menu, mHidingLevel, mSubMenuList, and SubMenuListEntry::name.
Referenced by AddItemList(), AudacityProject::CreateMenusAndCommands(), and AudacityProject::CreateRecentFilesMenu().
void CommandManager::Check (wxString name, bool checked)
References CommandListEntry::id, mCommandNameHash, and CommandListEntry::menu.
Referenced by AudacityProject::ModifyToolbarMenus(), AudacityProject::OnShowClipping(), AudacityProject::OnSimplifiedView(), and AudacityProject::SetSnapTo().
wxMenu * CommandManager::CurrentMenu () [protected]
This returns the current menu that we're appending to - note that it could be a submenu if BeginSubMenu was called and we haven't reached EndSubMenu yet.
References CurrentSubMenu(), and mCurrentMenu.
Referenced by AddItem(), AddItemList(), AddSeparator(), and EndSubMenu().
wxMenuBar * CommandManager::CurrentMenuBar () [protected]
Retrieve the 'current' menubar; either NULL or the last on in the mMenuBarList.
References mMenuBarList.
Referenced by BeginMenu().
wxMenu * CommandManager::CurrentSubMenu () [protected]
This returns the 'Current' Submenu, which is the one at the end of the mSubMenuList (or NULL, if it doesn't exist).
References mSubMenuList.
Referenced by CurrentMenu().
void CommandManager::Enable (CommandListEntry * entry, bool enabled) [protected]
Enables or disables a menu item based on its name (not the label in the menu bar, but the name of the command.) If you give it the name of a multi-item (one that was added using AddItemList(), it will enable or disable all of them at once
References CommandListEntry::count, CommandListEntry::enabled, CommandListEntry::id, mCommandIDHash, CommandListEntry::menu, CommandListEntry::multi, CommandListEntry::name, and NextIdentifier().
void CommandManager::Enable (wxString name, bool enabled)
References mCommandNameHash, and CommandListEntry::menu.
Referenced by EnableUsingFlags(), AudacityProject::ModifyUndoMenus(), and AudacityProject::UpdateMenus().
void CommandManager::EnableUsingFlags (wxUint32 flags, wxUint32 mask)
References Enable(), CommandListEntry::flags, CommandListEntry::index, CommandListEntry::mask, mCommandList, and CommandListEntry::multi.
Referenced by AudacityProject::UpdateMenus().
void CommandManager::EndMenu ()
This ends a menu by setting the pointer to it to NULL. It is still attached to the CurrentMenuBar()
References COMMAND, mCurrentMenu, mCurrentMenuName, and mHidingLevel.
Referenced by AudacityProject::CreateMenusAndCommands().
void CommandManager::EndSubMenu ()
This function is called after the final item of a SUBmenu is added. Submenu items are added just like regular menu items; they just happen after BeginSubMenu() is called but before EndSubMenu() is called.
References CurrentMenu(), mbSeparatorAllowed, SubMenuListEntry::menu, mHidingLevel, mSubMenuList, and SubMenuListEntry::name.
Referenced by AddItemList(), AudacityProject::CreateMenusAndCommands(), and AudacityProject::CreateRecentFilesMenu().
void CommandManager::GetAllCommandNames (wxArrayString & names, bool includeMultis)
References mCommandList, and name.
Referenced by GetAllMenuCommands::Apply(), and KeyConfigPrefs::RepopulateBindingsList().
void CommandManager::GetCategories (wxArrayString & cats)
References COMMAND, GetActiveProject(), mCommandList, name, and names.
Referenced by KeyConfigPrefs::Populate().
wxString CommandManager::GetCategoryFromName (wxString name)
References CommandListEntry::labelTop, and mCommandNameHash.
Referenced by KeyConfigPrefs::RepopulateBindingsList().
wxString CommandManager::GetDefaultKeyFromName (wxString name)
References CommandListEntry::defaultKey, and mCommandNameHash.
Referenced by KeyConfigPrefs::Apply(), HandleXMLTag(), and KeyConfigPrefs::OnDefaults().
bool CommandManager::GetEnabled (const wxString & name)
References CommandListEntry::enabled, mCommandNameHash, and CommandListEntry::menu.
Referenced by GetAllMenuCommands::Apply().
wxString CommandManager::GetKey (wxString label) [protected]
References KeyStringNormalize().
Referenced by NewIdentifier().
wxString CommandManager::GetKeyFromName (wxString name)
References CommandListEntry::key, and mCommandNameHash.
Referenced by KeyConfigPrefs::Apply(), LabelTrack::CaptureKey(), and KeyConfigPrefs::RepopulateBindingsList().
wxString CommandManager::GetLabelFromName (wxString name)
References CommandListEntry::label, and mCommandNameHash.
wxMenuBar * CommandManager::GetMenuBar (wxString sMenu) [protected]
Retrieves the menubar based on the name given in AddMenuBar(name)
References mMenuBarList, and name.
Referenced by AddMenuBar().
wxString CommandManager::GetPrefixedLabelFromName (wxString name)
References CommandListEntry::label, CommandListEntry::labelPrefix, and mCommandNameHash.
Referenced by KeyConfigPrefs::RepopulateBindingsList().
bool CommandManager::HandleCommandEntry (CommandListEntry * entry, wxUint32 flags, wxUint32 mask)
HandleCommandEntry() takes a CommandListEntry and executes it returning true iff successful. If you pass any flags, the command won't be executed unless the flags are compatible with the command's flags.
References CommandListEntry::callback, CommandListEntry::enabled, CommandListEntry::flags, GetActiveProject(), CommandListEntry::index, CommandListEntry::mask, TellUserWhyDisallowed(), and AudacityProject::TryToMakeActionAllowed().
Referenced by HandleKey(), HandleMenuID(), and HandleTextualCommand().
bool CommandManager::HandleKey (wxKeyEvent & evt, wxUint32 flags, wxUint32 mask)
Call this when a key event is received. If it matches a command, it will call the appropriate CommandManagerListener function. If you pass any flags, the command won't be executed unless the flags are compatible with the command's flags.
References HandleCommandEntry(), KeyEventToKeyString(), and mCommandKeyHash.
Referenced by AudacityProject::HandleKeyDown().
void CommandManager::HandleMenuClose (wxMenuEvent & evt)
References mOpenMenu, and ToggleAccels().
Referenced by HandleMenuOpen(), and AudacityProject::OnMenuEvent().
bool CommandManager::HandleMenuID (int id, wxUint32 flags, wxUint32 mask)
Call this when a menu event is received. If it matches a command, it will call the appropriate CommandManagerListener function. If you pass any flags, the command won't be executed unless the flags are compatible with the command's flags.
References HandleCommandEntry(), and mCommandIDHash.
Referenced by AudacityProject::OnMenu().
void CommandManager::HandleMenuOpen (wxMenuEvent & evt)
References HandleMenuClose(), mOpenMenu, and ToggleAccels().
Referenced by AudacityProject::OnMenuEvent().
bool CommandManager::HandleTextualCommand (wxString & Str, wxUint32 flags, wxUint32 mask)
HandleTextualCommand() allows us a limitted version of script/batch behavior, since we can get from a string command name to the actual code to run.
References ALL_EFFECTS, CONFIGURED_EFFECT, EffectManager::Get(), GetActiveProject(), EffectManager::GetEffects(), HandleCommandEntry(), mCommandList, and AudacityProject::OnEffect().
Referenced by ExecMenuCommand::Apply().
XMLTagHandler * CommandManager::HandleXMLChild (const wxChar * tag) [virtual]
Implements XMLTagHandler.
void CommandManager::HandleXMLEndTag (const wxChar * tag) [virtual]
Reimplemented from XMLTagHandler.
References mXMLKeysRead.
bool CommandManager::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements XMLTagHandler.
References GetDefaultKeyFromName(), XMLValueChecker::IsGoodString(), KeyStringNormalize(), mCommandNameHash, mXMLKeysRead, and name.
void CommandManager::InsertItem (wxString name, wxString label_in, CommandFunctor * callback, wxString after, int checkmark = -1)
Add a menu item to the current menu. When the user selects it, the given functor will be called
References GetActiveProject(), ItemShouldBeHidden(), label, mbSeparatorAllowed, mHiddenID, names, and NewIdentifier().
bool CommandManager::ItemShouldBeHidden (wxString & Label) [protected]
References mbHideFlaggedItems, and mHidingLevel.
Referenced by AddItem(), BeginMenu(), BeginSubMenu(), and InsertItem().
void CommandManager::Modify (wxString name, wxString newLabel)
Changes the label text of a menu item.
References CommandListEntry::id, CommandListEntry::key, CommandListEntry::label, mCommandNameHash, and CommandListEntry::menu.
Referenced by AudacityProject::ModifyUndoMenus(), and AudacityProject::OnEffect().
int CommandManager::NewIdentifier (wxString name, wxString label, wxMenu * menu, CommandFunctor * callback, bool multi, int index, int count) [protected]
Given all of the information for a command, comes up with a new unique ID, adds it to a list, and returns the ID. WARNING: Does this conflict with the identifiers set for controls/windows? If it does, a workaround may be to keep controls below wxID_LOWEST and keep menus above wxID_HIGHEST
References CommandListEntry::callback, CommandListEntry::count, CommandListEntry::defaultKey, CommandListEntry::enabled, CommandListEntry::flags, GetKey(), gPrefs, CommandListEntry::id, CommandListEntry::index, CommandListEntry::key, KeyStringNormalize(), CommandListEntry::label, CommandListEntry::labelPrefix, CommandListEntry::labelTop, CommandListEntry::mask, mCommandIDHash, mCommandKeyHash, mCommandList, mCommandNameHash, mCurrentID, mCurrentMenuName, mDefaultFlags, mDefaultMask, CommandListEntry::menu, mSubMenuList, CommandListEntry::multi, CommandListEntry::name, and NextIdentifier().
Referenced by AddCommand(), AddItem(), AddItemList(), and InsertItem().
int CommandManager::NextIdentifier (int ID) [protected]
Referenced by Enable(), and NewIdentifier().
void CommandManager::PurgeData ()
References CommandListEntry::callback, COMMAND, mCommandIDHash, mCommandKeyHash, mCommandList, mCommandNameHash, mCurrentID, mCurrentMenu, mCurrentMenuName, mMenuBarList, and mSubMenuList.
Referenced by AudacityProject::RebuildMenuBar(), and ~CommandManager().
void CommandManager::SetCommandFlags (wxUint32 flags, wxUint32 mask, ...)
References name, and SetCommandFlags().
void CommandManager::SetCommandFlags (const wxChar ** names, wxUint32 flags, wxUint32 mask)
References SetCommandFlags().
void CommandManager::SetCommandFlags (wxString name, wxUint32 flags, wxUint32 mask)
References CommandListEntry::flags, CommandListEntry::mask, and mCommandNameHash.
Referenced by AddCommand(), AddItem(), AudacityProject::CreateMenusAndCommands(), and SetCommandFlags().
void CommandManager::SetDefaultFlags (wxUint32 flags, wxUint32 mask)
References mDefaultFlags, and mDefaultMask.
Referenced by AudacityProject::CreateMenusAndCommands().
void CommandManager::SetKeyFromName (wxString name, wxString key)
References CommandListEntry::key, KeyStringNormalize(), and mCommandNameHash.
Referenced by KeyConfigPrefs::Cancel(), KeyConfigPrefs::OnClear(), KeyConfigPrefs::OnDefaults(), and KeyConfigPrefs::OnSet().
void CommandManager::TellUserWhyDisallowed (wxUint32 flagsGot, wxUint32 flagsRequired)
References AudioIONotBusyFlag, StereoRequiredFlag, TimeSelectedFlag, TracksExistFlag, and WaveTracksSelectedFlag.
Referenced by HandleCommandEntry().
void CommandManager::ToggleAccels (wxMenu * m, bool show) [protected]
References CommandListEntry::key, CommandListEntry::label, label, and mCommandIDHash.
Referenced by HandleMenuClose(), and HandleMenuOpen().
void CommandManager::WriteXML (XMLWriter & xmlFile) [virtual]
References AUDACITY_VERSION_STRING, XMLWriter::EndTag(), label, mCommandList, name, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
Referenced by KeyConfigPrefs::OnSave().
Member Data Documentation
bool CommandManager::mbHideFlaggedItems
Referenced by AudacityProject::CreateMenusAndCommands(), ItemShouldBeHidden(), and AudacityProject::OnSimplifiedView().
bool CommandManager::mbSeparatorAllowed [private]
Referenced by AddItem(), AddItemList(), AddSeparator(), BeginSubMenu(), EndSubMenu(), and InsertItem().
CommandIDHash CommandManager::mCommandIDHash [private]
Referenced by Enable(), HandleMenuID(), NewIdentifier(), PurgeData(), and ToggleAccels().
CommandNameHash CommandManager::mCommandKeyHash [private]
Referenced by HandleKey(), NewIdentifier(), and PurgeData().
CommandList CommandManager::mCommandList [private]
Referenced by EnableUsingFlags(), GetAllCommandNames(), GetCategories(), HandleTextualCommand(), NewIdentifier(), PurgeData(), and WriteXML().
CommandNameHash CommandManager::mCommandNameHash [private]
Referenced by Check(), Enable(), GetCategoryFromName(), GetDefaultKeyFromName(), GetEnabled(), GetKeyFromName(), GetLabelFromName(), GetPrefixedLabelFromName(), HandleXMLTag(), Modify(), NewIdentifier(), PurgeData(), SetCommandFlags(), and SetKeyFromName().
int CommandManager::mCurrentID [private]
Referenced by NewIdentifier(), and PurgeData().
wxMenu* CommandManager::mCurrentMenu [private]
Referenced by BeginMenu(), CurrentMenu(), EndMenu(), and PurgeData().
wxString CommandManager::mCurrentMenuName [private]
Referenced by BeginMenu(), EndMenu(), NewIdentifier(), and PurgeData().
wxUint32 CommandManager::mDefaultFlags [private]
Referenced by NewIdentifier(), and SetDefaultFlags().
wxUint32 CommandManager::mDefaultMask [private]
Referenced by NewIdentifier(), and SetDefaultFlags().
int CommandManager::mHiddenID [private]
Referenced by AddItem(), and InsertItem().
int CommandManager::mHidingLevel [private]
Referenced by AddItemList(), AddMenuBar(), AddSeparator(), BeginMenu(), BeginSubMenu(), EndMenu(), EndSubMenu(), and ItemShouldBeHidden().
MenuBarList CommandManager::mMenuBarList [private]
Referenced by AddMenuBar(), CurrentMenuBar(), GetMenuBar(), and PurgeData().
wxMenu* CommandManager::mOpenMenu [private]
Referenced by HandleMenuClose(), and HandleMenuOpen().
SubMenuList CommandManager::mSubMenuList [private]
Referenced by BeginSubMenu(), CurrentSubMenu(), EndSubMenu(), NewIdentifier(), and PurgeData().
int CommandManager::mXMLKeysRead [private]
Referenced by HandleXMLEndTag(), and HandleXMLTag().
The documentation for this class was generated from the following files:
CommandManager.h
CommandManager.cpp