Audacity: EffectRepair Class Reference
EffectRepair Class Reference
Use the interpolation code to fill in damaged audio. Damage can include pops, clicks, or clipping. As long as the damaged section is short and surrounded by lots of good audio, it is usually quite successful.
#include <Repair.h>
Public Member Functions
EffectRepair ()
virtual ~EffectRepair ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Process ()
Private Member Functions
bool ProcessOne (int count, WaveTrack *track, sampleCount start, sampleCount len, sampleCount repairStart, sampleCount repairLen)
Detailed Description
Use the interpolation code to fill in damaged audio. Damage can include pops, clicks, or clipping. As long as the damaged section is short and surrounded by lots of good audio, it is usually quite successful.
This was formerly the PopClickRemoval effect, but it was renamed and focused on the smaller subproblem of repairing the audio, rather than actually finding the clicks.
Constructor & Destructor Documentation
EffectRepair::EffectRepair ()
EffectRepair::~EffectRepair () [virtual]
Member Function Documentation
virtual wxString EffectRepair::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectRepair::GetEffectCategories () [inline, virtual]
virtual wxString EffectRepair::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectRepair::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectRepair::Process () [virtual]
The Repair effect needs some data to go on.
select an area to repair with some audio on at least one side (the more the better).));
Implements Effect.
References Effect::CopyInputTracks(), TrackListCondIterator::First(), WaveTrack::GetEndTime(), WaveTrack::GetRate(), WaveTrack::GetStartTime(), Effect::mOutputTracks, Effect::mT0, Effect::mT1, TrackListCondIterator::Next(), ProcessOne(), Effect::ReplaceProcessedTracks(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectRepair::ProcessOne (int count, WaveTrack * track, sampleCount start, sampleCount len, sampleCount repairStart, sampleCount repairLen) [private]
References floatSample, WaveTrack::Get(), InterpolateAudio(), WaveTrack::Set(), and Effect::TrackProgress().
Referenced by Process().
bool EffectRepair::PromptUser () [virtual]
Reimplemented from Effect.
bool EffectRepair::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
The documentation for this class was generated from the following files:
Repair.h
Repair.cpp