Audacity: PlatformCompatibility Class Reference
PlatformCompatibility Class Reference
Filename Compatibility utilities.
#include <PlatformCompatibility.h>
Static Public Member Functions
static wxString GetLongFileName (const wxString &shortFileName)
static wxString GetExecutablePath ()
static wxString ConvertSlashInFileName (const wxString &filePath)
Detailed Description
Filename Compatibility utilities.
See also:
FileNames
Member Function Documentation
wxString PlatformCompatibility::ConvertSlashInFileName (const wxString & filePath) [static]
Referenced by AudacityProject::OpenFile().
wxString PlatformCompatibility::GetExecutablePath () [static]
Referenced by FileNames::DataDir(), and FileNames::HtmlHelpDir().
wxString PlatformCompatibility::GetLongFileName (const wxString & shortFileName) [static]
Referenced by EffectNoiseRemoval::CleanSpeechMayWriteNoiseGate(), and AudacityProject::OpenFile().
The documentation for this class was generated from the following files:
PlatformCompatibility.h
PlatformCompatibility.cpp