Audacity: ExportFFmpeg Class Reference
ExportFFmpeg Class Reference
Controlling class for FFmpeg exporting. Creates the options dialog of the appropriate type, adds tags and invokes the export function.
Public Member Functions
ExportFFmpeg ()
void Destroy ()
bool CheckFileName (wxFileName &filename, int format=0)
Callback, called from GetFilename.
bool Init (const char *shortname, AudacityProject *project, Tags *metadata)
Format intialization.
bool InitCodecs (AudacityProject *project)
Codec intialization.
bool AddTags (Tags *metadata)
Writes metadata.
bool EncodeAudioFrame (int16_t *pFrame, int frameSize)
Encodes audio.
bool Finalize ()
Flushes audio encoder.
bool DisplayOptions (wxWindow *parent, int format=0)
bool CheckSampleRate (int rate, int lowrate, int highrate, const int *sampRates)
Check whether or not current project sample rate is compatible with the export codec.
int AskResample (int bitrate, int rate, int lowrate, int highrate, const int *sampRates)
Asks user to resample the project or cancel the export procedure.
int Export (AudacityProject *project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec *mixerSpec=NULL, Tags *metadata=NULL, int subformat=0)
Private Attributes
AVFormatContext * mEncFormatCtx
AVOutputFormat * mEncFormatDesc
AVStream * mEncAudioStream
AVCodecContext * mEncAudioCodecCtx
uint8_t * mEncAudioEncodedBuf
int mEncAudioEncodedBufSiz
AVFifoBuffer * mEncAudioFifo
uint8_t * mEncAudioFifoOutBuf
wxString mName
int mSubFormat
int mBitRate
int mSampleRate
int mChannels
bool mSupportsUTF8
Detailed Description
Controlling class for FFmpeg exporting. Creates the options dialog of the appropriate type, adds tags and invokes the export function.
Constructor & Destructor Documentation
ExportFFmpeg::ExportFFmpeg ()
References ExportPlugin::AddExtension(), ExportPlugin::AddFormat(), FFmpegLibs::avcodec_find_encoder, ExposedFormat::compiledIn, FMT_LAST, FMT_M4A, FMT_WMA2, ExportFFmpegOptions::fmts, FFmpegLibs::guess_format, MAX_AUDIO_PACKET_SIZE, mEncAudioCodecCtx, mEncAudioEncodedBuf, mEncAudioEncodedBufSiz, mEncAudioFifoOutBuf, mEncAudioStream, mEncFormatCtx, mEncFormatDesc, mSampleRate, mSupportsUTF8, name, PickFFmpegLibs(), ExportPlugin::SetCanMetaData(), ExportPlugin::SetDescription(), ExportPlugin::SetFormat(), and ExportPlugin::SetMaxChannels().
Member Function Documentation
bool ExportFFmpeg::AddTags (Tags * metadata)
Writes metadata.
References AddStringTagANSI(), AddStringTagUTF8(), Tags::GetTag(), mEncFormatCtx, mSupportsUTF8, TAG_ALBUM, TAG_ARTIST, TAG_COMMENTS, TAG_GENRE, TAG_TITLE, TAG_TRACK, and TAG_YEAR.
Referenced by Init().
int ExportFFmpeg::AskResample (int bitrate, int rate, int lowrate, int highrate, const int * sampRates)
Asks user to resample the project or cancel the export procedure.
References ShuttleGuiBase::AddChoice(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTitle(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), label, name, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::StartVerticalLay().
Referenced by InitCodecs().
bool ExportFFmpeg::CheckFileName (wxFileName & filename, int format = 0) [virtual]
Callback, called from GetFilename.
Reimplemented from ExportPlugin.
References AdjustFormatIndex(), CheckFFmpegPresence(), and FMT_AMRNB.
bool ExportFFmpeg::CheckSampleRate (int rate, int lowrate, int highrate, const int * sampRates)
Check whether or not current project sample rate is compatible with the export codec.
Referenced by InitCodecs().
void ExportFFmpeg::Destroy () [virtual]
Reimplemented from ExportPlugin.
References DropFFmpegLibs().
bool ExportFFmpeg::DisplayOptions (wxWindow * parent, int format = 0) [virtual]
Shows options dialog
Parameters:
format - index of export type
Reimplemented from ExportPlugin.
References AdjustFormatIndex(), CheckFFmpegPresence(), FMT_AC3, FMT_AMRNB, FMT_M4A, FMT_OTHER, FMT_WMA2, and mSubFormat.
bool ExportFFmpeg::EncodeAudioFrame (int16_t * pFrame, int frameSize)
Encodes audio.
References FFmpegLibs::av_fifo_generic_read, FFmpegLibs::av_fifo_generic_write, FFmpegLibs::av_fifo_realloc2, FFmpegLibs::av_fifo_size, FFmpegLibs::av_init_packet, FFmpegLibs::av_interleaved_write_frame, FFmpegLibs::av_rescale_q, FFmpegLibs::avcodec_encode_audio, mEncAudioCodecCtx, mEncAudioEncodedBuf, mEncAudioEncodedBufSiz, mEncAudioFifo, mEncAudioFifoOutBuf, mEncAudioStream, and mEncFormatCtx.
Referenced by Export().
int ExportFFmpeg::Export (AudacityProject * project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec * mixerSpec = NULL, Tags * metadata = NULL, int subformat = 0) [virtual]
Exports audio
Parameters:
project Audacity project
fName output file name
selectedOnly true if exporting only selected audio
t0 audio start time
t1 audio end time
mixerSpec mixer
metadata tags to write into file
subformat index of export type
Returns:
true if export succeded
Reimplemented from ExportPlugin.
References AdjustFormatIndex(), CheckFFmpegPresence(), EncodeAudioFrame(), eProgressSuccess, Finalize(), FMT_LAST, FMT_OTHER, ExportFFmpegOptions::fmts, Mixer::GetBuffer(), TrackList::GetTimeTrack(), AudacityProject::GetTracks(), TrackList::GetWaveTracks(), gPrefs, Init(), int16Sample, mChannels, Mixer::MixGetCurrentTime(), mName, mSampleRate, mSubFormat, Mixer::Process(), and ProgressDialog::Update().
bool ExportFFmpeg::Finalize ()
Flushes audio encoder.
References FFmpegLibs::av_fifo_free, FFmpegLibs::av_fifo_generic_read, FFmpegLibs::av_fifo_size, FFmpegLibs::av_free, FFmpegLibs::av_freep, FFmpegLibs::av_init_packet, FFmpegLibs::av_interleaved_write_frame, FFmpegLibs::av_rescale_q, FFmpegLibs::av_write_trailer, FFmpegLibs::avcodec_close, FFmpegLibs::avcodec_encode_audio, gPrefs, mEncAudioCodecCtx, mEncAudioEncodedBuf, mEncAudioEncodedBufSiz, mEncAudioFifo, mEncAudioFifoOutBuf, mEncAudioStream, mEncFormatCtx, mEncFormatDesc, and FFmpegLibs::url_fclose.
Referenced by Export().
bool ExportFFmpeg::Init (const char * shortname, AudacityProject * project, Tags * metadata)
Format intialization.
References AddTags(), FFmpegLibs::av_alloc_format_context, FFmpegLibs::av_log_set_callback, av_log_wx_callback(), FFmpegLibs::av_new_stream, FFmpegLibs::av_set_parameters, FFmpegLibs::av_write_header, ExposedFormat::canutf8, ExportFFmpegOptions::fmts, AudacityProject::GetTags(), FFmpegLibs::guess_format, InitCodecs(), mEncAudioStream, mEncFormatCtx, mEncFormatDesc, mName, mSubFormat, mSupportsUTF8, OSINPUT, ufile_fopen(), and FFmpegLibs::ValidLibsLoaded().
Referenced by Export().
bool ExportFFmpeg::InitCodecs (AudacityProject * project)
Codec intialization.
References AskResample(), FFmpegLibs::av_codec_get_tag, FFmpegLibs::av_fifo_alloc, FFmpegLibs::av_malloc, FFmpegLibs::avcodec_find_encoder, FFmpegLibs::avcodec_get_context_defaults, FFmpegLibs::avcodec_open, CheckSampleRate(), ExposedFormat::codecid, FMT_AC3, FMT_AMRNB, FMT_M4A, FMT_OTHER, FMT_WMA2, ExportFFmpegOptions::fmts, AudacityProject::GetRate(), gPrefs, ExportFFmpegOptions::iAACSampleRates, ExportFFmpegAC3Options::iAC3SampleRates, ExportFFmpegWMAOptions::iWMASampleRates, MAX_AUDIO_PACKET_SIZE, mChannels, mEncAudioCodecCtx, mEncAudioEncodedBuf, mEncAudioEncodedBufSiz, mEncAudioFifo, mEncAudioFifoOutBuf, mEncAudioStream, mEncFormatCtx, mEncFormatDesc, mSampleRate, and mSubFormat.
Referenced by Init().
Member Data Documentation
int ExportFFmpeg::mBitRate [private]
int ExportFFmpeg::mChannels [private]
Referenced by Export(), and InitCodecs().
AVCodecContext* ExportFFmpeg::mEncAudioCodecCtx [private]
Referenced by EncodeAudioFrame(), ExportFFmpeg(), Finalize(), and InitCodecs().
uint8_t* ExportFFmpeg::mEncAudioEncodedBuf [private]
Referenced by EncodeAudioFrame(), ExportFFmpeg(), Finalize(), and InitCodecs().
int ExportFFmpeg::mEncAudioEncodedBufSiz [private]
Referenced by EncodeAudioFrame(), ExportFFmpeg(), Finalize(), and InitCodecs().
AVFifoBuffer* ExportFFmpeg::mEncAudioFifo [private]
Referenced by EncodeAudioFrame(), Finalize(), and InitCodecs().
uint8_t* ExportFFmpeg::mEncAudioFifoOutBuf [private]
Referenced by EncodeAudioFrame(), ExportFFmpeg(), Finalize(), and InitCodecs().
AVStream* ExportFFmpeg::mEncAudioStream [private]
Referenced by EncodeAudioFrame(), ExportFFmpeg(), Finalize(), Init(), and InitCodecs().
AVFormatContext* ExportFFmpeg::mEncFormatCtx [private]
Referenced by AddTags(), EncodeAudioFrame(), ExportFFmpeg(), Finalize(), Init(), and InitCodecs().
AVOutputFormat* ExportFFmpeg::mEncFormatDesc [private]
Referenced by ExportFFmpeg(), Finalize(), Init(), and InitCodecs().
wxString ExportFFmpeg::mName [private]
Referenced by Export(), and Init().
int ExportFFmpeg::mSampleRate [private]
Referenced by Export(), ExportFFmpeg(), and InitCodecs().
int ExportFFmpeg::mSubFormat [private]
Referenced by DisplayOptions(), Export(), Init(), and InitCodecs().
bool ExportFFmpeg::mSupportsUTF8 [private]
Referenced by AddTags(), ExportFFmpeg(), and Init().
The documentation for this class was generated from the following file:
ExportFFmpeg.cpp