Audacity: ExportMP2 Class Reference
ExportMP2 Class Reference
Public Member Functions
ExportMP2 ()
void Destroy ()
bool DisplayOptions (wxWindow *parent, int format=0)
int Export (AudacityProject *project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec *mixerSpec=NULL, Tags *metadata=NULL, int subformat=0)
called to export audio into a file.
Private Member Functions
int AddTags (AudacityProject *project, char **buffer, bool *endOfFile, Tags *tags)
Constructor & Destructor Documentation
ExportMP2::ExportMP2 ()
References ExportPlugin::AddExtension(), ExportPlugin::AddFormat(), ExportPlugin::SetCanMetaData(), ExportPlugin::SetDescription(), ExportPlugin::SetFormat(), and ExportPlugin::SetMaxChannels().
Member Function Documentation
int ExportMP2::AddTags (AudacityProject * project, char ** buffer, bool * endOfFile, Tags * tags) [private]
References Tags::GetFirst(), Tags::GetGenre(), Tags::GetID3V2(), Tags::GetNext(), id3_frame_new(), name, TAG_ALBUM, TAG_ARTIST, TAG_COMMENTS, TAG_GENRE, TAG_TITLE, TAG_TRACK, and TAG_YEAR.
Referenced by Export().
void ExportMP2::Destroy () [virtual]
Reimplemented from ExportPlugin.
bool ExportMP2::DisplayOptions (wxWindow * parent, int format = 0) [virtual]
Reimplemented from ExportPlugin.
int ExportMP2::Export (AudacityProject * project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec * mixerSpec = NULL, Tags * metadata = NULL, int subformat = 0) [virtual]
called to export audio into a file.
Parameters:
selectedOnly Set to true if all tracks should be mixed, to false if only the selected tracks should be mixed and exported.
metadata A Tags object that will over-ride the one in *project and be used to tag the file that is exported.
subformat Control which of the multiple formats this exporter is capable of exporting should be used. Used where a single export plug-in handles a number of related formats, but they have separate entries in the Format drop-down list box. For example, the options to export to "Other PCM", "AIFF 16 Bit" and "WAV 16 Bit" are all the same libsndfile export plug-in, but with subformat set to 0, 1, and 2 respectively.
Reimplemented from ExportPlugin.
References AddTags(), FileIO::Close(), eProgressSuccess, Mixer::GetBuffer(), AudacityProject::GetRate(), AudacityProject::GetTags(), TrackList::GetTimeTrack(), AudacityProject::GetTracks(), TrackList::GetWaveTracks(), gPrefs, int16Sample, FileIO::IsOpened(), Mixer::MixGetCurrentTime(), FileIO::Output, Mixer::Process(), ProgressDialog::Update(), and FileIO::Write().
The documentation for this class was generated from the following file:
ExportMP2.cpp