Audacity: ExportFLACOptions Class Reference
ExportFLACOptions Class Reference
Public Member Functions
ExportFLACOptions (wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
void OnOK (wxCommandEvent &event)
Constructor & Destructor Documentation
ExportFLACOptions::ExportFLACOptions (wxWindow * parent)
References eIsCreatingFromPrefs.
Member Function Documentation
void ExportFLACOptions::OnOK (wxCommandEvent & event)
References eIsSavingToPrefs, and PopulateOrExchange().
void ExportFLACOptions::PopulateOrExchange (ShuttleGui & S)
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndTwoColumn(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartTwoColumn(), and ShuttleGuiBase::TieChoice().
Referenced by OnOK().
The documentation for this class was generated from the following file:
ExportFLAC.cpp