Audacity: ODWaveTrackTaskQueue Class Reference
ODWaveTrackTaskQueue Class Reference
A class representing a modular task to be used with the On-Demand structures.
#include <ODWaveTrackTaskQueue.h>
Public Member Functions
ODWaveTrackTaskQueue ()
Constructs an ODWaveTrackTaskQueue.
virtual ~ODWaveTrackTaskQueue ()
void AddWaveTrack (WaveTrack *track)
Adds a track to the associated list.
void RemoveWaveTrack (WaveTrack *track)
void DemandTrackUpdate (WaveTrack *track, double seconds)
changes the tasks associated with this Waveform to process the task from a different point in the track
void ReplaceWaveTrack (WaveTrack *oldTrack, WaveTrack *newTrack)
replaces all instances of a WaveTrack within this task with another.
void MakeWaveTrackIndependent (WaveTrack *track)
virtual bool CanMergeWith (ODWaveTrackTaskQueue *otherQueue)
returns whether or not this queue's task list and another's can merge together, as when we make two mono tracks stereo.
void MergeWaveTrack (WaveTrack *track)
bool ContainsWaveTrack (WaveTrack *track)
returns true if the argument is in the WaveTrack list.
WaveTrack * GetWaveTrack (size_t x)
int GetNumWaveTracks ()
returns the number of wavetracks in this queue.
void AddTask (ODTask *task)
Add a task to the queue.
bool IsEmpty ()
bool IsFrontTaskComplete ()
void RemoveFrontTask ()
Removes and deletes the front task from the list.
ODTask * GetFrontTask ()
Schedules the front task for immediate execution.
int GetNumTasks ()
returns the number of ODTasks in this queue
ODTask * GetTask (size_t x)
returns a ODTask at position x
void FillTipForWaveTrack (WaveTrack *t, const wxChar **ppTip)
fills in the status bar message for a given track
Protected Attributes
wxString mTipMsg
std::vector< WaveTrack * > mTracks
the list of tracks associated with this queue.
ODLock mTracksMutex
std::vector< ODTask * > mTasks
the list of tasks associated with the tracks. This class owns these tasks.
ODLock mTasksMutex
Detailed Description
A class representing a modular task to be used with the On-Demand structures.
watches over all to be done (not yet started and started but not finished) tasks associated with a WaveTrack.
Constructor & Destructor Documentation
ODWaveTrackTaskQueue::ODWaveTrackTaskQueue ()
Constructs an ODWaveTrackTaskQueue.
ODWaveTrackTaskQueue::~ODWaveTrackTaskQueue () [virtual]
References ODManager::Instance(), mTasks, and ODManager::RemoveTaskIfInQueue().
Member Function Documentation
void ODWaveTrackTaskQueue::AddTask (ODTask * task)
Add a task to the queue.
References ODTask::GetNumWaveTracks(), ODTask::GetWaveTrack(), mTasks, mTasksMutex, mTracks, and mTracksMutex.
Referenced by ODManager::AddNewTask().
void ODWaveTrackTaskQueue::AddWaveTrack (WaveTrack * track)
Adds a track to the associated list.
References mTracks, and mTracksMutex.
Referenced by MergeWaveTrack().
bool ODWaveTrackTaskQueue::CanMergeWith (ODWaveTrackTaskQueue * otherQueue) [virtual]
returns whether or not this queue's task list and another's can merge together, as when we make two mono tracks stereo.
References GetNumTasks(), GetTask(), mTasks, and mTasksMutex.
Referenced by ODManager::MakeWaveTrackDependent().
bool ODWaveTrackTaskQueue::ContainsWaveTrack (WaveTrack * track)
returns true if the argument is in the WaveTrack list.
References mTracks, and mTracksMutex.
Referenced by FillTipForWaveTrack().
void ODWaveTrackTaskQueue::DemandTrackUpdate (WaveTrack * track, double seconds)
changes the tasks associated with this Waveform to process the task from a different point in the track
changes the tasks associated with this Waveform to process the task from a different point in the track
Parameters:
track the track to update
seconds the point in the track from which the tasks associated with track should begin processing from.
References mTasks, and mTracksMutex.
void ODWaveTrackTaskQueue::FillTipForWaveTrack (WaveTrack * t, const wxChar ** ppTip)
fills in the status bar message for a given track
References ContainsWaveTrack(), GetFrontTask(), GetNumTasks(), and mTipMsg.
ODTask * ODWaveTrackTaskQueue::GetFrontTask ()
Schedules the front task for immediate execution.
References mTasks, and mTasksMutex.
Referenced by FillTipForWaveTrack(), and ODManager::UpdateQueues().
int ODWaveTrackTaskQueue::GetNumTasks ()
returns the number of ODTasks in this queue
References mTasks, and mTasksMutex.
Referenced by CanMergeWith(), and FillTipForWaveTrack().
int ODWaveTrackTaskQueue::GetNumWaveTracks ()
returns the number of wavetracks in this queue.
References mTracks, and mTracksMutex.
ODTask * ODWaveTrackTaskQueue::GetTask (size_t x)
returns a ODTask at position x
References mTasks, and mTasksMutex.
Referenced by CanMergeWith().
WaveTrack * ODWaveTrackTaskQueue::GetWaveTrack (size_t x)
References mTracks, and mTracksMutex.
bool ODWaveTrackTaskQueue::IsEmpty ()
References mTasks, mTasksMutex, mTracks, and mTracksMutex.
bool ODWaveTrackTaskQueue::IsFrontTaskComplete ()
References mTasks, and mTasksMutex.
void ODWaveTrackTaskQueue::MakeWaveTrackIndependent (WaveTrack * track)
References ODManager::AddNewTask(), ODTask::AddWaveTrack(), ODManager::Instance(), mTasks, mTasksMutex, mTracks, mTracksMutex, and RemoveWaveTrack().
Referenced by ODManager::MakeWaveTrackIndependent().
void ODWaveTrackTaskQueue::MergeWaveTrack (WaveTrack * track)
add track to the masterTrack's queue - this will allow future ODScheduling to affect them together. sets the NeedODUpdateFlag since we don't want the head task to finish without haven't dealt with the depednent
Parameters:
track the track to bring into the tasks AND tracklist for this queue
References AddWaveTrack(), mTasks, and mTasksMutex.
Referenced by ODManager::MakeWaveTrackDependent().
void ODWaveTrackTaskQueue::RemoveFrontTask ()
Removes and deletes the front task from the list.
References mTasks, and mTasksMutex.
void ODWaveTrackTaskQueue::RemoveWaveTrack (WaveTrack * track)
Removes a track from the list. Also notifies mTasks to stop using references to the instance in a thread-safe manner (may block)
References mTasks, mTasksMutex, mTracks, and mTracksMutex.
Referenced by MakeWaveTrackIndependent().
void ODWaveTrackTaskQueue::ReplaceWaveTrack (WaveTrack * oldTrack, WaveTrack * newTrack)
replaces all instances of a WaveTrack within this task with another.
References mTasks, mTasksMutex, mTracks, and mTracksMutex.
Member Data Documentation
std::vector<ODTask*> ODWaveTrackTaskQueue::mTasks [protected]
the list of tasks associated with the tracks. This class owns these tasks.
Referenced by AddTask(), CanMergeWith(), DemandTrackUpdate(), GetFrontTask(), GetNumTasks(), GetTask(), IsEmpty(), IsFrontTaskComplete(), MakeWaveTrackIndependent(), MergeWaveTrack(), RemoveFrontTask(), RemoveWaveTrack(), ReplaceWaveTrack(), and ~ODWaveTrackTaskQueue().
ODLock ODWaveTrackTaskQueue::mTasksMutex [protected]
Referenced by AddTask(), CanMergeWith(), GetFrontTask(), GetNumTasks(), GetTask(), IsEmpty(), IsFrontTaskComplete(), MakeWaveTrackIndependent(), MergeWaveTrack(), RemoveFrontTask(), RemoveWaveTrack(), and ReplaceWaveTrack().
wxString ODWaveTrackTaskQueue::mTipMsg [protected]
Referenced by FillTipForWaveTrack().
std::vector<WaveTrack*> ODWaveTrackTaskQueue::mTracks [protected]
the list of tracks associated with this queue.
Referenced by AddTask(), AddWaveTrack(), ContainsWaveTrack(), GetNumWaveTracks(), GetWaveTrack(), IsEmpty(), MakeWaveTrackIndependent(), RemoveWaveTrack(), and ReplaceWaveTrack().
ODLock ODWaveTrackTaskQueue::mTracksMutex [protected]
Referenced by AddTask(), AddWaveTrack(), ContainsWaveTrack(), DemandTrackUpdate(), GetNumWaveTracks(), GetWaveTrack(), IsEmpty(), MakeWaveTrackIndependent(), RemoveWaveTrack(), and ReplaceWaveTrack().
The documentation for this class was generated from the following files:
ODWaveTrackTaskQueue.h
ODWaveTrackTaskQueue.cpp