#!/bin/sh
#
# Prepare a disk image
#

#
SUFFIX=$1
TYPE=$2

# Setup
VER=`grep AUDACITY_VERSION_STRING src/Audacity.h | cut -f 2 -d '"'`
VERSION=`echo $VER | cut -f 1 -d '.'`
RELEASE=`echo $VER | cut -f 2 -d '.'`
REVISION=`echo $VER | cut -f 3 -d '.' | cut -f 1 -d '-'`

if [ -z "$SUFFIX" ]
then
   SUFFIX=`echo $VER- | cut -f 2 -d '-'`
fi

if [ ! -z "$TYPE" ]
then
   TYPE="-$TYPE"
fi

VERSION=$VERSION.$RELEASE.$REVISION$SUFFIX

VOL="Audacity $VERSION"
DMG="audacity-macosx$TYPE-$VERSION"

# Preclean
rm -rf "$DMG" "$DMG.dmg" TMP.dmg

# Create structure
mkdir "$DMG"
mkdir "$DMG/Languages"
mkdir "$DMG/nyquist"
mkdir "$DMG/plug-ins"

# Copy Audacity and clean it
cp -pR Audacity.app "$DMG"
strip "$DMG/Audacity.app/Contents/MacOS/audacity"

# Copy Languages
for name in locale/*.po
do
   src=`echo $name | sed -e 's/.po//'`
   dst="$DMG/Languages/`basename $src`"
   cp -pR $src $dst
done

# Copy Nyquist
cp -pR nyquist "$DMG"
rm -rf "$DMG/nyquist/"*CVS*

# Copy Plug-ins
cp -pR plug-ins "$DMG"
rm -rf "$DMG/plug-ins/"*CVS*

# Install misc files
cp -pR README.txt LICENSE.txt audacity-*-help.htb "$DMG"

# Create and mount the image
hdiutil create -ov -srcdir "$DMG" -fs HFS+ -volname "$VOL" TMP.dmg

# Compress and prepare for Internet delivery
hdiutil convert TMP.dmg -format UDZO -imagekey zlib-level=9 -o "$DMG.dmg"
hdiutil internet-enable -yes "$DMG.dmg"

# Cleanup
rm TMP.dmg

exit
