#!/bin/sh
#
# Prepare a disk image
#

#
SUFFIX=$1
TYPE=$2

# Setup
VERSION=`awk '/^#define+ AUDACITY_VERSION / {print $3}' src/Audacity.h`
RELEASE=`awk '/^#define+ AUDACITY_RELEASE / {print $3}' src/Audacity.h`
REVISION=`awk '/^#define+ AUDACITY_REVISION / {print $3}' src/Audacity.h`

if [ -z "$SUFFIX" ]
then
   SUFFIX=`egrep '^#define AUDACITY_SUFFIX +wxT' src/Audacity.h | cut -d '"' -f 2`
fi

if [ ! -z "$TYPE" ]
then
   TYPE="-$TYPE"
fi

VERSION=$VERSION.$RELEASE.$REVISION$SUFFIX

case `grep "^#define.*AUDACITY_BRANDING.*BRAND_" src/AudacityBranding.h | cut -f 3-5 -d "_"`
in
   UMIXIT)
      APP="UmixIt, powered by Audacity.app"
      VOL="UmixIt $VERSION"
      DMG="audacity_umixit-osx$TYPE-$VERSION"
   ;;
   THINKLABS)
      APP="Thinklabs Phonocardiography, powered by Audacity.app"
      VOL="Audacity Thinklabs$VERSION"
      DMG="audacity_thinklabs-osx$TYPE-$VERSION"
   ;;
   JAMLING__EASY)
      APP="Camp Jam, powered by Audacity.app"
      VOL="Audacity Camp Jam$VERSION"
      DMG="audacity_camp_jam-osx$TYPE-$VERSION-Easy"
   ;;
   JAMLING__FULL)
      APP="Camp Jam, powered by Audacity.app"
      VOL="Audacity Camp Jam$VERSION"
      DMG="audacity_camp_jam-osx$TYPE-$VERSION-Full"
   ;;
   *)
      APP="Audacity.app"
      VOL="Audacity $VERSION"
      DMG="audacity-osx$TYPE-$VERSION"
   ;;
esac

# Preclean
rm -rf "$DMG" "$DMG.dmg" TMP.dmg

# Create structure
mkdir "$DMG"
mkdir "$DMG/Languages"
mkdir "$DMG/nyquist"
mkdir "$DMG/plug-ins"

# Copy Audacity and clean it
cp -pR 'mac/build/Release Static Unicode/Audacity.app' "$DMG/$APP"
sed -i '' -e "s/v.r.r/$VERSION/g" "$DMG/$APP/Contents/Info.plist"
strip "$DMG/$APP/Contents/MacOS/"*

# Copy Languages
for name in locale/*.po
do
   src=`echo $name | sed -e 's/.po//'`
   dst="$DMG/Languages/`basename $src`"
   cp -pR $src $dst
done

# Copy Nyquist
cp -pR nyquist "$DMG"
rm -rf "$DMG/nyquist/"*CVS*

# Copy Plug-ins
cp -pR plug-ins "$DMG"
rm -rf "$DMG/plug-ins/"*CVS*

# Install misc files
cp -pR README.txt LICENSE.txt "$DMG"

# Create and mount the image
hdiutil create -ov -srcdir "$DMG" -fs HFS+ -volname "$VOL" TMP.dmg

# Compress and prepare for Internet delivery
hdiutil convert TMP.dmg -format UDZO -imagekey zlib-level=9 -o "$DMG.dmg"
hdiutil internet-enable -yes "$DMG.dmg"

# Cleanup
rm TMP.dmg

exit
