Audacity: AudacityApp.h File Reference
AudacityApp.h File Reference
#include "Audacity.h"
#include <wx/app.h>
#include <wx/dir.h>
#include <wx/event.h>
#include <wx/docview.h>
#include <wx/intl.h>
#include <wx/snglinst.h>
#include <wx/log.h>
#include "widgets/FileHistory.h"
Classes
class AudacityApp
AudacityApp is the 'main' class for Audacity.
Defines
#define MAX_AUDIO (1. - 1./(1<<15))
#define JUST_BELOW_MAX_AUDIO (1. - 1./(1<<14))
Enumerations
enum {
AlwaysEnabledFlag = 0x00000000, AudioIONotBusyFlag = 0x00000001, TimeSelectedFlag = 0x00000002, TracksSelectedFlag = 0x00000004,
TracksExistFlag = 0x00000008, LabelTracksExistFlag = 0x00000010, WaveTracksSelectedFlag = 0x00000020, ClipboardFlag = 0x00000040,
TextClipFlag = 0x00000040, UnsavedChangesFlag = 0x00000080, HasLastEffectFlag = 0x00000100, UndoAvailableFlag = 0x00000200,
RedoAvailableFlag = 0x00000400, ZoomInAvailableFlag = 0x00000800, ZoomOutAvailableFlag = 0x00001000, StereoRequiredFlag = 0x00002000,
TopDockHasFocus = 0x00004000, TrackPanelHasFocus = 0x00008000, BotDockHasFocus = 0x00010000, LabelsSelectedFlag = 0x00020000,
AudioIOBusyFlag = 0x00040000, PlayRegionLockedFlag = 0x00080000, PlayRegionNotLockedFlag = 0x00100000, CutCopyAvailableFlag = 0x00200000,
WaveTracksExistFlag = 0x00400000, NoteTracksExistFlag = 0x00800000, NoteTracksSelectedFlag = 0x01000000, HaveRecentFiles = 0x02000000,
LinkingDisabledFlag = 0x04000000, NoFlagsSpecifed = 0xffffffff
}
Functions
void SaveWindowSize ()
void QuitAudacity (bool bForce)
void QuitAudacity ()
DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API, EVT_OPEN_AUDIO_FILE,-1)
DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API, EVT_CAPTURE_KEYBOARD,-1)
DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API, EVT_RELEASE_KEYBOARD,-1)
DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API, EVT_CAPTURE_KEY,-1)
AudacityApp & wxGetApp ()
Variables
bool gIsQuitting
Define Documentation
#define JUST_BELOW_MAX_AUDIO (1. - 1./(1<<14))
Referenced by ODPCMAliasBlockFile::GetMinMax().
#define MAX_AUDIO (1. - 1./(1<<15))
Referenced by TrackArtist::DrawIndividualSamples(), TrackArtist::DrawMinMaxRMS(), EffectFindClipping::ProcessOne(), and Meter::UpdateDisplay().
Enumeration Type Documentation
anonymous enum
Enumerator:
AlwaysEnabledFlag
AudioIONotBusyFlag
TimeSelectedFlag
TracksSelectedFlag
TracksExistFlag
LabelTracksExistFlag
WaveTracksSelectedFlag
ClipboardFlag
TextClipFlag
UnsavedChangesFlag
HasLastEffectFlag
UndoAvailableFlag
RedoAvailableFlag
ZoomInAvailableFlag
ZoomOutAvailableFlag
StereoRequiredFlag
TopDockHasFocus
TrackPanelHasFocus
BotDockHasFocus
LabelsSelectedFlag
AudioIOBusyFlag
PlayRegionLockedFlag
PlayRegionNotLockedFlag
CutCopyAvailableFlag
WaveTracksExistFlag
NoteTracksExistFlag
NoteTracksSelectedFlag
HaveRecentFiles
LinkingDisabledFlag
NoFlagsSpecifed
Function Documentation
DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API , EVT_CAPTURE_KEY , - 1)
DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API , EVT_RELEASE_KEYBOARD , - 1)
DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API , EVT_CAPTURE_KEYBOARD , - 1)
DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API , EVT_OPEN_AUDIO_FILE , - 1)
void QuitAudacity ()
References QuitAudacity().
void QuitAudacity (bool bForce)
References AppQuiting, CloseContrastDialog(), CloseScreenshotTools(), AudacityProject::DeleteAllProjectsDeleteLock(), AudacityProject::DeleteClipboard(), ModuleManager::Dispatch(), gAudacityProjects, AudacityApp::mLogger, ODManager::Quit(), SaveWindowSize(), and wxGetApp().
void SaveWindowSize ()
References gAudacityProjects, GetDefaultWindowRect(), AudacityProject::GetNormalizedWindowState(), gPrefs, AudacityApp::SetWindowRectAlreadySaved(), and wxGetApp().
Referenced by AudacityProject::OnCloseWindow(), and QuitAudacity().
AudacityApp& wxGetApp ()
Referenced by GUIPrefs::Apply(), EffectsPrefs::Apply(), AudacityProject::BuildCleanFileName(), AudacityProject::CreateMenusAndCommands(), AudacityProject::CreateRecentFilesMenu(), EffectNoiseRemoval::EffectNoiseRemoval(), GetLanguages(), AudacityProject::GetUpdateFlags(), AudacityProject::Import(), ModuleManager::Initialize(), FFmpegLibs::InitLibs(), AudacityApp::InitTempDir(), LoadLadspaPlugins(), LoadModules(), LoadNyquistPlugins(), BatchProcessDialog::OnApplyToFiles(), DirectoriesPrefs::OnChooseTempDir(), AudacityProject::OnCloseWindow(), AudacityProject::OnExportCleanSpeechPresets(), AudacityProject::OnImportCleanSpeechPresets(), AudacityProject::OnLog(), AudacityProject::OpenFile(), QuitAudacity(), AudacityProject::RebuildMenuBar(), AudacityProject::SaveAs(), SaveWindowSize(), EffectNyquist::SetXlispPath(), AudacityProject::ShowOpenDialog(), AudioIO::StopStream(), TranslationExists(), Yield(), and AudacityProject::~AudacityProject().
Variable Documentation
bool gIsQuitting
Referenced by AudacityProject::OnCloseWindow(), AudacityApp::OnEndSession(), and AudacityApp::OnExit().