Audacity: AutoRecovery.cpp File Reference
AutoRecovery.cpp File Reference
#include "AutoRecovery.h"
#include "Audacity.h"
#include "AudacityApp.h"
#include "FileNames.h"
#include "blockfile/SimpleBlockFile.h"
#include <wx/wxprec.h>
#include <wx/filefn.h>
#include <wx/dir.h>
#include <wx/dialog.h>
#include <wx/app.h>
Classes
class AutoRecoveryDialog
The AutoRecoveryDialog prompts the user whether to recover previous Audacity projects that were closed incorrectly.
Enumerations
enum { ID_RECOVER_ALL = 10000, ID_RECOVER_NONE, ID_QUIT_AUDACITY, ID_FILE_LIST }
Functions
static bool HaveFilesToRecover ()
static bool RemoveAllAutoSaveFiles ()
static bool RecoverAllProjects (AudacityProject **pproj)
bool ShowAutoRecoveryDialogIfNeeded (AudacityProject **pproj, bool *didRecoverAnything)
Enumeration Type Documentation
anonymous enum
Enumerator:
ID_RECOVER_ALL
ID_RECOVER_NONE
ID_QUIT_AUDACITY
ID_FILE_LIST
Function Documentation
static bool HaveFilesToRecover () [static]
References FileNames::AutoSaveDir().
Referenced by ShowAutoRecoveryDialogIfNeeded().
static bool RecoverAllProjects (AudacityProject ** pproj) [static]
References FileNames::AutoSaveDir(), CreateNewAudacityProject(), AudacityProject::OnZoomFit(), and AudacityProject::OpenFile().
Referenced by ShowAutoRecoveryDialogIfNeeded().
static bool RemoveAllAutoSaveFiles () [static]
References FileNames::AutoSaveDir().
Referenced by ShowAutoRecoveryDialogIfNeeded().
bool ShowAutoRecoveryDialogIfNeeded (AudacityProject ** pproj, bool * didRecoverAnything)
References HaveFilesToRecover(), ID_RECOVER_ALL, ID_RECOVER_NONE, RecoverAllProjects(), and RemoveAllAutoSaveFiles().
Referenced by AudacityApp::OnInit().