Audacity: ExportCL.cpp File Reference
ExportCL.cpp File Reference
#include "../Audacity.h"
#include <wx/log.h>
#include <wx/process.h>
#include <wx/textctrl.h>
#include "Export.h"
#include "../Project.h"
#include "../Mix.h"
#include "../Prefs.h"
#include "../Internat.h"
#include "../float_cast.h"
Classes
class ExportCLOptions
class ExportCLProcess
struct wav_header
class ExportCL
Functions
static void Drain (wxInputStream *s, wxString *o)
ExportPlugin * New_ExportCL ()
Function Documentation
static void Drain (wxInputStream * s, wxString * o) [static]
References LAT1CTOWX.
Referenced by ExportCL::Export(), and ExportCLProcess::OnTerminate().
ExportPlugin* New_ExportCL ()
Referenced by Exporter::Exporter().