Audacity: ImportLOF.cpp File Reference
ImportLOF.cpp File Reference
#include "../Audacity.h"
#include <wx/string.h>
#include <wx/utils.h>
#include <wx/intl.h>
#include <wx/textfile.h>
#include <wx/msgdlg.h>
#include <wx/tokenzr.h>
#include "ImportLOF.h"
#include "ImportMIDI.h"
#include "../WaveTrack.h"
#include "ImportPlugin.h"
#include "Import.h"
#include "../Internat.h"
#include "../NoteTrack.h"
#include "../Project.h"
#include "../FileFormats.h"
#include "../Prefs.h"
Classes
class LOFImportPlugin
An ImportPlugin for LOF data.
class LOFImportFileHandle
An ImportFileHandle for LOF data.
Defines
#define BINARY_FILE_CHECK_BUFFER_SIZE 1024
#define DESC _("List of Files in basic text format")
Functions
void GetLOFImportPlugin (ImportPluginList *importPluginList, UnusableImportPluginList *unusableImportPluginList)
static int CountNumTracks (AudacityProject *proj)
Variables
static const wxChar * exts []
Define Documentation
#define BINARY_FILE_CHECK_BUFFER_SIZE 1024
Referenced by LOFImportPlugin::Open().
#define DESC _("List of Files in basic text format")
Function Documentation
static int CountNumTracks (AudacityProject * proj) [static]
References AudacityProject::GetTracks().
Referenced by LOFImportFileHandle::lofOpenFiles().
void GetLOFImportPlugin (ImportPluginList * importPluginList, UnusableImportPluginList * unusableImportPluginList)
Referenced by Importer::Importer().
Variable Documentation
const wxChar* exts[] [static]
Initial value:
{
   wxT("lof")
}