Audacity: InterpolateAudio.cpp File Reference
InterpolateAudio.cpp File Reference
#include <math.h>
#include <stdlib.h>
#include <wx/defs.h>
#include "InterpolateAudio.h"
#include "Matrix.h"
Functions
static int imin (int x, int y)
static int imax (int x, int y)
static void LinearInterpolateAudio (float *buffer, int len, int firstBad, int numBad)
void InterpolateAudio (float *buffer, int len, int firstBad, int numBad)
Function Documentation
static int imax (int x, int y) [inline, static]
Referenced by InterpolateAudio().
static int imin (int x, int y) [inline, static]
Referenced by InterpolateAudio().
void InterpolateAudio (float * buffer, int len, int firstBad, int numBad)
References Matrix::Cols(), imax(), imin(), InterpolateAudio(), InvertMatrix(), LinearInterpolateAudio(), MatrixConcatenateCols(), MatrixMultiply(), MatrixSubset(), Matrix::Rows(), TransposeMatrix(), VectorConcatenate(), and VectorSubset().
Referenced by InterpolateAudio(), and EffectRepair::ProcessOne().
static void LinearInterpolateAudio (float * buffer, int len, int firstBad, int numBad) [static]
Referenced by InterpolateAudio().