Audacity: PitchName.h File Reference
PitchName.h File Reference
#include <wx/defs.h>
Functions
double FreqToMIDInoteNumber (double freq)
unsigned int PitchIndex (double pitchNum)
wxChar * PitchName (double pitchNum, bool bWantFlats=false)
wxChar * PitchName_Absolute (double pitchNum, bool bWantFlats=false)
Function Documentation
double FreqToMIDInoteNumber (double freq)
Referenced by EffectChangePitch::DeduceFrequencies(), ChangePitchDialog::OnText_FromFrequency(), and FreqWindow::PlotPaint().
unsigned int PitchIndex (double pitchNum)
Referenced by EffectChangePitch::DeduceFrequencies(), ChangePitchDialog::OnText_FromFrequency(), and PitchName().
wxChar* PitchName (double pitchNum, bool bWantFlats = false)
References gPitchName, PitchIndex(), and pPitchName.
Referenced by PitchName_Absolute().
wxChar* PitchName_Absolute (double pitchNum, bool bWantFlats = false)
References gPitchName, PitchName(), and pPitchName.
Referenced by FreqWindow::PlotPaint().