Audacity: ScriptCommandRelay.h File Reference
ScriptCommandRelay.h File Reference
Contains declarations for ScriptCommandRelay.
#include "../Audacity.h"
Classes
class ScriptCommandRelay
ScriptCommandRelay is just a way to move some of the scripting-specific code out of LoadModules.
Typedefs
typedef int(* tpExecScriptServerFunc)(wxString *pIn, wxString *pOut)
typedef int(* tpRegScriptServerFunc)(tpExecScriptServerFunc pFn)
Functions
AUDACITY_DLL_API int ExecCommand (wxString *pIn, wxString *pOut)
Detailed Description
Contains declarations for ScriptCommandRelay.
Typedef Documentation
typedef int(* tpExecScriptServerFunc)(wxString *pIn, wxString *pOut)
typedef int(* tpRegScriptServerFunc)(tpExecScriptServerFunc pFn)
Function Documentation
AUDACITY_DLL_API int ExecCommand (wxString * pIn, wxString * pOut)
This is the function which actually obeys one command. Rather than applying the command directly, an event containing a reference to the command is sent to the main (GUI) thread. This is because having more than one thread access the GUI at a time causes problems with wxwidgets.
References CommandBuilder::Cleanup(), GetActiveProject(), CommandBuilder::GetCommand(), CommandBuilder::GetErrorMessage(), Response::GetMessage(), ScriptCommandRelay::PostCommand(), ScriptCommandRelay::ReceiveResponse(), AudacityProject::SafeDisplayStatusMessage(), and CommandBuilder::WasValid().
Referenced by ScriptCommandRelay::Run().