Audacity: ShuttleGui.cpp File Reference
ShuttleGui.cpp File Reference
Implements ShuttleGui, ShuttleGuiBase and InvisiblePanel.
#include "Audacity.h"
#include <wx/wx.h>
#include <wx/wxprec.h>
#include <wx/listctrl.h>
#include <wx/notebook.h>
#include <wx/treectrl.h>
#include <wx/spinctrl.h>
#include "Internat.h"
#include "Experimental.h"
#include "ShuttleGui.h"
#include "Shuttle.h"
#include "WrappedType.h"
#include "./widgets/Ruler.h"
#include "./widgets/AttachableScrollBar.h"
#include "ShuttlePrefs.h"
Classes
class InvisiblePanel
An InvisiblePanel is a panel which does not repaint its own background.
Functions
void SetIfCreated (wxChoice *&Var, wxChoice *Val)
void SetIfCreated (wxTextCtrl *&Var, wxTextCtrl *Val)
void SetIfCreated (wxStaticText *&Var, wxStaticText *Val)
wxSizer * CreateStdButtonSizer (wxWindow *parent, long buttons, wxButton *extra)
Detailed Description
Implements ShuttleGui, ShuttleGuiBase and InvisiblePanel.
Function Documentation
wxSizer* CreateStdButtonSizer (wxWindow * parent, long buttons, wxButton * extra)
References eCancelButton, eDebugButton, eDebugID, eHelpButton, eNoButton, eOkButton, ePreviewButton, ePreviewID, and eYesButton.
Referenced by ShuttleGui::AddStandardButtons(), EVT_COMMAND_RANGE(), ExportMixerDialog::ExportMixerDialog(), ImportStreamDialog::ImportStreamDialog(), LabelDialog::LabelDialog(), LadspaEffectDialog::LadspaEffectDialog(), EqualizationDialog::MakeEqualizationDialog(), NyquistInputDialog::NyquistInputDialog(), and VampEffectDialog::VampEffectDialog().
void SetIfCreated (wxStaticText *& Var, wxStaticText * Val)
void SetIfCreated (wxTextCtrl *& Var, wxTextCtrl * Val)
void SetIfCreated (wxChoice *& Var, wxChoice * Val)