Audacity: DirManager Class Reference
DirManager Class Reference
Creates and manages BlockFile objects.
#include <DirManager.h>
Public Member Functions
DirManager ()
virtual ~DirManager ()
void Ref ()
void Deref ()
bool SetProject (wxString &projPath, wxString &projName, bool create)
wxString GetProjectDataDir ()
wxString GetProjectName ()
wxLongLong GetFreeDiskSpace ()
BlockFile * NewSimpleBlockFile (samplePtr sampleData, sampleCount sampleLen, sampleFormat format, bool allowDeferredWrite=false)
BlockFile * NewAliasBlockFile (wxString aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel)
BlockFile * NewODAliasBlockFile (wxString aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel)
BlockFile * NewODDecodeBlockFile (wxString aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, int decodeType)
BlockFile * CopyBlockFile (BlockFile *b)
BlockFile * LoadBlockFile (const wxChar **attrs, sampleFormat format)
void SaveBlockFile (BlockFile *f, int depth, FILE *fp)
bool MoveToNewProjectDirectory (BlockFile *f)
bool CopyToNewProjectDirectory (BlockFile *f)
bool EnsureSafeFilename (wxFileName fName)
void Ref (BlockFile *f)
void Deref (BlockFile *f)
int GetRefCount (BlockFile *f)
void SetLoadingTarget (BlockFile **target)
void SetLoadingFormat (sampleFormat format)
void SetLoadingBlockLength (sampleCount len)
void SetMaxSamples (sampleCount max)
bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
XMLTagHandler * HandleXMLChild (const wxChar *tag)
void WriteXML (XMLWriter &xmlFile)
bool AssignFile (wxFileName &filename, wxString value, bool check)
int ProjectFSCK (bool forceerror, bool silentlycorrect, bool bIgnoreNonAUs=true)
void RemoveOrphanedBlockfiles ()
wxString GetDataFilesDir () const
void SetLocalTempDir (wxString path)
void WriteCacheToDisk ()
void FillBlockfilesCache ()
Static Public Member Functions
static void SetTempDir (wxString _temp)
static void CleanTempDir ()
static void SetDontDeleteTempFiles ()
Private Member Functions
wxString NewTrackName ()
wxFileName MakeBlockFileName ()
wxFileName MakeBlockFilePath (wxString value)
wxString NewTempBlockName ()
wxString NewBlockName ()
void BalanceInfoDel (wxString)
void BalanceInfoAdd (wxString)
void BalanceFileAdd (int)
int BalanceMidAdd (int, int)
Private Attributes
int mRef
BlockHash blockFileHash
DirHash dirTopPool
DirHash dirTopFull
DirHash dirMidPool
DirHash dirMidFull
wxString projName
wxString projPath
wxString projFull
wxString lastProject
wxArrayString aliasList
BlockFile ** mLoadingTarget
sampleFormat mLoadingFormat
sampleCount mLoadingBlockLen
sampleCount mMaxSamples
wxString mytemp
Static Private Attributes
static wxString globaltemp
static int numDirManagers = 0
static bool dontDeleteTempFiles = false
Friends
class SequenceTest
Detailed Description
Creates and manages BlockFile objects.
This class manages the files that a project uses to store most of its data. It creates new BlockFile objects, which can be used to store any type of data. BlockFiles support all of the common file operations, but they also support reference counting, so two different parts of a project can point to the same block of data.
For example, a track might contain 10 blocks of data representing its audio. If you copy the last 5 blocks and paste at the end of the file, no new blocks need to be created - we just store pointers to new ones. When part of a track is deleted, the affected blocks decrement their reference counts, and when they reach zero they are deleted. This same mechanism is also used to implement Undo.
The DirManager, besides mapping filenames to absolute paths, also hashes all of the block names used in a project, so that when reading a project from disk, multiple copies of the same block still get mapped to the same BlockFile object.
Constructor & Destructor Documentation
DirManager::DirManager ()
References dirTopPool, globaltemp, mLoadingTarget, mMaxSamples, mRef, mytemp, numDirManagers, projName, projPath, and ShowWarningDialog().
DirManager::~DirManager () [virtual]
References CleanTempDir(), mRef, and numDirManagers.
Member Function Documentation
bool DirManager::AssignFile (wxFileName & filename, wxString value, bool check)
References MakeBlockFilePath().
Referenced by SimpleBlockFile::BuildFromXML(), PCMAliasBlockFile::BuildFromXML(), ODPCMAliasBlockFile::BuildFromXML(), ODDecodeBlockFile::BuildFromXML(), CopyToNewProjectDirectory(), MakeBlockFileName(), and MoveToNewProjectDirectory().
void DirManager::BalanceFileAdd (int midkey) [private]
References dirMidFull, and dirMidPool.
Referenced by BalanceInfoAdd(), and MakeBlockFileName().
void DirManager::BalanceInfoAdd (wxString file) [private]
References BalanceFileAdd(), BalanceMidAdd(), and hexchar_to_int().
Referenced by HandleXMLTag().
void DirManager::BalanceInfoDel (wxString file) [private]
References dirMidFull, dirMidPool, dirTopFull, dirTopPool, hexchar_to_int(), mytemp, and projFull.
Referenced by Deref().
int DirManager::BalanceMidAdd (int topnum, int midkey) [private]
References dirMidFull, dirMidPool, dirTopFull, and dirTopPool.
Referenced by BalanceInfoAdd(), and MakeBlockFileName().
void DirManager::CleanTempDir () [static]
References dontDeleteTempFiles, globaltemp, rm_dash_rf_enumerate(), and rm_dash_rf_execute().
Referenced by ~DirManager().
BlockFile * DirManager::CopyBlockFile (BlockFile * b)
References aliasList, blockFileHash, BlockFile::Copy(), BlockFile::GetFileName(), BlockFile::IsLocked(), BlockFile::IsSummaryAvailable(), MakeBlockFileName(), and BlockFile::Ref().
Referenced by Sequence::AppendBlock(), and Sequence::Paste().
bool DirManager::CopyToNewProjectDirectory (BlockFile * f)
References AssignFile(), BlockFile::GetFileName(), BlockFile::IsSummaryAvailable(), BlockFile::IsSummaryBeingComputed(), and BlockFile::SetFileName().
Referenced by SetProject().
void DirManager::Deref (BlockFile * f)
References BalanceInfoDel(), blockFileHash, BlockFile::Deref(), and BlockFile::GetFileName().
void DirManager::Deref ()
References mRef.
Referenced by Sequence::Append(), Sequence::ConvertToSampleFormat(), Sequence::CopyWrite(), Sequence::Delete(), Track::Init(), AudacityProject::OnCloseWindow(), BenchmarkDialog::OnRun(), Sequence::Paste(), RemoveDependencies(), ReplaceBlockFiles(), Sequence::Set(), Sequence::~Sequence(), and Track::~Track().
bool DirManager::EnsureSafeFilename (wxFileName fName)
References aliasList, blockFileHash, AliasBlockFile::ChangeAliasedFile(), ODDecodeBlockFile::ChangeAudioFile(), AliasBlockFile::GetAliasedFile(), ODDecodeBlockFile::GetEncodedAudioFilename(), BlockFile::GetFileName(), BlockFile::IsAlias(), BlockFile::IsDataAvailable(), ODDecodeBlockFile::LockRead(), BlockFile::LockRead(), ODDecodeBlockFile::UnlockRead(), and BlockFile::UnlockRead().
Referenced by Exporter::CheckFilename(), and ExportMultiple::DoExport().
void DirManager::FillBlockfilesCache ()
References blockFileHash, BlockFile::FillCache(), GetFreeMemory(), BlockFile::GetNeedFillCache(), gPrefs, and ProgressDialog::Update().
Referenced by AudacityProject::Import(), and AudacityProject::OpenFile().
wxString DirManager::GetDataFilesDir () const
References mytemp, and projFull.
Referenced by MakeBlockFilePath(), and AudacityProject::WriteXML().
wxLongLong DirManager::GetFreeDiskSpace ()
References mytemp, and projPath.
Referenced by AudacityProject::OnTimer().
wxString DirManager::GetProjectDataDir ()
References projFull.
Referenced by SimpleBlockFile::BuildFromXML(), PCMAliasBlockFile::BuildFromXML(), ODPCMAliasBlockFile::BuildFromXML(), ODDecodeBlockFile::BuildFromXML(), and ImportXMLTagHandler::HandleXMLTag().
wxString DirManager::GetProjectName ()
References projName.
Referenced by AudacityProject::AddImportedTracks(), AudacityProject::Save(), and AudacityProject::WriteXML().
int DirManager::GetRefCount (BlockFile * f)
References BlockFile::mRefCount.
Referenced by Sequence::DebugPrintf().
XMLTagHandler* DirManager::HandleXMLChild (const wxChar * tag) [inline, virtual]
Implements XMLTagHandler.
bool DirManager::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements XMLTagHandler.
References BalanceInfoAdd(), blockFileHash, LegacyBlockFile::BuildFromXML(), LegacyAliasBlockFile::BuildFromXML(), ODDecodeBlockFile::BuildFromXML(), ODPCMAliasBlockFile::BuildFromXML(), PCMAliasBlockFile::BuildFromXML(), SimpleBlockFile::BuildFromXML(), SilentBlockFile::BuildFromXML(), BlockFile::GetLength(), ODManager::MarkLoadedODFlag(), mLoadingBlockLen, mLoadingFormat, mLoadingTarget, mMaxSamples, name, projFull, and Ref().
Referenced by RecordingRecoveryHandler::HandleXMLTag().
BlockFile* DirManager::LoadBlockFile (const wxChar ** attrs, sampleFormat format)
wxFileName DirManager::MakeBlockFileName () [private]
References AssignFile(), BalanceFileAdd(), BalanceMidAdd(), blockFileHash, dirMidPool, dirTopFull, and dirTopPool.
Referenced by CopyBlockFile(), NewAliasBlockFile(), NewODAliasBlockFile(), NewODDecodeBlockFile(), and NewSimpleBlockFile().
wxFileName DirManager::MakeBlockFilePath (wxString value) [private]
References GetDataFilesDir().
Referenced by AssignFile(), and ProjectFSCK().
bool DirManager::MoveToNewProjectDirectory (BlockFile * f)
References AssignFile(), BlockFile::GetFileName(), BlockFile::IsSummaryAvailable(), BlockFile::IsSummaryBeingComputed(), and BlockFile::SetFileName().
Referenced by SetProject().
BlockFile * DirManager::NewAliasBlockFile (wxString aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel)
References aliasList, blockFileHash, and MakeBlockFileName().
Referenced by Sequence::AppendAlias().
wxString DirManager::NewBlockName () [private]
BlockFile * DirManager::NewODAliasBlockFile (wxString aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel)
References aliasList, blockFileHash, and MakeBlockFileName().
Referenced by Sequence::AppendAlias().
BlockFile * DirManager::NewODDecodeBlockFile (wxString aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, int decodeType)
References aliasList, blockFileHash, and MakeBlockFileName().
Referenced by Sequence::AppendCoded().
BlockFile * DirManager::NewSimpleBlockFile (samplePtr sampleData, sampleCount sampleLen, sampleFormat format, bool allowDeferredWrite = false)
References blockFileHash, and MakeBlockFileName().
Referenced by Sequence::Append(), Sequence::Blockify(), Sequence::ConvertToSampleFormat(), Sequence::CopyWrite(), Sequence::Delete(), Sequence::Paste(), and RemoveDependencies().
wxString DirManager::NewTempBlockName () [private]
wxString DirManager::NewTrackName () [private]
int DirManager::ProjectFSCK (bool forceerror, bool silentlycorrect, bool bIgnoreNonAUs = true)
References blockFileHash, AliasBlockFile::ChangeAliasedFile(), FSCKstatus_CHANGED, FSCKstatus_CLOSEREQ, BlockFile::IsAlias(), BlockFile::IsSummaryAvailable(), MakeBlockFilePath(), mytemp, projFull, BlockFile::Recover(), rm_dash_rf_enumerate_prompt(), rm_dash_rf_execute(), ShowMultiDialog(), AliasBlockFile::SilenceAliasLog(), and BlockFile::SilenceLog().
Referenced by AudacityProject::OpenFile().
void DirManager::Ref (BlockFile * f)
References BlockFile::Ref().
void DirManager::Ref ()
References mRef.
Referenced by HandleXMLTag(), Track::Init(), ReplaceBlockFiles(), Sequence::Sequence(), and Track::Track().
void DirManager::RemoveOrphanedBlockfiles ()
References blockFileHash, mytemp, projFull, and rm_dash_rf_enumerate_prompt().
Referenced by AudacityProject::Save().
void DirManager::SaveBlockFile (BlockFile * f, int depth, FILE * fp)
static void DirManager::SetDontDeleteTempFiles () [inline, static]
References dontDeleteTempFiles.
Referenced by AudacityApp::OnInit().
void DirManager::SetLoadingBlockLength (sampleCount len) [inline]
References mLoadingBlockLen.
Referenced by Sequence::HandleXMLTag().
void DirManager::SetLoadingFormat (sampleFormat format) [inline]
References mLoadingFormat.
Referenced by Sequence::HandleXMLChild(), and RecordingRecoveryHandler::HandleXMLTag().
void DirManager::SetLoadingTarget (BlockFile ** target) [inline]
References mLoadingTarget.
Referenced by Sequence::HandleXMLTag(), and RecordingRecoveryHandler::HandleXMLTag().
void DirManager::SetLocalTempDir (wxString path)
References mytemp.
Referenced by AudacityProject::HandleXMLTag().
void DirManager::SetMaxSamples (sampleCount max) [inline]
References mMaxSamples.
Referenced by Sequence::HandleXMLTag().
bool DirManager::SetProject (wxString & projPath, wxString & projName, bool create)
References blockFileHash, CopyToNewProjectDirectory(), BlockFile::IsLocked(), MoveToNewProjectDirectory(), mytemp, OSFILENAME, projFull, rm_dash_rf_enumerate(), rm_dash_rf_execute(), and ProgressDialog::Update().
Referenced by AudacityProject::HandleXMLTag(), and AudacityProject::Save().
static void DirManager::SetTempDir (wxString _temp) [inline, static]
References globaltemp.
Referenced by AudacityApp::InitTempDir().
void DirManager::WriteCacheToDisk ()
References blockFileHash, BlockFile::GetNeedWriteCacheToDisk(), ProgressDialog::Update(), and BlockFile::WriteCacheToDisk().
Referenced by AudacityProject::OnAudioIOStopRecording().
void DirManager::WriteXML (XMLWriter & xmlFile) [inline]
Friends And Related Function Documentation
friend class SequenceTest [friend]
Member Data Documentation
wxArrayString DirManager::aliasList [private]
Referenced by CopyBlockFile(), EnsureSafeFilename(), NewAliasBlockFile(), NewODAliasBlockFile(), and NewODDecodeBlockFile().
BlockHash DirManager::blockFileHash [private]
Referenced by CopyBlockFile(), Deref(), EnsureSafeFilename(), FillBlockfilesCache(), HandleXMLTag(), MakeBlockFileName(), NewAliasBlockFile(), NewODAliasBlockFile(), NewODDecodeBlockFile(), NewSimpleBlockFile(), ProjectFSCK(), RemoveOrphanedBlockfiles(), SetProject(), and WriteCacheToDisk().
DirHash DirManager::dirMidFull [private]
Referenced by BalanceFileAdd(), BalanceInfoDel(), and BalanceMidAdd().
DirHash DirManager::dirMidPool [private]
Referenced by BalanceFileAdd(), BalanceInfoDel(), BalanceMidAdd(), and MakeBlockFileName().
DirHash DirManager::dirTopFull [private]
Referenced by BalanceInfoDel(), BalanceMidAdd(), and MakeBlockFileName().
DirHash DirManager::dirTopPool [private]
Referenced by BalanceInfoDel(), BalanceMidAdd(), DirManager(), and MakeBlockFileName().
bool DirManager::dontDeleteTempFiles = false [static, private]
Referenced by CleanTempDir(), and SetDontDeleteTempFiles().
wxString DirManager::globaltemp [static, private]
Referenced by CleanTempDir(), DirManager(), and SetTempDir().
wxString DirManager::lastProject [private]
sampleCount DirManager::mLoadingBlockLen [private]
Referenced by HandleXMLTag(), and SetLoadingBlockLength().
sampleFormat DirManager::mLoadingFormat [private]
Referenced by HandleXMLTag(), and SetLoadingFormat().
BlockFile** DirManager::mLoadingTarget [private]
Referenced by DirManager(), HandleXMLTag(), and SetLoadingTarget().
sampleCount DirManager::mMaxSamples [private]
Referenced by DirManager(), HandleXMLTag(), and SetMaxSamples().
int DirManager::mRef [private]
Referenced by Deref(), DirManager(), Ref(), and ~DirManager().
wxString DirManager::mytemp [private]
Referenced by BalanceInfoDel(), DirManager(), GetDataFilesDir(), GetFreeDiskSpace(), ProjectFSCK(), RemoveOrphanedBlockfiles(), SetLocalTempDir(), and SetProject().
int DirManager::numDirManagers = 0 [static, private]
Referenced by DirManager(), and ~DirManager().
wxString DirManager::projFull [private]
Referenced by BalanceInfoDel(), GetDataFilesDir(), GetProjectDataDir(), HandleXMLTag(), ProjectFSCK(), RemoveOrphanedBlockfiles(), and SetProject().
wxString DirManager::projName [private]
Referenced by DirManager(), and GetProjectName().
wxString DirManager::projPath [private]
Referenced by DirManager(), and GetFreeDiskSpace().
The documentation for this class was generated from the following files:
DirManager.h
DirManager.cpp