Audacity: QualityPrefs Class Reference
QualityPrefs Class Reference
A PrefsPanel used for setting audio quality.
#include <QualityPrefs.h>
Public Member Functions
QualityPrefs (wxWindow *parent)
virtual ~QualityPrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
void GetNamesAndLabels ()
void OnSampleRateChoice (wxCommandEvent &e)
DECLARE_EVENT_TABLE ()
Private Attributes
wxArrayString mDitherNames
wxArrayInt mDitherLabels
wxArrayString mSampleRateNames
wxArrayInt mSampleRateLabels
wxArrayString mSampleFormatNames
wxArrayInt mSampleFormatLabels
wxArrayString mConverterNames
wxArrayInt mConverterLabels
wxChoice * mSampleRates
wxTextCtrl * mOtherSampleRate
int mOtherSampleRateValue
Detailed Description
A PrefsPanel used for setting audio quality.
Constructor & Destructor Documentation
QualityPrefs::QualityPrefs (wxWindow * parent)
QualityPrefs::~QualityPrefs () [virtual]
Member Function Documentation
bool QualityPrefs::Apply () [virtual]
Implements PrefsPanel.
References eIsSavingToPrefs, gPrefs, InitDitherers(), mOtherSampleRate, mOtherSampleRateValue, and PopulateOrExchange().
QualityPrefs::DECLARE_EVENT_TABLE () [private]
void QualityPrefs::GetNamesAndLabels () [private]
Gets the lists of names and lists of labels which are used in the choice controls. The names are what the user sees in the wxChoice. The corresponding labels are what gets stored.
References floatSample, Resample::GetMethodName(), Resample::GetNumMethods(), int16Sample, int24Sample, mConverterLabels, mConverterNames, mDitherLabels, mDitherNames, mSampleFormatLabels, mSampleFormatNames, mSampleRateLabels, mSampleRateNames, Dither::none, AudioIO::NumStandardRates, Dither::rectangle, Dither::shaped, AudioIO::StandardRates, and Dither::triangle.
Referenced by Populate().
void QualityPrefs::OnSampleRateChoice (wxCommandEvent & e) [private]
Enables or disables the Edit box depending on whether we selected 'Other...' or not.
References mOtherSampleRate, and mSampleRates.
Referenced by Populate().
void QualityPrefs::Populate () [private]
References eIsCreatingFromPrefs, GetNamesAndLabels(), gPrefs, mOtherSampleRateValue, OnSampleRateChoice(), and PopulateOrExchange().
void QualityPrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddPrompt(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), floatSample, Resample::GetBestMethodDefault(), Resample::GetBestMethodKey(), Resample::GetFastMethodDefault(), Resample::GetFastMethodKey(), AudioIO::GetOptimalSupportedSampleRate(), ShuttleGui::Id(), ID_SAMPLE_RATE_CHOICE, mConverterLabels, mConverterNames, mDitherLabels, mDitherNames, mOtherSampleRate, mOtherSampleRateValue, mSampleFormatLabels, mSampleFormatNames, mSampleRateLabels, mSampleRateNames, mSampleRates, Dither::none, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetNoMatchSelector(), ShuttleGui::SetSizeHints(), ShuttleGuiBase::SetStretchyCol(), Dither::shaped, ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::TieChoice(), and ShuttleGuiBase::TieTextBox().
Referenced by Apply(), and Populate().
Member Data Documentation
wxArrayInt QualityPrefs::mConverterLabels [private]
Referenced by GetNamesAndLabels(), and PopulateOrExchange().
wxArrayString QualityPrefs::mConverterNames [private]
Referenced by GetNamesAndLabels(), and PopulateOrExchange().
wxArrayInt QualityPrefs::mDitherLabels [private]
Referenced by GetNamesAndLabels(), and PopulateOrExchange().
wxArrayString QualityPrefs::mDitherNames [private]
Referenced by GetNamesAndLabels(), and PopulateOrExchange().
wxTextCtrl* QualityPrefs::mOtherSampleRate [private]
Referenced by Apply(), OnSampleRateChoice(), and PopulateOrExchange().
int QualityPrefs::mOtherSampleRateValue [private]
Referenced by Apply(), Populate(), and PopulateOrExchange().
wxArrayInt QualityPrefs::mSampleFormatLabels [private]
Referenced by GetNamesAndLabels(), and PopulateOrExchange().
wxArrayString QualityPrefs::mSampleFormatNames [private]
Referenced by GetNamesAndLabels(), and PopulateOrExchange().
wxArrayInt QualityPrefs::mSampleRateLabels [private]
Referenced by GetNamesAndLabels(), and PopulateOrExchange().
wxArrayString QualityPrefs::mSampleRateNames [private]
Referenced by GetNamesAndLabels(), and PopulateOrExchange().
wxChoice* QualityPrefs::mSampleRates [private]
Referenced by OnSampleRateChoice(), and PopulateOrExchange().
The documentation for this class was generated from the following files:
QualityPrefs.h
QualityPrefs.cpp