Audacity: BenchmarkDialog Class Reference
BenchmarkDialog Class Reference
BenchmarkDialog is used for measuring performance and accuracy of the BlockFile system.
Public Member Functions
BenchmarkDialog (wxWindow *parent)
void MakeBenchmarkDialog ()
Private Member Functions
void OnRun (wxCommandEvent &event)
void OnSave (wxCommandEvent &event)
void OnClear (wxCommandEvent &event)
void OnClose (wxCommandEvent &event)
void Printf (const wxChar *format,...)
void HoldPrint (bool hold)
void FlushPrint ()
Private Attributes
bool mHoldPrint
wxString mToPrint
wxString mBlockSizeStr
wxString mDataSizeStr
wxString mNumEditsStr
wxString mRandSeedStr
bool mBlockDetail
bool mEditDetail
wxTextCtrl * mText
Detailed Description
BenchmarkDialog is used for measuring performance and accuracy of the BlockFile system.
Constructor & Destructor Documentation
BenchmarkDialog::BenchmarkDialog (wxWindow * parent)
Member Function Documentation
void BenchmarkDialog::FlushPrint () [private]
References mText, and mToPrint.
Referenced by HoldPrint(), OnRun(), and Printf().
void BenchmarkDialog::HoldPrint (bool hold) [private]
References FlushPrint(), and mHoldPrint.
Referenced by OnRun().
void BenchmarkDialog::MakeBenchmarkDialog ()
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddCheckBox(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTextWindow(), BlockSizeID, BSaveID, ClearID, DataSizeID, eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndVerticalLay(), ShuttleGui::Id(), mBlockDetail, mBlockSizeStr, mDataSizeStr, mEditDetail, mNumEditsStr, mRandSeedStr, mText, NumEditsID, RandSeedID, RunID, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartVerticalLay(), and StaticTextID.
void BenchmarkDialog::OnClear (wxCommandEvent & event) [private]
References mText.
void BenchmarkDialog::OnClose (wxCommandEvent & event) [private]
void BenchmarkDialog::OnRun (wxCommandEvent & event) [private]
References WaveTrack::Append(), WaveTrack::Cut(), Sequence::DebugPrintf(), DirManager::Deref(), WaveTrack::Flush(), FlushPrint(), WaveTrack::Get(), WaveTrack::GetClipByIndex(), WaveTrack::GetEndTime(), Sequence::GetMaxDiskBlockSize(), Sequence::GetNumSamples(), WaveClip::GetSequence(), gPrefs, HoldPrint(), int16Sample, mBlockDetail, mBlockSizeStr, mDataSizeStr, mEditDetail, mNumEditsStr, mRandSeedStr, mToPrint, TrackFactory::NewWaveTrack(), WaveTrack::Paste(), Printf(), Sequence::SetMaxDiskBlockSize(), and WaveTrack::SetRate().
void BenchmarkDialog::OnSave (wxCommandEvent & event) [private]
References mText.
void BenchmarkDialog::Printf (const wxChar * format, ...) [private]
References FlushPrint(), mHoldPrint, and mToPrint.
Referenced by OnRun().
Member Data Documentation
bool BenchmarkDialog::mBlockDetail [private]
Referenced by MakeBenchmarkDialog(), and OnRun().
wxString BenchmarkDialog::mBlockSizeStr [private]
Referenced by MakeBenchmarkDialog(), and OnRun().
wxString BenchmarkDialog::mDataSizeStr [private]
Referenced by MakeBenchmarkDialog(), and OnRun().
bool BenchmarkDialog::mEditDetail [private]
Referenced by MakeBenchmarkDialog(), and OnRun().
bool BenchmarkDialog::mHoldPrint [private]
Referenced by HoldPrint(), and Printf().
wxString BenchmarkDialog::mNumEditsStr [private]
Referenced by MakeBenchmarkDialog(), and OnRun().
wxString BenchmarkDialog::mRandSeedStr [private]
Referenced by MakeBenchmarkDialog(), and OnRun().
wxTextCtrl* BenchmarkDialog::mText [private]
Referenced by FlushPrint(), MakeBenchmarkDialog(), OnClear(), and OnSave().
wxString BenchmarkDialog::mToPrint [private]
Referenced by FlushPrint(), OnRun(), and Printf().
The documentation for this class was generated from the following file:
Benchmark.cpp