Audacity: SelectionBarListener Class Reference
SelectionBarListener Class Reference
A parent class of SelectionBar, used to forward events to do with changes in the SelectionBar.
#include <SelectionBar.h>
Public Member Functions
SelectionBarListener ()
virtual ~SelectionBarListener ()
virtual void AS_SetRate (double rate)=0
virtual void AS_ModifySelection (double &start, double &end)=0
virtual bool AS_GetSnapTo ()=0
virtual void AS_SetSnapTo (bool state)=0
Detailed Description
A parent class of SelectionBar, used to forward events to do with changes in the SelectionBar.
Constructor & Destructor Documentation
SelectionBarListener::SelectionBarListener () [inline]
virtual SelectionBarListener::~SelectionBarListener () [inline, virtual]
Member Function Documentation
virtual bool SelectionBarListener::AS_GetSnapTo () [pure virtual]
Implemented in AudacityProject.
virtual void SelectionBarListener::AS_ModifySelection (double & start, double & end) [pure virtual]
Implemented in AudacityProject.
Referenced by SelectionBar::ModifySelection().
virtual void SelectionBarListener::AS_SetRate (double rate) [pure virtual]
Implemented in AudacityProject.
Referenced by SelectionBar::OnRate().
virtual void SelectionBarListener::AS_SetSnapTo (bool state) [pure virtual]
Implemented in AudacityProject.
Referenced by SelectionBar::OnSnapTo().
The documentation for this class was generated from the following file:
SelectionBar.h