Audacity: KeyConfigPrefs Class Reference
KeyConfigPrefs Class Reference
A PrefsPanel for keybindings.
#include <KeyConfigPrefs.h>
Public Member Functions
KeyConfigPrefs (wxWindow *parent)
~KeyConfigPrefs ()
virtual bool Apply ()
virtual void Cancel ()
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
void CreateList ()
void RepopulateBindingsList ()
void OnDefaults (wxCommandEvent &e)
void OnLoad (wxCommandEvent &e)
void OnSave (wxCommandEvent &e)
void OnSet (wxCommandEvent &e)
void OnClear (wxCommandEvent &e)
void OnCategory (wxCommandEvent &e)
void OnItemSelected (wxListEvent &e)
void OnKeyDown (wxListEvent &e)
void OnCaptureKeyDown (wxKeyEvent &e)
void OnCaptureChar (wxKeyEvent &e)
DECLARE_EVENT_TABLE ()
Private Attributes
wxChoice * mCat
wxTextCtrl * mKey
wxListCtrl * mList
CommandManager * mManager
size_t mCommandSelected
wxArrayString mCats
wxArrayString mNames
wxArrayString mKeys
Detailed Description
A PrefsPanel for keybindings.
The code for displaying keybindings is similar to code in MousePrefs. It would be nice to create a new 'Bindings' class which both KeyConfigPrefs and MousePrefs use.
Constructor & Destructor Documentation
KeyConfigPrefs::KeyConfigPrefs (wxWindow * parent)
KeyConfigPrefs::~KeyConfigPrefs ()
References mKey, OnCaptureChar(), and OnCaptureKeyDown().
Member Function Documentation
bool KeyConfigPrefs::Apply () [virtual]
Implements PrefsPanel.
References CommandManager::GetDefaultKeyFromName(), CommandManager::GetKeyFromName(), gPrefs, KeyStringNormalize(), mManager, mNames, and name.
void KeyConfigPrefs::Cancel () [virtual]
Reimplemented from PrefsPanel.
References mKeys, mManager, mNames, and CommandManager::SetKeyFromName().
void KeyConfigPrefs::CreateList () [private]
Sets up mList with the right number of columns, titles, fills the contents and sets column widths.
References CommandColumn, KeyComboColumn, mList, and RepopulateBindingsList().
Referenced by Populate().
KeyConfigPrefs::DECLARE_EVENT_TABLE () [private]
void KeyConfigPrefs::OnCaptureChar (wxKeyEvent & e) [private]
Referenced by PopulateOrExchange(), and ~KeyConfigPrefs().
void KeyConfigPrefs::OnCaptureKeyDown (wxKeyEvent & e) [private]
References KeyEventToKeyString(), and KeyStringDisplay().
Referenced by PopulateOrExchange(), and ~KeyConfigPrefs().
void KeyConfigPrefs::OnCategory (wxCommandEvent & e) [private]
References RepopulateBindingsList().
void KeyConfigPrefs::OnClear (wxCommandEvent & e) [private]
References KeyComboColumn, mCommandSelected, mKey, mList, mManager, mNames, and CommandManager::SetKeyFromName().
void KeyConfigPrefs::OnDefaults (wxCommandEvent & e) [private]
References CommandManager::GetDefaultKeyFromName(), mManager, mNames, RepopulateBindingsList(), and CommandManager::SetKeyFromName().
void KeyConfigPrefs::OnItemSelected (wxListEvent & e) [private]
References KeyComboColumn, mCommandSelected, mKey, mList, and mNames.
void KeyConfigPrefs::OnKeyDown (wxListEvent & e) [private]
References CommandColumn, and mList.
void KeyConfigPrefs::OnLoad (wxCommandEvent & e) [private]
References XMLFileReader::GetErrorStr(), gPrefs, mManager, XMLFileReader::Parse(), and RepopulateBindingsList().
void KeyConfigPrefs::OnSave (wxCommandEvent & e) [private]
References XMLFileWriter::Close(), gPrefs, mManager, XMLFileWriter::Open(), and CommandManager::WriteXML().
void KeyConfigPrefs::OnSet (wxCommandEvent & e) [private]
References CommandColumn, KeyComboColumn, mCommandSelected, mKey, mList, mManager, mNames, and CommandManager::SetKeyFromName().
void KeyConfigPrefs::Populate () [private]
References ShuttleGuiBase::AddTitle(), CreateList(), eIsCreatingFromPrefs, ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), GetActiveProject(), CommandManager::GetCategories(), AudacityProject::GetCommandManager(), mCats, mCommandSelected, mManager, PopulateOrExchange(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::StartVerticalLay().
void KeyConfigPrefs::PopulateOrExchange (ShuttleGui & S) [private]
Normally in classes derived from PrefsPanel this function is used both to populate the panel and to exchange data with it. With KeyConfigPrefs all the exchanges are handled specially, so this is only used in populating the panel.
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddChoice(), ShuttleGuiBase::AddFixedText(), ShuttleGuiBase::AddListControlReportMode(), ShuttleGuiBase::AddWindow(), AssignDefaultsButtonID, CategoryID, ClearButtonID, CommandsListID, CurrentComboID, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndThreeColumn(), ShuttleGui::Id(), LoadButtonID, mCat, mCats, mKey, mList, OnCaptureChar(), OnCaptureKeyDown(), SaveButtonID, ShuttleGuiBase::SetBorder(), SetButtonID, ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::StartThreeColumn().
Referenced by Populate().
void KeyConfigPrefs::RepopulateBindingsList () [private]
References CommandManager::GetAllCommandNames(), CommandManager::GetCategoryFromName(), CommandManager::GetKeyFromName(), CommandManager::GetPrefixedLabelFromName(), KeyComboColumn, KeyStringDisplay(), label, mCat, mKeys, mList, mManager, mNames, and name.
Referenced by CreateList(), OnCategory(), OnDefaults(), and OnLoad().
Member Data Documentation
wxChoice* KeyConfigPrefs::mCat [private]
Referenced by PopulateOrExchange(), and RepopulateBindingsList().
wxArrayString KeyConfigPrefs::mCats [private]
Referenced by Populate(), and PopulateOrExchange().
size_t KeyConfigPrefs::mCommandSelected [private]
Referenced by OnClear(), OnItemSelected(), OnSet(), and Populate().
wxTextCtrl* KeyConfigPrefs::mKey [private]
Referenced by OnClear(), OnItemSelected(), OnSet(), PopulateOrExchange(), and ~KeyConfigPrefs().
wxArrayString KeyConfigPrefs::mKeys [private]
Referenced by Cancel(), and RepopulateBindingsList().
wxListCtrl* KeyConfigPrefs::mList [private]
Referenced by CreateList(), OnClear(), OnItemSelected(), OnKeyDown(), OnSet(), PopulateOrExchange(), and RepopulateBindingsList().
CommandManager* KeyConfigPrefs::mManager [private]
Referenced by Apply(), Cancel(), OnClear(), OnDefaults(), OnLoad(), OnSave(), OnSet(), Populate(), and RepopulateBindingsList().
wxArrayString KeyConfigPrefs::mNames [private]
Referenced by Apply(), Cancel(), OnClear(), OnDefaults(), OnItemSelected(), OnSet(), and RepopulateBindingsList().
The documentation for this class was generated from the following files:
KeyConfigPrefs.h
KeyConfigPrefs.cpp