Audacity: ODFileDecoder Class Reference
ODFileDecoder Class Reference
class to decode a particular file (one per file). Saves info such as filename and length (after the header is read.)
#include <ODDecodeTask.h>
Public Member Functions
ODFileDecoder (const wxString &fName)
This should handle unicode converted to UTF-8 on mac/linux, but OD TODO:check on windows.
virtual ~ODFileDecoder ()
virtual bool ReadHeader ()=0
virtual bool Init ()
virtual void Decode (samplePtr &data, sampleFormat &format, sampleCount start, sampleCount len, unsigned int channel)=0
wxString GetFileName ()
bool IsInitialized ()
Protected Member Functions
void MarkInitialized ()
Derived classes should call this after they have parsed the header.
Protected Attributes
bool mInited
ODLock mInitedLock
wxString mFName
unsigned int mSampleRate
unsigned int mNumSamples
unsigned int mNumChannels
Detailed Description
class to decode a particular file (one per file). Saves info such as filename and length (after the header is read.)
Constructor & Destructor Documentation
ODFileDecoder::ODFileDecoder (const wxString & fName)
This should handle unicode converted to UTF-8 on mac/linux, but OD TODO:check on windows.
References mFName, and mInited.
ODFileDecoder::~ODFileDecoder () [virtual]
Member Function Documentation
virtual void ODFileDecoder::Decode (samplePtr & data, sampleFormat & format, sampleCount start, sampleCount len, unsigned int channel) [pure virtual]
Decodes the samples for this blockfile from the real file into a float buffer. This is file specific, so subclasses must implement this only. the buffer should be created by the ODFileDecoder implementing this method. It should set the format parameter so that the client code can deal with it. This class should call ReadHeader() first, so it knows the length, and can prepare the file object if it needs to.
Implemented in ODFlacDecoder.
Referenced by ODDecodeBlockFile::WriteODDecodeBlockFile().
wxString ODFileDecoder::GetFileName () [inline]
References mFName.
virtual bool ODFileDecoder::Init () [inline, virtual]
References ReadHeader().
Referenced by ODDecodeTask::DoSomeInternal().
bool ODFileDecoder::IsInitialized ()
References mInited, and mInitedLock.
Referenced by ODDecodeTask::DoSomeInternal().
void ODFileDecoder::MarkInitialized () [protected]
Derived classes should call this after they have parsed the header.
References mInited, and mInitedLock.
Referenced by ODFlacDecoder::ReadHeader().
virtual bool ODFileDecoder::ReadHeader () [pure virtual]
Read header. Subclasses must override. Probably should save the info somewhere. Ideally called once per decoding of a file. This complicates the task because
Implemented in ODFlacDecoder.
Referenced by Init().
Member Data Documentation
wxString ODFileDecoder::mFName [protected]
Referenced by GetFileName(), ODFileDecoder(), and ODFlacDecoder::ReadHeader().
bool ODFileDecoder::mInited [protected]
Referenced by IsInitialized(), MarkInitialized(), and ODFileDecoder().
ODLock ODFileDecoder::mInitedLock [protected]
Referenced by IsInitialized(), and MarkInitialized().
unsigned int ODFileDecoder::mNumChannels [protected]
Reimplemented in ODFlacDecoder.
unsigned int ODFileDecoder::mNumSamples [protected]
Reimplemented in ODFlacDecoder.
unsigned int ODFileDecoder::mSampleRate [protected]
Reimplemented in ODFlacDecoder.
The documentation for this class was generated from the following files:
ODDecodeTask.h
ODDecodeTask.cpp