Audacity: AutoRecoveryDialog Class Reference
AutoRecoveryDialog Class Reference
The AutoRecoveryDialog prompts the user whether to recover previous Audacity projects that were closed incorrectly.
Public Member Functions
AutoRecoveryDialog (wxWindow *parent)
Private Member Functions
void PopulateList ()
void PopulateOrExchange (ShuttleGui &S)
void OnQuitAudacity (wxCommandEvent &evt)
void OnRecoverNone (wxCommandEvent &evt)
void OnRecoverAll (wxCommandEvent &evt)
Private Attributes
wxListCtrl * mFileList
Detailed Description
The AutoRecoveryDialog prompts the user whether to recover previous Audacity projects that were closed incorrectly.
Constructor & Destructor Documentation
AutoRecoveryDialog::AutoRecoveryDialog (wxWindow * parent)
References eIsCreating, and PopulateOrExchange().
Member Function Documentation
void AutoRecoveryDialog::OnQuitAudacity (wxCommandEvent & evt) [private]
References ID_QUIT_AUDACITY.
void AutoRecoveryDialog::OnRecoverAll (wxCommandEvent & evt) [private]
References ID_RECOVER_ALL.
void AutoRecoveryDialog::OnRecoverNone (wxCommandEvent & evt) [private]
References ID_RECOVER_NONE.
void AutoRecoveryDialog::PopulateList () [private]
References FileNames::AutoSaveDir(), and mFileList.
void AutoRecoveryDialog::PopulateOrExchange (ShuttleGui & S) [private]
References ID_FILE_LIST.
Referenced by AutoRecoveryDialog().
Member Data Documentation
wxListCtrl* AutoRecoveryDialog::mFileList [private]
Referenced by PopulateList().
The documentation for this class was generated from the following file:
AutoRecovery.cpp