Audacity: TrackGroupIterator Class Reference
TrackGroupIterator Class Reference
#include <Track.h>
Public Member Functions
TrackGroupIterator (TrackList *val)
virtual ~TrackGroupIterator ()
Track * First (Track *member)
Track * Next (bool skiplinked=false)
Track * Prev (bool skiplinked=false)
Track * Last (bool skiplinked=false)
Private Attributes
bool mInLabelSection
Constructor & Destructor Documentation
TrackGroupIterator::TrackGroupIterator (TrackList * val)
virtual TrackGroupIterator::~TrackGroupIterator () [inline, virtual]
Member Function Documentation
Track * TrackGroupIterator::First (Track * member)
References TrackListIterator::cur, Track::GetKind(), Track::GetNode(), TrackList::GetPrev(), TrackListIterator::l, Track::Label, mInLabelSection, and Track::Wave.
Referenced by Track::IsSynchroSelected(), EffectNyquist::Process(), EffectNyquist::ProcessOne(), TrackPanel::SelectTrackLength(), and TrackPanel::StartSlide().
Track * TrackGroupIterator::Last (bool skiplinked = false) [virtual]
Reimplemented from TrackListIterator.
References TrackListIterator::cur, Track::GetKind(), TrackList::GetNext(), TrackListIterator::l, Track::Label, mInLabelSection, Next(), TrackListNode::t, and Track::Wave.
Track * TrackGroupIterator::Next (bool skiplinked = false) [virtual]
Reimplemented from TrackListIterator.
References TrackListIterator::cur, Track::GetKind(), Track::Label, mInLabelSection, and Track::Wave.
Referenced by Track::IsSynchroSelected(), Last(), EffectNyquist::ProcessOne(), TrackPanel::SelectTrackLength(), and TrackPanel::StartSlide().
Track * TrackGroupIterator::Prev (bool skiplinked = false) [virtual]
Reimplemented from TrackListIterator.
References TrackListIterator::cur, Track::GetKind(), Track::Label, mInLabelSection, and Track::Wave.
Member Data Documentation
bool TrackGroupIterator::mInLabelSection [private]
Referenced by First(), Last(), Next(), and Prev().
The documentation for this class was generated from the following files:
Track.h
Track.cpp