Audacity: ToolsToolBar Class Reference
ToolsToolBar Class Reference
A kind of ToolBar with Tools on it.
#include <ToolsToolBar.h>
Public Member Functions
ToolsToolBar ()
virtual ~ToolsToolBar ()
void Create (wxWindow *parent)
void UpdatePrefs ()
void OnTool (wxCommandEvent &evt)
void SetCurrentTool (int tool, bool show)
int GetCurrentTool ()
bool IsDown (int tool)
int GetDownTool ()
const wxChar * GetMessageForTool (int ToolNumber)
void Populate ()
virtual void Repaint (wxDC *dc)
virtual void EnableDisableButtons ()
DECLARE_CLASS (ToolsToolBar)
DECLARE_EVENT_TABLE ()
Private Member Functions
void RegenerateToolsTooltips ()
wxImage * MakeToolImage (wxImage *tool, wxImage *mask, int style)
AButton * MakeTool (teBmps eTool, int id, const wxChar *label)
Private Attributes
AButton * mTool [numTools]
wxGridSizer * mToolSizer
int mCurrentTool
Detailed Description
A kind of ToolBar with Tools on it.
This class, which is a child of Toolbar, creates the window containing the tool selection (ibeam, envelope, move, zoom), the rewind/play/stop/record/ff buttons, and the volume control. The window can be embedded within a normal project window, or within a ToolbarFrame that is managed by a global ToolBarStub called gToolsToolBarStub.
All of the controls in this window were custom-written for Audacity - they are not native controls on any platform - however, it is intended that the images could be easily replaced to allow "skinning" or just customization to match the look and feel of each platform.
See also:
Themability
Constructor & Destructor Documentation
ToolsToolBar::ToolsToolBar ()
ToolsToolBar::~ToolsToolBar () [virtual]
References mTool.
Member Function Documentation
void ToolsToolBar::Create (wxWindow * parent) [virtual]
Reimplemented from ToolBar.
References gPrefs, mCurrentTool, mTool, multiTool, AButton::PushDown(), and selectTool.
ToolsToolBar::DECLARE_CLASS (ToolsToolBar)
Reimplemented from ToolBar.
ToolsToolBar::DECLARE_EVENT_TABLE ()
Reimplemented from ToolBar.
virtual void ToolsToolBar::EnableDisableButtons () [inline, virtual]
Implements ToolBar.
int ToolsToolBar::GetCurrentTool ()
Gets the currently active tool In Multi-mode this might not return the multi-tool itself since the active tool may be changed by what you hover over.
References mCurrentTool.
Referenced by TrackPanel::DetermineToolToUse(), and AudacityProject::TP_GetCurrentTool().
int ToolsToolBar::GetDownTool ()
References firstTool, IsDown(), and lastTool.
Referenced by AudacityProject::OnNextTool(), and AudacityProject::OnPrevTool().
const wxChar * ToolsToolBar::GetMessageForTool (int ToolNumber)
References MessageOfTool, and numTools.
Referenced by TrackPanel::HandleCursor().
bool ToolsToolBar::IsDown (int tool)
References AButton::IsDown(), and mTool.
Referenced by TrackPanel::DetermineToolToUse(), TrackPanel::DrawTracks(), GetDownTool(), TrackPanel::HandleCursor(), OnTool(), SetCurrentTool(), and TrackPanel::StartSlide().
AButton * ToolsToolBar::MakeTool (teBmps eTool, int id, const wxChar * label) [private]
References ThemeBase::ImageSize(), ToolBar::MakeButton(), mToolSizer, and theTheme.
Referenced by Populate().
wxImage* ToolsToolBar::MakeToolImage (wxImage * tool, wxImage * mask, int style) [private]
void ToolsToolBar::OnTool (wxCommandEvent & evt)
References firstTool, gPrefs, IsDown(), mCurrentTool, mTool, multiTool, numTools, AButton::PopUp(), AButton::PushDown(), and RedrawAllProjects().
void ToolsToolBar::Populate () [virtual]
Implements ToolBar.
References ToolBar::Add(), drawTool, envelopeTool, ToolBar::MakeButtonBackgroundsSmall(), MakeTool(), mTool, mToolSizer, multiTool, RegenerateToolsTooltips(), selectTool, slideTool, and zoomTool.
void ToolsToolBar::RegenerateToolsTooltips () [private]
References drawTool, envelopeTool, mTool, multiTool, selectTool, slideTool, and zoomTool.
Referenced by Populate(), and UpdatePrefs().
virtual void ToolsToolBar::Repaint (wxDC * dc) [inline, virtual]
Implements ToolBar.
void ToolsToolBar::SetCurrentTool (int tool, bool show)
Sets the currently active tool
Parameters:
tool - The index of the tool to be used.
show - should we update the button display?
References gPrefs, IsDown(), mCurrentTool, mTool, multiTool, AButton::PopUp(), AButton::PushDown(), and RefreshCursorForAllProjects().
Referenced by TrackPanel::DetermineToolToUse(), AudacityProject::OnNextTool(), AudacityProject::OnPrevTool(), and AudacityProject::SetTool().
void ToolsToolBar::UpdatePrefs () [virtual]
Reimplemented from ToolBar.
References RegenerateToolsTooltips().
Member Data Documentation
int ToolsToolBar::mCurrentTool [private]
Referenced by Create(), GetCurrentTool(), OnTool(), and SetCurrentTool().
AButton* ToolsToolBar::mTool[numTools] [private]
Referenced by Create(), IsDown(), OnTool(), Populate(), RegenerateToolsTooltips(), SetCurrentTool(), and ~ToolsToolBar().
wxGridSizer* ToolsToolBar::mToolSizer [private]
Referenced by MakeTool(), and Populate().
The documentation for this class was generated from the following files:
ToolsToolBar.h
ToolsToolBar.cpp