Audacity: Sequence Class Reference
Sequence Class Reference
Has a sequence of samples. Compare with RingBuffer.
#include <Sequence.h>
Public Member Functions
Sequence (DirManager *projDirManager, sampleFormat format)
Sequence (const Sequence &orig, DirManager *projDirManager)
Sequence * Duplicate (DirManager *projDirManager) const
virtual ~Sequence ()
sampleCount GetNumSamples () const
bool Get (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len) const
bool Set (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len)
bool GetWaveDisplay (float *min, float *max, float *rms, int *bl, int len, sampleCount *where, double samplesPerPixel)
bool Copy (sampleCount s0, sampleCount s1, Sequence **dest)
bool Paste (sampleCount s0, const Sequence *src)
sampleCount GetIdealAppendLen ()
bool Append (samplePtr buffer, sampleFormat format, sampleCount len, XMLWriter *blockFileLog=NULL)
bool Delete (sampleCount start, sampleCount len)
bool AppendAlias (wxString fullPath, sampleCount start, sampleCount len, int channel, bool useOD)
bool AppendCoded (wxString fName, sampleCount start, sampleCount len, int channel, int decodeType)
unsigned int GetODFlags ()
gets an int with OD flags so that we can determine which ODTasks should be run on this track after save/open, etc.
void AppendBlockFile (BlockFile *blockFile)
bool SetSilence (sampleCount s0, sampleCount len)
bool InsertSilence (sampleCount s0, sampleCount len)
DirManager * GetDirManager ()
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual void HandleXMLEndTag (const wxChar *tag)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
bool GetErrorOpening ()
bool Lock ()
bool CloseLock ()
bool Unlock ()
sampleFormat GetSampleFormat () const
bool SetSampleFormat (sampleFormat format)
bool ConvertToSampleFormat (sampleFormat format)
bool GetMinMax (sampleCount start, sampleCount len, float *min, float *max) const
bool GetRMS (sampleCount start, sampleCount len, float *outRMS) const
sampleCount GetBestBlockSize (sampleCount start) const
sampleCount GetMaxBlockSize () const
sampleCount GetIdealBlockSize () const
BlockArray * GetBlockArray ()
void LockDeleteUpdateMutex ()
void UnlockDeleteUpdateMutex ()
bool ConsistencyCheck (const wxChar *whereStr)
void Debug ()
void DebugPrintf (wxString *dest)
Static Public Member Functions
static void SetMaxDiskBlockSize (int bytes)
static int GetMaxDiskBlockSize ()
Private Member Functions
void CalcSummaryInfo ()
int FindBlock (sampleCount pos) const
int FindBlock (sampleCount pos, sampleCount lo, sampleCount guess, sampleCount hi) const
bool AppendBlock (SeqBlock *b)
bool Read (samplePtr buffer, sampleFormat format, SeqBlock *b, sampleCount start, sampleCount len) const
bool FirstWrite (samplePtr buffer, SeqBlock *b, sampleCount len)
bool CopyWrite (samplePtr buffer, SeqBlock *b, sampleCount start, sampleCount len)
void * GetSummary (samplePtr buffer, sampleCount len, float *min, float *max, float *rms)
BlockArray * Blockify (samplePtr buffer, sampleCount len)
Private Attributes
DirManager * mDirManager
BlockArray * mBlock
sampleFormat mSampleFormat
sampleCount mNumSamples
sampleCount mMinSamples
sampleCount mMaxSamples
bool mErrorOpening
ODLock mDeleteUpdateMutex
To block the Delete() method against the ODCalcSummaryTask::Update() method.
Static Private Attributes
static int sMaxDiskBlockSize = 1048576
Friends
class TrackArtist
Detailed Description
Has a sequence of samples. Compare with RingBuffer.
Constructor & Destructor Documentation
Sequence::Sequence (DirManager * projDirManager, sampleFormat format)
References mBlock, mDirManager, mErrorOpening, mMaxSamples, mMinSamples, mNumSamples, mSampleFormat, DirManager::Ref(), SAMPLE_SIZE, and sMaxDiskBlockSize.
Referenced by Copy(), Duplicate(), and InsertSilence().
Sequence::Sequence (const Sequence & orig, DirManager * projDirManager)
References mBlock, mDirManager, mErrorOpening, mMaxSamples, mMinSamples, mNumSamples, mSampleFormat, Paste(), and DirManager::Ref().
Sequence::~Sequence () [virtual]
References DirManager::Deref(), mBlock, and mDirManager.
Member Function Documentation
bool Sequence::Append (samplePtr buffer, sampleFormat format, sampleCount len, XMLWriter * blockFileLog = NULL)
References ConsistencyCheck(), CopySamples(), DeleteSamples(), DirManager::Deref(), SeqBlock::f, GetIdealBlockSize(), BlockFile::GetLength(), mBlock, mDirManager, mMaxSamples, mMinSamples, mNumSamples, mSampleFormat, NewSamples(), DirManager::NewSimpleBlockFile(), Read(), SAMPLE_SIZE, BlockFile::SaveXML(), and SeqBlock::start.
Referenced by WaveClip::Append(), WaveClip::Flush(), and WaveClip::Resample().
bool Sequence::AppendAlias (wxString fullPath, sampleCount start, sampleCount len, int channel, bool useOD)
References SeqBlock::f, BlockFile::GetLength(), mBlock, mDirManager, mNumSamples, DirManager::NewAliasBlockFile(), DirManager::NewODAliasBlockFile(), and SeqBlock::start.
Referenced by WaveClip::AppendAlias().
bool Sequence::AppendBlock (SeqBlock * b) [private]
Todo:
Error Could not paste! (Out of disk space?)
References DirManager::CopyBlockFile(), SeqBlock::f, BlockFile::GetLength(), mBlock, mDirManager, mNumSamples, and SeqBlock::start.
Referenced by Paste().
void Sequence::AppendBlockFile (BlockFile * blockFile)
References ConsistencyCheck(), SeqBlock::f, BlockFile::GetLength(), mBlock, mNumSamples, and SeqBlock::start.
Referenced by RecordingRecoveryHandler::HandleXMLTag().
bool Sequence::AppendCoded (wxString fName, sampleCount start, sampleCount len, int channel, int decodeType)
References SeqBlock::f, BlockFile::GetLength(), mBlock, mDirManager, mNumSamples, DirManager::NewODDecodeBlockFile(), and SeqBlock::start.
Referenced by WaveClip::AppendCoded().
BlockArray * Sequence::Blockify (samplePtr buffer, sampleCount len) [private]
References SeqBlock::f, mDirManager, mMaxSamples, mSampleFormat, DirManager::NewSimpleBlockFile(), SAMPLE_SIZE, and SeqBlock::start.
Referenced by Delete(), and Paste().
void Sequence::CalcSummaryInfo () [private]
bool Sequence::CloseLock ()
References mBlock.
Referenced by WaveClip::CloseLock().
bool Sequence::ConsistencyCheck (const wxChar * whereStr)
References Debug(), mBlock, and mNumSamples.
Referenced by Append(), AppendBlockFile(), Delete(), InsertSilence(), Paste(), and Set().
bool Sequence::ConvertToSampleFormat (sampleFormat format)
References CopySamples(), DeleteSamples(), DirManager::Deref(), SeqBlock::f, BlockFile::GetLength(), BlockFile::IsAlias(), mBlock, mDirManager, mSampleFormat, NewSamples(), DirManager::NewSimpleBlockFile(), and BlockFile::ReadData().
Referenced by WaveClip::ConvertToSampleFormat().
bool Sequence::Copy (sampleCount s0, sampleCount s1, Sequence ** dest)
References DeleteSamples(), FindBlock(), Get(), mBlock, mDirManager, mMaxSamples, mNumSamples, mSampleFormat, NewSamples(), and Sequence().
Referenced by WaveClip::CreateFromCopy().
bool Sequence::CopyWrite (samplePtr buffer, SeqBlock * b, sampleCount start, sampleCount len) [private]
References DeleteSamples(), DirManager::Deref(), SeqBlock::f, BlockFile::GetLength(), mDirManager, mMaxSamples, mSampleFormat, NewSamples(), DirManager::NewSimpleBlockFile(), Read(), and SAMPLE_SIZE.
Referenced by Set().
void Sequence::Debug ()
References DebugPrintf().
Referenced by ConsistencyCheck().
void Sequence::DebugPrintf (wxString * dest)
References DirManager::GetRefCount(), mBlock, mDirManager, and mNumSamples.
Referenced by Debug(), and BenchmarkDialog::OnRun().
bool Sequence::Delete (sampleCount start, sampleCount len)
References Blockify(), ConsistencyCheck(), DeleteSamples(), DirManager::Deref(), SeqBlock::f, FindBlock(), BlockFile::GetLength(), LockDeleteUpdateMutex(), mBlock, mDirManager, mMinSamples, mNumSamples, mSampleFormat, NewSamples(), DirManager::NewSimpleBlockFile(), Read(), SAMPLE_SIZE, SeqBlock::start, and UnlockDeleteUpdateMutex().
Sequence* Sequence::Duplicate (DirManager * projDirManager) const [inline]
References Sequence().
int Sequence::FindBlock (sampleCount pos, sampleCount lo, sampleCount guess, sampleCount hi) const [private]
References FindBlock(), and mBlock.
int Sequence::FindBlock (sampleCount pos) const [private]
References mBlock, and mNumSamples.
Referenced by Copy(), Delete(), FindBlock(), Get(), GetBestBlockSize(), GetMinMax(), GetRMS(), GetWaveDisplay(), Paste(), and Set().
bool Sequence::FirstWrite (samplePtr buffer, SeqBlock * b, sampleCount len) [private]
bool Sequence::Get (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len) const
References FindBlock(), mBlock, mNumSamples, Read(), and SAMPLE_SIZE.
Referenced by Copy(), WaveClip::GetSamples(), WaveClip::GetSpectrogram(), Paste(), and WaveClip::Resample().
sampleCount Sequence::GetBestBlockSize (sampleCount start) const
References FindBlock(), mBlock, mMaxSamples, and mMinSamples.
BlockArray* Sequence::GetBlockArray () [inline]
References mBlock.
Referenced by AudacityProject::AddImportedTracks(), and GetAllSeqBlocks().
DirManager* Sequence::GetDirManager () [inline]
References mDirManager.
Referenced by WaveClip::ClearAndAddCutLine(), WaveClip::HandleXMLChild(), WaveClip::Paste(), and WaveClip::Resample().
bool Sequence::GetErrorOpening () [inline]
References mErrorOpening.
sampleCount Sequence::GetIdealAppendLen ()
References GetMaxBlockSize(), max, and mBlock.
Referenced by WaveClip::Append().
sampleCount Sequence::GetIdealBlockSize () const
References mMaxSamples.
Referenced by Append(), WaveTrack::GetIdealBlockSize(), and InsertSilence().
sampleCount Sequence::GetMaxBlockSize () const
References mMaxSamples.
Referenced by WaveClip::Append(), WaveTrack::GetBestBlockSize(), GetIdealAppendLen(), and WaveTrack::GetMaxBlockSize().
int Sequence::GetMaxDiskBlockSize () [static]
References sMaxDiskBlockSize.
Referenced by BenchmarkDialog::OnRun().
bool Sequence::GetMinMax (sampleCount start, sampleCount len, float * min, float * max) const
References FindBlock(), max, mBlock, and min().
Referenced by WaveClip::GetMinMax().
sampleCount Sequence::GetNumSamples () const [inline]
References mNumSamples.
Referenced by WaveClip::GetEndSample(), WaveClip::GetEndTime(), WaveClip::GetSpectrogram(), WaveClip::GetWaveDisplay(), BenchmarkDialog::OnRun(), WaveClip::Resample(), WaveClip::TimeToSamplesClip(), WaveClip::UpdateEnvelopeTrackLen(), and WaveClip::WaveClip().
unsigned int Sequence::GetODFlags ()
gets an int with OD flags so that we can determine which ODTasks should be run on this track after save/open, etc.
References ODTask::eODPCMSummary, and mBlock.
Referenced by WaveTrack::GetODFlags().
bool Sequence::GetRMS (sampleCount start, sampleCount len, float * outRMS) const
References FindBlock(), and mBlock.
Referenced by WaveClip::GetRMS().
sampleFormat Sequence::GetSampleFormat () const
References mSampleFormat.
Referenced by WaveClip::Append(), WaveClip::ClearAndAddCutLine(), WaveClip::Flush(), WaveClip::GetWaveDisplay(), WaveClip::HandleXMLChild(), RecordingRecoveryHandler::HandleXMLTag(), and WaveClip::Resample().
void* Sequence::GetSummary (samplePtr buffer, sampleCount len, float * min, float * max, float * rms) [private]
bool Sequence::GetWaveDisplay (float * min, float * max, float * rms, int * bl, int len, sampleCount * where, double samplesPerPixel)
References FindBlock(), floatSample, mBlock, mMaxSamples, mNumSamples, and Read().
Referenced by WaveClip::GetWaveDisplay().
XMLTagHandler * Sequence::HandleXMLChild (const wxChar * tag) [virtual]
Implements XMLTagHandler.
References mDirManager, mSampleFormat, and DirManager::SetLoadingFormat().
void Sequence::HandleXMLEndTag (const wxChar * tag) [virtual]
Reimplemented from XMLTagHandler.
References mBlock, mErrorOpening, mMaxSamples, and mNumSamples.
bool Sequence::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements XMLTagHandler.
References SeqBlock::f, XMLValueChecker::IsGoodInt(), XMLValueChecker::IsValidSampleFormat(), mBlock, mDirManager, mErrorOpening, mMaxSamples, mNumSamples, mSampleFormat, DirManager::SetLoadingBlockLength(), DirManager::SetLoadingTarget(), DirManager::SetMaxSamples(), and SeqBlock::start.
bool Sequence::InsertSilence (sampleCount s0, sampleCount len)
References ConsistencyCheck(), SeqBlock::f, GetIdealBlockSize(), mBlock, mDirManager, mNumSamples, mSampleFormat, Paste(), Sequence(), and SeqBlock::start.
Referenced by WaveClip::InsertSilence().
bool Sequence::Lock ()
References mBlock.
Referenced by WaveClip::Lock().
void Sequence::LockDeleteUpdateMutex () [inline]
References mDeleteUpdateMutex.
Referenced by Delete(), ODDecodeTask::Update(), and ODComputeSummaryTask::Update().
bool Sequence::Paste (sampleCount s0, const Sequence * src)
References AppendBlock(), Blockify(), ConsistencyCheck(), DirManager::CopyBlockFile(), DeleteSamples(), DirManager::Deref(), SeqBlock::f, FindBlock(), Get(), BlockFile::GetLength(), mBlock, mDirManager, mMaxSamples, mMinSamples, mNumSamples, mSampleFormat, NewSamples(), DirManager::NewSimpleBlockFile(), Read(), SAMPLE_SIZE, and SeqBlock::start.
Referenced by InsertSilence(), WaveClip::Paste(), and Sequence().
bool Sequence::Read (samplePtr buffer, sampleFormat format, SeqBlock * b, sampleCount start, sampleCount len) const [private]
References ClearSamples(), SeqBlock::f, and BlockFile::ReadData().
Referenced by Append(), CopyWrite(), Delete(), Get(), GetWaveDisplay(), and Paste().
bool Sequence::Set (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len)
References ClearSamples(), ConsistencyCheck(), CopySamples(), CopyWrite(), DeleteSamples(), DirManager::Deref(), FindBlock(), mBlock, mDirManager, mMaxSamples, mNumSamples, mSampleFormat, NewSamples(), and SAMPLE_SIZE.
Referenced by WaveClip::SetSamples(), and SetSilence().
void Sequence::SetMaxDiskBlockSize (int bytes) [static]
References sMaxDiskBlockSize.
Referenced by AudacityApp::OnInit(), and BenchmarkDialog::OnRun().
bool Sequence::SetSampleFormat (sampleFormat format)
References mBlock, mNumSamples, and mSampleFormat.
bool Sequence::SetSilence (sampleCount s0, sampleCount len)
References mSampleFormat, and Set().
Referenced by WaveTrack::Silence().
bool Sequence::Unlock ()
References mBlock.
Referenced by WaveClip::Unlock().
void Sequence::UnlockDeleteUpdateMutex () [inline]
References mDeleteUpdateMutex.
Referenced by Delete(), ODDecodeTask::Update(), and ODComputeSummaryTask::Update().
void Sequence::WriteXML (XMLWriter & xmlFile) [virtual]
References XMLWriter::EndTag(), SeqBlock::f, mBlock, mMaxSamples, mNumSamples, mSampleFormat, BlockFile::SaveXML(), SeqBlock::start, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
Referenced by WaveClip::WriteXML().
Friends And Related Function Documentation
friend class TrackArtist [friend]
Member Data Documentation
BlockArray* Sequence::mBlock [private]
Referenced by Append(), AppendAlias(), AppendBlock(), AppendBlockFile(), AppendCoded(), CloseLock(), ConsistencyCheck(), ConvertToSampleFormat(), Copy(), DebugPrintf(), Delete(), FindBlock(), Get(), GetBestBlockSize(), GetBlockArray(), GetIdealAppendLen(), GetMinMax(), GetODFlags(), GetRMS(), GetWaveDisplay(), HandleXMLEndTag(), HandleXMLTag(), InsertSilence(), Lock(), Paste(), Sequence(), Set(), SetSampleFormat(), Unlock(), WriteXML(), and ~Sequence().
ODLock Sequence::mDeleteUpdateMutex [private]
To block the Delete() method against the ODCalcSummaryTask::Update() method.
Referenced by LockDeleteUpdateMutex(), and UnlockDeleteUpdateMutex().
DirManager* Sequence::mDirManager [private]
Referenced by Append(), AppendAlias(), AppendBlock(), AppendCoded(), Blockify(), ConvertToSampleFormat(), Copy(), CopyWrite(), DebugPrintf(), Delete(), GetDirManager(), HandleXMLChild(), HandleXMLTag(), InsertSilence(), Paste(), Sequence(), Set(), and ~Sequence().
bool Sequence::mErrorOpening [private]
Referenced by GetErrorOpening(), HandleXMLEndTag(), HandleXMLTag(), and Sequence().
sampleCount Sequence::mMaxSamples [private]
Referenced by Append(), Blockify(), Copy(), CopyWrite(), GetBestBlockSize(), GetIdealBlockSize(), GetMaxBlockSize(), GetWaveDisplay(), HandleXMLEndTag(), HandleXMLTag(), Paste(), Sequence(), Set(), and WriteXML().
sampleCount Sequence::mMinSamples [private]
Referenced by Append(), Delete(), GetBestBlockSize(), Paste(), and Sequence().
sampleCount Sequence::mNumSamples [private]
Referenced by Append(), AppendAlias(), AppendBlock(), AppendBlockFile(), AppendCoded(), ConsistencyCheck(), Copy(), DebugPrintf(), Delete(), FindBlock(), Get(), GetNumSamples(), GetWaveDisplay(), HandleXMLEndTag(), HandleXMLTag(), InsertSilence(), Paste(), Sequence(), Set(), SetSampleFormat(), and WriteXML().
sampleFormat Sequence::mSampleFormat [private]
Referenced by Append(), Blockify(), ConvertToSampleFormat(), Copy(), CopyWrite(), Delete(), GetSampleFormat(), HandleXMLChild(), HandleXMLTag(), InsertSilence(), Paste(), Sequence(), Set(), SetSampleFormat(), SetSilence(), and WriteXML().
int Sequence::sMaxDiskBlockSize = 1048576 [static, private]
Referenced by GetMaxDiskBlockSize(), Sequence(), and SetMaxDiskBlockSize().
The documentation for this class was generated from the following files:
Sequence.h
Sequence.cpp