Audacity: EditChainsDialog Class Reference
EditChainsDialog Class Reference
#include <BatchProcessDialog.h>
Public Member Functions
EditChainsDialog (wxWindow *parent)
Constructor.
~EditChainsDialog ()
Private Member Functions
void Populate ()
Creates the dialog and its contents.
void PopulateOrExchange (ShuttleGui &S)
Defines the dialog and does data exchange with it.
void PopulateChains ()
This clears and updates the contents of mChains.
void PopulateList ()
This clears and updates the contents of mList.
void AddItem (const wxString &command, wxString const &params)
Add one item into mList.
bool ChangeOK ()
void OnChainSelected (wxListEvent &event)
An item in the chains list has been selected.
void OnChainsBeginEdit (wxListEvent &event)
void OnChainsEndEdit (wxListEvent &event)
void OnAdd (wxCommandEvent &event)
void OnRemove (wxCommandEvent &event)
void OnRename (wxCommandEvent &event)
void OnCommandActivated (wxListEvent &event)
void OnInsert (wxCommandEvent &event)
void OnDelete (wxCommandEvent &event)
void OnUp (wxCommandEvent &event)
void OnDown (wxCommandEvent &event)
void OnDefaults (wxCommandEvent &event)
Select the empty Command chain.
void OnOK (wxCommandEvent &event)
Send changed values back to Prefs, and update Audacity.
void OnCancel (wxCommandEvent &event)
void OnKeyDown (wxKeyEvent &event)
DECLARE_EVENT_TABLE ()
Private Attributes
wxListCtrl * mChains
wxListCtrl * mList
List of chains.
wxButton * mRemove
List of commands in current command chain.
wxButton * mRename
wxButton * mDefaults
BatchCommands mBatchCommands
wxString mActiveChain
Provides list of available commands.
int mSelectedCommand
bool mChanged
Constructor & Destructor Documentation
EditChainsDialog::EditChainsDialog (wxWindow * parent)
Constructor.
References mChanged, mSelectedCommand, and Populate().
EditChainsDialog::~EditChainsDialog ()
Member Function Documentation
void EditChainsDialog::AddItem (const wxString & command, wxString const & params) [private]
Add one item into mList.
References ActionColumn, ItemNumberColumn, mList, and ParamsColumn.
Referenced by PopulateList().
bool EditChainsDialog::ChangeOK () [private]
References mActiveChain, mBatchCommands, mChanged, and BatchCommands::WriteChain().
Referenced by OnCancel(), and OnChainSelected().
EditChainsDialog::DECLARE_EVENT_TABLE () [private]
void EditChainsDialog::OnAdd (wxCommandEvent & event) [private]
References BatchCommands::AddChain(), mActiveChain, mBatchCommands, name, and PopulateChains().
void EditChainsDialog::OnCancel (wxCommandEvent & event) [private]
References ChangeOK().
void EditChainsDialog::OnChainsBeginEdit (wxListEvent & event) [private]
References BatchCommands::IsFixed(), mActiveChain, mBatchCommands, and mChains.
void EditChainsDialog::OnChainSelected (wxListEvent & event) [private]
An item in the chains list has been selected.
References ActionColumn, ChangeOK(), BatchCommands::IsFixed(), ItemNumberColumn, mActiveChain, mBatchCommands, mChains, mDefaults, mList, mRemove, mRename, PopulateList(), and BatchCommands::ReadChain().
void EditChainsDialog::OnChainsEndEdit (wxListEvent & event) [private]
References mActiveChain, mBatchCommands, PopulateChains(), and BatchCommands::RenameChain().
void EditChainsDialog::OnCommandActivated (wxListEvent & event) [private]
An item in the list has been selected. Bring up a dialog to allow its parameters to be edited.
References BatchCommands::AddToChain(), BatchCommands::DeleteFromChain(), BatchCommands::GetCommand(), BatchCommands::GetParams(), mBatchCommands, mChanged, mSelectedCommand, BatchCommandDialog::mSelectedCommand, BatchCommandDialog::mSelectedParameters, PopulateList(), and BatchCommandDialog::SetCommandAndParams().
void EditChainsDialog::OnDefaults (wxCommandEvent & event) [private]
Select the empty Command chain.
References mActiveChain, mBatchCommands, mChanged, PopulateList(), and BatchCommands::RestoreChain().
void EditChainsDialog::OnDelete (wxCommandEvent & event) [private]
References BatchCommands::DeleteFromChain(), mBatchCommands, mChanged, mList, mSelectedCommand, and PopulateList().
void EditChainsDialog::OnDown (wxCommandEvent & event) [private]
References BatchCommands::AddToChain(), BatchCommands::DeleteFromChain(), BatchCommands::GetCommand(), BatchCommands::GetParams(), mBatchCommands, mChanged, mList, mSelectedCommand, and PopulateList().
void EditChainsDialog::OnInsert (wxCommandEvent & event) [private]
References BatchCommands::AddToChain(), mBatchCommands, mChanged, mList, mSelectedCommand, BatchCommandDialog::mSelectedCommand, BatchCommandDialog::mSelectedParameters, and PopulateList().
void EditChainsDialog::OnKeyDown (wxKeyEvent & event) [private]
void EditChainsDialog::OnOK (wxCommandEvent & event) [private]
Send changed values back to Prefs, and update Audacity.
References gPrefs, mActiveChain, mBatchCommands, mChanged, and BatchCommands::WriteChain().
void EditChainsDialog::OnRemove (wxCommandEvent & event) [private]
References BatchCommands::DeleteChain(), mActiveChain, mBatchCommands, mChains, name, and PopulateChains().
void EditChainsDialog::OnRename (wxCommandEvent & event) [private]
References mChains.
void EditChainsDialog::OnUp (wxCommandEvent & event) [private]
References BatchCommands::AddToChain(), BatchCommands::DeleteFromChain(), BatchCommands::GetCommand(), BatchCommands::GetParams(), mBatchCommands, mChanged, mList, mSelectedCommand, and PopulateList().
void EditChainsDialog::Populate () [private]
Creates the dialog and its contents.
References ActionColumn, BlankColumn, eIsCreating, gPrefs, ItemNumberColumn, mActiveChain, mChains, mList, ParamsColumn, PopulateChains(), PopulateList(), and PopulateOrExchange().
Referenced by EditChainsDialog().
void EditChainsDialog::PopulateChains () [private]
This clears and updates the contents of mChains.
References BatchCommands::GetNames(), mActiveChain, mBatchCommands, mChains, and names.
Referenced by OnAdd(), OnChainsEndEdit(), OnRemove(), and Populate().
void EditChainsDialog::PopulateList () [private]
This clears and updates the contents of mList.
References ActionColumn, AddItem(), BlankColumn, BatchCommands::GetCommand(), BatchCommands::GetCount(), BatchCommands::GetParams(), ItemNumberColumn, mBatchCommands, mList, mSelectedCommand, and ParamsColumn.
Referenced by OnChainSelected(), OnCommandActivated(), OnDefaults(), OnDelete(), OnDown(), OnInsert(), OnUp(), and Populate().
void EditChainsDialog::PopulateOrExchange (ShuttleGui & S) [private]
Defines the dialog and does data exchange with it.
References ActionColumn, ShuttleGuiBase::AddButton(), AddButtonID, ShuttleGuiBase::AddListControlReportMode(), ShuttleGui::AddStandardButtons(), BlankColumn, ChainsListID, CommandsListID, DefaultsButtonID, DeleteButtonID, DownButtonID, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGui::Id(), InsertButtonID, ItemNumberColumn, mChains, mDefaults, mList, mRemove, mRename, ParamsColumn, RemoveButtonID, RenameButtonID, ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), and UpButtonID.
Referenced by Populate().
Member Data Documentation
wxString EditChainsDialog::mActiveChain [private]
Provides list of available commands.
Referenced by ChangeOK(), OnAdd(), OnChainsBeginEdit(), OnChainSelected(), OnChainsEndEdit(), OnDefaults(), OnOK(), OnRemove(), Populate(), and PopulateChains().
BatchCommands EditChainsDialog::mBatchCommands [private]
Referenced by ChangeOK(), OnAdd(), OnChainsBeginEdit(), OnChainSelected(), OnChainsEndEdit(), OnCommandActivated(), OnDefaults(), OnDelete(), OnDown(), OnInsert(), OnOK(), OnRemove(), OnUp(), PopulateChains(), and PopulateList().
wxListCtrl* EditChainsDialog::mChains [private]
Referenced by OnChainsBeginEdit(), OnChainSelected(), OnRemove(), OnRename(), Populate(), PopulateChains(), and PopulateOrExchange().
bool EditChainsDialog::mChanged [private]
Referenced by ChangeOK(), EditChainsDialog(), OnCommandActivated(), OnDefaults(), OnDelete(), OnDown(), OnInsert(), OnOK(), and OnUp().
wxButton* EditChainsDialog::mDefaults [private]
Referenced by OnChainSelected(), and PopulateOrExchange().
wxListCtrl* EditChainsDialog::mList [private]
List of chains.
Referenced by AddItem(), OnChainSelected(), OnDelete(), OnDown(), OnInsert(), OnUp(), Populate(), PopulateList(), and PopulateOrExchange().
wxButton* EditChainsDialog::mRemove [private]
List of commands in current command chain.
Referenced by OnChainSelected(), and PopulateOrExchange().
wxButton* EditChainsDialog::mRename [private]
Referenced by OnChainSelected(), and PopulateOrExchange().
int EditChainsDialog::mSelectedCommand [private]
Referenced by EditChainsDialog(), OnCommandActivated(), OnDelete(), OnDown(), OnInsert(), OnUp(), and PopulateList().
The documentation for this class was generated from the following files:
BatchProcessDialog.h
BatchProcessDialog.cpp