Audacity: BassBoostDialog Class Reference
BassBoostDialog Class Reference
Dialog for EffectBassBoost.
#include <BassBoost.h>
Public Member Functions
BassBoostDialog (EffectBassBoost *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
EffectBassBoost * mEffect
float freq
float boost
Private Member Functions
void OnBoostText (wxCommandEvent &event)
void OnFreqText (wxCommandEvent &event)
void OnBoostSlider (wxCommandEvent &event)
void OnFreqSlider (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
Private Attributes
wxSlider * mBoostS
wxSlider * mFreqS
wxTextCtrl * mBoostT
wxTextCtrl * mFreqT
Detailed Description
Dialog for EffectBassBoost.
Constructor & Destructor Documentation
BassBoostDialog::BassBoostDialog (EffectBassBoost * effect, wxWindow * parent)
Member Function Documentation
void BassBoostDialog::OnBoostSlider (wxCommandEvent & event) [private]
References mBoostS, and mBoostT.
void BassBoostDialog::OnBoostText (wxCommandEvent & event) [private]
References BOOST_MAX, BOOST_MIN, mBoostS, mBoostT, and TrapLong().
void BassBoostDialog::OnFreqSlider (wxCommandEvent & event) [private]
References mFreqS, and mFreqT.
void BassBoostDialog::OnFreqText (wxCommandEvent & event) [private]
References FREQ_MAX, FREQ_MIN, mFreqS, mFreqT, and TrapLong().
void BassBoostDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References boost, EffectBassBoost::dB_boost, freq, EffectBassBoost::frequency, mEffect, Effect::Preview(), and TransferDataFromWindow().
void BassBoostDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddSlider(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), BOOST_MAX, BOOST_MIN, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), FREQ_MAX, FREQ_MIN, ShuttleGui::Id(), ID_BOOST_SLIDER, ID_BOOST_TEXT, ID_FREQ_SLIDER, ID_FREQ_TEXT, mBoostS, mBoostT, mFreqS, mFreqT, numbers, ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartMultiColumn().
bool BassBoostDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References boost, BOOST_MAX, BOOST_MIN, freq, FREQ_MAX, FREQ_MIN, mBoostS, mFreqS, and TrapLong().
Referenced by OnPreview().
bool BassBoostDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References boost, freq, mBoostS, mBoostT, mFreqS, and mFreqT.
Referenced by EffectBassBoost::PromptUser().
Member Data Documentation
float BassBoostDialog::boost
Referenced by OnPreview(), EffectBassBoost::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
float BassBoostDialog::freq
Referenced by OnPreview(), EffectBassBoost::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* BassBoostDialog::mBoostS [private]
Referenced by OnBoostSlider(), OnBoostText(), PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
wxTextCtrl* BassBoostDialog::mBoostT [private]
Referenced by OnBoostSlider(), OnBoostText(), PopulateOrExchange(), and TransferDataToWindow().
EffectBassBoost* BassBoostDialog::mEffect
Referenced by OnPreview().
wxSlider* BassBoostDialog::mFreqS [private]
Referenced by OnFreqSlider(), OnFreqText(), PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
wxTextCtrl* BassBoostDialog::mFreqT [private]
Referenced by OnFreqSlider(), OnFreqText(), PopulateOrExchange(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
BassBoost.h
BassBoost.cpp