Audacity: EffectSoundTouch Class Reference
EffectSoundTouch Class Reference
#include <SoundTouchEffect.h>
Public Member Functions
virtual bool Process ()
Protected Attributes
SoundTouch * mSoundTouch
double mCurT0
double mCurT1
Private Member Functions
bool ProcessLabelTrack (Track *track)
bool ProcessOne (WaveTrack *t, sampleCount start, sampleCount end)
bool ProcessStereo (WaveTrack *leftTrack, WaveTrack *rightTrack, sampleCount start, sampleCount end)
bool ProcessStereoResults (const unsigned int outputCount, WaveTrack *outputLeftTrack, WaveTrack *outputRightTrack)
Private Attributes
int mCurTrackNum
double m_maxNewLength
Member Function Documentation
bool EffectSoundTouch::Process () [virtual]
Implements Effect.
Reimplemented in EffectChangePitch, and EffectChangeTempo.
References Track::All, Effect::CopyInputTracks(), TrackListIterator::First(), WaveTrack::GetEndTime(), Track::GetKind(), Track::GetLinked(), Track::GetSelected(), WaveTrack::GetStartTime(), Effect::GetTimeWarper(), Track::IsSynchroSelected(), Track::Label, m_maxNewLength, mCurT0, mCurT1, mCurTrackNum, Effect::mOutputTracks, mSoundTouch, Effect::mT0, Effect::mT1, TrackListIterator::Next(), ProcessLabelTrack(), ProcessOne(), ProcessStereo(), Effect::ReplaceProcessedTracks(), Track::SyncAdjust(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectSoundTouch::ProcessLabelTrack (Track * track) [private]
References Effect::GetTimeWarper(), and LabelTrack::WarpLabels().
Referenced by Process().
bool EffectSoundTouch::ProcessOne (WaveTrack * t, sampleCount start, sampleCount end) [private]
References WaveTrack::Append(), WaveTrack::ClearAndPaste(), floatSample, WaveTrack::Flush(), WaveTrack::Get(), WaveTrack::GetBestBlockSize(), WaveTrack::GetEndTime(), WaveTrack::GetMaxBlockSize(), WaveTrack::GetRate(), WaveTrack::GetSampleFormat(), Effect::GetTimeWarper(), m_maxNewLength, mCurT0, mCurT1, mCurTrackNum, Effect::mFactory, mSoundTouch, TrackFactory::NewWaveTrack(), and Effect::TrackProgress().
Referenced by Process().
bool EffectSoundTouch::ProcessStereo (WaveTrack * leftTrack, WaveTrack * rightTrack, sampleCount start, sampleCount end) [private]
References WaveTrack::ClearAndPaste(), floatSample, WaveTrack::Flush(), WaveTrack::Get(), WaveTrack::GetBestBlockSize(), WaveTrack::GetEndTime(), WaveTrack::GetMaxBlockSize(), WaveTrack::GetRate(), WaveTrack::GetSampleFormat(), Effect::GetTimeWarper(), m_maxNewLength, mCurT0, mCurT1, mCurTrackNum, Effect::mFactory, mSoundTouch, TrackFactory::NewWaveTrack(), ProcessStereoResults(), and Effect::TrackProgress().
Referenced by Process().
bool EffectSoundTouch::ProcessStereoResults (const unsigned int outputCount, WaveTrack * outputLeftTrack, WaveTrack * outputRightTrack) [private]
References WaveTrack::Append(), floatSample, and mSoundTouch.
Referenced by ProcessStereo().
Member Data Documentation
double EffectSoundTouch::m_maxNewLength [private]
Referenced by Process(), ProcessOne(), and ProcessStereo().
double EffectSoundTouch::mCurT0 [protected]
Referenced by Process(), ProcessOne(), and ProcessStereo().
double EffectSoundTouch::mCurT1 [protected]
Referenced by Process(), ProcessOne(), and ProcessStereo().
int EffectSoundTouch::mCurTrackNum [private]
Referenced by Process(), ProcessOne(), and ProcessStereo().
SoundTouch* EffectSoundTouch::mSoundTouch [protected]
Referenced by EffectChangeTempo::Init(), EffectChangePitch::Init(), Process(), EffectChangeTempo::Process(), EffectChangePitch::Process(), ProcessOne(), ProcessStereo(), and ProcessStereoResults().
The documentation for this class was generated from the following files:
SoundTouchEffect.h
SoundTouchEffect.cpp