Audacity: ChoiceEditor Class Reference
ChoiceEditor Class Reference
#include <Grid.h>
Classes
class FocusHandler
Public Member Functions
ChoiceEditor (size_t count=0, const wxString choices[]=NULL)
ChoiceEditor (const wxArrayString &choices)
~ChoiceEditor ()
virtual void Create (wxWindow *parent, wxWindowID id, wxEvtHandler *evtHandler)
void SetSize (const wxRect &rect)
void BeginEdit (int row, int col, wxGrid *grid)
bool EndEdit (int row, int col, wxGrid *grid)
void Reset ()
wxGridCellEditor * Clone () const
void SetChoices (const wxArrayString &choices)
wxString GetValue () const
Protected Member Functions
wxChoice * Choice () const
Private Attributes
ChoiceEditor::FocusHandler mHandler
wxArrayString mChoices
wxString mOld
Constructor & Destructor Documentation
ChoiceEditor::ChoiceEditor (size_t count = 0, const wxString choices[] = NULL)
References mChoices.
Referenced by Clone().
ChoiceEditor::ChoiceEditor (const wxArrayString & choices)
References mChoices.
ChoiceEditor::~ChoiceEditor ()
References ChoiceEditor::FocusHandler::DisconnectEvent(), and mHandler.
Member Function Documentation
void ChoiceEditor::BeginEdit (int row, int col, wxGrid * grid)
References Choice(), mChoices, and mOld.
wxChoice* ChoiceEditor::Choice () const [inline, protected]
Referenced by BeginEdit(), EndEdit(), GetValue(), and Reset().
wxGridCellEditor * ChoiceEditor::Clone () const
References ChoiceEditor(), and mChoices.
void ChoiceEditor::Create (wxWindow * parent, wxWindowID id, wxEvtHandler * evtHandler) [virtual]
References ChoiceEditor::FocusHandler::ConnectEvent(), mChoices, and mHandler.
bool ChoiceEditor::EndEdit (int row, int col, wxGrid * grid)
References Choice(), mChoices, and mOld.
wxString ChoiceEditor::GetValue () const
References Choice(), and mChoices.
void ChoiceEditor::Reset ()
References Choice(), mChoices, and mOld.
void ChoiceEditor::SetChoices (const wxArrayString & choices)
References mChoices.
Referenced by LabelDialog::TransferDataToWindow().
void ChoiceEditor::SetSize (const wxRect & rect)
Member Data Documentation
wxArrayString ChoiceEditor::mChoices [private]
Referenced by BeginEdit(), ChoiceEditor(), Clone(), Create(), EndEdit(), GetValue(), Reset(), and SetChoices().
ChoiceEditor::FocusHandler ChoiceEditor::mHandler [private]
Referenced by Create(), and ~ChoiceEditor().
wxString ChoiceEditor::mOld [private]
Referenced by BeginEdit(), EndEdit(), and Reset().
The documentation for this class was generated from the following files:
Grid.h
Grid.cpp