Audacity: ODComputeSummaryTask Class Reference
ODComputeSummaryTask Class Reference
A class representing a modular task to be used with the On-Demand structures.
#include <ODComputeSummaryTask.h>
Public Member Functions
ODComputeSummaryTask ()
Constructs an ODTask.
virtual ~ODComputeSummaryTask ()
virtual ODTask * Clone ()
virtual unsigned int GetODType ()
Subclasses should override to return respective type.
virtual const char * GetTaskName ()
Return the task name.
virtual const wxChar * GetTip ()
virtual bool UsesCustomWorkUntilPercentage ()
virtual float ComputeNextWorkUntilPercentageComplete ()
virtual void Terminate ()
releases memory that the ODTask owns. Subclasses should override.
Protected Member Functions
virtual void CalculatePercentComplete ()
recalculates the percentage complete.
virtual void DoSomeInternal ()
Computes and writes the data for one BlockFile if it still has a refcount.
virtual void Update ()
by default creates the order of the wavetrack to load.
virtual void ODUpdate ()
Readjusts the blockfile order to start at the new cursor.
void OrderBlockFiles (std::vector< ODPCMAliasBlockFile * > &unorderedBlocks)
Orders the input as either On-Demand or default layered order.
void MarkUpdateRan ()
tells us whether or not Update has been run at least once.
bool HasUpdateRan ()
Protected Attributes
ODLock mBlockFilesMutex
std::vector
< ODPCMAliasBlockFile * > mBlockFiles
int mMaxBlockFiles
int mComputedBlockFiles
ODLock mHasUpdateRanMutex
bool mHasUpdateRan
Detailed Description
A class representing a modular task to be used with the On-Demand structures.
Computes the summary data for a PCM (WAV) file and writes it to disk, updating the ODPCMAliasBlockFile and the GUI of the newly available data.
Constructor & Destructor Documentation
ODComputeSummaryTask::ODComputeSummaryTask ()
Constructs an ODTask.
Creates a new task that computes summaries for a wavetrack that needs to be specified through SetWaveTrack().
References mComputedBlockFiles, mHasUpdateRan, and mMaxBlockFiles.
virtual ODComputeSummaryTask::~ODComputeSummaryTask () [inline, virtual]
Member Function Documentation
void ODComputeSummaryTask::CalculatePercentComplete () [protected, virtual]
recalculates the percentage complete.
Implements ODTask.
References HasUpdateRan(), mBlockFiles, mMaxBlockFiles, ODTask::mPercentComplete, and ODTask::mPercentCompleteMutex.
Referenced by DoSomeInternal().
ODTask * ODComputeSummaryTask::Clone () [virtual]
Implements ODTask.
References ODTask::GetDemandSample(), and ODTask::mDemandSample.
float ODComputeSummaryTask::ComputeNextWorkUntilPercentageComplete () [virtual]
compute the next time we should take a break in terms of overall percentage. We want to do a constant number of blockfiles.
Reimplemented from ODTask.
References kNumBlockFilesPerDoSome, mMaxBlockFiles, ODTask::mPercentComplete, and ODTask::mPercentCompleteMutex.
void ODComputeSummaryTask::DoSomeInternal () [protected, virtual]
Computes and writes the data for one BlockFile if it still has a refcount.
Implements ODTask.
References CalculatePercentComplete(), ODPCMAliasBlockFile::Deref(), ODPCMAliasBlockFile::DoWriteSummary(), BlockFile::GetLength(), ODPCMAliasBlockFile::GetStart(), mBlockFiles, mBlockFilesMutex, mComputedBlockFiles, mMaxBlockFiles, ODTask::mPercentComplete, ODTask::mPercentCompleteMutex, ODTask::mWaveTrackMutex, and ODTask::mWaveTracks.
virtual unsigned int ODComputeSummaryTask::GetODType () [inline, virtual]
Subclasses should override to return respective type.
Reimplemented from ODTask.
References ODTask::eODPCMSummary.
virtual const char* ODComputeSummaryTask::GetTaskName () [inline, virtual]
Return the task name.
Reimplemented from ODTask.
virtual const wxChar* ODComputeSummaryTask::GetTip () [inline, virtual]
Implements ODTask.
bool ODComputeSummaryTask::HasUpdateRan () [protected]
References mHasUpdateRan, and mHasUpdateRanMutex.
Referenced by CalculatePercentComplete().
void ODComputeSummaryTask::MarkUpdateRan () [protected]
tells us whether or not Update has been run at least once.
References mHasUpdateRan, and mHasUpdateRanMutex.
Referenced by Update().
void ODComputeSummaryTask::ODUpdate () [protected, virtual]
Readjusts the blockfile order to start at the new cursor.
Reimplemented from ODTask.
void ODComputeSummaryTask::OrderBlockFiles (std::vector< ODPCMAliasBlockFile * > & unorderedBlocks) [protected]
Orders the input as either On-Demand or default layered order.
References ODTask::GetDemandSample(), mBlockFiles, and mMaxBlockFiles.
Referenced by Update().
void ODComputeSummaryTask::Terminate () [virtual]
releases memory that the ODTask owns. Subclasses should override.
Reimplemented from ODTask.
References mBlockFiles, and mBlockFilesMutex.
void ODComputeSummaryTask::Update () [protected, virtual]
by default creates the order of the wavetrack to load.
Readjusts the blockfile order in the default manner. If we have had an ODRequest Then it updates in the OD manner.
Reimplemented from ODTask.
References WaveClip::GetRate(), WaveClip::GetSequence(), WaveClip::GetSequenceBlockArray(), WaveClip::GetStartTime(), Sequence::LockDeleteUpdateMutex(), MarkUpdateRan(), mBlockFilesMutex, ODTask::mWaveTrackMutex, ODTask::mWaveTracks, OrderBlockFiles(), and Sequence::UnlockDeleteUpdateMutex().
virtual bool ODComputeSummaryTask::UsesCustomWorkUntilPercentage () [inline, virtual]
Reimplemented from ODTask.
Member Data Documentation
std::vector<ODPCMAliasBlockFile*> ODComputeSummaryTask::mBlockFiles [protected]
Referenced by CalculatePercentComplete(), DoSomeInternal(), OrderBlockFiles(), and Terminate().
ODLock ODComputeSummaryTask::mBlockFilesMutex [protected]
Referenced by DoSomeInternal(), Terminate(), and Update().
int ODComputeSummaryTask::mComputedBlockFiles [protected]
Referenced by DoSomeInternal(), and ODComputeSummaryTask().
bool ODComputeSummaryTask::mHasUpdateRan [protected]
Referenced by HasUpdateRan(), MarkUpdateRan(), and ODComputeSummaryTask().
ODLock ODComputeSummaryTask::mHasUpdateRanMutex [protected]
Referenced by HasUpdateRan(), and MarkUpdateRan().
int ODComputeSummaryTask::mMaxBlockFiles [protected]
Referenced by CalculatePercentComplete(), ComputeNextWorkUntilPercentageComplete(), DoSomeInternal(), ODComputeSummaryTask(), and OrderBlockFiles().
The documentation for this class was generated from the following files:
ODComputeSummaryTask.h
ODComputeSummaryTask.cpp