Audacity: XMLWriter Class Reference
XMLWriter Class Reference
Base class for XMLFileWriter and XMLStringWriter that provides the general functionality for creating XML in UTF8 encoding.
#include <XMLWriter.h>
Public Member Functions
XMLWriter ()
virtual ~XMLWriter ()
void StartTag (const wxString &name)
void EndTag (const wxString &name)
void WriteAttr (const wxString &name, const wxString &value)
void WriteAttr (const wxChar *name, const wxChar *value)
void WriteAttr (const wxString &name, const wxChar *value)
void WriteAttr (const wxChar *name, const wxString &value)
void WriteAttr (const wxString &name, int value)
void WriteAttr (const wxChar *name, int value)
void WriteAttr (const wxString &name, bool value)
void WriteAttr (const wxChar *name, bool value)
void WriteAttr (const wxString &name, long value)
void WriteAttr (const wxChar *name, long value)
void WriteAttr (const wxString &name, long long value)
void WriteAttr (const wxChar *name, long long value)
void WriteAttr (const wxString &name, size_t value)
void WriteAttr (const wxChar *name, size_t value)
void WriteAttr (const wxString &name, float value, int digits=-1)
void WriteAttr (const wxChar *name, float value, int digits=-1)
void WriteAttr (const wxString &name, double value, int digits=-1)
void WriteAttr (const wxChar *name, double value, int digits=-1)
void WriteData (const wxString &value)
void WriteData (const wxChar *value)
void WriteSubTree (const wxString &value)
void WriteSubTree (const wxChar *value)
void Write (const wxChar *data)
virtual void Write (const wxString &data)=0
wxString XMLEsc (const wxString &s)
Protected Attributes
bool mInTag
int mDepth
wxArrayString mTagstack
wxArrayInt mHasKids
Detailed Description
Base class for XMLFileWriter and XMLStringWriter that provides the general functionality for creating XML in UTF8 encoding.
XMLWriter
Constructor & Destructor Documentation
XMLWriter::XMLWriter ()
XMLWriter base class
References mDepth, mHasKids, and mInTag.
XMLWriter::~XMLWriter () [virtual]
Member Function Documentation
void XMLWriter::EndTag (const wxString & name)
References mDepth, mHasKids, mInTag, mTagstack, and Write().
Referenced by XMLFileWriter::Close(), ConvertLegacyProjectFile(), ConvertLegacyTrack(), AudioIO::FillBuffers(), SimpleBlockFile::SaveXML(), SilentBlockFile::SaveXML(), PCMAliasBlockFile::SaveXML(), ODPCMAliasBlockFile::SaveXML(), ODDecodeBlockFile::SaveXML(), LegacyBlockFile::SaveXML(), LegacyAliasBlockFile::SaveXML(), WaveTrack::WriteXML(), WaveClip::WriteXML(), TimeTrack::WriteXML(), Tags::WriteXML(), Sequence::WriteXML(), AudacityProject::WriteXML(), LabelTrack::WriteXML(), FFmpegPresets::WriteXML(), EqualizationDialog::WriteXML(), EnvPoint::WriteXML(), Envelope::WriteXML(), and CommandManager::WriteXML().
void XMLWriter::StartTag (const wxString & name)
References mDepth, mHasKids, mInTag, mTagstack, and Write().
Referenced by ConvertLegacyProjectFile(), ConvertLegacyTrack(), AudioIO::FillBuffers(), SimpleBlockFile::SaveXML(), SilentBlockFile::SaveXML(), PCMAliasBlockFile::SaveXML(), ODPCMAliasBlockFile::SaveXML(), ODDecodeBlockFile::SaveXML(), LegacyBlockFile::SaveXML(), LegacyAliasBlockFile::SaveXML(), WaveTrack::WriteXML(), WaveClip::WriteXML(), TimeTrack::WriteXML(), Tags::WriteXML(), Sequence::WriteXML(), AudacityProject::WriteXML(), LabelTrack::WriteXML(), FFmpegPresets::WriteXML(), EqualizationDialog::WriteXML(), EnvPoint::WriteXML(), Envelope::WriteXML(), and CommandManager::WriteXML().
virtual void XMLWriter::Write (const wxString & data) [pure virtual]
Implemented in XMLFileWriter, and XMLStringWriter.
void XMLWriter::Write (const wxChar * data)
Referenced by EndTag(), StartTag(), WriteAttr(), WriteData(), WriteSubTree(), AudacityProject::WriteXMLHeader(), and FFmpegPresets::WriteXMLHeader().
void XMLWriter::WriteAttr (const wxChar * name, double value, int digits = -1)
References WriteAttr().
void XMLWriter::WriteAttr (const wxString & name, double value, int digits = -1)
References Internat::ToString(), and Write().
void XMLWriter::WriteAttr (const wxChar * name, float value, int digits = -1)
References WriteAttr().
void XMLWriter::WriteAttr (const wxString & name, float value, int digits = -1)
References Internat::ToString(), and Write().
void XMLWriter::WriteAttr (const wxChar * name, size_t value)
References WriteAttr().
void XMLWriter::WriteAttr (const wxString & name, size_t value)
References Write().
void XMLWriter::WriteAttr (const wxChar * name, long long value)
References WriteAttr().
void XMLWriter::WriteAttr (const wxString & name, long long value)
References Write().
void XMLWriter::WriteAttr (const wxChar * name, long value)
References WriteAttr().
void XMLWriter::WriteAttr (const wxString & name, long value)
References Write().
void XMLWriter::WriteAttr (const wxChar * name, bool value)
References WriteAttr().
void XMLWriter::WriteAttr (const wxString & name, bool value)
References Write().
void XMLWriter::WriteAttr (const wxChar * name, int value)
References WriteAttr().
void XMLWriter::WriteAttr (const wxString & name, int value)
References Write().
void XMLWriter::WriteAttr (const wxChar * name, const wxString & value)
References WriteAttr().
void XMLWriter::WriteAttr (const wxString & name, const wxChar * value)
References WriteAttr().
void XMLWriter::WriteAttr (const wxChar * name, const wxChar * value)
References WriteAttr().
void XMLWriter::WriteAttr (const wxString & name, const wxString & value)
References Write(), and XMLEsc().
Referenced by ConvertLegacyProjectFile(), ConvertLegacyTrack(), AudioIO::FillBuffers(), SimpleBlockFile::SaveXML(), SilentBlockFile::SaveXML(), PCMAliasBlockFile::SaveXML(), ODPCMAliasBlockFile::SaveXML(), ODDecodeBlockFile::SaveXML(), LegacyBlockFile::SaveXML(), LegacyAliasBlockFile::SaveXML(), WriteAttr(), WaveTrack::WriteXML(), WaveClip::WriteXML(), TimeTrack::WriteXML(), Tags::WriteXML(), Sequence::WriteXML(), AudacityProject::WriteXML(), LabelTrack::WriteXML(), FFmpegPresets::WriteXML(), EqualizationDialog::WriteXML(), EnvPoint::WriteXML(), Envelope::WriteXML(), and CommandManager::WriteXML().
void XMLWriter::WriteData (const wxChar * value)
References WriteData().
void XMLWriter::WriteData (const wxString & value)
References mDepth, Write(), and XMLEsc().
Referenced by WriteData().
void XMLWriter::WriteSubTree (const wxChar * value)
References WriteSubTree().
void XMLWriter::WriteSubTree (const wxString & value)
References mHasKids, mInTag, and Write().
Referenced by AudioIO::FillBuffers(), and WriteSubTree().
wxString XMLWriter::XMLEsc (const wxString & s)
Referenced by WriteAttr(), and WriteData().
Member Data Documentation
int XMLWriter::mDepth [protected]
Referenced by EndTag(), StartTag(), WriteData(), and XMLWriter().
wxArrayInt XMLWriter::mHasKids [protected]
Referenced by EndTag(), StartTag(), WriteSubTree(), and XMLWriter().
bool XMLWriter::mInTag [protected]
Referenced by EndTag(), StartTag(), WriteSubTree(), and XMLWriter().
wxArrayString XMLWriter::mTagstack [protected]
Referenced by XMLFileWriter::Close(), EndTag(), and StartTag().
The documentation for this class was generated from the following files:
XMLWriter.h
XMLWriter.cpp