Audacity: AudioIO.cpp File Reference
AudioIO.cpp File Reference
#include "Audacity.h"
#include "float_cast.h"
#include "Experimental.h"
#include <math.h>
#include <stdlib.h>
#include <algorithm>
#include <wx/log.h>
#include <wx/textctrl.h>
#include <wx/msgdlg.h>
#include <wx/timer.h>
#include <wx/intl.h>
#include <wx/debug.h>
#include <wx/sstream.h>
#include <wx/txtstrm.h>
#include "AudacityApp.h"
#include "AudioIO.h"
#include "WaveTrack.h"
#include "Mix.h"
#include "Resample.h"
#include "RingBuffer.h"
#include "Prefs.h"
#include "Project.h"
#include "toolbars/ControlToolBar.h"
#include "widgets/Meter.h"
#include "../Experimental.h"
Classes
class AudioThread
Defined different on Mac and other platforms (on Mac it does not use wxWidgets wxThread), this class sits in a thread loop reading and writing audio.
Defines
#define NO_STABLE_INDICATOR -1000000000
#define LOWER_BOUND 0.0
#define UPPER_BOUND 1.0
#define MAX(a, b) ((a) > (b) ? (a) : (b))
Functions
int audacityAudioCallback (const void *inputBuffer, void *outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
void InitAudioIO ()
void DeinitAudioIO ()
wxString DeviceName (const PaDeviceInfo *info)
PaSampleFormat AudacityToPortAudioSampleFormat (sampleFormat format)
void DoSoftwarePlaythrough (const void *inputBuffer, sampleFormat inputFormat, int inputChannels, float *outputBuffer, int len, float gain)
Variables
AudioIO * gAudioIO
Define Documentation
#define LOWER_BOUND 0.0
#define MAX (a, b) ((a) > (b) ? (a) : (b))
Referenced by audacityAudioCallback().
#define NO_STABLE_INDICATOR -1000000000
#define UPPER_BOUND 1.0
Function Documentation
int audacityAudioCallback (const void * inputBuffer, void * outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData)
brief The function which is called from PortAudio's callback thread context to collect and deliver audio for / from the sound device.
This covers recording, playback, and doing both simultaneously. It is also invoked to do monitoring and software playthrough. Note that dealing with the two buffers needs some care to ensure that the right things happen for all possible cases.
Parameters:
inputBuffer Buffer of length framesPerBuffer containing samples from the sound card, or null if not capturing audio. Note that the data type will depend on the format of audio data that was chosen when the stream was created (so could be floats or various integers)
outputBuffer Uninitialised buffer of length framesPerBuffer which will be sent to the sound card after the callback, or null if not playing audio back.
framesPerBuffer The length of the playback and recording buffers
PaStreamCallbackTimeInfo Pointer to PortAudio time information structure, which tells us how long we have been playing / recording
statusFlags PortAudio stream status flags
userData pointer to user-defined data structure. Provided for flexibility by PortAudio, but not used by Audacity - the data is stored in the AudioIO class instead.
References RingBuffer::AvailForGet(), RingBuffer::AvailForPut(), ClearSamples(), CopySamples(), RingBuffer::Discard(), DoSoftwarePlaythrough(), floatSample, RingBuffer::Get(), GetActiveProject(), Track::GetChannel(), WaveTrack::GetChannelGain(), AudacityProject::GetControlToolBar(), TimeTrack::GetEnvelope(), Track::GetLinked(), Meter::GetMaxPeak(), Track::GetMute(), TimeTrack::GetRangeLower(), TimeTrack::GetRangeUpper(), Track::GetSolo(), Envelope::GetValue(), int16Sample, int24Sample, Meter::IsMeterDisabled(), AudioIO::IsPaused(), Track::LeftChannel, AudioIO::mAudioThreadFillBuffersLoopActive, AudioIO::mAudioThreadFillBuffersLoopRunning, AudioIO::mAudioThreadShouldCallFillBuffersOnce, MAX, AudioIO::mCaptureBuffers, AudioIO::mCaptureFormat, AudioIO::mEmulateMixerOutputVol, AudioIO::mInputMeter, AudioIO::mLastRecordingOffset, AudioIO::mLostSamples, AudioIO::mMixerOutputVol, AudioIO::mNumCaptureChannels, AudioIO::mNumPlaybackChannels, Track::MonoChannel, AudioIO::mOutputMeter, AudioIO::mPaused, AudioIO::mPauseRec, AudioIO::mPlaybackBuffers, AudioIO::mPlaybackMixers, AudioIO::mPlaybackTracks, AudioIO::mPlayLooped, AudioIO::mPortStreamV19, AudioIO::mRate, AudioIO::mSeek, AudioIO::mSilenceLevel, AudioIO::mSoftwarePlaythrough, AudioIO::mStreamToken, AudioIO::mT, AudioIO::mT0, AudioIO::mT1, AudioIO::mTime, AudioIO::mTimeTrack, AudioIO::mUpdateMeters, AudioIO::mUpdatingMeters, ControlToolBar::OnPause(), RingBuffer::Put(), Mixer::Reposition(), Track::RightChannel, and Meter::UpdateDisplay().
PaSampleFormat AudacityToPortAudioSampleFormat (sampleFormat format)
References floatSample, int16Sample, and int24Sample.
Referenced by AudioIO::StartPortAudioStream().
void DeinitAudioIO ()
Referenced by AudacityApp::OnExit().
wxString DeviceName (const PaDeviceInfo * info)
Referenced by DevicePrefs::Apply(), AudioIO::GetDeviceInfo(), AudioIO::getPlayDevIndex(), AudioIO::getRecordDevIndex(), InitAudioIO(), DeviceToolBar::OnChoice(), DevicePrefs::OnHost(), and DeviceToolBar::Populate().
void DoSoftwarePlaythrough (const void * inputBuffer, sampleFormat inputFormat, int inputChannels, float * outputBuffer, int len, float gain)
References CopySamples(), floatSample, and SAMPLE_SIZE.
Referenced by audacityAudioCallback().
void InitAudioIO ()
References DeviceName(), AudioIO::getPlayDevIndex(), AudioIO::getRecordDevIndex(), gPrefs, and AudioIO::mThread.
Referenced by AudacityApp::OnInit().
Variable Documentation
AudioIO* gAudioIO
Referenced by LabelTrack::CaptureKey(), CreateNewAudacityProject(), MeterToolBar::DestroyChildren(), TrackPanel::DoDrawIndicator(), ControlToolBar::EnableDisableButtons(), AudacityProject::GetUpdateFlags(), TrackPanel::HandleClosing(), TrackPanel::HandleLabelClick(), TrackPanel::HandleTrackSpecificMouseEvent(), TrackPanel::IsUnsafe(), AudacityProject::MakeReadyToPlay(), AudacityProject::OnAddLabelPlaying(), AudacityProject::OnAudioDeviceInfo(), TranscriptionToolBar::OnAutomateSelection(), TrackPanel::OnBoundaryMove(), EditToolBar::OnButton(), TranscriptionToolBar::OnCalibrate(), DeviceToolBar::OnChoice(), AudacityProject::OnCloseWindow(), TrackPanel::OnCursorLeft(), TrackPanel::OnCursorMove(), TrackPanel::OnCursorRight(), Meter::OnDisableMeter(), TranscriptionToolBar::OnEndOff(), TranscriptionToolBar::OnEndOn(), TranscriptionToolBar::OnKeyEvent(), ControlToolBar::OnKeyEvent(), Meter::OnMeterUpdate(), Meter::OnMouse(), PrefsDialog::OnOK(), TrackPanel::OnPaint(), ControlToolBar::OnPause(), TranscriptionToolBar::OnPlaySpeed(), AudacityProject::OnPlayStop(), AudacityProject::OnPlayStopSelect(), ControlToolBar::OnRecord(), TranscriptionToolBar::OnSelectSilence(), TranscriptionToolBar::OnSelectSound(), AudacityProject::OnSetLeftSelection(), AudacityProject::OnSetRightSelection(), TranscriptionToolBar::OnStartOff(), TranscriptionToolBar::OnStartOn(), AudacityProject::OnStop(), AudacityProject::OnStopSelect(), TrackPanel::OnTimer(), AudacityProject::OnTimer(), TrackPanel::OnTrackClose(), AudacityProject::OnZoomIn(), ControlToolBar::PlayPlayRegion(), MixerToolBar::Populate(), MeterToolBar::Populate(), Effect::Preview(), AudacityProject::PushState(), TrackPanel::SelectionHandleClick(), MixerToolBar::SetMixer(), ControlToolBar::SetVUMeters(), Meter::StartMonitoring(), ControlToolBar::StopPlaying(), AudacityProject::TP_DisplaySelection(), MixerToolBar::UpdateControls(), AudacityProject::UpdateMixerBoard(), MixerToolBar::UpdatePrefs(), and Meter::~Meter().