Audacity: BatchCommands.cpp File Reference
BatchCommands.cpp File Reference
#include "Audacity.h"
#include <wx/defs.h>
#include <wx/dir.h>
#include <wx/msgdlg.h>
#include <wx/filedlg.h>
#include <wx/textfile.h>
#include "Project.h"
#include "BatchCommands.h"
#include "commands/CommandManager.h"
#include "effects/EffectManager.h"
#include "FileNames.h"
#include "Internat.h"
#include "Prefs.h"
#include "Shuttle.h"
#include "export/ExportFLAC.h"
#include "export/ExportMP3.h"
#include "export/ExportOGG.h"
#include "export/ExportPCM.h"
#include "Theme.h"
#include "AllThemeResources.h"
Enumerations
enum eCommandType { CtEffect, CtMenu, CtSpecial }
Variables
wxString SpecialCommands []
static const wxString CleanSpeech = wxT("CleanSpeech")
static const wxString MP3Conversion = wxT("MP3 Conversion")
Enumeration Type Documentation
enum eCommandType
Enumerator:
CtEffect
CtMenu
CtSpecial
Variable Documentation
const wxString CleanSpeech = wxT("CleanSpeech") [static]
Referenced by BatchCommands::BatchCommands(), BatchCommands::IsFixed(), and BatchCommands::RestoreChain().
const wxString MP3Conversion = wxT("MP3 Conversion") [static]
Referenced by BatchCommands::BatchCommands(), BatchCommands::IsFixed(), and BatchCommands::RestoreChain().
wxString SpecialCommands[]
Initial value:
 {
   wxT("NoAction"),
   wxT("Import"),
   wxT("SaveHqMaster1"),
   wxT("SaveHqMaster2"),
   wxT("StereoToMono"),
   wxT("ExportFlac"),
   wxT("ExportMp3"),
   wxT("ExportOgg"),
   wxT("ExportWav")
}
Referenced by BatchCommands::ApplyCommand(), and BatchCommands::GetAllCommands().