Audacity: Dependencies.cpp File Reference
Dependencies.cpp File Reference
#include <wx/defs.h>
#include <wx/dialog.h>
#include <wx/hashmap.h>
#include <wx/progdlg.h>
#include <wx/choice.h>
#include "BlockFile.h"
#include "Dependencies.h"
#include "DirManager.h"
#include "Internat.h"
#include "Project.h"
#include "ShuttleGui.h"
#include "Prefs.h"
#include <wx/arrimpl.cpp>
Classes
class DependencyDialog
Enumerations
enum { FileListID = 6000, CopyID, FutureActionID }
Functions
WX_DEFINE_OBJARRAY (AliasedFileArray)
WX_DECLARE_HASH_MAP (wxString, AliasedFile *, wxStringHash, wxStringEqual, AliasedFileHash)
WX_DECLARE_HASH_MAP (BlockFile *, BlockFile *, wxPointerHash, wxPointerEqual, ReplacedBlockFileHash)
WX_DECLARE_HASH_MAP (BlockFile *, bool, wxPointerHash, wxPointerEqual, BoolBlockFileHash)
void GetAllSeqBlocks (AudacityProject *project, BlockArray *outBlocks)
void ReplaceBlockFiles (AudacityProject *project, ReplacedBlockFileHash &hash)
bool FindDependencies (AudacityProject *project, AliasedFileArray *outAliasedFiles)
bool RemoveDependencies (AudacityProject *project, AliasedFileArray *aliasedFiles)
EVT_BUTTON (wxID_CANCEL, DependencyDialog::OnCancel) DependencyDialog
bool ShowDependencyDialogIfNeeded (AudacityProject *project, bool isSaving)
Variables
wxString kDependencyDialogPrompt
Enumeration Type Documentation
anonymous enum
Enumerator:
FileListID
CopyID
FutureActionID
Function Documentation
EVT_BUTTON (wxID_CANCEL , DependencyDialog::OnCancel)
References eIsCreating.
bool FindDependencies (AudacityProject * project, AliasedFileArray * outAliasedFiles)
References AliasBlockFile::GetAliasedFile(), GetAllSeqBlocks(), AudacityProject::GetDefaultFormat(), BlockFile::GetLength(), BlockFile::IsAlias(), and SAMPLE_SIZE.
Referenced by ShowDependencyDialogIfNeeded().
void GetAllSeqBlocks (AudacityProject * project, BlockArray * outBlocks)
References TrackListIterator::First(), Sequence::GetBlockArray(), WaveTrack::GetClipIterator(), Track::GetKind(), WaveClip::GetSequence(), AudacityProject::GetTracks(), TrackListIterator::Next(), and Track::Wave.
Referenced by FindDependencies(), RemoveDependencies(), and ReplaceBlockFiles().
bool RemoveDependencies (AudacityProject * project, AliasedFileArray * aliasedFiles)
References DeleteSamples(), DirManager::Deref(), eProgressSuccess, AliasBlockFile::GetAliasedFile(), GetAllSeqBlocks(), AudacityProject::GetDefaultFormat(), AudacityProject::GetDirManager(), BlockFile::GetLength(), BlockFile::IsAlias(), NewSamples(), DirManager::NewSimpleBlockFile(), BlockFile::ReadData(), ReplaceBlockFiles(), SAMPLE_SIZE, and ProgressDialog::Update().
Referenced by DependencyDialog::OnCopy(), and ShowDependencyDialogIfNeeded().
void ReplaceBlockFiles (AudacityProject * project, ReplacedBlockFileHash & hash)
References DirManager::Deref(), GetAllSeqBlocks(), AudacityProject::GetDirManager(), and DirManager::Ref().
Referenced by RemoveDependencies().
bool ShowDependencyDialogIfNeeded (AudacityProject * project, bool isSaving)
References FindDependencies(), gPrefs, and RemoveDependencies().
Referenced by AudacityProject::OnCheckDependencies(), and AudacityProject::Save().
WX_DECLARE_HASH_MAP (BlockFile * , bool , wxPointerHash , wxPointerEqual , BoolBlockFileHash)
WX_DECLARE_HASH_MAP (BlockFile * , BlockFile * , wxPointerHash , wxPointerEqual , ReplacedBlockFileHash)
WX_DECLARE_HASH_MAP (wxString , AliasedFile * , wxStringHash , wxStringEqual , AliasedFileHash)
WX_DEFINE_OBJARRAY (AliasedFileArray)
Variable Documentation
wxString kDependencyDialogPrompt
Initial value:
_("Copying the following files into your project will remove this dependency.\
\nThis needs more disk space, but is safer.")
Referenced by DependencyDialog::PopulateOrExchange().