Audacity: DirManager.cpp File Reference
DirManager.cpp File Reference
#include "Audacity.h"
#include <wx/defs.h>
#include <wx/app.h>
#include <wx/dir.h>
#include <wx/log.h>
#include <wx/filefn.h>
#include <wx/hash.h>
#include <wx/msgdlg.h>
#include <wx/progdlg.h>
#include <wx/timer.h>
#include <wx/intl.h>
#include <wx/file.h>
#include <wx/filename.h>
#include <wx/object.h>
#include <time.h>
#include "AudacityApp.h"
#include "BlockFile.h"
#include "blockfile/LegacyBlockFile.h"
#include "blockfile/LegacyAliasBlockFile.h"
#include "blockfile/SimpleBlockFile.h"
#include "blockfile/SilentBlockFile.h"
#include "blockfile/PCMAliasBlockFile.h"
#include "blockfile/ODPCMAliasBlockFile.h"
#include "blockfile/ODDecodeBlockFile.h"
#include "DirManager.h"
#include "Internat.h"
#include "Project.h"
#include "Prefs.h"
#include "widgets/Warning.h"
#include "widgets/MultiDialog.h"
#include "prefs/PrefsDialog.h"
#include "ondemand/ODManager.h"
Functions
static int rm_dash_rf_enumerate_i (wxString dirpath, wxArrayString &flist, wxString dirspec, int files_p, int dirs_p, int progress_count, int progress_bias, const wxChar *prompt, ProgressDialog *progress)
static int rm_dash_rf_enumerate_prompt (wxString dirpath, wxArrayString &flist, wxString dirspec, int files_p, int dirs_p, int progress_count, const wxChar *prompt)
static int rm_dash_rf_enumerate (wxString dirpath, wxArrayString &flist, wxString dirspec, int files_p, int dirs_p)
static void rm_dash_rf_execute (wxArrayString &fList, int count, int files_p, int dirs_p, const wxChar *prompt)
static unsigned int hexchar_to_int (unsigned int x)
wxMemorySize GetFreeMemory ()
Function Documentation
wxMemorySize GetFreeMemory ()
Referenced by DirManager::FillBlockfilesCache(), and SimpleBlockFile::GetCache().
static unsigned int hexchar_to_int (unsigned int x) [inline, static]
Referenced by DirManager::BalanceInfoAdd(), and DirManager::BalanceInfoDel().
static int rm_dash_rf_enumerate (wxString dirpath, wxArrayString & flist, wxString dirspec, int files_p, int dirs_p) [static]
References rm_dash_rf_enumerate_i().
Referenced by DirManager::CleanTempDir(), and DirManager::SetProject().
static int rm_dash_rf_enumerate_i (wxString dirpath, wxArrayString & flist, wxString dirspec, int files_p, int dirs_p, int progress_count, int progress_bias, const wxChar * prompt, ProgressDialog * progress) [static]
References name, and ProgressDialog::Update().
Referenced by rm_dash_rf_enumerate(), and rm_dash_rf_enumerate_prompt().
static int rm_dash_rf_enumerate_prompt (wxString dirpath, wxArrayString & flist, wxString dirspec, int files_p, int dirs_p, int progress_count, const wxChar * prompt) [static]
References rm_dash_rf_enumerate_i().
Referenced by DirManager::ProjectFSCK(), and DirManager::RemoveOrphanedBlockfiles().
static void rm_dash_rf_execute (wxArrayString & fList, int count, int files_p, int dirs_p, const wxChar * prompt) [static]
References ProgressDialog::Update().
Referenced by DirManager::CleanTempDir(), DirManager::ProjectFSCK(), and DirManager::SetProject().