Audacity: Effect.cpp File Reference
Effect.cpp File Reference
#include "../Audacity.h"
#include <wx/defs.h>
#include <wx/string.h>
#include <wx/msgdlg.h>
#include <wx/progdlg.h>
#include <wx/sizer.h>
#include <wx/timer.h>
#include <wx/hashmap.h>
#include "Effect.h"
#include "../AudioIO.h"
#include "../Mix.h"
#include "../Prefs.h"
#include "../Project.h"
#include "../WaveTrack.h"
#include "../widgets/ProgressDialog.h"
#include "../ondemand/ODManager.h"
#include "TimeWarper.h"
Functions
WX_DECLARE_VOIDPTR_HASH_MAP (bool, t2bHash)
float TrapFloat (float x, float min, float max)
double TrapDouble (double x, double min, double max)
long TrapLong (long x, long min, long max)
Function Documentation
double TrapDouble (double x, double min, double max)
Referenced by AmplifyDialog::OnAmpSlider(), AmplifyDialog::OnAmpText(), WahwahDialog::OnFreqOffText(), PhaserDialog::OnFreqText(), AmplifyDialog::OnPeakText(), WahwahDialog::OnResonanceText(), EffectNormalize::StartProcessing(), WahwahDialog::TransferDataFromWindow(), ToneGenDialog::TransferDataFromWindow(), PhaserDialog::TransferDataFromWindow(), NoiseDialog::TransferDataFromWindow(), DtmfDialog::TransferDataFromWindow(), AmplifyDialog::TransferDataFromWindow(), and AmplifyDialog::TransferDataToWindow().
float TrapFloat (float x, float min, float max)
long TrapLong (long x, long min, long max)
Referenced by BassBoostDialog::OnBoostText(), WahwahDialog::OnDepthText(), PhaserDialog::OnDepthText(), PhaserDialog::OnDryWetText(), PhaserDialog::OnFeedbackText(), WahwahDialog::OnFreqText(), NoiseRemovalDialog::OnFreqText(), BassBoostDialog::OnFreqText(), NoiseRemovalDialog::OnGainText(), WahwahDialog::OnPhaseText(), PhaserDialog::OnPhaseText(), PhaserDialog::OnStagesText(), ClickRemovalDialog::OnThreshText(), NoiseRemovalDialog::OnTimeText(), ClickRemovalDialog::OnWidthText(), DtmfDialog::Recalculate(), WahwahDialog::TransferDataFromWindow(), PhaserDialog::TransferDataFromWindow(), ClickRemovalDialog::TransferDataFromWindow(), BassBoostDialog::TransferDataFromWindow(), and NoiseRemovalDialog::TransferDataToWindow().
WX_DECLARE_VOIDPTR_HASH_MAP (bool , t2bHash)