Audacity: Envelope.cpp File Reference
Envelope.cpp File Reference
#include "Envelope.h"
#include <math.h>
#include <wx/dc.h>
#include <wx/brush.h>
#include <wx/event.h>
#include <wx/pen.h>
#include <wx/textfile.h>
#include <wx/log.h>
#include "AColor.h"
#include "Prefs.h"
#include "DirManager.h"
#include "TrackArtist.h"
Defines
#define SQR(X) ((X)*(X))
Functions
double Limit (double Lo, double Value, double Hi)
void DrawPoint (wxDC &dc, const wxRect &r, int x, int y, bool top)
TODO: This should probably move to track artist.
void checkResult (int n, double a, double b)
Define Documentation
#define SQR (X) ((X)*(X))
Referenced by Envelope::HandleMouseButtonDown().
Function Documentation
void checkResult (int n, double a, double b)
Referenced by Envelope::testMe().
void DrawPoint (wxDC & dc, const wxRect & r, int x, int y, bool top)
TODO: This should probably move to track artist.
Referenced by Envelope::DrawPoints().
double Limit (double Lo, double Value, double Hi)
Limit() limits a double value to a range. TODO: Move to a general utilities source file.
Referenced by Envelope::CollapseRegion(), Envelope::MoveDraggedPoint(), and Envelope::toDB().