Audacity: ExportMP2.cpp File Reference
ExportMP2.cpp File Reference
#include "../Audacity.h"
#include <wx/defs.h>
#include <wx/textctrl.h>
#include <wx/dynlib.h>
#include <wx/msgdlg.h>
#include <wx/utils.h>
#include <wx/timer.h>
#include <wx/window.h>
#include <wx/log.h>
#include <wx/intl.h>
#include "Export.h"
#include "../FileIO.h"
#include "../Internat.h"
#include "../Mix.h"
#include "../Prefs.h"
#include "../Project.h"
#include "../Tags.h"
#include "../WaveTrack.h"
#include "twolame.h"
#include <id3tag.h>
Classes
class ExportMP2Options
class ExportMP2
Defines
#define LIBTWOLAME_STATIC
Functions
struct id3_frame * id3_frame_new (char const *)
id3_length_t id3_latin1_length (id3_latin1_t const *)
void id3_latin1_decode (id3_latin1_t const *, id3_ucs4_t *)
ExportPlugin * New_ExportMP2 ()
Variables
static int iBitrates []
Define Documentation
#define LIBTWOLAME_STATIC
Function Documentation
struct id3_frame* id3_frame_new (char const *) [read]
Referenced by ExportPCM::AddID3Chunk(), ExportMP3::AddTags(), and ExportMP2::AddTags().
void id3_latin1_decode (id3_latin1_t const * , id3_ucs4_t *)
id3_length_t id3_latin1_length (id3_latin1_t const *)
ExportPlugin* New_ExportMP2 ()
Referenced by Exporter::Exporter().
Variable Documentation
int iBitrates[] [static]
Initial value:
 {
   16, 24, 32, 40, 48, 56, 64,
   80, 96, 112, 128, 160,
   192, 224, 256, 320, 384
}
Referenced by ExportMP2Options::ExportMP2Options().