Audacity: ExportMP3.h File Reference
ExportMP3.h File Reference
Functions
ExportPlugin * New_ExportMP3 ()
wxString GetMP3Version (wxWindow *parent, bool prompt)
Function Documentation
wxString GetMP3Version (wxWindow * parent, bool prompt)
References MP3Exporter::FindLibrary(), MP3Exporter::GetLibraryVersion(), MP3Exporter::LoadLibrary(), MP3Exporter::No, and MP3Exporter::Yes.
Referenced by LibraryPrefs::SetMP3VersionText().
ExportPlugin* New_ExportMP3 ()
Referenced by Exporter::Exporter().