Audacity: FFmpeg.h File Reference
FFmpeg.h File Reference
#include <errno.h>
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libavutil/fifo.h>
#include "Audacity.h"
#include <wx/string.h>
#include <wx/dynlib.h>
#include <wx/log.h>
#include <wx/msgdlg.h>
#include <wx/utils.h>
#include "../widgets/LinkingHtmlWindow.h"
#include "FileDialog.h"
#include "ShuttleGui.h"
#include "../Prefs.h"
#include <wx/checkbox.h>
#include <wx/textctrl.h>
Classes
class FFmpegNotFoundDialog
class FFmpegLibs
Class used to dynamically load FFmpeg libraries.
Defines
#define __AUDACITY_FFMPEG__
#define INITDYN(w, f) if ((*(void**)&this->f=(void*)w->GetSymbol(wxT(#f))) == NULL) { wxLogMessage(wxT("Failed to load symbol ") wxT(#f)); return false; };
#define FFMPEG_STABLE 0
Functions
void av_log_wx_callback (void *ptr, int level, const char *fmt, va_list vl)
wxString GetFFmpegVersion (wxWindow *parent)
int ufile_fopen (ByteIOContext **s, const wxString &name, int flags)
void FFmpegStartup ()
bool LoadFFmpeg (bool showerror)
FFmpegLibs * PickFFmpegLibs ()
void DropFFmpegLibs ()
int ufile_fopen_input (AVFormatContext **ic_ptr, wxString &name)
Define Documentation
#define __AUDACITY_FFMPEG__
Describes shared object that is used to access FFmpeg libraries.
#define FFMPEG_STABLE 0
#define INITDYN (w, f) if ((*(void**)&this->f=(void*)w->GetSymbol(wxT(#f))) == NULL) { wxLogMessage(wxT("Failed to load symbol ") wxT(#f)); return false; };
Referenced by FFmpegLibs::InitLibs().
Function Documentation
void av_log_wx_callback (void * ptr, int level, const char * fmt, va_list vl)
Callback function to catch FFmpeg log messages. Uses wxLogMessage.
Referenced by FFmpegImportFileHandle::Init(), and ExportFFmpeg::Init().
void DropFFmpegLibs ()
! Helper function - destroys FFmpegLibs object if there is no need for it anymore, or just decrements it's reference count
References FFmpegLibs::refcount.
Referenced by CheckFFmpegPresence(), ExportFFmpeg::Destroy(), GetFFmpegVersion(), LoadFFmpeg(), AudacityApp::OnExit(), LibraryPrefs::OnFFmpegFindButton(), ExportFFmpegOptions::~ExportFFmpegOptions(), and FFmpegImportFileHandle::~FFmpegImportFileHandle().
void FFmpegStartup ()
Called during Audacity start-up to try and load the ffmpeg libraries
References gPrefs, and LoadFFmpeg().
Referenced by AudacityApp::OnInit().
wxString GetFFmpegVersion (wxWindow * parent)
References DropFFmpegLibs(), FFmpegLibs::GetLibraryVersion(), PickFFmpegLibs(), and FFmpegLibs::ValidLibsLoaded().
Referenced by LibraryPrefs::SetFFmpegVersionText().
bool LoadFFmpeg (bool showerror)
References DropFFmpegLibs(), gPrefs, FFmpegLibs::LoadLibs(), PickFFmpegLibs(), and FFmpegLibs::ValidLibsLoaded().
Referenced by FFmpegStartup(), and LibraryPrefs::OnFFmpegFindButton().
FFmpegLibs* PickFFmpegLibs ()
! Helper function - creates FFmpegLibs object if it does not exists or just increments reference count if it does It is usually called by constructors or initializators
References FFmpegLibs::refcount.
Referenced by CheckFFmpegPresence(), ExportFFmpeg::ExportFFmpeg(), ExportFFmpegOptions::ExportFFmpegOptions(), FFmpegImportFileHandle::FFmpegImportFileHandle(), GetFFmpegVersion(), LoadFFmpeg(), and LibraryPrefs::OnFFmpegFindButton().
int ufile_fopen (ByteIOContext ** s, const wxString & name, int flags)
References FFmpegLibs::url_close, FFmpegLibs::url_fdopen, and FFmpegLibs::url_open_protocol.
Referenced by ExportFFmpeg::Init(), and ufile_fopen_input().
int ufile_fopen_input (AVFormatContext ** ic_ptr, wxString & name)
References FFmpegLibs::av_freep, FFmpegLibs::av_iformat_next, FFmpegLibs::av_malloc, FFmpegLibs::av_open_input_stream, FFmpegLibs::get_buffer, FFmpegLibs::match_ext, PROBE_BUF_MAX, PROBE_BUF_MIN, ufile_fopen(), FFmpegLibs::url_fclose, and FFmpegLibs::url_fseek.
Referenced by FFmpegImportFileHandle::Init().