Audacity: FFT.cpp File Reference
FFT.cpp File Reference
Fast Fourier Transform routines.
#include <wx/intl.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "FFT.h"
#include "RealFFTf.h"
Functions
static int IsPowerOfTwo (int x)
static int NumberOfBitsNeeded (int PowerOfTwo)
static int ReverseBits (int index, int NumBits)
static void InitFFT ()
void DeinitFFT ()
int FastReverseBits (int i, int NumBits)
void FFT (int NumSamples, bool InverseTransform, float *RealIn, float *ImagIn, float *RealOut, float *ImagOut)
void RealFFT (int NumSamples, float *RealIn, float *RealOut, float *ImagOut)
void InverseRealFFT (int NumSamples, float *RealIn, float *ImagIn, float *RealOut)
void PowerSpectrum (int NumSamples, float *In, float *Out)
int NumWindowFuncs ()
const wxChar * WindowFuncName (int whichFunction)
void WindowFunc (int whichFunction, int NumSamples, float *in)
Variables
int ** gFFTBitTable = NULL
const int MaxFastBits = 16
Detailed Description
Fast Fourier Transform routines.
This file contains a few FFT routines, including a real-FFT routine that is almost twice as fast as a normal complex FFT, and a power spectrum routine when you know you don't care about phase information.
Some of this code was based on a free implementation of an FFT by Don Cross, available on the web at:
http://www.intersrv.com/~dcross/fft.html
The basic algorithm for his code was based on Numerican Recipes in Fortran. I optimized his code further by reducing array accesses, caching the bit reversal table, and eliminating float-to-double conversions, and I added the routines to calculate a real FFT and a real power spectrum.
Function Documentation
void DeinitFFT ()
References CleanupFFT(), gFFTBitTable, and MaxFastBits.
Referenced by AudacityApp::OnExit().
int FastReverseBits (int i, int NumBits) [inline]
References gFFTBitTable, MaxFastBits, and ReverseBits().
Referenced by FFT().
void FFT (int NumSamples, bool InverseTransform, float * RealIn, float * ImagIn, float * RealOut, float * ImagOut)
References FastReverseBits(), gFFTBitTable, InitFFT(), IsPowerOfTwo(), M_PI, and NumberOfBitsNeeded().
Referenced by EqualizationDialog::CalcFilter(), ComputeSpectrum(), PowerSpectrum(), RealFFT(), FreqWindow::Recalc(), and EqualizationPanel::Recalc().
void InitFFT () [static]
References gFFTBitTable, MaxFastBits, and ReverseBits().
Referenced by FFT().
void InverseRealFFT (int NumSamples, float * RealIn, float * ImagIn, float * RealOut)
References GetFFT(), HFFT, InverseRealFFTf(), ReleaseFFT(), and ReorderToTime().
Referenced by EqualizationDialog::CalcFilter(), FreqWindow::Recalc(), and EqualizationPanel::Recalc().
int IsPowerOfTwo (int x) [static]
Referenced by FFT().
int NumberOfBitsNeeded (int PowerOfTwo) [static]
Referenced by FFT().
int NumWindowFuncs ()
Referenced by FreqWindow::FreqWindow(), SpectrumPrefs::Populate(), and FreqWindow::Recalc().
void PowerSpectrum (int NumSamples, float * In, float * Out)
References FFT(), GetFFT(), HFFT, M_PI, RealFFTf(), and ReleaseFFT().
Referenced by ComputeSpectrum(), and FreqWindow::Recalc().
void RealFFT (int NumSamples, float * RealIn, float * RealOut, float * ImagOut)
References FFT(), GetFFT(), HFFT, M_PI, RealFFTf(), and ReleaseFFT().
Referenced by EqualizationDialog::CalcFilter(), ComputeSpectrum(), and FreqWindow::Recalc().
int ReverseBits (int index, int NumBits) [static]
Referenced by FastReverseBits(), and InitFFT().
void WindowFunc (int whichFunction, int NumSamples, float * in)
References M_PI.
Referenced by ComputeSpectrum(), WaveClip::GetSpectrogram(), and FreqWindow::Recalc().
const wxChar* WindowFuncName (int whichFunction)
Referenced by FreqWindow::FreqWindow(), and SpectrumPrefs::Populate().
Variable Documentation
int** gFFTBitTable = NULL
Referenced by DeinitFFT(), FastReverseBits(), FFT(), and InitFFT().
const int MaxFastBits = 16
Referenced by DeinitFFT(), FastReverseBits(), and InitFFT().