Audacity: HelpText.h File Reference
HelpText.h File Reference
Functions
wxString HelpText (const wxString &Key)
wxString TitleText (const wxString &Key)
Function Documentation
wxString HelpText (const wxString & Key)
References HelpTextBuiltIn(), LinkExpand(), and WrapText().
Referenced by ErrorDialog::OnHelp(), LinkingHtmlWindow::OnLinkClicked(), SplashDialog::Populate(), SplashDialog::Show2(), and ShowHelpDialog().
wxString TitleText (const wxString & Key)
Referenced by ErrorDialog::OnHelp(), and LinkingHtmlWindow::OnLinkClicked().