Audacity: HelpText.cpp File Reference
HelpText.cpp File Reference
Given a key, returns some html.
#include <wx/string.h>
#include <wx/intl.h>
#include "Audacity.h"
#include "HelpText.h"
#include "FileNames.h"
Functions
wxString WrapText (const wxString &Text)
wxString Link (const wxString &Key, const wxString &Text)
wxString WikiLink (const wxString &Key, const wxString &Text)
wxString FileLink (const wxString &Key, const wxString &Text)
wxString HttpLink (const wxString &Key, const wxString &Text)
wxString LinkExpand (const wxString &Text)
wxString TitleText (const wxString &Key)
wxString HelpTextBuiltIn (const wxString &Key)
wxString HelpText (const wxString &Key)
Detailed Description
Given a key, returns some html.
Function Documentation
wxString FileLink (const wxString & Key, const wxString & Text)
References FileNames::HtmlHelpDir().
Referenced by LinkExpand().
wxString HelpText (const wxString & Key)
References HelpTextBuiltIn(), LinkExpand(), and WrapText().
Referenced by ErrorDialog::OnHelp(), LinkingHtmlWindow::OnLinkClicked(), SplashDialog::Populate(), SplashDialog::Show2(), and ShowHelpDialog().
wxString HelpTextBuiltIn (const wxString & Key)
References AUDACITY_VERSION_STRING, and WrapText().
Referenced by HelpText().
wxString HttpLink (const wxString & Key, const wxString & Text)
Referenced by LinkExpand().
wxString Link (const wxString & Key, const wxString & Text)
Referenced by LinkExpand().
wxString LinkExpand (const wxString & Text)
References FileLink(), HttpLink(), Link(), and WikiLink().
Referenced by HelpText().
wxString TitleText (const wxString & Key)
Referenced by ErrorDialog::OnHelp(), and LinkingHtmlWindow::OnLinkClicked().
wxString WikiLink (const wxString & Key, const wxString & Text)
Referenced by LinkExpand().
wxString WrapText (const wxString & Text)
Referenced by HelpText(), and HelpTextBuiltIn().