Audacity: ImportRaw.h File Reference
ImportRaw.h File Reference
#include "Import.h"
Functions
int ImportRaw (wxWindow *parent, wxString fileName, TrackFactory *trackFactory, Track ***outTracks)
Function Documentation
int ImportRaw (wxWindow * parent, wxString fileName, TrackFactory * trackFactory, Track *** outTracks)
References WaveTrack::Append(), channels, eProgressCancelled, eProgressFailed, eProgressSuccess, floatSample, WaveTrack::GetMaxBlockSize(), gPrefs, int16Sample, Track::LeftChannel, ImportRawDialog::mChannels, ImportRawDialog::mEncoding, ImportRawDialog::mOffset, Track::MonoChannel, ImportRawDialog::mPercent, ImportRawDialog::mRate, NewSamples(), TrackFactory::NewWaveTrack(), RawAudioGuess(), Track::RightChannel, Track::SetChannel(), Track::SetLinked(), sf_subtype_more_than_16_bits(), and ProgressDialog::Update().
Referenced by AudacityProject::OnImportRaw().