Audacity: ImportRaw.cpp File Reference
ImportRaw.cpp File Reference
Functions for guessing audio type and attempting to read from unknown sample audio data. Implements ImportRawDialog.
#include "../Audacity.h"
#include "ImportRaw.h"
#include "Import.h"
#include "RawAudioGuess.h"
#include "../DirManager.h"
#include "../FileFormats.h"
#include "../Internat.h"
#include "../Prefs.h"
#include "../ShuttleGui.h"
#include "../WaveTrack.h"
#include <math.h>
#include <wx/defs.h>
#include <wx/button.h>
#include <wx/choice.h>
#include <wx/intl.h>
#include <wx/msgdlg.h>
#include <wx/panel.h>
#include <wx/progdlg.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/timer.h>
#include "sndfile.h"
Classes
class ImportRawDialog
ImportRawDialog prompts you with options such as endianness and sample size to help you importing data of an unknown format.
Enumerations
enum { ChoiceID = 9000, PlayID }
Functions
int ImportRaw (wxWindow *parent, wxString fileName, TrackFactory *trackFactory, Track ***outTracks)
Detailed Description
Functions for guessing audio type and attempting to read from unknown sample audio data. Implements ImportRawDialog.
Enumeration Type Documentation
anonymous enum
Enumerator:
ChoiceID
PlayID
Function Documentation
int ImportRaw (wxWindow * parent, wxString fileName, TrackFactory * trackFactory, Track *** outTracks)
References WaveTrack::Append(), channels, eProgressCancelled, eProgressFailed, eProgressSuccess, floatSample, WaveTrack::GetMaxBlockSize(), gPrefs, int16Sample, Track::LeftChannel, ImportRawDialog::mChannels, ImportRawDialog::mEncoding, ImportRawDialog::mOffset, Track::MonoChannel, ImportRawDialog::mPercent, ImportRawDialog::mRate, NewSamples(), TrackFactory::NewWaveTrack(), RawAudioGuess(), Track::RightChannel, Track::SetChannel(), Track::SetLinked(), sf_subtype_more_than_16_bits(), and ProgressDialog::Update().
Referenced by AudacityProject::OnImportRaw().