Audacity: ImportMP3.cpp File Reference
ImportMP3.cpp File Reference
#include <wx/wxprec.h>
#include <wx/window.h>
#include <wx/defs.h>
#include <wx/intl.h>
#include "../Audacity.h"
#include "../Prefs.h"
#include "Import.h"
#include "ImportMP3.h"
#include "ImportPlugin.h"
#include "../Internat.h"
#include "../Tags.h"
#include <wx/textctrl.h>
#include <wx/file.h>
#include <wx/thread.h>
#include <wx/msgdlg.h>
#include <wx/progdlg.h>
#include <wx/string.h>
#include <wx/timer.h>
#include "mad.h"
#include <id3tag.h>
#include "../WaveTrack.h"
Classes
struct private_data
class MP3ImportPlugin
An ImportPlugin for MP3 data.
class MP3ImportFileHandle
An ImportFileHandle for MP3 data.
Defines
#define DESC _("MP3 files")
#define INPUT_BUFFER_SIZE 65535
#define PROGRESS_SCALING_FACTOR 100000
Functions
void GetMP3ImportPlugin (ImportPluginList *importPluginList, UnusableImportPluginList *unusableImportPluginList)
enum mad_flow input_cb (void *_data, struct mad_stream *stream)
enum mad_flow output_cb (void *_data, struct mad_header const *header, struct mad_pcm *pcm)
enum mad_flow error_cb (void *_data, struct mad_stream *stream, struct mad_frame *frame)
float scale (mad_fixed_t sample)
Variables
static const wxChar * exts []
Define Documentation
#define DESC _("MP3 files")
#define INPUT_BUFFER_SIZE 65535
Referenced by MP3ImportFileHandle::Import(), and input_cb().
#define PROGRESS_SCALING_FACTOR 100000
Function Documentation
enum mad_flow error_cb (void * _data, struct mad_stream * stream, struct mad_frame * frame)
References MAD_FLOW_CONTINUE.
Referenced by MP3ImportFileHandle::Import().
void GetMP3ImportPlugin (ImportPluginList * importPluginList, UnusableImportPluginList * unusableImportPluginList)
Referenced by Importer::Importer().
enum mad_flow input_cb (void * _data, struct mad_stream * stream)
References eProgressSuccess, private_data::file, private_data::id3checked, INPUT_BUFFER_SIZE, private_data::inputBuffer, MAD_FLOW_CONTINUE, MAD_FLOW_STOP, mad_stream_buffer(), mad_stream::next_frame, private_data::progress, ProgressDialog::Update(), and private_data::updateResult.
Referenced by MP3ImportFileHandle::Import().
enum mad_flow output_cb (void * _data, struct mad_header const * header, struct mad_pcm * pcm)
References WaveTrack::Append(), private_data::channels, mad_pcm::channels, channels, floatSample, gPrefs, Track::LeftChannel, mad_pcm::length, MAD_FLOW_CONTINUE, Track::MonoChannel, TrackFactory::NewWaveTrack(), private_data::numChannels, Track::RightChannel, mad_pcm::samplerate, mad_pcm::samples, scale(), Track::SetChannel(), Track::SetLinked(), and private_data::trackFactory.
Referenced by MP3ImportFileHandle::Import().
float scale (mad_fixed_t sample) [inline]
References MAD_F_FRACBITS.
Referenced by TrackArtist::DrawClipSpectrum(), EqualizationPanel::OnPaint(), AudacityPrintout::OnPrintPage(), output_cb(), FreqWindow::Recalc(), and Ruler::Update().
Variable Documentation
const wxChar* exts[] [static]
Initial value:
{
   wxT("mp3"),
   wxT("mp2"),
   wxT("mpa")
}