Audacity: InterpolateAudio.h File Reference
InterpolateAudio.h File Reference
#include "Audacity.h"
Functions
void AUDACITY_DLL_API InterpolateAudio (float *buffer, int len, int firstBad, int numBad)
Function Documentation
void AUDACITY_DLL_API InterpolateAudio (float * buffer, int len, int firstBad, int numBad)
References Matrix::Cols(), imax(), imin(), InterpolateAudio(), InvertMatrix(), LinearInterpolateAudio(), MatrixConcatenateCols(), MatrixMultiply(), MatrixSubset(), Matrix::Rows(), TransposeMatrix(), VectorConcatenate(), and VectorSubset().
Referenced by InterpolateAudio(), and EffectRepair::ProcessOne().