Audacity: Legacy.h File Reference
Legacy.h File Reference
#include <wx/defs.h>
#include <wx/filename.h>
Functions
bool ConvertLegacyProjectFile (wxFileName filename)
Function Documentation
bool ConvertLegacyProjectFile (wxFileName filename)
References AUDACITY_VERSION_STRING, XMLFileWriter::Close(), ConvertLegacyTrack(), XMLWriter::EndTag(), label, name, XMLFileWriter::Open(), XMLWriter::StartTag(), XMLFileWriter::Write(), and XMLWriter::WriteAttr().
Referenced by AudacityProject::OpenFile().