Audacity: LinkingHtmlWindow.h File Reference
LinkingHtmlWindow.h File Reference
#include <wx/dialog.h>
#include <wx/html/htmlwin.h>
#include <wx/frame.h>
#include "HtmlWindow.h"
Classes
class LinkingHtmlWindow
class BrowserFrame
Functions
void OpenInDefaultBrowser (const wxHtmlLinkInfo &link)
Function Documentation
void OpenInDefaultBrowser (const wxHtmlLinkInfo & link)
Referenced by FindFFmpegDialog::OnDownload(), FindDialog::OnDownload(), LibraryPrefs::OnFFmpegDownButton(), ContrastDialog::OnGetURL(), ErrorDialog::OnHelp(), LinkingHtmlWindow::OnLinkClicked(), LibraryPrefs::OnMP3DownButton(), and ShowHelpDialog().