Audacity: LoadLadspa.cpp File Reference
LoadLadspa.cpp File Reference
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <map>
#include <queue>
#include <wx/dynlib.h>
#include <wx/filename.h>
#include <wx/hashmap.h>
#include <wx/list.h>
#include <wx/log.h>
#include <wx/string.h>
#include "ladspa.h"
#include "../../Audacity.h"
#include "../../AudacityApp.h"
#include "../../Experimental.h"
#include "../../Internat.h"
#include "../EffectManager.h"
#include "LadspaEffect.h"
Defines
#define descriptorFnName "ladspa_descriptor"
Functions
WX_DEFINE_ARRAY (wxDynamicLibrary *, DL_Array)
static void LoadLadspaEffect (wxSortedArrayString &uniq, wxString fname, DL_Array &dls)
void LoadLadspaPlugins ()
void UnloadLadspaPlugins ()
Variables
static DL_Array ladspa_dls
Define Documentation
#define descriptorFnName "ladspa_descriptor"
Referenced by LoadLadspaEffect().
Function Documentation
static void LoadLadspaEffect (wxSortedArrayString & uniq, wxString fname, DL_Array & dls) [static]
References descriptorFnName, EffectManager::Get(), _LADSPA_Descriptor::Label, LAT1CTOWX, EffectManager::RegisterEffect(), and _LADSPA_Descriptor::UniqueID.
Referenced by LoadLadspaPlugins().
void LoadLadspaPlugins ()
References AudacityApp::AddMultiPathsToPathList(), AudacityApp::AddUniquePathToPathList(), AudacityApp::audacityPathList, AudacityApp::FindFilesInPathList(), EffectManager::Get(), INSTALL_PREFIX, label, ladspa_dls, LoadLadspaEffect(), and wxGetApp().
Referenced by LoadEffects().
void UnloadLadspaPlugins ()
References ladspa_dls.
Referenced by UnloadEffects().
WX_DEFINE_ARRAY (wxDynamicLibrary * , DL_Array)
Variable Documentation
DL_Array ladspa_dls [static]
Referenced by LoadLadspaPlugins(), and UnloadLadspaPlugins().