Audacity: LoadModules.h File Reference
LoadModules.h File Reference
#include <wx/dynlib.h>
#include <wx/module.h>
Classes
class Module
class ModuleManager
Defines
#define ModuleDispatchName "ModuleDispatch"
Typedefs
typedef int(* fnModuleDispatch)(ModuleDispatchTypes type)
Enumerations
enum ModuleDispatchTypes {
ModuleInitialize, ModuleTerminate, AppInitialized, AppQuiting,
ProjectInitialized, ProjectClosing, MenusRebuilt
}
Functions
void LoadModules (CommandHandler &cmdHandler)
void LoadModule (wxString fname)
wxWindow * MakeHijackPanel ()
Define Documentation
#define ModuleDispatchName "ModuleDispatch"
Referenced by Module::Load().
Typedef Documentation
typedef int(* fnModuleDispatch)(ModuleDispatchTypes type)
Enumeration Type Documentation
enum ModuleDispatchTypes
Enumerator:
ModuleInitialize
ModuleTerminate
AppInitialized
AppQuiting
ProjectInitialized
ProjectClosing
MenusRebuilt
Function Documentation
void LoadModule (wxString fname)
References AUDACITY_VERSION_STRING, initFnName, mainPanelFnName, pPanelHijack, scriptFn, scriptFnName, and versionFnName.
Referenced by LoadModules().
void LoadModules (CommandHandler & cmdHandler)
References AudacityApp::AddMultiPathsToPathList(), AudacityApp::AddUniquePathToPathList(), AudacityApp::audacityPathList, AudacityApp::FindFilesInPathList(), INSTALL_PREFIX, LoadModule(), ScriptCommandRelay::Run(), scriptFn, ScriptCommandRelay::SetCommandHandler(), ScriptCommandRelay::SetRegScriptServerFunc(), and wxGetApp().
Referenced by AudacityApp::OnInit().
wxWindow* MakeHijackPanel ()
IF pPanelHijack has been found in a module DLL THEN when this function is called we'll go and create that window instead of the normal one.
References pPanelHijack.
Referenced by AudacityApp::OnInit().