Audacity: LoadModules.cpp File Reference
LoadModules.cpp File Reference
Based on LoadLadspa, this code loads pluggable Audacity extension modules. It also has the code to (a) invoke a script server and (b) invoke a function returning a replacement window, i.e. an alternative to the usual interface, for Audacity.
#include <wx/dynlib.h>
#include <wx/list.h>
#include <wx/log.h>
#include <wx/string.h>
#include "Audacity.h"
#include "AudacityApp.h"
#include "Internat.h"
#include "commands/ScriptCommandRelay.h"
#include <NonGuiThread.h>
#include "LoadModules.h"
Defines
#define initFnName "ExtensionModuleInit"
#define versionFnName "GetVersionString"
#define scriptFnName "RegScriptServerFunc"
#define mainPanelFnName "MainPanelFunc"
Typedefs
typedef wxWindow * pwxWindow
typedef int(* tModuleInit)(int)
typedef wxString(* tVersionFn)()
typedef pwxWindow(* tPanelFn)(int)
Functions
wxWindow * MakeHijackPanel ()
void LoadModule (wxString fname)
void LoadModules (CommandHandler &cmdHandler)
IMPLEMENT_DYNAMIC_CLASS (ModuleManager, wxModule)
Variables
tPanelFn pPanelHijack = NULL
tpRegScriptServerFunc scriptFn
Detailed Description
Based on LoadLadspa, this code loads pluggable Audacity extension modules. It also has the code to (a) invoke a script server and (b) invoke a function returning a replacement window, i.e. an alternative to the usual interface, for Audacity.
Define Documentation
#define initFnName "ExtensionModuleInit"
Referenced by LoadModule().
#define mainPanelFnName "MainPanelFunc"
Referenced by LoadModule().
#define scriptFnName "RegScriptServerFunc"
Referenced by LoadModule().
#define versionFnName "GetVersionString"
Referenced by LoadModule().
Typedef Documentation
typedef wxWindow* pwxWindow
typedef int(* tModuleInit)(int)
typedef pwxWindow(* tPanelFn)(int)
typedef wxString(* tVersionFn)()
Function Documentation
IMPLEMENT_DYNAMIC_CLASS (ModuleManager , wxModule)
void LoadModule (wxString fname)
References AUDACITY_VERSION_STRING, initFnName, mainPanelFnName, pPanelHijack, scriptFn, scriptFnName, and versionFnName.
Referenced by LoadModules().
void LoadModules (CommandHandler & cmdHandler)
References AudacityApp::AddMultiPathsToPathList(), AudacityApp::AddUniquePathToPathList(), AudacityApp::audacityPathList, AudacityApp::FindFilesInPathList(), INSTALL_PREFIX, LoadModule(), ScriptCommandRelay::Run(), scriptFn, ScriptCommandRelay::SetCommandHandler(), ScriptCommandRelay::SetRegScriptServerFunc(), and wxGetApp().
Referenced by AudacityApp::OnInit().
wxWindow* MakeHijackPanel ()
IF pPanelHijack has been found in a module DLL THEN when this function is called we'll go and create that window instead of the normal one.
References pPanelHijack.
Referenced by AudacityApp::OnInit().
Variable Documentation
tPanelFn pPanelHijack = NULL
Referenced by LoadModule(), and MakeHijackPanel().
tpRegScriptServerFunc scriptFn
Referenced by LoadModule(), and LoadModules().