Audacity: LoadLadspa.h File Reference
LoadLadspa.h File Reference
Functions
void LoadLadspaPlugins ()
void UnloadLadspaPlugins ()
Function Documentation
void LoadLadspaPlugins ()
References AudacityApp::AddMultiPathsToPathList(), AudacityApp::AddUniquePathToPathList(), AudacityApp::audacityPathList, AudacityApp::FindFilesInPathList(), EffectManager::Get(), INSTALL_PREFIX, label, ladspa_dls, LoadLadspaEffect(), and wxGetApp().
void UnloadLadspaPlugins ()
References ladspa_dls.
Referenced by UnloadEffects().