Audacity: Matrix.cpp File Reference
Matrix.cpp File Reference
#include <stdlib.h>
#include <math.h>
#include <wx/defs.h>
#include "Matrix.h"
Functions
Matrix IdentityMatrix (int N)
Vector operator+ (const Vector &left, const Vector &right)
Vector operator- (const Vector &left, const Vector &right)
Vector operator* (const Vector &left, const Vector &right)
Vector operator* (const Vector &left, double right)
Vector VectorSubset (const Vector &other, int start, int len)
Vector VectorConcatenate (const Vector &left, const Vector &right)
Vector operator* (const Vector &left, const Matrix &right)
Vector operator* (const Matrix &left, const Vector &right)
Matrix operator+ (const Matrix &left, const Matrix &right)
Matrix operator* (const Matrix &left, const double right)
Matrix ScalarMultiply (const Matrix &left, const Matrix &right)
Matrix MatrixMultiply (const Matrix &left, const Matrix &right)
Matrix MatrixSubset (const Matrix &input, int startRow, int numRows, int startCol, int numCols)
Matrix MatrixConcatenateCols (const Matrix &left, const Matrix &right)
Matrix TransposeMatrix (const Matrix &other)
bool InvertMatrix (const Matrix &input, Matrix &Minv)
Function Documentation
Matrix IdentityMatrix (int N)
Referenced by InvertMatrix().
bool InvertMatrix (const Matrix & input, Matrix & Minv)
References Matrix::Cols(), IdentityMatrix(), Matrix::Rows(), and Matrix::SwapRows().
Referenced by InterpolateAudio().
Matrix MatrixConcatenateCols (const Matrix & left, const Matrix & right)
References Matrix::Cols(), and Matrix::Rows().
Referenced by InterpolateAudio().
Matrix MatrixMultiply (const Matrix & left, const Matrix & right)
References Matrix::Cols(), and Matrix::Rows().
Referenced by InterpolateAudio().
Matrix MatrixSubset (const Matrix & input, int startRow, int numRows, int startCol, int numCols)
Referenced by InterpolateAudio().
Matrix operator* (const Matrix & left, const double right)
References Matrix::Cols(), and Matrix::Rows().
Vector operator* (const Matrix & left, const Vector & right)
References Matrix::Cols(), Vector::Len(), and Matrix::Rows().
Vector operator* (const Vector & left, const Matrix & right)
References Matrix::Cols(), Vector::Len(), and Matrix::Rows().
Vector operator* (const Vector & left, double right)
References Vector::Len().
Vector operator* (const Vector & left, const Vector & right)
References Vector::Len().
Matrix operator+ (const Matrix & left, const Matrix & right)
References Matrix::Cols(), and Matrix::Rows().
Vector operator+ (const Vector & left, const Vector & right)
References Vector::Len().
Vector operator- (const Vector & left, const Vector & right)
References Vector::Len().
Matrix ScalarMultiply (const Matrix & left, const Matrix & right)
References Matrix::Cols(), and Matrix::Rows().
Matrix TransposeMatrix (const Matrix & other)
References Matrix::Cols(), and Matrix::Rows().
Referenced by InterpolateAudio().
Vector VectorConcatenate (const Vector & left, const Vector & right)
References Vector::Len().
Referenced by InterpolateAudio().
Vector VectorSubset (const Vector & other, int start, int len)
Referenced by InterpolateAudio().