Audacity: Meter.cpp File Reference
Meter.cpp File Reference
#include "../Audacity.h"
#include "../AudacityApp.h"
#include <wx/defs.h>
#include <wx/dcmemory.h>
#include <wx/image.h>
#include <wx/intl.h>
#include <wx/menu.h>
#include <wx/settings.h>
#include <wx/textdlg.h>
#include <wx/numdlg.h>
#include <wx/tooltip.h>
#include <wx/msgdlg.h>
#include <math.h>
#include "Meter.h"
#include "../AudioIO.h"
#include "../AColor.h"
#include "../ImageManipulation.h"
#include "../Project.h"
#include "../toolbars/MeterToolBar.h"
#include "../toolbars/ControlToolBar.h"
#include "../Prefs.h"
#include "../Theme.h"
#include "../AllThemeResources.h"
#include "../Experimental.h"
Enumerations
enum {
OnMeterUpdateID = 6000, OnDisableMeterID, OnMonitorID, OnHorizontalID,
OnAutomatedInputLevelAdjustmentID, OnVerticalID, OnMultiID, OnEqualizerID,
OnWaveformID, OnLinearID, OnDBID, OnClipID,
OnFloatID, OnPreferencesID
}
Functions
static float floatMax (float a, float b)
static int intmin (int a, int b)
static int intmax (int a, int b)
static float ClipZeroToOne (float z)
static float ToDB (float v, float range)
Enumeration Type Documentation
anonymous enum
Enumerator:
OnMeterUpdateID
OnDisableMeterID
OnMonitorID
OnHorizontalID
OnAutomatedInputLevelAdjustmentID
OnVerticalID
OnMultiID
OnEqualizerID
OnWaveformID
OnLinearID
OnDBID
OnClipID
OnFloatID
OnPreferencesID
Function Documentation
static float ClipZeroToOne (float z) [static]
Referenced by ToDB().
static float floatMax (float a, float b) [static]
Referenced by Meter::OnMeterUpdate(), and Meter::UpdateDisplay().
static int intmax (int a, int b) [static]
Referenced by Meter::HandleLayout().
static int intmin (int a, int b) [static]
Referenced by Meter::HandleLayout(), and Meter::UpdateDisplay().
static float ToDB (float v, float range) [static]
References ClipZeroToOne().
Referenced by Meter::UpdateDisplay().