Audacity: Mix.cpp File Reference
Mix.cpp File Reference
#include "Audacity.h"
#include "Mix.h"
#include <math.h>
#include <wx/textctrl.h>
#include <wx/msgdlg.h>
#include <wx/progdlg.h>
#include <wx/timer.h>
#include <wx/intl.h>
#include "WaveTrack.h"
#include "DirManager.h"
#include "Envelope.h"
#include "Internat.h"
#include "Prefs.h"
#include "Project.h"
#include "Resample.h"
#include "float_cast.h"
Functions
bool MixAndRender (TrackList *tracks, TrackFactory *trackFactory, double rate, sampleFormat format, double startTime, double endTime, WaveTrack **newLeft, WaveTrack **newRight)
void MixBuffers (int numChannels, int *channelFlags, float *gains, samplePtr src, samplePtr *dests, int len, bool interleaved)
Function Documentation
bool MixAndRender (TrackList * tracks, TrackFactory * trackFactory, double rate, sampleFormat format, double startTime, double endTime, WaveTrack ** newLeft, WaveTrack ** newRight)
References WaveTrack::Append(), eProgressCancelled, eProgressFailed, eProgressStopped, eProgressSuccess, TrackListIterator::First(), WaveTrack::Flush(), Mixer::GetBuffer(), Track::GetChannel(), Track::GetEndTime(), WaveTrack::GetIdealBlockSize(), Track::GetKind(), Track::GetSelected(), TrackList::GetTimeTrack(), Track::LeftChannel, Mixer::MixGetCurrentTime(), Track::MonoChannel, TrackFactory::NewWaveTrack(), TrackListIterator::Next(), Mixer::Process(), Track::RightChannel, Track::SetChannel(), Track::SetLinked(), Track::SetName(), ProgressDialog::Update(), and Track::Wave.
Referenced by AudacityProject::HandleMixAndRender(), and Effect::Preview().
void MixBuffers (int numChannels, int * channelFlags, float * gains, samplePtr src, samplePtr * dests, int len, bool interleaved)
References floatSample, and SAMPLE_SIZE.
Referenced by Mixer::MixSameRate(), and Mixer::MixVariableRates().