Audacity: Mix.h File Reference
Mix.h File Reference
#include <wx/string.h>
#include "SampleFormat.h"
#include "WaveTrack.h"
#include "TimeTrack.h"
#include "Resample.h"
Classes
class MixerSpec
Class used with Mixer.
class Mixer
Functions for doing the mixdown of the tracks.
Functions
bool MixAndRender (TrackList *tracks, TrackFactory *factory, double rate, sampleFormat format, double startTime, double endTime, WaveTrack **newLeft, WaveTrack **newRight)
void MixBuffers (int numChannels, int *channelFlags, float *gains, samplePtr src, samplePtr *dests, int len, bool interleaved)
Function Documentation
bool MixAndRender (TrackList * tracks, TrackFactory * factory, double rate, sampleFormat format, double startTime, double endTime, WaveTrack ** newLeft, WaveTrack ** newRight)
References WaveTrack::Append(), eProgressCancelled, eProgressFailed, eProgressStopped, eProgressSuccess, TrackListIterator::First(), WaveTrack::Flush(), Mixer::GetBuffer(), Track::GetChannel(), Track::GetEndTime(), WaveTrack::GetIdealBlockSize(), Track::GetKind(), Track::GetSelected(), TrackList::GetTimeTrack(), Track::LeftChannel, Mixer::MixGetCurrentTime(), Track::MonoChannel, TrackFactory::NewWaveTrack(), TrackListIterator::Next(), Mixer::Process(), Track::RightChannel, Track::SetChannel(), Track::SetLinked(), Track::SetName(), ProgressDialog::Update(), and Track::Wave.
Referenced by AudacityProject::HandleMixAndRender(), and Effect::Preview().
void MixBuffers (int numChannels, int * channelFlags, float * gains, samplePtr src, samplePtr * dests, int len, bool interleaved)
References floatSample, and SAMPLE_SIZE.
Referenced by Mixer::MixSameRate(), and Mixer::MixVariableRates().