Audacity: Project.h File Reference
Project.h File Reference
#include "Audacity.h"
#include "DirManager.h"
#include "UndoManager.h"
#include "ViewInfo.h"
#include "TrackPanel.h"
#include "AudioIO.h"
#include "commands/CommandManager.h"
#include "effects/EffectManager.h"
#include "xml/XMLTagHandler.h"
#include "toolbars/SelectionBar.h"
#include "FreqWindow.h"
#include <wx/defs.h>
#include <wx/event.h>
#include <wx/log.h>
#include <wx/dragimag.h>
#include <wx/generic/dragimgg.h>
#include <wx/frame.h>
#include <wx/intl.h>
#include <wx/dcclient.h>
#include "Menus.h"
Classes
class ImportXMLTagHandler
class AudacityProject
AudacityProject provides the main window, with tools and tracks contained within it.
Enumerations
enum PlayMode { normalPlay, oneSecondPlay, loopedPlay }
Functions
AudacityProject * CreateNewAudacityProject ()
AUDACITY_DLL_API AudacityProject * GetActiveProject ()
void RedrawAllProjects ()
void RefreshCursorForAllProjects ()
AUDACITY_DLL_API void CloseAllProjects ()
void GetDefaultWindowRect (wxRect *defRect)
void GetNextWindowPlacement (wxRect *nextRect, bool *pMaximized, bool *pIconized)
bool IsWindowAccessible (wxRect *requestedRect)
WX_DEFINE_ARRAY (AudacityProject *, AProjectArray)
WX_DEFINE_ARRAY (wxMenu *, MenuArray)
Variables
const int AudacityProjectTimerID = 5200
AProjectArray gAudacityProjects
Enumeration Type Documentation
enum PlayMode
Enumerator:
normalPlay
oneSecondPlay
loopedPlay
Function Documentation
AUDACITY_DLL_API void CloseAllProjects ()
References AUDACITY_DLL_API, gAudacityOffsetInc, gAudacityPosInc, and gAudacityProjects.
AudacityProject* CreateNewAudacityProject ()
References ModuleManager::Dispatch(), gAudacityProjects, gAudioIO, GetNextWindowPlacement(), ProjectInitialized, SetActiveProject(), and AudioIO::SetListener().
Referenced by LOFImportFileHandle::lofOpenFiles(), AudacityApp::MRUOpen(), AudacityProject::OnCloseWindow(), AudacityApp::OnInit(), AudacityApp::OnMenuNew(), AudacityProject::OnNew(), AudacityProject::OpenFiles(), and RecoverAllProjects().
AUDACITY_DLL_API AudacityProject* GetActiveProject ()
Referenced by BatchCommands::ApplyChain(), BatchCommands::ApplyCommandInBatchMode(), BatchCommands::ApplyEffectCommand(), BatchCommands::ApplySpecialCommand(), Theme::ApplyUpdatedImages(), audacityAudioCallback(), BatchProcessDialog::BatchProcessDialog(), LabelTrack::CaptureKey(), EffectNoiseRemoval::CleanSpeechMayReadNoisegate(), EffectNoiseRemoval::CleanSpeechMayWriteNoiseGate(), ContrastDialog::ContrastDialog(), EffectEqualization::DontPromptUser(), TranscriptionToolBar::EnableDisableButtons(), EditToolBar::EnableDisableButtons(), ControlToolBar::EnableDisableButtons(), ExecCommand(), ExportPlugin::Export(), FreqWindow::FreqWindow(), BatchCommands::GetAllCommands(), CommandManager::GetCategories(), ContrastDialog::GetDB(), BatchCommands::GetEndTime(), TranscriptionToolBar::GetSamples(), CommandManager::HandleCommandEntry(), TrackPanel::HandleMinimizing(), TrackPanel::HandleSelect(), CommandManager::HandleTextualCommand(), CommandManager::InsertItem(), BatchCommands::IsMono(), Track::IsSynchroSelected(), LOFImportFileHandle::LOFImportFileHandle(), AudacityApp::MRUOpen(), BatchProcessDialog::OnApplyToFiles(), TranscriptionToolBar::OnAutomateSelection(), ControlToolBar::OnBatch(), EditToolBar::OnButton(), TranscriptionToolBar::OnCalibrate(), AudacityApp::OnChar(), DeviceToolBar::OnChoice(), TranscriptionToolBar::OnEndOff(), TranscriptionToolBar::OnEndOn(), ContrastDialog::OnExport(), ControlToolBar::OnFF(), AudacityApp::OnKeyDown(), Lyrics::OnKeyEvent(), ControlToolBar::OnKeyEvent(), AudacityApp::OnKeyUp(), TranscriptionToolBar::OnMakeLabel(), Meter::OnMouse(), HighlightTextCtrl::OnMouseEvent(), LWSlider::OnMouseEvent(), AButton::OnMouseEvent(), ControlToolBar::OnPlay(), TranscriptionToolBar::OnPlaySpeed(), ControlToolBar::OnRecord(), ControlToolBar::OnRewind(), LabelDialog::OnSelectCell(), TranscriptionToolBar::OnSelectSilence(), TranscriptionToolBar::OnSelectSound(), TranscriptionToolBar::OnStartOff(), TranscriptionToolBar::OnStartOn(), ContrastDialog::OnUseSelectionB(), ContrastDialog::OnUseSelectionF(), ControlToolBar::PlayCurrentRegion(), ControlToolBar::PlayPlayRegion(), KeyConfigPrefs::Populate(), NoiseRemovalDialog::PopulateOrExchange(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), EffectEqualization::ProcessOne(), EffectNoiseRemoval::PromptUser(), EffectEqualization::PromptUser(), TimerRecordDialog::RunWaitDialog(), TrackPanel::SelectionHandleClick(), TrackPanel::SelectTrackLength(), TrackPanel::SetFocusedTrack(), ControlToolBar::SetupCutPreviewTracks(), ShowHelpDialog(), SnapManager::Snap(), SnapManager::SnapManager(), ODManager::Start(), Meter::StartMonitoring(), ControlToolBar::StopPlaying(), AudioIO::StopStream(), WaveTrack::SyncAdjust(), ToneGenDialog::TransferDataFromWindow(), Lyrics::Update(), AudacityProject::UpdateMenus(), WaveTrack::WaveTrack(), and BatchCommands::WriteMp3File().
void GetDefaultWindowRect (wxRect * defRect)
Referenced by GetNextWindowPlacement(), and SaveWindowSize().
void GetNextWindowPlacement (wxRect * nextRect, bool * pMaximized, bool * pIconized)
References gAudacityProjects, GetDefaultWindowRect(), gPrefs, and IsWindowAccessible().
Referenced by CreateNewAudacityProject().
bool IsWindowAccessible (wxRect * requestedRect)
Referenced by GetNextWindowPlacement().
void RedrawAllProjects ()
References gAudacityProjects.
Referenced by ToolsToolBar::OnTool().
void RefreshCursorForAllProjects ()
References gAudacityProjects.
Referenced by ToolsToolBar::SetCurrentTool().
WX_DEFINE_ARRAY (wxMenu * , MenuArray)
WX_DEFINE_ARRAY (AudacityProject * , AProjectArray)
Variable Documentation
const int AudacityProjectTimerID = 5200
AProjectArray gAudacityProjects
Referenced by BatchPrefs::Apply(), CloseAllProjects(), CreateNewAudacityProject(), ODTask::DoSome(), ControlToolBar::EnableDisableButtons(), GetNextWindowPlacement(), AudacityApp::MRUOpen(), AudacityProject::OnCloseWindow(), AudacityApp::OnEndSession(), AudacityProject::OnIconize(), AudacityApp::OnMenuAbout(), AudacityApp::OnMenuExit(), AudacityApp::OnMenuNew(), AudacityApp::OnMenuOpen(), AudacityApp::OnMenuPreferences(), PrefsDialog::OnOK(), AudacityProject::OnPlayStop(), AudacityProject::OnPreferences(), ControlToolBar::OnRecord(), AudacityProject::OpenFiles(), QuitAudacity(), RedrawAllProjects(), RefreshCursorForAllProjects(), and SaveWindowSize().