Audacity: RealFFTf.h File Reference
RealFFTf.h File Reference
Classes
struct FFTParamType
Defines
#define fft_type float
#define HFFT FFTParam *
Typedefs
typedef struct FFTParamType FFTParam
Functions
HFFT InitializeFFT (int)
void EndFFT (HFFT)
HFFT GetFFT (int)
void ReleaseFFT (HFFT)
void CleanupFFT ()
void RealFFTf (fft_type *, HFFT)
void InverseRealFFTf (fft_type *, HFFT)
void ReorderToTime (HFFT hFFT, fft_type *buffer, fft_type *TimeOut)
void ReorderToFreq (HFFT hFFT, fft_type *buffer, fft_type *RealOut, fft_type *ImagOut)
Define Documentation
#define fft_type float
Referenced by InitializeFFT(), InverseRealFFTf(), and RealFFTf().
#define HFFT FFTParam *
Referenced by InitializeFFT(), InverseRealFFT(), PowerSpectrum(), and RealFFT().
Typedef Documentation
typedef struct FFTParamType FFTParam
Function Documentation
void CleanupFFT ()
References EndFFT(), hFFTArray, MAX_HFFT, and nFFTLockCount.
Referenced by DeinitFFT().
void EndFFT (HFFT)
Referenced by EffectNoiseRemoval::Cleanup(), CleanupFFT(), WaveClip::GetSpectrogram(), ReleaseFFT(), EffectEqualization::~EffectEqualization(), and WaveClip::~WaveClip().
HFFT GetFFT (int)
References hFFTArray, InitializeFFT(), MAX_HFFT, and nFFTLockCount.
Referenced by InverseRealFFT(), PowerSpectrum(), and RealFFT().
HFFT InitializeFFT (int)
References fft_type, HFFT, and M_PI.
Referenced by EffectEqualization::EffectEqualization(), GetFFT(), WaveClip::GetSpectrogram(), and EffectNoiseRemoval::Initialize().
void InverseRealFFTf (fft_type * , HFFT)
References fft_type.
Referenced by EffectEqualization::Filter(), InverseRealFFT(), and EffectNoiseRemoval::RemoveNoise().
void RealFFTf (fft_type * , HFFT)
References fft_type.
Referenced by ComputeSpectrumUsingRealFFTf(), EffectNoiseRemoval::FillFirstHistoryWindow(), EffectEqualization::Filter(), PowerSpectrum(), and RealFFT().
void ReleaseFFT (HFFT)
References EndFFT(), hFFTArray, MAX_HFFT, and nFFTLockCount.
Referenced by InverseRealFFT(), PowerSpectrum(), and RealFFT().
void ReorderToFreq (HFFT hFFT, fft_type * buffer, fft_type * RealOut, fft_type * ImagOut)
void ReorderToTime (HFFT hFFT, fft_type * buffer, fft_type * TimeOut)
Referenced by EffectEqualization::Filter(), and InverseRealFFT().