Audacity: SampleFormat.h File Reference
SampleFormat.h File Reference
#include "Audacity.h"
#include <wx/defs.h>
Defines
#define SAMPLE_SIZE(SampleFormat) (SampleFormat >> 16)
Return the size (in memory) of one sample (bytes).
#define SAMPLE_SIZE_DISK(SampleFormat)
Return the size on disk of one uncompressed sample (bytes).
Typedefs
typedef char * samplePtr
Enumerations
enum sampleFormat { int16Sample = 0x00020001, int24Sample = 0x00040001, floatSample = 0x0004000F }
Functions
const wxChar * GetSampleFormatStr (sampleFormat format)
AUDACITY_DLL_API samplePtr NewSamples (int count, sampleFormat format)
AUDACITY_DLL_API void DeleteSamples (samplePtr p)
void CopySamples (samplePtr src, sampleFormat srcFormat, samplePtr dst, sampleFormat dstFormat, unsigned int len, bool highQuality=true, unsigned int stride=1)
void CopySamplesNoDither (samplePtr src, sampleFormat srcFormat, samplePtr dst, sampleFormat dstFormat, unsigned int len, unsigned int stride=1)
void ClearSamples (samplePtr buffer, sampleFormat format, int start, int len)
void InitDitherers ()
Define Documentation
#define SAMPLE_SIZE (SampleFormat) (SampleFormat >> 16)
Return the size (in memory) of one sample (bytes).
Referenced by WaveClip::Append(), Sequence::Append(), Dither::Apply(), Sequence::Blockify(), Mixer::Clear(), ClearSamples(), ComputeLegacySummaryInfo(), Sequence::CopyWrite(), Sequence::Delete(), DoSoftwarePlaythrough(), ExportCL::Export(), SimpleBlockFile::FillCache(), FindDependencies(), WaveTrack::Get(), Sequence::Get(), RingBuffer::Get(), EffectNyquist::GetCallback(), PCMImportFileHandle::GetFileUncompressedBytes(), WaveClip::GetWaveDisplay(), MixBuffers(), Mixer::MixVariableRates(), NewSamples(), Sequence::Paste(), RingBuffer::Put(), SimpleBlockFile::ReadData(), PCMAliasBlockFile::ReadData(), ODPCMAliasBlockFile::ReadData(), LegacyBlockFile::ReadData(), RemoveDependencies(), Sequence::Sequence(), WaveTrack::Set(), Sequence::Set(), SimpleBlockFile::SimpleBlockFile(), ODFLACFile::write_callback(), and SimpleBlockFile::WriteSimpleBlockFile().
#define SAMPLE_SIZE_DISK (SampleFormat)
Value:
((SampleFormat == int24Sample) ? \
   3 : SAMPLE_SIZE(SampleFormat) )
Return the size on disk of one uncompressed sample (bytes).
Referenced by AudacityProject::OnTimer().
Typedef Documentation
typedef char* samplePtr
Enumeration Type Documentation
enum sampleFormat
Enumerator:
int16Sample
int24Sample
floatSample
Function Documentation
void ClearSamples (samplePtr buffer, sampleFormat format, int start, int len)
References SAMPLE_SIZE.
Referenced by audacityAudioCallback(), AudioIO::FillBuffers(), WaveTrack::Get(), Sequence::Read(), SilentBlockFile::ReadData(), ODDecodeBlockFile::ReadData(), and Sequence::Set().
void CopySamples (samplePtr src, sampleFormat srcFormat, samplePtr dst, sampleFormat dstFormat, unsigned int len, bool highQuality = true, unsigned int stride = 1)
References Dither::Apply(), gHighQualityDither, and gLowQualityDither.
Referenced by WaveClip::Append(), Sequence::Append(), audacityAudioCallback(), ODPCMAliasBlockFile::CalcSummary(), ODDecodeBlockFile::CalcSummary(), BlockFile::CalcSummary(), ComputeLegacySummaryInfo(), Sequence::ConvertToSampleFormat(), DoSoftwarePlaythrough(), RingBuffer::Get(), EffectNyquist::GetCallback(), WaveClip::GetWaveDisplay(), Mixer::Process(), RingBuffer::Put(), BlockFile::Read256(), BlockFile::Read64K(), SimpleBlockFile::ReadData(), PCMAliasBlockFile::ReadData(), ODPCMAliasBlockFile::ReadData(), LegacyBlockFile::ReadData(), and Sequence::Set().
void CopySamplesNoDither (samplePtr src, sampleFormat srcFormat, samplePtr dst, sampleFormat dstFormat, unsigned int len, unsigned int stride = 1)
References Dither::Apply(), and Dither::none.
AUDACITY_DLL_API void DeleteSamples (samplePtr p)
References AUDACITY_DLL_API.
Referenced by Sequence::Append(), ComputeLegacySummaryInfo(), Sequence::ConvertToSampleFormat(), Sequence::Copy(), Sequence::CopyWrite(), Sequence::Delete(), AudioIO::FillBuffers(), BlockFile::GetMinMax(), PCMImportFileHandle::Import(), Sequence::Paste(), EffectNyquist::ProcessOne(), SimpleBlockFile::ReadData(), PCMAliasBlockFile::ReadData(), ODPCMAliasBlockFile::ReadData(), LegacyBlockFile::ReadData(), RemoveDependencies(), Sequence::Set(), ODDecodeBlockFile::WriteODDecodeBlockFile(), ODPCMAliasBlockFile::WriteSummary(), AliasBlockFile::WriteSummary(), AudioIO::~AudioIO(), Mixer::~Mixer(), RingBuffer::~RingBuffer(), and WaveClip::~WaveClip().
const wxChar* GetSampleFormatStr (sampleFormat format)
References floatSample, int16Sample, and int24Sample.
Referenced by TrackPanel::BuildMenus(), TrackPanel::DrawOutside(), and TrackPanel::OnFormatChange().
void InitDitherers ()
References gHighQualityDither, gLowQualityDither, gPrefs, Dither::none, and Dither::shaped.
Referenced by QualityPrefs::Apply(), and AudacityApp::OnInit().
AUDACITY_DLL_API samplePtr NewSamples (int count, sampleFormat format)
References AUDACITY_DLL_API, and SAMPLE_SIZE.
Referenced by WaveClip::Append(), Sequence::Append(), ComputeLegacySummaryInfo(), Sequence::ConvertToSampleFormat(), Sequence::Copy(), Sequence::CopyWrite(), ODFlacDecoder::Decode(), Sequence::Delete(), AudioIO::FillBuffers(), EffectNyquist::GetCallback(), BlockFile::GetMinMax(), PCMImportFileHandle::Import(), ImportRaw(), Mixer::Mixer(), Sequence::Paste(), SimpleBlockFile::ReadData(), PCMAliasBlockFile::ReadData(), ODPCMAliasBlockFile::ReadData(), LegacyBlockFile::ReadData(), RemoveDependencies(), RingBuffer::RingBuffer(), Sequence::Set(), ODPCMAliasBlockFile::WriteSummary(), and AliasBlockFile::WriteSummary().