Audacity: ScriptCommandRelay.cpp File Reference
ScriptCommandRelay.cpp File Reference
Contains definitions for ScriptCommandRelay.
#include "ScriptCommandRelay.h"
#include "CommandTargets.h"
#include "CommandBuilder.h"
#include "AppCommandEvent.h"
#include "ResponseQueue.h"
#include "../Project.h"
#include <wx/string.h>
Functions
int ExecCommand (wxString *pIn, wxString *pOut)
Detailed Description
Contains definitions for ScriptCommandRelay.
Function Documentation
int ExecCommand (wxString * pIn, wxString * pOut)
This is the function which actually obeys one command. Rather than applying the command directly, an event containing a reference to the command is sent to the main (GUI) thread. This is because having more than one thread access the GUI at a time causes problems with wxwidgets.
References CommandBuilder::Cleanup(), GetActiveProject(), CommandBuilder::GetCommand(), CommandBuilder::GetErrorMessage(), Response::GetMessage(), ScriptCommandRelay::PostCommand(), ScriptCommandRelay::ReceiveResponse(), AudacityProject::SafeDisplayStatusMessage(), and CommandBuilder::WasValid().
Referenced by ScriptCommandRelay::Run().