Audacity: ShuttleGui.h File Reference
ShuttleGui.h File Reference
#include "Audacity.h"
#include <wx/string.h>
#include "WrappedType.h"
#include <wx/scrolbar.h>
Classes
class ShuttleGuiBase
Base class for shuttling data to and from a GUI.
class ShuttleGui
Derived from ShuttleGuiBase, an Audacity specific class for shuttling data to and from GUI.
Typedefs
typedef wxWindow wxNotebookPage
Enumerations
enum teShuttleMode {
eIsCreating, eIsGettingFromDialog, eIsSettingToDialog, eIsSavingViaShuttle,
eIsGettingViaShuttle, eIsCreatingFromPrefs, eIsSavingToPrefs
}
enum {
eOkButton = 0x0001, eCancelButton = 0x0002, eYesButton = 0x0004, eNoButton = 0x0008,
eHelpButton = 0x0010, ePreviewButton = 0x0020, eDebugButton = 0x0040
}
enum { ePreviewID = wxID_LOWEST - 1, eDebugID = wxID_LOWEST - 2 }
Functions
void SetIfCreated (wxChoice *&Var, wxChoice *Val)
void SetIfCreated (wxTextCtrl *&Var, wxTextCtrl *Val)
void SetIfCreated (wxStaticText *&Var, wxStaticText *Val)
AUDACITY_DLL_API wxSizer * CreateStdButtonSizer (wxWindow *parent, long buttons=eOkButton|eCancelButton, wxButton *extra=NULL)
Variables
const int nMaxNestedSizers = 20
Typedef Documentation
typedef wxWindow wxNotebookPage
Enumeration Type Documentation
anonymous enum
Enumerator:
eOkButton
eCancelButton
eYesButton
eNoButton
eHelpButton
ePreviewButton
eDebugButton
anonymous enum
Enumerator:
ePreviewID
eDebugID
enum teShuttleMode
Enumerator:
eIsCreating
eIsGettingFromDialog
eIsSettingToDialog
eIsSavingViaShuttle
eIsGettingViaShuttle
eIsCreatingFromPrefs
eIsSavingToPrefs
Function Documentation
AUDACITY_DLL_API wxSizer* CreateStdButtonSizer (wxWindow * parent, long buttons = eOkButton|eCancelButton, wxButton * extra = NULL)
References eCancelButton, eDebugButton, eDebugID, eHelpButton, eNoButton, eOkButton, ePreviewButton, ePreviewID, and eYesButton.
Referenced by ShuttleGui::AddStandardButtons(), EVT_COMMAND_RANGE(), ExportMixerDialog::ExportMixerDialog(), ImportStreamDialog::ImportStreamDialog(), LabelDialog::LabelDialog(), LadspaEffectDialog::LadspaEffectDialog(), EqualizationDialog::MakeEqualizationDialog(), NyquistInputDialog::NyquistInputDialog(), and VampEffectDialog::VampEffectDialog().
void SetIfCreated (wxStaticText *& Var, wxStaticText * Val)
void SetIfCreated (wxTextCtrl *& Var, wxTextCtrl * Val)
void SetIfCreated (wxChoice *& Var, wxChoice * Val)
Variable Documentation
const int nMaxNestedSizers = 20
Referenced by ShuttleGuiBase::PushSizer().