Audacity: VoiceKey.h File Reference
VoiceKey.h File Reference
#include "WaveTrack.h"
Classes
class VoiceKey
This implements a voice key, detecting either the next "ON" or "OFF" point.
Enumerations
enum VoiceKeyTypes {
VKT_NONE = 0, VKT_ENERGY = 1, VKT_SIGN_CHANGES_LOW = 2, VKT_SIGN_CHANGES_HIGH = 4,
VKT_DIRECTION_CHANGES_LOW = 8, VKT_DIRECTION_CHANGES_HIGH = 16
}
Functions
int sgn (int number)
Enumeration Type Documentation
enum VoiceKeyTypes
Enumerator:
VKT_NONE
VKT_ENERGY
VKT_SIGN_CHANGES_LOW
VKT_SIGN_CHANGES_HIGH
VKT_DIRECTION_CHANGES_LOW
VKT_DIRECTION_CHANGES_HIGH
Function Documentation
int sgn (int number) [inline]
Referenced by VoiceKey::OffBackward(), VoiceKey::OffForward(), VoiceKey::OnBackward(), VoiceKey::OnForward(), VoiceKey::TestDirectionChanges(), VoiceKey::TestDirectionChangesUpdate(), VoiceKey::TestSignChanges(), and VoiceKey::TestSignChangesUpdate().