Audacity: Warning.cpp File Reference
Warning.cpp File Reference
#include "../Audacity.h"
#include "Warning.h"
#include "../Prefs.h"
#include "../ShuttleGui.h"
#include <wx/button.h>
#include <wx/checkbox.h>
#include <wx/dialog.h>
#include <wx/intl.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
Classes
class WarningDialog
Gives a warning message, that can be dismissed, with crucially the ability to not see similar warnings again for this session.
Functions
void ShowWarningDialog (wxWindow *parent, wxString internalDialogName, wxString message)
Function Documentation
void ShowWarningDialog (wxWindow * parent, wxString internalDialogName, wxString message)
Displays a warning dialog with a check box that says "Don't show this warning again". If the user checks the box, the internalDialogName is noted in the preferences. The internalDialogName is never seen by the user; it should be unique to each message.
References gPrefs.
Referenced by Exporter::CheckMix(), DirManager::DirManager(), and AudacityProject::SaveAs().