Audacity: EffectLeveller Class Reference
EffectLeveller Class Reference
An EffectSimpleMono.
#include <Leveller.h>
Public Member Functions
EffectLeveller ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool Init ()
virtual void End ()
virtual bool CheckWhetherSkipEffect ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
Protected Member Functions
virtual bool ProcessSimpleMono (float *buffer, sampleCount len)
Private Member Functions
void CalcLevellerFactors ()
float LevelOneFrame (float frame)
Private Attributes
int mLevellerDbChoiceIndex
int mLevellerNumPasses
double mFrameSum
double mLevellerDbSilenceThreshold
Friends
class LevellerDialog
Detailed Description
An EffectSimpleMono.
Constructor & Destructor Documentation
EffectLeveller::EffectLeveller ()
References Init().
Member Function Documentation
void EffectLeveller::CalcLevellerFactors () [private]
References gAddOnValue, gAdjFactor, gAdjLimit, gLimit, LEVELER_FACTORS, mFrameSum, and mLevellerDbSilenceThreshold.
Referenced by Init(), and PromptUser().
bool EffectLeveller::CheckWhetherSkipEffect () [virtual]
Reimplemented from Effect.
References mLevellerDbChoiceIndex, mLevellerNumPasses, and Enums::NumDbChoices.
void EffectLeveller::End () [virtual]
Reimplemented from Effect.
References gPrefs, and mFrameSum.
virtual wxString EffectLeveller::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectLeveller::GetEffectCategories () [inline, virtual]
virtual wxString EffectLeveller::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectLeveller::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectLeveller::Init () [virtual]
Reimplemented from Effect.
References CalcLevellerFactors(), Enums::Db2Signal, gPrefs, mLevellerDbChoiceIndex, mLevellerDbSilenceThreshold, mLevellerNumPasses, NUM_PASSES_CHOICES, and Enums::NumDbChoices.
Referenced by EffectLeveller().
float EffectLeveller::LevelOneFrame (float frame) [private]
References gAddOnValue, gAdjFactor, gLimit, LEVELER_FACTORS, and mFrameSum.
Referenced by ProcessSimpleMono().
bool EffectLeveller::ProcessSimpleMono (float * buffer, sampleCount len) [protected, virtual]
Implements EffectSimpleMono.
References LevelOneFrame(), and mLevellerNumPasses.
bool EffectLeveller::PromptUser () [virtual]
Reimplemented from Effect.
References CalcLevellerFactors(), Enums::Db2Signal, gPrefs, mLevellerDbChoiceIndex, LevellerDialog::mLevellerDbChoiceIndex, mLevellerDbSilenceThreshold, mLevellerNumPasses, LevellerDialog::mLevellerNumPasses, Effect::mParent, and EffectDialog::TransferDataToWindow().
bool EffectLeveller::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References Enums::GetDbChoices(), mLevellerDbChoiceIndex, mLevellerNumPasses, Enums::NumDbChoices, Shuttle::TransferEnum(), and Shuttle::TransferInt().
Friends And Related Function Documentation
friend class LevellerDialog [friend]
Member Data Documentation
double EffectLeveller::mFrameSum [private]
Referenced by CalcLevellerFactors(), End(), and LevelOneFrame().
int EffectLeveller::mLevellerDbChoiceIndex [private]
Referenced by CheckWhetherSkipEffect(), Init(), LevellerDialog::OnPreview(), PromptUser(), and TransferParameters().
double EffectLeveller::mLevellerDbSilenceThreshold [private]
Referenced by CalcLevellerFactors(), Init(), and PromptUser().
int EffectLeveller::mLevellerNumPasses [private]
Referenced by CheckWhetherSkipEffect(), Init(), LevellerDialog::OnPreview(), ProcessSimpleMono(), PromptUser(), and TransferParameters().
The documentation for this class was generated from the following files:
Leveller.h
Leveller.cpp