Audacity: LinkingHtmlWindow Class Reference
LinkingHtmlWindow Class Reference
#include <LinkingHtmlWindow.h>
Public Member Functions
LinkingHtmlWindow (wxWindow *parent, wxWindowID id=-1, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxHW_SCROLLBAR_AUTO)
virtual void OnLinkClicked (const wxHtmlLinkInfo &link)
Constructor & Destructor Documentation
LinkingHtmlWindow::LinkingHtmlWindow (wxWindow * parent, wxWindowID id = -1, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxHW_SCROLLBAR_AUTO)
Member Function Documentation
void LinkingHtmlWindow::OnLinkClicked (const wxHtmlLinkInfo & link) [virtual]
References HelpText(), FileNames::HtmlHelpDir(), OpenInDefaultBrowser(), ShowHelpDialog(), TitleText(), and BrowserFrame::UpdateButtons().
The documentation for this class was generated from the following files:
LinkingHtmlWindow.h
LinkingHtmlWindow.cpp