Audacity: ProjectsPrefs Class Reference
ProjectsPrefs Class Reference
A PrefsPanel used to select options related to Audacity Project handling.
#include <ProjectsPrefs.h>
Public Member Functions
ProjectsPrefs (wxWindow *parent)
~ProjectsPrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
Creates the dialog and its contents.
void PopulateOrExchange (ShuttleGui &S)
Detailed Description
A PrefsPanel used to select options related to Audacity Project handling.
Constructor & Destructor Documentation
ProjectsPrefs::ProjectsPrefs (wxWindow * parent)
References Populate().
ProjectsPrefs::~ProjectsPrefs ()
Member Function Documentation
bool ProjectsPrefs::Apply () [virtual]
Implements PrefsPanel.
References eIsSavingToPrefs, and PopulateOrExchange().
void ProjectsPrefs::Populate () [private]
Creates the dialog and its contents.
References eIsCreatingFromPrefs, and PopulateOrExchange().
Referenced by ProjectsPrefs().
void ProjectsPrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddUnits(), ShuttleGuiBase::EndRadioButtonGroup(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndThreeColumn(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartRadioButtonGroup(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartThreeColumn(), ShuttleGuiBase::TieCheckBox(), ShuttleGuiBase::TieRadioButton(), and ShuttleGuiBase::TieTextBox().
Referenced by Apply(), and Populate().
The documentation for this class was generated from the following files:
ProjectsPrefs.h
ProjectsPrefs.cpp