Audacity: AudioIOListener Class Reference
AudioIOListener Class Reference
#include <AudioIO.h>
Public Member Functions
AudioIOListener ()
virtual ~AudioIOListener ()
virtual void OnAudioIORate (int rate)=0
virtual void OnAudioIOStartRecording ()=0
virtual void OnAudioIOStopRecording ()=0
virtual void OnAudioIONewBlockFiles (const wxString &blockFileLog)=0
Constructor & Destructor Documentation
AudioIOListener::AudioIOListener () [inline]
virtual AudioIOListener::~AudioIOListener () [inline, virtual]
Member Function Documentation
virtual void AudioIOListener::OnAudioIONewBlockFiles (const wxString & blockFileLog) [pure virtual]
Implemented in AudacityProject.
Referenced by AudioIO::FillBuffers().
virtual void AudioIOListener::OnAudioIORate (int rate) [pure virtual]
Implemented in AudacityProject.
Referenced by AudioIO::StartPortAudioStream().
virtual void AudioIOListener::OnAudioIOStartRecording () [pure virtual]
Implemented in AudacityProject.
Referenced by AudioIO::StartStream().
virtual void AudioIOListener::OnAudioIOStopRecording () [pure virtual]
Implemented in AudacityProject.
Referenced by AudioIO::StartStream(), and AudioIO::StopStream().
The documentation for this class was generated from the following file:
AudioIO.h