Audacity: HistoryWindow Class Reference
HistoryWindow Class Reference
Works with UndoManager to allow user to see descriptions of and undo previous commands. Also allows you to selectively clear the undo memory so as to free up space.
#include <HistoryWindow.h>
Public Member Functions
HistoryWindow (AudacityProject *parent, UndoManager *manager)
~HistoryWindow ()
void UpdateDisplay ()
Private Member Functions
void DoUpdate ()
void UpdateLevels ()
void OnShow (wxShowEvent &event)
void OnSize (wxSizeEvent &event)
void OnCloseWindow (wxCloseEvent &WXUNUSED(event))
void OnChar (wxKeyEvent &event)
void OnItemSelected (wxListEvent &event)
void OnDiscard (wxCommandEvent &event)
Private Attributes
AudacityProject * mProject
UndoManager * mManager
wxListCtrl * mList
wxTextCtrl * mAvail
wxSpinCtrl * mLevels
wxButton * mDiscard
int mSelected
Detailed Description
Works with UndoManager to allow user to see descriptions of and undo previous commands. Also allows you to selectively clear the undo memory so as to free up space.
Constructor & Destructor Documentation
HistoryWindow::HistoryWindow (AudacityProject * parent, UndoManager * manager)
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddListControlReportMode(), ShuttleGuiBase::AddPrompt(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddVariableText(), ShuttleGuiBase::AddWindow(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), ShuttleGui::Id(), ID_AVAIL, ID_LEVELS, OnChar(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::StartVerticalLay().
HistoryWindow::~HistoryWindow ()
References mAvail, and OnChar().
Member Function Documentation
void HistoryWindow::DoUpdate () [private]
References UndoManager::GetCurrentState(), UndoManager::GetLongDescription(), UndoManager::GetNumStates(), mList, mManager, mSelected, and UpdateLevels().
Referenced by UpdateDisplay().
void HistoryWindow::OnChar (wxKeyEvent & event) [private]
Referenced by HistoryWindow(), and ~HistoryWindow().
void HistoryWindow::OnCloseWindow (wxCloseEvent & WXUNUSEDevent) [private]
void HistoryWindow::OnDiscard (wxCommandEvent & event) [private]
References mLevels, mList, mManager, mProject, mSelected, UndoManager::RemoveStates(), AudacityProject::SetStateTo(), and UpdateLevels().
void HistoryWindow::OnItemSelected (wxListEvent & event) [private]
References mList, mProject, mSelected, AudacityProject::SetStateTo(), and UpdateLevels().
void HistoryWindow::OnShow (wxShowEvent & event) [private]
References UpdateDisplay().
void HistoryWindow::OnSize (wxSizeEvent & event) [private]
References mList, and mSelected.
void HistoryWindow::UpdateDisplay ()
References DoUpdate().
Referenced by AudacityProject::InitialState(), AudacityProject::OnHistory(), AudacityProject::OnRedo(), OnShow(), AudacityProject::OnUndo(), and AudacityProject::PushState().
void HistoryWindow::UpdateLevels () [private]
References mAvail, mDiscard, mLevels, mList, and mSelected.
Referenced by DoUpdate(), OnDiscard(), and OnItemSelected().
Member Data Documentation
wxTextCtrl* HistoryWindow::mAvail [private]
Referenced by UpdateLevels(), and ~HistoryWindow().
wxButton* HistoryWindow::mDiscard [private]
Referenced by UpdateLevels().
wxSpinCtrl* HistoryWindow::mLevels [private]
Referenced by OnDiscard(), and UpdateLevels().
wxListCtrl* HistoryWindow::mList [private]
Referenced by DoUpdate(), OnDiscard(), OnItemSelected(), OnSize(), and UpdateLevels().
UndoManager* HistoryWindow::mManager [private]
Referenced by DoUpdate(), and OnDiscard().
AudacityProject* HistoryWindow::mProject [private]
Referenced by OnDiscard(), and OnItemSelected().
int HistoryWindow::mSelected [private]
Referenced by DoUpdate(), OnDiscard(), OnItemSelected(), OnSize(), and UpdateLevels().
The documentation for this class was generated from the following files:
HistoryWindow.h
HistoryWindow.cpp