Audacity: EffectAutoDuckDialog Class Reference
EffectAutoDuckDialog Class Reference
#include <AutoDuck.h>
Public Member Functions
EffectAutoDuckDialog (EffectAutoDuck *effect, wxWindow *parent)
Private Member Functions
void OnOk (wxCommandEvent &evt)
void OnCancel (wxCommandEvent &evt)
void OnValueChanged (wxCommandEvent &evt)
Private Attributes
EffectAutoDuck * mEffect
wxTextCtrl * mDuckAmountDbBox
wxTextCtrl * mInnerFadeDownLenBox
wxTextCtrl * mInnerFadeUpLenBox
wxTextCtrl * mOuterFadeDownLenBox
wxTextCtrl * mOuterFadeUpLenBox
wxTextCtrl * mThresholdDbBox
wxTextCtrl * mMaximumPauseBox
EffectAutoDuckPanel * mPanel
Friends
class EffectAutoDuckPanel
Constructor & Destructor Documentation
EffectAutoDuckDialog::EffectAutoDuckDialog (EffectAutoDuck * effect, wxWindow * parent)
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddUnits(), ShuttleGuiBase::AddWindow(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndVerticalLay(), ShuttleGui::Id(), ID_PANEL, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartVerticalLay(), and Internat::ToDisplayString().
Member Function Documentation
void EffectAutoDuckDialog::OnCancel (wxCommandEvent & evt) [private]
void EffectAutoDuckDialog::OnOk (wxCommandEvent & evt) [private]
References EffectAutoDuck::mDuckAmountDb, mDuckAmountDbBox, mEffect, EffectAutoDuck::mInnerFadeDownLen, mInnerFadeDownLenBox, EffectAutoDuck::mInnerFadeUpLen, mInnerFadeUpLenBox, EffectAutoDuck::mMaximumPause, mMaximumPauseBox, EffectAutoDuck::mOuterFadeDownLen, mOuterFadeDownLenBox, EffectAutoDuck::mOuterFadeUpLen, mOuterFadeUpLenBox, EffectAutoDuck::mThresholdDb, and mThresholdDbBox.
void EffectAutoDuckDialog::OnValueChanged (wxCommandEvent & evt) [private]
References mPanel.
Friends And Related Function Documentation
friend class EffectAutoDuckPanel [friend]
Member Data Documentation
wxTextCtrl* EffectAutoDuckDialog::mDuckAmountDbBox [private]
Referenced by EffectAutoDuckPanel::OnMotion(), OnOk(), and EffectAutoDuckPanel::OnPaint().
EffectAutoDuck* EffectAutoDuckDialog::mEffect [private]
Referenced by OnOk().
wxTextCtrl* EffectAutoDuckDialog::mInnerFadeDownLenBox [private]
Referenced by EffectAutoDuckPanel::OnMotion(), OnOk(), and EffectAutoDuckPanel::OnPaint().
wxTextCtrl* EffectAutoDuckDialog::mInnerFadeUpLenBox [private]
Referenced by EffectAutoDuckPanel::OnMotion(), OnOk(), and EffectAutoDuckPanel::OnPaint().
wxTextCtrl* EffectAutoDuckDialog::mMaximumPauseBox [private]
Referenced by OnOk().
wxTextCtrl* EffectAutoDuckDialog::mOuterFadeDownLenBox [private]
Referenced by EffectAutoDuckPanel::OnMotion(), OnOk(), and EffectAutoDuckPanel::OnPaint().
wxTextCtrl* EffectAutoDuckDialog::mOuterFadeUpLenBox [private]
Referenced by EffectAutoDuckPanel::OnMotion(), OnOk(), and EffectAutoDuckPanel::OnPaint().
EffectAutoDuckPanel* EffectAutoDuckDialog::mPanel [private]
Referenced by OnValueChanged().
wxTextCtrl* EffectAutoDuckDialog::mThresholdDbBox [private]
Referenced by OnOk().
The documentation for this class was generated from the following files:
AutoDuck.h
AutoDuck.cpp