Audacity: EffectStereoToMono Class Reference
EffectStereoToMono Class Reference
An Effect.
#include <StereoToMono.h>
Public Member Functions
EffectStereoToMono ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool Init ()
virtual void End ()
virtual bool CheckWhetherSkipEffect ()
Protected Member Functions
virtual bool Process ()
Private Member Functions
bool ProcessOne (int)
Private Attributes
sampleCount mStart
sampleCount mEnd
WaveTrack * mLeftTrack
WaveTrack * mRightTrack
WaveTrack * mOutTrack
Detailed Description
An Effect.
Constructor & Destructor Documentation
EffectStereoToMono::EffectStereoToMono ()
References Init().
Member Function Documentation
bool EffectStereoToMono::CheckWhetherSkipEffect () [virtual]
Reimplemented from Effect.
References TrackListCondIterator::First(), Track::GetLinked(), Effect::mTracks, TrackListCondIterator::Next(), and Track::Wave.
void EffectStereoToMono::End () [virtual]
Reimplemented from Effect.
virtual wxString EffectStereoToMono::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectStereoToMono::GetEffectCategories () [inline, virtual]
virtual wxString EffectStereoToMono::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectStereoToMono::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectStereoToMono::Init () [virtual]
Reimplemented from Effect.
Referenced by EffectStereoToMono().
bool EffectStereoToMono::Process () [protected, virtual]
Implements Effect.
References WaveTrack::Clear(), Effect::CopyInputTracks(), TrackListCondIterator::First(), floatSample, GetActiveProject(), WaveTrack::GetEndTime(), WaveTrack::GetKind(), Track::GetLinked(), WaveTrack::GetRate(), Track::GetSelected(), WaveTrack::GetStartTime(), AudacityProject::GetTrackFactory(), mEnd, mLeftTrack, Effect::mOutputTracks, mOutTrack, mRightTrack, mStart, TrackFactory::NewWaveTrack(), TrackListCondIterator::Next(), ProcessOne(), Effect::ReplaceProcessedTracks(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectStereoToMono::ProcessOne (int count) [private]
References WaveTrack::Append(), WaveTrack::Clear(), floatSample, WaveTrack::Flush(), WaveTrack::Get(), WaveTrack::GetEndTime(), WaveTrack::GetMaxBlockSize(), WaveTrack::GetStartTime(), mEnd, mLeftTrack, Track::MonoChannel, Effect::mOutputTracks, mOutTrack, mRightTrack, mStart, WaveTrack::Paste(), TrackList::Remove(), Track::SetChannel(), Track::SetLinked(), and Effect::TrackProgress().
Referenced by Process().
Member Data Documentation
sampleCount EffectStereoToMono::mEnd [private]
Referenced by Process(), and ProcessOne().
WaveTrack* EffectStereoToMono::mLeftTrack [private]
Referenced by Process(), and ProcessOne().
WaveTrack* EffectStereoToMono::mOutTrack [private]
Referenced by Process(), and ProcessOne().
WaveTrack* EffectStereoToMono::mRightTrack [private]
Referenced by Process(), and ProcessOne().
sampleCount EffectStereoToMono::mStart [private]
Referenced by Process(), and ProcessOne().
The documentation for this class was generated from the following files:
StereoToMono.h
StereoToMono.cpp