Audacity: ExportPlugin Class Reference
ExportPlugin Class Reference
#include <Export.h>
Public Member Functions
ExportPlugin ()
virtual ~ExportPlugin ()
virtual void Destroy ()
int AddFormat ()
Add a new entry to the list of formats this plug-in can export.
void SetFormat (const wxString &format, int index)
void SetDescription (const wxString &description, int index)
void AddExtension (const wxString &extension, int index)
void SetExtensions (const wxArrayString &extensions, int index)
void SetMask (const wxString &mask, int index)
void SetMaxChannels (int maxchannels, int index)
void SetCanMetaData (bool canmetadata, int index)
virtual int GetFormatCount ()
virtual wxString GetFormat (int index)
virtual wxString GetDescription (int index)
virtual wxString GetExtension (int index=0)
Return the (first) file name extension for the sub-format.
virtual wxArrayString GetExtensions (int index=0)
Return all the file name extensions used for the sub-format.
virtual wxString GetMask (int index)
virtual int GetMaxChannels (int index)
virtual bool GetCanMetaData (int index)
virtual bool IsExtension (wxString &ext, int index)
virtual bool DisplayOptions (wxWindow *parent, int format=0)
virtual bool CheckFileName (wxFileName &filename, int format=0)
virtual int Export (AudacityProject *project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec *mixerSpec=NULL, Tags *metadata=NULL, int subformat=0)
called to export audio into a file.
virtual int DoExport (AudacityProject *project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec *mixerSpec, int subformat)
Private Attributes
FormatInfoArray mFormatInfos
Constructor & Destructor Documentation
ExportPlugin::ExportPlugin ()
References mFormatInfos.
ExportPlugin::~ExportPlugin () [virtual]
References mFormatInfos.
Member Function Documentation
void ExportPlugin::AddExtension (const wxString & extension, int index)
References mFormatInfos.
Referenced by ExportCL::ExportCL(), ExportFFmpeg::ExportFFmpeg(), ExportFLAC::ExportFLAC(), ExportMP2::ExportMP2(), ExportMP3::ExportMP3(), ExportOGG::ExportOGG(), and ExportPCM::ExportPCM().
int ExportPlugin::AddFormat ()
Add a new entry to the list of formats this plug-in can export.
To configure the format use SetFormat, SetCanMetaData etc with the index of the format.
Returns:
The number of formats currently set up. This is one more than the index of the newly added format.
References mFormatInfos.
Referenced by ExportCL::ExportCL(), ExportFFmpeg::ExportFFmpeg(), ExportFLAC::ExportFLAC(), ExportMP2::ExportMP2(), ExportMP3::ExportMP3(), ExportOGG::ExportOGG(), and ExportPCM::ExportPCM().
bool ExportPlugin::CheckFileName (wxFileName & filename, int format = 0) [virtual]
Reimplemented in ExportFFmpeg.
void ExportPlugin::Destroy () [virtual]
Reimplemented in ExportCL, ExportFFmpeg, ExportFLAC, ExportMP2, ExportMP3, ExportOGG, and ExportPCM.
bool ExportPlugin::DisplayOptions (wxWindow * parent, int format = 0) [virtual]
Reimplemented in ExportCL, ExportFFmpeg, ExportFLAC, ExportMP2, ExportMP3, ExportOGG, and ExportPCM.
int ExportPlugin::DoExport (AudacityProject * project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec * mixerSpec, int subformat) [virtual]
Referenced by Export().
int ExportPlugin::Export (AudacityProject * project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec * mixerSpec = NULL, Tags * metadata = NULL, int subformat = 0) [virtual]
called to export audio into a file.
Parameters:
selectedOnly Set to true if all tracks should be mixed, to false if only the selected tracks should be mixed and exported.
metadata A Tags object that will over-ride the one in *project and be used to tag the file that is exported.
subformat Control which of the multiple formats this exporter is capable of exporting should be used. Used where a single export plug-in handles a number of related formats, but they have separate entries in the Format drop-down list box. For example, the options to export to "Other PCM", "AIFF 16 Bit" and "WAV 16 Bit" are all the same libsndfile export plug-in, but with subformat set to 0, 1, and 2 respectively.
Reimplemented in ExportCL, ExportFFmpeg, ExportFLAC, ExportMP2, ExportMP3, ExportOGG, and ExportPCM.
References DoExport(), and GetActiveProject().
bool ExportPlugin::GetCanMetaData (int index) [virtual]
References mFormatInfos.
wxString ExportPlugin::GetDescription (int index) [virtual]
References mFormatInfos.
Referenced by GetMask().
wxString ExportPlugin::GetExtension (int index = 0) [virtual]
Return the (first) file name extension for the sub-format.
Parameters:
index The sub-format for which the extension is wanted
Reimplemented in ExportPCM.
References mFormatInfos.
Referenced by GetMask(), and IsExtension().
wxArrayString ExportPlugin::GetExtensions (int index = 0) [virtual]
Return all the file name extensions used for the sub-format.
Parameters:
index the sub-format for which the extension is required
References mFormatInfos.
Referenced by GetMask(), and IsExtension().
wxString ExportPlugin::GetFormat (int index) [virtual]
References mFormatInfos.
int ExportPlugin::GetFormatCount () [virtual]
References mFormatInfos.
Referenced by IsExtension().
wxString ExportPlugin::GetMask (int index) [virtual]
References exts, GetDescription(), GetExtension(), GetExtensions(), and mFormatInfos.
int ExportPlugin::GetMaxChannels (int index) [virtual]
References mFormatInfos.
bool ExportPlugin::IsExtension (wxString & ext, int index) [virtual]
References GetExtension(), GetExtensions(), and GetFormatCount().
void ExportPlugin::SetCanMetaData (bool canmetadata, int index)
References mFormatInfos.
Referenced by ExportCL::ExportCL(), ExportFFmpeg::ExportFFmpeg(), ExportFLAC::ExportFLAC(), ExportMP2::ExportMP2(), ExportMP3::ExportMP3(), ExportOGG::ExportOGG(), and ExportPCM::ExportPCM().
void ExportPlugin::SetDescription (const wxString & description, int index)
References mFormatInfos.
Referenced by ExportCL::ExportCL(), ExportFFmpeg::ExportFFmpeg(), ExportFLAC::ExportFLAC(), ExportMP2::ExportMP2(), ExportMP3::ExportMP3(), ExportOGG::ExportOGG(), and ExportPCM::ExportPCM().
void ExportPlugin::SetExtensions (const wxArrayString & extensions, int index)
References mFormatInfos.
Referenced by ExportPCM::ExportPCM().
void ExportPlugin::SetFormat (const wxString & format, int index)
Parameters:
index The plugin to set the format for (range 0 to one less than the count of formats)
References mFormatInfos.
Referenced by ExportCL::ExportCL(), ExportFFmpeg::ExportFFmpeg(), ExportFLAC::ExportFLAC(), ExportMP2::ExportMP2(), ExportMP3::ExportMP3(), ExportOGG::ExportOGG(), and ExportPCM::ExportPCM().
void ExportPlugin::SetMask (const wxString & mask, int index)
References mFormatInfos.
void ExportPlugin::SetMaxChannels (int maxchannels, int index)
References mFormatInfos.
Referenced by ExportCL::ExportCL(), ExportFFmpeg::ExportFFmpeg(), ExportFLAC::ExportFLAC(), ExportMP2::ExportMP2(), ExportMP3::ExportMP3(), ExportOGG::ExportOGG(), and ExportPCM::ExportPCM().
Member Data Documentation
FormatInfoArray ExportPlugin::mFormatInfos [private]
Referenced by AddExtension(), AddFormat(), ExportPlugin(), GetCanMetaData(), GetDescription(), GetExtension(), GetExtensions(), GetFormat(), GetFormatCount(), GetMask(), GetMaxChannels(), SetCanMetaData(), SetDescription(), SetExtensions(), SetFormat(), SetMask(), SetMaxChannels(), and ~ExportPlugin().
The documentation for this class was generated from the following files:
Export.h
Export.cpp