Audacity: AudioIO Class Reference
AudioIO Class Reference
AudioIO uses the PortAudio library to play and record sound.
#include <AudioIO.h>
Public Member Functions
AudioIO ()
~AudioIO ()
AudioIOListener * GetListener ()
void SetListener (AudioIOListener *listener)
void StartMonitoring (double sampleRate)
Start up Portaudio for capture and recording as needed for input monitoring and software playthrough only.
int StartStream (WaveTrackArray playbackTracks, WaveTrackArray captureTracks, TimeTrack *timeTrack, double sampleRate, double t0, double t1, AudioIOListener *listener, bool playLooped=false, double cutPreviewGapStart=0.0, double cutPreviewGapLen=0.0)
Start recording or playing back audio.
void StopStream ()
Stop recording, playback or input monitoring.
void SeekStream (double seconds)
Move the playback / recording position of the current stream by the specified amount from where it is now.
bool IsBusy ()
Returns true if audio i/o is busy starting, stopping, playing, or recording.
bool IsStreamActive ()
Returns true if the audio i/o is running at all, but not during cleanup.
bool IsStreamActive (int token)
bool IsAudioTokenActive (int token)
Returns true if the stream is active, or even if audio I/O is busy cleaning up its data or writing to disk.
bool IsMonitoring ()
Returns true if we're monitoring input (but not recording or playing actual audio).
void SetPaused (bool state)
Pause and un-pause playback and recording.
bool IsPaused ()
Find out if playback / recording is currently paused.
void SetMixer (int inputSource, float inputVolume, float playbackVolume)
void GetMixer (int *inputSource, float *inputVolume, float *playbackVolume)
bool InputMixerWorks ()
Find out if the input hardware level control is available.
wxArrayString GetInputSourceNames ()
Get the list of inputs to the current mixer device.
void HandleDeviceChange ()
update state after changing what audio devices are selected
void SetMeters (Meter *inputMeter, Meter *outputMeter)
Set the current VU meters - this should be done once after each call to StartStream currently.
double GetStreamTime ()
The time the stream has been playing for.
sampleFormat GetCaptureFormat ()
int GetNumCaptureChannels ()
wxString GetDeviceInfo ()
Get diagnostic information on all the available audio I/O devices.
Static Public Member Functions
static wxArrayLong GetSupportedPlaybackRates (int DevIndex=-1, double rate=0.0)
Get a list of sample rates the output (playback) device supports.
static wxArrayLong GetSupportedCaptureRates (int devIndex=-1, double rate=0.0)
Get a list of sample rates the input (recording) device supports.
static wxArrayLong GetSupportedSampleRates (int playDevice=-1, int recDevice=-1, double rate=0.0)
Get a list of sample rates the current input/output device combination supports.
static int GetOptimalSupportedSampleRate ()
Get a supported sample rate which can be used a an optimal default.
static bool ValidateDeviceNames (wxString play, wxString rec)
Ensure selected device names are valid.
Static Public Attributes
static const int StandardRates []
Array of common audio sample rates.
static const int NumStandardRates
How many standard sample rates there are.
Private Member Functions
double GetBestRate (bool capturing, bool playing, double sampleRate)
Function to automatically set an acceptable volume.
bool StartPortAudioStream (double sampleRate, unsigned int numPlaybackChannels, unsigned int numCaptureChannels, sampleFormat captureFormat)
Opens the portaudio stream(s) used to do playback or recording (or both) through.
void FillBuffers ()
int GetCommonlyAvailPlayback ()
Get the number of audio samples free in all of the playback buffers.
int GetCommonlyAvailCapture ()
Get the number of audio samples ready in all of the recording buffers.
double NormalizeStreamTime (double absoluteTime) const
Static Private Member Functions
static int getRecordDevIndex (wxString devName=wxT(""))
get the index of the supplied (named) recording device, or the device selected in the preferences if none given.
static int getPlayDevIndex (wxString devName=wxT(""))
get the index of the supplied (named) playback device, or the device selected in the preferences if none given.
Private Attributes
AudioThread * mThread
Resample ** mResample
RingBuffer ** mCaptureBuffers
WaveTrackArray mCaptureTracks
RingBuffer ** mPlaybackBuffers
WaveTrackArray mPlaybackTracks
Mixer ** mPlaybackMixers
int mStreamToken
int mStopStreamCount
double mFactor
double mRate
double mT
double mT0
double mT1
double mTime
double mWarpedT1
double mSeek
double mPlaybackRingBufferSecs
double mCaptureRingBufferSecs
double mMaxPlaybackSecsToCopy
double mMinCaptureSecsToCopy
bool mPaused
PaStream * mPortStreamV19
bool mSoftwarePlaythrough
bool mPauseRec
float mSilenceLevel
unsigned int mNumCaptureChannels
unsigned int mNumPlaybackChannels
sampleFormat mCaptureFormat
float * mTempFloats
int mLostSamples
volatile bool mAudioThreadShouldCallFillBuffersOnce
volatile bool mAudioThreadFillBuffersLoopRunning
volatile bool mAudioThreadFillBuffersLoopActive
volatile double mLastRecordingOffset
PaError mLastPaError
Meter * mInputMeter
Meter * mOutputMeter
bool mUpdateMeters
bool mUpdatingMeters
bool mEmulateMixerOutputVol
bool mInputMixerWorks
Can we control the hardware input level?
float mMixerOutputVol
bool mPlayLooped
double mCutPreviewGapStart
double mCutPreviewGapLen
samplePtr mSilentBuf
sampleCount mLastSilentBufSize
AudioIOListener * mListener
TimeTrack * mTimeTrack
Static Private Attributes
static const int RatesToTry []
Array of audio sample rates to try to use.
static const int NumRatesToTry
How many sample rates to try.
static int mNextStreamToken = 0
static int mCachedPlaybackIndex = -1
static wxArrayLong mCachedPlaybackRates
static int mCachedCaptureIndex = -1
static wxArrayLong mCachedCaptureRates
static wxArrayLong mCachedSampleRates
static double mCachedBestRateIn = 0.0
static double mCachedBestRateOut
Friends
class AudioThread
void InitAudioIO ()
void DeinitAudioIO ()
int audacityAudioCallback (const void *inputBuffer, void *outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
Detailed Description
AudioIO uses the PortAudio library to play and record sound.
Great care and attention to detail are necessary for understanding and modifying this system. The code in this file is run from three different thread contexts: the UI thread, the disk thread (which this file creates and maintains) and the PortAudio callback thread. To highlight this deliniation, the file is divided into three parts based on what thread context each function is intended to run in.
Todo:
run through all functions called from audio and portaudio threads to verify they are thread-safe.
Constructor & Destructor Documentation
AudioIO::AudioIO ()
References AudioThread, HandleDeviceChange(), LAT1CTOWX, mAudioThreadFillBuffersLoopActive, mAudioThreadFillBuffersLoopRunning, mAudioThreadShouldCallFillBuffersOnce, mEmulateMixerOutputVol, mInputMixerWorks, mLastPaError, mLastRecordingOffset, mLastSilentBufSize, mListener, mMixerOutputVol, mNumCaptureChannels, mPaused, mPlayLooped, mPortStreamV19, mSilentBuf, mStopStreamCount, mStreamToken, mTempFloats, mThread, mUpdateMeters, and mUpdatingMeters.
AudioIO::~AudioIO ()
References DeleteSamples(), mSilentBuf, mTempFloats, and mThread.
Member Function Documentation
void AudioIO::FillBuffers () [private]
References ClearSamples(), DeleteSamples(), XMLWriter::EndTag(), floatSample, RingBuffer::Get(), Mixer::GetBuffer(), GetCommonlyAvailCapture(), GetCommonlyAvailPlayback(), IsStreamActive(), mAudioThreadShouldCallFillBuffersOnce, mCaptureBuffers, mCaptureTracks, mFactor, mLastSilentBufSize, mListener, mMaxPlaybackSecsToCopy, mMinCaptureSecsToCopy, mPlaybackBuffers, mPlaybackMixers, mPlaybackTracks, mPlayLooped, mRate, mResample, mSilentBuf, mT, mT0, mWarpedT1, NewSamples(), AudioIOListener::OnAudioIONewBlockFiles(), Resample::Process(), Mixer::Process(), RingBuffer::Put(), XMLWriter::StartTag(), XMLWriter::WriteAttr(), and XMLWriter::WriteSubTree().
Referenced by AudioThread::Entry().
double AudioIO::GetBestRate (bool capturing, bool playing, double sampleRate) [private]
Function to automatically set an acceptable volume.
Return a valid sample rate that is supported by the current I/O device(s). The return from this function is used to determine the sample rate that audacity actually runs the audio I/O stream at. if there is no suitable rate available from the hardware, it returns 0. The sampleRate argument gives the desired sample rate (the rate of the audio to be handeled, i.e. the currently Project Rate). capturing is true if the stream is capturing one or more audio channels, and playing is true if one or more channels are being played.
References GetSupportedCaptureRates(), GetSupportedPlaybackRates(), GetSupportedSampleRates(), mCachedBestRateIn, and mCachedBestRateOut.
Referenced by StartPortAudioStream().
sampleFormat AudioIO::GetCaptureFormat () [inline]
Referenced by AudacityProject::OnTimer().
int AudioIO::GetCommonlyAvailCapture () [private]
Get the number of audio samples ready in all of the recording buffers.
Returns the smallest of the number of samples available for storage in the recording buffers (i.e. the number of samples that can be read from all record buffers without underflow).
References RingBuffer::AvailForGet(), mCaptureBuffers, and mCaptureTracks.
Referenced by FillBuffers().
int AudioIO::GetCommonlyAvailPlayback () [private]
Get the number of audio samples free in all of the playback buffers.
Returns the smallest of the buffer free space values in the event that they are different.
References RingBuffer::AvailForPut(), mPlaybackBuffers, and mPlaybackTracks.
Referenced by FillBuffers().
wxString AudioIO::GetDeviceInfo ()
Get diagnostic information on all the available audio I/O devices.
References audacityAudioCallback, DEFAULT_LATENCY_CORRECTION, DeviceName(), GetSupportedPlaybackRates(), GetSupportedSampleRates(), gPrefs, IsStreamActive(), and name.
Referenced by AudacityProject::OnAudioDeviceInfo().
wxArrayString AudioIO::GetInputSourceNames ()
Get the list of inputs to the current mixer device.
Returns an array of strings giving the names of the inputs to the soundcard mixer (driven by PortMixer)
Referenced by MixerToolBar::Populate(), and MixerToolBar::UpdatePrefs().
AudioIOListener* AudioIO::GetListener () [inline]
Referenced by AudacityProject::OnCloseWindow().
void AudioIO::GetMixer (int * inputSource, float * inputVolume, float * playbackVolume)
References mEmulateMixerOutputVol, mInputMixerWorks, and mMixerOutputVol.
Referenced by MixerToolBar::Populate(), MixerToolBar::UpdateControls(), and MixerToolBar::UpdatePrefs().
int AudioIO::GetNumCaptureChannels () [inline]
Referenced by TrackPanel::DoDrawIndicator(), AudacityProject::OnCloseWindow(), TrackPanel::OnTimer(), and AudacityProject::OnTimer().
int AudioIO::GetOptimalSupportedSampleRate () [static]
Get a supported sample rate which can be used a an optimal default.
Currently, this uses the first supported rate in the list [44100, 48000, highest sample rate]. Used in Project as a default value for project rates if one cannot be retrieved from the preferences. So all in all not that useful or important really
Todo:
: should this take into account PortAudio's value for PaDeviceInfo::defaultSampleRate? In principal this should let us work out which rates are "real" and which resampled in the drivers, and so prefer the real rates.
References GetSupportedSampleRates().
Referenced by QualityPrefs::PopulateOrExchange(), SelectionBar::UpdatePrefs(), and AudacityProject::UpdatePrefsVariables().
int AudioIO::getPlayDevIndex (wxString devName = wxT("")) [static, private]
get the index of the supplied (named) playback device, or the device selected in the preferences if none given.
Pure utility function, but it comes round a number of times in the code and would be neater done once. If the device isn't found, return the default device index.
References DeviceName(), and gPrefs.
Referenced by GetSupportedPlaybackRates(), GetSupportedSampleRates(), HandleDeviceChange(), InitAudioIO(), StartPortAudioStream(), and ValidateDeviceNames().
int AudioIO::getRecordDevIndex (wxString devName = wxT("")) [static, private]
get the index of the supplied (named) recording device, or the device selected in the preferences if none given.
Pure utility function, but it comes round a number of times in the code and would be neater done once. If the device isn't found, return the default device index.
References DeviceName(), and gPrefs.
Referenced by GetSupportedCaptureRates(), GetSupportedSampleRates(), HandleDeviceChange(), InitAudioIO(), StartPortAudioStream(), and ValidateDeviceNames().
double AudioIO::GetStreamTime ()
The time the stream has been playing for.
This is given in seconds based on starting at t0 When playing looped, this will start from t0 again, too. So the returned time should be always between t0 and t1
References IsStreamActive(), mTime, and NormalizeStreamTime().
Referenced by TrackPanel::DoDrawIndicator(), AudacityProject::OnAddLabelPlaying(), TrackPanel::OnBoundaryMove(), AudacityProject::OnPlayStopSelect(), AudacityProject::OnSetLeftSelection(), AudacityProject::OnSetRightSelection(), AudacityProject::OnStopSelect(), TrackPanel::OnTimer(), AudacityProject::OnZoomIn(), Effect::Preview(), AudacityProject::TP_DisplaySelection(), and AudacityProject::UpdateMixerBoard().
wxArrayLong AudioIO::GetSupportedCaptureRates (int devIndex = -1, double rate = 0.0) [static]
Get a list of sample rates the input (recording) device supports.
If no information about available sample rates can be fetched, an empty list is returned.
You can explicitely give the index of the device. If you don't give it, the currently selected device from the preferences will be used.
You may also specify a rate for which to check in addition to the standard rates.
References DEFAULT_LATENCY_DURATION, getRecordDevIndex(), gPrefs, mCachedCaptureIndex, mCachedCaptureRates, NumRatesToTry, and RatesToTry.
Referenced by GetBestRate(), GetSupportedSampleRates(), and HandleDeviceChange().
wxArrayLong AudioIO::GetSupportedPlaybackRates (int DevIndex = -1, double rate = 0.0) [static]
Get a list of sample rates the output (playback) device supports.
If no information about available sample rates can be fetched, an empty list is returned.
You can explicitely give the index of the device. If you don't give it, the currently selected device from the preferences will be used.
You may also specify a rate for which to check in addition to the standard rates.
References getPlayDevIndex(), mCachedPlaybackIndex, mCachedPlaybackRates, NumRatesToTry, and RatesToTry.
Referenced by GetBestRate(), GetDeviceInfo(), GetSupportedSampleRates(), and HandleDeviceChange().
wxArrayLong AudioIO::GetSupportedSampleRates (int playDevice = -1, int recDevice = -1, double rate = 0.0) [static]
Get a list of sample rates the current input/output device combination supports.
Since there is no concept (yet) for different input/output sample rates, this currently returns only sample rates that are supported on both the output and input device. If no information about available sample rates can be fetched, it returns a default list. You can explicitely give the indexes of the playDevice/recDevice. If you don't give them, the selected devices from the preferences will be used. You may also specify a rate for which to check in addition to the standard rates.
References getPlayDevIndex(), getRecordDevIndex(), GetSupportedCaptureRates(), GetSupportedPlaybackRates(), mCachedCaptureIndex, mCachedPlaybackIndex, and mCachedSampleRates.
Referenced by GetBestRate(), GetDeviceInfo(), GetOptimalSupportedSampleRate(), and HandleDeviceChange().
void AudioIO::HandleDeviceChange ()
update state after changing what audio devices are selected
Called when the devices stored in the preferences are changed to update the audio mixer capabilities
Todo:
: Make this do a sample rate query and store the result in the AudioIO object to avoid doing it later? Would simplify the GetSupported*Rate functions considerably
References audacityAudioCallback, DEFAULT_LATENCY_CORRECTION, getPlayDevIndex(), getRecordDevIndex(), GetSupportedCaptureRates(), GetSupportedPlaybackRates(), GetSupportedSampleRates(), IsStreamActive(), mCachedBestRateIn, mCachedCaptureIndex, mCachedCaptureRates, mCachedPlaybackIndex, mCachedPlaybackRates, mCachedSampleRates, mEmulateMixerOutputVol, mInputMixerWorks, and mMixerOutputVol.
Referenced by AudioIO(), DeviceToolBar::OnChoice(), and PrefsDialog::OnOK().
bool AudioIO::InputMixerWorks ()
Find out if the input hardware level control is available.
Checks the mInputMixerWorks variable, which is set up in AudioIO::HandleDeviceChange(). External people care, because we want to disable the UI if it doesn't work.
References mInputMixerWorks.
Referenced by MixerToolBar::Populate(), and MixerToolBar::UpdatePrefs().
bool AudioIO::IsAudioTokenActive (int token)
Returns true if the stream is active, or even if audio I/O is busy cleaning up its data or writing to disk.
This is used by TrackPanel to determine when a track has been completely recorded, and it's safe to flush to disk.
References mStreamToken.
Referenced by AudacityProject::GetUpdateFlags(), and TrackPanel::OnTimer().
bool AudioIO::IsBusy ()
Returns true if audio i/o is busy starting, stopping, playing, or recording.
When this is false, it's safe to start playing or recording
References mStreamToken.
Referenced by MeterToolBar::DestroyChildren(), ControlToolBar::EnableDisableButtons(), AudacityProject::MakeReadyToPlay(), TranscriptionToolBar::OnAutomateSelection(), EditToolBar::OnButton(), TranscriptionToolBar::OnCalibrate(), AudacityProject::OnCloseWindow(), TranscriptionToolBar::OnEndOff(), TranscriptionToolBar::OnEndOn(), TranscriptionToolBar::OnKeyEvent(), ControlToolBar::OnKeyEvent(), TranscriptionToolBar::OnPlaySpeed(), AudacityProject::OnPlayStop(), AudacityProject::OnPlayStopSelect(), ControlToolBar::OnRecord(), TranscriptionToolBar::OnSelectSilence(), TranscriptionToolBar::OnSelectSound(), TranscriptionToolBar::OnStartOff(), TranscriptionToolBar::OnStartOn(), ControlToolBar::PlayPlayRegion(), MeterToolBar::Populate(), Effect::Preview(), TrackPanel::SelectionHandleClick(), SetListener(), StartStream(), and AudacityProject::TP_DisplaySelection().
bool AudioIO::IsMonitoring ()
Returns true if we're monitoring input (but not recording or playing actual audio).
References mPortStreamV19, and mStreamToken.
Referenced by AudacityProject::OnCloseWindow(), Meter::OnDisableMeter(), Meter::OnMouse(), Meter::StartMonitoring(), and Meter::~Meter().
bool AudioIO::IsPaused ()
Find out if playback / recording is currently paused.
References mPaused.
Referenced by audacityAudioCallback(), TrackPanel::DoDrawIndicator(), TrackPanel::OnPaint(), and TrackPanel::OnTimer().
bool AudioIO::IsStreamActive (int token)
References IsStreamActive(), and mStreamToken.
bool AudioIO::IsStreamActive ()
Returns true if the audio i/o is running at all, but not during cleanup.
Doesn't return true if the device has been closed but some disk i/o or cleanup is still going on. If you want to know if it's safe to start a new stream, use IsBusy()
References mPortStreamV19.
Referenced by LabelTrack::CaptureKey(), TrackPanel::DoDrawIndicator(), FillBuffers(), GetDeviceInfo(), GetStreamTime(), TrackPanel::HandleClosing(), HandleDeviceChange(), TrackPanel::HandleLabelClick(), TrackPanel::HandleTrackSpecificMouseEvent(), IsStreamActive(), TrackPanel::IsUnsafe(), AudacityProject::MakeReadyToPlay(), AudacityProject::OnAddLabelPlaying(), TrackPanel::OnBoundaryMove(), AudacityProject::OnCloseWindow(), TrackPanel::OnCursorLeft(), TrackPanel::OnCursorMove(), TrackPanel::OnCursorRight(), ControlToolBar::OnKeyEvent(), TrackPanel::OnPaint(), AudacityProject::OnPlayStop(), AudacityProject::OnPlayStopSelect(), AudacityProject::OnSetLeftSelection(), AudacityProject::OnSetRightSelection(), AudacityProject::OnStop(), AudacityProject::OnStopSelect(), TrackPanel::OnTimer(), TrackPanel::OnTrackClose(), AudacityProject::OnZoomIn(), Effect::Preview(), and AudacityProject::PushState().
double AudioIO::NormalizeStreamTime (double absoluteTime) const [private]
References mCutPreviewGapLen, mCutPreviewGapStart, mT0, and mT1.
Referenced by GetStreamTime().
void AudioIO::SeekStream (double seconds) [inline]
Move the playback / recording position of the current stream by the specified amount from where it is now.
Referenced by TrackPanel::OnCursorLeft(), TrackPanel::OnCursorMove(), TrackPanel::OnCursorRight(), and ControlToolBar::PlayPlayRegion().
void AudioIO::SetListener (AudioIOListener * listener)
References IsBusy(), and mListener.
Referenced by CreateNewAudacityProject(), and AudacityProject::OnCloseWindow().
void AudioIO::SetMeters (Meter * inputMeter, Meter * outputMeter)
Set the current VU meters - this should be done once after each call to StartStream currently.
References mInputMeter, mOutputMeter, mRate, mUpdateMeters, and Meter::Reset().
Referenced by MeterToolBar::DestroyChildren(), MeterToolBar::Populate(), ControlToolBar::SetVUMeters(), and Meter::StartMonitoring().
void AudioIO::SetMixer (int inputSource, float inputVolume, float playbackVolume)
References mMixerOutputVol.
Referenced by MixerToolBar::SetMixer(), and MixerToolBar::UpdateControls().
void AudioIO::SetPaused (bool state)
Pause and un-pause playback and recording.
References mPaused.
Referenced by ControlToolBar::OnPause(), and ControlToolBar::StopPlaying().
void AudioIO::StartMonitoring (double sampleRate)
Start up Portaudio for capture and recording as needed for input monitoring and software playthrough only.
This uses the Default project sample format, current sample rate, and selected number of input channels to open the recording device and start reading input data. If software playthrough is enabled, it also opens the output device in stereo to play the data through
References floatSample, gPrefs, mLastPaError, mPortStreamV19, mSoftwarePlaythrough, mStreamToken, and StartPortAudioStream().
Referenced by Meter::StartMonitoring().
bool AudioIO::StartPortAudioStream (double sampleRate, unsigned int numPlaybackChannels, unsigned int numCaptureChannels, sampleFormat captureFormat) [private]
Opens the portaudio stream(s) used to do playback or recording (or both) through.
The sampleRate passed is the Project Rate of the active project. It may or may not be actually supported by playback or recording hardware currently in use (for many reasons). The number of Capture and Playback channels requested includes an allocation for doing software playthrough if necessary. The captureFormat is used for recording only, the playback being floating point always. Returns true if the stream opened sucessfully and false if it did not.
References audacityAudioCallback, AudacityToPortAudioSampleFormat(), DEFAULT_LATENCY_DURATION, floatSample, GetBestRate(), getPlayDevIndex(), getRecordDevIndex(), gPrefs, int24Sample, mCaptureFormat, mLastPaError, mListener, mNumCaptureChannels, mNumPlaybackChannels, mPortStreamV19, mRate, mSoftwarePlaythrough, and AudioIOListener::OnAudioIORate().
Referenced by StartMonitoring(), and StartStream().
int AudioIO::StartStream (WaveTrackArray playbackTracks, WaveTrackArray captureTracks, TimeTrack * timeTrack, double sampleRate, double t0, double t1, AudioIOListener * listener, bool playLooped = false, double cutPreviewGapStart = 0.0, double cutPreviewGapLen = 0.0)
Start recording or playing back audio.
Allocates buffers for recording and playback, gets the Audio thread to fill them, and sets the stream rolling. If successful, returns a token identifying this particular stream instance. For use with IsStreamActive() below
References Mixer::ApplyTrackGains(), Envelope::Average(), ENV_DB_RANGE, floatSample, TimeTrack::GetEnvelope(), TimeTrack::GetRangeLower(), TimeTrack::GetRangeUpper(), gPrefs, IsBusy(), mAudioThreadFillBuffersLoopRunning, mAudioThreadShouldCallFillBuffersOnce, mCaptureBuffers, mCaptureRingBufferSecs, mCaptureTracks, mCutPreviewGapLen, mCutPreviewGapStart, mFactor, mInputMeter, mLastRecordingOffset, mListener, mMaxPlaybackSecsToCopy, mMinCaptureSecsToCopy, mNextStreamToken, mNumCaptureChannels, mNumPlaybackChannels, mOutputMeter, mPauseRec, mPlaybackBuffers, mPlaybackMixers, mPlaybackRingBufferSecs, mPlaybackTracks, mPlayLooped, mPortStreamV19, mRate, mResample, mSeek, mSilenceLevel, mSoftwarePlaythrough, mStreamToken, mT, mT0, mT1, mTime, mTimeTrack, mWarpedT1, AudioIOListener::OnAudioIOStartRecording(), AudioIOListener::OnAudioIOStopRecording(), StartPortAudioStream(), and StopStream().
Referenced by ControlToolBar::OnRecord(), ControlToolBar::PlayPlayRegion(), and Effect::Preview().
void AudioIO::StopStream ()
Stop recording, playback or input monitoring.
Does quite a bit of housekeeping, including switching off monitoring, flushing recording buffers out to wave tracks, and applies latency correction to recorded tracks if necessary
References WaveTrack::Clear(), DEFAULT_LATENCY_CORRECTION, WaveTrack::Flush(), GetActiveProject(), WaveTrack::GetEndTime(), WaveTrack::GetStartTime(), AudacityProject::GetTracks(), TrackList::GetWaveTrackArray(), gPrefs, WaveTrack::InsertSilence(), mAudioThreadFillBuffersLoopRunning, mAudioThreadShouldCallFillBuffersOnce, mCaptureBuffers, mCaptureTracks, mInputMeter, mLastRecordingOffset, mListener, mNumCaptureChannels, mOutputMeter, mPlaybackBuffers, mPlaybackMixers, mPlaybackTracks, mPortStreamV19, mRate, mResample, mStopStreamCount, mStreamToken, mT0, mUpdateMeters, mUpdatingMeters, AudioIOListener::OnAudioIOStopRecording(), Meter::Reset(), WaveTrack::SetOffset(), and wxGetApp().
Referenced by AudacityProject::OnCloseWindow(), Meter::OnDisableMeter(), Effect::Preview(), Meter::StartMonitoring(), StartStream(), ControlToolBar::StopPlaying(), and Meter::~Meter().
bool AudioIO::ValidateDeviceNames (wxString play, wxString rec) [static]
Ensure selected device names are valid.
References getPlayDevIndex(), and getRecordDevIndex().
Friends And Related Function Documentation
int audacityAudioCallback (const void * inputBuffer, void * outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData) [friend]
brief The function which is called from PortAudio's callback thread context to collect and deliver audio for / from the sound device.
This covers recording, playback, and doing both simultaneously. It is also invoked to do monitoring and software playthrough. Note that dealing with the two buffers needs some care to ensure that the right things happen for all possible cases.
Parameters:
inputBuffer Buffer of length framesPerBuffer containing samples from the sound card, or null if not capturing audio. Note that the data type will depend on the format of audio data that was chosen when the stream was created (so could be floats or various integers)
outputBuffer Uninitialised buffer of length framesPerBuffer which will be sent to the sound card after the callback, or null if not playing audio back.
framesPerBuffer The length of the playback and recording buffers
PaStreamCallbackTimeInfo Pointer to PortAudio time information structure, which tells us how long we have been playing / recording
statusFlags PortAudio stream status flags
userData pointer to user-defined data structure. Provided for flexibility by PortAudio, but not used by Audacity - the data is stored in the AudioIO class instead.
Referenced by GetDeviceInfo(), HandleDeviceChange(), and StartPortAudioStream().
friend class AudioThread [friend]
Referenced by AudioIO().
void DeinitAudioIO () [friend]
void InitAudioIO () [friend]
Member Data Documentation
volatile bool AudioIO::mAudioThreadFillBuffersLoopActive [private]
Referenced by audacityAudioCallback(), AudioIO(), and AudioThread::Entry().
volatile bool AudioIO::mAudioThreadFillBuffersLoopRunning [private]
Referenced by audacityAudioCallback(), AudioIO(), AudioThread::Entry(), StartStream(), and StopStream().
volatile bool AudioIO::mAudioThreadShouldCallFillBuffersOnce [private]
Referenced by audacityAudioCallback(), AudioIO(), AudioThread::Entry(), FillBuffers(), StartStream(), and StopStream().
double AudioIO::mCachedBestRateIn = 0.0 [static, private]
Referenced by GetBestRate(), and HandleDeviceChange().
double AudioIO::mCachedBestRateOut [static, private]
Referenced by GetBestRate().
int AudioIO::mCachedCaptureIndex = -1 [static, private]
Referenced by GetSupportedCaptureRates(), GetSupportedSampleRates(), and HandleDeviceChange().
wxArrayLong AudioIO::mCachedCaptureRates [static, private]
Referenced by GetSupportedCaptureRates(), and HandleDeviceChange().
int AudioIO::mCachedPlaybackIndex = -1 [static, private]
Referenced by GetSupportedPlaybackRates(), GetSupportedSampleRates(), and HandleDeviceChange().
wxArrayLong AudioIO::mCachedPlaybackRates [static, private]
Referenced by GetSupportedPlaybackRates(), and HandleDeviceChange().
wxArrayLong AudioIO::mCachedSampleRates [static, private]
Referenced by GetSupportedSampleRates(), and HandleDeviceChange().
RingBuffer** AudioIO::mCaptureBuffers [private]
Referenced by audacityAudioCallback(), FillBuffers(), GetCommonlyAvailCapture(), StartStream(), and StopStream().
sampleFormat AudioIO::mCaptureFormat [private]
Referenced by audacityAudioCallback(), and StartPortAudioStream().
double AudioIO::mCaptureRingBufferSecs [private]
Referenced by StartStream().
WaveTrackArray AudioIO::mCaptureTracks [private]
Referenced by FillBuffers(), GetCommonlyAvailCapture(), StartStream(), and StopStream().
double AudioIO::mCutPreviewGapLen [private]
Referenced by NormalizeStreamTime(), and StartStream().
double AudioIO::mCutPreviewGapStart [private]
Referenced by NormalizeStreamTime(), and StartStream().
bool AudioIO::mEmulateMixerOutputVol [private]
Referenced by audacityAudioCallback(), AudioIO(), GetMixer(), and HandleDeviceChange().
double AudioIO::mFactor [private]
Referenced by FillBuffers(), and StartStream().
Meter* AudioIO::mInputMeter [private]
Referenced by audacityAudioCallback(), SetMeters(), StartStream(), and StopStream().
bool AudioIO::mInputMixerWorks [private]
Can we control the hardware input level?
This flag is set to true if using portmixer to control the input volume seems to be working (and so we offer the user the control), and to false (locking the control out) otherwise. This avoids stupid scaled clipping problems when trying to do software emulated input volume control
Referenced by AudioIO(), GetMixer(), HandleDeviceChange(), and InputMixerWorks().
PaError AudioIO::mLastPaError [private]
Referenced by AudioIO(), StartMonitoring(), and StartPortAudioStream().
volatile double AudioIO::mLastRecordingOffset [private]
Referenced by audacityAudioCallback(), AudioIO(), StartStream(), and StopStream().
sampleCount AudioIO::mLastSilentBufSize [private]
Referenced by AudioIO(), and FillBuffers().
AudioIOListener* AudioIO::mListener [private]
Referenced by AudioIO(), FillBuffers(), SetListener(), StartPortAudioStream(), StartStream(), and StopStream().
int AudioIO::mLostSamples [private]
Referenced by audacityAudioCallback().
double AudioIO::mMaxPlaybackSecsToCopy [private]
Referenced by FillBuffers(), and StartStream().
double AudioIO::mMinCaptureSecsToCopy [private]
Referenced by FillBuffers(), and StartStream().
float AudioIO::mMixerOutputVol [private]
Referenced by audacityAudioCallback(), AudioIO(), GetMixer(), HandleDeviceChange(), and SetMixer().
int AudioIO::mNextStreamToken = 0 [static, private]
Referenced by StartStream().
unsigned int AudioIO::mNumCaptureChannels [private]
Referenced by audacityAudioCallback(), AudioIO(), StartPortAudioStream(), StartStream(), and StopStream().
unsigned int AudioIO::mNumPlaybackChannels [private]
Referenced by audacityAudioCallback(), StartPortAudioStream(), and StartStream().
Meter* AudioIO::mOutputMeter [private]
Referenced by audacityAudioCallback(), SetMeters(), StartStream(), and StopStream().
bool AudioIO::mPaused [private]
Referenced by audacityAudioCallback(), AudioIO(), IsPaused(), and SetPaused().
bool AudioIO::mPauseRec [private]
Referenced by audacityAudioCallback(), and StartStream().
RingBuffer** AudioIO::mPlaybackBuffers [private]
Referenced by audacityAudioCallback(), FillBuffers(), GetCommonlyAvailPlayback(), StartStream(), and StopStream().
Mixer** AudioIO::mPlaybackMixers [private]
Referenced by audacityAudioCallback(), FillBuffers(), StartStream(), and StopStream().
double AudioIO::mPlaybackRingBufferSecs [private]
Referenced by StartStream().
WaveTrackArray AudioIO::mPlaybackTracks [private]
Referenced by audacityAudioCallback(), FillBuffers(), GetCommonlyAvailPlayback(), StartStream(), and StopStream().
bool AudioIO::mPlayLooped [private]
Referenced by audacityAudioCallback(), AudioIO(), FillBuffers(), and StartStream().
PaStream* AudioIO::mPortStreamV19 [private]
Referenced by audacityAudioCallback(), AudioIO(), IsMonitoring(), IsStreamActive(), StartMonitoring(), StartPortAudioStream(), StartStream(), and StopStream().
double AudioIO::mRate [private]
Referenced by audacityAudioCallback(), FillBuffers(), SetMeters(), StartPortAudioStream(), StartStream(), and StopStream().
Resample** AudioIO::mResample [private]
Referenced by FillBuffers(), StartStream(), and StopStream().
double AudioIO::mSeek [private]
Referenced by audacityAudioCallback(), and StartStream().
float AudioIO::mSilenceLevel [private]
Referenced by audacityAudioCallback(), and StartStream().
samplePtr AudioIO::mSilentBuf [private]
Referenced by AudioIO(), FillBuffers(), and ~AudioIO().
bool AudioIO::mSoftwarePlaythrough [private]
Referenced by audacityAudioCallback(), StartMonitoring(), StartPortAudioStream(), and StartStream().
int AudioIO::mStopStreamCount [private]
Referenced by AudioIO(), and StopStream().
int AudioIO::mStreamToken [private]
Referenced by audacityAudioCallback(), AudioIO(), IsAudioTokenActive(), IsBusy(), IsMonitoring(), IsStreamActive(), StartMonitoring(), StartStream(), and StopStream().
double AudioIO::mT [private]
Referenced by audacityAudioCallback(), FillBuffers(), and StartStream().
double AudioIO::mT0 [private]
Referenced by audacityAudioCallback(), FillBuffers(), NormalizeStreamTime(), StartStream(), and StopStream().
double AudioIO::mT1 [private]
Referenced by audacityAudioCallback(), NormalizeStreamTime(), and StartStream().
float* AudioIO::mTempFloats [private]
Referenced by AudioIO(), and ~AudioIO().
AudioThread* AudioIO::mThread [private]
Referenced by AudioIO(), InitAudioIO(), and ~AudioIO().
double AudioIO::mTime [private]
Referenced by audacityAudioCallback(), GetStreamTime(), and StartStream().
TimeTrack* AudioIO::mTimeTrack [private]
Referenced by audacityAudioCallback(), and StartStream().
bool AudioIO::mUpdateMeters [private]
Referenced by audacityAudioCallback(), AudioIO(), SetMeters(), and StopStream().
bool AudioIO::mUpdatingMeters [private]
Referenced by audacityAudioCallback(), AudioIO(), and StopStream().
double AudioIO::mWarpedT1 [private]
Referenced by FillBuffers(), and StartStream().
const int AudioIO::NumRatesToTry [static, private]
Initial value:
 sizeof(AudioIO::RatesToTry) /
                                      sizeof(AudioIO::RatesToTry[0])
How many sample rates to try.
Referenced by GetSupportedCaptureRates(), and GetSupportedPlaybackRates().
const int AudioIO::NumStandardRates [static]
Initial value:
 sizeof(AudioIO::StandardRates) /
                                      sizeof(AudioIO::StandardRates[0])
How many standard sample rates there are.
Referenced by QualityPrefs::GetNamesAndLabels(), and SelectionBar::UpdateRates().
const int AudioIO::RatesToTry [static, private]
Initial value:
 {
   8000,
   9600,
   11025,
   12000,
   15000,
   16000,
   22050,
   24000,
   32000,
   44100,
   48000,
   88200,
   96000,
   192000
}
Array of audio sample rates to try to use.
These are the rates we will check if a device supports, and is as long as I can think of (to try and work out what the card can do)
Referenced by GetSupportedCaptureRates(), and GetSupportedPlaybackRates().
const int AudioIO::StandardRates [static]
Initial value:
 {
   8000,
   11025,
   16000,
   22050,
   32000,
   44100,
   48000,
   96000
}
Array of common audio sample rates.
These are the rates we will always support, regardless of hardware support for them (by resampling in audacity if needed)
Referenced by QualityPrefs::GetNamesAndLabels(), and SelectionBar::UpdateRates().
The documentation for this class was generated from the following files:
AudioIO.h
AudioIO.cpp