Audacity: VisibleTrackIterator Class Reference
VisibleTrackIterator Class Reference
#include <Track.h>
Public Member Functions
VisibleTrackIterator (AudacityProject *project)
virtual ~VisibleTrackIterator ()
Protected Member Functions
bool Condition (Track *t)
Private Attributes
AudacityProject * mProject
wxRect mPanelRect
Constructor & Destructor Documentation
VisibleTrackIterator::VisibleTrackIterator (AudacityProject * project)
References AudacityProject::GetTPTracksUsableArea(), mPanelRect, mProject, AudacityProject::mViewInfo, and ViewInfo::vpos.
virtual VisibleTrackIterator::~VisibleTrackIterator () [inline, virtual]
Member Function Documentation
bool VisibleTrackIterator::Condition (Track * t) [protected, virtual]
Implements TrackListCondIterator.
References Track::GetHeight(), Track::GetY(), and mPanelRect.
Member Data Documentation
wxRect VisibleTrackIterator::mPanelRect [private]
Referenced by Condition(), and VisibleTrackIterator().
AudacityProject* VisibleTrackIterator::mProject [private]
Referenced by VisibleTrackIterator().
The documentation for this class was generated from the following files:
Track.h
Track.cpp