Audacity: LyricsWindow Class Reference
LyricsWindow Class Reference
#include <LyricsWindow.h>
Public Member Functions
LyricsWindow (AudacityProject *parent)
virtual ~LyricsWindow ()
Lyrics * GetLyricsPanel ()
Private Member Functions
void OnCloseWindow (wxCloseEvent &WXUNUSED(event))
void OnStyle_BouncingBall (wxCommandEvent &evt)
void OnStyle_Highlight (wxCommandEvent &evt)
Private Attributes
AudacityProject * mProject
Lyrics * mLyricsPanel
Constructor & Destructor Documentation
LyricsWindow::LyricsWindow (AudacityProject * parent)
LyricsWindow::~LyricsWindow () [virtual]
Member Function Documentation
Lyrics* LyricsWindow::GetLyricsPanel () [inline]
References mLyricsPanel.
Referenced by TrackPanel::HandleSelect(), TrackPanel::OnTimer(), and AudacityProject::UpdateLyrics().
void LyricsWindow::OnCloseWindow (wxCloseEvent & WXUNUSEDevent) [private]
void LyricsWindow::OnStyle_BouncingBall (wxCommandEvent & evt) [private]
References Lyrics::kBouncingBallLyrics, mLyricsPanel, and Lyrics::SetLyricsStyle().
void LyricsWindow::OnStyle_Highlight (wxCommandEvent & evt) [private]
References Lyrics::kHighlightLyrics, mLyricsPanel, and Lyrics::SetLyricsStyle().
Member Data Documentation
Lyrics* LyricsWindow::mLyricsPanel [private]
Referenced by GetLyricsPanel(), OnStyle_BouncingBall(), and OnStyle_Highlight().
AudacityProject* LyricsWindow::mProject [private]
The documentation for this class was generated from the following files:
LyricsWindow.h
LyricsWindow.cpp