Audacity: FFmpegImportPlugin Class Reference
FFmpegImportPlugin Class Reference
An ImportPlugin for FFmpeg data.
Public Member Functions
FFmpegImportPlugin ()
~FFmpegImportPlugin ()
wxString GetPluginFormatDescription ()
ImportFileHandle * Open (wxString Filename)
! Probes the file and opens it if appropriate
Detailed Description
An ImportPlugin for FFmpeg data.
A representative of FFmpeg loader in the Audacity import plugin list
Constructor & Destructor Documentation
FFmpegImportPlugin::FFmpegImportPlugin () [inline]
FFmpegImportPlugin::~FFmpegImportPlugin () [inline]
Member Function Documentation
wxString FFmpegImportPlugin::GetPluginFormatDescription () [virtual]
Implements ImportPlugin.
References DESC.
ImportFileHandle * FFmpegImportPlugin::Open (wxString Filename) [virtual]
! Probes the file and opens it if appropriate
Implements ImportPlugin.
References gPrefs, FFmpegImportFileHandle::Init(), ImportPlugin::SupportsExtension(), and FFmpegLibs::ValidLibsLoaded().
The documentation for this class was generated from the following file:
ImportFFmpeg.cpp