Audacity: Matrix Class Reference
Matrix Class Reference
Holds a matrix of doubles and supports arithmetic, subsetting, and matrix inversion. Used by InterpolateAudio.
#include <Matrix.h>
Public Member Functions
Matrix (const Matrix &copyFrom)
Matrix (int rows, int cols, double **data=NULL)
virtual ~Matrix ()
Matrix & operator= (const Matrix &other)
Vector & operator[] (int i)
Vector & operator[] (int i) const
int Rows () const
int Cols () const
void SwapRows (int i, int j)
double Sum () const
Private Member Functions
void CopyFrom (const Matrix &other)
Private Attributes
int mRows
int mCols
Vector ** mRowVec
Detailed Description
Holds a matrix of doubles and supports arithmetic, subsetting, and matrix inversion. Used by InterpolateAudio.
Constructor & Destructor Documentation
Matrix::Matrix (const Matrix & copyFrom)
References CopyFrom().
Matrix::Matrix (int rows, int cols, double ** data = NULL)
References mCols, mRows, and mRowVec.
Matrix::~Matrix () [virtual]
References mRows, and mRowVec.
Member Function Documentation
int Matrix::Cols () const [inline]
References mCols.
Referenced by InterpolateAudio(), InvertMatrix(), MatrixConcatenateCols(), MatrixMultiply(), operator*(), operator+(), ScalarMultiply(), Sum(), and TransposeMatrix().
void Matrix::CopyFrom (const Matrix & other) [private]
References mCols, mRows, and mRowVec.
Referenced by Matrix(), and operator=().
Matrix & Matrix::operator= (const Matrix & other)
References CopyFrom().
Vector& Matrix::operator[] (int i) const [inline]
References mRowVec.
Vector& Matrix::operator[] (int i) [inline]
References mRowVec.
int Matrix::Rows () const [inline]
References mRows.
Referenced by InterpolateAudio(), InvertMatrix(), MatrixConcatenateCols(), MatrixMultiply(), operator*(), operator+(), ScalarMultiply(), Sum(), and TransposeMatrix().
double Matrix::Sum () const
References Cols(), mRowVec, and Rows().
void Matrix::SwapRows (int i, int j)
References mRowVec.
Referenced by InvertMatrix().
Member Data Documentation
int Matrix::mCols [private]
Referenced by Cols(), CopyFrom(), and Matrix().
int Matrix::mRows [private]
Referenced by CopyFrom(), Matrix(), Rows(), and ~Matrix().
Vector** Matrix::mRowVec [private]
Referenced by CopyFrom(), Matrix(), operator[](), Sum(), SwapRows(), and ~Matrix().
The documentation for this class was generated from the following files:
Matrix.h
Matrix.cpp