Audacity: ShuttleGui Class Reference
ShuttleGui Class Reference
Derived from ShuttleGuiBase, an Audacity specific class for shuttling data to and from GUI.
#include <ShuttleGui.h>
Public Member Functions
ShuttleGui (wxWindow *pParent, teShuttleMode ShuttleMode)
~ShuttleGui (void)
ShuttleGui & Id (int id)
ShuttleGui & Prop (int iProp)
GuiWaveTrack * AddGuiWaveTrack (const wxString &Name)
AdornedRulerPanel * AddAdornedRuler (ViewInfo *pViewInfo)
RulerPanel * AddRulerVertical (float low, float hi, const wxString &Units)
AttachableScrollBar * AddAttachableScrollBar (long style=wxSB_HORIZONTAL)
void AddStandardButtons (long buttons=eOkButton|eCancelButton, wxButton *extra=NULL)
void AddSpace (int width, int height)
void AddSpace (int size)
int GetBorder ()
void SetSizeHints (int minX=-1, int minY=-1)
Used to modify an already placed Window.
void SetSizeHints (const wxArrayString &items)
void SetSizeHints (const wxArrayInt &items)
Static Public Member Functions
static void SetSizeHints (wxWindow *window, const wxArrayString &items)
static void SetSizeHints (wxWindow *window, const wxArrayInt &items)
Detailed Description
Derived from ShuttleGuiBase, an Audacity specific class for shuttling data to and from GUI.
ShuttleGui extends the idea of the data Shuttle class to include creation of dialog controls. As part of this it provides an interface to sizers that leads to shorter more readable code.
It also allows the code that is used to create dialogs to be reused to shuttle information in and out.
Most of the ShuttleGui functions are actually defined in ShuttleGuiBase.
wxWidgets widgets are dealt with by ShuttleGuiBase.
Audacity specific widgets are dealt with by ShuttleGui
There is documentation on how to use this class in ShuttleSystem
Constructor & Destructor Documentation
ShuttleGui::ShuttleGui (wxWindow * pParent, teShuttleMode ShuttleMode)
References eIsCreating, eIsCreatingFromPrefs, eIsGettingFromDialog, eIsSavingToPrefs, ShuttleGuiBase::Init(), Shuttle::mbStoreInClient, ShuttleGuiBase::mpShuttle, and ShuttleGuiBase::mShuttleMode.
ShuttleGui::~ShuttleGui (void)
References ShuttleGuiBase::mpShuttle.
Member Function Documentation
AdornedRulerPanel * ShuttleGui::AddAdornedRuler (ViewInfo * pViewInfo)
References eIsCreating, ShuttleGuiBase::miId, ShuttleGuiBase::miProp, ShuttleGuiBase::mpParent, ShuttleGuiBase::mpWind, ShuttleGuiBase::mShuttleMode, ShuttleGuiBase::UpdateSizers(), and ShuttleGuiBase::UseUpId().
AttachableScrollBar * ShuttleGui::AddAttachableScrollBar (long style = wxSB_HORIZONTAL)
References eIsCreating, ShuttleGuiBase::miId, ShuttleGuiBase::miProp, ShuttleGuiBase::mpParent, ShuttleGuiBase::mpWind, ShuttleGuiBase::mShuttleMode, ShuttleGuiBase::UpdateSizers(), and ShuttleGuiBase::UseUpId().
GuiWaveTrack * ShuttleGui::AddGuiWaveTrack (const wxString & Name)
References eIsCreating, ShuttleGuiBase::miId, ShuttleGuiBase::miProp, ShuttleGuiBase::mpParent, ShuttleGuiBase::mpWind, ShuttleGuiBase::mShuttleMode, ShuttleGuiBase::UpdateSizers(), and ShuttleGuiBase::UseUpId().
RulerPanel * ShuttleGui::AddRulerVertical (float low, float hi, const wxString & Units)
References eIsCreating, ShuttleGuiBase::miId, ShuttleGuiBase::miProp, ShuttleGuiBase::mpParent, ShuttleGuiBase::mpWind, ShuttleGuiBase::mShuttleMode, Ruler::RealFormat, RulerPanel::ruler, Ruler::SetBounds(), Ruler::SetFormat(), Ruler::SetLabelEdges(), Ruler::SetOrientation(), Ruler::SetRange(), Ruler::SetUnits(), ShuttleGuiBase::UpdateSizers(), and ShuttleGuiBase::UseUpId().
void ShuttleGui::AddSpace (int size) [inline]
References AddSpace().
Referenced by AddSpace().
void ShuttleGui::AddSpace (int width, int height)
References eIsCreating, ShuttleGuiBase::mpSizer, and ShuttleGuiBase::mShuttleMode.
Referenced by TracksPrefs::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), GUIPrefs::PopulateOrExchange(), and ExportFFmpegOptions::PopulateOrExchange().
void ShuttleGui::AddStandardButtons (long buttons = eOkButton | eCancelButton, wxButton * extra = NULL)
References CreateStdButtonSizer(), eIsCreating, ShuttleGuiBase::EndVerticalLay(), ShuttleGuiBase::miSizerProp, ShuttleGuiBase::mpParent, ShuttleGuiBase::mpSubSizer, ShuttleGuiBase::mShuttleMode, ShuttleGuiBase::PopSizer(), ShuttleGuiBase::StartVerticalLay(), and ShuttleGuiBase::UpdateSizers().
Referenced by ExportMP3::AskResample(), ExportFFmpeg::AskResample(), EffectAutoDuckDialog::EffectAutoDuckDialog(), ErrorDialog::ErrorDialog(), EVT_TREE_KEY_DOWN(), ImportRawDialog::ImportRawDialog(), EffectDialog::Init(), LangChoiceDialog::LangChoiceDialog(), TagsEditor::OnEdit(), TrackPanel::OnRateOther(), AudacityProject::OnResample(), TrackPanel::OnSetFont(), TimerRecordDialog::PopulateOrExchange(), TimeDialog::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), SoundActivatedRecord::PopulateOrExchange(), FFmpegNotFoundDialog::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), ExportPCMOptions::PopulateOrExchange(), ExportOGGOptions::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportMP2Options::PopulateOrExchange(), ExportFLACOptions::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), ExportFFmpegWMAOptions::PopulateOrExchange(), ExportFFmpegAMRWBOptions::PopulateOrExchange(), ExportFFmpegAMRNBOptions::PopulateOrExchange(), ExportFFmpegAACOptions::PopulateOrExchange(), ExportFFmpegAC3Options::PopulateOrExchange(), ExportCLOptions::PopulateOrExchange(), EditChainsDialog::PopulateOrExchange(), BatchCommandDialog::PopulateOrExchange(), ShowInfoDialog(), MixerToolBar::ShowInputSourceDialog(), SliderDialog::SliderDialog(), and WarningDialog::WarningDialog().
int ShuttleGui::GetBorder () [inline]
Referenced by NormalizeDialog::PopulateOrExchange().
ShuttleGui & ShuttleGui::Id (int id)
References ShuttleGuiBase::miIdSetByUser.
Referenced by ContrastDialog::ContrastDialog(), EffectAutoDuckDialog::EffectAutoDuckDialog(), ExportCL::Export(), HistoryWindow::HistoryWindow(), ImportRawDialog::ImportRawDialog(), BenchmarkDialog::MakeBenchmarkDialog(), BatchProcessDialog::OnApplyToFiles(), SplashDialog::Populate(), WahwahDialog::PopulateOrExchange(), TruncSilenceDialog::PopulateOrExchange(), TimeScaleDialog::PopulateOrExchange(), ThemePrefs::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), RepeatDialog::PopulateOrExchange(), QualityPrefs::PopulateOrExchange(), PhaserDialog::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), LibraryPrefs::PopulateOrExchange(), KeyConfigPrefs::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), ExportPCMOptions::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), DevicePrefs::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ClickRemovalDialog::PopulateOrExchange(), ChangeTempoDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), EditChainsDialog::PopulateOrExchange(), BatchProcessDialog::PopulateOrExchange(), BatchCommandDialog::PopulateOrExchange(), BassBoostDialog::PopulateOrExchange(), AmplifyDialog::PopulateOrExchange(), and ShowHtmlText().
ShuttleGui& ShuttleGui::Prop (int iProp) [inline]
Reimplemented from ShuttleGuiBase.
References ShuttleGuiBase::Prop().
Referenced by AboutDialog::AboutDialog(), EVT_TREE_KEY_DOWN(), SplashDialog::Populate(), AboutDialog::PopulateAudacityPage(), AboutDialog::PopulateInformationPage(), AboutDialog::PopulateLicensePage(), TagsEditor::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), and ShowHtmlText().
void ShuttleGui::SetSizeHints (wxWindow * window, const wxArrayInt & items) [static]
References SetSizeHints().
void ShuttleGui::SetSizeHints (wxWindow * window, const wxArrayString & items) [static]
void ShuttleGui::SetSizeHints (const wxArrayInt & items)
References eIsCreating, ShuttleGuiBase::mpLastWind, ShuttleGuiBase::mShuttleMode, and SetSizeHints().
void ShuttleGui::SetSizeHints (const wxArrayString & items)
References eIsCreating, ShuttleGuiBase::mpLastWind, ShuttleGuiBase::mShuttleMode, and SetSizeHints().
void ShuttleGui::SetSizeHints (int minX = -1, int minY = -1)
Used to modify an already placed Window.
Reimplemented from ShuttleGuiBase.
Referenced by DevicePrefs::OnDevice(), DevicePrefs::OnHost(), TracksPrefs::PopulateOrExchange(), SpectrumPrefs::PopulateOrExchange(), QualityPrefs::PopulateOrExchange(), GUIPrefs::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), DevicePrefs::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), ToneGenDialog::PopulateOrExchangeStandard(), and SetSizeHints().
The documentation for this class was generated from the following files:
ShuttleGui.h
ShuttleGui.cpp