Audacity: AttachableScrollBar Class Reference
AttachableScrollBar Class Reference
An AttachableScrollBar is a scroll bar that can be attached to multiple items and so control their scrolling. Uses floats internally, not ints, allowing for (external) control of zooming.
#include <AttachableScrollBar.h>
Public Member Functions
AttachableScrollBar (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxSB_HORIZONTAL)
~AttachableScrollBar (void)
void OnScroll (wxScrollEvent &event)
void SetViewInfo (ViewInfo *view)
void SetScrollBarFromViewInfo ()
void SetViewInfoFromScrollBar ()
DECLARE_EVENT_TABLE ()
Public Attributes
ViewInfo * mpViewInfo
Detailed Description
An AttachableScrollBar is a scroll bar that can be attached to multiple items and so control their scrolling. Uses floats internally, not ints, allowing for (external) control of zooming.
Limitations:
Currently horizontal only.
Attached item repainting not yet supported. Instead for now place the attached windows in an InvisiblePanel, and rely on refreshing of the invisible panel to refresh each of the objects.
Currently closely tied to the mViewInfo class. This will change to make the class much more generic.
Constructor & Destructor Documentation
AttachableScrollBar::AttachableScrollBar (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxSB_HORIZONTAL)
AttachableScrollBar::~AttachableScrollBar (void)
Member Function Documentation
AttachableScrollBar::DECLARE_EVENT_TABLE ()
void AttachableScrollBar::OnScroll (wxScrollEvent & event)
References mpViewInfo, and SetViewInfoFromScrollBar().
void AttachableScrollBar::SetScrollBarFromViewInfo ()
References ViewInfo::h, ViewInfo::lastZoom, mpViewInfo, ViewInfo::sbarH, ViewInfo::sbarScreen, ViewInfo::sbarTotal, ViewInfo::screen, ViewInfo::total, and ViewInfo::zoom.
Referenced by SetViewInfo().
void AttachableScrollBar::SetViewInfo (ViewInfo * view)
References mpViewInfo, and SetScrollBarFromViewInfo().
void AttachableScrollBar::SetViewInfoFromScrollBar ()
References ViewInfo::h, mpViewInfo, ViewInfo::sbarH, ViewInfo::screen, ViewInfo::total, and ViewInfo::zoom.
Referenced by OnScroll().
Member Data Documentation
ViewInfo* AttachableScrollBar::mpViewInfo
Referenced by OnScroll(), SetScrollBarFromViewInfo(), SetViewInfo(), and SetViewInfoFromScrollBar().
The documentation for this class was generated from the following files:
AttachableScrollBar.h
AttachableScrollBar.cpp