Audacity: TrackInfo Class Reference
TrackInfo Class Reference
The TrackInfo is shown to the side of a track It has the menus, pan and gain controls displayed in it.
#include <TrackPanel.h>
Public Member Functions
TrackInfo (wxWindow *pParentIn)
~TrackInfo ()
int GetTitleWidth () const
Public Attributes
LWSliderArray mGains
LWSliderArray mPans
wxWindow * pParent
wxFont mFont
Private Member Functions
void MakeMoreSliders ()
void EnsureSufficientSliders (int index)
void SetTrackInfoFont (wxDC *dc)
void DrawBackground (wxDC *dc, const wxRect r, bool bSelected, bool bSyncSel, bool bHasMuteSolo, const int labelw, const int vrul)
void DrawBordersWithin (wxDC *dc, const wxRect r, bool bHasMuteSolo)
void DrawCloseBox (wxDC *dc, const wxRect r, bool down)
void DrawTitleBar (wxDC *dc, const wxRect r, Track *t, bool down)
void DrawMuteSolo (wxDC *dc, const wxRect r, Track *t, bool down, bool solo, bool bHasSoloButton)
Draw the Mute or the Solo button, depending on the value of solo.
void DrawVRuler (wxDC *dc, const wxRect r, Track *t)
void DrawSliders (wxDC *dc, WaveTrack *t, wxRect r)
void DrawMinimize (wxDC *dc, const wxRect r, Track *t, bool down, bool minimized)
void GetTrackControlsRect (const wxRect r, wxRect &dest) const
void GetCloseBoxRect (const wxRect r, wxRect &dest) const
void GetTitleBarRect (const wxRect r, wxRect &dest) const
void GetMuteSoloRect (const wxRect r, wxRect &dest, bool solo, bool bHasSoloButton) const
void GetGainRect (const wxRect r, wxRect &dest) const
void GetPanRect (const wxRect r, wxRect &dest) const
void GetMinimizeRect (const wxRect r, wxRect &dest, bool minimized) const
Friends
class TrackPanel
Detailed Description
The TrackInfo is shown to the side of a track It has the menus, pan and gain controls displayed in it.
TrackPanel and not TrackInfo takes care of the functionality for each of the buttons in that panel.
In its current implementation TrackInfo is not derived from a wxWindow. Following the original coding style, it has been coded as a 'flyweight' class, which is passed state as needed, except for the array of gains and pans.
If we'd instead coded it as a wxWindow, we would have an instance of this class for each instance displayed.
Constructor & Destructor Documentation
TrackInfo::TrackInfo (wxWindow * pParentIn)
References GetTitleWidth(), MakeMoreSliders(), mFont, and pParent.
TrackInfo::~TrackInfo ()
References mGains, and mPans.
Member Function Documentation
void TrackInfo::DrawBackground (wxDC * dc, const wxRect r, bool bSelected, bool bSyncSel, bool bHasMuteSolo, const int labelw, const int vrul) [private]
References AColor::BevelTrackInfo(), TrackArtist::DrawLinkTiles(), and AColor::MediumTrackInfo().
Referenced by TrackPanel::DrawOutside().
void TrackInfo::DrawBordersWithin (wxDC * dc, const wxRect r, bool bHasMuteSolo) [private]
References GetTitleWidth(), and AColor::Line().
Referenced by TrackPanel::DrawOutside().
void TrackInfo::DrawCloseBox (wxDC * dc, const wxRect r, bool down) [private]
References AColor::BevelTrackInfo(), ThemeBase::Colour(), GetCloseBoxRect(), AColor::Line(), and theTheme.
Referenced by TrackPanel::CloseFunc(), TrackPanel::DrawOutside(), and TrackPanel::HandleClosing().
void TrackInfo::DrawMinimize (wxDC * dc, const wxRect r, Track * t, bool down, bool minimized) [private]
References AColor::Arrow(), AColor::BevelTrackInfo(), ThemeBase::Colour(), AColor::Dark(), GetMinimizeRect(), Track::GetSelected(), Track::IsSynchroSelected(), AColor::MediumTrackInfo(), and theTheme.
Referenced by TrackPanel::DrawOutside(), TrackPanel::HandleMinimizing(), and TrackPanel::MinimizeFunc().
void TrackInfo::DrawMuteSolo (wxDC * dc, const wxRect r, Track * t, bool down, bool solo, bool bHasSoloButton) [private]
Draw the Mute or the Solo button, depending on the value of solo.
References AColor::BevelTrackInfo(), Track::GetMute(), GetMuteSoloRect(), Track::GetSelected(), Track::GetSolo(), Track::IsSynchroSelected(), AColor::MediumTrackInfo(), AColor::Mute(), SetTrackInfoFont(), and AColor::Solo().
Referenced by TrackPanel::DrawOutside(), TrackPanel::HandleMutingSoloing(), and TrackPanel::MuteSoloFunc().
void TrackInfo::DrawSliders (wxDC * dc, WaveTrack * t, wxRect r) [private]
References EnsureSufficientSliders(), WaveTrack::GetGain(), GetGainRect(), Track::GetIndex(), WaveTrack::GetPan(), GetPanRect(), Track::GetSelected(), mGains, and mPans.
Referenced by TrackPanel::DrawOutside().
void TrackInfo::DrawTitleBar (wxDC * dc, const wxRect r, Track * t, bool down) [private]
References AColor::Arrow(), AColor::BevelTrackInfo(), ThemeBase::Colour(), Track::GetName(), Track::GetSelected(), GetTitleBarRect(), GetTitleWidth(), Track::IsSynchroSelected(), kLeftInset, AColor::MediumTrackInfo(), SetTrackInfoFont(), and theTheme.
Referenced by TrackPanel::DrawOutside(), TrackPanel::HandlePopping(), and TrackPanel::PopupFunc().
void TrackInfo::DrawVRuler (wxDC * dc, const wxRect r, Track * t) [private]
void TrackInfo::EnsureSufficientSliders (int index) [private]
References MakeMoreSliders(), mGains, and mPans.
Referenced by DrawSliders().
void TrackInfo::GetCloseBoxRect (const wxRect r, wxRect & dest) const [private]
Referenced by TrackPanel::CloseFunc(), DrawCloseBox(), and TrackPanel::HandleClosing().
void TrackInfo::GetGainRect (const wxRect r, wxRect & dest) const [private]
Referenced by DrawSliders(), TrackPanel::GainFunc(), and MakeMoreSliders().
void TrackInfo::GetMinimizeRect (const wxRect r, wxRect & dest, bool minimized) const [private]
Referenced by DrawMinimize(), GetTrackControlsRect(), TrackPanel::HandleMinimizing(), and TrackPanel::MinimizeFunc().
void TrackInfo::GetMuteSoloRect (const wxRect r, wxRect & dest, bool solo, bool bHasSoloButton) const [private]
Referenced by DrawMuteSolo(), TrackPanel::HandleMutingSoloing(), and TrackPanel::MuteSoloFunc().
void TrackInfo::GetPanRect (const wxRect r, wxRect & dest) const [private]
Referenced by DrawSliders(), MakeMoreSliders(), and TrackPanel::PanFunc().
void TrackInfo::GetTitleBarRect (const wxRect r, wxRect & dest) const [private]
References GetTitleWidth().
Referenced by DrawTitleBar(), GetTrackControlsRect(), TrackPanel::HandlePopping(), TrackPanel::OnTrackMenu(), and TrackPanel::PopupFunc().
int TrackInfo::GetTitleWidth () const
Referenced by DrawBordersWithin(), TrackPanel::DrawOutside(), DrawTitleBar(), TrackPanel::GetLabelWidth(), GetTitleBarRect(), GetTrackControlsRect(), TrackPanel::GetVRulerOffset(), and TrackInfo().
void TrackInfo::GetTrackControlsRect (const wxRect r, wxRect & dest) const [private]
References GetMinimizeRect(), GetTitleBarRect(), and GetTitleWidth().
Referenced by TrackPanel::DrawOutside(), and TrackPanel::HandleLabelClick().
void TrackInfo::MakeMoreSliders () [private]
References DB_SLIDER, GetGainRect(), GetPanRect(), mGains, mPans, PAN_SLIDER, pParent, and LWSlider::SetDefaultValue().
Referenced by EnsureSufficientSliders(), and TrackInfo().
void TrackInfo::SetTrackInfoFont (wxDC * dc) [private]
Todo:
Probably should move to 'Utils.cpp'.
References mFont.
Referenced by DrawMuteSolo(), TrackPanel::DrawOutside(), and DrawTitleBar().
Friends And Related Function Documentation
friend class TrackPanel [friend]
Member Data Documentation
wxFont TrackInfo::mFont
Referenced by SetTrackInfoFont(), and TrackInfo().
LWSliderArray TrackInfo::mGains
Referenced by DrawSliders(), EnsureSufficientSliders(), TrackPanel::HandleSliders(), MakeMoreSliders(), TrackPanel::OnTrackGain(), TrackPanel::OnTrackGainDec(), TrackPanel::OnTrackGainInc(), and ~TrackInfo().
LWSliderArray TrackInfo::mPans
Referenced by DrawSliders(), EnsureSufficientSliders(), TrackPanel::HandleSliders(), MakeMoreSliders(), TrackPanel::OnTrackPan(), TrackPanel::OnTrackPanLeft(), TrackPanel::OnTrackPanRight(), and ~TrackInfo().
wxWindow* TrackInfo::pParent
Referenced by MakeMoreSliders(), and TrackInfo().
The documentation for this class was generated from the following files:
TrackPanel.h
TrackPanel.cpp