Audacity: BlockFile Class Reference
BlockFile Class Reference
A BlockFile is a chunk of immutable audio data.
#include <BlockFile.h>
Public Member Functions
BlockFile (wxFileName fileName, sampleCount samples)
Construct a BlockFile.
virtual ~BlockFile ()
virtual int ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len)=0
Retrieves audio data from this BlockFile.
virtual bool GetNeedWriteCacheToDisk ()
virtual void WriteCacheToDisk ()
virtual bool GetNeedFillCache ()
virtual void FillCache ()
virtual void SaveXML (XMLWriter &xmlFile)=0
Stores a representation of this file in XML.
virtual wxFileName GetFileName ()
Gets the filename of the disk file associated with this BlockFile.
virtual void SetFileName (wxFileName &name)
sets the file name the summary info will be saved in. threadsafe.
virtual sampleCount GetLength ()
virtual void Lock ()
Locks this BlockFile, to prevent it from being moved.
virtual void Unlock ()
Unlock this BlockFile, allowing it to be moved.
virtual bool IsLocked ()
Returns TRUE if this BlockFile is locked.
virtual void GetMinMax (sampleCount start, sampleCount len, float *outMin, float *outMax, float *outRMS)
Gets extreme values for the specified region.
virtual void GetMinMax (float *outMin, float *outMax, float *outRMS)
Gets extreme values for the entire block.
virtual bool Read256 (float *buffer, sampleCount start, sampleCount len)
Returns the 256 byte summary data block.
virtual bool Read64K (float *buffer, sampleCount start, sampleCount len)
Returns the 64K summary data block.
virtual bool IsAlias ()
Returns TRUE if this block references another disk file.
virtual bool IsSummaryAvailable ()
Returns TRUE if this block's complete summary has been computed and is ready (for OD).
virtual bool IsDataAvailable ()
Returns TRUE if this block's complete data is ready to be accessed by Read().
virtual bool IsSummaryBeingComputed ()
Returns TRUE if the summary has not yet been written, but is actively being computed and written to disk.
virtual BlockFile * Copy (wxFileName newFileName)=0
Create a new BlockFile identical to this, using the given filename.
virtual wxLongLong GetSpaceUsage ()=0
virtual void Recover ()=0
if the on-disk state disappeared, either recover it (if it was
void SilenceLog ()
if we've detected an on-disk problem, the user opted to
virtual void CloseLock ()
virtual void LockRead ()
Prevents a read on other threads. The basic blockfile runs on only one thread, so does nothing.
virtual void UnlockRead ()
Allows reading on other threads.
Static Public Member Functions
static void Deinit ()
Protected Member Functions
virtual void * CalcSummary (samplePtr buffer, sampleCount len, sampleFormat format)
Calculate summary data for the given sample data.
virtual bool ReadSummary (void *data)=0
Read the summary section of the file. Derived classes implement.
virtual void FixSummary (void *data)
Protected Attributes
wxFileName mFileName
sampleCount mLen
SummaryInfo mSummaryInfo
float mMin
float mMax
float mRMS
bool mSilentLog
Private Member Functions
virtual void Ref ()
virtual bool Deref ()
virtual int RefCount ()
Private Attributes
int mLockCount
int mRefCount
Static Private Attributes
static char * fullSummary = 0
Friends
class DirManager
class ODComputeSummaryTask
class ODDecodeTask
class ODPCMAliasBlockFile
Detailed Description
A BlockFile is a chunk of immutable audio data.
A BlockFile represents a chunk of audio data. These chunks are assembled into sequences by the class Sequence. These classes are at the heart of how Audacity stores audio data.
BlockFile is an abstract base class that can be implemented in many different ways. However it does have a fairly large amount of shared code that deals with the physical file and manipulating the summary data.
BlockFile should be thought of as an immutable class. After it is constructed, it is essentially never changed (though there are a few exceptions). Most notably, the audio data and summary data are never altered once it is constructed. This is important to some of the derived classes that are actually aliases to audio data stored in existing files.
BlockFiles are reference-counted, and deleted when their reference count hits zero. DirManager is the class responsible for constructing and managing BlockFiles and managing their reference counts.
Constructor & Destructor Documentation
BlockFile::BlockFile (wxFileName fileName, sampleCount samples)
Construct a BlockFile.
Initializes the base BlockFile data. The block is initially unlocked and its reference count is 1.
Parameters:
fileName The name of the disk file associated with this BlockFile. Not all BlockFiles will store their sample data here (for example, AliasBlockFiles read their data from elsewhere), but all BlockFiles will store at least the summary data here.
samples The number of samples this BlockFile contains.
References mSilentLog.
BlockFile::~BlockFile () [virtual]
References IsLocked(), and mFileName.
Member Function Documentation
void * BlockFile::CalcSummary (samplePtr buffer, sampleCount len, sampleFormat format) [protected, virtual]
Calculate summary data for the given sample data.
Get a buffer containing a summary block describing this sample data. This must be called by derived classes when they are constructed, to allow them to construct their summary data, after which they should write that data to their disk file.
This method also has the side effect of setting the mMin, mMax, and mRMS members of this class.
You must not delete the returned buffer; it is static to this method.
Parameters:
buffer A buffer containing the sample data to be analyzed
len The length of the sample data
format The format of the sample data.
Reimplemented in ODDecodeBlockFile, and ODPCMAliasBlockFile.
References CopySamples(), floatSample, SummaryInfo::frames256, SummaryInfo::frames64K, fullSummary, headerTag, headerTagLen, max, min(), mMax, mMin, mRMS, mSummaryInfo, SummaryInfo::offset256, SummaryInfo::offset64K, and SummaryInfo::totalSummaryBytes.
Referenced by SimpleBlockFile::SimpleBlockFile(), SimpleBlockFile::WriteSimpleBlockFile(), and AliasBlockFile::WriteSummary().
virtual void BlockFile::CloseLock () [inline, virtual]
when the project closes, it locks the blockfiles. Override this in case it needs special treatment
Reimplemented in ODPCMAliasBlockFile.
References Lock().
virtual BlockFile* BlockFile::Copy (wxFileName newFileName) [pure virtual]
Create a new BlockFile identical to this, using the given filename.
Implemented in LegacyAliasBlockFile, LegacyBlockFile, ODDecodeBlockFile, ODPCMAliasBlockFile, PCMAliasBlockFile, SilentBlockFile, and SimpleBlockFile.
Referenced by DirManager::CopyBlockFile().
void BlockFile::Deinit () [static]
References fullSummary.
Referenced by AudacityApp::OnExit().
bool BlockFile::Deref () [private, virtual]
Decreases the reference count of this block by one. If this causes the count to become zero, deletes the associated disk file and deletes this object
Reimplemented in ODPCMAliasBlockFile.
References BLOCKFILE_DEBUG_OUTPUT, and mRefCount.
Referenced by DirManager::Deref().
virtual void BlockFile::FillCache () [inline, virtual]
Reimplemented in SimpleBlockFile.
Referenced by DirManager::FillBlockfilesCache().
void BlockFile::FixSummary (void * data) [protected, virtual]
Byte-swap the summary data, in case it was saved by a system on a different platform
References ComputeMinMax256(), SummaryInfo::fields, floatSample, SummaryInfo::format, max, min(), mSummaryInfo, SummaryInfo::offset256, SummaryInfo::offset64K, and SummaryInfo::totalSummaryBytes.
Referenced by SimpleBlockFile::ReadSummary(), ODPCMAliasBlockFile::ReadSummary(), and AliasBlockFile::ReadSummary().
wxFileName BlockFile::GetFileName () [virtual]
Gets the filename of the disk file associated with this BlockFile.
Returns the file name of the disk file associated with this BlockFile. Not all BlockFiles store their sample data here, but all BlockFiles have at least their summary data here.
Reimplemented in ODDecodeBlockFile, and ODPCMAliasBlockFile.
References mFileName.
Referenced by DirManager::CopyBlockFile(), DirManager::CopyToNewProjectDirectory(), DirManager::Deref(), DirManager::EnsureSafeFilename(), and DirManager::MoveToNewProjectDirectory().
virtual sampleCount BlockFile::GetLength () [inline, virtual]
References mLen.
Referenced by Sequence::Append(), Sequence::AppendAlias(), Sequence::AppendBlock(), Sequence::AppendBlockFile(), Sequence::AppendCoded(), Sequence::ConvertToSampleFormat(), Sequence::CopyWrite(), Sequence::Delete(), ODDecodeTask::DoSomeInternal(), ODComputeSummaryTask::DoSomeInternal(), FindDependencies(), DirManager::HandleXMLTag(), Sequence::Paste(), and RemoveDependencies().
void BlockFile::GetMinMax (float * outMin, float * outMax, float * outRMS) [virtual]
Gets extreme values for the entire block.
Retrieves the minimum, maximum, and maximum RMS of this entire block. This is faster than the other GetMinMax function since these values are already computed.
Parameters:
*outMin A pointer to where the minimum value for this block should be stored
*outMax A pointer to where the maximum value for this block should be stored
*outRMS A pointer to where the maximum RMS value for this block should be stored.
Reimplemented in ODDecodeBlockFile, and ODPCMAliasBlockFile.
References mMax, mMin, and mRMS.
void BlockFile::GetMinMax (sampleCount start, sampleCount len, float * outMin, float * outMax, float * outRMS) [virtual]
Gets extreme values for the specified region.
Retrieves the minimum, maximum, and maximum RMS of the specified sample data in this block.
Parameters:
start The offset in this block where the region should begin
len The number of samples to include in the region
*outMin A pointer to where the minimum value for this region should be stored
*outMax A pointer to where the maximum value for this region should be stored
*outRMS A pointer to where the maximum RMS value for this region should be stored.
Reimplemented in ODDecodeBlockFile, and ODPCMAliasBlockFile.
References DeleteSamples(), floatSample, max, min(), NewSamples(), and ReadData().
virtual bool BlockFile::GetNeedFillCache () [inline, virtual]
Reimplemented in SimpleBlockFile.
Referenced by DirManager::FillBlockfilesCache().
virtual bool BlockFile::GetNeedWriteCacheToDisk () [inline, virtual]
Reimplemented in SimpleBlockFile.
Referenced by DirManager::WriteCacheToDisk().
virtual wxLongLong BlockFile::GetSpaceUsage () [pure virtual]
Implemented in LegacyBlockFile, ODDecodeBlockFile, ODPCMAliasBlockFile, SilentBlockFile, SimpleBlockFile, and AliasBlockFile.
virtual bool BlockFile::IsAlias () [inline, virtual]
Returns TRUE if this block references another disk file.
Reimplemented in AliasBlockFile.
Referenced by AudacityProject::AddImportedTracks(), Sequence::ConvertToSampleFormat(), DirManager::EnsureSafeFilename(), FindDependencies(), DirManager::ProjectFSCK(), and RemoveDependencies().
virtual bool BlockFile::IsDataAvailable () [inline, virtual]
Returns TRUE if this block's complete data is ready to be accessed by Read().
Reimplemented in ODDecodeBlockFile.
Referenced by DirManager::EnsureSafeFilename().
bool BlockFile::IsLocked () [virtual]
Returns TRUE if this BlockFile is locked.
Returns true if the block is locked.
References mLockCount.
Referenced by DirManager::CopyBlockFile(), DirManager::SetProject(), ODPCMAliasBlockFile::Unlock(), and ~BlockFile().
virtual bool BlockFile::IsSummaryAvailable () [inline, virtual]
Returns TRUE if this block's complete summary has been computed and is ready (for OD).
Reimplemented in ODDecodeBlockFile, and ODPCMAliasBlockFile.
Referenced by DirManager::CopyBlockFile(), DirManager::CopyToNewProjectDirectory(), DirManager::MoveToNewProjectDirectory(), and DirManager::ProjectFSCK().
virtual bool BlockFile::IsSummaryBeingComputed () [inline, virtual]
Returns TRUE if the summary has not yet been written, but is actively being computed and written to disk.
Reimplemented in ODDecodeBlockFile, and ODPCMAliasBlockFile.
Referenced by DirManager::CopyToNewProjectDirectory(), and DirManager::MoveToNewProjectDirectory().
void BlockFile::Lock () [virtual]
Locks this BlockFile, to prevent it from being moved.
Marks this BlockFile as "locked." A locked BlockFile may not be moved or deleted, only copied. Locking a BlockFile prevents it from disappearing if the project is saved in a different location. When doing a "Save As," Audacity locks all blocks belonging to the already-existing project, to ensure that the existing project remains valid with all the blocks it needs. Audacity also locks the blocks of the last saved version of a project when the project is deleted so that the files aren't deleted when their refcount hits zero.
Reimplemented in ODPCMAliasBlockFile.
References BLOCKFILE_DEBUG_OUTPUT, and mLockCount.
Referenced by CloseLock().
virtual void BlockFile::LockRead () [inline, virtual]
Prevents a read on other threads. The basic blockfile runs on only one thread, so does nothing.
Reimplemented in ODDecodeBlockFile, and ODPCMAliasBlockFile.
Referenced by DirManager::EnsureSafeFilename().
bool BlockFile::Read256 (float * buffer, sampleCount start, sampleCount len) [virtual]
Returns the 256 byte summary data block.
Retrieves a portion of the 256-byte summary buffer from this BlockFile. This data provides information about the minimum value, the maximum value, and the maximum RMS value for every group of 256 samples in the file.
Parameters:
*buffer The area where the summary information will be written. It must be at least len*3 long.
start The offset in 256-sample increments
len The number of 256-sample summary frames to read
Reimplemented in ODDecodeBlockFile, and ODPCMAliasBlockFile.
References SummaryInfo::bytesPerFrame, CopySamples(), SummaryInfo::fields, floatSample, SummaryInfo::format, SummaryInfo::frames256, mSummaryInfo, SummaryInfo::offset256, ReadSummary(), and SummaryInfo::totalSummaryBytes.
bool BlockFile::Read64K (float * buffer, sampleCount start, sampleCount len) [virtual]
Returns the 64K summary data block.
Retrieves a portion of the 64K summary buffer from this BlockFile. This data provides information about the minimum value, the maximum value, and the maximum RMS value for every group of 64K samples in the file.
Parameters:
*buffer The area where the summary information will be written. It must be at least len*3 long.
start The offset in 64K-sample increments
len The number of 64K-sample summary frames to read
Reimplemented in ODDecodeBlockFile, and ODPCMAliasBlockFile.
References SummaryInfo::bytesPerFrame, CopySamples(), SummaryInfo::fields, floatSample, SummaryInfo::format, SummaryInfo::frames64K, mSummaryInfo, SummaryInfo::offset64K, ReadSummary(), and SummaryInfo::totalSummaryBytes.
virtual int BlockFile::ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len) [pure virtual]
Retrieves audio data from this BlockFile.
Implemented in LegacyBlockFile, ODDecodeBlockFile, ODPCMAliasBlockFile, PCMAliasBlockFile, SilentBlockFile, SimpleBlockFile, and AliasBlockFile.
Referenced by Sequence::ConvertToSampleFormat(), GetMinMax(), Sequence::Read(), and RemoveDependencies().
virtual bool BlockFile::ReadSummary (void * data) [protected, pure virtual]
Read the summary section of the file. Derived classes implement.
Implemented in LegacyBlockFile, ODDecodeBlockFile, ODPCMAliasBlockFile, SilentBlockFile, SimpleBlockFile, and AliasBlockFile.
Referenced by Read256(), and Read64K().
virtual void BlockFile::Recover () [pure virtual]
if the on-disk state disappeared, either recover it (if it was
Implemented in LegacyAliasBlockFile, LegacyBlockFile, ODDecodeBlockFile, ODPCMAliasBlockFile, PCMAliasBlockFile, SilentBlockFile, and SimpleBlockFile.
Referenced by DirManager::ProjectFSCK().
void BlockFile::Ref () [private, virtual]
Increases the reference count of this block by one. Only DirManager should call this method.
Reimplemented in ODPCMAliasBlockFile.
References BLOCKFILE_DEBUG_OUTPUT, and mRefCount.
Referenced by DirManager::CopyBlockFile(), and DirManager::Ref().
virtual int BlockFile::RefCount () [inline, private, virtual]
References mRefCount.
virtual void BlockFile::SaveXML (XMLWriter & xmlFile) [pure virtual]
Stores a representation of this file in XML.
Implemented in LegacyAliasBlockFile, LegacyBlockFile, ODDecodeBlockFile, ODPCMAliasBlockFile, PCMAliasBlockFile, SilentBlockFile, and SimpleBlockFile.
Referenced by Sequence::Append(), and Sequence::WriteXML().
void BlockFile::SetFileName (wxFileName & name) [virtual]
sets the file name the summary info will be saved in. threadsafe.
Reimplemented in ODDecodeBlockFile, and ODPCMAliasBlockFile.
References mFileName.
Referenced by DirManager::CopyToNewProjectDirectory(), and DirManager::MoveToNewProjectDirectory().
void BlockFile::SilenceLog () [inline]
if we've detected an on-disk problem, the user opted to
References mSilentLog.
Referenced by DirManager::ProjectFSCK().
void BlockFile::Unlock () [virtual]
Unlock this BlockFile, allowing it to be moved.
Marks this BlockFile as "unlocked.".
Reimplemented in ODPCMAliasBlockFile.
References BLOCKFILE_DEBUG_OUTPUT, and mLockCount.
virtual void BlockFile::UnlockRead () [inline, virtual]
Allows reading on other threads.
Reimplemented in ODDecodeBlockFile, and ODPCMAliasBlockFile.
Referenced by DirManager::EnsureSafeFilename().
virtual void BlockFile::WriteCacheToDisk () [inline, virtual]
Reimplemented in SimpleBlockFile.
Referenced by DirManager::WriteCacheToDisk().
Friends And Related Function Documentation
friend class DirManager [friend]
Reimplemented in ODPCMAliasBlockFile.
friend class ODComputeSummaryTask [friend]
Reimplemented in ODPCMAliasBlockFile.
friend class ODDecodeTask [friend]
Reimplemented in ODPCMAliasBlockFile.
friend class ODPCMAliasBlockFile [friend]
Member Data Documentation
char * BlockFile::fullSummary = 0 [static, private]
Referenced by CalcSummary(), and Deinit().
wxFileName BlockFile::mFileName [protected]
Referenced by SimpleBlockFile::FillCache(), ODPCMAliasBlockFile::GetFileName(), ODDecodeBlockFile::GetFileName(), GetFileName(), SimpleBlockFile::GetSpaceUsage(), ODPCMAliasBlockFile::GetSpaceUsage(), ODDecodeBlockFile::GetSpaceUsage(), LegacyBlockFile::GetSpaceUsage(), AliasBlockFile::GetSpaceUsage(), ODPCMAliasBlockFile::ODPCMAliasBlockFile(), SimpleBlockFile::ReadData(), LegacyBlockFile::ReadData(), SimpleBlockFile::ReadSummary(), ODPCMAliasBlockFile::ReadSummary(), LegacyBlockFile::ReadSummary(), AliasBlockFile::ReadSummary(), SimpleBlockFile::Recover(), SimpleBlockFile::SaveXML(), PCMAliasBlockFile::SaveXML(), ODPCMAliasBlockFile::SaveXML(), ODDecodeBlockFile::SaveXML(), LegacyBlockFile::SaveXML(), LegacyAliasBlockFile::SaveXML(), ODPCMAliasBlockFile::SetFileName(), ODDecodeBlockFile::SetFileName(), SetFileName(), SimpleBlockFile::WriteSimpleBlockFile(), AliasBlockFile::WriteSummary(), and ~BlockFile().
sampleCount BlockFile::mLen [protected]
Referenced by SimpleBlockFile::Copy(), SilentBlockFile::Copy(), PCMAliasBlockFile::Copy(), ODPCMAliasBlockFile::Copy(), ODDecodeBlockFile::Copy(), LegacyBlockFile::Copy(), LegacyAliasBlockFile::Copy(), SimpleBlockFile::FillCache(), GetLength(), SimpleBlockFile::ReadData(), LegacyBlockFile::ReadData(), SimpleBlockFile::Recover(), SimpleBlockFile::SaveXML(), SilentBlockFile::SaveXML(), PCMAliasBlockFile::SaveXML(), ODPCMAliasBlockFile::SaveXML(), ODDecodeBlockFile::SaveXML(), LegacyBlockFile::SaveXML(), LegacyAliasBlockFile::SaveXML(), SimpleBlockFile::WriteCacheToDisk(), ODDecodeBlockFile::WriteODDecodeBlockFile(), ODPCMAliasBlockFile::WriteSummary(), and AliasBlockFile::WriteSummary().
int BlockFile::mLockCount [private]
Referenced by IsLocked(), Lock(), and Unlock().
float BlockFile::mMax [protected]
Referenced by AliasBlockFile::AliasBlockFile(), ODPCMAliasBlockFile::CalcSummary(), ODDecodeBlockFile::CalcSummary(), CalcSummary(), SimpleBlockFile::Copy(), PCMAliasBlockFile::Copy(), ODPCMAliasBlockFile::Copy(), ODDecodeBlockFile::Copy(), GetMinMax(), LegacyAliasBlockFile::LegacyAliasBlockFile(), LegacyBlockFile::LegacyBlockFile(), SimpleBlockFile::SaveXML(), PCMAliasBlockFile::SaveXML(), SilentBlockFile::SilentBlockFile(), and SimpleBlockFile::SimpleBlockFile().
float BlockFile::mMin [protected]
Referenced by AliasBlockFile::AliasBlockFile(), ODPCMAliasBlockFile::CalcSummary(), ODDecodeBlockFile::CalcSummary(), CalcSummary(), SimpleBlockFile::Copy(), PCMAliasBlockFile::Copy(), ODPCMAliasBlockFile::Copy(), ODDecodeBlockFile::Copy(), GetMinMax(), LegacyAliasBlockFile::LegacyAliasBlockFile(), LegacyBlockFile::LegacyBlockFile(), SimpleBlockFile::SaveXML(), PCMAliasBlockFile::SaveXML(), SilentBlockFile::SilentBlockFile(), and SimpleBlockFile::SimpleBlockFile().
int BlockFile::mRefCount [private]
Referenced by Deref(), DirManager::GetRefCount(), Ref(), and RefCount().
float BlockFile::mRMS [protected]
Referenced by AliasBlockFile::AliasBlockFile(), ODPCMAliasBlockFile::CalcSummary(), ODDecodeBlockFile::CalcSummary(), CalcSummary(), SimpleBlockFile::Copy(), PCMAliasBlockFile::Copy(), ODPCMAliasBlockFile::Copy(), ODDecodeBlockFile::Copy(), GetMinMax(), LegacyAliasBlockFile::LegacyAliasBlockFile(), LegacyBlockFile::LegacyBlockFile(), SimpleBlockFile::SaveXML(), PCMAliasBlockFile::SaveXML(), SilentBlockFile::SilentBlockFile(), and SimpleBlockFile::SimpleBlockFile().
bool BlockFile::mSilentLog [protected]
Referenced by BlockFile(), SimpleBlockFile::ReadData(), LegacyBlockFile::ReadData(), SimpleBlockFile::ReadSummary(), ODPCMAliasBlockFile::ReadSummary(), LegacyBlockFile::ReadSummary(), AliasBlockFile::ReadSummary(), and SilenceLog().
SummaryInfo BlockFile::mSummaryInfo [protected]
Referenced by ODPCMAliasBlockFile::CalcSummary(), ODDecodeBlockFile::CalcSummary(), CalcSummary(), LegacyBlockFile::Copy(), LegacyAliasBlockFile::Copy(), SimpleBlockFile::FillCache(), FixSummary(), LegacyAliasBlockFile::LegacyAliasBlockFile(), LegacyBlockFile::LegacyBlockFile(), Read256(), Read64K(), LegacyBlockFile::ReadData(), SimpleBlockFile::ReadSummary(), SilentBlockFile::ReadSummary(), ODPCMAliasBlockFile::ReadSummary(), ODDecodeBlockFile::ReadSummary(), LegacyBlockFile::ReadSummary(), AliasBlockFile::ReadSummary(), SimpleBlockFile::Recover(), LegacyBlockFile::SaveXML(), LegacyAliasBlockFile::SaveXML(), SimpleBlockFile::SimpleBlockFile(), SimpleBlockFile::WriteSimpleBlockFile(), ODPCMAliasBlockFile::WriteSummary(), and AliasBlockFile::WriteSummary().
The documentation for this class was generated from the following files:
BlockFile.h
BlockFile.cpp