Audacity: TrackListCondIterator Class Reference
TrackListCondIterator Class Reference
#include <Track.h>
Public Member Functions
TrackListCondIterator (TrackList *val=NULL)
virtual ~TrackListCondIterator ()
Track * First (TrackList *val=NULL)
Track * StartWith (Track *val)
Track * Next (bool skiplinked=false)
Track * Prev (bool skiplinked=false)
Track * Last (bool skiplinked=false)
Protected Member Functions
virtual bool Condition (Track *t)=0
Constructor & Destructor Documentation
TrackListCondIterator::TrackListCondIterator (TrackList * val = NULL) [inline]
virtual TrackListCondIterator::~TrackListCondIterator () [inline, virtual]
Member Function Documentation
virtual bool TrackListCondIterator::Condition (Track * t) [protected, pure virtual]
Implemented in TrackListOfKindIterator, SelectedTrackListOfKindIterator, and VisibleTrackIterator.
Referenced by First(), Last(), Next(), Prev(), and StartWith().
Track * TrackListCondIterator::First (TrackList * val = NULL) [virtual]
Reimplemented from TrackListIterator.
References Condition(), and Next().
Referenced by EffectStereoToMono::CheckWhetherSkipEffect(), Effect::CopyInputTracks(), Effect::CountWaveTracks(), EffectChangePitch::DeduceFrequencies(), TrackPanel::DoDrawCursor(), TrackPanel::DoDrawIndicator(), EffectEqualization::DontPromptUser(), TrackPanel::DrawEverythingElse(), TrackPanel::FindTrack(), EffectNyquist::GetCtrlValue(), UndoManager::GetSpaceUsage(), TrackPanel::HandleSliders(), VampEffect::Init(), LadspaEffect::Init(), EffectAmplify::Init(), EffectCompressor::InitPass1(), TrackArtist::InvalidateSpectrumCache(), AudacityProject::OnPaste(), AudacityProject::OnPasteNewLabel(), AudacityProject::OnSilence(), Effect::Preview(), VampEffect::Process(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Process(), EffectSimpleMono::Process(), EffectRepair::Process(), EffectNyquist::Process(), EffectNormalize::Process(), EffectNoiseRemoval::Process(), EffectFindClipping::Process(), EffectEqualization::Process(), EffectEcho::Process(), EffectClickRemoval::Process(), EffectChangeLength::Process(), EffectAutoDuck::Process(), EffectTwoPassSimpleMono::ProcessPass(), EffectSpikeCleaner::ProcessSimpleMono(), EffectRepeat::PromptUser(), EffectEqualization::PromptUser(), AudacityProject::SaveCompressedWaveTracks(), AudacityProject::UpdateLyrics(), and TrackPanel::UpdateVRulers().
Track * TrackListCondIterator::Last (bool skiplinked = false) [virtual]
Reimplemented from TrackListIterator.
References Condition(), and Prev().
Referenced by AudacityProject::OnPaste().
Track * TrackListCondIterator::Next (bool skiplinked = false) [virtual]
Reimplemented from TrackListIterator.
References Condition(), and TrackListIterator::Next().
Referenced by EffectStereoToMono::CheckWhetherSkipEffect(), Effect::CopyInputTracks(), Effect::CountWaveTracks(), TrackPanel::DoDrawCursor(), TrackPanel::DoDrawIndicator(), TrackPanel::DrawEverythingElse(), TrackPanel::FindTrack(), First(), UndoManager::GetSpaceUsage(), TrackPanel::HandleSliders(), VampEffect::Init(), LadspaEffect::Init(), EffectAmplify::Init(), EffectCompressor::InitPass1(), TrackArtist::InvalidateSpectrumCache(), AudacityProject::OnPaste(), AudacityProject::OnPasteNewLabel(), AudacityProject::OnSilence(), Effect::Preview(), VampEffect::Process(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Process(), EffectSimpleMono::Process(), EffectRepair::Process(), EffectNyquist::Process(), EffectNormalize::Process(), EffectNoiseRemoval::Process(), EffectFindClipping::Process(), EffectEqualization::Process(), EffectEcho::Process(), EffectClickRemoval::Process(), EffectAutoDuck::Process(), EffectTwoPassSimpleMono::ProcessPass(), EffectRepeat::PromptUser(), AudacityProject::SaveCompressedWaveTracks(), and TrackPanel::UpdateVRulers().
Track * TrackListCondIterator::Prev (bool skiplinked = false) [virtual]
Reimplemented from TrackListIterator.
References Condition(), and TrackListIterator::Prev().
Referenced by Last().
Track * TrackListCondIterator::StartWith (Track * val) [virtual]
Reimplemented from TrackListIterator.
References Condition().
The documentation for this class was generated from the following files:
Track.h
Track.cpp