Audacity: TimeEditor Class Reference
TimeEditor Class Reference
#include <Grid.h>
Public Member Functions
TimeEditor ()
TimeEditor (const wxString &format, double rate)
~TimeEditor ()
void Create (wxWindow *parent, wxWindowID id, wxEvtHandler *handler)
bool IsAcceptedKey (wxKeyEvent &event)
void SetSize (const wxRect &rect)
void BeginEdit (int row, int col, wxGrid *grid)
bool EndEdit (int row, int col, wxGrid *grid)
void Reset ()
wxString GetFormat ()
double GetRate ()
void SetFormat (const wxString &format)
void SetRate (double rate)
wxGridCellEditor * Clone () const
wxString GetValue () const
TimeTextCtrl * GetTimeCtrl () const
Private Attributes
wxString mFormat
double mRate
double mOld
Constructor & Destructor Documentation
TimeEditor::TimeEditor ()
Referenced by Clone().
TimeEditor::TimeEditor (const wxString & format, double rate)
References mFormat, mOld, and mRate.
TimeEditor::~TimeEditor ()
Member Function Documentation
void TimeEditor::BeginEdit (int row, int col, wxGrid * grid)
References TimeTextCtrl::EnableMenu(), GetTimeCtrl(), mOld, and TimeTextCtrl::SetTimeValue().
wxGridCellEditor * TimeEditor::Clone () const
References mFormat, mRate, and TimeEditor().
void TimeEditor::Create (wxWindow * parent, wxWindowID id, wxEvtHandler * handler)
References mFormat, mOld, and mRate.
bool TimeEditor::EndEdit (int row, int col, wxGrid * grid)
References GetTimeCtrl(), TimeTextCtrl::GetTimeValue(), and mOld.
wxString TimeEditor::GetFormat ()
References mFormat.
Referenced by TimeRenderer::Draw(), and TimeRenderer::GetBestSize().
double TimeEditor::GetRate ()
References mRate.
Referenced by TimeRenderer::Draw(), and TimeRenderer::GetBestSize().
TimeTextCtrl* TimeEditor::GetTimeCtrl () const [inline]
Referenced by BeginEdit(), EndEdit(), GetValue(), and Reset().
wxString TimeEditor::GetValue () const
References GetTimeCtrl().
bool TimeEditor::IsAcceptedKey (wxKeyEvent & event)
void TimeEditor::Reset ()
References GetTimeCtrl(), mOld, and TimeTextCtrl::SetTimeValue().
void TimeEditor::SetFormat (const wxString & format)
References mFormat.
Referenced by LabelDialog::TransferDataToWindow().
void TimeEditor::SetRate (double rate)
References mRate.
Referenced by LabelDialog::TransferDataToWindow().
void TimeEditor::SetSize (const wxRect & rect)
Member Data Documentation
wxString TimeEditor::mFormat [private]
Referenced by Clone(), Create(), GetFormat(), SetFormat(), and TimeEditor().
double TimeEditor::mOld [private]
Referenced by BeginEdit(), Create(), EndEdit(), Reset(), and TimeEditor().
double TimeEditor::mRate [private]
Referenced by Clone(), Create(), GetRate(), SetRate(), and TimeEditor().
The documentation for this class was generated from the following files:
Grid.h
Grid.cpp