Audacity: ToolFrame Class Reference
ToolFrame Class Reference
Public Member Functions
ToolFrame (wxWindow *parent, ToolManager *manager, ToolBar *bar, wxPoint pos)
void OnGrabber (GrabberEvent &event)
void OnToolBarUpdate (wxCommandEvent &event)
void OnPaint (wxPaintEvent &event)
void OnMotion (wxMouseEvent &event)
void OnCaptureLost (wxMouseCaptureLostEvent &event)
void OnClose (wxCloseEvent &event)
DECLARE_CLASS (ToolFrame)
DECLARE_EVENT_TABLE ()
Private Attributes
wxWindow * mParent
ToolManager * mManager
ToolBar * mBar
wxSize mMinSize
Constructor & Destructor Documentation
ToolFrame::ToolFrame (wxWindow * parent, ToolManager * manager, ToolBar * bar, wxPoint pos) [inline]
References ToolBar::IsResizable(), mBar, mManager, mMinSize, mParent, ToolBar::SetDocked(), and sizerW.
Member Function Documentation
ToolFrame::DECLARE_CLASS (ToolFrame)
ToolFrame::DECLARE_EVENT_TABLE ()
void ToolFrame::OnCaptureLost (wxMouseCaptureLostEvent & event) [inline]
void ToolFrame::OnClose (wxCloseEvent & event) [inline]
void ToolFrame::OnGrabber (GrabberEvent & event) [inline]
References mManager.
void ToolFrame::OnMotion (wxMouseEvent & event) [inline]
References ToolBar::IsDocked(), ToolBar::IsResizable(), mBar, mMinSize, and sizerW.
void ToolFrame::OnPaint (wxPaintEvent & event) [inline]
References ToolBar::IsResizable(), AColor::Line(), mBar, and sizerW.
void ToolFrame::OnToolBarUpdate (wxCommandEvent & event) [inline]
References mBar.
Member Data Documentation
ToolBar* ToolFrame::mBar [private]
Referenced by OnMotion(), OnPaint(), OnToolBarUpdate(), and ToolFrame().
ToolManager* ToolFrame::mManager [private]
Referenced by OnGrabber(), and ToolFrame().
wxSize ToolFrame::mMinSize [private]
Referenced by OnMotion(), and ToolFrame().
wxWindow* ToolFrame::mParent [private]
Referenced by ToolFrame().
The documentation for this class was generated from the following file:
ToolManager.cpp