Audacity: WaveClip Class Reference
WaveClip Class Reference
This allows multiple clips to be a part of one WaveTrack.
#include <WaveClip.h>
Public Member Functions
WaveClip (DirManager *projDirManager, sampleFormat format, int rate)
WaveClip (WaveClip &orig, DirManager *projDirManager)
virtual ~WaveClip ()
void ConvertToSampleFormat (sampleFormat format)
void TimeToSamplesClip (double t0, sampleCount *s0) const
int GetRate () const
void SetRate (int rate)
bool Resample (int rate, ProgressDialog *progress=NULL)
void SetOffset (double offset)
double GetOffset () const
void Offset (double delta)
double GetStartTime () const
double GetEndTime () const
sampleCount GetStartSample () const
sampleCount GetEndSample () const
sampleCount GetNumSamples () const
bool WithinClip (double t) const
bool BeforeClip (double t) const
bool AfterClip (double t) const
bool GetSamples (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len) const
bool SetSamples (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len)
Envelope * GetEnvelope ()
BlockArray * GetSequenceBlockArray ()
Sequence * GetSequence ()
void MarkChanged ()
bool CreateFromCopy (double t0, double t1, WaveClip *other)
Create clip from copy, discarding previous information in the clip.
bool GetWaveDisplay (float *min, float *max, float *rms, int *bl, sampleCount *where, int numPixels, double t0, double pixelsPerSecond, bool &isLoadingOD)
bool GetSpectrogram (float *buffer, sampleCount *where, int numPixels, double t0, double pixelsPerSecond, bool autocorrelation)
bool GetMinMax (float *min, float *max, double t0, double t1)
bool GetRMS (float *rms, double t0, double t1)
void ClearDisplayRect ()
void SetDisplayRect (const wxRect &r)
void GetDisplayRect (wxRect *r)
void UpdateEnvelopeTrackLen ()
bool Append (samplePtr buffer, sampleFormat format, sampleCount len, unsigned int stride=1, XMLWriter *blockFileLog=NULL)
You must call Flush after the last Append.
bool Flush ()
Flush must be called after last Append.
bool AppendAlias (wxString fName, sampleCount start, sampleCount len, int channel, bool useOD)
bool AppendCoded (wxString fName, sampleCount start, sampleCount len, int channel, int decodeType)
bool Clear (double t0, double t1)
bool ClearAndAddCutLine (double t0, double t1)
Clear, and add cut line that starts at t0 and contains everything until t1.
bool Paste (double t0, WaveClip *other)
Paste data from other clip, resampling it if not equal rate.
bool InsertSilence (double t, double len)
WaveClipList * GetCutLines ()
Get access to cut lines list.
bool FindCutLine (double cutLinePosition, double *cutLineStart=NULL, double *cutLineEnd=NULL)
bool ExpandCutLine (double cutLinePosition)
bool RemoveCutLine (double cutLinePosition)
Remove cut line, without expanding the audio in it.
void RemoveAllCutLines ()
void OffsetCutLines (double t0, double len)
Offset cutlines right to time 't0' by time amount 'len'.
void Lock ()
Lock all blockfiles.
void CloseLock ()
void Unlock ()
Unlock all blockfiles.
void DeleteWaveCache ()
Delete the wave cache - force redraw. Thread-safe.
void AddInvalidRegion (long startSample, long endSample)
Adds an invalid region to the wavecache so it redraws that portion only.
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual void HandleXMLEndTag (const wxChar *tag)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
bool GetIsPlaceholder ()
void SetIsPlaceholder (bool val)
Public Attributes
SpecPxCache * mSpecPxCache
Protected Attributes
wxRect mDisplayRect
double mOffset
int mRate
int mDirty
bool mIsCutLine
Sequence * mSequence
Envelope * mEnvelope
WaveCache * mWaveCache
ODLock mWaveCacheMutex
SpecCache * mSpecCache
HFFT hFFT
float * mWindow
int mWindowType
int mWindowSize
samplePtr mAppendBuffer
sampleCount mAppendBufferLen
WaveClipList mCutLines
bool mIsPlaceholder
Private Member Functions
WaveClip (const WaveClip &)
Detailed Description
This allows multiple clips to be a part of one WaveTrack.
Constructor & Destructor Documentation
WaveClip::WaveClip (const WaveClip &) [inline, private]
Referenced by ClearAndAddCutLine(), HandleXMLChild(), and Paste().
WaveClip::WaveClip (DirManager * projDirManager, sampleFormat format, int rate)
References hFFT, mAppendBuffer, mAppendBufferLen, mDirty, mEnvelope, mIsPlaceholder, mOffset, mRate, mSequence, mSpecCache, mSpecPxCache, mWaveCache, mWindow, mWindowSize, and mWindowType.
WaveClip::WaveClip (WaveClip & orig, DirManager * projDirManager)
References GetIsPlaceholder(), Sequence::GetNumSamples(), GetOffset(), hFFT, mAppendBuffer, mAppendBufferLen, mCutLines, mDirty, mEnvelope, mIsPlaceholder, mOffset, mRate, mSequence, mSpecCache, mSpecPxCache, mWaveCache, mWindow, mWindowSize, mWindowType, Envelope::Paste(), Envelope::SetOffset(), and Envelope::SetTrackLen().
WaveClip::~WaveClip () [virtual]
References DeleteSamples(), EndFFT(), hFFT, mAppendBuffer, mCutLines, mEnvelope, mSequence, mSpecCache, mSpecPxCache, mWaveCache, and mWindow.
Member Function Documentation
void WaveClip::AddInvalidRegion (long startSample, long endSample)
Adds an invalid region to the wavecache so it redraws that portion only.
References WaveCache::AddInvalidRegion(), mWaveCache, and mWaveCacheMutex.
bool WaveClip::AfterClip (double t) const
References GetEndSample(), mAppendBufferLen, and mRate.
Referenced by TrackPanel::AddClipsToCaptured(), and WaveTrack::HandleClear().
bool WaveClip::Append (samplePtr buffer, sampleFormat format, sampleCount len, unsigned int stride = 1, XMLWriter * blockFileLog = NULL)
You must call Flush after the last Append.
References Sequence::Append(), CopySamples(), Sequence::GetIdealAppendLen(), Sequence::GetMaxBlockSize(), Sequence::GetSampleFormat(), mAppendBuffer, mAppendBufferLen, MarkChanged(), mSequence, NewSamples(), SAMPLE_SIZE, and UpdateEnvelopeTrackLen().
Referenced by WaveTrack::Append(), and EffectReverse::ProcessOneWave().
bool WaveClip::AppendAlias (wxString fName, sampleCount start, sampleCount len, int channel, bool useOD)
References Sequence::AppendAlias(), MarkChanged(), mSequence, and UpdateEnvelopeTrackLen().
Referenced by WaveTrack::AppendAlias().
bool WaveClip::AppendCoded (wxString fName, sampleCount start, sampleCount len, int channel, int decodeType)
References Sequence::AppendCoded(), MarkChanged(), mSequence, and UpdateEnvelopeTrackLen().
Referenced by WaveTrack::AppendCoded().
bool WaveClip::BeforeClip (double t) const
References GetStartSample(), and mRate.
Referenced by TrackPanel::AddClipsToCaptured(), WaveTrack::HandleClear(), and WaveTrack::InsertSilence().
bool WaveClip::Clear (double t0, double t1)
This name is consistent with WaveTrack::Clear. It performs a "Cut" operation (but without putting the cutted audio to the clipboard)
References Envelope::CollapseRegion(), GetEndTime(), GetEnvelope(), GetOffset(), GetSequence(), GetStartTime(), MarkChanged(), mCutLines, mOffset, Offset(), and TimeToSamplesClip().
Referenced by WaveTrack::HandleClear(), WaveTrack::SplitAt(), and WaveTrack::Trim().
bool WaveClip::ClearAndAddCutLine (double t0, double t1)
Clear, and add cut line that starts at t0 and contains everything until t1.
References Envelope::CollapseRegion(), CreateFromCopy(), Sequence::GetDirManager(), GetEndTime(), GetEnvelope(), GetOffset(), Sequence::GetSampleFormat(), GetSequence(), GetStartTime(), MarkChanged(), mCutLines, mOffset, mRate, mSequence, Offset(), SetOffset(), TimeToSamplesClip(), and WaveClip().
Referenced by WaveTrack::HandleClear().
void WaveClip::ClearDisplayRect ()
References mDisplayRect.
void WaveClip::CloseLock ()
References Sequence::CloseLock(), GetSequence(), and mCutLines.
void WaveClip::ConvertToSampleFormat (sampleFormat format)
References Sequence::ConvertToSampleFormat(), MarkChanged(), and mSequence.
bool WaveClip::CreateFromCopy (double t0, double t1, WaveClip * other)
Create clip from copy, discarding previous information in the clip.
References Sequence::Copy(), Envelope::CopyFrom(), MarkChanged(), mEnvelope, mSequence, and TimeToSamplesClip().
Referenced by ClearAndAddCutLine(), and WaveTrack::Copy().
void WaveClip::DeleteWaveCache ()
Delete the wave cache - force redraw. Thread-safe.
References mWaveCache, and mWaveCacheMutex.
bool WaveClip::ExpandCutLine (double cutLinePosition)
Expand cut line (that is, re-insert audio, then delete audio saved in cut line). Returns true if a cut line could be found and sucessfully expanded, false otherwise
References GetOffset(), mCutLines, mOffset, and Paste().
Referenced by WaveTrack::ExpandCutLine().
bool WaveClip::FindCutLine (double cutLinePosition, double * cutLineStart = NULL, double * cutLineEnd = NULL)
Find cut line at (approximately) this position. Returns true and fills in cutLineStart and cutLineEnd (if specified) if a cut line at this position could be found. Return false otherwise.
References GetEndTime(), GetOffset(), GetStartTime(), mCutLines, and mOffset.
Referenced by WaveTrack::ExpandCutLine().
bool WaveClip::Flush ()
Flush must be called after last Append.
References Sequence::Append(), Sequence::GetSampleFormat(), mAppendBuffer, mAppendBufferLen, MarkChanged(), mSequence, and UpdateEnvelopeTrackLen().
Referenced by WaveTrack::Flush().
WaveClipList* WaveClip::GetCutLines () [inline]
Get access to cut lines list.
Referenced by WaveTrack::ClearAndPaste(), and WaveTrack::UpdateLocationsCache().
void WaveClip::GetDisplayRect (wxRect * r)
References mDisplayRect.
Referenced by WaveTrack::GetClipAtX().
sampleCount WaveClip::GetEndSample () const
References Sequence::GetNumSamples(), GetStartSample(), and mSequence.
Referenced by AfterClip(), WaveTrack::Get(), EffectReverse::ProcessOneWave(), WaveTrack::Set(), WaveTrack::Silence(), and WithinClip().
double WaveClip::GetEndTime () const
References Sequence::GetNumSamples(), mAppendBufferLen, mOffset, mRate, and mSequence.
Referenced by WaveTrack::CanInsertClip(), WaveTrack::CanOffsetClip(), Clear(), ClearAndAddCutLine(), WaveTrack::ClearAndPaste(), WaveTrack::Copy(), WaveTrack::Disjoin(), TrackPanel::DoSlide(), TrackArtist::DrawClipSpectrum(), TrackArtist::DrawClipWaveform(), WaveTrack::ExpandCutLine(), FindCutLine(), WaveTrack::GetEnvelopeValues(), WaveTrack::GetMinMax(), WaveTrack::GetRMS(), WaveTrack::HandleClear(), TrackPanel::HandleSelect(), WaveTrack::IsEmpty(), WaveTrack::Join(), WaveTrack::MergeClips(), WaveTrack::Paste(), Paste(), EffectEqualization::ProcessOne(), SnapManager::SnapManager(), WaveTrack::SplitAt(), TrackPanel::StartSlide(), WaveTrack::Trim(), and WaveTrack::UpdateLocationsCache().
Envelope* WaveClip::GetEnvelope () [inline]
Referenced by Clear(), ClearAndAddCutLine(), TrackArtist::DrawClipWaveform(), TrackArtist::DrawIndividualSamples(), WaveTrack::GetActiveEnvelope(), WaveTrack::GetEnvelopeAtX(), WaveTrack::GetEnvelopeValues(), WaveTrack::HandleClear(), WaveTrack::HandleXMLChild(), InsertSilence(), and WaveTrack::SplitAt().
bool WaveClip::GetIsPlaceholder () [inline]
Referenced by WaveTrack::Paste(), and WaveClip().
bool WaveClip::GetMinMax (float * min, float * max, double t0, double t1)
References Sequence::GetMinMax(), mSequence, and TimeToSamplesClip().
sampleCount WaveClip::GetNumSamples () const [inline]
Referenced by CrossFader::CrossFadeMix(), TrackArtist::DrawIndividualSamples(), WaveTrack::Get(), WaveTrack::GetBestBlockSize(), WaveTrack::GetRMS(), AudacityProject::GetTime(), WaveTrack::Set(), and WaveTrack::Silence().
double WaveClip::GetOffset () const [inline]
Referenced by Clear(), ClearAndAddCutLine(), WaveTrack::ClearAndPaste(), WaveTrack::Copy(), TrackArtist::DrawClipSpectrum(), TrackArtist::DrawClipWaveform(), TrackArtist::DrawIndividualSamples(), ExpandCutLine(), FindCutLine(), WaveTrack::HandleClear(), TrackPanel::HandleSelect(), WaveTrack::Join(), OffsetCutLines(), WaveTrack::SetOffset(), WaveTrack::SplitAt(), WaveTrack::UpdateLocationsCache(), and WaveClip().
int WaveClip::GetRate () const [inline]
Referenced by TrackArtist::DrawClipSpectrum(), TrackArtist::DrawClipWaveform(), TrackArtist::DrawIndividualSamples(), WaveTrack::HandleClear(), WaveTrack::SplitAt(), ODDecodeTask::Update(), and ODComputeSummaryTask::Update().
bool WaveClip::GetRMS (float * rms, double t0, double t1)
References Sequence::GetRMS(), mSequence, and TimeToSamplesClip().
bool WaveClip::GetSamples (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len) const
References Sequence::Get(), and mSequence.
Referenced by WaveTrack::Disjoin(), TrackArtist::DrawIndividualSamples(), and WaveTrack::Get().
Sequence* WaveClip::GetSequence () [inline]
Referenced by AudacityProject::AddImportedTracks(), Clear(), ClearAndAddCutLine(), CloseLock(), CrossFader::CrossFadeMix(), GetAllSeqBlocks(), WaveTrack::GetBestBlockSize(), WaveTrack::GetIdealBlockSize(), WaveTrack::GetMaxBlockSize(), WaveTrack::GetODFlags(), WaveTrack::GetSequenceAtX(), WaveTrack::HandleXMLChild(), RecordingRecoveryHandler::HandleXMLTag(), InsertSilence(), Lock(), BenchmarkDialog::OnRun(), WaveTrack::Silence(), Unlock(), ODDecodeTask::Update(), and ODComputeSummaryTask::Update().
BlockArray* WaveClip::GetSequenceBlockArray () [inline]
Referenced by ODDecodeTask::Update(), and ODComputeSummaryTask::Update().
bool WaveClip::GetSpectrogram (float * buffer, sampleCount * where, int numPixels, double t0, double pixelsPerSecond, bool autocorrelation)
EXPERIMENTAL_FFT_SKIP_POINTS
EXPERIMENTAL_FFT_SKIP_POINTS
EXPERIMENTAL_FFT_SKIP_POINTS
References SpecCache::ac, ComputeSpectrum(), ComputeSpectrumUsingRealFFTf(), SpecCache::dirty, EndFFT(), floatSample, SpecCache::freq, SpecCache::frequencyGainOld, SpecCache::gainOld, Sequence::Get(), Sequence::GetNumSamples(), gPrefs, hFFT, InitializeFFT(), SpecCache::len, SpecCache::maxFreqOld, mDirty, SpecCache::minFreqOld, mRate, mSequence, mSpecCache, mWindow, mWindowSize, mWindowType, SpecCache::pps, SpecCache::rangeOld, SpecCache::start, SpecCache::where, WindowFunc(), SpecCache::windowSizeOld, and SpecCache::windowTypeOld.
Referenced by TrackArtist::DrawClipSpectrum().
sampleCount WaveClip::GetStartSample () const
References mOffset, and mRate.
Referenced by BeforeClip(), CrossFader::CrossFadeMix(), WaveTrack::Get(), GetEndSample(), WaveTrack::Paste(), EffectReverse::ProcessOneWave(), WaveTrack::Set(), WaveTrack::Silence(), and WithinClip().
double WaveClip::GetStartTime () const
References mOffset.
Referenced by WaveTrack::CanInsertClip(), WaveTrack::CanOffsetClip(), Clear(), ClearAndAddCutLine(), WaveTrack::ClearAndPaste(), WaveTrack::Copy(), WaveTrack::Disjoin(), TrackPanel::DoSlide(), TrackArtist::DrawClipSpectrum(), TrackArtist::DrawClipWaveform(), WaveTrack::ExpandCutLine(), FindCutLine(), WaveTrack::GetBestBlockSize(), WaveTrack::GetEnvelopeValues(), WaveTrack::GetMinMax(), WaveTrack::GetRMS(), AudacityProject::GetTime(), WaveTrack::HandleClear(), WaveTrack::IsEmpty(), WaveTrack::Join(), WaveTrack::Paste(), Paste(), EffectEqualization::ProcessOne(), SnapManager::SnapManager(), WaveTrack::SplitAt(), TrackPanel::StartSlide(), WaveTrack::Trim(), ODDecodeTask::Update(), ODComputeSummaryTask::Update(), and WaveTrack::UpdateLocationsCache().
bool WaveClip::GetWaveDisplay (float * min, float * max, float * rms, int * bl, sampleCount * where, int numPixels, double t0, double pixelsPerSecond, bool & isLoadingOD)
Getting high-level data from the for screen display and clipping calculations and Contrast
References WaveCache::bl, WaveCache::ClearInvalidRegions(), CopySamples(), WaveCache::dirty, floatSample, WaveCache::GetInvalidRegionEnd(), WaveCache::GetInvalidRegionStart(), WaveCache::GetNumInvalidRegions(), Sequence::GetNumSamples(), Sequence::GetSampleFormat(), Sequence::GetWaveDisplay(), WaveCache::len, mAppendBuffer, mAppendBufferLen, WaveCache::max, mDirty, WaveCache::min, mRate, mSequence, mWaveCache, mWaveCacheMutex, WaveCache::numODPixels, WaveCache::pps, WaveCache::rate, WaveCache::rms, SAMPLE_SIZE, WaveCache::start, and WaveCache::where.
Referenced by TrackArtist::DrawClipWaveform().
XMLTagHandler * WaveClip::HandleXMLChild (const wxChar * tag) [virtual]
Implements XMLTagHandler.
References Sequence::GetDirManager(), Sequence::GetSampleFormat(), mCutLines, mEnvelope, mRate, mSequence, and WaveClip().
void WaveClip::HandleXMLEndTag (const wxChar * tag) [virtual]
Reimplemented from XMLTagHandler.
References UpdateEnvelopeTrackLen().
Referenced by WaveTrack::HandleXMLEndTag().
bool WaveClip::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements XMLTagHandler.
References Internat::CompatibleToDouble(), XMLValueChecker::IsGoodString(), and SetOffset().
bool WaveClip::InsertSilence (double t, double len)
Insert silence - note that this is an efficient operation for large amounts of silence
References GetEnvelope(), GetSequence(), Sequence::InsertSilence(), Envelope::InsertSpace(), MarkChanged(), mRate, OffsetCutLines(), and TimeToSamplesClip().
Referenced by WaveTrack::Copy(), WaveTrack::InsertSilence(), and WaveTrack::Join().
void WaveClip::Lock ()
Lock all blockfiles.
References GetSequence(), Sequence::Lock(), and mCutLines.
void WaveClip::MarkChanged () [inline]
WaveTrack calls this whenever data in the wave clip changes. It is called automatically when WaveClip has a chance to know that something has changed, like when member functions SetSamples() etc. are called.
Referenced by Append(), AppendAlias(), AppendCoded(), Clear(), ClearAndAddCutLine(), ConvertToSampleFormat(), CreateFromCopy(), Flush(), InsertSilence(), WaveTrack::Paste(), Paste(), AudacityProject::RedrawProject(), WaveTrack::Set(), SetRate(), SetSamples(), and WaveTrack::Silence().
void WaveClip::Offset (double delta) [inline]
Referenced by Clear(), ClearAndAddCutLine(), WaveTrack::Copy(), TrackPanel::DoSlide(), WaveTrack::ExpandCutLine(), WaveTrack::HandleClear(), WaveTrack::InsertSilence(), OffsetCutLines(), WaveTrack::Paste(), Paste(), and WaveTrack::SplitAt().
void WaveClip::OffsetCutLines (double t0, double len)
Offset cutlines right to time 't0' by time amount 'len'.
References GetOffset(), mCutLines, mOffset, and Offset().
Referenced by InsertSilence(), and Paste().
bool WaveClip::Paste (double t0, WaveClip * other)
Paste data from other clip, resampling it if not equal rate.
References Sequence::GetDirManager(), GetEndTime(), GetStartTime(), MarkChanged(), mCutLines, mEnvelope, mOffset, mRate, mSequence, Offset(), OffsetCutLines(), Envelope::Paste(), Sequence::Paste(), Envelope::RemoveUnneededPoints(), Resample(), TimeToSamplesClip(), and WaveClip().
Referenced by ExpandCutLine(), WaveTrack::Join(), WaveTrack::MergeClips(), and WaveTrack::Paste().
void WaveClip::RemoveAllCutLines ()
References mCutLines.
Referenced by WaveTrack::Copy().
bool WaveClip::RemoveCutLine (double cutLinePosition)
Remove cut line, without expanding the audio in it.
References mCutLines, and mOffset.
bool WaveClip::Resample (int rate, ProgressDialog * progress = NULL)
References Sequence::Append(), eProgressSuccess, floatSample, Sequence::Get(), Sequence::GetDirManager(), Sequence::GetNumSamples(), Sequence::GetSampleFormat(), mRate, mSequence, mSpecCache, mWaveCache, and ProgressDialog::Update().
Referenced by WaveTrack::Paste(), and Paste().
void WaveClip::SetDisplayRect (const wxRect & r)
References mDisplayRect.
Referenced by TrackArtist::DrawClipSpectrum(), and TrackArtist::DrawClipWaveform().
void WaveClip::SetIsPlaceholder (bool val) [inline]
Referenced by WaveTrack::Copy().
void WaveClip::SetOffset (double offset)
References mEnvelope, mOffset, and Envelope::SetOffset().
Referenced by ClearAndAddCutLine(), WaveTrack::ClearAndPaste(), WaveTrack::Copy(), WaveTrack::GetLastOrCreateClip(), WaveTrack::HandleXMLChild(), HandleXMLTag(), WaveTrack::Join(), EffectReverse::ProcessOneWave(), WaveTrack::SetOffset(), and WaveTrack::Trim().
void WaveClip::SetRate (int rate)
References MarkChanged(), mRate, and UpdateEnvelopeTrackLen().
bool WaveClip::SetSamples (samplePtr buffer, sampleFormat format, sampleCount start, sampleCount len)
References MarkChanged(), mSequence, and Sequence::Set().
Referenced by WaveTrack::Set().
void WaveClip::TimeToSamplesClip (double t0, sampleCount * s0) const
References Sequence::GetNumSamples(), mOffset, mRate, and mSequence.
Referenced by Clear(), ClearAndAddCutLine(), CreateFromCopy(), WaveTrack::Disjoin(), GetMinMax(), GetRMS(), InsertSilence(), and Paste().
void WaveClip::Unlock ()
Unlock all blockfiles.
References GetSequence(), mCutLines, and Sequence::Unlock().
void WaveClip::UpdateEnvelopeTrackLen ()
Whenever you do an operation to the sequence that will change the number of samples (that is, the length of the clip), you will want to call this function to tell the envelope about it.
References Sequence::GetNumSamples(), mEnvelope, mRate, mSequence, and Envelope::SetTrackLen().
Referenced by Append(), AppendAlias(), AppendCoded(), Flush(), HandleXMLEndTag(), and SetRate().
bool WaveClip::WithinClip (double t) const
References GetEndSample(), GetStartSample(), mAppendBufferLen, and mRate.
Referenced by WaveTrack::HandleClear(), WaveTrack::InsertSilence(), WaveTrack::Paste(), and WaveTrack::SplitAt().
void WaveClip::WriteXML (XMLWriter & xmlFile) [virtual]
References XMLWriter::EndTag(), mCutLines, mEnvelope, mOffset, mSequence, XMLWriter::StartTag(), XMLWriter::WriteAttr(), Envelope::WriteXML(), and Sequence::WriteXML().
Member Data Documentation
HFFT WaveClip::hFFT [protected]
Referenced by GetSpectrogram(), WaveClip(), and ~WaveClip().
samplePtr WaveClip::mAppendBuffer [protected]
Referenced by Append(), Flush(), GetWaveDisplay(), WaveClip(), and ~WaveClip().
sampleCount WaveClip::mAppendBufferLen [protected]
Referenced by AfterClip(), Append(), Flush(), GetEndTime(), GetWaveDisplay(), WaveClip(), and WithinClip().
WaveClipList WaveClip::mCutLines [protected]
Referenced by Clear(), ClearAndAddCutLine(), CloseLock(), ExpandCutLine(), FindCutLine(), HandleXMLChild(), Lock(), OffsetCutLines(), Paste(), RemoveAllCutLines(), RemoveCutLine(), Unlock(), WaveClip(), WriteXML(), and ~WaveClip().
int WaveClip::mDirty [protected]
Referenced by GetSpectrogram(), GetWaveDisplay(), and WaveClip().
wxRect WaveClip::mDisplayRect [protected]
Referenced by ClearDisplayRect(), GetDisplayRect(), and SetDisplayRect().
Envelope* WaveClip::mEnvelope [protected]
Referenced by CreateFromCopy(), HandleXMLChild(), Paste(), SetOffset(), UpdateEnvelopeTrackLen(), WaveClip(), WriteXML(), and ~WaveClip().
bool WaveClip::mIsCutLine [protected]
bool WaveClip::mIsPlaceholder [protected]
Referenced by WaveClip().
double WaveClip::mOffset [protected]
Referenced by Clear(), ClearAndAddCutLine(), ExpandCutLine(), FindCutLine(), GetEndTime(), GetStartSample(), GetStartTime(), OffsetCutLines(), Paste(), RemoveCutLine(), SetOffset(), TimeToSamplesClip(), WaveClip(), and WriteXML().
int WaveClip::mRate [protected]
Referenced by AfterClip(), BeforeClip(), ClearAndAddCutLine(), GetEndTime(), GetSpectrogram(), GetStartSample(), GetWaveDisplay(), HandleXMLChild(), InsertSilence(), Paste(), Resample(), SetRate(), TimeToSamplesClip(), UpdateEnvelopeTrackLen(), WaveClip(), and WithinClip().
Sequence* WaveClip::mSequence [protected]
Referenced by Append(), AppendAlias(), AppendCoded(), ClearAndAddCutLine(), ConvertToSampleFormat(), CreateFromCopy(), Flush(), GetEndSample(), GetEndTime(), GetMinMax(), GetRMS(), GetSamples(), GetSpectrogram(), GetWaveDisplay(), HandleXMLChild(), Paste(), Resample(), SetSamples(), TimeToSamplesClip(), UpdateEnvelopeTrackLen(), WaveClip(), WriteXML(), and ~WaveClip().
SpecCache* WaveClip::mSpecCache [protected]
Referenced by GetSpectrogram(), Resample(), WaveClip(), and ~WaveClip().
SpecPxCache* WaveClip::mSpecPxCache
Referenced by TrackArtist::DrawClipSpectrum(), WaveClip(), and ~WaveClip().
WaveCache* WaveClip::mWaveCache [protected]
Referenced by AddInvalidRegion(), DeleteWaveCache(), GetWaveDisplay(), Resample(), WaveClip(), and ~WaveClip().
ODLock WaveClip::mWaveCacheMutex [protected]
Referenced by AddInvalidRegion(), DeleteWaveCache(), and GetWaveDisplay().
float* WaveClip::mWindow [protected]
Referenced by GetSpectrogram(), WaveClip(), and ~WaveClip().
int WaveClip::mWindowSize [protected]
Referenced by GetSpectrogram(), and WaveClip().
int WaveClip::mWindowType [protected]
Referenced by GetSpectrogram(), and WaveClip().
The documentation for this class was generated from the following files:
WaveClip.h
WaveClip.cpp