Audacity: SelectionBar Class Reference
SelectionBar Class Reference
(not quite a Toolbar) at foot of screen for setting and viewing the selection range.
#include <SelectionBar.h>
Public Member Functions
SelectionBar ()
virtual ~SelectionBar ()
void Create (wxWindow *parent)
virtual void Populate ()
virtual void Repaint (wxDC *dc)
virtual void EnableDisableButtons ()
virtual void UpdatePrefs ()
void SetTimes (double start, double end, double audio)
double GetLeftTime ()
double GetRightTime ()
void SetField (const wxChar *msg, int fieldNum)
void SetSnapTo (bool state)
void SetRate (double rate)
void SetListener (SelectionBarListener *l)
DECLARE_CLASS (SelectionBar)
DECLARE_EVENT_TABLE ()
Private Member Functions
void ValuesToControls ()
void OnUpdate (wxCommandEvent &evt)
void OnLeftTime (wxCommandEvent &evt)
void OnRightTime (wxCommandEvent &evt)
void OnEndRadio (wxCommandEvent &evt)
void OnLengthRadio (wxCommandEvent &evt)
void OnRate (wxCommandEvent &event)
void OnSnapTo (wxCommandEvent &event)
void OnFocus (wxFocusEvent &event)
void OnCaptureKey (wxCommandEvent &event)
void OnSize (wxSizeEvent &evt)
void ModifySelection ()
void UpdateRates ()
Private Attributes
SelectionBarListener * mListener
double mRate
double mStart
double mEnd
double mAudio
wxString mField [10]
TimeTextCtrl * mLeftTime
TimeTextCtrl * mRightTime
wxRadioButton * mRightEndButton
wxRadioButton * mRightLengthButton
TimeTextCtrl * mAudioTime
wxComboBox * mRateBox
wxCheckBox * mSnapTo
wxWindow * mRateText
Detailed Description
(not quite a Toolbar) at foot of screen for setting and viewing the selection range.
Constructor & Destructor Documentation
SelectionBar::SelectionBar ()
SelectionBar::~SelectionBar () [virtual]
Member Function Documentation
void SelectionBar::Create (wxWindow * parent) [virtual]
Reimplemented from ToolBar.
SelectionBar::DECLARE_CLASS (SelectionBar)
Reimplemented from ToolBar.
SelectionBar::DECLARE_EVENT_TABLE ()
Reimplemented from ToolBar.
virtual void SelectionBar::EnableDisableButtons () [inline, virtual]
Implements ToolBar.
double SelectionBar::GetLeftTime ()
References TimeTextCtrl::GetTimeValue(), and mLeftTime.
double SelectionBar::GetRightTime ()
References TimeTextCtrl::GetFormatString(), TimeTextCtrl::GetTimeValue(), mEnd, mRate, mRightEndButton, mRightTime, TimeTextCtrl::SetFormatString(), TimeTextCtrl::SetSampleRate(), and TimeTextCtrl::SetTimeValue().
void SelectionBar::ModifySelection () [private]
References SelectionBarListener::AS_ModifySelection(), TimeTextCtrl::GetTimeValue(), mEnd, mLeftTime, mListener, mRightEndButton, mRightTime, and mStart.
Referenced by OnLeftTime(), and OnRightTime().
void SelectionBar::OnCaptureKey (wxCommandEvent & event) [private]
References mRateText, and mSnapTo.
void SelectionBar::OnEndRadio (wxCommandEvent & evt) [private]
References gPrefs, mRightTime, and ValuesToControls().
void SelectionBar::OnFocus (wxFocusEvent & event) [private]
Referenced by Populate().
void SelectionBar::OnLeftTime (wxCommandEvent & evt) [private]
References ModifySelection().
void SelectionBar::OnLengthRadio (wxCommandEvent & evt) [private]
References gPrefs, mRightTime, and ValuesToControls().
void SelectionBar::OnRate (wxCommandEvent & event) [private]
References SelectionBarListener::AS_SetRate(), mAudioTime, mLeftTime, mListener, mRate, mRateBox, mRightTime, and TimeTextCtrl::SetSampleRate().
void SelectionBar::OnRightTime (wxCommandEvent & evt) [private]
References ModifySelection().
void SelectionBar::OnSize (wxSizeEvent & evt) [private]
void SelectionBar::OnSnapTo (wxCommandEvent & event) [private]
References SelectionBarListener::AS_SetSnapTo(), mListener, and mSnapTo.
void SelectionBar::OnUpdate (wxCommandEvent & evt) [private]
References TimeTextCtrl::GetBuiltinFormat(), TimeTextCtrl::GetBuiltinName(), gPrefs, mAudioTime, mLeftTime, mRate, mRateBox, mRateText, mRightEndButton, mRightLengthButton, mRightTime, ToolBar::ReCreateButtons(), TimeTextCtrl::SetFormatString(), ToolBar::Updated(), and ValuesToControls().
Referenced by UpdatePrefs().
void SelectionBar::Populate () [virtual]
Implements ToolBar.
References ToolBar::Add(), TimeTextCtrl::EnableMenu(), TimeTextCtrl::GetBuiltinFormat(), ToolBar::GetSizer(), gPrefs, mAudioTime, mLeftTime, mRate, mRateBox, mRateText, mRightEndButton, mRightLengthButton, mRightTime, mSnapTo, numbers, OnEndRadioID, OnFocus(), OnLeftTimeID, OnLengthRadioID, OnRateID, OnRightTimeID, OnSnapToID, TimeTextCtrl::SetFormatString(), toolbarSingle, and UpdateRates().
virtual void SelectionBar::Repaint (wxDC * dc) [inline, virtual]
Implements ToolBar.
void SelectionBar::SetField (const wxChar * msg, int fieldNum)
References mField.
void SelectionBar::SetListener (SelectionBarListener * l)
References mListener.
void SelectionBar::SetRate (double rate)
References mAudioTime, mLeftTime, mRate, mRateBox, mRightTime, and TimeTextCtrl::SetSampleRate().
Referenced by AudacityProject::AddImportedTracks(), and AudacityProject::HandleXMLTag().
void SelectionBar::SetSnapTo (bool state)
References mSnapTo.
Referenced by AudacityProject::SetSnapTo().
void SelectionBar::SetTimes (double start, double end, double audio)
References mAudio, mEnd, mStart, and ValuesToControls().
Referenced by AudacityProject::TP_DisplaySelection().
void SelectionBar::UpdatePrefs () [virtual]
Reimplemented from ToolBar.
References TimeTextCtrl::GetFormatIndex(), AudioIO::GetOptimalSupportedSampleRate(), gPrefs, mLeftTime, mRate, OnUpdate(), and ToolBar::SetLabel().
void SelectionBar::UpdateRates () [private]
References mRateBox, AudioIO::NumStandardRates, and AudioIO::StandardRates.
Referenced by Populate().
void SelectionBar::ValuesToControls () [private]
References mAudio, mAudioTime, mEnd, mLeftTime, mRightEndButton, mRightTime, mStart, and TimeTextCtrl::SetTimeValue().
Referenced by OnEndRadio(), OnLengthRadio(), OnUpdate(), and SetTimes().
Member Data Documentation
double SelectionBar::mAudio [private]
Referenced by SetTimes(), and ValuesToControls().
TimeTextCtrl* SelectionBar::mAudioTime [private]
Referenced by OnRate(), OnUpdate(), Populate(), SetRate(), and ValuesToControls().
double SelectionBar::mEnd [private]
Referenced by GetRightTime(), ModifySelection(), SetTimes(), and ValuesToControls().
wxString SelectionBar::mField[10] [private]
Referenced by SetField().
TimeTextCtrl* SelectionBar::mLeftTime [private]
Referenced by GetLeftTime(), ModifySelection(), OnRate(), OnUpdate(), Populate(), SetRate(), UpdatePrefs(), and ValuesToControls().
SelectionBarListener* SelectionBar::mListener [private]
Referenced by ModifySelection(), OnRate(), OnSnapTo(), and SetListener().
double SelectionBar::mRate [private]
Referenced by GetRightTime(), OnRate(), OnUpdate(), Populate(), SetRate(), and UpdatePrefs().
wxComboBox* SelectionBar::mRateBox [private]
Referenced by OnRate(), OnUpdate(), Populate(), SetRate(), and UpdateRates().
wxWindow* SelectionBar::mRateText [private]
Referenced by OnCaptureKey(), OnUpdate(), and Populate().
wxRadioButton* SelectionBar::mRightEndButton [private]
Referenced by GetRightTime(), ModifySelection(), OnUpdate(), Populate(), and ValuesToControls().
wxRadioButton* SelectionBar::mRightLengthButton [private]
Referenced by OnUpdate(), and Populate().
TimeTextCtrl* SelectionBar::mRightTime [private]
Referenced by GetRightTime(), ModifySelection(), OnEndRadio(), OnLengthRadio(), OnRate(), OnUpdate(), Populate(), SetRate(), and ValuesToControls().
wxCheckBox* SelectionBar::mSnapTo [private]
Referenced by OnCaptureKey(), OnSnapTo(), Populate(), and SetSnapTo().
double SelectionBar::mStart [private]
Referenced by ModifySelection(), SetTimes(), and ValuesToControls().
The documentation for this class was generated from the following files:
SelectionBar.h
SelectionBar.cpp