Audacity: ExportFLAC Class Reference
ExportFLAC Class Reference
Public Member Functions
ExportFLAC ()
void Destroy ()
bool DisplayOptions (wxWindow *parent, int format=0)
int Export (AudacityProject *project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec *mixerSpec=NULL, Tags *metadata=NULL, int subformat=0)
called to export audio into a file.
Private Member Functions
bool GetMetadata (AudacityProject *project, Tags *tags)
Private Attributes
FLAC__StreamMetadata * mMetadata
Constructor & Destructor Documentation
ExportFLAC::ExportFLAC ()
References ExportPlugin::AddExtension(), ExportPlugin::AddFormat(), ExportPlugin::SetCanMetaData(), ExportPlugin::SetDescription(), ExportPlugin::SetFormat(), and ExportPlugin::SetMaxChannels().
Member Function Documentation
void ExportFLAC::Destroy () [virtual]
Reimplemented from ExportPlugin.
bool ExportFLAC::DisplayOptions (wxWindow * parent, int format = 0) [virtual]
Reimplemented from ExportPlugin.
int ExportFLAC::Export (AudacityProject * project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec * mixerSpec = NULL, Tags * metadata = NULL, int subformat = 0) [virtual]
called to export audio into a file.
Parameters:
selectedOnly Set to true if all tracks should be mixed, to false if only the selected tracks should be mixed and exported.
metadata A Tags object that will over-ride the one in *project and be used to tag the file that is exported.
subformat Control which of the multiple formats this exporter is capable of exporting should be used. Used where a single export plug-in handles a number of related formats, but they have separate entries in the Format drop-down list box. For example, the options to export to "Other PCM", "AIFF 16 Bit" and "WAV 16 Bit" are all the same libsndfile export plug-in, but with subformat set to 0, 1, and 2 respectively.
Reimplemented from ExportPlugin.
References do_escape_coding, do_exhaustive_model_search, do_mid_side_stereo, eProgressSuccess, flacLevels, Mixer::GetBuffer(), GetMetadata(), AudacityProject::GetRate(), TrackList::GetTimeTrack(), AudacityProject::GetTracks(), TrackList::GetWaveTracks(), gPrefs, int16Sample, int24Sample, loose_mid_side_stereo, max_lpc_order, max_residual_partition_order, min_residual_partition_order, Mixer::MixGetCurrentTime(), mMetadata, OSOUTPUT, Mixer::Process(), qlp_coeff_precision, rice_parameter_search_dist, SAMPLES_PER_RUN, and ProgressDialog::Update().
bool ExportFLAC::GetMetadata (AudacityProject * project, Tags * tags) [private]
References Tags::GetFirst(), Tags::GetNext(), AudacityProject::GetTags(), mMetadata, and TAG_YEAR.
Referenced by Export().
Member Data Documentation
FLAC__StreamMetadata* ExportFLAC::mMetadata [private]
Referenced by Export(), and GetMetadata().
The documentation for this class was generated from the following file:
ExportFLAC.cpp