Audacity: DirectoriesPrefs Class Reference
DirectoriesPrefs Class Reference
A PrefsPanel used to select directories.
#include <DirectoriesPrefs.h>
Public Member Functions
DirectoriesPrefs (wxWindow *parent)
~DirectoriesPrefs ()
virtual bool Apply ()
virtual bool Validate ()
Private Member Functions
void Populate ()
Creates the dialog and its contents.
void PopulateOrExchange (ShuttleGui &S)
void UpdateFreeSpace (wxCommandEvent &e)
void OnChooseTempDir (wxCommandEvent &e)
DECLARE_EVENT_TABLE ()
Private Attributes
wxStaticText * mFreeSpace
wxTextCtrl * mTempDir
Detailed Description
A PrefsPanel used to select directories.
Constructor & Destructor Documentation
DirectoriesPrefs::DirectoriesPrefs (wxWindow * parent)
DirectoriesPrefs::~DirectoriesPrefs ()
Member Function Documentation
bool DirectoriesPrefs::Apply () [virtual]
Implements PrefsPanel.
References eIsSavingToPrefs, and PopulateOrExchange().
DirectoriesPrefs::DECLARE_EVENT_TABLE () [private]
void DirectoriesPrefs::OnChooseTempDir (wxCommandEvent & e) [private]
References gPrefs, mTempDir, UpdateFreeSpace(), and wxGetApp().
void DirectoriesPrefs::Populate () [private]
Creates the dialog and its contents.
References eIsCreatingFromPrefs, PopulateOrExchange(), and UpdateFreeSpace().
void DirectoriesPrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddFixedText(), ShuttleGuiBase::AddVariableText(), ChooseButtonID, ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndTwoColumn(), ShuttleGui::Id(), mFreeSpace, mTempDir, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartTwoColumn(), TempDirID, ShuttleGuiBase::TieCheckBox(), and ShuttleGuiBase::TieTextBox().
Referenced by Apply(), and Populate().
void DirectoriesPrefs::UpdateFreeSpace (wxCommandEvent & e) [private]
References Internat::FormatSize(), label, mFreeSpace, and mTempDir.
Referenced by OnChooseTempDir(), and Populate().
bool DirectoriesPrefs::Validate () [virtual]
References gPrefs, and mTempDir.
Member Data Documentation
wxStaticText* DirectoriesPrefs::mFreeSpace [private]
Referenced by PopulateOrExchange(), and UpdateFreeSpace().
wxTextCtrl* DirectoriesPrefs::mTempDir [private]
Referenced by OnChooseTempDir(), PopulateOrExchange(), UpdateFreeSpace(), and Validate().
The documentation for this class was generated from the following files:
DirectoriesPrefs.h
DirectoriesPrefs.cpp