Audacity: Exporter Class Reference
Exporter Class Reference
#include <Export.h>
Public Member Functions
Exporter ()
virtual ~Exporter ()
void RegisterPlugin (ExportPlugin *plugin)
bool Process (AudacityProject *project, bool selectedOnly, double t0, double t1)
bool Process (AudacityProject *project, int numChannels, const wxChar *type, const wxString filename, bool selectedOnly, double t0, double t1)
void DisplayOptions (int index)
int FindFormatIndex (int exportindex)
const ExportPluginArray GetPlugins ()
Private Member Functions
bool ExamineTracks ()
bool GetFilename ()
bool CheckFilename ()
bool CheckMix ()
bool ExportTracks ()
Private Attributes
FileDialog * mDialog
AudacityProject * mProject
MixerSpec * mMixerSpec
ExportPluginArray mPlugins
wxFileName mFilename
wxFileName mActualName
double mT0
double mT1
int mFilterIndex
int mFormat
int mSubFormat
int mNumSelected
int mNumLeft
int mNumRight
int mNumMono
int mChannels
bool mSelectedOnly
Constructor & Destructor Documentation
Exporter::Exporter ()
References mMixerSpec, New_ExportCL(), New_ExportFFmpeg(), New_ExportFLAC(), New_ExportMP2(), New_ExportMP3(), New_ExportOGG(), New_ExportPCM(), and RegisterPlugin().
Exporter::~Exporter () [virtual]
References mMixerSpec, and mPlugins.
Member Function Documentation
bool Exporter::CheckFilename () [private]
References DirManager::EnsureSafeFilename(), AudacityProject::GetDirManager(), gPrefs, mActualName, mFilename, mFormat, mPlugins, mProject, and mSubFormat.
Referenced by Process().
bool Exporter::CheckMix () [private]
References MixerSpec::GetNumChannels(), AudacityProject::GetTracks(), gPrefs, mChannels, mFormat, mMixerSpec, mNumLeft, mNumMono, mNumRight, mPlugins, mProject, mSelectedOnly, mSubFormat, and ShowWarningDialog().
Referenced by Process().
void Exporter::DisplayOptions (int index)
References mDialog, mPlugins, and mProject.
bool Exporter::ExamineTracks () [private]
References TrackListIterator::First(), Track::GetChannel(), Track::GetEndTime(), Track::GetKind(), Track::GetMute(), Track::GetOffset(), Track::GetSelected(), AudacityProject::GetTracks(), Track::LeftChannel, mNumLeft, mNumMono, mNumRight, mNumSelected, Track::MonoChannel, mProject, mSelectedOnly, mT0, mT1, TrackListIterator::Next(), Track::RightChannel, and Track::Wave.
Referenced by Process().
bool Exporter::ExportTracks () [private]
References eProgressStopped, eProgressSuccess, mActualName, mChannels, mFilename, mFormat, mMixerSpec, mPlugins, mProject, mSelectedOnly, mSubFormat, mT0, and mT1.
Referenced by Process().
int Exporter::FindFormatIndex (int exportindex)
References mPlugins.
bool Exporter::GetFilename () [private]
References ExportCallback(), AudacityProject::GetName(), gPrefs, mDialog, mFilename, mFilterIndex, mFormat, mPlugins, mProject, and mSubFormat.
Referenced by Process().
const ExportPluginArray Exporter::GetPlugins ()
References mPlugins.
bool Exporter::Process (AudacityProject * project, int numChannels, const wxChar * type, const wxString filename, bool selectedOnly, double t0, double t1)
References ExportTracks(), mActualName, mChannels, mFilename, mFormat, mPlugins, mProject, mSelectedOnly, mSubFormat, mT0, and mT1.
bool Exporter::Process (AudacityProject * project, bool selectedOnly, double t0, double t1)
References CheckFilename(), CheckMix(), ExamineTracks(), ExportTracks(), GetFilename(), AudacityProject::GetShowId3Dialog(), AudacityProject::GetTags(), mFormat, mMixerSpec, mPlugins, mProject, mSelectedOnly, mSubFormat, mT0, mT1, and Tags::ShowEditDialog().
Referenced by ExportCommand::Apply(), BatchCommands::ApplySpecialCommand(), AudacityProject::OnExport(), AudacityProject::OnExportSelection(), AudacityProject::Save(), AudacityProject::SaveCompressedWaveTracks(), and BatchCommands::WriteMp3File().
void Exporter::RegisterPlugin (ExportPlugin * plugin)
References mPlugins.
Referenced by Exporter().
Member Data Documentation
wxFileName Exporter::mActualName [private]
Referenced by CheckFilename(), ExportTracks(), and Process().
int Exporter::mChannels [private]
Referenced by CheckMix(), ExportTracks(), and Process().
FileDialog* Exporter::mDialog [private]
Referenced by DisplayOptions(), and GetFilename().
wxFileName Exporter::mFilename [private]
Referenced by CheckFilename(), ExportTracks(), GetFilename(), and Process().
int Exporter::mFilterIndex [private]
Referenced by GetFilename().
int Exporter::mFormat [private]
Referenced by CheckFilename(), CheckMix(), ExportTracks(), GetFilename(), and Process().
MixerSpec* Exporter::mMixerSpec [private]
Referenced by CheckMix(), Exporter(), ExportTracks(), Process(), and ~Exporter().
int Exporter::mNumLeft [private]
Referenced by CheckMix(), and ExamineTracks().
int Exporter::mNumMono [private]
Referenced by CheckMix(), and ExamineTracks().
int Exporter::mNumRight [private]
Referenced by CheckMix(), and ExamineTracks().
int Exporter::mNumSelected [private]
Referenced by ExamineTracks().
ExportPluginArray Exporter::mPlugins [private]
Referenced by CheckFilename(), CheckMix(), DisplayOptions(), ExportTracks(), FindFormatIndex(), GetFilename(), GetPlugins(), Process(), RegisterPlugin(), and ~Exporter().
AudacityProject* Exporter::mProject [private]
Referenced by CheckFilename(), CheckMix(), DisplayOptions(), ExamineTracks(), ExportTracks(), GetFilename(), and Process().
bool Exporter::mSelectedOnly [private]
Referenced by CheckMix(), ExamineTracks(), ExportTracks(), and Process().
int Exporter::mSubFormat [private]
Referenced by CheckFilename(), CheckMix(), ExportTracks(), GetFilename(), and Process().
double Exporter::mT0 [private]
Referenced by ExamineTracks(), ExportTracks(), and Process().
double Exporter::mT1 [private]
Referenced by ExamineTracks(), ExportTracks(), and Process().
The documentation for this class was generated from the following files:
Export.h
Export.cpp