Audacity: FLACImportFileHandle Class Reference
FLACImportFileHandle Class Reference
An ImportFileHandle for FLAC data.
Public Member Functions
FLACImportFileHandle (const wxString &name)
~FLACImportFileHandle ()
bool Init ()
wxString GetFileDescription ()
int GetFileUncompressedBytes ()
int Import (TrackFactory *trackFactory, Track ***outTracks, int *outNumTracks, Tags *tags)
wxInt32 GetStreamCount ()
wxArrayString * GetStreamInfo ()
void SetStreamUsage (wxInt32 StreamID, bool Use)
Private Attributes
sampleFormat mFormat
MyFLACFile * mFile
wxFFile mHandle
unsigned long mSampleRate
unsigned long mNumChannels
unsigned long mBitsPerSample
FLAC__uint64 mNumSamples
FLAC__uint64 mSamplesDone
bool mStreamInfoDone
int mUpdateResult
WaveTrack ** mChannels
ODDecodeFlacTask * mDecoderTask
Friends
class MyFLACFile
Detailed Description
An ImportFileHandle for FLAC data.
Constructor & Destructor Documentation
FLACImportFileHandle::FLACImportFileHandle (const wxString & name)
References floatSample, gPrefs, mFile, mFormat, and MyFLACFile.
FLACImportFileHandle::~FLACImportFileHandle ()
References mFile.
Member Function Documentation
wxString FLACImportFileHandle::GetFileDescription () [virtual]
Implements ImportFileHandle.
References DESC.
int FLACImportFileHandle::GetFileUncompressedBytes () [virtual]
Implements ImportFileHandle.
wxInt32 FLACImportFileHandle::GetStreamCount () [inline, virtual]
Implements ImportFileHandle.
wxArrayString* FLACImportFileHandle::GetStreamInfo () [inline, virtual]
Implements ImportFileHandle.
int FLACImportFileHandle::Import (TrackFactory * trackFactory, Track *** outTracks, int * outNumTracks, Tags * tags) [virtual]
Implements ImportFileHandle.
References ODManager::AddNewTask(), ODTask::AddWaveTrack(), Tags::Clear(), ImportFileHandle::CreateProgress(), ODTask::eODFLAC, eProgressCancelled, eProgressFailed, eProgressSuccess, WaveTrack::Flush(), WaveTrack::GetMaxBlockSize(), Tags::HasTag(), ODManager::Instance(), Track::LeftChannel, mChannels, MyFLACFile::mComments, mDecoderTask, mFile, ImportFileHandle::mFilename, mFormat, mNumChannels, mNumSamples, Track::MonoChannel, ImportFileHandle::mProgress, mSampleRate, mStreamInfoDone, mUpdateResult, name, TrackFactory::NewWaveTrack(), Track::RightChannel, Track::SetChannel(), Track::SetLinked(), Tags::SetTag(), TAG_YEAR, and ProgressDialog::Update().
bool FLACImportFileHandle::Init ()
References ODDecodeFlacTask::CreateFileDecoder(), MyFLACFile::get_was_error(), ODFlacDecoder::mBitsPerSample, mBitsPerSample, mDecoderTask, mFile, ImportFileHandle::mFilename, ODFlacDecoder::mFormat, mFormat, mHandle, ODFlacDecoder::mNumChannels, mNumChannels, ODFlacDecoder::mNumSamples, mNumSamples, ODFlacDecoder::mSampleRate, mSampleRate, mStreamInfoDone, OSINPUT, and ODFlacDecoder::ReadHeader().
Referenced by FLACImportPlugin::Open().
void FLACImportFileHandle::SetStreamUsage (wxInt32 StreamID, bool Use) [inline, virtual]
Implements ImportFileHandle.
Friends And Related Function Documentation
friend class MyFLACFile [friend]
Referenced by FLACImportFileHandle().
Member Data Documentation
unsigned long FLACImportFileHandle::mBitsPerSample [private]
Referenced by Init(), and MyFLACFile::metadata_callback().
WaveTrack** FLACImportFileHandle::mChannels [private]
Referenced by Import(), and MyFLACFile::write_callback().
ODDecodeFlacTask* FLACImportFileHandle::mDecoderTask [private]
Referenced by Import(), and Init().
MyFLACFile* FLACImportFileHandle::mFile [private]
Referenced by FLACImportFileHandle(), Import(), Init(), and ~FLACImportFileHandle().
sampleFormat FLACImportFileHandle::mFormat [private]
Referenced by FLACImportFileHandle(), Import(), Init(), and MyFLACFile::metadata_callback().
wxFFile FLACImportFileHandle::mHandle [private]
Referenced by Init().
unsigned long FLACImportFileHandle::mNumChannels [private]
Referenced by Import(), Init(), MyFLACFile::metadata_callback(), and MyFLACFile::write_callback().
FLAC__uint64 FLACImportFileHandle::mNumSamples [private]
Referenced by Import(), Init(), MyFLACFile::metadata_callback(), and MyFLACFile::write_callback().
unsigned long FLACImportFileHandle::mSampleRate [private]
Referenced by Import(), Init(), and MyFLACFile::metadata_callback().
FLAC__uint64 FLACImportFileHandle::mSamplesDone [private]
Referenced by MyFLACFile::write_callback().
bool FLACImportFileHandle::mStreamInfoDone [private]
Referenced by Import(), Init(), and MyFLACFile::metadata_callback().
int FLACImportFileHandle::mUpdateResult [private]
Referenced by Import(), and MyFLACFile::write_callback().
The documentation for this class was generated from the following file:
ImportFLAC.cpp