Audacity: NoiseDialog Class Reference
NoiseDialog Class Reference
#include <Noise.h>
Public Member Functions
NoiseDialog (EffectNoise *effect, wxWindow *parent, const wxString &title)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
double nRate
double nTime
wxArrayString * nTypeList
double nDuration
int nType
double nAmplitude
bool nIsSelection
Private Member Functions
void OnTimeCtrlUpdate (wxCommandEvent &event)
Private Attributes
EffectNoise * mEffect
TimeTextCtrl * mNoiseDurationT
Constructor & Destructor Documentation
NoiseDialog::NoiseDialog (EffectNoise * effect, wxWindow * parent, const wxString & title)
Member Function Documentation
void NoiseDialog::OnTimeCtrlUpdate (wxCommandEvent & event) [private]
void NoiseDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddPrompt(), ShuttleGuiBase::AddWindow(), TimeTextCtrl::EnableMenu(), ShuttleGuiBase::EndMultiColumn(), TimeTextCtrl::GetBuiltinFormat(), mEffect, mNoiseDurationT, Effect::mProjectRate, nAmplitude, nDuration, nIsSelection, nType, nTypeList, TimeTextCtrl::SetFormatString(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::TieChoice(), and ShuttleGuiBase::TieTextBox().
bool NoiseDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References AMP_MAX, AMP_MIN, TimeTextCtrl::GetTimeValue(), mNoiseDurationT, nAmplitude, nDuration, and TrapDouble().
bool NoiseDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References mNoiseDurationT, nDuration, and TimeTextCtrl::SetTimeValue().
Referenced by EffectNoise::PromptUser().
Member Data Documentation
EffectNoise* NoiseDialog::mEffect [private]
Referenced by PopulateOrExchange().
TimeTextCtrl* NoiseDialog::mNoiseDurationT [private]
Referenced by PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
double NoiseDialog::nAmplitude
Referenced by PopulateOrExchange(), EffectNoise::PromptUser(), and TransferDataFromWindow().
double NoiseDialog::nDuration
Referenced by PopulateOrExchange(), EffectNoise::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
bool NoiseDialog::nIsSelection
Referenced by PopulateOrExchange(), and EffectNoise::PromptUser().
double NoiseDialog::nRate
double NoiseDialog::nTime
int NoiseDialog::nType
Referenced by PopulateOrExchange(), and EffectNoise::PromptUser().
wxArrayString* NoiseDialog::nTypeList
Referenced by PopulateOrExchange(), and EffectNoise::PromptUser().
The documentation for this class was generated from the following files:
Noise.h
Noise.cpp