Audacity: Tags Class Reference
Tags Class Reference
ID3 Tags (for MP3).
#include <Tags.h>
Public Member Functions
Tags ()
virtual ~Tags ()
Tags & operator= (const Tags &src)
bool ShowEditDialog (wxWindow *parent, wxString title, bool force=false)
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
void SetID3V2 (bool id3v2)
bool GetID3V2 ()
void AllowEditTitle (bool editTitle)
void AllowEditTrackNumber (bool editTrackNumber)
void LoadDefaultGenres ()
void LoadGenres ()
int GetNumUserGenres ()
wxString GetUserGenre (int value)
wxString GetGenre (int value)
int GetGenre (const wxString &name)
bool HasTag (const wxString &name)
wxString GetTag (const wxString &name)
bool GetFirst (wxString &name, wxString &value)
bool GetNext (wxString &name, wxString &value)
void SetTag (const wxString &name, const wxString &value)
void SetTag (const wxString &name, const int &value)
bool IsEmpty ()
void Clear ()
Private Member Functions
void LoadDefaults ()
Private Attributes
bool mID3V2
TagMap::iterator mIter
TagMap mXref
TagMap mMap
wxArrayString mGenres
bool mEditTitle
bool mEditTrackNumber
Detailed Description
ID3 Tags (for MP3).
This class started as an ID3 tag
This class holds a few informational tags, such as Title, Author, etc. that can be associated with a project or other audio file. It is modeled after the ID3 format for MP3 files, and it can both import ID3 tags from MP3 files, and export them as well.
It can present the user with a dialog for editing this information.
It only keeps track of the fields that are standard in ID3v1 (title, author, artist, track num, year, genre, and comments), but it can export both ID3v1 or the newer ID3v2 format. The primary reason you would want to export ID3v2 tags instead of ID3v1, since we're not supporting any v2 fields, is that ID3v2 tags are inserted at the BEGINNING of an mp3 file, which is far more useful for streaming.
Use of this functionality requires that libid3tag be compiled in with Audacity.
Constructor & Destructor Documentation
Tags::Tags ()
References LoadDefaults(), LoadGenres(), mEditTitle, mEditTrackNumber, and mID3V2.
Tags::~Tags () [virtual]
Member Function Documentation
void Tags::AllowEditTitle (bool editTitle)
References mEditTitle.
void Tags::AllowEditTrackNumber (bool editTrackNumber)
References mEditTrackNumber.
void Tags::Clear ()
References mID3V2, mMap, and mXref.
Referenced by OggImportFileHandle::Import(), FLACImportFileHandle::Import(), MP3ImportFileHandle::ImportID3(), TagsEditor::OnClear(), TagsEditor::OnLoad(), TagsEditor::TransferDataFromWindow(), and FFmpegImportFileHandle::WriteMetadata().
bool Tags::GetFirst (wxString & name, wxString & value)
References mIter, and mMap.
Referenced by ExportPCM::AddID3Chunk(), ExportMP3::AddTags(), ExportMP2::AddTags(), ExportOGG::FillComment(), ExportFLAC::GetMetadata(), TagsEditor::OnSaveDefaults(), TagsEditor::TransferDataToWindow(), and WriteXML().
int Tags::GetGenre (const wxString & name)
References DefaultGenres.
wxString Tags::GetGenre (int value)
References DefaultGenres.
Referenced by ExportMP3::AddTags(), ExportMP2::AddTags(), PCMImportFileHandle::Import(), and MP3ImportFileHandle::ImportID3().
bool Tags::GetID3V2 ()
References mID3V2.
Referenced by ExportMP3::AddTags(), and ExportMP2::AddTags().
bool Tags::GetNext (wxString & name, wxString & value)
References mIter, and mMap.
Referenced by ExportPCM::AddID3Chunk(), ExportMP3::AddTags(), ExportMP2::AddTags(), ExportOGG::FillComment(), ExportFLAC::GetMetadata(), TagsEditor::OnSaveDefaults(), TagsEditor::TransferDataToWindow(), and WriteXML().
int Tags::GetNumUserGenres ()
References mGenres.
Referenced by GetUserGenre(), TagsEditor::OnEdit(), TagsEditor::OnReset(), and TagsEditor::PopulateGenres().
wxString Tags::GetTag (const wxString & name)
References mMap, and mXref.
Referenced by ExportPCM::AddStrings(), ExportFFmpeg::AddTags(), PCMImportFileHandle::Import(), MP3ImportFileHandle::ImportID3(), TagsEditor::OnLoad(), TagsEditor::OnSave(), TagsEditor::OnSaveDefaults(), and TagsEditor::TransferDataToWindow().
wxString Tags::GetUserGenre (int value)
References GetNumUserGenres(), and mGenres.
Referenced by TagsEditor::OnEdit(), TagsEditor::OnReset(), and TagsEditor::PopulateGenres().
XMLTagHandler * Tags::HandleXMLChild (const wxChar * tag) [virtual]
Implements XMLTagHandler.
bool Tags::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements XMLTagHandler.
References XMLValueChecker::IsGoodInt(), XMLValueChecker::IsGoodString(), mID3V2, and SetTag().
bool Tags::HasTag (const wxString & name)
References mXref.
Referenced by ExportPCM::AddStrings(), PCMImportFileHandle::Import(), OggImportFileHandle::Import(), FLACImportFileHandle::Import(), MP3ImportFileHandle::ImportID3(), and IsEmpty().
bool Tags::IsEmpty ()
References HasTag(), TAG_ALBUM, TAG_ARTIST, and TAG_TITLE.
void Tags::LoadDefaultGenres ()
References DefaultGenres, and mGenres.
Referenced by LoadGenres(), and TagsEditor::OnReset().
void Tags::LoadDefaults () [private]
References gPrefs, mID3V2, name, and SetTag().
Referenced by Tags().
void Tags::LoadGenres ()
References FileNames::DataDir(), LoadDefaultGenres(), and mGenres.
Referenced by TagsEditor::OnEdit(), TagsEditor::OnReset(), and Tags().
Tags & Tags::operator= (const Tags & src)
References mEditTitle, mEditTrackNumber, mGenres, mID3V2, mMap, and mXref.
void Tags::SetID3V2 (bool id3v2)
References mID3V2.
Referenced by PCMImportFileHandle::Import(), and MP3ImportFileHandle::ImportID3().
void Tags::SetTag (const wxString & name, const int & value)
References SetTag().
void Tags::SetTag (const wxString & name, const wxString & value)
References mMap, and mXref.
Referenced by ExportMultiple::ExportMultipleByLabel(), ExportMultiple::ExportMultipleByTrack(), HandleXMLTag(), PCMImportFileHandle::Import(), OggImportFileHandle::Import(), FLACImportFileHandle::Import(), MP3ImportFileHandle::ImportID3(), LoadDefaults(), TagsEditor::OnLoad(), TagsEditor::OnSave(), TagsEditor::OnSaveDefaults(), SetTag(), TagsEditor::TransferDataFromWindow(), TagsEditor::TransferDataToWindow(), and FFmpegImportFileHandle::WriteMetadata().
bool Tags::ShowEditDialog (wxWindow * parent, wxString title, bool force = false)
References mEditTitle, and mEditTrackNumber.
Referenced by ExportMultiple::ExportMultipleByLabel(), ExportMultiple::ExportMultipleByTrack(), AudacityProject::OnEditMetadata(), and Exporter::Process().
void Tags::WriteXML (XMLWriter & xmlFile) [virtual]
References XMLWriter::EndTag(), GetFirst(), GetNext(), mID3V2, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
Referenced by TagsEditor::OnSave(), and AudacityProject::WriteXML().
Member Data Documentation
bool Tags::mEditTitle [private]
Referenced by AllowEditTitle(), operator=(), ShowEditDialog(), and Tags().
bool Tags::mEditTrackNumber [private]
Referenced by AllowEditTrackNumber(), operator=(), ShowEditDialog(), and Tags().
wxArrayString Tags::mGenres [private]
Referenced by GetNumUserGenres(), GetUserGenre(), LoadDefaultGenres(), LoadGenres(), and operator=().
bool Tags::mID3V2 [private]
Referenced by Clear(), GetID3V2(), HandleXMLTag(), LoadDefaults(), operator=(), SetID3V2(), Tags(), and WriteXML().
TagMap::iterator Tags::mIter [private]
Referenced by GetFirst(), and GetNext().
TagMap Tags::mMap [private]
Referenced by Clear(), GetFirst(), GetNext(), GetTag(), operator=(), and SetTag().
TagMap Tags::mXref [private]
Referenced by Clear(), GetTag(), HasTag(), operator=(), and SetTag().
The documentation for this class was generated from the following files:
Tags.h
Tags.cpp