Audacity: BatchCommandDialog Class Reference
BatchCommandDialog Class Reference
Provides a list of configurable commands for use with BatchCommands.
#include <BatchCommandDialog.h>
Public Member Functions
BatchCommandDialog (wxWindow *parent, wxWindowID id)
void SetCommandAndParams (const wxString &Command, const wxString &Params)
Public Attributes
wxString mSelectedCommand
wxString mSelectedParameters
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
void OnEditParams (wxCommandEvent &event)
void OnChoice (wxCommandEvent &event)
void OnOk (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void OnItemSelected (wxListEvent &event)
void ValidateChoices ()
void PopulateCommandList ()
int GetSelectedItem ()
Private Attributes
wxButton * mEditParams
wxListCtrl * mChoices
wxTextCtrl * mCommand
wxTextCtrl * mParameters
Detailed Description
Provides a list of configurable commands for use with BatchCommands.
Provides a list of commands, mostly effects, which can be chained together in a simple linear sequence. Can configure parameters on each selected command.
Constructor & Destructor Documentation
BatchCommandDialog::BatchCommandDialog (wxWindow * parent, wxWindowID id)
Member Function Documentation
int BatchCommandDialog::GetSelectedItem () [private]
References mChoices, and mSelectedCommand.
void BatchCommandDialog::OnCancel (wxCommandEvent & event) [private]
void BatchCommandDialog::OnChoice (wxCommandEvent & event) [private]
void BatchCommandDialog::OnEditParams (wxCommandEvent & event) [private]
References EffectManager::Get(), BatchCommands::GetCurrentParamsFor(), EffectManager::GetEffectByIdentifier(), mCommand, mParameters, BatchCommands::PromptForParamsFor(), and BatchCommands::SetCurrentParametersFor().
void BatchCommandDialog::OnItemSelected (wxListEvent & event) [private]
References EffectManager::Get(), BatchCommands::GetCurrentParamsFor(), EffectManager::GetEffectByIdentifier(), mChoices, mCommand, mEditParams, and mParameters.
void BatchCommandDialog::OnOk (wxCommandEvent & event) [private]
References mCommand, mParameters, mSelectedCommand, and mSelectedParameters.
void BatchCommandDialog::Populate () [private]
References eIsCreating, and PopulateOrExchange().
void BatchCommandDialog::PopulateCommandList () [private]
References BatchCommands::GetAllCommands(), and mChoices.
Referenced by PopulateOrExchange().
void BatchCommandDialog::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddListControl(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTextBox(), CommandsListID, EditParamsButtonID, ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), ShuttleGui::Id(), mChoices, mCommand, mEditParams, mParameters, PopulateCommandList(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::StartVerticalLay().
Referenced by Populate().
void BatchCommandDialog::SetCommandAndParams (const wxString & Command, const wxString & Params)
References mChoices, mCommand, and mParameters.
Referenced by EditChainsDialog::OnCommandActivated().
void BatchCommandDialog::ValidateChoices () [private]
Member Data Documentation
wxListCtrl* BatchCommandDialog::mChoices [private]
Referenced by GetSelectedItem(), OnItemSelected(), PopulateCommandList(), PopulateOrExchange(), and SetCommandAndParams().
wxTextCtrl* BatchCommandDialog::mCommand [private]
Referenced by OnEditParams(), OnItemSelected(), OnOk(), PopulateOrExchange(), and SetCommandAndParams().
wxButton* BatchCommandDialog::mEditParams [private]
Referenced by OnItemSelected(), and PopulateOrExchange().
wxTextCtrl* BatchCommandDialog::mParameters [private]
Referenced by OnEditParams(), OnItemSelected(), OnOk(), PopulateOrExchange(), and SetCommandAndParams().
wxString BatchCommandDialog::mSelectedCommand
Referenced by GetSelectedItem(), EditChainsDialog::OnCommandActivated(), EditChainsDialog::OnInsert(), and OnOk().
wxString BatchCommandDialog::mSelectedParameters
Referenced by EditChainsDialog::OnCommandActivated(), EditChainsDialog::OnInsert(), and OnOk().
The documentation for this class was generated from the following files:
BatchCommandDialog.h
BatchCommandDialog.cpp