Audacity: ChangeLengthDialog Class Reference
ChangeLengthDialog Class Reference
Dialog used with EffectChangeLength.
#include <ChangeLength.h>
Public Member Functions
ChangeLengthDialog (wxWindow *parent, wxWindowID id, const wxString &title)
virtual bool TransferDataToWindow ()
virtual bool TransferDataFromWindow ()
Public Attributes
double mFromLength
double mToLength
Private Member Functions
void OnOk (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void OnRecalculate (wxCommandEvent &event)
void OnText_ToLength (wxCommandEvent &event)
Private Attributes
wxTextCtrl * m_pTextCtrl_ToRange
wxTextCtrl * m_pTextCtrl_PercentChange
wxTextCtrl * m_pTextCtrl_FromLength
wxTextCtrl * m_pTextCtrl_ToLength
double mPercentChange
Detailed Description
Dialog used with EffectChangeLength.
Constructor & Destructor Documentation
ChangeLengthDialog::ChangeLengthDialog (wxWindow * parent, wxWindowID id, const wxString & title)
References ID_CHANGE_LENGTH_FROM_TEXT, ID_PERCENT_CHANGE_TEXT, and ID_TO_RANGE_TEXT.
Member Function Documentation
void ChangeLengthDialog::OnCancel (wxCommandEvent & event) [private]
void ChangeLengthDialog::OnOk (wxCommandEvent & event) [private]
References TransferDataFromWindow().
void ChangeLengthDialog::OnRecalculate (wxCommandEvent & event) [private]
References TransferDataFromWindow(), and TransferDataToWindow().
void ChangeLengthDialog::OnText_ToLength (wxCommandEvent & event) [private]
References m_pTextCtrl_ToLength, mFromLength, mPercentChange, and mToLength.
bool ChangeLengthDialog::TransferDataFromWindow () [virtual]
References m_pTextCtrl_ToLength, and mToLength.
Referenced by OnOk(), and OnRecalculate().
bool ChangeLengthDialog::TransferDataToWindow () [virtual]
References m_pTextCtrl_FromLength, m_pTextCtrl_PercentChange, m_pTextCtrl_ToLength, m_pTextCtrl_ToRange, mFromLength, and mToLength.
Referenced by OnRecalculate(), and EffectChangeLength::PromptUser().
Member Data Documentation
wxTextCtrl* ChangeLengthDialog::m_pTextCtrl_FromLength [private]
Referenced by TransferDataToWindow().
wxTextCtrl* ChangeLengthDialog::m_pTextCtrl_PercentChange [private]
Referenced by TransferDataToWindow().
wxTextCtrl* ChangeLengthDialog::m_pTextCtrl_ToLength [private]
Referenced by OnText_ToLength(), TransferDataFromWindow(), and TransferDataToWindow().
wxTextCtrl* ChangeLengthDialog::m_pTextCtrl_ToRange [private]
Referenced by TransferDataToWindow().
double ChangeLengthDialog::mFromLength
Referenced by OnText_ToLength(), EffectChangeLength::PromptUser(), and TransferDataToWindow().
double ChangeLengthDialog::mPercentChange [private]
Referenced by OnText_ToLength().
double ChangeLengthDialog::mToLength
Referenced by OnText_ToLength(), EffectChangeLength::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
ChangeLength.h
ChangeLength.cpp