Audacity: AppCommandEvent Class Reference
AppCommandEvent Class Reference
An event 'envelope' for sending Command objects through the wxwidgets event loop.
#include <AppCommandEvent.h>
Public Member Functions
AppCommandEvent (wxEventType commandType=wxEVT_APP_COMMAND_RECEIVED, int id=0)
AppCommandEvent (const AppCommandEvent &event)
~AppCommandEvent ()
virtual wxEvent * Clone () const
void SetCommand (Command *cmd)
Store a pointer to a command object.
Command * GetCommand ()
Private Attributes
Command * mCommand
Detailed Description
An event 'envelope' for sending Command objects through the wxwidgets event loop.
This allows commands to be communicated from the script thread to the main thread.
Constructor & Destructor Documentation
AppCommandEvent::AppCommandEvent (wxEventType commandType = wxEVT_APP_COMMAND_RECEIVED, int id = 0)
Referenced by Clone().
AppCommandEvent::AppCommandEvent (const AppCommandEvent & event)
References mCommand.
AppCommandEvent::~AppCommandEvent ()
Member Function Documentation
wxEvent * AppCommandEvent::Clone () const [virtual]
References AppCommandEvent().
Command * AppCommandEvent::GetCommand ()
References mCommand.
void AppCommandEvent::SetCommand (Command * cmd)
Store a pointer to a command object.
References mCommand.
Referenced by ScriptCommandRelay::PostCommand().
Member Data Documentation
Command* AppCommandEvent::mCommand [private]
Referenced by AppCommandEvent(), GetCommand(), and SetCommand().
The documentation for this class was generated from the following files:
AppCommandEvent.h
AppCommandEvent.cpp