Audacity: TimeTrack Class Reference
TimeTrack Class Reference
A kind of Track used to 'warp time'.
#include <TimeTrack.h>
Public Member Functions
TimeTrack (DirManager *projDirManager)
TimeTrack (TimeTrack &orig)
virtual ~TimeTrack ()
virtual int GetKind () const
virtual double GetOffset ()
virtual void SetOffset (double)
virtual double GetStartTime ()
virtual double GetEndTime ()
void Draw (wxDC &dc, const wxRect &r, double h, double pps)
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
bool Lock ()
bool Unlock ()
Envelope * GetEnvelope ()
long GetRangeLower ()
long GetRangeUpper ()
void SetRangeLower (long lower)
void SetRangeUpper (long upper)
double warp (double t)
void testMe ()
Private Member Functions
void Init (const TimeTrack &orig)
virtual Track * Duplicate ()
Private Attributes
Envelope * mEnvelope
Ruler * mRuler
long mRangeLower
long mRangeUpper
wxBrush blankBrush
wxPen blankPen
Friends
class TrackFactory
Detailed Description
A kind of Track used to 'warp time'.
Constructor & Destructor Documentation
TimeTrack::TimeTrack (DirManager * projDirManager)
References blankBrush, blankPen, Envelope::Flatten(), Track::GetDefaultName(), mEnvelope, Track::mHeight, Envelope::Mirror(), mRangeLower, mRangeUpper, mRuler, Track::SetDefaultName(), Ruler::SetFormat(), Envelope::SetInterpolateDB(), Ruler::SetLabelEdges(), Track::SetName(), Envelope::SetTrackLen(), and Ruler::TimeFormat.
Referenced by Duplicate().
TimeTrack::TimeTrack (TimeTrack & orig)
References blankBrush, blankPen, Envelope::Flatten(), Init(), mEnvelope, Track::mHeight, Envelope::Mirror(), mRangeLower, mRangeUpper, mRuler, Envelope::Paste(), Ruler::SetFormat(), Envelope::SetInterpolateDB(), Ruler::SetLabelEdges(), Envelope::SetOffset(), Envelope::SetTrackLen(), and Ruler::TimeFormat.
TimeTrack::~TimeTrack () [virtual]
References mEnvelope, and mRuler.
Member Function Documentation
void TimeTrack::Draw (wxDC & dc, const wxRect & r, double h, double pps)
References blankBrush, blankPen, Ruler::Draw(), AColor::envelopePen, GetEnvelope(), Track::GetHeight(), GetRangeLower(), GetRangeUpper(), Envelope::GetValues(), AColor::Line(), max, min(), mRuler, Ruler::SetBounds(), Ruler::SetFlip(), and Ruler::SetRange().
Referenced by TrackArtist::DrawTimeTrack().
Track * TimeTrack::Duplicate () [private, virtual]
Implements Track.
References TimeTrack().
virtual double TimeTrack::GetEndTime () [inline, virtual]
Reimplemented from Track.
Envelope* TimeTrack::GetEnvelope () [inline]
References mEnvelope.
Referenced by audacityAudioCallback(), Draw(), TrackArtist::DrawTimeTrack(), TrackPanel::ForwardEventToTimeTrackEnvelope(), Mixer::MixVariableRates(), AudioIO::StartStream(), testMe(), and warp().
virtual int TimeTrack::GetKind () const [inline, virtual]
Reimplemented from Track.
References Track::Time.
virtual double TimeTrack::GetOffset () [inline, virtual]
Reimplemented from Track.
long TimeTrack::GetRangeLower () [inline]
References mRangeLower.
Referenced by audacityAudioCallback(), Draw(), Mixer::Mixer(), Mixer::MixVariableRates(), TrackPanel::OnSetTimeTrackRange(), AudioIO::StartStream(), and warp().
long TimeTrack::GetRangeUpper () [inline]
References mRangeUpper.
Referenced by audacityAudioCallback(), Draw(), Mixer::Mixer(), Mixer::MixVariableRates(), TrackPanel::OnSetTimeTrackRange(), AudioIO::StartStream(), and warp().
virtual double TimeTrack::GetStartTime () [inline, virtual]
Reimplemented from Track.
XMLTagHandler * TimeTrack::HandleXMLChild (const wxChar * tag) [virtual]
Implements Track.
References mEnvelope.
bool TimeTrack::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements Track.
References Internat::CompatibleToDouble(), XMLValueChecker::IsGoodInt(), XMLValueChecker::IsGoodString(), XMLValueChecker::IsValidChannel(), Track::mChannel, mEnvelope, Track::mHeight, Track::mMinimized, Track::mName, Track::mOffset, and Envelope::SetOffset().
void TimeTrack::Init (const TimeTrack & orig) [private]
Reimplemented from Track.
References Track::GetDefaultName(), Track::GetName(), Track::SetDefaultName(), and Track::SetName().
Referenced by TimeTrack().
bool TimeTrack::Lock ()
virtual void TimeTrack::SetOffset (double) [inline, virtual]
Reimplemented from Track.
void TimeTrack::SetRangeLower (long lower) [inline]
References mRangeLower.
Referenced by TranscriptionToolBar::OnPlaySpeed(), and TrackPanel::OnSetTimeTrackRange().
void TimeTrack::SetRangeUpper (long upper) [inline]
References mRangeUpper.
Referenced by TranscriptionToolBar::OnPlaySpeed(), and TrackPanel::OnSetTimeTrackRange().
void TimeTrack::testMe ()
References Envelope::Flatten(), GetEnvelope(), Envelope::Insert(), Envelope::SetDefaultValue(), and warp().
bool TimeTrack::Unlock ()
double TimeTrack::warp (double t)
References GetEnvelope(), GetRangeLower(), GetRangeUpper(), and Envelope::Integral().
Referenced by TrackPanel::DoDrawCursor(), and testMe().
void TimeTrack::WriteXML (XMLWriter & xmlFile) [virtual]
Implements Track.
References XMLWriter::EndTag(), Track::GetActualHeight(), Track::GetMinimized(), Track::mChannel, mEnvelope, Track::mName, Track::mOffset, XMLWriter::StartTag(), XMLWriter::WriteAttr(), and Envelope::WriteXML().
Friends And Related Function Documentation
friend class TrackFactory [friend]
Member Data Documentation
wxBrush TimeTrack::blankBrush [private]
Referenced by Draw(), and TimeTrack().
wxPen TimeTrack::blankPen [private]
Referenced by Draw(), and TimeTrack().
Envelope* TimeTrack::mEnvelope [private]
Referenced by GetEnvelope(), HandleXMLChild(), HandleXMLTag(), TimeTrack(), WriteXML(), and ~TimeTrack().
long TimeTrack::mRangeLower [private]
Referenced by GetRangeLower(), SetRangeLower(), and TimeTrack().
long TimeTrack::mRangeUpper [private]
Referenced by GetRangeUpper(), SetRangeUpper(), and TimeTrack().
Ruler* TimeTrack::mRuler [private]
Referenced by Draw(), TimeTrack(), and ~TimeTrack().
The documentation for this class was generated from the following files:
TimeTrack.h
TimeTrack.cpp