Audacity: FileIO Class Reference
FileIO Class Reference
#include <FileIO.h>
Public Types
enum FileIOMode { Input, Output }
typedef enum FileIO::FileIOMode FileIOMode
Public Member Functions
FileIO (const wxString name, FileIOMode mode)
~FileIO ()
bool IsOpened ()
void Close ()
wxInputStream & Read (void *buffer, size_t size)
wxOutputStream & Write (const void *buffer, size_t size)
void SetCatalogInfo ()
void SetCatalogInfo (wxUint32 type)
Private Attributes
wxString mName
FileIOMode mMode
wxURI mUri
wxFTP * mFtp
wxInputStream * mInputStream
wxOutputStream * mOutputStream
bool mOpen
Member Typedef Documentation
typedef enum FileIO::FileIOMode FileIO::FileIOMode
Member Enumeration Documentation
enum FileIO::FileIOMode
Enumerator:
Input
Output
Constructor & Destructor Documentation
FileIO::FileIO (const wxString name, FileIOMode mode)
References Input, mFtp, mInputStream, mMode, mName, mOpen, mOutputStream, and mUri.
FileIO::~FileIO ()
References Close().
Member Function Documentation
void FileIO::Close ()
References mFtp, mInputStream, mOpen, mOutputStream, and SetCatalogInfo().
Referenced by ExportOGG::Export(), ExportMP2::Export(), and ~FileIO().
bool FileIO::IsOpened ()
References mOpen.
Referenced by ExportOGG::Export(), and ExportMP2::Export().
wxInputStream & FileIO::Read (void * buffer, size_t size)
References mInputStream.
void FileIO::SetCatalogInfo (wxUint32 type)
References mFtp, mName, and mOpen.
void FileIO::SetCatalogInfo ()
References mFtp, mName, and mOpen.
Referenced by Close().
wxOutputStream & FileIO::Write (const void * buffer, size_t size)
References mOutputStream.
Referenced by ExportOGG::Export(), and ExportMP2::Export().
Member Data Documentation
wxFTP* FileIO::mFtp [private]
Referenced by Close(), FileIO(), and SetCatalogInfo().
wxInputStream* FileIO::mInputStream [private]
Referenced by Close(), FileIO(), and Read().
FileIOMode FileIO::mMode [private]
Referenced by FileIO().
wxString FileIO::mName [private]
Referenced by FileIO(), and SetCatalogInfo().
bool FileIO::mOpen [private]
Referenced by Close(), FileIO(), IsOpened(), and SetCatalogInfo().
wxOutputStream* FileIO::mOutputStream [private]
Referenced by Close(), FileIO(), and Write().
wxURI FileIO::mUri [private]
Referenced by FileIO().
The documentation for this class was generated from the following files:
FileIO.h
FileIO.cpp