Audacity: EffectDialog Class Reference
EffectDialog Class Reference
New (Jun-2006) base class for effects dialogs. Likely to get greater use in future.
#include <Effect.h>
Public Member Functions
EffectDialog (wxWindow *parent, const wxString &title, int type=PROCESS_EFFECT, int flags=wxDEFAULT_DIALOG_STYLE)
void Init ()
virtual void PopulateOrExchange (ShuttleGui &S)
virtual bool TransferDataToWindow ()
virtual bool TransferDataFromWindow ()
virtual bool Validate ()
virtual void OnPreview (wxCommandEvent &event)
Private Attributes
int mType
Detailed Description
New (Jun-2006) base class for effects dialogs. Likely to get greater use in future.
Constructor & Destructor Documentation
EffectDialog::EffectDialog (wxWindow * parent, const wxString & title, int type = PROCESS_EFFECT, int flags = wxDEFAULT_DIALOG_STYLE)
References mType.
Member Function Documentation
void EffectDialog::Init ()
References ShuttleGui::AddStandardButtons(), eCancelButton, eIsCreating, ShuttleGuiBase::EndVerticalLay(), eOkButton, ePreviewButton, INSERT_EFFECT, mType, PopulateOrExchange(), PROCESS_EFFECT, ShuttleGuiBase::SetBorder(), and ShuttleGuiBase::StartVerticalLay().
Referenced by FindClippingDialog::FindClippingDialog(), EffectToneGen::PromptUser(), EffectNoise::PromptUser(), and EffectDtmf::PromptUser().
void EffectDialog::OnPreview (wxCommandEvent & event) [virtual]
Reimplemented in AmplifyDialog, BassBoostDialog, ChangePitchDialog, ChangeSpeedDialog, ChangeTempoDialog, ClickRemovalDialog, CompressorDialog, EchoDialog, LevellerDialog, NoiseRemovalDialog, NormalizeDialog, PhaserDialog, RepeatDialog, TruncSilenceDialog, and WahwahDialog.
void EffectDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented in AmplifyDialog, BassBoostDialog, ChangePitchDialog, ChangeSpeedDialog, ChangeTempoDialog, ClickRemovalDialog, CompressorDialog, DtmfDialog, EchoDialog, FindClippingDialog, LevellerDialog, NoiseDialog, NoiseRemovalDialog, NormalizeDialog, PhaserDialog, RepeatDialog, TimeScaleDialog, ToneGenDialog, TruncSilenceDialog, and WahwahDialog.
Referenced by Init(), TransferDataFromWindow(), and TransferDataToWindow().
bool EffectDialog::TransferDataFromWindow () [virtual]
Reimplemented in AmplifyDialog, BassBoostDialog, ChangePitchDialog, ChangeSpeedDialog, ChangeTempoDialog, ClickRemovalDialog, CompressorDialog, DtmfDialog, EchoDialog, FindClippingDialog, NoiseDialog, NoiseRemovalDialog, NormalizeDialog, PhaserDialog, RepeatDialog, TimeScaleDialog, ToneGenDialog, and WahwahDialog.
References eIsGettingFromDialog, and PopulateOrExchange().
Referenced by TruncSilenceDialog::OnDurationChange(), TruncSilenceDialog::OnPreview(), and LevellerDialog::OnPreview().
bool EffectDialog::TransferDataToWindow () [virtual]
Reimplemented in AmplifyDialog, BassBoostDialog, ChangePitchDialog, ChangeSpeedDialog, ChangeTempoDialog, ClickRemovalDialog, CompressorDialog, DtmfDialog, EchoDialog, NoiseDialog, NoiseRemovalDialog, NormalizeDialog, PhaserDialog, RepeatDialog, TimeScaleDialog, ToneGenDialog, and WahwahDialog.
References eIsSettingToDialog, and PopulateOrExchange().
Referenced by EffectLeveller::PromptUser().
bool EffectDialog::Validate () [virtual]
Reimplemented in AmplifyDialog.
Member Data Documentation
int EffectDialog::mType [private]
Referenced by EffectDialog(), and Init().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp