Audacity: RangeValidator Class Reference
RangeValidator Class Reference
Parameter must lie between the two given numbers.
#include <Validators.h>
Public Member Functions
RangeValidator (double l, double u)
virtual bool Validate (const wxVariant &v)
Judge whether the passed value satisfies the Validator.
virtual wxString GetDescription () const
virtual Validator * GetClone () const
This MUST be overridden, to avoid slicing!
Private Attributes
double mLower
double mUpper
Detailed Description
Parameter must lie between the two given numbers.
Constructor & Destructor Documentation
RangeValidator::RangeValidator (double l, double u) [inline]
Referenced by GetClone().
Member Function Documentation
virtual Validator* RangeValidator::GetClone () const [inline, virtual]
This MUST be overridden, to avoid slicing!
Reimplemented from Validator.
References mLower, mUpper, and RangeValidator().
virtual wxString RangeValidator::GetDescription () const [inline, virtual]
Return a description (for error messages) should be of the form 'v must be $description'
Reimplemented from Validator.
References mLower, and mUpper.
virtual bool RangeValidator::Validate (const wxVariant & v) [inline, virtual]
Judge whether the passed value satisfies the Validator.
Reimplemented from Validator.
References mLower, mUpper, and Validator::SetConverted().
Member Data Documentation
double RangeValidator::mLower [private]
Referenced by GetClone(), GetDescription(), and Validate().
double RangeValidator::mUpper [private]
Referenced by GetClone(), GetDescription(), and Validate().
The documentation for this class was generated from the following file:
Validators.h