Audacity: ToolDock Class Reference
ToolDock Class Reference
A dynamic panel where a ToolBar can be docked.
#include <ToolDock.h>
Public Member Functions
ToolDock (ToolManager *manager, wxWindow *parent, int dockid)
~ToolDock ()
void LayoutToolBars ()
void ShowHide (int type)
void Expose (int type, bool show)
int GetOrder (ToolBar *bar)
void Dock (ToolBar *bar, int ndx=-1)
void Undock (ToolBar *bar)
int PositionBar (ToolBar *t, wxPoint &pos, wxRect &rect)
DECLARE_CLASS (ToolDock)
DECLARE_EVENT_TABLE ()
Protected Member Functions
void OnErase (wxEraseEvent &event)
void OnSize (wxSizeEvent &event)
void OnPaint (wxPaintEvent &event)
void OnGrabber (GrabberEvent &event)
Private Member Functions
void ReadConfig ()
void WriteConfig ()
int FlowLayout (int cnt, wxRect boxen[], wxRect ideal[], int i, int x, int y, int width, int height)
void Updated ()
Private Attributes
int mTotalToolBarHeight
wxWindow * mParent
ToolManager * mManager
wxArrayPtrVoid mDockedBars
ToolBar * mBars [ToolBarCount]
Detailed Description
A dynamic panel where a ToolBar can be docked.
Constructor & Destructor Documentation
ToolDock::ToolDock (ToolManager * manager, wxWindow * parent, int dockid)
ToolDock::~ToolDock ()
Member Function Documentation
ToolDock::DECLARE_CLASS (ToolDock)
ToolDock::DECLARE_EVENT_TABLE ()
void ToolDock::Dock (ToolBar * bar, int ndx = -1)
References LayoutToolBars(), mBars, mDockedBars, ToolBar::SetDocked(), and Updated().
Referenced by ToolManager::OnMouse(), ToolManager::ReadConfig(), and ToolManager::Reset().
void ToolDock::Expose (int type, bool show)
References ToolBar::Expose(), LayoutToolBars(), mBars, mDockedBars, and Updated().
Referenced by ToolManager::Expose().
int ToolDock::FlowLayout (int cnt, wxRect boxen[], wxRect ideal[], int i, int x, int y, int width, int height) [private]
int ToolDock::GetOrder (ToolBar * bar)
References mDockedBars.
Referenced by ToolManager::WriteConfig().
void ToolDock::LayoutToolBars ()
References mDockedBars, ToolBarCount, and toolbarGap.
Referenced by Dock(), Expose(), ToolManager::LayoutToolBars(), and ShowHide().
void ToolDock::OnErase (wxEraseEvent & event) [protected]
void ToolDock::OnGrabber (GrabberEvent & event) [protected]
References mBars, mDockedBars, and mManager.
void ToolDock::OnPaint (wxPaintEvent & event) [protected]
References AColor::Dark(), AColor::Line(), and mDockedBars.
void ToolDock::OnSize (wxSizeEvent & event) [protected]
int ToolDock::PositionBar (ToolBar * t, wxPoint & pos, wxRect & rect)
References ToolBar::IsResizable(), mDockedBars, min(), ToolBarCount, and toolbarGap.
Referenced by ToolManager::OnMouse().
void ToolDock::ReadConfig () [private]
void ToolDock::ShowHide (int type)
References ToolBar::Expose(), ToolBar::IsVisible(), LayoutToolBars(), mBars, mDockedBars, and Updated().
Referenced by ToolManager::ReadConfig(), and ToolManager::ShowHide().
void ToolDock::Undock (ToolBar * bar)
References mDockedBars.
Referenced by ToolManager::Reset().
void ToolDock::Updated () [private]
Referenced by Dock(), Expose(), and ShowHide().
void ToolDock::WriteConfig () [private]
Member Data Documentation
ToolBar* ToolDock::mBars[ToolBarCount] [private]
Referenced by Dock(), Expose(), OnGrabber(), and ShowHide().
wxArrayPtrVoid ToolDock::mDockedBars [private]
Referenced by Dock(), Expose(), GetOrder(), LayoutToolBars(), OnGrabber(), OnPaint(), PositionBar(), ShowHide(), and Undock().
ToolManager* ToolDock::mManager [private]
Referenced by OnGrabber().
wxWindow* ToolDock::mParent [private]
int ToolDock::mTotalToolBarHeight [private]
The documentation for this class was generated from the following files:
ToolDock.h
ToolDock.cpp