Audacity: ToolBarArea Class Reference
ToolBarArea Class Reference
An alterantive to ToolBarFrame which can contain an ExpandingToolBar. ToolBarArea is used for a 'docked' ToolBar, ToolBarFrame for a floating one.
#include <ExpandingToolBar.h>
Public Member Functions
ToolBarArea (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~ToolBarArea ()
virtual bool Layout ()
virtual void Fit ()
virtual void OnSize (wxSizeEvent &evt)
virtual void OnMouse (wxMouseEvent &evt)
void CollapseAll (bool now=false)
void AddChild (ExpandingToolBar *child)
void RemoveChild (ExpandingToolBar *child)
ToolBarArrangement * SaveArrangement ()
void RestoreArrangement (ToolBarArrangement *arrangement)
wxArrayRect GetDropTargets ()
void MoveChild (ExpandingToolBar *child, wxRect dropTarget)
void SetCapturedChild (ExpandingToolBar *child)
Protected Member Functions
void ContractRow (int rowIndex)
bool ExpandRow (int rowIndex)
void LayoutOne (int childIndex)
void AdjustLayout ()
void Fit (bool horizontal, bool vertical)
Protected Attributes
ExpandingToolBarArray mChildArray
wxArrayInt mRowArray
wxSize mLastLayoutSize
bool mInOnSize
ExpandingToolBar * mCapturedChild
wxSize mMinSize
wxSize mMaxSize
wxSize mActualSize
wxArrayRect mDropTargets
wxArrayInt mDropTargetIndices
wxArrayInt mDropTargetRows
Detailed Description
An alterantive to ToolBarFrame which can contain an ExpandingToolBar. ToolBarArea is used for a 'docked' ToolBar, ToolBarFrame for a floating one.
Constructor & Destructor Documentation
ToolBarArea::ToolBarArea (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
ToolBarArea::~ToolBarArea ()
Member Function Documentation
void ToolBarArea::AddChild (ExpandingToolBar * child)
References Fit(), LayoutOne(), mChildArray, and mRowArray.
Referenced by ExpandingToolBar::OnSize().
void ToolBarArea::AdjustLayout () [protected]
References ExpandRow(), LayoutOne(), mChildArray, and mRowArray.
Referenced by OnSize().
void ToolBarArea::CollapseAll (bool now = false)
References mChildArray.
Referenced by ExpandingToolBar::FinishMoving(), and ExpandingToolBar::StartMoving().
void ToolBarArea::ContractRow (int rowIndex) [protected]
References mChildArray, and mRowArray.
Referenced by LayoutOne(), and MoveChild().
bool ToolBarArea::ExpandRow (int rowIndex) [protected]
References mChildArray, and mRowArray.
Referenced by AdjustLayout(), and LayoutOne().
void ToolBarArea::Fit (bool horizontal, bool vertical) [protected]
References mActualSize, mChildArray, mMaxSize, and mMinSize.
void ToolBarArea::Fit () [virtual]
Referenced by AddChild(), MoveChild(), OnSize(), RemoveChild(), and RestoreArrangement().
wxArrayRect ToolBarArea::GetDropTargets ()
References mChildArray, mDropTargetIndices, mDropTargetRows, mDropTargets, and mRowArray.
Referenced by ExpandingToolBar::StartMoving().
bool ToolBarArea::Layout () [virtual]
References LayoutOne(), mChildArray, and mRowArray.
Referenced by OnSize().
void ToolBarArea::LayoutOne (int childIndex) [protected]
References ContractRow(), ExpandRow(), mChildArray, mLastLayoutSize, and mRowArray.
Referenced by AddChild(), AdjustLayout(), Layout(), MoveChild(), and RemoveChild().
void ToolBarArea::MoveChild (ExpandingToolBar * child, wxRect dropTarget)
References ContractRow(), Fit(), LayoutOne(), mChildArray, mDropTargetIndices, mDropTargetRows, mDropTargets, and mRowArray.
Referenced by ExpandingToolBar::FinishMoving().
void ToolBarArea::OnMouse (wxMouseEvent & evt) [virtual]
References ExpandingToolBar::FinishMoving(), mCapturedChild, and ExpandingToolBar::UpdateMoving().
void ToolBarArea::OnSize (wxSizeEvent & evt) [virtual]
References AdjustLayout(), Fit(), Layout(), mInOnSize, and mLastLayoutSize.
void ToolBarArea::RemoveChild (ExpandingToolBar * child)
References Fit(), LayoutOne(), mChildArray, and mRowArray.
Referenced by ExpandingToolBar::StartMoving().
void ToolBarArea::RestoreArrangement (ToolBarArrangement * arrangement)
References ToolBarArrangement::childArray, Fit(), mChildArray, mRowArray, ToolBarArrangement::rectArray, and ToolBarArrangement::rowArray.
Referenced by ExpandingToolBar::FinishMoving().
ToolBarArrangement * ToolBarArea::SaveArrangement ()
References ToolBarArrangement::childArray, mChildArray, mRowArray, ToolBarArrangement::rectArray, and ToolBarArrangement::rowArray.
Referenced by ExpandingToolBar::StartMoving().
void ToolBarArea::SetCapturedChild (ExpandingToolBar * child)
References mCapturedChild.
Referenced by ExpandingToolBar::FinishMoving(), and ExpandingToolBar::StartMoving().
Member Data Documentation
wxSize ToolBarArea::mActualSize [protected]
Referenced by Fit().
ExpandingToolBar* ToolBarArea::mCapturedChild [protected]
Referenced by OnMouse(), and SetCapturedChild().
ExpandingToolBarArray ToolBarArea::mChildArray [protected]
Referenced by AddChild(), AdjustLayout(), CollapseAll(), ContractRow(), ExpandRow(), Fit(), GetDropTargets(), Layout(), LayoutOne(), MoveChild(), RemoveChild(), RestoreArrangement(), and SaveArrangement().
wxArrayInt ToolBarArea::mDropTargetIndices [protected]
Referenced by GetDropTargets(), and MoveChild().
wxArrayInt ToolBarArea::mDropTargetRows [protected]
Referenced by GetDropTargets(), and MoveChild().
wxArrayRect ToolBarArea::mDropTargets [protected]
Referenced by GetDropTargets(), and MoveChild().
bool ToolBarArea::mInOnSize [protected]
Referenced by OnSize().
wxSize ToolBarArea::mLastLayoutSize [protected]
Referenced by LayoutOne(), and OnSize().
wxSize ToolBarArea::mMaxSize [protected]
Referenced by Fit().
wxSize ToolBarArea::mMinSize [protected]
Referenced by Fit().
wxArrayInt ToolBarArea::mRowArray [protected]
Referenced by AddChild(), AdjustLayout(), ContractRow(), ExpandRow(), GetDropTargets(), Layout(), LayoutOne(), MoveChild(), RemoveChild(), RestoreArrangement(), and SaveArrangement().
The documentation for this class was generated from the following files:
ExpandingToolBar.h
ExpandingToolBar.cpp