Audacity: ToolManager Class Reference
ToolManager Class Reference
Manages the ToolDocks and handles the dragging, floating, and docking of ToolBars.
#include <ToolManager.h>
Public Member Functions
ToolManager (AudacityProject *parent)
~ToolManager ()
void LayoutToolBars ()
void UpdatePrefs ()
bool IsDocked (int type)
bool IsVisible (int type)
void ShowHide (int type)
void Expose (int type, bool show)
ToolBar * GetToolBar (int type) const
ToolDock * GetTopDock ()
ToolDock * GetBotDock ()
void Reset ()
DECLARE_CLASS (ToolManager)
DECLARE_EVENT_TABLE ()
Private Member Functions
ToolBar * Float (ToolBar *t, wxPoint &pos)
void OnTimer (wxTimerEvent &event)
void OnMouse (wxMouseEvent &event)
void OnCaptureLost (wxMouseCaptureLostEvent &event)
void OnGrabber (GrabberEvent &event)
void OnIndicatorCreate (wxWindowCreateEvent &event)
void OnIndicatorPaint (wxPaintEvent &event)
void ReadConfig ()
void WriteConfig ()
void Updated ()
Private Attributes
AudacityProject * mParent
ToolFrame * mDragWindow
ToolDock * mDragDock
ToolBar * mDragBar
wxPoint mDragOffset
int mDragBefore
wxPoint mLastPos
wxRect mBarPos
wxFrame * mIndicator
wxRegion * mLeft
wxRegion * mDown
wxRegion * mCurrent
wxTimer mTimer
bool mLastState
wxArrayPtrVoid mDockedBars
ToolDock * mTopDock
ToolDock * mBotDock
ToolBar * mBars [ToolBarCount]
Detailed Description
Manages the ToolDocks and handles the dragging, floating, and docking of ToolBars.
class ToolManager
Constructor & Destructor Documentation
ToolManager::ToolManager (AudacityProject * parent)
Methods for ToolManager
References BotDockID, ControlBarID, DeviceBarID, EditBarID, MeterBarID, MixerBarID, OnCaptureLost(), OnIndicatorCreate(), OnIndicatorPaint(), OnMouse(), SelectionBarID, ToolsBarID, TopDockID, and TranscriptionBarID.
ToolManager::~ToolManager ()
References mDown, mIndicator, mLeft, mParent, OnCaptureLost(), OnIndicatorCreate(), OnIndicatorPaint(), OnMouse(), and WriteConfig().
Member Function Documentation
ToolManager::DECLARE_CLASS (ToolManager)
ToolManager::DECLARE_EVENT_TABLE ()
void ToolManager::Expose (int type, bool show)
References ToolBar::Expose(), ToolDock::Expose(), ToolBar::GetDock(), ToolBar::IsDocked(), and mBars.
Referenced by Reset().
ToolBar* ToolManager::Float (ToolBar * t, wxPoint & pos) [private]
ToolDock * ToolManager::GetBotDock ()
References mBotDock.
Referenced by ScreenshotCommand::Apply(), AudacityProject::GetFocusedFrame(), AudacityProject::NextFrame(), AudacityProject::PrevFrame(), and AudacityProject::UpdateLayout().
ToolBar * ToolManager::GetToolBar (int type) const
References mBars.
Referenced by ScreenshotCommand::CaptureToolbar(), AudacityProject::GetControlToolBar(), AudacityProject::GetDeviceToolBar(), AudacityProject::GetEditToolBar(), AudacityProject::GetMeterToolBar(), AudacityProject::GetMixerToolBar(), AudacityProject::GetSelectionBar(), AudacityProject::GetToolsToolBar(), AudacityProject::GetTranscriptionToolBar(), and AudacityProject::ModifyToolbarMenus().
ToolDock * ToolManager::GetTopDock ()
References mTopDock.
Referenced by ScreenshotCommand::Apply(), AudacityProject::GetFocusedFrame(), AudacityProject::NextFrame(), and AudacityProject::PrevFrame().
bool ToolManager::IsDocked (int type)
References ToolBar::IsDocked(), and mBars.
bool ToolManager::IsVisible (int type)
References ToolBar::IsDocked(), ToolBar::IsVisible(), and mBars.
Referenced by ScreenshotCommand::CaptureToolbar(), AudacityProject::ModifyToolbarMenus(), and WriteConfig().
void ToolManager::LayoutToolBars ()
References ToolDock::LayoutToolBars(), mBotDock, and mTopDock.
Referenced by Reset(), and AudacityProject::UpdateLayout().
void ToolManager::OnCaptureLost (wxMouseCaptureLostEvent & event) [private]
References mDragWindow, mParent, and OnMouse().
Referenced by ToolManager(), and ~ToolManager().
void ToolManager::OnGrabber (GrabberEvent & event) [private]
References ToolBar::IsDocked(), mBars, mDragBar, mDragOffset, mDragWindow, mLastState, mParent, mTimer, ToolBar::SetDocked(), SetOption(), and Updated().
void ToolManager::OnIndicatorCreate (wxWindowCreateEvent & event) [private]
References mCurrent, and mIndicator.
Referenced by ToolManager(), and ~ToolManager().
void ToolManager::OnIndicatorPaint (wxPaintEvent & event) [private]
Referenced by ToolManager(), and ~ToolManager().
void ToolManager::OnMouse (wxMouseEvent & event) [private]
References ToolDock::Dock(), mBarPos, mBotDock, mCurrent, mDown, mDragBar, mDragBefore, mDragDock, mDragOffset, mDragWindow, mIndicator, mLastPos, mLeft, mParent, mTimer, mTopDock, ToolDock::PositionBar(), ToolBar::SetDocked(), and SetOption().
Referenced by OnCaptureLost(), ToolManager(), and ~ToolManager().
void ToolManager::OnTimer (wxTimerEvent & event) [private]
References mDragWindow, mIndicator, mLastState, and SetOption().
void ToolManager::ReadConfig () [private]
References ToolBar::Add(), BotDockID, ToolBar::Create(), DeviceBarID, ToolDock::Dock(), DockCount, ToolBar::Expose(), ToolBar::GetSection(), gPrefs, mBars, mBotDock, mParent, mTopDock, NoBarID, SelectionBarID, ToolBar::SetDocked(), SetOption(), ToolDock::ShowHide(), ToolBarCount, and TopDockID.
void ToolManager::Reset ()
References DeviceBarID, ToolDock::Dock(), ToolBar::EnableDisableButtons(), Expose(), ToolBar::GetDock(), ToolBar::IsDocked(), ToolBar::IsResizable(), LayoutToolBars(), mBars, mBotDock, mTopDock, ToolBar::ReCreateButtons(), SelectionBarID, ToolBarCount, ToolDock::Undock(), and Updated().
Referenced by ScreenshotCommand::Apply(), AudacityProject::OnResetToolBars(), ScreenFrame::ScreenFrame(), and ScreenFrame::SizeMainWindow().
void ToolManager::ShowHide (int type)
References ToolBar::Expose(), ToolBar::GetDock(), ToolBar::IsDocked(), ToolBar::IsVisible(), mBars, and ToolDock::ShowHide().
Referenced by ScreenshotCommand::CaptureToolbar(), AudacityProject::OnShowControlToolBar(), AudacityProject::OnShowDeviceToolBar(), AudacityProject::OnShowEditToolBar(), AudacityProject::OnShowMeterToolBar(), AudacityProject::OnShowMixerToolBar(), AudacityProject::OnShowSelectionToolBar(), AudacityProject::OnShowToolsToolBar(), and AudacityProject::OnShowTranscriptionToolBar().
void ToolManager::Updated () [private]
References mParent.
Referenced by OnGrabber(), and Reset().
void ToolManager::UpdatePrefs ()
References mBars, ToolBarCount, and ToolBar::UpdatePrefs().
Referenced by AudacityProject::UpdatePrefs().
void ToolManager::WriteConfig () [private]
References BotDockID, ToolDock::GetOrder(), ToolBar::GetSection(), gPrefs, ToolBar::IsDocked(), IsVisible(), mBars, mBotDock, mTopDock, NoDockID, ToolBarCount, and TopDockID.
Referenced by ~ToolManager().
Member Data Documentation
wxRect ToolManager::mBarPos [private]
Referenced by OnMouse().
ToolBar* ToolManager::mBars[ToolBarCount] [private]
Referenced by Expose(), GetToolBar(), IsDocked(), IsVisible(), OnGrabber(), ReadConfig(), Reset(), ShowHide(), UpdatePrefs(), and WriteConfig().
ToolDock* ToolManager::mBotDock [private]
Referenced by GetBotDock(), LayoutToolBars(), OnMouse(), ReadConfig(), Reset(), and WriteConfig().
wxRegion* ToolManager::mCurrent [private]
Referenced by OnIndicatorCreate(), and OnMouse().
wxArrayPtrVoid ToolManager::mDockedBars [private]
wxRegion* ToolManager::mDown [private]
Referenced by OnMouse(), and ~ToolManager().
ToolBar* ToolManager::mDragBar [private]
Referenced by OnGrabber(), and OnMouse().
int ToolManager::mDragBefore [private]
Referenced by OnMouse().
ToolDock* ToolManager::mDragDock [private]
Referenced by OnMouse().
wxPoint ToolManager::mDragOffset [private]
Referenced by OnGrabber(), and OnMouse().
ToolFrame* ToolManager::mDragWindow [private]
Referenced by OnCaptureLost(), OnGrabber(), OnMouse(), and OnTimer().
wxFrame* ToolManager::mIndicator [private]
Referenced by OnIndicatorCreate(), OnMouse(), OnTimer(), and ~ToolManager().
wxPoint ToolManager::mLastPos [private]
Referenced by OnMouse().
bool ToolManager::mLastState [private]
Referenced by OnGrabber(), and OnTimer().
wxRegion* ToolManager::mLeft [private]
Referenced by OnMouse(), and ~ToolManager().
AudacityProject* ToolManager::mParent [private]
Referenced by OnCaptureLost(), OnGrabber(), OnMouse(), ReadConfig(), Updated(), and ~ToolManager().
wxTimer ToolManager::mTimer [private]
Referenced by OnGrabber(), and OnMouse().
ToolDock* ToolManager::mTopDock [private]
Referenced by GetTopDock(), LayoutToolBars(), OnMouse(), ReadConfig(), Reset(), and WriteConfig().
The documentation for this class was generated from the following files:
ToolManager.h
ToolManager.cpp