Audacity: RepeatDialog Class Reference
RepeatDialog Class Reference
Dialog used with EffectRepeat.
#include <Repeat.h>
Public Member Functions
RepeatDialog (EffectRepeat *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
int repeatCount
int maxCount
double selectionTimeSecs
Private Member Functions
void OnRepeatTextChange (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
void DisplayNewTime ()
Private Attributes
EffectRepeat * mEffect
wxTextCtrl * mRepeatCount
wxStaticText * mTotalTime
Detailed Description
Dialog used with EffectRepeat.
Constructor & Destructor Documentation
RepeatDialog::RepeatDialog (EffectRepeat * effect, wxWindow * parent)
Member Function Documentation
void RepeatDialog::DisplayNewTime () [private]
References TimeTextCtrl::GetBuiltinFormat(), TimeTextCtrl::GetTimeString(), mEffect, Effect::mProjectRate, mTotalTime, repeatCount, selectionTimeSecs, and TimeTextCtrl::SetFormatString().
Referenced by OnRepeatTextChange(), and TransferDataToWindow().
void RepeatDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References mEffect, Effect::Preview(), repeatCount, EffectRepeat::repeatCount, and TransferDataFromWindow().
void RepeatDialog::OnRepeatTextChange (wxCommandEvent & event) [private]
References DisplayNewTime(), and TransferDataFromWindow().
void RepeatDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddVariableText(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGui::Id(), ID_REPEAT_TEXT, mRepeatCount, mTotalTime, numbers, and ShuttleGuiBase::StartHorizontalLay().
bool RepeatDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References maxCount, mRepeatCount, and repeatCount.
Referenced by OnPreview(), and OnRepeatTextChange().
bool RepeatDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References DisplayNewTime(), mRepeatCount, and repeatCount.
Referenced by EffectRepeat::PromptUser().
Member Data Documentation
int RepeatDialog::maxCount
Referenced by EffectRepeat::PromptUser(), and TransferDataFromWindow().
EffectRepeat* RepeatDialog::mEffect [private]
Referenced by DisplayNewTime(), and OnPreview().
wxTextCtrl* RepeatDialog::mRepeatCount [private]
Referenced by PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
wxStaticText* RepeatDialog::mTotalTime [private]
Referenced by DisplayNewTime(), and PopulateOrExchange().
int RepeatDialog::repeatCount
Referenced by DisplayNewTime(), OnPreview(), EffectRepeat::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
double RepeatDialog::selectionTimeSecs
Referenced by DisplayNewTime(), and EffectRepeat::PromptUser().
The documentation for this class was generated from the following files:
Repeat.h
Repeat.cpp