Audacity: ImportFileHandle Class Reference
ImportFileHandle Class Reference
An ImportFileHandle for data.
#include <ImportPlugin.h>
Public Member Functions
ImportFileHandle (const wxString &filename)
virtual ~ImportFileHandle ()
void CreateProgress ()
virtual wxString GetFileDescription ()=0
virtual int GetFileUncompressedBytes ()=0
virtual int Import (TrackFactory *trackFactory, Track ***outTracks, int *outNumTracks, Tags *tags)=0
virtual wxInt32 GetStreamCount ()=0
virtual wxArrayString * GetStreamInfo ()=0
virtual void SetStreamUsage (wxInt32 StreamID, bool Use)=0
Protected Attributes
wxString mFilename
ProgressDialog * mProgress
Detailed Description
An ImportFileHandle for data.
Base class for FlacImportFileHandle, LOFImportFileHandle, MP3ImportFileHandle, OggImportFileHandle and PCMImportFileHandle. Gives API for sound file import.
The Ogg format supports multiple logical bitstreams that can be chained within the physical bitstream. The sampling rate and number of channels can vary between these logical bitstreams. For the moment, we'll ignore all but the first logical bitstream.
Ogg also allows for an arbitrary number of channels. Luckily, so does Audacity. We'll call the first channel LeftChannel, the second RightChannel, and all others after it MonoChannel.
Constructor & Destructor Documentation
ImportFileHandle::ImportFileHandle (const wxString & filename) [inline]
virtual ImportFileHandle::~ImportFileHandle () [inline, virtual]
References mProgress.
Member Function Documentation
void ImportFileHandle::CreateProgress () [inline]
References GetFileDescription(), mFilename, and mProgress.
Referenced by PCMImportFileHandle::Import(), OggImportFileHandle::Import(), MP3ImportFileHandle::Import(), FLACImportFileHandle::Import(), and FFmpegImportFileHandle::Import().
virtual wxString ImportFileHandle::GetFileDescription () [pure virtual]
Implemented in FFmpegImportFileHandle, FLACImportFileHandle, LOFImportFileHandle, MP3ImportFileHandle, OggImportFileHandle, and PCMImportFileHandle.
Referenced by CreateProgress().
virtual int ImportFileHandle::GetFileUncompressedBytes () [pure virtual]
Implemented in FFmpegImportFileHandle, FLACImportFileHandle, LOFImportFileHandle, MP3ImportFileHandle, OggImportFileHandle, and PCMImportFileHandle.
virtual wxInt32 ImportFileHandle::GetStreamCount () [pure virtual]
Implemented in FFmpegImportFileHandle, FLACImportFileHandle, LOFImportFileHandle, MP3ImportFileHandle, OggImportFileHandle, and PCMImportFileHandle.
Referenced by Importer::Import().
virtual wxArrayString* ImportFileHandle::GetStreamInfo () [pure virtual]
Implemented in FFmpegImportFileHandle, FLACImportFileHandle, LOFImportFileHandle, MP3ImportFileHandle, OggImportFileHandle, and PCMImportFileHandle.
virtual int ImportFileHandle::Import (TrackFactory * trackFactory, Track *** outTracks, int * outNumTracks, Tags * tags) [pure virtual]
Implemented in FFmpegImportFileHandle, FLACImportFileHandle, LOFImportFileHandle, MP3ImportFileHandle, OggImportFileHandle, and PCMImportFileHandle.
Referenced by Importer::Import().
virtual void ImportFileHandle::SetStreamUsage (wxInt32 StreamID, bool Use) [pure virtual]
Implemented in FFmpegImportFileHandle, FLACImportFileHandle, LOFImportFileHandle, MP3ImportFileHandle, OggImportFileHandle, and PCMImportFileHandle.
Referenced by Importer::Import(), and ImportStreamDialog::OnOk().
Member Data Documentation
wxString ImportFileHandle::mFilename [protected]
Referenced by CreateProgress(), PCMImportFileHandle::Import(), FLACImportFileHandle::Import(), MP3ImportFileHandle::ImportID3(), and FLACImportFileHandle::Init().
ProgressDialog* ImportFileHandle::mProgress [protected]
Referenced by CreateProgress(), PCMImportFileHandle::Import(), OggImportFileHandle::Import(), MP3ImportFileHandle::Import(), FLACImportFileHandle::Import(), MyFLACFile::write_callback(), FFmpegImportFileHandle::WriteData(), and ~ImportFileHandle().
The documentation for this class was generated from the following file:
ImportPlugin.h