Audacity: GetProjectInfoCommand Class Reference
GetProjectInfoCommand Class Reference
Command that returns requested project information.
#include <GetProjectInfoCommand.h>
Public Member Functions
GetProjectInfoCommand (CommandType &type, CommandOutputTarget *target)
virtual ~GetProjectInfoCommand ()
virtual bool Apply (CommandExecutionContext context)
Private Types
typedef bool(GetProjectInfoCommand::* Getter)(Track *track) const
Private Member Functions
int SendNumberOfTracks (CommandExecutionContext context)
int SendFocusedTrackIndex (CommandExecutionContext context)
void SendTracksInfo (TrackList *projTracks, Getter)
bool testSelected (Track *track) const
bool testLinked (Track *track) const
bool testSolo (Track *track) const
bool testMute (Track *track) const
Detailed Description
Command that returns requested project information.
Member Typedef Documentation
typedef bool(GetProjectInfoCommand::* GetProjectInfoCommand::Getter)(Track *track) const [private]
Constructor & Destructor Documentation
GetProjectInfoCommand::GetProjectInfoCommand (CommandType & type, CommandOutputTarget * target) [inline]
virtual GetProjectInfoCommand::~GetProjectInfoCommand () [inline, virtual]
Member Function Documentation
bool GetProjectInfoCommand::Apply (CommandExecutionContext context) [virtual]
Actually carry out the command. Return true if successful and false otherwise.
Reimplemented from CommandImplementation.
References CommandImplementation::Error(), AudacityProject::GetFileName(), CommandImplementation::GetString(), AudacityProject::GetTracks(), CommandExecutionContext::proj, SendFocusedTrackIndex(), SendNumberOfTracks(), SendTracksInfo(), CommandImplementation::Status(), testLinked(), testMute(), testSelected(), and testSolo().
int GetProjectInfoCommand::SendFocusedTrackIndex (CommandExecutionContext context) [private]
References TrackPanel::GetFocusedTrack(), AudacityProject::GetTrackPanel(), AudacityProject::GetTracks(), CommandExecutionContext::proj, and CommandImplementation::Status().
Referenced by Apply().
int GetProjectInfoCommand::SendNumberOfTracks (CommandExecutionContext context) [private]
References AudacityProject::GetTracks(), CommandExecutionContext::proj, and CommandImplementation::Status().
Referenced by Apply().
void GetProjectInfoCommand::SendTracksInfo (TrackList * projTracks, Getter functPtrToGetter) [private]
References TrackListIterator::First(), TrackListIterator::Next(), and CommandImplementation::Status().
Referenced by Apply().
bool GetProjectInfoCommand::testLinked (Track * track) const [inline, private]
References Track::GetLinked().
Referenced by Apply().
bool GetProjectInfoCommand::testMute (Track * track) const [inline, private]
References Track::GetMute().
Referenced by Apply().
bool GetProjectInfoCommand::testSelected (Track * track) const [inline, private]
References Track::GetSelected().
Referenced by Apply().
bool GetProjectInfoCommand::testSolo (Track * track) const [inline, private]
References Track::GetSolo().
Referenced by Apply().
The documentation for this class was generated from the following files:
GetProjectInfoCommand.h
GetProjectInfoCommand.cpp