Audacity: TimeTextCtrl Class Reference
TimeTextCtrl Class Reference
TimeTextCtrl provides the advanced time formatting control used in the status bar of Audacity.
#include <TimeTextCtrl.h>
Public Member Functions
DECLARE_DYNAMIC_CLASS (TimeTextCtrl)
TimeTextCtrl (wxWindow *parent, wxWindowID id, wxString formatString=wxT(""), double timeValue=0.0, double sampleRate=44100, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, bool autoPos=false)
virtual ~TimeTextCtrl ()
virtual bool Layout ()
virtual void Fit ()
void SetFieldFocus (int digit)
void SetFormatString (wxString formatString)
void SetSampleRate (double sampleRate)
void SetTimeValue (double newTime)
void Increment ()
void Decrement ()
const double GetTimeValue ()
wxString GetTimeString ()
wxString GetFormatString ()
int GetFormatIndex ()
int GetNumBuiltins ()
wxString GetBuiltinName (const int index)
wxString GetBuiltinFormat (const int index)
wxString GetBuiltinFormat (const wxString &name)
void EnableMenu (bool enable=true)
int GetFocusedField ()
int GetFocusedDigit ()
Private Member Functions
void OnCaptureKey (wxCommandEvent &event)
void OnKeyDown (wxKeyEvent &event)
void OnMouse (wxMouseEvent &event)
void OnErase (wxEraseEvent &event)
void OnPaint (wxPaintEvent &event)
void OnFocus (wxFocusEvent &event)
void OnContext (wxContextMenuEvent &event)
void OnMenu (wxCommandEvent &event)
void ValueToControls ()
void ControlsToValue ()
void PrintDebugInfo ()
void UpdateAutoFocus ()
void Updated ()
void Increase (int steps)
void Decrease (int steps)
Private Attributes
BuiltinFormatString BuiltinFormatStrings [16]
array of formats the control knows about internally array of string pairs for name of the format and the format string needed to create that format output. This is used for the pop-up list of formats to choose from in the control. Note that the size will need adjusting if new time formats are added
double mTimeValue
wxString mFormatString
bool mMenuEnabled
wxBitmap * mBackgroundBitmap
wxFont * mDigitFont
wxFont * mLabelFont
int mDigitBoxW
int mDigitBoxH
int mDigitW
int mDigitH
int mBorderLeft
int mBorderTop
int mBorderRight
int mBorderBottom
int mWidth
int mHeight
int mButtonWidth
int mFocusedDigit
int mLastField
bool mAutoPos
DigitInfoArray mDigits
TimeConverter mConverter
double mScrollRemainder
Friends
class TimeTextCtrlAx
Detailed Description
TimeTextCtrl provides the advanced time formatting control used in the status bar of Audacity.
The TimeTextCtrl makes use of a format string to specify the exact way that a single time value is split into several fields, such as the hh:mm:ss format. The advantage of this format string is that it is very small and compact, but human-readable and somewhat intuitive, so that it's easy to add new time layouts in the future. It's also designed to make it easier to add i18n support, since the way that times are displayed in different languages could conceivably vary a lot.
The time to be formatted is expressed in seconds, so the format string specifies the relationship of each field to the number of seconds.
Let's start by considering an example: here's the format string that prints an integer number of seconds in the hour minute second h:m:s format:
:60:60
The "*" is a wildcard, saying that the leftmost field can contain numbers of arbitrary magnitude. The next character, ':', since it is not a digit or a wildcard, is interpreted as a delimiter, and will be displayed between those fields. The next number, 60, indicates that the range of the next field (minutes) is 60. Then there's another ':' delimiter, and finally the last field (seconds) is 60. So, if you give it a number like 3758 (note format it as:
3758 seconds, "*:60:60" -> "1:2:38"
Note that 3758 = 1*60*60 + 2*60 + 38.
When TimeTextCtrl formats an integer, you can think of its process as working from right to left. Given the value "3758", it fills in the seconds by dividing by 60, sticking the remainder in the seconds field and then passing the quotient to the next field to the left.
In order to format a field with leading zeros, simply add a leading zero to that field, like this:
3758 seconds, "*:060:060" -> "1:02:38"
In order to format fractions, simply include a field delimiter ending with a decimal point. If the delimiter is simply '.' with nothing else, then the '.' is actually displayed. Otherwise the '.' is dropped, and the other characters in the delimiter are displayed instead.
Here's how we'd display hours, minutes, and seconds with three decimal places after the seconds:
3758.5 seconds, "*:060:060.01000" -> "1:02:38.500"
Similarly, here's how we'd display the fractional part of seconds as film frames (24 per second) instead of milliseconds:
3758.5 seconds, "*:060:060 and .24 frames" -> "1:02:38 and 12 frames"
Note that the decimal '.' is associated with the delimeter, not with the 24.
Additionally, the special character '#' can be used in place of a number to represent the current sample rate. Use '0#' to add leading zeros to that field. For example:
3758.5 seconds, "*:060:060+.#samples" -> "1:02:38+22050samples"
(Almost) Finally, there is a rule that allows you to change the units into something other than seconds. To do this, put a "|" character on the far right, followed by a number specifying the scaling factor. As an exception to previous rules, decimal points are allowed in the final scaling factor - the period is not interpreted as it would be before the "|" character. (This is fine, because all previous fields must be integers to make sense.) Anyway, if you include a scaling factor after a "|", the time will be multiplied by this factor before it is formatted. For example, to express the current time in NTSC frames (~29.97 fps), you could use the following formatting:
3758.5 seconds, "*.01000 frames|29.97002997" -> "112642.358 frames"
Finally there is a further special character that can be used after a "|" and that is "N". This applies special rule for NTSC drop-frame timecode.
Summary of format string rules:
The characters '0-9', '*', and '#' are numeric. Any sequence of these characters is treated as defining a new field by specifying its range. All other characters become delimiters between fields. (The one exception is that '.' is treated as numeric after the optional '|'.)
A field with a range of '*', which only makes sense as the leftmost field, means the field should display as large a number as necessary. (Note: this no longer makes sense here and applies to a previous version).
The character '#' represents the current sample rate.
If a field specifier beings with a leading zero, it will be formatted with leading zeros, too - enough to display the maximum value that field can display. So the number 7 in a field specified as '01000' would be formatted as '007'. Bond. James Bond.
Any non-numeric characters before the first field are treated as a prefix, and will be displayed to the left of the first field.
A delimiter ending in '.' is treated specially. All fields after this delimeter are fractional fields, after the decimal point.
The '|' character is treated as a special delimiter. The number to the right of this character (which is allowed to contain a decimal point) is treated as a scaling factor. The time is multiplied by this factor before multiplying.
The special character 'N' after '|' is only used for NTSC drop-frame.
Constructor & Destructor Documentation
TimeTextCtrl::TimeTextCtrl (wxWindow * parent, wxWindowID id, wxString formatString = wxT(""), double timeValue = 0.0, double sampleRate = 44100, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, bool autoPos = false)
References BuiltinFormatStrings, Fit(), BuiltinFormatString::formatStr, Layout(), mButtonWidth, mConverter, mDigitBoxH, mDigitBoxW, mFormatString, mMenuEnabled, TimeConverter::mSampleRate, BuiltinFormatString::name, TimeConverter::ParseFormatString(), TimeTextCtrlAx, and ValueToControls().
TimeTextCtrl::~TimeTextCtrl () [virtual]
References mBackgroundBitmap, mDigitFont, and mLabelFont.
Member Function Documentation
void TimeTextCtrl::ControlsToValue () [private]
References TimeConverter::ControlsToValue(), mConverter, and mTimeValue.
Referenced by Decrease(), GetTimeValue(), Increase(), OnKeyDown(), SetFormatString(), SetSampleRate(), and SetTimeValue().
TimeTextCtrl::DECLARE_DYNAMIC_CLASS (TimeTextCtrl)
void TimeTextCtrl::Decrease (int steps) [private]
References ControlsToValue(), mConverter, mDigits, TimeConverter::mFields, mFocusedDigit, TimeConverter::mNtscDrop, TimeConverter::mScalingFactor, mTimeValue, and ValueToControls().
Referenced by Decrement(), OnKeyDown(), and OnMouse().
void TimeTextCtrl::Decrement ()
References Decrease(), mDigits, and mFocusedDigit.
Referenced by TrackPanel::GridMove().
void TimeTextCtrl::EnableMenu (bool enable = true)
References Fit(), Layout(), mButtonWidth, and mMenuEnabled.
Referenced by TimeEditor::BeginEdit(), SelectionBar::Populate(), TimerRecordDialog::PopulateOrExchange(), TimeDialog::PopulateOrExchange(), NoiseDialog::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), and ToneGenDialog::PopulateOrExchangeStandard().
void TimeTextCtrl::Fit () [virtual]
References mButtonWidth, mHeight, and mWidth.
Referenced by EnableMenu(), SetFormatString(), SetSampleRate(), and TimeTextCtrl().
wxString TimeTextCtrl::GetBuiltinFormat (const wxString & name)
References GetBuiltinFormat(), GetBuiltinName(), and GetNumBuiltins().
wxString TimeTextCtrl::GetBuiltinFormat (const int index)
References BuiltinFormatStrings, BuiltinFormatString::formatStr, and GetNumBuiltins().
Referenced by RepeatDialog::DisplayNewTime(), GetBuiltinFormat(), GetFormatIndex(), TrackPanel::GridMove(), OnContext(), OnMenu(), SelectionBar::OnUpdate(), SelectionBar::Populate(), TimeDialog::PopulateOrExchange(), NoiseDialog::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), ToneGenDialog::PopulateOrExchangeStandard(), SnapManager::SnapManager(), and TimeDialog::TransferDataToWindow().
wxString TimeTextCtrl::GetBuiltinName (const int index)
References BuiltinFormatStrings, GetNumBuiltins(), and BuiltinFormatString::name.
Referenced by GetBuiltinFormat(), OnContext(), OnMenu(), and SelectionBar::OnUpdate().
int TimeTextCtrl::GetFocusedDigit () [inline]
References mFocusedDigit.
int TimeTextCtrl::GetFocusedField () [inline]
References mLastField.
int TimeTextCtrl::GetFormatIndex ()
References GetBuiltinFormat(), GetNumBuiltins(), and mFormatString.
Referenced by SelectionBar::UpdatePrefs().
wxString TimeTextCtrl::GetFormatString ()
References mFormatString.
Referenced by SelectionBar::GetRightTime().
int TimeTextCtrl::GetNumBuiltins ()
References BuiltinFormatStrings.
Referenced by GetBuiltinFormat(), GetBuiltinName(), GetFormatIndex(), OnContext(), and OnMenu().
wxString TimeTextCtrl::GetTimeString ()
References mConverter, TimeConverter::mValueString, and ValueToControls().
Referenced by RepeatDialog::DisplayNewTime().
const double TimeTextCtrl::GetTimeValue ()
References ControlsToValue(), and mTimeValue.
Referenced by SnapManager::CondListAdd(), TimeEditor::EndEdit(), SelectionBar::GetLeftTime(), SelectionBar::GetRightTime(), TrackPanel::GridMove(), SelectionBar::ModifySelection(), TimerRecordDialog::OnDatePicker_End(), TimerRecordDialog::OnDatePicker_Start(), ContrastDialog::OnExport(), ContrastDialog::OnGetBackgroundDB(), ContrastDialog::OnGetForegroundDB(), TimerRecordDialog::OnTimeText_Duration(), TimerRecordDialog::OnTimeText_End(), TimerRecordDialog::OnTimeText_Start(), DtmfDialog::Recalculate(), ToneGenDialog::TransferDataFromWindow(), TimerRecordDialog::TransferDataFromWindow(), TimeDialog::TransferDataFromWindow(), and NoiseDialog::TransferDataFromWindow().
void TimeTextCtrl::Increase (int steps) [private]
References ControlsToValue(), mConverter, mDigits, TimeConverter::mFields, mFocusedDigit, TimeConverter::mNtscDrop, TimeConverter::mScalingFactor, mTimeValue, and ValueToControls().
Referenced by Increment(), OnKeyDown(), and OnMouse().
void TimeTextCtrl::Increment ()
References Increase(), mDigits, and mFocusedDigit.
Referenced by TrackPanel::GridMove().
bool TimeTextCtrl::Layout () [virtual]
References AColor::Arrow(), AColor::Bevel(), label, mBackgroundBitmap, mBorderBottom, mBorderLeft, mBorderRight, mBorderTop, mButtonWidth, mConverter, mDigitBoxH, mDigitBoxW, mDigitFont, mDigitH, mDigits, mDigitW, TimeConverter::mFields, mHeight, mLabelFont, mMenuEnabled, TimeConverter::mPrefix, mWidth, ThemeBase::SetBrushColour(), and theTheme.
Referenced by EnableMenu(), SetFormatString(), SetSampleRate(), and TimeTextCtrl().
void TimeTextCtrl::OnCaptureKey (wxCommandEvent & event) [private]
void TimeTextCtrl::OnContext (wxContextMenuEvent & event) [private]
References GetBuiltinFormat(), GetBuiltinName(), GetNumBuiltins(), ID_MENU, mFormatString, and mMenuEnabled.
Referenced by OnMouse().
void TimeTextCtrl::OnErase (wxEraseEvent & event) [private]
void TimeTextCtrl::OnFocus (wxFocusEvent & event) [private]
void TimeTextCtrl::OnKeyDown (wxKeyEvent & event) [private]
References ControlsToValue(), Decrease(), Increase(), mConverter, mDigits, mFocusedDigit, TimeConverter::mValueString, SetFieldFocus(), Updated(), ValueToControls(), and wxEVT_COMMAND_BUTTON_CLICKED.
void TimeTextCtrl::OnMenu (wxCommandEvent & event) [private]
References GetBuiltinFormat(), GetBuiltinName(), GetNumBuiltins(), ID_MENU, mMenuEnabled, and SetFormatString().
void TimeTextCtrl::OnMouse (wxMouseEvent & event) [private]
References Decrease(), Increase(), mDigits, mFocusedDigit, mMenuEnabled, mScrollRemainder, mWidth, OnContext(), and Updated().
void TimeTextCtrl::OnPaint (wxPaintEvent & event) [private]
References ThemeBase::Colour(), mBackgroundBitmap, mConverter, mDigitBoxH, mDigitBoxW, mDigitFont, mDigitH, mDigits, mDigitW, mFocusedDigit, mHeight, TimeConverter::mValueString, mWidth, ThemeBase::SetBrushColour(), ThemeBase::SetPenColour(), and theTheme.
void TimeTextCtrl::PrintDebugInfo () [private]
void TimeTextCtrl::SetFieldFocus (int digit)
References mDigits, mFocusedDigit, and mLastField.
Referenced by OnKeyDown(), and Updated().
void TimeTextCtrl::SetFormatString (wxString formatString)
References ControlsToValue(), Fit(), Layout(), mConverter, mFormatString, TimeConverter::ParseFormatString(), UpdateAutoFocus(), and ValueToControls().
Referenced by RepeatDialog::DisplayNewTime(), SelectionBar::GetRightTime(), TrackPanel::GridMove(), OnMenu(), SelectionBar::OnUpdate(), SelectionBar::Populate(), TimeDialog::PopulateOrExchange(), NoiseDialog::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), ToneGenDialog::PopulateOrExchangeStandard(), SnapManager::SnapManager(), and TimeDialog::TransferDataToWindow().
void TimeTextCtrl::SetSampleRate (double sampleRate)
References ControlsToValue(), Fit(), Layout(), mConverter, mFormatString, TimeConverter::mSampleRate, TimeConverter::ParseFormatString(), and ValueToControls().
Referenced by SelectionBar::GetRightTime(), SelectionBar::OnRate(), SelectionBar::SetRate(), and TimeDialog::TransferDataToWindow().
void TimeTextCtrl::SetTimeValue (double newTime)
References ControlsToValue(), mTimeValue, and ValueToControls().
Referenced by TimeEditor::BeginEdit(), SnapManager::CondListAdd(), SelectionBar::GetRightTime(), TrackPanel::GridMove(), InitContrastDialog(), TimerRecordDialog::OnDatePicker_End(), ContrastDialog::OnReset(), TimerRecordDialog::OnTimer(), TimerRecordDialog::OnTimeText_End(), TimerRecordDialog::OnTimeText_Start(), ContrastDialog::OnUseSelectionB(), ContrastDialog::OnUseSelectionF(), TimerRecordDialog::PopulateOrExchange(), TimeEditor::Reset(), ToneGenDialog::TransferDataToWindow(), TimeDialog::TransferDataToWindow(), NoiseDialog::TransferDataToWindow(), DtmfDialog::TransferDataToWindow(), TimerRecordDialog::UpdateDuration(), TimerRecordDialog::UpdateEnd(), and SelectionBar::ValuesToControls().
void TimeTextCtrl::UpdateAutoFocus () [private]
References mAutoPos, mConverter, mDigits, mFocusedDigit, and TimeConverter::mValueString.
Referenced by SetFormatString().
void TimeTextCtrl::Updated () [private]
References mFocusedDigit, SetFieldFocus(), and wxEVT_COMMAND_TEXT_UPDATED.
Referenced by OnKeyDown(), and OnMouse().
void TimeTextCtrl::ValueToControls () [private]
References mConverter, mTimeValue, and TimeConverter::ValueToControls().
Referenced by Decrease(), GetTimeString(), Increase(), OnKeyDown(), SetFormatString(), SetSampleRate(), SetTimeValue(), and TimeTextCtrl().
Friends And Related Function Documentation
friend class TimeTextCtrlAx [friend]
Referenced by TimeTextCtrl().
Member Data Documentation
BuiltinFormatString TimeTextCtrl::BuiltinFormatStrings[16] [private]
array of formats the control knows about internally array of string pairs for name of the format and the format string needed to create that format output. This is used for the pop-up list of formats to choose from in the control. Note that the size will need adjusting if new time formats are added
Referenced by GetBuiltinFormat(), GetBuiltinName(), GetNumBuiltins(), and TimeTextCtrl().
bool TimeTextCtrl::mAutoPos [private]
Referenced by UpdateAutoFocus().
wxBitmap* TimeTextCtrl::mBackgroundBitmap [private]
Referenced by Layout(), OnPaint(), and ~TimeTextCtrl().
int TimeTextCtrl::mBorderBottom [private]
Referenced by Layout().
int TimeTextCtrl::mBorderLeft [private]
Referenced by Layout().
int TimeTextCtrl::mBorderRight [private]
Referenced by Layout().
int TimeTextCtrl::mBorderTop [private]
Referenced by Layout().
int TimeTextCtrl::mButtonWidth [private]
Referenced by EnableMenu(), Fit(), Layout(), and TimeTextCtrl().
TimeConverter TimeTextCtrl::mConverter [private]
Referenced by ControlsToValue(), Decrease(), GetTimeString(), Increase(), Layout(), OnKeyDown(), OnPaint(), SetFormatString(), SetSampleRate(), TimeTextCtrl(), UpdateAutoFocus(), and ValueToControls().
int TimeTextCtrl::mDigitBoxH [private]
Referenced by Layout(), OnPaint(), and TimeTextCtrl().
int TimeTextCtrl::mDigitBoxW [private]
Referenced by Layout(), OnPaint(), and TimeTextCtrl().
wxFont* TimeTextCtrl::mDigitFont [private]
Referenced by Layout(), OnPaint(), and ~TimeTextCtrl().
int TimeTextCtrl::mDigitH [private]
Referenced by Layout(), and OnPaint().
DigitInfoArray TimeTextCtrl::mDigits [private]
Referenced by Decrease(), Decrement(), Increase(), Increment(), Layout(), OnKeyDown(), OnMouse(), OnPaint(), SetFieldFocus(), and UpdateAutoFocus().
int TimeTextCtrl::mDigitW [private]
Referenced by Layout(), and OnPaint().
int TimeTextCtrl::mFocusedDigit [private]
Referenced by Decrease(), Decrement(), GetFocusedDigit(), Increase(), Increment(), OnKeyDown(), OnMouse(), OnPaint(), SetFieldFocus(), UpdateAutoFocus(), and Updated().
wxString TimeTextCtrl::mFormatString [private]
Referenced by GetFormatIndex(), GetFormatString(), OnContext(), SetFormatString(), SetSampleRate(), and TimeTextCtrl().
int TimeTextCtrl::mHeight [private]
Referenced by Fit(), Layout(), and OnPaint().
wxFont* TimeTextCtrl::mLabelFont [private]
Referenced by Layout(), and ~TimeTextCtrl().
int TimeTextCtrl::mLastField [private]
Referenced by GetFocusedField(), and SetFieldFocus().
bool TimeTextCtrl::mMenuEnabled [private]
Referenced by EnableMenu(), Layout(), OnContext(), OnMenu(), OnMouse(), and TimeTextCtrl().
double TimeTextCtrl::mScrollRemainder [private]
Referenced by OnMouse().
double TimeTextCtrl::mTimeValue [private]
Referenced by ControlsToValue(), Decrease(), GetTimeValue(), Increase(), SetTimeValue(), and ValueToControls().
int TimeTextCtrl::mWidth [private]
Referenced by Fit(), Layout(), OnMouse(), and OnPaint().
The documentation for this class was generated from the following files:
TimeTextCtrl.h
TimeTextCtrl.cpp