Audacity: UndoManager Class Reference
UndoManager Class Reference
Works with HistoryWindow to provide the Undo functionality.
#include <UndoManager.h>
Public Member Functions
UndoManager ()
~UndoManager ()
void PushState (TrackList *l, double sel0, double sel1, wxString longDescription, wxString shortDescription, bool consolidate=false)
void ModifyState (TrackList *l, double sel0, double sel1)
void ClearStates ()
void RemoveStates (int num)
void RemoveStateAt (int n)
unsigned int GetNumStates ()
unsigned int GetCurrentState ()
void GetShortDescription (unsigned int n, wxString *desc)
void GetLongDescription (unsigned int n, wxString *desc, wxString *size)
void SetLongDescription (unsigned int n, wxString desc)
TrackList * SetStateTo (unsigned int n, double *sel0, double *sel1)
TrackList * Undo (double *sel0, double *sel1)
TrackList * Redo (double *sel0, double *sel1)
bool UndoAvailable ()
bool RedoAvailable ()
bool UnsavedChanges ()
void StateSaved ()
void Debug ()
void SetODChangesFlag ()
to mark as unsaved changes without changing the state/tracks.
bool HasODChangesFlag ()
void ResetODChangesFlag ()
Private Member Functions
wxLongLong GetSpaceUsage (int index)
Private Attributes
int current
int saved
UndoStack stack
wxString lastAction
int consolidationCount
bool mODChanges
ODLock mODChangesMutex
Detailed Description
Works with HistoryWindow to provide the Undo functionality.
Constructor & Destructor Documentation
UndoManager::UndoManager ()
References consolidationCount, current, ResetODChangesFlag(), and saved.
UndoManager::~UndoManager ()
References ClearStates().
Member Function Documentation
void UndoManager::ClearStates ()
References RemoveStates(), and stack.
Referenced by AudacityProject::InitialState(), BatchProcessDialog::OnApplyToFiles(), AudacityProject::OnCloseWindow(), and ~UndoManager().
void UndoManager::Debug ()
References current, TrackListIterator::First(), WaveTrack::GetEndTime(), WaveTrack::GetStartTime(), and stack.
unsigned int UndoManager::GetCurrentState ()
References current.
Referenced by BatchCommands::ApplyChain(), HistoryWindow::DoUpdate(), and AudacityProject::ModifyUndoMenus().
void UndoManager::GetLongDescription (unsigned int n, wxString * desc, wxString * size)
References Internat::FormatSize(), GetSpaceUsage(), and stack.
Referenced by HistoryWindow::DoUpdate().
unsigned int UndoManager::GetNumStates ()
References stack.
Referenced by HistoryWindow::DoUpdate().
void UndoManager::GetShortDescription (unsigned int n, wxString * desc)
References stack.
Referenced by AudacityProject::ModifyUndoMenus().
wxLongLong UndoManager::GetSpaceUsage (int index) [private]
References TrackListCondIterator::First(), WaveTrack::GetClipIterator(), TrackListCondIterator::Next(), stack, and Track::Wave.
Referenced by GetLongDescription().
bool UndoManager::HasODChangesFlag ()
References mODChanges, and mODChangesMutex.
Referenced by UnsavedChanges().
void UndoManager::ModifyState (TrackList * l, double sel0, double sel1)
References TrackList::Add(), current, Track::Duplicate(), TrackListIterator::First(), TrackListIterator::Next(), and stack.
Referenced by AudacityProject::ModifyState(), and PushState().
void UndoManager::PushState (TrackList * l, double sel0, double sel1, wxString longDescription, wxString shortDescription, bool consolidate = false)
References TrackList::Add(), consolidationCount, current, UndoStackElem::description, Track::Duplicate(), TrackListIterator::First(), lastAction, ModifyState(), TrackListIterator::Next(), RemoveStateAt(), saved, UndoStackElem::sel0, UndoStackElem::sel1, UndoStackElem::shortDescription, stack, and UndoStackElem::tracks.
Referenced by AudacityProject::InitialState(), and AudacityProject::PushState().
TrackList * UndoManager::Redo (double * sel0, double * sel1)
References consolidationCount, current, lastAction, RedoAvailable(), and stack.
Referenced by AudacityProject::OnRedo().
bool UndoManager::RedoAvailable ()
References current, and stack.
Referenced by EditToolBar::EnableDisableButtons(), AudacityProject::GetUpdateFlags(), AudacityProject::ModifyUndoMenus(), AudacityProject::OnRedo(), and Redo().
void UndoManager::RemoveStateAt (int n)
References stack.
Referenced by PushState(), and RemoveStates().
void UndoManager::RemoveStates (int num)
References current, RemoveStateAt(), and saved.
Referenced by ClearStates(), and HistoryWindow::OnDiscard().
void UndoManager::ResetODChangesFlag ()
References mODChanges, and mODChangesMutex.
Referenced by StateSaved(), and UndoManager().
void UndoManager::SetLongDescription (unsigned int n, wxString desc)
References stack.
void UndoManager::SetODChangesFlag ()
to mark as unsaved changes without changing the state/tracks.
References mODChanges, and mODChangesMutex.
TrackList * UndoManager::SetStateTo (unsigned int n, double * sel0, double * sel1)
References consolidationCount, current, lastAction, and stack.
Referenced by AudacityProject::SetStateTo().
void UndoManager::StateSaved ()
References current, ResetODChangesFlag(), and saved.
Referenced by AudacityProject::InitialState(), and AudacityProject::Save().
TrackList * UndoManager::Undo (double * sel0, double * sel1)
References consolidationCount, current, lastAction, stack, and UndoAvailable().
Referenced by AudacityProject::OnUndo().
bool UndoManager::UndoAvailable ()
References current.
Referenced by EditToolBar::EnableDisableButtons(), AudacityProject::GetUpdateFlags(), AudacityProject::ModifyUndoMenus(), AudacityProject::OnUndo(), and Undo().
bool UndoManager::UnsavedChanges ()
References current, HasODChangesFlag(), and saved.
Referenced by AudacityProject::GetUpdateFlags(), AudacityProject::OnCloseWindow(), and AudacityProject::Save().
Member Data Documentation
int UndoManager::consolidationCount [private]
Referenced by PushState(), Redo(), SetStateTo(), Undo(), and UndoManager().
int UndoManager::current [private]
Referenced by Debug(), GetCurrentState(), ModifyState(), PushState(), Redo(), RedoAvailable(), RemoveStates(), SetStateTo(), StateSaved(), Undo(), UndoAvailable(), UndoManager(), and UnsavedChanges().
wxString UndoManager::lastAction [private]
Referenced by PushState(), Redo(), SetStateTo(), and Undo().
bool UndoManager::mODChanges [private]
Referenced by HasODChangesFlag(), ResetODChangesFlag(), and SetODChangesFlag().
ODLock UndoManager::mODChangesMutex [private]
Referenced by HasODChangesFlag(), ResetODChangesFlag(), and SetODChangesFlag().
int UndoManager::saved [private]
Referenced by PushState(), RemoveStates(), StateSaved(), UndoManager(), and UnsavedChanges().
UndoStack UndoManager::stack [private]
Referenced by ClearStates(), Debug(), GetLongDescription(), GetNumStates(), GetShortDescription(), GetSpaceUsage(), ModifyState(), PushState(), Redo(), RedoAvailable(), RemoveStateAt(), SetLongDescription(), SetStateTo(), and Undo().
The documentation for this class was generated from the following files:
UndoManager.h
UndoManager.cpp