Audacity: WahwahDialog Class Reference
WahwahDialog Class Reference
Dialog for EffectWahwah.
#include <Wahwah.h>
Public Member Functions
WahwahDialog (EffectWahwah *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
wxSlider * GetResonanceSlider ()
wxSlider * GetDepthSlider ()
wxSlider * GetPhaseSlider ()
wxSlider * GetFreqSlider ()
wxSlider * GetFreqOffSlider ()
wxTextCtrl * GetResonanceText ()
wxTextCtrl * GetDepthText ()
wxTextCtrl * GetPhaseText ()
wxTextCtrl * GetFreqText ()
wxTextCtrl * GetFreqOffText ()
Public Attributes
float freq
float freqoff
float startphase
float res
float depth
Private Member Functions
void OnResonanceSlider (wxCommandEvent &event)
void OnDepthSlider (wxCommandEvent &event)
void OnPhaseSlider (wxCommandEvent &event)
void OnFreqSlider (wxCommandEvent &event)
void OnFreqOffSlider (wxCommandEvent &event)
void OnResonanceText (wxCommandEvent &event)
void OnDepthText (wxCommandEvent &event)
void OnPhaseText (wxCommandEvent &event)
void OnFreqText (wxCommandEvent &event)
void OnFreqOffText (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
Private Attributes
EffectWahwah * mEffect
Detailed Description
Dialog for EffectWahwah.
Constructor & Destructor Documentation
WahwahDialog::WahwahDialog (EffectWahwah * effect, wxWindow * parent)
Member Function Documentation
wxSlider* WahwahDialog::GetDepthSlider () [inline]
Referenced by OnDepthSlider(), OnDepthText(), and TransferDataToWindow().
wxTextCtrl* WahwahDialog::GetDepthText () [inline]
References ID_DEPTHTEXT.
Referenced by OnDepthSlider(), OnDepthText(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* WahwahDialog::GetFreqOffSlider () [inline]
References ID_FREQOFFSLIDER.
Referenced by OnFreqOffSlider(), OnFreqOffText(), and TransferDataToWindow().
wxTextCtrl* WahwahDialog::GetFreqOffText () [inline]
References ID_FREQOFFTEXT.
Referenced by OnFreqOffSlider(), OnFreqOffText(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* WahwahDialog::GetFreqSlider () [inline]
References ID_FREQSLIDER.
Referenced by OnFreqSlider(), OnFreqText(), and TransferDataToWindow().
wxTextCtrl* WahwahDialog::GetFreqText () [inline]
References ID_FREQTEXT.
Referenced by OnFreqSlider(), OnFreqText(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* WahwahDialog::GetPhaseSlider () [inline]
References ID_PHASESLIDER.
Referenced by OnPhaseSlider(), OnPhaseText(), and TransferDataToWindow().
wxTextCtrl* WahwahDialog::GetPhaseText () [inline]
References ID_PHASETEXT.
Referenced by OnPhaseSlider(), OnPhaseText(), TransferDataFromWindow(), and TransferDataToWindow().
wxSlider* WahwahDialog::GetResonanceSlider () [inline]
References ID_RESONANCESLIDER.
Referenced by OnResonanceSlider(), OnResonanceText(), and TransferDataToWindow().
wxTextCtrl* WahwahDialog::GetResonanceText () [inline]
References ID_RESONANCETEXT.
Referenced by OnResonanceSlider(), OnResonanceText(), TransferDataFromWindow(), and TransferDataToWindow().
void WahwahDialog::OnDepthSlider (wxCommandEvent & event) [private]
References depth, GetDepthSlider(), and GetDepthText().
void WahwahDialog::OnDepthText (wxCommandEvent & event) [private]
References depth, DEPTH_MAX, DEPTH_MIN, GetDepthSlider(), GetDepthText(), and TrapLong().
void WahwahDialog::OnFreqOffSlider (wxCommandEvent & event) [private]
References freqoff, GetFreqOffSlider(), and GetFreqOffText().
void WahwahDialog::OnFreqOffText (wxCommandEvent & event) [private]
References freqoff, FREQOFF_MAX, FREQOFF_MIN, GetFreqOffSlider(), GetFreqOffText(), and TrapDouble().
void WahwahDialog::OnFreqSlider (wxCommandEvent & event) [private]
References GetFreqSlider(), and GetFreqText().
void WahwahDialog::OnFreqText (wxCommandEvent & event) [private]
References freq, FREQ_MAX, FREQ_MIN, GetFreqSlider(), GetFreqText(), and TrapLong().
void WahwahDialog::OnPhaseSlider (wxCommandEvent & event) [private]
References GetPhaseSlider(), and GetPhaseText().
void WahwahDialog::OnPhaseText (wxCommandEvent & event) [private]
References GetPhaseSlider(), GetPhaseText(), PHASE_MAX, PHASE_MIN, and TrapLong().
void WahwahDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References depth, EffectWahwah::depth, freq, EffectWahwah::freq, freqoff, EffectWahwah::freqofs, M_PI, mEffect, Effect::Preview(), res, EffectWahwah::res, startphase, EffectWahwah::startphase, and TransferDataFromWindow().
void WahwahDialog::OnResonanceSlider (wxCommandEvent & event) [private]
References GetResonanceSlider(), GetResonanceText(), and res.
void WahwahDialog::OnResonanceText (wxCommandEvent & event) [private]
References GetResonanceSlider(), GetResonanceText(), res, RES_MAX, RES_MIN, and TrapDouble().
void WahwahDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddSlider(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), DEPTH_MAX, DEPTH_MIN, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), FREQ_MAX, FREQ_MIN, FREQOFF_MAX, FREQOFF_MIN, ShuttleGui::Id(), ID_DEPTHSLIDER, ID_DEPTHTEXT, ID_FREQOFFSLIDER, ID_FREQOFFTEXT, ID_FREQSLIDER, ID_FREQTEXT, ID_PHASESLIDER, ID_PHASETEXT, ID_RESONANCESLIDER, ID_RESONANCETEXT, PHASE_MAX, PHASE_MIN, RES_MAX, RES_MIN, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartMultiColumn().
bool WahwahDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References depth, DEPTH_MAX, DEPTH_MIN, freq, FREQ_MAX, FREQ_MIN, freqoff, FREQOFF_MAX, FREQOFF_MIN, GetDepthText(), GetFreqOffText(), GetFreqText(), GetPhaseText(), GetResonanceText(), PHASE_MAX, PHASE_MIN, res, RES_MAX, RES_MIN, startphase, TrapDouble(), and TrapLong().
Referenced by OnPreview().
bool WahwahDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References depth, freq, freqoff, GetDepthSlider(), GetDepthText(), GetFreqOffSlider(), GetFreqOffText(), GetFreqSlider(), GetFreqText(), GetPhaseSlider(), GetPhaseText(), GetResonanceSlider(), GetResonanceText(), res, and startphase.
Referenced by EffectWahwah::PromptUser().
Member Data Documentation
float WahwahDialog::depth
Referenced by OnDepthSlider(), OnDepthText(), OnPreview(), EffectWahwah::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
float WahwahDialog::freq
Referenced by OnFreqText(), OnPreview(), EffectWahwah::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
float WahwahDialog::freqoff
Referenced by OnFreqOffSlider(), OnFreqOffText(), OnPreview(), EffectWahwah::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
EffectWahwah* WahwahDialog::mEffect [private]
Referenced by OnPreview().
float WahwahDialog::res
Referenced by OnPreview(), OnResonanceSlider(), OnResonanceText(), EffectWahwah::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
float WahwahDialog::startphase
Referenced by OnPreview(), EffectWahwah::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
Wahwah.h
Wahwah.cpp