Audacity: AliasBlockFile Class Reference
AliasBlockFile Class Reference
A BlockFile that refers to data in an existing file.
#include <BlockFile.h>
Public Member Functions
AliasBlockFile (wxFileName baseFileName, wxFileName aliasedFileName, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel)
Constructs an AliasBlockFile.
AliasBlockFile (wxFileName existingSummaryFile, wxFileName aliasedFileName, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, float min, float max, float RMS)
virtual ~AliasBlockFile ()
virtual int ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len)=0
Retrieves audio data from the aliased file.
virtual wxLongLong GetSpaceUsage ()
void SilenceAliasLog ()
as SilentLog (which would affect Summary data access), but
wxFileName GetAliasedFile ()
Gets the name of the aliased file.
void ChangeAliasedFile (wxFileName newAliasedFile)
Modifies the name of the aliased file.
bool IsAlias ()
Returns TRUE if this is an AliasBlockFile.
Protected Member Functions
virtual void WriteSummary ()
Write the summary to disk, using the derived ReadData() to get the data.
virtual bool ReadSummary (void *data)
Read the summary into a buffer.
Protected Attributes
wxFileName mAliasedFileName
sampleCount mAliasStart
int mAliasChannel
bool mSilentAliasLog
Detailed Description
A BlockFile that refers to data in an existing file.
An AliasBlockFile references an existing disk file for its storage instead of copying the data. It still writes a file to disk, but only stores summary data in it.
This is a common base class for all alias block files. It handles reading and writing summary data, leaving very little for derived classes to need to implement.
Constructor & Destructor Documentation
AliasBlockFile::AliasBlockFile (wxFileName baseFileName, wxFileName aliasedFileName, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel)
Constructs an AliasBlockFile.
Constructs an AliasBlockFile based on the given information about the aliased file.
Note that derived classes /must/ call AliasBlockFile::WriteSummary() in their constructors for the summary file to be correctly written to disk.
Parameters:
baseFileName The name of the summary file to be written, but without an extension. This constructor will add the appropriate extension before passing it to BlockFile::BlockFile
aliasedFileName The name of the file where the audio data for this block actually exists.
aliasStart The offset in the aliased file where this block's data begins
aliasLen The length of this block's data in the aliased file.
aliasChannel The channel where this block's data is located in the aliased file
References mSilentAliasLog.
AliasBlockFile::AliasBlockFile (wxFileName existingSummaryFile, wxFileName aliasedFileName, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, float min, float max, float RMS)
References BlockFile::mMax, BlockFile::mMin, BlockFile::mRMS, and mSilentAliasLog.
AliasBlockFile::~AliasBlockFile () [virtual]
Member Function Documentation
void AliasBlockFile::ChangeAliasedFile (wxFileName newAliasedFile)
Modifies the name of the aliased file.
Modify this block to point at a different file. This is generally looked down on, but it is necessary in one case: see DirManager::EnsureSafeFilename().
References mAliasedFileName.
Referenced by DirManager::EnsureSafeFilename(), and DirManager::ProjectFSCK().
wxFileName AliasBlockFile::GetAliasedFile ()
Gets the name of the aliased file.
Get the name of the file where the audio data for this block is stored.
References mAliasedFileName.
Referenced by DirManager::EnsureSafeFilename(), FindDependencies(), and RemoveDependencies().
wxLongLong AliasBlockFile::GetSpaceUsage () [virtual]
Implements BlockFile.
Reimplemented in ODPCMAliasBlockFile.
References BlockFile::mFileName.
bool AliasBlockFile::IsAlias () [inline, virtual]
Returns TRUE if this is an AliasBlockFile.
Reimplemented from BlockFile.
virtual int AliasBlockFile::ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len) [pure virtual]
Retrieves audio data from the aliased file.
Implements BlockFile.
Implemented in ODPCMAliasBlockFile, and PCMAliasBlockFile.
Referenced by WriteSummary().
bool AliasBlockFile::ReadSummary (void * data) [protected, virtual]
Read the summary into a buffer.
Read the summary of this alias block from disk. Since the audio data is elsewhere, this consists of reading the entire summary file.
Parameters:
*data The buffer where the summary data will be stored. It must be at least mSummaryInfo.totalSummaryBytes long.
Implements BlockFile.
Reimplemented in ODPCMAliasBlockFile.
References BlockFile::FixSummary(), BlockFile::mFileName, BlockFile::mSilentLog, BlockFile::mSummaryInfo, and SummaryInfo::totalSummaryBytes.
void AliasBlockFile::SilenceAliasLog () [inline]
as SilentLog (which would affect Summary data access), but
References mSilentAliasLog.
Referenced by DirManager::ProjectFSCK().
void AliasBlockFile::WriteSummary () [protected, virtual]
Write the summary to disk, using the derived ReadData() to get the data.
Write the summary to disk. Derived classes must call this method from their constructors for the summary to be correctly written. It uses the derived class's ReadData() to retrieve the data to summarize.
Reimplemented in ODPCMAliasBlockFile.
References BlockFile::CalcSummary(), DeleteSamples(), floatSample, BlockFile::mFileName, BlockFile::mLen, BlockFile::mSummaryInfo, NewSamples(), ReadData(), and SummaryInfo::totalSummaryBytes.
Referenced by PCMAliasBlockFile::PCMAliasBlockFile(), PCMAliasBlockFile::Recover(), and LegacyAliasBlockFile::Recover().
Member Data Documentation
int AliasBlockFile::mAliasChannel [protected]
Referenced by PCMAliasBlockFile::Copy(), ODPCMAliasBlockFile::Copy(), LegacyAliasBlockFile::Copy(), PCMAliasBlockFile::ReadData(), ODPCMAliasBlockFile::ReadData(), PCMAliasBlockFile::SaveXML(), ODPCMAliasBlockFile::SaveXML(), and LegacyAliasBlockFile::SaveXML().
wxFileName AliasBlockFile::mAliasedFileName [protected]
Referenced by ChangeAliasedFile(), PCMAliasBlockFile::Copy(), ODPCMAliasBlockFile::Copy(), LegacyAliasBlockFile::Copy(), GetAliasedFile(), PCMAliasBlockFile::ReadData(), ODPCMAliasBlockFile::ReadData(), PCMAliasBlockFile::SaveXML(), ODPCMAliasBlockFile::SaveXML(), and LegacyAliasBlockFile::SaveXML().
sampleCount AliasBlockFile::mAliasStart [protected]
Referenced by PCMAliasBlockFile::Copy(), ODPCMAliasBlockFile::Copy(), LegacyAliasBlockFile::Copy(), PCMAliasBlockFile::ReadData(), ODPCMAliasBlockFile::ReadData(), PCMAliasBlockFile::SaveXML(), ODPCMAliasBlockFile::SaveXML(), and LegacyAliasBlockFile::SaveXML().
bool AliasBlockFile::mSilentAliasLog [protected]
Referenced by AliasBlockFile(), PCMAliasBlockFile::ReadData(), ODPCMAliasBlockFile::ReadData(), and SilenceAliasLog().
The documentation for this class was generated from the following files:
BlockFile.h
BlockFile.cpp