Audacity: ExportMP3Options Class Reference
ExportMP3Options Class Reference
Public Member Functions
ExportMP3Options (wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
void OnOK (wxCommandEvent &event)
void OnSET (wxCommandEvent &evt)
void OnVBR (wxCommandEvent &evt)
void OnABR (wxCommandEvent &evt)
void OnCBR (wxCommandEvent &evt)
void LoadNames (CHOICES *choices, int count)
wxArrayString GetNames (CHOICES *choices, int count)
wxArrayInt GetLabels (CHOICES *choices, int count)
Private Attributes
wxRadioButton * mStereo
wxRadioButton * mJoint
wxRadioButton * mSET
wxRadioButton * mVBR
wxRadioButton * mABR
wxRadioButton * mCBR
wxChoice * mRate
wxChoice * mMode
Constructor & Destructor Documentation
ExportMP3Options::ExportMP3Options (wxWindow * parent)
References eIsCreatingFromPrefs, and InitMP3_Statics().
Member Function Documentation
wxArrayInt ExportMP3Options::GetLabels (CHOICES * choices, int count)
References label.
Referenced by PopulateOrExchange().
wxArrayString ExportMP3Options::GetNames (CHOICES * choices, int count)
References name, and names.
Referenced by PopulateOrExchange().
void ExportMP3Options::LoadNames (CHOICES * choices, int count)
References mRate, and name.
Referenced by OnABR(), OnCBR(), OnSET(), and OnVBR().
void ExportMP3Options::OnABR (wxCommandEvent & evt)
References LoadNames(), mJoint, mMode, mRate, and mStereo.
void ExportMP3Options::OnCBR (wxCommandEvent & evt)
References LoadNames(), mJoint, mMode, mRate, and mStereo.
void ExportMP3Options::OnOK (wxCommandEvent & event)
References eIsSavingToPrefs, and PopulateOrExchange().
void ExportMP3Options::OnSET (wxCommandEvent & evt)
References LoadNames(), mJoint, mMode, mRate, and mStereo.
void ExportMP3Options::OnVBR (wxCommandEvent & evt)
References LoadNames(), mJoint, mMode, mRate, and mStereo.
void ExportMP3Options::PopulateOrExchange (ShuttleGui & S)
References ShuttleGuiBase::AddPrompt(), ShuttleGui::AddStandardButtons(), CHANNEL_JOINT, CHANNEL_STEREO, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndRadioButtonGroup(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndTwoColumn(), GetLabels(), GetNames(), ShuttleGui::Id(), ID_ABR, ID_CBR, ID_SET, ID_VBR, mABR, mCBR, mJoint, mMode, MODE_ABR, MODE_CBR, MODE_SET, MODE_VBR, mRate, mSET, mStereo, mVBR, PRESET_STANDARD, QUALITY_4, ROUTINE_FAST, ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartRadioButtonGroup(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartTwoColumn(), ShuttleGuiBase::TieChoice(), and ShuttleGuiBase::TieRadioButton().
Referenced by OnOK().
Member Data Documentation
wxRadioButton* ExportMP3Options::mABR [private]
Referenced by PopulateOrExchange().
wxRadioButton* ExportMP3Options::mCBR [private]
Referenced by PopulateOrExchange().
wxRadioButton* ExportMP3Options::mJoint [private]
Referenced by OnABR(), OnCBR(), OnSET(), OnVBR(), and PopulateOrExchange().
wxChoice* ExportMP3Options::mMode [private]
Referenced by OnABR(), OnCBR(), OnSET(), OnVBR(), and PopulateOrExchange().
wxChoice* ExportMP3Options::mRate [private]
Referenced by LoadNames(), OnABR(), OnCBR(), OnSET(), OnVBR(), and PopulateOrExchange().
wxRadioButton* ExportMP3Options::mSET [private]
Referenced by PopulateOrExchange().
wxRadioButton* ExportMP3Options::mStereo [private]
Referenced by OnABR(), OnCBR(), OnSET(), OnVBR(), and PopulateOrExchange().
wxRadioButton* ExportMP3Options::mVBR [private]
Referenced by PopulateOrExchange().
The documentation for this class was generated from the following file:
ExportMP3.cpp