Audacity: EffectChangeLength Class Reference
EffectChangeLength Class Reference
An Effect.
#include <ChangeLength.h>
Public Member Functions
EffectChangeLength ()
virtual wxString GetEffectName ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool Init ()
virtual void End ()
virtual bool CheckWhetherSkipEffect ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Process ()
Private Attributes
WaveTrack * mTrack
double mFromLength
double mToLength
Friends
class ChangeLengthDialog
Detailed Description
An Effect.
Constructor & Destructor Documentation
EffectChangeLength::EffectChangeLength ()
References Init().
Member Function Documentation
bool EffectChangeLength::CheckWhetherSkipEffect () [virtual]
Reimplemented from Effect.
void EffectChangeLength::End () [virtual]
Reimplemented from Effect.
virtual wxString EffectChangeLength::GetEffectAction () [inline, virtual]
Implements Effect.
virtual wxString EffectChangeLength::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectChangeLength::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectChangeLength::Init () [virtual]
Reimplemented from Effect.
References gPrefs, mFromLength, Effect::mT0, Effect::mT1, and mToLength.
Referenced by EffectChangeLength().
bool EffectChangeLength::Process () [virtual]
Implements Effect.
References TrackListCondIterator::First(), mTrack, Effect::mTracks, and Track::Wave.
bool EffectChangeLength::PromptUser () [virtual]
Reimplemented from Effect.
References gPrefs, mFromLength, ChangeLengthDialog::mFromLength, Effect::mParent, mToLength, ChangeLengthDialog::mToLength, and ChangeLengthDialog::TransferDataToWindow().
bool EffectChangeLength::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
Friends And Related Function Documentation
friend class ChangeLengthDialog [friend]
Member Data Documentation
double EffectChangeLength::mFromLength [private]
Referenced by Init(), and PromptUser().
double EffectChangeLength::mToLength [private]
Referenced by Init(), and PromptUser().
WaveTrack* EffectChangeLength::mTrack [private]
Referenced by Process().
The documentation for this class was generated from the following files:
ChangeLength.h
ChangeLength.cpp