Audacity: XMLFileWriterException Class Reference
XMLFileWriterException Class Reference
#include <XMLWriter.h>
Public Member Functions
XMLFileWriterException (const wxString &message)
wxString GetMessage () const
Protected Attributes
wxString mMessage
Detailed Description
Exception thrown by various XMLFileWriter methods
Constructor & Destructor Documentation
XMLFileWriterException::XMLFileWriterException (const wxString & message) [inline]
References mMessage.
Member Function Documentation
wxString XMLFileWriterException::GetMessage () const [inline]
References mMessage.
Referenced by AudacityProject::AutoSave(), TagsEditor::OnSave(), AudacityProject::Save(), and EqualizationDialog::SaveCurves().
Member Data Documentation
wxString XMLFileWriterException::mMessage [protected]
Referenced by GetMessage(), and XMLFileWriterException().
The documentation for this class was generated from the following file:
XMLWriter.h