Audacity: Ruler Class Reference
Ruler Class Reference
Used to display a Ruler.
#include <Ruler.h>
Classes
class Label
An array of these created by the Ruler is used to determine what and where text annotations to the numbers on the Ruler get drawn.
Public Types
enum RulerFormat {
IntFormat, RealFormat, RealLogFormat, TimeFormat,
LinearDBFormat
}
Public Member Functions
Ruler ()
~Ruler ()
void SetBounds (int left, int top, int right, int bottom)
void SetOrientation (int orient)
void SetRange (double min, double max)
void SetFormat (RulerFormat format)
void SetUnits (wxString units)
void SetLog (bool log)
void SetSpacing (int spacing)
void SetLabelEdges (bool labelEdges)
void SetFlip (bool flip)
void SetMinor (bool value)
void SetFonts (const wxFont &minorFont, const wxFont &majorFont, const wxFont &minorMinorFont)
void OfflimitsPixels (int start, int end)
void GetMaxSize (wxCoord *width, wxCoord *height)
void SetCustomMode (bool value)
void SetCustomMajorLabels (wxArrayString *label, int numLabel, int start, int step)
void SetCustomMinorLabels (wxArrayString *label, int numLabel, int start, int step)
void Draw (wxDC &dc)
void Draw (wxDC &dc, Envelope *speedEnv, long minSpeed, long maxSpeed)
void DrawGrid (wxDC &dc, int length, bool minor=true, bool major=true, int xOffset=0, int yOffset=0)
void SetTickColour (const wxColour &colour)
int GetZeroPosition ()
Public Attributes
bool mbTicksOnly
bool mbTicksAtExtremes
wxRect mRect
Private Member Functions
void Invalidate ()
void Update ()
void Update (Envelope *speedEnv, long minSpeed, long maxSpeed)
void FindTickSizes ()
void FindLinearTickSizes (double UPP)
wxString LabelString (double d, bool major)
void Tick (int pos, double d, bool major, bool minor)
void TickCustom (int labelIdx, bool major, bool minor)
int FindZero (Label *label, int len)
Private Attributes
wxColour mTickColour
wxPen mPen
int mMaxWidth
int mMaxHeight
int mLeft
int mTop
int mRight
int mBottom
int mLead
int mLength
int mLengthOld
wxDC * mDC
wxFont * mMinorFont
wxFont * mMajorFont
wxFont * mMinorMinorFont
bool mUserFonts
double mMin
double mMax
double mMajor
double mMinor
int mDigits
int * mUserBits
int * mBits
int mUserBitLen
bool mValid
int mNumMajor
Label * mMajorLabels
int mNumMinor
Label * mMinorLabels
int mNumMinorMinor
Label * mMinorMinorLabels
int mOrientation
int mSpacing
bool mHasSetSpacing
bool mLabelEdges
RulerFormat mFormat
bool mLog
bool mFlip
bool mCustom
bool mbMinor
bool mMajorGrid
bool mMinorGrid
int mGridLineLength
wxString mUnits
Detailed Description
Used to display a Ruler.
This is a generic class which can be used to display just about any kind of ruler.
At a minimum, the user must specify the dimensions of the ruler, its orientation (horizontal or vertical), and the values displayed at the two ends of the ruler (min and max). By default, this class will display tick marks at reasonable round numbers and fractions, for example, 100, 50, 10, 5, 1, 0.5, 0.1, etc.
The class is designed to display a small handful of labeled Major ticks, and a few Minor ticks between each of these. Minor ticks are labeled if there is enough space. Labels will never run into each other.
In addition to Real numbers, the Ruler currently supports two other formats for its display:
Integer - never shows tick marks for fractions of an integer
Time - Assumes values represent seconds, and labels the tick marks in "HH:MM:SS" format, e.g. 4000 seconds becomes "1:06:40", for example. Will display fractions of a second, and tick marks are all reasonable round numbers for time (i.e. 15 seconds, 30 seconds, etc.)
Member Enumeration Documentation
enum Ruler::RulerFormat
Enumerator:
IntFormat
RealFormat
RealLogFormat
TimeFormat
LinearDBFormat
Constructor & Destructor Documentation
Ruler::Ruler ()
References mBits, mbMinor, mBottom, mbTicksAtExtremes, mbTicksOnly, mCustom, mFlip, mFormat, mGridLineLength, mHasSetSpacing, mLabelEdges, mLeft, mLength, mLengthOld, mLog, mMajorFont, mMajorGrid, mMajorLabels, mMax, mMin, mMinorFont, mMinorGrid, mMinorLabels, mMinorMinorFont, mMinorMinorLabels, mOrientation, mPen, mRight, mSpacing, mTickColour, mTop, mUnits, mUserBitLen, mUserBits, mUserFonts, mValid, and RealFormat.
Ruler::~Ruler ()
References Invalidate(), mMajorFont, mMajorLabels, mMinorFont, mMinorLabels, mMinorMinorFont, mMinorMinorLabels, and mUserBits.
Member Function Documentation
void Ruler::Draw (wxDC & dc, Envelope * speedEnv, long minSpeed, long maxSpeed)
References mbMinor, mBottom, mbTicksAtExtremes, mbTicksOnly, mDC, mFlip, mLeft, mLength, mMajorFont, mMajorLabels, mMinorFont, mMinorLabels, mMinorMinorFont, mMinorMinorLabels, mNumMajor, mNumMinor, mNumMinorMinor, mOrientation, mPen, mRight, mTickColour, mTop, mValid, Ruler::Label::pos, and Update().
void Ruler::Draw (wxDC & dc)
Referenced by AdornedRulerPanel::DoDrawMarks(), TimeTrack::Draw(), TrackArtist::DrawVRuler(), Meter::HandlePaint(), RulerPanel::OnPaint(), CompressorPanel::OnPaint(), and AudacityPrintout::OnPrintPage().
void Ruler::DrawGrid (wxDC & dc, int length, bool minor = true, bool major = true, int xOffset = 0, int yOffset = 0)
References GetZeroPosition(), mbMinor, mDC, mGridLineLength, mMajorGrid, mMajorLabels, mMinorGrid, mMinorLabels, mNumMajor, mNumMinor, mOrientation, Ruler::Label::pos, and Update().
Referenced by FreqWindow::DrawPlot(), and EqualizationPanel::OnPaint().
void Ruler::FindLinearTickSizes (double UPP) [private]
References IntFormat, LinearDBFormat, mDigits, mFormat, mMajor, mMinor, RealFormat, RealLogFormat, and TimeFormat.
Referenced by Update().
void Ruler::FindTickSizes () [private]
int Ruler::FindZero (Label * label, int len) [private]
References Ruler::Label::text.
Referenced by GetZeroPosition().
void Ruler::GetMaxSize (wxCoord * width, wxCoord * height)
References mDC, mRect, mValid, and Update().
Referenced by FreqWindow::DrawPlot(), AdornedRulerPanel::GetMaxSize(), EqualizationDialog::MakeEqualizationDialog(), CompressorPanel::OnPaint(), EqualizationDialog::TransferDataFromWindow(), and TrackArtist::UpdateVRuler().
int Ruler::GetZeroPosition ()
References FindZero(), mMajorLabels, mMinorLabels, mNumMajor, and mNumMinor.
Referenced by DrawGrid().
void Ruler::Invalidate () [private]
References mBits, mBottom, mLeft, mLength, mOrientation, mRight, mTop, mUserBitLen, mUserBits, and mValid.
Referenced by SetBounds(), SetFlip(), SetFonts(), SetFormat(), SetLabelEdges(), SetLog(), SetOrientation(), SetRange(), SetSpacing(), SetUnits(), and ~Ruler().
wxString Ruler::LabelString (double d, bool major) [private]
References IntFormat, LinearDBFormat, mDigits, mFormat, mMinor, mUnits, RealFormat, RealLogFormat, and TimeFormat.
Referenced by Tick().
void Ruler::OfflimitsPixels (int start, int end)
References mBottom, mLeft, mLength, mOrientation, mRight, mTop, mUserBitLen, and mUserBits.
Referenced by Meter::HandleLayout().
void Ruler::SetBounds (int left, int top, int right, int bottom)
References Invalidate(), mBottom, mLeft, mRight, and mTop.
Referenced by ShuttleGui::AddRulerVertical(), RulerPanel::DoSetSize(), TimeTrack::Draw(), Meter::HandleLayout(), EqualizationDialog::MakeEqualizationDialog(), CompressorPanel::OnPaint(), AudacityPrintout::OnPrintPage(), AdornedRulerPanel::OnSize(), and TrackArtist::UpdateVRuler().
void Ruler::SetCustomMajorLabels (wxArrayString * label, int numLabel, int start, int step)
References mMajorLabels, mNumMajor, Ruler::Label::pos, and Ruler::Label::text.
void Ruler::SetCustomMinorLabels (wxArrayString * label, int numLabel, int start, int step)
References mMinorLabels, mNumMinor, Ruler::Label::pos, and Ruler::Label::text.
void Ruler::SetCustomMode (bool value)
References mCustom.
void Ruler::SetFlip (bool flip)
References Invalidate(), and mFlip.
Referenced by TimeTrack::Draw(), Meter::HandleLayout(), EqualizationDialog::MakeEqualizationDialog(), and CompressorPanel::OnPaint().
void Ruler::SetFonts (const wxFont & minorFont, const wxFont & majorFont, const wxFont & minorMinorFont)
References Invalidate(), mMajorFont, mMinorFont, mMinorMinorFont, and mUserFonts.
void Ruler::SetFormat (RulerFormat format)
References Invalidate(), and mFormat.
Referenced by ShuttleGui::AddRulerVertical(), FreqWindow::DrawPlot(), Meter::HandleLayout(), EqualizationDialog::MakeEqualizationDialog(), CompressorPanel::OnPaint(), AudacityPrintout::OnPrintPage(), TimeTrack::TimeTrack(), and TrackArtist::UpdateVRuler().
void Ruler::SetLabelEdges (bool labelEdges)
References Invalidate(), and mLabelEdges.
Referenced by ShuttleGui::AddRulerVertical(), Meter::HandleLayout(), EqualizationDialog::MakeEqualizationDialog(), AudacityPrintout::OnPrintPage(), TimeTrack::TimeTrack(), and TrackArtist::UpdateVRuler().
void Ruler::SetLog (bool log)
References Invalidate(), and mLog.
Referenced by FreqWindow::DrawPlot(), EqualizationDialog::MakeEqualizationDialog(), EqualizationDialog::OnDrawRadio(), EqualizationDialog::OnLinFreq(), EqualizationDialog::UpdateGraphic(), and TrackArtist::UpdateVRuler().
void Ruler::SetMinor (bool value)
References mbMinor.
void Ruler::SetOrientation (int orient)
References Invalidate(), mHasSetSpacing, mOrientation, and mSpacing.
Referenced by ShuttleGui::AddRulerVertical(), Meter::HandleLayout(), EqualizationDialog::MakeEqualizationDialog(), CompressorPanel::OnPaint(), AudacityPrintout::OnPrintPage(), and TrackArtist::UpdateVRuler().
void Ruler::SetRange (double min, double max)
References Invalidate(), mMax, and mMin.
Referenced by ShuttleGui::AddRulerVertical(), AdornedRulerPanel::DoDrawMarks(), TimeTrack::Draw(), FreqWindow::DrawPlot(), Meter::HandleLayout(), EqualizationDialog::MakeEqualizationDialog(), EqualizationDialog::OnDrawRadio(), EqualizationDialog::OnLinFreq(), CompressorPanel::OnPaint(), AudacityPrintout::OnPrintPage(), EqualizationDialog::TransferDataFromWindow(), EqualizationDialog::UpdateGraphic(), and TrackArtist::UpdateVRuler().
void Ruler::SetSpacing (int spacing)
References Invalidate(), mHasSetSpacing, and mSpacing.
void Ruler::SetTickColour (const wxColour & colour) [inline]
Referenced by AdornedRulerPanel::DoDrawMarks().
void Ruler::SetUnits (wxString units)
References Invalidate(), and mUnits.
Referenced by ShuttleGui::AddRulerVertical(), FreqWindow::DrawPlot(), EqualizationDialog::MakeEqualizationDialog(), CompressorPanel::OnPaint(), and TrackArtist::UpdateVRuler().
void Ruler::Tick (int pos, double d, bool major, bool minor) [private]
References label, LabelString(), Ruler::Label::lx, Ruler::Label::ly, max, mBits, mDC, mFlip, mLead, mLeft, mLength, mMajorFont, mMajorLabels, mMaxHeight, mMaxWidth, mMinorFont, mMinorLabels, mMinorMinorFont, mMinorMinorLabels, mNumMajor, mNumMinor, mNumMinorMinor, mOrientation, mRect, mSpacing, mTop, Ruler::Label::pos, and Ruler::Label::text.
Referenced by Update().
void Ruler::TickCustom (int labelIdx, bool major, bool minor) [private]
References label, Ruler::Label::lx, Ruler::Label::ly, max, mBits, mDC, mFlip, mLead, mLeft, mLength, mMajorFont, mMajorLabels, mMaxHeight, mMaxWidth, mMinorFont, mMinorLabels, mMinorMinorFont, mMinorMinorLabels, mNumMajor, mNumMinor, mOrientation, mRect, mSpacing, mTop, Ruler::Label::pos, and Ruler::Label::text.
Referenced by Update().
void Ruler::Update (Envelope * speedEnv, long minSpeed, long maxSpeed) [private]
References Envelope::Average(), FindLinearTickSizes(), Ruler::Label::lx, Ruler::Label::ly, mBits, mBottom, mCustom, mDC, mDigits, mFlip, mLabelEdges, mLead, mLeft, mLength, mLengthOld, mLog, mMajor, mMajorFont, mMajorLabels, mMax, mMaxHeight, mMaxWidth, mMin, mMinor, mMinorFont, mMinorLabels, mMinorMinorFont, mMinorMinorLabels, mNumMajor, mNumMinor, mNumMinorMinor, mOrientation, mRect, mTop, mUserBits, mUserFonts, mValid, scale(), Tick(), and TickCustom().
void Ruler::Update () [private]
Referenced by Draw(), DrawGrid(), and GetMaxSize().
Member Data Documentation
int* Ruler::mBits [private]
Referenced by Invalidate(), Ruler(), Tick(), TickCustom(), and Update().
bool Ruler::mbMinor [private]
Referenced by Draw(), DrawGrid(), Ruler(), and SetMinor().
int Ruler::mBottom [private]
Referenced by Draw(), Invalidate(), OfflimitsPixels(), Ruler(), SetBounds(), and Update().
bool Ruler::mbTicksAtExtremes
Referenced by Draw(), and Ruler().
bool Ruler::mbTicksOnly
Referenced by Draw(), and Ruler().
bool Ruler::mCustom [private]
Referenced by Ruler(), SetCustomMode(), and Update().
wxDC* Ruler::mDC [private]
Referenced by Draw(), DrawGrid(), GetMaxSize(), Tick(), TickCustom(), and Update().
int Ruler::mDigits [private]
Referenced by FindLinearTickSizes(), LabelString(), and Update().
bool Ruler::mFlip [private]
Referenced by Draw(), Ruler(), SetFlip(), Tick(), TickCustom(), and Update().
RulerFormat Ruler::mFormat [private]
Referenced by FindLinearTickSizes(), LabelString(), Ruler(), and SetFormat().
int Ruler::mGridLineLength [private]
Referenced by DrawGrid(), and Ruler().
bool Ruler::mHasSetSpacing [private]
Referenced by Ruler(), SetOrientation(), and SetSpacing().
bool Ruler::mLabelEdges [private]
Referenced by Ruler(), SetLabelEdges(), and Update().
int Ruler::mLead [private]
Referenced by Tick(), TickCustom(), and Update().
int Ruler::mLeft [private]
Referenced by Draw(), Invalidate(), OfflimitsPixels(), Ruler(), SetBounds(), Tick(), TickCustom(), and Update().
int Ruler::mLength [private]
Referenced by Draw(), Invalidate(), OfflimitsPixels(), Ruler(), Tick(), TickCustom(), and Update().
int Ruler::mLengthOld [private]
Referenced by Ruler(), and Update().
bool Ruler::mLog [private]
Referenced by Ruler(), SetLog(), and Update().
double Ruler::mMajor [private]
Referenced by FindLinearTickSizes(), and Update().
wxFont * Ruler::mMajorFont [private]
Referenced by Draw(), Ruler(), SetFonts(), Tick(), TickCustom(), Update(), and ~Ruler().
bool Ruler::mMajorGrid [private]
Referenced by DrawGrid(), and Ruler().
Label* Ruler::mMajorLabels [private]
Referenced by Draw(), DrawGrid(), GetZeroPosition(), Ruler(), SetCustomMajorLabels(), Tick(), TickCustom(), Update(), and ~Ruler().
double Ruler::mMax [private]
Referenced by Ruler(), SetRange(), and Update().
int Ruler::mMaxHeight [private]
Referenced by Tick(), TickCustom(), and Update().
int Ruler::mMaxWidth [private]
Referenced by Tick(), TickCustom(), and Update().
double Ruler::mMin [private]
Referenced by Ruler(), SetRange(), and Update().
double Ruler::mMinor [private]
Referenced by FindLinearTickSizes(), LabelString(), and Update().
wxFont* Ruler::mMinorFont [private]
Referenced by Draw(), Ruler(), SetFonts(), Tick(), TickCustom(), Update(), and ~Ruler().
bool Ruler::mMinorGrid [private]
Referenced by DrawGrid(), and Ruler().
Label* Ruler::mMinorLabels [private]
Referenced by Draw(), DrawGrid(), GetZeroPosition(), Ruler(), SetCustomMinorLabels(), Tick(), TickCustom(), Update(), and ~Ruler().
wxFont* Ruler::mMinorMinorFont [private]
Referenced by Draw(), Ruler(), SetFonts(), Tick(), TickCustom(), Update(), and ~Ruler().
Label* Ruler::mMinorMinorLabels [private]
Referenced by Draw(), Ruler(), Tick(), TickCustom(), Update(), and ~Ruler().
int Ruler::mNumMajor [private]
Referenced by Draw(), DrawGrid(), GetZeroPosition(), SetCustomMajorLabels(), Tick(), TickCustom(), and Update().
int Ruler::mNumMinor [private]
Referenced by Draw(), DrawGrid(), GetZeroPosition(), SetCustomMinorLabels(), Tick(), TickCustom(), and Update().
int Ruler::mNumMinorMinor [private]
Referenced by Draw(), Tick(), and Update().
int Ruler::mOrientation [private]
Referenced by Draw(), DrawGrid(), Invalidate(), OfflimitsPixels(), Ruler(), SetOrientation(), Tick(), TickCustom(), and Update().
wxPen Ruler::mPen [private]
Referenced by Draw(), and Ruler().
wxRect Ruler::mRect
Referenced by GetMaxSize(), Tick(), TickCustom(), and Update().
int Ruler::mRight [private]
Referenced by Draw(), Invalidate(), OfflimitsPixels(), Ruler(), and SetBounds().
int Ruler::mSpacing [private]
Referenced by Ruler(), SetOrientation(), SetSpacing(), Tick(), and TickCustom().
wxColour Ruler::mTickColour [private]
Referenced by Draw(), and Ruler().
int Ruler::mTop [private]
Referenced by Draw(), Invalidate(), OfflimitsPixels(), Ruler(), SetBounds(), Tick(), TickCustom(), and Update().
wxString Ruler::mUnits [private]
Referenced by LabelString(), Ruler(), and SetUnits().
int Ruler::mUserBitLen [private]
Referenced by Invalidate(), OfflimitsPixels(), and Ruler().
int* Ruler::mUserBits [private]
Referenced by Invalidate(), OfflimitsPixels(), Ruler(), Update(), and ~Ruler().
bool Ruler::mUserFonts [private]
Referenced by Ruler(), SetFonts(), and Update().
bool Ruler::mValid [private]
Referenced by Draw(), GetMaxSize(), Invalidate(), Ruler(), and Update().
The documentation for this class was generated from the following files:
Ruler.h
Ruler.cpp