Audacity: BlockGenerator Class Reference
BlockGenerator Class Reference
#include <Generator.h>
Public Member Functions
BlockGenerator ()
Protected Member Functions
virtual void GenerateBlock (float *data, const WaveTrack &track, sampleCount block)=0
bool GenerateTrack (WaveTrack *tmp, const WaveTrack &track, int ntrack)
Protected Attributes
sampleCount numSamples
Constructor & Destructor Documentation
BlockGenerator::BlockGenerator () [inline]
Member Function Documentation
virtual void BlockGenerator::GenerateBlock (float * data, const WaveTrack & track, sampleCount block) [protected, pure virtual]
Implemented in EffectNoise, and EffectToneGen.
Referenced by GenerateTrack().
bool BlockGenerator::GenerateTrack (WaveTrack * tmp, const WaveTrack & track, int ntrack) [protected, virtual]
Implements Generator.
References WaveTrack::Append(), floatSample, GenerateBlock(), WaveTrack::GetBestBlockSize(), WaveTrack::GetMaxBlockSize(), Generator::mDuration, numSamples, WaveTrack::TimeToLongSamples(), and Effect::TrackProgress().
Member Data Documentation
sampleCount BlockGenerator::numSamples [protected]
Reimplemented in EffectNoise.
Referenced by GenerateTrack(), and EffectToneGen::MakeTone().
The documentation for this class was generated from the following files:
Generator.h
Generator.cpp