Audacity: TrackPanel Class Reference
TrackPanel Class Reference
The TrackPanel class coordinates updates and operations on the main part of the screen which contains multiple tracks.
#include <TrackPanel.h>
Classes
class AudacityTimer
Timer class dedicated to infomring the TrackPanel that it is time to refresh some aspect of the screen.
Public Member Functions
TrackPanel (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size, TrackList *tracks, ViewInfo *viewInfo, TrackPanelListener *listener, AdornedRulerPanel *ruler)
virtual ~TrackPanel ()
void BuildMenus (void)
void DeleteMenus (void)
void UpdatePrefs ()
void OnSize (wxSizeEvent &event)
OnSize() is called when the panel is resized.
void OnErase (wxEraseEvent &event)
void OnPaint (wxPaintEvent &event)
void OnMouseEvent (wxMouseEvent &event)
void OnCaptureLost (wxMouseCaptureLostEvent &event)
Should handle the case when the mouse capture is lost.
void OnCaptureKey (wxCommandEvent &event)
Filter captured keys typed into LabelTracks.
void OnKeyDown (wxKeyEvent &event)
Allow typing into LabelTracks.
void OnChar (wxKeyEvent &event)
Allow typing into LabelTracks.
void OnSetFocus (wxFocusEvent &event)
void OnKillFocus (wxFocusEvent &event)
void OnContextMenu (wxContextMenuEvent &event)
void OnTrackListResized (wxCommandEvent &event)
void OnTrackListUpdated (wxCommandEvent &event)
double GetMostRecentXPos ()
void OnTimer ()
AS: This gets called on our wx timer events.
int GetLeftOffset () const
void GetTracksUsableArea (int *width, int *height) const
void SelectNone ()
void SetStop (bool bStopped)
virtual void Refresh (bool eraseBackground=true, const wxRect *rect=(const wxRect *) NULL)
void RefreshTrack (Track *trk, bool refreshbacking=true)
void DisplaySelection ()
Displays the bounds of the selection in the status bar.
void SetSelectionFormat (int iformat)
void SetSnapTo (int snapto)
void HandleShiftKey (bool down)
void HandleControlKey (bool down)
AudacityProject * GetProject () const
void OnPrevTrack (bool shift=false)
void OnNextTrack (bool shift=false)
void OnToggle ()
void OnCursorLeft (bool shift, bool ctrl)
void OnCursorRight (bool shift, bool ctrl)
void OnCursorMove (bool forward, bool jump, bool longjump)
void OnBoundaryMove (bool left, bool boundaryContract)
void ScrollIntoView (double pos)
void ScrollIntoView (int x)
void OnTrackPan ()
void OnTrackPanLeft ()
void OnTrackPanRight ()
void OnTrackGain ()
This will pop up the track gain dialog for specified track.
void OnTrackGainDec ()
void OnTrackGainInc ()
void OnTrackMenu (Track *t=NULL)
void OnTrackMute (bool shiftdown, Track *t=NULL)
void OnTrackSolo (bool shiftdown, Track *t=NULL)
void OnTrackClose ()
Track * GetFirstSelectedTrack ()
void EnsureVisible (Track *t)
Track * GetFocusedTrack ()
void SetFocusedTrack (Track *t)
void HandleCursorForLastMouseEvent ()
void UpdateVRulers ()
void UpdateVRuler (Track *t)
void UpdateTrackVRuler (Track *t)
void UpdateVRulerSize ()
Public Attributes
wxSize vrulerSize
Private Types
enum MouseCaptureEnum {
IsUncaptured = 0, IsVZooming, IsClosing, IsSelecting,
IsAdjustingLabel, IsResizing, IsResizingBetweenLinkedTracks, IsResizingBelowLinkedTracks,
IsRearranging, IsSliding, IsEnveloping, IsMuting,
IsSoloing, IsGainSliding, IsPanSliding, IsMinimizing,
IsOverCutLine, WasOverCutLine, IsPopping, IsZooming
}
Private Member Functions
MixerBoard * GetMixerBoard ()
bool IsUnsafe ()
bool HandleLabelTrackMouseEvent (LabelTrack *lTrack, wxRect &r, wxMouseEvent &event)
Event has happened on a track and it has been determined to be a label track.
bool HandleTrackLocationMouseEvent (WaveTrack *track, wxRect &r, wxMouseEvent &event)
void HandleTrackSpecificMouseEvent (wxMouseEvent &event)
void DrawIndicator ()
void DoDrawIndicator (wxDC &dc)
Second level DrawIndicator().
void DrawCursor ()
void DoDrawCursor (wxDC &dc)
Second level DrawCursor().
void ScrollDuringDrag ()
int DetermineToolToUse (ToolsToolBar *pTtb, wxMouseEvent &event)
bool HitTestEnvelope (Track *track, wxRect &r, wxMouseEvent &event)
bool HitTestSamples (Track *track, wxRect &r, wxMouseEvent &event)
bool HitTestSlide (Track *track, wxRect &r, wxMouseEvent &event)
void HandleSelect (wxMouseEvent &event)
void SelectionHandleDrag (wxMouseEvent &event, Track *pTrack)
void SelectionHandleClick (wxMouseEvent &event, Track *pTrack, wxRect r)
void StartSelection (int mouseXCoordinate, int trackLeftEdge)
Reset our selection markers.
void ExtendSelection (int mouseXCoordinate, int trackLeftEdge, Track *pTrack)
Extend the existing selection.
void SelectTracksByLabel (LabelTrack *t)
Select all tracks marked by the label track lt.
void SelectTrackLength (Track *t)
double GridMove (double t, int minPix)
bool SetCursorByActivity ()
void SetCursorAndTipWhenInLabel (Track *t, wxMouseEvent &event, const wxChar **ppTip)
void SetCursorAndTipWhenInVResizeArea (Track *label, bool blinked, const wxChar **ppTip)
When in the resize area we can adjust size or relative size.
void SetCursorAndTipWhenInLabelTrack (LabelTrack *pLT, wxMouseEvent &event, const wxChar **ppTip)
void SetCursorAndTipWhenSelectTool (Track *t, wxMouseEvent &event, wxRect &r, bool bMultiToolMode, const wxChar **ppTip)
void SetCursorAndTipByTool (int tool, wxMouseEvent &event, const wxChar **ppTip)
void HandleCursor (wxMouseEvent &event)
void HandleEnvelope (wxMouseEvent &event)
void ForwardEventToTimeTrackEnvelope (wxMouseEvent &event)
void ForwardEventToWaveTrackEnvelope (wxMouseEvent &event)
void ForwardEventToEnvelope (wxMouseEvent &event)
void HandleSlide (wxMouseEvent &event)
void StartSlide (wxMouseEvent &event)
Prepare for sliding.
void DoSlide (wxMouseEvent &event)
void AddClipsToCaptured (Track *t, bool withinSelection)
void AddClipsToCaptured (Track *t, double t0, double t1)
void HandleZoom (wxMouseEvent &event)
void HandleZoomClick (wxMouseEvent &event)
Zoom button down, record the position.
void HandleZoomDrag (wxMouseEvent &event)
Zoom drag.
void HandleZoomButtonUp (wxMouseEvent &event)
Zoom button up.
bool IsDragZooming ()
Determines if drag zooming is active.
void DragZoom (wxMouseEvent &event, int x)
void DoZoomInOut (wxMouseEvent &event, int x)
void HandleVZoom (wxMouseEvent &event)
void HandleVZoomClick (wxMouseEvent &event)
VZoom click.
void HandleVZoomDrag (wxMouseEvent &event)
VZoom drag.
void HandleVZoomButtonUp (wxMouseEvent &event)
bool IsSampleEditingPossible (wxMouseEvent &event, Track *t)
void HandleSampleEditing (wxMouseEvent &event)
void HandleSampleEditingClick (wxMouseEvent &event)
void HandleSampleEditingDrag (wxMouseEvent &event)
void HandleSampleEditingButtonUp (wxMouseEvent &event)
void HandleWheelRotation (wxMouseEvent &event)
Handle mouse wheel rotation (for zoom in/out and vertical scrolling).
void HandleResizeClick (wxMouseEvent &event)
void HandleResizeDrag (wxMouseEvent &event)
void HandleResizeButtonUp (wxMouseEvent &event)
void HandleResize (wxMouseEvent &event)
void HandleLabelClick (wxMouseEvent &event)
void HandleRearrange (wxMouseEvent &event)
void CalculateRearrangingThresholds (wxMouseEvent &event)
void HandleClosing (wxMouseEvent &event)
void HandlePopping (wxMouseEvent &event)
void HandleMutingSoloing (wxMouseEvent &event, bool solo)
Handle when the mute or solo button is pressed for some track.
void HandleMinimizing (wxMouseEvent &event)
void HandleSliders (wxMouseEvent &event, bool pan)
bool MuteSoloFunc (Track *t, wxRect r, int x, int f, bool solo)
bool MinimizeFunc (Track *t, wxRect r, int x, int f)
bool CloseFunc (Track *t, wxRect r, int x, int y)
bool PopupFunc (Track *t, wxRect r, int x, int y)
bool GainFunc (Track *t, wxRect r, wxMouseEvent &event, int x, int y)
bool PanFunc (Track *t, wxRect r, wxMouseEvent &event, int x, int y)
void MakeParentRedrawScrollbars ()
void MakeParentPushState (wxString desc, wxString shortDesc, bool consolidate=false)
void MakeParentModifyState ()
void MakeParentResize ()
void OnSetName (wxCommandEvent &event)
void OnSetFont (wxCommandEvent &event)
void OnMoveTrack (wxCommandEvent &event)
AS: Move a track up or down, depending.
void OnChangeOctave (wxCommandEvent &event)
void OnChannelChange (wxCommandEvent &event)
void OnSetDisplay (wxCommandEvent &event)
void OnSetTimeTrackRange (wxCommandEvent &event)
void SetMenuCheck (wxMenu &menu, int newId)
Puts a check mark at a given position in a menu, clearing all other check marks.
void SetRate (Track *pTrack, double rate)
void OnRateChange (wxCommandEvent &event)
void OnRateOther (wxCommandEvent &event)
void OnFormatChange (wxCommandEvent &event)
void OnSplitStereo (wxCommandEvent &event)
Split a stereo track into two tracks...
void OnSplitStereoMono (wxCommandEvent &event)
Split a stereo track into two mono tracks...
void SplitStereo (bool stereo)
Split a stereo track into two tracks...
void OnMergeStereo (wxCommandEvent &event)
Merge two tracks into one stereo track ??
void OnCutSelectedText (wxCommandEvent &event)
Cut selected text if cut menu item is selected.
void OnCopySelectedText (wxCommandEvent &event)
Copy selected text if copy menu item is selected.
void OnPasteSelectedText (wxCommandEvent &event)
paste selected text if p`aste menu item is selected
void SetTrackPan (Track *t, LWSlider *s)
void SetTrackGain (Track *t, LWSlider *s)
void RemoveTrack (Track *toRemove)
Removes the specified track. Called from HandleClosing.
Track * FindTrack (int mouseX, int mouseY, bool label, bool link, wxRect *trackRect=NULL)
wxRect FindTrackRect (Track *target, bool label)
int GetTitleOffset () const
int GetVRulerWidth () const
int GetVRulerOffset () const
int GetLabelWidth () const
void DrawTracks (wxDC *dc)
void DrawEverythingElse (wxDC *dc, const wxRegion region, const wxRect panelRect, const wxRect clip)
void DrawOutside (Track *t, wxDC *dc, const wxRect rec, const wxRect trackRect)
void DrawZooming (wxDC *dc, const wxRect clip)
void HighlightFocusedTrack (wxDC *dc, const wxRect r)
Draw a three-level highlight gradient around the focused track.
void DrawShadow (Track *t, wxDC *dc, const wxRect r)
void DrawBordersAroundTrack (Track *t, wxDC *dc, const wxRect r, const int labelw, const int vrul)
void DrawOutsideOfTrack (Track *t, wxDC *dc, const wxRect r)
int IdOfRate (int rate)
Converts a sampling rate to a wxWidgets menu item id.
int IdOfFormat (int format)
Converts a format enumeration to a wxWidgets menu item Id.
bool HasSoloButton ()
wxString TrackSubText (Track *t)
bool MoveClipToTrack (WaveClip *clip, WaveTrack *src, WaveTrack *dst)
double PositionToTime (wxInt64 mouseXCoordinate, wxInt64 trackLeftEdge) const
wxInt64 TimeToPosition (double time, wxInt64 trackLeftEdge) const
STM: Converts a project time to screen x position.
void SetCapturedTrack (Track *t, enum MouseCaptureEnum MouseCapture=IsUncaptured)
Private Attributes
int mLabelTrackStartXPos
int mLabelTrackStartYPos
TrackInfo mTrackInfo
TrackPanelListener * mListener
TrackList * mTracks
ViewInfo * mViewInfo
AdornedRulerPanel * mRuler
double mSeekShort
double mSeekLong
TrackArtist * mTrackArtist
TrackPanel::AudacityTimer mTimer
double mLastIndicator
double mLastCursor
int mTimeCount
wxMemoryDC mBackingDC
wxBitmap * mBacking
bool mRefreshBacking
int mPrevWidth
int mPrevHeight
wxLongLong mLastSelectionAdjustment
double mSelStart
Track * mCapturedTrack
Envelope * mCapturedEnvelope
WaveClip * mCapturedClip
TrackClipArray mCapturedClipArray
bool mCapturedClipIsSelection
WaveTrack::Location mCapturedTrackLocation
wxRect mCapturedTrackLocationRect
wxRect mCapturedRect
wxBaseArrayDouble mSlideSnapFromPoints
wxBaseArrayDouble mSlideSnapToPoints
wxArrayInt mSlideSnapLinePixels
double mHSlideAmount
bool mDidSlideVertically
bool mRedrawAfterStop
bool mIndicatorShowing
wxMouseEvent mLastMouseEvent
int mMouseClickX
int mMouseClickY
int mMouseMostRecentX
int mMouseMostRecentY
int mZoomStart
int mZoomEnd
SnapManager * mSnapManager
wxInt64 mSnapLeft
wxInt64 mSnapRight
bool mSnapPreferRightEdge
Track * mDrawingTrack
int mDrawingTrackTop
sampleCount mDrawingStartSample
float mDrawingStartSampleValue
sampleCount mDrawingLastDragSample
float mDrawingLastDragSampleValue
int mInitialTrackHeight
int mInitialUpperTrackHeight
bool mAutoScrolling
enum MouseCaptureEnum mMouseCapture
bool mAdjustSelectionEdges
bool mSlideUpDownOnly
bool mCircularTrackNavigation
float mdBr
int mMoveUpThreshold
int mMoveDownThreshold
wxCursor * mArrowCursor
wxCursor * mPencilCursor
wxCursor * mSelectCursor
wxCursor * mResizeCursor
wxCursor * mSlideCursor
wxCursor * mEnvelopeCursor
wxCursor * mSmoothCursor
wxCursor * mZoomInCursor
wxCursor * mZoomOutCursor
wxCursor * mLabelCursorLeft
wxCursor * mLabelCursorRight
wxCursor * mRearrangeCursor
wxCursor * mDisabledCursor
wxCursor * mAdjustLeftSelectionCursor
wxCursor * mAdjustRightSelectionCursor
wxMenu * mWaveTrackMenu
wxMenu * mNoteTrackMenu
wxMenu * mTimeTrackMenu
wxMenu * mLabelTrackMenu
wxMenu * mRateMenu
wxMenu * mFormatMenu
wxMenu * mLabelTrackInfoMenu
Track * mPopupMenuTarget
TrackPanelAx * mAx
wxString mSoloPref
double mVertScrollRemainder
Friends
class TrackPanelAx
class ScreenshotCommand
Detailed Description
The TrackPanel class coordinates updates and operations on the main part of the screen which contains multiple tracks.
It uses many other classes, but in particular it uses the TrackInfo class to draw the label on the left of a track, and the TrackArtist class to draw the actual waveforms.
The TrackPanel manages multiple tracks and their TrackInfos.
Note that with stereo tracks there will be one TrackInfo being used by two wavetracks.
Member Enumeration Documentation
enum TrackPanel::MouseCaptureEnum [private]
Enumerator:
IsUncaptured
IsVZooming
IsClosing
IsSelecting
IsAdjustingLabel
IsResizing
IsResizingBetweenLinkedTracks
IsResizingBelowLinkedTracks
IsRearranging
IsSliding
IsEnveloping
IsMuting
IsSoloing
IsGainSliding
IsPanSliding
IsMinimizing
IsOverCutLine
WasOverCutLine
IsPopping
IsZooming
Constructor & Destructor Documentation
TrackPanel::TrackPanel (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size, TrackList * tracks, ViewInfo * viewInfo, TrackPanelListener * listener, AdornedRulerPanel * ruler)
References BuildMenus(), IsUncaptured, kLeftInset, kTimerInterval, kTopInset, mAdjustLeftSelectionCursor, mAdjustRightSelectionCursor, mArrowCursor, mAx, mCapturedTrack, mCircularTrackNavigation, mDisabledCursor, mDrawingTrack, mEnvelopeCursor, mIndicatorShowing, mLabelCursorLeft, mLabelCursorRight, mLabelTrackInfoMenu, mLabelTrackMenu, mLabelTrackStartXPos, mLastCursor, mLastIndicator, mLastSelectionAdjustment, mMouseCapture, mNoteTrackMenu, mPencilCursor, mPopupMenuTarget, mPrevHeight, mPrevWidth, mRearrangeCursor, mRedrawAfterStop, mResizeCursor, mSelectCursor, mSlideCursor, mSlideUpDownOnly, mSmoothCursor, mSnapLeft, mSnapManager, mSnapRight, mTimeCount, mTimer, mTimeTrackMenu, mTrackArtist, mTracks, mWaveTrackMenu, mZoomEnd, mZoomInCursor, mZoomOutCursor, mZoomStart, OnTrackListResized(), OnTrackListUpdated(), TrackPanel::AudacityTimer::parent, TrackArtist::SetInset(), TrackPanelAx, and UpdatePrefs().
TrackPanel::~TrackPanel () [virtual]
References DeleteMenus(), mAdjustLeftSelectionCursor, mAdjustRightSelectionCursor, mArrowCursor, mAx, mBacking, mBackingDC, mDisabledCursor, mEnvelopeCursor, mLabelCursorLeft, mLabelCursorRight, mPencilCursor, mRearrangeCursor, mResizeCursor, mSelectCursor, mSlideCursor, mSmoothCursor, mSnapManager, mTimer, mTrackArtist, mTracks, mZoomInCursor, mZoomOutCursor, OnTrackListResized(), and OnTrackListUpdated().
Member Function Documentation
void TrackPanel::AddClipsToCaptured (Track * t, double t0, double t1) [private]
References WaveClip::AfterClip(), WaveClip::BeforeClip(), Track::GetKind(), mCapturedClipArray, and Track::Wave.
void TrackPanel::AddClipsToCaptured (Track * t, bool withinSelection) [private]
References Track::GetEndTime(), Track::GetStartTime(), mViewInfo, ViewInfo::sel0, and ViewInfo::sel1.
Referenced by StartSlide().
void TrackPanel::BuildMenus (void)
References DeleteMenus(), floatSample, GetSampleFormatStr(), int16Sample, int24Sample, mFormatMenu, mLabelTrackInfoMenu, mLabelTrackMenu, mNoteTrackMenu, mRateMenu, mTimeTrackMenu, mWaveTrackMenu, On24BitID, OnChannelRightID, OnRate11ID, OnRate16ID, OnRate22ID, OnRate44ID, OnRate48ID, OnSpectrumID, OnSpectrumLogID, and OnWaveformDBID.
Referenced by AudacityProject::RebuildOtherMenus(), and TrackPanel().
void TrackPanel::CalculateRearrangingThresholds (wxMouseEvent & event) [private]
Figure out how far the user must drag the mouse up or down before the track will swap with the one above or below
References TrackList::CanMoveDown(), TrackList::CanMoveUp(), TrackList::GetGroupHeight(), TrackList::GetNext(), TrackList::GetPrev(), mCapturedTrack, mMoveDownThreshold, mMoveUpThreshold, and mTracks.
Referenced by HandleLabelClick(), and HandleRearrange().
bool TrackPanel::CloseFunc (Track * t, wxRect r, int x, int y) [private]
References TrackInfo::DrawCloseBox(), TrackInfo::GetCloseBoxRect(), IsClosing, mCapturedRect, mTrackInfo, and SetCapturedTrack().
Referenced by HandleLabelClick().
void TrackPanel::DeleteMenus (void)
References mLabelTrackInfoMenu, mLabelTrackMenu, mNoteTrackMenu, mTimeTrackMenu, and mWaveTrackMenu.
Referenced by BuildMenus(), and ~TrackPanel().
int TrackPanel::DetermineToolToUse (ToolsToolBar * pTtb, wxMouseEvent & event) [private]
If we are in multimode, looks at the type of track and where we are on it to determine what object we are hovering over and hence what tool to use.
Parameters:
pTtb - A pointer to the tools tool bar
event - Mouse event, with info about position and what mouse buttons are down.
References drawTool, envelopeTool, FindTrack(), ToolsToolBar::GetCurrentTool(), Track::GetKind(), HitTestEnvelope(), HitTestSamples(), HitTestSlide(), ToolsToolBar::IsDown(), IsUncaptured, Track::Label, mMouseCapture, multiTool, selectTool, ToolsToolBar::SetCurrentTool(), slideTool, Track::Time, Track::Wave, and zoomTool.
Referenced by HandleCursor(), and HandleTrackSpecificMouseEvent().
void TrackPanel::DisplaySelection ()
Displays the bounds of the selection in the status bar.
References mListener, and TrackPanelListener::TP_DisplaySelection().
Referenced by DoDrawCursor(), DoDrawIndicator(), ExtendSelection(), HandleTrackLocationMouseEvent(), OnTimer(), Refresh(), and SelectionHandleClick().
void TrackPanel::DoDrawCursor (wxDC & dc) [private]
Second level DrawCursor().
References between_inclusive(), AColor::CursorColor(), DisplaySelection(), AdornedRulerPanel::DrawCursor(), TrackListCondIterator::First(), GetLeftOffset(), GetProject(), ViewInfo::h, TrackPanelAx::IsFocused(), kTopInset, AColor::Line(), mAx, mBacking, mBackingDC, mLastCursor, mRuler, mViewInfo, TrackListCondIterator::Next(), ViewInfo::screen, ViewInfo::sel0, Track::Time, ViewInfo::vpos, TimeTrack::warp(), and ViewInfo::zoom.
Referenced by DoDrawIndicator(), DrawCursor(), and OnPaint().
void TrackPanel::DoDrawIndicator (wxDC & dc) [private]
Second level DrawIndicator().
References between_inclusive(), ViewInfo::bUpdateTrackIndicator, DisplaySelection(), DoDrawCursor(), AdornedRulerPanel::DrawIndicator(), TrackListCondIterator::First(), gAudioIO, AudacityProject::GetAudioIOToken(), GetLabelWidth(), GetLeftOffset(), AudioIO::GetNumCaptureChannels(), GetProject(), AudioIO::GetStreamTime(), ViewInfo::h, AColor::IndicatorColor(), AudioIO::IsPaused(), AudioIO::IsStreamActive(), kLeftInset, kTopInset, Track::Label, AColor::Line(), loopedPlay, MakeParentRedrawScrollbars(), mBacking, mBackingDC, mIndicatorShowing, mLastCursor, mLastIndicator, AudacityProject::mLastPlayMode, mListener, mRuler, mViewInfo, TrackListCondIterator::Next(), oneSecondPlay, ViewInfo::screen, TrackPanelListener::TP_ScrollWindow(), ViewInfo::vpos, and ViewInfo::zoom.
Referenced by DrawIndicator(), and OnPaint().
void TrackPanel::DoSlide (wxMouseEvent & event) [private]
Slide tracks horizontally, or slide clips horizontally or vertically (e.g. moving clips between tracks).
References WaveTrack::CanOffsetClip(), FindTrack(), TrackList::GetEndTime(), WaveClip::GetEndTime(), WaveTrack::GetKind(), GetLeftOffset(), TrackList::GetLink(), Track::GetLinked(), WaveTrack::GetRate(), TrackList::GetStartTime(), WaveClip::GetStartTime(), mCapturedClip, mCapturedClipArray, mCapturedClipIsSelection, mCapturedTrack, mDidSlideVertically, mHSlideAmount, mMouseClickX, MoveClipToTrack(), mSlideUpDownOnly, mSnapLeft, mSnapManager, mSnapPreferRightEdge, mSnapRight, mTracks, mViewInfo, WaveClip::Offset(), Track::Offset(), Refresh(), ViewInfo::sel0, ViewInfo::sel1, SnapManager::Snap(), TimeToPosition(), Track::Wave, and ViewInfo::zoom.
Referenced by HandleSlide().
void TrackPanel::DoZoomInOut (wxMouseEvent & event, int trackLeftEdge) [private]
This handles normal Zoom In/Out, if you just clicked; IOW, if you were NOT dragging to zoom an area.
Todo:
MAGIC NUMBER: We've got several in this function.
References gMaxZoom, gMinZoom, ViewInfo::h, mViewInfo, PositionToTime(), and ViewInfo::zoom.
Referenced by HandleZoomButtonUp().
void TrackPanel::DragZoom (wxMouseEvent & event, int trackLeftEdge) [private]
This actually sets the Zoom value when you're done doing a drag zoom.
References gMaxZoom, gMinZoom, ViewInfo::h, mViewInfo, mZoomEnd, mZoomStart, PositionToTime(), ViewInfo::screen, and ViewInfo::zoom.
Referenced by HandleZoomButtonUp().
void TrackPanel::DrawBordersAroundTrack (Track * t, wxDC * dc, const wxRect r, const int labelw, const int vrul) [private]
References Track::GetHeight(), Track::GetLinked(), kTopInset, and AColor::Line().
Referenced by DrawOutside().
void TrackPanel::DrawCursor () [private]
This function draws the cursor things, both in the ruler as seen at the top of the screen, but also in each of the selected tracks. These are the 'vertical lines' through waves and ruler.
References DoDrawCursor().
Referenced by OnCursorLeft(), OnCursorMove(), and OnCursorRight().
void TrackPanel::DrawEverythingElse (wxDC * dc, const wxRegion region, const wxRect panelRect, const wxRect clip) [private]
Draws 'Everything else'. In particular it draws:
Drop shadow for tracks and vertical rulers.
Zooming Indicators.
Fills in space below the tracks.
References DrawOutside(), TrackArtist::DrawVRuler(), DrawZooming(), TrackListCondIterator::First(), GetFocusedTrack(), Track::GetHeight(), GetLeftOffset(), Track::GetLinked(), GetProject(), GetVRulerOffset(), GetVRulerWidth(), Track::GetY(), HighlightFocusedTrack(), IsDragZooming(), TrackPanelAx::IsFocused(), IsVZooming, IsZooming, kTopInset, AColor::Line(), mAx, mMouseCapture, mSnapLeft, mSnapManager, mSnapRight, mTrackArtist, mViewInfo, TrackListCondIterator::Next(), AColor::SnapGuidePen(), AColor::TrackPanelBackground(), and ViewInfo::vpos.
Referenced by DrawTracks().
void TrackPanel::DrawIndicator () [private]
This updates the indicator (on a timer tick) that shows where the current play or record position is. To do this, we cheat a little. The indicator is drawn during the ruler drawing process (that should probably change, but...), so we create a memory DC and tell the ruler to draw itself there, and then just blit that to the screen. The indicator is a small triangle, red for record, green for play.
References DoDrawIndicator().
Referenced by OnTimer().
void TrackPanel::DrawOutside (Track * t, wxDC * dc, const wxRect rec, const wxRect trackRect) [private]
References ThemeBase::Colour(), TrackInfo::DrawBackground(), DrawBordersAroundTrack(), TrackInfo::DrawBordersWithin(), TrackInfo::DrawCloseBox(), TrackInfo::DrawMinimize(), TrackInfo::DrawMuteSolo(), DrawOutsideOfTrack(), DrawShadow(), TrackInfo::DrawSliders(), TrackInfo::DrawTitleBar(), Track::GetKind(), GetLabelWidth(), Track::GetMinimized(), GetSampleFormatStr(), Track::GetSelected(), TrackInfo::GetTitleWidth(), TrackInfo::GetTrackControlsRect(), GetVRulerOffset(), HasSoloButton(), IsClosing, IsMinimizing, IsMuting, IsPopping, IsSoloing, Track::IsSynchroSelected(), kLeftInset, kTopInset, mCapturedTrack, mMouseCapture, mTrackInfo, Track::Note, TrackInfo::SetTrackInfoFont(), theTheme, TrackSubText(), and Track::Wave.
Referenced by DrawEverythingElse().
void TrackPanel::DrawOutsideOfTrack (Track * t, wxDC * dc, const wxRect r) [private]
References Track::GetHeight(), Track::GetLinked(), kLeftInset, kTopInset, and AColor::TrackPanelBackground().
Referenced by DrawOutside().
void TrackPanel::DrawShadow (Track * t, wxDC * dc, const wxRect r) [private]
References AColor::Dark(), and AColor::Line().
Referenced by DrawOutside().
void TrackPanel::DrawTracks (wxDC * dc) [private]
Draw the actual track areas. We only draw the borders and the little buttons and menues and whatnot here, the actual contents of each track are drawn by the TrackArtist.
References DrawEverythingElse(), drawTool, TrackArtist::DrawTracks(), envelopeTool, GetLabelWidth(), GetProject(), ToolsToolBar::IsDown(), mListener, mTrackArtist, mTracks, multiTool, mViewInfo, TrackPanelListener::TP_GetToolsToolBar(), and ViewInfo::vpos.
Referenced by OnPaint().
void TrackPanel::DrawZooming (wxDC * dc, const wxRect clip) [private]
Draw zooming indicator that shows the region that will be zoomed into when the user clicks and drags with a zoom cursor. Handles both vertical and horizontal zooming.
References GetTracksUsableArea(), GetVRulerOffset(), GetVRulerWidth(), IsVZooming, mMouseCapture, mZoomEnd, and mZoomStart.
Referenced by DrawEverythingElse().
void TrackPanel::EnsureVisible (Track * t)
References TrackListIterator::First(), Track::GetHeight(), Track::GetLinked(), mListener, mTracks, mViewInfo, TrackListIterator::Next(), Refresh(), ViewInfo::scrollStep, SetFocusedTrack(), TrackPanelListener::TP_ScrollUpDown(), and ViewInfo::vpos.
Referenced by AudacityProject::AddImportedTracks(), AudacityProject::DoAddLabel(), AudacityProject::HandleMixAndRender(), HandleRearrange(), AudacityProject::OnEffect(), AudacityProject::OnImportMIDI(), OnMouseEvent(), AudacityProject::OnNewLabelTrack(), AudacityProject::OnNewStereoTrack(), AudacityProject::OnNewTimeTrack(), AudacityProject::OnNewWaveTrack(), OnNextTrack(), AudacityProject::OnPaste(), AudacityProject::OnPasteNewLabel(), OnPrevTrack(), AudacityProject::OnRedo(), AudacityProject::OnRemoveTracks(), OnToggle(), and AudacityProject::OnUndo().
void TrackPanel::ExtendSelection (int mouseXCoordinate, int trackLeftEdge, Track * pTrack) [private]
Extend the existing selection.
References clip_bottom(), ODManager::DemandTrackUpdate(), DisplaySelection(), AdornedRulerPanel::DrawSelection(), Track::GetKind(), ODManager::Instance(), ODManager::IsInstanceCreated(), MakeParentModifyState(), mCapturedTrack, mRuler, mSelStart, mSnapLeft, mSnapManager, mSnapRight, mViewInfo, PositionToTime(), Refresh(), ViewInfo::sel0, ViewInfo::sel1, SnapManager::Snap(), TimeToPosition(), and Track::Wave.
Referenced by SelectionHandleClick(), and SelectionHandleDrag().
Track * TrackPanel::FindTrack (int mouseX, int mouseY, bool label, bool link, wxRect * trackRect = NULL) [private]
Determines which track is under the mouse
Parameters:
mouseX - mouse X position.
mouseY - mouse Y position.
label - true iff the X Y position is relative to side-panel with the labels in it.
link - true iff we should consider a hit in any linked track as a hit.
*trackRect - returns track rectangle.
References TrackListCondIterator::First(), Track::GetHeight(), GetLeftOffset(), GetProject(), Track::GetY(), kLeftInset, kTopInset, mViewInfo, TrackListCondIterator::Next(), and ViewInfo::vpos.
Referenced by DetermineToolToUse(), DoSlide(), HandleCursor(), HandleEnvelope(), HandleLabelClick(), HandleResizeClick(), HandleSampleEditingClick(), HandleSelect(), HandleTrackSpecificMouseEvent(), HandleVZoomClick(), HandleZoomClick(), OnMouseEvent(), SelectionHandleDrag(), and StartSlide().
wxRect TrackPanel::FindTrackRect (Track * target, bool label) [private]
This finds the rectangle of a given track, either the of the label 'adornment' or the track itself
References Track::GetHeight(), Track::GetLink(), Track::GetLinked(), Track::GetY(), kLeftInset, kTopInset, mViewInfo, and ViewInfo::vpos.
Referenced by ScreenshotCommand::Apply(), and OnTrackMenu().
void TrackPanel::ForwardEventToEnvelope (wxMouseEvent & event) [private]
The Envelope class actually handles things at the mouse event level, so we have to forward the events over. Envelope will then tell us whether or not we need to redraw.
References ForwardEventToTimeTrackEnvelope(), ForwardEventToWaveTrackEnvelope(), Track::GetKind(), mCapturedTrack, Track::Time, and Track::Wave.
Referenced by HandleEnvelope().
void TrackPanel::ForwardEventToTimeTrackEnvelope (wxMouseEvent & event) [private]
We've established we're a time track. send events for its envelope.
References TimeTrack::GetEnvelope(), ViewInfo::h, mCapturedRect, mCapturedTrack, Envelope::MouseEvent(), mViewInfo, RefreshTrack(), and ViewInfo::zoom.
Referenced by ForwardEventToEnvelope().
void TrackPanel::ForwardEventToWaveTrackEnvelope (wxMouseEvent & event) [private]
We've established we're a wave track. send events for its envelope.
References WaveTrack::GetActiveEnvelope(), WaveTrack::GetDisplay(), WaveTrack::GetDisplayBounds(), WaveTrack::GetEnvelopeAtX(), Track::GetLink(), ViewInfo::h, mCapturedEnvelope, mCapturedRect, mCapturedTrack, Envelope::MouseEvent(), mViewInfo, RefreshTrack(), and ViewInfo::zoom.
Referenced by ForwardEventToEnvelope().
bool TrackPanel::GainFunc (Track * t, wxRect r, wxMouseEvent & event, int x, int y) [private]
References TrackInfo::GetGainRect(), HandleSliders(), IsGainSliding, mCapturedRect, mTrackInfo, and SetCapturedTrack().
Referenced by HandleLabelClick().
Track * TrackPanel::GetFirstSelectedTrack ()
References TrackListIterator::First(), Track::GetSelected(), mTracks, and TrackListIterator::Next().
Referenced by AudacityProject::AddImportedTracks(), AudacityProject::OnEffect(), AudacityProject::OnRedo(), and AudacityProject::OnUndo().
Track * TrackPanel::GetFocusedTrack ()
References TrackPanelAx::GetFocus(), and mAx.
Referenced by GetTrackInfoCommand::Apply(), DrawEverythingElse(), OnBoundaryMove(), OnCaptureKey(), OnChar(), OnCursorLeft(), OnCursorRight(), OnKeyDown(), OnNextTrack(), OnPrevTrack(), OnSetFocus(), OnToggle(), OnTrackClose(), OnTrackGain(), OnTrackGainDec(), OnTrackGainInc(), OnTrackListUpdated(), OnTrackMenu(), OnTrackMute(), OnTrackPan(), OnTrackPanLeft(), OnTrackPanRight(), OnTrackSolo(), RemoveTrack(), and GetProjectInfoCommand::SendFocusedTrackIndex().
int TrackPanel::GetLabelWidth () const [inline, private]
References TrackInfo::GetTitleWidth(), GetVRulerWidth(), and mTrackInfo.
Referenced by DoDrawIndicator(), DrawOutside(), DrawTracks(), GetLeftOffset(), GetMostRecentXPos(), and GetTracksUsableArea().
int TrackPanel::GetLeftOffset () const [inline]
References GetLabelWidth().
Referenced by DoDrawCursor(), DoDrawIndicator(), DoSlide(), DrawEverythingElse(), FindTrack(), HandleSampleEditingClick(), HandleSampleEditingDrag(), HandleTrackSpecificMouseEvent(), HandleWheelRotation(), HandleZoomButtonUp(), HandleZoomDrag(), ScrollIntoView(), SelectionHandleClick(), StartSlide(), and UpdateVRulerSize().
MixerBoard * TrackPanel::GetMixerBoard () [private]
References AudacityProject::GetMixerBoard(), and GetProject().
Referenced by HandleLabelClick(), HandleRearrange(), HandleSliders(), OnMoveTrack(), OnSetName(), OnTimer(), OnTrackMute(), OnTrackSolo(), and RemoveTrack().
double TrackPanel::GetMostRecentXPos ()
References GetLabelWidth(), ViewInfo::h, mMouseMostRecentX, mViewInfo, and ViewInfo::zoom.
Referenced by AudacityProject::OnPlayOneSecond(), and AudacityProject::OnPlayToSelection().
AudacityProject * TrackPanel::GetProject () const
Gets the pointer to the AudacityProject that goes with this track panel.
Referenced by DoDrawCursor(), DoDrawIndicator(), DrawEverythingElse(), DrawTracks(), FindTrack(), GetMixerBoard(), GridMove(), HandleClosing(), HandleLabelClick(), HandleSliders(), HandleTrackSpecificMouseEvent(), IsUnsafe(), OnBoundaryMove(), OnCursorLeft(), OnCursorMove(), OnCursorRight(), OnPaint(), OnTimer(), OnTrackClose(), OnTrackMute(), OnTrackSolo(), and StartSlide().
int TrackPanel::GetTitleOffset () const [inline, private]
Referenced by GetVRulerOffset().
void TrackPanel::GetTracksUsableArea (int * width, int * height) const
References GetLabelWidth(), and kLeftInset.
Referenced by AudacityProject::DoZoomFitV(), DrawZooming(), AudacityProject::FixScrollbars(), AudacityProject::GetTPTracksUsableArea(), HandleZoomDrag(), AudacityProject::OnZoomFit(), and ScrollIntoView().
int TrackPanel::GetVRulerOffset () const [inline, private]
References GetTitleOffset(), TrackInfo::GetTitleWidth(), and mTrackInfo.
Referenced by DrawEverythingElse(), DrawOutside(), DrawZooming(), HandleTrackSpecificMouseEvent(), SetCursorAndTipWhenInLabel(), and UpdateTrackVRuler().
int TrackPanel::GetVRulerWidth () const [private]
References vrulerSize.
Referenced by DrawEverythingElse(), DrawZooming(), GetLabelWidth(), and UpdateTrackVRuler().
double TrackPanel::GridMove (double t, int minPix) [private]
References TimeTextCtrl::Decrement(), TimeTextCtrl::GetBuiltinFormat(), GetProject(), TimeTextCtrl::GetTimeValue(), gPrefs, TimeTextCtrl::Increment(), mViewInfo, TimeTextCtrl::SetFormatString(), TimeTextCtrl::SetTimeValue(), and ViewInfo::zoom.
Referenced by OnCursorLeft(), and OnCursorRight().
void TrackPanel::HandleClosing (wxMouseEvent & event) [private]
References TrackInfo::DrawCloseBox(), gAudioIO, AudacityProject::GetAudioIOToken(), TrackInfo::GetCloseBoxRect(), GetProject(), TrackList::IsEmpty(), AudioIO::IsStreamActive(), mCapturedRect, mCapturedTrack, mListener, mTrackInfo, mTracks, mViewInfo, Refresh(), RemoveTrack(), ViewInfo::sel0, ViewInfo::sel1, SetCapturedTrack(), TrackPanelListener::TP_DisplayStatusMessage(), TrackPanelListener::TP_RedrawScrollbars(), and ViewInfo::zoom.
Referenced by OnMouseEvent().
void TrackPanel::HandleControlKey (bool down)
References HandleCursorForLastMouseEvent(), and mLastMouseEvent.
Referenced by AudacityProject::HandleKeyDown(), and AudacityProject::HandleKeyUp().
void TrackPanel::HandleCursor (wxMouseEvent & event) [private]
TrackPanel::HandleCursor() sets the cursor drawn at the mouse location. As this procedure checks which region the mouse is over, it is appropriate to establish the message in the status bar.
References DetermineToolToUse(), FindTrack(), Track::GetKind(), Track::GetLinked(), ToolsToolBar::GetMessageForTool(), ToolsToolBar::IsDown(), Track::Label, label, mArrowCursor, mLastMouseEvent, mListener, multiTool, selectTool, SetCursorAndTipByTool(), SetCursorAndTipWhenInLabel(), SetCursorAndTipWhenInLabelTrack(), SetCursorAndTipWhenInVResizeArea(), SetCursorAndTipWhenSelectTool(), SetCursorByActivity(), TrackPanelListener::TP_DisplayStatusMessage(), TrackPanelListener::TP_GetToolsToolBar(), TRACK_RESIZE_REGION, and within().
Referenced by HandleCursorForLastMouseEvent(), HandleTrackSpecificMouseEvent(), and OnMouseEvent().
void TrackPanel::HandleCursorForLastMouseEvent ()
References HandleCursor(), and mLastMouseEvent.
Referenced by HandleControlKey(), HandleShiftKey(), and AudacityProject::RefreshCursor().
void TrackPanel::HandleEnvelope (wxMouseEvent & event) [private]
HandleEnvelope gets called when the user is changing the amplitude envelope on a track.
References FindTrack(), ForwardEventToEnvelope(), Track::GetKind(), kTopInset, MakeParentPushState(), mCapturedEnvelope, mCapturedRect, mCapturedTrack, and Track::Wave.
Referenced by HandleTrackSpecificMouseEvent().
void TrackPanel::HandleLabelClick (wxMouseEvent & event) [private]
This handles when the user clicks on the "Label" area of a track, ie the part with all the buttons and the drop down menu, etc.
References CalculateRearrangingThresholds(), CloseFunc(), FindTrack(), GainFunc(), gAudioIO, AudacityProject::GetAudioIOToken(), Track::GetKind(), GetMixerBoard(), GetProject(), Track::GetSelected(), TrackInfo::GetTrackControlsRect(), IsRearranging, AudioIO::IsStreamActive(), MakeParentModifyState(), MinimizeFunc(), mTrackInfo, mTracks, MuteSoloFunc(), Track::Note, PanFunc(), PopupFunc(), Refresh(), MixerBoard::RefreshTrackCluster(), MixerBoard::RefreshTrackClusters(), TrackList::Select(), SelectNone(), SelectTrackLength(), SetCapturedTrack(), SetFocusedTrack(), and Track::Wave.
Referenced by HandleTrackSpecificMouseEvent().
bool TrackPanel::HandleLabelTrackMouseEvent (LabelTrack * lTrack, wxRect & r, wxMouseEvent & event) [private]
Event has happened on a track and it has been determined to be a label track.
Todo:
This function is one of a large number of functions in TrackPanel which suitably modified belong in other classes.
References TrackListIterator::First(), Track::GetKind(), LabelTrack::GetLabel(), LabelTrack::getSelectedIndex(), ViewInfo::h, LabelTrack::HandleMouse(), IsAdjustingLabel, LabelTrack::IsTextClipSupported(), LabelTrack::IsTextSelected(), kLeftInset, Track::Label, MakeParentPushState(), mCapturedRect, mLabelTrackInfoMenu, mLabelTrackStartXPos, mLabelTrackStartYPos, mMouseCapture, mPopupMenuTarget, mTracks, mViewInfo, TrackListIterator::Next(), LabelTrack::OverGlyph(), LabelTrack::OverTextBox(), RefreshTrack(), ViewInfo::sel0, ViewInfo::sel1, SetCapturedTrack(), LabelTrack::SetDragXPos(), LabelTrack::SetInBox(), LabelTrack::SetResetCursorPos(), LabelTrack::SetWrongDragging(), and ViewInfo::zoom.
Referenced by HandleTrackSpecificMouseEvent(), and OnMouseEvent().
void TrackPanel::HandleMinimizing (wxMouseEvent & event) [private]
References TrackInfo::DrawMinimize(), GetActiveProject(), TrackList::GetLink(), Track::GetMinimized(), TrackInfo::GetMinimizeRect(), MakeParentModifyState(), MakeParentRedrawScrollbars(), mCapturedRect, mCapturedTrack, mTrackInfo, mTracks, AudacityProject::RedrawProject(), Refresh(), SetCapturedTrack(), and Track::SetMinimized().
Referenced by OnMouseEvent().
void TrackPanel::HandleMutingSoloing (wxMouseEvent & event, bool solo) [private]
Handle when the mute or solo button is pressed for some track.
References TrackInfo::DrawMuteSolo(), TrackInfo::GetMuteSoloRect(), HasSoloButton(), mCapturedRect, mCapturedTrack, mTrackInfo, OnTrackMute(), OnTrackSolo(), Refresh(), and SetCapturedTrack().
Referenced by OnMouseEvent().
void TrackPanel::HandlePopping (wxMouseEvent & event) [private]
References TrackInfo::DrawTitleBar(), TrackInfo::GetTitleBarRect(), mCapturedRect, mCapturedTrack, mTrackInfo, OnTrackMenu(), and SetCapturedTrack().
Referenced by OnMouseEvent().
void TrackPanel::HandleRearrange (wxMouseEvent & event) [private]
The user is dragging one of the tracks: change the track order accordingly
References CalculateRearrangingThresholds(), EnsureVisible(), Track::GetKind(), GetMixerBoard(), Track::GetName(), MakeParentPushState(), mArrowCursor, mCapturedTrack, mMoveDownThreshold, mMoveUpThreshold, TrackList::MoveDown(), MixerBoard::MoveTrackCluster(), TrackList::MoveUp(), mTracks, SetCapturedTrack(), and Track::Wave.
Referenced by OnMouseEvent().
void TrackPanel::HandleResize (wxMouseEvent & event) [private]
HandleResize gets called when:
A mouse-down event occurs in the "resize region" of a track, i.e. to change its vertical height.
A mouse event occurs and mIsResizing==true (i.e. while the resize is going on)
References HandleResizeButtonUp(), HandleResizeClick(), and HandleResizeDrag().
Referenced by HandleTrackSpecificMouseEvent(), and OnMouseEvent().
void TrackPanel::HandleResizeButtonUp (wxMouseEvent & event) [private]
This happens when the button is released from a drag. Since we actually took care of resizing the track when we got drag events, all we have to do here is clean up. We also modify the undo state (the action doesn't become undo-able, but it gets merged with the previous undo-able event).
References MakeParentModifyState(), MakeParentRedrawScrollbars(), and SetCapturedTrack().
Referenced by HandleResize().
void TrackPanel::HandleResizeClick (wxMouseEvent & event) [private]
ButtonDown means they just clicked and haven't released yet. We use this opportunity to save which track they clicked on, and the initial height of the track, so as they drag we can update the track size.
References FindTrack(), Track::GetHeight(), Track::GetLink(), Track::GetLinked(), TrackList::GetNext(), TrackList::GetPrev(), IsResizing, IsResizingBelowLinkedTracks, IsResizingBetweenLinkedTracks, label, mInitialTrackHeight, mInitialUpperTrackHeight, mMouseClickX, mMouseClickY, mTracks, and SetCapturedTrack().
Referenced by HandleResize().
void TrackPanel::HandleResizeDrag (wxMouseEvent & event) [private]
Resize dragging means that the mouse button IS down and has moved from its initial location. By the time we get here, we have already received a ButtonDown() event and saved the track being resized in mCapturedTrack.
References Track::GetHeight(), Track::GetLink(), Track::GetLinked(), Track::GetMinimized(), Track::GetMinimizedHeight(), TrackList::GetNext(), TrackList::GetPrev(), IsResizing, IsResizingBelowLinkedTracks, IsResizingBetweenLinkedTracks, mCapturedTrack, mInitialTrackHeight, mInitialUpperTrackHeight, mMouseCapture, mMouseClickY, mTracks, Refresh(), Track::SetHeight(), and Track::SetMinimized().
Referenced by HandleResize().
void TrackPanel::HandleSampleEditing (wxMouseEvent & event) [private]
This handles adjusting individual samples by hand using the draw tool(s)
There are several member data structure for handling drawing:
mDrawingTrack: keeps track of which track you clicked down on, so drawing doesn't jump to a new track
mDrawingTrackTop: The top position of the drawing track--makes drawing easier.
mDrawingStartSample: The sample you clicked down on, so that you can hold it steady
mDrawingStartSampleValue: The original value of the initial sample
mDrawingLastDragSample: When drag-drawing, this keeps track of the last sample you dragged over, so it can smoothly redraw samples that got skipped over
mDrawingLastDragSampleValue: The value of the last
References HandleSampleEditingButtonUp(), HandleSampleEditingClick(), HandleSampleEditingDrag(), and mDrawingTrack.
Referenced by HandleTrackSpecificMouseEvent().
void TrackPanel::HandleSampleEditingButtonUp (wxMouseEvent & event) [private]
References MakeParentPushState(), and mDrawingTrack.
Referenced by HandleSampleEditing().
void TrackPanel::HandleSampleEditingClick (wxMouseEvent & event) [private]
We're in a track view and zoomed enough to see the samples. Someone has just clicked the mouse. What do we do?
Todo:
Should mCapturedTrack take the place of mDrawingTrack??
References FindTrack(), floatSample, Track::GetHeight(), GetLeftOffset(), Envelope::GetValue(), IsSampleEditingPossible(), mDrawingLastDragSample, mDrawingLastDragSampleValue, mDrawingStartSample, mDrawingStartSampleValue, mDrawingTrack, mDrawingTrackTop, PositionToTime(), RefreshTrack(), SMOOTHING_BRUSH_RADIUS, SMOOTHING_KERNEL_RADIUS, SMOOTHING_PROPORTION_MAX, and SMOOTHING_PROPORTION_MIN.
Referenced by HandleSampleEditing().
void TrackPanel::HandleSampleEditingDrag (wxMouseEvent & event) [private]
References floatSample, Track::GetHeight(), GetLeftOffset(), Envelope::GetValue(), LLABS, mDrawingLastDragSample, mDrawingLastDragSampleValue, mDrawingStartSample, mDrawingStartSampleValue, mDrawingTrack, mDrawingTrackTop, PositionToTime(), and RefreshTrack().
Referenced by HandleSampleEditing().
void TrackPanel::HandleSelect (wxMouseEvent & event) [private]
This function handles various ways of starting and extending selections. These are the selections you make by clicking and dragging over a waveform.
References FindTrack(), GetActiveProject(), WaveTrack::GetClipAtX(), WaveClip::GetEndTime(), Track::GetKind(), LyricsWindow::GetLyricsPanel(), AudacityProject::GetLyricsWindow(), WaveClip::GetOffset(), AudacityProject::GetSel0(), IsSliding, MakeParentModifyState(), mCapturedClipArray, mCapturedTrack, mMouseCapture, mSnapLeft, mSnapManager, mSnapRight, mTracks, mViewInfo, Refresh(), ViewInfo::sel0, ViewInfo::sel1, TrackList::Select(), SelectionHandleClick(), SelectionHandleDrag(), SelectNone(), SelectTrackLength(), SetCapturedTrack(), StartSlide(), Lyrics::Update(), and Track::Wave.
Referenced by HandleTrackSpecificMouseEvent(), and ScrollDuringDrag().
void TrackPanel::HandleShiftKey (bool down)
References HandleCursorForLastMouseEvent(), and mLastMouseEvent.
Referenced by AudacityProject::HandleKeyDown(), and AudacityProject::HandleKeyUp().
void TrackPanel::HandleSlide (wxMouseEvent & event) [private]
References DoSlide(), IsSliding, MakeParentPushState(), MakeParentRedrawScrollbars(), mCapturedTrack, mDidSlideVertically, mHSlideAmount, mMouseCapture, mSnapLeft, mSnapManager, mSnapRight, SetCapturedTrack(), and StartSlide().
Referenced by HandleTrackSpecificMouseEvent().
void TrackPanel::HandleSliders (wxMouseEvent & event, bool pan) [private]
References TrackListCondIterator::First(), LWSlider::Get(), Track::GetIndex(), TrackList::GetLink(), GetMixerBoard(), GetProject(), IsUncaptured, MakeParentPushState(), mCapturedTrack, TrackInfo::mGains, mMouseCapture, TrackInfo::mPans, mTrackInfo, mTracks, TrackListCondIterator::Next(), LWSlider::OnMouseEvent(), RefreshTrack(), SetCapturedTrack(), WaveTrack::SetGain(), WaveTrack::SetPan(), MixerBoard::UpdateGain(), and MixerBoard::UpdatePan().
Referenced by GainFunc(), OnMouseEvent(), and PanFunc().
bool TrackPanel::HandleTrackLocationMouseEvent (WaveTrack * track, wxRect & r, wxMouseEvent & event) [private]
References WaveTrack::Location::clipidx1, WaveTrack::Location::clipidx2, DisplaySelection(), WaveTrack::ExpandCutLine(), WaveTrack::GetCachedLocation(), TrackList::GetLink(), WaveTrack::GetNumCachedLocations(), ViewInfo::h, IsOverCutLine, IsUncaptured, WaveTrack::locationCutLine, WaveTrack::locationMergePoint, MakeParentPushState(), mCapturedTrackLocation, mCapturedTrackLocationRect, WaveTrack::MergeClips(), mMouseCapture, mTracks, mViewInfo, WaveTrack::Location::pos, RefreshTrack(), WaveTrack::RemoveCutLine(), ViewInfo::sel0, ViewInfo::sel1, SetCapturedTrack(), SetCursorByActivity(), WaveTrack::Location::typ, WasOverCutLine, and ViewInfo::zoom.
Referenced by HandleTrackSpecificMouseEvent().
void TrackPanel::HandleTrackSpecificMouseEvent (wxMouseEvent & event) [private]
References DetermineToolToUse(), drawTool, envelopeTool, FindTrack(), gAudioIO, AudacityProject::GetAudioIOToken(), Track::GetKind(), GetLeftOffset(), GetProject(), GetVRulerOffset(), HandleCursor(), HandleEnvelope(), HandleLabelClick(), HandleLabelTrackMouseEvent(), HandleResize(), HandleSampleEditing(), HandleSelect(), HandleSlide(), HandleTrackLocationMouseEvent(), HandleVZoom(), HandleZoom(), IsOverCutLine, AudioIO::IsStreamActive(), IsUncaptured, Track::Label, mCapturedTrack, mListener, mMouseCapture, selectTool, slideTool, TrackPanelListener::TP_GetToolsToolBar(), TRACK_RESIZE_REGION, WasOverCutLine, Track::Wave, within(), and zoomTool.
Referenced by OnMouseEvent().
void TrackPanel::HandleVZoom (wxMouseEvent & event) [private]
Vertical zooming (triggered by clicking in the vertical ruler)
References HandleVZoomButtonUp(), HandleVZoomClick(), and HandleVZoomDrag().
Referenced by HandleTrackSpecificMouseEvent(), and OnMouseEvent().
void TrackPanel::HandleVZoomButtonUp (wxMouseEvent & event) [private]
VZoom Button up. There are three cases:
Drag-zooming; we already have a min and max
Zoom out; ensure we don't go too small.
Zoom in; ensure we don't go too large.
References WaveTrack::GetDisplayBounds(), Track::GetHeight(), Track::GetKind(), TrackList::GetLink(), TrackArtist::GetSpectrumLogMaxFreq(), TrackArtist::GetSpectrumLogMinFreq(), TrackArtist::GetSpectrumMaxFreq(), TrackArtist::GetSpectrumMinFreq(), TrackArtist::GetSpectrumWindowSize(), TrackArtist::InvalidateSpectrumCache(), IsDragZooming(), IsUncaptured, MakeParentModifyState(), max, mCapturedRect, mCapturedTrack, min(), mMouseCapture, mTrackArtist, mTracks, mZoomEnd, mZoomStart, Refresh(), WaveTrack::SetDisplayBounds(), TrackArtist::SetSpectrumLogMaxFreq(), TrackArtist::SetSpectrumLogMinFreq(), TrackArtist::SetSpectrumMaxFreq(), TrackArtist::SetSpectrumMinFreq(), WaveTrack::SpectrumDisplay, WaveTrack::SpectrumLogDisplay, UpdateVRuler(), and Track::Wave.
Referenced by HandleVZoom().
void TrackPanel::HandleVZoomClick (wxMouseEvent & event) [private]
VZoom click.
References FindTrack(), Track::GetKind(), IsVZooming, mCapturedRect, mCapturedTrack, mMouseCapture, mZoomEnd, mZoomStart, WaveTrack::SpectrumLogDisplay, and Track::Wave.
Referenced by HandleVZoom().
void TrackPanel::HandleVZoomDrag (wxMouseEvent & event) [private]
VZoom drag.
References IsDragZooming(), mZoomEnd, and Refresh().
Referenced by HandleVZoom().
void TrackPanel::HandleWheelRotation (wxMouseEvent & event) [private]
Handle mouse wheel rotation (for zoom in/out and vertical scrolling).
References GetLeftOffset(), gMaxZoom, ViewInfo::h, MakeParentRedrawScrollbars(), mListener, mVertScrollRemainder, mViewInfo, PositionToTime(), Refresh(), TrackPanelListener::TP_ScrollUpDown(), TrackPanelListener::TP_ScrollWindow(), and ViewInfo::zoom.
Referenced by OnMouseEvent().
void TrackPanel::HandleZoom (wxMouseEvent & event) [private]
This function takes care of our different zoom possibilities. It is possible for a user to just "zoom in" or "zoom out," but it is also possible for a user to drag and select an area that he or she wants to be zoomed in on. We use mZoomStart and mZoomEnd to track the beggining and end of such a zoom area. Note that the ViewInfo member mViewInfo actually keeps track of our zoom constant, so we achieve zooming by altering the zoom constant and forcing a refresh.
References HandleZoomButtonUp(), HandleZoomClick(), HandleZoomDrag(), IsZooming, and mMouseCapture.
Referenced by HandleTrackSpecificMouseEvent(), and OnMouseEvent().
void TrackPanel::HandleZoomButtonUp (wxMouseEvent & event) [private]
Zoom button up.
References DoZoomInOut(), DragZoom(), GetLeftOffset(), IsDragZooming(), MakeParentRedrawScrollbars(), mZoomEnd, mZoomStart, Refresh(), and SetCapturedTrack().
Referenced by HandleZoom().
void TrackPanel::HandleZoomClick (wxMouseEvent & event) [private]
Zoom button down, record the position.
References FindTrack(), IsZooming, mCapturedRect, mCapturedTrack, mZoomEnd, mZoomStart, and SetCapturedTrack().
Referenced by HandleZoom().
void TrackPanel::HandleZoomDrag (wxMouseEvent & event) [private]
Zoom drag.
References GetLeftOffset(), GetTracksUsableArea(), IsDragZooming(), mZoomEnd, and Refresh().
Referenced by HandleZoom().
bool TrackPanel::HasSoloButton () [inline, private]
Referenced by DrawOutside(), HandleMutingSoloing(), and MuteSoloFunc().
void TrackPanel::HighlightFocusedTrack (wxDC * dc, const wxRect r) [private]
Draw a three-level highlight gradient around the focused track.
References kLeftInset, kTopInset, and AColor::TrackFocusPen().
Referenced by DrawEverythingElse().
bool TrackPanel::HitTestEnvelope (Track * track, wxRect & r, wxMouseEvent & event) [private]
Function that tells us if the mouse event landed on a envelope boundary.
References WaveTrack::GetDisplay(), WaveTrack::GetDisplayBounds(), WaveTrack::GetEnvelopeAtX(), Envelope::GetValueAtX(), GetWaveYPos(), ViewInfo::h, mdBr, mViewInfo, and ViewInfo::zoom.
Referenced by DetermineToolToUse().
bool TrackPanel::HitTestSamples (Track * track, wxRect & r, wxMouseEvent & event) [private]
Function that tells us if the mouse event landed on an editable sample
References floatSample, WaveTrack::Get(), WaveTrack::GetDisplay(), WaveTrack::GetDisplayBounds(), WaveTrack::GetEnvelopeAtX(), WaveTrack::GetRate(), Envelope::GetValue(), GetWaveYPos(), ViewInfo::h, mdBr, mViewInfo, and ViewInfo::zoom.
Referenced by DetermineToolToUse().
bool TrackPanel::HitTestSlide (Track * track, wxRect & r, wxMouseEvent & event) [private]
Function that tells us if the mouse event landed on a time-slider that allows us to time shift the sequence.
Referenced by DetermineToolToUse().
int TrackPanel::IdOfFormat (int format) [private]
Converts a format enumeration to a wxWidgets menu item Id.
References floatSample, int16Sample, int24Sample, and On24BitID.
Referenced by OnTrackMenu().
int TrackPanel::IdOfRate (int rate) [private]
Converts a sampling rate to a wxWidgets menu item id.
Referenced by OnTrackMenu().
bool TrackPanel::IsDragZooming () [private]
Determines if drag zooming is active.
References DragThreshold, mZoomEnd, and mZoomStart.
Referenced by DrawEverythingElse(), HandleVZoomButtonUp(), HandleVZoomDrag(), HandleZoomButtonUp(), and HandleZoomDrag().
bool TrackPanel::IsSampleEditingPossible (wxMouseEvent & event, Track * t) [private]
Determines if we can edit samples in a wave track. Also pops up warning messages in certain cases where we can't.
Returns:
true if we can edit the samples, false otherwise.
References Track::GetKind(), mViewInfo, Track::Wave, WaveTrack::WaveformDisplay, and ViewInfo::zoom.
Referenced by HandleSampleEditingClick().
bool TrackPanel::IsUnsafe () [private]
Used to determine whether it is safe or not to perform certain edits at the moment.
Returns:
true if audio is being recorded or is playing.
References gAudioIO, AudacityProject::GetAudioIOToken(), GetProject(), and AudioIO::IsStreamActive().
Referenced by OnTrackMenu(), SetCursorAndTipByTool(), and SetCursorByActivity().
void TrackPanel::MakeParentModifyState () [private]
References mListener, and TrackPanelListener::TP_ModifyState().
Referenced by ExtendSelection(), HandleLabelClick(), HandleMinimizing(), HandleResizeButtonUp(), HandleSelect(), HandleVZoomButtonUp(), OnBoundaryMove(), OnChangeOctave(), OnCursorLeft(), OnCursorMove(), OnCursorRight(), OnSetDisplay(), and StartSelection().
void TrackPanel::MakeParentPushState (wxString desc, wxString shortDesc, bool consolidate = false) [private]
Makes our Parent (well, whoever is listening to us) push their state. this causes application state to be preserved on a stack for undo ops.
References mListener, and TrackPanelListener::TP_PushState().
Referenced by HandleEnvelope(), HandleLabelTrackMouseEvent(), HandleRearrange(), HandleSampleEditingButtonUp(), HandleSlide(), HandleSliders(), HandleTrackLocationMouseEvent(), OnChannelChange(), OnChar(), OnCutSelectedText(), OnFormatChange(), OnKeyDown(), OnMergeStereo(), OnMoveTrack(), OnPasteSelectedText(), OnSetName(), OnSetTimeTrackRange(), OnTimer(), RemoveTrack(), SelectionHandleClick(), SetRate(), SetTrackGain(), SetTrackPan(), and SplitStereo().
void TrackPanel::MakeParentRedrawScrollbars () [private]
References mListener, and TrackPanelListener::TP_RedrawScrollbars().
Referenced by DoDrawIndicator(), HandleMinimizing(), HandleResizeButtonUp(), HandleSlide(), HandleWheelRotation(), HandleZoomButtonUp(), OnFormatChange(), OnRateChange(), OnRateOther(), OnTimer(), and RemoveTrack().
void TrackPanel::MakeParentResize () [private]
References mListener, and TrackPanelListener::TP_HandleResize().
Referenced by RemoveTrack().
bool TrackPanel::MinimizeFunc (Track * t, wxRect r, int x, int f) [private]
References TrackInfo::DrawMinimize(), Track::GetMinimized(), TrackInfo::GetMinimizeRect(), IsMinimizing, mCapturedRect, mTrackInfo, and SetCapturedTrack().
Referenced by HandleLabelClick().
bool TrackPanel::MoveClipToTrack (WaveClip * clip, WaveTrack * src, WaveTrack * dst) [private]
References WaveTrack::CanInsertClip(), TrackList::GetLink(), Track::GetLinked(), mCapturedClipArray, WaveTrack::MoveClipToTrack(), and mTracks.
Referenced by DoSlide().
bool TrackPanel::MuteSoloFunc (Track * t, wxRect r, int x, int y, bool solo) [private]
Mute or solo the given track (t). If solo is true, we're soloing, otherwise we're muting. Basically, check and see whether x and y fall within the area of the appropriate button.
References TrackInfo::DrawMuteSolo(), TrackInfo::GetMuteSoloRect(), HasSoloButton(), IsMuting, IsSoloing, mCapturedRect, mTrackInfo, and SetCapturedTrack().
Referenced by HandleLabelClick().
void TrackPanel::OnBoundaryMove (bool left, bool boundaryContract)
References gAudioIO, AudacityProject::GetAudioIOToken(), TrackList::GetEndTime(), GetFocusedTrack(), GetProject(), AudioIO::GetStreamTime(), AudioIO::IsStreamActive(), MakeParentModifyState(), mLastSelectionAdjustment, mTracks, mViewInfo, Refresh(), ScrollIntoView(), ViewInfo::sel0, ViewInfo::sel1, and ViewInfo::zoom.
Referenced by AudacityProject::OnSelSetExtendLeft(), and AudacityProject::OnSelSetExtendRight().
void TrackPanel::OnCaptureKey (wxCommandEvent & event)
Filter captured keys typed into LabelTracks.
References GetFocusedTrack(), Track::GetKind(), and Track::Label.
void TrackPanel::OnCaptureLost (wxMouseCaptureLostEvent & event)
Should handle the case when the mouse capture is lost.
References mMouseMostRecentX, mMouseMostRecentY, and OnMouseEvent().
void TrackPanel::OnChangeOctave (wxCommandEvent & event) [private]
This only applies to MIDI tracks. Presumably, it shifts the whole sequence by an octave.
References Track::GetKind(), MakeParentModifyState(), mPopupMenuTarget, Track::Note, and Refresh().
void TrackPanel::OnChannelChange (wxCommandEvent & event) [private]
References Track::GetName(), MakeParentPushState(), mPopupMenuTarget, Refresh(), and Track::SetChannel().
void TrackPanel::OnChar (wxKeyEvent & event)
Allow typing into LabelTracks.
References GetFocusedTrack(), Track::GetKind(), Track::Label, MakeParentPushState(), mViewInfo, Refresh(), RefreshTrack(), ViewInfo::sel0, and ViewInfo::sel1.
void TrackPanel::OnContextMenu (wxContextMenuEvent & event)
References OnTrackMenu().
void TrackPanel::OnCopySelectedText (wxCommandEvent & event) [private]
Copy selected text if copy menu item is selected.
References LabelTrack::CopySelectedText(), mPopupMenuTarget, and RefreshTrack().
void TrackPanel::OnCursorLeft (bool shift, bool ctrl)
References DrawCursor(), gAudioIO, AudacityProject::GetAudioIOToken(), GetFocusedTrack(), GetProject(), gPrefs, GridMove(), AudioIO::IsStreamActive(), MakeParentModifyState(), mLastSelectionAdjustment, mSeekLong, mSeekShort, mViewInfo, Refresh(), ScrollIntoView(), AudioIO::SeekStream(), ViewInfo::sel0, ViewInfo::sel1, and ViewInfo::zoom.
Referenced by AudacityProject::OnCursorLeft(), AudacityProject::OnSeekLeftLong(), AudacityProject::OnSeekLeftShort(), AudacityProject::OnSelContractRight(), and AudacityProject::OnSelExtendLeft().
void TrackPanel::OnCursorMove (bool forward, bool jump, bool longjump)
References DrawCursor(), gAudioIO, AudacityProject::GetAudioIOToken(), TrackList::GetEndTime(), GetProject(), AudioIO::IsStreamActive(), MakeParentModifyState(), mLastSelectionAdjustment, mSeekLong, mSeekShort, mTracks, mViewInfo, Refresh(), ScrollIntoView(), AudioIO::SeekStream(), ViewInfo::sel0, ViewInfo::sel1, and ViewInfo::zoom.
Referenced by AudacityProject::OnCursorLongJumpLeft(), AudacityProject::OnCursorLongJumpRight(), AudacityProject::OnCursorShortJumpLeft(), and AudacityProject::OnCursorShortJumpRight().
void TrackPanel::OnCursorRight (bool shift, bool ctrl)
References DrawCursor(), gAudioIO, AudacityProject::GetAudioIOToken(), TrackList::GetEndTime(), GetFocusedTrack(), GetProject(), gPrefs, GridMove(), AudioIO::IsStreamActive(), MakeParentModifyState(), mLastSelectionAdjustment, mSeekLong, mSeekShort, mTracks, mViewInfo, Refresh(), ScrollIntoView(), AudioIO::SeekStream(), ViewInfo::sel0, ViewInfo::sel1, and ViewInfo::zoom.
Referenced by AudacityProject::OnCursorRight(), AudacityProject::OnSeekRightLong(), AudacityProject::OnSeekRightShort(), AudacityProject::OnSelContractLeft(), and AudacityProject::OnSelExtendRight().
void TrackPanel::OnCutSelectedText (wxCommandEvent & event) [private]
Cut selected text if cut menu item is selected.
References LabelTrack::CutSelectedText(), MakeParentPushState(), mPopupMenuTarget, and RefreshTrack().
void TrackPanel::OnErase (wxEraseEvent & event)
OnErase() is called during the normal course of completing an erase operation.
void TrackPanel::OnFormatChange (wxCommandEvent & event) [private]
Handles the selection from the Format submenu of the track menu.
References floatSample, Track::GetKind(), TrackList::GetLink(), Track::GetName(), GetSampleFormatStr(), int16Sample, int24Sample, MakeParentPushState(), MakeParentRedrawScrollbars(), mFormatMenu, mPopupMenuTarget, mTracks, On24BitID, Refresh(), SetMenuCheck(), and Track::Wave.
void TrackPanel::OnKeyDown (wxKeyEvent & event)
Allow typing into LabelTracks.
References LabelTrack::CalcCursorX(), GetFocusedTrack(), Track::GetKind(), Track::Label, MakeParentPushState(), mViewInfo, LabelTrack::OnKeyDown(), Refresh(), RefreshTrack(), ScrollIntoView(), ViewInfo::sel0, and ViewInfo::sel1.
void TrackPanel::OnKillFocus (wxFocusEvent & event)
References Refresh().
void TrackPanel::OnMergeStereo (wxCommandEvent & event) [private]
Merge two tracks into one stereo track ??
References Track::GetKind(), Track::GetLink(), Track::GetName(), ODManager::Instance(), ODManager::IsInstanceCreated(), Track::LeftChannel, MakeParentPushState(), ODManager::MakeWaveTrackDependent(), Track::Merge(), mPopupMenuTarget, Refresh(), Track::RightChannel, Track::SetChannel(), Track::SetLinked(), and Track::Wave.
void TrackPanel::OnMouseEvent (wxMouseEvent & event)
This handles just generic mouse events. Then, based on our current state, we forward the mouse events to various interested parties.
References EnsureVisible(), FindTrack(), HandleClosing(), HandleCursor(), HandleLabelTrackMouseEvent(), HandleMinimizing(), HandleMutingSoloing(), HandlePopping(), HandleRearrange(), HandleResize(), HandleSliders(), HandleTrackSpecificMouseEvent(), HandleVZoom(), HandleWheelRotation(), HandleZoom(), IsAdjustingLabel, IsClosing, IsGainSliding, IsMinimizing, IsMuting, IsPanSliding, IsPopping, IsRearranging, IsResizing, IsResizingBelowLinkedTracks, IsResizingBetweenLinkedTracks, IsSoloing, IsVZooming, IsZooming, kTimerInterval, mAutoScrolling, mCapturedRect, mCapturedTrack, mMouseCapture, mMouseMostRecentX, mMouseMostRecentY, and mTimer.
Referenced by OnCaptureLost().
void TrackPanel::OnMoveTrack (wxCommandEvent & event) [private]
AS: Move a track up or down, depending.
References Track::GetKind(), GetMixerBoard(), Track::GetName(), MakeParentPushState(), TrackList::Move(), MixerBoard::MoveTrackCluster(), mPopupMenuTarget, mTracks, Refresh(), and Track::Wave.
void TrackPanel::OnNextTrack (bool shift = false)
The following function moves to the next track, selecting and unselecting depending if you are on the start of a block or not.
References EnsureVisible(), TrackListIterator::First(), GetFocusedTrack(), TrackList::GetNext(), Track::GetSelected(), mCircularTrackNavigation, mTracks, TrackList::Select(), and SetFocusedTrack().
Referenced by AudacityProject::OnCursorDown(), and AudacityProject::OnShiftDown().
void TrackPanel::OnPaint (wxPaintEvent & event)
AS: OnPaint() is called during the normal course of completing a repaint operation.
References DoDrawCursor(), DoDrawIndicator(), DrawTracks(), gAudioIO, AudacityProject::GetAudioIOToken(), GetProject(), AudioIO::IsPaused(), AudioIO::IsStreamActive(), mBacking, mBackingDC, mIndicatorShowing, mRefreshBacking, mViewInfo, ViewInfo::sel0, and ViewInfo::sel1.
void TrackPanel::OnPasteSelectedText (wxCommandEvent & event) [private]
paste selected text if p`aste menu item is selected
References MakeParentPushState(), mPopupMenuTarget, mViewInfo, LabelTrack::PasteSelectedText(), RefreshTrack(), ViewInfo::sel0, and ViewInfo::sel1.
void TrackPanel::OnPrevTrack (bool shift = false)
The following function moves to the previous track selecting and unselecting depending if you are on the start of a block or not.
Todo:
Merge related functions, TrackPanel::OnPrevTrack and TrackPanel::OnNextTrack.
References EnsureVisible(), TrackListIterator::First(), GetFocusedTrack(), TrackList::GetPrev(), Track::GetSelected(), TrackListIterator::Last(), mCircularTrackNavigation, mTracks, TrackListIterator::Next(), TrackList::Select(), and SetFocusedTrack().
Referenced by AudacityProject::OnCursorUp(), and AudacityProject::OnShiftUp().
void TrackPanel::OnRateChange (wxCommandEvent & event) [private]
This function handles the selection from the Rate submenu of the track menu, except for "Other" (/see OnRateOther).
References Track::GetKind(), MakeParentRedrawScrollbars(), mPopupMenuTarget, mRateMenu, Refresh(), SetMenuCheck(), SetRate(), and Track::Wave.
void TrackPanel::OnRateOther (wxCommandEvent & event) [private]
Todo:
Remove artificial constants!!
Todo:
Make a real dialog box out of this!!
References ShuttleGuiBase::AddCombo(), ShuttleGui::AddStandardButtons(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndVerticalLay(), Track::GetKind(), MakeParentRedrawScrollbars(), mPopupMenuTarget, mRateMenu, Refresh(), SetMenuCheck(), SetRate(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartVerticalLay(), and Track::Wave.
void TrackPanel::OnSetDisplay (wxCommandEvent & event) [private]
Set the Display mode based on the menu choice in the Track Menu. Note that gModes MUST BE IN THE SAME ORDER AS THE MENU CHOICES!! const wxChar *gModes[] = { wxT("waveform"), wxT("waveformDB"), wxT("spectrum"), wxT("pitch") };
References WaveTrack::GetDisplay(), Track::GetKind(), Track::GetLink(), TrackArtist::InvalidateSpectrumCache(), MakeParentModifyState(), mPopupMenuTarget, mTrackArtist, Refresh(), WaveTrack::SetDisplay(), UpdateVRuler(), and Track::Wave.
void TrackPanel::OnSetFocus (wxFocusEvent & event)
References GetFocusedTrack(), Refresh(), and SetFocusedTrack().
void TrackPanel::OnSetFont (wxCommandEvent & event) [private]
References ShuttleGuiBase::AddPrompt(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddWindow(), eIsCreating, ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndVerticalLay(), gPrefs, Refresh(), LabelTrack::ResetFont(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::SetStretchyRow(), ShuttleGuiBase::StartMultiColumn(), and ShuttleGuiBase::StartVerticalLay().
void TrackPanel::OnSetName (wxCommandEvent & event) [private]
References Track::GetKind(), GetMixerBoard(), Track::GetName(), MakeParentPushState(), mPopupMenuTarget, Refresh(), Track::SetName(), MixerBoard::UpdateName(), and Track::Wave.
void TrackPanel::OnSetTimeTrackRange (wxCommandEvent & event) [private]
References TimeTrack::GetRangeLower(), TimeTrack::GetRangeUpper(), MakeParentPushState(), mPopupMenuTarget, Refresh(), TimeTrack::SetRangeLower(), and TimeTrack::SetRangeUpper().
void TrackPanel::OnSize (wxSizeEvent & event)
OnSize() is called when the panel is resized.
References mBacking, mBackingDC, and Refresh().
void TrackPanel::OnSplitStereo (wxCommandEvent & event) [private]
Split a stereo track into two tracks...
References SplitStereo().
void TrackPanel::OnSplitStereoMono (wxCommandEvent & event) [private]
Split a stereo track into two mono tracks...
References SplitStereo().
void TrackPanel::OnTimer ()
AS: This gets called on our wx timer events.
References DisplaySelection(), DrawIndicator(), TrackListIterator::First(), gAudioIO, AudacityProject::GetAudioIOToken(), AudacityProject::GetControlToolBar(), LyricsWindow::GetLyricsPanel(), AudacityProject::GetLyricsWindow(), GetMixerBoard(), AudioIO::GetNumCaptureChannels(), GetProject(), AudacityProject::GetSel0(), AudioIO::GetStreamTime(), AudioIO::IsAudioTokenActive(), AudioIO::IsPaused(), IsSelecting, AudioIO::IsStreamActive(), AudacityProject::IsTimerRecordCancelled(), loopedPlay, MakeParentPushState(), MakeParentRedrawScrollbars(), mCapturedTrack, mIndicatorShowing, AudacityProject::mLastPlayMode, mListener, mMouseCapture, mRedrawAfterStop, mRefreshBacking, mTimeCount, mTracks, TrackListIterator::Next(), AudacityProject::OnUndo(), AudacityProject::RedrawProject(), Refresh(), MixerBoard::ResetMeters(), AudacityProject::ResetTimerRecordFlag(), ScrollDuringDrag(), AudacityProject::SetAudioIOToken(), ControlToolBar::StopPlaying(), TrackPanelListener::TP_ScrollUpDown(), Lyrics::Update(), MixerBoard::UpdateMeters(), and Track::Wave.
void TrackPanel::OnToggle ()
References EnsureVisible(), GetFocusedTrack(), Track::GetSelected(), mTracks, and TrackList::Select().
Referenced by AudacityProject::OnToggle().
void TrackPanel::OnTrackClose ()
References gAudioIO, GetFocusedTrack(), GetProject(), TrackList::IsEmpty(), AudioIO::IsStreamActive(), mListener, mTracks, mViewInfo, Refresh(), RemoveTrack(), ViewInfo::sel0, ViewInfo::sel1, SetCapturedTrack(), TrackPanelListener::TP_DisplayStatusMessage(), TrackPanelListener::TP_RedrawScrollbars(), and ViewInfo::zoom.
Referenced by AudacityProject::OnTrackClose().
void TrackPanel::OnTrackGain ()
This will pop up the track gain dialog for specified track.
References GetFocusedTrack(), Track::GetIndex(), Track::GetKind(), TrackInfo::mGains, mTrackInfo, SetTrackGain(), LWSlider::ShowDialog(), and Track::Wave.
Referenced by AudacityProject::OnTrackGain().
void TrackPanel::OnTrackGainDec ()
References LWSlider::Decrease(), GetFocusedTrack(), Track::GetIndex(), Track::GetKind(), TrackInfo::mGains, mTrackInfo, SetTrackGain(), and Track::Wave.
Referenced by AudacityProject::OnTrackGainDec().
void TrackPanel::OnTrackGainInc ()
References GetFocusedTrack(), Track::GetIndex(), Track::GetKind(), LWSlider::Increase(), TrackInfo::mGains, mTrackInfo, SetTrackGain(), and Track::Wave.
Referenced by AudacityProject::OnTrackGainInc().
void TrackPanel::OnTrackListResized (wxCommandEvent & event)
References UpdateVRuler().
Referenced by OnTrackListUpdated(), TrackPanel(), and ~TrackPanel().
void TrackPanel::OnTrackListUpdated (wxCommandEvent & event)
References TrackList::Contains(), GetFocusedTrack(), mTracks, OnTrackListResized(), and SetFocusedTrack().
Referenced by TrackPanel(), and ~TrackPanel().
void TrackPanel::OnTrackMenu (Track * t = NULL)
References TrackList::CanMoveDown(), TrackList::CanMoveUp(), FindTrackRect(), Track::GetChannel(), GetFocusedTrack(), Track::GetKind(), Track::GetLinked(), TrackList::GetNext(), WaveTrack::GetRate(), WaveTrack::GetSampleFormat(), TrackInfo::GetTitleBarRect(), IdOfFormat(), IdOfRate(), IsUnsafe(), Track::Label, Track::LeftChannel, mFormatMenu, mLabelTrackMenu, mNoteTrackMenu, Track::MonoChannel, mPopupMenuTarget, mRateMenu, mTimeTrackMenu, mTrackInfo, mTracks, mWaveTrackMenu, Track::Note, OnChannelRightID, OnSpectrumID, OnSpectrumLogID, OnWaveformDBID, WaveTrack::PitchDisplay, Refresh(), Track::RightChannel, SetCapturedTrack(), SetMenuCheck(), WaveTrack::SpectrumDisplay, WaveTrack::SpectrumLogDisplay, Track::Time, Track::Wave, WaveTrack::WaveformDBDisplay, and WaveTrack::WaveformDisplay.
Referenced by HandlePopping(), and OnContextMenu().
void TrackPanel::OnTrackMute (bool shiftdown, Track * t = NULL)
References GetFocusedTrack(), Track::GetKind(), GetMixerBoard(), GetProject(), AudacityProject::HandleTrackMute(), mAx, Refresh(), TrackPanelAx::Updated(), MixerBoard::UpdateMute(), MixerBoard::UpdateSolo(), and Track::Wave.
Referenced by HandleMutingSoloing(), and AudacityProject::OnTrackMute().
void TrackPanel::OnTrackPan ()
References GetFocusedTrack(), Track::GetIndex(), Track::GetKind(), TrackInfo::mPans, mTrackInfo, SetTrackPan(), LWSlider::ShowDialog(), and Track::Wave.
Referenced by AudacityProject::OnTrackPan().
void TrackPanel::OnTrackPanLeft ()
References LWSlider::Decrease(), GetFocusedTrack(), Track::GetIndex(), Track::GetKind(), TrackInfo::mPans, mTrackInfo, SetTrackPan(), and Track::Wave.
Referenced by AudacityProject::OnTrackPanLeft().
void TrackPanel::OnTrackPanRight ()
References GetFocusedTrack(), Track::GetIndex(), Track::GetKind(), LWSlider::Increase(), TrackInfo::mPans, mTrackInfo, SetTrackPan(), and Track::Wave.
Referenced by AudacityProject::OnTrackPanRight().
void TrackPanel::OnTrackSolo (bool shiftdown, Track * t = NULL)
References GetFocusedTrack(), Track::GetKind(), GetMixerBoard(), GetProject(), AudacityProject::HandleTrackSolo(), mAx, Refresh(), TrackPanelAx::Updated(), MixerBoard::UpdateMute(), MixerBoard::UpdateSolo(), and Track::Wave.
Referenced by HandleMutingSoloing(), and AudacityProject::OnTrackSolo().
bool TrackPanel::PanFunc (Track * t, wxRect r, wxMouseEvent & event, int x, int y) [private]
References TrackInfo::GetPanRect(), HandleSliders(), IsPanSliding, mCapturedRect, mTrackInfo, and SetCapturedTrack().
Referenced by HandleLabelClick().
bool TrackPanel::PopupFunc (Track * t, wxRect r, int x, int y) [private]
References TrackInfo::DrawTitleBar(), TrackInfo::GetTitleBarRect(), IsPopping, mCapturedRect, mTrackInfo, and SetCapturedTrack().
Referenced by HandleLabelClick().
double TrackPanel::PositionToTime (wxInt64 mouseXCoordinate, wxInt64 trackLeftEdge) const [private]
Converts a position (mouse X coordinate) to project time, in seconds. Needs the left edge of the track as an additional parameter.
References ViewInfo::h, mViewInfo, and ViewInfo::zoom.
Referenced by DoZoomInOut(), DragZoom(), ExtendSelection(), HandleSampleEditingClick(), HandleSampleEditingDrag(), HandleWheelRotation(), ScrollIntoView(), SelectionHandleClick(), and StartSlide().
void TrackPanel::Refresh (bool eraseBackground = true, const wxRect * rect = (const wxRect *) NULL) [virtual]
This function overrides Refresh() of wxWindow so that the boolean play indicator can be set to false, so that an old play indicator that is no longer there won't get XORed (to erase it), thus redrawing it on the TrackPanel
References DisplaySelection(), and mRefreshBacking.
Referenced by AudacityProject::AddImportedTracks(), AudacityProject::AS_ModifySelection(), DoSlide(), EnsureVisible(), ExtendSelection(), AudacityProject::FixScrollbars(), HandleClosing(), HandleLabelClick(), HandleMinimizing(), HandleMutingSoloing(), HandleResizeDrag(), HandleSelect(), HandleVZoomButtonUp(), HandleVZoomDrag(), HandleWheelRotation(), HandleZoomButtonUp(), HandleZoomDrag(), OnBoundaryMove(), EditToolBar::OnButton(), OnChangeOctave(), OnChannelChange(), OnChar(), AudacityProject::OnCopy(), AudacityProject::OnCopyLabels(), OnCursorLeft(), OnCursorMove(), OnCursorRight(), AudacityProject::OnCursorSelEnd(), AudacityProject::OnCursorSelStart(), AudacityProject::OnCursorTrackEnd(), AudacityProject::OnCursorTrackStart(), AudacityProject::OnCut(), AudacityProject::OnEffect(), OnFormatChange(), OnKeyDown(), OnKillFocus(), OnMergeStereo(), OnMoveTrack(), AudacityProject::OnNextTool(), AudacityProject::OnODTaskComplete(), AudacityProject::OnODTaskUpdate(), AudacityProject::OnPrevTool(), OnRateChange(), OnRateOther(), AudacityProject::OnRemoveTracks(), AudacityProject::OnScroll(), AudacityProject::OnSelectAll(), AudacityProject::OnSelectCursorEnd(), AudacityProject::OnSelectionRestore(), AudacityProject::OnSelectStartCursor(), OnSetDisplay(), OnSetFocus(), OnSetFont(), AudacityProject::OnSetLeftSelection(), OnSetName(), AudacityProject::OnSetRightSelection(), OnSetTimeTrackRange(), AudacityProject::OnShowClipping(), AudacityProject::OnSilence(), AudacityProject::OnSilenceLabels(), OnSize(), AudacityProject::OnSortName(), AudacityProject::OnSortTime(), AudacityProject::OnSplit(), OnTimer(), OnTrackClose(), OnTrackMenu(), OnTrackMute(), OnTrackSolo(), AudacityProject::OnZeroCrossing(), AudacityProject::OnZoomIn(), AudacityProject::OnZoomNormal(), AudacityProject::OpenFile(), AudacityProject::RedrawProject(), RefreshTrack(), RemoveTrack(), ScrollIntoView(), AudacityProject::SelectNone(), SetFocusedTrack(), AudacityProject::SetStateTo(), SetStop(), AudacityProject::SetTool(), AudacityProject::SkipEnd(), SplitStereo(), UpdatePrefs(), and UpdateVRulerSize().
void TrackPanel::RefreshTrack (Track * trk, bool refreshbacking = true)
References Track::GetHeight(), Track::GetLink(), Track::GetLinked(), Track::GetY(), kLeftInset, kTopInset, mRefreshBacking, mViewInfo, Refresh(), and ViewInfo::vpos.
Referenced by ForwardEventToTimeTrackEnvelope(), ForwardEventToWaveTrackEnvelope(), HandleLabelTrackMouseEvent(), HandleSampleEditingClick(), HandleSampleEditingDrag(), HandleSliders(), HandleTrackLocationMouseEvent(), OnChar(), OnCopySelectedText(), OnCutSelectedText(), OnKeyDown(), OnPasteSelectedText(), AudacityProject::RefreshTPTrack(), SetCursorAndTipWhenInLabelTrack(), SetTrackGain(), and SetTrackPan().
void TrackPanel::RemoveTrack (Track * toRemove) [private]
Removes the specified track. Called from HandleClosing.
References GetFocusedTrack(), Track::GetKind(), Track::GetLink(), GetMixerBoard(), Track::GetName(), TrackList::GetNext(), TrackList::GetPrev(), TrackList::IsEmpty(), MakeParentPushState(), MakeParentRedrawScrollbars(), MakeParentResize(), mTracks, name, Refresh(), TrackList::Remove(), MixerBoard::RemoveTrackCluster(), SetFocusedTrack(), and Track::Wave.
Referenced by HandleClosing(), and OnTrackClose().
void TrackPanel::ScrollDuringDrag () [private]
We check on each timer tick to see if we need to scroll. Scrolling is handled by mListener, which is an interface to the window TrackPanel is embedded in.
References HandleSelect(), mAutoScrolling, mCapturedRect, mListener, mMouseMostRecentX, TrackPanelListener::TP_ScrollLeft(), and TrackPanelListener::TP_ScrollRight().
Referenced by OnTimer().
void TrackPanel::ScrollIntoView (int x)
References GetLeftOffset(), PositionToTime(), and ScrollIntoView().
void TrackPanel::ScrollIntoView (double pos)
References GetTracksUsableArea(), ViewInfo::h, mListener, mViewInfo, Refresh(), TrackPanelListener::TP_ScrollWindow(), and ViewInfo::zoom.
Referenced by OnBoundaryMove(), OnCursorLeft(), OnCursorMove(), OnCursorRight(), AudacityProject::OnCursorSelEnd(), AudacityProject::OnCursorSelStart(), AudacityProject::OnCursorTrackEnd(), AudacityProject::OnCursorTrackStart(), OnKeyDown(), AudacityProject::OnPaste(), AudacityProject::OnZoomIn(), ScrollIntoView(), and AudacityProject::SkipEnd().
void TrackPanel::SelectionHandleClick (wxMouseEvent & event, Track * pTrack, wxRect r) [private]
This function gets called when we're handling selection and the mouse was just clicked.
References ODManager::DemandTrackUpdate(), DisplaySelection(), ExtendSelection(), TrackListIterator::First(), gAudioIO, GetActiveProject(), AudacityProject::GetControlToolBar(), Track::GetKind(), GetLeftOffset(), Track::GetSelected(), ViewInfo::h, LabelTrack::HandleMouse(), ODManager::Instance(), AudioIO::IsBusy(), ODManager::IsInstanceCreated(), LabelTrack::IsSelected(), IsSelecting, Track::Label, mAdjustSelectionEdges, MakeParentPushState(), mCapturedRect, mCapturedTrack, mMouseCapture, mMouseClickX, mMouseClickY, mSelStart, mSnapLeft, mSnapManager, mSnapRight, mTracks, mViewInfo, TrackListIterator::Next(), ControlToolBar::PlayPlayRegion(), PositionToTime(), ViewInfo::sel0, ViewInfo::sel1, TrackList::Select(), SELECTION_RESIZE_REGION, SelectNone(), SelectTracksByLabel(), SetFocusedTrack(), ControlToolBar::SetPlay(), Track::SetSelected(), StartSelection(), ControlToolBar::StopPlaying(), TimeToPosition(), ViewInfo::total, Track::Wave, within(), and ViewInfo::zoom.
Referenced by HandleSelect().
void TrackPanel::SelectionHandleDrag (wxMouseEvent & event, Track * clickedTrack) [private]
AS: If we're dragging to extend a selection (or actually, if the screen is scrolling while you're selecting), we handle it here.
References ExtendSelection(), FindTrack(), Track::GetIndex(), IsSelecting, mAutoScrolling, mCapturedRect, mCapturedTrack, mMouseCapture, mMouseMostRecentX, mMouseMostRecentY, mSelStart, mTracks, TrackListIterator::Next(), TrackList::Select(), TrackListIterator::StartWith(), and TimeToPosition().
Referenced by HandleSelect().
void TrackPanel::SelectNone ()
References TrackListIterator::First(), Track::GetKind(), Track::Label, mTracks, TrackListIterator::Next(), and Track::SetSelected().
Referenced by HandleLabelClick(), HandleSelect(), and SelectionHandleClick().
void TrackPanel::SelectTrackLength (Track * t) [private]
Set selection length to the length of a track -- but if linking is turned on, use the largest possible selection in the group. And if it's a stereo track, do the same for the stereo channels.
References TrackGroupIterator::First(), GetActiveProject(), Track::GetEndTime(), Track::GetLink(), Track::GetOffset(), AudacityProject::IsSticky(), mTracks, mViewInfo, TrackGroupIterator::Next(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by HandleLabelClick(), and HandleSelect().
void TrackPanel::SelectTracksByLabel (LabelTrack * t) [private]
Select all tracks marked by the label track lt.
References TrackListIterator::First(), Track::GetSelected(), mTracks, TrackListIterator::Next(), and Track::SetSelected().
Referenced by SelectionHandleClick().
void TrackPanel::SetCapturedTrack (Track * t, enum MouseCaptureEnum MouseCapture = IsUncaptured) [private]
Remembers the track we clicked on and why we captured it. We also use this function to clear the record of the captured track, passing NULL as the track.
References IsUncaptured, mCapturedTrack, and mMouseCapture.
Referenced by CloseFunc(), GainFunc(), HandleClosing(), HandleLabelClick(), HandleLabelTrackMouseEvent(), HandleMinimizing(), HandleMutingSoloing(), HandlePopping(), HandleRearrange(), HandleResizeButtonUp(), HandleResizeClick(), HandleSelect(), HandleSlide(), HandleSliders(), HandleTrackLocationMouseEvent(), HandleZoomButtonUp(), HandleZoomClick(), MinimizeFunc(), MuteSoloFunc(), OnTrackClose(), OnTrackMenu(), PanFunc(), and PopupFunc().
void TrackPanel::SetCursorAndTipByTool (int tool, wxMouseEvent & event, const wxChar ** ppTip) [private]
In this function we know what tool we are using, so set the cursor accordingly.
References drawTool, envelopeTool, IsUnsafe(), mDisabledCursor, mEnvelopeCursor, mPencilCursor, mSlideCursor, mSmoothCursor, mZoomInCursor, mZoomOutCursor, selectTool, slideTool, and zoomTool.
Referenced by HandleCursor().
void TrackPanel::SetCursorAndTipWhenInLabel (Track * t, wxMouseEvent & event, const wxChar ** ppTip) [private]
When in the label, we can either vertical zoom or re-order tracks. Dont't change cursor/tip to zoom if display is not waveform (either linear of dB) or Spectrum
References Track::GetKind(), GetVRulerOffset(), mArrowCursor, mZoomInCursor, mZoomOutCursor, WaveTrack::SpectrumDisplay, WaveTrack::SpectrumLogDisplay, and Track::Wave.
Referenced by HandleCursor().
void TrackPanel::SetCursorAndTipWhenInLabelTrack (LabelTrack * pLT, wxMouseEvent & event, const wxChar ** ppTip) [private]
When in a label track, find out if we've hit anything that would cause a cursor change.
References mArrowCursor, LabelTrack::mbHitCenter, LabelTrack::mOldEdge, LabelTrack::OverGlyph(), and RefreshTrack().
Referenced by HandleCursor().
void TrackPanel::SetCursorAndTipWhenInVResizeArea (Track * label, bool blinked, const wxChar ** ppTip) [private]
When in the resize area we can adjust size or relative size.
References mResizeCursor.
Referenced by HandleCursor().
void TrackPanel::SetCursorAndTipWhenSelectTool (Track * t, wxMouseEvent & event, wxRect & r, bool bMultiToolMode, const wxChar ** ppTip) [private]
References ODManager::FillTipForWaveTrack(), Track::GetKind(), Track::GetSelected(), ODManager::Instance(), ODManager::IsInstanceCreated(), mAdjustLeftSelectionCursor, mAdjustRightSelectionCursor, mAdjustSelectionEdges, mSelectCursor, mViewInfo, ViewInfo::sel0, ViewInfo::sel1, SELECTION_RESIZE_REGION, TimeToPosition(), Track::Wave, and within().
Referenced by HandleCursor().
bool TrackPanel::SetCursorByActivity () [private]
References IsAdjustingLabel, IsEnveloping, IsOverCutLine, IsRearranging, IsSelecting, IsSliding, IsUnsafe(), mArrowCursor, mDisabledCursor, mEnvelopeCursor, mMouseCapture, mRearrangeCursor, mSelectCursor, and mSlideCursor.
Referenced by HandleCursor(), and HandleTrackLocationMouseEvent().
void TrackPanel::SetFocusedTrack (Track * t)
References GetActiveProject(), Track::GetKind(), Track::GetLink(), Track::GetLinked(), AudacityProject::HasKeyboardCapture(), Track::Label, mAx, Refresh(), and TrackPanelAx::SetFocus().
Referenced by EnsureVisible(), HandleLabelClick(), AudacityProject::HandleMixAndRender(), OnNextTrack(), OnPrevTrack(), AudacityProject::OnRedo(), OnSetFocus(), OnTrackListUpdated(), AudacityProject::OnUndo(), AudacityProject::OpenFile(), RemoveTrack(), SelectionHandleClick(), and AudacityProject::SetStateTo().
void TrackPanel::SetMenuCheck (wxMenu & menu, int newId) [private]
Puts a check mark at a given position in a menu, clearing all other check marks.
Referenced by OnFormatChange(), OnRateChange(), OnRateOther(), and OnTrackMenu().
void TrackPanel::SetRate (Track * pTrack, double rate) [private]
Sets the sample rate for a track, and if it is linked to another track, that one as well.
References TrackList::GetLink(), Track::GetName(), MakeParentPushState(), and mTracks.
Referenced by OnRateChange(), and OnRateOther().
void TrackPanel::SetSelectionFormat (int iformat)
void TrackPanel::SetSnapTo (int snapto)
void TrackPanel::SetStop (bool bStopped)
References ViewInfo::bIsPlaying, mViewInfo, and Refresh().
Referenced by AudacityProject::SetStop().
void TrackPanel::SetTrackGain (Track * t, LWSlider * s) [private]
References LWSlider::Get(), TrackList::GetLink(), MakeParentPushState(), mTracks, RefreshTrack(), and WaveTrack::SetGain().
Referenced by OnTrackGain(), OnTrackGainDec(), and OnTrackGainInc().
void TrackPanel::SetTrackPan (Track * t, LWSlider * s) [private]
References LWSlider::Get(), TrackList::GetLink(), MakeParentPushState(), mTracks, RefreshTrack(), and WaveTrack::SetPan().
Referenced by OnTrackPan(), OnTrackPanLeft(), and OnTrackPanRight().
void TrackPanel::SplitStereo (bool stereo) [private]
Split a stereo track into two tracks...
References Track::GetKind(), Track::GetLink(), Track::GetName(), ODManager::Instance(), ODManager::IsInstanceCreated(), MakeParentPushState(), ODManager::MakeWaveTrackIndependent(), Track::MonoChannel, mPopupMenuTarget, Refresh(), Track::SetChannel(), Track::SetLinked(), Track::SetName(), and Track::Wave.
Referenced by OnSplitStereo(), and OnSplitStereoMono().
void TrackPanel::StartSelection (int mouseXCoordinate, int trackLeftEdge) [private]
Reset our selection markers.
References ViewInfo::h, MakeParentModifyState(), mCapturedTrack, mSelStart, mSnapLeft, mSnapManager, mSnapRight, mViewInfo, ViewInfo::sel0, ViewInfo::sel1, SnapManager::Snap(), TimeToPosition(), and ViewInfo::zoom.
Referenced by SelectionHandleClick().
void TrackPanel::StartSlide (wxMouseEvent & event) [private]
Prepare for sliding.
References AddClipsToCaptured(), FindTrack(), TrackGroupIterator::First(), TrackListIterator::First(), WaveTrack::GetClipAtX(), WaveClip::GetEndTime(), Track::GetKind(), GetLeftOffset(), TrackList::GetLink(), GetProject(), Track::GetSelected(), WaveClip::GetStartTime(), ViewInfo::h, ToolsToolBar::IsDown(), IsSliding, mCapturedClip, mCapturedClipArray, mCapturedClipIsSelection, mCapturedRect, mCapturedTrack, mDidSlideVertically, mHSlideAmount, mListener, mMouseCapture, mMouseClickX, mMouseClickY, mSelStart, mSlideUpDownOnly, mSnapLeft, mSnapManager, mSnapPreferRightEdge, mSnapRight, mTracks, multiTool, mViewInfo, TrackGroupIterator::Next(), TrackListIterator::Next(), PositionToTime(), ViewInfo::sel0, ViewInfo::sel1, TrackPanelListener::TP_GetToolsToolBar(), Track::Wave, and ViewInfo::zoom.
Referenced by HandleSelect(), and HandleSlide().
wxInt64 TrackPanel::TimeToPosition (double time, wxInt64 trackLeftEdge) const [private]
STM: Converts a project time to screen x position.
References ViewInfo::h, mViewInfo, and ViewInfo::zoom.
Referenced by DoSlide(), ExtendSelection(), SelectionHandleClick(), SelectionHandleDrag(), SetCursorAndTipWhenSelectTool(), and StartSelection().
wxString TrackPanel::TrackSubText (Track * t) [private]
Returns the string to be displayed in the track label indicating whether the track is mono, left, right, or stereo and what sample rate it's using.
References Track::GetChannel(), Track::GetLinked(), Track::LeftChannel, Track::MonoChannel, and Track::RightChannel.
Referenced by DrawOutside().
void TrackPanel::UpdatePrefs ()
References ViewInfo::bUpdateTrackIndicator, ENV_DB_RANGE, gPrefs, mAdjustSelectionEdges, mCircularTrackNavigation, mdBr, mSeekLong, mSeekShort, mSoloPref, mTrackArtist, mViewInfo, Refresh(), TrackArtist::UpdatePrefs(), and UpdateVRulers().
Referenced by AudacityProject::OnShowClipping(), TrackPanel(), and AudacityProject::UpdatePrefs().
void TrackPanel::UpdateTrackVRuler (Track * t)
References Track::GetHeight(), Track::GetLink(), GetVRulerOffset(), GetVRulerWidth(), kTopInset, mTrackArtist, and TrackArtist::UpdateVRuler().
Referenced by UpdateVRuler(), and UpdateVRulers().
void TrackPanel::UpdateVRuler (Track * t)
References UpdateTrackVRuler(), and UpdateVRulerSize().
Referenced by HandleVZoomButtonUp(), OnSetDisplay(), and OnTrackListResized().
void TrackPanel::UpdateVRulers ()
References TrackListCondIterator::First(), mTracks, TrackListCondIterator::Next(), UpdateTrackVRuler(), UpdateVRulerSize(), and Track::Wave.
Referenced by UpdatePrefs().
void TrackPanel::UpdateVRulerSize ()
References TrackListIterator::First(), GetLeftOffset(), mRuler, mTracks, TrackListIterator::Next(), Refresh(), AdornedRulerPanel::SetLeftOffset(), vrulerSize, and Track::vrulerSize.
Referenced by UpdateVRuler(), and UpdateVRulers().
Friends And Related Function Documentation
friend class ScreenshotCommand [friend]
friend class TrackPanelAx [friend]
Referenced by TrackPanel().
Member Data Documentation
wxCursor* TrackPanel::mAdjustLeftSelectionCursor [private]
Referenced by SetCursorAndTipWhenSelectTool(), TrackPanel(), and ~TrackPanel().
wxCursor* TrackPanel::mAdjustRightSelectionCursor [private]
Referenced by SetCursorAndTipWhenSelectTool(), TrackPanel(), and ~TrackPanel().
bool TrackPanel::mAdjustSelectionEdges [private]
Referenced by SelectionHandleClick(), SetCursorAndTipWhenSelectTool(), and UpdatePrefs().
wxCursor* TrackPanel::mArrowCursor [private]
Referenced by HandleCursor(), HandleRearrange(), SetCursorAndTipWhenInLabel(), SetCursorAndTipWhenInLabelTrack(), SetCursorByActivity(), TrackPanel(), and ~TrackPanel().
bool TrackPanel::mAutoScrolling [private]
Referenced by OnMouseEvent(), ScrollDuringDrag(), and SelectionHandleDrag().
TrackPanelAx* TrackPanel::mAx [private]
Referenced by DoDrawCursor(), DrawEverythingElse(), GetFocusedTrack(), OnTrackMute(), OnTrackSolo(), SetFocusedTrack(), TrackPanel(), and ~TrackPanel().
wxBitmap* TrackPanel::mBacking [private]
Referenced by DoDrawCursor(), DoDrawIndicator(), OnPaint(), OnSize(), and ~TrackPanel().
wxMemoryDC TrackPanel::mBackingDC [private]
Referenced by DoDrawCursor(), DoDrawIndicator(), OnPaint(), OnSize(), and ~TrackPanel().
WaveClip* TrackPanel::mCapturedClip [private]
Referenced by DoSlide(), and StartSlide().
TrackClipArray TrackPanel::mCapturedClipArray [private]
Referenced by AddClipsToCaptured(), DoSlide(), HandleSelect(), MoveClipToTrack(), and StartSlide().
bool TrackPanel::mCapturedClipIsSelection [private]
Referenced by DoSlide(), and StartSlide().
Envelope* TrackPanel::mCapturedEnvelope [private]
Referenced by ForwardEventToWaveTrackEnvelope(), and HandleEnvelope().
wxRect TrackPanel::mCapturedRect [private]
Referenced by CloseFunc(), ForwardEventToTimeTrackEnvelope(), ForwardEventToWaveTrackEnvelope(), GainFunc(), HandleClosing(), HandleEnvelope(), HandleLabelTrackMouseEvent(), HandleMinimizing(), HandleMutingSoloing(), HandlePopping(), HandleVZoomButtonUp(), HandleVZoomClick(), HandleZoomClick(), MinimizeFunc(), MuteSoloFunc(), OnMouseEvent(), PanFunc(), PopupFunc(), ScrollDuringDrag(), SelectionHandleClick(), SelectionHandleDrag(), and StartSlide().
Track* TrackPanel::mCapturedTrack [private]
Referenced by CalculateRearrangingThresholds(), DoSlide(), DrawOutside(), ExtendSelection(), ForwardEventToEnvelope(), ForwardEventToTimeTrackEnvelope(), ForwardEventToWaveTrackEnvelope(), HandleClosing(), HandleEnvelope(), HandleMinimizing(), HandleMutingSoloing(), HandlePopping(), HandleRearrange(), HandleResizeDrag(), HandleSelect(), HandleSlide(), HandleSliders(), HandleTrackSpecificMouseEvent(), HandleVZoomButtonUp(), HandleVZoomClick(), HandleZoomClick(), OnMouseEvent(), OnTimer(), SelectionHandleClick(), SelectionHandleDrag(), SetCapturedTrack(), StartSelection(), StartSlide(), and TrackPanel().
WaveTrack::Location TrackPanel::mCapturedTrackLocation [private]
Referenced by HandleTrackLocationMouseEvent().
wxRect TrackPanel::mCapturedTrackLocationRect [private]
Referenced by HandleTrackLocationMouseEvent().
bool TrackPanel::mCircularTrackNavigation [private]
Referenced by OnNextTrack(), OnPrevTrack(), TrackPanel(), and UpdatePrefs().
float TrackPanel::mdBr [private]
Referenced by HitTestEnvelope(), HitTestSamples(), and UpdatePrefs().
bool TrackPanel::mDidSlideVertically [private]
Referenced by DoSlide(), HandleSlide(), and StartSlide().
wxCursor* TrackPanel::mDisabledCursor [private]
Referenced by SetCursorAndTipByTool(), SetCursorByActivity(), TrackPanel(), and ~TrackPanel().
sampleCount TrackPanel::mDrawingLastDragSample [private]
Referenced by HandleSampleEditingClick(), and HandleSampleEditingDrag().
float TrackPanel::mDrawingLastDragSampleValue [private]
Referenced by HandleSampleEditingClick(), and HandleSampleEditingDrag().
sampleCount TrackPanel::mDrawingStartSample [private]
Referenced by HandleSampleEditingClick(), and HandleSampleEditingDrag().
float TrackPanel::mDrawingStartSampleValue [private]
Referenced by HandleSampleEditingClick(), and HandleSampleEditingDrag().
Track* TrackPanel::mDrawingTrack [private]
Referenced by HandleSampleEditing(), HandleSampleEditingButtonUp(), HandleSampleEditingClick(), HandleSampleEditingDrag(), and TrackPanel().
int TrackPanel::mDrawingTrackTop [private]
Referenced by HandleSampleEditingClick(), and HandleSampleEditingDrag().
wxCursor* TrackPanel::mEnvelopeCursor [private]
Referenced by SetCursorAndTipByTool(), SetCursorByActivity(), TrackPanel(), and ~TrackPanel().
wxMenu* TrackPanel::mFormatMenu [private]
Referenced by BuildMenus(), OnFormatChange(), and OnTrackMenu().
double TrackPanel::mHSlideAmount [private]
Referenced by DoSlide(), HandleSlide(), and StartSlide().
bool TrackPanel::mIndicatorShowing [private]
Referenced by DoDrawIndicator(), OnPaint(), OnTimer(), and TrackPanel().
int TrackPanel::mInitialTrackHeight [private]
Referenced by HandleResizeClick(), and HandleResizeDrag().
int TrackPanel::mInitialUpperTrackHeight [private]
Referenced by HandleResizeClick(), and HandleResizeDrag().
wxCursor* TrackPanel::mLabelCursorLeft [private]
Referenced by TrackPanel(), and ~TrackPanel().
wxCursor* TrackPanel::mLabelCursorRight [private]
Referenced by TrackPanel(), and ~TrackPanel().
wxMenu* TrackPanel::mLabelTrackInfoMenu [private]
Referenced by BuildMenus(), DeleteMenus(), HandleLabelTrackMouseEvent(), and TrackPanel().
wxMenu* TrackPanel::mLabelTrackMenu [private]
Referenced by BuildMenus(), DeleteMenus(), OnTrackMenu(), and TrackPanel().
int TrackPanel::mLabelTrackStartXPos [private]
Referenced by HandleLabelTrackMouseEvent(), and TrackPanel().
int TrackPanel::mLabelTrackStartYPos [private]
Referenced by HandleLabelTrackMouseEvent().
double TrackPanel::mLastCursor [private]
Referenced by DoDrawCursor(), DoDrawIndicator(), and TrackPanel().
double TrackPanel::mLastIndicator [private]
Referenced by DoDrawIndicator(), and TrackPanel().
wxMouseEvent TrackPanel::mLastMouseEvent [private]
Referenced by HandleControlKey(), HandleCursor(), HandleCursorForLastMouseEvent(), and HandleShiftKey().
wxLongLong TrackPanel::mLastSelectionAdjustment [private]
Referenced by OnBoundaryMove(), OnCursorLeft(), OnCursorMove(), OnCursorRight(), and TrackPanel().
TrackPanelListener* TrackPanel::mListener [private]
Referenced by DisplaySelection(), DoDrawIndicator(), DrawTracks(), EnsureVisible(), HandleClosing(), HandleCursor(), HandleTrackSpecificMouseEvent(), HandleWheelRotation(), MakeParentModifyState(), MakeParentPushState(), MakeParentRedrawScrollbars(), MakeParentResize(), OnTimer(), OnTrackClose(), ScrollDuringDrag(), ScrollIntoView(), and StartSlide().
enum MouseCaptureEnum TrackPanel::mMouseCapture [private]
Referenced by DetermineToolToUse(), DrawEverythingElse(), DrawOutside(), DrawZooming(), HandleLabelTrackMouseEvent(), HandleResizeDrag(), HandleSelect(), HandleSlide(), HandleSliders(), HandleTrackLocationMouseEvent(), HandleTrackSpecificMouseEvent(), HandleVZoomButtonUp(), HandleVZoomClick(), HandleZoom(), OnMouseEvent(), OnTimer(), SelectionHandleClick(), SelectionHandleDrag(), SetCapturedTrack(), SetCursorByActivity(), StartSlide(), and TrackPanel().
int TrackPanel::mMouseClickX [private]
Referenced by DoSlide(), HandleResizeClick(), SelectionHandleClick(), and StartSlide().
int TrackPanel::mMouseClickY [private]
Referenced by HandleResizeClick(), HandleResizeDrag(), SelectionHandleClick(), and StartSlide().
int TrackPanel::mMouseMostRecentX [private]
Referenced by GetMostRecentXPos(), OnCaptureLost(), OnMouseEvent(), ScrollDuringDrag(), and SelectionHandleDrag().
int TrackPanel::mMouseMostRecentY [private]
Referenced by OnCaptureLost(), OnMouseEvent(), and SelectionHandleDrag().
int TrackPanel::mMoveDownThreshold [private]
Referenced by CalculateRearrangingThresholds(), and HandleRearrange().
int TrackPanel::mMoveUpThreshold [private]
Referenced by CalculateRearrangingThresholds(), and HandleRearrange().
wxMenu* TrackPanel::mNoteTrackMenu [private]
Referenced by BuildMenus(), DeleteMenus(), OnTrackMenu(), and TrackPanel().
wxCursor* TrackPanel::mPencilCursor [private]
Referenced by SetCursorAndTipByTool(), TrackPanel(), and ~TrackPanel().
Track* TrackPanel::mPopupMenuTarget [private]
Referenced by HandleLabelTrackMouseEvent(), OnChangeOctave(), OnChannelChange(), OnCopySelectedText(), OnCutSelectedText(), OnFormatChange(), OnMergeStereo(), OnMoveTrack(), OnPasteSelectedText(), OnRateChange(), OnRateOther(), OnSetDisplay(), OnSetName(), OnSetTimeTrackRange(), OnTrackMenu(), SplitStereo(), and TrackPanel().
int TrackPanel::mPrevHeight [private]
Referenced by TrackPanel().
int TrackPanel::mPrevWidth [private]
Referenced by TrackPanel().
wxMenu* TrackPanel::mRateMenu [private]
Referenced by BuildMenus(), OnRateChange(), OnRateOther(), and OnTrackMenu().
wxCursor* TrackPanel::mRearrangeCursor [private]
Referenced by SetCursorByActivity(), TrackPanel(), and ~TrackPanel().
bool TrackPanel::mRedrawAfterStop [private]
Referenced by OnTimer(), and TrackPanel().
bool TrackPanel::mRefreshBacking [private]
Referenced by OnPaint(), OnTimer(), Refresh(), and RefreshTrack().
wxCursor* TrackPanel::mResizeCursor [private]
Referenced by SetCursorAndTipWhenInVResizeArea(), TrackPanel(), and ~TrackPanel().
AdornedRulerPanel* TrackPanel::mRuler [private]
Referenced by ScreenshotCommand::Apply(), DoDrawCursor(), DoDrawIndicator(), ExtendSelection(), and UpdateVRulerSize().
double TrackPanel::mSeekLong [private]
Referenced by OnCursorLeft(), OnCursorMove(), OnCursorRight(), and UpdatePrefs().
double TrackPanel::mSeekShort [private]
Referenced by OnCursorLeft(), OnCursorMove(), OnCursorRight(), and UpdatePrefs().
wxCursor* TrackPanel::mSelectCursor [private]
Referenced by SetCursorAndTipWhenSelectTool(), SetCursorByActivity(), TrackPanel(), and ~TrackPanel().
double TrackPanel::mSelStart [private]
Referenced by ExtendSelection(), SelectionHandleClick(), SelectionHandleDrag(), StartSelection(), and StartSlide().
wxCursor* TrackPanel::mSlideCursor [private]
Referenced by SetCursorAndTipByTool(), SetCursorByActivity(), TrackPanel(), and ~TrackPanel().
wxBaseArrayDouble TrackPanel::mSlideSnapFromPoints [private]
wxArrayInt TrackPanel::mSlideSnapLinePixels [private]
wxBaseArrayDouble TrackPanel::mSlideSnapToPoints [private]
bool TrackPanel::mSlideUpDownOnly [private]
Referenced by DoSlide(), StartSlide(), and TrackPanel().
wxCursor* TrackPanel::mSmoothCursor [private]
Referenced by SetCursorAndTipByTool(), TrackPanel(), and ~TrackPanel().
wxInt64 TrackPanel::mSnapLeft [private]
Referenced by DoSlide(), DrawEverythingElse(), ExtendSelection(), HandleSelect(), HandleSlide(), SelectionHandleClick(), StartSelection(), StartSlide(), and TrackPanel().
SnapManager* TrackPanel::mSnapManager [private]
Referenced by DoSlide(), DrawEverythingElse(), ExtendSelection(), HandleSelect(), HandleSlide(), SelectionHandleClick(), StartSelection(), StartSlide(), TrackPanel(), and ~TrackPanel().
bool TrackPanel::mSnapPreferRightEdge [private]
Referenced by DoSlide(), and StartSlide().
wxInt64 TrackPanel::mSnapRight [private]
Referenced by DoSlide(), DrawEverythingElse(), ExtendSelection(), HandleSelect(), HandleSlide(), SelectionHandleClick(), StartSelection(), StartSlide(), and TrackPanel().
wxString TrackPanel::mSoloPref [private]
Referenced by UpdatePrefs().
int TrackPanel::mTimeCount [private]
Referenced by OnTimer(), and TrackPanel().
TrackPanel::AudacityTimer TrackPanel::mTimer [private]
Referenced by OnMouseEvent(), TrackPanel(), and ~TrackPanel().
wxMenu* TrackPanel::mTimeTrackMenu [private]
Referenced by BuildMenus(), DeleteMenus(), OnTrackMenu(), and TrackPanel().
TrackArtist* TrackPanel::mTrackArtist [private]
Referenced by DrawEverythingElse(), DrawTracks(), HandleVZoomButtonUp(), OnSetDisplay(), TrackPanel(), UpdatePrefs(), UpdateTrackVRuler(), and ~TrackPanel().
TrackInfo TrackPanel::mTrackInfo [private]
Referenced by CloseFunc(), DrawOutside(), GainFunc(), GetLabelWidth(), GetVRulerOffset(), HandleClosing(), HandleLabelClick(), HandleMinimizing(), HandleMutingSoloing(), HandlePopping(), HandleSliders(), MinimizeFunc(), MuteSoloFunc(), OnTrackGain(), OnTrackGainDec(), OnTrackGainInc(), OnTrackMenu(), OnTrackPan(), OnTrackPanLeft(), OnTrackPanRight(), PanFunc(), and PopupFunc().
TrackList* TrackPanel::mTracks [private]
Referenced by CalculateRearrangingThresholds(), DoSlide(), DrawTracks(), EnsureVisible(), TrackPanelAx::FindTrack(), GetFirstSelectedTrack(), HandleClosing(), HandleLabelClick(), HandleLabelTrackMouseEvent(), HandleMinimizing(), HandleRearrange(), HandleResizeClick(), HandleResizeDrag(), HandleSelect(), HandleSliders(), HandleTrackLocationMouseEvent(), HandleVZoomButtonUp(), MoveClipToTrack(), OnBoundaryMove(), OnCursorMove(), OnCursorRight(), OnFormatChange(), OnMoveTrack(), OnNextTrack(), OnPrevTrack(), OnTimer(), OnToggle(), OnTrackClose(), OnTrackListUpdated(), OnTrackMenu(), RemoveTrack(), SelectionHandleClick(), SelectionHandleDrag(), SelectNone(), SelectTrackLength(), SelectTracksByLabel(), TrackPanelAx::SetFocus(), SetRate(), SetTrackGain(), SetTrackPan(), StartSlide(), TrackPanelAx::TrackNum(), TrackPanel(), UpdateVRulers(), UpdateVRulerSize(), and ~TrackPanel().
double TrackPanel::mVertScrollRemainder [private]
Referenced by HandleWheelRotation().
ViewInfo* TrackPanel::mViewInfo [private]
Referenced by AddClipsToCaptured(), DoDrawCursor(), DoDrawIndicator(), DoSlide(), DoZoomInOut(), DragZoom(), DrawEverythingElse(), DrawTracks(), EnsureVisible(), ExtendSelection(), FindTrack(), FindTrackRect(), ForwardEventToTimeTrackEnvelope(), ForwardEventToWaveTrackEnvelope(), GetMostRecentXPos(), GridMove(), HandleClosing(), HandleLabelTrackMouseEvent(), HandleSelect(), HandleTrackLocationMouseEvent(), HandleWheelRotation(), HitTestEnvelope(), HitTestSamples(), IsSampleEditingPossible(), OnBoundaryMove(), OnChar(), OnCursorLeft(), OnCursorMove(), OnCursorRight(), OnKeyDown(), OnPaint(), OnPasteSelectedText(), OnTrackClose(), PositionToTime(), RefreshTrack(), ScrollIntoView(), SelectionHandleClick(), SelectTrackLength(), SetCursorAndTipWhenSelectTool(), SetStop(), StartSelection(), StartSlide(), TimeToPosition(), and UpdatePrefs().
wxMenu* TrackPanel::mWaveTrackMenu [private]
Referenced by BuildMenus(), DeleteMenus(), OnTrackMenu(), and TrackPanel().
int TrackPanel::mZoomEnd [private]
Referenced by DragZoom(), DrawZooming(), HandleVZoomButtonUp(), HandleVZoomClick(), HandleVZoomDrag(), HandleZoomButtonUp(), HandleZoomClick(), HandleZoomDrag(), IsDragZooming(), and TrackPanel().
wxCursor* TrackPanel::mZoomInCursor [private]
Referenced by SetCursorAndTipByTool(), SetCursorAndTipWhenInLabel(), TrackPanel(), and ~TrackPanel().
wxCursor* TrackPanel::mZoomOutCursor [private]
Referenced by SetCursorAndTipByTool(), SetCursorAndTipWhenInLabel(), TrackPanel(), and ~TrackPanel().
int TrackPanel::mZoomStart [private]
Referenced by DragZoom(), DrawZooming(), HandleVZoomButtonUp(), HandleVZoomClick(), HandleZoomButtonUp(), HandleZoomClick(), IsDragZooming(), and TrackPanel().
wxSize TrackPanel::vrulerSize
Referenced by GetVRulerWidth(), and UpdateVRulerSize().
The documentation for this class was generated from the following files:
TrackPanel.h
TrackPanel.cpp