Audacity: TagsEditor Class Reference
TagsEditor Class Reference
Derived from ExpandingToolBar, this dialog allows editing of Tags.
#include <Tags.h>
Public Member Functions
TagsEditor (wxWindow *parent, wxString title, Tags *tags, bool editTitle, bool editTrackNumber)
virtual ~TagsEditor ()
void PopulateOrExchange (ShuttleGui &S)
virtual bool TransferDataToWindow ()
virtual bool TransferDataFromWindow ()
Private Member Functions
void PopulateGenres ()
void SetEditors ()
void OnChange (wxGridEvent &event)
void OnEdit (wxCommandEvent &event)
void OnReset (wxCommandEvent &event)
void OnClear (wxCommandEvent &event)
void OnLoad (wxCommandEvent &event)
void OnSave (wxCommandEvent &event)
void OnSaveDefaults (wxCommandEvent &event)
void OnAdd (wxCommandEvent &event)
void OnRemove (wxCommandEvent &event)
void OnOk (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
bool IsWindowRectValid (const wxRect *windowRect) const
Private Attributes
Tags * mTags
bool mEditTitle
bool mEditTrack
Tags mLocal
Grid * mGrid
ComboEditor * mComboEditor
wxGridCellStringRenderer * mStringRenderer
Detailed Description
Derived from ExpandingToolBar, this dialog allows editing of Tags.
Constructor & Destructor Documentation
TagsEditor::TagsEditor (wxWindow * parent, wxString title, Tags * tags, bool editTitle, bool editTrackNumber)
References eIsCreating, gPrefs, LABEL_ALBUM, LABEL_ARTIST, LABEL_COMMENTS, LABEL_GENRE, LABEL_TITLE, LABEL_TRACK, LABEL_YEAR, labelmap, names, TAG_ALBUM, TAG_ARTIST, TAG_COMMENTS, TAG_GENRE, TAG_TITLE, TAG_TRACK, and TAG_YEAR.
TagsEditor::~TagsEditor () [virtual]
References mGrid.
Member Function Documentation
bool TagsEditor::IsWindowRectValid (const wxRect * windowRect) const [private]
void TagsEditor::OnAdd (wxCommandEvent & event) [private]
References mGrid.
void TagsEditor::OnCancel (wxCommandEvent & event) [private]
References mGrid.
void TagsEditor::OnChange (wxGridEvent & event) [private]
References labelmap, mGrid, and STATICCNT.
void TagsEditor::OnClear (wxCommandEvent & event) [private]
References Tags::Clear(), mLocal, and TransferDataToWindow().
void TagsEditor::OnEdit (wxCommandEvent & event) [private]
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTextWindow(), FileNames::DataDir(), eIsCreating, ShuttleGuiBase::EndVerticalLay(), Tags::GetNumUserGenres(), Tags::GetUserGenre(), Tags::LoadGenres(), mGrid, mLocal, PopulateGenres(), and ShuttleGuiBase::StartVerticalLay().
void TagsEditor::OnLoad (wxCommandEvent & event) [private]
References Tags::Clear(), FileNames::DataDir(), XMLFileReader::GetErrorStr(), Tags::GetTag(), mEditTitle, mEditTrack, mLocal, XMLFileReader::Parse(), Tags::SetTag(), TAG_TITLE, TAG_TRACK, and TransferDataToWindow().
void TagsEditor::OnOk (wxCommandEvent & event) [private]
References gPrefs, mGrid, mLocal, mTags, and TransferDataFromWindow().
void TagsEditor::OnRemove (wxCommandEvent & event) [private]
References LABEL_TITLE, LABEL_TRACK, mEditTitle, mEditTrack, mGrid, and STATICCNT.
void TagsEditor::OnReset (wxCommandEvent & event) [private]
References FileNames::DataDir(), Tags::GetNumUserGenres(), Tags::GetUserGenre(), Tags::LoadDefaultGenres(), Tags::LoadGenres(), mLocal, and PopulateGenres().
void TagsEditor::OnSave (wxCommandEvent & event) [private]
References XMLFileWriter::Close(), FileNames::DataDir(), XMLFileWriterException::GetMessage(), Tags::GetTag(), mEditTitle, mEditTrack, mLocal, XMLFileWriter::Open(), Tags::SetTag(), TAG_TITLE, TAG_TRACK, TransferDataFromWindow(), and Tags::WriteXML().
void TagsEditor::OnSaveDefaults (wxCommandEvent & event) [private]
References Tags::GetFirst(), Tags::GetNext(), Tags::GetTag(), gPrefs, mEditTitle, mEditTrack, mLocal, Tags::SetTag(), TAG_TITLE, TAG_TRACK, and TransferDataFromWindow().
void TagsEditor::PopulateGenres () [private]
References Tags::GetNumUserGenres(), Tags::GetUserGenre(), mGrid, and mLocal.
Referenced by OnEdit(), and OnReset().
void TagsEditor::PopulateOrExchange (ShuttleGui & S)
References ShuttleGuiBase::AddButton(), AddID, ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddUnits(), ShuttleGuiBase::AddWindow(), ClearID, eCancelButton, EditID, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), eOkButton, ShuttleGuiBase::GetParent(), ShuttleGui::Id(), LoadID, mComboEditor, mGrid, mStringRenderer, names, ShuttleGui::Prop(), RemoveID, ResetID, SaveDefaultsID, SaveID, ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::StartVerticalLay().
void TagsEditor::SetEditors () [private]
References label, LABEL_GENRE, and mGrid.
Referenced by TransferDataToWindow().
bool TagsEditor::TransferDataFromWindow () [virtual]
References Tags::Clear(), LABEL_ALBUM, LABEL_ARTIST, LABEL_COMMENTS, LABEL_GENRE, LABEL_TITLE, LABEL_TRACK, LABEL_YEAR, mGrid, mLocal, Tags::SetTag(), TAG_ALBUM, TAG_ARTIST, TAG_COMMENTS, TAG_GENRE, TAG_TITLE, TAG_TRACK, and TAG_YEAR.
Referenced by OnOk(), OnSave(), and OnSaveDefaults().
bool TagsEditor::TransferDataToWindow () [virtual]
References Tags::GetFirst(), Tags::GetNext(), Tags::GetTag(), label, LABEL_TITLE, LABEL_TRACK, labelmap, mEditTitle, mEditTrack, mGrid, mLocal, name, SetEditors(), Tags::SetTag(), and STATICCNT.
Referenced by OnClear(), and OnLoad().
Member Data Documentation
ComboEditor* TagsEditor::mComboEditor [private]
Referenced by PopulateOrExchange().
bool TagsEditor::mEditTitle [private]
Referenced by OnLoad(), OnRemove(), OnSave(), OnSaveDefaults(), and TransferDataToWindow().
bool TagsEditor::mEditTrack [private]
Referenced by OnLoad(), OnRemove(), OnSave(), OnSaveDefaults(), and TransferDataToWindow().
Grid* TagsEditor::mGrid [private]
Referenced by OnAdd(), OnCancel(), OnChange(), OnEdit(), OnOk(), OnRemove(), PopulateGenres(), PopulateOrExchange(), SetEditors(), TransferDataFromWindow(), TransferDataToWindow(), and ~TagsEditor().
Tags TagsEditor::mLocal [private]
Referenced by OnClear(), OnEdit(), OnLoad(), OnOk(), OnReset(), OnSave(), OnSaveDefaults(), PopulateGenres(), TransferDataFromWindow(), and TransferDataToWindow().
wxGridCellStringRenderer* TagsEditor::mStringRenderer [private]
Referenced by PopulateOrExchange().
Tags* TagsEditor::mTags [private]
Referenced by OnOk().
The documentation for this class was generated from the following files:
Tags.h
Tags.cpp