Audacity: CommandType Class Reference
CommandType Class Reference
Base class for containing data common to all commands of a given type. Also acts as a factory.
#include <CommandType.h>
Public Member Functions
CommandType ()
virtual ~CommandType ()
wxString GetName ()
CommandSignature & GetSignature ()
wxString Describe ()
virtual wxString BuildName ()=0
virtual void BuildSignature (CommandSignature &signature)=0
Postcondition: signature is a 'signature' map containing parameter.
virtual Command * Create (CommandOutputTarget *target)=0
Private Attributes
wxString * mName
CommandSignature * mSignature
Detailed Description
Base class for containing data common to all commands of a given type. Also acts as a factory.
Constructor & Destructor Documentation
CommandType::CommandType ()
CommandType::~CommandType () [virtual]
References mName, and mSignature.
Member Function Documentation
virtual wxString CommandType::BuildName () [pure virtual]
Implemented in BatchEvalCommandType, CompareAudioCommandType, ExecMenuCommandType, GetAllMenuCommandsType, GetProjectInfoCommandType, GetTrackInfoCommandType, HelpCommandType, ImportCommandType, ExportCommandType, MessageCommandType, GetPreferenceCommandType, SetPreferenceCommandType, ScreenshotCommandType, SelectCommandType, SetProjectInfoCommandType, and SetTrackInfoCommandType.
Referenced by GetName().
virtual void CommandType::BuildSignature (CommandSignature & signature) [pure virtual]
Postcondition: signature is a 'signature' map containing parameter.
Implemented in BatchEvalCommandType, CompareAudioCommandType, ExecMenuCommandType, GetAllMenuCommandsType, GetProjectInfoCommandType, GetTrackInfoCommandType, HelpCommandType, ImportCommandType, ExportCommandType, MessageCommandType, GetPreferenceCommandType, SetPreferenceCommandType, ScreenshotCommandType, SelectCommandType, SetProjectInfoCommandType, and SetTrackInfoCommandType.
Referenced by GetSignature().
virtual Command* CommandType::Create (CommandOutputTarget * target) [pure virtual]
Implemented in BatchEvalCommandType, CompareAudioCommandType, ExecMenuCommandType, GetAllMenuCommandsType, GetProjectInfoCommandType, GetTrackInfoCommandType, HelpCommandType, ImportCommandType, ExportCommandType, MessageCommandType, GetPreferenceCommandType, SetPreferenceCommandType, ScreenshotCommandType, SelectCommandType, SetProjectInfoCommandType, and SetTrackInfoCommandType.
Referenced by CommandBuilder::BuildCommand(), and AudacityProject::SafeDisplayStatusMessage().
wxString CommandType::Describe ()
References CommandSignature::GetDefaults(), Validator::GetDescription(), GetName(), GetSignature(), CommandSignature::GetValidator(), and mSignature.
Referenced by HelpCommand::Apply().
wxString CommandType::GetName ()
References BuildName(), and mName.
Referenced by CommandDirectory::AddCommand(), Describe(), and CommandImplementation::GetName().
CommandSignature & CommandType::GetSignature ()
References BuildSignature(), and mSignature.
Referenced by CommandBuilder::BuildCommand(), Describe(), CommandImplementation::GetSignature(), and CommandImplementation::SetParameter().
Member Data Documentation
wxString* CommandType::mName [private]
Referenced by GetName(), and ~CommandType().
CommandSignature* CommandType::mSignature [private]
Referenced by Describe(), GetSignature(), and ~CommandType().
The documentation for this class was generated from the following files:
CommandType.h
CommandType.cpp