Audacity: EffectSilence Class Reference
EffectSilence Class Reference
An Effect for the "Generator" menu to add silence.
#include <Silence.h>
Public Member Functions
EffectSilence ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual wxString GetEffectDescription ()
virtual bool PromptUser ()
Protected Member Functions
bool GenerateTrack (WaveTrack *tmp, const WaveTrack &track, int ntrack)
Detailed Description
An Effect for the "Generator" menu to add silence.
Constructor & Destructor Documentation
EffectSilence::EffectSilence () [inline]
References BUILTIN_EFFECT, INSERT_EFFECT, and Effect::SetEffectFlags().
Member Function Documentation
bool EffectSilence::GenerateTrack (WaveTrack * tmp, const WaveTrack & track, int ntrack) [protected, virtual]
Implements Generator.
References WaveTrack::InsertSilence(), and Generator::mDuration.
virtual wxString EffectSilence::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectSilence::GetEffectCategories () [inline, virtual]
virtual wxString EffectSilence::GetEffectDescription () [inline, virtual]
Reimplemented from Effect.
References Generator::mDuration.
virtual wxString EffectSilence::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectSilence::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectSilence::PromptUser () [virtual]
Reimplemented from Effect.
References TimeDialog::GetTimeValue(), Generator::mDuration, Effect::mParent, Effect::mProjectRate, Effect::mT0, Effect::mT1, TimeDialog::SetFormatString(), TimeDialog::SetSampleRate(), and TimeDialog::SetTimeValue().
The documentation for this class was generated from the following files:
Silence.h
Silence.cpp