Audacity: EffectChangeSpeed Class Reference
EffectChangeSpeed Class Reference
An Effect that affects both pitch & Speed.
#include <ChangeSpeed.h>
Public Member Functions
EffectChangeSpeed ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual wxString GetEffectDescription ()
Protected Member Functions
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool CheckWhetherSkipEffect ()
virtual bool Process ()
Private Member Functions
bool ProcessOne (WaveTrack *t, sampleCount start, sampleCount end)
bool ProcessLabelTrack (Track *t)
Private Attributes
int mCurTrackNum
double m_maxNewLength
double mCurT0
double mCurT1
double m_PercentChange
int m_FromVinyl
int m_ToVinyl
double mFactor
Friends
class ChangeSpeedDialog
Detailed Description
An Effect that affects both pitch & Speed.
Constructor & Destructor Documentation
EffectChangeSpeed::EffectChangeSpeed ()
References m_FromVinyl, m_PercentChange, and m_ToVinyl.
Member Function Documentation
virtual bool EffectChangeSpeed::CheckWhetherSkipEffect () [inline, protected, virtual]
Reimplemented from Effect.
References m_PercentChange.
virtual wxString EffectChangeSpeed::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectChangeSpeed::GetEffectCategories () [inline, virtual]
wxString EffectChangeSpeed::GetEffectDescription () [virtual]
Reimplemented from Effect.
References GetEffectName(), and m_PercentChange.
virtual wxString EffectChangeSpeed::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectChangeSpeed::GetEffectName () [inline, virtual]
Implements Effect.
Referenced by GetEffectDescription().
bool EffectChangeSpeed::Process () [protected, virtual]
Implements Effect.
References Track::All, Effect::CopyInputTracks(), TrackListIterator::First(), WaveTrack::GetEndTime(), Track::GetKind(), Track::GetSelected(), WaveTrack::GetStartTime(), Track::IsSynchroSelected(), Track::Label, m_maxNewLength, m_PercentChange, mCurT0, mCurT1, mCurTrackNum, mFactor, Effect::mOutputTracks, Effect::mT0, Effect::mT1, TrackListIterator::Next(), ProcessLabelTrack(), ProcessOne(), Effect::ReplaceProcessedTracks(), Track::SyncAdjust(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectChangeSpeed::ProcessLabelTrack (Track * t) [private]
References Effect::GetTimeWarper(), mFactor, Effect::mT0, Effect::mT1, Effect::SetTimeWarper(), and LabelTrack::WarpLabels().
Referenced by Process().
bool EffectChangeSpeed::ProcessOne (WaveTrack * t, sampleCount start, sampleCount end) [private]
References WaveTrack::Append(), WaveTrack::ClearAndPaste(), floatSample, WaveTrack::Flush(), WaveTrack::Get(), WaveTrack::GetBestBlockSize(), WaveTrack::GetEndTime(), WaveTrack::GetMaxBlockSize(), WaveTrack::GetRate(), WaveTrack::GetSampleFormat(), Effect::GetTimeWarper(), m_maxNewLength, mCurT0, mCurT1, mCurTrackNum, mFactor, Effect::mFactory, TrackFactory::NewWaveTrack(), Resample::Process(), Effect::SetTimeWarper(), and Effect::TrackProgress().
Referenced by Process().
bool EffectChangeSpeed::PromptUser () [protected, virtual]
Reimplemented from Effect.
References m_FromVinyl, ChangeSpeedDialog::m_FromVinyl, m_PercentChange, ChangeSpeedDialog::m_PercentChange, m_ToVinyl, ChangeSpeedDialog::m_ToVinyl, and Effect::mParent.
bool EffectChangeSpeed::TransferParameters (Shuttle & shuttle) [protected, virtual]
Reimplemented from Effect.
References m_PercentChange, and Shuttle::TransferDouble().
Friends And Related Function Documentation
friend class ChangeSpeedDialog [friend]
Member Data Documentation
int EffectChangeSpeed::m_FromVinyl [private]
Referenced by EffectChangeSpeed(), and PromptUser().
double EffectChangeSpeed::m_maxNewLength [private]
Referenced by Process(), and ProcessOne().
double EffectChangeSpeed::m_PercentChange [private]
Referenced by CheckWhetherSkipEffect(), EffectChangeSpeed(), GetEffectDescription(), ChangeSpeedDialog::OnPreview(), Process(), PromptUser(), and TransferParameters().
int EffectChangeSpeed::m_ToVinyl [private]
Referenced by EffectChangeSpeed(), and PromptUser().
double EffectChangeSpeed::mCurT0 [private]
Referenced by Process(), and ProcessOne().
double EffectChangeSpeed::mCurT1 [private]
Referenced by Process(), and ProcessOne().
int EffectChangeSpeed::mCurTrackNum [private]
Referenced by Process(), and ProcessOne().
double EffectChangeSpeed::mFactor [private]
Referenced by Process(), ProcessLabelTrack(), and ProcessOne().
The documentation for this class was generated from the following files:
ChangeSpeed.h
ChangeSpeed.cpp