Audacity: DevicePrefs Class Reference
DevicePrefs Class Reference
A PrefsPanel used to select recording and playback devices and other settings.
#include <DevicePrefs.h>
Public Member Functions
DevicePrefs (wxWindow *parent)
virtual ~DevicePrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
void GetNamesAndLabels ()
void OnHost (wxCommandEvent &e)
void OnDevice (wxCommandEvent &e)
wxString GetDefaultPlayDevice (int index)
wxString GetDefaultRecordDevice (int index)
DECLARE_EVENT_TABLE ()
Private Attributes
wxArrayString mHostNames
wxArrayString mHostLabels
wxString mPlayDevice
wxString mRecordDevice
long mRecordChannels
wxChoice * mHost
wxChoice * mPlay
wxChoice * mRecord
wxChoice * mChannels
Detailed Description
A PrefsPanel used to select recording and playback devices and other settings.
Presents interface for user to select the recording device and playback device, from the list of choices that PortAudio makes available.
Also lets user decide how many channels to record.
Constructor & Destructor Documentation
DevicePrefs::DevicePrefs (wxWindow * parent)
DevicePrefs::~DevicePrefs () [virtual]
Member Function Documentation
bool DevicePrefs::Apply () [virtual]
Implements PrefsPanel.
References DeviceName(), eIsSavingToPrefs, gPrefs, mChannels, mPlay, mRecord, and PopulateOrExchange().
DevicePrefs::DECLARE_EVENT_TABLE () [private]
wxString DevicePrefs::GetDefaultPlayDevice (int index) [private]
References name.
Referenced by OnHost().
wxString DevicePrefs::GetDefaultRecordDevice (int index) [private]
References name.
Referenced by OnHost().
void DevicePrefs::GetNamesAndLabels () [private]
References mHostLabels, mHostNames, and name.
Referenced by Populate().
void DevicePrefs::OnDevice (wxCommandEvent & e) [private]
References eIsCreating, mChannels, mRecord, mRecordChannels, name, and ShuttleGui::SetSizeHints().
Referenced by OnHost().
void DevicePrefs::OnHost (wxCommandEvent & e) [private]
References DeviceName(), eIsCreating, GetDefaultPlayDevice(), GetDefaultRecordDevice(), mHost, mHostNames, mPlay, mPlayDevice, mRecord, mRecordDevice, name, OnDevice(), and ShuttleGui::SetSizeHints().
Referenced by Populate().
void DevicePrefs::Populate () [private]
References eIsCreatingFromPrefs, GetNamesAndLabels(), gPrefs, mPlayDevice, mRecordChannels, mRecordDevice, OnHost(), and PopulateOrExchange().
void DevicePrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddChoice(), ShuttleGuiBase::AddFixedText(), ShuttleGuiBase::AddPrompt(), ChannelsID, ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), HostID, ShuttleGui::Id(), mChannels, mHost, mHostLabels, mHostNames, mPlay, mRecord, PlayID, RecordID, ShuttleGuiBase::SetBorder(), ShuttleGui::SetSizeHints(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::TieChoice().
Referenced by Apply(), and Populate().
Member Data Documentation
wxChoice* DevicePrefs::mChannels [private]
Referenced by Apply(), OnDevice(), and PopulateOrExchange().
wxChoice* DevicePrefs::mHost [private]
Referenced by OnHost(), and PopulateOrExchange().
wxArrayString DevicePrefs::mHostLabels [private]
Referenced by GetNamesAndLabels(), and PopulateOrExchange().
wxArrayString DevicePrefs::mHostNames [private]
Referenced by GetNamesAndLabels(), OnHost(), and PopulateOrExchange().
wxChoice* DevicePrefs::mPlay [private]
Referenced by Apply(), OnHost(), and PopulateOrExchange().
wxString DevicePrefs::mPlayDevice [private]
Referenced by OnHost(), and Populate().
wxChoice* DevicePrefs::mRecord [private]
Referenced by Apply(), OnDevice(), OnHost(), and PopulateOrExchange().
long DevicePrefs::mRecordChannels [private]
Referenced by OnDevice(), and Populate().
wxString DevicePrefs::mRecordDevice [private]
Referenced by OnHost(), and Populate().
The documentation for this class was generated from the following files:
DevicePrefs.h
DevicePrefs.cpp