Audacity: AdornedRulerPanel Class Reference
AdornedRulerPanel Class Reference
#include <Ruler.h>
Public Member Functions
AdornedRulerPanel (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, ViewInfo *viewinfo=NULL)
~AdornedRulerPanel ()
void SetLeftOffset (int offset)
void DrawCursor (double pos)
void DrawIndicator (double pos, bool rec)
void DrawSelection ()
void ClearIndicator ()
void SetPlayRegion (double playRegionStart, double playRegionEnd)
void ClearPlayRegion ()
void GetPlayRegion (double *playRegionStart, double *playRegionEnd)
void SetProject (AudacityProject *project)
void GetMaxSize (wxCoord *width, wxCoord *height)
Static Public Member Functions
static int GetRulerHeight ()
Private Types
enum MouseEventState {
mesNone, mesDraggingPlayRegionStart, mesDraggingPlayRegionEnd, mesSelectingPlayRegionClick,
mesSelectingPlayRegionRange
}
Private Member Functions
void OnErase (wxEraseEvent &evt)
void OnPaint (wxPaintEvent &evt)
void OnSize (wxSizeEvent &evt)
void OnMouseEvents (wxMouseEvent &evt)
void OnCaptureLost (wxMouseCaptureLostEvent &evt)
void DoDrawBorder (wxDC *dc)
void DoDrawMarks (wxDC *dc, bool)
void DoDrawCursor (wxDC *dc)
void DoDrawSelection (wxDC *dc)
void DoDrawIndicator (wxDC *dc)
void DoDrawPlayRegion (wxDC *dc)
double Pos2Time (int p)
int Time2Pos (double t)
bool IsWithinMarker (int mousePosX, double markerTime)
Private Attributes
Ruler ruler
ViewInfo * mViewInfo
AudacityProject * mProject
wxBitmap * mBuffer
wxRect mOuter
wxRect mInner
int mLeftOffset
double mCurPos
int mIndType
double mIndPos
double mPlayRegionStart
double mPlayRegionEnd
MouseEventState mMouseEventState
int mButtonDownMousePos
int mLastMouseX
Member Enumeration Documentation
enum AdornedRulerPanel::MouseEventState [private]
Enumerator:
mesNone
mesDraggingPlayRegionStart
mesDraggingPlayRegionEnd
mesSelectingPlayRegionClick
mesSelectingPlayRegionRange
Constructor & Destructor Documentation
AdornedRulerPanel::AdornedRulerPanel (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, ViewInfo * viewinfo = NULL)
References Ruler::TimeFormat.
AdornedRulerPanel::~AdornedRulerPanel ()
References mBuffer.
Member Function Documentation
void AdornedRulerPanel::ClearIndicator ()
References mIndType.
Referenced by DrawIndicator().
void AdornedRulerPanel::ClearPlayRegion ()
References mPlayRegionEnd, and mPlayRegionStart.
void AdornedRulerPanel::DoDrawBorder (wxDC * dc) [private]
References AColor::BevelTrackInfo(), AColor::MediumTrackInfo(), mInner, and mOuter.
Referenced by OnPaint().
void AdornedRulerPanel::DoDrawCursor (wxDC * dc) [private]
References ViewInfo::h, mCurPos, mInner, mLeftOffset, mViewInfo, and ViewInfo::zoom.
Referenced by OnPaint().
void AdornedRulerPanel::DoDrawIndicator (wxDC * dc) [private]
References ViewInfo::h, AColor::IndicatorColor(), mIndPos, mIndType, mLeftOffset, mViewInfo, and ViewInfo::zoom.
Referenced by OnPaint().
void AdornedRulerPanel::DoDrawMarks (wxDC * dc, bool) [private]
References ThemeBase::Colour(), Ruler::Draw(), ViewInfo::h, max, min(), mInner, mLeftOffset, mViewInfo, ruler, Ruler::SetRange(), Ruler::SetTickColour(), theTheme, and ViewInfo::zoom.
Referenced by OnPaint().
void AdornedRulerPanel::DoDrawPlayRegion (wxDC * dc) [private]
References GetPlayRegion(), AudacityProject::IsPlayRegionLocked(), mInner, mProject, PLAY_REGION_GLOBAL_OFFSET_Y, PLAY_REGION_RECT_HEIGHT, PLAY_REGION_RECT_WIDTH, PLAY_REGION_TRIANGLE_SIZE, AColor::PlayRegionColor(), and Time2Pos().
Referenced by OnPaint().
void AdornedRulerPanel::DoDrawSelection (wxDC * dc) [private]
References ThemeBase::Colour(), ViewInfo::h, mInner, mLeftOffset, mViewInfo, ViewInfo::sel0, ViewInfo::sel1, theTheme, and ViewInfo::zoom.
Referenced by OnPaint().
void AdornedRulerPanel::DrawCursor (double pos)
References mCurPos.
Referenced by TrackPanel::DoDrawCursor().
void AdornedRulerPanel::DrawIndicator (double pos, bool rec)
References ClearIndicator(), mIndPos, and mIndType.
Referenced by TrackPanel::DoDrawIndicator().
void AdornedRulerPanel::DrawSelection ()
Referenced by TrackPanel::ExtendSelection().
void AdornedRulerPanel::GetMaxSize (wxCoord * width, wxCoord * height)
References Ruler::GetMaxSize(), and ruler.
void AdornedRulerPanel::GetPlayRegion (double * playRegionStart, double * playRegionEnd)
References mPlayRegionEnd, and mPlayRegionStart.
Referenced by DoDrawPlayRegion(), and AudacityProject::GetPlayRegion().
static int AdornedRulerPanel::GetRulerHeight () [inline, static]
Referenced by ScreenshotCommand::Apply(), and AudacityProject::AudacityProject().
bool AdornedRulerPanel::IsWithinMarker (int mousePosX, double markerTime) [private]
References SELECT_TOLERANCE_PIXEL, and Time2Pos().
Referenced by OnMouseEvents().
void AdornedRulerPanel::OnCaptureLost (wxMouseCaptureLostEvent & evt) [private]
References mLastMouseX, and OnMouseEvents().
void AdornedRulerPanel::OnErase (wxEraseEvent & evt) [private]
void AdornedRulerPanel::OnMouseEvents (wxMouseEvent & evt) [private]
References AudacityProject::GetControlToolBar(), IsWithinMarker(), mButtonDownMousePos, mesDraggingPlayRegionEnd, mesDraggingPlayRegionStart, mesNone, mesSelectingPlayRegionClick, mesSelectingPlayRegionRange, mLastMouseX, mMouseEventState, mPlayRegionEnd, mPlayRegionStart, mProject, ControlToolBar::PlayDefault(), Pos2Time(), SELECT_TOLERANCE_PIXEL, and ControlToolBar::StopPlaying().
Referenced by OnCaptureLost().
void AdornedRulerPanel::OnPaint (wxPaintEvent & evt) [private]
References DoDrawBorder(), DoDrawCursor(), DoDrawIndicator(), DoDrawMarks(), DoDrawPlayRegion(), DoDrawSelection(), mIndType, mViewInfo, ViewInfo::sel0, and ViewInfo::sel1.
void AdornedRulerPanel::OnSize (wxSizeEvent & evt) [private]
References mBuffer, mInner, mOuter, ruler, and Ruler::SetBounds().
double AdornedRulerPanel::Pos2Time (int p) [private]
References ViewInfo::h, mLeftOffset, mViewInfo, and ViewInfo::zoom.
Referenced by OnMouseEvents().
void AdornedRulerPanel::SetLeftOffset (int offset) [inline]
Referenced by TrackPanel::UpdateVRulerSize().
void AdornedRulerPanel::SetPlayRegion (double playRegionStart, double playRegionEnd)
References mesNone, mMouseEventState, mPlayRegionEnd, and mPlayRegionStart.
Referenced by AudacityProject::TP_DisplaySelection().
void AdornedRulerPanel::SetProject (AudacityProject * project) [inline]
int AdornedRulerPanel::Time2Pos (double t) [private]
References ViewInfo::h, mLeftOffset, mViewInfo, and ViewInfo::zoom.
Referenced by DoDrawPlayRegion(), and IsWithinMarker().
Member Data Documentation
wxBitmap* AdornedRulerPanel::mBuffer [private]
Referenced by OnSize(), and ~AdornedRulerPanel().
int AdornedRulerPanel::mButtonDownMousePos [private]
Referenced by OnMouseEvents().
double AdornedRulerPanel::mCurPos [private]
Referenced by DoDrawCursor(), and DrawCursor().
double AdornedRulerPanel::mIndPos [private]
Referenced by DoDrawIndicator(), and DrawIndicator().
int AdornedRulerPanel::mIndType [private]
Referenced by ClearIndicator(), DoDrawIndicator(), DrawIndicator(), and OnPaint().
wxRect AdornedRulerPanel::mInner [private]
Referenced by DoDrawBorder(), DoDrawCursor(), DoDrawMarks(), DoDrawPlayRegion(), DoDrawSelection(), and OnSize().
int AdornedRulerPanel::mLastMouseX [private]
Referenced by OnCaptureLost(), and OnMouseEvents().
int AdornedRulerPanel::mLeftOffset [private]
Referenced by DoDrawCursor(), DoDrawIndicator(), DoDrawMarks(), DoDrawSelection(), Pos2Time(), and Time2Pos().
MouseEventState AdornedRulerPanel::mMouseEventState [private]
Referenced by OnMouseEvents(), and SetPlayRegion().
wxRect AdornedRulerPanel::mOuter [private]
Referenced by DoDrawBorder(), and OnSize().
double AdornedRulerPanel::mPlayRegionEnd [private]
Referenced by ClearPlayRegion(), GetPlayRegion(), OnMouseEvents(), and SetPlayRegion().
double AdornedRulerPanel::mPlayRegionStart [private]
Referenced by ClearPlayRegion(), GetPlayRegion(), OnMouseEvents(), and SetPlayRegion().
AudacityProject* AdornedRulerPanel::mProject [private]
Referenced by DoDrawPlayRegion(), and OnMouseEvents().
ViewInfo* AdornedRulerPanel::mViewInfo [private]
Referenced by DoDrawCursor(), DoDrawIndicator(), DoDrawMarks(), DoDrawSelection(), OnPaint(), Pos2Time(), and Time2Pos().
Ruler AdornedRulerPanel::ruler [private]
Referenced by DoDrawMarks(), GetMaxSize(), and OnSize().
The documentation for this class was generated from the following files:
Ruler.h
Ruler.cpp