Audacity: ExportMP3 Class Reference
ExportMP3 Class Reference
Public Member Functions
ExportMP3 ()
void Destroy ()
bool DisplayOptions (wxWindow *parent, int format=0)
int Export (AudacityProject *project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec *mixerSpec=NULL, Tags *metadata=NULL, int subformat=0)
called to export audio into a file.
Private Member Functions
int FindValue (CHOICES *choices, int cnt, int needle, int def)
wxString FindName (CHOICES *choices, int cnt, int needle)
int AskResample (int bitrate, int rate, int lowrate, int highrate)
int AddTags (AudacityProject *project, char **buffer, bool *endOfFile, Tags *tags)
Constructor & Destructor Documentation
ExportMP3::ExportMP3 ()
References ExportPlugin::AddExtension(), ExportPlugin::AddFormat(), InitMP3_Statics(), ExportPlugin::SetCanMetaData(), ExportPlugin::SetDescription(), ExportPlugin::SetFormat(), and ExportPlugin::SetMaxChannels().
Member Function Documentation
int ExportMP3::AddTags (AudacityProject * project, char ** buffer, bool * endOfFile, Tags * tags) [private]
References Tags::GetFirst(), Tags::GetGenre(), Tags::GetID3V2(), Tags::GetNext(), id3_frame_new(), name, TAG_ALBUM, TAG_ARTIST, TAG_COMMENTS, TAG_GENRE, TAG_TITLE, TAG_TRACK, and TAG_YEAR.
Referenced by Export().
int ExportMP3::AskResample (int bitrate, int rate, int lowrate, int highrate) [private]
References ShuttleGuiBase::AddChoice(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTitle(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), CHOICES::label, label, CHOICES::name, name, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::StartVerticalLay().
Referenced by Export().
void ExportMP3::Destroy () [virtual]
Reimplemented from ExportPlugin.
bool ExportMP3::DisplayOptions (wxWindow * parent, int format = 0) [virtual]
Reimplemented from ExportPlugin.
int ExportMP3::Export (AudacityProject * project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec * mixerSpec = NULL, Tags * metadata = NULL, int subformat = 0) [virtual]
called to export audio into a file.
Parameters:
selectedOnly Set to true if all tracks should be mixed, to false if only the selected tracks should be mixed and exported.
metadata A Tags object that will over-ride the one in *project and be used to tag the file that is exported.
subformat Control which of the multiple formats this exporter is capable of exporting should be used. Used where a single export plug-in handles a number of related formats, but they have separate entries in the Format drop-down list box. For example, the options to export to "Other PCM", "AIFF 16 Bit" and "WAV 16 Bit" are all the same libsndfile export plug-in, but with subformat set to 0, 1, and 2 respectively.
Reimplemented from ExportPlugin.
References AddTags(), AskResample(), CHANNEL_JOINT, CHANNEL_STEREO, MP3Exporter::EncodeBuffer(), MP3Exporter::EncodeBufferMono(), MP3Exporter::EncodeRemainder(), MP3Exporter::EncodeRemainderMono(), eProgressSuccess, FindName(), FindValue(), MP3Exporter::FinishStream(), Mixer::GetBuffer(), MP3Exporter::GetOutBufferSize(), AudacityProject::GetRate(), AudacityProject::GetTags(), TrackList::GetTimeTrack(), AudacityProject::GetTracks(), TrackList::GetWaveTracks(), gPrefs, MP3Exporter::InitializeStream(), int16Sample, MP3Exporter::LoadLibrary(), MP3Exporter::Maybe, Mixer::MixGetCurrentTime(), MODE_ABR, MODE_CBR, MODE_SET, MODE_VBR, PRESET_STANDARD, Mixer::Process(), MP3Exporter::PutInfoTag(), QUALITY_2, ROUTINE_FAST, MP3Exporter::SetBitrate(), MP3Exporter::SetChannel(), MP3Exporter::SetMode(), MP3Exporter::SetQuality(), ProgressDialog::Update(), and MP3Exporter::ValidLibraryLoaded().
wxString ExportMP3::FindName (CHOICES * choices, int cnt, int needle) [private]
References label, and CHOICES::name.
Referenced by Export().
int ExportMP3::FindValue (CHOICES * choices, int cnt, int needle, int def) [private]
References label.
Referenced by Export().
The documentation for this class was generated from the following file:
ExportMP3.cpp