Audacity: VoiceKey Class Reference
VoiceKey Class Reference
This implements a voice key, detecting either the next "ON" or "OFF" point.
#include <VoiceKey.h>
Public Member Functions
VoiceKey ()
~VoiceKey ()
sampleCount OnForward (WaveTrack &t, sampleCount start, sampleCount len)
sampleCount OnBackward (WaveTrack &t, sampleCount start, sampleCount len)
sampleCount OffForward (WaveTrack &t, sampleCount start, sampleCount len)
sampleCount OffBackward (WaveTrack &t, sampleCount start, sampleCount len)
void CalibrateNoise (WaveTrack &t, sampleCount start, sampleCount len)
void AdjustThreshold (double t)
bool AboveThreshold (WaveTrack &t, sampleCount start, sampleCount len)
void SetKeyType (bool erg, bool scLow, bool scHigh, bool dcLow, bool dcHigh)
Private Member Functions
double TestEnergy (WaveTrack &t, sampleCount start, sampleCount len)
double TestSignChanges (WaveTrack &t, sampleCount start, sampleCount len)
double TestDirectionChanges (WaveTrack &t, sampleCount start, sampleCount len)
void TestEnergyUpdate (double &prevErg, int length, const sampleFormat &drop, const sampleFormat &add)
void TestSignChangesUpdate (double &currentsignchanges, int length, const sampleFormat &a1, const sampleFormat &a2, const sampleFormat &z1, const sampleFormat &z2)
void TestDirectionChangesUpdate (double &currentdirectionchanges, int length, int &atrend, const sampleFormat &a1, const sampleFormat &a2, int &ztrend, const sampleFormat &z1, const sampleFormat &z2)
Private Attributes
double mWindowSize
double mThresholdAdjustment
double mEnergyMean
double mEnergySD
double mSignChangesMean
double mSignChangesSD
double mDirectionChangesMean
double mDirectionChangesSD
double mThresholdEnergy
double mThresholdSignChangesLower
double mThresholdSignChangesUpper
double mThresholdDirectionChangesLower
double mThresholdDirectionChangesUpper
bool mUseEnergy
bool mUseSignChangesLow
bool mUseSignChangesHigh
bool mUseDirectionChangesLow
bool mUseDirectionChangesHigh
double mSilentWindowSize
double mSignalWindowSize
Detailed Description
This implements a voice key, detecting either the next "ON" or "OFF" point.
Constructor & Destructor Documentation
VoiceKey::VoiceKey ()
References AdjustThreshold(), mDirectionChangesMean, mDirectionChangesSD, mEnergyMean, mEnergySD, mSignalWindowSize, mSignChangesMean, mSignChangesSD, mSilentWindowSize, mUseDirectionChangesHigh, mUseDirectionChangesLow, mUseEnergy, mUseSignChangesHigh, mUseSignChangesLow, and mWindowSize.
VoiceKey::~VoiceKey ()
Member Function Documentation
bool VoiceKey::AboveThreshold (WaveTrack & t, sampleCount start, sampleCount len)
References mThresholdDirectionChangesLower, mThresholdDirectionChangesUpper, mThresholdEnergy, mThresholdSignChangesLower, mThresholdSignChangesUpper, mUseDirectionChangesHigh, mUseDirectionChangesLow, mUseEnergy, mUseSignChangesHigh, mUseSignChangesLow, TestDirectionChanges(), TestEnergy(), and TestSignChanges().
Referenced by OffBackward(), OffForward(), OnBackward(), and OnForward().
void VoiceKey::AdjustThreshold (double t)
References mDirectionChangesMean, mDirectionChangesSD, mEnergyMean, mEnergySD, mSignChangesMean, mSignChangesSD, mThresholdAdjustment, mThresholdDirectionChangesLower, mThresholdDirectionChangesUpper, mThresholdEnergy, mThresholdSignChangesLower, and mThresholdSignChangesUpper.
Referenced by CalibrateNoise(), TranscriptionToolBar::OnAutomateSelection(), TranscriptionToolBar::OnCalibrate(), TranscriptionToolBar::OnEndOff(), TranscriptionToolBar::OnEndOn(), TranscriptionToolBar::OnSelectSilence(), TranscriptionToolBar::OnSelectSound(), TranscriptionToolBar::OnStartOff(), TranscriptionToolBar::OnStartOn(), and VoiceKey().
void VoiceKey::CalibrateNoise (WaveTrack & t, sampleCount start, sampleCount len)
References AdjustThreshold(), WaveTrack::GetRate(), mDirectionChangesMean, mDirectionChangesSD, mEnergyMean, mEnergySD, mSignChangesMean, mSignChangesSD, mThresholdAdjustment, mWindowSize, TestDirectionChanges(), TestEnergy(), and TestSignChanges().
Referenced by TranscriptionToolBar::OnCalibrate().
sampleCount VoiceKey::OffBackward (WaveTrack & t, sampleCount start, sampleCount len)
References AboveThreshold(), floatSample, WaveTrack::Get(), WaveTrack::GetRate(), mSilentWindowSize, mThresholdDirectionChangesLower, mThresholdDirectionChangesUpper, mThresholdEnergy, mThresholdSignChangesLower, mThresholdSignChangesUpper, mUseDirectionChangesHigh, mUseDirectionChangesLow, mUseEnergy, mUseSignChangesHigh, mUseSignChangesLow, mWindowSize, sgn(), TestDirectionChanges(), TestDirectionChangesUpdate(), TestEnergy(), TestEnergyUpdate(), TestSignChanges(), and TestSignChangesUpdate().
Referenced by TranscriptionToolBar::OnEndOff(), and TranscriptionToolBar::OnSelectSound().
sampleCount VoiceKey::OffForward (WaveTrack & t, sampleCount start, sampleCount len)
References AboveThreshold(), floatSample, WaveTrack::Get(), WaveTrack::GetRate(), mSilentWindowSize, mThresholdDirectionChangesLower, mThresholdDirectionChangesUpper, mThresholdEnergy, mThresholdSignChangesLower, mThresholdSignChangesUpper, mUseDirectionChangesHigh, mUseDirectionChangesLow, mUseEnergy, mUseSignChangesHigh, mUseSignChangesLow, mWindowSize, sgn(), TestDirectionChanges(), TestDirectionChangesUpdate(), TestEnergy(), TestEnergyUpdate(), TestSignChanges(), and TestSignChangesUpdate().
Referenced by TranscriptionToolBar::OnAutomateSelection(), TranscriptionToolBar::OnSelectSound(), and TranscriptionToolBar::OnStartOff().
sampleCount VoiceKey::OnBackward (WaveTrack & t, sampleCount start, sampleCount len)
References AboveThreshold(), floatSample, WaveTrack::Get(), WaveTrack::GetRate(), mSilentWindowSize, mThresholdDirectionChangesLower, mThresholdDirectionChangesUpper, mThresholdEnergy, mThresholdSignChangesLower, mThresholdSignChangesUpper, mUseDirectionChangesHigh, mUseDirectionChangesLow, mUseEnergy, mUseSignChangesHigh, mUseSignChangesLow, mWindowSize, sgn(), TestDirectionChanges(), TestDirectionChangesUpdate(), TestEnergy(), TestEnergyUpdate(), TestSignChanges(), and TestSignChangesUpdate().
Referenced by TranscriptionToolBar::OnEndOn(), and TranscriptionToolBar::OnSelectSilence().
sampleCount VoiceKey::OnForward (WaveTrack & t, sampleCount start, sampleCount len)
References AboveThreshold(), floatSample, WaveTrack::Get(), WaveTrack::GetRate(), mSignalWindowSize, mThresholdDirectionChangesLower, mThresholdDirectionChangesUpper, mThresholdEnergy, mThresholdSignChangesLower, mThresholdSignChangesUpper, mUseDirectionChangesHigh, mUseDirectionChangesLow, mUseEnergy, mUseSignChangesHigh, mUseSignChangesLow, mWindowSize, sgn(), TestDirectionChanges(), TestDirectionChangesUpdate(), TestEnergy(), TestEnergyUpdate(), TestSignChanges(), and TestSignChangesUpdate().
Referenced by TranscriptionToolBar::OnAutomateSelection(), TranscriptionToolBar::OnSelectSilence(), and TranscriptionToolBar::OnStartOn().
void VoiceKey::SetKeyType (bool erg, bool scLow, bool scHigh, bool dcLow, bool dcHigh)
References mUseDirectionChangesHigh, mUseDirectionChangesLow, mUseEnergy, mUseSignChangesHigh, and mUseSignChangesLow.
Referenced by TranscriptionToolBar::SetKeyType().
double VoiceKey::TestDirectionChanges (WaveTrack & t, sampleCount start, sampleCount len) [private]
References floatSample, WaveTrack::Get(), WaveTrack::GetBestBlockSize(), WaveTrack::GetMaxBlockSize(), and sgn().
Referenced by AboveThreshold(), CalibrateNoise(), OffBackward(), OffForward(), OnBackward(), and OnForward().
void VoiceKey::TestDirectionChangesUpdate (double & currentdirectionchanges, int length, int & atrend, const sampleFormat & a1, const sampleFormat & a2, int & ztrend, const sampleFormat & z1, const sampleFormat & z2) [private]
References sgn().
Referenced by OffBackward(), OffForward(), OnBackward(), and OnForward().
double VoiceKey::TestEnergy (WaveTrack & t, sampleCount start, sampleCount len) [private]
References floatSample, WaveTrack::Get(), WaveTrack::GetBestBlockSize(), and WaveTrack::GetMaxBlockSize().
Referenced by AboveThreshold(), CalibrateNoise(), OffBackward(), OffForward(), OnBackward(), and OnForward().
void VoiceKey::TestEnergyUpdate (double & prevErg, int length, const sampleFormat & drop, const sampleFormat & add) [private]
Referenced by OffBackward(), OffForward(), OnBackward(), and OnForward().
double VoiceKey::TestSignChanges (WaveTrack & t, sampleCount start, sampleCount len) [private]
References floatSample, WaveTrack::Get(), WaveTrack::GetBestBlockSize(), WaveTrack::GetMaxBlockSize(), and sgn().
Referenced by AboveThreshold(), CalibrateNoise(), OffBackward(), OffForward(), OnBackward(), and OnForward().
void VoiceKey::TestSignChangesUpdate (double & currentsignchanges, int length, const sampleFormat & a1, const sampleFormat & a2, const sampleFormat & z1, const sampleFormat & z2) [private]
References sgn().
Referenced by OffBackward(), OffForward(), OnBackward(), and OnForward().
Member Data Documentation
double VoiceKey::mDirectionChangesMean [private]
Referenced by AdjustThreshold(), CalibrateNoise(), and VoiceKey().
double VoiceKey::mDirectionChangesSD [private]
Referenced by AdjustThreshold(), CalibrateNoise(), and VoiceKey().
double VoiceKey::mEnergyMean [private]
Referenced by AdjustThreshold(), CalibrateNoise(), and VoiceKey().
double VoiceKey::mEnergySD [private]
Referenced by AdjustThreshold(), CalibrateNoise(), and VoiceKey().
double VoiceKey::mSignalWindowSize [private]
Referenced by OnForward(), and VoiceKey().
double VoiceKey::mSignChangesMean [private]
Referenced by AdjustThreshold(), CalibrateNoise(), and VoiceKey().
double VoiceKey::mSignChangesSD [private]
Referenced by AdjustThreshold(), CalibrateNoise(), and VoiceKey().
double VoiceKey::mSilentWindowSize [private]
Referenced by OffBackward(), OffForward(), OnBackward(), and VoiceKey().
double VoiceKey::mThresholdAdjustment [private]
Referenced by AdjustThreshold(), and CalibrateNoise().
double VoiceKey::mThresholdDirectionChangesLower [private]
Referenced by AboveThreshold(), AdjustThreshold(), OffBackward(), OffForward(), OnBackward(), and OnForward().
double VoiceKey::mThresholdDirectionChangesUpper [private]
Referenced by AboveThreshold(), AdjustThreshold(), OffBackward(), OffForward(), OnBackward(), and OnForward().
double VoiceKey::mThresholdEnergy [private]
Referenced by AboveThreshold(), AdjustThreshold(), OffBackward(), OffForward(), OnBackward(), and OnForward().
double VoiceKey::mThresholdSignChangesLower [private]
Referenced by AboveThreshold(), AdjustThreshold(), OffBackward(), OffForward(), OnBackward(), and OnForward().
double VoiceKey::mThresholdSignChangesUpper [private]
Referenced by AboveThreshold(), AdjustThreshold(), OffBackward(), OffForward(), OnBackward(), and OnForward().
bool VoiceKey::mUseDirectionChangesHigh [private]
Referenced by AboveThreshold(), OffBackward(), OffForward(), OnBackward(), OnForward(), SetKeyType(), and VoiceKey().
bool VoiceKey::mUseDirectionChangesLow [private]
Referenced by AboveThreshold(), OffBackward(), OffForward(), OnBackward(), OnForward(), SetKeyType(), and VoiceKey().
bool VoiceKey::mUseEnergy [private]
Referenced by AboveThreshold(), OffBackward(), OffForward(), OnBackward(), OnForward(), SetKeyType(), and VoiceKey().
bool VoiceKey::mUseSignChangesHigh [private]
Referenced by AboveThreshold(), OffBackward(), OffForward(), OnBackward(), OnForward(), SetKeyType(), and VoiceKey().
bool VoiceKey::mUseSignChangesLow [private]
Referenced by AboveThreshold(), OffBackward(), OffForward(), OnBackward(), OnForward(), SetKeyType(), and VoiceKey().
double VoiceKey::mWindowSize [private]
Referenced by CalibrateNoise(), OffBackward(), OffForward(), OnBackward(), OnForward(), and VoiceKey().
The documentation for this class was generated from the following files:
VoiceKey.h
VoiceKey.cpp