Audacity: NoiseRemovalDialog Class Reference
NoiseRemovalDialog Class Reference
Dialog used with EffectNoiseRemoval.
#include <NoiseRemoval.h>
Public Member Functions
NoiseRemovalDialog (EffectNoiseRemoval *effect, wxWindow *parent)
wxSizer * MakeNoiseRemovalDialog (bool call_fit=true, bool set_sizer=true)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
EffectNoiseRemoval * m_pEffect
wxButton * m_pButton_GetProfile
wxButton * m_pButton_Preview
wxButton * m_pButton_RemoveNoise
wxSlider * mGainS
wxSlider * mFreqS
wxSlider * mTimeS
wxTextCtrl * mGainT
wxTextCtrl * mFreqT
wxTextCtrl * mTimeT
double mGain
double mFreq
double mTime
Private Member Functions
void OnGetProfile (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
void OnRemoveNoise (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void OnGainText (wxCommandEvent &event)
void OnFreqText (wxCommandEvent &event)
void OnTimeText (wxCommandEvent &event)
void OnGainSlider (wxCommandEvent &event)
void OnFreqSlider (wxCommandEvent &event)
void OnTimeSlider (wxCommandEvent &event)
Detailed Description
Dialog used with EffectNoiseRemoval.
Constructor & Destructor Documentation
NoiseRemovalDialog::NoiseRemovalDialog (EffectNoiseRemoval * effect, wxWindow * parent)
Member Function Documentation
wxSizer* NoiseRemovalDialog::MakeNoiseRemovalDialog (bool call_fit = true, bool set_sizer = true)
void NoiseRemovalDialog::OnCancel (wxCommandEvent & event) [private]
void NoiseRemovalDialog::OnFreqSlider (wxCommandEvent & event) [private]
References mFreq, mFreqS, and mFreqT.
void NoiseRemovalDialog::OnFreqText (wxCommandEvent & event) [private]
References FREQ_MAX, FREQ_MIN, mFreq, mFreqS, mFreqT, and TrapLong().
void NoiseRemovalDialog::OnGainSlider (wxCommandEvent & event) [private]
References mGain, mGainS, and mGainT.
void NoiseRemovalDialog::OnGainText (wxCommandEvent & event) [private]
References GAIN_MAX, GAIN_MIN, mGain, mGainS, mGainT, and TrapLong().
void NoiseRemovalDialog::OnGetProfile (wxCommandEvent & event) [private]
void NoiseRemovalDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References m_pEffect, EffectNoiseRemoval::mAttackDecayTime, EffectNoiseRemoval::mDoProfile, mFreq, EffectNoiseRemoval::mFreqSmoothingHz, mGain, EffectNoiseRemoval::mNoiseGain, mTime, Effect::Preview(), and TransferDataFromWindow().
void NoiseRemovalDialog::OnRemoveNoise (wxCommandEvent & event) [private]
void NoiseRemovalDialog::OnTimeSlider (wxCommandEvent & event) [private]
References mTime, mTimeS, and mTimeT.
void NoiseRemovalDialog::OnTimeText (wxCommandEvent & event) [private]
References mTime, mTimeS, mTimeT, TIME_MAX, TIME_MIN, and TrapLong().
void NoiseRemovalDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddSlider(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddVariableText(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), FREQ_MAX, FREQ_MIN, GAIN_MAX, GAIN_MIN, GetActiveProject(), AudacityProject::GetCleanSpeechMode(), ShuttleGui::Id(), ID_BUTTON_GETPROFILE, ID_FREQ_SLIDER, ID_FREQ_TEXT, ID_GAIN_SLIDER, ID_GAIN_TEXT, ID_TIME_SLIDER, ID_TIME_TEXT, m_pButton_GetProfile, mFreqS, mFreqT, mGainS, mGainT, mTimeS, mTimeT, ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), TIME_MAX, and TIME_MIN.
bool NoiseRemovalDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
Referenced by OnPreview().
bool NoiseRemovalDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References FREQ_MAX, FREQ_MIN, GAIN_MAX, GAIN_MIN, mFreq, mFreqS, mFreqT, mGain, mGainS, mGainT, mTime, mTimeS, mTimeT, TIME_MAX, TIME_MIN, and TrapLong().
Referenced by EffectNoiseRemoval::PromptUser().
Member Data Documentation
wxButton* NoiseRemovalDialog::m_pButton_GetProfile
Referenced by PopulateOrExchange().
wxButton* NoiseRemovalDialog::m_pButton_Preview
Referenced by EffectNoiseRemoval::PromptUser().
wxButton* NoiseRemovalDialog::m_pButton_RemoveNoise
Referenced by EffectNoiseRemoval::PromptUser().
EffectNoiseRemoval* NoiseRemovalDialog::m_pEffect
Referenced by OnPreview().
double NoiseRemovalDialog::mFreq
Referenced by OnFreqSlider(), OnFreqText(), OnPreview(), EffectNoiseRemoval::PromptUser(), and TransferDataToWindow().
wxSlider* NoiseRemovalDialog::mFreqS
Referenced by OnFreqSlider(), OnFreqText(), PopulateOrExchange(), and TransferDataToWindow().
wxTextCtrl* NoiseRemovalDialog::mFreqT
Referenced by OnFreqSlider(), OnFreqText(), PopulateOrExchange(), and TransferDataToWindow().
double NoiseRemovalDialog::mGain
Referenced by OnGainSlider(), OnGainText(), OnPreview(), EffectNoiseRemoval::PromptUser(), and TransferDataToWindow().
wxSlider* NoiseRemovalDialog::mGainS
Referenced by OnGainSlider(), OnGainText(), PopulateOrExchange(), and TransferDataToWindow().
wxTextCtrl* NoiseRemovalDialog::mGainT
Referenced by OnGainSlider(), OnGainText(), PopulateOrExchange(), and TransferDataToWindow().
double NoiseRemovalDialog::mTime
Referenced by OnPreview(), OnTimeSlider(), OnTimeText(), EffectNoiseRemoval::PromptUser(), and TransferDataToWindow().
wxSlider* NoiseRemovalDialog::mTimeS
Referenced by OnTimeSlider(), OnTimeText(), PopulateOrExchange(), and TransferDataToWindow().
wxTextCtrl* NoiseRemovalDialog::mTimeT
Referenced by OnTimeSlider(), OnTimeText(), PopulateOrExchange(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
NoiseRemoval.h
NoiseRemoval.cpp