Audacity: ShuttleGuiBase Class Reference
ShuttleGuiBase Class Reference
Base class for shuttling data to and from a GUI.
#include <ShuttleGui.h>
Public Member Functions
ShuttleGuiBase (wxWindow *pParent, teShuttleMode ShuttleMode)
~ShuttleGuiBase (void)
void Init ()
void AddPrompt (const wxString &Prompt)
Right aligned text string.
void AddUnits (const wxString &Prompt)
Left aligned text string.
void AddTitle (const wxString &Prompt)
Centred text string.
wxWindow * AddWindow (wxWindow *pWindow, int Flags=wxALIGN_CENTRE|wxALL)
wxSlider * AddSlider (const wxString &Prompt, int pos, int Max, int Min=0)
wxSlider * AddVSlider (const wxString &Prompt, int pos, int Max)
wxSpinCtrl * AddSpinCtrl (const wxString &Prompt, int Value, int Max, int Min)
wxTreeCtrl * AddTree ()
wxRadioButton * AddRadioButton (const wxString &Prompt)
wxRadioButton * AddRadioButtonToGroup (const wxString &Prompt)
wxButton * AddButton (const wxString &Text, int PositionFlags=wxALIGN_CENTRE)
wxBitmapButton * AddBitmapButton (const wxBitmap &Bitmap, int PositionFlags=wxALIGN_CENTRE)
wxStaticText * AddVariableText (const wxString &Str, bool bCenter=false, int PositionFlags=0)
wxTextCtrl * AddTextBox (const wxString &Caption, const wxString &Value, const int nChars)
wxTextCtrl * AddTextWindow (const wxString &Value)
Multiline text box that grows.
wxListBox * AddListBox (const wxArrayString *pChoices, long style=0)
wxListCtrl * AddListControl ()
wxListCtrl * AddListControlReportMode ()
wxCheckBox * AddCheckBox (const wxString &Prompt, const wxString &Selected)
wxCheckBox * AddCheckBoxOnRight (const wxString &Prompt, const wxString &Selected)
wxComboBox * AddCombo (const wxString &Prompt, const wxString &Selected, const wxArrayString *pChoices)
wxChoice * AddChoice (const wxString &Prompt, const wxString &Selected, const wxArrayString *pChoices)
wxMenuBar * AddMenuBar ()
wxMenu * AddMenu (const wxString &Title)
void AddIcon (wxBitmap *pBmp)
void AddIconButton (const wxString &Command, const wxString &Params, wxBitmap *pBmp)
void AddFixedText (const wxString &Str, bool bCenter=false)
void AddConstTextBox (const wxString &Caption, const wxString &Value)
Single line text box of fixed size.
void StartHorizontalLay (int PositionFlags=wxALIGN_CENTRE, int iProp=1)
void EndHorizontalLay ()
void StartVerticalLay (int iProp=1)
void EndVerticalLay ()
wxScrolledWindow * StartScroller (int iStyle=0)
void EndScroller ()
wxPanel * StartPanel (int iStyle=0)
void EndPanel ()
void StartMultiColumn (int nCols, int PositionFlags=wxALIGN_LEFT)
void EndMultiColumn ()
void StartTwoColumn ()
void EndTwoColumn ()
void StartThreeColumn ()
void EndThreeColumn ()
wxStaticBox * StartStatic (const wxString &Str, int iProp=0)
void EndStatic ()
wxNotebook * StartNotebook ()
void EndNotebook ()
wxNotebookPage * StartNotebookPage (const wxString Name)
void StartNotebookPage (const wxString Name, wxNotebookPage *pPage)
void EndNotebookPage ()
wxPanel * StartInvisiblePanel ()
void EndInvisiblePanel ()
void StartRadioButtonGroup (const wxString &SettingName)
void EndRadioButtonGroup ()
void StartRadioButtonGroup (const wxString &SettingName, const int iDefaultValue)
void StartRadioButtonGroup (const wxString &SettingName, const wxString &DefaultValue)
void DoDataShuttle (const wxString &Name, WrappedType &WrappedRef)
bool DoStep (int iStep)
int TranslateToIndex (const wxString &Value, const wxArrayString &Choices)
String-to-Index.
wxString TranslateFromIndex (const int nIn, const wxArrayString &Choices)
Index-to-String.
int TranslateToIndex (const int Value, const wxArrayInt &Choices)
Int-to-Index (choices can be items like e.g 0x400120).
int TranslateFromIndex (const int nIn, const wxArrayInt &Choices)
Index-to-int (choices can be items like e.g 0x400120).
wxTextCtrl * TieTextBox (const wxString &Prompt, WrappedType &WrappedRef, const int nChars)
wxTextCtrl * TieTextBox (const wxString &Caption, wxString &Value, const int nChars=0)
wxTextCtrl * TieTextBox (const wxString &Prompt, int &Selected, const int nChars=0)
wxTextCtrl * TieTextBox (const wxString &Prompt, double &Value, const int nChars=0)
wxCheckBox * TieCheckBox (const wxString &Prompt, WrappedType &WrappedRef)
wxCheckBox * TieCheckBox (const wxString &Prompt, const wxString &Selected)
wxCheckBox * TieCheckBox (const wxString &Prompt, bool &Var)
wxCheckBox * TieCheckBoxOnRight (const wxString &Prompt, WrappedType &WrappedRef)
wxCheckBox * TieCheckBoxOnRight (const wxString &Prompt, bool &Var)
wxChoice * TieChoice (const wxString &Prompt, WrappedType &WrappedRef, const wxArrayString *pChoices)
wxChoice * TieChoice (const wxString &Prompt, wxString &Selected, const wxArrayString *pChoices)
wxChoice * TieChoice (const wxString &Prompt, int &Selected, const wxArrayString *pChoices)
wxSlider * TieSlider (const wxString &Prompt, WrappedType &WrappedRef, const int max, const int min=0)
wxSlider * TieSlider (const wxString &Prompt, int &pos, const int max, const int min=0)
wxSlider * TieSlider (const wxString &Prompt, float &pos, const float fMin, const float fMax)
wxSlider * TieVSlider (const wxString &Prompt, float &pos, const float fMin, const float fMax)
wxRadioButton * TieRadioButton (const wxString &Prompt, WrappedType &WrappedRef)
wxRadioButton * TieRadioButton (const wxString &Prompt, const int iValue)
This function must be within a StartRadioButtonGroup - EndRadioButtonGroup pair.
wxRadioButton * TieRadioButton (const wxString &Prompt, const wxString &Value)
This function must be within a StartRadioButtonGroup - EndRadioButtonGroup pair.
wxSpinCtrl * TieSpinCtrl (const wxString &Prompt, WrappedType &WrappedRef, const int max, const int min=0)
wxSpinCtrl * TieSpinCtrl (const wxString &Prompt, int &Value, const int max, const int min=0)
wxCheckBox * TieCheckBox (const wxString &Prompt, const wxString &SettingName, const bool bDefault)
wxCheckBox * TieCheckBoxOnRight (const wxString &Prompt, const wxString &SettingName, const bool bDefault)
wxChoice * TieChoice (const wxString &Prompt, const wxString &SettingName, const wxString &Default, const wxArrayString &Choices, const wxArrayString &TranslatedChoices)
wxChoice * TieChoice (const wxString &Prompt, const wxString &SettingName, const int Default, const wxArrayString &Choices, const wxArrayInt &TranslatedChoices)
wxTextCtrl * TieTextBox (const wxString &Prompt, const wxString &SettingName, const wxString &Default, const int nChars)
wxTextCtrl * TieTextBox (const wxString &Prompt, const wxString &SettingName, const double &Default, const int nChars)
wxSlider * TieSlider (const wxString &Prompt, const wxString &SettingName, const int iDefault, const int max, const int min=0)
wxSpinCtrl * TieSpinCtrl (const wxString &Prompt, const wxString &SettingName, const int Value, const int max, const int min)
void EnableCtrl (bool bEnable)
void SetSizeHints (int minX, int minY)
Used to modify an already placed Window.
void SetBorder (int Border)
void SetStyle (int Style)
void SetNoMatchSelector (int iSelector)
void SetSizerProportion (int iProp)
void SetStretchyCol (int i)
Used to modify an already placed FlexGridSizer to make a column stretchy.
void SetStretchyRow (int i)
Used to modify an already placed FlexGridSizer to make a row stretchy.
wxWindow * GetParent ()
ShuttleGuiBase & Prop (int iProp)
int GetId ()
void UseUpId ()
Protected Member Functions
void SetProportions (int Default)
void PushSizer ()
void PopSizer ()
void UpdateSizersCore (bool bPrepend, int Flags)
void UpdateSizers ()
void UpdateSizersC ()
void UpdateSizersAtStart ()
long Style (long Style)
Protected Attributes
wxWindow * mpLastWind
wxWindow * mpDlg
wxSizer * pSizerStack [nMaxNestedSizers]
wxString mBoxName
Shuttle * mpShuttle
int miNoMatchSelector
teShuttleMode mShuttleMode
Used in choices to determine which item to use on no match.
wxString mSettingName
int mRadioCount
The setting controlled by a group.
WrappedType mRadioValue
The index of this radio item. -1 for none.
wxString mRadioValueString
The wrapped value associated with the active radio button.
int mRadioValueInt
Unwrapped string value.
int miSizerProp
Unwrapped integer value.
int mSizerDepth
int miBorder
long miStyle
int miProp
int miId
int miIdNext
int miIdSetByUser
int miPropSetByUser
wxSizer * mpSubSizer
wxSizer * mpSizer
wxWindow * mpParent
wxWindow * mpWind
wxMenuBar * mpMenuBar
wxMenu * mpMenu
Detailed Description
Base class for shuttling data to and from a GUI.
see also ShuttleGui
Use the:
Start / End methods for containers, like two-column-layout.
Add methods if you are only interested in creating the controls.
Tie methods if you also want to exchange data using ShuttleGui.
The code in this file is fairly repetitive. We are dealing with
Many different types of Widget.
Creation / Reading / Writing / Exporting / Importing
int, float, string variants (for example of TextCtrl contents).
A technique used to reduce the size of the Tie functions is to have one generic Tie function that uses WrappedType for its data type. Type specific Tie functions themselves call the generic variant.
A second technique used to reduce the size of Tie functions only comes into play for two-step Tie functions. (A two step Tie function is one that transfers data between the registry and the GUI via an intermediate temporary variable). In the two step style, a function ShuttleGuiBase::DoStep() determines which transfers in the function are to be done, reducing repetitive if-then-else's.
Although unusual, these two techniques make the code easier to add to and much easier to check for correctness. The alternative 'more obvious' code that just repeats code as needed is considerably longer.
You would rarely use ShuttleGuiBase directly, instead you'd use ShuttleGui.
There is DOxygen documentation on how to use the ShuttleGui class in ShuttleSystem .
Constructor & Destructor Documentation
ShuttleGuiBase::ShuttleGuiBase (wxWindow * pParent, teShuttleMode ShuttleMode)
References eIsCreating, Init(), mpDlg, mpParent, and mShuttleMode.
ShuttleGuiBase::~ShuttleGuiBase (void)
Member Function Documentation
wxBitmapButton * ShuttleGuiBase::AddBitmapButton (const wxBitmap & Bitmap, int PositionFlags = wxALIGN_CENTRE)
References eIsCreating, miId, miProp, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizersCore(), and UseUpId().
wxButton * ShuttleGuiBase::AddButton (const wxString & Text, int PositionFlags = wxALIGN_CENTRE)
References eIsCreating, miId, miProp, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizersCore(), and UseUpId().
Referenced by ContrastDialog::ContrastDialog(), ExportCL::Export(), HistoryWindow::HistoryWindow(), BenchmarkDialog::MakeBenchmarkDialog(), BatchProcessDialog::OnApplyToFiles(), ThemePrefs::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), LibraryPrefs::PopulateOrExchange(), KeyConfigPrefs::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), EditChainsDialog::PopulateOrExchange(), BatchProcessDialog::PopulateOrExchange(), BatchCommandDialog::PopulateOrExchange(), and ShowHtmlText().
wxCheckBox * ShuttleGuiBase::AddCheckBox (const wxString & Prompt, const wxString & Selected)
References eIsCreating, miId, miProp, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), and UseUpId().
Referenced by BenchmarkDialog::MakeBenchmarkDialog(), SplashDialog::Populate(), TimeScaleDialog::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), FFmpegNotFoundDialog::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), AmplifyDialog::PopulateOrExchange(), TieCheckBox(), and WarningDialog::WarningDialog().
wxCheckBox * ShuttleGuiBase::AddCheckBoxOnRight (const wxString & Prompt, const wxString & Selected)
For a consistant two-column layout we want labels on the left and controls on the right. CheckBoxes break that rule, so we fake it by placing a static text label and then a tick box with an empty label.
References AddPrompt(), eIsCreating, miId, miProp, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), and UseUpId().
Referenced by TieCheckBoxOnRight().
wxChoice * ShuttleGuiBase::AddChoice (const wxString & Prompt, const wxString & Selected, const wxArrayString * pChoices)
References AddPrompt(), eIsCreating, miId, miProp, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), and UseUpId().
Referenced by ExportMP3::AskResample(), ExportFFmpeg::AskResample(), ImportRawDialog::ImportRawDialog(), LangChoiceDialog::LangChoiceDialog(), KeyConfigPrefs::PopulateOrExchange(), ExportPCMOptions::PopulateOrExchange(), DevicePrefs::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), MixerToolBar::ShowInputSourceDialog(), and TieChoice().
wxComboBox * ShuttleGuiBase::AddCombo (const wxString & Prompt, const wxString & Selected, const wxArrayString * pChoices)
References AddPrompt(), eIsCreating, miId, miProp, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), and UseUpId().
Referenced by TrackPanel::OnRateOther(), AudacityProject::OnResample(), and ExportFFmpegOptions::PopulateOrExchange().
void ShuttleGuiBase::AddConstTextBox (const wxString & Caption, const wxString & Value)
Single line text box of fixed size.
References AddPrompt(), eIsCreating, miId, miProp, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), and UseUpId().
void ShuttleGuiBase::AddFixedText (const wxString & Str, bool bCenter = false)
References eIsCreating, miId, miProp, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), UpdateSizersC(), and UseUpId().
Referenced by ContrastDialog::ContrastDialog(), ErrorDialog::ErrorDialog(), BatchProcessDialog::OnApplyToProject(), ThemePrefs::PopulateOrExchange(), KeyConfigPrefs::PopulateOrExchange(), ImportExportPrefs::PopulateOrExchange(), FFmpegNotFoundDialog::PopulateOrExchange(), ExportPCMOptions::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), ExportCLOptions::PopulateOrExchange(), EffectsPrefs::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), DevicePrefs::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), and ToneGenDialog::PopulateOrExchangeStandard().
void ShuttleGuiBase::AddIcon (wxBitmap * pBmp)
References eIsCreating, miId, mpParent, mpWind, mShuttleMode, Style(), UpdateSizersC(), and UseUpId().
void ShuttleGuiBase::AddIconButton (const wxString & Command, const wxString & Params, wxBitmap * pBmp)
wxListBox * ShuttleGuiBase::AddListBox (const wxArrayString * pChoices, long style = 0)
References eIsCreating, miId, mpDlg, mpParent, mpWind, mShuttleMode, SetProportions(), UpdateSizers(), and UseUpId().
Referenced by ExportFFmpegOptions::PopulateOrExchange().
wxListCtrl * ShuttleGuiBase::AddListControl ()
References eIsCreating, miId, mpDlg, mpParent, mpWind, mShuttleMode, SetProportions(), Style(), UpdateSizers(), and UseUpId().
Referenced by BatchCommandDialog::PopulateOrExchange().
wxListCtrl * ShuttleGuiBase::AddListControlReportMode ()
References eIsCreating, miId, mpDlg, mpParent, mpWind, mShuttleMode, SetProportions(), Style(), UpdateSizers(), and UseUpId().
Referenced by HistoryWindow::HistoryWindow(), BatchProcessDialog::OnApplyToFiles(), MousePrefs::PopulateOrExchange(), KeyConfigPrefs::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), EditChainsDialog::PopulateOrExchange(), and BatchProcessDialog::PopulateOrExchange().
wxMenu * ShuttleGuiBase::AddMenu (const wxString & Title)
References mpMenu, and mpMenuBar.
wxMenuBar * ShuttleGuiBase::AddMenuBar ()
References mpMenuBar, and mpParent.
void ShuttleGuiBase::AddPrompt (const wxString & Prompt)
Right aligned text string.
References eIsCreating, miProp, mpParent, mpWind, mShuttleMode, Style(), and UpdateSizersCore().
Referenced by AddCheckBoxOnRight(), AddChoice(), AddCombo(), AddConstTextBox(), AddSlider(), AddSpinCtrl(), AddTextBox(), HistoryWindow::HistoryWindow(), TrackPanel::OnSetFont(), QualityPrefs::PopulateOrExchange(), NoiseDialog::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), DevicePrefs::PopulateOrExchange(), and ChangePitchDialog::PopulateOrExchange().
wxRadioButton * ShuttleGuiBase::AddRadioButton (const wxString & Prompt)
Todo:
This function and the next one, suitably adapted, could be used by TieRadioButton.
References eIsCreating, miId, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), and UseUpId().
Referenced by ExportMultiple::PopulateOrExchange(), and ChangePitchDialog::PopulateOrExchange().
wxRadioButton * ShuttleGuiBase::AddRadioButtonToGroup (const wxString & Prompt)
References eIsCreating, miId, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), and UseUpId().
Referenced by ExportMultiple::PopulateOrExchange(), and ChangePitchDialog::PopulateOrExchange().
wxSlider * ShuttleGuiBase::AddSlider (const wxString & Prompt, int pos, int Max, int Min = 0)
References AddPrompt(), eIsCreating, miId, miProp, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), and UseUpId().
Referenced by WahwahDialog::PopulateOrExchange(), TimeScaleDialog::PopulateOrExchange(), PhaserDialog::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ClickRemovalDialog::PopulateOrExchange(), ChangeTempoDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), BassBoostDialog::PopulateOrExchange(), AmplifyDialog::PopulateOrExchange(), and TieSlider().
wxSpinCtrl * ShuttleGuiBase::AddSpinCtrl (const wxString & Prompt, int Value, int Max, int Min)
References AddPrompt(), eIsCreating, miId, miProp, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), and UseUpId().
Referenced by TieSpinCtrl().
wxTextCtrl * ShuttleGuiBase::AddTextBox (const wxString & Caption, const wxString & Value, const int nChars)
References AddPrompt(), eIsCreating, miId, miProp, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), and UseUpId().
Referenced by ContrastDialog::ContrastDialog(), EffectAutoDuckDialog::EffectAutoDuckDialog(), HistoryWindow::HistoryWindow(), ImportRawDialog::ImportRawDialog(), BenchmarkDialog::MakeBenchmarkDialog(), WahwahDialog::PopulateOrExchange(), TimeScaleDialog::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), RepeatDialog::PopulateOrExchange(), PhaserDialog::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), FindDialog::PopulateOrExchange(), EchoDialog::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), ClickRemovalDialog::PopulateOrExchange(), ChangeTempoDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), BatchCommandDialog::PopulateOrExchange(), BassBoostDialog::PopulateOrExchange(), AmplifyDialog::PopulateOrExchange(), SliderDialog::SliderDialog(), and TieTextBox().
wxTextCtrl * ShuttleGuiBase::AddTextWindow (const wxString & Value)
Multiline text box that grows.
References eIsCreating, miId, mpDlg, mpParent, mpWind, mShuttleMode, SetProportions(), Style(), UpdateSizers(), and UseUpId().
Referenced by ExportCL::Export(), BenchmarkDialog::MakeBenchmarkDialog(), TagsEditor::OnEdit(), and ShowInfoDialog().
void ShuttleGuiBase::AddTitle (const wxString & Prompt)
Centred text string.
References eIsCreating, mpParent, mpWind, mShuttleMode, Style(), and UpdateSizers().
Referenced by ExportMP3::AskResample(), ExportFFmpeg::AskResample(), ContrastDialog::ContrastDialog(), EffectAutoDuckDialog::EffectAutoDuckDialog(), KeyConfigPrefs::Populate(), WahwahDialog::PopulateOrExchange(), TruncSilenceDialog::PopulateOrExchange(), TimeScaleDialog::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), RepeatDialog::PopulateOrExchange(), PhaserDialog::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), LevellerDialog::PopulateOrExchange(), FindClippingDialog::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), FindDialog::PopulateOrExchange(), EchoDialog::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ClickRemovalDialog::PopulateOrExchange(), ChangeTempoDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), BassBoostDialog::PopulateOrExchange(), AmplifyDialog::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), and ShowInfoDialog().
wxTreeCtrl * ShuttleGuiBase::AddTree ()
References eIsCreating, miId, mpDlg, mpParent, mpWind, mShuttleMode, SetProportions(), Style(), UpdateSizers(), and UseUpId().
void ShuttleGuiBase::AddUnits (const wxString & Prompt)
Left aligned text string.
References eIsCreating, miProp, mpParent, mpWind, mShuttleMode, Style(), and UpdateSizersCore().
Referenced by EffectAutoDuckDialog::EffectAutoDuckDialog(), ImportRawDialog::ImportRawDialog(), TruncSilenceDialog::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), RecordingPrefs::PopulateOrExchange(), ProjectsPrefs::PopulateOrExchange(), PlaybackPrefs::PopulateOrExchange(), ChangeTempoDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), and WarningDialog::WarningDialog().
wxStaticText * ShuttleGuiBase::AddVariableText (const wxString & Str, bool bCenter = false, int PositionFlags = 0)
References eIsCreating, miId, miProp, mpDlg, mpParent, mpWind, mShuttleMode, Style(), UpdateSizers(), UpdateSizersC(), UpdateSizersCore(), and UseUpId().
Referenced by HistoryWindow::HistoryWindow(), TruncSilenceDialog::PopulateOrExchange(), RepeatDialog::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), LibraryPrefs::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), and CompressorDialog::PopulateOrExchange().
wxSlider* ShuttleGuiBase::AddVSlider (const wxString & Prompt, int pos, int Max)
wxWindow * ShuttleGuiBase::AddWindow (wxWindow * pWindow, int Flags = wxALIGN_CENTRE | wxALL)
Very generic 'Add' function. We can add anything we like. Useful for unique controls
References eIsCreating, mpWind, mShuttleMode, SetProportions(), and UpdateSizersCore().
Referenced by AboutDialog::AboutDialog(), ContrastDialog::ContrastDialog(), EffectAutoDuckDialog::EffectAutoDuckDialog(), EVT_TREE_KEY_DOWN(), HistoryWindow::HistoryWindow(), TrackPanel::OnSetFont(), SplashDialog::Populate(), AboutDialog::PopulateAudacityPage(), AboutDialog::PopulateInformationPage(), AboutDialog::PopulateLicensePage(), TimerRecordDialog::PopulateOrExchange(), TimeDialog::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), NoiseDialog::PopulateOrExchange(), KeyConfigPrefs::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), ToneGenDialog::PopulateOrExchangeStandard(), ShowHtmlText(), ShowInfoDialog(), and SliderDialog::SliderDialog().
void ShuttleGuiBase::DoDataShuttle (const wxString & Name, WrappedType & WrappedRef)
When we're exchanging with the configured shuttle rather than with the GUI We use this function.
References mpShuttle, and Shuttle::TransferWrappedType().
Referenced by EndRadioButtonGroup(), StartRadioButtonGroup(), TieCheckBox(), TieCheckBoxOnRight(), TieChoice(), TieSlider(), TieSpinCtrl(), and TieTextBox().
bool ShuttleGuiBase::DoStep (int iStep)
Code-Condenser function.
We have functions which need to do:
  // Either: Values are coming in:
  DoDataShuttle( SettingName, WrappedRef );
  TieMyControl( Prompt, WrappedRef );
  // Or: Values are going out:
  TieMyControl( Prompt, WrappedRef );
  DoDataShuttle( SettingName, WrappedRef );
So we make a list of all the possible steps, and have DoStep choose which ones are actually done, like this:
  if( DoStep(1) ) DoFirstThing();
  if( DoStep(2) ) DoSecondThing();
  if( DoStep(3) ) DoThirdThing();
The repeated choice logic can then be taken out of those functions.
JKC: This paves the way for doing data validation too, though when we add that we wil need to renumber the steps.
References eIsCreating, eIsGettingFromDialog, eIsSettingToDialog, and mShuttleMode.
Referenced by TieCheckBox(), TieCheckBoxOnRight(), TieChoice(), TieSlider(), TieSpinCtrl(), and TieTextBox().
void ShuttleGuiBase::EnableCtrl (bool bEnable)
References eIsCreating, mpLastWind, and mShuttleMode.
void ShuttleGuiBase::EndHorizontalLay ()
References eIsCreating, mShuttleMode, and PopSizer().
Referenced by ExportMP3::AskResample(), ExportFFmpeg::AskResample(), ContrastDialog::ContrastDialog(), EffectAutoDuckDialog::EffectAutoDuckDialog(), EVT_TREE_KEY_DOWN(), HistoryWindow::HistoryWindow(), BenchmarkDialog::MakeBenchmarkDialog(), BatchProcessDialog::OnApplyToFiles(), BatchProcessDialog::OnApplyToProject(), TrackPanel::OnRateOther(), AudacityProject::OnResample(), WahwahDialog::PopulateOrExchange(), TruncSilenceDialog::PopulateOrExchange(), TimeScaleDialog::PopulateOrExchange(), ThemePrefs::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), RepeatDialog::PopulateOrExchange(), QualityPrefs::PopulateOrExchange(), PhaserDialog::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), LevellerDialog::PopulateOrExchange(), KeyConfigPrefs::PopulateOrExchange(), FindClippingDialog::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), ExportPCMOptions::PopulateOrExchange(), ExportOGGOptions::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportMP2Options::PopulateOrExchange(), ExportFLACOptions::PopulateOrExchange(), ExportFFmpegWMAOptions::PopulateOrExchange(), ExportFFmpegAMRWBOptions::PopulateOrExchange(), ExportFFmpegAMRNBOptions::PopulateOrExchange(), ExportFFmpegAC3Options::PopulateOrExchange(), ExportCLOptions::PopulateOrExchange(), EchoDialog::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ClickRemovalDialog::PopulateOrExchange(), ChangeTempoDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), EditChainsDialog::PopulateOrExchange(), BatchProcessDialog::PopulateOrExchange(), BatchPrefs::PopulateOrExchange(), BassBoostDialog::PopulateOrExchange(), AmplifyDialog::PopulateOrExchange(), ShowHtmlText(), ShowInfoDialog(), and MixerToolBar::ShowInputSourceDialog().
void ShuttleGuiBase::EndInvisiblePanel ()
References EndPanel().
void ShuttleGuiBase::EndMultiColumn ()
References eIsCreating, mShuttleMode, and PopSizer().
Referenced by ContrastDialog::ContrastDialog(), EffectAutoDuckDialog::EffectAutoDuckDialog(), HistoryWindow::HistoryWindow(), ImportRawDialog::ImportRawDialog(), BenchmarkDialog::MakeBenchmarkDialog(), TrackPanel::OnSetFont(), WahwahDialog::PopulateOrExchange(), TracksPrefs::PopulateOrExchange(), TimeScaleDialog::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), SpectrumPrefs::PopulateOrExchange(), SoundActivatedRecord::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), RecordingPrefs::PopulateOrExchange(), QualityPrefs::PopulateOrExchange(), PhaserDialog::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), NoiseDialog::PopulateOrExchange(), GUIPrefs::PopulateOrExchange(), FindClippingDialog::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), ExportPCMOptions::PopulateOrExchange(), ExportOGGOptions::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), ExportCLOptions::PopulateOrExchange(), EchoDialog::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), DevicePrefs::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ClickRemovalDialog::PopulateOrExchange(), ChangeTempoDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), BatchCommandDialog::PopulateOrExchange(), BassBoostDialog::PopulateOrExchange(), AmplifyDialog::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), and ToneGenDialog::PopulateOrExchangeStandard().
void ShuttleGuiBase::EndNotebook ()
References mpParent.
Referenced by AboutDialog::AboutDialog().
void ShuttleGuiBase::EndNotebookPage ()
References eIsCreating, mpParent, mShuttleMode, and PopSizer().
Referenced by AboutDialog::PopulateAudacityPage(), AboutDialog::PopulateInformationPage(), and AboutDialog::PopulateLicensePage().
void ShuttleGuiBase::EndPanel ()
References eIsCreating, mpParent, mShuttleMode, and PopSizer().
Referenced by EndInvisiblePanel(), ScreenFrame::PopulateOrExchange(), and ShowHtmlText().
void ShuttleGuiBase::EndRadioButtonGroup ()
Call this after any TieRadioButton calls. It's generic too. We don't need type-specific ones.
References DoDataShuttle(), eIsGettingFromDialog, WrappedType::Init(), mRadioCount, mRadioValue, mSettingName, and mShuttleMode.
Referenced by ProjectsPrefs::PopulateOrExchange(), ImportExportPrefs::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), and ExportMP3Options::PopulateOrExchange().
void ShuttleGuiBase::EndScroller ()
References eIsCreating, mpParent, mpSizer, mShuttleMode, and PopSizer().
void ShuttleGuiBase::EndStatic ()
References eIsCreating, mShuttleMode, and PopSizer().
Referenced by ExportMP3::AskResample(), ExportFFmpeg::AskResample(), ContrastDialog::ContrastDialog(), HistoryWindow::HistoryWindow(), BatchProcessDialog::OnApplyToFiles(), BatchProcessDialog::OnApplyToProject(), KeyConfigPrefs::Populate(), WarningsPrefs::PopulateOrExchange(), TracksPrefs::PopulateOrExchange(), TimerRecordDialog::PopulateOrExchange(), TimeDialog::PopulateOrExchange(), ThemePrefs::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), SpectrumPrefs::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), RecordingPrefs::PopulateOrExchange(), QualityPrefs::PopulateOrExchange(), ProjectsPrefs::PopulateOrExchange(), PlaybackPrefs::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), MousePrefs::PopulateOrExchange(), LibraryPrefs::PopulateOrExchange(), LevellerDialog::PopulateOrExchange(), KeyConfigPrefs::PopulateOrExchange(), ImportExportPrefs::PopulateOrExchange(), GUIPrefs::PopulateOrExchange(), ExportPCMOptions::PopulateOrExchange(), ExportOGGOptions::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportMP2Options::PopulateOrExchange(), ExportFLACOptions::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), ExportFFmpegWMAOptions::PopulateOrExchange(), ExportFFmpegAMRWBOptions::PopulateOrExchange(), ExportFFmpegAMRNBOptions::PopulateOrExchange(), ExportFFmpegAACOptions::PopulateOrExchange(), ExportFFmpegAC3Options::PopulateOrExchange(), ExportCLOptions::PopulateOrExchange(), EffectsPrefs::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), DevicePrefs::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), EditChainsDialog::PopulateOrExchange(), BatchProcessDialog::PopulateOrExchange(), BatchPrefs::PopulateOrExchange(), and BatchCommandDialog::PopulateOrExchange().
void ShuttleGuiBase::EndThreeColumn () [inline]
Referenced by RecordingPrefs::PopulateOrExchange(), ProjectsPrefs::PopulateOrExchange(), PlaybackPrefs::PopulateOrExchange(), and KeyConfigPrefs::PopulateOrExchange().
void ShuttleGuiBase::EndTwoColumn () [inline]
Referenced by ImportRawDialog::ImportRawDialog(), TruncSilenceDialog::PopulateOrExchange(), SpectrumPrefs::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), LibraryPrefs::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportMP2Options::PopulateOrExchange(), ExportFLACOptions::PopulateOrExchange(), ExportFFmpegWMAOptions::PopulateOrExchange(), ExportFFmpegAMRWBOptions::PopulateOrExchange(), ExportFFmpegAMRNBOptions::PopulateOrExchange(), ExportFFmpegAACOptions::PopulateOrExchange(), ExportFFmpegAC3Options::PopulateOrExchange(), and DirectoriesPrefs::PopulateOrExchange().
void ShuttleGuiBase::EndVerticalLay ()
References eIsCreating, mShuttleMode, and PopSizer().
Referenced by ShuttleGui::AddStandardButtons(), ExportMP3::AskResample(), ExportFFmpeg::AskResample(), EffectAutoDuckDialog::EffectAutoDuckDialog(), ErrorDialog::ErrorDialog(), EVT_TREE_KEY_DOWN(), HistoryWindow::HistoryWindow(), ImportRawDialog::ImportRawDialog(), EffectDialog::Init(), LangChoiceDialog::LangChoiceDialog(), BenchmarkDialog::MakeBenchmarkDialog(), BatchProcessDialog::OnApplyToFiles(), TagsEditor::OnEdit(), TrackPanel::OnRateOther(), AudacityProject::OnResample(), TrackPanel::OnSetFont(), SplashDialog::Populate(), KeyConfigPrefs::Populate(), AboutDialog::PopulateAudacityPage(), AboutDialog::PopulateInformationPage(), AboutDialog::PopulateLicensePage(), TimerRecordDialog::PopulateOrExchange(), TimeDialog::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), SoundActivatedRecord::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), FFmpegNotFoundDialog::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), BatchProcessDialog::PopulateOrExchange(), BatchCommandDialog::PopulateOrExchange(), ShowInfoDialog(), MixerToolBar::ShowInputSourceDialog(), and SliderDialog::SliderDialog().
int ShuttleGuiBase::GetId () [inline]
wxWindow* ShuttleGuiBase::GetParent () [inline]
Referenced by AboutDialog::AboutDialog(), SplashDialog::Populate(), AboutDialog::PopulateAudacityPage(), AboutDialog::PopulateInformationPage(), AboutDialog::PopulateLicensePage(), TagsEditor::PopulateOrExchange(), and CompressorDialog::PopulateOrExchange().
void ShuttleGuiBase::Init ()
References eIsCreating, miBorder, miId, miIdNext, miIdSetByUser, miNoMatchSelector, miProp, miPropSetByUser, miSizerProp, miStyle, mpParent, mpShuttle, mpSizer, mpSubSizer, mpWind, mRadioCount, mSettingName, mShuttleMode, mSizerDepth, and PushSizer().
Referenced by ShuttleGui::ShuttleGui(), and ShuttleGuiBase().
void ShuttleGuiBase::PopSizer () [protected]
References mpSizer, mSizerDepth, and pSizerStack.
Referenced by ShuttleGui::AddStandardButtons(), EndHorizontalLay(), EndMultiColumn(), EndNotebookPage(), EndPanel(), EndScroller(), EndStatic(), and EndVerticalLay().
ShuttleGuiBase & ShuttleGuiBase::Prop (int iProp)
Reimplemented in ShuttleGui.
References miPropSetByUser.
Referenced by ShuttleGui::Prop().
void ShuttleGuiBase::PushSizer () [protected]
References mpSizer, mSizerDepth, nMaxNestedSizers, and pSizerStack.
Referenced by Init(), StartInvisiblePanel(), StartNotebookPage(), StartPanel(), StartScroller(), and UpdateSizersCore().
void ShuttleGuiBase::SetBorder (int Border) [inline]
Referenced by ExportMP3::AskResample(), ExportFFmpeg::AskResample(), ContrastDialog::ContrastDialog(), EffectAutoDuckDialog::EffectAutoDuckDialog(), ErrorDialog::ErrorDialog(), HistoryWindow::HistoryWindow(), ImportRawDialog::ImportRawDialog(), EffectDialog::Init(), LangChoiceDialog::LangChoiceDialog(), BenchmarkDialog::MakeBenchmarkDialog(), BatchProcessDialog::OnApplyToProject(), SplashDialog::Populate(), WarningsPrefs::PopulateOrExchange(), WahwahDialog::PopulateOrExchange(), TracksPrefs::PopulateOrExchange(), TimeScaleDialog::PopulateOrExchange(), TimerRecordDialog::PopulateOrExchange(), TimeDialog::PopulateOrExchange(), ThemePrefs::PopulateOrExchange(), SpectrumPrefs::PopulateOrExchange(), SoundActivatedRecord::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), RecordingPrefs::PopulateOrExchange(), QualityPrefs::PopulateOrExchange(), ProjectsPrefs::PopulateOrExchange(), PlaybackPrefs::PopulateOrExchange(), PhaserDialog::PopulateOrExchange(), MousePrefs::PopulateOrExchange(), LibraryPrefs::PopulateOrExchange(), KeyConfigPrefs::PopulateOrExchange(), ImportExportPrefs::PopulateOrExchange(), GUIPrefs::PopulateOrExchange(), FFmpegNotFoundDialog::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), EffectsPrefs::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), DevicePrefs::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ChangeTempoDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), BatchProcessDialog::PopulateOrExchange(), BatchPrefs::PopulateOrExchange(), ShowInfoDialog(), and WarningDialog::WarningDialog().
void ShuttleGuiBase::SetNoMatchSelector (int iSelector) [inline]
Referenced by QualityPrefs::PopulateOrExchange().
void ShuttleGuiBase::SetProportions (int Default) [protected]
References miProp, and miPropSetByUser.
Referenced by AddListBox(), AddListControl(), AddListControlReportMode(), AddTextWindow(), AddTree(), AddWindow(), StartInvisiblePanel(), StartNotebook(), StartNotebookPage(), StartPanel(), and StartScroller().
void ShuttleGuiBase::SetSizeHints (int minX, int minY)
Used to modify an already placed Window.
Reimplemented in ShuttleGui.
References eIsCreating, mpLastWind, and mShuttleMode.
void ShuttleGuiBase::SetSizerProportion (int iProp) [inline]
void ShuttleGuiBase::SetStretchyCol (int i)
Used to modify an already placed FlexGridSizer to make a column stretchy.
References eIsCreating, mpSizer, and mShuttleMode.
Referenced by ContrastDialog::ContrastDialog(), TrackPanel::OnSetFont(), SplashDialog::Populate(), SoundActivatedRecord::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), RecordingPrefs::PopulateOrExchange(), QualityPrefs::PopulateOrExchange(), PhaserDialog::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), ExportPCMOptions::PopulateOrExchange(), ExportOGGOptions::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), ExportCLOptions::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ClickRemovalDialog::PopulateOrExchange(), BatchCommandDialog::PopulateOrExchange(), and BassBoostDialog::PopulateOrExchange().
void ShuttleGuiBase::SetStretchyRow (int i)
Used to modify an already placed FlexGridSizer to make a row stretchy.
References eIsCreating, mpSizer, and mShuttleMode.
Referenced by TrackPanel::OnSetFont(), and ExportFFmpegOptions::PopulateOrExchange().
void ShuttleGuiBase::SetStyle (int Style) [inline]
Referenced by BatchProcessDialog::OnApplyToFiles(), WahwahDialog::PopulateOrExchange(), TimeScaleDialog::PopulateOrExchange(), PhaserDialog::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ClickRemovalDialog::PopulateOrExchange(), ChangeTempoDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), EditChainsDialog::PopulateOrExchange(), BatchProcessDialog::PopulateOrExchange(), BatchCommandDialog::PopulateOrExchange(), BassBoostDialog::PopulateOrExchange(), AmplifyDialog::PopulateOrExchange(), ShowHtmlText(), and ShowInfoDialog().
void ShuttleGuiBase::StartHorizontalLay (int PositionFlags = wxALIGN_CENTRE, int iProp = 1)
Starts a Horizontal Layout.
Use wxEXPAND and 0 to expand horizontally but not vertically.
Use wxEXPAND and 1 to expand horizontally and vertically.
Use wxCENTRE and 1 for no expansion.
Parameters:
PositionFlag Typically wxEXPAND or wxCENTRE.
iProp Proportionality for resizing.
References eIsCreating, miSizerProp, mpSubSizer, mShuttleMode, and UpdateSizersCore().
Referenced by ExportMP3::AskResample(), ExportFFmpeg::AskResample(), ContrastDialog::ContrastDialog(), EffectAutoDuckDialog::EffectAutoDuckDialog(), EVT_TREE_KEY_DOWN(), ExportCL::Export(), HistoryWindow::HistoryWindow(), LangChoiceDialog::LangChoiceDialog(), BenchmarkDialog::MakeBenchmarkDialog(), BatchProcessDialog::OnApplyToFiles(), BatchProcessDialog::OnApplyToProject(), TrackPanel::OnRateOther(), AudacityProject::OnResample(), WahwahDialog::PopulateOrExchange(), TruncSilenceDialog::PopulateOrExchange(), TimeScaleDialog::PopulateOrExchange(), ThemePrefs::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), RepeatDialog::PopulateOrExchange(), PhaserDialog::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), LevellerDialog::PopulateOrExchange(), KeyConfigPrefs::PopulateOrExchange(), FindClippingDialog::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), ExportPCMOptions::PopulateOrExchange(), ExportOGGOptions::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportMP2Options::PopulateOrExchange(), ExportFLACOptions::PopulateOrExchange(), ExportFFmpegWMAOptions::PopulateOrExchange(), ExportFFmpegAMRWBOptions::PopulateOrExchange(), ExportFFmpegAMRNBOptions::PopulateOrExchange(), ExportFFmpegAC3Options::PopulateOrExchange(), ExportCLOptions::PopulateOrExchange(), EchoDialog::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ClickRemovalDialog::PopulateOrExchange(), ChangeTempoDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), EditChainsDialog::PopulateOrExchange(), BatchProcessDialog::PopulateOrExchange(), BatchPrefs::PopulateOrExchange(), BassBoostDialog::PopulateOrExchange(), AmplifyDialog::PopulateOrExchange(), ShowHtmlText(), ShowInfoDialog(), and MixerToolBar::ShowInputSourceDialog().
wxPanel * ShuttleGuiBase::StartInvisiblePanel ()
References eIsCreating, miBorder, miId, mpDlg, mpParent, mpSizer, mpWind, mShuttleMode, PushSizer(), SetProportions(), UpdateSizers(), and UseUpId().
void ShuttleGuiBase::StartMultiColumn (int nCols, int PositionFlags = wxALIGN_LEFT)
References eIsCreating, mpSubSizer, mShuttleMode, and UpdateSizersCore().
Referenced by ContrastDialog::ContrastDialog(), EffectAutoDuckDialog::EffectAutoDuckDialog(), HistoryWindow::HistoryWindow(), ImportRawDialog::ImportRawDialog(), BenchmarkDialog::MakeBenchmarkDialog(), TrackPanel::OnSetFont(), SplashDialog::Populate(), WahwahDialog::PopulateOrExchange(), TracksPrefs::PopulateOrExchange(), TimeScaleDialog::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), SpectrumPrefs::PopulateOrExchange(), SoundActivatedRecord::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), RecordingPrefs::PopulateOrExchange(), QualityPrefs::PopulateOrExchange(), PhaserDialog::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), NoiseDialog::PopulateOrExchange(), GUIPrefs::PopulateOrExchange(), FindClippingDialog::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), ExportPCMOptions::PopulateOrExchange(), ExportOGGOptions::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), ExportCLOptions::PopulateOrExchange(), EchoDialog::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), DevicePrefs::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ClickRemovalDialog::PopulateOrExchange(), ChangeTempoDialog::PopulateOrExchange(), ChangeSpeedDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), BatchCommandDialog::PopulateOrExchange(), BassBoostDialog::PopulateOrExchange(), AmplifyDialog::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), and ToneGenDialog::PopulateOrExchangeStandard().
wxNotebook * ShuttleGuiBase::StartNotebook ()
References eIsCreating, miId, mpDlg, mpParent, mpWind, mShuttleMode, SetProportions(), Style(), UpdateSizers(), and UseUpId().
Referenced by AboutDialog::AboutDialog().
void ShuttleGuiBase::StartNotebookPage (const wxString Name, wxNotebookPage * pPage)
References eIsCreating, mpParent, mpSizer, mShuttleMode, PushSizer(), and SetProportions().
wxNotebookPage * ShuttleGuiBase::StartNotebookPage (const wxString Name)
References eIsCreating, mpParent, mpSizer, mShuttleMode, PushSizer(), and SetProportions().
Referenced by AboutDialog::PopulateAudacityPage(), AboutDialog::PopulateInformationPage(), and AboutDialog::PopulateLicensePage().
wxPanel * ShuttleGuiBase::StartPanel (int iStyle = 0)
References eIsCreating, miBorder, miId, mpDlg, mpParent, mpSizer, mpWind, mShuttleMode, PushSizer(), SetProportions(), Style(), UpdateSizers(), and UseUpId().
Referenced by ScreenFrame::PopulateOrExchange(), and ShowHtmlText().
void ShuttleGuiBase::StartRadioButtonGroup (const wxString & SettingName, const wxString & DefaultValue)
String specific version of StartRadioButtonGroup. All 'TieRadioButton()' enclosed must be strings.
References mRadioValue, mRadioValueString, WrappedType::SetTo(), and StartRadioButtonGroup().
void ShuttleGuiBase::StartRadioButtonGroup (const wxString & SettingName, const int iDefaultValue)
Integer specific version of StartRadioButtonGroup. All 'TieRadioButton()' enclosed must be ints.
References mRadioValue, mRadioValueInt, WrappedType::SetTo(), and StartRadioButtonGroup().
void ShuttleGuiBase::StartRadioButtonGroup (const wxString & SettingName)
Call this before any TieRadioButton calls. This is the generic version and requires mRadioValue already initialised. Versions for specific types must do that initialisation.
References DoDataShuttle(), eIsCreating, eWrappedNotSet, WrappedType::eWrappedType, mRadioCount, mRadioValue, mSettingName, and mShuttleMode.
Referenced by ProjectsPrefs::PopulateOrExchange(), ImportExportPrefs::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), and StartRadioButtonGroup().
wxScrolledWindow * ShuttleGuiBase::StartScroller (int iStyle = 0)
This allows subsequent controls and static boxes to be in a scrolled panel. Very handy if you are running out of space on a dialog.
The iStyle parameter is used in some very hacky code that dynamically repopulates a dialog. It also controls the background colour. Look at the code for details.
Parameters:
istyle deprecated parameter, but has been used for hacking.
References eIsCreating, miId, mpDlg, mpParent, mpSizer, mpWind, mShuttleMode, PushSizer(), SetProportions(), Style(), UpdateSizers(), UpdateSizersAtStart(), and UseUpId().
wxStaticBox * ShuttleGuiBase::StartStatic (const wxString & Str, int iProp = 0)
Starts a static box around a number of controls.
Parameters:
Str The text of the title for the box.
iProp The resizing proportion value. Use iProp == 0 for a minimum sized static box. Use iProp == 1 for a box that grows if there is space to spare.
References eIsCreating, mBoxName, miId, miSizerProp, mpParent, mpSubSizer, mShuttleMode, UpdateSizers(), and UseUpId().
Referenced by ExportMP3::AskResample(), ExportFFmpeg::AskResample(), ContrastDialog::ContrastDialog(), HistoryWindow::HistoryWindow(), BatchProcessDialog::OnApplyToFiles(), BatchProcessDialog::OnApplyToProject(), KeyConfigPrefs::Populate(), WarningsPrefs::PopulateOrExchange(), TracksPrefs::PopulateOrExchange(), TimerRecordDialog::PopulateOrExchange(), TimeDialog::PopulateOrExchange(), ThemePrefs::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), SpectrumPrefs::PopulateOrExchange(), ScreenFrame::PopulateOrExchange(), RecordingPrefs::PopulateOrExchange(), QualityPrefs::PopulateOrExchange(), ProjectsPrefs::PopulateOrExchange(), PlaybackPrefs::PopulateOrExchange(), NoiseRemovalDialog::PopulateOrExchange(), MousePrefs::PopulateOrExchange(), LibraryPrefs::PopulateOrExchange(), LevellerDialog::PopulateOrExchange(), KeyConfigPrefs::PopulateOrExchange(), ImportExportPrefs::PopulateOrExchange(), GUIPrefs::PopulateOrExchange(), ExportPCMOptions::PopulateOrExchange(), ExportOGGOptions::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportMP2Options::PopulateOrExchange(), ExportFLACOptions::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), ExportFFmpegWMAOptions::PopulateOrExchange(), ExportFFmpegAMRWBOptions::PopulateOrExchange(), ExportFFmpegAMRNBOptions::PopulateOrExchange(), ExportFFmpegAACOptions::PopulateOrExchange(), ExportFFmpegAC3Options::PopulateOrExchange(), ExportCLOptions::PopulateOrExchange(), EffectsPrefs::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), DevicePrefs::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), CompressorDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), EditChainsDialog::PopulateOrExchange(), BatchProcessDialog::PopulateOrExchange(), BatchPrefs::PopulateOrExchange(), and BatchCommandDialog::PopulateOrExchange().
void ShuttleGuiBase::StartThreeColumn () [inline]
Referenced by TruncSilenceDialog::PopulateOrExchange(), RecordingPrefs::PopulateOrExchange(), ProjectsPrefs::PopulateOrExchange(), PlaybackPrefs::PopulateOrExchange(), and KeyConfigPrefs::PopulateOrExchange().
void ShuttleGuiBase::StartTwoColumn () [inline]
Referenced by ImportRawDialog::ImportRawDialog(), SpectrumPrefs::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), LibraryPrefs::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportMP2Options::PopulateOrExchange(), ExportFLACOptions::PopulateOrExchange(), ExportFFmpegWMAOptions::PopulateOrExchange(), ExportFFmpegAMRWBOptions::PopulateOrExchange(), ExportFFmpegAMRNBOptions::PopulateOrExchange(), ExportFFmpegAACOptions::PopulateOrExchange(), ExportFFmpegAC3Options::PopulateOrExchange(), and DirectoriesPrefs::PopulateOrExchange().
void ShuttleGuiBase::StartVerticalLay (int iProp = 1)
References eIsCreating, miSizerProp, mpSubSizer, mShuttleMode, and UpdateSizers().
Referenced by ShuttleGui::AddStandardButtons(), ExportMP3::AskResample(), ExportFFmpeg::AskResample(), EffectAutoDuckDialog::EffectAutoDuckDialog(), ErrorDialog::ErrorDialog(), EVT_TREE_KEY_DOWN(), HistoryWindow::HistoryWindow(), ImportRawDialog::ImportRawDialog(), EffectDialog::Init(), LangChoiceDialog::LangChoiceDialog(), BenchmarkDialog::MakeBenchmarkDialog(), BatchProcessDialog::OnApplyToFiles(), TagsEditor::OnEdit(), TrackPanel::OnRateOther(), AudacityProject::OnResample(), TrackPanel::OnSetFont(), SplashDialog::Populate(), KeyConfigPrefs::Populate(), AboutDialog::PopulateAudacityPage(), AboutDialog::PopulateInformationPage(), AboutDialog::PopulateLicensePage(), TimerRecordDialog::PopulateOrExchange(), TimeDialog::PopulateOrExchange(), TagsEditor::PopulateOrExchange(), SoundActivatedRecord::PopulateOrExchange(), NormalizeDialog::PopulateOrExchange(), FFmpegNotFoundDialog::PopulateOrExchange(), FindFFmpegDialog::PopulateOrExchange(), FindDialog::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), DependencyDialog::PopulateOrExchange(), ChangePitchDialog::PopulateOrExchange(), BatchProcessDialog::PopulateOrExchange(), BatchCommandDialog::PopulateOrExchange(), ShowInfoDialog(), MixerToolBar::ShowInputSourceDialog(), SliderDialog::SliderDialog(), and WarningDialog::WarningDialog().
long ShuttleGuiBase::Style (long Style) [protected]
References miStyle.
Referenced by AddBitmapButton(), AddButton(), AddCheckBox(), AddCheckBoxOnRight(), AddChoice(), AddCombo(), AddConstTextBox(), AddFixedText(), AddIcon(), AddListControl(), AddListControlReportMode(), AddPrompt(), AddRadioButton(), AddRadioButtonToGroup(), AddSlider(), AddSpinCtrl(), AddTextBox(), AddTextWindow(), AddTitle(), AddTree(), AddUnits(), AddVariableText(), StartNotebook(), StartPanel(), and StartScroller().
wxCheckBox * ShuttleGuiBase::TieCheckBox (const wxString & Prompt, const wxString & SettingName, const bool bDefault)
Variant of the standard TieCheckBox which does the two step exchange between gui and stack variable and stack variable and shuttle.
References DoDataShuttle(), DoStep(), and TieCheckBox().
wxCheckBox * ShuttleGuiBase::TieCheckBox (const wxString & Prompt, bool & Var)
References TieCheckBox().
wxCheckBox* ShuttleGuiBase::TieCheckBox (const wxString & Prompt, const wxString & Selected)
wxCheckBox * ShuttleGuiBase::TieCheckBox (const wxString & Prompt, WrappedType & WrappedRef)
References AddCheckBox(), DoDataShuttle(), eIsCreating, eIsGettingFromDialog, eIsGettingViaShuttle, eIsSavingViaShuttle, eIsSettingToDialog, miId, mpDlg, mShuttleMode, WrappedType::ReadAsBool(), WrappedType::ReadAsString(), UseUpId(), and WrappedType::WriteToAsBool().
Referenced by WarningsPrefs::PopulateOrExchange(), TracksPrefs::PopulateOrExchange(), ThemePrefs::PopulateOrExchange(), SpectrumPrefs::PopulateOrExchange(), RecordingPrefs::PopulateOrExchange(), ProjectsPrefs::PopulateOrExchange(), ImportExportPrefs::PopulateOrExchange(), GUIPrefs::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), ExportCLOptions::PopulateOrExchange(), EffectsPrefs::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), BatchPrefs::PopulateOrExchange(), TieCheckBox(), and TieCheckBoxOnRight().
wxCheckBox * ShuttleGuiBase::TieCheckBoxOnRight (const wxString & Prompt, const wxString & SettingName, const bool bDefault)
Variant of the standard TieCheckBox which does the two step exchange between gui and stack variable and stack variable and shuttle.
References DoDataShuttle(), DoStep(), and TieCheckBoxOnRight().
wxCheckBox * ShuttleGuiBase::TieCheckBoxOnRight (const wxString & Prompt, bool & Var)
References AddCheckBoxOnRight(), eIsCreating, mShuttleMode, WrappedType::ReadAsString(), and TieCheckBox().
wxCheckBox * ShuttleGuiBase::TieCheckBoxOnRight (const wxString & Prompt, WrappedType & WrappedRef)
References AddCheckBoxOnRight(), DoDataShuttle(), eIsCreating, eIsGettingFromDialog, eIsGettingViaShuttle, eIsSavingViaShuttle, eIsSettingToDialog, miId, mpDlg, mShuttleMode, WrappedType::ReadAsBool(), WrappedType::ReadAsString(), UseUpId(), and WrappedType::WriteToAsBool().
Referenced by TieCheckBoxOnRight().
wxChoice * ShuttleGuiBase::TieChoice (const wxString & Prompt, const wxString & SettingName, const int Default, const wxArrayString & Choices, const wxArrayInt & TranslatedChoices)
Variant of the standard TieChoice which does the two step exchange between gui and stack variable and stack variable and shuttle. Difference to previous one is that the Translated choices and default are integers, not Strings.
Parameters:
Prompt The prompt shown beside the control.
SettingName The setting name as stored in gPrefs
Default The default value for this control (translated)
Choices An array of choices that appear on screen.
TranslatedChoices The correcponding values (as an integer array)
References DoDataShuttle(), DoStep(), TieChoice(), TranslateFromIndex(), and TranslateToIndex().
wxChoice * ShuttleGuiBase::TieChoice (const wxString & Prompt, const wxString & SettingName, const wxString & Default, const wxArrayString & Choices, const wxArrayString & TranslatedChoices)
Variant of the standard TieChoice which does the two step exchange between gui and stack variable and stack variable and shuttle.
Parameters:
Prompt The prompt shown beside the control.
SettingName The setting name as stored in gPrefs
Default The default value for this control (translated)
Choices An array of choices that appear on screen.
TranslatedChoices The corresponding values (as a string array)
References DoDataShuttle(), DoStep(), TieChoice(), TranslateFromIndex(), and TranslateToIndex().
wxChoice * ShuttleGuiBase::TieChoice (const wxString & Prompt, int & Selected, const wxArrayString * pChoices)
References TieChoice().
wxChoice * ShuttleGuiBase::TieChoice (const wxString & Prompt, wxString & Selected, const wxArrayString * pChoices)
References TieChoice().
wxChoice * ShuttleGuiBase::TieChoice (const wxString & Prompt, WrappedType & WrappedRef, const wxArrayString * pChoices)
References AddChoice(), DoDataShuttle(), eIsCreating, eIsGettingFromDialog, eIsGettingViaShuttle, eIsSavingViaShuttle, eIsSettingToDialog, WrappedType::IsString(), miId, mpDlg, mShuttleMode, WrappedType::ReadAsInt(), WrappedType::ReadAsString(), UseUpId(), WrappedType::WriteToAsInt(), and WrappedType::WriteToAsString().
Referenced by TruncSilenceDialog::PopulateOrExchange(), TracksPrefs::PopulateOrExchange(), SpectrumPrefs::PopulateOrExchange(), QualityPrefs::PopulateOrExchange(), NoiseDialog::PopulateOrExchange(), LevellerDialog::PopulateOrExchange(), GUIPrefs::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), ExportMP2Options::PopulateOrExchange(), ExportFLACOptions::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), ExportFFmpegWMAOptions::PopulateOrExchange(), ExportFFmpegAMRWBOptions::PopulateOrExchange(), ExportFFmpegAMRNBOptions::PopulateOrExchange(), ExportFFmpegAC3Options::PopulateOrExchange(), DevicePrefs::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), ToneGenDialog::PopulateOrExchangeStandard(), and TieChoice().
wxRadioButton * ShuttleGuiBase::TieRadioButton (const wxString & Prompt, const wxString & Value)
This function must be within a StartRadioButtonGroup - EndRadioButtonGroup pair.
References TieRadioButton().
wxRadioButton * ShuttleGuiBase::TieRadioButton (const wxString & Prompt, const int iValue)
This function must be within a StartRadioButtonGroup - EndRadioButtonGroup pair.
References TieRadioButton().
wxRadioButton * ShuttleGuiBase::TieRadioButton (const wxString & Prompt, WrappedType & WrappedRef)
References eIsCreating, eIsGettingFromDialog, miId, mpDlg, mpParent, mpWind, mRadioCount, mRadioValue, mShuttleMode, UpdateSizers(), UseUpId(), WrappedType::ValuesMatch(), and WrappedType::WriteToAsWrappedType().
Referenced by ProjectsPrefs::PopulateOrExchange(), ImportExportPrefs::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), ExportMP3Options::PopulateOrExchange(), and TieRadioButton().
wxSlider * ShuttleGuiBase::TieSlider (const wxString & Prompt, const wxString & SettingName, const int iDefault, const int max, const int min = 0)
Variant of the standard TieSlider which does the two step exchange between gui and stack variable and stack variable and shuttle.
References DoDataShuttle(), DoStep(), and TieSlider().
wxSlider * ShuttleGuiBase::TieSlider (const wxString & Prompt, float & pos, const float fMin, const float fMax)
References TieSlider().
wxSlider * ShuttleGuiBase::TieSlider (const wxString & Prompt, int & pos, const int max, const int min = 0)
References TieSlider().
wxSlider * ShuttleGuiBase::TieSlider (const wxString & Prompt, WrappedType & WrappedRef, const int max, const int min = 0)
References AddSlider(), DoDataShuttle(), eIsCreating, eIsGettingFromDialog, eIsGettingViaShuttle, eIsSavingViaShuttle, eIsSettingToDialog, miId, mpDlg, mShuttleMode, WrappedType::ReadAsInt(), UseUpId(), and WrappedType::WriteToAsInt().
Referenced by SoundActivatedRecord::PopulateOrExchange(), RecordingPrefs::PopulateOrExchange(), ExportOGGOptions::PopulateOrExchange(), ExportFFmpegAACOptions::PopulateOrExchange(), TieSlider(), and TieVSlider().
wxSpinCtrl * ShuttleGuiBase::TieSpinCtrl (const wxString & Prompt, const wxString & SettingName, const int Value, const int max, const int min)
Variant of the standard TieSpinCtrl which does the two step exchange between gui and stack variable and stack variable and shuttle.
References DoDataShuttle(), DoStep(), and TieSpinCtrl().
wxSpinCtrl * ShuttleGuiBase::TieSpinCtrl (const wxString & Prompt, int & Value, const int max, const int min = 0)
References TieSpinCtrl().
wxSpinCtrl * ShuttleGuiBase::TieSpinCtrl (const wxString & Prompt, WrappedType & WrappedRef, const int max, const int min = 0)
References AddSpinCtrl(), DoDataShuttle(), eIsCreating, eIsGettingFromDialog, eIsGettingViaShuttle, eIsSavingViaShuttle, eIsSettingToDialog, miId, mpDlg, mShuttleMode, WrappedType::ReadAsInt(), UseUpId(), and WrappedType::WriteToAsInt().
Referenced by ExportFFmpegOptions::PopulateOrExchange(), and TieSpinCtrl().
wxTextCtrl * ShuttleGuiBase::TieTextBox (const wxString & Prompt, const wxString & SettingName, const double & Default, const int nChars)
Variant of the standard TieTextBox which does the two step exchange between gui and stack variable and stack variable and shuttle. This one does it for double values...
References DoDataShuttle(), DoStep(), and TieTextBox().
wxTextCtrl * ShuttleGuiBase::TieTextBox (const wxString & Prompt, const wxString & SettingName, const wxString & Default, const int nChars)
Variant of the standard TieTextBox which does the two step exchange between gui and stack variable and stack variable and shuttle.
References DoDataShuttle(), DoStep(), and TieTextBox().
wxTextCtrl * ShuttleGuiBase::TieTextBox (const wxString & Prompt, double & Value, const int nChars = 0)
References TieTextBox().
wxTextCtrl * ShuttleGuiBase::TieTextBox (const wxString & Prompt, int & Selected, const int nChars = 0)
References TieTextBox().
wxTextCtrl * ShuttleGuiBase::TieTextBox (const wxString & Caption, wxString & Value, const int nChars = 0)
References TieTextBox().
wxTextCtrl * ShuttleGuiBase::TieTextBox (const wxString & Prompt, WrappedType & WrappedRef, const int nChars)
References AddTextBox(), DoDataShuttle(), eIsCreating, eIsGettingFromDialog, eIsGettingViaShuttle, eIsSavingViaShuttle, eIsSettingToDialog, miId, mpDlg, mShuttleMode, WrappedType::ReadAsString(), UseUpId(), and WrappedType::WriteToAsString().
Referenced by TruncSilenceDialog::PopulateOrExchange(), SpectrumPrefs::PopulateOrExchange(), RecordingPrefs::PopulateOrExchange(), QualityPrefs::PopulateOrExchange(), ProjectsPrefs::PopulateOrExchange(), PlaybackPrefs::PopulateOrExchange(), NoiseDialog::PopulateOrExchange(), FindClippingDialog::PopulateOrExchange(), ExportMultiple::PopulateOrExchange(), ExportFFmpegOptions::PopulateOrExchange(), ExportCLOptions::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), DirectoriesPrefs::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), ToneGenDialog::PopulateOrExchangeStandard(), and TieTextBox().
wxSlider * ShuttleGuiBase::TieVSlider (const wxString & Prompt, float & pos, const float fMin, const float fMax)
References TieSlider().
int ShuttleGuiBase::TranslateFromIndex (const int nIn, const wxArrayInt & Choices)
Index-to-int (choices can be items like e.g 0x400120).
References miNoMatchSelector.
wxString ShuttleGuiBase::TranslateFromIndex (const int nIn, const wxArrayString & Choices)
Index-to-String.
References miNoMatchSelector.
Referenced by TieChoice().
int ShuttleGuiBase::TranslateToIndex (const int Value, const wxArrayInt & Choices)
Int-to-Index (choices can be items like e.g 0x400120).
References miNoMatchSelector.
int ShuttleGuiBase::TranslateToIndex (const wxString & Value, const wxArrayString & Choices)
String-to-Index.
References miNoMatchSelector.
Referenced by TieChoice().
void ShuttleGuiBase::UpdateSizers () [protected]
References UpdateSizersCore().
Referenced by ShuttleGui::AddAdornedRuler(), ShuttleGui::AddAttachableScrollBar(), AddCheckBox(), AddCheckBoxOnRight(), AddChoice(), AddCombo(), AddConstTextBox(), AddFixedText(), ShuttleGui::AddGuiWaveTrack(), AddListBox(), AddListControl(), AddListControlReportMode(), AddRadioButton(), AddRadioButtonToGroup(), ShuttleGui::AddRulerVertical(), AddSlider(), AddSpinCtrl(), ShuttleGui::AddStandardButtons(), AddTextBox(), AddTextWindow(), AddTitle(), AddTree(), AddVariableText(), StartInvisiblePanel(), StartNotebook(), StartPanel(), StartScroller(), StartStatic(), StartVerticalLay(), and TieRadioButton().
void ShuttleGuiBase::UpdateSizersAtStart () [protected]
References UpdateSizersCore().
Referenced by StartScroller().
void ShuttleGuiBase::UpdateSizersC () [protected]
References UpdateSizersCore().
Referenced by AddFixedText(), AddIcon(), and AddVariableText().
void ShuttleGuiBase::UpdateSizersCore (bool bPrepend, int Flags) [protected]
References miBorder, miProp, miSizerProp, mpLastWind, mpParent, mpSizer, mpSubSizer, mpWind, and PushSizer().
Referenced by AddBitmapButton(), AddButton(), AddPrompt(), AddUnits(), AddVariableText(), AddWindow(), StartHorizontalLay(), StartMultiColumn(), UpdateSizers(), UpdateSizersAtStart(), and UpdateSizersC().
void ShuttleGuiBase::UseUpId ()
The Ids increment as we add new controls. However, the user can force the id manually, for example if they need a specific Id for a button, and then let it resume normal numbering later. UseUpId() sets miId to the next Id, either using the user specicfied one, or resuming the sequence.
References miId, miIdNext, and miIdSetByUser.
Referenced by ShuttleGui::AddAdornedRuler(), ShuttleGui::AddAttachableScrollBar(), AddBitmapButton(), AddButton(), AddCheckBox(), AddCheckBoxOnRight(), AddChoice(), AddCombo(), AddConstTextBox(), AddFixedText(), ShuttleGui::AddGuiWaveTrack(), AddIcon(), AddListBox(), AddListControl(), AddListControlReportMode(), AddRadioButton(), AddRadioButtonToGroup(), ShuttleGui::AddRulerVertical(), AddSlider(), AddSpinCtrl(), AddTextBox(), AddTextWindow(), AddTree(), AddVariableText(), StartInvisiblePanel(), StartNotebook(), StartPanel(), StartScroller(), StartStatic(), TieCheckBox(), TieCheckBoxOnRight(), TieChoice(), TieRadioButton(), TieSlider(), TieSpinCtrl(), and TieTextBox().
Member Data Documentation
wxString ShuttleGuiBase::mBoxName [protected]
Referenced by StartStatic().
int ShuttleGuiBase::miBorder [protected]
Referenced by Init(), StartInvisiblePanel(), StartPanel(), and UpdateSizersCore().
int ShuttleGuiBase::miId [protected]
Referenced by ShuttleGui::AddAdornedRuler(), ShuttleGui::AddAttachableScrollBar(), AddBitmapButton(), AddButton(), AddCheckBox(), AddCheckBoxOnRight(), AddChoice(), AddCombo(), AddConstTextBox(), AddFixedText(), ShuttleGui::AddGuiWaveTrack(), AddIcon(), AddListBox(), AddListControl(), AddListControlReportMode(), AddRadioButton(), AddRadioButtonToGroup(), ShuttleGui::AddRulerVertical(), AddSlider(), AddSpinCtrl(), AddTextBox(), AddTextWindow(), AddTree(), AddVariableText(), Init(), StartInvisiblePanel(), StartNotebook(), StartPanel(), StartScroller(), StartStatic(), TieCheckBox(), TieCheckBoxOnRight(), TieChoice(), TieRadioButton(), TieSlider(), TieSpinCtrl(), TieTextBox(), and UseUpId().
int ShuttleGuiBase::miIdNext [protected]
Referenced by Init(), and UseUpId().
int ShuttleGuiBase::miIdSetByUser [protected]
Referenced by ShuttleGui::Id(), Init(), and UseUpId().
int ShuttleGuiBase::miNoMatchSelector [protected]
Controls source/destination of shuttled data. You can leave this NULL if you are shuttling to variables
Referenced by Init(), TranslateFromIndex(), and TranslateToIndex().
int ShuttleGuiBase::miProp [protected]
Referenced by ShuttleGui::AddAdornedRuler(), ShuttleGui::AddAttachableScrollBar(), AddBitmapButton(), AddButton(), AddCheckBox(), AddCheckBoxOnRight(), AddChoice(), AddCombo(), AddConstTextBox(), AddFixedText(), ShuttleGui::AddGuiWaveTrack(), AddPrompt(), ShuttleGui::AddRulerVertical(), AddSlider(), AddSpinCtrl(), AddTextBox(), AddUnits(), AddVariableText(), Init(), SetProportions(), and UpdateSizersCore().
int ShuttleGuiBase::miPropSetByUser [protected]
Referenced by Init(), Prop(), and SetProportions().
int ShuttleGuiBase::miSizerProp [protected]
Unwrapped integer value.
Referenced by ShuttleGui::AddStandardButtons(), Init(), StartHorizontalLay(), StartStatic(), StartVerticalLay(), and UpdateSizersCore().
long ShuttleGuiBase::miStyle [protected]
Referenced by Init(), and Style().
wxWindow* ShuttleGuiBase::mpDlg [protected]
Referenced by AddBitmapButton(), AddButton(), AddCheckBox(), AddCheckBoxOnRight(), AddChoice(), AddCombo(), AddListBox(), AddListControl(), AddListControlReportMode(), AddRadioButton(), AddRadioButtonToGroup(), AddSlider(), AddSpinCtrl(), AddTextBox(), AddTextWindow(), AddTree(), AddVariableText(), ShuttleGuiBase(), StartInvisiblePanel(), StartNotebook(), StartPanel(), StartScroller(), TieCheckBox(), TieCheckBoxOnRight(), TieChoice(), TieRadioButton(), TieSlider(), TieSpinCtrl(), and TieTextBox().
wxWindow* ShuttleGuiBase::mpLastWind [protected]
Referenced by EnableCtrl(), ShuttleGui::SetSizeHints(), SetSizeHints(), and UpdateSizersCore().
wxMenu* ShuttleGuiBase::mpMenu [protected]
Referenced by AddMenu().
wxMenuBar* ShuttleGuiBase::mpMenuBar [protected]
Referenced by AddMenu(), and AddMenuBar().
wxWindow* ShuttleGuiBase::mpParent [protected]
Referenced by ShuttleGui::AddAdornedRuler(), ShuttleGui::AddAttachableScrollBar(), AddBitmapButton(), AddButton(), AddCheckBox(), AddCheckBoxOnRight(), AddChoice(), AddCombo(), AddConstTextBox(), AddFixedText(), ShuttleGui::AddGuiWaveTrack(), AddIcon(), AddListBox(), AddListControl(), AddListControlReportMode(), AddMenuBar(), AddPrompt(), AddRadioButton(), AddRadioButtonToGroup(), ShuttleGui::AddRulerVertical(), AddSlider(), AddSpinCtrl(), ShuttleGui::AddStandardButtons(), AddTextBox(), AddTextWindow(), AddTitle(), AddTree(), AddUnits(), AddVariableText(), EndNotebook(), EndNotebookPage(), EndPanel(), EndScroller(), Init(), ShuttleGuiBase(), StartInvisiblePanel(), StartNotebook(), StartNotebookPage(), StartPanel(), StartScroller(), StartStatic(), TieRadioButton(), and UpdateSizersCore().
Shuttle* ShuttleGuiBase::mpShuttle [protected]
Referenced by DoDataShuttle(), Init(), ShuttleGui::ShuttleGui(), and ShuttleGui::~ShuttleGui().
wxSizer* ShuttleGuiBase::mpSizer [protected]
Referenced by ShuttleGui::AddSpace(), EndScroller(), Init(), PopSizer(), PushSizer(), SetStretchyCol(), SetStretchyRow(), StartInvisiblePanel(), StartNotebookPage(), StartPanel(), StartScroller(), and UpdateSizersCore().
wxSizer* ShuttleGuiBase::mpSubSizer [protected]
Referenced by ShuttleGui::AddStandardButtons(), Init(), StartHorizontalLay(), StartMultiColumn(), StartStatic(), StartVerticalLay(), and UpdateSizersCore().
wxWindow* ShuttleGuiBase::mpWind [protected]
Referenced by ShuttleGui::AddAdornedRuler(), ShuttleGui::AddAttachableScrollBar(), AddBitmapButton(), AddButton(), AddCheckBox(), AddCheckBoxOnRight(), AddChoice(), AddCombo(), AddConstTextBox(), AddFixedText(), ShuttleGui::AddGuiWaveTrack(), AddIcon(), AddListBox(), AddListControl(), AddListControlReportMode(), AddPrompt(), AddRadioButton(), AddRadioButtonToGroup(), ShuttleGui::AddRulerVertical(), AddSlider(), AddSpinCtrl(), AddTextBox(), AddTextWindow(), AddTitle(), AddTree(), AddUnits(), AddVariableText(), AddWindow(), Init(), StartInvisiblePanel(), StartNotebook(), StartPanel(), StartScroller(), TieRadioButton(), and UpdateSizersCore().
int ShuttleGuiBase::mRadioCount [protected]
The setting controlled by a group.
Referenced by EndRadioButtonGroup(), Init(), StartRadioButtonGroup(), and TieRadioButton().
WrappedType ShuttleGuiBase::mRadioValue [protected]
The index of this radio item. -1 for none.
Referenced by EndRadioButtonGroup(), StartRadioButtonGroup(), and TieRadioButton().
int ShuttleGuiBase::mRadioValueInt [protected]
Unwrapped string value.
Referenced by StartRadioButtonGroup().
wxString ShuttleGuiBase::mRadioValueString [protected]
The wrapped value associated with the active radio button.
Referenced by StartRadioButtonGroup().
wxString ShuttleGuiBase::mSettingName [protected]
Referenced by EndRadioButtonGroup(), Init(), and StartRadioButtonGroup().
teShuttleMode ShuttleGuiBase::mShuttleMode [protected]
Used in choices to determine which item to use on no match.
Referenced by ShuttleGui::AddAdornedRuler(), ShuttleGui::AddAttachableScrollBar(), AddBitmapButton(), AddButton(), AddCheckBox(), AddCheckBoxOnRight(), AddChoice(), AddCombo(), AddConstTextBox(), AddFixedText(), ShuttleGui::AddGuiWaveTrack(), AddIcon(), AddListBox(), AddListControl(), AddListControlReportMode(), AddPrompt(), AddRadioButton(), AddRadioButtonToGroup(), ShuttleGui::AddRulerVertical(), AddSlider(), ShuttleGui::AddSpace(), AddSpinCtrl(), ShuttleGui::AddStandardButtons(), AddTextBox(), AddTextWindow(), AddTitle(), AddTree(), AddUnits(), AddVariableText(), AddWindow(), DoStep(), EnableCtrl(), EndHorizontalLay(), EndMultiColumn(), EndNotebookPage(), EndPanel(), EndRadioButtonGroup(), EndScroller(), EndStatic(), EndVerticalLay(), Init(), ShuttleGui::SetSizeHints(), SetSizeHints(), SetStretchyCol(), SetStretchyRow(), ShuttleGui::ShuttleGui(), ShuttleGuiBase(), StartHorizontalLay(), StartInvisiblePanel(), StartMultiColumn(), StartNotebook(), StartNotebookPage(), StartPanel(), StartRadioButtonGroup(), StartScroller(), StartStatic(), StartVerticalLay(), TieCheckBox(), TieCheckBoxOnRight(), TieChoice(), TieRadioButton(), TieSlider(), TieSpinCtrl(), and TieTextBox().
int ShuttleGuiBase::mSizerDepth [protected]
Referenced by Init(), PopSizer(), and PushSizer().
wxSizer* ShuttleGuiBase::pSizerStack[nMaxNestedSizers] [protected]
Referenced by PopSizer(), and PushSizer().
The documentation for this class was generated from the following files:
ShuttleGui.h
ShuttleGui.cpp