Audacity: LevellerDialog Class Reference
LevellerDialog Class Reference
Dialog for EffectLeveller.
#include <Leveller.h>
Public Member Functions
LevellerDialog (EffectLeveller *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
Public Attributes
int mLevellerDbChoiceIndex
int mLevellerNumPasses
Private Member Functions
void OnPreview (wxCommandEvent &event)
Private Attributes
EffectLeveller * mEffect
wxChoice * mLevellerDbSilenceThresholdChoice
wxChoice * mLevellerNumPassesChoice
Detailed Description
Dialog for EffectLeveller.
Constructor & Destructor Documentation
LevellerDialog::LevellerDialog (EffectLeveller * effect, wxWindow * parent)
Member Function Documentation
void LevellerDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References mEffect, mLevellerDbChoiceIndex, EffectLeveller::mLevellerDbChoiceIndex, mLevellerNumPasses, EffectLeveller::mLevellerNumPasses, Effect::Preview(), and EffectDialog::TransferDataFromWindow().
void LevellerDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddTitle(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), Enums::GetDbChoices(), mLevellerDbChoiceIndex, mLevellerNumPasses, Enums::NumDbChoices, ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::TieChoice().
Member Data Documentation
EffectLeveller* LevellerDialog::mEffect [private]
Referenced by OnPreview().
int LevellerDialog::mLevellerDbChoiceIndex
Referenced by OnPreview(), PopulateOrExchange(), and EffectLeveller::PromptUser().
wxChoice* LevellerDialog::mLevellerDbSilenceThresholdChoice [private]
int LevellerDialog::mLevellerNumPasses
Referenced by OnPreview(), PopulateOrExchange(), and EffectLeveller::PromptUser().
wxChoice* LevellerDialog::mLevellerNumPassesChoice [private]
The documentation for this class was generated from the following files:
Leveller.h
Leveller.cpp