Audacity: RecordingRecoveryHandler Class Reference
RecordingRecoveryHandler Class Reference
#include <AutoRecovery.h>
Public Member Functions
RecordingRecoveryHandler (AudacityProject *proj)
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
Private Attributes
AudacityProject * mProject
int mChannel
int mNumChannels
Constructor & Destructor Documentation
RecordingRecoveryHandler::RecordingRecoveryHandler (AudacityProject * proj)
Recording recovery handler
References mChannel, mNumChannels, and mProject.
Member Function Documentation
XMLTagHandler * RecordingRecoveryHandler::HandleXMLChild (const wxChar * tag) [virtual]
Implements XMLTagHandler.
bool RecordingRecoveryHandler::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements XMLTagHandler.
References Sequence::AppendBlockFile(), AudacityProject::GetDirManager(), WaveTrack::GetLastOrCreateClip(), Sequence::GetSampleFormat(), WaveClip::GetSequence(), AudacityProject::GetTracks(), TrackList::GetWaveTrackArray(), DirManager::HandleXMLTag(), XMLValueChecker::IsGoodInt(), XMLValueChecker::IsValidChannel(), mChannel, mNumChannels, mProject, DirManager::SetLoadingFormat(), and DirManager::SetLoadingTarget().
virtual void RecordingRecoveryHandler::WriteXML (XMLWriter & xmlFile) [inline, virtual]
Member Data Documentation
int RecordingRecoveryHandler::mChannel [private]
Referenced by HandleXMLTag(), and RecordingRecoveryHandler().
int RecordingRecoveryHandler::mNumChannels [private]
Referenced by HandleXMLTag(), and RecordingRecoveryHandler().
AudacityProject* RecordingRecoveryHandler::mProject [private]
Referenced by HandleXMLTag(), and RecordingRecoveryHandler().
The documentation for this class was generated from the following files:
AutoRecovery.h
AutoRecovery.cpp