Audacity: TrackPanelAx Class Reference
TrackPanelAx Class Reference
Helper to TrackPanel to give accessibility.
#include <TrackPanelAx.h>
Public Member Functions
TrackPanelAx (wxWindow *window)
virtual ~TrackPanelAx ()
Track * GetFocus ()
void SetFocus (Track *track)
bool IsFocused (Track *track)
void Updated ()
Private Member Functions
int TrackNum (Track *track)
Track * FindTrack (int num)
Private Attributes
TrackPanel * mTrackPanel
Track * mFocusedTrack
Detailed Description
Helper to TrackPanel to give accessibility.
Constructor & Destructor Documentation
TrackPanelAx::TrackPanelAx (wxWindow * window)
TrackPanelAx::~TrackPanelAx () [virtual]
Member Function Documentation
Track * TrackPanelAx::FindTrack (int num) [private]
References TrackListIterator::First(), mTrackPanel, TrackPanel::mTracks, and TrackListIterator::Next().
Track * TrackPanelAx::GetFocus ()
References mFocusedTrack, SetFocus(), and TrackNum().
Referenced by TrackPanel::GetFocusedTrack(), and Updated().
bool TrackPanelAx::IsFocused (Track * track)
References Track::GetLink(), mFocusedTrack, and SetFocus().
Referenced by TrackPanel::DoDrawCursor(), and TrackPanel::DrawEverythingElse().
void TrackPanelAx::SetFocus (Track * track)
References TrackListIterator::First(), Track::GetSelected(), mFocusedTrack, mTrackPanel, TrackPanel::mTracks, and TrackNum().
Referenced by GetFocus(), IsFocused(), TrackPanel::SetFocusedTrack(), and Updated().
int TrackPanelAx::TrackNum (Track * track) [private]
References TrackListIterator::First(), mTrackPanel, TrackPanel::mTracks, and TrackListIterator::Next().
Referenced by GetFocus(), SetFocus(), and Updated().
void TrackPanelAx::Updated ()
References GetFocus(), mTrackPanel, SetFocus(), and TrackNum().
Referenced by TrackPanel::OnTrackMute(), and TrackPanel::OnTrackSolo().
Member Data Documentation
Track* TrackPanelAx::mFocusedTrack [private]
Referenced by GetFocus(), IsFocused(), and SetFocus().
TrackPanel* TrackPanelAx::mTrackPanel [private]
Referenced by FindTrack(), SetFocus(), TrackNum(), and Updated().
The documentation for this class was generated from the following files:
TrackPanelAx.h
TrackPanelAx.cpp