Audacity: FindDialog Class Reference
FindDialog Class Reference
Public Member Functions
FindDialog (wxWindow *parent, wxString path, wxString name, wxString type)
void PopulateOrExchange (ShuttleGui &S)
void OnBrowse (wxCommandEvent &event)
void OnDownload (wxCommandEvent &event)
wxString GetLibPath ()
Private Attributes
wxFileName mLibPath
wxString mPath
wxString mName
wxString mType
wxTextCtrl * mPathText
Constructor & Destructor Documentation
FindDialog::FindDialog (wxWindow * parent, wxString path, wxString name, wxString type) [inline]
References eIsCreating, mLibPath, mName, mPath, mType, and PopulateOrExchange().
Member Function Documentation
wxString FindDialog::GetLibPath () [inline]
References mLibPath.
Referenced by MP3Exporter::FindLibrary().
void FindDialog::OnBrowse (wxCommandEvent & event) [inline]
References mLibPath, mName, mPathText, and mType.
void FindDialog::OnDownload (wxCommandEvent & event) [inline]
References OpenInDefaultBrowser().
void FindDialog::PopulateOrExchange (ShuttleGui & S) [inline]
References ShuttleGuiBase::AddButton(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddVariableText(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndVerticalLay(), ShuttleGui::Id(), ID_BROWSE, ID_DLOAD, mLibPath, mName, mPathText, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), and ShuttleGuiBase::StartVerticalLay().
Referenced by FindDialog().
Member Data Documentation
wxFileName FindDialog::mLibPath [private]
Referenced by FindDialog(), GetLibPath(), OnBrowse(), and PopulateOrExchange().
wxString FindDialog::mName [private]
Referenced by FindDialog(), OnBrowse(), and PopulateOrExchange().
wxString FindDialog::mPath [private]
Referenced by FindDialog().
wxTextCtrl* FindDialog::mPathText [private]
Referenced by OnBrowse(), and PopulateOrExchange().
wxString FindDialog::mType [private]
Referenced by FindDialog(), and OnBrowse().
The documentation for this class was generated from the following file:
ExportMP3.cpp