Audacity: ExportCLOptions Class Reference
ExportCLOptions Class Reference
Public Member Functions
ExportCLOptions (wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
void OnOK (wxCommandEvent &event)
Constructor & Destructor Documentation
ExportCLOptions::ExportCLOptions (wxWindow * parent)
References eIsCreatingFromPrefs.
Member Function Documentation
void ExportCLOptions::OnOK (wxCommandEvent & event)
References eIsSavingToPrefs, and PopulateOrExchange().
void ExportCLOptions::PopulateOrExchange (ShuttleGui & S)
References ShuttleGuiBase::AddFixedText(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::TieCheckBox(), and ShuttleGuiBase::TieTextBox().
Referenced by OnOK().
The documentation for this class was generated from the following file:
ExportCL.cpp