Audacity: ChangeSpeedDialog Class Reference
ChangeSpeedDialog Class Reference
Dialog used with EffectChangeSpeed.
#include <ChangeSpeed.h>
Public Member Functions
ChangeSpeedDialog (EffectChangeSpeed *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
double m_PercentChange
int m_FromVinyl
int m_ToVinyl
Private Member Functions
void OnText_PercentChange (wxCommandEvent &event)
void OnSlider_PercentChange (wxCommandEvent &event)
void OnChoice_FromVinyl (wxCommandEvent &event)
void OnChoice_ToVinyl (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
void Update_Text_PercentChange ()
void Update_Slider_PercentChange ()
void Update_Vinyl ()
void Update_PercentChange ()
Private Attributes
EffectChangeSpeed * mEffect
bool m_bLoopDetect
wxTextCtrl * m_pTextCtrl_PercentChange
wxSlider * m_pSlider_PercentChange
wxChoice * m_pChoice_FromVinyl
wxChoice * m_pChoice_ToVinyl
Detailed Description
Dialog used with EffectChangeSpeed.
Constructor & Destructor Documentation
ChangeSpeedDialog::ChangeSpeedDialog (EffectChangeSpeed * effect, wxWindow * parent)
Member Function Documentation
void ChangeSpeedDialog::OnChoice_FromVinyl (wxCommandEvent & event) [private]
References m_bLoopDetect, m_FromVinyl, m_pChoice_FromVinyl, and Update_PercentChange().
void ChangeSpeedDialog::OnChoice_ToVinyl (wxCommandEvent & event) [private]
References m_bLoopDetect, m_pChoice_ToVinyl, m_ToVinyl, and Update_PercentChange().
void ChangeSpeedDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References m_PercentChange, EffectChangeSpeed::m_PercentChange, mEffect, Effect::Preview(), TransferDataFromWindow(), and Update_Text_PercentChange().
void ChangeSpeedDialog::OnSlider_PercentChange (wxCommandEvent & event) [private]
References m_bLoopDetect, m_PercentChange, m_pSlider_PercentChange, PERCENTCHANGE_SLIDER_WARP, Update_Text_PercentChange(), and Update_Vinyl().
void ChangeSpeedDialog::OnText_PercentChange (wxCommandEvent & event) [private]
References m_bLoopDetect, m_PercentChange, m_pTextCtrl_PercentChange, Update_Slider_PercentChange(), and Update_Vinyl().
void ChangeSpeedDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddChoice(), ShuttleGuiBase::AddSlider(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddUnits(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGui::Id(), ID_CHOICE_FROMVINYL, ID_CHOICE_TOVINYL, ID_SLIDER_PERCENTCHANGE, ID_TEXT_PERCENTCHANGE, m_pChoice_FromVinyl, m_pChoice_ToVinyl, m_pSlider_PercentChange, m_pTextCtrl_PercentChange, PERCENTCHANGE_MAX, PERCENTCHANGE_MIN, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartMultiColumn().
bool ChangeSpeedDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References m_FromVinyl, m_pChoice_FromVinyl, m_pChoice_ToVinyl, m_PercentChange, m_pTextCtrl_PercentChange, and m_ToVinyl.
Referenced by OnPreview().
bool ChangeSpeedDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References m_bLoopDetect, m_FromVinyl, m_pChoice_FromVinyl, m_pChoice_ToVinyl, m_ToVinyl, Update_Slider_PercentChange(), and Update_Text_PercentChange().
void ChangeSpeedDialog::Update_PercentChange () [private]
References CHOICE_33ANDATHIRD, CHOICE_45, CHOICE_78, CHOICE_NA, m_FromVinyl, m_PercentChange, m_ToVinyl, Update_Slider_PercentChange(), and Update_Text_PercentChange().
Referenced by OnChoice_FromVinyl(), and OnChoice_ToVinyl().
void ChangeSpeedDialog::Update_Slider_PercentChange () [private]
References m_PercentChange, m_pSlider_PercentChange, and PERCENTCHANGE_SLIDER_WARP.
Referenced by OnText_PercentChange(), TransferDataToWindow(), and Update_PercentChange().
void ChangeSpeedDialog::Update_Text_PercentChange () [private]
References m_PercentChange, and m_pTextCtrl_PercentChange.
Referenced by OnPreview(), OnSlider_PercentChange(), TransferDataToWindow(), and Update_PercentChange().
void ChangeSpeedDialog::Update_Vinyl () [private]
References CHOICE_NA, m_pChoice_FromVinyl, m_pChoice_ToVinyl, and m_PercentChange.
Referenced by OnSlider_PercentChange(), and OnText_PercentChange().
Member Data Documentation
bool ChangeSpeedDialog::m_bLoopDetect [private]
Referenced by OnChoice_FromVinyl(), OnChoice_ToVinyl(), OnSlider_PercentChange(), OnText_PercentChange(), and TransferDataToWindow().
int ChangeSpeedDialog::m_FromVinyl
Referenced by OnChoice_FromVinyl(), EffectChangeSpeed::PromptUser(), TransferDataFromWindow(), TransferDataToWindow(), and Update_PercentChange().
wxChoice* ChangeSpeedDialog::m_pChoice_FromVinyl [private]
Referenced by OnChoice_FromVinyl(), PopulateOrExchange(), TransferDataFromWindow(), TransferDataToWindow(), and Update_Vinyl().
wxChoice* ChangeSpeedDialog::m_pChoice_ToVinyl [private]
Referenced by OnChoice_ToVinyl(), PopulateOrExchange(), TransferDataFromWindow(), TransferDataToWindow(), and Update_Vinyl().
double ChangeSpeedDialog::m_PercentChange
Referenced by OnPreview(), OnSlider_PercentChange(), OnText_PercentChange(), EffectChangeSpeed::PromptUser(), TransferDataFromWindow(), Update_PercentChange(), Update_Slider_PercentChange(), Update_Text_PercentChange(), and Update_Vinyl().
wxSlider* ChangeSpeedDialog::m_pSlider_PercentChange [private]
Referenced by OnSlider_PercentChange(), PopulateOrExchange(), and Update_Slider_PercentChange().
wxTextCtrl* ChangeSpeedDialog::m_pTextCtrl_PercentChange [private]
Referenced by OnText_PercentChange(), PopulateOrExchange(), TransferDataFromWindow(), and Update_Text_PercentChange().
int ChangeSpeedDialog::m_ToVinyl
Referenced by OnChoice_ToVinyl(), EffectChangeSpeed::PromptUser(), TransferDataFromWindow(), TransferDataToWindow(), and Update_PercentChange().
EffectChangeSpeed* ChangeSpeedDialog::mEffect [private]
Referenced by OnPreview().
The documentation for this class was generated from the following files:
ChangeSpeed.h
ChangeSpeed.cpp