Audacity: ModuleManager Class Reference
ModuleManager Class Reference
#include <LoadModules.h>
Public Member Functions
ModuleManager ()
virtual ~ModuleManager ()
virtual bool OnInit ()
virtual void OnExit ()
Static Public Member Functions
static void Initialize ()
static int Dispatch (ModuleDispatchTypes type)
Private Member Functions
DECLARE_DYNAMIC_CLASS (ModuleManager)
Private Attributes
wxArrayPtrVoid mModules
Static Private Attributes
static ModuleManager * mInstance
Constructor & Destructor Documentation
ModuleManager::ModuleManager () [inline]
virtual ModuleManager::~ModuleManager () [inline, virtual]
Member Function Documentation
ModuleManager::DECLARE_DYNAMIC_CLASS (ModuleManager) [private]
int ModuleManager::Dispatch (ModuleDispatchTypes type) [static]
References Module::Dispatch(), mInstance, and mModules.
Referenced by CreateNewAudacityProject(), AudacityProject::OnCloseWindow(), AudacityApp::OnInit(), QuitAudacity(), and AudacityProject::RebuildMenuBar().
void ModuleManager::Initialize () [static]
References AudacityApp::AddMultiPathsToPathList(), AudacityApp::AddUniquePathToPathList(), AudacityApp::audacityPathList, AudacityApp::FindFilesInPathList(), Module::Load(), mInstance, mModules, and wxGetApp().
Referenced by AudacityApp::OnInit().
void ModuleManager::OnExit (void) [virtual]
References mModules.
bool ModuleManager::OnInit (void) [virtual]
References mInstance.
Member Data Documentation
ModuleManager * ModuleManager::mInstance [static, private]
Referenced by Dispatch(), Initialize(), and OnInit().
wxArrayPtrVoid ModuleManager::mModules [private]
Referenced by Dispatch(), Initialize(), and OnExit().
The documentation for this class was generated from the following files:
LoadModules.h
LoadModules.cpp