Audacity: HighlightTextCtrl Class Reference
HighlightTextCtrl Class Reference
#include <Lyrics.h>
Public Member Functions
HighlightTextCtrl (Lyrics *parent, wxWindowID id, const wxString &value=wxT(""), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
virtual ~HighlightTextCtrl ()
void OnMouseEvent (wxMouseEvent &evt)
Private Attributes
Lyrics * mLyrics
Constructor & Destructor Documentation
HighlightTextCtrl::HighlightTextCtrl (Lyrics * parent, wxWindowID id, const wxString & value = wxT(""), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
virtual HighlightTextCtrl::~HighlightTextCtrl () [inline, virtual]
Member Function Documentation
void HighlightTextCtrl::OnMouseEvent (wxMouseEvent & evt)
References Lyrics::FindSyllable(), GetActiveProject(), Lyrics::GetCurrentSyllableIndex(), Lyrics::GetSyllable(), mLyrics, AudacityProject::mViewInfo, ViewInfo::sel1, AudacityProject::SetSel0(), and Syllable::t.
Member Data Documentation
Lyrics* HighlightTextCtrl::mLyrics [private]
Referenced by OnMouseEvent().
The documentation for this class was generated from the following files:
Lyrics.h
Lyrics.cpp