Audacity: EditToolBar Class Reference
EditToolBar Class Reference
A ToolBar that has the edit buttons on it.
#include <EditToolBar.h>
Public Member Functions
EditToolBar ()
virtual ~EditToolBar ()
void Create (wxWindow *parent)
void OnButton (wxCommandEvent &event)
void Populate ()
void Repaint (wxDC *dc)
void EnableDisableButtons ()
void UpdatePrefs ()
DECLARE_CLASS (EditToolBar)
DECLARE_EVENT_TABLE ()
Private Member Functions
AButton * AddButton (teBmps eFore, teBmps eDisabled, int id, const wxChar *label, bool toggle=false)
void AddSeparator ()
void MakeButtons ()
void RegenerateTooltips ()
Private Attributes
AButton * mButtons [ETBNumButtons]
wxImage * upImage
wxImage * downImage
wxImage * hiliteImage
Detailed Description
A ToolBar that has the edit buttons on it.
This class, which is a child of Toolbar, creates the window containing interfaces to commonly-used edit functions that are otherwise only available through menus. The window can be embedded within a normal project window, or within a ToolbarFrame that is managed by a global ToolBarStub called gControlToolBarStub.
All of the controls in this window were custom-written for Audacity - they are not native controls on any platform - however, it is intended that the images could be easily replaced to allow "skinning" or just customization to match the look and feel of each platform.
Constructor & Destructor Documentation
EditToolBar::EditToolBar ()
EditToolBar::~EditToolBar () [virtual]
References ETBNumButtons, and mButtons.
Member Function Documentation
AButton * EditToolBar::AddButton (teBmps eFore, teBmps eDisabled, int id, const wxChar * label, bool toggle = false) [private]
This is a convenience function that allows for button creation in MakeButtons() with fewer arguments Very similar to code in ControlToolBar...
References ToolBar::Add(), ThemeBase::ImageSize(), ToolBar::MakeButton(), mButtons, and theTheme.
Referenced by Populate().
void EditToolBar::AddSeparator () [private]
References ToolBar::AddSpacer().
Referenced by Populate().
void EditToolBar::Create (wxWindow * parent) [virtual]
Reimplemented from ToolBar.
EditToolBar::DECLARE_CLASS (EditToolBar)
Reimplemented from ToolBar.
EditToolBar::DECLARE_EVENT_TABLE ()
Reimplemented from ToolBar.
void EditToolBar::EnableDisableButtons () [virtual]
Implements ToolBar.
References AudacityProject::Clipboard(), ETBCopyID, ETBCutID, ETBPasteID, ETBRedoID, ETBSilenceID, ETBTrimID, ETBUndoID, ETBZoomFitID, ETBZoomInID, ETBZoomOutID, ETBZoomSelID, GetActiveProject(), AudacityProject::GetSel0(), AudacityProject::GetSel1(), AudacityProject::GetStickyFlag(), AudacityProject::GetTracks(), AudacityProject::GetUndoManager(), AudacityProject::GetZoom(), gMaxZoom, gMinZoom, TrackList::IsEmpty(), mButtons, AButton::PopUp(), UndoManager::RedoAvailable(), AButton::SetEnabled(), and UndoManager::UndoAvailable().
Referenced by AudacityProject::OnStickyLabel().
void EditToolBar::MakeButtons () [private]
void EditToolBar::OnButton (wxCommandEvent & event)
References ETBCopyID, ETBCutID, ETBPasteID, ETBRedoID, ETBSilenceID, ETBTrimID, ETBUndoID, ETBZoomFitID, ETBZoomInID, ETBZoomOutID, ETBZoomSelID, gAudioIO, GetActiveProject(), AudacityProject::GetStickyFlag(), AudacityProject::GetTrackPanel(), AudioIO::IsBusy(), mButtons, AudacityProject::ModifyToolbarMenus(), AudacityProject::OnCopy(), AudacityProject::OnCut(), AudacityProject::OnPaste(), AudacityProject::OnRedo(), AudacityProject::OnSilence(), AudacityProject::OnStickyLabel(), AudacityProject::OnTrim(), AudacityProject::OnUndo(), AudacityProject::OnZoomFit(), AudacityProject::OnZoomIn(), AudacityProject::OnZoomOut(), AudacityProject::OnZoomSel(), AudacityProject::OnZoomToggle(), AButton::PopUp(), TrackPanel::Refresh(), and ToolBar::SetButton().
void EditToolBar::Populate () [virtual]
Implements ToolBar.
References AddButton(), AddSeparator(), ETBCopyID, ETBCutID, ETBPasteID, ETBRedoID, ETBSilenceID, ETBTrimID, ETBUndoID, ETBZoomFitID, ETBZoomInID, ETBZoomOutID, ETBZoomSelID, ToolBar::MakeButtonBackgroundsSmall(), mButtons, AButton::PushDown(), RegenerateTooltips(), and AButton::SetEnabled().
void EditToolBar::RegenerateTooltips () [private]
References ETBCopyID, ETBCutID, ETBPasteID, ETBRedoID, ETBSilenceID, ETBTrimID, ETBUndoID, ETBZoomFitID, ETBZoomInID, ETBZoomOutID, ETBZoomSelID, and mButtons.
Referenced by Populate(), and UpdatePrefs().
void EditToolBar::Repaint (wxDC * dc) [inline, virtual]
Implements ToolBar.
void EditToolBar::UpdatePrefs () [virtual]
Reimplemented from ToolBar.
References RegenerateTooltips(), and ToolBar::SetLabel().
Member Data Documentation
wxImage* EditToolBar::downImage [private]
wxImage* EditToolBar::hiliteImage [private]
AButton* EditToolBar::mButtons[ETBNumButtons] [private]
Referenced by AddButton(), EnableDisableButtons(), OnButton(), Populate(), RegenerateTooltips(), and ~EditToolBar().
wxImage* EditToolBar::upImage [private]
The documentation for this class was generated from the following files:
EditToolBar.h
EditToolBar.cpp