Audacity: ExportFFmpegWMAOptions Class Reference
ExportFFmpegWMAOptions Class Reference
Options dialog for FFmpeg exporting of WMA format.
#include <ExportFFmpegDialogs.h>
Public Member Functions
ExportFFmpegWMAOptions (wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
void OnOK (wxCommandEvent &event)
Static Public Attributes
static const int iWMASampleRates []
static const int iWMABitRate []
Bit Rates supported by WMA encoder. Setting bit rate to other values will not result in different file size.
Private Attributes
wxArrayString mBitRateNames
wxArrayInt mBitRateLabels
wxChoice * mBitRateChoice
wxButton * mOk
int mBitRateFromChoice
Detailed Description
Options dialog for FFmpeg exporting of WMA format.
Constructor & Destructor Documentation
ExportFFmpegWMAOptions::ExportFFmpegWMAOptions (wxWindow * parent)
References eIsCreatingFromPrefs, iWMABitRate, mBitRateLabels, mBitRateNames, and PopulateOrExchange().
Member Function Documentation
void ExportFFmpegWMAOptions::OnOK (wxCommandEvent & event)
References eIsSavingToPrefs, and PopulateOrExchange().
void ExportFFmpegWMAOptions::PopulateOrExchange (ShuttleGui & S)
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndTwoColumn(), mBitRateLabels, mBitRateNames, ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartTwoColumn(), and ShuttleGuiBase::TieChoice().
Referenced by ExportFFmpegWMAOptions(), and OnOK().
Member Data Documentation
const int ExportFFmpegWMAOptions::iWMABitRate [static]
Initial value:
{ 24634, 26012, 27734, 29457, 31524, 33764, 36348, 39448, 42894, 47028, 52024,
   58225, 65805, 75624, 88716, 106976, 134539, 180189, 271835, 546598 }
Bit Rates supported by WMA encoder. Setting bit rate to other values will not result in different file size.
Referenced by ExportFFmpegWMAOptions().
const int ExportFFmpegWMAOptions::iWMASampleRates [static]
Initial value:
{ 8000, 11025, 16000, 22050, 44100, 0}
Referenced by ExportFFmpeg::InitCodecs().
wxChoice* ExportFFmpegWMAOptions::mBitRateChoice [private]
int ExportFFmpegWMAOptions::mBitRateFromChoice [private]
wxArrayInt ExportFFmpegWMAOptions::mBitRateLabels [private]
Referenced by ExportFFmpegWMAOptions(), and PopulateOrExchange().
wxArrayString ExportFFmpegWMAOptions::mBitRateNames [private]
Referenced by ExportFFmpegWMAOptions(), and PopulateOrExchange().
wxButton* ExportFFmpegWMAOptions::mOk [private]
The documentation for this class was generated from the following files:
ExportFFmpegDialogs.h
ExportFFmpegDialogs.cpp