Audacity: BatchProcessDialog Class Reference
BatchProcessDialog Class Reference
Shows progress in executing commands in BatchCommands.
#include <BatchProcessDialog.h>
Public Member Functions
BatchProcessDialog (wxWindow *parent)
virtual ~BatchProcessDialog ()
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
Defines the dialog and does data exchange with it.
void OnApplyToProject (wxCommandEvent &event)
void OnApplyToFiles (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
Public Attributes
wxButton * mOK
wxButton * mCancel
wxListCtrl * mChains
wxListCtrl * mList
BatchCommands mBatchCommands
bool mAbort
Detailed Description
Shows progress in executing commands in BatchCommands.
Constructor & Destructor Documentation
BatchProcessDialog::BatchProcessDialog (wxWindow * parent)
References GetActiveProject(), and AudacityProject::GetCleanSpeechMode().
BatchProcessDialog::~BatchProcessDialog () [virtual]
Member Function Documentation
void BatchProcessDialog::OnApplyToFiles (wxCommandEvent & event)
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddListControlReportMode(), BatchCommands::ApplyChain(), UndoManager::ClearStates(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), Format::formatExtensions, Format::formatName, GetActiveProject(), AudacityProject::GetCleanSpeechMode(), AudacityProject::GetIsEmpty(), Importer::GetSupportedImportFormats(), AudacityProject::GetUndoManager(), gPrefs, ShuttleGui::Id(), AudacityProject::Import(), mAbort, mBatchCommands, mChains, AudacityApp::mImporter, mList, name, AudacityProject::OnRemoveTracks(), AudacityProject::OnSelectAll(), BatchCommands::ReadChain(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartVerticalLay(), and wxGetApp().
void BatchProcessDialog::OnApplyToProject (wxCommandEvent & event)
References ShuttleGuiBase::AddFixedText(), BatchCommands::ApplyChain(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), gPrefs, mBatchCommands, mChains, name, BatchCommands::ReadChain(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartStatic().
void BatchProcessDialog::OnCancel (wxCommandEvent & event)
void BatchProcessDialog::Populate ()
References eIsCreating, and PopulateOrExchange().
void BatchProcessDialog::PopulateOrExchange (ShuttleGui & S)
Defines the dialog and does data exchange with it.
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddListControlReportMode(), ApplyToFilesID, ApplyToProjectID, ChainsListID, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), BatchCommands::GetNames(), gPrefs, ShuttleGui::Id(), mBatchCommands, mChains, name, names, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::StartVerticalLay().
Referenced by Populate().
Member Data Documentation
bool BatchProcessDialog::mAbort
Referenced by OnApplyToFiles().
BatchCommands BatchProcessDialog::mBatchCommands
Referenced by OnApplyToFiles(), OnApplyToProject(), and PopulateOrExchange().
wxButton* BatchProcessDialog::mCancel
wxListCtrl* BatchProcessDialog::mChains
Referenced by OnApplyToFiles(), OnApplyToProject(), and PopulateOrExchange().
wxListCtrl* BatchProcessDialog::mList
Referenced by OnApplyToFiles().
wxButton* BatchProcessDialog::mOK
The documentation for this class was generated from the following files:
BatchProcessDialog.h
BatchProcessDialog.cpp