Audacity: ImportRawDialog Class Reference
ImportRawDialog Class Reference
ImportRawDialog prompts you with options such as endianness and sample size to help you importing data of an unknown format.
Public Member Functions
ImportRawDialog (wxWindow *parent, int encoding, int channels, int offset, double rate)
~ImportRawDialog ()
void OnOK (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void OnPlay (wxCommandEvent &event)
void OnChoice (wxCommandEvent &event)
Public Attributes
int mEncoding
int mChannels
int mOffset
double mRate
double mPercent
Private Attributes
wxButton * mOK
wxChoice * mEncodingChoice
wxChoice * mEndianChoice
wxChoice * mChannelChoice
wxTextCtrl * mOffsetText
wxTextCtrl * mPercentText
wxTextCtrl * mRateText
int mNumEncodings
int * mEncodingSubtype
Detailed Description
ImportRawDialog prompts you with options such as endianness and sample size to help you importing data of an unknown format.
Constructor & Destructor Documentation
ImportRawDialog::ImportRawDialog (wxWindow * parent, int encoding, int channels, int offset, double rate)
References ShuttleGuiBase::AddChoice(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddUnits(), eIsCreating, ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndTwoColumn(), ShuttleGuiBase::EndVerticalLay(), ShuttleGui::Id(), LAT1CTOWX, ShuttleGuiBase::SetBorder(), sf_encoding_index_name(), sf_encoding_index_to_subtype(), sf_num_encodings(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartTwoColumn(), and ShuttleGuiBase::StartVerticalLay().
ImportRawDialog::~ImportRawDialog ()
References mEncodingSubtype.
Member Function Documentation
void ImportRawDialog::OnCancel (wxCommandEvent & event)
void ImportRawDialog::OnChoice (wxCommandEvent & event)
void ImportRawDialog::OnOK (wxCommandEvent & event)
void ImportRawDialog::OnPlay (wxCommandEvent & event)
Member Data Documentation
wxChoice* ImportRawDialog::mChannelChoice [private]
int ImportRawDialog::mChannels
Referenced by ImportRaw().
int ImportRawDialog::mEncoding
Referenced by ImportRaw().
wxChoice* ImportRawDialog::mEncodingChoice [private]
int* ImportRawDialog::mEncodingSubtype [private]
Referenced by ~ImportRawDialog().
wxChoice* ImportRawDialog::mEndianChoice [private]
int ImportRawDialog::mNumEncodings [private]
int ImportRawDialog::mOffset
Referenced by ImportRaw().
wxTextCtrl* ImportRawDialog::mOffsetText [private]
wxButton* ImportRawDialog::mOK [private]
double ImportRawDialog::mPercent
Referenced by ImportRaw().
wxTextCtrl* ImportRawDialog::mPercentText [private]
double ImportRawDialog::mRate
Referenced by ImportRaw().
wxTextCtrl* ImportRawDialog::mRateText [private]
The documentation for this class was generated from the following file:
ImportRaw.cpp