Audacity: ScriptCommandRelay Class Reference
ScriptCommandRelay Class Reference
ScriptCommandRelay is just a way to move some of the scripting-specific code out of LoadModules.
#include <ScriptCommandRelay.h>
Static Public Member Functions
static void SetRegScriptServerFunc (tpRegScriptServerFunc scriptFn)
static void SetCommandHandler (CommandHandler &ch)
static void Run ()
Calls the script function, passing it the function for obeying commands.
static void PostCommand (AudacityProject *project, Command *cmd)
Send a command to a project, to be applied in that context.
static void SendResponse (const wxString &response)
Adds a response to the queue to be sent back to the script.
static Response ReceiveResponse ()
Gets a response from the queue (may block).
static ResponseQueueTarget * GetResponseTarget ()
Static Private Attributes
static CommandHandler * sCmdHandler
static tpRegScriptServerFunc sScriptFn
static ResponseQueue sResponseQueue
Detailed Description
ScriptCommandRelay is just a way to move some of the scripting-specific code out of LoadModules.
Member Function Documentation
ResponseQueueTarget * ScriptCommandRelay::GetResponseTarget () [static]
Get a pointer to a message target which allows commands to send responses back to a script.
References sResponseQueue.
Referenced by CommandBuilder::BuildCommand().
void ScriptCommandRelay::PostCommand (AudacityProject * project, Command * cmd) [static]
Send a command to a project, to be applied in that context.
References AppCommandEvent::SetCommand().
Referenced by ExecCommand(), and AudacityProject::SafeDisplayStatusMessage().
Response ScriptCommandRelay::ReceiveResponse () [static]
Gets a response from the queue (may block).
References ResponseQueue::WaitAndGetResponse().
Referenced by ExecCommand().
void ScriptCommandRelay::Run () [static]
Calls the script function, passing it the function for obeying commands.
References ExecCommand(), and sScriptFn.
Referenced by LoadModules().
void ScriptCommandRelay::SendResponse (const wxString & response) [static]
Adds a response to the queue to be sent back to the script.
References ResponseQueue::AddResponse(), and sResponseQueue.
Referenced by CommandBuilder::BuildCommand().
void ScriptCommandRelay::SetCommandHandler (CommandHandler & ch) [static]
References sCmdHandler.
Referenced by LoadModules().
void ScriptCommandRelay::SetRegScriptServerFunc (tpRegScriptServerFunc scriptFn) [static]
References sScriptFn.
Referenced by LoadModules().
Member Data Documentation
CommandHandler * ScriptCommandRelay::sCmdHandler [static, private]
Referenced by SetCommandHandler().
ResponseQueue ScriptCommandRelay::sResponseQueue [static, private]
Referenced by GetResponseTarget(), and SendResponse().
tpRegScriptServerFunc ScriptCommandRelay::sScriptFn [static, private]
Referenced by Run(), and SetRegScriptServerFunc().
The documentation for this class was generated from the following files:
ScriptCommandRelay.h
ScriptCommandRelay.cpp