Audacity: EffectTwoPassSimpleMono Class Reference
EffectTwoPassSimpleMono Class Reference
An Effect base class that implements a two pass process by using EffectSimpleMono.
#include <TwoPassSimpleMono.h>
Public Member Functions
virtual bool Process ()
Protected Member Functions
virtual bool InitPass1 ()
virtual bool InitPass2 ()
virtual bool NewTrackPass1 ()
virtual bool NewTrackPass2 ()
virtual bool ProcessPass1 (float *buffer, sampleCount len)
virtual bool ProcessPass2 (float *buffer, sampleCount len)
virtual bool TwoBufferProcessPass1 (float *buffer1, sampleCount len1, float *buffer2, sampleCount len2)
virtual bool TwoBufferProcessPass2 (float *buffer1, sampleCount len1, float *buffer2, sampleCount len2)
void DisableSecondPass ()
Protected Attributes
int mCurTrackNum
double mCurRate
double mCurT0
double mCurT1
int mCurChannel
int mPass
bool mSecondPassDisabled
Private Member Functions
bool ProcessOne (WaveTrack *t, sampleCount start, sampleCount end)
bool ProcessPass ()
Detailed Description
An Effect base class that implements a two pass process by using EffectSimpleMono.
Inherit from it if your effect needs to pass twice over the data. It does the first pass on all selected tracks before going back and doing the second pass over all selected tracks.
Member Function Documentation
void EffectTwoPassSimpleMono::DisableSecondPass () [inline, protected]
References mSecondPassDisabled.
Referenced by EffectCompressor::InitPass1().
bool EffectTwoPassSimpleMono::InitPass1 () [protected, virtual]
Reimplemented in EffectCompressor.
Referenced by Process().
bool EffectTwoPassSimpleMono::InitPass2 () [protected, virtual]
Reimplemented in EffectCompressor.
Referenced by Process().
bool EffectTwoPassSimpleMono::NewTrackPass1 () [protected, virtual]
Reimplemented in EffectCompressor.
Referenced by ProcessPass().
bool EffectTwoPassSimpleMono::NewTrackPass2 () [protected, virtual]
Referenced by ProcessPass().
bool EffectTwoPassSimpleMono::Process () [virtual]
Implements Effect.
References Effect::CopyInputTracks(), InitPass1(), InitPass2(), mPass, mSecondPassDisabled, ProcessPass(), and Effect::ReplaceProcessedTracks().
bool EffectTwoPassSimpleMono::ProcessOne (WaveTrack * t, sampleCount start, sampleCount end) [private]
References floatSample, WaveTrack::Get(), WaveTrack::GetBestBlockSize(), WaveTrack::GetMaxBlockSize(), Effect::GetNumWaveTracks(), mCurTrackNum, mPass, mSecondPassDisabled, WaveTrack::Set(), Effect::TotalProgress(), TwoBufferProcessPass1(), and TwoBufferProcessPass2().
Referenced by ProcessPass().
bool EffectTwoPassSimpleMono::ProcessPass () [private]
References TrackListCondIterator::First(), Track::GetChannel(), WaveTrack::GetEndTime(), WaveTrack::GetRate(), WaveTrack::GetStartTime(), mCurChannel, mCurRate, mCurT0, mCurT1, mCurTrackNum, Effect::mOutputTracks, mPass, Effect::mT0, Effect::mT1, NewTrackPass1(), NewTrackPass2(), TrackListCondIterator::Next(), ProcessOne(), WaveTrack::TimeToLongSamples(), and Track::Wave.
Referenced by Process().
virtual bool EffectTwoPassSimpleMono::ProcessPass1 (float * buffer, sampleCount len) [inline, protected, virtual]
Referenced by TwoBufferProcessPass1().
virtual bool EffectTwoPassSimpleMono::ProcessPass2 (float * buffer, sampleCount len) [inline, protected, virtual]
Reimplemented in EffectCompressor.
Referenced by TwoBufferProcessPass2().
virtual bool EffectTwoPassSimpleMono::TwoBufferProcessPass1 (float * buffer1, sampleCount len1, float * buffer2, sampleCount len2) [inline, protected, virtual]
Reimplemented in EffectCompressor.
References ProcessPass1().
Referenced by ProcessOne().
virtual bool EffectTwoPassSimpleMono::TwoBufferProcessPass2 (float * buffer1, sampleCount len1, float * buffer2, sampleCount len2) [inline, protected, virtual]
References ProcessPass2().
Referenced by ProcessOne().
Member Data Documentation
int EffectTwoPassSimpleMono::mCurChannel [protected]
Referenced by ProcessPass().
double EffectTwoPassSimpleMono::mCurRate [protected]
Referenced by EffectCompressor::NewTrackPass1(), and ProcessPass().
double EffectTwoPassSimpleMono::mCurT0 [protected]
Referenced by ProcessPass().
double EffectTwoPassSimpleMono::mCurT1 [protected]
Referenced by ProcessPass().
int EffectTwoPassSimpleMono::mCurTrackNum [protected]
Referenced by ProcessOne(), and ProcessPass().
int EffectTwoPassSimpleMono::mPass [protected]
Referenced by Process(), ProcessOne(), and ProcessPass().
bool EffectTwoPassSimpleMono::mSecondPassDisabled [protected]
Referenced by DisableSecondPass(), Process(), and ProcessOne().
The documentation for this class was generated from the following files:
TwoPassSimpleMono.h
TwoPassSimpleMono.cpp