Audacity: Vector Class Reference
Vector Class Reference
Holds a matrix of doubles and supports arithmetic operations, including Vector-Matrix operations. Used by InterpolateAudio.
#include <Matrix.h>
Public Member Functions
Vector ()
Vector (const Vector &copyFrom)
Vector (int len, double *data=NULL, bool copy=true)
Vector (int len, float *data)
Vector & operator= (const Vector &other)
virtual ~Vector ()
double & operator[] (int i)
double operator[] (int i) const
int Len () const
double Sum () const
Private Member Functions
void CopyFrom (const Vector &other)
Private Attributes
int mN
double * mData
bool mCopy
Detailed Description
Holds a matrix of doubles and supports arithmetic operations, including Vector-Matrix operations. Used by InterpolateAudio.
Constructor & Destructor Documentation
Vector::Vector ()
References mCopy, mData, and mN.
Vector::Vector (const Vector & copyFrom)
References CopyFrom().
Vector::Vector (int len, double * data = NULL, bool copy = true)
References mCopy, mData, and mN.
Vector::Vector (int len, float * data)
References mCopy, mData, and mN.
Vector::~Vector () [virtual]
References mCopy, and mData.
Member Function Documentation
void Vector::CopyFrom (const Vector & other) [private]
References Len(), mCopy, mData, and mN.
Referenced by Vector().
int Vector::Len () const [inline]
References mN.
Referenced by CopyFrom(), operator*(), operator+(), operator-(), operator=(), Sum(), and VectorConcatenate().
Vector & Vector::operator= (const Vector & other)
References Len(), and mData.
double Vector::operator[] (int i) const [inline]
References mData.
double& Vector::operator[] (int i) [inline]
References mData.
double Vector::Sum () const
References Len(), and mData.
Member Data Documentation
bool Vector::mCopy [private]
Referenced by CopyFrom(), Vector(), and ~Vector().
double* Vector::mData [private]
Referenced by CopyFrom(), operator=(), operator[](), Sum(), Vector(), and ~Vector().
int Vector::mN [private]
Referenced by CopyFrom(), Len(), and Vector().
The documentation for this class was generated from the following files:
Matrix.h
Matrix.cpp