Audacity: Envelope Class Reference
Envelope Class Reference
Draggable curve used in TrackPanel for varying amplification.
#include <Envelope.h>
Public Member Functions
Envelope ()
void Initialize (int numPoints)
virtual ~Envelope ()
void SetInterpolateDB (bool db)
void Mirror (bool mirror)
void Flatten (double value)
void SetDefaultValue (double value)
int GetDragPoint (void)
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
void DrawPoints (wxDC &dc, const wxRect &r, double h, double pps, bool dB, float zoomMin=-1.0, float zoomMax=1.0)
TODO: This should probably move to track artist.
bool MouseEvent (wxMouseEvent &event, wxRect &r, double h, double pps, bool dB, float zoomMin=-1.0, float zoomMax=1.0, float eMin=0., float eMax=2.)
bool HandleMouseButtonDown (wxMouseEvent &event, wxRect &r, double h, double pps, bool dB, float zoomMin=-1.0, float zoomMax=1.0, float eMin=0., float eMax=2.)
bool HandleDragging (wxMouseEvent &event, wxRect &r, double h, double pps, bool dB, float zoomMin=-1.0, float zoomMax=1.0, float eMin=0., float eMax=2.)
bool HandleMouseButtonUp (wxMouseEvent &event, wxRect &r, double h, double pps, bool dB, float zoomMin=-1.0, float zoomMax=1.0)
void GetEventParams (int &height, bool &upper, bool dB, wxMouseEvent &event, wxRect &r, float &zoomMin, float &zoomMax)
void CollapseRegion (double t0, double t1)
void CopyFrom (const Envelope *e, double t0, double t1)
void Paste (double t0, Envelope *e)
void InsertSpace (double t0, double tlen)
void RemoveUnneededPoints (double time=-1, double tolerence=0.001)
void SetOffset (double newOffset)
void SetTrackLen (double trackLen)
double GetValue (double t) const
Get envelope value at time t.
double GetValueAtX (int x, const wxRect &r, double h, double pps)
Get envelope value at pixel X.
void GetValues (double *buffer, int len, double t0, double tstep) const
Get many envelope points at once.
int NumberOfPointsAfter (double t)
double NextPointAfter (double t)
double Average (double t0, double t1)
double Integral (double t0, double t1)
double Integral (double t0, double t1, double minY, double maxY)
void print ()
void testMe ()
bool IsDirty () const
int Insert (double when, double value)
Add a point at a particular spot.
int Move (double when, double value)
Move a point at when to value.
void Delete (int point)
delete a point by it's position in array
int GetNumberOfPoints () const
Return number of points.
void GetPoints (double *bufferWhen, double *bufferValue, int bufferLen) const
Returns the sets of when and value pairs.
Private Member Functions
double fromDB (double x) const
double toDB (double x)
EnvPoint * AddPointAtEnd (double t, double val)
void MarkDragPointForDeletion ()
float ValueOfPixel (int y, int height, bool upper, bool dB, float zoomMin, float zoomMax, float eMin=-10000., float eMax=10000.)
void BinarySearchForTime (int &Lo, int &Hi, double t) const
double GetInterpolationStartValueAtPoint (int iPoint) const
void MoveDraggedPoint (wxMouseEvent &event, wxRect &r, double h, double pps, bool dB, float zoomMin, float zoomMax, float eMin, float eMax)
void resetIntegralMemoizer ()
Private Attributes
EnvArray mEnv
bool mMirror
double mOffset
The time at which the envelope starts, i.e. the start offset.
double mTrackLen
The length of the envelope, which is the same as the length of the underlying track (normally).
double mTrackEpsilon
The shortest distance appart that points on an envelope can be before being considered the same point.
double mDefaultValue
int mContourOffset
Number of pixels contour is from the true envelope.
double mInitialWhen
double mInitialVal
int mDragPoint
int mInitialX
int mInitialY
bool mUpper
bool mIsDeleting
int mButton
bool mDB
bool mDirty
double lastIntegral_t0
double lastIntegral_t1
double lastIntegral_result
Detailed Description
Draggable curve used in TrackPanel for varying amplification.
This class manages an envelope - i.e. a piecewise linear funtion that the user can edit by dragging control points around. The envelope is most commonly used to control the amplitude of a waveform, but it is also used to shape the Equalization curve.
Constructor & Destructor Documentation
Envelope::Envelope ()
References mButton, mDB, mDefaultValue, mDirty, mDragPoint, mIsDeleting, mMirror, mOffset, mTrackEpsilon, and mTrackLen.
Envelope::~Envelope () [virtual]
References mDragPoint, and mEnv.
Member Function Documentation
EnvPoint * Envelope::AddPointAtEnd (double t, double val) [private]
References mEnv, EnvPoint::t, and EnvPoint::val.
Referenced by CopyFrom(), and HandleXMLChild().
double Envelope::Average (double t0, double t1)
References GetValue(), and Integral().
Referenced by AudioIO::StartStream(), and Ruler::Update().
void Envelope::BinarySearchForTime (int & Lo, int & Hi, double t) const [private]
Parameters:
Lo returns index before this time.
Hi returns index after this time.
References mEnv.
Referenced by GetValues(), Integral(), NextPointAfter(), and NumberOfPointsAfter().
void Envelope::CollapseRegion (double t0, double t1)
References Limit(), mEnv, mOffset, and mTrackLen.
Referenced by WaveClip::Clear(), and WaveClip::ClearAndAddCutLine().
void Envelope::CopyFrom (const Envelope * e, double t0, double t1)
References AddPointAtEnd(), GetValue(), mEnv, mOffset, and mTrackLen.
Referenced by WaveClip::CreateFromCopy(), and EqualizationDialog::ErrMin().
void Envelope::Delete (int point)
delete a point by it's position in array
References mEnv.
Referenced by EqualizationDialog::OnDrawRadio(), EqualizationDialog::OnOk(), Paste(), and RemoveUnneededPoints().
void Envelope::DrawPoints (wxDC & dc, const wxRect & r, double h, double pps, bool dB, float zoomMin = -1.0, float zoomMax = 1.0)
TODO: This should probably move to track artist.
References DrawPoint(), ENV_DB_RANGE, AColor::envelopeBrush, AColor::envelopePen, GetWaveYPos(), gPrefs, mDragPoint, mEnv, mMirror, and mOffset.
Referenced by TrackArtist::DrawClipWaveform(), TrackArtist::DrawTimeTrack(), and EqualizationPanel::OnPaint().
void Envelope::Flatten (double value)
Flatten removes all points from the envelope to make it horizontal at a chosen y-value. - the y-value for the flat envelope.
References mEnv, and SetDefaultValue().
Referenced by EqualizationDialog::EnvLinToLog(), EqualizationDialog::EnvLogToLin(), EqualizationDialog::ErrMin(), EqualizationDialog::GraphicEQ(), EqualizationDialog::OnClear(), EqualizationDialog::setCurve(), TimeTrack::testMe(), testMe(), and TimeTrack::TimeTrack().
double Envelope::fromDB (double x) const [private]
References ENV_DB_RANGE, and gPrefs.
Referenced by ValueOfPixel().
int Envelope::GetDragPoint (void) [inline]
References mDragPoint.
Referenced by WaveTrack::GetActiveEnvelope().
void Envelope::GetEventParams (int & height, bool & upper, bool dB, wxMouseEvent & event, wxRect & r, float & zoomMin, float & zoomMax)
double Envelope::GetInterpolationStartValueAtPoint (int iPoint) const [private]
GetInterpolationStartValueAtPoint() is used to select either the envelope value or its log depending on whether we are doing linear or log interpolation.
Parameters:
iPoint index in env array to look at.
Returns:
value there, or its (safe) log10.
References mDB, and mEnv.
Referenced by GetValues().
int Envelope::GetNumberOfPoints () const
Return number of points.
References mEnv.
Referenced by EqualizationDialog::EnvelopeUpdated(), EqualizationDialog::EnvLinToLog(), EqualizationDialog::EnvLogToLin(), WaveTrack::HandleClear(), EqualizationDialog::OnDrawRadio(), EqualizationDialog::OnInvert(), and EqualizationDialog::OnOk().
void Envelope::GetPoints (double * bufferWhen, double * bufferValue, int bufferLen) const
Returns the sets of when and value pairs.
References mEnv.
Referenced by EqualizationDialog::EnvelopeUpdated(), EqualizationDialog::EnvLinToLog(), EqualizationDialog::EnvLogToLin(), EqualizationDialog::OnDrawRadio(), EqualizationDialog::OnInvert(), and EqualizationDialog::OnOk().
double Envelope::GetValue (double t) const
Get envelope value at time t.
References GetValues().
Referenced by audacityAudioCallback(), Average(), EqualizationDialog::CalcFilter(), CopyFrom(), EqualizationDialog::ErrMin(), GetValueAtX(), WaveTrack::HandleClear(), TrackPanel::HandleSampleEditingClick(), TrackPanel::HandleSampleEditingDrag(), TrackPanel::HitTestSamples(), Mixer::MixVariableRates(), Paste(), RemoveUnneededPoints(), WaveTrack::SplitAt(), and EqualizationDialog::UpdateGraphic().
double Envelope::GetValueAtX (int x, const wxRect & r, double h, double pps)
Get envelope value at pixel X.
References GetValue().
Referenced by TrackArtist::DrawIndividualSamples(), HandleMouseButtonDown(), and TrackPanel::HitTestEnvelope().
void Envelope::GetValues (double * buffer, int len, double t0, double tstep) const
Get many envelope points at once.
This is much faster than calling GetValue() multiple times if you need more than one value in a row.
References BinarySearchForTime(), GetInterpolationStartValueAtPoint(), mDB, mDefaultValue, mEnv, mOffset, mTrackEpsilon, and mTrackLen.
Referenced by TimeTrack::Draw(), TrackArtist::DrawClipWaveform(), WaveTrack::GetEnvelopeValues(), GetValue(), and EqualizationPanel::OnPaint().
bool Envelope::HandleDragging (wxMouseEvent & event, wxRect & r, double h, double pps, bool dB, float zoomMin = -1.0, float zoomMax = 1.0, float eMin = 0., float eMax = 2.)
References MarkDragPointForDeletion(), mDirty, mIsDeleting, and MoveDraggedPoint().
Referenced by MouseEvent().
bool Envelope::HandleMouseButtonDown (wxMouseEvent & event, wxRect & r, double h, double pps, bool dB, float zoomMin = -1.0, float zoomMax = 1.0, float eMin = 0., float eMax = 2.)
HandleMouseButtonDown either finds an existing control point or adds a new one which is then recorded as the point to drag. This is slightly complicated by there possibly being four control points for a given time value: We have an upper and lower envelope line. Also we may be showing an inner envelope (at 0.5 the range).
References ENV_DB_RANGE, GetValueAtX(), GetWaveYPos(), gPrefs, Insert(), mButton, mContourOffset, mDirty, mDragPoint, mEnv, mInitialVal, mInitialWhen, mInitialX, mInitialY, mIsDeleting, mMirror, mOffset, mUpper, SQR, and ValueOfPixel().
Referenced by MouseEvent().
bool Envelope::HandleMouseButtonUp (wxMouseEvent & event, wxRect & r, double h, double pps, bool dB, float zoomMin = -1.0, float zoomMax = 1.0)
References mButton, mDragPoint, mEnv, and mIsDeleting.
Referenced by MouseEvent().
XMLTagHandler * Envelope::HandleXMLChild (const wxChar * tag) [virtual]
Implements XMLTagHandler.
References AddPointAtEnd().
bool Envelope::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements XMLTagHandler.
References XMLValueChecker::IsGoodInt(), and mEnv.
void Envelope::Initialize (int numPoints)
int Envelope::Insert (double when, double value)
Add a point at a particular spot.
Add a control point to the envelope.
Control point positions start at zero and are measured in seconds from the start of the envelope. The position of the envelope on the project-wide time scale is store in seconds in Envelope::mOffset. This is worth remembering. If you call Envelope::Insert() from WaveClip, or anywhere else outside the Envelope class that is using project timing, subtract the envelope's mOffset from the time. If you call Envelope::Insert() from within Envelope, don't subtract mOffset because you are working in relative time inside the envelope
Parameters:
when the time in seconds when the envelope point should be created.
value the envelope value to use at the given point.
Returns:
the index of the new envelope point within array of envelope points.
References mEnv, mTrackLen, EnvPoint::t, and EnvPoint::val.
Referenced by EqualizationDialog::EnvLinToLog(), EqualizationDialog::EnvLogToLin(), EqualizationDialog::GraphicEQ(), WaveTrack::HandleClear(), HandleMouseButtonDown(), Paste(), RemoveUnneededPoints(), EqualizationDialog::setCurve(), WaveTrack::SplitAt(), TimeTrack::testMe(), testMe(), and EqualizationDialog::UpdateGraphic().
void Envelope::InsertSpace (double t0, double tlen)
References mEnv, and mTrackLen.
Referenced by WaveClip::InsertSilence().
double Envelope::Integral (double t0, double t1, double minY, double maxY)
References Integral().
double Envelope::Integral (double t0, double t1)
References BinarySearchForTime(), mDefaultValue, and mEnv.
Referenced by Average(), Integral(), testMe(), and TimeTrack::warp().
bool Envelope::IsDirty () const
void Envelope::MarkDragPointForDeletion () [private]
Mark dragged point for deletion. It will be deleted on mouse button up.
References mDefaultValue, mDragPoint, mEnv, and mIsDeleting.
Referenced by HandleDragging().
void Envelope::Mirror (bool mirror)
References mMirror.
Referenced by EqualizationDialog::ErrMin(), testMe(), and TimeTrack::TimeTrack().
bool Envelope::MouseEvent (wxMouseEvent & event, wxRect & r, double h, double pps, bool dB, float zoomMin = -1.0, float zoomMax = 1.0, float eMin = 0., float eMax = 2.)
References HandleDragging(), HandleMouseButtonDown(), HandleMouseButtonUp(), mButton, and mDragPoint.
Referenced by TrackPanel::ForwardEventToTimeTrackEnvelope(), TrackPanel::ForwardEventToWaveTrackEnvelope(), and EqualizationPanel::OnMouseEvent().
int Envelope::Move (double when, double value)
Move a point at when to value.
Returns 0 if point moved, -1 if not found.
References mEnv.
Referenced by EqualizationDialog::EnvLinToLog(), EqualizationDialog::EnvLogToLin(), EqualizationDialog::GraphicEQ(), and EqualizationDialog::OnInvert().
void Envelope::MoveDraggedPoint (wxMouseEvent & event, wxRect & r, double h, double pps, bool dB, float zoomMin, float zoomMax, float eMin, float eMax) [private]
References Limit(), mDragPoint, mEnv, mInitialWhen, mInitialX, mTrackEpsilon, mTrackLen, mUpper, and ValueOfPixel().
Referenced by HandleDragging().
double Envelope::NextPointAfter (double t)
References BinarySearchForTime(), and mEnv.
Referenced by testMe().
int Envelope::NumberOfPointsAfter (double t)
References BinarySearchForTime(), and mEnv.
Referenced by testMe().
void Envelope::Paste (double t0, Envelope * e)
References Delete(), GetValue(), Insert(), mDefaultValue, mEnv, mOffset, mTrackEpsilon, and mTrackLen.
Referenced by WaveClip::Paste(), TimeTrack::TimeTrack(), and WaveClip::WaveClip().
void Envelope::print ()
References mEnv.
void Envelope::RemoveUnneededPoints (double time = -1, double tolerence = 0.001)
References Delete(), GetValue(), Insert(), mEnv, and mOffset.
Referenced by WaveTrack::HandleClear(), and WaveClip::Paste().
void Envelope::resetIntegralMemoizer () [inline, private]
References lastIntegral_result, lastIntegral_t0, and lastIntegral_t1.
void Envelope::SetDefaultValue (double value) [inline]
References mDefaultValue.
Referenced by Flatten(), TimeTrack::testMe(), and testMe().
void Envelope::SetInterpolateDB (bool db)
References mDB.
Referenced by EqualizationDialog::ErrMin(), testMe(), and TimeTrack::TimeTrack().
void Envelope::SetOffset (double newOffset)
References mOffset.
Referenced by TimeTrack::HandleXMLTag(), WaveClip::SetOffset(), TimeTrack::TimeTrack(), and WaveClip::WaveClip().
void Envelope::SetTrackLen (double trackLen)
References mEnv, and mTrackLen.
Referenced by EqualizationDialog::EnvLinToLog(), EqualizationDialog::EnvLogToLin(), EqualizationDialog::ErrMin(), EqualizationDialog::GraphicEQ(), EqualizationDialog::OnClear(), EqualizationDialog::setCurve(), TimeTrack::TimeTrack(), WaveClip::UpdateEnvelopeTrackLen(), and WaveClip::WaveClip().
void Envelope::testMe ()
References checkResult(), Flatten(), Insert(), Integral(), mEnv, Mirror(), NextPointAfter(), NumberOfPointsAfter(), SetDefaultValue(), and SetInterpolateDB().
double Envelope::toDB (double x) [private]
References ENV_DB_RANGE, gPrefs, and Limit().
float Envelope::ValueOfPixel (int y, int height, bool upper, bool dB, float zoomMin, float zoomMax, float eMin = -10000., float eMax = 10000.) [private]
ValueOfPixel() converts a y position on screen to an envelope value.
Parameters:
y - y position, usually of the mouse.relative to the clip.
height - height of the rectangle we are in. - true if we are on the upper line, false if on lower. - display mode either linear or log. - vertical scale, typically -1.0 - vertical scale, typically +1.0 - clips result to this range. - clips result to this range.
References fromDB(), and mContourOffset.
Referenced by HandleMouseButtonDown(), and MoveDraggedPoint().
void Envelope::WriteXML (XMLWriter & xmlFile) [virtual]
References XMLWriter::EndTag(), mEnv, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
Referenced by WaveClip::WriteXML(), and TimeTrack::WriteXML().
Member Data Documentation
double Envelope::lastIntegral_result [private]
Referenced by resetIntegralMemoizer().
double Envelope::lastIntegral_t0 [private]
Referenced by resetIntegralMemoizer().
double Envelope::lastIntegral_t1 [private]
Referenced by resetIntegralMemoizer().
int Envelope::mButton [private]
Referenced by Envelope(), HandleMouseButtonDown(), HandleMouseButtonUp(), and MouseEvent().
int Envelope::mContourOffset [private]
Number of pixels contour is from the true envelope.
Referenced by HandleMouseButtonDown(), and ValueOfPixel().
bool Envelope::mDB [private]
Referenced by Envelope(), GetInterpolationStartValueAtPoint(), GetValues(), and SetInterpolateDB().
double Envelope::mDefaultValue [private]
Referenced by Envelope(), GetValues(), Integral(), MarkDragPointForDeletion(), Paste(), and SetDefaultValue().
bool Envelope::mDirty [private]
Referenced by Envelope(), HandleDragging(), and HandleMouseButtonDown().
int Envelope::mDragPoint [private]
Referenced by DrawPoints(), Envelope(), GetDragPoint(), HandleMouseButtonDown(), HandleMouseButtonUp(), MarkDragPointForDeletion(), MouseEvent(), MoveDraggedPoint(), and ~Envelope().
EnvArray Envelope::mEnv [private]
Referenced by AddPointAtEnd(), BinarySearchForTime(), CollapseRegion(), CopyFrom(), Delete(), DrawPoints(), Flatten(), GetInterpolationStartValueAtPoint(), GetNumberOfPoints(), GetPoints(), GetValues(), HandleMouseButtonDown(), HandleMouseButtonUp(), HandleXMLTag(), Insert(), InsertSpace(), Integral(), MarkDragPointForDeletion(), Move(), MoveDraggedPoint(), NextPointAfter(), NumberOfPointsAfter(), Paste(), print(), RemoveUnneededPoints(), SetTrackLen(), testMe(), WriteXML(), and ~Envelope().
double Envelope::mInitialVal [private]
Referenced by HandleMouseButtonDown().
double Envelope::mInitialWhen [private]
Referenced by HandleMouseButtonDown(), and MoveDraggedPoint().
int Envelope::mInitialX [private]
Referenced by HandleMouseButtonDown(), and MoveDraggedPoint().
int Envelope::mInitialY [private]
Referenced by HandleMouseButtonDown().
bool Envelope::mIsDeleting [private]
Referenced by Envelope(), HandleDragging(), HandleMouseButtonDown(), HandleMouseButtonUp(), and MarkDragPointForDeletion().
bool Envelope::mMirror [private]
Referenced by DrawPoints(), Envelope(), HandleMouseButtonDown(), and Mirror().
double Envelope::mOffset [private]
The time at which the envelope starts, i.e. the start offset.
Referenced by CollapseRegion(), CopyFrom(), DrawPoints(), Envelope(), GetValues(), HandleMouseButtonDown(), Paste(), RemoveUnneededPoints(), and SetOffset().
double Envelope::mTrackEpsilon [private]
The shortest distance appart that points on an envelope can be before being considered the same point.
Referenced by Envelope(), GetValues(), MoveDraggedPoint(), and Paste().
double Envelope::mTrackLen [private]
The length of the envelope, which is the same as the length of the underlying track (normally).
Referenced by CollapseRegion(), CopyFrom(), Envelope(), GetValues(), Insert(), InsertSpace(), MoveDraggedPoint(), Paste(), and SetTrackLen().
bool Envelope::mUpper [private]
Referenced by HandleMouseButtonDown(), and MoveDraggedPoint().
The documentation for this class was generated from the following files:
Envelope.h
Envelope.cpp