Audacity: TimeWarper Class Reference
TimeWarper Class Reference
Transforms one point in time to another point. For example, a time stretching effect might use one to keep track of what happens to labels and split points in the input.
#include <TimeWarper.h>
Public Member Functions
virtual ~TimeWarper ()
virtual double Warp (double originalTime) const =0
Detailed Description
Transforms one point in time to another point. For example, a time stretching effect might use one to keep track of what happens to labels and split points in the input.
Constructor & Destructor Documentation
virtual TimeWarper::~TimeWarper () [inline, virtual]
Member Function Documentation
virtual double TimeWarper::Warp (double originalTime) const [pure virtual]
Implemented in IdentityTimeWarper, ShiftTimeWarper, LinearTimeWarper, LogarithmicTimeWarper, StepTimeWarper, and RegionTimeWarper.
Referenced by WaveTrack::ClearAndPaste(), RegionTimeWarper::Warp(), ShiftTimeWarper::Warp(), and LabelTrack::WarpLabels().
The documentation for this class was generated from the following file:
TimeWarper.h