Audacity: Lyrics Class Reference
Lyrics Class Reference
#include <Lyrics.h>
Public Member Functions
Lyrics (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
virtual ~Lyrics ()
void Clear ()
void Add (double t, wxString syllable)
void Finish (double finalT)
int FindSyllable (long startChar)
int GetCurrentSyllableIndex ()
Syllable * GetSyllable (int nSyl)
void SetCurrentSyllableIndex (int nSyl)
LyricsStyle GetLyricsStyle ()
void SetLyricsStyle (const LyricsStyle newLyricsStyle)
void Update (double t)
void OnKeyEvent (wxKeyEvent &event)
void OnPaint (wxPaintEvent &evt)
void OnSize (wxSizeEvent &evt)
void HandlePaint (wxDC &dc)
void HandlePaint_BouncingBall (wxDC &dc)
void HandleLayout ()
Private Types
enum LyricsStyle { kBouncingBallLyrics, kHighlightLyrics }
Private Member Functions
unsigned int GetDefaultFontSize () const
void SetDrawnFont (wxDC *dc)
void SetHighlightFont ()
void Measure (wxDC *dc)
int FindSyllable (double t)
void GetKaraokePosition (double t, int *outX, double *outY)
Private Attributes
int mWidth
int mHeight
int mKaraokeHeight
unsigned int mKaraokeFontSize
LyricsStyle mLyricsStyle
HighlightTextCtrl * mHighlightTextCtrl
double mT
int mCurrentSyllable
SyllableArray mSyllables
wxString mText
int mTextHeight
bool mMeasurementsDone
Member Enumeration Documentation
enum Lyrics::LyricsStyle [private]
Enumerator:
kBouncingBallLyrics
kHighlightLyrics
Constructor & Destructor Documentation
Lyrics::Lyrics (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
Lyrics::~Lyrics () [virtual]
Member Function Documentation
void Lyrics::Add (double t, wxString syllable)
References mHighlightTextCtrl, mSyllables, and mText.
Referenced by AudacityProject::UpdateLyrics().
void Lyrics::Clear ()
References mHighlightTextCtrl, mSyllables, and mText.
Referenced by AudacityProject::UpdateLyrics().
int Lyrics::FindSyllable (double t) [private]
References mSyllables.
int Lyrics::FindSyllable (long startChar)
References mSyllables.
Referenced by GetKaraokePosition(), HighlightTextCtrl::OnMouseEvent(), and Update().
void Lyrics::Finish (double finalT)
References mCurrentSyllable, mHighlightTextCtrl, mMeasurementsDone, and mSyllables.
Referenced by AudacityProject::UpdateLyrics().
int Lyrics::GetCurrentSyllableIndex () [inline]
References mCurrentSyllable.
Referenced by HighlightTextCtrl::OnMouseEvent().
unsigned int Lyrics::GetDefaultFontSize () const [private]
References kBouncingBallLyrics, and mLyricsStyle.
Referenced by OnSize().
void Lyrics::GetKaraokePosition (double t, int * outX, double * outY) [private]
References FindSyllable(), I_FIRST_REAL_SYLLABLE, M_PI, and mSyllables.
Referenced by HandlePaint_BouncingBall().
LyricsStyle Lyrics::GetLyricsStyle () [inline]
References mLyricsStyle.
Syllable* Lyrics::GetSyllable (int nSyl) [inline]
References mSyllables.
Referenced by HighlightTextCtrl::OnMouseEvent().
void Lyrics::HandleLayout ()
void Lyrics::HandlePaint (wxDC & dc)
References HandlePaint_BouncingBall(), kBouncingBallLyrics, mKaraokeHeight, mLyricsStyle, and mWidth.
Referenced by OnPaint().
void Lyrics::HandlePaint_BouncingBall (wxDC & dc)
References GetKaraokePosition(), mKaraokeHeight, mSyllables, mT, mTextHeight, mWidth, and SetDrawnFont().
Referenced by HandlePaint().
void Lyrics::Measure (wxDC * dc) [private]
References I_FIRST_REAL_SYLLABLE, mMeasurementsDone, mSyllables, mTextHeight, and SetDrawnFont().
Referenced by OnPaint().
void Lyrics::OnKeyEvent (wxKeyEvent & event)
References GetActiveProject(), and AudacityProject::HandleKeyDown().
void Lyrics::OnPaint (wxPaintEvent & evt)
References HandlePaint(), kBouncingBallLyrics, Measure(), mKaraokeHeight, mLyricsStyle, mMeasurementsDone, and mWidth.
Referenced by OnSize().
void Lyrics::OnSize (wxSizeEvent & evt)
References GetDefaultFontSize(), kBouncingBallLyrics, LYRICS_DEFAULT_HEIGHT, mHeight, mHighlightTextCtrl, mKaraokeFontSize, mKaraokeHeight, mLyricsStyle, mMeasurementsDone, mWidth, OnPaint(), and SetHighlightFont().
Referenced by SetLyricsStyle().
void Lyrics::SetCurrentSyllableIndex (int nSyl) [inline]
References mCurrentSyllable.
void Lyrics::SetDrawnFont (wxDC * dc) [private]
References mKaraokeFontSize.
Referenced by HandlePaint_BouncingBall(), and Measure().
void Lyrics::SetHighlightFont () [private]
References mHighlightTextCtrl, and mKaraokeFontSize.
Referenced by OnSize().
void Lyrics::SetLyricsStyle (const LyricsStyle newLyricsStyle)
References kHighlightLyrics, mHighlightTextCtrl, mLyricsStyle, and OnSize().
Referenced by LyricsWindow::OnStyle_BouncingBall(), and LyricsWindow::OnStyle_Highlight().
void Lyrics::Update (double t)
References FindSyllable(), GetActiveProject(), AudacityProject::GetSel0(), kBouncingBallLyrics, kHighlightLyrics, mCurrentSyllable, mHighlightTextCtrl, mKaraokeHeight, mLyricsStyle, mSyllables, mT, and mWidth.
Referenced by TrackPanel::HandleSelect(), TrackPanel::OnTimer(), and AudacityProject::UpdateLyrics().
Member Data Documentation
int Lyrics::mCurrentSyllable [private]
Referenced by Finish(), GetCurrentSyllableIndex(), SetCurrentSyllableIndex(), and Update().
int Lyrics::mHeight [private]
Referenced by OnSize().
HighlightTextCtrl* Lyrics::mHighlightTextCtrl [private]
Referenced by Add(), Clear(), Finish(), OnSize(), SetHighlightFont(), SetLyricsStyle(), and Update().
unsigned int Lyrics::mKaraokeFontSize [private]
Referenced by OnSize(), SetDrawnFont(), and SetHighlightFont().
int Lyrics::mKaraokeHeight [private]
Referenced by HandlePaint(), HandlePaint_BouncingBall(), OnPaint(), OnSize(), and Update().
LyricsStyle Lyrics::mLyricsStyle [private]
Referenced by GetDefaultFontSize(), GetLyricsStyle(), HandlePaint(), OnPaint(), OnSize(), SetLyricsStyle(), and Update().
bool Lyrics::mMeasurementsDone [private]
Referenced by Finish(), Measure(), OnPaint(), and OnSize().
SyllableArray Lyrics::mSyllables [private]
Referenced by Add(), Clear(), FindSyllable(), Finish(), GetKaraokePosition(), GetSyllable(), HandlePaint_BouncingBall(), Measure(), and Update().
double Lyrics::mT [private]
Referenced by HandlePaint_BouncingBall(), and Update().
wxString Lyrics::mText [private]
Referenced by Add(), and Clear().
int Lyrics::mTextHeight [private]
Referenced by HandlePaint_BouncingBall(), and Measure().
int Lyrics::mWidth [private]
Referenced by HandlePaint(), HandlePaint_BouncingBall(), OnPaint(), OnSize(), and Update().
The documentation for this class was generated from the following files:
Lyrics.h
Lyrics.cpp