Audacity: ODDecodeTask Class Reference
ODDecodeTask Class Reference
A class representing a modular task to be used with the On-Demand structures.
#include <ODDecodeTask.h>
Public Member Functions
ODDecodeTask ()
Constructs an ODTask.
virtual ~ODDecodeTask ()
virtual ODTask * Clone ()=0
virtual const char * GetTaskName ()
Return the task name.
virtual const wxChar * GetTip ()
virtual unsigned int GetODType ()
Subclasses should override to return respective type.
virtual ODFileDecoder * CreateFileDecoder (const wxString &fileName)=0
Creates an ODFileDecoder that decodes a file of filetype the subclass handles.
virtual ODFileDecoder * GetOrCreateMatchingFileDecoder (ODDecodeBlockFile *blockFile)
virtual int GetNumFileDecoders ()
Protected Member Functions
virtual void CalculatePercentComplete ()
recalculates the percentage complete.
virtual void DoSomeInternal ()
Computes and writes the data for one BlockFile if it still has a refcount.
virtual void Update ()
by default creates the order of the wavetrack to load.
virtual void ODUpdate ()
Readjusts the blockfile order to start at the new cursor.
void OrderBlockFiles (std::vector< ODDecodeBlockFile * > &unorderedBlocks)
Orders the input as either On-Demand or default layered order.
Protected Attributes
std::vector< ODDecodeBlockFile * > mBlockFiles
std::vector< ODFileDecoder * > mDecoders
int mMaxBlockFiles
int mComputedBlockFiles
Detailed Description
A class representing a modular task to be used with the On-Demand structures.
Decodes a file into a simpleBlockFile, but not immediately.
This is an abstract class that subclasses will have to derive the types from. For any type there should only be one ODDecodeTask associated with a given track. There could be the ODBlockFiles of several FLACs in one track (after copy and pasting), so things aren't as simple as they seem - the implementation needs to be robust enough to allow all the user changes such as copy/paste, delete, and so on.
Constructor & Destructor Documentation
ODDecodeTask::ODDecodeTask ()
Constructs an ODTask.
Creates a new task that computes summaries for a wavetrack that needs to be specified through SetWaveTrack().
References mComputedBlockFiles, and mMaxBlockFiles.
virtual ODDecodeTask::~ODDecodeTask () [inline, virtual]
Member Function Documentation
void ODDecodeTask::CalculatePercentComplete () [protected, virtual]
recalculates the percentage complete.
Implements ODTask.
References mBlockFiles, mMaxBlockFiles, ODTask::mPercentComplete, and ODTask::mPercentCompleteMutex.
Referenced by DoSomeInternal().
virtual ODTask* ODDecodeTask::Clone () [pure virtual]
Implements ODTask.
Implemented in ODDecodeFlacTask.
virtual ODFileDecoder* ODDecodeTask::CreateFileDecoder (const wxString & fileName) [pure virtual]
Creates an ODFileDecoder that decodes a file of filetype the subclass handles.
Implemented in ODDecodeFlacTask.
Referenced by GetOrCreateMatchingFileDecoder().
void ODDecodeTask::DoSomeInternal () [protected, virtual]
Computes and writes the data for one BlockFile if it still has a refcount.
Implements ODTask.
References CalculatePercentComplete(), ODDecodeBlockFile::DoWriteBlockFile(), BlockFile::GetLength(), GetOrCreateMatchingFileDecoder(), ODDecodeBlockFile::GetStart(), ODFileDecoder::Init(), ODFileDecoder::IsInitialized(), ODDecodeBlockFile::LockRead(), mBlockFiles, mComputedBlockFiles, mMaxBlockFiles, ODTask::mPercentComplete, ODTask::mPercentCompleteMutex, ODTask::mWaveTrackMutex, ODTask::mWaveTracks, ODDecodeBlockFile::SetODFileDecoder(), and ODDecodeBlockFile::UnlockRead().
int ODDecodeTask::GetNumFileDecoders () [virtual]
References mDecoders.
virtual unsigned int ODDecodeTask::GetODType () [inline, virtual]
Subclasses should override to return respective type.
Reimplemented from ODTask.
Reimplemented in ODDecodeFlacTask.
References ODTask::eODNone.
Referenced by Update().
ODFileDecoder * ODDecodeTask::GetOrCreateMatchingFileDecoder (ODDecodeBlockFile * blockFile) [virtual]
there could be the ODBlockFiles of several FLACs in one track (after copy and pasting) so we keep a list of decoders that keep track of the file names, etc, and check the blocks against them. Blocks that have IsDataAvailable()==false are blockfiles to be decoded. if BlockFile::GetDecodeType()==ODDecodeTaskGetODType() then this decoder should handle it. Decoders are accessible with the methods below. These aren't thread-safe and should only be called from the decoding thread.
References CreateFileDecoder(), ODDecodeBlockFile::GetAudioFileName(), and mDecoders.
Referenced by DoSomeInternal().
virtual const char* ODDecodeTask::GetTaskName () [inline, virtual]
Return the task name.
Reimplemented from ODTask.
virtual const wxChar* ODDecodeTask::GetTip () [inline, virtual]
Implements ODTask.
void ODDecodeTask::ODUpdate () [protected, virtual]
Readjusts the blockfile order to start at the new cursor.
Reimplemented from ODTask.
void ODDecodeTask::OrderBlockFiles (std::vector< ODDecodeBlockFile * > & unorderedBlocks) [protected]
Orders the input as either On-Demand or default layered order.
References ODTask::GetDemandSample(), mBlockFiles, and mMaxBlockFiles.
Referenced by Update().
void ODDecodeTask::Update () [protected, virtual]
by default creates the order of the wavetrack to load.
Readjusts the blockfile order in the default manner. If we have had an ODRequest Then it updates in the OD manner.
Reimplemented from ODTask.
References GetODType(), WaveClip::GetRate(), WaveClip::GetSequence(), WaveClip::GetSequenceBlockArray(), WaveClip::GetStartTime(), Sequence::LockDeleteUpdateMutex(), ODTask::mWaveTrackMutex, ODTask::mWaveTracks, OrderBlockFiles(), and Sequence::UnlockDeleteUpdateMutex().
Member Data Documentation
std::vector<ODDecodeBlockFile*> ODDecodeTask::mBlockFiles [protected]
Referenced by CalculatePercentComplete(), DoSomeInternal(), and OrderBlockFiles().
int ODDecodeTask::mComputedBlockFiles [protected]
Referenced by DoSomeInternal(), and ODDecodeTask().
std::vector<ODFileDecoder*> ODDecodeTask::mDecoders [protected]
Referenced by ODDecodeFlacTask::CreateFileDecoder(), GetNumFileDecoders(), and GetOrCreateMatchingFileDecoder().
int ODDecodeTask::mMaxBlockFiles [protected]
Referenced by CalculatePercentComplete(), DoSomeInternal(), ODDecodeTask(), and OrderBlockFiles().
The documentation for this class was generated from the following files:
ODDecodeTask.h
ODDecodeTask.cpp