Audacity: ChoiceEditor::FocusHandler Class Reference
ChoiceEditor::FocusHandler Class Reference
Public Member Functions
void ConnectEvent (wxWindow *w)
void DisconnectEvent (wxWindow *w)
void OnKillFocus (wxFocusEvent &event)
Member Function Documentation
void ChoiceEditor::FocusHandler::ConnectEvent (wxWindow * w) [inline]
References OnKillFocus().
Referenced by ChoiceEditor::Create().
void ChoiceEditor::FocusHandler::DisconnectEvent (wxWindow * w) [inline]
References OnKillFocus().
Referenced by ChoiceEditor::~ChoiceEditor().
void ChoiceEditor::FocusHandler::OnKillFocus (wxFocusEvent & event) [inline]
Referenced by ConnectEvent(), and DisconnectEvent().
The documentation for this class was generated from the following file:
Grid.h