Audacity: CompressorPanel Class Reference
CompressorPanel Class Reference
Panel used within the CompressorDialog for EffectCompressor.
#include <Compressor.h>
Public Member Functions
CompressorPanel (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
void OnPaint (wxPaintEvent &event)
Public Attributes
double threshold
double noisefloor
double ratio
Private Attributes
wxBitmap * mBitmap
wxRect mEnvRect
int mWidth
int mHeight
Detailed Description
Panel used within the CompressorDialog for EffectCompressor.
Constructor & Destructor Documentation
CompressorPanel::CompressorPanel (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
Member Function Documentation
void CompressorPanel::OnPaint (wxPaintEvent & event)
References Ruler::Draw(), Ruler::GetMaxSize(), AColor::Line(), Ruler::LinearDBFormat, mBitmap, mEnvRect, mHeight, mWidth, ratio, Ruler::SetBounds(), Ruler::SetFlip(), Ruler::SetFormat(), Ruler::SetOrientation(), Ruler::SetRange(), Ruler::SetUnits(), threshold, and AColor::WideEnvelopePen.
Member Data Documentation
wxBitmap* CompressorPanel::mBitmap [private]
Referenced by OnPaint().
wxRect CompressorPanel::mEnvRect [private]
Referenced by OnPaint().
int CompressorPanel::mHeight [private]
Referenced by OnPaint().
int CompressorPanel::mWidth [private]
Referenced by OnPaint().
double CompressorPanel::noisefloor
Referenced by CompressorDialog::PopulateOrExchange(), CompressorDialog::TransferDataFromWindow(), and CompressorDialog::TransferDataToWindow().
double CompressorPanel::ratio
Referenced by OnPaint(), CompressorDialog::PopulateOrExchange(), CompressorDialog::TransferDataFromWindow(), and CompressorDialog::TransferDataToWindow().
double CompressorPanel::threshold
Referenced by OnPaint(), CompressorDialog::PopulateOrExchange(), CompressorDialog::TransferDataFromWindow(), and CompressorDialog::TransferDataToWindow().
The documentation for this class was generated from the following files:
Compressor.h
Compressor.cpp