Audacity: PCMImportFileHandle Class Reference
PCMImportFileHandle Class Reference
An ImportFileHandle for PCM data.
Public Member Functions
PCMImportFileHandle (wxString name, SNDFILE *file, SF_INFO info)
~PCMImportFileHandle ()
wxString GetFileDescription ()
int GetFileUncompressedBytes ()
int Import (TrackFactory *trackFactory, Track ***outTracks, int *outNumTracks, Tags *tags)
wxInt32 GetStreamCount ()
wxArrayString * GetStreamInfo ()
void SetStreamUsage (wxInt32 StreamID, bool Use)
Private Attributes
SNDFILE * mFile
SF_INFO mInfo
sampleFormat mFormat
Detailed Description
An ImportFileHandle for PCM data.
Constructor & Destructor Documentation
PCMImportFileHandle::PCMImportFileHandle (wxString name, SNDFILE * file, SF_INFO info)
References floatSample, gPrefs, mFormat, mInfo, and sf_subtype_more_than_16_bits().
PCMImportFileHandle::~PCMImportFileHandle ()
References mFile.
Member Function Documentation
wxString PCMImportFileHandle::GetFileDescription () [virtual]
Implements ImportFileHandle.
References mInfo, and sf_header_name().
int PCMImportFileHandle::GetFileUncompressedBytes () [virtual]
Implements ImportFileHandle.
References mFormat, mInfo, and SAMPLE_SIZE.
wxInt32 PCMImportFileHandle::GetStreamCount () [inline, virtual]
Implements ImportFileHandle.
wxArrayString* PCMImportFileHandle::GetStreamInfo () [inline, virtual]
Implements ImportFileHandle.
int PCMImportFileHandle::Import (TrackFactory * trackFactory, Track *** outTracks, int * outNumTracks, Tags * tags) [virtual]
Implements ImportFileHandle.
References ODManager::AddNewTask(), ODTask::AddWaveTrack(), WaveTrack::Append(), channels, ImportFileHandle::CreateProgress(), DeleteSamples(), eProgressCancelled, eProgressFailed, eProgressSuccess, floatSample, WaveTrack::Flush(), Tags::GetGenre(), WaveTrack::GetMaxBlockSize(), Tags::GetTag(), gPrefs, Tags::HasTag(), ODManager::Instance(), int16Sample, kMinimumODFileSampleSize, Track::LeftChannel, mFile, ImportFileHandle::mFilename, mFormat, mInfo, Track::MonoChannel, ImportFileHandle::mProgress, NewSamples(), TrackFactory::NewWaveTrack(), Track::RightChannel, Track::SetChannel(), Tags::SetID3V2(), Track::SetLinked(), Tags::SetTag(), TAG_ALBUM, TAG_ARTIST, TAG_COMMENTS, TAG_GENRE, TAG_TITLE, TAG_TRACK, TAG_YEAR, ProgressDialog::Update(), and UTF8CTOWX.
void PCMImportFileHandle::SetStreamUsage (wxInt32 StreamID, bool Use) [inline, virtual]
Implements ImportFileHandle.
Member Data Documentation
SNDFILE* PCMImportFileHandle::mFile [private]
Referenced by Import(), and ~PCMImportFileHandle().
sampleFormat PCMImportFileHandle::mFormat [private]
Referenced by GetFileUncompressedBytes(), Import(), and PCMImportFileHandle().
SF_INFO PCMImportFileHandle::mInfo [private]
Referenced by GetFileDescription(), GetFileUncompressedBytes(), Import(), and PCMImportFileHandle().
The documentation for this class was generated from the following file:
ImportPCM.cpp