Audacity: TrackFactory Class Reference
TrackFactory Class Reference
Used to create a WaveTrack, or a LabelTrack.. Implementation of the functions of this class are dispersed through the different Track classes.
#include <Track.h>
Public Member Functions
WaveTrack * DuplicateWaveTrack (WaveTrack &orig)
WaveTrack * NewWaveTrack (sampleFormat format=(sampleFormat) 0, double rate=0)
LabelTrack * NewLabelTrack ()
TimeTrack * NewTimeTrack ()
NoteTrack * NewNoteTrack ()
Private Member Functions
TrackFactory (DirManager *dirManager)
Private Attributes
DirManager * mDirManager
Friends
class AudacityProject
class BenchmarkDialog
Detailed Description
Used to create a WaveTrack, or a LabelTrack.. Implementation of the functions of this class are dispersed through the different Track classes.
Constructor & Destructor Documentation
TrackFactory::TrackFactory (DirManager * dirManager) [inline, private]
Member Function Documentation
WaveTrack * TrackFactory::DuplicateWaveTrack (WaveTrack & orig)
References WaveTrack::Duplicate().
Referenced by AudacityProject::SaveCompressedWaveTracks().
LabelTrack * TrackFactory::NewLabelTrack ()
References mDirManager.
Referenced by AudacityProject::HandleXMLChild(), AudacityProject::OnPaste(), VampEffect::Process(), EffectFindClipping::Process(), and EffectNyquist::ProcessOne().
NoteTrack * TrackFactory::NewNoteTrack ()
References mDirManager.
Referenced by AudacityProject::HandleXMLChild(), and AudacityProject::OnPaste().
TimeTrack * TrackFactory::NewTimeTrack ()
References mDirManager.
Referenced by AudacityProject::HandleXMLChild(), and AudacityProject::OnPaste().
WaveTrack * TrackFactory::NewWaveTrack (sampleFormat format = (sampleFormat)0, double rate = 0)
References mDirManager.
Referenced by AudacityProject::HandleXMLChild(), PCMImportFileHandle::Import(), OggImportFileHandle::Import(), FLACImportFileHandle::Import(), FFmpegImportFileHandle::Import(), ImportRaw(), MixAndRender(), AudacityProject::OnEffect(), AudacityProject::OnNewStereoTrack(), AudacityProject::OnNewWaveTrack(), AudacityProject::OnPaste(), ControlToolBar::OnRecord(), BenchmarkDialog::OnRun(), output_cb(), EffectStereoToMono::Process(), EffectSBSMS::Process(), Generator::Process(), EffectSoundTouch::ProcessOne(), EffectNyquist::ProcessOne(), EffectNoiseRemoval::ProcessOne(), EffectEqualization::ProcessOne(), EffectChangeSpeed::ProcessOne(), EffectSoundTouch::ProcessStereo(), and WaveTrack::SyncAdjust().
Friends And Related Function Documentation
friend class AudacityProject [friend]
friend class BenchmarkDialog [friend]
Member Data Documentation
DirManager* TrackFactory::mDirManager [private]
Referenced by NewLabelTrack(), NewNoteTrack(), NewTimeTrack(), and NewWaveTrack().
The documentation for this class was generated from the following files:
Track.h
LabelTrack.cpp
NoteTrack.cpp
TimeTrack.cpp
WaveTrack.cpp