Audacity: LOFImportFileHandle Class Reference
LOFImportFileHandle Class Reference
An ImportFileHandle for LOF data.
Public Member Functions
LOFImportFileHandle (const wxString &name, wxTextFile *file)
~LOFImportFileHandle ()
wxString GetFileDescription ()
int GetFileUncompressedBytes ()
int Import (TrackFactory *trackFactory, Track ***outTracks, int *outNumTracks, Tags *tags)
wxInt32 GetStreamCount ()
wxArrayString * GetStreamInfo ()
void SetStreamUsage (wxInt32 StreamID, bool Use)
Private Member Functions
void lofOpenFiles (wxString *ln)
Processes a single line from a LOF text file, doing whatever is indicated on the line.
void doDuration ()
void doScrollOffset ()
Private Attributes
wxTextFile * mTextFile
wxFileName * mLOFFileName
AudacityProject * mProject
bool windowCalledOnce
bool callDurationFactor
double durationFactor
bool callScrollOffset
double scrollOffset
Detailed Description
An ImportFileHandle for LOF data.
Supports the opening of ".lof" files which are text files that contain a list of individual files to open in audacity in specific formats. Files may be file names (in the same directory as the LOF file), absolute paths or relative paths relative to the directory of the LOF file.
(In BNF) The syntax for an LOF file, denoted by <lof>:
  <lof> ::= [<window> | <file> | <#>]*
  <window> ::= window [<window-parameter>]* <newline>
  <window-parameter> ::= offset <time> | duration <time>
  <time> ::= [<digit>]+ [ . [<digit>]* ]
  <file> ::= file [<file-parameter>]* <newline>
  <file-parameter> ::= offset <time>
  <#> ::= <comment> <newline>
EXAMPLE LOF file:
  # everything following the hash character is ignored
  window # an initial window command is implicit and optional
  file "C:\folder1\sample1.wav"    # sample1.wav is displayed
  file "C:\sample2.wav" offset 5   # sample2 is displayed with a 5s offset
  File "C:\sample3.wav"            # sample3 is displayed with no offset
  File "foo.aiff" # foo is loaded from the same directory as the LOF file
  window offset 5 duration 10      # open a new window, zoom to display
  # 10 seconds total starting at 5 (ending at 15) seconds
  file "C:\sample3.wav" offset 2.5
SEMANTICS:
There are two commands: "window" creates a new window, and "file" appends a track to the current window and displays the file there. The first file is always placed in a new window, whether or not an initial "window" command is given.
Commands have optional keyword parameters that may be listed in any order. A parameter should only occur once per command. The "offset" parameter specifies a time offset. For windows, this is the leftmost time displayed in the window. For files, the offset is an amount by which the file is shifted in time before display (only enabled for audio; not midi). The offset is specified as an integer or decimal number of seconds, and the default value is zero.
Windows may also have a "duration" parameter, which specifies how much time should be displayed in the window. The default duration is equal to the duration of the longest track currently displayed.
Constructor & Destructor Documentation
LOFImportFileHandle::LOFImportFileHandle (const wxString & name, wxTextFile * file)
References callDurationFactor, callScrollOffset, durationFactor, GetActiveProject(), mLOFFileName, mProject, scrollOffset, and windowCalledOnce.
LOFImportFileHandle::~LOFImportFileHandle ()
References mLOFFileName, and mTextFile.
Member Function Documentation
void LOFImportFileHandle::doDuration () [private]
References callDurationFactor, durationFactor, TrackList::GetEndTime(), AudacityProject::GetTracks(), AudacityProject::GetZoom(), mProject, and AudacityProject::Zoom().
Referenced by Import(), and lofOpenFiles().
void LOFImportFileHandle::doScrollOffset () [private]
References callScrollOffset, mProject, scrollOffset, and AudacityProject::TP_ScrollWindow().
Referenced by Import(), and lofOpenFiles().
wxString LOFImportFileHandle::GetFileDescription () [virtual]
Implements ImportFileHandle.
References DESC.
int LOFImportFileHandle::GetFileUncompressedBytes () [virtual]
Implements ImportFileHandle.
wxInt32 LOFImportFileHandle::GetStreamCount () [inline, virtual]
Implements ImportFileHandle.
wxArrayString* LOFImportFileHandle::GetStreamInfo () [inline, virtual]
Implements ImportFileHandle.
int LOFImportFileHandle::Import (TrackFactory * trackFactory, Track *** outTracks, int * outNumTracks, Tags * tags) [virtual]
Implements ImportFileHandle.
References doDuration(), doScrollOffset(), eProgressFailed, eProgressSuccess, lofOpenFiles(), and mTextFile.
void LOFImportFileHandle::lofOpenFiles (wxString * ln) [private]
Processes a single line from a LOF text file, doing whatever is indicated on the line.
This function should just return for lines it cannot deal with, and the caller will continue to the next line of the input file
References TrackList::Add(), callDurationFactor, callScrollOffset, Internat::CompatibleToDouble(), CountNumTracks(), CreateNewAudacityProject(), doDuration(), doScrollOffset(), durationFactor, AudacityProject::GetDirManager(), AudacityProject::GetTracks(), ImportMIDI(), mLOFFileName, mProject, AudacityProject::OpenFile(), scrollOffset, and windowCalledOnce.
Referenced by Import().
void LOFImportFileHandle::SetStreamUsage (wxInt32 StreamID, bool Use) [inline, virtual]
Implements ImportFileHandle.
Member Data Documentation
bool LOFImportFileHandle::callDurationFactor [private]
Referenced by doDuration(), LOFImportFileHandle(), and lofOpenFiles().
bool LOFImportFileHandle::callScrollOffset [private]
Referenced by doScrollOffset(), LOFImportFileHandle(), and lofOpenFiles().
double LOFImportFileHandle::durationFactor [private]
Referenced by doDuration(), LOFImportFileHandle(), and lofOpenFiles().
wxFileName* LOFImportFileHandle::mLOFFileName [private]
The name of the LOF file, which is used to interpret relative paths in it
Referenced by LOFImportFileHandle(), lofOpenFiles(), and ~LOFImportFileHandle().
AudacityProject* LOFImportFileHandle::mProject [private]
Referenced by doDuration(), doScrollOffset(), LOFImportFileHandle(), and lofOpenFiles().
wxTextFile* LOFImportFileHandle::mTextFile [private]
Referenced by Import(), and ~LOFImportFileHandle().
double LOFImportFileHandle::scrollOffset [private]
Referenced by doScrollOffset(), LOFImportFileHandle(), and lofOpenFiles().
bool LOFImportFileHandle::windowCalledOnce [private]
Referenced by LOFImportFileHandle(), and lofOpenFiles().
The documentation for this class was generated from the following file:
ImportLOF.cpp