Audacity: ContrastDialog Class Reference
ContrastDialog Class Reference
#include <Contrast.h>
Public Member Functions
ContrastDialog (wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos)
~ContrastDialog ()
void OnGetForegroundDB (wxCommandEvent &event)
void OnGetBackgroundDB (wxCommandEvent &event)
Public Attributes
wxButton * m_pButton_UseCurrentF
wxButton * m_pButton_UseCurrentB
wxButton * m_pButton_GetURL
wxButton * m_pButton_Export
wxButton * m_pButton_Reset
wxButton * m_pButton_Close
TimeTextCtrl * mForegroundStartT
TimeTextCtrl * mForegroundEndT
TimeTextCtrl * mBackgroundStartT
TimeTextCtrl * mBackgroundEndT
bool bFGset
bool bBGset
double mT0
double mT1
double mProjectRate
double mStartTimeF
double mEndTimeF
double mStartTimeB
double mEndTimeB
Private Member Functions
void OnGetURL (wxCommandEvent &event)
void OnExport (wxCommandEvent &event)
void OnForegroundStartT (wxCommandEvent &event)
void OnForegroundEndT (wxCommandEvent &event)
void OnUseSelectionF (wxCommandEvent &event)
void OnUseSelectionB (wxCommandEvent &event)
void results ()
void OnReset (wxCommandEvent &event)
void OnClose (wxCommandEvent &event)
void OnChar (wxKeyEvent &event)
float GetDB ()
double GetStartTime ()
void SetStartTime (double)
double GetEndTime ()
void SetEndTime (double)
Private Attributes
wxTextCtrl * mForegroundRMSText
wxTextCtrl * mBackgroundRMSText
wxTextCtrl * mPassFailText
wxTextCtrl * mDiffText
float foregrounddB
float backgrounddB
double mT0orig
double mT1orig
bool mDoBackground
double length
Constructor & Destructor Documentation
ContrastDialog::ContrastDialog (wxWindow * parent, wxWindowID id, const wxString & title, const wxPoint & pos)
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddFixedText(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::AddWindow(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), GetActiveProject(), AudacityProject::GetRate(), ShuttleGui::Id(), ID_BACKGROUNDDB_TEXT, ID_BACKGROUNDEND_T, ID_BACKGROUNDSTART_T, ID_FOREGROUNDDB_TEXT, ID_FOREGROUNDEND_T, ID_FOREGROUNDSTART_T, ID_RESULTS_TEXT, ID_RESULTSDB_TEXT, OnChar(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), and ShuttleGuiBase::StartStatic().
ContrastDialog::~ContrastDialog ()
References mBackgroundRMSText, mDiffText, mForegroundRMSText, mPassFailText, and OnChar().
Member Function Documentation
float ContrastDialog::GetDB () [private]
References GetActiveProject(), GetStartTime(), AudacityProject::GetTracks(), mT0, and mT1.
Referenced by OnGetBackgroundDB(), and OnGetForegroundDB().
double ContrastDialog::GetEndTime () [private]
References mT1.
double ContrastDialog::GetStartTime () [private]
References mT0.
Referenced by GetDB().
void ContrastDialog::OnChar (wxKeyEvent & event) [private]
Referenced by ContrastDialog(), and ~ContrastDialog().
void ContrastDialog::OnClose (wxCommandEvent & event) [private]
void ContrastDialog::OnExport (wxCommandEvent & event) [private]
References backgrounddB, foregrounddB, GetActiveProject(), AudacityProject::GetFileName(), TimeTextCtrl::GetTimeValue(), mBackgroundEndT, mBackgroundStartT, mForegroundEndT, and mForegroundStartT.
void ContrastDialog::OnForegroundEndT (wxCommandEvent & event) [private]
void ContrastDialog::OnForegroundStartT (wxCommandEvent & event) [private]
void ContrastDialog::OnGetBackgroundDB (wxCommandEvent & event)
References backgrounddB, GetDB(), TimeTextCtrl::GetTimeValue(), m_pButton_UseCurrentB, mBackgroundEndT, mBackgroundStartT, results(), SetEndTime(), and SetStartTime().
Referenced by OnReset(), and OnUseSelectionB().
void ContrastDialog::OnGetForegroundDB (wxCommandEvent & event)
References foregrounddB, GetDB(), TimeTextCtrl::GetTimeValue(), m_pButton_UseCurrentF, mForegroundEndT, mForegroundStartT, results(), SetEndTime(), and SetStartTime().
Referenced by OnReset(), and OnUseSelectionF().
void ContrastDialog::OnGetURL (wxCommandEvent & event) [private]
References OpenInDefaultBrowser().
void ContrastDialog::OnReset (wxCommandEvent & event) [private]
References bBGset, bFGset, mBackgroundEndT, mBackgroundStartT, mForegroundEndT, mForegroundStartT, OnGetBackgroundDB(), OnGetForegroundDB(), results(), and TimeTextCtrl::SetTimeValue().
void ContrastDialog::OnUseSelectionB (wxCommandEvent & event) [private]
References bBGset, GetActiveProject(), AudacityProject::GetTracks(), mBackgroundEndT, mBackgroundStartT, AudacityProject::mViewInfo, OnGetBackgroundDB(), ViewInfo::sel0, ViewInfo::sel1, TimeTextCtrl::SetTimeValue(), and Track::Wave.
void ContrastDialog::OnUseSelectionF (wxCommandEvent & event) [private]
References bFGset, GetActiveProject(), AudacityProject::GetTracks(), mForegroundEndT, mForegroundStartT, AudacityProject::mViewInfo, OnGetForegroundDB(), ViewInfo::sel0, ViewInfo::sel1, TimeTextCtrl::SetTimeValue(), and Track::Wave.
void ContrastDialog::results () [private]
References backgrounddB, foregrounddB, mBackgroundRMSText, mDiffText, mForegroundRMSText, and mPassFailText.
Referenced by OnGetBackgroundDB(), OnGetForegroundDB(), and OnReset().
void ContrastDialog::SetEndTime (double t) [private]
References mT1.
Referenced by OnGetBackgroundDB(), and OnGetForegroundDB().
void ContrastDialog::SetStartTime (double t) [private]
References mT0.
Referenced by OnGetBackgroundDB(), and OnGetForegroundDB().
Member Data Documentation
float ContrastDialog::backgrounddB [private]
Referenced by OnExport(), OnGetBackgroundDB(), and results().
bool ContrastDialog::bBGset
Referenced by InitContrastDialog(), OnReset(), and OnUseSelectionB().
bool ContrastDialog::bFGset
Referenced by InitContrastDialog(), OnReset(), and OnUseSelectionF().
float ContrastDialog::foregrounddB [private]
Referenced by OnExport(), OnGetForegroundDB(), and results().
double ContrastDialog::length [private]
wxButton* ContrastDialog::m_pButton_Close
wxButton* ContrastDialog::m_pButton_Export
wxButton* ContrastDialog::m_pButton_GetURL
wxButton* ContrastDialog::m_pButton_Reset
wxButton* ContrastDialog::m_pButton_UseCurrentB
Referenced by OnGetBackgroundDB().
wxButton* ContrastDialog::m_pButton_UseCurrentF
Referenced by OnGetForegroundDB().
TimeTextCtrl* ContrastDialog::mBackgroundEndT
Referenced by InitContrastDialog(), OnExport(), OnGetBackgroundDB(), OnReset(), and OnUseSelectionB().
wxTextCtrl* ContrastDialog::mBackgroundRMSText [private]
Referenced by results(), and ~ContrastDialog().
TimeTextCtrl* ContrastDialog::mBackgroundStartT
Referenced by InitContrastDialog(), OnExport(), OnGetBackgroundDB(), OnReset(), and OnUseSelectionB().
wxTextCtrl* ContrastDialog::mDiffText [private]
Referenced by results(), and ~ContrastDialog().
bool ContrastDialog::mDoBackground [private]
double ContrastDialog::mEndTimeB
double ContrastDialog::mEndTimeF
TimeTextCtrl* ContrastDialog::mForegroundEndT
Referenced by InitContrastDialog(), OnExport(), OnGetForegroundDB(), OnReset(), and OnUseSelectionF().
wxTextCtrl* ContrastDialog::mForegroundRMSText [private]
Referenced by results(), and ~ContrastDialog().
TimeTextCtrl* ContrastDialog::mForegroundStartT
Referenced by InitContrastDialog(), OnExport(), OnGetForegroundDB(), OnReset(), and OnUseSelectionF().
wxTextCtrl* ContrastDialog::mPassFailText [private]
Referenced by results(), and ~ContrastDialog().
double ContrastDialog::mProjectRate
double ContrastDialog::mStartTimeB
double ContrastDialog::mStartTimeF
double ContrastDialog::mT0
Referenced by GetDB(), GetStartTime(), and SetStartTime().
double ContrastDialog::mT0orig [private]
double ContrastDialog::mT1
Referenced by GetDB(), GetEndTime(), and SetEndTime().
double ContrastDialog::mT1orig [private]
The documentation for this class was generated from the following files:
Contrast.h
Contrast.cpp