Audacity: MP3ImportFileHandle Class Reference
MP3ImportFileHandle Class Reference
An ImportFileHandle for MP3 data.
Public Member Functions
MP3ImportFileHandle (wxFile *file, wxString filename)
~MP3ImportFileHandle ()
wxString GetFileDescription ()
int GetFileUncompressedBytes ()
int Import (TrackFactory *trackFactory, Track ***outTracks, int *outNumTracks, Tags *tags)
wxInt32 GetStreamCount ()
wxArrayString * GetStreamInfo ()
void SetStreamUsage (wxInt32 StreamID, bool Use)
Private Member Functions
void ImportID3 (Tags *tags)
Private Attributes
wxFile * mFile
void * mUserData
struct private_data mPrivateData
mad_decoder mDecoder
Detailed Description
An ImportFileHandle for MP3 data.
Audacity has finally moved to using a single mp3 library on all platforms! It is the high performance, beautifully written libmad (mpeg audio decoder). Finally there is harmony in the mp3 universe.
Much of this source code is based on 'minimad.c' as distributed with libmad.
Constructor & Destructor Documentation
MP3ImportFileHandle::MP3ImportFileHandle (wxFile * file, wxString filename) [inline]
MP3ImportFileHandle::~MP3ImportFileHandle ()
References mFile.
Member Function Documentation
wxString MP3ImportFileHandle::GetFileDescription () [virtual]
Implements ImportFileHandle.
References DESC.
int MP3ImportFileHandle::GetFileUncompressedBytes () [virtual]
Implements ImportFileHandle.
wxInt32 MP3ImportFileHandle::GetStreamCount () [inline, virtual]
Implements ImportFileHandle.
wxArrayString* MP3ImportFileHandle::GetStreamInfo () [inline, virtual]
Implements ImportFileHandle.
int MP3ImportFileHandle::Import (TrackFactory * trackFactory, Track *** outTracks, int * outNumTracks, Tags * tags) [virtual]
Implements ImportFileHandle.
References private_data::channels, ImportFileHandle::CreateProgress(), eProgressCancelled, eProgressFailed, eProgressSuccess, error_cb(), private_data::file, WaveTrack::Flush(), private_data::id3checked, ImportID3(), INPUT_BUFFER_SIZE, input_cb(), private_data::inputBuffer, mad_decoder_finish(), mad_decoder_init(), MAD_DECODER_MODE_SYNC, mad_decoder_run(), mDecoder, mFile, mPrivateData, ImportFileHandle::mProgress, private_data::numChannels, output_cb(), private_data::progress, private_data::trackFactory, and private_data::updateResult.
void MP3ImportFileHandle::ImportID3 (Tags * tags) [private]
References Tags::Clear(), Tags::GetGenre(), Tags::GetTag(), Tags::HasTag(), ImportFileHandle::mFilename, Tags::SetID3V2(), Tags::SetTag(), TAG_ALBUM, TAG_ARTIST, TAG_COMMENTS, TAG_GENRE, TAG_TITLE, TAG_TRACK, TAG_YEAR, and UTF8CTOWX.
Referenced by Import().
void MP3ImportFileHandle::SetStreamUsage (wxInt32 StreamID, bool Use) [inline, virtual]
Implements ImportFileHandle.
Member Data Documentation
mad_decoder MP3ImportFileHandle::mDecoder [private]
Referenced by Import().
wxFile* MP3ImportFileHandle::mFile [private]
Referenced by Import(), and ~MP3ImportFileHandle().
struct private_data MP3ImportFileHandle::mPrivateData [read, private]
Referenced by Import().
void* MP3ImportFileHandle::mUserData [private]
The documentation for this class was generated from the following file:
ImportMP3.cpp