Audacity: XMLFileReader Class Reference
XMLFileReader Class Reference
Reads a file and passes the results through an XMLTagHandler.
#include <XMLFileReader.h>
Public Member Functions
XMLFileReader ()
virtual ~XMLFileReader ()
bool Parse (XMLTagHandler *baseHandler, const wxString &fname)
wxString GetErrorStr ()
Static Public Member Functions
static void startElement (void *userData, const char *name, const char **atts)
static void endElement (void *userData, const char *name)
static void charHandler (void *userData, const char *s, int len)
Private Attributes
XML_Parser mParser
int mMaxDepth
int mDepth
XMLTagHandler ** mHandler
XMLTagHandler * mBaseHandler
wxString mErrorStr
Detailed Description
Reads a file and passes the results through an XMLTagHandler.
Constructor & Destructor Documentation
XMLFileReader::XMLFileReader ()
References charHandler(), endElement(), mBaseHandler, mDepth, mErrorStr, mHandler, mMaxDepth, mParser, startElement(), XML_ParserCreate(), XML_SetCharacterDataHandler(), XML_SetElementHandler(), and XML_SetUserData().
XMLFileReader::~XMLFileReader () [virtual]
References mHandler, mParser, and XML_ParserFree().
Member Function Documentation
void XMLFileReader::charHandler (void * userData, const char * s, int len) [static]
References mDepth, mHandler, and XMLTagHandler::ReadXMLContent().
Referenced by XMLFileReader().
void XMLFileReader::endElement (void * userData, const char * name) [static]
References mDepth, mHandler, and XMLTagHandler::ReadXMLEndTag().
Referenced by XMLFileReader().
wxString XMLFileReader::GetErrorStr ()
References mErrorStr.
Referenced by EqualizationDialog::LoadCurves(), TagsEditor::OnLoad(), KeyConfigPrefs::OnLoad(), and AudacityProject::OpenFile().
bool XMLFileReader::Parse (XMLTagHandler * baseHandler, const wxString & fname)
References mBaseHandler, mErrorStr, mHandler, mParser, XML_ErrorString(), XML_GetErrorCode(), and XML_Parse().
Referenced by FFmpegPresets::FFmpegPresets(), FFmpegPresets::ImportPresets(), EqualizationDialog::LoadCurves(), TagsEditor::OnLoad(), KeyConfigPrefs::OnLoad(), and AudacityProject::OpenFile().
void XMLFileReader::startElement (void * userData, const char * name, const char ** atts) [static]
References mBaseHandler, mDepth, mHandler, mMaxDepth, XMLTagHandler::ReadXMLChild(), and XMLTagHandler::ReadXMLTag().
Referenced by XMLFileReader().
Member Data Documentation
XMLTagHandler* XMLFileReader::mBaseHandler [private]
Referenced by Parse(), startElement(), and XMLFileReader().
int XMLFileReader::mDepth [private]
Referenced by charHandler(), endElement(), startElement(), and XMLFileReader().
wxString XMLFileReader::mErrorStr [private]
Referenced by GetErrorStr(), Parse(), and XMLFileReader().
XMLTagHandler** XMLFileReader::mHandler [private]
Referenced by charHandler(), endElement(), Parse(), startElement(), XMLFileReader(), and ~XMLFileReader().
int XMLFileReader::mMaxDepth [private]
Referenced by startElement(), and XMLFileReader().
XML_Parser XMLFileReader::mParser [private]
Referenced by Parse(), XMLFileReader(), and ~XMLFileReader().
The documentation for this class was generated from the following files:
XMLFileReader.h
XMLFileReader.cpp