Audacity: WarningDialog Class Reference
WarningDialog Class Reference
Gives a warning message, that can be dismissed, with crucially the ability to not see similar warnings again for this session.
Public Member Functions
WarningDialog (wxWindow *parent, wxString message)
Private Member Functions
void OnOK (wxCommandEvent &event)
Private Attributes
wxCheckBox * mCheckBox
Detailed Description
Gives a warning message, that can be dismissed, with crucially the ability to not see similar warnings again for this session.
Constructor & Destructor Documentation
WarningDialog::WarningDialog (wxWindow * parent, wxString message)
References ShuttleGuiBase::AddCheckBox(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::AddUnits(), eIsCreating, eOkButton, ShuttleGuiBase::SetBorder(), and ShuttleGuiBase::StartVerticalLay().
Member Function Documentation
void WarningDialog::OnOK (wxCommandEvent & event) [private]
References mCheckBox.
Member Data Documentation
wxCheckBox* WarningDialog::mCheckBox [private]
Referenced by OnOK().
The documentation for this class was generated from the following file:
Warning.cpp