Audacity: AudioUnitEffect Class Reference
AudioUnitEffect Class Reference
An Effect class that handles a wide range of effects. ??Mac only??
#include <AudioUnitEffect.h>
Public Member Functions
AudioUnitEffect (wxString name, Component component)
virtual ~AudioUnitEffect ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool Init ()
virtual bool PromptUser ()
virtual bool Process ()
virtual void End ()
Private Member Functions
bool SetRateAndChannels (AudioUnit unit, int numChannels, Float64 sampleRate)
bool ProcessStereo (int count, WaveTrack *left, WaveTrack *right, sampleCount lstart, sampleCount rstart, sampleCount len)
bool DoRender (AudioUnit unit, int numChannels, float *leftBuffer, float *rightBuffer, int len, int unitBlockSize, AudioTimeStamp *timeStamp, AudioBufferList *bufferList)
bool CopyParameters (AudioUnit srcUnit, AudioUnit dstUnit)
Component GetCarbonViewComponent (OSType subtype)
Static Private Member Functions
static OSStatus SimpleAudioRenderCallback (void *inRefCon, AudioUnitRenderActionFlags *inActionFlags, const AudioTimeStamp *inTimeStamp, UInt32 inBusNumber, UInt32 inNumFrames, AudioBufferList *ioData)
Private Attributes
wxString mName
Component mComponent
AudioUnit mUnit
bool mSupportsMono
bool mSupportsStereo
float * mLeftBufferForCallback
float * mRightBufferForCallback
Detailed Description
An Effect class that handles a wide range of effects. ??Mac only??
Constructor & Destructor Documentation
AudioUnitEffect::AudioUnitEffect (wxString name, Component component)
References mComponent, mUnit, PLUGIN_EFFECT, PROCESS_EFFECT, and Effect::SetEffectFlags().
AudioUnitEffect::~AudioUnitEffect () [virtual]
References mUnit.
Member Function Documentation
bool AudioUnitEffect::CopyParameters (AudioUnit srcUnit, AudioUnit dstUnit) [private]
bool AudioUnitEffect::DoRender (AudioUnit unit, int numChannels, float * leftBuffer, float * rightBuffer, int len, int unitBlockSize, AudioTimeStamp * timeStamp, AudioBufferList * bufferList) [private]
References mLeftBufferForCallback, and mRightBufferForCallback.
Referenced by ProcessStereo().
void AudioUnitEffect::End () [virtual]
Reimplemented from Effect.
Component AudioUnitEffect::GetCarbonViewComponent (OSType subtype) [private]
Referenced by PromptUser().
wxString AudioUnitEffect::GetEffectAction () [virtual]
Implements Effect.
References mName.
std::set< wxString > AudioUnitEffect::GetEffectCategories () [virtual]
wxString AudioUnitEffect::GetEffectIdentifier () [virtual]
Reimplemented from Effect.
References mName.
wxString AudioUnitEffect::GetEffectName () [virtual]
Implements Effect.
References mName.
bool AudioUnitEffect::Init () [virtual]
Reimplemented from Effect.
References Effect::mProjectRate, mSupportsMono, mSupportsStereo, mUnit, and SetRateAndChannels().
bool AudioUnitEffect::Process () [virtual]
Implements Effect.
References Effect::CopyInputTracks(), TrackListIterator::First(), Track::GetLinked(), Effect::GetSamples(), Effect::mOutputTracks, mSupportsStereo, TrackListIterator::Next(), ProcessStereo(), and Effect::ReplaceProcessedTracks().
bool AudioUnitEffect::ProcessStereo (int count, WaveTrack * left, WaveTrack * right, sampleCount lstart, sampleCount rstart, sampleCount len) [private]
References DoRender(), floatSample, WaveTrack::Get(), WaveTrack::GetMaxBlockSize(), WaveTrack::GetRate(), mLeftBufferForCallback, mRightBufferForCallback, mUnit, WaveTrack::Set(), SetRateAndChannels(), SimpleAudioRenderCallback(), Effect::TrackGroupProgress(), and Effect::TrackProgress().
Referenced by Process().
bool AudioUnitEffect::PromptUser () [virtual]
Reimplemented from Effect.
References GetCarbonViewComponent(), mComponent, mName, Effect::mParent, and mUnit.
bool AudioUnitEffect::SetRateAndChannels (AudioUnit unit, int numChannels, Float64 sampleRate) [private]
Referenced by Init(), and ProcessStereo().
OSStatus AudioUnitEffect::SimpleAudioRenderCallback (void * inRefCon, AudioUnitRenderActionFlags * inActionFlags, const AudioTimeStamp * inTimeStamp, UInt32 inBusNumber, UInt32 inNumFrames, AudioBufferList * ioData) [static, private]
References mLeftBufferForCallback, and mRightBufferForCallback.
Referenced by ProcessStereo().
Member Data Documentation
Component AudioUnitEffect::mComponent [private]
Referenced by AudioUnitEffect(), and PromptUser().
float* AudioUnitEffect::mLeftBufferForCallback [private]
Referenced by DoRender(), ProcessStereo(), and SimpleAudioRenderCallback().
wxString AudioUnitEffect::mName [private]
Referenced by GetEffectAction(), GetEffectIdentifier(), GetEffectName(), and PromptUser().
float* AudioUnitEffect::mRightBufferForCallback [private]
Referenced by DoRender(), ProcessStereo(), and SimpleAudioRenderCallback().
bool AudioUnitEffect::mSupportsMono [private]
Referenced by Init().
bool AudioUnitEffect::mSupportsStereo [private]
Referenced by Init(), and Process().
AudioUnit AudioUnitEffect::mUnit [private]
Referenced by AudioUnitEffect(), Init(), ProcessStereo(), PromptUser(), and ~AudioUnitEffect().
The documentation for this class was generated from the following files:
AudioUnitEffect.h
AudioUnitEffect.cpp