Audacity: FFmpegLibs Class Reference
FFmpegLibs Class Reference
Class used to dynamically load FFmpeg libraries.
#include <FFmpeg.h>
Public Member Functions
FFmpegLibs ()
~FFmpegLibs ()
bool FindLibs (wxWindow *parent)
bool LoadLibs (wxWindow *parent, bool showerr)
bool ValidLibsLoaded ()
bool InitLibs (wxString libpath_codec, bool showerr)
void FreeLibs ()
! Frees (unloads) loaded libraries
wxString GetLibraryVersion ()
wxString GetLibraryTypeString ()
wxString GetLibAVFormatPath ()
wxString GetLibAVFormatName ()
wxString GetLibAVCodecName ()
wxString GetLibAVUtilName ()
Public Attributes
void(* av_log_set_callback)(void(*)(void *, int, const char *, va_list))
void(* av_log_default_callback)(void *ptr, int level, const char *fmt, va_list vl)
void(* av_free)(void *ptr)
unsigned(* avcodec_version)(void)
unsigned(* avformat_version)(void)
unsigned(* avutil_version)(void)
void(* avcodec_init)(void)
AVCodec *(* avcodec_find_encoder)(enum CodecID id)
AVCodec *(* avcodec_find_encoder_by_name)(const char *name)
AVCodec *(* avcodec_find_decoder)(enum CodecID id)
AVCodec *(* avcodec_find_decoder_by_name)(const char *name)
enum CodecID(* av_codec_get_id)(const struct AVCodecTag *const *tags, unsigned int tag)
unsigned int(* av_codec_get_tag)(const struct AVCodecTag *const *tags, enum CodecID id)
void(* avcodec_string)(char *buf, int buf_size, AVCodecContext *enc, int encode)
void(* avcodec_get_context_defaults)(AVCodecContext *s)
AVCodecContext *(* avcodec_alloc_context)(void)
void(* avcodec_get_frame_defaults)(AVFrame *pic)
AVFrame *(* avcodec_alloc_frame)(void)
int(* avcodec_open)(AVCodecContext *avctx, AVCodec *codec)
int(* avcodec_decode_audio2)(AVCodecContext *avctx, int16_t *samples, int *frame_size_ptr, const uint8_t *buf, int buf_size)
int(* avcodec_encode_audio)(AVCodecContext *avctx, uint8_t *buf, int buf_size, const short *samples)
int(* avcodec_close)(AVCodecContext *avctx)
void(* avcodec_register_all)(void)
void(* avcodec_flush_buffers)(AVCodecContext *avctx)
int(* av_get_bits_per_sample)(enum CodecID codec_id)
int(* av_get_bits_per_sample_format)(enum SampleFormat sample_fmt)
void *(* av_fast_realloc)(void *ptr, unsigned int *size, unsigned int min_size)
int(* av_open_input_file)(AVFormatContext **ic_ptr, const char *filename, AVInputFormat *fmt, int buf_size, AVFormatParameters *ap)
int(* av_open_input_stream)(AVFormatContext **ic_ptr, ByteIOContext *pb, const char *filename, AVInputFormat *fmt, AVFormatParameters *ap)
int(* get_buffer)(ByteIOContext *s, unsigned char *buf, int size)
void(* av_register_all)(void)
int(* register_protocol)(URLProtocol *protocol)
int(* av_register_protocol)(URLProtocol *protocol)
int(* av_strstart)(const char *str, const char *pfx, const char **ptr)
int(* av_find_stream_info)(AVFormatContext *ic)
int(* av_read_frame)(AVFormatContext *s, AVPacket *pkt)
int(* av_seek_frame)(AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
int(* av_close_input_file)(AVFormatContext *s)
int(* av_index_search_timestamp)(AVStream *st, int64_t timestamp, int flags)
int(* av_write_header)(AVFormatContext *s)
AVInputFormat *(* av_iformat_next)(AVInputFormat *f)
AVOutputFormat *(* av_oformat_next)(AVOutputFormat *f)
AVCodec *(* av_codec_next)(AVCodec *c)
int(* av_set_parameters)(AVFormatContext *s, AVFormatParameters *ap)
int(* url_open_protocol)(URLContext **puc, struct URLProtocol *up, const char *filename, int flags)
int(* url_fdopen)(ByteIOContext **s, URLContext *h)
int(* url_close)(URLContext *h)
int(* url_fopen)(ByteIOContext **s, const char *filename, int flags)
int64_t(* url_fseek)(ByteIOContext *s, int64_t offset, int whence)
int(* url_fclose)(ByteIOContext *s)
int(* url_fsize)(ByteIOContext *s)
AVStream *(* av_new_stream)(AVFormatContext *s, int id)
AVFormatContext *(* av_alloc_format_context)(void)
AVOutputFormat *(* guess_format)(const char *short_name, const char *filename, const char *mime_type)
int(* match_ext)(const char *filename, const char *extensions)
int(* av_write_trailer)(AVFormatContext *s)
int(* av_interleaved_write_frame)(AVFormatContext *s, AVPacket *pkt)
int(* av_write_frame)(AVFormatContext *s, AVPacket *pkt)
void(* av_init_packet)(AVPacket *pkt)
int(* av_fifo_generic_write)(AVFifoBuffer *f, void *src, int size, int(*func)(void *, void *, int))
void(* av_fifo_free)(AVFifoBuffer *f)
int(* av_fifo_size)(AVFifoBuffer *f)
void *(* av_malloc)(unsigned int size)
void(* av_freep)(void *ptr)
int64_t(* av_rescale_q)(int64_t a, AVRational bq, AVRational cq)
void(* av_free_packet)(AVPacket *pkt)
AVFifoBuffer *(* av_fifo_alloc)(unsigned int size)
int(* av_fifo_generic_read)(AVFifoBuffer *f, uint8_t *buf, int buf_size, int(*func)(void *, void *, int))
int(* av_fifo_realloc2)(AVFifoBuffer *f, unsigned int size)
int refcount
Private Attributes
wxString mLibAVFormatPath
! Stored path to libavformat library
wxString mAVCodecVersion
! Stored library version
wxString mAVFormatVersion
wxString mAVUtilVersion
wxDynamicLibrary * avformat
! wx interfaces for dynamic libraries
wxDynamicLibrary * avcodec
wxDynamicLibrary * avutil
bool mLibsLoaded
! true if libraries are loaded, false otherwise
Detailed Description
Class used to dynamically load FFmpeg libraries.
Manages liabv* libraries - loads/unloads libraries, imports symbols. Only one instance of this class should exist at each given moment. function definitions are taken from FFmpeg headers manually, eventually (at next major FFmpeg version change) we'll have to review them and update if necessary.
Constructor & Destructor Documentation
FFmpegLibs::FFmpegLibs ()
References gPrefs.
FFmpegLibs::~FFmpegLibs ()
References FreeLibs().
Member Function Documentation
bool FFmpegLibs::FindLibs (wxWindow * parent)
! Finds libav* libraries
Returns:
true if found, false if not found
References GetLibAVFormatName(), GetLibAVFormatPath(), FindFFmpegDialog::GetLibPath(), GetLibraryTypeString(), gPrefs, mLibAVFormatPath, and name.
Referenced by LibraryPrefs::OnFFmpegFindButton().
void FFmpegLibs::FreeLibs ()
! Frees (unloads) loaded libraries
References avcodec, avformat, avutil, and mLibsLoaded.
Referenced by InitLibs(), LoadLibs(), LibraryPrefs::OnFFmpegFindButton(), and ~FFmpegLibs().
wxString FFmpegLibs::GetLibAVCodecName () [inline]
Referenced by InitLibs().
wxString FFmpegLibs::GetLibAVFormatName () [inline]
Referenced by FindLibs(), and LoadLibs().
wxString FFmpegLibs::GetLibAVFormatPath () [inline]
Referenced by FindLibs(), and LoadLibs().
wxString FFmpegLibs::GetLibAVUtilName () [inline]
Referenced by InitLibs().
wxString FFmpegLibs::GetLibraryTypeString () [inline]
Referenced by FindLibs().
wxString FFmpegLibs::GetLibraryVersion () [inline]
! Returns library version as string
Returns:
libavformat library version or empty string?
References mAVCodecVersion, mAVFormatVersion, and mAVUtilVersion.
Referenced by GetFFmpegVersion().
bool FFmpegLibs::InitLibs (wxString libpath_codec, bool showerr)
! Initializes the libraries. Call after LoadLibs (when ValidLibsLoaded returns true)
Parameters:
libpath_codec - full file path to the libavformat library
showerr - controls whether or not to show an error dialog if libraries cannot be loaded
Returns:
true if initialization completed without errors, false otherwise do not call (it is called by FindLibs automatically)
References av_alloc_format_context, av_close_input_file, av_codec_get_id, av_codec_get_tag, av_codec_next, av_fast_realloc, av_fifo_alloc, av_fifo_free, av_fifo_generic_read, av_fifo_generic_write, av_fifo_realloc2, av_fifo_size, av_find_stream_info, av_free, av_free_packet, av_freep, av_get_bits_per_sample, av_get_bits_per_sample_format, av_iformat_next, av_index_search_timestamp, av_init_packet, av_interleaved_write_frame, av_log_default_callback, av_log_set_callback, av_malloc, av_new_stream, av_oformat_next, av_open_input_file, av_open_input_stream, av_read_frame, av_register_all, av_register_protocol, av_rescale_q, av_seek_frame, av_set_parameters, av_strstart, av_write_frame, av_write_header, av_write_trailer, avcodec, avcodec_alloc_context, avcodec_alloc_frame, avcodec_close, avcodec_decode_audio2, avcodec_encode_audio, avcodec_find_decoder, avcodec_find_decoder_by_name, avcodec_find_encoder, avcodec_find_encoder_by_name, avcodec_flush_buffers, avcodec_get_context_defaults, avcodec_get_frame_defaults, avcodec_init, avcodec_open, avcodec_register_all, avcodec_string, avcodec_version, avformat, avformat_version, avutil, avutil_version, FreeLibs(), get_buffer, GetLibAVCodecName(), GetLibAVUtilName(), guess_format, INITDYN, match_ext, mAVCodecVersion, mAVFormatVersion, mAVUtilVersion, AudacityApp::mLogger, name, register_protocol, url_close, url_fclose, url_fdopen, url_fopen, url_fseek, url_fsize, url_open_protocol, and wxGetApp().
Referenced by LoadLibs().
bool FFmpegLibs::LoadLibs (wxWindow * parent, bool showerr)
! Loads libav* libraries
Parameters:
showerr - controls whether or not to show an error dialog if libraries cannot be loaded
Returns:
true if loaded, false if not loaded
References FreeLibs(), GetLibAVFormatName(), GetLibAVFormatPath(), InitLibs(), mLibAVFormatPath, mLibsLoaded, and ValidLibsLoaded().
Referenced by LoadFFmpeg().
bool FFmpegLibs::ValidLibsLoaded ()
! Checks if libraries are loaded
Returns:
true if libraries are loaded, false otherwise
References mLibsLoaded.
Referenced by CheckFFmpegPresence(), ExportFFmpegOptions::ExportFFmpegOptions(), GetFFmpegVersion(), FFmpegImportFileHandle::Init(), ExportFFmpeg::Init(), LoadFFmpeg(), LoadLibs(), FFmpegImportPlugin::Open(), and FFmpegImportFileHandle::~FFmpegImportFileHandle().
Member Data Documentation
AVFormatContext*(* FFmpegLibs::av_alloc_format_context)(void)
Referenced by ExportFFmpeg::Init(), and InitLibs().
int(* FFmpegLibs::av_close_input_file)(AVFormatContext *s)
Referenced by InitLibs(), and FFmpegImportFileHandle::~FFmpegImportFileHandle().
enum CodecID(* FFmpegLibs::av_codec_get_id)(const struct AVCodecTag *const *tags, unsigned int tag)
Referenced by InitLibs().
unsigned int(* FFmpegLibs::av_codec_get_tag)(const struct AVCodecTag *const *tags, enum CodecID id)
Referenced by ExportFFmpeg::InitCodecs(), and InitLibs().
AVCodec*(* FFmpegLibs::av_codec_next)(AVCodec *c)
Referenced by ExportFFmpegOptions::FetchCodecList(), ExportFFmpegOptions::FetchCompatibleCodecList(), and InitLibs().
void*(* FFmpegLibs::av_fast_realloc)(void *ptr, unsigned int *size, unsigned int min_size)
Referenced by FFmpegImportFileHandle::DecodeFrame(), and InitLibs().
AVFifoBuffer*(* FFmpegLibs::av_fifo_alloc)(unsigned int size)
Referenced by ExportFFmpeg::InitCodecs(), and InitLibs().
void(* FFmpegLibs::av_fifo_free)(AVFifoBuffer *f)
Referenced by ExportFFmpeg::Finalize(), and InitLibs().
int(* FFmpegLibs::av_fifo_generic_read)(AVFifoBuffer *f, uint8_t *buf, int buf_size, int(*func)(void *, void *, int))
Referenced by ExportFFmpeg::EncodeAudioFrame(), ExportFFmpeg::Finalize(), and InitLibs().
int(* FFmpegLibs::av_fifo_generic_write)(AVFifoBuffer *f, void *src, int size, int(*func)(void *, void *, int))
Referenced by ExportFFmpeg::EncodeAudioFrame(), and InitLibs().
int(* FFmpegLibs::av_fifo_realloc2)(AVFifoBuffer *f, unsigned int size)
Referenced by ExportFFmpeg::EncodeAudioFrame(), and InitLibs().
int(* FFmpegLibs::av_fifo_size)(AVFifoBuffer *f)
Referenced by ExportFFmpeg::EncodeAudioFrame(), ExportFFmpeg::Finalize(), and InitLibs().
int(* FFmpegLibs::av_find_stream_info)(AVFormatContext *ic)
Referenced by FFmpegImportFileHandle::Init(), and InitLibs().
void(* FFmpegLibs::av_free)(void *ptr)
Referenced by ExportFFmpeg::Finalize(), InitLibs(), and FFmpegImportFileHandle::~FFmpegImportFileHandle().
void(* FFmpegLibs::av_free_packet)(AVPacket *pkt)
Referenced by FFmpegImportFileHandle::Import(), InitLibs(), and FFmpegImportFileHandle::ReadNextFrame().
void(* FFmpegLibs::av_freep)(void *ptr)
Referenced by ExportFFmpeg::Finalize(), InitLibs(), and ufile_fopen_input().
int(* FFmpegLibs::av_get_bits_per_sample)(enum CodecID codec_id)
Referenced by InitLibs().
int(* FFmpegLibs::av_get_bits_per_sample_format)(enum SampleFormat sample_fmt)
Referenced by InitLibs().
AVInputFormat*(* FFmpegLibs::av_iformat_next)(AVInputFormat *f)
Referenced by InitLibs(), and ufile_fopen_input().
int(* FFmpegLibs::av_index_search_timestamp)(AVStream *st, int64_t timestamp, int flags)
Referenced by InitLibs().
void(* FFmpegLibs::av_init_packet)(AVPacket *pkt)
Referenced by ExportFFmpeg::EncodeAudioFrame(), ExportFFmpeg::Finalize(), and InitLibs().
int(* FFmpegLibs::av_interleaved_write_frame)(AVFormatContext *s, AVPacket *pkt)
Referenced by ExportFFmpeg::EncodeAudioFrame(), ExportFFmpeg::Finalize(), and InitLibs().
void(* FFmpegLibs::av_log_default_callback)(void *ptr, int level, const char *fmt, va_list vl)
Referenced by InitLibs(), and FFmpegImportFileHandle::~FFmpegImportFileHandle().
void(* FFmpegLibs::av_log_set_callback)(void(*)(void *, int, const char *, va_list))
Referenced by FFmpegImportFileHandle::Init(), ExportFFmpeg::Init(), InitLibs(), and FFmpegImportFileHandle::~FFmpegImportFileHandle().
void*(* FFmpegLibs::av_malloc)(unsigned int size)
Referenced by ExportFFmpeg::InitCodecs(), InitLibs(), and ufile_fopen_input().
AVStream*(* FFmpegLibs::av_new_stream)(AVFormatContext *s, int id)
Referenced by ExportFFmpeg::Init(), and InitLibs().
AVOutputFormat*(* FFmpegLibs::av_oformat_next)(AVOutputFormat *f)
Referenced by ExportFFmpegOptions::FetchCompatibleFormatList(), ExportFFmpegOptions::FetchFormatList(), and InitLibs().
int(* FFmpegLibs::av_open_input_file)(AVFormatContext **ic_ptr, const char *filename, AVInputFormat *fmt, int buf_size, AVFormatParameters *ap)
Referenced by InitLibs().
int(* FFmpegLibs::av_open_input_stream)(AVFormatContext **ic_ptr, ByteIOContext *pb, const char *filename, AVInputFormat *fmt, AVFormatParameters *ap)
Referenced by InitLibs(), and ufile_fopen_input().
int(* FFmpegLibs::av_read_frame)(AVFormatContext *s, AVPacket *pkt)
Referenced by InitLibs(), and FFmpegImportFileHandle::ReadNextFrame().
void(* FFmpegLibs::av_register_all)(void)
Referenced by InitLibs().
int(* FFmpegLibs::av_register_protocol)(URLProtocol *protocol)
Referenced by InitLibs().
int64_t(* FFmpegLibs::av_rescale_q)(int64_t a, AVRational bq, AVRational cq)
Referenced by ExportFFmpeg::EncodeAudioFrame(), ExportFFmpeg::Finalize(), and InitLibs().
int(* FFmpegLibs::av_seek_frame)(AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
Referenced by InitLibs().
int(* FFmpegLibs::av_set_parameters)(AVFormatContext *s, AVFormatParameters *ap)
Referenced by ExportFFmpeg::Init(), and InitLibs().
int(* FFmpegLibs::av_strstart)(const char *str, const char *pfx, const char **ptr)
Referenced by InitLibs().
int(* FFmpegLibs::av_write_frame)(AVFormatContext *s, AVPacket *pkt)
Referenced by InitLibs().
int(* FFmpegLibs::av_write_header)(AVFormatContext *s)
Referenced by ExportFFmpeg::Init(), and InitLibs().
int(* FFmpegLibs::av_write_trailer)(AVFormatContext *s)
Referenced by ExportFFmpeg::Finalize(), and InitLibs().
wxDynamicLibrary* FFmpegLibs::avcodec [private]
Referenced by FreeLibs(), and InitLibs().
AVCodecContext*(* FFmpegLibs::avcodec_alloc_context)(void)
Referenced by InitLibs().
AVFrame*(* FFmpegLibs::avcodec_alloc_frame)(void)
Referenced by InitLibs().
int(* FFmpegLibs::avcodec_close)(AVCodecContext *avctx)
Referenced by ExportFFmpeg::Finalize(), and InitLibs().
int(* FFmpegLibs::avcodec_decode_audio2)(AVCodecContext *avctx, int16_t *samples, int *frame_size_ptr, const uint8_t *buf, int buf_size)
Referenced by FFmpegImportFileHandle::DecodeFrame(), and InitLibs().
int(* FFmpegLibs::avcodec_encode_audio)(AVCodecContext *avctx, uint8_t *buf, int buf_size, const short *samples)
Referenced by ExportFFmpeg::EncodeAudioFrame(), ExportFFmpeg::Finalize(), and InitLibs().
AVCodec*(* FFmpegLibs::avcodec_find_decoder)(enum CodecID id)
Referenced by FFmpegImportFileHandle::InitCodecs(), and InitLibs().
AVCodec*(* FFmpegLibs::avcodec_find_decoder_by_name)(const char *name)
Referenced by InitLibs().
AVCodec*(* FFmpegLibs::avcodec_find_encoder)(enum CodecID id)
Referenced by ExportFFmpeg::ExportFFmpeg(), ExportFFmpegOptions::ExportFFmpegOptions(), ExportFFmpegOptions::FetchCompatibleCodecList(), ExportFFmpeg::InitCodecs(), and InitLibs().
AVCodec*(* FFmpegLibs::avcodec_find_encoder_by_name)(const char *name)
Referenced by ExportFFmpegOptions::DoOnCodecList(), ExportFFmpegOptions::DoOnFormatList(), InitLibs(), and ExportFFmpegOptions::OnOK().
void(* FFmpegLibs::avcodec_flush_buffers)(AVCodecContext *avctx)
Referenced by InitLibs().
void(* FFmpegLibs::avcodec_get_context_defaults)(AVCodecContext *s)
Referenced by ExportFFmpeg::InitCodecs(), and InitLibs().
void(* FFmpegLibs::avcodec_get_frame_defaults)(AVFrame *pic)
Referenced by InitLibs().
void(* FFmpegLibs::avcodec_init)(void)
Referenced by InitLibs().
int(* FFmpegLibs::avcodec_open)(AVCodecContext *avctx, AVCodec *codec)
Referenced by FFmpegImportFileHandle::InitCodecs(), ExportFFmpeg::InitCodecs(), and InitLibs().
void(* FFmpegLibs::avcodec_register_all)(void)
Referenced by InitLibs().
void(* FFmpegLibs::avcodec_string)(char *buf, int buf_size, AVCodecContext *enc, int encode)
Referenced by InitLibs().
unsigned(* FFmpegLibs::avcodec_version)(void)
Referenced by InitLibs().
wxDynamicLibrary* FFmpegLibs::avformat [private]
! wx interfaces for dynamic libraries
Referenced by FreeLibs(), and InitLibs().
unsigned(* FFmpegLibs::avformat_version)(void)
Referenced by InitLibs().
wxDynamicLibrary* FFmpegLibs::avutil [private]
Referenced by FreeLibs(), and InitLibs().
unsigned(* FFmpegLibs::avutil_version)(void)
Referenced by InitLibs().
int(* FFmpegLibs::get_buffer)(ByteIOContext *s, unsigned char *buf, int size)
Referenced by InitLibs(), and ufile_fopen_input().
AVOutputFormat*(* FFmpegLibs::guess_format)(const char *short_name, const char *filename, const char *mime_type)
Referenced by ExportFFmpegOptions::DoOnCodecList(), ExportFFmpegOptions::DoOnFormatList(), ExportFFmpeg::ExportFFmpeg(), ExportFFmpegOptions::FetchCompatibleCodecList(), ExportFFmpegOptions::FetchCompatibleFormatList(), ExportFFmpeg::Init(), and InitLibs().
int(* FFmpegLibs::match_ext)(const char *filename, const char *extensions)
Referenced by InitLibs(), and ufile_fopen_input().
wxString FFmpegLibs::mAVCodecVersion [private]
! Stored library version
Referenced by GetLibraryVersion(), and InitLibs().
wxString FFmpegLibs::mAVFormatVersion [private]
Referenced by GetLibraryVersion(), and InitLibs().
wxString FFmpegLibs::mAVUtilVersion [private]
Referenced by GetLibraryVersion(), and InitLibs().
wxString FFmpegLibs::mLibAVFormatPath [private]
! Stored path to libavformat library
Referenced by FindLibs(), and LoadLibs().
bool FFmpegLibs::mLibsLoaded [private]
! true if libraries are loaded, false otherwise
Referenced by FreeLibs(), LoadLibs(), and ValidLibsLoaded().
int FFmpegLibs::refcount
Ugly reference counting. I thought of using wxStuff for that, but decided that wx reference counting is not useful, since there's no data sharing - object is shared because libraries are.
Referenced by DropFFmpegLibs(), and PickFFmpegLibs().
int(* FFmpegLibs::register_protocol)(URLProtocol *protocol)
Referenced by InitLibs().
int(* FFmpegLibs::url_close)(URLContext *h)
Referenced by InitLibs(), and ufile_fopen().
int(* FFmpegLibs::url_fclose)(ByteIOContext *s)
Referenced by ExportFFmpeg::Finalize(), InitLibs(), and ufile_fopen_input().
int(* FFmpegLibs::url_fdopen)(ByteIOContext **s, URLContext *h)
Referenced by InitLibs(), and ufile_fopen().
int(* FFmpegLibs::url_fopen)(ByteIOContext **s, const char *filename, int flags)
Referenced by InitLibs().
int64_t(* FFmpegLibs::url_fseek)(ByteIOContext *s, int64_t offset, int whence)
Referenced by InitLibs(), and ufile_fopen_input().
int(* FFmpegLibs::url_fsize)(ByteIOContext *s)
Referenced by InitLibs().
int(* FFmpegLibs::url_open_protocol)(URLContext **puc, struct URLProtocol *up, const char *filename, int flags)
Referenced by InitLibs(), and ufile_fopen().
The documentation for this class was generated from the following files:
FFmpeg.h
FFmpeg.cpp