Audacity: ToolBarDialog Class Reference
ToolBarDialog Class Reference
A dialog based container for ExpandingToolBars providing modal based operations.
#include <ExpandingToolBar.h>
Public Member Functions
ToolBarDialog (wxWindow *parent, wxWindowID id, const wxString &name=wxEmptyString, const wxPoint &pos=wxDefaultPosition)
~ToolBarDialog ()
virtual void Fit ()
void SetChild (ExpandingToolBar *child)
Protected Attributes
ExpandingToolBar * mChild
Detailed Description
A dialog based container for ExpandingToolBars providing modal based operations.
Constructor & Destructor Documentation
ToolBarDialog::ToolBarDialog (wxWindow * parent, wxWindowID id, const wxString & name = wxEmptyString, const wxPoint & pos = wxDefaultPosition)
ToolBarDialog::~ToolBarDialog ()
Member Function Documentation
void ToolBarDialog::Fit () [virtual]
References mChild.
Referenced by SetChild().
void ToolBarDialog::SetChild (ExpandingToolBar * child)
References Fit(), and mChild.
Referenced by ExpandingToolBar::OnSize().
Member Data Documentation
ExpandingToolBar* ToolBarDialog::mChild [protected]
Referenced by Fit(), and SetChild().
The documentation for this class was generated from the following files:
ExpandingToolBar.h
ExpandingToolBar.cpp