Audacity: AColor Class Reference
AColor Class Reference
AColor Manages color brushes and pens.
#include <AColor.h>
Static Public Member Functions
static void Init ()
static void ReInit ()
static void Arrow (wxDC &dc, wxCoord x, wxCoord y, int width, bool down=true)
static void Line (wxDC &dc, wxCoord x1, wxCoord y1, wxCoord x2, wxCoord y2)
static void DrawFocus (wxDC &dc, wxRect &r)
static void Bevel (wxDC &dc, bool up, wxRect &r)
static void BevelTrackInfo (wxDC &dc, bool up, wxRect &r)
static wxColour Blend (const wxColour &c1, const wxColour &c2)
static void UseThemeColour (wxDC *dc, int iIndex)
static void TrackPanelBackground (wxDC *dc, bool selected)
static void Light (wxDC *dc, bool selected)
static void Medium (wxDC *dc, int index)
static void MediumTrackInfo (wxDC *dc, bool selected, bool syncSel)
static void Dark (wxDC *dc, bool selected)
static void CursorColor (wxDC *dc)
static void IndicatorColor (wxDC *dc, bool bIsNotRecording)
static void PlayRegionColor (wxDC *dc, bool locked)
static void Mute (wxDC *dc, bool on, bool selected, bool soloing)
static void Solo (wxDC *dc, bool on, bool selected)
static void MIDIChannel (wxDC *dc, int channel)
static void LightMIDIChannel (wxDC *dc, int channel)
static void DarkMIDIChannel (wxDC *dc, int channel)
static void TrackFocusPen (wxDC *dc, int level)
static void SnapGuidePen (wxDC *dc)
Static Public Attributes
static wxBrush lightBrush [2]
static wxBrush mediumBrush [3]
static wxBrush darkBrush [2]
static wxPen lightPen [2]
static wxPen mediumPen [3]
static wxPen darkPen [2]
static wxPen cursorPen
static wxPen indicatorPen [2]
static wxBrush indicatorBrush [2]
static wxPen playRegionPen [2]
static wxBrush playRegionBrush [2]
static wxBrush muteBrush [2]
static wxBrush soloBrush
static wxPen clippingPen
static wxPen envelopePen
static wxPen WideEnvelopePen
static wxBrush envelopeBrush
static wxBrush labelTextNormalBrush
static wxBrush labelTextEditBrush
static wxBrush labelUnselectedBrush
static wxBrush labelSelectedBrush
static wxBrush labelSyncSelBrush
static wxPen labelUnselectedPen
static wxPen labelSelectedPen
static wxPen labelSyncSelPen
static wxPen labelSurroundPen
static wxPen trackFocusPens [3]
static wxPen snapGuidePen
static wxBrush tooltipBrush
Static Private Attributes
static wxPen sparePen
static wxBrush spareBrush
static bool inited = false
Detailed Description
AColor Manages color brushes and pens.
It is also a place to document colour usage policy in Audacity
Member Function Documentation
void AColor::Arrow (wxDC & dc, wxCoord x, wxCoord y, int width, bool down = true) [static]
Referenced by TrackInfo::DrawMinimize(), TrackInfo::DrawTitleBar(), Meter::HandlePaint(), and TimeTextCtrl::Layout().
void AColor::Bevel (wxDC & dc, bool up, wxRect & r) [static]
References Dark(), Light(), and Line().
Referenced by BevelTrackInfo(), MixerBoard::CreateMuteSoloImages(), Grabber::DrawGrabber(), Meter::DrawMeterBar(), Meter::HandlePaint(), TimeTextCtrl::Layout(), MixerBoard::LoadMusicalInstruments(), MixerTrackCluster::OnPaint(), and ControlToolBar::Repaint().
void AColor::BevelTrackInfo (wxDC & dc, bool up, wxRect & r) [static]
References Bevel(), Blend(), ThemeBase::Colour(), and theTheme.
Referenced by AdornedRulerPanel::DoDrawBorder(), TrackInfo::DrawBackground(), TrackInfo::DrawCloseBox(), TrackInfo::DrawMinimize(), TrackInfo::DrawMuteSolo(), TrackInfo::DrawTitleBar(), and TrackArtist::DrawVRuler().
wxColour AColor::Blend (const wxColour & c1, const wxColour & c2) [static]
Referenced by BevelTrackInfo().
void AColor::CursorColor (wxDC * dc) [static]
References cursorPen, Init(), and inited.
Referenced by TrackPanel::DoDrawCursor().
void AColor::Dark (wxDC * dc, bool selected) [static]
References darkBrush, darkPen, Init(), and inited.
Referenced by Bevel(), LWSlider::Draw(), Grabber::DrawGrabber(), TrackInfo::DrawMinimize(), TrackPanel::DrawShadow(), TrackArtist::DrawTimeSlider(), ToolDock::OnPaint(), ToolBar::OnPaint(), and TrackPanelBackground().
void AColor::DarkMIDIChannel (wxDC * dc, int channel) [static]
References AColor_midicolors.
Referenced by NoteTrack::DrawLabelControls(), and TrackArtist::DrawNoteTrack().
void AColor::DrawFocus (wxDC & dc, wxRect & r) [static]
Referenced by ASlider::OnPaint(), and AButton::OnPaint().
void AColor::IndicatorColor (wxDC * dc, bool bIsNotRecording) [static]
References indicatorBrush, indicatorPen, Init(), and inited.
Referenced by TrackPanel::DoDrawIndicator(), and AdornedRulerPanel::DoDrawIndicator().
void AColor::Init () [static]
References clippingPen, cursorPen, darkBrush, darkPen, envelopeBrush, envelopePen, indicatorBrush, indicatorPen, inited, labelSelectedBrush, labelSelectedPen, labelSurroundPen, labelSyncSelBrush, labelSyncSelPen, labelTextEditBrush, labelTextNormalBrush, labelUnselectedBrush, labelUnselectedPen, lightBrush, lightPen, mediumBrush, mediumPen, muteBrush, playRegionBrush, playRegionPen, ThemeBase::SetBrushColour(), ThemeBase::SetPenColour(), snapGuidePen, soloBrush, theTheme, tooltipBrush, trackFocusPens, and WideEnvelopePen.
Referenced by CursorColor(), Dark(), IndicatorColor(), Light(), Medium(), Mute(), AudacityApp::OnInit(), PlayRegionColor(), ReInit(), SnapGuidePen(), Solo(), TrackFocusPen(), and UseThemeColour().
void AColor::Light (wxDC * dc, bool selected) [static]
References Init(), inited, lightBrush, and lightPen.
Referenced by Bevel(), LWSlider::Draw(), Grabber::DrawGrabber(), and TrackArtist::DrawTimeSlider().
void AColor::LightMIDIChannel (wxDC * dc, int channel) [static]
References AColor_midicolors.
Referenced by NoteTrack::DrawLabelControls(), and TrackArtist::DrawNoteTrack().
void AColor::Line (wxDC & dc, wxCoord x1, wxCoord y1, wxCoord x2, wxCoord y2) [static]
Referenced by Bevel(), TrackPanel::DoDrawCursor(), TrackPanel::DoDrawIndicator(), TimeTrack::Draw(), LabelTrack::Draw(), LWSlider::Draw(), TrackPanel::DrawBordersAroundTrack(), TrackInfo::DrawBordersWithin(), TrackArtist::DrawClipWaveform(), TrackInfo::DrawCloseBox(), TrackArtist::DrawEnvLine(), TrackPanel::DrawEverythingElse(), Grabber::DrawGrabber(), TrackArtist::DrawIndividualSamples(), NoteTrack::DrawLabelControls(), LabelStruct::DrawLines(), Meter::DrawMeterBar(), TrackArtist::DrawMinMaxRMS(), TrackArtist::DrawNegativeOffsetTrackArrows(), TrackArtist::DrawNoteTrack(), FreqWindow::DrawPlot(), TrackPanel::DrawShadow(), TrackArtist::DrawTimeSlider(), TrackArtist::DrawVRuler(), TrackArtist::DrawWaveform(), TrackArtist::DrawWaveformBackground(), ToolFrame::OnPaint(), ToolDock::OnPaint(), ToolBar::OnPaint(), ExportMixerPanel::OnPaint(), EqualizationPanel::OnPaint(), CompressorPanel::OnPaint(), EffectAutoDuckPanel::OnPaint(), AudacityPrintout::OnPrintPage(), and FreqWindow::PlotPaint().
void AColor::Medium (wxDC * dc, int index) [static]
References Init(), inited, mediumBrush, and mediumPen.
Referenced by Grabber::DrawGrabber(), MediumTrackInfo(), and MixerTrackCluster::OnPaint().
void AColor::MediumTrackInfo (wxDC * dc, bool selected, bool syncSel) [static]
References Medium(), and UseThemeColour().
Referenced by AdornedRulerPanel::DoDrawBorder(), TrackInfo::DrawBackground(), TrackInfo::DrawMinimize(), TrackInfo::DrawMuteSolo(), and TrackInfo::DrawTitleBar().
void AColor::MIDIChannel (wxDC * dc, int channel) [static]
References AColor_midicolors.
Referenced by NoteTrack::DrawLabelControls(), and TrackArtist::DrawNoteTrack().
void AColor::Mute (wxDC * dc, bool on, bool selected, bool soloing) [static]
References Init(), inited, mediumBrush, and muteBrush.
Referenced by MixerBoard::CreateMuteSoloImages(), and TrackInfo::DrawMuteSolo().
void AColor::PlayRegionColor (wxDC * dc, bool locked) [static]
References Init(), inited, playRegionBrush, and playRegionPen.
Referenced by AdornedRulerPanel::DoDrawPlayRegion().
void AColor::ReInit () [static]
References Init(), and inited.
Referenced by ThemePrefs::OnLoadThemeCache().
void AColor::SnapGuidePen (wxDC * dc) [static]
References Init(), inited, and snapGuidePen.
Referenced by TrackPanel::DrawEverythingElse().
void AColor::Solo (wxDC * dc, bool on, bool selected) [static]
References Init(), inited, mediumBrush, and soloBrush.
Referenced by MixerBoard::CreateMuteSoloImages(), and TrackInfo::DrawMuteSolo().
void AColor::TrackFocusPen (wxDC * dc, int level) [static]
References Init(), inited, and trackFocusPens.
Referenced by TrackPanel::HighlightFocusedTrack().
void AColor::TrackPanelBackground (wxDC * dc, bool selected) [static]
References Dark(), and UseThemeColour().
Referenced by TrackPanel::DrawEverythingElse(), and TrackPanel::DrawOutsideOfTrack().
void AColor::UseThemeColour (wxDC * dc, int iIndex) [static]
References ThemeBase::Colour(), Init(), inited, spareBrush, sparePen, and theTheme.
Referenced by MediumTrackInfo(), and TrackPanelBackground().
Member Data Documentation
wxPen AColor::clippingPen [static]
Referenced by Init().
wxPen AColor::cursorPen [static]
Referenced by CursorColor(), and Init().
wxBrush AColor::darkBrush [static]
Referenced by Dark(), and Init().
wxPen AColor::darkPen [static]
Referenced by Dark(), and Init().
wxBrush AColor::envelopeBrush [static]
Referenced by Envelope::DrawPoints(), Init(), and ExportMixerPanel::OnPaint().
wxPen AColor::envelopePen [static]
Referenced by TimeTrack::Draw(), TrackArtist::DrawEnvelope(), Envelope::DrawPoints(), Init(), and EffectAutoDuckPanel::OnPaint().
wxBrush AColor::indicatorBrush [static]
Referenced by IndicatorColor(), and Init().
wxPen AColor::indicatorPen [static]
Referenced by IndicatorColor(), and Init().
bool AColor::inited = false [static, private]
Referenced by CursorColor(), Dark(), IndicatorColor(), Init(), Light(), Medium(), Mute(), PlayRegionColor(), ReInit(), SnapGuidePen(), Solo(), TrackFocusPen(), and UseThemeColour().
wxBrush AColor::labelSelectedBrush [static]
Referenced by LabelTrack::Draw(), and Init().
wxPen AColor::labelSelectedPen [static]
Referenced by LabelTrack::Draw(), and Init().
wxPen AColor::labelSurroundPen [static]
Referenced by LabelTrack::Draw(), and Init().
wxBrush AColor::labelSyncSelBrush [static]
Referenced by LabelTrack::Draw(), and Init().
wxPen AColor::labelSyncSelPen [static]
Referenced by LabelTrack::Draw(), and Init().
wxBrush AColor::labelTextEditBrush [static]
Referenced by LabelTrack::Draw(), and Init().
wxBrush AColor::labelTextNormalBrush [static]
Referenced by LabelTrack::Draw(), and Init().
wxBrush AColor::labelUnselectedBrush [static]
Referenced by LabelTrack::Draw(), and Init().
wxPen AColor::labelUnselectedPen [static]
Referenced by LabelTrack::Draw(), and Init().
wxBrush AColor::lightBrush [static]
Referenced by Init(), and Light().
wxPen AColor::lightPen [static]
Referenced by Init(), and Light().
wxBrush AColor::mediumBrush [static]
Referenced by Init(), Medium(), Mute(), and Solo().
wxPen AColor::mediumPen [static]
Referenced by Init(), and Medium().
wxBrush AColor::muteBrush [static]
Referenced by Init(), and Mute().
wxBrush AColor::playRegionBrush [static]
Referenced by Init(), ExportMixerPanel::OnPaint(), and PlayRegionColor().
wxPen AColor::playRegionPen [static]
Referenced by Init(), and PlayRegionColor().
wxPen AColor::snapGuidePen [static]
Referenced by Init(), and SnapGuidePen().
wxBrush AColor::soloBrush [static]
Referenced by Init(), and Solo().
wxBrush AColor::spareBrush [static, private]
Referenced by UseThemeColour().
wxPen AColor::sparePen [static, private]
Referenced by UseThemeColour().
wxBrush AColor::tooltipBrush [static]
Referenced by Init(), and TipPanel::OnPaint().
wxPen AColor::trackFocusPens [static]
Referenced by Init(), and TrackFocusPen().
wxPen AColor::WideEnvelopePen [static]
Referenced by Init(), and CompressorPanel::OnPaint().
The documentation for this class was generated from the following files:
AColor.h
AColor.cpp