Audacity: ExportOGG Class Reference
ExportOGG Class Reference
Public Member Functions
ExportOGG ()
void Destroy ()
bool DisplayOptions (wxWindow *parent, int format=0)
int Export (AudacityProject *project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec *mixerSpec=NULL, Tags *metadata=NULL, int subformat=0)
called to export audio into a file.
Private Member Functions
bool FillComment (AudacityProject *project, vorbis_comment *comment, Tags *metadata)
Constructor & Destructor Documentation
ExportOGG::ExportOGG ()
References ExportPlugin::AddExtension(), ExportPlugin::AddFormat(), ExportPlugin::SetCanMetaData(), ExportPlugin::SetDescription(), ExportPlugin::SetFormat(), and ExportPlugin::SetMaxChannels().
Member Function Documentation
void ExportOGG::Destroy () [virtual]
Reimplemented from ExportPlugin.
bool ExportOGG::DisplayOptions (wxWindow * parent, int format = 0) [virtual]
Reimplemented from ExportPlugin.
int ExportOGG::Export (AudacityProject * project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec * mixerSpec = NULL, Tags * metadata = NULL, int subformat = 0) [virtual]
called to export audio into a file.
Parameters:
selectedOnly Set to true if all tracks should be mixed, to false if only the selected tracks should be mixed and exported.
metadata A Tags object that will over-ride the one in *project and be used to tag the file that is exported.
subformat Control which of the multiple formats this exporter is capable of exporting should be used. Used where a single export plug-in handles a number of related formats, but they have separate entries in the Format drop-down list box. For example, the options to export to "Other PCM", "AIFF 16 Bit" and "WAV 16 Bit" are all the same libsndfile export plug-in, but with subformat set to 0, 1, and 2 respectively.
Reimplemented from ExportPlugin.
References FileIO::Close(), eProgressSuccess, FillComment(), floatSample, Mixer::GetBuffer(), AudacityProject::GetRate(), TrackList::GetTimeTrack(), AudacityProject::GetTracks(), TrackList::GetWaveTracks(), gPrefs, FileIO::IsOpened(), Mixer::MixGetCurrentTime(), FileIO::Output, Mixer::Process(), SAMPLES_PER_RUN, ProgressDialog::Update(), and FileIO::Write().
bool ExportOGG::FillComment (AudacityProject * project, vorbis_comment * comment, Tags * metadata) [private]
References Tags::GetFirst(), Tags::GetNext(), AudacityProject::GetTags(), and TAG_YEAR.
Referenced by Export().
The documentation for this class was generated from the following file:
ExportOGG.cpp