Audacity: VampEffect Class Reference
VampEffect Class Reference
#include <VampEffect.h>
Public Member Functions
VampEffect (Vamp::HostExt::PluginLoader::PluginKey key, int output, bool hasParameters, wxString name, wxString category=wxString())
virtual ~VampEffect ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool Init ()
virtual bool PromptUser ()
virtual bool Process ()
virtual void End ()
Private Member Functions
VampEffect (const VampEffect &)
VampEffect & operator= (const VampEffect &)
void AddFeatures (LabelTrack *track, Vamp::Plugin::FeatureSet &features)
Private Attributes
Vamp::HostExt::PluginLoader::PluginKey mKey
int mOutput
bool mHasParameters
wxString mName
double mRate
wxString mCategory
Vamp::Plugin * mPlugin
Constructor & Destructor Documentation
VampEffect::VampEffect (Vamp::HostExt::PluginLoader::PluginKey key, int output, bool hasParameters, wxString name, wxString category = wxString())
References ANALYZE_EFFECT, PLUGIN_EFFECT, and Effect::SetEffectFlags().
VampEffect::~VampEffect () [virtual]
References mPlugin.
VampEffect::VampEffect (const VampEffect &) [private]
Member Function Documentation
void VampEffect::AddFeatures (LabelTrack * track, Vamp::Plugin::FeatureSet & features) [private]
References LabelTrack::AddLabel(), label, LAT1CTOWX, and mOutput.
Referenced by Process().
void VampEffect::End () [virtual]
Reimplemented from Effect.
References mPlugin.
wxString VampEffect::GetEffectAction () [virtual]
Implements Effect.
References GetEffectName().
std::set< wxString > VampEffect::GetEffectCategories () [virtual]
References mCategory.
wxString VampEffect::GetEffectIdentifier () [virtual]
Reimplemented from Effect.
References LAT1CTOWX, and mKey.
wxString VampEffect::GetEffectName () [virtual]
Implements Effect.
References LAT1CTOWX, mHasParameters, and mName.
Referenced by GetEffectAction(), and Process().
bool VampEffect::Init () [virtual]
Reimplemented from Effect.
References TrackListCondIterator::First(), Track::GetLinked(), WaveTrack::GetRate(), mKey, mPlugin, Effect::mProjectRate, mRate, Effect::mTracks, TrackListCondIterator::Next(), and Track::Wave.
Referenced by Process().
VampEffect& VampEffect::operator= (const VampEffect &) [private]
bool VampEffect::Process () [virtual]
!! todo: retain parameters previously set
Implements Effect.
References TrackList::Add(), AddFeatures(), channels, TrackListCondIterator::First(), floatSample, WaveTrack::Get(), GetEffectName(), Track::GetLinked(), Track::GetName(), Effect::GetNumWaveGroups(), Effect::GetSamples(), Init(), Effect::mFactory, mPlugin, mRate, Effect::mTracks, TrackFactory::NewLabelTrack(), TrackListCondIterator::Next(), Track::SetName(), Effect::TrackGroupProgress(), Effect::TrackProgress(), and Track::Wave.
bool VampEffect::PromptUser () [virtual]
Reimplemented from Effect.
References mHasParameters, Effect::mParent, and mPlugin.
Member Data Documentation
wxString VampEffect::mCategory [private]
Referenced by GetEffectCategories().
bool VampEffect::mHasParameters [private]
Referenced by GetEffectName(), and PromptUser().
Vamp::HostExt::PluginLoader::PluginKey VampEffect::mKey [private]
Referenced by GetEffectIdentifier(), and Init().
wxString VampEffect::mName [private]
Referenced by GetEffectName().
int VampEffect::mOutput [private]
Referenced by AddFeatures().
Vamp::Plugin* VampEffect::mPlugin [private]
Referenced by End(), Init(), Process(), PromptUser(), and ~VampEffect().
double VampEffect::mRate [private]
Referenced by Init(), and Process().
The documentation for this class was generated from the following files:
VampEffect.h
VampEffect.cpp