Audacity: TrackListIterator Class Reference
TrackListIterator Class Reference
An iterator for a TrackList.
#include <Track.h>
Public Member Functions
TrackListIterator (TrackList *val=NULL)
virtual ~TrackListIterator ()
virtual Track * First (TrackList *val=NULL)
virtual Track * StartWith (Track *val)
virtual Track * Next (bool skiplinked=false)
virtual Track * Prev (bool skiplinked=false)
virtual Track * Last (bool skiplinked=false)
Track * ReplaceCurrent (Track *t)
Track * RemoveCurrent (bool deletetrack=false)
Protected Attributes
TrackList * l
TrackListNode * cur
Detailed Description
An iterator for a TrackList.
Constructor & Destructor Documentation
TrackListIterator::TrackListIterator (TrackList * val = NULL)
References cur, and l.
virtual TrackListIterator::~TrackListIterator () [inline, virtual]
Member Function Documentation
Track * TrackListIterator::First (TrackList * val = NULL) [virtual]
Reimplemented in TrackListCondIterator.
References cur, TrackList::head, l, and TrackListNode::t.
Referenced by SelectCommand::Apply(), AudacityProject::Clear(), ExportMultiple::CountTracksAndLabels(), UndoManager::Debug(), AudacityProject::DoAddLabel(), AudacityProject::DoZoomFitV(), TrackArtist::DrawTracks(), AudacityProject::EditByLabel(), AudacityProject::EditClipboardByLabel(), TrackPanel::EnsureVisible(), Exporter::ExamineTracks(), ExportMixerDialog::ExportMixerDialog(), ExportMultiple::ExportMultipleByTrack(), LabelDialog::FindAllLabels(), TrackPanelAx::FindTrack(), GetAllSeqBlocks(), TrackPanel::GetFirstSelectedTrack(), AudacityProject::GetFirstVisible(), TrackList::GetNumExportChannels(), AudacityProject::GetRegionsByLabel(), AudacityProject::GetUpdateFlags(), AudacityProject::HandleAlign(), TrackPanel::HandleLabelTrackMouseEvent(), AudacityProject::HandleMixAndRender(), AudacityProject::HandleTrackMute(), AudacityProject::HandleTrackSolo(), MixerBoard::HasSolo(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Init(), EffectAutoDuck::Init(), BatchCommands::IsMono(), ODTask::IsTaskAssociatedWithProject(), MixAndRender(), UndoManager::ModifyState(), AudacityProject::NearestZeroCrossing(), TranscriptionToolBar::OnAutomateSelection(), TranscriptionToolBar::OnCalibrate(), AudacityProject::OnCloseWindow(), AudacityProject::OnCollapseAllTracks(), AudacityProject::OnCopy(), AudacityProject::OnCursorTrackEnd(), AudacityProject::OnCursorTrackStart(), AudacityProject::OnCut(), AudacityProject::OnDisjoin(), AudacityProject::OnDuplicate(), AudacityProject::OnEffect(), TranscriptionToolBar::OnEndOff(), TranscriptionToolBar::OnEndOn(), AudacityProject::OnExpandAllTracks(), AudacityProject::OnExportLabels(), AudacityProject::OnExportMIDI(), AudacityProject::OnJoin(), AudacityProject::OnMuteAllTracks(), TrackPanel::OnNextTrack(), AudacityProject::OnPaste(), AudacityProject::OnPasteNewLabel(), TrackPanel::OnPrevTrack(), AudacityPrintout::OnPrintPage(), ControlToolBar::OnRecord(), AudacityProject::OnRemoveTracks(), AudacityProject::OnResample(), AudacityProject::OnSelectAll(), LabelDialog::OnSelectCell(), AudacityProject::OnSelectCursorEnd(), TranscriptionToolBar::OnSelectSilence(), TranscriptionToolBar::OnSelectSound(), AudacityProject::OnSelectStartCursor(), AudacityProject::OnSortName(), AudacityProject::OnSortTime(), AudacityProject::OnSplit(), AudacityProject::OnSplitCut(), AudacityProject::OnSplitDelete(), AudacityProject::OnSplitLabelsToTracks(), AudacityProject::OnSplitNew(), TranscriptionToolBar::OnStartOff(), TranscriptionToolBar::OnStartOn(), TrackPanel::OnTimer(), AudacityProject::OnTrim(), AudacityProject::OnUnMuteAllTracks(), AudacityProject::OpenFile(), ControlToolBar::PlayPlayRegion(), AudacityProject::PopState(), EffectSoundTouch::Process(), EffectSBSMS::Process(), EffectReverse::Process(), EffectRepeat::Process(), LadspaEffect::Process(), Generator::Process(), EffectChangeSpeed::Process(), AudioUnitEffect::Process(), EffectNyquist::ProcessOne(), UndoManager::PushState(), AudacityProject::RedrawProject(), Effect::ReplaceProcessedTracks(), AudacityProject::Save(), AudacityProject::SaveCompressedWaveTracks(), TrackPanel::SelectionHandleClick(), TrackPanel::SelectNone(), AudacityProject::SelectNone(), TrackPanel::SelectTracksByLabel(), GetProjectInfoCommand::SendTracksInfo(), SetProjectInfoCommand::SetAllTracksParam(), TrackPanelAx::SetFocus(), SnapManager::SnapManager(), TrackPanel::StartSlide(), StartWith(), TrackPanelAx::TrackNum(), LabelDialog::TransferDataFromWindow(), MixerBoard::UpdateTrackClusters(), TrackPanel::UpdateVRulerSize(), and AudacityProject::WriteXML().
Track * TrackListIterator::Last (bool skiplinked = false) [virtual]
Reimplemented in TrackListCondIterator, and TrackGroupIterator.
References cur, Track::GetLink(), Track::GetLinked(), l, TrackListNode::prev, TrackListNode::t, and TrackList::tail.
Referenced by AudacityProject::OnDuplicate(), TrackPanel::OnPrevTrack(), and AudacityProject::OnSplitNew().
Track * TrackListIterator::Next (bool skiplinked = false) [virtual]
Reimplemented in TrackListCondIterator, and TrackGroupIterator.
References cur, Track::GetLinked(), TrackListNode::next, and TrackListNode::t.
Referenced by SelectCommand::Apply(), AudacityProject::Clear(), ExportMultiple::CountTracksAndLabels(), AudacityProject::DoAddLabel(), AudacityProject::DoZoomFitV(), TrackArtist::DrawTracks(), AudacityProject::EditByLabel(), AudacityProject::EditClipboardByLabel(), TrackPanel::EnsureVisible(), Exporter::ExamineTracks(), ExportMixerDialog::ExportMixerDialog(), ExportMultiple::ExportMultipleByTrack(), LabelDialog::FindAllLabels(), TrackPanelAx::FindTrack(), GetAllSeqBlocks(), TrackPanel::GetFirstSelectedTrack(), AudacityProject::GetFirstVisible(), TrackList::GetNumExportChannels(), AudacityProject::GetRegionsByLabel(), AudacityProject::GetUpdateFlags(), AudacityProject::HandleAlign(), TrackPanel::HandleLabelTrackMouseEvent(), AudacityProject::HandleMixAndRender(), AudacityProject::HandleTrackMute(), AudacityProject::HandleTrackSolo(), MixerBoard::HasSolo(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Init(), EffectAutoDuck::Init(), BatchCommands::IsMono(), ODTask::IsTaskAssociatedWithProject(), MixAndRender(), UndoManager::ModifyState(), AudacityProject::NearestZeroCrossing(), TrackListCondIterator::Next(), TrackAndGroupIterator::NextGroup(), AudacityProject::OnCloseWindow(), AudacityProject::OnCollapseAllTracks(), AudacityProject::OnCopy(), AudacityProject::OnCursorTrackEnd(), AudacityProject::OnCursorTrackStart(), AudacityProject::OnCut(), AudacityProject::OnDisjoin(), AudacityProject::OnDuplicate(), AudacityProject::OnEffect(), AudacityProject::OnExpandAllTracks(), AudacityProject::OnExportLabels(), AudacityProject::OnExportMIDI(), AudacityProject::OnJoin(), AudacityProject::OnMuteAllTracks(), AudacityProject::OnPaste(), AudacityProject::OnPasteNewLabel(), TrackPanel::OnPrevTrack(), AudacityPrintout::OnPrintPage(), ControlToolBar::OnRecord(), AudacityProject::OnRemoveTracks(), AudacityProject::OnResample(), AudacityProject::OnSelectAll(), LabelDialog::OnSelectCell(), AudacityProject::OnSelectCursorEnd(), AudacityProject::OnSelectStartCursor(), AudacityProject::OnSplit(), AudacityProject::OnSplitCut(), AudacityProject::OnSplitDelete(), AudacityProject::OnSplitLabelsToTracks(), AudacityProject::OnSplitNew(), TrackPanel::OnTimer(), AudacityProject::OnTrim(), AudacityProject::OnUnMuteAllTracks(), AudacityProject::OpenFile(), ControlToolBar::PlayPlayRegion(), AudacityProject::PopState(), EffectSoundTouch::Process(), EffectSBSMS::Process(), EffectReverse::Process(), EffectRepeat::Process(), LadspaEffect::Process(), Generator::Process(), EffectChangeSpeed::Process(), AudioUnitEffect::Process(), EffectNyquist::ProcessOne(), UndoManager::PushState(), AudacityProject::RedrawProject(), AudacityProject::Save(), AudacityProject::SaveCompressedWaveTracks(), TrackPanel::SelectionHandleClick(), TrackPanel::SelectionHandleDrag(), TrackPanel::SelectNone(), AudacityProject::SelectNone(), TrackPanel::SelectTracksByLabel(), GetProjectInfoCommand::SendTracksInfo(), SetProjectInfoCommand::SetAllTracksParam(), SnapManager::SnapManager(), TrackPanel::StartSlide(), TrackPanelAx::TrackNum(), LabelDialog::TransferDataFromWindow(), MixerBoard::UpdateTrackClusters(), TrackPanel::UpdateVRulerSize(), and AudacityProject::WriteXML().
Track * TrackListIterator::Prev (bool skiplinked = false) [virtual]
Reimplemented in TrackListCondIterator, and TrackGroupIterator.
References cur, Track::GetLinked(), TrackListNode::prev, and TrackListNode::t.
Referenced by TrackListCondIterator::Prev().
Track * TrackListIterator::RemoveCurrent (bool deletetrack = false)
References cur, l, TrackListNode::next, TrackList::Remove(), and TrackListNode::t.
Referenced by AudacityProject::HandleMixAndRender(), AudacityProject::OnRemoveTracks(), AudacityProject::OnSortName(), AudacityProject::OnSortTime(), and Effect::ReplaceProcessedTracks().
Track * TrackListIterator::ReplaceCurrent (Track * t)
References cur, l, TrackList::RecalcPositions(), TrackList::ResizedEvent(), Track::SetOwner(), TrackListNode::t, and TrackList::UpdatedEvent().
Track * TrackListIterator::StartWith (Track * val) [virtual]
Reimplemented in TrackListCondIterator.
References cur, First(), Track::GetNode(), l, and TrackListNode::t.
Referenced by TrackArtist::DrawTracks(), and TrackPanel::SelectionHandleDrag().
Member Data Documentation
TrackListNode* TrackListIterator::cur [protected]
Referenced by TrackGroupIterator::First(), First(), TrackGroupIterator::Last(), Last(), TrackGroupIterator::Next(), Next(), TrackAndGroupIterator::NextGroup(), TrackGroupIterator::Prev(), Prev(), RemoveCurrent(), ReplaceCurrent(), StartWith(), and TrackListIterator().
TrackList* TrackListIterator::l [protected]
Referenced by TrackGroupIterator::First(), First(), TrackGroupIterator::Last(), Last(), RemoveCurrent(), ReplaceCurrent(), StartWith(), and TrackListIterator().
The documentation for this class was generated from the following files:
Track.h
Track.cpp