Audacity: EchoDialog Class Reference
EchoDialog Class Reference
EchoDialog used with EffectEcho.
#include <Echo.h>
Public Member Functions
EchoDialog (EffectEcho *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
Public Attributes
float delay
float decay
Private Member Functions
void OnPreview (wxCommandEvent &event)
Private Attributes
bool m_bLoopDetect
EffectEcho * m_pEffect
wxTextCtrl * m_pTextCtrl_Delay
wxTextCtrl * m_pTextCtrl_Decay
Detailed Description
EchoDialog used with EffectEcho.
Constructor & Destructor Documentation
EchoDialog::EchoDialog (EffectEcho * effect, wxWindow * parent)
Member Function Documentation
void EchoDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References decay, EffectEcho::decay, delay, EffectEcho::delay, m_pEffect, Effect::Preview(), and TransferDataFromWindow().
void EchoDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), m_pTextCtrl_Decay, m_pTextCtrl_Delay, ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartMultiColumn().
bool EchoDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References decay, delay, m_pTextCtrl_Decay, and m_pTextCtrl_Delay.
Referenced by OnPreview().
bool EchoDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References decay, delay, m_bLoopDetect, m_pTextCtrl_Decay, and m_pTextCtrl_Delay.
Member Data Documentation
float EchoDialog::decay
Referenced by OnPreview(), EffectEcho::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
float EchoDialog::delay
Referenced by OnPreview(), EffectEcho::PromptUser(), TransferDataFromWindow(), and TransferDataToWindow().
bool EchoDialog::m_bLoopDetect [private]
Referenced by TransferDataToWindow().
EffectEcho* EchoDialog::m_pEffect [private]
Referenced by OnPreview().
wxTextCtrl* EchoDialog::m_pTextCtrl_Decay [private]
Referenced by PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
wxTextCtrl* EchoDialog::m_pTextCtrl_Delay [private]
Referenced by PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
The documentation for this class was generated from the following files:
Echo.h
Echo.cpp