Audacity: ExportOGGOptions Class Reference
ExportOGGOptions Class Reference
Public Member Functions
ExportOGGOptions (wxWindow *parent, int format)
void PopulateOrExchange (ShuttleGui &S)
void OnOK (wxCommandEvent &event)
Private Attributes
int mOggQualityUnscaled
Constructor & Destructor Documentation
ExportOGGOptions::ExportOGGOptions (wxWindow * parent, int format)
References eIsCreatingFromPrefs, and gPrefs.
Member Function Documentation
void ExportOGGOptions::OnOK (wxCommandEvent & event)
References eIsSavingToPrefs, gPrefs, mOggQualityUnscaled, and PopulateOrExchange().
void ExportOGGOptions::PopulateOrExchange (ShuttleGui & S)
References ShuttleGui::AddStandardButtons(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), mOggQualityUnscaled, ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::TieSlider().
Referenced by OnOK().
Member Data Documentation
int ExportOGGOptions::mOggQualityUnscaled [private]
Referenced by OnOK(), and PopulateOrExchange().
The documentation for this class was generated from the following file:
ExportOGG.cpp