Audacity: ExportPCM Class Reference
ExportPCM Class Reference
Public Member Functions
ExportPCM ()
void Destroy ()
bool DisplayOptions (wxWindow *parent, int format=0)
int Export (AudacityProject *project, int channels, wxString fName, bool selectedOnly, double t0, double t1, MixerSpec *mixerSpec=NULL, Tags *metadata=NULL, int subformat=0)
wxString GetExtension (int index=0)
Return the (first) file name extension for the sub-format.
Private Member Functions
bool AddStrings (AudacityProject *project, SNDFILE *sf, Tags *tags)
void AddID3Chunk (wxString fName, Tags *tags)
Constructor & Destructor Documentation
ExportPCM::ExportPCM ()
References ExportPlugin::AddExtension(), ExportPlugin::AddFormat(), ExportPlugin::SetCanMetaData(), ExportPlugin::SetDescription(), ExportPlugin::SetExtensions(), ExportPlugin::SetFormat(), ExportPlugin::SetMaxChannels(), sf_get_all_extensions(), and sf_header_extension().
Member Function Documentation
void ExportPCM::AddID3Chunk (wxString fName, Tags * tags) [private]
References Tags::GetFirst(), Tags::GetNext(), id3_frame_new(), name, TAG_ALBUM, TAG_ARTIST, TAG_COMMENTS, TAG_GENRE, TAG_TITLE, TAG_TRACK, and TAG_YEAR.
Referenced by Export().
bool ExportPCM::AddStrings (AudacityProject * project, SNDFILE * sf, Tags * tags) [private]
References Tags::GetTag(), Tags::HasTag(), TAG_ARTIST, TAG_COMMENTS, TAG_TITLE, and TAG_YEAR.
Referenced by Export().
void ExportPCM::Destroy () [virtual]
Reimplemented from ExportPlugin.
bool ExportPCM::DisplayOptions (wxWindow * parent, int format = 0) [virtual]
Parameters:
format The same information as the subformat argument to the Export method. Controls use of pre-defined export settings.
Reimplemented from ExportPlugin.
int ExportPCM::Export (AudacityProject * project, int numChannels, wxString fName, bool selectionOnly, double t0, double t1, MixerSpec * mixerSpec = NULL, Tags * metadata = NULL, int subformat = 0) [virtual]
Parameters:
subformat Control whether we are doing a "preset" export to a popular file type, or giving the user full control over libsndfile. Set to 0 (default) gives full control, 1 gives 16-bit AIFF, 2 gives 16-bit WAV 3 gives a GSM 6.10 WAV file
Reimplemented from ExportPlugin.
References AddID3Chunk(), AddStrings(), eProgressSuccess, floatSample, Mixer::GetBuffer(), AudacityProject::GetRate(), AudacityProject::GetTags(), TrackList::GetTimeTrack(), AudacityProject::GetTracks(), TrackList::GetWaveTracks(), int16Sample, ODManager::LockLibSndFileMutex(), Mixer::MixGetCurrentTime(), Mixer::Process(), ReadExportFormatPref(), sf_header_name(), sf_subtype_more_than_16_bits(), and ODManager::UnlockLibSndFileMutex().
wxString ExportPCM::GetExtension (int index = 0) [virtual]
Return the (first) file name extension for the sub-format.
Parameters:
index The sub-format for which the extension is wanted
Reimplemented from ExportPlugin.
References ReadExportFormatPref(), and sf_header_extension().
The documentation for this class was generated from the following file:
ExportPCM.cpp