Audacity: Mixer Class Reference
Mixer Class Reference
Functions for doing the mixdown of the tracks.
#include <Mix.h>
Public Member Functions
Mixer (int numInputTracks, WaveTrack **inputTracks, TimeTrack *timeTrack, double startTime, double stopTime, int numOutChannels, int outBufferSize, bool outInterleaved, double outRate, sampleFormat outFormat, bool highQuality=true, MixerSpec *mixerSpec=NULL)
virtual ~Mixer ()
void ApplyTrackGains (bool apply=true)
sampleCount Process (sampleCount maxSamples)
void Restart ()
void Reposition (double t)
double MixGetCurrentTime ()
Current time in seconds.
samplePtr GetBuffer ()
Retrieve the main buffer or the interleaved buffer.
samplePtr GetBuffer (int channel)
Retrieve one of the non-interleaved buffers.
Private Member Functions
void Clear ()
sampleCount MixSameRate (int *channelFlags, WaveTrack *src, sampleCount *pos)
sampleCount MixVariableRates (int *channelFlags, WaveTrack *track, sampleCount *pos, float *queue, int *queueStart, int *queueLen, Resample *SRC)
Private Attributes
int mNumInputTracks
WaveTrack ** mInputTrack
TimeTrack * mTimeTrack
sampleCount * mSamplePos
bool mApplyTrackGains
float * mGains
double * mEnvValues
double mT
double mT0
double mT1
Resample ** mSRC
float ** mSampleQueue
int * mQueueStart
int * mQueueLen
int mQueueMaxLen
int mProcessLen
MixerSpec * mMixerSpec
int mMaxOut
int mNumChannels
int mNumBuffers
int mBufferSize
int mInterleavedBufferSize
sampleFormat mFormat
bool mInterleaved
samplePtr * mBuffer
samplePtr * mTemp
float * mFloatBuffer
double mRate
Detailed Description
Functions for doing the mixdown of the tracks.
Constructor & Destructor Documentation
Mixer::Mixer (int numInputTracks, WaveTrack ** inputTracks, TimeTrack * timeTrack, double startTime, double stopTime, int numOutChannels, int outBufferSize, bool outInterleaved, double outRate, sampleFormat outFormat, bool highQuality = true, MixerSpec * mixerSpec = NULL)
References floatSample, MixerSpec::GetNumChannels(), MixerSpec::GetNumTracks(), TimeTrack::GetRangeLower(), TimeTrack::GetRangeUpper(), WaveTrack::GetRate(), mApplyTrackGains, mBuffer, mBufferSize, mEnvValues, mFloatBuffer, mFormat, mGains, mInputTrack, mInterleaved, mInterleavedBufferSize, mMixerSpec, mNumBuffers, mNumChannels, mNumInputTracks, mProcessLen, mQueueLen, mQueueMaxLen, mQueueStart, mRate, mSamplePos, mSampleQueue, mSRC, mT, mT0, mT1, mTemp, mTimeTrack, NewSamples(), and WaveTrack::TimeToLongSamples().
Mixer::~Mixer () [virtual]
References DeleteSamples(), mBuffer, mEnvValues, mFloatBuffer, mGains, mInputTrack, mNumBuffers, mNumInputTracks, mQueueLen, mQueueStart, mSamplePos, mSampleQueue, mSRC, and mTemp.
Member Function Documentation
void Mixer::ApplyTrackGains (bool apply = true)
References mApplyTrackGains.
Referenced by AudioIO::StartStream().
void Mixer::Clear () [private]
References floatSample, mInterleavedBufferSize, mNumBuffers, mTemp, and SAMPLE_SIZE.
Referenced by Process().
samplePtr Mixer::GetBuffer (int channel)
Retrieve one of the non-interleaved buffers.
References mBuffer.
samplePtr Mixer::GetBuffer ()
Retrieve the main buffer or the interleaved buffer.
References mBuffer.
Referenced by ExportPCM::Export(), ExportOGG::Export(), ExportMP3::Export(), ExportMP2::Export(), ExportFLAC::Export(), ExportFFmpeg::Export(), ExportCL::Export(), AudioIO::FillBuffers(), and MixAndRender().
double Mixer::MixGetCurrentTime ()
Current time in seconds.
References mT.
Referenced by ExportPCM::Export(), ExportOGG::Export(), ExportMP3::Export(), ExportMP2::Export(), ExportFLAC::Export(), ExportFFmpeg::Export(), ExportCL::Export(), and MixAndRender().
sampleCount Mixer::MixSameRate (int * channelFlags, WaveTrack * src, sampleCount * pos) [private]
References floatSample, WaveTrack::Get(), WaveTrack::GetChannelGain(), WaveTrack::GetEndTime(), WaveTrack::GetEnvelopeValues(), WaveTrack::GetRate(), mApplyTrackGains, mEnvValues, mFloatBuffer, mGains, mInterleaved, MixBuffers(), mMaxOut, mNumChannels, mRate, mT1, and mTemp.
Referenced by Process().
sampleCount Mixer::MixVariableRates (int * channelFlags, WaveTrack * track, sampleCount * pos, float * queue, int * queueStart, int * queueLen, Resample * SRC) [private]
References floatSample, WaveTrack::Get(), WaveTrack::GetChannelGain(), WaveTrack::GetEndTime(), TimeTrack::GetEnvelope(), WaveTrack::GetEnvelopeValues(), TimeTrack::GetRangeLower(), TimeTrack::GetRangeUpper(), WaveTrack::GetRate(), Envelope::GetValue(), mApplyTrackGains, mEnvValues, mFloatBuffer, mGains, mInterleaved, MixBuffers(), mMaxOut, mNumChannels, mProcessLen, mQueueMaxLen, mRate, mT1, mTemp, mTimeTrack, Resample::Process(), SAMPLE_SIZE, and WaveTrack::TimeToLongSamples().
Referenced by Process().
sampleCount Mixer::Process (sampleCount maxSamples)
Process a maximum of 'maxSamples' samples and put them into a buffer which can be retrieved by calling GetBuffer(). Returns number of output samples, or 0, if there are no more samples that must be processed.
References Clear(), CopySamples(), floatSample, Track::GetChannel(), WaveTrack::GetRate(), Track::LeftChannel, mBuffer, mFormat, mInputTrack, mInterleaved, MixSameRate(), MixVariableRates(), MixerSpec::mMap, mMaxOut, mMixerSpec, mNumBuffers, mNumChannels, mNumInputTracks, Track::MonoChannel, mQueueLen, mQueueStart, mRate, mSamplePos, mSampleQueue, mSRC, mT, mT1, mTemp, mTimeTrack, and Track::RightChannel.
Referenced by ExportPCM::Export(), ExportOGG::Export(), ExportMP3::Export(), ExportMP2::Export(), ExportFLAC::Export(), ExportFFmpeg::Export(), ExportCL::Export(), AudioIO::FillBuffers(), and MixAndRender().
void Mixer::Reposition (double t)
Reposition processing to absolute time next time Process() is called.
References mInputTrack, mNumInputTracks, mQueueLen, mQueueStart, mSamplePos, mT, mT0, mT1, and WaveTrack::TimeToLongSamples().
Referenced by audacityAudioCallback().
void Mixer::Restart ()
Restart processing at beginning of buffer next time Process() is called.
References mInputTrack, mNumInputTracks, mQueueLen, mQueueStart, mSamplePos, mT, and mT0.
Member Data Documentation
bool Mixer::mApplyTrackGains [private]
Referenced by ApplyTrackGains(), Mixer(), MixSameRate(), and MixVariableRates().
samplePtr* Mixer::mBuffer [private]
Referenced by GetBuffer(), Mixer(), Process(), and ~Mixer().
int Mixer::mBufferSize [private]
Referenced by Mixer().
double* Mixer::mEnvValues [private]
Referenced by Mixer(), MixSameRate(), MixVariableRates(), and ~Mixer().
float* Mixer::mFloatBuffer [private]
Referenced by Mixer(), MixSameRate(), MixVariableRates(), and ~Mixer().
sampleFormat Mixer::mFormat [private]
Referenced by Mixer(), and Process().
float* Mixer::mGains [private]
Referenced by Mixer(), MixSameRate(), MixVariableRates(), and ~Mixer().
WaveTrack** Mixer::mInputTrack [private]
Referenced by Mixer(), Process(), Reposition(), Restart(), and ~Mixer().
bool Mixer::mInterleaved [private]
Referenced by Mixer(), MixSameRate(), MixVariableRates(), and Process().
int Mixer::mInterleavedBufferSize [private]
Referenced by Clear(), and Mixer().
int Mixer::mMaxOut [private]
Referenced by MixSameRate(), MixVariableRates(), and Process().
MixerSpec* Mixer::mMixerSpec [private]
Referenced by Mixer(), and Process().
int Mixer::mNumBuffers [private]
Referenced by Clear(), Mixer(), Process(), and ~Mixer().
int Mixer::mNumChannels [private]
Referenced by Mixer(), MixSameRate(), MixVariableRates(), and Process().
int Mixer::mNumInputTracks [private]
Referenced by Mixer(), Process(), Reposition(), Restart(), and ~Mixer().
int Mixer::mProcessLen [private]
Referenced by Mixer(), and MixVariableRates().
int* Mixer::mQueueLen [private]
Referenced by Mixer(), Process(), Reposition(), Restart(), and ~Mixer().
int Mixer::mQueueMaxLen [private]
Referenced by Mixer(), and MixVariableRates().
int* Mixer::mQueueStart [private]
Referenced by Mixer(), Process(), Reposition(), Restart(), and ~Mixer().
double Mixer::mRate [private]
Referenced by Mixer(), MixSameRate(), MixVariableRates(), and Process().
sampleCount* Mixer::mSamplePos [private]
Referenced by Mixer(), Process(), Reposition(), Restart(), and ~Mixer().
float** Mixer::mSampleQueue [private]
Referenced by Mixer(), Process(), and ~Mixer().
Resample** Mixer::mSRC [private]
Referenced by Mixer(), Process(), and ~Mixer().
double Mixer::mT [private]
Referenced by Mixer(), MixGetCurrentTime(), Process(), Reposition(), and Restart().
double Mixer::mT0 [private]
Referenced by Mixer(), Reposition(), and Restart().
double Mixer::mT1 [private]
Referenced by Mixer(), MixSameRate(), MixVariableRates(), Process(), and Reposition().
samplePtr* Mixer::mTemp [private]
Referenced by Clear(), Mixer(), MixSameRate(), MixVariableRates(), Process(), and ~Mixer().
TimeTrack* Mixer::mTimeTrack [private]
Referenced by Mixer(), MixVariableRates(), and Process().
The documentation for this class was generated from the following files:
Mix.h
Mix.cpp