Audacity: Track Class Reference
Track Class Reference
Fundamental data object of Audacity, placed in the TrackPanel. Classes derived form it include the WaveTrack, NoteTrack, LabelTrack and TimeTrack.
#include <Track.h>
Public Types
enum { LeftChannel = 0, RightChannel = 1, MonoChannel = 2 }
enum TrackKindEnum {
None, Wave, Note, Label,
Time, All
}
Public Member Functions
virtual int GetMinimizedHeight () const
int GetActualHeight ()
int GetIndex () const
void SetIndex (int index)
int GetY () const
void SetY (int y)
int GetHeight () const
void SetHeight (int h)
bool GetMinimized () const
void SetMinimized (bool isMinimized)
Track * GetLink () const
const TrackListNode * GetNode ()
void SetOwner (TrackList *list, TrackListNode *node)
Track (DirManager *projDirManager)
Track (const Track &orig)
virtual ~Track ()
void Init (const Track &orig)
virtual Track * Duplicate ()=0
virtual void Merge (const Track &orig)
wxString GetName () const
void SetName (wxString n)
wxString GetDefaultName () const
void SetDefaultName (wxString n)
bool GetSelected () const
bool GetMute () const
bool GetLinked () const
bool GetSolo () const
void SetSelected (bool s)
void SetMute (bool m)
void SetLinked (bool l)
void SetSolo (bool s)
int GetChannel () const
virtual double GetOffset ()
void Offset (double t)
virtual void SetOffset (double o)
void SetChannel (int c)
DirManager * GetDirManager () const
virtual bool Cut (double t0, double t1, Track **dest)
virtual bool Copy (double t0, double t1, Track **dest)
virtual bool Clear (double t0, double t1)
virtual bool Paste (double t, Track *src)
virtual bool SyncAdjust (double oldT1, double newT1)
virtual bool Silence (double t0, double t1)
virtual bool InsertSilence (double t, double len)
virtual int GetKind () const
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)=0
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)=0
virtual void WriteXML (XMLWriter &xmlFile)=0
virtual bool GetErrorOpening ()
virtual double GetStartTime ()
virtual double GetEndTime ()
bool IsSynchroSelected ()
Public Attributes
wxSize vrulerSize
Protected Attributes
TrackList * mList
TrackListNode * mNode
int mIndex
int mY
int mHeight
wxString mName
wxString mDefaultName
bool mSelected
bool mLinked
bool mMinimized
int mChannel
double mOffset
bool mMute
bool mSolo
DirManager * mDirManager
Detailed Description
Fundamental data object of Audacity, placed in the TrackPanel. Classes derived form it include the WaveTrack, NoteTrack, LabelTrack and TimeTrack.
Member Enumeration Documentation
anonymous enum
Enumerator:
LeftChannel
RightChannel
MonoChannel
enum Track::TrackKindEnum
Enumerator:
None
Wave
Note
Label
Time
All
Constructor & Destructor Documentation
Track::Track (DirManager * projDirManager)
References mChannel, mDirManager, mHeight, mIndex, mLinked, mList, mMinimized, mMute, mNode, mOffset, MonoChannel, mSelected, mSolo, mY, and DirManager::Ref().
Track::Track (const Track & orig)
References Init(), mDirManager, mIndex, mList, mNode, mOffset, and mY.
Track::~Track () [virtual]
References DirManager::Deref(), and mDirManager.
Member Function Documentation
virtual bool Track::Clear (double t0, double t1) [inline, virtual]
Reimplemented in LabelTrack, NoteTrack, and WaveTrack.
Referenced by AudacityProject::Clear(), AudacityProject::OnCut(), AudacityProject::OnPaste(), ControlToolBar::SetupCutPreviewTracks(), and SyncAdjust().
virtual bool Track::Copy (double t0, double t1, Track ** dest) [inline, virtual]
Referenced by AudacityProject::OnCopy(), AudacityProject::OnCut(), AudacityProject::OnDuplicate(), AudacityProject::OnSplitCut(), and AudacityProject::OnSplitLabelsToTracks().
virtual bool Track::Cut (double t0, double t1, Track ** dest) [inline, virtual]
Referenced by AudacityProject::OnCut(), and SyncAdjust().
virtual Track* Track::Duplicate () [pure virtual]
Implemented in LabelTrack, NoteTrack, TimeTrack, and WaveTrack.
Referenced by UndoManager::ModifyState(), AudacityProject::OpenFile(), AudacityProject::PopState(), UndoManager::PushState(), AudacityProject::Save(), and ControlToolBar::SetupCutPreviewTracks().
int Track::GetActualHeight () [inline]
Referenced by WaveTrack::WriteXML(), TimeTrack::WriteXML(), AudacityProject::WriteXML(), and LabelTrack::WriteXML().
int Track::GetChannel () const [inline]
Referenced by audacityAudioCallback(), AudacityProject::EditClipboardByLabel(), Exporter::ExamineTracks(), ExportMultiple::ExportMultipleByTrack(), TrackList::GetNumExportChannels(), MixAndRender(), AudacityProject::OnCopy(), AudacityProject::OnCut(), AudacityProject::OnPaste(), AudacityProject::OnSplitCut(), TrackPanel::OnTrackMenu(), AudacityProject::OpenFile(), EffectSimpleMono::Process(), EffectNormalize::Process(), Mixer::Process(), EffectTwoPassSimpleMono::ProcessPass(), and TrackPanel::TrackSubText().
wxString Track::GetDefaultName () const [inline]
Referenced by WaveTrack::Init(), TimeTrack::Init(), LabelTrack::LabelTrack(), NoteTrack::NoteTrack(), TimeTrack::TimeTrack(), and WaveTrack::WaveTrack().
DirManager* Track::GetDirManager () const [inline]
Referenced by LabelTrack::Copy(), and LabelTrack::SplitCut().
virtual double Track::GetEndTime () [inline, virtual]
Reimplemented in LabelTrack, NoteTrack, TimeTrack, and WaveTrack.
Referenced by TrackPanel::AddClipsToCaptured(), WaveTrack::ClearAndPaste(), Exporter::ExamineTracks(), ExportMultiple::ExportMultipleByTrack(), TrackList::GetEndTime(), AudacityProject::HandleAlign(), MixAndRender(), AudacityProject::OnCursorTrackEnd(), AudacityProject::OnEffect(), AudacityProject::OnSelectCursorEnd(), AudacityProject::OnSplitLabelsToTracks(), AudacityProject::SaveCompressedWaveTracks(), TrackPanel::SelectTrackLength(), and SyncAdjust().
virtual bool Track::GetErrorOpening () [inline, virtual]
Reimplemented in WaveTrack.
Referenced by AudacityProject::OpenFile().
int Track::GetHeight () const
References GetMinimizedHeight(), mHeight, and mMinimized.
Referenced by VisibleTrackIterator::Condition(), AudacityProject::DoZoomFitV(), TimeTrack::Draw(), TrackPanel::DrawBordersAroundTrack(), TrackPanel::DrawEverythingElse(), TrackPanel::DrawOutsideOfTrack(), TrackArtist::DrawTracks(), TrackPanel::EnsureVisible(), TrackPanel::FindTrack(), TrackPanel::FindTrackRect(), TrackList::GetGroupHeight(), TrackList::GetHeight(), TrackPanel::HandleResizeClick(), TrackPanel::HandleResizeDrag(), TrackPanel::HandleSampleEditingClick(), TrackPanel::HandleSampleEditingDrag(), TrackPanel::HandleVZoomButtonUp(), AudacityPrintout::OnPrintPage(), ControlToolBar::OnRecord(), TrackList::RecalcPositions(), TrackPanel::RefreshTrack(), AudacityProject::UpdateFirstVisible(), and TrackPanel::UpdateTrackVRuler().
int Track::GetIndex () const
References mIndex.
Referenced by TrackInfo::DrawSliders(), TrackList::GetCount(), TrackPanel::HandleSliders(), TrackPanel::OnTrackGain(), TrackPanel::OnTrackGainDec(), TrackPanel::OnTrackGainInc(), TrackPanel::OnTrackPan(), TrackPanel::OnTrackPanLeft(), TrackPanel::OnTrackPanRight(), TrackList::RecalcPositions(), and TrackPanel::SelectionHandleDrag().
virtual int Track::GetKind () const [inline, virtual]
Reimplemented in LabelTrack, NoteTrack, TimeTrack, and WaveTrack.
Referenced by TrackPanel::AddClipsToCaptured(), AudacityProject::Clear(), TrackListOfKindIterator::Condition(), ExportMultiple::CountTracksAndLabels(), Effect::CountWaveTracks(), TrackPanel::DetermineToolToUse(), AudacityProject::DoAddLabel(), AudacityProject::DoZoomFitV(), TrackPanel::DrawOutside(), TrackArtist::DrawTrack(), TrackArtist::DrawVRuler(), AudacityProject::EditByLabel(), AudacityProject::EditClipboardByLabel(), Exporter::ExamineTracks(), ExportMultiple::ExportMultipleByTrack(), TrackPanel::ExtendSelection(), LabelDialog::FindAllLabels(), TrackGroupIterator::First(), TrackPanel::ForwardEventToEnvelope(), GetAllSeqBlocks(), TrackList::GetNoteTrackArray(), TrackList::GetNumExportChannels(), AudacityProject::GetRegionsByLabel(), AudacityProject::GetTime(), TrackList::GetTimeTrack(), AudacityProject::GetUpdateFlags(), TrackList::GetWaveTrackArray(), TrackList::GetWaveTracks(), TrackPanel::HandleCursor(), TrackPanel::HandleEnvelope(), TrackPanel::HandleLabelClick(), TrackPanel::HandleLabelTrackMouseEvent(), AudacityProject::HandleMixAndRender(), TrackPanel::HandleRearrange(), TrackPanel::HandleSelect(), TrackPanel::HandleTrackSpecificMouseEvent(), TrackPanel::HandleVZoomButtonUp(), TrackPanel::HandleVZoomClick(), EffectAutoDuck::Init(), TrackPanel::IsSampleEditingPossible(), ODTask::IsTaskAssociatedWithProject(), TrackGroupIterator::Last(), WaveTrack::Merge(), MixAndRender(), AudacityProject::NearestZeroCrossing(), TrackGroupIterator::Next(), TrackAndGroupIterator::NextGroup(), TrackPanel::OnCaptureKey(), TrackPanel::OnChangeOctave(), TrackPanel::OnChar(), AudacityProject::OnCloseWindow(), AudacityProject::OnCopy(), AudacityProject::OnCut(), AudacityProject::OnDisjoin(), AudacityProject::OnEffect(), AudacityProject::OnExportLabels(), AudacityProject::OnExportMIDI(), TrackPanel::OnFormatChange(), AudacityProject::OnJoin(), TrackPanel::OnKeyDown(), TrackPanel::OnMergeStereo(), TrackPanel::OnMoveTrack(), AudacityProject::OnPaste(), TrackPanel::OnRateChange(), TrackPanel::OnRateOther(), AudacityProject::OnRemoveTracks(), AudacityProject::OnResample(), TrackPanel::OnSetDisplay(), TrackPanel::OnSetName(), AudacityProject::OnSortTime(), AudacityProject::OnSplitCut(), AudacityProject::OnSplitDelete(), AudacityProject::OnSplitLabelsToTracks(), TrackPanel::OnTrackGain(), TrackPanel::OnTrackGainDec(), TrackPanel::OnTrackGainInc(), TrackPanel::OnTrackMenu(), TrackPanel::OnTrackMute(), TrackPanel::OnTrackPan(), TrackPanel::OnTrackPanLeft(), TrackPanel::OnTrackPanRight(), TrackPanel::OnTrackSolo(), AudacityProject::OnTrim(), AudacityProject::OpenFile(), WaveTrack::Paste(), NoteTrack::Paste(), LabelTrack::Paste(), LabelTrack::PasteOver(), AudacityProject::PopState(), TrackGroupIterator::Prev(), EffectSoundTouch::Process(), EffectSBSMS::Process(), EffectReverse::Process(), Generator::Process(), EffectChangeSpeed::Process(), EffectAutoDuck::Process(), AudacityProject::RedrawProject(), TrackPanel::RemoveTrack(), AudacityProject::Save(), AudacityProject::SaveCompressedWaveTracks(), TrackPanel::SelectionHandleClick(), TrackPanel::SelectNone(), TrackPanel::SetCursorAndTipWhenInLabel(), TrackPanel::SetCursorAndTipWhenSelectTool(), TrackPanel::SetFocusedTrack(), SetProjectInfoCommand::setMute(), SetProjectInfoCommand::setSolo(), SnapManager::SnapManager(), TrackPanel::SplitStereo(), TrackPanel::StartSlide(), LabelDialog::TransferDataFromWindow(), MixerBoard::UpdateTrackClusters(), TrackArtist::UpdateVRuler(), and AudacityProject::WriteXML().
Track * Track::GetLink () const
References GetLinked(), mLinked, mNode, TrackListNode::next, TrackListNode::prev, and TrackListNode::t.
Referenced by TrackArtist::DrawTracks(), TrackPanel::FindTrackRect(), TrackPanel::ForwardEventToWaveTrackEnvelope(), TrackList::GetGroupHeight(), TrackList::GetLink(), GetMinimizedHeight(), TrackList::GetPrev(), AudacityProject::HandleMixAndRender(), TrackPanel::HandleResizeClick(), TrackPanel::HandleResizeDrag(), TrackPanelAx::IsFocused(), TrackListIterator::Last(), TrackPanel::OnMergeStereo(), TrackPanel::OnSetDisplay(), AudacityProject::OpenFile(), TrackPanel::RefreshTrack(), TrackPanel::RemoveTrack(), TrackPanel::SelectTrackLength(), TrackPanel::SetFocusedTrack(), ControlToolBar::SetupCutPreviewTracks(), TrackPanel::SplitStereo(), TrackList::Swap(), and TrackPanel::UpdateTrackVRuler().
bool Track::GetLinked () const [inline]
Referenced by audacityAudioCallback(), EffectStereoToMono::CheckWhetherSkipEffect(), ExportMultiple::CountTracksAndLabels(), Effect::CountWaveTracks(), TrackPanel::DoSlide(), TrackPanel::DrawBordersAroundTrack(), TrackPanel::DrawEverythingElse(), TrackPanel::DrawOutsideOfTrack(), TrackArtist::DrawTracks(), AudacityProject::EditClipboardByLabel(), TrackPanel::EnsureVisible(), ExportMultiple::ExportMultipleByTrack(), TrackPanel::FindTrackRect(), GetLink(), TrackList::GetNext(), TrackList::GetPrev(), AudacityProject::GetUpdateFlags(), TrackPanel::HandleCursor(), AudacityProject::HandleMixAndRender(), TrackPanel::HandleResizeClick(), TrackPanel::HandleResizeDrag(), AudacityProject::HandleTrackMute(), AudacityProject::HandleTrackSolo(), VampEffect::Init(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Init(), LadspaEffect::Init(), BatchCommands::IsMono(), TrackListIterator::Last(), TrackPanel::MoveClipToTrack(), TrackListIterator::Next(), AudacityProject::OnCopy(), AudacityProject::OnCut(), AudacityProject::OnPaste(), AudacityProject::OnSplitCut(), AudacityProject::OnSplitLabelsToTracks(), TrackPanel::OnTrackMenu(), AudacityProject::OpenFile(), TrackListIterator::Prev(), VampEffect::Process(), EffectStereoToMono::Process(), EffectSoundTouch::Process(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Process(), EffectSBSMS::Process(), LadspaEffect::Process(), AudioUnitEffect::Process(), TrackPanel::RefreshTrack(), AudacityProject::SaveCompressedWaveTracks(), TrackList::Select(), TrackPanel::SetFocusedTrack(), TrackList::Swap(), GetProjectInfoCommand::testLinked(), TrackPanel::TrackSubText(), MixerBoard::UpdateTrackClusters(), and AudacityProject::WriteXML().
bool Track::GetMinimized () const
References mMinimized.
Referenced by TrackPanel::DrawOutside(), TrackPanel::HandleMinimizing(), TrackPanel::HandleResizeDrag(), TrackPanel::MinimizeFunc(), WaveTrack::WriteXML(), TimeTrack::WriteXML(), AudacityProject::WriteXML(), and LabelTrack::WriteXML().
int Track::GetMinimizedHeight () const [virtual]
References GetLink().
Referenced by GetHeight(), and TrackPanel::HandleResizeDrag().
bool Track::GetMute () const [inline]
Referenced by audacityAudioCallback(), TrackInfo::DrawMuteSolo(), TrackArtist::DrawTrack(), Exporter::ExamineTracks(), TrackList::GetWaveTracks(), AudacityProject::HandleTrackMute(), AudacityProject::SaveCompressedWaveTracks(), GetProjectInfoCommand::testMute(), MixerTrackCluster::UpdateMeter(), MixerTrackCluster::UpdateMute(), and AudacityProject::WriteXML().
wxString Track::GetName () const [inline]
Referenced by LabelDialog::AddLabels(), SelectCommand::Apply(), CompareAudioCommand::Apply(), TrackInfo::DrawTitleBar(), AudacityProject::EditClipboardByLabel(), ExportMultiple::ExportMultipleByTrack(), MixerBoard::GetMusicalInstrumentBitmap(), AudacityProject::HandleMixAndRender(), TrackPanel::HandleRearrange(), WaveTrack::Init(), TimeTrack::Init(), TrackPanel::OnChannelChange(), AudacityProject::OnCopy(), AudacityProject::OnCut(), TrackPanel::OnFormatChange(), TrackPanel::OnMergeStereo(), TrackPanel::OnMoveTrack(), AudacityProject::OnPaste(), TrackPanel::OnSetName(), AudacityProject::OnSortName(), AudacityProject::OnSplitCut(), VampEffect::Process(), TrackPanel::RemoveTrack(), AudacityProject::SaveCompressedWaveTracks(), TrackPanel::SetRate(), TrackPanel::SplitStereo(), and MixerTrackCluster::UpdateName().
const TrackListNode * Track::GetNode ()
References mNode.
Referenced by TrackGroupIterator::First(), TrackList::GetNext(), TrackList::GetPrev(), TrackList::MoveDown(), TrackList::MoveUp(), TrackList::Remove(), TrackList::Replace(), TrackList::Select(), TrackListIterator::StartWith(), and TrackList::Swap().
virtual double Track::GetOffset () [inline, virtual]
Reimplemented in TimeTrack, and WaveTrack.
Referenced by Exporter::ExamineTracks(), TrackList::GetMinOffset(), AudacityProject::HandleAlign(), AudacityProject::OnCursorTrackStart(), AudacityProject::OnDuplicate(), AudacityProject::OnSelectStartCursor(), AudacityProject::OnSplitLabelsToTracks(), AudacityProject::OnSplitNew(), TrackPanel::SelectTrackLength(), and AudacityProject::WriteXML().
bool Track::GetSelected () const [inline]
Referenced by AudacityProject::Clear(), SelectedTrackListOfKindIterator::Condition(), Effect::CountWaveTracks(), AudacityProject::DoAddLabel(), LabelTrack::Draw(), TrackArtist::DrawClipSpectrum(), TrackArtist::DrawClipWaveform(), TrackArtist::DrawLabelTrack(), TrackInfo::DrawMinimize(), TrackInfo::DrawMuteSolo(), TrackArtist::DrawNoteTrack(), TrackPanel::DrawOutside(), TrackInfo::DrawSliders(), TrackInfo::DrawTitleBar(), AudacityProject::EditByLabel(), AudacityProject::EditClipboardByLabel(), Exporter::ExamineTracks(), ExportMultiple::ExportMultipleByTrack(), TrackPanel::GetFirstSelectedTrack(), TrackList::GetNoteTrackArray(), TrackList::GetNumExportChannels(), AudacityProject::GetRegionsByLabel(), AudacityProject::GetUpdateFlags(), TrackList::GetWaveTrackArray(), TrackList::GetWaveTracks(), AudacityProject::HandleAlign(), TrackPanel::HandleLabelClick(), AudacityProject::HandleMixAndRender(), MixerTrackCluster::HandleSelect(), EffectAutoDuck::Init(), IsSynchroSelected(), MixAndRender(), AudacityProject::NearestZeroCrossing(), AudacityProject::OnCopy(), AudacityProject::OnCursorTrackEnd(), AudacityProject::OnCursorTrackStart(), AudacityProject::OnCut(), AudacityProject::OnDisjoin(), AudacityProject::OnDuplicate(), AudacityProject::OnEffect(), AudacityProject::OnExportMIDI(), AudacityProject::OnJoin(), TrackPanel::OnNextTrack(), MixerTrackCluster::OnPaint(), AudacityProject::OnPaste(), TrackPanel::OnPrevTrack(), AudacityProject::OnRemoveTracks(), AudacityProject::OnResample(), AudacityProject::OnSelectCursorEnd(), AudacityProject::OnSelectStartCursor(), AudacityProject::OnSplit(), AudacityProject::OnSplitCut(), AudacityProject::OnSplitDelete(), AudacityProject::OnSplitLabelsToTracks(), TrackPanel::OnToggle(), AudacityProject::OnTrim(), EffectStereoToMono::Process(), EffectSoundTouch::Process(), EffectSBSMS::Process(), EffectReverse::Process(), Generator::Process(), EffectChangeSpeed::Process(), EffectNyquist::ProcessOne(), AudacityProject::SaveCompressedWaveTracks(), TrackPanel::SelectionHandleClick(), TrackPanel::SelectTracksByLabel(), TrackPanel::SetCursorAndTipWhenSelectTool(), TrackPanelAx::SetFocus(), TrackPanel::StartSlide(), and GetProjectInfoCommand::testSelected().
bool Track::GetSolo () const [inline]
Referenced by audacityAudioCallback(), TrackInfo::DrawMuteSolo(), TrackArtist::DrawTrack(), TrackArtist::DrawTracks(), AudacityProject::HandleTrackSolo(), MixerBoard::HasSolo(), MixerTrackCluster::OnButton_Mute(), MixerTrackCluster::OnButton_Solo(), AudacityProject::SaveCompressedWaveTracks(), GetProjectInfoCommand::testSolo(), MixerTrackCluster::UpdateMeter(), MixerTrackCluster::UpdateMute(), MixerTrackCluster::UpdateSolo(), and AudacityProject::WriteXML().
virtual double Track::GetStartTime () [inline, virtual]
Reimplemented in LabelTrack, NoteTrack, TimeTrack, and WaveTrack.
Referenced by TrackPanel::AddClipsToCaptured(), ExportMultiple::ExportMultipleByTrack(), TrackList::GetStartTime(), and AudacityProject::SaveCompressedWaveTracks().
int Track::GetY () const
References mY.
Referenced by VisibleTrackIterator::Condition(), TrackPanel::DrawEverythingElse(), TrackArtist::DrawTracks(), TrackPanel::FindTrack(), TrackPanel::FindTrackRect(), TrackList::GetHeight(), TrackList::RecalcPositions(), TrackPanel::RefreshTrack(), and AudacityProject::UpdateFirstVisible().
virtual XMLTagHandler* Track::HandleXMLChild (const wxChar * tag) [pure virtual]
Implements XMLTagHandler.
Implemented in LabelTrack, NoteTrack, TimeTrack, and WaveTrack.
virtual bool Track::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [pure virtual]
Implements XMLTagHandler.
Implemented in LabelTrack, NoteTrack, TimeTrack, and WaveTrack.
void Track::Init (const Track & orig)
Reimplemented in TimeTrack, and WaveTrack.
References DirManager::Deref(), mChannel, mDefaultName, mDirManager, mHeight, mLinked, mMinimized, mMute, mName, mSelected, mSolo, and DirManager::Ref().
Referenced by NoteTrack::Copy(), NoteTrack::Cut(), AudacityProject::OnDuplicate(), AudacityProject::OnSplitLabelsToTracks(), and Track().
virtual bool Track::InsertSilence (double t, double len) [inline, virtual]
Reimplemented in LabelTrack, and WaveTrack.
bool Track::IsSynchroSelected ()
References TrackGroupIterator::First(), GetActiveProject(), GetSelected(), AudacityProject::IsSticky(), mList, and TrackGroupIterator::Next().
Referenced by AudacityProject::Clear(), LabelTrack::Draw(), TrackArtist::DrawClipWaveform(), TrackArtist::DrawLabelTrack(), TrackInfo::DrawMinimize(), TrackInfo::DrawMuteSolo(), TrackPanel::DrawOutside(), TrackInfo::DrawTitleBar(), AudacityProject::EditByLabel(), AudacityProject::HandleAlign(), AudacityProject::OnCut(), AudacityProject::OnPaste(), EffectSoundTouch::Process(), EffectSBSMS::Process(), EffectReverse::Process(), Generator::Process(), EffectChangeSpeed::Process(), and EffectNyquist::ProcessOne().
void Track::Merge (const Track & orig) [virtual]
References mMute, mSelected, and mSolo.
Referenced by TrackPanel::OnMergeStereo().
void Track::Offset (double t) [inline]
Referenced by TrackPanel::DoSlide(), and AudacityProject::EditClipboardByLabel().
virtual bool Track::Paste (double t, Track * src) [inline, virtual]
Referenced by AudacityProject::OnPaste(), and SyncAdjust().
void Track::SetChannel (int c) [inline]
Referenced by AudacityProject::EditClipboardByLabel(), PCMImportFileHandle::Import(), OggImportFileHandle::Import(), FLACImportFileHandle::Import(), FFmpegImportFileHandle::Import(), ImportRaw(), MixAndRender(), TrackPanel::OnChannelChange(), AudacityProject::OnCopy(), AudacityProject::OnCut(), TrackPanel::OnMergeStereo(), AudacityProject::OnNewStereoTrack(), AudacityProject::OnPaste(), ControlToolBar::OnRecord(), AudacityProject::OnSplitCut(), AudacityProject::OnSplitNew(), output_cb(), EffectStereoToMono::ProcessOne(), and TrackPanel::SplitStereo().
void Track::SetDefaultName (wxString n) [inline]
Referenced by WaveTrack::Init(), TimeTrack::Init(), LabelTrack::LabelTrack(), NoteTrack::NoteTrack(), TimeTrack::TimeTrack(), and WaveTrack::WaveTrack().
void Track::SetHeight (int h)
References mHeight, mList, mNode, TrackList::RecalcPositions(), and TrackList::ResizedEvent().
Referenced by AudacityProject::DoZoomFitV(), TrackPanel::HandleResizeDrag(), LabelTrack::HandleXMLTag(), LabelTrack::LabelTrack(), and ControlToolBar::OnRecord().
void Track::SetIndex (int index)
References mIndex.
Referenced by TrackList::RecalcPositions().
void Track::SetLinked (bool l) [inline]
Referenced by AudacityProject::EditClipboardByLabel(), WaveTrack::HandleXMLTag(), PCMImportFileHandle::Import(), OggImportFileHandle::Import(), FLACImportFileHandle::Import(), FFmpegImportFileHandle::Import(), ImportRaw(), MixAndRender(), AudacityProject::OnCopy(), AudacityProject::OnCut(), TrackPanel::OnMergeStereo(), AudacityProject::OnNewStereoTrack(), AudacityProject::OnPaste(), ControlToolBar::OnRecord(), AudacityProject::OnSplitCut(), AudacityProject::OnSplitLabelsToTracks(), AudacityProject::OnSplitNew(), AudacityProject::OpenFile(), output_cb(), EffectStereoToMono::ProcessOne(), and TrackPanel::SplitStereo().
void Track::SetMinimized (bool isMinimized)
References mList, mMinimized, mNode, TrackList::RecalcPositions(), and TrackList::ResizedEvent().
Referenced by TrackPanel::HandleMinimizing(), TrackPanel::HandleResizeDrag(), LabelTrack::HandleXMLTag(), AudacityProject::OnCollapseAllTracks(), AudacityProject::OnExpandAllTracks(), and ControlToolBar::OnRecord().
void Track::SetMute (bool m) [inline]
Referenced by AudacityProject::HandleTrackMute(), AudacityProject::HandleTrackSolo(), AudacityProject::OnMuteAllTracks(), AudacityProject::OnUnMuteAllTracks(), AudacityProject::SaveCompressedWaveTracks(), and SetProjectInfoCommand::setMute().
void Track::SetName (wxString n) [inline]
Referenced by AudacityProject::AddImportedTracks(), AudacityProject::EditClipboardByLabel(), AudacityProject::HandleMixAndRender(), WaveTrack::Init(), TimeTrack::Init(), LabelTrack::LabelTrack(), MixAndRender(), NoteTrack::NoteTrack(), AudacityProject::OnCopy(), AudacityProject::OnCut(), AudacityProject::OnPaste(), TrackPanel::OnSetName(), AudacityProject::OnSplitCut(), AudacityProject::OnSplitLabelsToTracks(), AudacityProject::OnSplitNew(), VampEffect::Process(), EffectFindClipping::Process(), TrackPanel::SplitStereo(), TimeTrack::TimeTrack(), LabelDialog::TransferDataFromWindow(), and WaveTrack::WaveTrack().
virtual void Track::SetOffset (double o) [inline, virtual]
Reimplemented in LabelTrack, TimeTrack, and WaveTrack.
Referenced by AudacityProject::HandleAlign(), AudacityProject::OnDuplicate(), AudacityProject::OnSplitLabelsToTracks(), AudacityProject::OnSplitNew(), and EffectFindClipping::Process().
void Track::SetOwner (TrackList * list, TrackListNode * node)
References mList, and mNode.
Referenced by TrackList::Add(), TrackList::AddToHead(), TrackList::Clear(), TrackList::Remove(), TrackList::Replace(), TrackListIterator::ReplaceCurrent(), and TrackList::Swap().
void Track::SetSelected (bool s) [inline]
Referenced by AudacityProject::AddImportedTracks(), SelectCommand::Apply(), AudacityProject::DoAddLabel(), ExportMultiple::ExportMultipleByTrack(), MixerTrackCluster::HandleSelect(), AudacityProject::OnEffect(), AudacityProject::OnImportLabels(), AudacityProject::OnImportMIDI(), AudacityProject::OnNewLabelTrack(), AudacityProject::OnNewStereoTrack(), AudacityProject::OnNewTimeTrack(), AudacityProject::OnNewWaveTrack(), AudacityProject::OnPaste(), AudacityProject::OnPasteNewLabel(), AudacityProject::OnSelectAll(), LabelDialog::OnSelectCell(), Effect::Preview(), AudacityProject::SaveCompressedWaveTracks(), TrackList::Select(), TrackPanel::SelectionHandleClick(), TrackPanel::SelectNone(), AudacityProject::SelectNone(), TrackPanel::SelectTracksByLabel(), and SetProjectInfoCommand::setSelected().
void Track::SetSolo (bool s) [inline]
Referenced by AudacityProject::HandleTrackMute(), AudacityProject::HandleTrackSolo(), AudacityProject::SaveCompressedWaveTracks(), and SetProjectInfoCommand::setSolo().
void Track::SetY (int y)
References mY.
Referenced by TrackList::RecalcPositions().
virtual bool Track::Silence (double t0, double t1) [inline, virtual]
Reimplemented in LabelTrack, and WaveTrack.
Referenced by AudacityProject::OnSplitCut(), and AudacityProject::OnSplitDelete().
bool Track::SyncAdjust (double oldT1, double newT1) [virtual]
Reimplemented in WaveTrack.
References Clear(), Cut(), GetEndTime(), and Paste().
Referenced by AudacityProject::OnPaste(), EffectSoundTouch::Process(), EffectSBSMS::Process(), EffectRepeat::Process(), Generator::Process(), EffectChangeSpeed::Process(), and EffectNyquist::ProcessOne().
virtual void Track::WriteXML (XMLWriter & xmlFile) [pure virtual]
Implemented in LabelTrack, NoteTrack, TimeTrack, and WaveTrack.
Referenced by AudacityProject::WriteXML().
Member Data Documentation
int Track::mChannel [protected]
Referenced by WaveTrack::HandleXMLTag(), TimeTrack::HandleXMLTag(), Init(), Track(), WaveTrack::WriteXML(), and TimeTrack::WriteXML().
wxString Track::mDefaultName [protected]
Referenced by Init().
DirManager* Track::mDirManager [mutable, protected]
Reimplemented in NoteTrack.
Referenced by WaveTrack::Copy(), WaveTrack::CreateClip(), WaveTrack::GetMaxBlockSize(), WaveTrack::HandleClear(), Init(), WaveTrack::Paste(), WaveTrack::SplitAt(), Track(), WaveTrack::WaveTrack(), and ~Track().
int Track::mHeight [protected]
Referenced by GetHeight(), WaveTrack::HandleXMLTag(), TimeTrack::HandleXMLTag(), Init(), SetHeight(), TimeTrack::TimeTrack(), and Track().
int Track::mIndex [protected]
Referenced by GetIndex(), SetIndex(), and Track().
bool Track::mLinked [protected]
Referenced by GetLink(), Init(), Track(), and WaveTrack::WriteXML().
TrackList* Track::mList [protected]
Referenced by IsSynchroSelected(), SetHeight(), SetMinimized(), SetOwner(), and Track().
bool Track::mMinimized [protected]
Referenced by GetHeight(), GetMinimized(), WaveTrack::HandleXMLTag(), TimeTrack::HandleXMLTag(), Init(), SetMinimized(), and Track().
bool Track::mMute [protected]
Referenced by WaveTrack::HandleXMLTag(), Init(), Merge(), Track(), and WaveTrack::WriteXML().
wxString Track::mName [protected]
Referenced by WaveTrack::HandleXMLTag(), TimeTrack::HandleXMLTag(), LabelTrack::HandleXMLTag(), Init(), WaveTrack::WriteXML(), TimeTrack::WriteXML(), and LabelTrack::WriteXML().
TrackListNode* Track::mNode [protected]
Referenced by GetLink(), GetNode(), SetHeight(), SetMinimized(), SetOwner(), and Track().
double Track::mOffset [protected]
Referenced by WaveTrack::GetLastOrCreateClip(), TimeTrack::HandleXMLTag(), WaveTrack::SetOffset(), Track(), and TimeTrack::WriteXML().
bool Track::mSelected [protected]
Referenced by Init(), Merge(), and Track().
bool Track::mSolo [protected]
Referenced by WaveTrack::HandleXMLTag(), Init(), Merge(), Track(), and WaveTrack::WriteXML().
int Track::mY [protected]
Referenced by GetY(), SetY(), and Track().
wxSize Track::vrulerSize
Referenced by TrackArtist::DrawVRuler(), TrackArtist::UpdateVRuler(), and TrackPanel::UpdateVRulerSize().
The documentation for this class was generated from the following files:
Track.h
Track.cpp