Audacity: SnapManager Class Reference
SnapManager Class Reference
#include <Snap.h>
Public Member Functions
SnapManager (TrackList *tracks, TrackClipArray *exclusions, double zoom, int pixelTolerance, bool noTimeSnap=false)
~SnapManager ()
bool Snap (Track *currentTrack, double t, bool rightEdge, double *out_t, bool *snappedPoint, bool *snappedTime)
Private Member Functions
void CondListAdd (double t, Track *tr, TimeTextCtrl *ttc)
double Get (int index)
double Diff (double t, int index)
int Find (double t, int i0, int i1)
int Find (double t)
bool SnapToPoints (Track *currentTrack, double t, bool rightEdge, double *out_t)
Private Attributes
double mEpsilon
double mTolerance
double mZoom
SnapPointArray * mSnapPoints
bool mSnapToTime
wxString mFormat
Constructor & Destructor Documentation
SnapManager::SnapManager (TrackList * tracks, TrackClipArray * exclusions, double zoom, int pixelTolerance, bool noTimeSnap = false)
References CompareSnapPoints(), CondListAdd(), TrackListIterator::First(), GetActiveProject(), TimeTextCtrl::GetBuiltinFormat(), WaveTrack::GetClipIterator(), WaveClip::GetEndTime(), Track::GetKind(), LabelTrack::GetLabel(), LabelTrack::GetNumLabels(), AudacityProject::GetRate(), WaveClip::GetStartTime(), gPrefs, label, Track::Label, mEpsilon, mFormat, mSnapPoints, mSnapToTime, mTolerance, TrackListIterator::Next(), TimeTextCtrl::SetFormatString(), LabelStruct::t, LabelStruct::t1, and Track::Wave.
SnapManager::~SnapManager ()
References mSnapPoints.
Member Function Documentation
void SnapManager::CondListAdd (double t, Track * tr, TimeTextCtrl * ttc) [private]
References TimeTextCtrl::GetTimeValue(), mSnapPoints, and TimeTextCtrl::SetTimeValue().
Referenced by SnapManager().
double SnapManager::Diff (double t, int index) [private]
References Get().
Referenced by Find(), and SnapToPoints().
int SnapManager::Find (double t) [private]
References Diff(), Find(), Get(), and mSnapPoints.
int SnapManager::Find (double t, int i0, int i1) [private]
References Get().
Referenced by Find(), and SnapToPoints().
double SnapManager::Get (int index) [private]
References mSnapPoints.
Referenced by Diff(), Find(), and SnapToPoints().
bool SnapManager::Snap (Track * currentTrack, double t, bool rightEdge, double * out_t, bool * snappedPoint, bool * snappedTime)
References TimeConverter::ControlsToValue(), GetActiveProject(), AudacityProject::GetRate(), mFormat, TimeConverter::mSampleRate, mSnapToTime, TimeConverter::ParseFormatString(), SnapToPoints(), and TimeConverter::ValueToControls().
Referenced by TrackPanel::DoSlide(), TrackPanel::ExtendSelection(), and TrackPanel::StartSelection().
bool SnapManager::SnapToPoints (Track * currentTrack, double t, bool rightEdge, double * out_t) [private]
References Diff(), Find(), Get(), mEpsilon, mSnapPoints, and mTolerance.
Referenced by Snap().
Member Data Documentation
double SnapManager::mEpsilon [private]
Referenced by SnapManager(), and SnapToPoints().
wxString SnapManager::mFormat [private]
Referenced by Snap(), and SnapManager().
SnapPointArray* SnapManager::mSnapPoints [private]
Referenced by CondListAdd(), Find(), Get(), SnapManager(), SnapToPoints(), and ~SnapManager().
bool SnapManager::mSnapToTime [private]
Referenced by Snap(), and SnapManager().
double SnapManager::mTolerance [private]
Referenced by SnapManager(), and SnapToPoints().
double SnapManager::mZoom [private]
The documentation for this class was generated from the following files:
Snap.h
Snap.cpp