Audacity: CompareAudioCommand Class Reference
CompareAudioCommand Class Reference
Returns information about the amount of audio that is about a certain threshold of difference in two selected tracks.
#include <CompareAudioCommand.h>
Public Member Functions
CompareAudioCommand (CommandType &type, CommandOutputTarget *target)
virtual bool Apply (CommandExecutionContext context)
Protected Member Functions
virtual double CompareSample (double value1, double value2)
Private Member Functions
bool GetSelection (AudacityProject &proj)
Private Attributes
double mT0
double mT1
WaveTrack * mTrack0
WaveTrack * mTrack1
Detailed Description
Returns information about the amount of audio that is about a certain threshold of difference in two selected tracks.
Constructor & Destructor Documentation
CompareAudioCommand::CompareAudioCommand (CommandType & type, CommandOutputTarget * target) [inline]
Member Function Documentation
bool CompareAudioCommand::Apply (CommandExecutionContext context) [virtual]
Actually carry out the command. Return true if successful and false otherwise.
Reimplemented from CommandImplementation.
References CompareSample(), floatSample, WaveTrack::Get(), WaveTrack::GetBestBlockSize(), CommandImplementation::GetDouble(), WaveTrack::GetMaxBlockSize(), Track::GetName(), GetSelection(), WaveTrack::LongSamplesToTime(), min(), mT0, mT1, mTrack0, mTrack1, CommandImplementation::Progress(), CommandExecutionContext::proj, CommandImplementation::Status(), and WaveTrack::TimeToLongSamples().
double CompareAudioCommand::CompareSample (double value1, double value2) [protected, virtual]
Referenced by Apply().
bool CompareAudioCommand::GetSelection (AudacityProject & proj) [private]
References CommandImplementation::Error(), AudacityProject::GetTracks(), mT0, mT1, mTrack0, mTrack1, AudacityProject::mViewInfo, ViewInfo::sel0, ViewInfo::sel1, CommandImplementation::Status(), and Track::Wave.
Referenced by Apply().
Member Data Documentation
double CompareAudioCommand::mT0 [private]
Referenced by Apply(), and GetSelection().
double CompareAudioCommand::mT1 [private]
Referenced by Apply(), and GetSelection().
WaveTrack* CompareAudioCommand::mTrack0 [private]
Referenced by Apply(), and GetSelection().
WaveTrack* CompareAudioCommand::mTrack1 [private]
Referenced by Apply(), and GetSelection().
The documentation for this class was generated from the following files:
CompareAudioCommand.h
CompareAudioCommand.cpp