Audacity: TrackList Class Reference
TrackList Class Reference
A list of TrackListNode items.
#include <Track.h>
Public Member Functions
TrackList ()
virtual ~TrackList ()
void Add (Track *t)
Add this Track or all children of this TrackGroup.
void AddToHead (Track *t)
void Replace (Track *t, Track *with, bool deletetrack=false)
Replace first track with second track.
void Remove (Track *t, bool deletetrack=false)
Remove this Track or all children of this TrackGroup.
void Clear (bool deleteTracks=false)
Make the list empty.
void Select (Track *t, bool selected=true)
Track * GetLink (Track *t) const
Track * GetPrev (Track *t, bool linked=false) const
Track * GetNext (Track *t, bool linked=false) const
int GetGroupHeight (Track *t) const
bool CanMoveUp (Track *t) const
bool CanMoveDown (Track *t) const
bool MoveUp (Track *t)
bool MoveDown (Track *t)
bool Move (Track *t, bool up)
TimeTrack * GetTimeTrack ()
int GetNumExportChannels (bool selectionOnly)
Find out how many channels this track list mixes to.
WaveTrackArray GetWaveTrackArray (bool selectionOnly)
void GetWaveTracks (bool selectionOnly, int *num, WaveTrack ***tracks)
NoteTrackArray GetNoteTrackArray (bool selectionOnly)
bool Contains (Track *t) const
Mainly a test function. Uses a linear search, so could be slow.
bool IsEmpty () const
int GetCount () const
double GetStartTime () const
double GetEndTime () const
double GetMinOffset () const
int GetHeight () const
Private Member Functions
void RecalcPositions (const TrackListNode *node)
void UpdatedEvent (const TrackListNode *node)
void ResizedEvent (const TrackListNode *node)
void Swap (TrackListNode *s1, TrackListNode *s2)
Private Attributes
TrackListNode * head
TrackListNode * tail
Friends
class Track
class TrackListIterator
Detailed Description
A list of TrackListNode items.
Constructor & Destructor Documentation
TrackList::TrackList ()
References head, and tail.
TrackList::~TrackList () [virtual]
References Clear().
Member Function Documentation
void TrackList::Add (Track * t)
Add this Track or all children of this TrackGroup.
References head, TrackListNode::next, TrackListNode::prev, RecalcPositions(), Track::SetOwner(), TrackListNode::t, tail, and UpdatedEvent().
Referenced by AudacityProject::AddImportedTracks(), Effect::AddToOutputTracks(), Effect::CopyInputTracks(), AudacityProject::DoAddLabel(), AudacityProject::EditClipboardByLabel(), AudacityProject::HandleMixAndRender(), AudacityProject::HandleXMLChild(), LOFImportFileHandle::lofOpenFiles(), UndoManager::ModifyState(), AudacityProject::OnCopy(), AudacityProject::OnCut(), AudacityProject::OnDuplicate(), AudacityProject::OnEffect(), AudacityProject::OnImportLabels(), AudacityProject::OnImportMIDI(), AudacityProject::OnNewLabelTrack(), AudacityProject::OnNewStereoTrack(), AudacityProject::OnNewWaveTrack(), AudacityProject::OnPaste(), AudacityProject::OnPasteNewLabel(), ControlToolBar::OnRecord(), AudacityProject::OnSortName(), AudacityProject::OnSortTime(), AudacityProject::OnSplitCut(), AudacityProject::OnSplitLabelsToTracks(), AudacityProject::OnSplitNew(), AudacityProject::OpenFile(), AudacityProject::PopState(), VampEffect::Process(), EffectFindClipping::Process(), UndoManager::PushState(), Effect::ReplaceProcessedTracks(), AudacityProject::Save(), AudacityProject::SaveCompressedWaveTracks(), ControlToolBar::SetupCutPreviewTracks(), and LabelDialog::TransferDataFromWindow().
void TrackList::AddToHead (Track * t)
References head, TrackListNode::next, TrackListNode::prev, RecalcPositions(), ResizedEvent(), Track::SetOwner(), TrackListNode::t, tail, and UpdatedEvent().
Referenced by AudacityProject::OnNewTimeTrack().
bool TrackList::CanMoveDown (Track * t) const
References GetNext().
Referenced by TrackPanel::CalculateRearrangingThresholds(), and TrackPanel::OnTrackMenu().
bool TrackList::CanMoveUp (Track * t) const
References GetPrev().
Referenced by TrackPanel::CalculateRearrangingThresholds(), and TrackPanel::OnTrackMenu().
void TrackList::Clear (bool deleteTracks = false)
Make the list empty.
References head, TrackListNode::next, Track::SetOwner(), TrackListNode::t, tail, and UpdatedEvent().
Referenced by AudacityProject::ClearClipboard(), ControlToolBar::ClearCutPreviewTracks(), AudacityProject::DeleteClipboard(), AudacityProject::OnCloseWindow(), AudacityProject::OpenFile(), AudacityProject::PopState(), Effect::Preview(), Effect::ReplaceProcessedTracks(), AudacityProject::Save(), AudacityProject::SaveCompressedWaveTracks(), and ~TrackList().
bool TrackList::Contains (Track * t) const
Mainly a test function. Uses a linear search, so could be slow.
References head, TrackListNode::next, and TrackListNode::t.
Referenced by TrackPanel::OnTrackListUpdated().
int TrackList::GetCount () const
References Track::GetIndex(), TrackListNode::t, and tail.
Referenced by SelectCommand::Apply().
double TrackList::GetEndTime () const
References Track::GetEndTime(), head, max, TrackListNode::next, and TrackListNode::t.
Referenced by SelectCommand::Apply(), ExportCommand::Apply(), LOFImportFileHandle::doDuration(), TrackPanel::DoSlide(), ExportMultiple::ExportMultipleByLabel(), AudacityProject::FixScrollbars(), BatchCommands::GetEndTime(), TrackPanel::OnBoundaryMove(), TrackPanel::OnCursorMove(), TrackPanel::OnCursorRight(), AudacityProject::OnExport(), AudacityPrintout::OnPrintPage(), AudacityProject::OnSelectAll(), TranscriptionToolBar::OnSelectSilence(), TranscriptionToolBar::OnSelectSound(), AudacityProject::OnZoomFit(), ControlToolBar::PlayPlayRegion(), AudacityProject::Save(), and AudacityProject::SkipEnd().
int TrackList::GetGroupHeight (Track * t) const
For mono track height of track For stereo track combined height of track and linked track.
References Track::GetHeight(), and Track::GetLink().
Referenced by TrackPanel::CalculateRearrangingThresholds().
int TrackList::GetHeight () const
References Track::GetHeight(), Track::GetY(), TrackListNode::t, and tail.
Referenced by AudacityProject::FixScrollbars(), and AudacityPrintout::OnPrintPage().
Track * TrackList::GetLink (Track * t) const
If this track is linked to another track (the track immediately before or after it), return its partner. Otherwise return null.
References Track::GetLink().
Referenced by TrackPanel::DoSlide(), TrackPanel::HandleMinimizing(), TrackPanel::HandleSliders(), TrackPanel::HandleTrackLocationMouseEvent(), TrackPanel::HandleVZoomButtonUp(), TrackPanel::MoveClipToTrack(), TrackPanel::OnFormatChange(), TrackPanel::SetRate(), TrackPanel::SetTrackGain(), TrackPanel::SetTrackPan(), and TrackPanel::StartSlide().
double TrackList::GetMinOffset () const
References Track::GetOffset(), head, TrackListNode::next, and TrackListNode::t.
Referenced by AudacityProject::OnSelectAll().
Track * TrackList::GetNext (Track * t, bool linked = false) const
References Track::GetLinked(), Track::GetNode(), TrackListNode::next, and TrackListNode::t.
Referenced by TrackPanel::CalculateRearrangingThresholds(), CanMoveDown(), TrackPanel::HandleResizeClick(), TrackPanel::HandleResizeDrag(), TrackGroupIterator::Last(), MoveDown(), TrackPanel::OnNextTrack(), AudacityProject::OnRemoveTracks(), TrackPanel::OnTrackMenu(), TrackPanel::RemoveTrack(), and AudacityProject::UpdateFirstVisible().
NoteTrackArray TrackList::GetNoteTrackArray (bool selectionOnly)
References Track::GetKind(), Track::GetSelected(), head, TrackListNode::next, Track::Note, and TrackListNode::t.
Referenced by ControlToolBar::OnRecord(), and ControlToolBar::PlayPlayRegion().
int TrackList::GetNumExportChannels (bool selectionOnly)
Find out how many channels this track list mixes to.
This is used in exports of the tracks to work out whether to export in Mono, Stereo etc.
Parameters:
selectionOnly Whether to consider the entire track list or only the selected members of it
References TrackListIterator::First(), Track::GetChannel(), Track::GetKind(), Track::GetSelected(), Track::LeftChannel, Track::MonoChannel, TrackListIterator::Next(), Track::RightChannel, and Track::Wave.
Referenced by ExportMultiple::ExportMultipleByLabel().
Track * TrackList::GetPrev (Track * t, bool linked = false) const
References Track::GetLink(), Track::GetLinked(), Track::GetNode(), TrackListNode::prev, and TrackListNode::t.
Referenced by TrackPanel::CalculateRearrangingThresholds(), CanMoveUp(), TrackGroupIterator::First(), TrackPanel::HandleResizeClick(), TrackPanel::HandleResizeDrag(), MoveUp(), TrackPanel::OnPrevTrack(), TrackPanel::RemoveTrack(), and AudacityProject::UpdateFirstVisible().
double TrackList::GetStartTime () const
References Track::GetStartTime(), head, min(), TrackListNode::next, and TrackListNode::t.
Referenced by TrackPanel::DoSlide(), and ControlToolBar::PlayPlayRegion().
TimeTrack * TrackList::GetTimeTrack ()
References Track::GetKind(), head, TrackListNode::next, TrackListNode::t, and Track::Time.
Referenced by ExportPCM::Export(), ExportOGG::Export(), ExportMP3::Export(), ExportMP2::Export(), ExportFLAC::Export(), ExportFFmpeg::Export(), ExportCL::Export(), MixAndRender(), AudacityProject::OnNewTimeTrack(), ControlToolBar::OnRecord(), and ControlToolBar::PlayPlayRegion().
WaveTrackArray TrackList::GetWaveTrackArray (bool selectionOnly)
References Track::GetKind(), Track::GetSelected(), head, TrackListNode::next, TrackListNode::t, and Track::Wave.
Referenced by RecordingRecoveryHandler::HandleXMLTag(), ControlToolBar::OnRecord(), ControlToolBar::PlayPlayRegion(), and AudioIO::StopStream().
void TrackList::GetWaveTracks (bool selectionOnly, int * num, WaveTrack *** tracks)
Consider this function depricated in favor of GetWaveTrackArray
References Track::GetKind(), Track::GetMute(), Track::GetSelected(), head, TrackListNode::next, TrackListNode::t, and Track::Wave.
Referenced by ExportPCM::Export(), ExportOGG::Export(), ExportMP3::Export(), ExportMP2::Export(), ExportFLAC::Export(), ExportFFmpeg::Export(), and ExportCL::Export().
bool TrackList::IsEmpty () const
References head.
Referenced by AudacityProject::AddImportedTracks(), EditToolBar::EnableDisableButtons(), TrackPanel::HandleClosing(), ControlToolBar::OnRecord(), TrackPanel::OnTrackClose(), AudacityProject::OpenFiles(), and TrackPanel::RemoveTrack().
bool TrackList::Move (Track * t, bool up) [inline]
Referenced by TrackPanel::OnMoveTrack().
bool TrackList::MoveDown (Track * t)
References GetNext(), Track::GetNode(), and Swap().
Referenced by TrackPanel::HandleRearrange().
bool TrackList::MoveUp (Track * t)
References Track::GetNode(), GetPrev(), and Swap().
Referenced by TrackPanel::HandleRearrange().
void TrackList::RecalcPositions (const TrackListNode * node) [private]
References Track::GetHeight(), Track::GetIndex(), Track::GetY(), TrackListNode::next, TrackListNode::prev, Track::SetIndex(), Track::SetY(), and TrackListNode::t.
Referenced by Add(), AddToHead(), Remove(), Replace(), TrackListIterator::ReplaceCurrent(), Track::SetHeight(), Track::SetMinimized(), and Swap().
void TrackList::Remove (Track * t, bool deletetrack = false)
Remove this Track or all children of this TrackGroup.
References Track::GetNode(), head, TrackListNode::next, TrackListNode::prev, RecalcPositions(), ResizedEvent(), Track::SetOwner(), tail, and UpdatedEvent().
Referenced by AudacityProject::OnEffect(), ControlToolBar::OnRecord(), EffectFindClipping::Process(), EffectStereoToMono::ProcessOne(), TrackListIterator::RemoveCurrent(), TrackPanel::RemoveTrack(), and Effect::ReplaceProcessedTracks().
void TrackList::Replace (Track * t, Track * with, bool deletetrack = false)
Replace first track with second track.
References Track::GetNode(), RecalcPositions(), ResizedEvent(), Track::SetOwner(), TrackListNode::t, and UpdatedEvent().
Referenced by Effect::ReplaceProcessedTracks().
void TrackList::ResizedEvent (const TrackListNode * node) [private]
References TrackListNode::t.
Referenced by AddToHead(), Remove(), Replace(), TrackListIterator::ReplaceCurrent(), Track::SetHeight(), Track::SetMinimized(), and Swap().
void TrackList::Select (Track * t, bool selected = true)
Select a track, and if it is linked to another track, select it, too.
References Track::GetLinked(), Track::GetNode(), TrackListNode::next, TrackListNode::prev, Track::SetSelected(), and TrackListNode::t.
Referenced by TrackPanel::HandleLabelClick(), TrackPanel::HandleSelect(), TrackPanel::OnNextTrack(), TrackPanel::OnPrevTrack(), TrackPanel::OnToggle(), TrackPanel::SelectionHandleClick(), and TrackPanel::SelectionHandleDrag().
void TrackList::Swap (TrackListNode * s1, TrackListNode * s2) [private]
References Track::GetLink(), Track::GetLinked(), Track::GetNode(), TrackListNode::next, RecalcPositions(), ResizedEvent(), Track::SetOwner(), TrackListNode::t, and UpdatedEvent().
Referenced by MoveDown(), and MoveUp().
void TrackList::UpdatedEvent (const TrackListNode * node) [private]
References TrackListNode::t.
Referenced by Add(), AddToHead(), Clear(), Remove(), Replace(), TrackListIterator::ReplaceCurrent(), and Swap().
Friends And Related Function Documentation
friend class Track [friend]
friend class TrackListIterator [friend]
Member Data Documentation
TrackListNode* TrackList::head [private]
Referenced by Add(), AddToHead(), Clear(), Contains(), TrackListIterator::First(), GetEndTime(), GetMinOffset(), GetNoteTrackArray(), GetStartTime(), GetTimeTrack(), GetWaveTrackArray(), GetWaveTracks(), IsEmpty(), Remove(), and TrackList().
TrackListNode* TrackList::tail [private]
Referenced by Add(), AddToHead(), Clear(), GetCount(), GetHeight(), TrackListIterator::Last(), Remove(), and TrackList().
The documentation for this class was generated from the following files:
Track.h
Track.cpp