Audacity: CommandOutputTarget Class Reference
CommandOutputTarget Class Reference
#include <CommandTargets.h>
Public Member Functions
CommandOutputTarget (CommandProgressTarget *pt=TargetFactory::ProgressDefault(), CommandMessageTarget *st=TargetFactory::MessageDefault(), CommandMessageTarget *et=TargetFactory::MessageDefault())
~CommandOutputTarget ()
void Progress (double completed)
void Status (wxString status)
void Error (wxString message)
Private Attributes
CommandProgressTarget * mProgressTarget
CommandMessageTarget * mStatusTarget
CommandMessageTarget * mErrorTarget
Detailed Description
Used to aggregate the various output targets a command may have. Assumes responsibility for pointers passed into it.
Constructor & Destructor Documentation
CommandOutputTarget::CommandOutputTarget (CommandProgressTarget * pt = TargetFactory::ProgressDefault(), CommandMessageTarget * st = TargetFactory::MessageDefault(), CommandMessageTarget * et = TargetFactory::MessageDefault()) [inline]
CommandOutputTarget::~CommandOutputTarget () [inline]
References mErrorTarget, mProgressTarget, and mStatusTarget.
Member Function Documentation
void CommandOutputTarget::Error (wxString message) [inline]
References mErrorTarget, and CommandMessageTarget::Update().
Referenced by ScreenshotCommand::Capture(), and CommandImplementation::Error().
void CommandOutputTarget::Progress (double completed) [inline]
References mProgressTarget, and CommandProgressTarget::Update().
Referenced by CommandImplementation::Progress().
void CommandOutputTarget::Status (wxString status) [inline]
References mStatusTarget, and CommandMessageTarget::Update().
Referenced by ScreenshotCommand::Capture(), and CommandImplementation::Status().
Member Data Documentation
CommandMessageTarget* CommandOutputTarget::mErrorTarget [private]
Referenced by Error(), and ~CommandOutputTarget().
CommandProgressTarget* CommandOutputTarget::mProgressTarget [private]
Referenced by Progress(), and ~CommandOutputTarget().
CommandMessageTarget* CommandOutputTarget::mStatusTarget [private]
Referenced by Status(), and ~CommandOutputTarget().
The documentation for this class was generated from the following file:
CommandTargets.h