Audacity: WarningsPrefs Class Reference
WarningsPrefs Class Reference
A PrefsPanel to enable/disable certain warning messages.
#include <WarningsPrefs.h>
Public Member Functions
WarningsPrefs (wxWindow *parent)
~WarningsPrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
Detailed Description
A PrefsPanel to enable/disable certain warning messages.
Constructor & Destructor Documentation
WarningsPrefs::WarningsPrefs (wxWindow * parent)
References Populate().
WarningsPrefs::~WarningsPrefs ()
Member Function Documentation
bool WarningsPrefs::Apply () [virtual]
Implements PrefsPanel.
References eIsSavingToPrefs, and PopulateOrExchange().
void WarningsPrefs::Populate () [private]
References eIsCreatingFromPrefs, and PopulateOrExchange().
Referenced by WarningsPrefs().
void WarningsPrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::EndStatic(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::TieCheckBox().
Referenced by Apply(), and Populate().
The documentation for this class was generated from the following files:
WarningsPrefs.h
WarningsPrefs.cpp