Audacity: OggImportFileHandle Class Reference
OggImportFileHandle Class Reference
Public Member Functions
OggImportFileHandle (const wxString &filename, wxFFile *file, OggVorbis_File *vorbisFile)
~OggImportFileHandle ()
wxString GetFileDescription ()
int GetFileUncompressedBytes ()
int Import (TrackFactory *trackFactory, Track ***outTracks, int *outNumTracks, Tags *tags)
wxInt32 GetStreamCount ()
wxArrayString * GetStreamInfo ()
void SetStreamUsage (wxInt32 StreamID, bool Use)
Private Attributes
wxFFile * mFile
OggVorbis_File * mVorbisFile
int * mStreamUsage
wxArrayString * mStreamInfo
WaveTrack *** mChannels
Constructor & Destructor Documentation
OggImportFileHandle::OggImportFileHandle (const wxString & filename, wxFFile * file, OggVorbis_File * vorbisFile) [inline]
References mStreamInfo, and mStreamUsage.
OggImportFileHandle::~OggImportFileHandle ()
References mFile, mStreamInfo, mStreamUsage, and mVorbisFile.
Member Function Documentation
wxString OggImportFileHandle::GetFileDescription () [virtual]
Implements ImportFileHandle.
References DESC.
int OggImportFileHandle::GetFileUncompressedBytes () [virtual]
Implements ImportFileHandle.
wxInt32 OggImportFileHandle::GetStreamCount () [inline, virtual]
Implements ImportFileHandle.
References mVorbisFile.
wxArrayString* OggImportFileHandle::GetStreamInfo () [inline, virtual]
Implements ImportFileHandle.
References mStreamInfo.
int OggImportFileHandle::Import (TrackFactory * trackFactory, Track *** outTracks, int * outNumTracks, Tags * tags) [virtual]
Implements ImportFileHandle.
References Tags::Clear(), CODEC_TRANSFER_SIZE, ImportFileHandle::CreateProgress(), eProgressCancelled, eProgressFailed, eProgressSuccess, WaveTrack::Flush(), Tags::HasTag(), int16Sample, Track::LeftChannel, mChannels, mFile, Track::MonoChannel, ImportFileHandle::mProgress, mStreamUsage, mVorbisFile, name, TrackFactory::NewWaveTrack(), Track::RightChannel, SAMPLES_PER_CALLBACK, Track::SetChannel(), Track::SetLinked(), Tags::SetTag(), TAG_YEAR, ProgressDialog::Update(), and UTF8CTOWX.
void OggImportFileHandle::SetStreamUsage (wxInt32 StreamID, bool Use) [inline, virtual]
Implements ImportFileHandle.
References mStreamUsage, and mVorbisFile.
Member Data Documentation
WaveTrack*** OggImportFileHandle::mChannels [private]
Referenced by Import().
wxFFile* OggImportFileHandle::mFile [private]
Referenced by Import(), and ~OggImportFileHandle().
wxArrayString* OggImportFileHandle::mStreamInfo [private]
Referenced by GetStreamInfo(), OggImportFileHandle(), and ~OggImportFileHandle().
int* OggImportFileHandle::mStreamUsage [private]
Referenced by Import(), OggImportFileHandle(), SetStreamUsage(), and ~OggImportFileHandle().
OggVorbis_File* OggImportFileHandle::mVorbisFile [private]
Referenced by GetStreamCount(), Import(), SetStreamUsage(), and ~OggImportFileHandle().
The documentation for this class was generated from the following file:
ImportOGG.cpp