Audacity: AboutDialog Class Reference
AboutDialog Class Reference
The AboutDialog shows the program version and developer credits.
#include <AboutDialog.h>
Public Member Functions
AboutDialog (wxWindow *parent)
virtual ~AboutDialog ()
void OnOK (wxCommandEvent &event)
Public Attributes
wxBoxSizer * topsizer
wxStaticBitmap * icon
wxBitmap * logo
Private Types
enum Role {
roleTeamDeveloper, roleTeamSupport, roleEmeritusDeveloper, roleEmeritusSupport,
roleContributor, roleLibrary, roleThanks
}
Private Member Functions
void PopulateAudacityPage (ShuttleGui &S)
void PopulateLicensePage (ShuttleGui &S)
void PopulateInformationPage (ShuttleGui &S)
: Fills out the "Information" tab of the preferences dialogue Provides as much information as possible about build-time options and the libraries used, to try and make Linux support easier. Basically anything about the build we might wish to know should be visible here
void CreateCreditsList ()
void AddCredit (const wxString &description, Role role)
wxString GetCreditsByRole (AboutDialog::Role role)
void AddBuildinfoRow (wxString *htmlstring, const wxChar *libname, const wxChar *libdesc, wxString status)
Add a table row saying if a library is used or not.
void AddBuildinfoRow (wxString *htmlstring, const wxChar *libname, const wxChar *libdesc)
Add a table row saying if a library is used or not.
Private Attributes
AboutDialogCreditItemsList creditItems
Detailed Description
The AboutDialog shows the program version and developer credits.
It is a simple scrolling window with an 'OK... Audacious!' button to close it.
Member Enumeration Documentation
enum AboutDialog::Role [private]
Enumerator:
roleTeamDeveloper
roleTeamSupport
roleEmeritusDeveloper
roleEmeritusSupport
roleContributor
roleLibrary
roleThanks
Constructor & Destructor Documentation
AboutDialog::AboutDialog (wxWindow * parent)
References ShuttleGuiBase::AddWindow(), ThemeBase::Colour(), eIsCreating, ShuttleGuiBase::EndNotebook(), ShuttleGuiBase::GetParent(), ShuttleGui::Prop(), ShuttleGuiBase::StartNotebook(), and theTheme.
AboutDialog::~AboutDialog () [virtual]
References icon.
Member Function Documentation
void AboutDialog::AddBuildinfoRow (wxString * htmlstring, const wxChar * libname, const wxChar * libdesc) [private]
Add a table row saying if a library is used or not.
Used when creating the build information tab to show build dates and file paths
void AboutDialog::AddBuildinfoRow (wxString * htmlstring, const wxChar * libname, const wxChar * libdesc, wxString status) [private]
Add a table row saying if a library is used or not.
Used when creating the build information tab to show if each optional library is enabled or not, and what it does
Referenced by PopulateInformationPage().
void AboutDialog::AddCredit (const wxString & description, Role role) [private]
References creditItems, AboutDialogCreditItem::description, and AboutDialogCreditItem::role.
Referenced by CreateCreditsList().
void AboutDialog::CreateCreditsList () [private]
References AddCredit(), roleContributor, roleEmeritusDeveloper, roleEmeritusSupport, roleLibrary, roleTeamDeveloper, roleTeamSupport, and roleThanks.
Referenced by PopulateAudacityPage().
wxString AboutDialog::GetCreditsByRole (AboutDialog::Role role) [private]
References creditItems, AboutDialogCreditItem::description, and AboutDialogCreditItem::role.
Referenced by PopulateAudacityPage().
void AboutDialog::OnOK (wxCommandEvent & event)
void AboutDialog::PopulateAudacityPage (ShuttleGui & S) [private]
References ShuttleGuiBase::AddWindow(), AUDACITY_VERSION_STRING, ThemeBase::Colour(), CreateCreditsList(), creditItems, ShuttleGuiBase::EndNotebookPage(), ShuttleGuiBase::EndVerticalLay(), GetCreditsByRole(), ShuttleGuiBase::GetParent(), icon, logo, LOGOWITHNAME_HEIGHT, LOGOWITHNAME_WIDTH, ShuttleGui::Prop(), roleContributor, roleEmeritusDeveloper, roleEmeritusSupport, roleLibrary, roleTeamDeveloper, roleTeamSupport, roleThanks, ShuttleGuiBase::StartNotebookPage(), ShuttleGuiBase::StartVerticalLay(), and theTheme.
void AboutDialog::PopulateInformationPage (ShuttleGui & S) [private]
: Fills out the "Information" tab of the preferences dialogue Provides as much information as possible about build-time options and the libraries used, to try and make Linux support easier. Basically anything about the build we might wish to know should be visible here
References AddBuildinfoRow(), ShuttleGuiBase::AddWindow(), FileNames::DataDir(), ShuttleGuiBase::EndNotebookPage(), ShuttleGuiBase::EndVerticalLay(), ShuttleGuiBase::GetParent(), INSTALL_PREFIX, LOGOWITHNAME_WIDTH, ShuttleGui::Prop(), ShuttleGuiBase::StartNotebookPage(), and ShuttleGuiBase::StartVerticalLay().
void AboutDialog::PopulateLicensePage (ShuttleGui & S) [private]
References ShuttleGuiBase::AddWindow(), ShuttleGuiBase::EndNotebookPage(), ShuttleGuiBase::EndVerticalLay(), ShuttleGuiBase::GetParent(), LOGOWITHNAME_WIDTH, ShuttleGui::Prop(), ShuttleGuiBase::StartNotebookPage(), and ShuttleGuiBase::StartVerticalLay().
Member Data Documentation
AboutDialogCreditItemsList AboutDialog::creditItems [private]
Referenced by AddCredit(), GetCreditsByRole(), and PopulateAudacityPage().
wxStaticBitmap* AboutDialog::icon
Referenced by PopulateAudacityPage(), and ~AboutDialog().
wxBitmap* AboutDialog::logo
Referenced by PopulateAudacityPage().
wxBoxSizer* AboutDialog::topsizer
The documentation for this class was generated from the following files:
AboutDialog.h
AboutDialog.cpp