Audacity: Effect Class Reference
Effect Class Reference
Base class for many of the effects in Audacity.
#include <Effect.h>
Public Member Functions
virtual wxString GetEffectName ()=0
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()=0
virtual wxString GetEffectDescription ()
virtual int GetEffectFlags ()
virtual bool TransferParameters (Shuttle &shuttle)
void SetEffectFlags (int NewFlags)
virtual void Preview ()
int GetID ()
bool DoEffect (wxWindow *parent, int flags, double projectRate, TrackList *list, TrackFactory *factory, double *t0, double *t1, wxString params)
wxString GetPreviewName ()
Static Public Member Functions
static wxString StripAmpersand (const wxString &str)
Protected Member Functions
Effect ()
virtual ~Effect ()
virtual bool Init ()
virtual bool PromptUser ()
virtual bool CheckWhetherSkipEffect ()
virtual bool Process ()=0
virtual void End ()
bool TotalProgress (double frac)
bool TrackProgress (int whichTrack, double frac)
bool TrackGroupProgress (int whichGroup, double frac)
int GetNumWaveTracks ()
int GetNumWaveGroups ()
void GetSamples (WaveTrack *track, sampleCount *start, sampleCount *len)
void SetTimeWarper (TimeWarper *warper)
TimeWarper * GetTimeWarper ()
void CopyInputTracks (int trackType=Track::Wave)
void ReplaceProcessedTracks (const bool bGoodResult)
void AddToOutputTracks (Track *t)
Protected Attributes
wxWindow * mParent
ProgressDialog * mProgress
double mProjectRate
TrackFactory * mFactory
TrackList * mTracks
TrackList * mOutputTracks
double mT0
double mT1
TimeWarper * mWarper
int mFlags
double mLength
int mOutputTracksType
Static Protected Attributes
static double sDefaultGenerateLen = 30.0
Private Member Functions
void CountWaveTracks ()
Private Attributes
wxArrayPtrVoid mIMap
wxArrayPtrVoid mOMap
int mNumTracks
int mNumGroups
int mID
Friends
class BatchCommands
class EffectManager
Detailed Description
Base class for many of the effects in Audacity.
Constructor & Destructor Documentation
Effect::Effect () [protected]
References ADVANCED_EFFECT, BUILTIN_EFFECT, mFlags, mLength, mNumGroups, mNumTracks, mOutputTracks, mOutputTracksType, mTracks, Track::None, and PROCESS_EFFECT.
Effect::~Effect () [protected, virtual]
References mWarper.
Member Function Documentation
void Effect::AddToOutputTracks (Track * t) [protected]
References TrackList::Add(), mIMap, mOMap, and mOutputTracks.
Referenced by EffectNyquist::ProcessOne().
virtual bool Effect::CheckWhetherSkipEffect () [inline, protected, virtual]
Reimplemented in EffectAutoDuck, EffectChangeLength, EffectChangePitch, EffectChangeSpeed, EffectChangeTempo, EffectClickRemoval, EffectLeveller, EffectNoiseRemoval, EffectNormalize, EffectSpikeCleaner, EffectStereoToMono, and EffectTruncSilence.
Referenced by DoEffect().
void Effect::CopyInputTracks (int trackType = Track::Wave) [protected]
References TrackList::Add(), Track::All, TrackListCondIterator::First(), mIMap, mOMap, mOutputTracks, mOutputTracksType, mTracks, and TrackListCondIterator::Next().
Referenced by EffectTwoPassSimpleMono::Process(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), EffectSoundTouch::Process(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Process(), EffectSimpleMono::Process(), EffectSBSMS::Process(), EffectReverse::Process(), EffectRepeat::Process(), EffectRepair::Process(), EffectNyquist::Process(), EffectNormalize::Process(), EffectNoiseRemoval::Process(), LadspaEffect::Process(), Generator::Process(), EffectEqualization::Process(), EffectEcho::Process(), EffectClickRemoval::Process(), EffectChangeSpeed::Process(), EffectAutoDuck::Process(), and AudioUnitEffect::Process().
void Effect::CountWaveTracks () [private]
References TrackListCondIterator::First(), Track::GetKind(), Track::GetLinked(), Track::GetSelected(), mNumGroups, mNumTracks, mTracks, TrackListCondIterator::Next(), and Track::Wave.
Referenced by DoEffect(), and Preview().
bool Effect::DoEffect (wxWindow * parent, int flags, double projectRate, TrackList * list, TrackFactory * factory, double * t0, double * t1, wxString params)
References CheckWhetherSkipEffect(), CONFIGURED_EFFECT, CountWaveTracks(), End(), GetEffectAction(), GetEffectName(), Init(), Shuttle::mbStoreInClient, mFactory, mOutputTracks, ShuttleCli::mParams, mParent, mProgress, mProjectRate, mT0, mT1, mTracks, Process(), PromptUser(), StripAmpersand(), and TransferParameters().
Referenced by AudacityProject::OnEffect().
virtual void Effect::End () [inline, protected, virtual]
Reimplemented in AudioUnitEffect, EffectAutoDuck, EffectAvcCompressor, EffectChangeLength, LadspaEffect, EffectLeveller, LV2Effect, EffectNormalize, EffectSimplePairedTwoTrack< _DataType, _xxxSample >, EffectSpikeCleaner, EffectStereoToMono, EffectTruncSilence, VampEffect, and EffectSimplePairedTwoTrack< IAVCSAMPLETYPE, AVCCOMPSAMPLETYPE >.
Referenced by DoEffect(), and Preview().
virtual wxString Effect::GetEffectAction () [pure virtual]
Implemented in EffectAmplify, AudioUnitEffect, EffectAutoDuck, EffectAvcCompressor, EffectBassBoost, EffectChangeLength, EffectChangePitch, EffectChangeSpeed, EffectChangeTempo, EffectClickRemoval, EffectCompressor, EffectDtmf, EffectEcho, EffectEqualization, EffectFadeIn, EffectFadeOut, EffectFindClipping, EffectInvert, LadspaEffect, EffectLeveller, LV2Effect, EffectNoise, EffectNoiseRemoval, EffectNormalize, EffectNyquist, EffectPhaser, EffectRepair, EffectRepeat, EffectReverse, EffectSilence, EffectSpikeCleaner, EffectStereoToMono, EffectTimeScale, EffectToneGen, EffectTruncSilence, VampEffect, and EffectWahwah.
Referenced by DoEffect().
virtual wxString Effect::GetEffectDescription () [inline, virtual]
Reimplemented in EffectAmplify, EffectAvcCompressor, EffectBassBoost, EffectChangePitch, EffectChangeSpeed, EffectChangeTempo, EffectDtmf, EffectEcho, EffectFindClipping, EffectNoise, EffectNormalize, EffectPhaser, EffectRepeat, EffectSilence, EffectTimeScale, EffectToneGen, and EffectWahwah.
Referenced by AudacityProject::OnEffect().
virtual int Effect::GetEffectFlags () [inline, virtual]
Referenced by LadspaEffectDialog::GetLength(), AudacityProject::OnEffect(), EffectNyquist::Process(), and EffectNyquist::ProcessOne().
virtual wxString Effect::GetEffectIdentifier () [inline, virtual]
Reimplemented in EffectAmplify, AudioUnitEffect, EffectAutoDuck, EffectBassBoost, EffectChangeLength, EffectChangePitch, EffectChangeSpeed, EffectChangeTempo, EffectClickRemoval, EffectCompressor, EffectDtmf, EffectEcho, EffectEqualization, EffectFadeIn, EffectFadeOut, EffectFindClipping, EffectInvert, LadspaEffect, EffectLeveller, LV2Effect, EffectNoise, EffectNoiseRemoval, EffectNormalize, EffectNyquist, EffectPhaser, EffectRepair, EffectRepeat, EffectReverse, EffectSilence, EffectSpikeCleaner, EffectStereoToMono, EffectTimeScale, EffectToneGen, EffectTruncSilence, VampEffect, and EffectWahwah.
virtual wxString Effect::GetEffectName () [pure virtual]
Implemented in EffectAmplify, AudioUnitEffect, EffectAutoDuck, EffectAvcCompressor, EffectBassBoost, EffectChangeLength, EffectChangePitch, EffectChangeSpeed, EffectChangeTempo, EffectClickRemoval, EffectCompressor, EffectDtmf, EffectEcho, EffectEqualization, EffectFadeIn, EffectFadeOut, EffectFindClipping, EffectInvert, LadspaEffect, EffectLeveller, LV2Effect, EffectNoise, EffectNoiseRemoval, EffectNormalize, EffectNyquist, EffectPhaser, EffectRepair, EffectRepeat, EffectReverse, EffectSilence, EffectSpikeCleaner, EffectStereoToMono, EffectTimeScale, EffectToneGen, EffectTruncSilence, VampEffect, and EffectWahwah.
Referenced by AudacityProject::CreateMenusAndCommands(), DoEffect(), AudacityProject::OnEffect(), EffectCategory::CompareEffects::operator()(), Preview(), and EffectManager::RegisterEffect().
int Effect::GetID () [inline]
int Effect::GetNumWaveGroups () [inline, protected]
Referenced by VampEffect::Process(), and EffectNyquist::Process().
int Effect::GetNumWaveTracks () [inline, protected]
Referenced by EffectAutoDuck::ApplyDuckFade(), EffectAutoDuck::Process(), EffectTwoPassSimpleMono::ProcessOne(), and EffectNoiseRemoval::PromptUser().
wxString Effect::GetPreviewName ()
void Effect::GetSamples (WaveTrack * track, sampleCount * start, sampleCount * len) [protected]
References WaveTrack::GetEndTime(), WaveTrack::GetStartTime(), INSERT_EFFECT, WaveTrack::InsertSilence(), mFlags, mLength, mT0, mT1, and WaveTrack::TimeToLongSamples().
Referenced by EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Init(), VampEffect::Process(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Process(), LadspaEffect::Process(), and AudioUnitEffect::Process().
TimeWarper * Effect::GetTimeWarper () [protected]
References mWarper.
Referenced by EffectSoundTouch::Process(), EffectSBSMS::Process(), Generator::Process(), EffectSoundTouch::ProcessLabelTrack(), EffectSBSMS::ProcessLabelTrack(), EffectChangeSpeed::ProcessLabelTrack(), EffectSoundTouch::ProcessOne(), EffectChangeSpeed::ProcessOne(), and EffectSoundTouch::ProcessStereo().
virtual bool Effect::Init () [inline, protected, virtual]
Reimplemented in EffectAmplify, AudioUnitEffect, EffectAutoDuck, EffectAvcCompressor, EffectChangeLength, EffectChangePitch, EffectChangeTempo, EffectClickRemoval, EffectCompressor, EffectDtmf, EffectEqualization, Generator, LadspaEffect, EffectLeveller, LV2Effect, EffectNoise, EffectNoiseRemoval, EffectNormalize, EffectSimplePairedTwoTrack< _DataType, _xxxSample >, EffectSpikeCleaner, EffectStereoToMono, EffectTimeScale, EffectTruncSilence, VampEffect, and EffectSimplePairedTwoTrack< IAVCSAMPLETYPE, AVCCOMPSAMPLETYPE >.
Referenced by DoEffect(), and Preview().
void Effect::Preview () [virtual]
References TrackList::Clear(), CountWaveTracks(), End(), eProgressSuccess, TrackListCondIterator::First(), floatSample, gAudioIO, GetEffectName(), AudioIO::GetStreamTime(), gPrefs, Init(), AudioIO::IsBusy(), AudioIO::IsStreamActive(), mFactory, MixAndRender(), mOutputTracks, mProgress, mProjectRate, mT0, mT1, mTracks, TrackListCondIterator::Next(), pdlgHideCancelButton, Process(), Track::SetSelected(), AudioIO::StartStream(), AudioIO::StopStream(), StripAmpersand(), ProgressDialog::Update(), and Track::Wave.
Referenced by WahwahDialog::OnPreview(), TruncSilenceDialog::OnPreview(), RepeatDialog::OnPreview(), PhaserDialog::OnPreview(), NormalizeDialog::OnPreview(), NoiseRemovalDialog::OnPreview(), LevellerDialog::OnPreview(), EqualizationDialog::OnPreview(), EchoDialog::OnPreview(), CompressorDialog::OnPreview(), ClickRemovalDialog::OnPreview(), ChangeTempoDialog::OnPreview(), ChangeSpeedDialog::OnPreview(), ChangePitchDialog::OnPreview(), BassBoostDialog::OnPreview(), AudioUnitDialog::OnPreview(), and AmplifyDialog::OnPreview().
virtual bool Effect::Process () [protected, pure virtual]
Implemented in AudioUnitEffect, EffectAutoDuck, EffectChangeLength, EffectChangePitch, EffectChangeSpeed, EffectChangeTempo, EffectClickRemoval, EffectEcho, EffectEqualization, EffectFindClipping, Generator, LadspaEffect, LV2Effect, EffectNoiseRemoval, EffectNormalize, EffectNyquist, EffectRepair, EffectRepeat, EffectReverse, EffectSBSMS, EffectSimpleMono, EffectSimplePairedTwoTrack< _DataType, _xxxSample >, EffectSoundTouch, EffectStereoToMono, EffectTimeScale, EffectTruncSilence, EffectTwoPassSimpleMono, VampEffect, and EffectSimplePairedTwoTrack< IAVCSAMPLETYPE, AVCCOMPSAMPLETYPE >.
Referenced by DoEffect(), and Preview().
virtual bool Effect::PromptUser () [inline, protected, virtual]
Reimplemented in EffectAmplify, AudioUnitEffect, EffectAutoDuck, EffectAvcCompressor, EffectBassBoost, EffectChangeLength, EffectChangePitch, EffectChangeSpeed, EffectChangeTempo, EffectClickRemoval, EffectCompressor, EffectDtmf, EffectEcho, EffectEqualization, EffectFindClipping, LadspaEffect, EffectLeveller, LV2Effect, EffectNoise, EffectNoiseRemoval, EffectNormalize, EffectNyquist, EffectPhaser, EffectRepair, EffectRepeat, EffectSilence, EffectSpikeCleaner, EffectTimeScale, EffectToneGen, EffectTruncSilence, VampEffect, and EffectWahwah.
Referenced by DoEffect(), and BatchCommands::PromptForParamsFor().
void Effect::ReplaceProcessedTracks (const bool bGoodResult) [protected]
References TrackList::Add(), TrackList::Clear(), TrackListIterator::First(), ODManager::Instance(), ODManager::IsInstanceCreated(), mIMap, mOMap, mOutputTracks, mOutputTracksType, mTracks, Track::None, TrackList::Remove(), TrackListIterator::RemoveCurrent(), TrackList::Replace(), and ODManager::ReplaceWaveTrack().
Referenced by EffectTwoPassSimpleMono::Process(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), EffectSoundTouch::Process(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Process(), EffectSimpleMono::Process(), EffectSBSMS::Process(), EffectReverse::Process(), EffectRepeat::Process(), EffectRepair::Process(), EffectNyquist::Process(), EffectNormalize::Process(), EffectNoiseRemoval::Process(), LadspaEffect::Process(), Generator::Process(), EffectEqualization::Process(), EffectEcho::Process(), EffectClickRemoval::Process(), EffectChangeSpeed::Process(), EffectAutoDuck::Process(), and AudioUnitEffect::Process().
void Effect::SetEffectFlags (int NewFlags) [inline]
Referenced by AudioUnitEffect::AudioUnitEffect(), EffectAutoDuck::EffectAutoDuck(), EffectDtmf::EffectDtmf(), EffectFindClipping::EffectFindClipping(), EffectNoise::EffectNoise(), EffectNyquist::EffectNyquist(), EffectSilence::EffectSilence(), EffectToneGen::EffectToneGen(), LadspaEffect::LadspaEffect(), EffectNyquist::Parse(), EffectNyquist::ParseFile(), EffectManager::RegisterEffect(), EffectNyquist::SetCommand(), and VampEffect::VampEffect().
void Effect::SetTimeWarper (TimeWarper * warper) [protected]
References mWarper.
Referenced by EffectSBSMS::Process(), Generator::Process(), EffectChangeTempo::Process(), EffectChangePitch::Process(), EffectSBSMS::ProcessLabelTrack(), EffectChangeSpeed::ProcessLabelTrack(), and EffectChangeSpeed::ProcessOne().
wxString Effect::StripAmpersand (const wxString & str) [static]
Referenced by DoEffect(), Preview(), and EffectManager::RegisterEffect().
bool Effect::TotalProgress (double frac) [protected]
References eProgressSuccess, mProgress, and ProgressDialog::Update().
Referenced by EffectAutoDuck::ApplyDuckFade(), EffectNyquist::GetCallback(), EffectAutoDuck::Process(), EffectTwoPassSimpleMono::ProcessOne(), and EffectNyquist::PutCallback().
bool Effect::TrackGroupProgress (int whichGroup, double frac) [protected]
References eProgressSuccess, mNumGroups, mProgress, and ProgressDialog::Update().
Referenced by VampEffect::Process(), LadspaEffect::ProcessStereo(), AudioUnitEffect::ProcessStereo(), and EffectSimplePairedTwoTrack< _DataType, _xxxSample >::ProcessTwo().
bool Effect::TrackProgress (int whichTrack, double frac) [protected]
References eProgressSuccess, mNumTracks, mProgress, and ProgressDialog::Update().
Referenced by BlockGenerator::GenerateTrack(), EffectDtmf::GenerateTrack(), VampEffect::Process(), EffectTruncSilence::Process(), EffectSBSMS::Process(), EffectRepeat::Process(), EffectStereoToMono::ProcessOne(), EffectSoundTouch::ProcessOne(), EffectSimpleMono::ProcessOne(), EffectRepair::ProcessOne(), EffectNormalize::ProcessOne(), EffectNoiseRemoval::ProcessOne(), EffectFindClipping::ProcessOne(), EffectEqualization::ProcessOne(), EffectEcho::ProcessOne(), EffectClickRemoval::ProcessOne(), EffectChangeSpeed::ProcessOne(), EffectReverse::ProcessOneClip(), EffectSoundTouch::ProcessStereo(), LadspaEffect::ProcessStereo(), AudioUnitEffect::ProcessStereo(), and EffectSimplePairedTwoTrack< _DataType, _xxxSample >::ProcessTwo().
virtual bool Effect::TransferParameters (Shuttle & shuttle) [inline, virtual]
Reimplemented in EffectAmplify, EffectAutoDuck, EffectAvcCompressor, EffectBassBoost, EffectChangeLength, EffectChangePitch, EffectChangeSpeed, EffectChangeTempo, EffectClickRemoval, EffectCompressor, EffectDtmf, EffectEcho, EffectEqualization, EffectFindClipping, EffectLeveller, EffectNoise, EffectNoiseRemoval, EffectNormalize, EffectPhaser, EffectRepair, EffectRepeat, EffectSpikeCleaner, EffectTimeScale, EffectToneGen, EffectTruncSilence, and EffectWahwah.
Referenced by DoEffect(), BatchCommands::GetCurrentParamsFor(), and BatchCommands::SetCurrentParametersFor().
Friends And Related Function Documentation
friend class BatchCommands [friend]
friend class EffectManager [friend]
Member Data Documentation
TrackFactory* Effect::mFactory [protected]
Referenced by DoEffect(), Preview(), VampEffect::Process(), EffectSBSMS::Process(), Generator::Process(), EffectFindClipping::Process(), EffectSoundTouch::ProcessOne(), EffectNyquist::ProcessOne(), EffectNoiseRemoval::ProcessOne(), EffectChangeSpeed::ProcessOne(), and EffectSoundTouch::ProcessStereo().
int Effect::mFlags [protected]
Referenced by Effect(), and GetSamples().
int Effect::mID [private]
Referenced by EffectManager::RegisterEffect().
wxArrayPtrVoid Effect::mIMap [private]
Referenced by AddToOutputTracks(), CopyInputTracks(), and ReplaceProcessedTracks().
double Effect::mLength [protected]
Referenced by Effect(), GetSamples(), LadspaEffect::LadspaEffect(), and LadspaEffect::PromptUser().
int Effect::mNumGroups [private]
Referenced by CountWaveTracks(), Effect(), and TrackGroupProgress().
int Effect::mNumTracks [private]
Referenced by CountWaveTracks(), Effect(), and TrackProgress().
wxArrayPtrVoid Effect::mOMap [private]
Referenced by AddToOutputTracks(), CopyInputTracks(), and ReplaceProcessedTracks().
TrackList* Effect::mOutputTracks [protected]
Referenced by AddToOutputTracks(), CopyInputTracks(), DoEffect(), Effect(), Preview(), EffectTruncSilence::Process(), EffectStereoToMono::Process(), EffectSoundTouch::Process(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Process(), EffectSimpleMono::Process(), EffectSBSMS::Process(), EffectReverse::Process(), EffectRepeat::Process(), EffectRepair::Process(), EffectNyquist::Process(), EffectNormalize::Process(), EffectNoiseRemoval::Process(), LadspaEffect::Process(), Generator::Process(), EffectEqualization::Process(), EffectEcho::Process(), EffectClickRemoval::Process(), EffectChangeSpeed::Process(), EffectAutoDuck::Process(), AudioUnitEffect::Process(), EffectStereoToMono::ProcessOne(), EffectNyquist::ProcessOne(), EffectTwoPassSimpleMono::ProcessPass(), and ReplaceProcessedTracks().
int Effect::mOutputTracksType [protected]
Referenced by CopyInputTracks(), Effect(), and ReplaceProcessedTracks().
wxWindow* Effect::mParent [protected]
Referenced by DoEffect(), EffectAutoDuck::Init(), EffectNyquist::Process(), EffectNyquist::ProcessOne(), BatchCommands::PromptForParamsFor(), EffectWahwah::PromptUser(), VampEffect::PromptUser(), EffectTruncSilence::PromptUser(), EffectToneGen::PromptUser(), EffectTimeScale::PromptUser(), EffectSpikeCleaner::PromptUser(), EffectSilence::PromptUser(), EffectRepeat::PromptUser(), EffectPhaser::PromptUser(), EffectNyquist::PromptUser(), EffectNormalize::PromptUser(), EffectNoiseRemoval::PromptUser(), EffectNoise::PromptUser(), EffectLeveller::PromptUser(), LadspaEffect::PromptUser(), EffectFindClipping::PromptUser(), EffectEqualization::PromptUser(), EffectEcho::PromptUser(), EffectDtmf::PromptUser(), EffectCompressor::PromptUser(), EffectClickRemoval::PromptUser(), EffectChangeTempo::PromptUser(), EffectChangeSpeed::PromptUser(), EffectChangePitch::PromptUser(), EffectChangeLength::PromptUser(), EffectBassBoost::PromptUser(), EffectAvcCompressor::PromptUser(), EffectAutoDuck::PromptUser(), AudioUnitEffect::PromptUser(), and EffectAmplify::PromptUser().
ProgressDialog* Effect::mProgress [protected]
Referenced by DoEffect(), Preview(), EffectNyquist::Process(), TotalProgress(), TrackGroupProgress(), and TrackProgress().
double Effect::mProjectRate [protected]
Referenced by RepeatDialog::DisplayNewTime(), DoEffect(), VampEffect::Init(), LadspaEffect::Init(), AudioUnitEffect::Init(), EffectNoiseRemoval::Initialize(), LadspaEffect::LadspaEffect(), NoiseDialog::PopulateOrExchange(), DtmfDialog::PopulateOrExchange(), ToneGenDialog::PopulateOrExchangeExtended(), ToneGenDialog::PopulateOrExchangeStandard(), Preview(), and EffectSilence::PromptUser().
double Effect::mT0 [protected]
Referenced by EffectAutoDuck::ApplyDuckFade(), EffectChangePitch::DeduceFrequencies(), DoEffect(), GetSamples(), EffectDtmf::Init(), EffectChangeTempo::Init(), EffectChangeLength::Init(), EffectAmplify::Init(), Preview(), EffectTruncSilence::Process(), EffectSoundTouch::Process(), EffectSimpleMono::Process(), EffectSBSMS::Process(), EffectReverse::Process(), EffectRepeat::Process(), EffectRepair::Process(), EffectNyquist::Process(), EffectNormalize::Process(), EffectNoiseRemoval::Process(), Generator::Process(), EffectFindClipping::Process(), EffectEqualization::Process(), EffectEcho::Process(), EffectClickRemoval::Process(), EffectChangeTempo::Process(), EffectChangeSpeed::Process(), EffectAutoDuck::Process(), EffectSBSMS::ProcessLabelTrack(), EffectChangeSpeed::ProcessLabelTrack(), EffectNyquist::ProcessOne(), EffectTwoPassSimpleMono::ProcessPass(), EffectToneGen::PromptUser(), EffectSilence::PromptUser(), EffectRepeat::PromptUser(), EffectNoise::PromptUser(), LadspaEffect::PromptUser(), EffectNoise::Success(), and EffectDtmf::Success().
double Effect::mT1 [protected]
Referenced by EffectAutoDuck::ApplyDuckFade(), DoEffect(), GetSamples(), EffectDtmf::Init(), EffectChangeTempo::Init(), EffectChangeLength::Init(), EffectAmplify::Init(), Preview(), EffectTruncSilence::Process(), EffectSoundTouch::Process(), EffectSimpleMono::Process(), EffectSBSMS::Process(), EffectReverse::Process(), EffectRepeat::Process(), EffectRepair::Process(), EffectNyquist::Process(), EffectNormalize::Process(), EffectNoiseRemoval::Process(), Generator::Process(), EffectFindClipping::Process(), EffectEqualization::Process(), EffectEcho::Process(), EffectClickRemoval::Process(), EffectChangeTempo::Process(), EffectChangeSpeed::Process(), EffectAutoDuck::Process(), EffectSBSMS::ProcessLabelTrack(), EffectChangeSpeed::ProcessLabelTrack(), EffectNyquist::ProcessOne(), EffectTwoPassSimpleMono::ProcessPass(), EffectToneGen::PromptUser(), EffectSilence::PromptUser(), EffectRepeat::PromptUser(), EffectNoise::PromptUser(), LadspaEffect::PromptUser(), EffectNoise::Success(), and EffectDtmf::Success().
TrackList* Effect::mTracks [protected]
Referenced by EffectStereoToMono::CheckWhetherSkipEffect(), CopyInputTracks(), CountWaveTracks(), EffectChangePitch::DeduceFrequencies(), DoEffect(), EffectEqualization::DontPromptUser(), Effect(), EffectNyquist::GetCtrlValue(), VampEffect::Init(), EffectSimplePairedTwoTrack< _DataType, _xxxSample >::Init(), LadspaEffect::Init(), EffectAutoDuck::Init(), EffectAmplify::Init(), EffectCompressor::InitPass1(), Preview(), VampEffect::Process(), EffectTruncSilence::Process(), EffectFindClipping::Process(), EffectChangeLength::Process(), EffectSpikeCleaner::ProcessSimpleMono(), EffectRepeat::PromptUser(), EffectEqualization::PromptUser(), and ReplaceProcessedTracks().
TimeWarper* Effect::mWarper [protected]
Referenced by GetTimeWarper(), SetTimeWarper(), and ~Effect().
double Effect::sDefaultGenerateLen = 30.0 [static, protected]
Referenced by LadspaEffect::PromptUser().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp