Audacity: RingBuffer Class Reference
RingBuffer Class Reference
Holds streamed audio samples.
#include <RingBuffer.h>
Public Member Functions
RingBuffer (sampleFormat format, int size)
~RingBuffer ()
int AvailForPut ()
int Put (samplePtr buffer, sampleFormat format, int samples)
int AvailForGet ()
int Get (samplePtr buffer, sampleFormat format, int samples)
int Discard (int samples)
Private Member Functions
int Len ()
Private Attributes
sampleFormat mFormat
int mStart
int mEnd
int mBufferSize
samplePtr mBuffer
Detailed Description
Holds streamed audio samples.
This class is thread-safe, assuming that there is only one thread writing, and one thread reading. If two threads both need to read, or both need to write, they need to lock this class from outside using their own mutex.
AvailForPut and AvailForGet may underestimate but will never overestimate.
Constructor & Destructor Documentation
RingBuffer::RingBuffer (sampleFormat format, int size)
References mBuffer, mBufferSize, mEnd, mFormat, mStart, and NewSamples().
RingBuffer::~RingBuffer ()
References DeleteSamples(), and mBuffer.
Member Function Documentation
int RingBuffer::AvailForGet ()
References Len().
Referenced by audacityAudioCallback(), and AudioIO::GetCommonlyAvailCapture().
int RingBuffer::AvailForPut ()
References Len(), and mBufferSize.
Referenced by audacityAudioCallback(), and AudioIO::GetCommonlyAvailPlayback().
int RingBuffer::Discard (int samples)
References Len(), mBufferSize, and mStart.
Referenced by audacityAudioCallback().
int RingBuffer::Get (samplePtr buffer, sampleFormat format, int samples)
References CopySamples(), Len(), mBuffer, mBufferSize, mFormat, mStart, and SAMPLE_SIZE.
Referenced by audacityAudioCallback(), and AudioIO::FillBuffers().
int RingBuffer::Len () [private]
References mBufferSize, mEnd, and mStart.
Referenced by AvailForGet(), AvailForPut(), Discard(), Get(), and Put().
int RingBuffer::Put (samplePtr buffer, sampleFormat format, int samples)
References CopySamples(), Len(), mBuffer, mBufferSize, mEnd, mFormat, and SAMPLE_SIZE.
Referenced by audacityAudioCallback(), and AudioIO::FillBuffers().
Member Data Documentation
samplePtr RingBuffer::mBuffer [private]
Referenced by Get(), Put(), RingBuffer(), and ~RingBuffer().
int RingBuffer::mBufferSize [private]
Referenced by AvailForPut(), Discard(), Get(), Len(), Put(), and RingBuffer().
int RingBuffer::mEnd [private]
Referenced by Len(), Put(), and RingBuffer().
sampleFormat RingBuffer::mFormat [private]
Referenced by Get(), Put(), and RingBuffer().
int RingBuffer::mStart [private]
Referenced by Discard(), Get(), Len(), and RingBuffer().
The documentation for this class was generated from the following files:
RingBuffer.h
RingBuffer.cpp