Audacity: EffectCategory Class Reference
EffectCategory Class Reference
EffectManager contains all the information about an effect category.
#include <EffectCategory.h>
Classes
struct CompareCategories
struct CompareEffects
Public Types
typedef std::set< Effect
*, CompareEffects > EffectSet
typedef std::set
< EffectCategory
*, CompareCategories > CategorySet
Public Member Functions
const wxString & GetUri () const
const wxString & GetName () const
const CategorySet & GetParents () const
const CategorySet & GetSubCategories () const
EffectSet GetEffects (int type=ALL_EFFECTS) const
EffectSet GetAllEffects (int type=ALL_EFFECTS) const
Protected Member Functions
EffectCategory (const wxString &uri, const wxString &name)
bool AddParent (EffectCategory *parent)
bool AddEffect (Effect *effect)
void FreezeParents ()
void UnfreezeParents ()
bool IsDescendantOf (EffectCategory *category)
Protected Attributes
wxString mUri
wxString mName
CategorySet mParents
CategorySet mSubCategories
EffectSet mEffects
bool mParentsFrozen
Friends
class EffectManager
Detailed Description
EffectManager contains all the information about an effect category.
That includes links to parent categories and subcategories, name and URI, and of course the effects that belong to this category.
Member Typedef Documentation
typedef std::set<EffectCategory*, CompareCategories> EffectCategory::CategorySet
typedef std::set<Effect*, CompareEffects> EffectCategory::EffectSet
Constructor & Destructor Documentation
EffectCategory::EffectCategory (const wxString & uri, const wxString & name) [protected]
All constructors and destructors are non-public, allowing only EffectManager (which is our friend) to create new categories.
Member Function Documentation
bool EffectCategory::AddEffect (Effect * effect) [protected]
Add an effect to this category. This is protected so only our friend EffectManager can call it.
References mEffects.
Referenced by EffectManager::RegisterEffect().
bool EffectCategory::AddParent (EffectCategory * parent) [protected]
Add a new parent category to this category, making this a subcategory of the parent. Returns true if the parent was added (or already had been added), false if the parent could not be added because FreezeParents() has been called. This is protected so only our friend EffectManager can change the category graph (it needs to keep track of root nodes).
References IsDescendantOf(), mParents, mParentsFrozen, and mSubCategories.
void EffectCategory::FreezeParents () [protected]
This function sets a flag that makes AddParent() fail when called for this category object, preventing anyone from adding new parents to this category. This is useful if you are mapping a different category tree onto the already existing one (e.g. LRDF onto LV2) and don't want to add more internal parent/subcategory relations between already existing categories, but still want to allow adding of completely new, unmapped subcategories.
References mParentsFrozen.
EffectSet EffectCategory::GetAllEffects (int type = ALL_EFFECTS) const
Return all the effects that belong to this immediate category or any of its subcategories), filtered by effect type.
References GetEffects(), and mSubCategories.
EffectSet EffectCategory::GetEffects (int type = ALL_EFFECTS) const
Return all the effects that belong to this immediate category (not any of its subcategories), filtered by effect type.
References mEffects.
Referenced by AudacityProject::CreateMenusAndCommands(), and GetAllEffects().
const wxString & EffectCategory::GetName () const
Return the (possibly i18n'd) name for the category.
References mName.
Referenced by EffectCategory::CompareCategories::operator()().
const CategorySet & EffectCategory::GetParents () const
Return all the parent categories of this category. A category may have 0, 1 or more parents - the structure of all categories forms a DAG, not necessarily a tree, since LV2 allows for categories to have multiple parents (e.g. Reverb is a subcategory of both Simulator and Delay).
References mParents.
const CategorySet & EffectCategory::GetSubCategories () const
Return all the subcategories of this category. A category may have 0, 1 or more subcategories.
References mSubCategories.
Referenced by AudacityProject::CreateMenusAndCommands().
const wxString & EffectCategory::GetUri () const
Return the URI for this category, which is used as a global, persistent string identifier for the category.
References mUri.
bool EffectCategory::IsDescendantOf (EffectCategory * category) [protected]
Returns true if category is an ancestor of this category, false if not.
References mParents.
Referenced by AddParent().
void EffectCategory::UnfreezeParents () [protected]
Reset the flag set by FreezeParents(), allowing to add parent categories again.
References mParentsFrozen.
Friends And Related Function Documentation
friend class EffectManager [friend]
Member Data Documentation
EffectSet EffectCategory::mEffects [protected]
Referenced by AddEffect(), and GetEffects().
wxString EffectCategory::mName [protected]
Referenced by GetName().
CategorySet EffectCategory::mParents [protected]
Referenced by AddParent(), GetParents(), and IsDescendantOf().
bool EffectCategory::mParentsFrozen [protected]
Referenced by AddParent(), FreezeParents(), and UnfreezeParents().
CategorySet EffectCategory::mSubCategories [protected]
Referenced by AddParent(), GetAllEffects(), and GetSubCategories().
wxString EffectCategory::mUri [protected]
Referenced by GetUri().
The documentation for this class was generated from the following files:
EffectCategory.h
EffectCategory.cpp