Audacity: SilentBlockFile Class Reference
SilentBlockFile Class Reference
A BlockFile containing nothing but silence. Saves disk space.
#include <SilentBlockFile.h>
Public Member Functions
SilentBlockFile (sampleCount sampleLen)
virtual ~SilentBlockFile ()
virtual bool ReadSummary (void *data)
Read the summary section of the disk file.
virtual int ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len)
Read the data section of the disk file.
virtual BlockFile * Copy (wxFileName newFileName)
Create a new block file identical to this one.
virtual void SaveXML (XMLWriter &xmlFile)
Write an XML representation of this file.
virtual wxLongLong GetSpaceUsage ()
virtual void Recover ()
if the on-disk state disappeared, either recover it (if it was
Static Public Member Functions
static BlockFile * BuildFromXML (DirManager &dm, const wxChar **attrs)
static
Detailed Description
A BlockFile containing nothing but silence. Saves disk space.
Constructor & Destructor Documentation
SilentBlockFile::SilentBlockFile (sampleCount sampleLen)
References BlockFile::mMax, BlockFile::mMin, and BlockFile::mRMS.
Referenced by BuildFromXML(), and Copy().
SilentBlockFile::~SilentBlockFile () [virtual]
Member Function Documentation
BlockFile * SilentBlockFile::BuildFromXML (DirManager & dm, const wxChar ** attrs) [static]
static
References XMLValueChecker::IsGoodInt(), and SilentBlockFile().
Referenced by DirManager::HandleXMLTag().
BlockFile * SilentBlockFile::Copy (wxFileName newFileName) [virtual]
Create a new block file identical to this one.
Create a copy of this BlockFile.
Implements BlockFile.
References BlockFile::mLen, and SilentBlockFile().
wxLongLong SilentBlockFile::GetSpaceUsage () [virtual]
Implements BlockFile.
int SilentBlockFile::ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len) [virtual]
Read the data section of the disk file.
Implements BlockFile.
References ClearSamples().
bool SilentBlockFile::ReadSummary (void * data) [virtual]
Read the summary section of the disk file.
Implements BlockFile.
References BlockFile::mSummaryInfo, and SummaryInfo::totalSummaryBytes.
virtual void SilentBlockFile::Recover () [inline, virtual]
if the on-disk state disappeared, either recover it (if it was
Implements BlockFile.
void SilentBlockFile::SaveXML (XMLWriter & xmlFile) [virtual]
Write an XML representation of this file.
Implements BlockFile.
References XMLWriter::EndTag(), BlockFile::mLen, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
The documentation for this class was generated from the following files:
SilentBlockFile.h
SilentBlockFile.cpp