Audacity: TranscriptionToolBar Class Reference
TranscriptionToolBar Class Reference
A kind of ToolBar used to help with analysing voice recordings.
#include <TranscriptionToolBar.h>
Public Member Functions
TranscriptionToolBar ()
virtual ~TranscriptionToolBar ()
void Create (wxWindow *parent)
virtual void OnKeyEvent (wxKeyEvent &event)
virtual void OnPlaySpeed (wxCommandEvent &event)
virtual void OnSpeedSlider (wxCommandEvent &event)
virtual void OnStartOn (wxCommandEvent &event)
virtual void OnStartOff (wxCommandEvent &event)
virtual void OnEndOn (wxCommandEvent &event)
virtual void OnEndOff (wxCommandEvent &event)
virtual void OnSelectSound (wxCommandEvent &event)
virtual void OnSelectSilence (wxCommandEvent &event)
virtual void OnCalibrate (wxCommandEvent &event)
virtual void OnMakeLabel (wxCommandEvent &event)
virtual void OnAutomateSelection (wxCommandEvent &event)
virtual void OnSensitivitySlider (wxCommandEvent &event)
virtual void Populate ()
virtual void Repaint (wxDC *dc)
virtual void EnableDisableButtons ()
virtual void UpdatePrefs ()
void OnFocus (wxFocusEvent &event)
void OnCaptureKey (wxCommandEvent &event)
virtual double GetSensitivity ()
virtual void SetKeyType (wxCommandEvent &event)
void PlayAtSpeed ()
void ShowPlaySpeedDialog ()
void AdjustPlaySpeed (float adj)
DECLARE_CLASS (TranscriptionToolBar)
DECLARE_EVENT_TABLE ()
Private Member Functions
void InitializeTranscriptionToolBar ()
AButton * AddButton (teBmps eFore, teBmps eDisabled, int id, const wxChar *label)
void GetSamples (WaveTrack *t, sampleCount *s0, sampleCount *slen)
void SetButton (bool newstate, AButton *button)
void RegenerateTooltips ()
Private Attributes
AButton * mButtons [TTBNumButtons]
wxImage * upImage
wxImage * downImage
wxImage * hiliteImage
ASlider * mPlaySpeedSlider
double mPlaySpeed
ASlider * mSensitivitySlider
double mSensitivity
VoiceKey * mVk
wxBrush mBackgroundBrush
wxPen mBackgroundPen
int mBackgroundWidth
int mBackgroundHeight
TimeTrack * mTimeTrack
wxChoice * mKeyTypeChoice
Detailed Description
A kind of ToolBar used to help with analysing voice recordings.
Constructor & Destructor Documentation
TranscriptionToolBar::TranscriptionToolBar ()
TranscriptionToolBar::~TranscriptionToolBar () [virtual]
References mTimeTrack, and mVk.
Member Function Documentation
AButton * TranscriptionToolBar::AddButton (teBmps eFore, teBmps eDisabled, int id, const wxChar * label) [private]
This is a convenience function that allows for button creation in MakeButtons() with fewer arguments Very similar to code in ControlToolBar...
References ToolBar::Add(), ThemeBase::ImageSize(), ToolBar::MakeButton(), mButtons, and theTheme.
Referenced by Populate().
void TranscriptionToolBar::AdjustPlaySpeed (float adj)
References ASlider::Decrease(), ASlider::Increase(), mPlaySpeedSlider, and OnSpeedSlider().
Referenced by AudacityProject::OnPlaySpeedDec(), and AudacityProject::OnPlaySpeedInc().
void TranscriptionToolBar::Create (wxWindow * parent) [virtual]
Reimplemented from ToolBar.
References AButton::Disable(), AButton::Enable(), ASlider::Get(), mBackgroundBrush, mBackgroundHeight, mBackgroundPen, mBackgroundWidth, mButtons, mPlaySpeed, mPlaySpeedSlider, TTB_AutomateSelection, TTB_Calibrate, TTB_EndOff, TTB_EndOn, TTB_MakeLabel, TTB_SelectSilence, TTB_SelectSound, TTB_StartOff, and TTB_StartOn.
TranscriptionToolBar::DECLARE_CLASS (TranscriptionToolBar)
Reimplemented from ToolBar.
TranscriptionToolBar::DECLARE_EVENT_TABLE ()
Reimplemented from ToolBar.
void TranscriptionToolBar::EnableDisableButtons () [virtual]
Implements ToolBar.
References GetActiveProject(), AudacityProject::GetSel0(), AudacityProject::GetSel1(), AudacityProject::GetTracks(), mButtons, AButton::SetEnabled(), and TTB_Calibrate.
void TranscriptionToolBar::GetSamples (WaveTrack * t, sampleCount * s0, sampleCount * slen) [private]
References GetActiveProject(), WaveTrack::GetOffset(), WaveTrack::GetRate(), AudacityProject::GetSel0(), and AudacityProject::GetSel1().
Referenced by OnAutomateSelection(), OnCalibrate(), OnEndOff(), OnEndOn(), OnSelectSilence(), OnSelectSound(), OnStartOff(), and OnStartOn().
double TranscriptionToolBar::GetSensitivity () [virtual]
References mSensitivity.
Referenced by OnAutomateSelection(), OnEndOff(), OnEndOn(), OnSelectSilence(), OnSelectSound(), OnStartOff(), and OnStartOn().
void TranscriptionToolBar::InitializeTranscriptionToolBar () [private]
void TranscriptionToolBar::OnAutomateSelection (wxCommandEvent & event) [virtual]
References VoiceKey::AdjustThreshold(), AudacityProject::DoAddLabel(), TrackListIterator::First(), gAudioIO, GetActiveProject(), GetSamples(), GetSensitivity(), AudacityProject::GetTracks(), AudioIO::IsBusy(), mButtons, mVk, VoiceKey::OffForward(), VoiceKey::OnForward(), AudacityProject::RedrawProject(), SetButton(), TTB_AutomateSelection, and TTB_EndOff.
void TranscriptionToolBar::OnCalibrate (wxCommandEvent & event) [virtual]
References VoiceKey::AdjustThreshold(), VoiceKey::CalibrateNoise(), AButton::Enable(), TrackListIterator::First(), gAudioIO, GetActiveProject(), GetSamples(), AudacityProject::GetTracks(), AudioIO::IsBusy(), mButtons, mVk, OnSensitivitySlider(), SetButton(), TTB_AutomateSelection, TTB_Calibrate, TTB_EndOff, TTB_EndOn, TTB_SelectSilence, TTB_SelectSound, TTB_StartOff, and TTB_StartOn.
void TranscriptionToolBar::OnCaptureKey (wxCommandEvent & event)
References mPlaySpeedSlider.
void TranscriptionToolBar::OnEndOff (wxCommandEvent & event) [virtual]
References VoiceKey::AdjustThreshold(), TrackListIterator::First(), gAudioIO, GetActiveProject(), GetSamples(), GetSensitivity(), AudacityProject::GetTracks(), AudioIO::IsBusy(), mButtons, mVk, VoiceKey::OffBackward(), AudacityProject::RedrawProject(), SetButton(), AudacityProject::SetSel1(), and TTB_EndOff.
void TranscriptionToolBar::OnEndOn (wxCommandEvent & event) [virtual]
References VoiceKey::AdjustThreshold(), TrackListIterator::First(), gAudioIO, GetActiveProject(), GetSamples(), GetSensitivity(), AudacityProject::GetTracks(), AudioIO::IsBusy(), mButtons, mVk, VoiceKey::OnBackward(), AudacityProject::RedrawProject(), SetButton(), AudacityProject::SetSel1(), and TTB_EndOn.
void TranscriptionToolBar::OnFocus (wxFocusEvent & event)
Referenced by Populate().
void TranscriptionToolBar::OnKeyEvent (wxKeyEvent & event) [virtual]
References gAudioIO, and AudioIO::IsBusy().
void TranscriptionToolBar::OnMakeLabel (wxCommandEvent & event) [virtual]
References AudacityProject::DoAddLabel(), GetActiveProject(), AudacityProject::GetSel0(), AudacityProject::GetSel1(), mButtons, SetButton(), and TTB_MakeLabel.
void TranscriptionToolBar::OnPlaySpeed (wxCommandEvent & event) [virtual]
References gAudioIO, GetActiveProject(), AudacityProject::GetControlToolBar(), AudacityProject::GetDirManager(), AudacityProject::GetPlayRegion(), AudioIO::IsBusy(), mButtons, mPlaySpeed, mTimeTrack, ControlToolBar::PlayPlayRegion(), SetButton(), TimeTrack::SetRangeLower(), TimeTrack::SetRangeUpper(), ControlToolBar::StopPlaying(), and TTB_PlaySpeed.
Referenced by PlayAtSpeed().
void TranscriptionToolBar::OnSelectSilence (wxCommandEvent & event) [virtual]
References VoiceKey::AdjustThreshold(), TrackListIterator::First(), gAudioIO, GetActiveProject(), TrackList::GetEndTime(), GetSamples(), GetSensitivity(), AudacityProject::GetTracks(), AudioIO::IsBusy(), mButtons, mVk, VoiceKey::OnBackward(), VoiceKey::OnForward(), AudacityProject::RedrawProject(), SetButton(), AudacityProject::SetSel0(), AudacityProject::SetSel1(), and TTB_SelectSilence.
void TranscriptionToolBar::OnSelectSound (wxCommandEvent & event) [virtual]
References VoiceKey::AdjustThreshold(), TrackListIterator::First(), gAudioIO, GetActiveProject(), TrackList::GetEndTime(), GetSamples(), GetSensitivity(), AudacityProject::GetTracks(), AudioIO::IsBusy(), mButtons, mVk, VoiceKey::OffBackward(), VoiceKey::OffForward(), AudacityProject::RedrawProject(), SetButton(), AudacityProject::SetSel0(), AudacityProject::SetSel1(), and TTB_SelectSound.
void TranscriptionToolBar::OnSensitivitySlider (wxCommandEvent & event) [virtual]
References ASlider::Get(), mSensitivity, and mSensitivitySlider.
Referenced by OnCalibrate().
void TranscriptionToolBar::OnSpeedSlider (wxCommandEvent & event) [virtual]
References ASlider::Get(), mPlaySpeed, and mPlaySpeedSlider.
Referenced by AdjustPlaySpeed(), and ShowPlaySpeedDialog().
void TranscriptionToolBar::OnStartOff (wxCommandEvent & event) [virtual]
References VoiceKey::AdjustThreshold(), TrackListIterator::First(), gAudioIO, GetActiveProject(), GetSamples(), GetSensitivity(), AudacityProject::GetTracks(), AudioIO::IsBusy(), mButtons, mVk, VoiceKey::OffForward(), AudacityProject::RedrawProject(), SetButton(), AudacityProject::SetSel0(), TTB_StartOff, and TTB_StartOn.
void TranscriptionToolBar::OnStartOn (wxCommandEvent & event) [virtual]
References VoiceKey::AdjustThreshold(), TrackListIterator::First(), gAudioIO, GetActiveProject(), GetSamples(), GetSensitivity(), AudacityProject::GetTracks(), AudioIO::IsBusy(), mButtons, mVk, VoiceKey::OnForward(), AudacityProject::RedrawProject(), SetButton(), AudacityProject::SetSel0(), and TTB_StartOn.
void TranscriptionToolBar::PlayAtSpeed ()
References OnPlaySpeed().
Referenced by AudacityProject::OnPlayAtSpeed().
void TranscriptionToolBar::Populate () [virtual]
Implements ToolBar.
References ToolBar::Add(), AddButton(), ToolBar::MakeButtonBackgroundsSmall(), mKeyTypeChoice, mPlaySpeedSlider, mSensitivitySlider, OnFocus(), ASlider::Set(), ASlider::SetScroll(), SPEED_SLIDER, TTB_AutomateSelection, TTB_Calibrate, TTB_EndOff, TTB_EndOn, TTB_KeyType, TTB_MakeLabel, TTB_PlaySpeed, TTB_PlaySpeedSlider, TTB_SelectSilence, TTB_SelectSound, TTB_SensitivitySlider, TTB_StartOff, TTB_StartOn, and UpdatePrefs().
void TranscriptionToolBar::RegenerateTooltips () [private]
References mButtons, mKeyTypeChoice, mPlaySpeedSlider, mSensitivitySlider, TTB_AutomateSelection, TTB_Calibrate, TTB_EndOff, TTB_EndOn, TTB_MakeLabel, TTB_PlaySpeed, TTB_SelectSilence, TTB_SelectSound, TTB_StartOff, and TTB_StartOn.
Referenced by UpdatePrefs().
virtual void TranscriptionToolBar::Repaint (wxDC * dc) [inline, virtual]
Implements ToolBar.
void TranscriptionToolBar::SetButton (bool newstate, AButton * button) [private]
Reimplemented from ToolBar.
References AButton::PopUp(), and AButton::PushDown().
Referenced by OnAutomateSelection(), OnCalibrate(), OnEndOff(), OnEndOn(), OnMakeLabel(), OnPlaySpeed(), OnSelectSilence(), OnSelectSound(), OnStartOff(), and OnStartOn().
void TranscriptionToolBar::SetKeyType (wxCommandEvent & event) [virtual]
References mKeyTypeChoice, mVk, and VoiceKey::SetKeyType().
void TranscriptionToolBar::ShowPlaySpeedDialog ()
References mPlaySpeedSlider, OnSpeedSlider(), and ASlider::ShowDialog().
Referenced by AudacityProject::OnSetPlaySpeed().
void TranscriptionToolBar::UpdatePrefs () [virtual]
Reimplemented from ToolBar.
References RegenerateTooltips(), and ToolBar::SetLabel().
Referenced by Populate().
Member Data Documentation
wxImage* TranscriptionToolBar::downImage [private]
wxImage* TranscriptionToolBar::hiliteImage [private]
wxBrush TranscriptionToolBar::mBackgroundBrush [private]
Referenced by Create().
int TranscriptionToolBar::mBackgroundHeight [private]
Referenced by Create().
wxPen TranscriptionToolBar::mBackgroundPen [private]
Referenced by Create().
int TranscriptionToolBar::mBackgroundWidth [private]
Referenced by Create().
AButton* TranscriptionToolBar::mButtons[TTBNumButtons] [private]
Referenced by AddButton(), Create(), EnableDisableButtons(), OnAutomateSelection(), OnCalibrate(), OnEndOff(), OnEndOn(), OnMakeLabel(), OnPlaySpeed(), OnSelectSilence(), OnSelectSound(), OnStartOff(), OnStartOn(), and RegenerateTooltips().
wxChoice* TranscriptionToolBar::mKeyTypeChoice [private]
Referenced by Populate(), RegenerateTooltips(), and SetKeyType().
double TranscriptionToolBar::mPlaySpeed [private]
Referenced by Create(), OnPlaySpeed(), and OnSpeedSlider().
ASlider* TranscriptionToolBar::mPlaySpeedSlider [private]
Referenced by AdjustPlaySpeed(), Create(), OnCaptureKey(), OnSpeedSlider(), Populate(), RegenerateTooltips(), and ShowPlaySpeedDialog().
double TranscriptionToolBar::mSensitivity [private]
Referenced by GetSensitivity(), and OnSensitivitySlider().
ASlider* TranscriptionToolBar::mSensitivitySlider [private]
Referenced by OnSensitivitySlider(), Populate(), and RegenerateTooltips().
TimeTrack* TranscriptionToolBar::mTimeTrack [private]
Referenced by OnPlaySpeed(), and ~TranscriptionToolBar().
VoiceKey* TranscriptionToolBar::mVk [private]
Referenced by OnAutomateSelection(), OnCalibrate(), OnEndOff(), OnEndOn(), OnSelectSilence(), OnSelectSound(), OnStartOff(), OnStartOn(), SetKeyType(), and ~TranscriptionToolBar().
wxImage* TranscriptionToolBar::upImage [private]
The documentation for this class was generated from the following files:
TranscriptionToolBar.h
TranscriptionToolBar.cpp