Audacity: EffectNoiseRemoval Class Reference
EffectNoiseRemoval Class Reference
A two-pass effect to remove background noise.
#include <NoiseRemoval.h>
Public Member Functions
EffectNoiseRemoval ()
virtual ~EffectNoiseRemoval ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Init ()
virtual bool CheckWhetherSkipEffect ()
virtual bool Process ()
Private Member Functions
void CleanSpeechMayReadNoisegate ()
void CleanSpeechMayWriteNoiseGate ()
bool ProcessOne (int count, WaveTrack *track, sampleCount start, sampleCount len)
void Initialize ()
void StartNewTrack ()
void ProcessSamples (sampleCount len, float *buffer)
void FillFirstHistoryWindow ()
void ApplyFreqSmoothing (float *spec)
void GetProfile ()
void RemoveNoise ()
void RotateHistoryWindows ()
void FinishTrack ()
void Cleanup ()
Private Attributes
bool mDoProfile
bool mHasProfile
int mLevel
double mSampleRate
int mWindowSize
int mSpectrumSize
float mMinSignalTime
float * mNoiseThreshold
double mFreqSmoothingHz
double mNoiseGain
double mAttackDecayTime
WaveTrack * mOutputTrack
sampleCount mInSampleCount
sampleCount mOutSampleCount
int mInputPos
HFFT hFFT
float * mFFTBuffer
float * mWindow
int mFreqSmoothingBins
int mAttackDecayBlocks
float mOneBlockAttackDecay
float mNoiseAttenFactor
int mMinSignalBlocks
int mHistoryLen
float * mInWaveBuffer
float * mOutImagBuffer
float * mOutOverlapBuffer
float ** mSpectrums
float ** mGains
float ** mRealFFTs
float ** mImagFFTs
Friends
class NoiseRemovalDialog
Detailed Description
A two-pass effect to remove background noise.
The first pass is done over just noise. For each windowed sample of the sound, we take a FFT and then statistics are tabulated for each frequency band - specifically the maximum level achieved by at least (n) sampling windows in a row, for various values of (n).
During the noise removal phase, we start by setting a gain control for each frequency band such that if the sound has exceeded the previously-determined threshold, the gain is set to 0, otherwise the gain is set lower (e.g. -18 dB), to suppress the noise. Then frequency-smoothing is applied so that a single frequency is never suppressed or boosted in isolation, and then time-smoothing is applied so that the gain for each frequency band moves slowly. Lookahead is employed; this effect is not designed for real-time but if it were, there would be a significant delay.
The gain controls are applied to the complex FFT of the signal, and then the inverse FFT is applied, followed by a Hanning window; the output signal is then pieced together using overlap/add of half the window size.
Constructor & Destructor Documentation
EffectNoiseRemoval::EffectNoiseRemoval ()
References CleanSpeechMayReadNoisegate(), gPrefs, Init(), mAttackDecayTime, mDoProfile, mFreqSmoothingHz, mHasProfile, mMinSignalTime, mNoiseGain, mNoiseThreshold, mSpectrumSize, mWindowSize, AudacityApp::SetCleanSpeechNoiseGate(), AudacityApp::SetCleanSpeechNoiseGateExpectedCount(), and wxGetApp().
EffectNoiseRemoval::~EffectNoiseRemoval () [virtual]
References mNoiseThreshold.
Member Function Documentation
void EffectNoiseRemoval::ApplyFreqSmoothing (float * spec) [private]
References mFreqSmoothingBins, and mSpectrumSize.
Referenced by Cleanup(), and RemoveNoise().
bool EffectNoiseRemoval::CheckWhetherSkipEffect () [virtual]
Reimplemented from Effect.
References mLevel.
void EffectNoiseRemoval::CleanSpeechMayReadNoisegate () [private]
References GetActiveProject(), gPrefs, mDoProfile, mHasProfile, mNoiseThreshold, mSpectrumSize, mWindowSize, FileNames::NRPDir(), and FileNames::NRPFile().
Referenced by EffectNoiseRemoval(), Process(), and PromptUser().
void EffectNoiseRemoval::CleanSpeechMayWriteNoiseGate () [private]
Bug:
1 in wxWidgets documentation; wxMkDir returns false if directory didn't exist, even if it successfully creates it. so we create and then test if it exists instead.
Bug:
2 in wxWidgets documentation; wxMkDir has only one argument under MSW
References GetActiveProject(), AudacityProject::GetCleanSpeechMode(), PlatformCompatibility::GetLongFileName(), mNoiseThreshold, mWindowSize, FileNames::NRPDir(), and FileNames::NRPFile().
Referenced by Process().
void EffectNoiseRemoval::Cleanup () [private]
References ApplyFreqSmoothing(), EndFFT(), hFFT, mDoProfile, mFFTBuffer, mGains, mHistoryLen, mImagFFTs, mInWaveBuffer, mNoiseThreshold, mOutImagBuffer, mOutOverlapBuffer, mRealFFTs, mSpectrums, and mWindow.
Referenced by Process().
void EffectNoiseRemoval::FillFirstHistoryWindow () [private]
References hFFT, mFFTBuffer, mGains, mImagFFTs, mInWaveBuffer, mNoiseAttenFactor, mRealFFTs, mSpectrums, mSpectrumSize, mWindowSize, and RealFFTf().
Referenced by ProcessSamples().
void EffectNoiseRemoval::FinishTrack () [private]
References mInSampleCount, mOutSampleCount, mWindowSize, and ProcessSamples().
Referenced by ProcessOne().
virtual wxString EffectNoiseRemoval::GetEffectAction () [inline, virtual]
Implements Effect.
References mDoProfile.
virtual std::set<wxString> EffectNoiseRemoval::GetEffectCategories () [inline, virtual]
virtual wxString EffectNoiseRemoval::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectNoiseRemoval::GetEffectName () [inline, virtual]
Implements Effect.
void EffectNoiseRemoval::GetProfile () [private]
References mHistoryLen, min(), mMinSignalBlocks, mNoiseThreshold, mOutSampleCount, mSpectrums, mSpectrumSize, and mWindowSize.
Referenced by ProcessSamples().
bool EffectNoiseRemoval::Init () [virtual]
Reimplemented from Effect.
References gPrefs, MAX_NOISE_LEVEL, and mLevel.
Referenced by EffectNoiseRemoval().
void EffectNoiseRemoval::Initialize () [private]
References hFFT, InitializeFFT(), M_PI, mAttackDecayBlocks, mAttackDecayTime, mDoProfile, mFFTBuffer, mFreqSmoothingBins, mFreqSmoothingHz, mGains, mHistoryLen, mImagFFTs, mInWaveBuffer, mMinSignalBlocks, mMinSignalTime, mNoiseAttenFactor, mNoiseGain, mNoiseThreshold, mOneBlockAttackDecay, mOutImagBuffer, mOutOverlapBuffer, Effect::mProjectRate, mRealFFTs, mSampleRate, mSpectrums, mSpectrumSize, mWindow, and mWindowSize.
Referenced by Process().
bool EffectNoiseRemoval::Process () [virtual]
Implements Effect.
References CleanSpeechMayReadNoisegate(), CleanSpeechMayWriteNoiseGate(), Cleanup(), Effect::CopyInputTracks(), TrackListCondIterator::First(), WaveTrack::GetEndTime(), WaveTrack::GetStartTime(), Initialize(), mDoProfile, mHasProfile, Effect::mOutputTracks, Effect::mT0, Effect::mT1, TrackListCondIterator::Next(), ProcessOne(), Effect::ReplaceProcessedTracks(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectNoiseRemoval::ProcessOne (int count, WaveTrack * track, sampleCount start, sampleCount len) [private]
References WaveTrack::ClearAndPaste(), FinishTrack(), floatSample, WaveTrack::Flush(), WaveTrack::Get(), WaveTrack::GetBestBlockSize(), WaveTrack::GetEndTime(), WaveTrack::GetMaxBlockSize(), WaveTrack::GetRate(), WaveTrack::GetSampleFormat(), WaveTrack::HandleClear(), WaveTrack::LongSamplesToTime(), mDoProfile, Effect::mFactory, mInSampleCount, mOutputTrack, TrackFactory::NewWaveTrack(), ProcessSamples(), StartNewTrack(), and Effect::TrackProgress().
Referenced by Process().
void EffectNoiseRemoval::ProcessSamples (sampleCount len, float * buffer) [private]
References FillFirstHistoryWindow(), GetProfile(), mDoProfile, mInputPos, mInSampleCount, mInWaveBuffer, mOutSampleCount, mWindowSize, RemoveNoise(), and RotateHistoryWindows().
Referenced by FinishTrack(), and ProcessOne().
bool EffectNoiseRemoval::PromptUser () [virtual]
Reimplemented from Effect.
References CleanSpeechMayReadNoisegate(), GetActiveProject(), AudacityProject::GetCleanSpeechMode(), Effect::GetNumWaveTracks(), gPrefs, NoiseRemovalDialog::m_pButton_Preview, NoiseRemovalDialog::m_pButton_RemoveNoise, mAttackDecayTime, mDoProfile, NoiseRemovalDialog::mFreq, mFreqSmoothingHz, NoiseRemovalDialog::mGain, mHasProfile, mNoiseGain, Effect::mParent, NoiseRemovalDialog::mTime, and NoiseRemovalDialog::TransferDataToWindow().
void EffectNoiseRemoval::RemoveNoise () [private]
References WaveTrack::Append(), ApplyFreqSmoothing(), floatSample, hFFT, InverseRealFFTf(), mFFTBuffer, mGains, mHistoryLen, mImagFFTs, min(), mMinSignalBlocks, mNoiseAttenFactor, mNoiseThreshold, mOneBlockAttackDecay, mOutOverlapBuffer, mOutputTrack, mOutSampleCount, mRealFFTs, mSpectrums, mSpectrumSize, mWindow, and mWindowSize.
Referenced by ProcessSamples().
void EffectNoiseRemoval::RotateHistoryWindows () [private]
References mGains, mHistoryLen, mImagFFTs, mRealFFTs, and mSpectrums.
Referenced by ProcessSamples().
void EffectNoiseRemoval::StartNewTrack () [private]
References mGains, mHistoryLen, mImagFFTs, mInputPos, mInSampleCount, mNoiseAttenFactor, mOutOverlapBuffer, mOutSampleCount, mRealFFTs, mSpectrums, mSpectrumSize, and mWindowSize.
Referenced by ProcessOne().
bool EffectNoiseRemoval::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
Friends And Related Function Documentation
friend class NoiseRemovalDialog [friend]
Member Data Documentation
HFFT EffectNoiseRemoval::hFFT [private]
Referenced by Cleanup(), FillFirstHistoryWindow(), Initialize(), and RemoveNoise().
int EffectNoiseRemoval::mAttackDecayBlocks [private]
Referenced by Initialize().
double EffectNoiseRemoval::mAttackDecayTime [private]
Referenced by EffectNoiseRemoval(), Initialize(), NoiseRemovalDialog::OnPreview(), and PromptUser().
bool EffectNoiseRemoval::mDoProfile [private]
Referenced by CleanSpeechMayReadNoisegate(), Cleanup(), EffectNoiseRemoval(), GetEffectAction(), Initialize(), NoiseRemovalDialog::OnPreview(), Process(), ProcessOne(), ProcessSamples(), and PromptUser().
float* EffectNoiseRemoval::mFFTBuffer [private]
Referenced by Cleanup(), FillFirstHistoryWindow(), Initialize(), and RemoveNoise().
int EffectNoiseRemoval::mFreqSmoothingBins [private]
Referenced by ApplyFreqSmoothing(), and Initialize().
double EffectNoiseRemoval::mFreqSmoothingHz [private]
Referenced by EffectNoiseRemoval(), Initialize(), NoiseRemovalDialog::OnPreview(), and PromptUser().
float** EffectNoiseRemoval::mGains [private]
Referenced by Cleanup(), FillFirstHistoryWindow(), Initialize(), RemoveNoise(), RotateHistoryWindows(), and StartNewTrack().
bool EffectNoiseRemoval::mHasProfile [private]
Referenced by CleanSpeechMayReadNoisegate(), EffectNoiseRemoval(), Process(), and PromptUser().
int EffectNoiseRemoval::mHistoryLen [private]
Referenced by Cleanup(), GetProfile(), Initialize(), RemoveNoise(), RotateHistoryWindows(), and StartNewTrack().
float** EffectNoiseRemoval::mImagFFTs [private]
Referenced by Cleanup(), FillFirstHistoryWindow(), Initialize(), RemoveNoise(), RotateHistoryWindows(), and StartNewTrack().
int EffectNoiseRemoval::mInputPos [private]
Referenced by ProcessSamples(), and StartNewTrack().
sampleCount EffectNoiseRemoval::mInSampleCount [private]
Referenced by FinishTrack(), ProcessOne(), ProcessSamples(), and StartNewTrack().
float* EffectNoiseRemoval::mInWaveBuffer [private]
Referenced by Cleanup(), FillFirstHistoryWindow(), Initialize(), and ProcessSamples().
int EffectNoiseRemoval::mLevel [private]
Referenced by CheckWhetherSkipEffect(), and Init().
int EffectNoiseRemoval::mMinSignalBlocks [private]
Referenced by GetProfile(), Initialize(), and RemoveNoise().
float EffectNoiseRemoval::mMinSignalTime [private]
Referenced by EffectNoiseRemoval(), and Initialize().
float EffectNoiseRemoval::mNoiseAttenFactor [private]
Referenced by FillFirstHistoryWindow(), Initialize(), RemoveNoise(), and StartNewTrack().
double EffectNoiseRemoval::mNoiseGain [private]
Referenced by EffectNoiseRemoval(), Initialize(), NoiseRemovalDialog::OnPreview(), and PromptUser().
float* EffectNoiseRemoval::mNoiseThreshold [private]
Referenced by CleanSpeechMayReadNoisegate(), CleanSpeechMayWriteNoiseGate(), Cleanup(), EffectNoiseRemoval(), GetProfile(), Initialize(), RemoveNoise(), and ~EffectNoiseRemoval().
float EffectNoiseRemoval::mOneBlockAttackDecay [private]
Referenced by Initialize(), and RemoveNoise().
float* EffectNoiseRemoval::mOutImagBuffer [private]
Referenced by Cleanup(), and Initialize().
float* EffectNoiseRemoval::mOutOverlapBuffer [private]
Referenced by Cleanup(), Initialize(), RemoveNoise(), and StartNewTrack().
WaveTrack* EffectNoiseRemoval::mOutputTrack [private]
Referenced by ProcessOne(), and RemoveNoise().
sampleCount EffectNoiseRemoval::mOutSampleCount [private]
Referenced by FinishTrack(), GetProfile(), ProcessSamples(), RemoveNoise(), and StartNewTrack().
float** EffectNoiseRemoval::mRealFFTs [private]
Referenced by Cleanup(), FillFirstHistoryWindow(), Initialize(), RemoveNoise(), RotateHistoryWindows(), and StartNewTrack().
double EffectNoiseRemoval::mSampleRate [private]
Referenced by Initialize().
float** EffectNoiseRemoval::mSpectrums [private]
Referenced by Cleanup(), FillFirstHistoryWindow(), GetProfile(), Initialize(), RemoveNoise(), RotateHistoryWindows(), and StartNewTrack().
int EffectNoiseRemoval::mSpectrumSize [private]
Referenced by ApplyFreqSmoothing(), CleanSpeechMayReadNoisegate(), EffectNoiseRemoval(), FillFirstHistoryWindow(), GetProfile(), Initialize(), RemoveNoise(), and StartNewTrack().
float* EffectNoiseRemoval::mWindow [private]
Referenced by Cleanup(), Initialize(), and RemoveNoise().
int EffectNoiseRemoval::mWindowSize [private]
Referenced by CleanSpeechMayReadNoisegate(), CleanSpeechMayWriteNoiseGate(), EffectNoiseRemoval(), FillFirstHistoryWindow(), FinishTrack(), GetProfile(), Initialize(), ProcessSamples(), RemoveNoise(), and StartNewTrack().
The documentation for this class was generated from the following files:
NoiseRemoval.h
NoiseRemoval.cpp