Audacity: AmplifyDialog Class Reference
AmplifyDialog Class Reference
Dilaog used with EffectAmplify.
#include <Amplify.h>
Public Member Functions
AmplifyDialog (EffectAmplify *effect, wxWindow *parent)
void PopulateOrExchange (ShuttleGui &S)
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
bool Validate ()
Public Attributes
EffectAmplify * mEffect
float ratio
float peak
bool noclip
Private Member Functions
void OnAmpText (wxCommandEvent &event)
void OnPeakText (wxCommandEvent &event)
void OnAmpSlider (wxCommandEvent &event)
void OnClipCheckBox (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
void CheckClip ()
DECLARE_EVENT_TABLE ()
Private Attributes
wxSlider * mAmpS
wxTextCtrl * mAmpT
wxTextCtrl * mPeakT
wxCheckBox * mClip
Detailed Description
Dilaog used with EffectAmplify.
Constructor & Destructor Documentation
AmplifyDialog::AmplifyDialog (EffectAmplify * effect, wxWindow * parent)
Member Function Documentation
void AmplifyDialog::CheckClip () [private]
References mClip, peak, and ratio.
Referenced by OnAmpSlider(), OnAmpText(), OnClipCheckBox(), and OnPeakText().
AmplifyDialog::DECLARE_EVENT_TABLE () [private]
void AmplifyDialog::OnAmpSlider (wxCommandEvent & event) [private]
References AMP_MAX, AMP_MIN, CheckClip(), mAmpS, mAmpT, mClip, mPeakT, peak, ratio, and TrapDouble().
void AmplifyDialog::OnAmpText (wxCommandEvent & event) [private]
References AMP_MAX, AMP_MIN, CheckClip(), mAmpS, mAmpT, mPeakT, peak, ratio, and TrapDouble().
void AmplifyDialog::OnClipCheckBox (wxCommandEvent & event) [private]
References CheckClip().
void AmplifyDialog::OnPeakText (wxCommandEvent & event) [private]
References AMP_MAX, AMP_MIN, CheckClip(), mAmpS, mAmpT, mPeakT, peak, ratio, and TrapDouble().
void AmplifyDialog::OnPreview (wxCommandEvent & event) [private, virtual]
Reimplemented from EffectDialog.
References mEffect, noclip, peak, EffectAmplify::peak, Effect::Preview(), ratio, EffectAmplify::ratio, and TransferDataFromWindow().
void AmplifyDialog::PopulateOrExchange (ShuttleGui & S) [virtual]
This is a virtual function which will be overridden to provide the actual parameters that we want for each kind of dialog.
Reimplemented from EffectDialog.
References ShuttleGuiBase::AddCheckBox(), ShuttleGuiBase::AddSlider(), ShuttleGuiBase::AddTextBox(), ShuttleGuiBase::AddTitle(), AMP_MAX, AMP_MIN, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGui::Id(), ID_AMP_SLIDER, ID_AMP_TEXT, ID_CLIP_CHECKBOX, ID_PEAK_TEXT, mAmpS, mAmpT, mClip, mPeakT, ShuttleGuiBase::SetStyle(), ShuttleGuiBase::StartHorizontalLay(), and ShuttleGuiBase::StartMultiColumn().
bool AmplifyDialog::TransferDataFromWindow () [virtual]
Reimplemented from EffectDialog.
References AMP_MAX, AMP_MIN, mAmpT, mClip, noclip, ratio, and TrapDouble().
Referenced by OnPreview(), and Validate().
bool AmplifyDialog::TransferDataToWindow () [virtual]
Reimplemented from EffectDialog.
References AMP_MAX, AMP_MIN, mAmpS, mAmpT, mPeakT, peak, ratio, and TrapDouble().
Referenced by EffectAmplify::PromptUser().
bool AmplifyDialog::Validate () [virtual]
Reimplemented from EffectDialog.
References mClip, peak, ratio, and TransferDataFromWindow().
Member Data Documentation
wxSlider* AmplifyDialog::mAmpS [private]
Referenced by OnAmpSlider(), OnAmpText(), OnPeakText(), PopulateOrExchange(), and TransferDataToWindow().
wxTextCtrl* AmplifyDialog::mAmpT [private]
Referenced by OnAmpSlider(), OnAmpText(), OnPeakText(), PopulateOrExchange(), TransferDataFromWindow(), and TransferDataToWindow().
wxCheckBox* AmplifyDialog::mClip [private]
Referenced by CheckClip(), OnAmpSlider(), PopulateOrExchange(), TransferDataFromWindow(), and Validate().
EffectAmplify* AmplifyDialog::mEffect
Referenced by OnPreview().
wxTextCtrl* AmplifyDialog::mPeakT [private]
Referenced by OnAmpSlider(), OnAmpText(), OnPeakText(), PopulateOrExchange(), and TransferDataToWindow().
bool AmplifyDialog::noclip
Referenced by OnPreview(), EffectAmplify::PromptUser(), and TransferDataFromWindow().
float AmplifyDialog::peak
Referenced by CheckClip(), OnAmpSlider(), OnAmpText(), OnPeakText(), OnPreview(), EffectAmplify::PromptUser(), TransferDataToWindow(), and Validate().
float AmplifyDialog::ratio
Referenced by CheckClip(), OnAmpSlider(), OnAmpText(), OnPeakText(), OnPreview(), EffectAmplify::PromptUser(), TransferDataFromWindow(), TransferDataToWindow(), and Validate().
The documentation for this class was generated from the following files:
Amplify.h
Amplify.cpp