Audacity: DependencyDialog Class Reference
DependencyDialog Class Reference
Public Member Functions
DependencyDialog (wxWindow *parent, wxWindowID id, AudacityProject *project, AliasedFileArray *aliasedFiles, bool isSaving)
Private Member Functions
void PopulateList ()
void OnList (wxListEvent &evt)
void OnCopy (wxCommandEvent &evt)
void OnNo (wxCommandEvent &evt)
void OnYes (wxCommandEvent &evt)
void PopulateOrExchange (ShuttleGui &S)
void SaveChoice ()
virtual void OnCancel (wxCommandEvent &evt)
Private Attributes
AudacityProject * mProject
AliasedFileArray * mAliasedFiles
wxListCtrl * mFileList
wxButton * mCopyButton
wxChoice * mChoice
bool mIsSaving
Constructor & Destructor Documentation
DependencyDialog::DependencyDialog (wxWindow * parent, wxWindowID id, AudacityProject * project, AliasedFileArray * aliasedFiles, bool isSaving)
Member Function Documentation
void DependencyDialog::OnCancel (wxCommandEvent & evt) [private, virtual]
References mIsSaving.
void DependencyDialog::OnCopy (wxCommandEvent & evt) [private]
References mAliasedFiles, mFileList, mProject, PopulateList(), RemoveDependencies(), and SaveChoice().
void DependencyDialog::OnList (wxListEvent & evt) [private]
References mAliasedFiles, mCopyButton, and mFileList.
void DependencyDialog::OnNo (wxCommandEvent & evt) [private]
References SaveChoice().
void DependencyDialog::OnYes (wxCommandEvent & evt) [private]
References SaveChoice().
void DependencyDialog::PopulateList () [private]
References Internat::FormatSize(), mAliasedFiles, and mFileList.
Referenced by OnCopy(), and PopulateOrExchange().
void DependencyDialog::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddButton(), ShuttleGuiBase::AddChoice(), ShuttleGuiBase::AddListControlReportMode(), ShuttleGuiBase::AddVariableText(), CopyID, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndVerticalLay(), FileListID, FutureActionID, ShuttleGui::Id(), kDependencyDialogPrompt, mChoice, mCopyButton, mFileList, mIsSaving, PopulateList(), ShuttleGuiBase::SetBorder(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartStatic(), and ShuttleGuiBase::StartVerticalLay().
void DependencyDialog::SaveChoice () [private]
References gPrefs, and mChoice.
Referenced by OnCopy(), OnNo(), and OnYes().
Member Data Documentation
AliasedFileArray* DependencyDialog::mAliasedFiles [private]
Referenced by OnCopy(), OnList(), and PopulateList().
wxChoice* DependencyDialog::mChoice [private]
Referenced by PopulateOrExchange(), and SaveChoice().
wxButton* DependencyDialog::mCopyButton [private]
Referenced by OnList(), and PopulateOrExchange().
wxListCtrl* DependencyDialog::mFileList [private]
Referenced by OnCopy(), OnList(), PopulateList(), and PopulateOrExchange().
bool DependencyDialog::mIsSaving [private]
Referenced by OnCancel(), and PopulateOrExchange().
AudacityProject* DependencyDialog::mProject [private]
Referenced by OnCopy().
The documentation for this class was generated from the following file:
Dependencies.cpp