Audacity: CommandMessageTarget Class Reference
CommandMessageTarget Class Reference
Interface for objects that can receive (string) messages from a command.
#include <CommandTargets.h>
Public Member Functions
virtual ~CommandMessageTarget ()
virtual void Update (wxString message)=0
Detailed Description
Interface for objects that can receive (string) messages from a command.
Constructor & Destructor Documentation
virtual CommandMessageTarget::~CommandMessageTarget () [inline, virtual]
Member Function Documentation
virtual void CommandMessageTarget::Update (wxString message) [pure virtual]
Implemented in NullMessageTarget, MessageBoxTarget, StatusBarTarget, ResponseQueueTarget, and CombinedMessageTarget.
Referenced by CommandOutputTarget::Error(), CommandOutputTarget::Status(), CombinedMessageTarget::Update(), and ProgressToMessageTarget::Update().
The documentation for this class was generated from the following file:
CommandTargets.h