Audacity: XMLTagHandler Class Reference
XMLTagHandler Class Reference
This class is an interface which should be implemented by classes which wish to be able to load and save themselves using XML files.
#include <XMLTagHandler.h>
Public Member Functions
XMLTagHandler ()
virtual ~XMLTagHandler ()
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)=0
virtual void HandleXMLEndTag (const wxChar *tag)
virtual void HandleXMLContent (const wxString &content)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)=0
bool ReadXMLTag (const char *tag, const char **attrs)
void ReadXMLEndTag (const char *tag)
void ReadXMLContent (const char *s, int len)
XMLTagHandler * ReadXMLChild (const char *tag)
Detailed Description
This class is an interface which should be implemented by classes which wish to be able to load and save themselves using XML files.
Constructor & Destructor Documentation
XMLTagHandler::XMLTagHandler () [inline]
virtual XMLTagHandler::~XMLTagHandler () [inline, virtual]
Member Function Documentation
virtual XMLTagHandler* XMLTagHandler::HandleXMLChild (const wxChar * tag) [pure virtual]
Implemented in RecordingRecoveryHandler, CommandManager, DirManager, EqualizationDialog, EnvPoint, Envelope, FFmpegPresets, LabelTrack, NoteTrack, ImportXMLTagHandler, AudacityProject, Sequence, Tags, TimeTrack, Track, WaveClip, and WaveTrack.
Referenced by ReadXMLChild().
virtual void XMLTagHandler::HandleXMLContent (const wxString & content) [inline, virtual]
Referenced by ReadXMLContent().
virtual void XMLTagHandler::HandleXMLEndTag (const wxChar * tag) [inline, virtual]
Reimplemented in CommandManager, Sequence, WaveClip, and WaveTrack.
Referenced by ReadXMLEndTag().
virtual bool XMLTagHandler::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [pure virtual]
Implemented in RecordingRecoveryHandler, CommandManager, DirManager, EqualizationDialog, EnvPoint, Envelope, FFmpegPresets, LabelTrack, NoteTrack, ImportXMLTagHandler, AudacityProject, Sequence, Tags, TimeTrack, Track, WaveClip, and WaveTrack.
Referenced by ReadXMLTag().
XMLTagHandler * XMLTagHandler::ReadXMLChild (const char * tag)
References HandleXMLChild(), and UTF8CTOWX.
Referenced by XMLFileReader::startElement().
void XMLTagHandler::ReadXMLContent (const char * s, int len)
References HandleXMLContent().
Referenced by XMLFileReader::charHandler().
void XMLTagHandler::ReadXMLEndTag (const char * tag)
References HandleXMLEndTag(), and UTF8CTOWX.
Referenced by XMLFileReader::endElement().
bool XMLTagHandler::ReadXMLTag (const char * tag, const char ** attrs)
References HandleXMLTag(), and UTF8CTOWX.
Referenced by XMLFileReader::startElement().
The documentation for this class was generated from the following files:
XMLTagHandler.h
XMLTagHandler.cpp