Audacity: PrefsDialog Class Reference
PrefsDialog Class Reference
Dialog that shows the current PrefsPanel in a tabbed divider.
#include <PrefsDialog.h>
Public Member Functions
PrefsDialog (wxWindow *parent)
virtual ~PrefsDialog ()
void OnCategoryChange (wxCommandEvent &e)
void OnOK (wxCommandEvent &e)
void OnCancel (wxCommandEvent &e)
void OnTreeKeyDown (wxTreeEvent &e)
void SelectPageByName (wxString pageName)
void ShowTempDirPage ()
Private Attributes
wxTreebook * mCategories
Detailed Description
Dialog that shows the current PrefsPanel in a tabbed divider.
Constructor & Destructor Documentation
PrefsDialog::PrefsDialog (wxWindow * parent)
PrefsDialog::~PrefsDialog () [virtual]
Member Function Documentation
void PrefsDialog::OnCancel (wxCommandEvent & e)
References mCategories.
void PrefsDialog::OnCategoryChange (wxCommandEvent & e)
void PrefsDialog::OnOK (wxCommandEvent & e)
References PrefsPanel::Apply(), gAudacityProjects, gAudioIO, gPrefs, AudioIO::HandleDeviceChange(), and mCategories.
Referenced by OnTreeKeyDown().
void PrefsDialog::OnTreeKeyDown (wxTreeEvent & e)
References OnOK().
void PrefsDialog::SelectPageByName (wxString pageName)
References mCategories.
Referenced by ShowTempDirPage().
void PrefsDialog::ShowTempDirPage ()
References SelectPageByName().
Referenced by AudacityApp::InitTempDir().
Member Data Documentation
wxTreebook* PrefsDialog::mCategories [private]
Referenced by OnCancel(), OnOK(), and SelectPageByName().
The documentation for this class was generated from the following files:
PrefsDialog.h
PrefsDialog.cpp