Audacity: EffectNoise Class Reference
EffectNoise Class Reference
An Effect for the "Generator" menu to add white noise.
#include <Noise.h>
Public Member Functions
EffectNoise ()
virtual bool Init ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectDescription ()
virtual wxString GetEffectAction ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
void GenerateBlock (float *data, const WaveTrack &track, sampleCount block)
void Success ()
Protected Member Functions
virtual bool MakeNoise (float *buffer, sampleCount len, float fs, float amplitude)
Private Attributes
sampleCount numSamples
int noiseType
double noiseAmplitude
Friends
class NoiseDialog
Detailed Description
An Effect for the "Generator" menu to add white noise.
Constructor & Destructor Documentation
EffectNoise::EffectNoise () [inline]
References BUILTIN_EFFECT, INSERT_EFFECT, noiseAmplitude, noiseType, and Effect::SetEffectFlags().
Member Function Documentation
void EffectNoise::GenerateBlock (float * data, const WaveTrack & track, sampleCount block) [virtual]
Implements BlockGenerator.
References WaveTrack::GetRate(), MakeNoise(), and noiseAmplitude.
virtual wxString EffectNoise::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectNoise::GetEffectCategories () [inline, virtual]
virtual wxString EffectNoise::GetEffectDescription () [inline, virtual]
Reimplemented from Effect.
References Generator::mDuration.
virtual wxString EffectNoise::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectNoise::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectNoise::Init () [virtual]
Reimplemented from Generator.
References gPrefs, and Generator::mDuration.
bool EffectNoise::MakeNoise (float * buffer, sampleCount len, float fs, float amplitude) [protected, virtual]
References M_PI, and noiseType.
Referenced by GenerateBlock().
bool EffectNoise::PromptUser () [virtual]
Reimplemented from Effect.
References gPrefs, EffectDialog::Init(), Generator::mDuration, Effect::mParent, Effect::mT0, Effect::mT1, NoiseDialog::nAmplitude, NoiseDialog::nDuration, NoiseDialog::nIsSelection, noiseAmplitude, noiseType, NoiseDialog::nType, NoiseDialog::nTypeList, and NoiseDialog::TransferDataToWindow().
void EffectNoise::Success () [virtual]
Reimplemented from Generator.
References gPrefs, Generator::mDuration, Effect::mT0, Effect::mT1, noiseAmplitude, and noiseType.
bool EffectNoise::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
Friends And Related Function Documentation
friend class NoiseDialog [friend]
Member Data Documentation
double EffectNoise::noiseAmplitude [private]
Referenced by EffectNoise(), GenerateBlock(), PromptUser(), and Success().
int EffectNoise::noiseType [private]
Referenced by EffectNoise(), MakeNoise(), PromptUser(), and Success().
sampleCount EffectNoise::numSamples [private]
Reimplemented from BlockGenerator.
The documentation for this class was generated from the following files:
Noise.h
Noise.cpp