Audacity: MixerBoard Class Reference
MixerBoard Class Reference
#include <MixerBoard.h>
Public Member Functions
MixerBoard (AudacityProject *pProject, wxFrame *parent, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
virtual ~MixerBoard ()
void UpdateTrackClusters ()
int GetTrackClustersWidth ()
void MoveTrackCluster (const WaveTrack *pLeftTrack, bool bUp)
void RemoveTrackCluster (const WaveTrack *pLeftTrack)
wxBitmap * GetMusicalInstrumentBitmap (const WaveTrack *pLeftTrack)
bool HasSolo ()
void RefreshTrackCluster (const WaveTrack *pLeftTrack, bool bEraseBackground=true)
void RefreshTrackClusters (bool bEraseBackground=true)
void ResizeTrackClusters ()
void ResetMeters ()
void UpdateName (const WaveTrack *pLeftTrack)
void UpdateMute (const WaveTrack *pLeftTrack=NULL)
void UpdateSolo (const WaveTrack *pLeftTrack=NULL)
void UpdatePan (const WaveTrack *pLeftTrack)
void UpdateGain (const WaveTrack *pLeftTrack)
void UpdateMeters (const double t1, const bool bLoopedPlay)
void UpdateWidth ()
Public Attributes
wxImage * mImageMuteUp
wxImage * mImageMuteOver
wxImage * mImageMuteDown
wxImage * mImageMuteDownWhileSolo
wxImage * mImageMuteDisabled
wxImage * mImageSoloUp
wxImage * mImageSoloOver
wxImage * mImageSoloDown
wxImage * mImageSoloDisabled
int mMuteSoloWidth
Private Member Functions
void CreateMuteSoloImages ()
int FindMixerTrackCluster (const WaveTrack *pLeftTrack, MixerTrackCluster **hMixerTrackCluster) const
void LoadMusicalInstruments ()
void OnSize (wxSizeEvent &evt)
Private Attributes
MixerTrackClusterArray mMixerTrackClusters
MusicalInstrumentArray mMusicalInstruments
AudacityProject * mProject
MixerBoardScrolledWindow * mScrolledWindow
double mPrevT1
TrackList * mTracks
Friends
class MixerBoardFrame
Constructor & Destructor Documentation
MixerBoard::MixerBoard (AudacityProject * pProject, wxFrame * parent, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
References kInset, and kRightSideStackWidth.
MixerBoard::~MixerBoard () [virtual]
References mImageMuteDisabled, mImageMuteDown, mImageMuteDownWhileSolo, mImageMuteOver, mImageMuteUp, mImageSoloDisabled, mImageSoloDown, mImageSoloOver, mImageSoloUp, and mMusicalInstruments.
Member Function Documentation
void MixerBoard::CreateMuteSoloImages () [private]
References AColor::Bevel(), kInset, kQuadrupleInset, kRightSideStackWidth, mImageMuteDisabled, mImageMuteDown, mImageMuteDownWhileSolo, mImageMuteOver, mImageMuteUp, mImageSoloDisabled, mImageSoloDown, mImageSoloOver, mImageSoloUp, mMuteSoloWidth, AColor::Mute(), MUTE_SOLO_HEIGHT, and AColor::Solo().
Referenced by UpdateTrackClusters().
int MixerBoard::FindMixerTrackCluster (const WaveTrack * pLeftTrack, MixerTrackCluster ** hMixerTrackCluster) const [private]
References mMixerTrackClusters.
Referenced by MoveTrackCluster(), RefreshTrackCluster(), RemoveTrackCluster(), UpdateGain(), UpdateMute(), UpdateName(), UpdatePan(), and UpdateSolo().
wxBitmap * MixerBoard::GetMusicalInstrumentBitmap (const WaveTrack * pLeftTrack)
References Track::GetName(), and mMusicalInstruments.
Referenced by MixerTrackCluster::UpdateName().
int MixerBoard::GetTrackClustersWidth ()
References kDoubleInset, kInset, kMixerTrackClusterWidth, and mMixerTrackClusters.
Referenced by UpdateWidth().
bool MixerBoard::HasSolo ()
References TrackListIterator::First(), Track::GetSolo(), mTracks, and TrackListIterator::Next().
Referenced by MixerTrackCluster::UpdateMeter().
void MixerBoard::LoadMusicalInstruments () [private]
References AColor::Bevel(), mMusicalInstruments, and MUSICAL_INSTRUMENT_HEIGHT_AND_WIDTH.
void MixerBoard::MoveTrackCluster (const WaveTrack * pLeftTrack, bool bUp)
References FindMixerTrackCluster(), kInset, kMixerTrackClusterWidth, and mMixerTrackClusters.
Referenced by TrackPanel::HandleRearrange(), and TrackPanel::OnMoveTrack().
void MixerBoard::OnSize (wxSizeEvent & evt) [private]
References mScrolledWindow, RefreshTrackClusters(), and ResizeTrackClusters().
void MixerBoard::RefreshTrackCluster (const WaveTrack * pLeftTrack, bool bEraseBackground = true)
References FindMixerTrackCluster().
Referenced by TrackPanel::HandleLabelClick().
void MixerBoard::RefreshTrackClusters (bool bEraseBackground = true)
References mMixerTrackClusters.
Referenced by TrackPanel::HandleLabelClick(), MixerTrackCluster::HandleSelect(), and OnSize().
void MixerBoard::RemoveTrackCluster (const WaveTrack * pLeftTrack)
References FindMixerTrackCluster(), kInset, kMixerTrackClusterWidth, mMixerTrackClusters, and UpdateWidth().
Referenced by AudacityProject::OnRemoveTracks(), TrackPanel::RemoveTrack(), and UpdateTrackClusters().
void MixerBoard::ResetMeters ()
References mMixerTrackClusters, and mPrevT1.
Referenced by TrackPanel::OnTimer().
void MixerBoard::ResizeTrackClusters ()
References mMixerTrackClusters.
Referenced by OnSize(), AudacityProject::UpdatePrefs(), and UpdateTrackClusters().
void MixerBoard::UpdateGain (const WaveTrack * pLeftTrack)
References FindMixerTrackCluster(), and MixerTrackCluster::UpdateGain().
Referenced by TrackPanel::HandleSliders().
void MixerBoard::UpdateMeters (const double t1, const bool bLoopedPlay)
References mMixerTrackClusters, and mPrevT1.
Referenced by TrackPanel::OnTimer(), and AudacityProject::UpdateMixerBoard().
void MixerBoard::UpdateMute (const WaveTrack * pLeftTrack = NULL)
References FindMixerTrackCluster(), mMixerTrackClusters, and MixerTrackCluster::UpdateMute().
Referenced by MixerTrackCluster::OnButton_Solo(), AudacityProject::OnMuteAllTracks(), TrackPanel::OnTrackMute(), TrackPanel::OnTrackSolo(), and AudacityProject::OnUnMuteAllTracks().
void MixerBoard::UpdateName (const WaveTrack * pLeftTrack)
References FindMixerTrackCluster(), and MixerTrackCluster::UpdateName().
Referenced by TrackPanel::OnSetName().
void MixerBoard::UpdatePan (const WaveTrack * pLeftTrack)
References FindMixerTrackCluster(), and MixerTrackCluster::UpdatePan().
Referenced by TrackPanel::HandleSliders().
void MixerBoard::UpdateSolo (const WaveTrack * pLeftTrack = NULL)
References FindMixerTrackCluster(), mMixerTrackClusters, and MixerTrackCluster::UpdateSolo().
Referenced by MixerTrackCluster::OnButton_Mute(), MixerTrackCluster::OnButton_Solo(), TrackPanel::OnTrackMute(), and TrackPanel::OnTrackSolo().
void MixerBoard::UpdateTrackClusters ()
References CreateMuteSoloImages(), TrackListIterator::First(), Track::GetKind(), Track::GetLinked(), kDoubleInset, kInset, kMixerTrackClusterWidth, mImageMuteUp, mMixerTrackClusters, mProject, mScrolledWindow, mTracks, TrackListIterator::Next(), RemoveTrackCluster(), ResizeTrackClusters(), UpdateWidth(), and Track::Wave.
Referenced by AudacityProject::UpdateMixerBoard().
void MixerBoard::UpdateWidth ()
References GetTrackClustersWidth(), kDoubleInset, MIXER_BOARD_MIN_WIDTH, and mScrolledWindow.
Referenced by MixerBoardFrame::OnMaximize(), RemoveTrackCluster(), and UpdateTrackClusters().
Friends And Related Function Documentation
friend class MixerBoardFrame [friend]
Member Data Documentation
wxImage* MixerBoard::mImageMuteDisabled
Referenced by CreateMuteSoloImages(), and ~MixerBoard().
wxImage* MixerBoard::mImageMuteDown
Referenced by CreateMuteSoloImages(), and ~MixerBoard().
wxImage* MixerBoard::mImageMuteDownWhileSolo
Referenced by CreateMuteSoloImages(), and ~MixerBoard().
wxImage* MixerBoard::mImageMuteOver
Referenced by CreateMuteSoloImages(), and ~MixerBoard().
wxImage* MixerBoard::mImageMuteUp
Referenced by CreateMuteSoloImages(), UpdateTrackClusters(), and ~MixerBoard().
wxImage* MixerBoard::mImageSoloDisabled
Referenced by CreateMuteSoloImages(), and ~MixerBoard().
wxImage* MixerBoard::mImageSoloDown
Referenced by CreateMuteSoloImages(), and ~MixerBoard().
wxImage* MixerBoard::mImageSoloOver
Referenced by CreateMuteSoloImages(), and ~MixerBoard().
wxImage* MixerBoard::mImageSoloUp
Referenced by CreateMuteSoloImages(), and ~MixerBoard().
MixerTrackClusterArray MixerBoard::mMixerTrackClusters [private]
Referenced by FindMixerTrackCluster(), GetTrackClustersWidth(), MoveTrackCluster(), RefreshTrackClusters(), RemoveTrackCluster(), ResetMeters(), ResizeTrackClusters(), UpdateMeters(), UpdateMute(), UpdateSolo(), and UpdateTrackClusters().
MusicalInstrumentArray MixerBoard::mMusicalInstruments [private]
Referenced by GetMusicalInstrumentBitmap(), LoadMusicalInstruments(), and ~MixerBoard().
int MixerBoard::mMuteSoloWidth
Referenced by CreateMuteSoloImages().
double MixerBoard::mPrevT1 [private]
Referenced by ResetMeters(), and UpdateMeters().
AudacityProject* MixerBoard::mProject [private]
Referenced by UpdateTrackClusters().
MixerBoardScrolledWindow* MixerBoard::mScrolledWindow [private]
Referenced by OnSize(), UpdateTrackClusters(), and UpdateWidth().
TrackList* MixerBoard::mTracks [private]
Referenced by HasSolo(), and UpdateTrackClusters().
The documentation for this class was generated from the following files:
MixerBoard.h
MixerBoard.cpp