Audacity: FreqWindow Class Reference
FreqWindow Class Reference
Displays a spectrum plot of the waveform. Has options for selecting parameters of the plot.
#include <FreqWindow.h>
Public Member Functions
FreqWindow (wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos)
virtual ~FreqWindow ()
void GetAudio ()
void Plot ()
void PlotMouseEvent (wxMouseEvent &event)
void PlotPaint (wxPaintEvent &event)
void OnCloseWindow (wxCloseEvent &event)
void OnCloseButton (wxCommandEvent &event)
void OnSize (wxSizeEvent &event)
void OnAlgChoice (wxCommandEvent &event)
void OnSizeChoice (wxCommandEvent &event)
void OnFuncChoice (wxCommandEvent &event)
void OnAxisChoice (wxCommandEvent &event)
void OnExport (wxCommandEvent &event)
void OnReplot (wxCommandEvent &event)
void OnGridOnOff (wxCommandEvent &event)
void Recalc ()
void DrawPlot ()
Private Member Functions
float GetProcessedValue (float freq0, float freq1)
Private Attributes
float * mBuffer
bool mDrawGrid
int mSize
int mAlg
int mFunc
int mAxis
int dBRange
AudacityProject * p
wxStatusBar * mInfo
FreqPlot * mFreqPlot
wxFont mFreqFont
wxCursor * mArrowCursor
wxCursor * mCrossCursor
wxButton * mCloseButton
wxButton * mExportButton
wxButton * mReplotButton
wxChoice * mAlgChoice
wxChoice * mSizeChoice
wxChoice * mFuncChoice
wxChoice * mAxisChoice
wxCheckBox * mGridOnOff
wxRect mPlotRect
wxRect mInfoRect
wxRect mUpdateRect
wxFlexGridSizer * szr
RulerPanel * vRuler
RulerPanel * hRuler
wxStaticText * mInfoText
int mLeftMargin
int mBottomMargin
int mInfoHeight
double mRate
int mDataLen
float * mData
int mWindowSize
float * mProcessed
int mProcessedSize
bool mLogAxis
float mYMin
float mYMax
float mYStep
wxBitmap * mBitmap
int mMouseX
int mMouseY
Static Private Attributes
static const int fontSize = 10
Detailed Description
Displays a spectrum plot of the waveform. Has options for selecting parameters of the plot.
Has a feature that finds peaks and reports their value as you move the mouse around.
Constructor & Destructor Documentation
FreqWindow::FreqWindow (wxWindow * parent, wxWindowID id, const wxString & title, const wxPoint & pos)
References ENV_DB_RANGE, FREQ_WINDOW_HEIGHT, FREQ_WINDOW_WIDTH, GetActiveProject(), gPrefs, Ruler::LinearDBFormat, NumWindowFuncs(), Ruler::RealFormat, and WindowFuncName().
FreqWindow::~FreqWindow () [virtual]
References mAlgChoice, mArrowCursor, mBitmap, mBuffer, mCloseButton, mCrossCursor, mData, mFreqPlot, mFuncChoice, mProcessed, and mSizeChoice.
Member Function Documentation
void FreqWindow::DrawPlot ()
References ThemeBase::Colour(), Ruler::DrawGrid(), Ruler::GetMaxSize(), GetProcessedValue(), hRuler, AColor::Line(), Ruler::LinearDBFormat, mAlgChoice, mBitmap, mData, mDataLen, mDrawGrid, mFreqFont, mLogAxis, mPlotRect, mProcessed, mProcessedSize, mRate, mUpdateRect, mWindowSize, mYMax, mYMin, Ruler::RealFormat, RulerPanel::ruler, Ruler::SetFormat(), Ruler::SetLog(), Ruler::SetRange(), Ruler::SetUnits(), szr, theTheme, and vRuler.
Referenced by OnAxisChoice(), OnSize(), and Recalc().
void FreqWindow::GetAudio ()
References floatSample, WaveTrack::Get(), WaveTrack::GetRate(), AudacityProject::GetTracks(), mBuffer, mDataLen, mRate, AudacityProject::mViewInfo, p, ViewInfo::sel0, ViewInfo::sel1, WaveTrack::TimeToLongSamples(), and Track::Wave.
float FreqWindow::GetProcessedValue (float freq0, float freq1) [private]
References CubicInterpolate(), mAlgChoice, mProcessed, mProcessedSize, mRate, and mWindowSize.
Referenced by DrawPlot(), and PlotPaint().
void FreqWindow::OnAlgChoice (wxCommandEvent & event)
References mAlgChoice, mAxisChoice, mLogAxis, and Recalc().
void FreqWindow::OnAxisChoice (wxCommandEvent & event)
References DrawPlot(), mAxisChoice, mFreqPlot, and mLogAxis.
void FreqWindow::OnCloseButton (wxCommandEvent & event)
void FreqWindow::OnCloseWindow (wxCloseEvent & event)
void FreqWindow::OnExport (wxCommandEvent & event)
void FreqWindow::OnFuncChoice (wxCommandEvent & event)
References Recalc().
void FreqWindow::OnGridOnOff (wxCommandEvent & event)
void FreqWindow::OnReplot (wxCommandEvent & event)
Referenced by AudacityProject::OnPlotSpectrum().
void FreqWindow::OnSize (wxSizeEvent & event)
References DrawPlot(), mFreqPlot, mPlotRect, and mUpdateRect.
Referenced by Plot().
void FreqWindow::OnSizeChoice (wxCommandEvent & event)
References Recalc().
void FreqWindow::Plot ()
References mBuffer, mData, mDataLen, OnSize(), and Recalc().
void FreqWindow::PlotMouseEvent (wxMouseEvent & event)
References mArrowCursor, mCrossCursor, mFreqPlot, mInfoText, mMouseX, mMouseY, and mPlotRect.
Referenced by FreqPlot::OnMouseEvent().
void FreqWindow::PlotPaint (wxPaintEvent & event)
References CubicMaximize(), FreqToMIDInoteNumber(), GetProcessedValue(), AColor::Line(), mAlgChoice, max, mBitmap, mFreqFont, mInfoText, mLogAxis, mMouseX, mMouseY, mPlotRect, mProcessed, mProcessedSize, mRate, mWindowSize, and PitchName_Absolute().
Referenced by FreqPlot::OnPaint().
void FreqWindow::Recalc ()
References dBRange, DrawPlot(), FFT(), InverseRealFFT(), mAlgChoice, mData, mDataLen, mFreqPlot, mFuncChoice, mProcessed, mProcessedSize, mSizeChoice, mWindowSize, mYMax, mYMin, mYStep, NumWindowFuncs(), PowerSpectrum(), RealFFT(), scale(), ProgressDialog::Update(), and WindowFunc().
Referenced by OnAlgChoice(), OnFuncChoice(), OnSizeChoice(), and Plot().
Member Data Documentation
int FreqWindow::dBRange [private]
Referenced by Recalc().
const int FreqWindow::fontSize = 10 [static, private]
RulerPanel* FreqWindow::hRuler [private]
Referenced by DrawPlot().
int FreqWindow::mAlg [private]
wxChoice* FreqWindow::mAlgChoice [private]
Referenced by DrawPlot(), GetProcessedValue(), OnAlgChoice(), PlotPaint(), Recalc(), and ~FreqWindow().
wxCursor* FreqWindow::mArrowCursor [private]
Referenced by PlotMouseEvent(), and ~FreqWindow().
int FreqWindow::mAxis [private]
wxChoice* FreqWindow::mAxisChoice [private]
Referenced by OnAlgChoice(), and OnAxisChoice().
wxBitmap* FreqWindow::mBitmap [private]
Referenced by DrawPlot(), PlotPaint(), and ~FreqWindow().
int FreqWindow::mBottomMargin [private]
float* FreqWindow::mBuffer [private]
Referenced by GetAudio(), Plot(), and ~FreqWindow().
wxButton* FreqWindow::mCloseButton [private]
Referenced by ~FreqWindow().
wxCursor* FreqWindow::mCrossCursor [private]
Referenced by PlotMouseEvent(), and ~FreqWindow().
float* FreqWindow::mData [private]
Referenced by DrawPlot(), Plot(), Recalc(), and ~FreqWindow().
int FreqWindow::mDataLen [private]
Referenced by DrawPlot(), GetAudio(), Plot(), and Recalc().
bool FreqWindow::mDrawGrid [private]
Referenced by DrawPlot().
wxButton* FreqWindow::mExportButton [private]
wxFont FreqWindow::mFreqFont [private]
Referenced by DrawPlot(), and PlotPaint().
FreqPlot* FreqWindow::mFreqPlot [private]
Referenced by OnAxisChoice(), OnSize(), PlotMouseEvent(), Recalc(), and ~FreqWindow().
int FreqWindow::mFunc [private]
wxChoice* FreqWindow::mFuncChoice [private]
Referenced by Recalc(), and ~FreqWindow().
wxCheckBox* FreqWindow::mGridOnOff [private]
wxStatusBar* FreqWindow::mInfo [private]
int FreqWindow::mInfoHeight [private]
wxRect FreqWindow::mInfoRect [private]
wxStaticText* FreqWindow::mInfoText [private]
Referenced by PlotMouseEvent(), and PlotPaint().
int FreqWindow::mLeftMargin [private]
bool FreqWindow::mLogAxis [private]
Referenced by DrawPlot(), OnAlgChoice(), OnAxisChoice(), and PlotPaint().
int FreqWindow::mMouseX [private]
Referenced by PlotMouseEvent(), and PlotPaint().
int FreqWindow::mMouseY [private]
Referenced by PlotMouseEvent(), and PlotPaint().
wxRect FreqWindow::mPlotRect [private]
Referenced by DrawPlot(), OnSize(), PlotMouseEvent(), and PlotPaint().
float* FreqWindow::mProcessed [private]
Referenced by DrawPlot(), GetProcessedValue(), PlotPaint(), Recalc(), and ~FreqWindow().
int FreqWindow::mProcessedSize [private]
Referenced by DrawPlot(), GetProcessedValue(), PlotPaint(), and Recalc().
double FreqWindow::mRate [private]
Referenced by DrawPlot(), GetAudio(), GetProcessedValue(), and PlotPaint().
wxButton* FreqWindow::mReplotButton [private]
int FreqWindow::mSize [private]
wxChoice* FreqWindow::mSizeChoice [private]
Referenced by Recalc(), and ~FreqWindow().
wxRect FreqWindow::mUpdateRect [private]
Referenced by DrawPlot(), and OnSize().
int FreqWindow::mWindowSize [private]
Referenced by DrawPlot(), GetProcessedValue(), PlotPaint(), and Recalc().
float FreqWindow::mYMax [private]
Referenced by DrawPlot(), and Recalc().
float FreqWindow::mYMin [private]
Referenced by DrawPlot(), and Recalc().
float FreqWindow::mYStep [private]
Referenced by Recalc().
AudacityProject* FreqWindow::p [private]
Referenced by GetAudio().
wxFlexGridSizer* FreqWindow::szr [private]
Referenced by DrawPlot().
RulerPanel* FreqWindow::vRuler [private]
Referenced by DrawPlot().
The documentation for this class was generated from the following files:
FreqWindow.h
FreqWindow.cpp