Audacity: LegacyAliasBlockFile Class Reference
LegacyAliasBlockFile Class Reference
An AliasBlockFile that references uncompressed data in an existing file.
#include <LegacyAliasBlockFile.h>
Public Member Functions
LegacyAliasBlockFile (wxFileName fileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, sampleCount summaryLen, bool noRMS)
Constructs a LegacyAliasBlockFile, writing the summary to disk.
virtual ~LegacyAliasBlockFile ()
virtual void SaveXML (XMLWriter &xmlFile)
Stores a representation of this file in XML.
virtual BlockFile * Copy (wxFileName fileName)
virtual void Recover ()
if the on-disk state disappeared, either recover it (if it was
Static Public Member Functions
static BlockFile * BuildFromXML (wxString projDir, const wxChar **attrs)
Detailed Description
An AliasBlockFile that references uncompressed data in an existing file.
Constructor & Destructor Documentation
LegacyAliasBlockFile::LegacyAliasBlockFile (wxFileName fileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, sampleCount summaryLen, bool noRMS)
Constructs a LegacyAliasBlockFile, writing the summary to disk.
References ComputeLegacySummaryInfo(), floatSample, int16Sample, BlockFile::mMax, BlockFile::mMin, BlockFile::mRMS, and BlockFile::mSummaryInfo.
Referenced by BuildFromXML(), and Copy().
LegacyAliasBlockFile::~LegacyAliasBlockFile () [virtual]
Member Function Documentation
BlockFile * LegacyAliasBlockFile::BuildFromXML (wxString projDir, const wxChar ** attrs) [static]
References XMLValueChecker::IsGoodFileName(), XMLValueChecker::IsGoodInt(), XMLValueChecker::IsGoodPathName(), XMLValueChecker::IsValidChannel(), and LegacyAliasBlockFile().
Referenced by DirManager::HandleXMLTag().
BlockFile * LegacyAliasBlockFile::Copy (wxFileName newFileName) [virtual]
Construct a new LegacyAliasBlockFile based on this one, but writing the summary data to a new file.
Parameters:
newFileName The filename to copy the summary data to.
Reimplemented from PCMAliasBlockFile.
References SummaryInfo::fields, LegacyAliasBlockFile(), AliasBlockFile::mAliasChannel, AliasBlockFile::mAliasedFileName, AliasBlockFile::mAliasStart, BlockFile::mLen, BlockFile::mSummaryInfo, and SummaryInfo::totalSummaryBytes.
void LegacyAliasBlockFile::Recover () [virtual]
if the on-disk state disappeared, either recover it (if it was
Reimplemented from PCMAliasBlockFile.
References AliasBlockFile::WriteSummary().
void LegacyAliasBlockFile::SaveXML (XMLWriter & xmlFile) [virtual]
Stores a representation of this file in XML.
Reimplemented from PCMAliasBlockFile.
References XMLWriter::EndTag(), SummaryInfo::fields, AliasBlockFile::mAliasChannel, AliasBlockFile::mAliasedFileName, AliasBlockFile::mAliasStart, BlockFile::mFileName, BlockFile::mLen, BlockFile::mSummaryInfo, XMLWriter::StartTag(), SummaryInfo::totalSummaryBytes, and XMLWriter::WriteAttr().
The documentation for this class was generated from the following files:
LegacyAliasBlockFile.h
LegacyAliasBlockFile.cpp