Audacity: EffectNormalize Class Reference
EffectNormalize Class Reference
An Effect.
#include <Normalize.h>
Public Member Functions
EffectNormalize ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual wxString GetEffectDescription ()
virtual bool PromptUser ()
virtual bool TransferParameters (Shuttle &shuttle)
virtual bool Init ()
virtual void End ()
virtual bool CheckWhetherSkipEffect ()
virtual bool Process ()
Private Member Functions
bool ProcessOne (WaveTrack *t, sampleCount start, sampleCount end)
virtual void StartAnalysis ()
virtual void AnalyzeData (float *buffer, sampleCount len)
virtual void StartProcessing ()
virtual void ProcessData (float *buffer, sampleCount len)
Private Attributes
bool mGain
bool mDC
double mLevel
int mCurTrackNum
double mCurRate
double mCurT0
double mCurT1
int mCurChannel
float mMult
float mOffset
float mMin
float mMax
double mSum
int mCount
Friends
class NormalizeDialog
Detailed Description
An Effect.
Constructor & Destructor Documentation
EffectNormalize::EffectNormalize ()
References Init().
Member Function Documentation
void EffectNormalize::AnalyzeData (float * buffer, sampleCount len) [private, virtual]
References mCount, mMax, mMin, and mSum.
Referenced by ProcessOne().
bool EffectNormalize::CheckWhetherSkipEffect () [virtual]
Reimplemented from Effect.
References mDC, and mGain.
void EffectNormalize::End () [virtual]
Reimplemented from Effect.
References gFrameSum, gPrefs, mMult, and mOffset.
virtual wxString EffectNormalize::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectNormalize::GetEffectCategories () [inline, virtual]
wxString EffectNormalize::GetEffectDescription () [virtual]
Reimplemented from Effect.
References GetEffectName(), mDC, mGain, and mLevel.
virtual wxString EffectNormalize::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectNormalize::GetEffectName () [inline, virtual]
Implements Effect.
Referenced by GetEffectDescription().
bool EffectNormalize::Init () [virtual]
Reimplemented from Effect.
References gPrefs, mDC, mGain, and mLevel.
Referenced by EffectNormalize().
bool EffectNormalize::Process () [virtual]
Implements Effect.
References Effect::CopyInputTracks(), TrackListCondIterator::First(), Track::GetChannel(), WaveTrack::GetEndTime(), WaveTrack::GetRate(), WaveTrack::GetStartTime(), mCurChannel, mCurRate, mCurT0, mCurT1, mCurTrackNum, mDC, mGain, Effect::mOutputTracks, Effect::mT0, Effect::mT1, TrackListCondIterator::Next(), ProcessOne(), Effect::ReplaceProcessedTracks(), WaveTrack::TimeToLongSamples(), and Track::Wave.
void EffectNormalize::ProcessData (float * buffer, sampleCount len) [private, virtual]
References gFrameSum, mMult, and mOffset.
Referenced by ProcessOne().
bool EffectNormalize::ProcessOne (WaveTrack * t, sampleCount start, sampleCount end) [private]
References AnalyzeData(), floatSample, WaveTrack::Get(), WaveTrack::GetBestBlockSize(), WaveTrack::GetMaxBlockSize(), mCurTrackNum, ProcessData(), WaveTrack::Set(), StartAnalysis(), StartProcessing(), and Effect::TrackProgress().
Referenced by Process().
bool EffectNormalize::PromptUser () [virtual]
Reimplemented from Effect.
References gPrefs, mDC, NormalizeDialog::mDC, mGain, NormalizeDialog::mGain, mLevel, NormalizeDialog::mLevel, Effect::mParent, and NormalizeDialog::TransferDataToWindow().
void EffectNormalize::StartAnalysis () [private, virtual]
References mCount, mMax, mMin, and mSum.
Referenced by ProcessOne().
void EffectNormalize::StartProcessing () [private, virtual]
References mCount, mDC, mGain, mLevel, mMax, mMin, mMult, mOffset, mSum, NORMALIZE_DB_MAX, NORMALIZE_DB_MIN, and TrapDouble().
Referenced by ProcessOne().
bool EffectNormalize::TransferParameters (Shuttle & shuttle) [virtual]
Reimplemented from Effect.
References mDC, mGain, mLevel, Shuttle::TransferBool(), and Shuttle::TransferDouble().
Friends And Related Function Documentation
friend class NormalizeDialog [friend]
Member Data Documentation
int EffectNormalize::mCount [private]
Referenced by AnalyzeData(), StartAnalysis(), and StartProcessing().
int EffectNormalize::mCurChannel [private]
Referenced by Process().
double EffectNormalize::mCurRate [private]
Referenced by Process().
double EffectNormalize::mCurT0 [private]
Referenced by Process().
double EffectNormalize::mCurT1 [private]
Referenced by Process().
int EffectNormalize::mCurTrackNum [private]
Referenced by Process(), and ProcessOne().
bool EffectNormalize::mDC [private]
Referenced by CheckWhetherSkipEffect(), GetEffectDescription(), Init(), NormalizeDialog::OnPreview(), Process(), PromptUser(), StartProcessing(), and TransferParameters().
bool EffectNormalize::mGain [private]
Referenced by CheckWhetherSkipEffect(), GetEffectDescription(), Init(), NormalizeDialog::OnPreview(), Process(), PromptUser(), StartProcessing(), and TransferParameters().
double EffectNormalize::mLevel [private]
Referenced by GetEffectDescription(), Init(), NormalizeDialog::OnPreview(), PromptUser(), StartProcessing(), and TransferParameters().
float EffectNormalize::mMax [private]
Referenced by AnalyzeData(), StartAnalysis(), and StartProcessing().
float EffectNormalize::mMin [private]
Referenced by AnalyzeData(), StartAnalysis(), and StartProcessing().
float EffectNormalize::mMult [private]
Referenced by End(), ProcessData(), and StartProcessing().
float EffectNormalize::mOffset [private]
Referenced by End(), ProcessData(), and StartProcessing().
double EffectNormalize::mSum [private]
Referenced by AnalyzeData(), StartAnalysis(), and StartProcessing().
The documentation for this class was generated from the following files:
Normalize.h
Normalize.cpp