Audacity: LegacyBlockFile Class Reference
LegacyBlockFile Class Reference
Audacity 1.1.0 block file format:.
#include <LegacyBlockFile.h>
Public Member Functions
LegacyBlockFile (wxFileName existingFile, sampleFormat format, sampleCount summaryLen, sampleCount len, bool noRMS)
Create the memory structure to refer to the given block file.
virtual ~LegacyBlockFile ()
virtual bool ReadSummary (void *data)
Read the summary section of the disk file.
virtual int ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len)
Read the data section of the disk file.
virtual BlockFile * Copy (wxFileName newFileName)
Create a new block file identical to this one.
virtual void SaveXML (XMLWriter &xmlFile)
Write an XML representation of this file.
virtual wxLongLong GetSpaceUsage ()
virtual void Recover ()
if the on-disk state disappeared, either recover it (if it was
Static Public Member Functions
static BlockFile * BuildFromXML (wxString dir, const wxChar **attrs, sampleCount len, sampleFormat format)
static
Protected Attributes
sampleFormat mFormat
Detailed Description
Audacity 1.1.0 block file format:.
Header tag: 20 bytes "AudacityBlockFile110"
64K summaries (min, max, RMS, each a 4-byte float)
256 summaries (min, max, RMS, each a 4-byte float)
Constructor & Destructor Documentation
LegacyBlockFile::LegacyBlockFile (wxFileName existingFile, sampleFormat format, sampleCount summaryLen, sampleCount len, bool noRMS)
Create the memory structure to refer to the given block file.
Construct a LegacyBlockFile memory structure that will point to an existing block file. This file must exist and be a valid block file.
Parameters:
existingFile The disk file this LegacyBlockFile should use.
References ComputeLegacySummaryInfo(), floatSample, int16Sample, BlockFile::mMax, BlockFile::mMin, BlockFile::mRMS, and BlockFile::mSummaryInfo.
Referenced by BuildFromXML(), and Copy().
LegacyBlockFile::~LegacyBlockFile () [virtual]
Member Function Documentation
BlockFile * LegacyBlockFile::BuildFromXML (wxString dir, const wxChar ** attrs, sampleCount len, sampleFormat format) [static]
static
References XMLValueChecker::IsGoodFileName(), XMLValueChecker::IsGoodInt(), XMLValueChecker::IsValidSampleFormat(), and LegacyBlockFile().
Referenced by DirManager::HandleXMLTag().
BlockFile * LegacyBlockFile::Copy (wxFileName newFileName) [virtual]
Create a new block file identical to this one.
Create a copy of this BlockFile, but using a different disk file.
Parameters:
newFileName The name of the new file to use.
Implements BlockFile.
References SummaryInfo::fields, LegacyBlockFile(), mFormat, BlockFile::mLen, BlockFile::mSummaryInfo, and SummaryInfo::totalSummaryBytes.
wxLongLong LegacyBlockFile::GetSpaceUsage () [virtual]
Implements BlockFile.
References BlockFile::mFileName.
int LegacyBlockFile::ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len) [virtual]
Read the data section of the disk file.
Read the data portion of the block file using libsndfile. Convert it to the given format if it is not already.
Parameters:
data The buffer where the data will be stored
format The format the data will be stored in
start The offset in this block file
len The number of samples to read
Implements BlockFile.
References CopySamples(), DeleteSamples(), floatSample, int16Sample, int24Sample, BlockFile::mFileName, mFormat, BlockFile::mLen, BlockFile::mSilentLog, BlockFile::mSummaryInfo, NewSamples(), SAMPLE_SIZE, sf_subtype_is_integer(), and SummaryInfo::totalSummaryBytes.
bool LegacyBlockFile::ReadSummary (void * data) [virtual]
Read the summary section of the disk file.
Read the summary section of the disk file.
Parameters:
*data The buffer to write the data to. It must be at least mSummaryinfo.totalSummaryBytes long.
Implements BlockFile.
References BlockFile::mFileName, BlockFile::mSilentLog, BlockFile::mSummaryInfo, and SummaryInfo::totalSummaryBytes.
void LegacyBlockFile::Recover () [virtual]
if the on-disk state disappeared, either recover it (if it was
Implements BlockFile.
void LegacyBlockFile::SaveXML (XMLWriter & xmlFile) [virtual]
Write an XML representation of this file.
Implements BlockFile.
References XMLWriter::EndTag(), SummaryInfo::fields, BlockFile::mFileName, BlockFile::mLen, BlockFile::mSummaryInfo, XMLWriter::StartTag(), SummaryInfo::totalSummaryBytes, and XMLWriter::WriteAttr().
Member Data Documentation
sampleFormat LegacyBlockFile::mFormat [protected]
Referenced by Copy(), and ReadData().
The documentation for this class was generated from the following files:
LegacyBlockFile.h
LegacyBlockFile.cpp