Audacity: RecordingPrefs Class Reference
RecordingPrefs Class Reference
A PrefsPanel used to select recording options.
#include <RecordingPrefs.h>
Public Member Functions
RecordingPrefs (wxWindow *parent)
virtual ~RecordingPrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
void PopulateOrExchange (ShuttleGui &S)
Detailed Description
A PrefsPanel used to select recording options.
Presents interface for user to update the various recording options like playthrough, latency correction, and others.
Constructor & Destructor Documentation
RecordingPrefs::RecordingPrefs (wxWindow * parent)
References Populate().
RecordingPrefs::~RecordingPrefs () [virtual]
Member Function Documentation
bool RecordingPrefs::Apply () [virtual]
Implements PrefsPanel.
References DEFAULT_LATENCY_DURATION, eIsSavingToPrefs, gPrefs, min(), and PopulateOrExchange().
void RecordingPrefs::Populate () [private]
References eIsCreatingFromPrefs, and PopulateOrExchange().
Referenced by RecordingPrefs().
void RecordingPrefs::PopulateOrExchange (ShuttleGui & S) [private]
References ShuttleGuiBase::AddUnits(), DEFAULT_LATENCY_CORRECTION, DEFAULT_LATENCY_DURATION, ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), ShuttleGuiBase::EndThreeColumn(), ENV_DB_RANGE, gPrefs, ShuttleGuiBase::SetBorder(), ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartMultiColumn(), ShuttleGuiBase::StartStatic(), ShuttleGuiBase::StartThreeColumn(), ShuttleGuiBase::TieCheckBox(), ShuttleGuiBase::TieSlider(), and ShuttleGuiBase::TieTextBox().
Referenced by Apply(), and Populate().
The documentation for this class was generated from the following files:
RecordingPrefs.h
RecordingPrefs.cpp