Audacity: Resample Class Reference
Resample Class Reference
Combined interface to libresample and libsamplerate.
#include <Resample.h>
Public Member Functions
Resample (bool useBestMethod, double minFactor, double maxFactor)
bool Ok ()
Returns true if the constructor succeeded.
int Process (double factor, float *inBuffer, int inBufferLen, bool lastFlag, int *inBufferUsed, float *outBuffer, int outBufferLen)
Main processing function. Resamples from the input buffer to the output buffer.
~Resample ()
Static Public Member Functions
static bool ResamplingEnabled ()
static wxString GetResamplingLibraryName ()
static int GetNumMethods ()
static wxString GetMethodName (int index)
static int GetFastMethod ()
static int GetBestMethod ()
static void SetFastMethod (int index)
static void SetBestMethod (int index)
static const wxString GetFastMethodKey ()
static const wxString GetBestMethodKey ()
static int GetFastMethodDefault ()
static int GetBestMethodDefault ()
Private Attributes
int mMethod
void * mHandle
bool mInitial
Detailed Description
Combined interface to libresample and libsamplerate.
This class abstracts the interface to two different resampling libraries:
libresample, written by Dominic Mazzoni based on Resample-1.7 by Julius Smith. LGPL.
libsamplerate, written by Erik de Castro Lopo. GPL. The author of libsamplerate requests that you not distribute a binary version of Audacity that links to libsamplerate and also has plug-in support.
Constructor & Destructor Documentation
Resample::Resample (bool useBestMethod, double minFactor, double maxFactor)
Constructor. The first parameter lets you select either the best method or the fast method - the particular method used was set by SetFastMethod or SetBestMethod, above. minFactor and maxFactor specify the range of factors that will be used, if you plan to vary the factor over time. Otherwise set minFactor and maxFactor to the same value for optimized performance.
References GetBestMethod(), GetFastMethod(), mHandle, and mMethod.
Resample::~Resample ()
References mHandle.
Member Function Documentation
int Resample::GetBestMethod () [static]
References GetBestMethodDefault(), GetBestMethodKey(), and gPrefs.
Referenced by Resample().
int Resample::GetBestMethodDefault () [static]
Referenced by GetBestMethod(), and QualityPrefs::PopulateOrExchange().
const wxString Resample::GetBestMethodKey () [static]
Referenced by GetBestMethod(), QualityPrefs::PopulateOrExchange(), and SetBestMethod().
int Resample::GetFastMethod () [static]
Audacity identifies two methods out of all of the choices: a Fast method intended for real-time audio I/O, and a Best method intended for mixing and exporting. These are saved in the preferences when you call Set[Best,Fast]Method.
References GetFastMethodDefault(), GetFastMethodKey(), and gPrefs.
Referenced by Resample().
int Resample::GetFastMethodDefault () [static]
Referenced by GetFastMethod(), and QualityPrefs::PopulateOrExchange().
const wxString Resample::GetFastMethodKey () [static]
Referenced by GetFastMethod(), QualityPrefs::PopulateOrExchange(), and SetFastMethod().
wxString Resample::GetMethodName (int index) [static]
Referenced by QualityPrefs::GetNamesAndLabels().
int Resample::GetNumMethods () [static]
Resamplers may have more than one method, offering a tradeoff between speed and quality. This lets you query the various methods available.
Referenced by QualityPrefs::GetNamesAndLabels().
wxString Resample::GetResamplingLibraryName () [static]
Returns the name of the library used for resampling (long format, may include author name and version number).
bool Resample::Ok ()
Returns true if the constructor succeeded.
References mHandle.
int Resample::Process (double factor, float * inBuffer, int inBufferLen, bool lastFlag, int * inBufferUsed, float * outBuffer, int outBufferLen)
Main processing function. Resamples from the input buffer to the output buffer.
Reads samples from the input buffer, and writes samples to the output buffer. Stops when either is exhaughsted, or we reach a convenient block end, unless lastFlag is set to force emptying the input buffer. The number of input samples used is returned in inBufferUsed, and the number of output samples generated is the return value of the function. This function may do nothing if you don't pass a large enough output buffer (i.e. there is no where to put a full block of output data)
Parameters:
factor The scaling factor to resample by.
inBuffer Buffer of input samples to be processed (mono)
inBufferLen Length of the input buffer, in samples.
lastFlag Flag to indicate this is the last lot of input samples and the buffer needs to be emptied out into the rate converter.
inBufferUsed Number of samples from inBuffer that have been used (unless lastFlag is true, we don't garuntee to process all the samples in the input this time, we may leave some for next time)
outBuffer Buffer to write output (converted) samples to.
outBufferLen How big outBuffer is.
Returns:
Number of output samples created by this call
References mHandle.
Referenced by AudioIO::FillBuffers(), Mixer::MixVariableRates(), and EffectChangeSpeed::ProcessOne().
bool Resample::ResamplingEnabled () [static]
This will return true if Audacity is being compiled with resampling support.
void Resample::SetBestMethod (int index) [static]
References GetBestMethodKey(), and gPrefs.
void Resample::SetFastMethod (int index) [static]
References GetFastMethodKey(), and gPrefs.
Member Data Documentation
void* Resample::mHandle [private]
Referenced by Ok(), Process(), Resample(), and ~Resample().
bool Resample::mInitial [private]
int Resample::mMethod [private]
Referenced by Resample().
The documentation for this class was generated from the following files:
Resample.h
Resample.cpp