Audacity: SelectCommand Class Reference
SelectCommand Class Reference
Command for changing the selection.
#include <SelectCommand.h>
Public Member Functions
SelectCommand (SelectCommandType &type, CommandOutputTarget *target)
virtual bool Apply (CommandExecutionContext context)
Detailed Description
Command for changing the selection.
Constructor & Destructor Documentation
SelectCommand::SelectCommand (SelectCommandType & type, CommandOutputTarget * target) [inline]
Member Function Documentation
bool SelectCommand::Apply (CommandExecutionContext context) [virtual]
Actually carry out the command. Return true if successful and false otherwise.
Reimplemented from CommandImplementation.
References CommandImplementation::Error(), TrackListIterator::First(), TrackList::GetCount(), CommandImplementation::GetDouble(), TrackList::GetEndTime(), CommandImplementation::GetLong(), Track::GetName(), CommandImplementation::GetString(), AudacityProject::GetTracks(), AudacityProject::mViewInfo, name, TrackListIterator::Next(), AudacityProject::OnSelectAll(), AudacityProject::OnSelectNone(), CommandExecutionContext::proj, ViewInfo::sel0, ViewInfo::sel1, Track::SetSelected(), and CommandImplementation::Status().
The documentation for this class was generated from the following files:
SelectCommand.h
SelectCommand.cpp