Audacity: Validator Class Reference
Validator Class Reference
A Validator is an object which checks whether a wxVariant satisfies a certain criterion. This is a base validator which allows anything.
#include <Validators.h>
Public Member Functions
Validator ()
virtual ~Validator ()
void SetConverted (const wxVariant &v)
const wxVariant & GetConverted ()
virtual bool Validate (const wxVariant &v)
Judge whether the passed value satisfies the Validator.
virtual wxString GetDescription () const
virtual Validator * GetClone () const
This MUST be overridden, to avoid slicing!
Private Attributes
wxVariant mConverted
Detailed Description
A Validator is an object which checks whether a wxVariant satisfies a certain criterion. This is a base validator which allows anything.
Constructor & Destructor Documentation
Validator::Validator () [inline]
Referenced by GetClone().
virtual Validator::~Validator () [inline, virtual]
Member Function Documentation
virtual Validator* Validator::GetClone () const [inline, virtual]
This MUST be overridden, to avoid slicing!
Reimplemented in OptionValidator, BoolValidator, BoolArrayValidator, DoubleValidator, RangeValidator, and IntValidator.
References Validator().
const wxVariant& Validator::GetConverted () [inline]
References mConverted.
Referenced by CommandImplementation::SetParameter(), IntValidator::Validate(), DoubleValidator::Validate(), and BoolValidator::Validate().
virtual wxString Validator::GetDescription () const [inline, virtual]
Return a description (for error messages) should be of the form 'v must be $description'
Reimplemented in OptionValidator, BoolValidator, BoolArrayValidator, DoubleValidator, RangeValidator, and IntValidator.
Referenced by CommandSignature::AddParameter(), CommandType::Describe(), and CommandImplementation::SetParameter().
void Validator::SetConverted (const wxVariant & v) [inline]
References mConverted.
Referenced by IntValidator::Validate(), RangeValidator::Validate(), DoubleValidator::Validate(), BoolArrayValidator::Validate(), BoolValidator::Validate(), OptionValidator::Validate(), and Validate().
virtual bool Validator::Validate (const wxVariant & v) [inline, virtual]
Judge whether the passed value satisfies the Validator.
Reimplemented in OptionValidator, BoolValidator, BoolArrayValidator, DoubleValidator, RangeValidator, and IntValidator.
References SetConverted().
Referenced by CommandSignature::AddParameter(), and CommandImplementation::SetParameter().
Member Data Documentation
wxVariant Validator::mConverted [private]
Referenced by GetConverted(), and SetConverted().
The documentation for this class was generated from the following file:
Validators.h