Audacity: UploadDialog Class Reference
UploadDialog Class Reference
A contributed class for uploading audio via FTP.
#include <UploadDialog.h>
Public Member Functions
UploadDialog (wxWindow *parent)
virtual ~UploadDialog ()
void OnCancel (wxCommandEvent &event)
void OnConnect (wxCommandEvent &event)
void OnDisconnect (wxCommandEvent &event)
void OnUploadFile (wxCommandEvent &event)
void OnUploadDir (wxCommandEvent &event)
void OnCreateDir (wxCommandEvent &event)
void OnActivateItem (wxListEvent &event)
void OnActivateSite (wxListEvent &event)
void OnListRightClick (wxListEvent &event)
void OnPopupMenu (wxCommandEvent &event)
void OnNewSite (wxCommandEvent &event)
void OnDeleteSite (wxCommandEvent &event)
void OnFtpChange (wxCommandEvent &event)
void OnSelectSite (wxListEvent &event)
void OnCharPress (wxKeyEvent &event)
void GetDirContents (void)
void RefreshFiles (void)
void ExtractListData (wxString string, wxArrayString *results)
bool SaveFtpSite (wxString name, wxString host, wxString user, wxString pass)
void LoadFtpSiteList (void)
void UpdateSiteList (void)
void DownloadItem (wxString &src, wxString &dest, bool dir, bool multi)
void DownloadItem (wxString &src, bool dir)
void DownloadMultipleItems (void)
void DownloadFile (wxString src, wxString dest)
void DownloadDir (wxString src, wxString dest)
void GetDeleteList (wxString src)
void RemoveItems (wxArrayString *files, wxArrayString *dirs)
void UploadFile (wxString src, wxString dest)
void UploadDir (wxString src, wxString dest)
Public Attributes
wxBoxSizer * topsizer
wxButton * btnConnect
wxButton * btnDisconnect
wxButton * btnUploadFile
wxButton * btnUploadDir
wxButton * btnCreateDir
wxButton * btnNewSite
wxButton * btnDelSite
wxCheckBox * cbSave
wxCheckBox * cbPasv
wxImageList * icons
wxListView * siteList
wxListView * fileManager
wxTextCtrl * txtFtpName
wxTextCtrl * txtFtpHost
wxTextCtrl * txtFtpUser
wxTextCtrl * txtFtpPass
wxFTP * ftp
wxPoint mousePos
wxArrayString * filenameList
wxArrayString * filepermList
wxArrayString * filesizeList
wxArrayString * dirnameList
wxArrayString * dirpermList
wxArrayString * dirsizeList
wxArrayString * displayNames
wxArrayString * displayPerm
wxArrayString * displaySizes
wxArrayString * deleteFileList
wxArrayString * deleteDirList
wxArrayString * ftpList
ProgressDialog * mProgress
long listIndex
long ftpIndex
long currentFtp
bool abort
Detailed Description
A contributed class for uploading audio via FTP.
Constructor & Destructor Documentation
UploadDialog::UploadDialog (wxWindow * parent)
Todo:
get these XPMs out of here and into Theme.
References ThemeBase::Bitmap(), theTheme, wxID_FTPHOST, wxID_FTPNAME, wxID_FTPPASS, and wxID_FTPUSER.
UploadDialog::~UploadDialog () [virtual]
Member Function Documentation
void UploadDialog::DownloadDir (wxString src, wxString dest)
References abort, displayNames, displayPerm, DownloadItem(), ftp, and GetDirContents().
Referenced by DownloadItem(), and DownloadMultipleItems().
void UploadDialog::DownloadFile (wxString src, wxString dest)
References abort, CHUNKSIZE, eProgressSuccess, ftp, mProgress, and ProgressDialog::Update().
Referenced by DownloadItem(), and DownloadMultipleItems().
void UploadDialog::DownloadItem (wxString & src, bool dir)
References abort, DownloadDir(), and DownloadFile().
void UploadDialog::DownloadItem (wxString & src, wxString & dest, bool dir, bool multi)
References abort, DownloadDir(), and DownloadFile().
Referenced by DownloadDir(), and OnPopupMenu().
void UploadDialog::DownloadMultipleItems (void)
References displayNames, displayPerm, DownloadDir(), DownloadFile(), and fileManager.
Referenced by OnPopupMenu().
void UploadDialog::ExtractListData (wxString string, wxArrayString * results)
Referenced by GetDirContents().
void UploadDialog::GetDeleteList (wxString src)
References deleteDirList, deleteFileList, displayNames, displayPerm, ftp, GetDirContents(), mProgress, and ProgressDialog::Update().
Referenced by OnPopupMenu().
void UploadDialog::GetDirContents (void)
References dirnameList, dirpermList, dirsizeList, displayNames, displayPerm, displaySizes, ExtractListData(), filenameList, filepermList, filesizeList, and ftp.
Referenced by DownloadDir(), GetDeleteList(), and RefreshFiles().
void UploadDialog::LoadFtpSiteList (void)
References FileNames::DataDir(), and ftpList.
Referenced by UpdateSiteList().
void UploadDialog::OnActivateItem (wxListEvent & event)
References displayNames, ftp, and RefreshFiles().
void UploadDialog::OnActivateSite (wxListEvent & event)
void UploadDialog::OnCancel (wxCommandEvent & event)
References ftp, and OnDisconnect().
void UploadDialog::OnCharPress (wxKeyEvent & event)
void UploadDialog::OnConnect (wxCommandEvent & event)
void UploadDialog::OnCreateDir (wxCommandEvent & event)
References ftp, and RefreshFiles().
void UploadDialog::OnDeleteSite (wxCommandEvent & event)
References FileNames::DataDir(), ftpIndex, siteList, and UpdateSiteList().
void UploadDialog::OnDisconnect (wxCommandEvent & event)
Referenced by OnCancel().
void UploadDialog::OnFtpChange (wxCommandEvent & event)
References ftpIndex, siteList, and txtFtpName.
void UploadDialog::OnListRightClick (wxListEvent & event)
References fileManager, listIndex, mousePos, wxID_POPUP_DELETE, wxID_POPUP_DOWNLOAD, and wxID_POPUP_RENAME.
void UploadDialog::OnNewSite (wxCommandEvent & event)
References ftpIndex, siteList, and txtFtpName.
void UploadDialog::OnPopupMenu (wxCommandEvent & event)
References abort, deleteDirList, deleteFileList, displayNames, displayPerm, DownloadItem(), DownloadMultipleItems(), fileManager, ftp, GetDeleteList(), listIndex, mProgress, RefreshFiles(), RemoveItems(), wxID_POPUP_DELETE, wxID_POPUP_DOWNLOAD, and wxID_POPUP_RENAME.
void UploadDialog::OnSelectSite (wxListEvent & event)
References currentFtp, ftpIndex, ftpList, txtFtpHost, txtFtpName, txtFtpPass, and txtFtpUser.
void UploadDialog::OnUploadDir (wxCommandEvent & event)
void UploadDialog::OnUploadFile (wxCommandEvent & event)
void UploadDialog::RefreshFiles (void)
References displayNames, displayPerm, displaySizes, fileManager, and GetDirContents().
Referenced by OnActivateItem(), OnCreateDir(), OnPopupMenu(), and UploadDir().
void UploadDialog::RemoveItems (wxArrayString * files, wxArrayString * dirs)
References ftp, mProgress, and ProgressDialog::Update().
Referenced by OnPopupMenu().
bool UploadDialog::SaveFtpSite (wxString name, wxString host, wxString user, wxString pass)
References FileNames::DataDir().
void UploadDialog::UpdateSiteList (void)
References ftpList, LoadFtpSiteList(), and siteList.
Referenced by OnDeleteSite().
void UploadDialog::UploadDir (wxString src, wxString dest)
References abort, ftp, RefreshFiles(), and UploadFile().
void UploadDialog::UploadFile (wxString src, wxString dest)
References abort, CHUNKSIZE, ftp, mProgress, and ProgressDialog::Update().
Referenced by UploadDir().
Member Data Documentation
bool UploadDialog::abort
Referenced by DownloadDir(), DownloadFile(), DownloadItem(), OnPopupMenu(), UploadDir(), and UploadFile().
wxButton* UploadDialog::btnConnect
wxButton* UploadDialog::btnCreateDir
wxButton* UploadDialog::btnDelSite
wxButton* UploadDialog::btnDisconnect
wxButton* UploadDialog::btnNewSite
wxButton* UploadDialog::btnUploadDir
wxButton* UploadDialog::btnUploadFile
wxCheckBox* UploadDialog::cbPasv
wxCheckBox* UploadDialog::cbSave
long UploadDialog::currentFtp
Referenced by OnSelectSite().
wxArrayString* UploadDialog::deleteDirList
Referenced by GetDeleteList(), and OnPopupMenu().
wxArrayString* UploadDialog::deleteFileList
Referenced by GetDeleteList(), and OnPopupMenu().
wxArrayString* UploadDialog::dirnameList
Referenced by GetDirContents().
wxArrayString* UploadDialog::dirpermList
Referenced by GetDirContents().
wxArrayString* UploadDialog::dirsizeList
Referenced by GetDirContents().
wxArrayString* UploadDialog::displayNames
Referenced by DownloadDir(), DownloadMultipleItems(), GetDeleteList(), GetDirContents(), OnActivateItem(), OnPopupMenu(), and RefreshFiles().
wxArrayString* UploadDialog::displayPerm
Referenced by DownloadDir(), DownloadMultipleItems(), GetDeleteList(), GetDirContents(), OnPopupMenu(), and RefreshFiles().
wxArrayString* UploadDialog::displaySizes
Referenced by GetDirContents(), and RefreshFiles().
wxListView* UploadDialog::fileManager
Referenced by DownloadMultipleItems(), OnListRightClick(), OnPopupMenu(), and RefreshFiles().
wxArrayString* UploadDialog::filenameList
Referenced by GetDirContents().
wxArrayString* UploadDialog::filepermList
Referenced by GetDirContents().
wxArrayString* UploadDialog::filesizeList
Referenced by GetDirContents().
wxFTP* UploadDialog::ftp
Referenced by DownloadDir(), DownloadFile(), GetDeleteList(), GetDirContents(), OnActivateItem(), OnCancel(), OnCreateDir(), OnPopupMenu(), RemoveItems(), UploadDir(), and UploadFile().
long UploadDialog::ftpIndex
Referenced by OnDeleteSite(), OnFtpChange(), OnNewSite(), and OnSelectSite().
wxArrayString* UploadDialog::ftpList
Referenced by LoadFtpSiteList(), OnSelectSite(), and UpdateSiteList().
wxImageList* UploadDialog::icons
long UploadDialog::listIndex
Referenced by OnListRightClick(), and OnPopupMenu().
wxPoint UploadDialog::mousePos
Referenced by OnListRightClick().
ProgressDialog* UploadDialog::mProgress
Referenced by DownloadFile(), GetDeleteList(), OnPopupMenu(), RemoveItems(), and UploadFile().
wxListView* UploadDialog::siteList
Referenced by OnDeleteSite(), OnFtpChange(), OnNewSite(), and UpdateSiteList().
wxBoxSizer* UploadDialog::topsizer
wxTextCtrl* UploadDialog::txtFtpHost
Referenced by OnSelectSite().
wxTextCtrl* UploadDialog::txtFtpName
Referenced by OnFtpChange(), OnNewSite(), and OnSelectSite().
wxTextCtrl* UploadDialog::txtFtpPass
Referenced by OnSelectSite().
wxTextCtrl* UploadDialog::txtFtpUser
Referenced by OnSelectSite().
The documentation for this class was generated from the following files:
UploadDialog.h
UploadDialog.cpp