Audacity: ImportPlugin Class Reference
ImportPlugin Class Reference
Base class for FlacImportPlugin, LOFImportPlugin, MP3ImportPlugin, OggImportPlugin and PCMImportPlugin. Gives API for sound file import.
#include <ImportPlugin.h>
Public Member Functions
virtual wxString GetPluginFormatDescription ()=0
virtual wxArrayString GetSupportedExtensions ()
bool SupportsExtension (wxString extension)
virtual ImportFileHandle * Open (wxString Filename)=0
virtual ~ImportPlugin ()
Protected Member Functions
ImportPlugin (wxArrayString supportedExtensions)
Protected Attributes
wxArrayString mExtensions
Detailed Description
Base class for FlacImportPlugin, LOFImportPlugin, MP3ImportPlugin, OggImportPlugin and PCMImportPlugin. Gives API for sound file import.
Constructor & Destructor Documentation
virtual ImportPlugin::~ImportPlugin () [inline, virtual]
ImportPlugin::ImportPlugin (wxArrayString supportedExtensions) [inline, protected]
Member Function Documentation
virtual wxString ImportPlugin::GetPluginFormatDescription () [pure virtual]
Implemented in FFmpegImportPlugin, FLACImportPlugin, LOFImportPlugin, MP3ImportPlugin, OggImportPlugin, and PCMImportPlugin.
Referenced by Importer::GetSupportedImportFormats(), and Importer::Import().
virtual wxArrayString ImportPlugin::GetSupportedExtensions () [inline, virtual]
References mExtensions.
Referenced by Importer::GetSupportedImportFormats().
virtual ImportFileHandle* ImportPlugin::Open (wxString Filename) [pure virtual]
Implemented in FFmpegImportPlugin, FLACImportPlugin, LOFImportPlugin, MP3ImportPlugin, OggImportPlugin, and PCMImportPlugin.
Referenced by Importer::Import().
bool ImportPlugin::SupportsExtension (wxString extension) [inline]
References mExtensions.
Referenced by Importer::Import(), and FFmpegImportPlugin::Open().
Member Data Documentation
wxArrayString ImportPlugin::mExtensions [protected]
Referenced by GetSupportedExtensions(), PCMImportPlugin::PCMImportPlugin(), and SupportsExtension().
The documentation for this class was generated from the following file:
ImportPlugin.h