Audacity: ExportMixerDialog Class Reference
ExportMixerDialog Class Reference
Dialog for advanced mixing.
#include <Export.h>
Public Member Functions
ExportMixerDialog (TrackList *tracks, bool selectedOnly, int maxNumChannels, wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER)
virtual ~ExportMixerDialog ()
MixerSpec * GetMixerSpec ()
Private Member Functions
void OnOk (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void OnSlider (wxCommandEvent &event)
void OnSize (wxSizeEvent &event)
Private Attributes
wxStaticText * mChannelsText
MixerSpec * mMixerSpec
wxArrayString mTrackNames
Detailed Description
Dialog for advanced mixing.
Constructor & Destructor Documentation
ExportMixerDialog::ExportMixerDialog (TrackList * tracks, bool selectedOnly, int maxNumChannels, wxWindow * parent, wxWindowID id, const wxString & title, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER)
References channels, CreateStdButtonSizer(), eCancelButton, eOkButton, TrackListIterator::First(), ID_MIXERPANEL, label, Track::LeftChannel, TrackListIterator::Next(), Track::RightChannel, and Track::Wave.
ExportMixerDialog::~ExportMixerDialog () [virtual]
References mMixerSpec.
Member Function Documentation
MixerSpec* ExportMixerDialog::GetMixerSpec () [inline]
References mMixerSpec.
void ExportMixerDialog::OnCancel (wxCommandEvent & event) [private]
void ExportMixerDialog::OnOk (wxCommandEvent & event) [private]
void ExportMixerDialog::OnSize (wxSizeEvent & event) [private]
References ID_MIXERPANEL.
void ExportMixerDialog::OnSlider (wxCommandEvent & event) [private]
References channels, MixerSpec::GetNumChannels(), ID_MIXERPANEL, ID_SLIDER_CHANNEL, label, mChannelsText, mMixerSpec, and MixerSpec::SetNumChannels().
Member Data Documentation
wxStaticText* ExportMixerDialog::mChannelsText [private]
Referenced by OnSlider().
MixerSpec* ExportMixerDialog::mMixerSpec [private]
Referenced by GetMixerSpec(), OnSlider(), and ~ExportMixerDialog().
wxArrayString ExportMixerDialog::mTrackNames [private]
The documentation for this class was generated from the following files:
Export.h
Export.cpp