Audacity: MixerSpec Class Reference
MixerSpec Class Reference
Class used with Mixer.
#include <Mix.h>
Public Member Functions
MixerSpec (int numTracks, int maxNumChannels)
MixerSpec (const MixerSpec &mixerSpec)
virtual ~MixerSpec ()
bool SetNumChannels (int numChannels)
int GetNumChannels ()
int GetMaxNumChannels ()
int GetNumTracks ()
MixerSpec & operator= (const MixerSpec &mixerSpec)
Public Attributes
bool ** mMap
Private Member Functions
void Alloc ()
void Free ()
Private Attributes
int mNumTracks
int mNumChannels
int mMaxNumChannels
Detailed Description
Class used with Mixer.
Constructor & Destructor Documentation
MixerSpec::MixerSpec (int numTracks, int maxNumChannels)
References Alloc(), mMap, mMaxNumChannels, mNumChannels, and mNumTracks.
MixerSpec::MixerSpec (const MixerSpec & mixerSpec)
References Alloc(), mMap, mMaxNumChannels, mNumChannels, and mNumTracks.
MixerSpec::~MixerSpec () [virtual]
References Free().
Member Function Documentation
void MixerSpec::Alloc () [private]
References mMap, mMaxNumChannels, and mNumTracks.
Referenced by MixerSpec(), and operator=().
void MixerSpec::Free () [private]
References mMap, and mNumTracks.
Referenced by operator=(), and ~MixerSpec().
int MixerSpec::GetMaxNumChannels () [inline]
int MixerSpec::GetNumChannels () [inline]
Referenced by Exporter::CheckMix(), Mixer::Mixer(), ExportMixerPanel::OnMouseEvent(), ExportMixerPanel::OnPaint(), and ExportMixerDialog::OnSlider().
int MixerSpec::GetNumTracks () [inline]
Referenced by Mixer::Mixer(), ExportMixerPanel::OnMouseEvent(), and ExportMixerPanel::OnPaint().
MixerSpec & MixerSpec::operator= (const MixerSpec & mixerSpec)
References Alloc(), Free(), mMap, mMaxNumChannels, mNumChannels, and mNumTracks.
bool MixerSpec::SetNumChannels (int numChannels)
References mMap, mMaxNumChannels, mNumChannels, and mNumTracks.
Referenced by ExportMixerDialog::OnSlider().
Member Data Documentation
bool** MixerSpec::mMap
Referenced by Alloc(), Free(), MixerSpec(), ExportMixerPanel::OnMouseEvent(), ExportMixerPanel::OnPaint(), operator=(), Mixer::Process(), and SetNumChannels().
int MixerSpec::mMaxNumChannels [private]
Referenced by Alloc(), MixerSpec(), operator=(), and SetNumChannels().
int MixerSpec::mNumChannels [private]
Referenced by MixerSpec(), operator=(), and SetNumChannels().
int MixerSpec::mNumTracks [private]
Referenced by Alloc(), Free(), MixerSpec(), operator=(), and SetNumChannels().
The documentation for this class was generated from the following files:
Mix.h
Mix.cpp