Audacity: LabelDialog Class Reference
LabelDialog Class Reference
Dialog for editing labels.
#include <LabelDialog.h>
Public Member Functions
LabelDialog (wxWindow *parent, DirManager *dirmanager, TrackList *tracks, ViewInfo &viewinfo, double rate)
~LabelDialog ()
virtual bool Show (bool show=true)
Private Member Functions
bool TransferDataToWindow ()
bool TransferDataFromWindow ()
bool Validate ()
void FindAllLabels ()
void AddLabels (LabelTrack *t)
wxString TrackName (int &index, wxString dflt=_("Label Track"))
void OnUpdate (wxCommandEvent &event)
void OnInsert (wxCommandEvent &event)
void OnRemove (wxCommandEvent &event)
void OnImport (wxCommandEvent &event)
void OnExport (wxCommandEvent &event)
void OnSelectCell (wxGridEvent &event)
void OnCellChange (wxGridEvent &event)
void OnChangeTrack (wxGridEvent &event, int row, RowData *rd)
void OnChangeLabel (wxGridEvent &event, int row, RowData *rd)
void OnChangeStime (wxGridEvent &event, int row, RowData *rd)
void OnChangeEtime (wxGridEvent &event, int row, RowData *rd)
void OnOK (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
DECLARE_EVENT_TABLE ()
Private Attributes
Grid * mGrid
ChoiceEditor * mChoiceEditor
TimeEditor * mTimeEditor
RowDataArray mData
DirManager * mDirManager
TrackList * mTracks
ViewInfo * mViewInfo
wxArrayString mTrackNames
wxString mFormat
double mRate
int mInitialRow
Detailed Description
Dialog for editing labels.
Constructor & Destructor Documentation
LabelDialog::LabelDialog (wxWindow * parent, DirManager * dirmanager, TrackList * tracks, ViewInfo & viewinfo, double rate)
References Col_Etime, Col_Label, Col_Max, Col_Stime, Col_Track, CreateStdButtonSizer(), eCancelButton, eOkButton, GRID_VALUE_CHOICE, GRID_VALUE_TIME, and headers.
LabelDialog::~LabelDialog ()
References mData.
Member Function Documentation
void LabelDialog::AddLabels (LabelTrack * t) [private]
References RowData::etime, LabelTrack::GetLabel(), Track::GetName(), LabelTrack::GetNumLabels(), LabelTrack::getSelectedIndex(), RowData::index, mData, mInitialRow, RowData::stime, LabelStruct::t, LabelStruct::t1, LabelStruct::title, RowData::title, and TrackName().
Referenced by FindAllLabels(), and OnImport().
LabelDialog::DECLARE_EVENT_TABLE () [private]
void LabelDialog::FindAllLabels () [private]
References AddLabels(), TrackListIterator::First(), Track::GetKind(), Track::Label, mData, mInitialRow, mTracks, TrackListIterator::Next(), and OnInsert().
void LabelDialog::OnCancel (wxCommandEvent & event) [private]
References mGrid.
void LabelDialog::OnCellChange (wxGridEvent & event) [private]
References Col_Etime, Col_Label, Col_Stime, Col_Track, mData, OnChangeEtime(), OnChangeLabel(), OnChangeStime(), and OnChangeTrack().
void LabelDialog::OnChangeEtime (wxGridEvent & event, int row, RowData * rd) [private]
References Col_Etime, Col_Stime, RowData::etime, mGrid, and RowData::stime.
Referenced by OnCellChange().
void LabelDialog::OnChangeLabel (wxGridEvent & event, int row, RowData * rd) [private]
References Col_Label, mGrid, and RowData::title.
Referenced by OnCellChange().
void LabelDialog::OnChangeStime (wxGridEvent & event, int row, RowData * rd) [private]
References Col_Etime, Col_Stime, RowData::etime, mGrid, and RowData::stime.
Referenced by OnCellChange().
void LabelDialog::OnChangeTrack (wxGridEvent & event, int row, RowData * rd) [private]
References Col_Track, RowData::index, mGrid, mTrackNames, TrackName(), and TransferDataToWindow().
Referenced by OnCellChange().
void LabelDialog::OnExport (wxCommandEvent & event) [private]
References LabelTrack::AddLabel(), RowData::etime, LabelTrack::Export(), mData, mDirManager, RowData::stime, and RowData::title.
void LabelDialog::OnImport (wxCommandEvent & event) [private]
References AddLabels(), gPrefs, LabelTrack::Import(), mDirManager, and TransferDataToWindow().
void LabelDialog::OnInsert (wxCommandEvent & event) [private]
References Col_Label, Col_Track, RowData::etime, ID_INSERTA, RowData::index, mData, mGrid, mTrackNames, RowData::stime, RowData::title, and TransferDataToWindow().
Referenced by FindAllLabels().
void LabelDialog::OnOK (wxCommandEvent & event) [private]
References mGrid, TransferDataFromWindow(), and Validate().
void LabelDialog::OnRemove (wxCommandEvent & event) [private]
References mData, mGrid, and TransferDataToWindow().
void LabelDialog::OnSelectCell (wxGridEvent & event) [private]
References RowData::etime, TrackListIterator::First(), GetActiveProject(), mData, mTracks, mViewInfo, TrackListIterator::Next(), AudacityProject::RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, Track::SetSelected(), and RowData::stime.
void LabelDialog::OnUpdate (wxCommandEvent & event) [private]
References mFormat, and TransferDataToWindow().
bool LabelDialog::Show (bool show = true) [virtual]
References Col_Label, mGrid, and mInitialRow.
wxString LabelDialog::TrackName (int & index, wxString dflt = _("Label Track")) [private]
References mTrackNames.
Referenced by AddLabels(), OnChangeTrack(), and TransferDataToWindow().
bool LabelDialog::TransferDataFromWindow () [private]
References TrackList::Add(), LabelTrack::DeleteLabel(), RowData::etime, TrackListIterator::First(), Track::GetKind(), LabelTrack::GetNumLabels(), RowData::index, Track::Label, mData, mDirManager, mTrackNames, mTracks, name, TrackListIterator::Next(), Track::SetName(), RowData::stime, and RowData::title.
Referenced by OnOK().
bool LabelDialog::TransferDataToWindow () [private]
References Col_Etime, Col_Label, Col_Stime, Col_Track, RowData::etime, RowData::index, mChoiceEditor, mData, mFormat, mGrid, mRate, mTimeEditor, mTrackNames, ChoiceEditor::SetChoices(), TimeEditor::SetFormat(), TimeEditor::SetRate(), RowData::stime, RowData::title, and TrackName().
Referenced by OnChangeTrack(), OnImport(), OnInsert(), OnRemove(), and OnUpdate().
bool LabelDialog::Validate () [private]
References mData, and mGrid.
Referenced by OnOK().
Member Data Documentation
ChoiceEditor* LabelDialog::mChoiceEditor [private]
Referenced by TransferDataToWindow().
RowDataArray LabelDialog::mData [private]
Referenced by AddLabels(), FindAllLabels(), OnCellChange(), OnExport(), OnInsert(), OnRemove(), OnSelectCell(), TransferDataFromWindow(), TransferDataToWindow(), Validate(), and ~LabelDialog().
DirManager* LabelDialog::mDirManager [private]
Referenced by OnExport(), OnImport(), and TransferDataFromWindow().
wxString LabelDialog::mFormat [private]
Referenced by OnUpdate(), and TransferDataToWindow().
Grid* LabelDialog::mGrid [private]
Referenced by OnCancel(), OnChangeEtime(), OnChangeLabel(), OnChangeStime(), OnChangeTrack(), OnInsert(), OnOK(), OnRemove(), Show(), TransferDataToWindow(), and Validate().
int LabelDialog::mInitialRow [private]
Referenced by AddLabels(), FindAllLabels(), and Show().
double LabelDialog::mRate [private]
Referenced by TransferDataToWindow().
TimeEditor* LabelDialog::mTimeEditor [private]
Referenced by TransferDataToWindow().
wxArrayString LabelDialog::mTrackNames [private]
Referenced by OnChangeTrack(), OnInsert(), TrackName(), TransferDataFromWindow(), and TransferDataToWindow().
TrackList* LabelDialog::mTracks [private]
Referenced by FindAllLabels(), OnSelectCell(), and TransferDataFromWindow().
ViewInfo* LabelDialog::mViewInfo [private]
Referenced by OnSelectCell().
The documentation for this class was generated from the following files:
LabelDialog.h
LabelDialog.cpp