Audacity: AudioUnitDialog Class Reference
AudioUnitDialog Class Reference
A Dialog used with AudioUnitEffect.
Public Member Functions
AudioUnitDialog (wxWindow *parent, wxWindowID id, wxString title, AudioUnit unit, AudioUnitCarbonView carbonView, Effect *effect)
virtual ~AudioUnitDialog ()
void RemoveHandler ()
void OnOK (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void OnPreview (wxCommandEvent &event)
Private Attributes
AudioUnit mUnit
AudioUnitGUIControl * mGUIControl
wxBoxSizer * mMainSizer
Effect * mEffect
EventHandlerRef mHandlerRef
EventHandlerUPP mHandlerUPP
Detailed Description
A Dialog used with AudioUnitEffect.
Constructor & Destructor Documentation
AudioUnitDialog::AudioUnitDialog (wxWindow * parent, wxWindowID id, wxString title, AudioUnit unit, AudioUnitCarbonView carbonView, Effect * effect)
References EventHandler(), and EventListener().
AudioUnitDialog::~AudioUnitDialog () [virtual]
References RemoveHandler().
Member Function Documentation
void AudioUnitDialog::OnCancel (wxCommandEvent & event)
void AudioUnitDialog::OnOK (wxCommandEvent & event)
void AudioUnitDialog::OnPreview (wxCommandEvent & event)
References mEffect, and Effect::Preview().
void AudioUnitDialog::RemoveHandler ()
References mHandlerRef, and mHandlerUPP.
Referenced by EventHandler(), and ~AudioUnitDialog().
Member Data Documentation
Effect* AudioUnitDialog::mEffect [private]
Referenced by OnPreview().
AudioUnitGUIControl* AudioUnitDialog::mGUIControl [private]
EventHandlerRef AudioUnitDialog::mHandlerRef [private]
Referenced by RemoveHandler().
EventHandlerUPP AudioUnitDialog::mHandlerUPP [private]
Referenced by RemoveHandler().
wxBoxSizer* AudioUnitDialog::mMainSizer [private]
AudioUnit AudioUnitDialog::mUnit [private]
The documentation for this class was generated from the following file:
AudioUnitEffect.cpp