Audacity: AudacityProject Class Reference
AudacityProject Class Reference
AudacityProject provides the main window, with tools and tracks contained within it.
#include <Project.h>
Public Member Functions
AudacityProject (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size)
virtual ~AudacityProject ()
TrackList * GetTracks ()
UndoManager * GetUndoManager ()
sampleFormat GetDefaultFormat ()
double GetRate ()
double GetZoom ()
double GetSel0 ()
double GetSel1 ()
Track * GetFirstVisible ()
void UpdateFirstVisible ()
void GetPlayRegion (double *playRegionStart, double *playRegionEnd)
bool IsPlayRegionLocked ()
void SetSel0 (double)
void SetSel1 (double)
bool Clipboard ()
wxString GetName ()
DirManager * GetDirManager ()
TrackFactory * GetTrackFactory ()
AdornedRulerPanel * GetRulerPanel ()
Tags * GetTags ()
int GetAudioIOToken ()
void SetAudioIOToken (int token)
bool IsActive ()
void OpenFile (wxString fileName, bool addtohistory=true)
bool WarnOfLegacyFile ()
bool Import (wxString fileName, WaveTrackArray *pTrackArray=NULL)
void AddImportedTracks (wxString fileName, Track **newTracks, int numTracks)
bool Save (bool overwrite=true, bool fromSaveAs=false, bool bWantSaveCompressed=false)
bool SaveAs (bool bWantSaveCompressed=false)
bool SaveCompressedWaveTracks (const wxString strProjectPathName)
void Clear ()
wxString GetFileName ()
bool GetDirty ()
void SetProjectTitle ()
TrackPanel * GetTrackPanel ()
bool GetIsEmpty ()
bool GetTracksFitVerticallyZoomed ()
void SetTracksFitVerticallyZoomed (bool flag)
bool GetShowId3Dialog ()
void SetShowId3Dialog (bool flag)
bool GetCleanSpeechMode ()
void SetCleanSpeechMode (bool flag)
bool GetNormalizeOnLoad ()
void SetNormalizeOnLoad (bool flag)
void CommandManagerCallback (void *fptr)
void CommandManagerListCallback (void *fptr, int index)
void CreateMenusAndCommands ()
void CreateRecentFilesMenu (CommandManager *c)
void ModifyUndoMenus ()
void ModifyToolbarMenus ()
int GetFocusedFrame ()
wxUint32 GetUpdateFlags ()
double NearestZeroCrossing (double t0)
int DoAddLabel (double left, double right)
void SetTool (int tool)
void OnSelectTool ()
void OnZoomTool ()
void OnEnvelopeTool ()
void OnTimeShiftTool ()
void OnDrawTool ()
void OnMultiTool ()
void OnNextTool ()
void OnPrevTool ()
void OnStop ()
void OnPause ()
void OnRecord ()
void OnRecordAppend ()
void OnStopSelect ()
void OnSkipStart ()
void OnSkipEnd ()
void OnSeekLeftShort ()
void OnSeekRightShort ()
void OnSeekLeftLong ()
void OnSeekRightLong ()
bool MakeReadyToPlay ()
void OnPlayStop ()
void OnPlayStopSelect ()
void OnPlayOneSecond ()
void OnPlayToSelection ()
void OnPlayLooped ()
void OnPlayCutPreview ()
void OnTrackPan ()
void OnTrackPanLeft ()
void OnTrackPanRight ()
void OnTrackGain ()
void OnTrackGainInc ()
void OnTrackGainDec ()
void OnTrackMenu ()
void OnTrackMute ()
void OnTrackSolo ()
void OnTrackClose ()
void OnOutputGain ()
void OnInputGain ()
void OnInputSource ()
void OnOutputGainInc ()
void OnOutputGainDec ()
void OnInputGainInc ()
void OnInputGainDec ()
void OnPlayAtSpeed ()
void OnSetPlaySpeed ()
void OnPlaySpeedInc ()
void OnPlaySpeedDec ()
void OnCursorUp ()
void OnShiftUp ()
void OnCursorDown ()
void OnShiftDown ()
void OnToggle ()
void OnCursorLeft ()
void OnCursorRight ()
void OnSelExtendLeft ()
void OnSelExtendRight ()
void OnSelContractLeft ()
void OnSelContractRight ()
void OnCursorShortJumpLeft ()
void OnCursorShortJumpRight ()
void OnCursorLongJumpLeft ()
void OnCursorLongJumpRight ()
void OnSelSetExtendLeft ()
void OnSelSetExtendRight ()
void OnSetLeftSelection ()
void OnSetRightSelection ()
void OnSelToStart ()
void OnSelToEnd ()
void OnZeroCrossing ()
void OnLockPlayRegion ()
void OnUnlockPlayRegion ()
double GetTime (Track *t)
void OnSortTime ()
void OnSortName ()
void OnSnapToOn ()
void OnSnapToOff ()
void OnFullScreen ()
void OnNew ()
void OnOpen ()
void OnClose ()
void OnSave ()
void OnSaveAs ()
void OnSaveCompressed ()
void OnCheckDependencies ()
void OnExport ()
void OnExportSelection ()
void OnExportMultiple ()
void OnExportLabels ()
void OnExportMIDI ()
void OnUpload ()
void OnPreferences ()
void OnPageSetup ()
void OnPrint ()
void OnExit ()
void OnUndo ()
void OnRedo ()
void OnCut ()
void OnSplitCut ()
void OnCopy ()
void OnPaste ()
void OnPasteNewLabel ()
void OnPasteOver ()
void OnTrim ()
void OnDelete ()
void OnSplitDelete ()
void OnSilence ()
void OnSplit ()
void OnSplitNew ()
void OnSplitLabelsToTracks ()
void OnJoin ()
void OnDisjoin ()
void OnDuplicate ()
void OnCutLabels ()
void OnSplitCutLabels ()
void OnCopyLabels ()
void OnDeleteLabels ()
void OnSplitDeleteLabels ()
void OnSilenceLabels ()
void OnSplitLabels ()
void OnJoinLabels ()
void OnDisjoinLabels ()
void OnSelectAll ()
void OnSelectNone ()
void OnSelectCursorEnd ()
void OnSelectStartCursor ()
void OnZoomIn ()
void OnZoomOut ()
void OnZoomToggle ()
void OnZoomNormal ()
void OnZoomFit ()
void OnZoomFitV ()
void DoZoomFitV ()
void OnZoomSel ()
void OnExpandAllTracks ()
void OnCollapseAllTracks ()
void OnMuteAllTracks ()
void OnUnMuteAllTracks ()
void OnShowClipping ()
void OnHistory ()
void OnKaraoke ()
void OnMixerBoard ()
void OnPlotSpectrum ()
void OnContrast ()
void OnShowControlToolBar ()
void OnShowDeviceToolBar ()
void OnShowEditToolBar ()
void OnShowMeterToolBar ()
void OnShowMixerToolBar ()
void OnShowSelectionToolBar ()
void OnShowToolsToolBar ()
void OnShowTranscriptionToolBar ()
void OnResetToolBars ()
void OnSimplifiedView ()
void OnSoundActivated ()
void OnToggleSoundActivated ()
void OnTogglePlayRecording ()
void OnToggleSWPlaythrough ()
void OnImport ()
void OnImportLabels ()
void OnImportMIDI ()
void OnImportRaw ()
void OnEditMetadata ()
void OnMixAndRender ()
void OnMixAndRenderToNewTrack ()
void HandleMixAndRender (bool toNewTrack)
void OnSelectionSave ()
void OnSelectionRestore ()
void OnCursorTrackStart ()
void OnCursorTrackEnd ()
void OnCursorSelStart ()
void OnCursorSelEnd ()
void OnAlign (int index)
void OnAlignMoveSel (int index)
void HandleAlign (int index, bool moveSel)
void OnNewWaveTrack ()
void OnNewStereoTrack ()
void OnNewLabelTrack ()
void OnNewTimeTrack ()
void OnTimerRecord ()
void OnRemoveTracks ()
void OnStickyLabel ()
void OnAddLabel ()
void OnAddLabelPlaying ()
void OnEditLabels ()
bool OnEffect (int type, Effect *f, wxString params=wxEmptyString, bool saveState=true)
void OnEffect (int type, int index)
void OnGenerateEffect (int index)
void OnGeneratePlugin (int index)
void OnRepeatLastEffect (int index)
void OnProcessAny (int index)
void OnProcessEffect (int index)
void OnProcessPlugin (int index)
void OnAnalyzeEffect (int index)
void OnAnalyzePlugin (int index)
void OnApplyChain ()
void OnEditChains ()
void OnImportCleanSpeechPresets ()
void OnExportCleanSpeechPresets ()
void OnStereoToMono (int index)
wxString BuildCleanFileName (wxString fileName)
void OnAbout ()
void OnQuickHelp ()
void OnManual ()
void OnLog ()
void OnHelpWelcome ()
void OnBenchmark ()
void OnScreenshot ()
void OnAudioDeviceInfo ()
void OnSeparator ()
void PrevFrame ()
void NextFrame ()
void OnResample ()
CommandManager * GetCommandManager ()
void RebuildMenuBar ()
void RebuildOtherMenus ()
void MayStartMonitoring ()
void OnMenuEvent (wxMenuEvent &event)
void OnMenu (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
void OnActivate (wxActivateEvent &event)
void OnMouseEvent (wxMouseEvent &event)
void OnIconize (wxIconizeEvent &event)
void OnSize (wxSizeEvent &event)
void OnMove (wxMoveEvent &event)
void OnScroll (wxScrollEvent &event)
void OnCloseWindow (wxCloseEvent &event)
void OnTimer (wxTimerEvent &event)
void OnToolBarUpdate (wxCommandEvent &event)
void OnOpenAudioFile (wxCommandEvent &event)
void OnCaptureKeyboard (wxCommandEvent &event)
void OnReleaseKeyboard (wxCommandEvent &event)
void OnODTaskUpdate (wxCommandEvent &event)
Handles the redrawing necessary for tasks as they partially update in the background.
void OnODTaskComplete (wxCommandEvent &event)
void OnTrackListUpdated (wxCommandEvent &event)
bool HandleKeyDown (wxKeyEvent &event)
bool HandleChar (wxKeyEvent &event)
bool HandleKeyUp (wxKeyEvent &event)
void HandleResize ()
void UpdateLayout ()
void UpdateMenus ()
void UpdatePrefs ()
void UpdatePrefsVariables ()
void RedrawProject (const bool bForceWaveTracks=false)
void RefreshCursor ()
void SelectNone ()
void SelectAllIfNone ()
void Zoom (double level)
void Rewind (bool shift)
void SkipEnd (bool shift)
void SetStop (bool bStopped)
void EditByLabel (WaveTrack::EditFunction action, bool syncTracks)
void EditClipboardByLabel (WaveTrack::EditDestFunction action)
bool IsSticky ()
bool GetStickyFlag ()
void SetStickyFlag (bool flag)
void HandleTrackMute (Track *t, const bool exclusive)
void HandleTrackSolo (Track *t, const bool alternate)
void SetSnapTo (bool state)
bool GetSnapTo ()
void OnScrollLeft ()
void OnScrollRight ()
void OnScrollLeftButton (wxScrollEvent &event)
void OnScrollRightButton (wxScrollEvent &event)
void FinishAutoScroll ()
void FixScrollbars ()
void SafeDisplayStatusMessage (const wxChar *msg)
virtual wxSize GetTPTracksUsableArea ()
virtual void RefreshTPTrack (Track *pTrk, bool refreshbacking=true)
virtual void TP_DisplaySelection ()
virtual void TP_DisplayStatusMessage (wxString msg)
virtual int TP_GetCurrentTool ()
virtual ToolsToolBar * TP_GetToolsToolBar ()
virtual ControlToolBar * TP_GetControlToolBar ()
virtual void TP_OnPlayKey ()
virtual void TP_PushState (wxString longDesc, wxString shortDesc, bool consolidate)
virtual void TP_ModifyState ()
virtual void TP_RedrawScrollbars ()
virtual void TP_ScrollLeft ()
virtual void TP_ScrollRight ()
virtual void TP_ScrollWindow (double scrollto)
virtual void TP_ScrollUpDown (int delta)
virtual void TP_HandleResize ()
ControlToolBar * GetControlToolBar ()
DeviceToolBar * GetDeviceToolBar ()
EditToolBar * GetEditToolBar ()
MeterToolBar * GetMeterToolBar ()
MixerToolBar * GetMixerToolBar ()
SelectionBar * GetSelectionBar ()
ToolsToolBar * GetToolsToolBar ()
TranscriptionToolBar * GetTranscriptionToolBar ()
LyricsWindow * GetLyricsWindow ()
MixerBoard * GetMixerBoard ()
virtual void AS_SetRate (double rate)
virtual void AS_ModifySelection (double &start, double &end)
virtual void AS_SetSnapTo (bool state)
virtual bool AS_GetSnapTo ()
void SetStateTo (unsigned int n)
virtual bool HandleXMLTag (const wxChar *tag, const wxChar **attrs)
virtual XMLTagHandler * HandleXMLChild (const wxChar *tag)
virtual void WriteXML (XMLWriter &xmlFile)
void WriteXMLHeader (XMLWriter &xmlFile)
wxWindow * HasKeyboardCapture ()
void CaptureKeyboard (wxWindow *h)
void ReleaseKeyboard (wxWindow *h)
virtual void OnAudioIORate (int rate)
virtual void OnAudioIOStartRecording ()
virtual void OnAudioIOStopRecording ()
virtual void OnAudioIONewBlockFiles (const wxString &blockFileLog)
bool TryToMakeActionAllowed (wxUint32 &flags, wxUint32 flagsRqd, wxUint32 mask)
void PushState (wxString desc, wxString shortDesc, bool consolidate=false)
bool IsSoloSimple ()
bool IsSoloNone ()
void SetNormalizedWindowState (wxRect pSizeAndLocation)
wxRect GetNormalizedWindowState () const
bool IsTimerRecordCancelled ()
void ResetTimerRecordFlag ()
Static Public Member Functions
static wxArrayString ShowOpenDialog (wxString extraformat=wxEmptyString, wxString extrafilter=wxEmptyString)
Show an open dialogue for opening audio files, and possibly other sorts of files.
static void OpenFiles (AudacityProject *proj)
static void DeleteClipboard ()
static void DeleteAllProjectsDeleteLock ()
static void AllProjectsDeleteLock ()
Prevents delete from external thread - for e.g. use of GetActiveProject.
static void AllProjectsDeleteUnlock ()
Reallows deletion of projects from outside threads.
Public Attributes
double mSel0save
double mSel1save
PlayMode mLastPlayMode
ViewInfo mViewInfo
ToolManager * mToolManager
bool mShowSplashScreen
wxString mHelpPref
wxString mSoloPref
Private Member Functions
void ClearClipboard ()
void InitialState ()
void ModifyState ()
void PopState (TrackList *l)
void UpdateLyrics ()
void UpdateMixerBoard ()
void GetRegionsByLabel (Regions &regions)
void AutoSaveIfNeeded ()
void AutoSave ()
void DeleteCurrentAutoSaveFile ()
Static Private Member Functions
static bool IsAutoSaveEnabled ()
static bool GetCacheBlockFiles ()
Private Attributes
wxString mFileName
DirManager * mDirManager
double mRate
sampleFormat mDefaultFormat
wxMenu * mRecentFilesMenu
Tags * mTags
TrackList * mTracks
bool mSnapTo
TrackList * mLastSavedTracks
UndoManager mUndoManager
bool mDirty
CommandManager mCommandManager
wxUint32 mLastFlags
wxTimer * mTimer
long mLastStatusUpdateTime
wxStatusBar * mStatusBar
AdornedRulerPanel * mRuler
TrackPanel * mTrackPanel
TrackFactory * mTrackFactory
wxPanel * mMainPanel
wxScrollBar * mHsbar
wxScrollBar * mVsbar
bool mAutoScrolling
bool mActive
bool mIconized
HistoryWindow * mHistoryWindow
LyricsWindow * mLyricsWindow
MixerBoard * mMixerBoard
MixerBoardFrame * mMixerBoardFrame
FreqWindow * mFreqWindow
int mAudioIOToken
bool mIsDeleting
bool mTracksFitVerticallyZoomed
bool mNormalizeOnLoad
bool mCleanSpeechMode
bool mShowId3Dialog
bool mEmptyCanBeDirty
bool mSelectAllOnNone
bool mStickyFlag
bool mLockPlayRegion
wxWindow * mLastFocusedWindow
wxWindow * mKeyboardCaptured
ImportXMLTagHandler * mImportXMLTagHandler
wxString mAutoSaveFileName
long mLastAutoSaveTime
bool mAutoSaving
bool mIsRecovered
wxString mRecoveryAutoSaveDataDir
RecordingRecoveryHandler * mRecordingRecoveryHandler
bool mImportedDependencies
bool mWantSaveCompressed
wxArrayString mStrOtherNamesArray
Effect * mLastEffect
int mLastEffectType
wxRect mNormalizedWindowState
bool mTimerRecordCanceled
Static Private Attributes
static TrackList * msClipboard = new TrackList()
static AudacityProject * msClipProject = NULL
static double msClipLen = 0.0
static ODLock * msAllProjectDeleteMutex = new ODLock()
Friends
class ScreenshotCommand
Detailed Description
AudacityProject provides the main window, with tools and tracks contained within it.
In Audacity, the main window you work in is called a project. AudacityProjects can contain an arbitrary number of tracks of many different types, but if a project contains just one or two tracks then it can be saved in standard formats like WAV or AIFF. This window is the one that contains the menu bar (except on the Mac).
Attention:
The menu functions for AudacityProject, those for creating the menu bars and acting on clicks, are found in file Menus.cpp
Constructor & Destructor Documentation
AudacityProject::AudacityProject (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size)
References AUDACITY_VERSION_STRING, ThemeBase::Bitmap(), CreateMenusAndCommands(), AdornedRulerPanel::GetRulerHeight(), OnTrackListUpdated(), MixerToolBar::RecreateTipWindows(), theTheme, and TrackPanelID.
AudacityProject::~AudacityProject () [virtual]
References AudacityApp::GetRecentFiles(), mRecentFilesMenu, FileHistory::RemoveMenu(), and wxGetApp().
Member Function Documentation
void AudacityProject::AddImportedTracks (wxString fileName, Track ** newTracks, int numTracks)
References TrackList::Add(), TrackPanel::EnsureVisible(), SeqBlock::f, Sequence::GetBlockArray(), TrackPanel::GetFirstSelectedTrack(), DirManager::GetProjectName(), GetSelectionBar(), WaveClip::GetSequence(), BlockFile::IsAlias(), TrackList::IsEmpty(), mDirManager, mFileName, mImportedDependencies, mRate, mTrackPanel, mTracks, OnZoomFit(), PushState(), TrackPanel::Refresh(), SelectNone(), Track::SetName(), SetProjectTitle(), SelectionBar::SetRate(), Track::SetSelected(), and Track::Wave.
Referenced by Import(), and OnImportRaw().
void AudacityProject::AllProjectsDeleteLock () [static]
Prevents delete from external thread - for e.g. use of GetActiveProject.
Prevents deletion of projects from outside threads.
References msAllProjectDeleteMutex.
Referenced by ODTask::DoSome(), OnCloseWindow(), and ODManager::Start().
void AudacityProject::AllProjectsDeleteUnlock () [static]
Reallows deletion of projects from outside threads.
References msAllProjectDeleteMutex.
Referenced by ODTask::DoSome(), OnCloseWindow(), and ODManager::Start().
bool AudacityProject::AS_GetSnapTo () [virtual]
Implements SelectionBarListener.
References GetSnapTo().
void AudacityProject::AS_ModifySelection (double & start, double & end) [virtual]
Implements SelectionBarListener.
References ModifyState(), mTrackPanel, mViewInfo, TrackPanel::Refresh(), ViewInfo::sel0, and ViewInfo::sel1.
void AudacityProject::AS_SetRate (double rate) [virtual]
Implements SelectionBarListener.
References mRate.
void AudacityProject::AS_SetSnapTo (bool state) [virtual]
Implements SelectionBarListener.
References RedrawProject(), and SetSnapTo().
void AudacityProject::AutoSave () [private]
References FileNames::AutoSaveDir(), XMLFileWriter::CloseWithoutEndingTags(), CreateUniqueName(), DeleteCurrentAutoSaveFile(), XMLFileWriterException::GetMessage(), mAutoSaveFileName, mAutoSaving, mFileName, mLastAutoSaveTime, XMLFileWriter::Open(), WriteXML(), and WriteXMLHeader().
Referenced by AutoSaveIfNeeded(), OnAudioIOStartRecording(), OnAudioIOStopRecording(), and OpenFile().
void AudacityProject::AutoSaveIfNeeded () [private]
References AutoSave(), gPrefs, IsAutoSaveEnabled(), mAutoSaveFileName, and mLastAutoSaveTime.
Referenced by PushState().
wxString AudacityProject::BuildCleanFileName (wxString fileName)
References AudacityApp::AddFileToHistory(), gPrefs, and wxGetApp().
Referenced by BatchCommands::ApplySpecialCommand().
void AudacityProject::CaptureKeyboard (wxWindow * h)
References mKeyboardCaptured.
Referenced by OnCaptureKeyboard().
void AudacityProject::Clear ()
References Track::Clear(), TrackListIterator::First(), Track::GetKind(), Track::GetSelected(), IsSticky(), Track::IsSynchroSelected(), Track::Label, mTracks, mViewInfo, TrackListIterator::Next(), PushState(), RedrawProject(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by OnDelete().
void AudacityProject::ClearClipboard () [private]
References TrackList::Clear(), msClipboard, msClipLen, and msClipProject.
Referenced by EditClipboardByLabel(), OnCopy(), OnCut(), and OnSplitCut().
bool AudacityProject::Clipboard () [inline]
Referenced by EditToolBar::EnableDisableButtons().
void AudacityProject::CommandManagerCallback (void * fptr)
void AudacityProject::CommandManagerListCallback (void * fptr, int index)
void AudacityProject::CreateMenusAndCommands ()
CreateMenusAndCommands builds the menus, and also rebuilds them after changes in configured preferences - for example changes in key-bindings affect the short-cut key legend that appears beside each command, and changes in 'CleanSpeech Mode' customise the menus to a restricted subset
References CommandManager::AddCheck(), CommandManager::AddCommand(), CommandManager::AddItem(), CommandManager::AddItemList(), CommandManager::AddMenuBar(), CommandManager::AddSeparator(), ADVANCED_EFFECT, AlwaysEnabledFlag, ANALYZE_EFFECT, AudioIOBusyFlag, AudioIONotBusyFlag, CommandManager::BeginMenu(), CommandManager::BeginSubMenu(), BUILTIN_EFFECT, ClipboardFlag, CreateRecentFilesMenu(), CutCopyAvailableFlag, CommandManager::EndMenu(), CommandManager::EndSubMenu(), FN, FNI, EffectManager::Get(), Effect::GetEffectName(), EffectCategory::GetEffects(), EffectManager::GetEffects(), EffectCategory::GetSubCategories(), gPrefs, HasLastEffectFlag, INSERT_EFFECT, LabelsSelectedFlag, LabelTracksExistFlag, LinkingDisabledFlag, CommandManager::mbHideFlaggedItems, mCleanSpeechMode, mCommandManager, mLastEffect, mLastEffectType, mLastFlags, ModifyUndoMenus(), mSel0save, mSel1save, names, NextFrame(), NoteTracksSelectedFlag, OnAbout(), OnAddLabel(), OnAddLabelPlaying(), OnAlign(), OnAlignMoveSel(), OnAnalyzeEffect(), OnAnalyzePlugin(), OnApplyChain(), OnAudioDeviceInfo(), OnBenchmark(), OnCheckDependencies(), OnClose(), OnCollapseAllTracks(), OnContrast(), OnCopy(), OnCopyLabels(), OnCursorDown(), OnCursorLeft(), OnCursorLongJumpLeft(), OnCursorLongJumpRight(), OnCursorRight(), OnCursorSelEnd(), OnCursorSelStart(), OnCursorShortJumpLeft(), OnCursorShortJumpRight(), OnCursorTrackEnd(), OnCursorTrackStart(), OnCursorUp(), OnCut(), OnCutLabels(), OnDelete(), OnDeleteLabels(), OnDisjoin(), OnDisjoinLabels(), OnDrawTool(), OnDuplicate(), OnEditChains(), OnEditLabels(), OnEditMetadata(), OnEnvelopeTool(), OnExit(), OnExpandAllTracks(), OnExport(), OnExportCleanSpeechPresets(), OnExportLabels(), OnExportMIDI(), OnExportMultiple(), OnExportSelection(), OnFullScreen(), OnGenerateEffect(), OnGeneratePlugin(), OnHistory(), OnImport(), OnImportCleanSpeechPresets(), OnImportLabels(), OnImportMIDI(), OnImportRaw(), OnInputGain(), OnInputGainDec(), OnInputGainInc(), OnInputSource(), OnJoin(), OnJoinLabels(), OnKaraoke(), OnLockPlayRegion(), OnLog(), OnManual(), OnMixAndRender(), OnMixAndRenderToNewTrack(), OnMixerBoard(), OnMultiTool(), OnMuteAllTracks(), OnNew(), OnNewLabelTrack(), OnNewStereoTrack(), OnNewTimeTrack(), OnNewWaveTrack(), OnNextTool(), OnOpen(), OnOutputGain(), OnOutputGainDec(), OnOutputGainInc(), OnPageSetup(), OnPaste(), OnPasteNewLabel(), OnPause(), OnPlayAtSpeed(), OnPlayCutPreview(), OnPlayLooped(), OnPlayOneSecond(), OnPlaySpeedDec(), OnPlaySpeedInc(), OnPlayStop(), OnPlayStopSelect(), OnPlayToSelection(), OnPlotSpectrum(), OnPreferences(), OnPrevTool(), OnPrint(), OnProcessAny(), OnProcessEffect(), OnProcessPlugin(), OnQuickHelp(), OnRecord(), OnRecordAppend(), OnRedo(), OnRemoveTracks(), OnRepeatLastEffect(), OnResample(), OnResetToolBars(), OnSave(), OnSaveAs(), OnSaveCompressed(), OnScreenshot(), OnSeekLeftLong(), OnSeekLeftShort(), OnSeekRightLong(), OnSeekRightShort(), OnSelContractLeft(), OnSelContractRight(), OnSelectAll(), OnSelectCursorEnd(), OnSelectionRestore(), OnSelectionSave(), OnSelectNone(), OnSelectStartCursor(), OnSelectTool(), OnSelExtendLeft(), OnSelExtendRight(), OnSelSetExtendLeft(), OnSelSetExtendRight(), OnSelToEnd(), OnSelToStart(), OnSetLeftSelection(), OnSetPlaySpeed(), OnSetRightSelection(), OnShiftDown(), OnShiftUp(), OnShowClipping(), OnShowControlToolBar(), OnShowDeviceToolBar(), OnShowEditToolBar(), OnShowMeterToolBar(), OnShowMixerToolBar(), OnShowSelectionToolBar(), OnShowToolsToolBar(), OnShowTranscriptionToolBar(), OnSilence(), OnSilenceLabels(), OnSimplifiedView(), OnSkipEnd(), OnSkipStart(), OnSnapToOff(), OnSnapToOn(), OnSortName(), OnSortTime(), OnSoundActivated(), OnSplit(), OnSplitCut(), OnSplitCutLabels(), OnSplitDelete(), OnSplitDeleteLabels(), OnSplitLabels(), OnSplitNew(), OnStereoToMono(), OnStickyLabel(), OnStop(), OnTimerRecord(), OnTimeShiftTool(), OnToggle(), OnTogglePlayRecording(), OnToggleSoundActivated(), OnToggleSWPlaythrough(), OnTrackClose(), OnTrackGain(), OnTrackGainDec(), OnTrackGainInc(), OnTrackMenu(), OnTrackMute(), OnTrackPan(), OnTrackPanLeft(), OnTrackPanRight(), OnTrackSolo(), OnTrim(), OnUndo(), OnUnlockPlayRegion(), OnUnMuteAllTracks(), OnUpload(), OnZeroCrossing(), OnZoomFit(), OnZoomFitV(), OnZoomIn(), OnZoomNormal(), OnZoomOut(), OnZoomSel(), OnZoomTool(), PlayRegionLockedFlag, PlayRegionNotLockedFlag, PLUGIN_EFFECT, PrevFrame(), PROCESS_EFFECT, RedoAvailableFlag, CommandManager::SetCommandFlags(), CommandManager::SetDefaultFlags(), StereoRequiredFlag, TimeSelectedFlag, TrackPanelHasFocus, TracksExistFlag, TracksSelectedFlag, UndoAvailableFlag, UnsavedChangesFlag, WaveTracksExistFlag, WaveTracksSelectedFlag, wxGetApp(), ZoomInAvailableFlag, and ZoomOutAvailableFlag.
Referenced by RebuildMenuBar().
void AudacityProject::CreateRecentFilesMenu (CommandManager * c)
References FileHistory::AddFilesToMenu(), CommandManager::BeginSubMenu(), CommandManager::EndSubMenu(), AudacityApp::GetRecentFiles(), mRecentFilesMenu, FileHistory::UseMenu(), and wxGetApp().
Referenced by CreateMenusAndCommands().
void AudacityProject::DeleteAllProjectsDeleteLock () [static]
References msAllProjectDeleteMutex.
Referenced by QuitAudacity().
void AudacityProject::DeleteClipboard () [static]
References TrackList::Clear(), and msClipboard.
Referenced by OnCloseWindow(), and QuitAudacity().
void AudacityProject::DeleteCurrentAutoSaveFile () [private]
References mAutoSaveFileName.
Referenced by AutoSave(), OnCloseWindow(), and Save().
int AudacityProject::DoAddLabel (double left, double right)
References TrackList::Add(), LabelTrack::AddLabel(), TrackPanel::EnsureVisible(), TrackListIterator::First(), Track::GetKind(), Track::GetSelected(), IsSticky(), Track::Label, mDirManager, mTrackPanel, mTracks, TrackListIterator::Next(), PushState(), RedrawProject(), and Track::SetSelected().
Referenced by OnAddLabel(), OnAddLabelPlaying(), TranscriptionToolBar::OnAutomateSelection(), and TranscriptionToolBar::OnMakeLabel().
void AudacityProject::DoZoomFitV ()
References TrackListIterator::First(), Track::GetHeight(), Track::GetKind(), TrackPanel::GetTracksUsableArea(), mTrackPanel, mTracks, TrackListIterator::Next(), Track::SetHeight(), and Track::Wave.
Referenced by OnZoomFitV(), and PushState().
void AudacityProject::EditByLabel (WaveTrack::EditFunction action, bool syncTracks)
References TrackListIterator::First(), Track::GetKind(), GetRegionsByLabel(), Track::GetSelected(), Track::IsSynchroSelected(), mTracks, TrackListIterator::Next(), and Track::Wave.
Referenced by OnCutLabels(), OnDeleteLabels(), OnDisjoinLabels(), OnJoinLabels(), OnSilenceLabels(), OnSplitDeleteLabels(), and OnSplitLabels().
void AudacityProject::EditClipboardByLabel (WaveTrack::EditDestFunction action)
References TrackList::Add(), ClearClipboard(), TrackListIterator::First(), Track::GetChannel(), Track::GetKind(), Track::GetLinked(), Track::GetName(), GetRegionsByLabel(), Track::GetSelected(), msClipboard, msClipLen, mTracks, TrackListIterator::Next(), Track::Offset(), WaveTrack::Paste(), Track::SetChannel(), Track::SetLinked(), Track::SetName(), and Track::Wave.
Referenced by OnCopyLabels(), OnCutLabels(), and OnSplitCutLabels().
void AudacityProject::FinishAutoScroll ()
References mAutoScrolling, and OnScroll().
Referenced by OnResample(), OnScrollLeft(), and OnScrollRight().
void AudacityProject::FixScrollbars ()
References TrackList::GetEndTime(), TrackList::GetHeight(), TrackPanel::GetTracksUsableArea(), ViewInfo::h, ViewInfo::lastZoom, mHsbar, mTrackPanel, mTracks, mViewInfo, mVsbar, TrackPanel::Refresh(), ViewInfo::sbarH, ViewInfo::sbarScale, ViewInfo::sbarScreen, ViewInfo::sbarTotal, ViewInfo::screen, ViewInfo::scrollStep, ViewInfo::total, UpdateFirstVisible(), UpdateLayout(), UpdateMenus(), ViewInfo::vpos, and ViewInfo::zoom.
Referenced by HandleResize(), OnCloseWindow(), RedrawProject(), TP_RedrawScrollbars(), and Zoom().
int AudacityProject::GetAudioIOToken ()
References mAudioIOToken.
Referenced by LabelTrack::CaptureKey(), TrackPanel::DoDrawIndicator(), GetUpdateFlags(), TrackPanel::HandleClosing(), TrackPanel::HandleLabelClick(), TrackPanel::HandleTrackSpecificMouseEvent(), TrackPanel::IsUnsafe(), MakeReadyToPlay(), OnAddLabelPlaying(), TrackPanel::OnBoundaryMove(), OnCloseWindow(), TrackPanel::OnCursorLeft(), TrackPanel::OnCursorMove(), TrackPanel::OnCursorRight(), TrackPanel::OnPaint(), OnPlayStop(), OnPlayStopSelect(), OnSetLeftSelection(), OnSetRightSelection(), TrackPanel::OnTimer(), OnZoomIn(), and PushState().
bool AudacityProject::GetCacheBlockFiles () [static, private]
References gPrefs.
Referenced by OnAudioIONewBlockFiles(), and OnAudioIOStartRecording().
bool AudacityProject::GetCleanSpeechMode () [inline]
Referenced by BatchProcessDialog::BatchProcessDialog(), EffectNoiseRemoval::CleanSpeechMayWriteNoiseGate(), BatchCommands::GetAllCommands(), BatchProcessDialog::OnApplyToFiles(), ControlToolBar::OnRecord(), NoiseRemovalDialog::PopulateOrExchange(), and EffectNoiseRemoval::PromptUser().
CommandManager* AudacityProject::GetCommandManager () [inline]
Referenced by GetAllMenuCommands::Apply(), ExecMenuCommand::Apply(), LabelTrack::CaptureKey(), and KeyConfigPrefs::Populate().
ControlToolBar * AudacityProject::GetControlToolBar ()
References ControlBarID, ToolManager::GetToolBar(), and mToolManager.
Referenced by Theme::ApplyUpdatedImages(), audacityAudioCallback(), MakeReadyToPlay(), OnCloseWindow(), AdornedRulerPanel::OnMouseEvents(), OnPause(), OnPlayCutPreview(), OnPlayLooped(), OnPlayOneSecond(), TranscriptionToolBar::OnPlaySpeed(), OnPlayStop(), OnPlayStopSelect(), OnPlayToSelection(), OnRecord(), OnRecordAppend(), OnSkipEnd(), OnSkipStart(), OnStop(), OnStopSelect(), TrackPanel::OnTimer(), TrackPanel::SelectionHandleClick(), and TP_GetControlToolBar().
sampleFormat AudacityProject::GetDefaultFormat () [inline]
Referenced by FindDependencies(), RemoveDependencies(), and WaveTrack::WaveTrack().
DeviceToolBar * AudacityProject::GetDeviceToolBar ()
References DeviceBarID, ToolManager::GetToolBar(), and mToolManager.
DirManager * AudacityProject::GetDirManager ()
References mDirManager.
Referenced by Exporter::CheckFilename(), ExportMultiple::DoExport(), ImportXMLTagHandler::HandleXMLTag(), RecordingRecoveryHandler::HandleXMLTag(), Import(), LOFImportFileHandle::lofOpenFiles(), TranscriptionToolBar::OnPlaySpeed(), OpenFile(), RemoveDependencies(), and ReplaceBlockFiles().
bool AudacityProject::GetDirty () [inline]
Referenced by AudacityApp::MRUOpen().
EditToolBar * AudacityProject::GetEditToolBar ()
References EditBarID, ToolManager::GetToolBar(), and mToolManager.
Referenced by OnStickyLabel().
wxString AudacityProject::GetFileName () [inline]
Referenced by GetProjectInfoCommand::Apply(), BatchCommands::ApplySpecialCommand(), and ContrastDialog::OnExport().
Track * AudacityProject::GetFirstVisible ()
References TrackListIterator::First(), mTracks, mViewInfo, TrackListIterator::Next(), ViewInfo::track, and ViewInfo::vpos.
int AudacityProject::GetFocusedFrame ()
References BotDockHasFocus, ToolManager::GetBotDock(), ToolManager::GetTopDock(), mToolManager, mTrackPanel, TopDockHasFocus, and TrackPanelHasFocus.
Referenced by GetUpdateFlags(), NextFrame(), and PrevFrame().
bool AudacityProject::GetIsEmpty () [inline]
Referenced by AudacityApp::MRUOpen(), and BatchProcessDialog::OnApplyToFiles().
LyricsWindow* AudacityProject::GetLyricsWindow () [inline]
Referenced by TrackPanel::HandleSelect(), and TrackPanel::OnTimer().
MeterToolBar * AudacityProject::GetMeterToolBar ()
References ToolManager::GetToolBar(), MeterBarID, and mToolManager.
Referenced by MayStartMonitoring(), ControlToolBar::SetVUMeters(), Meter::StartMonitoring(), and ControlToolBar::StopPlaying().
MixerBoard* AudacityProject::GetMixerBoard () [inline]
Referenced by TrackPanel::GetMixerBoard().
MixerToolBar * AudacityProject::GetMixerToolBar ()
References ToolManager::GetToolBar(), MixerBarID, and mToolManager.
Referenced by OnInputGain(), OnInputGainDec(), OnInputGainInc(), OnInputSource(), OnOutputGain(), OnOutputGainDec(), OnOutputGainInc(), and OnTimer().
wxString AudacityProject::GetName ()
References mFileName.
Referenced by Exporter::GetFilename(), OnPrint(), ExportMultiple::PopulateOrExchange(), SaveAs(), and SetProjectTitle().
wxRect AudacityProject::GetNormalizedWindowState () const [inline]
Referenced by SaveWindowSize().
bool AudacityProject::GetNormalizeOnLoad () [inline]
void AudacityProject::GetPlayRegion (double * playRegionStart, double * playRegionEnd)
References AdornedRulerPanel::GetPlayRegion(), and mRuler.
Referenced by TranscriptionToolBar::OnPlaySpeed(), and ControlToolBar::PlayCurrentRegion().
double AudacityProject::GetRate () [inline]
Referenced by ContrastDialog::ContrastDialog(), EffectEqualization::DontPromptUser(), ExportPCM::Export(), ExportOGG::Export(), ExportMP3::Export(), ExportMP2::Export(), ExportFLAC::Export(), ExportCL::Export(), ExportFFmpeg::InitCodecs(), NearestZeroCrossing(), OnPaste(), ControlToolBar::OnRecord(), OnTimer(), ControlToolBar::PlayPlayRegion(), EffectEqualization::PromptUser(), SnapManager::Snap(), SnapManager::SnapManager(), Meter::StartMonitoring(), and WaveTrack::WaveTrack().
void AudacityProject::GetRegionsByLabel (Regions & regions) [private]
References REGION::cmp(), REGION::end, TrackListIterator::First(), Track::GetKind(), LabelTrack::GetLabel(), LabelTrack::GetNumLabels(), Track::GetSelected(), Track::Label, mTracks, mViewInfo, TrackListIterator::Next(), ViewInfo::sel0, ViewInfo::sel1, REGION::start, LabelStruct::t, and LabelStruct::t1.
Referenced by EditByLabel(), and EditClipboardByLabel().
AdornedRulerPanel * AudacityProject::GetRulerPanel ()
References mRuler.
double AudacityProject::GetSel0 () [inline]
Referenced by TranscriptionToolBar::EnableDisableButtons(), EditToolBar::EnableDisableButtons(), TranscriptionToolBar::GetSamples(), TrackPanel::HandleSelect(), MixerTrackCluster::HandleSelect(), TranscriptionToolBar::OnMakeLabel(), ControlToolBar::OnRecord(), TrackPanel::OnTimer(), Lyrics::Update(), and UpdateLyrics().
double AudacityProject::GetSel1 () [inline]
Referenced by TranscriptionToolBar::EnableDisableButtons(), EditToolBar::EnableDisableButtons(), TranscriptionToolBar::GetSamples(), MixerTrackCluster::HandleSelect(), TranscriptionToolBar::OnMakeLabel(), and ControlToolBar::OnRecord().
SelectionBar * AudacityProject::GetSelectionBar ()
References ToolManager::GetToolBar(), mToolManager, and SelectionBarID.
Referenced by AddImportedTracks(), HandleXMLTag(), SetSnapTo(), and TP_DisplaySelection().
bool AudacityProject::GetShowId3Dialog () [inline]
Referenced by BatchCommands::ApplyCommandInBatchMode(), ExportMultiple::ExportMultipleByLabel(), ExportMultiple::ExportMultipleByTrack(), and Exporter::Process().
bool AudacityProject::GetSnapTo ()
Referenced by AS_GetSnapTo().
bool AudacityProject::GetStickyFlag () [inline]
Referenced by EditToolBar::EnableDisableButtons(), IsSticky(), EditToolBar::OnButton(), and OnStickyLabel().
Tags * AudacityProject::GetTags ()
References mTags.
Referenced by ExportPCM::Export(), ExportMP3::Export(), ExportMP2::Export(), ExportMultiple::ExportMultipleByLabel(), ExportMultiple::ExportMultipleByTrack(), ExportOGG::FillComment(), ExportFLAC::GetMetadata(), ExportFFmpeg::Init(), and Exporter::Process().
double AudacityProject::GetTime (Track * t)
References WaveTrack::GetClipByIndex(), WaveTrack::GetEndTime(), Track::GetKind(), WaveTrack::GetNumClips(), WaveClip::GetNumSamples(), LabelTrack::GetStartTime(), WaveClip::GetStartTime(), Track::Label, and Track::Wave.
Referenced by OnSortTime().
ToolsToolBar * AudacityProject::GetToolsToolBar ()
References ToolManager::GetToolBar(), mToolManager, and ToolsBarID.
Referenced by OnNextTool(), OnPrevTool(), SetTool(), TP_GetCurrentTool(), and TP_GetToolsToolBar().
wxSize AudacityProject::GetTPTracksUsableArea () [virtual]
References TrackPanel::GetTracksUsableArea(), and mTrackPanel.
Referenced by VisibleTrackIterator::VisibleTrackIterator().
TrackFactory * AudacityProject::GetTrackFactory ()
References mTrackFactory.
Referenced by ControlToolBar::OnRecord(), EffectStereoToMono::Process(), EffectEqualization::ProcessOne(), and WaveTrack::SyncAdjust().
TrackPanel* AudacityProject::GetTrackPanel () [inline]
Referenced by GetTrackInfoCommand::Apply(), EditToolBar::OnButton(), and GetProjectInfoCommand::SendFocusedTrackIndex().
TrackList* AudacityProject::GetTracks () [inline]
Referenced by SetTrackInfoCommand::Apply(), SetProjectInfoCommand::Apply(), SelectCommand::Apply(), ScreenshotCommand::Apply(), ExportCommand::Apply(), GetTrackInfoCommand::Apply(), GetProjectInfoCommand::Apply(), Exporter::CheckMix(), CountNumTracks(), LOFImportFileHandle::doDuration(), TranscriptionToolBar::EnableDisableButtons(), EditToolBar::EnableDisableButtons(), ControlToolBar::EnableDisableButtons(), Exporter::ExamineTracks(), ExportPCM::Export(), ExportOGG::Export(), ExportMP3::Export(), ExportMP2::Export(), ExportFLAC::Export(), ExportFFmpeg::Export(), ExportCL::Export(), GetAllSeqBlocks(), FreqWindow::GetAudio(), ContrastDialog::GetDB(), BatchCommands::GetEndTime(), CompareAudioCommand::GetSelection(), RecordingRecoveryHandler::HandleXMLTag(), BatchCommands::IsMono(), ODTask::IsTaskAssociatedWithProject(), LOFImportFileHandle::lofOpenFiles(), TranscriptionToolBar::OnAutomateSelection(), TranscriptionToolBar::OnCalibrate(), TranscriptionToolBar::OnEndOff(), TranscriptionToolBar::OnEndOn(), ControlToolBar::OnRecord(), TranscriptionToolBar::OnSelectSilence(), TranscriptionToolBar::OnSelectSound(), ScreenFrame::OnShortTracks(), TranscriptionToolBar::OnStartOff(), TranscriptionToolBar::OnStartOn(), ContrastDialog::OnUseSelectionB(), ContrastDialog::OnUseSelectionF(), ControlToolBar::PlayPlayRegion(), GetProjectInfoCommand::SendFocusedTrackIndex(), GetProjectInfoCommand::SendNumberOfTracks(), ControlToolBar::SetupCutPreviewTracks(), ScreenFrame::SizeTracks(), and AudioIO::StopStream().
bool AudacityProject::GetTracksFitVerticallyZoomed () [inline]
Referenced by PushState().
TranscriptionToolBar * AudacityProject::GetTranscriptionToolBar ()
References ToolManager::GetToolBar(), mToolManager, and TranscriptionBarID.
Referenced by OnPlayAtSpeed(), OnPlaySpeedDec(), OnPlaySpeedInc(), and OnSetPlaySpeed().
UndoManager* AudacityProject::GetUndoManager () [inline]
Referenced by BatchCommands::ApplyChain(), EditToolBar::EnableDisableButtons(), and BatchProcessDialog::OnApplyToFiles().
wxUint32 AudacityProject::GetUpdateFlags ()
References AudioIOBusyFlag, AudioIONotBusyFlag, ClipboardFlag, CutCopyAvailableFlag, TrackListIterator::First(), gAudioIO, GetAudioIOToken(), GetFocusedFrame(), Track::GetKind(), LabelTrack::GetLabel(), Track::GetLinked(), LabelTrack::GetNumLabels(), Track::GetSelected(), GetZoom(), gMaxZoom, gMinZoom, HasLastEffectFlag, HaveRecentFiles, AudioIO::IsAudioTokenActive(), IsPlayRegionLocked(), IsSticky(), LabelTrack::IsTextClipSupported(), LabelTrack::IsTextSelected(), Track::Label, LabelsSelectedFlag, LabelTracksExistFlag, LinkingDisabledFlag, mLastEffect, msClipLen, mTracks, mUndoManager, mViewInfo, TrackListIterator::Next(), Track::Note, NoteTracksExistFlag, NoteTracksSelectedFlag, PlayRegionLockedFlag, PlayRegionNotLockedFlag, UndoManager::RedoAvailable(), RedoAvailableFlag, ViewInfo::sel0, ViewInfo::sel1, StereoRequiredFlag, LabelStruct::t, LabelStruct::t1, TextClipFlag, TimeSelectedFlag, TracksExistFlag, TracksSelectedFlag, UndoManager::UndoAvailable(), UndoAvailableFlag, UndoManager::UnsavedChanges(), UnsavedChangesFlag, Track::Wave, WaveTracksExistFlag, WaveTracksSelectedFlag, wxGetApp(), ZoomInAvailableFlag, and ZoomOutAvailableFlag.
Referenced by HandleKeyDown(), OnMenu(), SelectAllIfNone(), TryToMakeActionAllowed(), and UpdateMenus().
double AudacityProject::GetZoom () [inline]
Referenced by LOFImportFileHandle::doDuration(), EditToolBar::EnableDisableButtons(), and GetUpdateFlags().
void AudacityProject::HandleAlign (int index, bool moveSel)
References TrackListIterator::First(), Track::GetEndTime(), Track::GetOffset(), Track::GetSelected(), Track::IsSynchroSelected(), kAlign, kAlignCursor, kAlignEndCursor, kAlignEndSelEnd, kAlignEndSelStart, kAlignSelEnd, kAlignSelStart, kAlignZero, mTracks, mViewInfo, TrackListIterator::Next(), PushState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, and Track::SetOffset().
Referenced by OnAlign(), and OnAlignMoveSel().
bool AudacityProject::HandleChar (wxKeyEvent & event)
Referenced by AudacityApp::OnChar().
bool AudacityProject::HandleKeyDown (wxKeyEvent & event)
References GetUpdateFlags(), TrackPanel::HandleControlKey(), CommandManager::HandleKey(), TrackPanel::HandleShiftKey(), HasKeyboardCapture(), mCommandManager, and mTrackPanel.
Referenced by AudacityApp::OnKeyDown(), MixerTrackCluster::OnKeyEvent(), and Lyrics::OnKeyEvent().
bool AudacityProject::HandleKeyUp (wxKeyEvent & event)
References TrackPanel::HandleControlKey(), TrackPanel::HandleShiftKey(), and mTrackPanel.
Referenced by AudacityApp::OnKeyUp().
void AudacityProject::HandleMixAndRender (bool toNewTrack)
References TrackList::Add(), TrackPanel::EnsureVisible(), TrackListIterator::First(), Track::GetKind(), Track::GetLink(), Track::GetLinked(), Track::GetName(), Track::GetSelected(), mDefaultFormat, MixAndRender(), mRate, mTrackFactory, mTrackPanel, mTracks, TrackListIterator::Next(), PushState(), RedrawProject(), TrackListIterator::RemoveCurrent(), TrackPanel::SetFocusedTrack(), Track::SetName(), and Track::Wave.
Referenced by OnMixAndRender(), and OnMixAndRenderToNewTrack().
void AudacityProject::HandleResize ()
References FixScrollbars(), mTrackPanel, and UpdateLayout().
Referenced by OnImport(), OnImportRaw(), OnSize(), OnToolBarUpdate(), OpenFile(), PopState(), SetStateTo(), and TP_HandleResize().
void AudacityProject::HandleTrackMute (Track * t, const bool exclusive)
References TrackListIterator::First(), Track::GetLinked(), Track::GetMute(), IsSoloSimple(), mTracks, TrackListIterator::Next(), Track::SetMute(), and Track::SetSolo().
Referenced by MixerTrackCluster::OnButton_Mute(), and TrackPanel::OnTrackMute().
void AudacityProject::HandleTrackSolo (Track * t, const bool alternate)
References TrackListIterator::First(), Track::GetLinked(), Track::GetSolo(), IsSoloSimple(), mTracks, TrackListIterator::Next(), Track::SetMute(), and Track::SetSolo().
Referenced by MixerTrackCluster::OnButton_Solo(), and TrackPanel::OnTrackSolo().
XMLTagHandler * AudacityProject::HandleXMLChild (const wxChar * tag) [virtual]
Implements XMLTagHandler.
References TrackList::Add(), mImportXMLTagHandler, mRecordingRecoveryHandler, mTags, mTrackFactory, mTracks, TrackFactory::NewLabelTrack(), TrackFactory::NewNoteTrack(), TrackFactory::NewTimeTrack(), and TrackFactory::NewWaveTrack().
bool AudacityProject::HandleXMLTag (const wxChar * tag, const wxChar ** attrs) [virtual]
Implements XMLTagHandler.
References AUDACITY_FILE_FORMAT_VERSION, AUDACITY_VERSION_STRING, Internat::CompatibleToDouble(), GetSelectionBar(), ViewInfo::h, mDirManager, mFileName, mIsRecovered, mRate, mRecoveryAutoSaveDataDir, mViewInfo, ViewInfo::sel0, ViewInfo::sel1, DirManager::SetLocalTempDir(), DirManager::SetProject(), SetProjectTitle(), SelectionBar::SetRate(), ViewInfo::track, ViewInfo::vpos, and ViewInfo::zoom.
wxWindow * AudacityProject::HasKeyboardCapture ()
References mKeyboardCaptured.
Referenced by HandleKeyDown(), and TrackPanel::SetFocusedTrack().
bool AudacityProject::Import (wxString fileName, WaveTrackArray * pTrackArray = NULL)
References AudacityApp::AddFileToHistory(), AddImportedTracks(), ALL_EFFECTS, CONFIGURED_EFFECT, DirManager::FillBlockfilesCache(), EffectManager::Get(), GetDirManager(), gPrefs, Importer::Import(), AudacityApp::mImporter, mTags, mTrackFactory, OnEffect(), SelectAllIfNone(), SelectNone(), ShowErrorDialog(), Track::Wave, and wxGetApp().
Referenced by ImportCommand::Apply(), ImportXMLTagHandler::HandleXMLTag(), BatchProcessDialog::OnApplyToFiles(), OnImport(), and OpenFile().
void AudacityProject::InitialState () [private]
References UndoManager::ClearStates(), mHistoryWindow, mImportXMLTagHandler, ModifyUndoMenus(), mTracks, mUndoManager, mViewInfo, UndoManager::PushState(), Save(), ViewInfo::sel0, ViewInfo::sel1, UndoManager::StateSaved(), HistoryWindow::UpdateDisplay(), UpdateLyrics(), UpdateMenus(), and UpdateMixerBoard().
Referenced by OpenFile().
bool AudacityProject::IsActive ()
References mActive.
Referenced by UpdateMenus().
bool AudacityProject::IsAutoSaveEnabled () [static, private]
References gPrefs.
Referenced by AutoSaveIfNeeded(), OnAudioIONewBlockFiles(), OnAudioIOStartRecording(), and OnAudioIOStopRecording().
bool AudacityProject::IsPlayRegionLocked () [inline]
Referenced by AdornedRulerPanel::DoDrawPlayRegion(), and GetUpdateFlags().
bool AudacityProject::IsSoloNone () [inline]
Referenced by MixerTrackCluster::HandleResize().
bool AudacityProject::IsSoloSimple () [inline]
Referenced by HandleTrackMute(), HandleTrackSolo(), MixerTrackCluster::OnButton_Mute(), and MixerTrackCluster::OnButton_Solo().
bool AudacityProject::IsSticky ()
References GetStickyFlag().
Referenced by Clear(), DoAddLabel(), GetUpdateFlags(), Track::IsSynchroSelected(), OnPaste(), and TrackPanel::SelectTrackLength().
bool AudacityProject::IsTimerRecordCancelled () [inline]
Referenced by OnCloseWindow(), and TrackPanel::OnTimer().
bool AudacityProject::MakeReadyToPlay ()
MakeReadyToPlay stops whatever is currently playing and pops the play button up. Then, if nothing is now playing, it pushes the play button down and enables the stop button.
References gAudioIO, GetAudioIOToken(), GetControlToolBar(), AudioIO::IsBusy(), AudioIO::IsStreamActive(), ControlToolBar::OnStop(), ControlToolBar::SetPlay(), and ControlToolBar::SetStop().
Referenced by OnPlayCutPreview(), OnPlayLooped(), OnPlayOneSecond(), and OnPlayToSelection().
void AudacityProject::MayStartMonitoring ()
References GetMeterToolBar(), gPrefs, and MeterToolBar::StartMonitoring().
Referenced by AudacityApp::OnInit(), and ControlToolBar::StopPlaying().
void AudacityProject::ModifyState () [private]
References UndoManager::ModifyState(), mTracks, mUndoManager, mViewInfo, ViewInfo::sel0, and ViewInfo::sel1.
Referenced by AS_ModifySelection(), OnCollapseAllTracks(), OnCursorSelEnd(), OnCursorSelStart(), OnCursorTrackEnd(), OnCursorTrackStart(), OnExpandAllTracks(), OnMuteAllTracks(), OnPlayStopSelect(), OnSelectAll(), OnSelectCursorEnd(), OnSelectionRestore(), OnSelectNone(), OnSelectStartCursor(), OnSelToEnd(), OnSelToStart(), OnSetLeftSelection(), OnSetRightSelection(), OnStopSelect(), OnUnMuteAllTracks(), OnZeroCrossing(), OnZoomFitV(), and TP_ModifyState().
void AudacityProject::ModifyToolbarMenus ()
References CommandManager::Check(), ControlBarID, DeviceBarID, EditBarID, ToolBar::EnableDisableButtons(), ToolManager::GetToolBar(), gPrefs, ToolManager::IsVisible(), mCommandManager, MeterBarID, MixerBarID, mStickyFlag, mToolManager, SelectionBarID, ToolBarCount, ToolsBarID, and TranscriptionBarID.
Referenced by EditToolBar::OnButton(), OnResetToolBars(), OnShowControlToolBar(), OnShowDeviceToolBar(), OnShowEditToolBar(), OnShowMeterToolBar(), OnShowMixerToolBar(), OnShowSelectionToolBar(), OnShowToolsToolBar(), OnShowTranscriptionToolBar(), OnTogglePlayRecording(), OnToggleSoundActivated(), OnToggleSWPlaythrough(), and UpdateMenus().
void AudacityProject::ModifyUndoMenus ()
References CommandManager::Enable(), UndoManager::GetCurrentState(), UndoManager::GetShortDescription(), mCommandManager, CommandManager::Modify(), mUndoManager, UndoManager::RedoAvailable(), and UndoManager::UndoAvailable().
Referenced by CreateMenusAndCommands(), InitialState(), OnApplyChain(), OnRedo(), OnUndo(), PushState(), and SetStateTo().
double AudacityProject::NearestZeroCrossing (double t0)
References TrackListIterator::First(), floatSample, WaveTrack::Get(), Track::GetKind(), WaveTrack::GetRate(), GetRate(), Track::GetSelected(), min(), mTracks, TrackListIterator::Next(), WaveTrack::TimeToLongSamples(), and Track::Wave.
Referenced by OnZeroCrossing().
void AudacityProject::NextFrame ()
References BotDockHasFocus, ToolManager::GetBotDock(), GetFocusedFrame(), ToolManager::GetTopDock(), mToolManager, mTrackPanel, TopDockHasFocus, and TrackPanelHasFocus.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnAbout ()
Referenced by CreateMenusAndCommands().
void AudacityProject::OnActivate (wxActivateEvent & event)
References mActive, mIsDeleting, mLastFocusedWindow, mTrackPanel, and SetActiveProject().
void AudacityProject::OnAddLabel ()
References DoAddLabel(), mViewInfo, ViewInfo::sel0, and ViewInfo::sel1.
Referenced by LabelTrack::CaptureKey(), and CreateMenusAndCommands().
void AudacityProject::OnAddLabelPlaying ()
References DoAddLabel(), gAudioIO, GetAudioIOToken(), AudioIO::GetStreamTime(), and AudioIO::IsStreamActive().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnAlign (int index)
References HandleAlign().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnAlignMoveSel (int index)
References HandleAlign().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnAnalyzeEffect (int index)
References ANALYZE_EFFECT, BUILTIN_EFFECT, and OnEffect().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnAnalyzePlugin (int index)
References ANALYZE_EFFECT, OnEffect(), and PLUGIN_EFFECT.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnApplyChain ()
References ModifyUndoMenus().
Referenced by CreateMenusAndCommands(), and ControlToolBar::OnBatch().
void AudacityProject::OnAudioDeviceInfo ()
References gAudioIO, AudioIO::GetDeviceInfo(), and ShowInfoDialog().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnAudioIONewBlockFiles (const wxString & blockFileLog) [virtual]
Implements AudioIOListener.
References GetCacheBlockFiles(), IsAutoSaveEnabled(), and mAutoSaveFileName.
void AudacityProject::OnAudioIORate (int rate) [virtual]
Implements AudioIOListener.
References mStatusBar.
void AudacityProject::OnAudioIOStartRecording () [virtual]
Implements AudioIOListener.
References AutoSave(), GetCacheBlockFiles(), and IsAutoSaveEnabled().
void AudacityProject::OnAudioIOStopRecording () [virtual]
Implements AudioIOListener.
References AutoSave(), IsAutoSaveEnabled(), mDirManager, and DirManager::WriteCacheToDisk().
void AudacityProject::OnBenchmark ()
References RunBenchmark().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCaptureKeyboard (wxCommandEvent & event)
References CaptureKeyboard().
void AudacityProject::OnCheckDependencies ()
References ShowDependencyDialogIfNeeded().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnClose ()
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCloseWindow (wxCloseEvent & event)
References AllProjectsDeleteLock(), AllProjectsDeleteUnlock(), TrackList::Clear(), UndoManager::ClearStates(), CreateNewAudacityProject(), DeleteClipboard(), DeleteCurrentAutoSaveFile(), DirManager::Deref(), ModuleManager::Dispatch(), TrackListIterator::First(), FixScrollbars(), gActiveProject, gAudacityProjects, gAudioIO, GetAudioIOToken(), GetControlToolBar(), Track::GetKind(), AudioIO::GetListener(), AudioIO::GetNumCaptureChannels(), gIsQuitting, gPrefs, AudioIO::IsBusy(), AudioIO::IsMonitoring(), AudioIO::IsStreamActive(), IsTimerRecordCancelled(), mDirManager, mEmptyCanBeDirty, mFreqWindow, mHistoryWindow, mImportXMLTagHandler, mIsDeleting, mLastFocusedWindow, mLastSavedTracks, AudacityApp::mLogger, mTags, mTimer, mToolManager, mTrackFactory, mTrackPanel, mTracks, mUndoManager, TrackListIterator::Next(), ControlToolBar::OnStop(), OnTrackListUpdated(), OnUndo(), ProjectClosing, PushState(), QuitAudacity(), RedrawProject(), ResetTimerRecordFlag(), Save(), SaveWindowSize(), SetAudioIOToken(), AudioIO::SetListener(), AudacityApp::SetWindowRectAlreadySaved(), AudioIO::StopStream(), UndoManager::UnsavedChanges(), Track::Wave, and wxGetApp().
void AudacityProject::OnCollapseAllTracks ()
References TrackListIterator::First(), ModifyState(), mTracks, TrackListIterator::Next(), RedrawProject(), and Track::SetMinimized().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnContrast ()
References InitContrastDialog().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCopy ()
References TrackList::Add(), ClearClipboard(), Track::Copy(), TrackListIterator::First(), Track::GetChannel(), Track::GetKind(), Track::GetLinked(), Track::GetName(), Track::GetSelected(), Track::Label, msClipboard, msClipLen, msClipProject, mTrackPanel, mTracks, mViewInfo, TrackListIterator::Next(), TrackPanel::Refresh(), ViewInfo::sel0, ViewInfo::sel1, Track::SetChannel(), Track::SetLinked(), and Track::SetName().
Referenced by CreateMenusAndCommands(), and EditToolBar::OnButton().
void AudacityProject::OnCopyLabels ()
References WaveTrack::Copy(), EditClipboardByLabel(), msClipProject, mTrackPanel, mViewInfo, PushState(), TrackPanel::Refresh(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorDown ()
References mTrackPanel, and TrackPanel::OnNextTrack().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorLeft ()
References mTrackPanel, and TrackPanel::OnCursorLeft().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorLongJumpLeft ()
References mTrackPanel, and TrackPanel::OnCursorMove().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorLongJumpRight ()
References mTrackPanel, and TrackPanel::OnCursorMove().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorRight ()
References mTrackPanel, and TrackPanel::OnCursorRight().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorSelEnd ()
References ModifyState(), mTrackPanel, mViewInfo, TrackPanel::Refresh(), TrackPanel::ScrollIntoView(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorSelStart ()
References ModifyState(), mTrackPanel, mViewInfo, TrackPanel::Refresh(), TrackPanel::ScrollIntoView(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorShortJumpLeft ()
References mTrackPanel, and TrackPanel::OnCursorMove().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorShortJumpRight ()
References mTrackPanel, and TrackPanel::OnCursorMove().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorTrackEnd ()
References TrackListIterator::First(), Track::GetEndTime(), Track::GetSelected(), ModifyState(), mTrackPanel, mTracks, mViewInfo, TrackListIterator::Next(), TrackPanel::Refresh(), TrackPanel::ScrollIntoView(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorTrackStart ()
References TrackListIterator::First(), Track::GetOffset(), Track::GetSelected(), ModifyState(), mTrackPanel, mTracks, mViewInfo, TrackListIterator::Next(), TrackPanel::Refresh(), TrackPanel::ScrollIntoView(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCursorUp ()
References mTrackPanel, and TrackPanel::OnPrevTrack().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnCut ()
References TrackList::Add(), Track::Clear(), ClearClipboard(), Track::Copy(), Track::Cut(), TrackListIterator::First(), Track::GetChannel(), Track::GetKind(), Track::GetLinked(), Track::GetName(), Track::GetSelected(), gPrefs, Track::IsSynchroSelected(), Track::Label, msClipboard, msClipLen, msClipProject, mTrackPanel, mTracks, mViewInfo, TrackListIterator::Next(), Track::Note, PushState(), RedrawProject(), TrackPanel::Refresh(), ViewInfo::sel0, ViewInfo::sel1, Track::SetChannel(), Track::SetLinked(), Track::SetName(), and Track::Wave.
Referenced by CreateMenusAndCommands(), and EditToolBar::OnButton().
void AudacityProject::OnCutLabels ()
References WaveTrack::Clear(), WaveTrack::ClearAndAddCutLine(), WaveTrack::Copy(), EditByLabel(), EditClipboardByLabel(), gPrefs, msClipProject, mViewInfo, PushState(), RedrawProject(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnDelete ()
References Clear().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnDeleteLabels ()
References WaveTrack::Clear(), EditByLabel(), mViewInfo, PushState(), RedrawProject(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnDisjoin ()
References TrackListIterator::First(), Track::GetKind(), Track::GetSelected(), mTracks, mViewInfo, TrackListIterator::Next(), PushState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, and Track::Wave.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnDisjoinLabels ()
References WaveTrack::Disjoin(), EditByLabel(), mViewInfo, PushState(), RedrawProject(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnDrawTool ()
References drawTool, and SetTool().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnDuplicate ()
References TrackList::Add(), Track::Copy(), TrackListIterator::First(), Track::GetOffset(), Track::GetSelected(), Track::Init(), TrackListIterator::Last(), mTracks, mViewInfo, TrackListIterator::Next(), PushState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, and Track::SetOffset().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnEditChains ()
Referenced by CreateMenusAndCommands().
void AudacityProject::OnEditLabels ()
References mDirManager, mTracks, mViewInfo, PushState(), and RedrawProject().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnEditMetadata ()
References mTags, PushState(), and Tags::ShowEditDialog().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnEffect (int type, int index)
References EffectManager::Get(), EffectManager::GetEffects(), and OnEffect().
bool AudacityProject::OnEffect (int type, Effect * f, wxString params = wxEmptyString, bool saveState = true)
OnEffect() takes an Effect and executes it.
At the moment flags are used only to indicate whether to prompt for parameters or whether to use the most recently stored values.
At some point we should change to specifying a parameter source - one of: + Prompt + Use previous values + Parse from a string that is passed in
DanH: I've added the third option as a temporary measure. I think this should eventually be done by having effects as Command objects.
References TrackList::Add(), ANALYZE_EFFECT, Effect::DoEffect(), TrackPanel::EnsureVisible(), TrackListIterator::First(), Effect::GetEffectDescription(), Effect::GetEffectFlags(), Effect::GetEffectName(), Track::GetEndTime(), TrackPanel::GetFirstSelectedTrack(), Track::GetKind(), Track::GetSelected(), INSERT_EFFECT, mCommandManager, mLastEffect, mLastEffectType, CommandManager::Modify(), mRate, mTrackFactory, mTrackPanel, mTracks, mViewInfo, TrackFactory::NewWaveTrack(), TrackListIterator::Next(), OnZoomFit(), PushState(), RedrawProject(), TrackPanel::Refresh(), TrackList::Remove(), ViewInfo::sel0, ViewInfo::sel1, Track::SetSelected(), and Track::Wave.
Referenced by BatchCommands::ApplyEffectCommand(), CommandManager::HandleTextualCommand(), Import(), OnAnalyzeEffect(), OnAnalyzePlugin(), OnEffect(), OnGenerateEffect(), OnGeneratePlugin(), OnProcessAny(), OnProcessEffect(), OnProcessPlugin(), OnRepeatLastEffect(), and OnStereoToMono().
void AudacityProject::OnEnvelopeTool ()
References envelopeTool, and SetTool().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnExit (void)
References QuitAudacity().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnExpandAllTracks ()
References TrackListIterator::First(), ModifyState(), mTracks, TrackListIterator::Next(), RedrawProject(), and Track::SetMinimized().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnExport ()
References TrackList::GetEndTime(), mTracks, and Exporter::Process().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnExportCleanSpeechPresets ()
References FileNames::DataDir(), AudacityApp::GetCleanSpeechNoiseGate(), AudacityApp::GetCleanSpeechNoiseGateExpectedCount(), gPrefs, PRESET_COUNT, PRESET_FORMAT, SKIP_EFFECT_MILLISECOND, and wxGetApp().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnExportLabels ()
References TrackListIterator::First(), Track::GetKind(), Track::Label, mTracks, and TrackListIterator::Next().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnExportMIDI ()
References NoteTrack::ExportAllegro(), NoteTrack::ExportMIDI(), TrackListIterator::First(), Track::GetKind(), Track::GetSelected(), mTracks, TrackListIterator::Next(), and Track::Note.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnExportMultiple ()
References ExportMultiple::ShowModal().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnExportSelection ()
References mViewInfo, Exporter::Process(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnFullScreen ()
Referenced by CreateMenusAndCommands().
void AudacityProject::OnGenerateEffect (int index)
References BUILTIN_EFFECT, INSERT_EFFECT, and OnEffect().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnGeneratePlugin (int index)
References INSERT_EFFECT, OnEffect(), and PLUGIN_EFFECT.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnHelpWelcome ()
References SplashDialog::Show2().
Referenced by AudacityApp::OnInit().
void AudacityProject::OnHistory ()
References mHistoryWindow, mUndoManager, and HistoryWindow::UpdateDisplay().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnIconize (wxIconizeEvent & event)
References gAudacityProjects, and mIconized.
void AudacityProject::OnImport ()
References CompareNoCaseFileName(), gPrefs, HandleResize(), Import(), ODManager::Pause(), ODManager::Resume(), and ShowOpenDialog().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnImportCleanSpeechPresets ()
References FileNames::DataDir(), AudacityApp::GetCleanSpeechNoiseGate(), AudacityApp::GetCleanSpeechNoiseGateExpectedCount(), gPrefs, PRESET_COUNT, PRESET_FORMAT, and wxGetApp().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnImportLabels ()
References TrackList::Add(), gPrefs, LabelTrack::Import(), mDirManager, mTracks, PushState(), RedrawProject(), SelectNone(), and Track::SetSelected().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnImportMIDI ()
References TrackList::Add(), TrackPanel::EnsureVisible(), gPrefs, ImportMIDI(), mDirManager, mTrackPanel, mTracks, PushState(), RedrawProject(), SelectNone(), and Track::SetSelected().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnImportRaw ()
References AddImportedTracks(), gPrefs, HandleResize(), ImportRaw(), and mTrackFactory.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnInputGain ()
References GetMixerToolBar(), and MixerToolBar::ShowInputGainDialog().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnInputGainDec ()
References MixerToolBar::AdjustInputGain(), and GetMixerToolBar().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnInputGainInc ()
References MixerToolBar::AdjustInputGain(), and GetMixerToolBar().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnInputSource ()
References GetMixerToolBar(), and MixerToolBar::ShowInputSourceDialog().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnJoin ()
References TrackListIterator::First(), Track::GetKind(), Track::GetSelected(), mTracks, mViewInfo, TrackListIterator::Next(), PushState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, and Track::Wave.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnJoinLabels ()
References EditByLabel(), WaveTrack::Join(), mViewInfo, PushState(), RedrawProject(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnKaraoke ()
References mLyricsWindow.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnLockPlayRegion ()
References mLockPlayRegion, and mRuler.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnLog ()
References AudacityApp::mLogger, and wxGetApp().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnManual ()
References FileNames::HtmlHelpIndexFile(), and ShowHelpDialog().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnMenu (wxCommandEvent & event)
References GetUpdateFlags(), CommandManager::HandleMenuID(), and mCommandManager.
void AudacityProject::OnMenuEvent (wxMenuEvent & event)
References CommandManager::HandleMenuClose(), CommandManager::HandleMenuOpen(), and mCommandManager.
void AudacityProject::OnMixAndRender ()
References HandleMixAndRender().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnMixAndRenderToNewTrack ()
References HandleMixAndRender().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnMixerBoard ()
References MixerBoardFrame::mMixerBoard, mMixerBoard, and mMixerBoardFrame.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnMouseEvent (wxMouseEvent & event)
References SetActiveProject().
void AudacityProject::OnMove (wxMoveEvent & event)
References SetNormalizedWindowState().
void AudacityProject::OnMultiTool ()
References multiTool, and SetTool().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnMuteAllTracks ()
References TrackListIterator::First(), mMixerBoard, ModifyState(), mTracks, TrackListIterator::Next(), RedrawProject(), Track::SetMute(), and MixerBoard::UpdateMute().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnNew ()
References CreateNewAudacityProject().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnNewLabelTrack ()
References TrackList::Add(), TrackPanel::EnsureVisible(), mDirManager, mTrackPanel, mTracks, PushState(), RedrawProject(), SelectNone(), and Track::SetSelected().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnNewStereoTrack ()
References TrackList::Add(), TrackPanel::EnsureVisible(), Track::LeftChannel, mDefaultFormat, mTrackFactory, mTrackPanel, mTracks, TrackFactory::NewWaveTrack(), PushState(), RedrawProject(), Track::RightChannel, SelectNone(), Track::SetChannel(), Track::SetLinked(), and Track::SetSelected().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnNewTimeTrack ()
References TrackList::AddToHead(), TrackPanel::EnsureVisible(), TrackList::GetTimeTrack(), mDirManager, mTrackPanel, mTracks, PushState(), RedrawProject(), SelectNone(), and Track::SetSelected().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnNewWaveTrack ()
References TrackList::Add(), TrackPanel::EnsureVisible(), mDefaultFormat, mTrackFactory, mTrackPanel, mTracks, TrackFactory::NewWaveTrack(), PushState(), RedrawProject(), SelectNone(), and Track::SetSelected().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnNextTool ()
References ToolsToolBar::GetDownTool(), GetToolsToolBar(), mTrackPanel, numTools, TrackPanel::Refresh(), and ToolsToolBar::SetCurrentTool().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnODTaskComplete (wxCommandEvent & event)
References mTrackPanel, and TrackPanel::Refresh().
void AudacityProject::OnODTaskUpdate (wxCommandEvent & event)
Handles the redrawing necessary for tasks as they partially update in the background.
References mTrackPanel, and TrackPanel::Refresh().
void AudacityProject::OnOpen ()
References OpenFiles().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnOpenAudioFile (wxCommandEvent & event)
References OpenFile().
void AudacityProject::OnOutputGain ()
References GetMixerToolBar(), and MixerToolBar::ShowOutputGainDialog().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnOutputGainDec ()
References MixerToolBar::AdjustOutputGain(), and GetMixerToolBar().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnOutputGainInc ()
References MixerToolBar::AdjustOutputGain(), and GetMixerToolBar().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPageSetup ()
References HandlePageSetup().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPaste ()
References TrackList::Add(), LabelTrack::CalcCursorX(), WaveTrack::Clear(), Track::Clear(), TrackPanel::EnsureVisible(), TrackListIterator::First(), TrackListCondIterator::First(), WaveTrack::Flush(), Track::GetChannel(), Track::GetKind(), Track::GetLinked(), Track::GetName(), GetRate(), WaveTrack::GetRate(), WaveTrack::GetSampleFormat(), Track::GetSelected(), WaveTrack::InsertSilence(), LabelTrack::IsSelected(), IsSticky(), Track::IsSynchroSelected(), Track::Label, TrackListCondIterator::Last(), msClipboard, msClipLen, msClipProject, mTrackFactory, mTrackPanel, mTracks, mViewInfo, TrackFactory::NewLabelTrack(), TrackFactory::NewNoteTrack(), TrackFactory::NewTimeTrack(), TrackFactory::NewWaveTrack(), TrackListIterator::Next(), TrackListCondIterator::Next(), Track::Note, Track::Paste(), LabelTrack::PasteSelectedText(), PushState(), RedrawProject(), TrackPanel::ScrollIntoView(), ViewInfo::sel0, ViewInfo::sel1, Track::SetChannel(), Track::SetLinked(), Track::SetName(), Track::SetSelected(), Track::SyncAdjust(), Track::Time, and Track::Wave.
Referenced by CreateMenusAndCommands(), EditToolBar::OnButton(), and OnPasteOver().
void AudacityProject::OnPasteNewLabel ()
References TrackList::Add(), LabelTrack::AddLabel(), TrackPanel::EnsureVisible(), TrackListIterator::First(), TrackListCondIterator::First(), Track::Label, mDirManager, mTrackPanel, mTracks, mViewInfo, TrackListCondIterator::Next(), TrackListIterator::Next(), LabelTrack::PasteSelectedText(), PushState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, Track::SetSelected(), and LabelTrack::Unselect().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPasteOver ()
References msClipLen, mViewInfo, OnPaste(), ViewInfo::sel0, and ViewInfo::sel1.
void AudacityProject::OnPause ()
References GetControlToolBar(), and ControlToolBar::OnPause().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPlayAtSpeed ()
References GetTranscriptionToolBar(), and TranscriptionToolBar::PlayAtSpeed().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPlayCutPreview ()
References GetControlToolBar(), MakeReadyToPlay(), and ControlToolBar::PlayCurrentRegion().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPlayLooped ()
References GetControlToolBar(), MakeReadyToPlay(), and ControlToolBar::PlayCurrentRegion().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPlayOneSecond ()
References GetControlToolBar(), TrackPanel::GetMostRecentXPos(), MakeReadyToPlay(), mLastPlayMode, mTrackPanel, oneSecondPlay, and ControlToolBar::PlayPlayRegion().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPlaySpeedDec ()
References TranscriptionToolBar::AdjustPlaySpeed(), and GetTranscriptionToolBar().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPlaySpeedInc ()
References TranscriptionToolBar::AdjustPlaySpeed(), and GetTranscriptionToolBar().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPlayStop ()
References gAudacityProjects, gAudioIO, GetAudioIOToken(), GetControlToolBar(), AudioIO::IsBusy(), AudioIO::IsStreamActive(), ControlToolBar::PlayCurrentRegion(), ControlToolBar::SetPlay(), ControlToolBar::SetStop(), ControlToolBar::StopPlaying(), and TP_DisplaySelection().
Referenced by CreateMenusAndCommands(), and TP_OnPlayKey().
void AudacityProject::OnPlayStopSelect ()
References gAudioIO, GetAudioIOToken(), GetControlToolBar(), AudioIO::GetStreamTime(), AudioIO::IsBusy(), AudioIO::IsStreamActive(), ModifyState(), mViewInfo, ControlToolBar::OnStop(), ControlToolBar::PlayCurrentRegion(), ViewInfo::sel0, ViewInfo::sel1, ControlToolBar::SetPlay(), and ControlToolBar::SetStop().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPlayToSelection ()
The idea for this function (and first implementation) was from Juhana Sadeharju. The function plays the sound between the current mouse position and the nearest selection boundary. This gives four possible play regions depending on where the current mouse position is relative to the left and right boundaries of the selection region.
References GetControlToolBar(), TrackPanel::GetMostRecentXPos(), MakeReadyToPlay(), mLastPlayMode, mTrackPanel, mViewInfo, oneSecondPlay, ControlToolBar::PlayPlayRegion(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPlotSpectrum ()
References mFreqWindow, and FreqWindow::OnReplot().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPreferences ()
References gAudacityProjects, RebuildMenuBar(), and RebuildOtherMenus().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPrevTool ()
References ToolsToolBar::GetDownTool(), GetToolsToolBar(), mTrackPanel, numTools, TrackPanel::Refresh(), and ToolsToolBar::SetCurrentTool().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnPrint ()
References GetName(), HandlePrint(), and mTracks.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnProcessAny (int index)
References ALL_EFFECTS, EffectManager::Get(), EffectManager::GetEffect(), and OnEffect().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnProcessEffect (int index)
References ADVANCED_EFFECT, BUILTIN_EFFECT, mCleanSpeechMode, OnEffect(), and PROCESS_EFFECT.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnProcessPlugin (int index)
References OnEffect(), PLUGIN_EFFECT, and PROCESS_EFFECT.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnQuickHelp ()
References FileNames::HtmlHelpIndexFile(), and ShowHelpDialog().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnRecord ()
References GetControlToolBar(), and ControlToolBar::OnRecord().
Referenced by CreateMenusAndCommands(), and TimerRecordDialog::RunWaitDialog().
void AudacityProject::OnRecordAppend ()
References GetControlToolBar(), and ControlToolBar::OnRecord().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnRedo ()
References TrackPanel::EnsureVisible(), TrackPanel::GetFirstSelectedTrack(), mHistoryWindow, ModifyUndoMenus(), mTrackPanel, mUndoManager, mViewInfo, PopState(), UndoManager::Redo(), UndoManager::RedoAvailable(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, TrackPanel::SetFocusedTrack(), and HistoryWindow::UpdateDisplay().
Referenced by CreateMenusAndCommands(), and EditToolBar::OnButton().
void AudacityProject::OnReleaseKeyboard (wxCommandEvent & event)
References ReleaseKeyboard().
void AudacityProject::OnRemoveTracks ()
References TrackPanel::EnsureVisible(), TrackListIterator::First(), Track::GetKind(), TrackList::GetNext(), Track::GetSelected(), mMixerBoard, mTrackPanel, mTracks, TrackListIterator::Next(), PushState(), TrackPanel::Refresh(), TrackListIterator::RemoveCurrent(), MixerBoard::RemoveTrackCluster(), and Track::Wave.
Referenced by CreateMenusAndCommands(), and BatchProcessDialog::OnApplyToFiles().
void AudacityProject::OnRepeatLastEffect (int index)
References CONFIGURED_EFFECT, mLastEffect, mLastEffectType, and OnEffect().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnResample ()
References ShuttleGuiBase::AddCombo(), ShuttleGui::AddStandardButtons(), eIsCreating, ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndVerticalLay(), FinishAutoScroll(), TrackListIterator::First(), Track::GetKind(), Track::GetSelected(), mTracks, TrackListIterator::Next(), PushState(), RedrawProject(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartVerticalLay(), and Track::Wave.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnResetToolBars ()
References ModifyToolbarMenus(), mToolManager, and ToolManager::Reset().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSave ()
References Save().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSaveAs ()
References SaveAs().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSaveCompressed ()
References SaveAs().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnScreenshot ()
References OpenScreenshotTools().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnScroll (wxScrollEvent & event)
References ViewInfo::h, mAutoScrolling, mHsbar, mTrackPanel, mViewInfo, mVsbar, TrackPanel::Refresh(), ViewInfo::sbarH, ViewInfo::sbarScale, ViewInfo::screen, ViewInfo::scrollStep, ViewInfo::total, UpdateFirstVisible(), ViewInfo::vpos, and ViewInfo::zoom.
Referenced by FinishAutoScroll(), OnScrollLeftButton(), OnScrollRightButton(), TP_ScrollUpDown(), and TP_ScrollWindow().
void AudacityProject::OnScrollLeft ()
This method handles general left-scrolling, either for drag-scrolling or when the scrollbar is clicked to the left of the thumb
References FinishAutoScroll(), mHsbar, mViewInfo, sbarHjump, and ViewInfo::sbarScale.
Referenced by TP_ScrollLeft().
void AudacityProject::OnScrollLeftButton (wxScrollEvent & event)
This handles the event when the left direction button on the scrollbar is depresssed
References mHsbar, mViewInfo, OnScroll(), sbarHjump, and ViewInfo::sbarScale.
void AudacityProject::OnScrollRight ()
This method handles general right-scrolling, either for drag-scrolling or when the scrollbar is clicked to the right of the thumb
References FinishAutoScroll(), max, mHsbar, mViewInfo, sbarHjump, and ViewInfo::sbarScale.
Referenced by TP_ScrollRight().
void AudacityProject::OnScrollRightButton (wxScrollEvent & event)
This handles the event when the right direction button on the scrollbar is depresssed
References max, mHsbar, mViewInfo, OnScroll(), sbarHjump, and ViewInfo::sbarScale.
void AudacityProject::OnSeekLeftLong ()
References mTrackPanel, and TrackPanel::OnCursorLeft().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSeekLeftShort ()
References mTrackPanel, and TrackPanel::OnCursorLeft().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSeekRightLong ()
References mTrackPanel, and TrackPanel::OnCursorRight().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSeekRightShort ()
References mTrackPanel, and TrackPanel::OnCursorRight().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelContractLeft ()
References mTrackPanel, and TrackPanel::OnCursorRight().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelContractRight ()
References mTrackPanel, and TrackPanel::OnCursorLeft().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelectAll ()
References TrackListIterator::First(), TrackList::GetEndTime(), TrackList::GetMinOffset(), mMixerBoard, ModifyState(), mTrackPanel, mTracks, mViewInfo, TrackListIterator::Next(), TrackPanel::Refresh(), ViewInfo::sel0, ViewInfo::sel1, and Track::SetSelected().
Referenced by SelectCommand::Apply(), CreateMenusAndCommands(), BatchProcessDialog::OnApplyToFiles(), SelectAllIfNone(), and TryToMakeActionAllowed().
void AudacityProject::OnSelectCursorEnd ()
References TrackListIterator::First(), Track::GetEndTime(), Track::GetSelected(), ModifyState(), mTrackPanel, mTracks, mViewInfo, TrackListIterator::Next(), TrackPanel::Refresh(), and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelectionRestore ()
References ModifyState(), mSel0save, mSel1save, mTrackPanel, mViewInfo, TrackPanel::Refresh(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelectionSave ()
References mSel0save, mSel1save, mViewInfo, ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelectNone ()
References ModifyState(), mViewInfo, ViewInfo::sel0, ViewInfo::sel1, and SelectNone().
Referenced by SelectCommand::Apply(), and CreateMenusAndCommands().
void AudacityProject::OnSelectStartCursor ()
References TrackListIterator::First(), Track::GetOffset(), Track::GetSelected(), ModifyState(), mTrackPanel, mTracks, mViewInfo, TrackListIterator::Next(), TrackPanel::Refresh(), and ViewInfo::sel0.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelectTool ()
References selectTool, and SetTool().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelExtendLeft ()
References mTrackPanel, and TrackPanel::OnCursorLeft().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelExtendRight ()
References mTrackPanel, and TrackPanel::OnCursorRight().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelSetExtendLeft ()
References mTrackPanel, and TrackPanel::OnBoundaryMove().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelSetExtendRight ()
References mTrackPanel, and TrackPanel::OnBoundaryMove().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelToEnd ()
References ModifyState(), and SkipEnd().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSelToStart ()
References ModifyState(), and Rewind().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSeparator ()
void AudacityProject::OnSetLeftSelection ()
References gAudioIO, GetAudioIOToken(), AudioIO::GetStreamTime(), TimeDialog::GetTimeValue(), gPrefs, AudioIO::IsStreamActive(), ModifyState(), mRate, mTrackPanel, mViewInfo, TrackPanel::Refresh(), ViewInfo::sel0, ViewInfo::sel1, TimeDialog::SetFormatString(), TimeDialog::SetSampleRate(), and TimeDialog::SetTimeValue().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSetPlaySpeed ()
References GetTranscriptionToolBar(), and TranscriptionToolBar::ShowPlaySpeedDialog().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSetRightSelection ()
References gAudioIO, GetAudioIOToken(), AudioIO::GetStreamTime(), TimeDialog::GetTimeValue(), gPrefs, AudioIO::IsStreamActive(), ModifyState(), mRate, mTrackPanel, mViewInfo, TrackPanel::Refresh(), ViewInfo::sel0, ViewInfo::sel1, TimeDialog::SetFormatString(), TimeDialog::SetSampleRate(), and TimeDialog::SetTimeValue().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnShiftDown ()
References mTrackPanel, and TrackPanel::OnNextTrack().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnShiftUp ()
References mTrackPanel, and TrackPanel::OnPrevTrack().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnShowClipping ()
References CommandManager::Check(), gPrefs, mCommandManager, mTrackPanel, TrackPanel::Refresh(), and TrackPanel::UpdatePrefs().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnShowControlToolBar ()
References ControlBarID, ModifyToolbarMenus(), mToolManager, and ToolManager::ShowHide().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnShowDeviceToolBar ()
References DeviceBarID, ModifyToolbarMenus(), mToolManager, and ToolManager::ShowHide().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnShowEditToolBar ()
References EditBarID, ModifyToolbarMenus(), mToolManager, and ToolManager::ShowHide().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnShowMeterToolBar ()
References MeterBarID, ModifyToolbarMenus(), mToolManager, and ToolManager::ShowHide().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnShowMixerToolBar ()
References MixerBarID, ModifyToolbarMenus(), mToolManager, and ToolManager::ShowHide().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnShowSelectionToolBar ()
References ModifyToolbarMenus(), mToolManager, SelectionBarID, and ToolManager::ShowHide().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnShowToolsToolBar ()
References ModifyToolbarMenus(), mToolManager, ToolManager::ShowHide(), and ToolsBarID.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnShowTranscriptionToolBar ()
References ModifyToolbarMenus(), mToolManager, ToolManager::ShowHide(), and TranscriptionBarID.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSilence ()
References TrackListCondIterator::First(), mTrackPanel, mTracks, mViewInfo, TrackListCondIterator::Next(), PushState(), TrackPanel::Refresh(), ViewInfo::sel0, ViewInfo::sel1, and Track::Wave.
Referenced by CreateMenusAndCommands(), and EditToolBar::OnButton().
void AudacityProject::OnSilenceLabels ()
References EditByLabel(), mTrackPanel, mViewInfo, PushState(), TrackPanel::Refresh(), ViewInfo::sel0, ViewInfo::sel1, and WaveTrack::Silence().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSimplifiedView ()
References CommandManager::Check(), CommandManager::mbHideFlaggedItems, mCommandManager, and RebuildMenuBar().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSize (wxSizeEvent & event)
References HandleResize(), and SetNormalizedWindowState().
void AudacityProject::OnSkipEnd ()
References GetControlToolBar(), and ControlToolBar::OnFF().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSkipStart ()
References GetControlToolBar(), and ControlToolBar::OnRewind().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSnapToOff ()
References SetSnapTo().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSnapToOn ()
References SetSnapTo().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSortName ()
References TrackList::Add(), TrackListIterator::First(), Track::GetName(), mTrackPanel, mTracks, PushState(), TrackPanel::Refresh(), and TrackListIterator::RemoveCurrent().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSortTime ()
References TrackList::Add(), TrackListIterator::First(), Track::GetKind(), GetTime(), mTrackPanel, mTracks, PushState(), TrackPanel::Refresh(), TrackListIterator::RemoveCurrent(), and Track::Wave.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSoundActivated ()
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSplit ()
References TrackListIterator::First(), Track::GetSelected(), mTrackPanel, mTracks, mViewInfo, TrackListIterator::Next(), PushState(), TrackPanel::Refresh(), ViewInfo::sel0, ViewInfo::sel1, WaveTrack::Split(), and Track::Wave.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSplitCut ()
References TrackList::Add(), ClearClipboard(), Track::Copy(), TrackListIterator::First(), Track::GetChannel(), Track::GetKind(), Track::GetLinked(), Track::GetName(), Track::GetSelected(), msClipboard, msClipLen, msClipProject, mTracks, mViewInfo, TrackListIterator::Next(), PushState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, Track::SetChannel(), Track::SetLinked(), Track::SetName(), Track::Silence(), and Track::Wave.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSplitCutLabels ()
References EditClipboardByLabel(), msClipProject, mViewInfo, PushState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, and WaveTrack::SplitCut().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSplitDelete ()
References TrackListIterator::First(), Track::GetKind(), Track::GetSelected(), mTracks, mViewInfo, TrackListIterator::Next(), PushState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, Track::Silence(), and Track::Wave.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSplitDeleteLabels ()
References EditByLabel(), mViewInfo, PushState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, and WaveTrack::SplitDelete().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSplitLabels ()
References EditByLabel(), PushState(), RedrawProject(), and WaveTrack::Split().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnSplitLabelsToTracks ()
References TrackList::Add(), Track::Copy(), TrackListIterator::First(), Track::GetEndTime(), Track::GetKind(), LabelTrack::GetLabel(), Track::GetLinked(), LabelTrack::GetNumLabels(), Track::GetOffset(), Track::GetSelected(), Track::Init(), Track::Label, label, mTracks, name, TrackListIterator::Next(), PushState(), RedrawProject(), Track::SetLinked(), Track::SetName(), Track::SetOffset(), LabelStruct::t, LabelStruct::title, and Track::Wave.
void AudacityProject::OnSplitNew ()
References TrackList::Add(), TrackListIterator::First(), Track::GetOffset(), TrackListIterator::Last(), mTracks, mViewInfo, TrackListIterator::Next(), PushState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, Track::SetChannel(), Track::SetLinked(), Track::SetName(), Track::SetOffset(), and Track::Wave.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnStereoToMono (int index)
References ALL_EFFECTS, EffectManager::Get(), and OnEffect().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnStickyLabel ()
References EditToolBar::EnableDisableButtons(), GetEditToolBar(), GetStickyFlag(), and SetStickyFlag().
Referenced by CreateMenusAndCommands(), and EditToolBar::OnButton().
void AudacityProject::OnStop ()
References gAudioIO, GetControlToolBar(), AudioIO::IsStreamActive(), and ControlToolBar::OnStop().
Referenced by CreateMenusAndCommands(), and TimerRecordDialog::RunWaitDialog().
void AudacityProject::OnStopSelect ()
References gAudioIO, GetControlToolBar(), AudioIO::GetStreamTime(), AudioIO::IsStreamActive(), ModifyState(), mViewInfo, ControlToolBar::OnStop(), ViewInfo::sel0, and ViewInfo::sel1.
void AudacityProject::OnTimer (wxTimerEvent & event)
References gAudioIO, AudioIO::GetCaptureFormat(), DirManager::GetFreeDiskSpace(), GetMixerToolBar(), AudioIO::GetNumCaptureChannels(), ODManager::GetOverallPercentComplete(), GetRate(), ODManager::GetTotalNumTasks(), ODManager::Instance(), ODManager::IsInstanceCreated(), mDirManager, mLastStatusUpdateTime, mStatusBar, SAMPLE_SIZE_DISK, ODManager::SignalTaskQueueLoop(), and MixerToolBar::UpdateControls().
void AudacityProject::OnTimerRecord ()
References mTimerRecordCanceled, and TimerRecordDialog::RunWaitDialog().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTimeShiftTool ()
References SetTool(), and slideTool.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnToggle ()
References mTrackPanel, and TrackPanel::OnToggle().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTogglePlayRecording ()
References gPrefs, and ModifyToolbarMenus().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnToggleSoundActivated ()
References gPrefs, and ModifyToolbarMenus().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnToggleSWPlaythrough ()
References gPrefs, and ModifyToolbarMenus().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnToolBarUpdate (wxCommandEvent & event)
A toolbar has been updated, so handle it like a sizing event.
References HandleResize().
void AudacityProject::OnTrackClose ()
References mTrackPanel, and TrackPanel::OnTrackClose().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTrackGain ()
References mTrackPanel, and TrackPanel::OnTrackGain().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTrackGainDec ()
References mTrackPanel, and TrackPanel::OnTrackGainDec().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTrackGainInc ()
References mTrackPanel, and TrackPanel::OnTrackGainInc().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTrackListUpdated (wxCommandEvent & event)
References mViewInfo, and ViewInfo::track.
Referenced by AudacityProject(), and OnCloseWindow().
void AudacityProject::OnTrackMenu ()
References mTrackPanel.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTrackMute ()
References mTrackPanel, and TrackPanel::OnTrackMute().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTrackPan ()
References mTrackPanel, and TrackPanel::OnTrackPan().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTrackPanLeft ()
References mTrackPanel, and TrackPanel::OnTrackPanLeft().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTrackPanRight ()
References mTrackPanel, and TrackPanel::OnTrackPanRight().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTrackSolo ()
References mTrackPanel, and TrackPanel::OnTrackSolo().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnTrim ()
References TrackListIterator::First(), Track::GetKind(), Track::GetSelected(), mTracks, mViewInfo, TrackListIterator::Next(), PushState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, and Track::Wave.
Referenced by CreateMenusAndCommands(), and EditToolBar::OnButton().
void AudacityProject::OnUndo ()
References TrackPanel::EnsureVisible(), TrackPanel::GetFirstSelectedTrack(), mHistoryWindow, ModifyUndoMenus(), mTrackPanel, mUndoManager, mViewInfo, PopState(), RedrawProject(), ViewInfo::sel0, ViewInfo::sel1, TrackPanel::SetFocusedTrack(), UndoManager::Undo(), UndoManager::UndoAvailable(), and HistoryWindow::UpdateDisplay().
Referenced by CreateMenusAndCommands(), EditToolBar::OnButton(), OnCloseWindow(), and TrackPanel::OnTimer().
void AudacityProject::OnUnlockPlayRegion ()
References mLockPlayRegion, and mRuler.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnUnMuteAllTracks ()
References TrackListIterator::First(), mMixerBoard, ModifyState(), mTracks, TrackListIterator::Next(), RedrawProject(), Track::SetMute(), and MixerBoard::UpdateMute().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnUpdateUI (wxUpdateUIEvent & event)
References UpdateMenus().
void AudacityProject::OnUpload ()
Referenced by CreateMenusAndCommands().
void AudacityProject::OnZeroCrossing ()
References ModifyState(), mTrackPanel, mViewInfo, NearestZeroCrossing(), TrackPanel::Refresh(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by CreateMenusAndCommands().
void AudacityProject::OnZoomFit ()
References TrackList::GetEndTime(), TrackPanel::GetTracksUsableArea(), mTrackPanel, mTracks, TP_ScrollWindow(), and Zoom().
Referenced by AddImportedTracks(), CreateMenusAndCommands(), EditToolBar::OnButton(), OnEffect(), and RecoverAllProjects().
void AudacityProject::OnZoomFitV ()
References DoZoomFitV(), ModifyState(), mVsbar, and RedrawProject().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnZoomIn ()
References gAudioIO, GetAudioIOToken(), AudioIO::GetStreamTime(), ViewInfo::h, AudioIO::IsStreamActive(), mTrackPanel, mViewInfo, TrackPanel::Refresh(), ViewInfo::screen, TrackPanel::ScrollIntoView(), ViewInfo::sel0, ViewInfo::sel1, TP_ScrollWindow(), ViewInfo::zoom, and Zoom().
Referenced by CreateMenusAndCommands(), and EditToolBar::OnButton().
void AudacityProject::OnZoomNormal ()
References mTrackPanel, TrackPanel::Refresh(), and Zoom().
Referenced by CreateMenusAndCommands().
void AudacityProject::OnZoomOut ()
References ViewInfo::h, mViewInfo, ViewInfo::screen, TP_ScrollWindow(), ViewInfo::zoom, and Zoom().
Referenced by CreateMenusAndCommands(), and EditToolBar::OnButton().
void AudacityProject::OnZoomSel ()
References mViewInfo, ViewInfo::screen, ViewInfo::sel0, ViewInfo::sel1, TP_ScrollWindow(), ViewInfo::zoom, and Zoom().
Referenced by CreateMenusAndCommands(), and EditToolBar::OnButton().
void AudacityProject::OnZoomToggle ()
References ViewInfo::h, mViewInfo, ViewInfo::screen, TP_ScrollWindow(), Zoom(), and ViewInfo::zoom.
Referenced by EditToolBar::OnButton().
void AudacityProject::OnZoomTool ()
References SetTool(), and zoomTool.
Referenced by CreateMenusAndCommands().
void AudacityProject::OpenFile (wxString fileName, bool addtohistory = true)
Parse project file
References TrackList::Add(), AudacityApp::AddFileToHistory(), ODManager::AddNewTask(), ODTask::AddWaveTrack(), AutoSave(), TrackList::Clear(), ConvertLegacyProjectFile(), PlatformCompatibility::ConvertSlashInFileName(), Track::Duplicate(), ODTask::eODFLAC, ODTask::eODPCMSummary, DirManager::FillBlockfilesCache(), TrackListIterator::First(), FSCKstatus_CHANGED, FSCKstatus_CLOSEREQ, Track::GetChannel(), GetDirManager(), Track::GetErrorOpening(), XMLFileReader::GetErrorStr(), Track::GetKind(), Track::GetLink(), Track::GetLinked(), PlatformCompatibility::GetLongFileName(), HandleResize(), ODManager::HasLoadedODFlag(), Import(), InitialState(), ODManager::Instance(), LAT1CTOWX, Track::LeftChannel, mFileName, mIsRecovered, mLastSavedTracks, mRecordingRecoveryHandler, mRecoveryAutoSaveDataDir, mTrackPanel, mTracks, TrackListIterator::Next(), XMLFileReader::Parse(), DirManager::ProjectFSCK(), PushState(), TrackPanel::Refresh(), Track::RightChannel, TrackPanel::SetFocusedTrack(), Track::SetLinked(), SetProjectTitle(), ODManager::UnmarkLoadedODFlag(), WarnOfLegacyFile(), Track::Wave, and wxGetApp().
Referenced by LOFImportFileHandle::lofOpenFiles(), AudacityApp::MRUOpen(), AudacityApp::OnInit(), OnOpenAudioFile(), OpenFiles(), and RecoverAllProjects().
void AudacityProject::OpenFiles (AudacityProject * proj) [static]
References CompareNoCaseFileName(), CreateNewAudacityProject(), gAudacityProjects, gPrefs, TrackList::IsEmpty(), mDirty, mTracks, OpenFile(), ODManager::Pause(), ODManager::Resume(), and ShowOpenDialog().
Referenced by AudacityApp::OnMenuOpen(), and OnOpen().
void AudacityProject::PopState (TrackList * l) [private]
References TrackList::Add(), ODManager::AddNewTask(), ODTask::AddWaveTrack(), TrackList::Clear(), Track::Duplicate(), TrackListIterator::First(), Track::GetKind(), HandleResize(), ODManager::Instance(), ODManager::IsInstanceCreated(), mTracks, TrackListIterator::Next(), UpdateLyrics(), UpdateMenus(), UpdateMixerBoard(), and Track::Wave.
Referenced by OnRedo(), OnUndo(), and SetStateTo().
void AudacityProject::PrevFrame ()
References BotDockHasFocus, ToolManager::GetBotDock(), GetFocusedFrame(), ToolManager::GetTopDock(), mToolManager, mTrackPanel, TopDockHasFocus, and TrackPanelHasFocus.
Referenced by CreateMenusAndCommands().
void AudacityProject::PushState (wxString desc, wxString shortDesc, bool consolidate = false)
References AutoSaveIfNeeded(), DoZoomFitV(), gAudioIO, GetAudioIOToken(), GetTracksFitVerticallyZoomed(), AudioIO::IsStreamActive(), mDirty, mHistoryWindow, ModifyUndoMenus(), mTracks, mUndoManager, mViewInfo, UndoManager::PushState(), ViewInfo::sel0, ViewInfo::sel1, HistoryWindow::UpdateDisplay(), UpdateLyrics(), UpdateMenus(), and UpdateMixerBoard().
Referenced by AddImportedTracks(), BatchCommands::ApplyChain(), Clear(), DoAddLabel(), HandleAlign(), HandleMixAndRender(), OnCloseWindow(), OnCopyLabels(), OnCut(), OnCutLabels(), OnDeleteLabels(), OnDisjoin(), OnDisjoinLabels(), OnDuplicate(), OnEditLabels(), OnEditMetadata(), OnEffect(), OnImportLabels(), OnImportMIDI(), OnJoin(), OnJoinLabels(), OnNewLabelTrack(), OnNewStereoTrack(), OnNewTimeTrack(), OnNewWaveTrack(), OnPaste(), OnPasteNewLabel(), OnRemoveTracks(), OnResample(), OnSilence(), OnSilenceLabels(), OnSortName(), OnSortTime(), OnSplit(), OnSplitCut(), OnSplitCutLabels(), OnSplitDelete(), OnSplitDeleteLabels(), OnSplitLabels(), OnSplitLabelsToTracks(), OnSplitNew(), OnTrim(), OpenFile(), and TP_PushState().
void AudacityProject::RebuildMenuBar ()
References CreateMenusAndCommands(), ModuleManager::Dispatch(), AudacityApp::GetRecentFiles(), mCommandManager, MenusRebuilt, mRecentFilesMenu, CommandManager::PurgeData(), FileHistory::RemoveMenu(), and wxGetApp().
Referenced by OnPreferences(), and OnSimplifiedView().
void AudacityProject::RebuildOtherMenus ()
References TrackPanel::BuildMenus(), and mTrackPanel.
Referenced by OnPreferences().
void AudacityProject::RedrawProject (const bool bForceWaveTracks = false)
References TrackListIterator::First(), FixScrollbars(), WaveTrack::GetClipIterator(), Track::GetKind(), WaveClip::MarkChanged(), mTrackPanel, mTracks, TrackListIterator::Next(), TrackPanel::Refresh(), and Track::Wave.
Referenced by AS_SetSnapTo(), Clear(), DoAddLabel(), HandleAlign(), TrackPanel::HandleMinimizing(), HandleMixAndRender(), TranscriptionToolBar::OnAutomateSelection(), MixerTrackCluster::OnButton_Mute(), MixerTrackCluster::OnButton_Solo(), OnCloseWindow(), OnCollapseAllTracks(), OnCut(), OnCutLabels(), OnDeleteLabels(), OnDisjoin(), OnDisjoinLabels(), OnDuplicate(), OnEditLabels(), OnEffect(), TranscriptionToolBar::OnEndOff(), TranscriptionToolBar::OnEndOn(), OnExpandAllTracks(), OnImportLabels(), OnImportMIDI(), OnJoin(), OnJoinLabels(), OnMuteAllTracks(), OnNewLabelTrack(), OnNewStereoTrack(), OnNewTimeTrack(), OnNewWaveTrack(), OnPaste(), OnPasteNewLabel(), CommandHandler::OnReceiveCommand(), OnRedo(), OnResample(), LabelDialog::OnSelectCell(), TranscriptionToolBar::OnSelectSilence(), TranscriptionToolBar::OnSelectSound(), ScreenFrame::OnShortTracks(), OnSplitCut(), OnSplitCutLabels(), OnSplitDelete(), OnSplitDeleteLabels(), OnSplitLabels(), OnSplitLabelsToTracks(), OnSplitNew(), TranscriptionToolBar::OnStartOff(), TranscriptionToolBar::OnStartOn(), TrackPanel::OnTimer(), OnTrim(), OnUndo(), OnUnMuteAllTracks(), OnZoomFitV(), ScreenFrame::SizeTracks(), and ScreenFrame::TimeZoom().
void AudacityProject::RefreshCursor ()
References TrackPanel::HandleCursorForLastMouseEvent(), and mTrackPanel.
void AudacityProject::RefreshTPTrack (Track * pTrk, bool refreshbacking = true) [virtual]
References mTrackPanel, and TrackPanel::RefreshTrack().
Referenced by MixerTrackCluster::HandleSelect(), MixerTrackCluster::HandleSliderGain(), MixerTrackCluster::HandleSliderPan(), MixerTrackCluster::OnButton_Mute(), and MixerTrackCluster::OnButton_Solo().
void AudacityProject::ReleaseKeyboard (wxWindow * h)
References mKeyboardCaptured.
Referenced by OnReleaseKeyboard().
void AudacityProject::ResetTimerRecordFlag () [inline]
Referenced by OnCloseWindow(), and TrackPanel::OnTimer().
void AudacityProject::Rewind (bool shift)
References mViewInfo, ViewInfo::sel0, ViewInfo::sel1, and TP_ScrollWindow().
Referenced by ControlToolBar::OnRewind(), and OnSelToStart().
void AudacityProject::SafeDisplayStatusMessage (const wxChar * msg)
References CommandType::Create(), CommandDirectory::Get(), CommandDirectory::LookUp(), TargetFactory::MessageDefault(), mLastStatusUpdateTime, mStatusBar, ScriptCommandRelay::PostCommand(), TargetFactory::ProgressDefault(), and Command::SetParameter().
Referenced by ExecCommand().
bool AudacityProject::Save (bool overwrite = true, bool fromSaveAs = false, bool bWantSaveCompressed = false)
References TrackList::Add(), TrackList::Clear(), XMLFileWriter::Close(), DeleteCurrentAutoSaveFile(), Track::Duplicate(), TrackListIterator::First(), TrackList::GetEndTime(), Track::GetKind(), XMLFileWriterException::GetMessage(), DirManager::GetProjectName(), mCleanSpeechMode, mDirManager, mEmptyCanBeDirty, mFileName, mImportedDependencies, mIsRecovered, mLastSavedTracks, mRecoveryAutoSaveDataDir, mStatusBar, mTracks, mUndoManager, mWantSaveCompressed, TrackListIterator::Next(), XMLFileWriter::Open(), Exporter::Process(), DirManager::RemoveOrphanedBlockfiles(), SaveAs(), SaveCompressedWaveTracks(), DirManager::SetProject(), SetProjectTitle(), ShowDependencyDialogIfNeeded(), UndoManager::StateSaved(), UndoManager::UnsavedChanges(), Track::Wave, WriteXML(), and WriteXMLHeader().
Referenced by InitialState(), OnCloseWindow(), OnSave(), and SaveAs().
bool AudacityProject::SaveAs (bool bWantSaveCompressed = false)
References AudacityApp::AddFileToHistory(), GetName(), mCleanSpeechMode, mFileName, Save(), SetProjectTitle(), ShowWarningDialog(), and wxGetApp().
Referenced by OnSaveAs(), OnSaveCompressed(), and Save().
bool AudacityProject::SaveCompressedWaveTracks (const wxString strProjectPathName)
References TrackList::Add(), TrackList::Clear(), TrackFactory::DuplicateWaveTrack(), TrackListIterator::First(), TrackListCondIterator::First(), Track::GetEndTime(), Track::GetKind(), Track::GetLinked(), Track::GetMute(), Track::GetName(), Track::GetSelected(), Track::GetSolo(), Track::GetStartTime(), FileNames::MakeNameUnique(), mStrOtherNamesArray, mTrackFactory, mTracks, TrackListIterator::Next(), TrackListCondIterator::Next(), Exporter::Process(), WaveTrack::SetGain(), Track::SetMute(), WaveTrack::SetPan(), Track::SetSelected(), Track::SetSolo(), and Track::Wave.
Referenced by Save().
void AudacityProject::SelectAllIfNone ()
References GetUpdateFlags(), mViewInfo, OnSelectAll(), ViewInfo::sel0, ViewInfo::sel1, and TracksSelectedFlag.
Referenced by BatchCommands::ApplyEffectCommand(), and Import().
void AudacityProject::SelectNone ()
References TrackListIterator::First(), mMixerBoard, mTrackPanel, mTracks, TrackListIterator::Next(), TrackPanel::Refresh(), and Track::SetSelected().
Referenced by AddImportedTracks(), MixerTrackCluster::HandleSelect(), Import(), OnImportLabels(), OnImportMIDI(), MixerBoardScrolledWindow::OnMouseEvent(), OnNewLabelTrack(), OnNewStereoTrack(), OnNewTimeTrack(), OnNewWaveTrack(), and OnSelectNone().
void AudacityProject::SetAudioIOToken (int token)
References mAudioIOToken.
Referenced by OnCloseWindow(), ControlToolBar::OnRecord(), TrackPanel::OnTimer(), and ControlToolBar::PlayPlayRegion().
void AudacityProject::SetCleanSpeechMode (bool flag) [inline]
void AudacityProject::SetNormalizedWindowState (wxRect pSizeAndLocation) [inline]
Referenced by OnMove(), and OnSize().
void AudacityProject::SetNormalizeOnLoad (bool flag) [inline]
void AudacityProject::SetProjectTitle ()
References GetName(), mCleanSpeechMode, and mIsRecovered.
Referenced by AddImportedTracks(), HandleXMLTag(), OpenFile(), Save(), SaveAs(), and UpdatePrefs().
void AudacityProject::SetSel0 (double newSel0)
References mViewInfo, and ViewInfo::sel0.
Referenced by HighlightTextCtrl::OnMouseEvent(), TranscriptionToolBar::OnSelectSilence(), TranscriptionToolBar::OnSelectSound(), TranscriptionToolBar::OnStartOff(), and TranscriptionToolBar::OnStartOn().
void AudacityProject::SetSel1 (double newSel1)
References mViewInfo, and ViewInfo::sel1.
Referenced by TranscriptionToolBar::OnEndOff(), TranscriptionToolBar::OnEndOn(), TranscriptionToolBar::OnSelectSilence(), and TranscriptionToolBar::OnSelectSound().
void AudacityProject::SetShowId3Dialog (bool flag) [inline]
Referenced by BatchCommands::ApplyCommandInBatchMode().
void AudacityProject::SetSnapTo (bool state)
References CommandManager::Check(), GetSelectionBar(), gPrefs, mCommandManager, and SelectionBar::SetSnapTo().
Referenced by AS_SetSnapTo(), OnSnapToOff(), OnSnapToOn(), and UpdatePrefs().
void AudacityProject::SetStateTo (unsigned int n)
References HandleResize(), ModifyUndoMenus(), mTrackPanel, mUndoManager, mViewInfo, PopState(), TrackPanel::Refresh(), ViewInfo::sel0, ViewInfo::sel1, TrackPanel::SetFocusedTrack(), UndoManager::SetStateTo(), UpdateLyrics(), and UpdateMixerBoard().
Referenced by BatchCommands::ApplyChain(), HistoryWindow::OnDiscard(), and HistoryWindow::OnItemSelected().
void AudacityProject::SetStickyFlag (bool flag) [inline]
Referenced by OnStickyLabel().
void AudacityProject::SetStop (bool bStopped)
References mTrackPanel, and TrackPanel::SetStop().
void AudacityProject::SetTool (int tool)
References GetToolsToolBar(), mTrackPanel, TrackPanel::Refresh(), and ToolsToolBar::SetCurrentTool().
Referenced by OnDrawTool(), OnEnvelopeTool(), OnMultiTool(), OnSelectTool(), OnTimeShiftTool(), and OnZoomTool().
void AudacityProject::SetTracksFitVerticallyZoomed (bool flag) [inline]
wxArrayString AudacityProject::ShowOpenDialog (wxString extraformat = wxEmptyString, wxString extrafilter = wxEmptyString) [static]
Show an open dialogue for opening audio files, and possibly other sorts of files.
The file type filter will automatically contain:
"All files" with any extension or none,
"All supported files" based on the file formats supported in this build of Audacity,
All of the individual formats specified by the importer plug-ins which are built into this build of Audacity, each with the relevant file extensions for that format. The dialogue will start in the DefaultOpenPath directory read from the preferences, failing that the working directory. The file format filter will be set to the DefaultOpenType from the preferences, failing that the first format specified in the dialogue. These two parameters will be saved to the preferences once the user has chosen a file to open.
Parameters:
extraformat Specify the name of an additional format to allow opening in this dialogue. This string is free-form, but should be short enough to fit in the file dialogue filter drop-down. It should be translated.
extrafilter Specify the file extension(s) for the additional format specified by extraformat. The patterns must include the wildcard (e.g. "*.aup" not "aup" or ".aup"), separate multiple patters with a semicolon, e.g. "*.aup;*.AUP" because patterns are case-sensitive. Do not add a trailing semicolon to the string. This string should not be translated
Returns:
Array of file paths which the user selected to open (multiple selections allowed).
< List of file format names and extensions, separated
by | characters between _formats_ and extensions for each _format_, i.e. format1name | *.ext | format2name | *.ex1;*.ex2
< One long list of all supported file extensions,
semicolon separated
References Format::formatExtensions, Format::formatName, Importer::GetSupportedImportFormats(), gPrefs, AudacityApp::mImporter, and wxGetApp().
Referenced by OnImport(), and OpenFiles().
void AudacityProject::SkipEnd (bool shift)
References TrackList::GetEndTime(), mTrackPanel, mTracks, mViewInfo, TrackPanel::Refresh(), TrackPanel::ScrollIntoView(), ViewInfo::sel0, and ViewInfo::sel1.
Referenced by ControlToolBar::OnFF(), and OnSelToEnd().
void AudacityProject::TP_DisplaySelection () [virtual]
Implements TrackPanelListener.
References gAudioIO, GetSelectionBar(), AudioIO::GetStreamTime(), AudioIO::IsBusy(), mLockPlayRegion, mRuler, mViewInfo, ViewInfo::sel0, ViewInfo::sel1, AdornedRulerPanel::SetPlayRegion(), and SelectionBar::SetTimes().
Referenced by ControlToolBar::OnPlay(), and OnPlayStop().
void AudacityProject::TP_DisplayStatusMessage (wxString msg) [virtual]
Implements TrackPanelListener.
References mLastStatusUpdateTime, and mStatusBar.
Referenced by Meter::OnMouse(), LWSlider::OnMouseEvent(), and AButton::OnMouseEvent().
ControlToolBar * AudacityProject::TP_GetControlToolBar () [virtual]
Implements TrackPanelListener.
References GetControlToolBar().
int AudacityProject::TP_GetCurrentTool () [virtual]
Implements TrackPanelListener.
References ToolsToolBar::GetCurrentTool(), and GetToolsToolBar().
ToolsToolBar * AudacityProject::TP_GetToolsToolBar () [virtual]
Implements TrackPanelListener.
References GetToolsToolBar().
void AudacityProject::TP_HandleResize () [virtual]
Implements TrackPanelListener.
References HandleResize().
void AudacityProject::TP_ModifyState () [virtual]
Implements TrackPanelListener.
References ModifyState().
void AudacityProject::TP_OnPlayKey () [virtual]
Implements TrackPanelListener.
References OnPlayStop().
void AudacityProject::TP_PushState (wxString longDesc, wxString shortDesc, bool consolidate) [virtual]
Implements TrackPanelListener.
References PushState().
Referenced by MixerTrackCluster::HandleSliderGain(), and MixerTrackCluster::HandleSliderPan().
void AudacityProject::TP_RedrawScrollbars () [virtual]
Implements TrackPanelListener.
References FixScrollbars().
void AudacityProject::TP_ScrollLeft () [virtual]
Implements TrackPanelListener.
References OnScrollLeft().
void AudacityProject::TP_ScrollRight () [virtual]
Implements TrackPanelListener.
References OnScrollRight().
void AudacityProject::TP_ScrollUpDown (int delta) [virtual]
Implements TrackPanelListener.
References max, mVsbar, and OnScroll().
void AudacityProject::TP_ScrollWindow (double scrollto) [virtual]
Implements TrackPanelListener.
References max, mHsbar, mViewInfo, OnScroll(), ViewInfo::sbarScale, and ViewInfo::zoom.
Referenced by LOFImportFileHandle::doScrollOffset(), OnZoomFit(), OnZoomIn(), OnZoomOut(), OnZoomSel(), OnZoomToggle(), and Rewind().
bool AudacityProject::TryToMakeActionAllowed (wxUint32 & flags, wxUint32 flagsRqd, wxUint32 mask)
Determines if flags for command are compatible with current state. If not, then try some recovery action to make it so.
Returns:
whether compatible or not after any actions taken.
References GetUpdateFlags(), mSelectAllOnNone, OnSelectAll(), TimeSelectedFlag, WaveTracksExistFlag, and WaveTracksSelectedFlag.
Referenced by CommandManager::HandleCommandEntry().
void AudacityProject::UpdateFirstVisible ()
References Track::GetHeight(), TrackList::GetNext(), TrackList::GetPrev(), Track::GetY(), mTracks, mViewInfo, ViewInfo::track, and ViewInfo::vpos.
Referenced by FixScrollbars(), and OnScroll().
void AudacityProject::UpdateLayout ()
References ToolManager::GetBotDock(), ToolManager::LayoutToolBars(), mToolManager, and mTrackPanel.
Referenced by FixScrollbars(), and HandleResize().
void AudacityProject::UpdateLyrics () [private]
References Lyrics::Add(), Lyrics::Clear(), Lyrics::Finish(), TrackListCondIterator::First(), LabelTrack::GetEndTime(), LabelTrack::GetLabel(), LyricsWindow::GetLyricsPanel(), LabelTrack::GetNumLabels(), GetSel0(), Track::Label, mLyricsWindow, mTracks, LabelStruct::t, LabelStruct::title, and Lyrics::Update().
Referenced by InitialState(), PopState(), PushState(), and SetStateTo().
void AudacityProject::UpdateMenus ()
References CutCopyAvailableFlag, CommandManager::Enable(), CommandManager::EnableUsingFlags(), GetActiveProject(), GetUpdateFlags(), IsActive(), mCommandManager, mLastFlags, ModifyToolbarMenus(), mSelectAllOnNone, TimeSelectedFlag, TracksExistFlag, TracksSelectedFlag, WaveTracksExistFlag, and WaveTracksSelectedFlag.
Referenced by FixScrollbars(), InitialState(), OnUpdateUI(), PopState(), and PushState().
void AudacityProject::UpdateMixerBoard () [private]
References gAudioIO, AudioIO::GetStreamTime(), loopedPlay, mLastPlayMode, mMixerBoard, MixerBoard::UpdateMeters(), and MixerBoard::UpdateTrackClusters().
Referenced by InitialState(), PopState(), PushState(), and SetStateTo().
void AudacityProject::UpdatePrefs ()
References gPrefs, mLastFocusedWindow, mMixerBoard, mToolManager, mTrackPanel, MixerBoard::ResizeTrackClusters(), SetProjectTitle(), SetSnapTo(), ToolManager::UpdatePrefs(), TrackPanel::UpdatePrefs(), and UpdatePrefsVariables().
Referenced by DeviceToolBar::OnChoice().
void AudacityProject::UpdatePrefsVariables ()
References ViewInfo::bUpdateTrackIndicator, AudioIO::GetOptimalSupportedSampleRate(), gPrefs, mCleanSpeechMode, mDefaultFormat, mEmptyCanBeDirty, mHelpPref, mNormalizeOnLoad, mRate, mSelectAllOnNone, mShowId3Dialog, mShowSplashScreen, mSoloPref, mTracksFitVerticallyZoomed, and mViewInfo.
Referenced by UpdatePrefs().
bool AudacityProject::WarnOfLegacyFile ()
Referenced by OpenFile().
void AudacityProject::WriteXML (XMLWriter & xmlFile) [virtual]
References AUDACITY_FILE_FORMAT_VERSION, AUDACITY_VERSION_STRING, XMLWriter::EndTag(), TrackListIterator::First(), Track::GetActualHeight(), DirManager::GetDataFilesDir(), WaveTrack::GetGain(), Track::GetKind(), Track::GetLinked(), Track::GetMinimized(), Track::GetMute(), Track::GetOffset(), WaveTrack::GetPan(), DirManager::GetProjectName(), Track::GetSolo(), ViewInfo::h, mAutoSaving, mDirManager, mFileName, mRate, mStrOtherNamesArray, mTags, mTracks, mViewInfo, mWantSaveCompressed, TrackListIterator::Next(), ViewInfo::sel0, ViewInfo::sel1, XMLWriter::StartTag(), ViewInfo::vpos, Track::Wave, XMLWriter::WriteAttr(), Track::WriteXML(), Tags::WriteXML(), and ViewInfo::zoom.
Referenced by AutoSave(), and Save().
void AudacityProject::WriteXMLHeader (XMLWriter & xmlFile)
References XMLWriter::Write().
Referenced by AutoSave(), and Save().
void AudacityProject::Zoom (double level)
References FixScrollbars(), gMaxZoom, gMinZoom, mViewInfo, and ViewInfo::zoom.
Referenced by LOFImportFileHandle::doDuration(), OnZoomFit(), OnZoomIn(), OnZoomNormal(), OnZoomOut(), OnZoomSel(), and OnZoomToggle().
Friends And Related Function Documentation
friend class ScreenshotCommand [friend]
Member Data Documentation
bool AudacityProject::mActive [private]
Referenced by IsActive(), and OnActivate().
int AudacityProject::mAudioIOToken [private]
Referenced by GetAudioIOToken(), and SetAudioIOToken().
wxString AudacityProject::mAutoSaveFileName [private]
Referenced by AutoSave(), AutoSaveIfNeeded(), DeleteCurrentAutoSaveFile(), and OnAudioIONewBlockFiles().
bool AudacityProject::mAutoSaving [private]
Referenced by AutoSave(), and WriteXML().
bool AudacityProject::mAutoScrolling [private]
Referenced by FinishAutoScroll(), and OnScroll().
bool AudacityProject::mCleanSpeechMode [private]
Referenced by CreateMenusAndCommands(), OnProcessEffect(), Save(), SaveAs(), SetProjectTitle(), and UpdatePrefsVariables().
CommandManager AudacityProject::mCommandManager [private]
Referenced by CreateMenusAndCommands(), HandleKeyDown(), ModifyToolbarMenus(), ModifyUndoMenus(), OnEffect(), OnMenu(), OnMenuEvent(), OnShowClipping(), OnSimplifiedView(), RebuildMenuBar(), SetSnapTo(), and UpdateMenus().
sampleFormat AudacityProject::mDefaultFormat [private]
Referenced by HandleMixAndRender(), OnNewStereoTrack(), OnNewWaveTrack(), and UpdatePrefsVariables().
DirManager* AudacityProject::mDirManager [private]
Referenced by AddImportedTracks(), DoAddLabel(), GetDirManager(), HandleXMLTag(), OnAudioIOStopRecording(), OnCloseWindow(), OnEditLabels(), OnImportLabels(), OnImportMIDI(), OnNewLabelTrack(), OnNewTimeTrack(), OnPasteNewLabel(), OnTimer(), Save(), and WriteXML().
bool AudacityProject::mDirty [private]
Referenced by OpenFiles(), and PushState().
bool AudacityProject::mEmptyCanBeDirty [private]
Referenced by OnCloseWindow(), Save(), and UpdatePrefsVariables().
wxString AudacityProject::mFileName [private]
Referenced by AddImportedTracks(), AutoSave(), GetName(), HandleXMLTag(), OpenFile(), Save(), SaveAs(), and WriteXML().
FreqWindow* AudacityProject::mFreqWindow [private]
Referenced by OnCloseWindow(), and OnPlotSpectrum().
wxString AudacityProject::mHelpPref
Referenced by ShowHelpDialog(), and UpdatePrefsVariables().
HistoryWindow* AudacityProject::mHistoryWindow [private]
Referenced by InitialState(), OnCloseWindow(), OnHistory(), OnRedo(), OnUndo(), and PushState().
wxScrollBar* AudacityProject::mHsbar [private]
Referenced by FixScrollbars(), OnScroll(), OnScrollLeft(), OnScrollLeftButton(), OnScrollRight(), OnScrollRightButton(), and TP_ScrollWindow().
bool AudacityProject::mIconized [private]
Referenced by OnIconize().
bool AudacityProject::mImportedDependencies [private]
Referenced by AddImportedTracks(), and Save().
ImportXMLTagHandler* AudacityProject::mImportXMLTagHandler [private]
Referenced by HandleXMLChild(), InitialState(), and OnCloseWindow().
bool AudacityProject::mIsDeleting [private]
Referenced by OnActivate(), and OnCloseWindow().
bool AudacityProject::mIsRecovered [private]
Referenced by HandleXMLTag(), OpenFile(), Save(), and SetProjectTitle().
wxWindow* AudacityProject::mKeyboardCaptured [private]
Referenced by CaptureKeyboard(), HasKeyboardCapture(), and ReleaseKeyboard().
long AudacityProject::mLastAutoSaveTime [private]
Referenced by AutoSave(), and AutoSaveIfNeeded().
Effect* AudacityProject::mLastEffect [private]
Referenced by CreateMenusAndCommands(), GetUpdateFlags(), OnEffect(), and OnRepeatLastEffect().
int AudacityProject::mLastEffectType [private]
Referenced by CreateMenusAndCommands(), OnEffect(), and OnRepeatLastEffect().
wxUint32 AudacityProject::mLastFlags [private]
Referenced by CreateMenusAndCommands(), and UpdateMenus().
wxWindow* AudacityProject::mLastFocusedWindow [private]
Referenced by OnActivate(), OnCloseWindow(), and UpdatePrefs().
PlayMode AudacityProject::mLastPlayMode
Referenced by TrackPanel::DoDrawIndicator(), OnPlayOneSecond(), OnPlayToSelection(), TrackPanel::OnTimer(), ControlToolBar::PlayCurrentRegion(), and UpdateMixerBoard().
TrackList* AudacityProject::mLastSavedTracks [private]
Referenced by OnCloseWindow(), OpenFile(), and Save().
long AudacityProject::mLastStatusUpdateTime [private]
Referenced by OnTimer(), SafeDisplayStatusMessage(), and TP_DisplayStatusMessage().
bool AudacityProject::mLockPlayRegion [private]
Referenced by OnLockPlayRegion(), OnUnlockPlayRegion(), and TP_DisplaySelection().
LyricsWindow* AudacityProject::mLyricsWindow [private]
Referenced by OnKaraoke(), and UpdateLyrics().
wxPanel* AudacityProject::mMainPanel [private]
MixerBoard* AudacityProject::mMixerBoard [private]
Referenced by OnMixerBoard(), OnMuteAllTracks(), OnRemoveTracks(), OnSelectAll(), OnUnMuteAllTracks(), SelectNone(), UpdateMixerBoard(), and UpdatePrefs().
MixerBoardFrame* AudacityProject::mMixerBoardFrame [private]
Referenced by OnMixerBoard().
wxRect AudacityProject::mNormalizedWindowState [private]
bool AudacityProject::mNormalizeOnLoad [private]
Referenced by UpdatePrefsVariables().
double AudacityProject::mRate [private]
Referenced by AddImportedTracks(), AS_SetRate(), HandleMixAndRender(), HandleXMLTag(), OnEffect(), OnSetLeftSelection(), OnSetRightSelection(), UpdatePrefsVariables(), and WriteXML().
wxMenu* AudacityProject::mRecentFilesMenu [private]
Referenced by CreateRecentFilesMenu(), RebuildMenuBar(), and ~AudacityProject().
RecordingRecoveryHandler* AudacityProject::mRecordingRecoveryHandler [private]
Referenced by HandleXMLChild(), and OpenFile().
wxString AudacityProject::mRecoveryAutoSaveDataDir [private]
Referenced by HandleXMLTag(), OpenFile(), and Save().
AdornedRulerPanel* AudacityProject::mRuler [private]
Referenced by GetPlayRegion(), GetRulerPanel(), OnLockPlayRegion(), OnUnlockPlayRegion(), and TP_DisplaySelection().
ODLock * AudacityProject::msAllProjectDeleteMutex = new ODLock() [static, private]
Referenced by AllProjectsDeleteLock(), AllProjectsDeleteUnlock(), and DeleteAllProjectsDeleteLock().
TrackList * AudacityProject::msClipboard = new TrackList() [static, private]
Referenced by ClearClipboard(), DeleteClipboard(), EditClipboardByLabel(), OnCopy(), OnCut(), OnPaste(), and OnSplitCut().
double AudacityProject::msClipLen = 0.0 [static, private]
Referenced by ClearClipboard(), EditClipboardByLabel(), GetUpdateFlags(), OnCopy(), OnCut(), OnPaste(), OnPasteOver(), and OnSplitCut().
AudacityProject * AudacityProject::msClipProject = NULL [static, private]
Referenced by ClearClipboard(), OnCopy(), OnCopyLabels(), OnCut(), OnCutLabels(), OnPaste(), OnSplitCut(), and OnSplitCutLabels().
double AudacityProject::mSel0save
Referenced by CreateMenusAndCommands(), OnSelectionRestore(), and OnSelectionSave().
double AudacityProject::mSel1save
Referenced by CreateMenusAndCommands(), OnSelectionRestore(), and OnSelectionSave().
bool AudacityProject::mSelectAllOnNone [private]
Referenced by TryToMakeActionAllowed(), UpdateMenus(), and UpdatePrefsVariables().
bool AudacityProject::mShowId3Dialog [private]
Referenced by UpdatePrefsVariables().
bool AudacityProject::mShowSplashScreen
Referenced by AudacityApp::OnInit(), and UpdatePrefsVariables().
bool AudacityProject::mSnapTo [private]
wxString AudacityProject::mSoloPref
Referenced by UpdatePrefsVariables().
wxStatusBar* AudacityProject::mStatusBar [private]
Referenced by OnAudioIORate(), OnTimer(), SafeDisplayStatusMessage(), Save(), and TP_DisplayStatusMessage().
bool AudacityProject::mStickyFlag [private]
Referenced by ModifyToolbarMenus().
wxArrayString AudacityProject::mStrOtherNamesArray [private]
Referenced by SaveCompressedWaveTracks(), and WriteXML().
Tags* AudacityProject::mTags [private]
Referenced by GetTags(), HandleXMLChild(), Import(), OnCloseWindow(), OnEditMetadata(), and WriteXML().
wxTimer* AudacityProject::mTimer [private]
Referenced by OnCloseWindow().
bool AudacityProject::mTimerRecordCanceled [private]
Referenced by OnTimerRecord().
ToolManager* AudacityProject::mToolManager
Referenced by ScreenshotCommand::Apply(), GetControlToolBar(), GetDeviceToolBar(), GetEditToolBar(), GetFocusedFrame(), GetMeterToolBar(), GetMixerToolBar(), GetSelectionBar(), GetToolsToolBar(), GetTranscriptionToolBar(), ModifyToolbarMenus(), NextFrame(), OnCloseWindow(), OnResetToolBars(), OnShowControlToolBar(), OnShowDeviceToolBar(), OnShowEditToolBar(), OnShowMeterToolBar(), OnShowMixerToolBar(), OnShowSelectionToolBar(), OnShowToolsToolBar(), OnShowTranscriptionToolBar(), PrevFrame(), ScreenFrame::ScreenFrame(), ScreenFrame::SizeMainWindow(), UpdateLayout(), and UpdatePrefs().
TrackFactory* AudacityProject::mTrackFactory [private]
Referenced by GetTrackFactory(), HandleMixAndRender(), HandleXMLChild(), Import(), OnCloseWindow(), OnEffect(), OnImportRaw(), OnNewStereoTrack(), OnNewWaveTrack(), OnPaste(), and SaveCompressedWaveTracks().
TrackPanel* AudacityProject::mTrackPanel [private]
Referenced by AddImportedTracks(), ScreenshotCommand::Apply(), AS_ModifySelection(), DoAddLabel(), DoZoomFitV(), FixScrollbars(), GetFocusedFrame(), GetTPTracksUsableArea(), HandleKeyDown(), HandleKeyUp(), HandleMixAndRender(), HandleResize(), NextFrame(), OnActivate(), OnCloseWindow(), OnCopy(), OnCopyLabels(), OnCursorDown(), OnCursorLeft(), OnCursorLongJumpLeft(), OnCursorLongJumpRight(), OnCursorRight(), OnCursorSelEnd(), OnCursorSelStart(), OnCursorShortJumpLeft(), OnCursorShortJumpRight(), OnCursorTrackEnd(), OnCursorTrackStart(), OnCursorUp(), OnCut(), OnEffect(), OnImportMIDI(), OnNewLabelTrack(), OnNewStereoTrack(), OnNewTimeTrack(), OnNewWaveTrack(), OnNextTool(), OnODTaskComplete(), OnODTaskUpdate(), OnPaste(), OnPasteNewLabel(), OnPlayOneSecond(), OnPlayToSelection(), OnPrevTool(), OnRedo(), OnRemoveTracks(), OnScroll(), OnSeekLeftLong(), OnSeekLeftShort(), OnSeekRightLong(), OnSeekRightShort(), OnSelContractLeft(), OnSelContractRight(), OnSelectAll(), OnSelectCursorEnd(), OnSelectionRestore(), OnSelectStartCursor(), OnSelExtendLeft(), OnSelExtendRight(), OnSelSetExtendLeft(), OnSelSetExtendRight(), OnSetLeftSelection(), OnSetRightSelection(), OnShiftDown(), OnShiftUp(), OnShowClipping(), OnSilence(), OnSilenceLabels(), OnSortName(), OnSortTime(), OnSplit(), OnToggle(), OnTrackClose(), OnTrackGain(), OnTrackGainDec(), OnTrackGainInc(), OnTrackMenu(), OnTrackMute(), OnTrackPan(), OnTrackPanLeft(), OnTrackPanRight(), OnTrackSolo(), OnUndo(), OnZeroCrossing(), OnZoomFit(), OnZoomIn(), OnZoomNormal(), OpenFile(), PrevFrame(), RebuildOtherMenus(), RedrawProject(), RefreshCursor(), RefreshTPTrack(), SelectNone(), SetStateTo(), SetStop(), SetTool(), SkipEnd(), UpdateLayout(), and UpdatePrefs().
TrackList* AudacityProject::mTracks [private]
Referenced by AddImportedTracks(), Clear(), DoAddLabel(), DoZoomFitV(), EditByLabel(), EditClipboardByLabel(), FixScrollbars(), GetFirstVisible(), GetRegionsByLabel(), GetUpdateFlags(), HandleAlign(), HandleMixAndRender(), HandleTrackMute(), HandleTrackSolo(), HandleXMLChild(), InitialState(), ModifyState(), NearestZeroCrossing(), OnCloseWindow(), OnCollapseAllTracks(), OnCopy(), OnCursorTrackEnd(), OnCursorTrackStart(), OnCut(), OnDisjoin(), OnDuplicate(), OnEditLabels(), OnEffect(), OnExpandAllTracks(), OnExport(), OnExportLabels(), OnExportMIDI(), OnImportLabels(), OnImportMIDI(), OnJoin(), OnMuteAllTracks(), OnNewLabelTrack(), OnNewStereoTrack(), OnNewTimeTrack(), OnNewWaveTrack(), OnPaste(), OnPasteNewLabel(), OnPrint(), OnRemoveTracks(), OnResample(), OnSelectAll(), OnSelectCursorEnd(), OnSelectStartCursor(), OnSilence(), OnSortName(), OnSortTime(), OnSplit(), OnSplitCut(), OnSplitDelete(), OnSplitLabelsToTracks(), OnSplitNew(), OnTrim(), OnUnMuteAllTracks(), OnZoomFit(), OpenFile(), OpenFiles(), PopState(), PushState(), RedrawProject(), Save(), SaveCompressedWaveTracks(), SelectNone(), SkipEnd(), UpdateFirstVisible(), UpdateLyrics(), and WriteXML().
bool AudacityProject::mTracksFitVerticallyZoomed [private]
Referenced by UpdatePrefsVariables().
UndoManager AudacityProject::mUndoManager [private]
Referenced by GetUpdateFlags(), InitialState(), ModifyState(), ModifyUndoMenus(), OnCloseWindow(), OnHistory(), OnRedo(), OnUndo(), PushState(), Save(), and SetStateTo().
ViewInfo AudacityProject::mViewInfo
Referenced by SelectCommand::Apply(), ExportCommand::Apply(), AS_ModifySelection(), LabelTrack::CaptureKey(), Clear(), FixScrollbars(), FreqWindow::GetAudio(), GetFirstVisible(), GetRegionsByLabel(), CompareAudioCommand::GetSelection(), GetUpdateFlags(), HandleAlign(), MixerTrackCluster::HandleSelect(), HandleXMLTag(), InitialState(), ModifyState(), OnAddLabel(), OnCopy(), OnCopyLabels(), OnCursorSelEnd(), OnCursorSelStart(), OnCursorTrackEnd(), OnCursorTrackStart(), OnCut(), OnCutLabels(), OnDeleteLabels(), OnDisjoin(), OnDisjoinLabels(), OnDuplicate(), OnEditLabels(), OnEffect(), OnExportSelection(), OnJoin(), OnJoinLabels(), HighlightTextCtrl::OnMouseEvent(), OnPaste(), OnPasteNewLabel(), OnPasteOver(), OnPlayStopSelect(), OnPlayToSelection(), OnRedo(), OnScroll(), OnScrollLeft(), OnScrollLeftButton(), OnScrollRight(), OnScrollRightButton(), OnSelectAll(), OnSelectCursorEnd(), OnSelectionRestore(), OnSelectionSave(), OnSelectNone(), OnSelectStartCursor(), OnSetLeftSelection(), OnSetRightSelection(), OnSilence(), OnSilenceLabels(), OnSplit(), OnSplitCut(), OnSplitCutLabels(), OnSplitDelete(), OnSplitDeleteLabels(), OnSplitNew(), OnStopSelect(), OnTrackListUpdated(), OnTrim(), OnUndo(), ContrastDialog::OnUseSelectionB(), ContrastDialog::OnUseSelectionF(), OnZeroCrossing(), OnZoomIn(), OnZoomOut(), OnZoomSel(), OnZoomToggle(), PushState(), Rewind(), SelectAllIfNone(), SetSel0(), SetSel1(), SetStateTo(), SkipEnd(), ScreenFrame::TimeZoom(), TP_DisplaySelection(), TP_ScrollWindow(), UpdateFirstVisible(), UpdatePrefsVariables(), VisibleTrackIterator::VisibleTrackIterator(), WriteXML(), and Zoom().
wxScrollBar* AudacityProject::mVsbar [private]
Referenced by FixScrollbars(), OnScroll(), OnZoomFitV(), and TP_ScrollUpDown().
bool AudacityProject::mWantSaveCompressed [private]
Referenced by Save(), and WriteXML().
The documentation for this class was generated from the following files:
Project.h
Menus.cpp
Project.cpp