Audacity: Profiler Class Reference
Profiler Class Reference
A simple profiler to measure the average time lengths that a particular task/function takes. Currently not thread-safe and not thread-smart, but it will probably work fine if you use it on a high level.
#include <Profiler.h>
Public Member Functions
virtual ~Profiler ()
write to a profile at the end of the test.
void Begin (char *fileName, int lineNum, char *taskDescription)
start the task timer.
void End (char *fileName, int lineNum, char *taskDescription)
end the task timer.
Static Public Member Functions
static Profiler * Instance ()
Gets the singleton instance.
Protected Member Functions
Profiler ()
private constructor - Singleton.
TaskProfile * GetOrCreateTaskProfile (char *fileName, int lineNum)
find a taskProfile for the given task, otherwise create
TaskProfile * GetTaskProfileByDescription (char *description)
Protected Attributes
std::vector< TaskProfile * > mTasks
ODLock mTasksMutex
Detailed Description
A simple profiler to measure the average time lengths that a particular task/function takes. Currently not thread-safe and not thread-smart, but it will probably work fine if you use it on a high level.
Constructor & Destructor Documentation
Profiler::~Profiler () [virtual]
write to a profile at the end of the test.
References mTasks.
Profiler::Profiler () [inline, protected]
private constructor - Singleton.
Referenced by Instance().
Member Function Documentation
void Profiler::Begin (char * fileName, int lineNum, char * taskDescription)
start the task timer.
References TaskProfile::Begin(), GetOrCreateTaskProfile(), and mTasksMutex.
void Profiler::End (char * fileName, int lineNum, char * taskDescription)
end the task timer.
References TaskProfile::End(), GetTaskProfileByDescription(), and mTasksMutex.
TaskProfile * Profiler::GetOrCreateTaskProfile (char * fileName, int lineNum) [protected]
find a taskProfile for the given task, otherwise create
References mTasks.
Referenced by Begin().
TaskProfile * Profiler::GetTaskProfileByDescription (char * description) [protected]
References mTasks.
Referenced by End().
Profiler * Profiler::Instance () [static]
Gets the singleton instance.
References Profiler().
Member Data Documentation
std::vector<TaskProfile*> Profiler::mTasks [protected]
Referenced by GetOrCreateTaskProfile(), GetTaskProfileByDescription(), and ~Profiler().
ODLock Profiler::mTasksMutex [protected]
Referenced by Begin(), and End().
The documentation for this class was generated from the following files:
Profiler.h
Profiler.cpp