Audacity: PCMAliasBlockFile Class Reference
PCMAliasBlockFile Class Reference
An AliasBlockFile that references uncompressed data in an existing file.
#include <PCMAliasBlockFile.h>
Public Member Functions
PCMAliasBlockFile (wxFileName baseFileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel)
Constructs a PCMAliasBlockFile, writing the summary to disk.
PCMAliasBlockFile (wxFileName fileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, bool writeSummary)
Constructs a PCMAliasBlockFile with the option of not writing to disk.
PCMAliasBlockFile (wxFileName existingFileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, float min, float max, float rms)
virtual ~PCMAliasBlockFile ()
virtual int ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len)
Reads the specified data from the aliased file using libsndfile.
virtual void SaveXML (XMLWriter &xmlFile)
Stores a representation of this file in XML.
virtual BlockFile * Copy (wxFileName fileName)
virtual void Recover ()
if the on-disk state disappeared, either recover it (if it was
Static Public Member Functions
static BlockFile * BuildFromXML (DirManager &dm, const wxChar **attrs)
Detailed Description
An AliasBlockFile that references uncompressed data in an existing file.
Constructor & Destructor Documentation
PCMAliasBlockFile::PCMAliasBlockFile (wxFileName baseFileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel)
Constructs a PCMAliasBlockFile, writing the summary to disk.
References AliasBlockFile::WriteSummary().
Referenced by BuildFromXML(), Copy(), and ODPCMAliasBlockFile::Copy().
PCMAliasBlockFile::PCMAliasBlockFile (wxFileName fileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, bool writeSummary)
Constructs a PCMAliasBlockFile with the option of not writing to disk.
References AliasBlockFile::WriteSummary().
PCMAliasBlockFile::PCMAliasBlockFile (wxFileName existingFileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, float min, float max, float rms)
PCMAliasBlockFile::~PCMAliasBlockFile () [virtual]
Member Function Documentation
BlockFile * PCMAliasBlockFile::BuildFromXML (DirManager & dm, const wxChar ** attrs) [static]
Reimplemented in ODPCMAliasBlockFile.
References DirManager::AssignFile(), Internat::CompatibleToDouble(), DirManager::GetProjectDataDir(), XMLValueChecker::IsGoodFileName(), XMLValueChecker::IsGoodFileString(), XMLValueChecker::IsGoodInt(), XMLValueChecker::IsGoodPathName(), XMLValueChecker::IsGoodString(), XMLValueChecker::IsValidChannel(), max, min(), and PCMAliasBlockFile().
Referenced by DirManager::HandleXMLTag().
BlockFile * PCMAliasBlockFile::Copy (wxFileName newFileName) [virtual]
Construct a new PCMAliasBlockFile based on this one, but writing the summary data to a new file.
Parameters:
newFileName The filename to copy the summary data to.
Implements BlockFile.
Reimplemented in LegacyAliasBlockFile, and ODPCMAliasBlockFile.
References AliasBlockFile::mAliasChannel, AliasBlockFile::mAliasedFileName, AliasBlockFile::mAliasStart, BlockFile::mLen, BlockFile::mMax, BlockFile::mMin, BlockFile::mRMS, and PCMAliasBlockFile().
int PCMAliasBlockFile::ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len) [virtual]
Reads the specified data from the aliased file using libsndfile.
Reads the specified data from the aliased file, using libsndfile, and converts it to the given sample format.
Parameters:
data The buffer to read the sample data into.
format The format to convert the data into
start The offset within the block to begin reading
len The number of samples to read
Implements AliasBlockFile.
Reimplemented in ODPCMAliasBlockFile.
References CopySamples(), DeleteSamples(), floatSample, int16Sample, ODManager::LockLibSndFileMutex(), AliasBlockFile::mAliasChannel, AliasBlockFile::mAliasedFileName, AliasBlockFile::mAliasStart, AliasBlockFile::mSilentAliasLog, NewSamples(), SAMPLE_SIZE, sf_subtype_more_than_16_bits(), and ODManager::UnlockLibSndFileMutex().
void PCMAliasBlockFile::Recover () [virtual]
if the on-disk state disappeared, either recover it (if it was
Implements BlockFile.
Reimplemented in LegacyAliasBlockFile, and ODPCMAliasBlockFile.
References AliasBlockFile::WriteSummary().
void PCMAliasBlockFile::SaveXML (XMLWriter & xmlFile) [virtual]
Stores a representation of this file in XML.
Implements BlockFile.
Reimplemented in LegacyAliasBlockFile, and ODPCMAliasBlockFile.
References XMLWriter::EndTag(), AliasBlockFile::mAliasChannel, AliasBlockFile::mAliasedFileName, AliasBlockFile::mAliasStart, BlockFile::mFileName, BlockFile::mLen, BlockFile::mMax, BlockFile::mMin, BlockFile::mRMS, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
The documentation for this class was generated from the following files:
PCMAliasBlockFile.h
PCMAliasBlockFile.cpp