Audacity: LWSlider Class Reference
LWSlider Class Reference
Lightweight version of ASlider. In other words it does not have a window permanently associated with it.
#include <ASlider.h>
Public Member Functions
LWSlider (wxWindow *parent, wxString name, const wxPoint &pos, const wxSize &size, float minValue, float maxValue, float stepValue, bool canUseShift, int style, bool heavyweight=false, bool popup=true, int orientation=wxHORIZONTAL)
LWSlider (wxWindow *parent, wxString name, const wxPoint &pos, const wxSize &size, int style, bool heavyweight=false, bool popup=true, int orientation=wxHORIZONTAL)
void Init (wxWindow *parent, wxString name, const wxPoint &pos, const wxSize &size, float minValue, float maxValue, float stepValue, bool canUseShift, int style, bool heavyweight, bool popup, float speed, int orientation=wxHORIZONTAL)
virtual ~LWSlider ()
wxWindowID GetId ()
void SetId (wxWindowID id)
void SetDefaultValue (float value)
void SetDefaultShortcut (bool value)
void GetScroll (float &line, float &page)
void SetScroll (float line, float page)
float Get (bool convert=true)
void Set (float value)
void Increase (float steps)
void Decrease (float steps)
void SetSpeed (float speed)
void Move (const wxPoint &newpos)
void OnPaint (wxDC &dc, bool selected)
void OnSize (wxSizeEvent &event)
void OnMouseEvent (wxMouseEvent &event)
void OnKeyEvent (wxKeyEvent &event)
void Refresh ()
void RecreateTipWin ()
bool ShowDialog ()
bool ShowDialog (wxPoint pos)
void SetEnabled (bool enabled)
bool GetEnabled ()
Private Member Functions
void FormatPopWin ()
void SetPopWinPosition ()
void CreatePopWin ()
void Draw ()
bool DoShowDialog (wxPoint pos)
void SendUpdate (float newValue)
int ValueToPosition (float val)
float DragPositionToValue (int fromPos, bool shiftDown)
float ClickPositionToValue (int fromPos, bool shiftDown)
wxWindow * GetToolTipParent () const
Private Attributes
wxWindow * mParent
int mStyle
int mOrientation
bool mHW
bool mPopup
int mLeft
int mTop
int mWidth
int mHeight
int mCenterY
int mLeftX
int mRightX
int mWidthX
int mCenterX
int mTopY
int mBottomY
int mHeightY
int mThumbWidth
int mThumbHeight
float mClickValue
int mClickPos
float mMinValue
float mMaxValue
float mStepValue
float mSpeed
float mScrollLine
float mScrollPage
float mCurrentValue
bool mDefaultShortcut
float mDefaultValue
bool mCanUseShift
wxWindowID mID
wxWindow * mPopWin
Ruler * mpRuler
bool mIsDragging
wxBitmap * mBitmap
wxBitmap * mSelBitmap
wxBitmap * mThumbBitmap
wxBitmap * mSelThumbBitmap
wxString mName
bool mEnabled
Friends
class ASlider
class ASliderAx
Detailed Description
Lightweight version of ASlider. In other words it does not have a window permanently associated with it.
Constructor & Destructor Documentation
LWSlider::LWSlider (wxWindow * parent, wxString name, const wxPoint & pos, const wxSize & size, float minValue, float maxValue, float stepValue, bool canUseShift, int style, bool heavyweight = false, bool popup = true, int orientation = wxHORIZONTAL)
References Init().
LWSlider::LWSlider (wxWindow * parent, wxString name, const wxPoint & pos, const wxSize & size, int style, bool heavyweight = false, bool popup = true, int orientation = wxHORIZONTAL)
References DB_SLIDER, FRAC_SLIDER, Init(), PAN_SLIDER, SPEED_SLIDER, and STEP_CONTINUOUS.
LWSlider::~LWSlider () [virtual]
References mBitmap, mOrientation, mPopWin, mpRuler, and mThumbBitmap.
Member Function Documentation
float LWSlider::ClickPositionToValue (int fromPos, bool shiftDown) [private]
References mBottomY, mCanUseShift, mHeightY, mLeft, mMaxValue, mMinValue, mOrientation, mStepValue, mThumbWidth, mWidthX, and STEP_CONTINUOUS.
Referenced by OnMouseEvent().
void LWSlider::CreatePopWin () [private]
References DB_SLIDER, GetToolTipParent(), mName, mPopWin, mStyle, PAN_SLIDER, and SPEED_SLIDER.
Referenced by Init(), and RecreateTipWin().
void LWSlider::Decrease (float steps)
References mCurrentValue, mMaxValue, mMinValue, mStepValue, and Refresh().
Referenced by ASlider::Decrease(), OnKeyEvent(), OnMouseEvent(), TrackPanel::OnTrackGainDec(), and TrackPanel::OnTrackPanLeft().
bool LWSlider::DoShowDialog (wxPoint pos) [private]
References SliderDialog::Get(), Get(), mCurrentValue, mHeight, mName, mScrollLine, mScrollPage, mStyle, and mWidth.
Referenced by OnMouseEvent(), and ShowDialog().
float LWSlider::DragPositionToValue (int fromPos, bool shiftDown) [private]
References mCanUseShift, mClickPos, mClickValue, mHeightY, mMaxValue, mMinValue, mOrientation, mSpeed, mStepValue, mWidthX, and STEP_CONTINUOUS.
Referenced by OnMouseEvent().
void LWSlider::Draw () [private]
References ThemeBase::Bitmap(), ThemeBase::Colour(), AColor::Dark(), DB_SLIDER, AColor::Light(), AColor::Line(), mBitmap, mBottomY, mCenterX, mCenterY, mEnabled, mHeight, mHeightY, mLeftX, mMaxValue, mMinValue, mOrientation, mRightX, mStyle, mThumbBitmap, mThumbHeight, mThumbWidth, mTopY, mWidth, mWidthX, PAN_SLIDER, sliderFontSize, and theTheme.
Referenced by Init(), OnSize(), and SetEnabled().
void LWSlider::FormatPopWin () [private]
References DB_SLIDER, FRAC_SLIDER, mCurrentValue, mName, mPopWin, mStyle, PAN_SLIDER, and SPEED_SLIDER.
Referenced by OnMouseEvent(), and SendUpdate().
float LWSlider::Get (bool convert = true)
References DB_SLIDER, mCurrentValue, and mStyle.
Referenced by DoShowDialog(), ASlider::Get(), TrackPanel::HandleSliders(), TrackPanel::SetTrackGain(), and TrackPanel::SetTrackPan().
bool LWSlider::GetEnabled ()
References mEnabled.
Referenced by ASlider::Enable(), and ASlider::IsEnabled().
wxWindowID LWSlider::GetId ()
References mID.
Referenced by ASlider::OnSlider().
void LWSlider::GetScroll (float & line, float & page)
References mScrollLine, and mScrollPage.
Referenced by ASlider::GetScroll().
wxWindow * LWSlider::GetToolTipParent () const [private]
References mParent.
Referenced by CreatePopWin(), and SetPopWinPosition().
void LWSlider::Increase (float steps)
References mCurrentValue, mMaxValue, mMinValue, mStepValue, and Refresh().
Referenced by ASlider::Increase(), OnKeyEvent(), OnMouseEvent(), TrackPanel::OnTrackGainInc(), and TrackPanel::OnTrackPanRight().
void LWSlider::Init (wxWindow * parent, wxString name, const wxPoint & pos, const wxSize & size, float minValue, float maxValue, float stepValue, bool canUseShift, int style, bool heavyweight, bool popup, float speed, int orientation = wxHORIZONTAL)
References CreatePopWin(), Draw(), mBitmap, mCanUseShift, mCurrentValue, mDefaultShortcut, mDefaultValue, mEnabled, mHeight, mHW, mID, mIsDragging, mMaxValue, mMinValue, mName, mOrientation, Move(), mParent, mPopup, mPopWin, mpRuler, mScrollLine, mScrollPage, mSpeed, mStepValue, mStyle, and mWidth.
Referenced by LWSlider().
void LWSlider::Move (const wxPoint & newpos)
References mLeft, and mTop.
Referenced by Init().
void LWSlider::OnKeyEvent (wxKeyEvent & event)
References Decrease(), Increase(), mCurrentValue, mEnabled, mMaxValue, mMinValue, mParent, mScrollLine, mScrollPage, SendUpdate(), and wxEVT_COMMAND_BUTTON_CLICKED.
Referenced by ASlider::OnKeyEvent().
void LWSlider::OnMouseEvent (wxMouseEvent & event)
References ClickPositionToValue(), Decrease(), DoShowDialog(), DragPositionToValue(), FormatPopWin(), GetActiveProject(), Increase(), mCenterX, mCenterY, mClickPos, mClickValue, mCurrentValue, mDefaultShortcut, mDefaultValue, mEnabled, mIsDragging, mLeft, mOrientation, mParent, mPopup, mPopWin, mThumbHeight, mThumbWidth, mTop, Refresh(), SendUpdate(), SetPopWinPosition(), AudacityProject::TP_DisplayStatusMessage(), and ValueToPosition().
Referenced by TrackPanel::HandleSliders(), ASlider::OnCaptureLost(), and ASlider::OnMouseEvent().
void LWSlider::OnPaint (wxDC & dc, bool selected)
References mBitmap, mCenterX, mCenterY, mCurrentValue, mHW, mLeft, mOrientation, mPopWin, mThumbBitmap, mThumbHeight, mThumbWidth, mTop, and ValueToPosition().
Referenced by ASlider::OnPaint().
void LWSlider::OnSize (wxSizeEvent & event)
References Draw(), mHeight, mWidth, and Refresh().
Referenced by ASlider::OnSize().
void LWSlider::RecreateTipWin ()
References CreatePopWin(), and mPopWin.
Referenced by ASlider::RecreateTipWin().
void LWSlider::Refresh ()
References mHW, and mParent.
Referenced by Decrease(), Increase(), OnMouseEvent(), OnSize(), SendUpdate(), Set(), and SetEnabled().
void LWSlider::SendUpdate (float newValue) [private]
References FormatPopWin(), mCurrentValue, mID, mMaxValue, mMinValue, mParent, mPopWin, and Refresh().
Referenced by OnKeyEvent(), and OnMouseEvent().
void LWSlider::Set (float value)
References DB_SLIDER, mCurrentValue, mIsDragging, mMaxValue, mMinValue, mStyle, and Refresh().
Referenced by ASlider::Set().
void LWSlider::SetDefaultShortcut (bool value)
References mDefaultShortcut.
Referenced by SetDefaultValue().
void LWSlider::SetDefaultValue (float value)
References mDefaultValue, and SetDefaultShortcut().
Referenced by TrackInfo::MakeMoreSliders().
void LWSlider::SetEnabled (bool enabled)
References Draw(), mEnabled, and Refresh().
Referenced by ASlider::Enable().
void LWSlider::SetId (wxWindowID id)
References mID.
void LWSlider::SetPopWinPosition () [private]
References GetToolTipParent(), mHeight, mLeft, mOrientation, mParent, mPopWin, mTop, and mWidth.
Referenced by OnMouseEvent().
void LWSlider::SetScroll (float line, float page)
References mScrollLine, and mScrollPage.
Referenced by ASlider::SetScroll().
void LWSlider::SetSpeed (float speed)
References mSpeed.
Referenced by ASlider::SetSpeed().
bool LWSlider::ShowDialog (wxPoint pos)
References DoShowDialog().
bool LWSlider::ShowDialog ()
References DoShowDialog(), mLeft, mParent, and mTop.
Referenced by TrackPanel::OnTrackGain(), TrackPanel::OnTrackPan(), and ASlider::ShowDialog().
int LWSlider::ValueToPosition (float val) [private]
References mHeightY, mMaxValue, mMinValue, mOrientation, and mWidthX.
Referenced by OnMouseEvent(), and OnPaint().
Friends And Related Function Documentation
friend class ASlider [friend]
friend class ASliderAx [friend]
Member Data Documentation
wxBitmap* LWSlider::mBitmap [private]
Referenced by Draw(), Init(), OnPaint(), and ~LWSlider().
int LWSlider::mBottomY [private]
Referenced by ClickPositionToValue(), and Draw().
bool LWSlider::mCanUseShift [private]
Referenced by ClickPositionToValue(), DragPositionToValue(), and Init().
int LWSlider::mCenterX [private]
Referenced by Draw(), OnMouseEvent(), and OnPaint().
int LWSlider::mCenterY [private]
Referenced by Draw(), OnMouseEvent(), and OnPaint().
int LWSlider::mClickPos [private]
Referenced by DragPositionToValue(), and OnMouseEvent().
float LWSlider::mClickValue [private]
Referenced by DragPositionToValue(), and OnMouseEvent().
float LWSlider::mCurrentValue [private]
Referenced by Decrease(), DoShowDialog(), FormatPopWin(), Get(), Increase(), Init(), OnKeyEvent(), OnMouseEvent(), OnPaint(), SendUpdate(), and Set().
bool LWSlider::mDefaultShortcut [private]
Referenced by Init(), OnMouseEvent(), and SetDefaultShortcut().
float LWSlider::mDefaultValue [private]
Referenced by Init(), OnMouseEvent(), and SetDefaultValue().
bool LWSlider::mEnabled [private]
Referenced by Draw(), GetEnabled(), Init(), OnKeyEvent(), OnMouseEvent(), and SetEnabled().
int LWSlider::mHeight [private]
Referenced by DoShowDialog(), Draw(), Init(), ASlider::OnPaint(), OnSize(), and SetPopWinPosition().
int LWSlider::mHeightY [private]
Referenced by ClickPositionToValue(), DragPositionToValue(), Draw(), and ValueToPosition().
bool LWSlider::mHW [private]
Referenced by Init(), OnPaint(), and Refresh().
wxWindowID LWSlider::mID [private]
Referenced by GetId(), Init(), SendUpdate(), and SetId().
bool LWSlider::mIsDragging [private]
Referenced by Init(), OnMouseEvent(), and Set().
int LWSlider::mLeft [private]
Referenced by ClickPositionToValue(), Move(), OnMouseEvent(), OnPaint(), SetPopWinPosition(), and ShowDialog().
int LWSlider::mLeftX [private]
Referenced by Draw().
float LWSlider::mMaxValue [private]
Referenced by ClickPositionToValue(), Decrease(), DragPositionToValue(), Draw(), Increase(), Init(), OnKeyEvent(), SendUpdate(), Set(), and ValueToPosition().
float LWSlider::mMinValue [private]
Referenced by ClickPositionToValue(), Decrease(), DragPositionToValue(), Draw(), Increase(), Init(), OnKeyEvent(), SendUpdate(), Set(), and ValueToPosition().
wxString LWSlider::mName [private]
Referenced by CreatePopWin(), DoShowDialog(), FormatPopWin(), and Init().
int LWSlider::mOrientation [private]
Referenced by ClickPositionToValue(), DragPositionToValue(), Draw(), Init(), OnMouseEvent(), OnPaint(), SetPopWinPosition(), ValueToPosition(), and ~LWSlider().
wxWindow* LWSlider::mParent [private]
Referenced by GetToolTipParent(), Init(), OnKeyEvent(), OnMouseEvent(), Refresh(), SendUpdate(), SetPopWinPosition(), and ShowDialog().
bool LWSlider::mPopup [private]
Referenced by Init(), and OnMouseEvent().
wxWindow* LWSlider::mPopWin [private]
Referenced by CreatePopWin(), FormatPopWin(), Init(), OnMouseEvent(), OnPaint(), RecreateTipWin(), SendUpdate(), SetPopWinPosition(), and ~LWSlider().
Ruler* LWSlider::mpRuler [private]
Referenced by Init(), and ~LWSlider().
int LWSlider::mRightX [private]
Referenced by Draw().
float LWSlider::mScrollLine [private]
Referenced by DoShowDialog(), GetScroll(), Init(), OnKeyEvent(), and SetScroll().
float LWSlider::mScrollPage [private]
Referenced by DoShowDialog(), GetScroll(), Init(), OnKeyEvent(), and SetScroll().
wxBitmap* LWSlider::mSelBitmap [private]
wxBitmap* LWSlider::mSelThumbBitmap [private]
float LWSlider::mSpeed [private]
Referenced by DragPositionToValue(), Init(), and SetSpeed().
float LWSlider::mStepValue [private]
Referenced by ClickPositionToValue(), Decrease(), DragPositionToValue(), Increase(), and Init().
int LWSlider::mStyle [private]
Referenced by CreatePopWin(), DoShowDialog(), Draw(), FormatPopWin(), Get(), Init(), and Set().
wxBitmap* LWSlider::mThumbBitmap [private]
Referenced by Draw(), OnPaint(), and ~LWSlider().
int LWSlider::mThumbHeight [private]
Referenced by Draw(), OnMouseEvent(), and OnPaint().
int LWSlider::mThumbWidth [private]
Referenced by ClickPositionToValue(), Draw(), OnMouseEvent(), and OnPaint().
int LWSlider::mTop [private]
Referenced by Move(), OnMouseEvent(), OnPaint(), SetPopWinPosition(), and ShowDialog().
int LWSlider::mTopY [private]
Referenced by Draw().
int LWSlider::mWidth [private]
Referenced by DoShowDialog(), Draw(), Init(), ASlider::OnPaint(), OnSize(), and SetPopWinPosition().
int LWSlider::mWidthX [private]
Referenced by ClickPositionToValue(), DragPositionToValue(), Draw(), and ValueToPosition().
The documentation for this class was generated from the following files:
ASlider.h
ASlider.cpp