Audacity: SimpleBlockFile Class Reference
SimpleBlockFile Class Reference
A BlockFile that reads and writes uncompressed data using libsndfile.
#include <SimpleBlockFile.h>
Public Member Functions
SimpleBlockFile (wxFileName baseFileName, samplePtr sampleData, sampleCount sampleLen, sampleFormat format, bool allowDeferredWrite=false, bool bypassCache=false)
Create a disk file and write summary and sample data to it.
SimpleBlockFile (wxFileName existingFile, sampleCount len, float min, float max, float rms)
Create the memory structure to refer to the given block file.
virtual ~SimpleBlockFile ()
virtual bool ReadSummary (void *data)
Read the summary section of the disk file.
virtual int ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len)
Read the data section of the disk file.
virtual BlockFile * Copy (wxFileName newFileName)
Create a new block file identical to this one.
virtual void SaveXML (XMLWriter &xmlFile)
Write an XML representation of this file.
virtual wxLongLong GetSpaceUsage ()
virtual void Recover ()
if the on-disk state disappeared, either recover it (if it was
virtual bool GetNeedWriteCacheToDisk ()
virtual void WriteCacheToDisk ()
virtual bool GetNeedFillCache ()
virtual void FillCache ()
Static Public Member Functions
static BlockFile * BuildFromXML (DirManager &dm, const wxChar **attrs)
static
Protected Member Functions
bool WriteSimpleBlockFile (samplePtr sampleData, sampleCount sampleLen, sampleFormat format, void *summaryData)
void ReadIntoCache ()
Static Protected Member Functions
static bool GetCache ()
Protected Attributes
SimpleBlockFileCache mCache
Detailed Description
A BlockFile that reads and writes uncompressed data using libsndfile.
A block file that writes the audio data to an .au file and reads it back using libsndfile.
There are two ways to construct a simple block file. One is to supply data and have the constructor write the file. The other is for when the file already exists and we simply want to create the data structure to refer to it.
The block file can be cached in two ways. Caching is enabled if the preference "/Directories/CacheBlockFiles" is set, otherwise disabled. The default is to disable caching.
Read-caching: If caching is enabled, all block files will always be read-cached. Block files on disk will be read as soon as they are created and hold in memory. New block files will be written to disk, but hold in memory, so they are never read from disk in the current session.
Write-caching: If caching is enabled and the parameter allowDeferredWrite is enabled at the block file constructor, new block files are hold in memory and only written to disk when WriteCacheToDisk() is called. This is used during recording to prevent disk access. After recording, WriteCacheToDisk() will be called on all block files and they will be written to disk. During normal editing, no write cache is active, that is, any block files will be written to disk instantly.
Even with write cache, auto recovery during normal editing will work as expected. However, auto recovery during recording will not work (not even manual auto recovery, because the files are never written physically to disk).
Constructor & Destructor Documentation
SimpleBlockFile::SimpleBlockFile (wxFileName baseFileName, samplePtr sampleData, sampleCount sampleLen, sampleFormat format, bool allowDeferredWrite = false, bool bypassCache = false)
Create a disk file and write summary and sample data to it.
Constructs a SimpleBlockFile based on sample data and writes it to disk.
Parameters:
baseFileName The filename to use, but without an extension. This constructor will add the appropriate extension (.au in this case).
sampleData The sample data to be written to this block.
sampleLen The number of samples to be written to this block.
format The format of the given samples.
allowDeferredWrite Allow deferred write-caching
References SimpleBlockFileCache::active, BlockFile::CalcSummary(), DEBUG_OUTPUT, SimpleBlockFileCache::format, GetCache(), mCache, BlockFile::mSummaryInfo, SimpleBlockFileCache::needWrite, SAMPLE_SIZE, SimpleBlockFileCache::sampleData, SimpleBlockFileCache::summaryData, SummaryInfo::totalSummaryBytes, and WriteSimpleBlockFile().
Referenced by BuildFromXML(), and Copy().
SimpleBlockFile::SimpleBlockFile (wxFileName existingFile, sampleCount len, float min, float max, float rms)
Create the memory structure to refer to the given block file.
Construct a SimpleBlockFile memory structure that will point to an existing block file. This file must exist and be a valid block file.
Parameters:
existingFile The disk file this SimpleBlockFile should use.
References SimpleBlockFileCache::active, DEBUG_OUTPUT, mCache, BlockFile::mMax, BlockFile::mMin, and BlockFile::mRMS.
SimpleBlockFile::~SimpleBlockFile () [virtual]
References SimpleBlockFileCache::active, mCache, SimpleBlockFileCache::sampleData, and SimpleBlockFileCache::summaryData.
Member Function Documentation
BlockFile * SimpleBlockFile::BuildFromXML (DirManager & dm, const wxChar ** attrs) [static]
static
Reimplemented in ODDecodeBlockFile.
References DirManager::AssignFile(), Internat::CompatibleToDouble(), DirManager::GetProjectDataDir(), XMLValueChecker::IsGoodFileString(), XMLValueChecker::IsGoodInt(), XMLValueChecker::IsGoodString(), max, min(), and SimpleBlockFile().
Referenced by DirManager::HandleXMLTag().
BlockFile * SimpleBlockFile::Copy (wxFileName newFileName) [virtual]
Create a new block file identical to this one.
Create a copy of this BlockFile, but using a different disk file.
Parameters:
newFileName The name of the new file to use.
Implements BlockFile.
Reimplemented in ODDecodeBlockFile.
References BlockFile::mLen, BlockFile::mMax, BlockFile::mMin, BlockFile::mRMS, and SimpleBlockFile().
void SimpleBlockFile::FillCache () [virtual]
Reimplemented from BlockFile.
References SimpleBlockFileCache::active, AU_SAMPLE_FORMAT_16, AU_SAMPLE_FORMAT_24, DEBUG_OUTPUT, auHeader::encoding, floatSample, SimpleBlockFileCache::format, int16Sample, int24Sample, auHeader::magic, mCache, BlockFile::mFileName, BlockFile::mLen, BlockFile::mSummaryInfo, SimpleBlockFileCache::needWrite, ReadData(), ReadSummary(), SAMPLE_SIZE, SimpleBlockFileCache::sampleData, SimpleBlockFileCache::summaryData, SwapUintEndianess(), and SummaryInfo::totalSummaryBytes.
bool SimpleBlockFile::GetCache () [static, protected]
References GetFreeMemory(), and gPrefs.
Referenced by SimpleBlockFile().
virtual bool SimpleBlockFile::GetNeedFillCache () [inline, virtual]
Reimplemented from BlockFile.
References SimpleBlockFileCache::active, and mCache.
bool SimpleBlockFile::GetNeedWriteCacheToDisk () [virtual]
Reimplemented from BlockFile.
References SimpleBlockFileCache::active, mCache, and SimpleBlockFileCache::needWrite.
Referenced by WriteCacheToDisk().
wxLongLong SimpleBlockFile::GetSpaceUsage () [virtual]
Implements BlockFile.
Reimplemented in ODDecodeBlockFile.
References SimpleBlockFileCache::active, mCache, BlockFile::mFileName, and SimpleBlockFileCache::needWrite.
int SimpleBlockFile::ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len) [virtual]
Read the data section of the disk file.
Read the data portion of the block file using libsndfile. Convert it to the given format if it is not already.
Parameters:
data The buffer where the data will be stored
format The format the data will be stored in
start The offset in this block file
len The number of samples to read
Implements BlockFile.
Reimplemented in ODDecodeBlockFile.
References SimpleBlockFileCache::active, CopySamples(), DEBUG_OUTPUT, DeleteSamples(), floatSample, SimpleBlockFileCache::format, int16Sample, int24Sample, mCache, BlockFile::mFileName, BlockFile::mLen, BlockFile::mSilentLog, NewSamples(), SAMPLE_SIZE, SimpleBlockFileCache::sampleData, and sf_subtype_is_integer().
Referenced by FillCache().
void SimpleBlockFile::ReadIntoCache () [protected]
bool SimpleBlockFile::ReadSummary (void * data) [virtual]
Read the summary section of the disk file.
Read the summary section of the disk file.
Parameters:
*data The buffer to write the data to. It must be at least mSummaryinfo.totalSummaryBytes long.
Implements BlockFile.
Reimplemented in ODDecodeBlockFile.
References SimpleBlockFileCache::active, DEBUG_OUTPUT, BlockFile::FixSummary(), mCache, BlockFile::mFileName, BlockFile::mSilentLog, BlockFile::mSummaryInfo, SimpleBlockFileCache::summaryData, and SummaryInfo::totalSummaryBytes.
Referenced by FillCache().
void SimpleBlockFile::Recover () [virtual]
if the on-disk state disappeared, either recover it (if it was
Implements BlockFile.
Reimplemented in ODDecodeBlockFile.
References AU_SAMPLE_FORMAT_16, auHeader::channels, auHeader::dataOffset, auHeader::dataSize, auHeader::encoding, auHeader::magic, BlockFile::mFileName, BlockFile::mLen, BlockFile::mSummaryInfo, auHeader::sampleRate, and SummaryInfo::totalSummaryBytes.
void SimpleBlockFile::SaveXML (XMLWriter & xmlFile) [virtual]
Write an XML representation of this file.
Implements BlockFile.
Reimplemented in ODDecodeBlockFile.
References XMLWriter::EndTag(), BlockFile::mFileName, BlockFile::mLen, BlockFile::mMax, BlockFile::mMin, BlockFile::mRMS, XMLWriter::StartTag(), and XMLWriter::WriteAttr().
void SimpleBlockFile::WriteCacheToDisk () [virtual]
Reimplemented from BlockFile.
References DEBUG_OUTPUT, SimpleBlockFileCache::format, GetNeedWriteCacheToDisk(), mCache, BlockFile::mLen, SimpleBlockFileCache::needWrite, SimpleBlockFileCache::sampleData, SimpleBlockFileCache::summaryData, and WriteSimpleBlockFile().
bool SimpleBlockFile::WriteSimpleBlockFile (samplePtr sampleData, sampleCount sampleLen, sampleFormat format, void * summaryData) [protected]
References AU_SAMPLE_FORMAT_16, AU_SAMPLE_FORMAT_24, AU_SAMPLE_FORMAT_FLOAT, BlockFile::CalcSummary(), auHeader::channels, auHeader::dataOffset, auHeader::dataSize, DEBUG_OUTPUT, auHeader::encoding, floatSample, int16Sample, int24Sample, auHeader::magic, BlockFile::mFileName, BlockFile::mSummaryInfo, SAMPLE_SIZE, auHeader::sampleRate, and SummaryInfo::totalSummaryBytes.
Referenced by SimpleBlockFile(), WriteCacheToDisk(), and ODDecodeBlockFile::WriteODDecodeBlockFile().
Member Data Documentation
SimpleBlockFileCache SimpleBlockFile::mCache [protected]
Referenced by FillCache(), GetNeedFillCache(), GetNeedWriteCacheToDisk(), GetSpaceUsage(), ReadData(), ReadSummary(), SimpleBlockFile(), WriteCacheToDisk(), and ~SimpleBlockFile().
The documentation for this class was generated from the following files:
SimpleBlockFile.h
SimpleBlockFile.cpp