Audacity: HelpCommand Class Reference
HelpCommand Class Reference
Command which returns information about the given command.
#include <HelpCommand.h>
Public Member Functions
HelpCommand (HelpCommandType &type, CommandOutputTarget *target)
virtual bool Apply (CommandExecutionContext context)
Detailed Description
Command which returns information about the given command.
Constructor & Destructor Documentation
HelpCommand::HelpCommand (HelpCommandType & type, CommandOutputTarget * target) [inline]
Member Function Documentation
bool HelpCommand::Apply (CommandExecutionContext context) [virtual]
Actually carry out the command. Return true if successful and false otherwise.
Reimplemented from CommandImplementation.
References CommandType::Describe(), CommandImplementation::Error(), CommandDirectory::Get(), CommandImplementation::GetString(), CommandDirectory::LookUp(), and CommandImplementation::Status().
The documentation for this class was generated from the following files:
HelpCommand.h
HelpCommand.cpp