Audacity: AudioUnitGUIControl Class Reference
AudioUnitGUIControl Class Reference
Used with AudioUnitEffect.
Public Member Functions
AudioUnitGUIControl (wxWindow *parent, wxWindowID id, wxPoint pos, wxSize size, ControlRef controlRef)
virtual ~AudioUnitGUIControl ()
bool Create (wxWindow *parent, wxWindowID id, wxPoint pos, wxSize size, ControlRef controlRef)
void OnMouse (wxMouseEvent &event)
Private Member Functions
short GetModifiers (wxMouseEvent &event)
Detailed Description
Used with AudioUnitEffect.
Constructor & Destructor Documentation
AudioUnitGUIControl::AudioUnitGUIControl (wxWindow * parent, wxWindowID id, wxPoint pos, wxSize size, ControlRef controlRef) [inline]
References Create().
AudioUnitGUIControl::~AudioUnitGUIControl () [virtual]
Member Function Documentation
bool AudioUnitGUIControl::Create (wxWindow * parent, wxWindowID id, wxPoint pos, wxSize size, ControlRef controlRef)
Referenced by AudioUnitGUIControl().
short AudioUnitGUIControl::GetModifiers (wxMouseEvent & event) [private]
Referenced by OnMouse().
void AudioUnitGUIControl::OnMouse (wxMouseEvent & event)
References GetModifiers().
The documentation for this class was generated from the following file:
AudioUnitEffect.cpp