Audacity: ExportPCMOptions Class Reference
ExportPCMOptions Class Reference
Public Member Functions
ExportPCMOptions (wxWindow *parent, int format)
void PopulateOrExchange (ShuttleGui &S)
void OnHeaderChoice (wxCommandEvent &evt)
void OnChoice (wxCommandEvent &event)
void OnOK (wxCommandEvent &event)
Private Member Functions
bool ValidatePair (int format)
int GetFormat ()
Private Attributes
wxArrayString mHeaderNames
wxArrayString mEncodingNames
wxChoice * mHeaderChoice
wxChoice * mEncodingChoice
wxButton * mOk
int mHeaderFromChoice
int mEncodingFromChoice
wxArrayInt mEncodingFormats
Constructor & Destructor Documentation
ExportPCMOptions::ExportPCMOptions (wxWindow * parent, int format)
References eIsCreatingFromPrefs, ReadExportFormatPref(), sf_encoding_index_name(), sf_encoding_index_to_subtype(), sf_header_index_name(), sf_header_index_to_type(), sf_num_encodings(), and sf_num_headers().
Member Function Documentation
int ExportPCMOptions::GetFormat () [private]
References mEncodingChoice, mEncodingFormats, mHeaderChoice, and sf_header_index_to_type().
Referenced by OnHeaderChoice(), and OnOK().
void ExportPCMOptions::OnChoice (wxCommandEvent & event)
void ExportPCMOptions::OnHeaderChoice (wxCommandEvent & evt)
References GetFormat(), mEncodingChoice, mEncodingFormats, mEncodingFromChoice, mEncodingNames, mHeaderChoice, sf_encoding_index_name(), sf_encoding_index_to_subtype(), sf_header_index_to_type(), sf_num_encodings(), sf_num_simple_formats(), sf_simple_format(), and ValidatePair().
void ExportPCMOptions::OnOK (wxCommandEvent & event)
References GetFormat(), and WriteExportFormatPref().
void ExportPCMOptions::PopulateOrExchange (ShuttleGui & S)
References ShuttleGuiBase::AddChoice(), ShuttleGuiBase::AddFixedText(), ShuttleGui::AddStandardButtons(), ShuttleGuiBase::EndHorizontalLay(), ShuttleGuiBase::EndMultiColumn(), ShuttleGuiBase::EndStatic(), ShuttleGui::Id(), ID_ENCODING_CHOICE, ID_HEADER_CHOICE, mEncodingChoice, mEncodingFromChoice, mEncodingNames, mHeaderChoice, mHeaderFromChoice, mHeaderNames, mOk, ShuttleGuiBase::SetStretchyCol(), ShuttleGuiBase::StartHorizontalLay(), ShuttleGuiBase::StartMultiColumn(), and ShuttleGuiBase::StartStatic().
bool ExportPCMOptions::ValidatePair (int format) [private]
Calls a libsndfile library function to determine whether the user's choice of sample encoding (e.g. pcm 16-bit or GSM 6.10 compression) is compatible with their choice of file format (e.g. WAV, AIFF) and enables/disables the OK button accordingly.
References mOk.
Referenced by OnHeaderChoice().
Member Data Documentation
wxChoice* ExportPCMOptions::mEncodingChoice [private]
Referenced by GetFormat(), OnHeaderChoice(), and PopulateOrExchange().
wxArrayInt ExportPCMOptions::mEncodingFormats [private]
Referenced by GetFormat(), and OnHeaderChoice().
int ExportPCMOptions::mEncodingFromChoice [private]
Referenced by OnHeaderChoice(), and PopulateOrExchange().
wxArrayString ExportPCMOptions::mEncodingNames [private]
Referenced by OnHeaderChoice(), and PopulateOrExchange().
wxChoice* ExportPCMOptions::mHeaderChoice [private]
Referenced by GetFormat(), OnHeaderChoice(), and PopulateOrExchange().
int ExportPCMOptions::mHeaderFromChoice [private]
Referenced by PopulateOrExchange().
wxArrayString ExportPCMOptions::mHeaderNames [private]
Referenced by PopulateOrExchange().
wxButton* ExportPCMOptions::mOk [private]
Referenced by PopulateOrExchange(), and ValidatePair().
The documentation for this class was generated from the following file:
ExportPCM.cpp