Audacity: MousePrefs Class Reference
MousePrefs Class Reference
A PrefsPanel that presents an interface for user to view the default bindings of mouse buttons to commands.
#include <MousePrefs.h>
Public Member Functions
MousePrefs (wxWindow *parent)
Constructor.
~MousePrefs ()
virtual bool Apply ()
Private Member Functions
void Populate ()
Creates the dialog and its contents.
void PopulateOrExchange (ShuttleGui &S)
Places controls on the panel and also exchanges data with them.
void CreateList ()
Creates the contents of mList.
void AddItem (wxString const &buttons, wxString const &tool, wxString const &action, wxString const &comment=wxEmptyString)
Adds an item to mList.
Private Attributes
wxListCtrl * mList
Detailed Description
A PrefsPanel that presents an interface for user to view the default bindings of mouse buttons to commands.
April/2003: These are default bindings and are not yet configurable. They are provided to give information about what the bindings are.
Configuration when available will be mostly used by power users who are unlikely to change the default bindings, but will add bindings (e.g. for cut, play, and their own nyquist filters) using currently unused combinations.
Unlike key-bindings which are parameterless, mouse bindings provide parameters:
a single point for a click, and
a stream of points or a start and end point for a drag.
If we allow a nyquist filter to be bound to the mouse, instead of being applied to the current selection it would be applied to the start and end points of the drag.
Constructor & Destructor Documentation
MousePrefs::MousePrefs (wxWindow * parent)
Constructor.
References Populate().
MousePrefs::~MousePrefs ()
Member Function Documentation
void MousePrefs::AddItem (wxString const & buttons, wxString const & tool, wxString const & action, wxString const & comment = wxEmptyString) [private]
Adds an item to mList.
References ActionColumn, ButtonsColumn, CommentColumn, mList, and ToolColumn.
Referenced by CreateList().
bool MousePrefs::Apply () [virtual]
Update the preferences stored on disk. Currently does nothing as Mouse Preferences don't change.
Implements PrefsPanel.
void MousePrefs::CreateList () [private]
Creates the contents of mList.
References ActionColumn, AddItem(), BlankColumn, ButtonsColumn, CommentColumn, mList, and ToolColumn.
Referenced by Populate().
void MousePrefs::Populate () [private]
Creates the dialog and its contents.
References CreateList(), eIsCreatingFromPrefs, and PopulateOrExchange().
Referenced by MousePrefs().
void MousePrefs::PopulateOrExchange (ShuttleGui & S) [private]
Places controls on the panel and also exchanges data with them.
References ShuttleGuiBase::AddListControlReportMode(), ShuttleGuiBase::EndStatic(), mList, ShuttleGuiBase::SetBorder(), and ShuttleGuiBase::StartStatic().
Referenced by Populate().
Member Data Documentation
wxListCtrl* MousePrefs::mList [private]
Referenced by AddItem(), CreateList(), and PopulateOrExchange().
The documentation for this class was generated from the following files:
MousePrefs.h
MousePrefs.cpp