Audacity: ODPCMAliasBlockFile Class Reference
ODPCMAliasBlockFile Class Reference
An AliasBlockFile that references uncompressed data in an existing file.
#include <ODPCMAliasBlockFile.h>
Public Member Functions
ODPCMAliasBlockFile (wxFileName baseFileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel)
Constructs a PCMAliasBlockFile, writing the summary to disk.
ODPCMAliasBlockFile (wxFileName existingFileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, float min, float max, float rms, bool summaryAvailable)
summaryAvailable should be true if the file has been written already.
virtual ~ODPCMAliasBlockFile ()
virtual bool IsSummaryAvailable ()
Returns TRUE if this block's complete summary has been computed and is ready (for OD).
virtual bool IsSummaryBeingComputed ()
Returns TRUE if the summary has not yet been written, but is actively being computed and written to disk.
virtual wxLongLong GetSpaceUsage ()
virtual void GetMinMax (sampleCount start, sampleCount len, float *outMin, float *outMax, float *outRMS)
Gets extreme values for the specified region.
virtual void GetMinMax (float *outMin, float *outMax, float *outRMS)
Gets extreme values for the entire block.
virtual bool Read256 (float *buffer, sampleCount start, sampleCount len)
Returns the 256 byte summary data block.
virtual bool Read64K (float *buffer, sampleCount start, sampleCount len)
Returns the 64K summary data block.
virtual BlockFile * Copy (wxFileName fileName)
Makes new ODPCMAliasBlockFile or PCMAliasBlockFile depending on summary availability.
virtual void SaveXML (XMLWriter &xmlFile)
Saves as xml ODPCMAliasBlockFile or PCMAliasBlockFile depending on summary availability.
virtual void Recover (void)
Writes the summary file if summary data is available.
void DoWriteSummary ()
A public interface to WriteSummary.
void SetStart (sampleCount startSample)
Sets the value that indicates where the first sample in this block corresponds to the global sequence/clip. Only for display use.
sampleCount GetStart ()
Gets the value that indicates where the first sample in this block corresponds to the global sequence/clip. Only for display use.
void Lock ()
Locks the blockfile only if it has a file that exists.
void Unlock ()
Unlocks the blockfile only if it has a file that exists.
void SetClipOffset (sampleCount numSamples)
sets the amount of samples the clip associated with this blockfile is offset in the wavetrack (non effecting)
sampleCount GetClipOffset ()
Gets the number of samples the clip associated with this blockfile is offset by.
virtual int ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len)
Reads the specified data from the aliased file using libsndfile.
virtual bool ReadSummary (void *data)
Read the summary into a buffer.
virtual void SetFileName (wxFileName &name)
sets the file name the summary info will be saved in. threadsafe.
virtual wxFileName GetFileName ()
sets the file name the summary info will be saved in. threadsafe.
virtual void CloseLock ()
virtual void LockRead ()
Prevents a read on other threads.
virtual void UnlockRead ()
Allows reading on other threads.
Static Public Member Functions
static BlockFile * BuildFromXML (DirManager &dm, const wxChar **attrs)
Reconstructs from XML a ODPCMAliasBlockFile and reschedules it for OD loading.
Protected Member Functions
virtual void WriteSummary ()
Write the summary to disk, using the derived ReadData() to get the data.
virtual void * CalcSummary (samplePtr buffer, sampleCount len, sampleFormat format)
Private Member Functions
virtual void Ref ()
virtual bool Deref ()
Private Attributes
char * mFileNameChar
ODLock mWriteSummaryMutex
ODLock mFileNameMutex
ODLock mAliasedFileNameMutex
Also need to protect the aliased file name.
ODLock mReadDataMutex
ODLock mDerefMutex
ODLock mRefMutex
ODLock mSummaryAvailableMutex
bool mSummaryAvailable
bool mSummaryBeingComputed
bool mHasBeenSaved
sampleCount mStart
for reporting after task is complete. Only for display use.
sampleCount mClipOffset
the ODTask needs to know where this blockfile lies in the track, so for convenience, we have this here.
Friends
class DirManager
class ODComputeSummaryTask
class ODDecodeTask
Detailed Description
An AliasBlockFile that references uncompressed data in an existing file.
ODPCMAliasBlockFile is a special type of PCMAliasBlockFile that does not necessarily have summary data available The summary is eventually computed and written to a file in a background thread.
Load On-Demand implementation of the AliasBlockFile for PCM files.
to load large files more quickly, we take skip computing the summary data and put ODPCMAliasBlockFiles in the sequence as place holders. A background thread loads and computes the summary data into these classes. ODPCMAliasBlockFiles are unlike all other BlockFiles are not immutable (for the most part,) because when new summary data is computed for an existing ODPCMAliasBlockFile we save the buffer then and write the Summary File.
All BlockFile methods that treat the summary data as a buffer that exists in its BlockFile are implemented here to behave when the data is not available yet.
Some of these methods have been overridden only because they used the unsafe wxLog calls in the base class.
Constructor & Destructor Documentation
ODPCMAliasBlockFile::ODPCMAliasBlockFile (wxFileName baseFileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel)
Constructs a PCMAliasBlockFile, writing the summary to disk.
References BlockFile::mFileName, mFileNameChar, mHasBeenSaved, mSummaryAvailable, and mSummaryBeingComputed.
Referenced by BuildFromXML(), and Copy().
ODPCMAliasBlockFile::ODPCMAliasBlockFile (wxFileName existingFileName, wxFileName aliasedFile, sampleCount aliasStart, sampleCount aliasLen, int aliasChannel, float min, float max, float rms, bool summaryAvailable)
summaryAvailable should be true if the file has been written already.
References BlockFile::mFileName, mFileNameChar, mHasBeenSaved, mSummaryAvailable, and mSummaryBeingComputed.
ODPCMAliasBlockFile::~ODPCMAliasBlockFile () [virtual]
References mFileNameChar.
Member Function Documentation
BlockFile * ODPCMAliasBlockFile::BuildFromXML (DirManager & dm, const wxChar ** attrs) [static]
Reconstructs from XML a ODPCMAliasBlockFile and reschedules it for OD loading.
Constructs a ODPCMAliasBlockFile from the xml output of WriteXML. Does not schedule the ODPCMAliasBlockFile for OD loading. Client code must do this.
XMLValueChecker::IsGoodFileName(summaryFileName.GetFullName(), summaryFileName.GetPath(wxPATH_GET_VOLUME)) ||
Reimplemented from PCMAliasBlockFile.
References DirManager::AssignFile(), DirManager::GetProjectDataDir(), XMLValueChecker::IsGoodFileName(), XMLValueChecker::IsGoodFileString(), XMLValueChecker::IsGoodInt(), XMLValueChecker::IsGoodPathName(), XMLValueChecker::IsValidChannel(), and ODPCMAliasBlockFile().
Referenced by DirManager::HandleXMLTag().
void * ODPCMAliasBlockFile::CalcSummary (samplePtr buffer, sampleCount len, sampleFormat format) [protected, virtual]
A thread-safe version of CalcSummary. BlockFile::CalcSummary uses a static summary array across the class, which we can't use. Get a buffer containing a summary block describing this sample data. This must be called by derived classes when they are constructed, to allow them to construct their summary data, after which they should write that data to their disk file.
This method also has the side effect of setting the mMin, mMax, and mRMS members of this class.
Unlike BlockFile's implementation You SHOULD delete the returned buffer. this is protected so it shouldn't be hard to deal with - just override all BlockFile methods that use this method.
Parameters:
buffer A buffer containing the sample data to be analyzed
len The length of the sample data
format The format of the sample data.
Reimplemented from BlockFile.
References aheaderTag, aheaderTagLen, CopySamples(), floatSample, SummaryInfo::frames256, SummaryInfo::frames64K, max, min(), BlockFile::mMax, BlockFile::mMin, BlockFile::mRMS, BlockFile::mSummaryInfo, SummaryInfo::offset256, SummaryInfo::offset64K, and SummaryInfo::totalSummaryBytes.
Referenced by WriteSummary().
void ODPCMAliasBlockFile::CloseLock () [virtual]
when the project closes, it locks the blockfiles. Override this in case it needs special treatment
Reimplemented from BlockFile.
References Lock(), and mHasBeenSaved.
BlockFile * ODPCMAliasBlockFile::Copy (wxFileName newFileName) [virtual]
Makes new ODPCMAliasBlockFile or PCMAliasBlockFile depending on summary availability.
If the summary has been computed, Construct a new PCMAliasBlockFile based on this one. otherwise construct an ODPCMAliasBlockFile that still needs to be computed.
Parameters:
newFileName The filename to copy the summary data to.
Reimplemented from PCMAliasBlockFile.
References IsSummaryAvailable(), LockRead(), AliasBlockFile::mAliasChannel, AliasBlockFile::mAliasedFileName, AliasBlockFile::mAliasStart, mHasBeenSaved, BlockFile::mLen, BlockFile::mMax, BlockFile::mMin, BlockFile::mRMS, ODPCMAliasBlockFile(), PCMAliasBlockFile::PCMAliasBlockFile(), and UnlockRead().
bool ODPCMAliasBlockFile::Deref () [private, virtual]
Decreases the reference count of this block by one. If this causes the count to become zero, deletes the associated disk file and deletes this object
Reimplemented from BlockFile.
References mDerefMutex.
Referenced by ODComputeSummaryTask::DoSomeInternal().
void ODPCMAliasBlockFile::DoWriteSummary ()
A public interface to WriteSummary.
Calls write summary, and makes sure it is only done once in a thread-safe fashion.
References IsSummaryAvailable(), mWriteSummaryMutex, and WriteSummary().
Referenced by ODComputeSummaryTask::DoSomeInternal().
sampleCount ODPCMAliasBlockFile::GetClipOffset () [inline]
Gets the number of samples the clip associated with this blockfile is offset by.
References mClipOffset.
wxFileName ODPCMAliasBlockFile::GetFileName () [virtual]
sets the file name the summary info will be saved in. threadsafe.
Reimplemented from BlockFile.
References BlockFile::mFileName, mFileNameMutex, and name.
void ODPCMAliasBlockFile::GetMinMax (float * outMin, float * outMax, float * outRMS) [virtual]
Gets extreme values for the entire block.
Reimplemented from BlockFile.
References GetMinMax(), IsSummaryAvailable(), and JUST_BELOW_MAX_AUDIO.
void ODPCMAliasBlockFile::GetMinMax (sampleCount start, sampleCount len, float * outMin, float * outMax, float * outRMS) [virtual]
Gets extreme values for the specified region.
Reimplemented from BlockFile.
References IsSummaryAvailable(), and JUST_BELOW_MAX_AUDIO.
Referenced by GetMinMax().
wxLongLong ODPCMAliasBlockFile::GetSpaceUsage () [virtual]
Reimplemented from AliasBlockFile.
References IsSummaryAvailable(), BlockFile::mFileName, and mFileNameMutex.
sampleCount ODPCMAliasBlockFile::GetStart () [inline]
Gets the value that indicates where the first sample in this block corresponds to the global sequence/clip. Only for display use.
References mStart.
Referenced by ODComputeSummaryTask::DoSomeInternal().
bool ODPCMAliasBlockFile::IsSummaryAvailable () [virtual]
Returns TRUE if this block's complete summary has been computed and is ready (for OD).
Reimplemented from BlockFile.
References mSummaryAvailable, and mSummaryAvailableMutex.
Referenced by Copy(), DoWriteSummary(), GetMinMax(), GetSpaceUsage(), Lock(), Read256(), Read64K(), Recover(), SaveXML(), and Unlock().
virtual bool ODPCMAliasBlockFile::IsSummaryBeingComputed () [inline, virtual]
Returns TRUE if the summary has not yet been written, but is actively being computed and written to disk.
Reimplemented from BlockFile.
References mSummaryBeingComputed.
void ODPCMAliasBlockFile::Lock () [virtual]
Locks the blockfile only if it has a file that exists.
Locks the blockfile only if it has a file that exists. This needs to be done so that the unsaved ODPCMAliasBlockfiles are deleted upon exit
Reimplemented from BlockFile.
References IsSummaryAvailable(), and mHasBeenSaved.
Referenced by CloseLock().
void ODPCMAliasBlockFile::LockRead () [virtual]
Prevents a read on other threads.
Reimplemented from BlockFile.
References mReadDataMutex.
Referenced by Copy(), ReadData(), and SaveXML().
bool ODPCMAliasBlockFile::Read256 (float * buffer, sampleCount start, sampleCount len) [virtual]
Returns the 256 byte summary data block.
Returns the 256 byte summary data block. Clients should check to see if the summary is available before trying to read it with this call.
Reimplemented from BlockFile.
References IsSummaryAvailable().
bool ODPCMAliasBlockFile::Read64K (float * buffer, sampleCount start, sampleCount len) [virtual]
Returns the 64K summary data block.
Returns the 64K summary data block. Clients should check to see if the summary is available before trying to read it with this call.
Reimplemented from BlockFile.
References IsSummaryAvailable().
int ODPCMAliasBlockFile::ReadData (samplePtr data, sampleFormat format, sampleCount start, sampleCount len) [virtual]
Reads the specified data from the aliased file using libsndfile.
Reads the specified data from the aliased file, using libsndfile, and converts it to the given sample format. Copied from PCMAliasBlockFIle but wxLog calls taken out for thread safety
Parameters:
data The buffer to read the sample data into.
format The format to convert the data into
start The offset within the block to begin reading
len The number of samples to read
Reimplemented from PCMAliasBlockFile.
References CopySamples(), DeleteSamples(), floatSample, int16Sample, ODManager::LockLibSndFileMutex(), LockRead(), AliasBlockFile::mAliasChannel, AliasBlockFile::mAliasedFileName, AliasBlockFile::mAliasStart, AliasBlockFile::mSilentAliasLog, NewSamples(), SAMPLE_SIZE, sf_subtype_more_than_16_bits(), ODManager::UnlockLibSndFileMutex(), and UnlockRead().
Referenced by WriteSummary().
bool ODPCMAliasBlockFile::ReadSummary (void * data) [virtual]
Read the summary into a buffer.
Read the summary of this alias block from disk. Since the audio data is elsewhere, this consists of reading the entire summary file.
Parameters:
*data The buffer where the summary data will be stored. It must be at least mSummaryInfo.totalSummaryBytes long.
Reimplemented from AliasBlockFile.
References BlockFile::FixSummary(), BlockFile::mFileName, mFileNameMutex, BlockFile::mSilentLog, BlockFile::mSummaryInfo, and SummaryInfo::totalSummaryBytes.
void ODPCMAliasBlockFile::Recover (void) [virtual]
Writes the summary file if summary data is available.
Reimplemented from PCMAliasBlockFile.
References IsSummaryAvailable(), and WriteSummary().
void ODPCMAliasBlockFile::Ref () [private, virtual]
Increases the reference count of this block by one. Only DirManager should call this method. This method has been overidden to be threadsafe. It is important especially if two blockfiles deref at the same time resulting in a double deletion of the file
Reimplemented from BlockFile.
References mRefMutex.
void ODPCMAliasBlockFile::SaveXML (XMLWriter & xmlFile) [virtual]
Saves as xml ODPCMAliasBlockFile or PCMAliasBlockFile depending on summary availability.
Writes the xml as a PCMAliasBlockFile if we can (if we have a summary file) Otherwise writes XML as a subset of attributes with 'odpcmaliasblockfile as the start tag. Most notably, the summaryfile attribute refers to a file that does not yet, so when the project file is read back in and this object reconstructed, it needs to avoid trying to open it as well as schedule itself for OD loading
Reimplemented from PCMAliasBlockFile.
References XMLWriter::EndTag(), IsSummaryAvailable(), LockRead(), AliasBlockFile::mAliasChannel, AliasBlockFile::mAliasedFileName, AliasBlockFile::mAliasStart, BlockFile::mFileName, mFileNameMutex, mHasBeenSaved, BlockFile::mLen, XMLWriter::StartTag(), UnlockRead(), and XMLWriter::WriteAttr().
void ODPCMAliasBlockFile::SetClipOffset (sampleCount numSamples) [inline]
sets the amount of samples the clip associated with this blockfile is offset in the wavetrack (non effecting)
References mClipOffset.
void ODPCMAliasBlockFile::SetFileName (wxFileName & name) [virtual]
sets the file name the summary info will be saved in. threadsafe.
Reimplemented from BlockFile.
References BlockFile::mFileName, mFileNameChar, and mFileNameMutex.
void ODPCMAliasBlockFile::SetStart (sampleCount startSample) [inline]
Sets the value that indicates where the first sample in this block corresponds to the global sequence/clip. Only for display use.
References mStart.
void ODPCMAliasBlockFile::Unlock () [virtual]
Unlocks the blockfile only if it has a file that exists.
unlocks the blockfile only if it has a file that exists. This needs to be done so that the unsaved ODPCMAliasBlockfiles are deleted upon exit
Reimplemented from BlockFile.
References BlockFile::IsLocked(), and IsSummaryAvailable().
void ODPCMAliasBlockFile::UnlockRead () [virtual]
Allows reading on other threads.
Reimplemented from BlockFile.
References mReadDataMutex.
Referenced by Copy(), ReadData(), and SaveXML().
void ODPCMAliasBlockFile::WriteSummary () [protected, virtual]
Write the summary to disk, using the derived ReadData() to get the data.
Reimplemented from AliasBlockFile.
References CalcSummary(), DeleteSamples(), floatSample, mFileNameChar, mFileNameMutex, BlockFile::mLen, mSummaryAvailable, mSummaryAvailableMutex, BlockFile::mSummaryInfo, NewSamples(), ReadData(), and SummaryInfo::totalSummaryBytes.
Referenced by DoWriteSummary(), and Recover().
Friends And Related Function Documentation
friend class DirManager [friend]
Reimplemented from BlockFile.
friend class ODComputeSummaryTask [friend]
Reimplemented from BlockFile.
friend class ODDecodeTask [friend]
Reimplemented from BlockFile.
Member Data Documentation
ODLock ODPCMAliasBlockFile::mAliasedFileNameMutex [private]
Also need to protect the aliased file name.
sampleCount ODPCMAliasBlockFile::mClipOffset [private]
the ODTask needs to know where this blockfile lies in the track, so for convenience, we have this here.
Referenced by GetClipOffset(), and SetClipOffset().
ODLock ODPCMAliasBlockFile::mDerefMutex [private]
Referenced by Deref().
char* ODPCMAliasBlockFile::mFileNameChar [private]
Referenced by ODPCMAliasBlockFile(), SetFileName(), WriteSummary(), and ~ODPCMAliasBlockFile().
ODLock ODPCMAliasBlockFile::mFileNameMutex [private]
Referenced by GetFileName(), GetSpaceUsage(), ReadSummary(), SaveXML(), SetFileName(), and WriteSummary().
bool ODPCMAliasBlockFile::mHasBeenSaved [private]
Referenced by CloseLock(), Copy(), Lock(), ODPCMAliasBlockFile(), and SaveXML().
ODLock ODPCMAliasBlockFile::mReadDataMutex [private]
Referenced by LockRead(), and UnlockRead().
ODLock ODPCMAliasBlockFile::mRefMutex [private]
Referenced by Ref().
sampleCount ODPCMAliasBlockFile::mStart [private]
for reporting after task is complete. Only for display use.
Referenced by GetStart(), and SetStart().
bool ODPCMAliasBlockFile::mSummaryAvailable [private]
Referenced by IsSummaryAvailable(), ODPCMAliasBlockFile(), and WriteSummary().
ODLock ODPCMAliasBlockFile::mSummaryAvailableMutex [private]
Referenced by IsSummaryAvailable(), and WriteSummary().
bool ODPCMAliasBlockFile::mSummaryBeingComputed [private]
Referenced by IsSummaryBeingComputed(), and ODPCMAliasBlockFile().
ODLock ODPCMAliasBlockFile::mWriteSummaryMutex [private]
Referenced by DoWriteSummary().
The documentation for this class was generated from the following files:
ODPCMAliasBlockFile.h
ODPCMAliasBlockFile.cpp