Audacity: DeviceToolBar Class Reference
DeviceToolBar Class Reference
A toobar to allow easier changing of input and output devices .
#include <DeviceToolBar.h>
Public Member Functions
DeviceToolBar ()
virtual ~DeviceToolBar ()
void Create (wxWindow *parent)
void RecreateTipWindows ()
void UpdatePrefs ()
virtual void Populate ()
virtual void Repaint (wxDC *dc)
virtual void EnableDisableButtons ()
void OnFocus (wxFocusEvent &event)
void OnCaptureKey (wxCommandEvent &event)
void OnChoice (wxCommandEvent &event)
DECLARE_CLASS (DeviceToolBar)
DECLARE_EVENT_TABLE ()
Private Member Functions
void RegenerateTooltips ()
Private Attributes
wxBitmap * mPlayBitmap
wxBitmap * mRecordBitmap
wxChoice * mInput
wxChoice * mOutput
Detailed Description
A toobar to allow easier changing of input and output devices .
Constructor & Destructor Documentation
DeviceToolBar::DeviceToolBar ()
Methods for DeviceToolBar
DeviceToolBar::~DeviceToolBar () [virtual]
References mPlayBitmap, and mRecordBitmap.
Member Function Documentation
void DeviceToolBar::Create (wxWindow * parent) [virtual]
Reimplemented from ToolBar.
DeviceToolBar::DECLARE_CLASS (DeviceToolBar)
Reimplemented from ToolBar.
DeviceToolBar::DECLARE_EVENT_TABLE ()
Reimplemented from ToolBar.
virtual void DeviceToolBar::EnableDisableButtons () [inline, virtual]
Implements ToolBar.
void DeviceToolBar::OnCaptureKey (wxCommandEvent & event)
References mInput, and mOutput.
void DeviceToolBar::OnChoice (wxCommandEvent & event)
References DeviceName(), gAudioIO, GetActiveProject(), gPrefs, AudioIO::HandleDeviceChange(), mInput, mOutput, name, and AudacityProject::UpdatePrefs().
void DeviceToolBar::OnFocus (wxFocusEvent & event)
Referenced by Populate().
void DeviceToolBar::Populate () [virtual]
Implements ToolBar.
References ToolBar::Add(), ThemeBase::Bitmap(), DeviceName(), mInput, mOutput, mPlayBitmap, mRecordBitmap, name, OnFocus(), theTheme, and UpdatePrefs().
void DeviceToolBar::RecreateTipWindows ()
void DeviceToolBar::RegenerateTooltips () [private]
References mInput, and mOutput.
Referenced by UpdatePrefs().
virtual void DeviceToolBar::Repaint (wxDC * dc) [inline, virtual]
Implements ToolBar.
void DeviceToolBar::UpdatePrefs () [virtual]
Reimplemented from ToolBar.
References gPrefs, mInput, mOutput, RegenerateTooltips(), and ToolBar::SetLabel().
Referenced by Populate().
Member Data Documentation
wxChoice* DeviceToolBar::mInput [private]
Referenced by OnCaptureKey(), OnChoice(), Populate(), RegenerateTooltips(), and UpdatePrefs().
wxChoice* DeviceToolBar::mOutput [private]
Referenced by OnCaptureKey(), OnChoice(), Populate(), RegenerateTooltips(), and UpdatePrefs().
wxBitmap* DeviceToolBar::mPlayBitmap [private]
Referenced by Populate(), and ~DeviceToolBar().
wxBitmap* DeviceToolBar::mRecordBitmap [private]
Referenced by Populate(), and ~DeviceToolBar().
The documentation for this class was generated from the following files:
DeviceToolBar.h
DeviceToolBar.cpp