Audacity: EffectReverse Class Reference
EffectReverse Class Reference
An Effect that reverses the selected audio.
#include <Reverse.h>
Public Member Functions
EffectReverse ()
virtual wxString GetEffectName ()
virtual std::set< wxString > GetEffectCategories ()
virtual wxString GetEffectIdentifier ()
virtual wxString GetEffectAction ()
virtual bool Process ()
Private Member Functions
bool ProcessOneClip (int count, WaveTrack *track, sampleCount start, sampleCount len, sampleCount originalStart, sampleCount originalEnd)
bool ProcessOneWave (int count, WaveTrack *track, sampleCount start, sampleCount len)
Detailed Description
An Effect that reverses the selected audio.
Constructor & Destructor Documentation
EffectReverse::EffectReverse ()
Member Function Documentation
virtual wxString EffectReverse::GetEffectAction () [inline, virtual]
Implements Effect.
virtual std::set<wxString> EffectReverse::GetEffectCategories () [inline, virtual]
virtual wxString EffectReverse::GetEffectIdentifier () [inline, virtual]
Reimplemented from Effect.
virtual wxString EffectReverse::GetEffectName () [inline, virtual]
Implements Effect.
bool EffectReverse::Process () [virtual]
Implements Effect.
References Track::All, LabelTrack::ChangeLabelsOnReverse(), Effect::CopyInputTracks(), TrackListIterator::First(), Track::GetKind(), Track::GetSelected(), Track::IsSynchroSelected(), Track::Label, Effect::mOutputTracks, Effect::mT0, Effect::mT1, TrackListIterator::Next(), ProcessOneWave(), Effect::ReplaceProcessedTracks(), WaveTrack::TimeToLongSamples(), and Track::Wave.
bool EffectReverse::ProcessOneClip (int count, WaveTrack * track, sampleCount start, sampleCount len, sampleCount originalStart, sampleCount originalEnd) [private]
References floatSample, WaveTrack::Get(), WaveTrack::GetBestBlockSize(), WaveTrack::GetMaxBlockSize(), WaveTrack::Set(), and Effect::TrackProgress().
Referenced by ProcessOneWave().
bool EffectReverse::ProcessOneWave (int count, WaveTrack * track, sampleCount start, sampleCount len) [private]
References WaveTrack::AddClip(), WaveClip::Append(), WaveTrack::FillSortedClipArray(), WaveTrack::GetClipIterator(), WaveClip::GetEndSample(), WaveClip::GetStartSample(), WaveTrack::LongSamplesToTime(), ProcessOneClip(), WaveTrack::RemoveAndReturnClip(), WaveClip::SetOffset(), WaveTrack::SplitAt(), and WaveTrack::TimeToLongSamples().
Referenced by Process().
The documentation for this class was generated from the following files:
Reverse.h
Reverse.cpp