Audacity: _LADSPA_Descriptor Class Reference
_LADSPA_Descriptor Class Reference
_LADSPA_Descriptor is a structure that provides the API to a LADSPA (Linux Audio Plugin Architecture) Effect.
#include <ladspa.h>
Public Attributes
unsigned long UniqueID
const char * Label
LADSPA_Properties Properties
const char * Name
const char * Maker
const char * Copyright
unsigned long PortCount
const LADSPA_PortDescriptor * PortDescriptors
const char *const * PortNames
const LADSPA_PortRangeHint * PortRangeHints
void * ImplementationData
LADSPA_Handle(* instantiate)(const struct _LADSPA_Descriptor *Descriptor, unsigned long SampleRate)
void(* connect_port)(LADSPA_Handle Instance, unsigned long Port, LADSPA_Data *DataLocation)
void(* activate)(LADSPA_Handle Instance)
void(* run)(LADSPA_Handle Instance, unsigned long SampleCount)
void(* run_adding)(LADSPA_Handle Instance, unsigned long SampleCount)
void(* set_run_adding_gain)(LADSPA_Handle Instance, LADSPA_Data Gain)
void(* deactivate)(LADSPA_Handle Instance)
void(* cleanup)(LADSPA_Handle Instance)
Detailed Description
_LADSPA_Descriptor is a structure that provides the API to a LADSPA (Linux Audio Plugin Architecture) Effect.
It specifies how many parameters there are and the callback to run the effect, amongst other properties.
Member Data Documentation
void(* _LADSPA_Descriptor::activate)(LADSPA_Handle Instance)
Referenced by LadspaEffect::ProcessStereo().
void(* _LADSPA_Descriptor::cleanup)(LADSPA_Handle Instance)
Referenced by LadspaEffect::ProcessStereo().
void(* _LADSPA_Descriptor::connect_port)(LADSPA_Handle Instance, unsigned long Port, LADSPA_Data *DataLocation)
Referenced by LadspaEffect::ProcessStereo().
const char* _LADSPA_Descriptor::Copyright
void(* _LADSPA_Descriptor::deactivate)(LADSPA_Handle Instance)
Referenced by LadspaEffect::ProcessStereo().
void* _LADSPA_Descriptor::ImplementationData
LADSPA_Handle(* _LADSPA_Descriptor::instantiate)(const struct _LADSPA_Descriptor *Descriptor, unsigned long SampleRate)
Referenced by LadspaEffect::ProcessStereo().
const char* _LADSPA_Descriptor::Label
Referenced by LoadLadspaEffect().
const char* _LADSPA_Descriptor::Maker
const char* _LADSPA_Descriptor::Name
Referenced by LadspaEffect::LadspaEffect().
unsigned long _LADSPA_Descriptor::PortCount
Referenced by LadspaEffect::LadspaEffect(), and LadspaEffect::ProcessStereo().
const LADSPA_PortDescriptor* _LADSPA_Descriptor::PortDescriptors
Referenced by LadspaEffect::LadspaEffect(), and LadspaEffect::ProcessStereo().
const char* const* _LADSPA_Descriptor::PortNames
const LADSPA_PortRangeHint* _LADSPA_Descriptor::PortRangeHints
Referenced by LadspaEffectDialog::HandleText(), LadspaEffect::LadspaEffect(), and LadspaEffectDialog::OnSlider().
LADSPA_Properties _LADSPA_Descriptor::Properties
void(* _LADSPA_Descriptor::run)(LADSPA_Handle Instance, unsigned long SampleCount)
Referenced by LadspaEffect::ProcessStereo().
void(* _LADSPA_Descriptor::run_adding)(LADSPA_Handle Instance, unsigned long SampleCount)
void(* _LADSPA_Descriptor::set_run_adding_gain)(LADSPA_Handle Instance, LADSPA_Data Gain)
unsigned long _LADSPA_Descriptor::UniqueID
Referenced by LoadLadspaEffect().
The documentation for this class was generated from the following file:
ladspa.h